### ISSUE TITLE
Add Client-ID Ban? (Suggestion)

### ISSUE THREAD

**Issue by Akuroma** [pmmp/PocketMine-MP#1004]
### Issue description
Maybe it would be great to have CID-Bans in pmmp.

### Steps to reproduce the issue

1. Add commands (bancid and pardoncid)

### OS and versions

* PocketMine-MP: PocketMine-MP 1.6.2dev
* PHP: 
* Server OS: Linux (Ubuntu 14.04)
* Game version: PE/Win10 (delete as appropriate)

### Crashdump, backtrace or other files

* ...

**Comment by SOF3** [comment]
This should be implemented with a plugin.

After all, the PocketMine ban API is very inflexible, e.g. difficult for plugin synchronization, etc. A plugin that handles all the ban-related stuff would be better than implementing it in the core anyway.
