### ISSUE TITLE
Servers extremely slow / player movement 

### ISSUE THREAD

**Issue by Lazerplayz** [pmmp/PocketMine-MP#1006]
### Issue description

 Okay so basically when there are 50-60 players on thr server you start experiencing player movment issues, when you have 90-100 players on your server is slow it takes 1-2 seconds for the player to move or the popup to change

### Steps to reproduce the issue

1. ^ look into desc
2. ...

### OS and versions

* PocketMine-MP:
* PHP:
* Server OS:
* Game version: PE/Win10 (delete as appropriate)

### Crashdump, backtrace or other files

* ...

**Comment by dktapps** [comment]
Without knowing your PocketMine-MP version, OS, PHP, Client version, or plugins and how the issue occurred, the issue cannot begin to be solved.
A pre-formatted template is provided that shows the required information to begin to find, test and solve an issue.
Until the adequate template and information is provided, the issue will be closed; it may be reopened if you update the ticket with the correct template and required information.

[Contribution guidelines](https://github.com/pmmp/PocketMine-MP/blob/master/CONTRIBUTING.md)

**Comment by Lazerplayz** [comment]
@dktapps how about now?
