### ISSUE TITLE
Hunger

### ISSUE THREAD

**Issue by Akuroma** [pmmp/PocketMine-MP#1011]
### Issue description

The hunger of players degenerates very fast. Is it possible that this is going to be slowed down a little bit?

### OS and versions

* PocketMine-MP:  PocketMine-MP 1.6.2dev 「Unleashed」
* PHP:
* Server OS: Linux (Ubuntu 14.04)
* Game version: PE/Win10 (delete as appropriate)

### Crashdump, backtrace or other files

* ...

**Comment by dktapps** [comment]
It's supposed to simulate vanilla MCPE, and does.

**Comment by Matthww** [comment]
In a fresh with no plugins or anything edited PMMP server. It takes 10 seconds to lose 0.5 food
But on a singeplayer world also flat it takes about 1 minute to lose 0.5 food

I was jumping + running

**Comment by dktapps** [comment]
Yes, I just tested it locally. I think the saturation attribute default is incorrect.
