### ISSUE TITLE
Trying to use /enchant with a non-existent or non-implemented enchantment causes Protection to be applied instead

### ISSUE THREAD

**Issue by akaSnapy** [pmmp/PocketMine-MP#1012]
### Issue description
Every enchant u try to add to a item it puts Protection instead.

### Steps to reproduce the issue
Get an item, (A sword) try to do /enchant name sharpness(id 9) 1

### OS and versions
* PocketMine-MP:Latest(Branch Master)
* PHP:7.0.19
* Server OS:Linux Ubuntu
* Game version: PE/Win10 (delete as appropriate):PE

**Comment by Muqsit** [comment]
This is because only 3 enchants are currently registered in Enchantment::init().
#close

**Comment by akaSnapy** [comment]
Then it needs a fix..

**Comment by TheDiamondYT1** [comment]
@akaSnapy It is **not** a bug. Its not just implemented yet.

**Comment by dktapps** [comment]
Technically speaking it is a bug, it's unexpected behaviour. It should tell you the enchantment doesn't exist, not apply a completely different enchantment. This bug is fixed on the `api3/blocks` branch.

**Comment by akaSnapy** [comment]
It may be fixed, but i can't git clone that branch, smh.

**Comment by Qimie** [comment]
Im laughing hard rn bc Everyone said it was not a bug and then Dylan comes
and say its a bug. Lol XD

**Comment by TheDiamondYT1** [comment]
@Qimie It's not a bug in `api3/blocks`, however **it is** a bug in `master`.  This makes us all correct.

##### Okay, that's enough useless comments 😂

**Comment by brianzp** [comment]
So when is this going to be implemented/fixed in the master branch?

**Comment by ImagicalGamer** [comment]
@brianzp whenever `api3/blocks` is merged into the master branch.

**Comment by MichaelM04** [comment]
@akaSnapy Linux: "git clone https://github.com/pmmp/PocketMine-MP.git --branch api3/blocks --recursive"

**Comment by brianzp** [comment]
Are multiple enchantments the same issue? And are they fixed on api3/blocks

**Comment by optimusprime338** [comment]
enchants are messed up! at least it was working with advanced kits not that not too!

**Comment by Muqsit** [comment]
@optimusprime338 That issue was already fixed almost 2w ago: https://github.com/pmmp/PocketMine-MP/commit/fb59b57bdfc4b1b04e079bf4e3d8ec48385a38e5

**Comment by optimusprime338** [comment]
It still not working .. only <3 IDs working

**Comment by dktapps** [comment]
i.e. the enchantments that were registered... which is how it should have behaved from the start. Do read the title.

**Comment by optimusprime338** [comment]
Thanks!
