### ISSUE TITLE
Potion doesn't effect.

### ISSUE THREAD

**Issue by ParkChanSol** [pmmp/PocketMine-MP#1014]
### Issue description

Player drink potion, but potion effect doesn't appear.

### Steps to reproduce the issue

Get a potion. drink potion (potion is speed.. etc)

### OS and versions

* PocketMine-MP:29e88d8
* PHP:7.0.1
* Server OS: Windows 10
* Game version: PE/Win10 (delete as appropriate): PE

**Comment by dktapps** [comment]
Potions are not yet implemented on primary branches.

**Comment by ParkChanSol** [comment]
@dktapps Where branch appear potion effect?

**Comment by dktapps** [comment]
You can use `api3/blocks` if you want to test bleeding-edge.

**Comment by ParkChanSol** [comment]
@dktapps Thx
