### ISSUE TITLE
PlayerHungerChangeEvent?

### ISSUE THREAD

**Issue by Pizzahaet** [pmmp/PocketMine-MP#1016]
I would like for PlayerHunerChangeEvent to be added because I have this plugin called no hunger in world and it uses this to work

**Comment by ParkChanSol** [comment]
If you want to stop player's hunger. use PlayerExhaustEvent

**Comment by SOF3** [comment]
PlayerExhaustEvent is the actual action that causes decrease in hunger.
If you otherwise simply want to monitor the change in food value, use a repeating task instead. Creating an event for every minor change like this is too verbose.
