### ISSUE TITLE
Strange Black Shadow on World

### ISSUE THREAD

**Issue by ChaostixZix** [pmmp/PocketMine-MP#1017]
* PocketMine-MP:1.6.2dev Unleashed API 3.0.0-ALPHA5
* PHP:7.0.3
* Server OS:Ubuntu 
* Game version:Win10 (delete as appropriate)

I dont know what's the error, but everytime i logged in to server, there is a black shadow.
i've tried to relogin. but, its not fixed
![screenshot at jun 05 21-11-08](https://cloud.githubusercontent.com/assets/19998246/26813521/ab9db18a-4a33-11e7-9209-fbcf254be68a.png)

Also. When you try to teleport to other world, the last world chunk still exist
![screenshot at jun 05 21-14-00](https://cloud.githubusercontent.com/assets/19998246/26813557/e8db67cc-4a33-11e7-9f18-e0042ba8b1c5.png)

**Comment by Driesboy** [comment]
#970 search before open a issue

**Comment by Misteboss** [comment]
You can fix it by modifying Level.php on line 2654, you need to replace 
        `if(!$chunk->isLightPopulated() and $chunk->isPopulated() and $this->getServer()>getProperty("chunk-ticking.light-updates", false)){` by deleting this condition.
Then restart your server join your world /save-all and re add the condition

**Comment by Misteboss** [comment]
@jasonwynn10 Yep this the objective.. you just need to do it one time and your world will be fixed.. can you stop think i'm stupid

**Comment by Qimie** [comment]
But this still happens in CosmicPE... Lol
