### ISSUE TITLE
logged out due to Login timeout

### ISSUE THREAD

**Issue by ValgeYT** [pmmp/PocketMine-MP#1019]
I have minecraft v1.1.0 , disconnecting from server with " logged out due to Login timeout"  in console
![t9fe2pffcvk](https://cloud.githubusercontent.com/assets/16214087/26822212/f53caa02-4ab1-11e7-9c2a-acfd5207e97c.jpg)

**Comment by dktapps** [comment]
Without knowing your PocketMine-MP version, OS, PHP, Client version, or plugins and how the issue occurred, the issue cannot begin to be solved.
A pre-formatted template is provided that shows the required information to begin to find, test and solve an issue.
Until the adequate template and information is provided, the issue will be closed; it may be reopened if you update the ticket with the correct template and required information.

[Contribution guidelines](https://github.com/pmmp/PocketMine-MP/blob/master/CONTRIBUTING.md)
