### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by SerezhaIvanov** [pmmp/PocketMine-MP#1020]
### Issue description
Plugin don't work

### OS and versions

* PocketMine-MP: 1.6.2dev
* PHP: 3.0.0-ALPHA 5
* Server OS: Ubuntu
* Game version: PE

### Crashdump, backtrace or other files
Fatal error: Class images\MapInfoRequestPacket contains 1 abstract method and must therefore be declared abstract or implement the r
maining methods (pocketmine\network\mcpe\protocol\DataPacket::handle) in /home/srv1/plugins/images/src/images/MapInfoRequestPacket.p
p on line 22
* ...

**Comment by SerezhaIvanov** [comment]
Help

**Comment by SOF3** [comment]
If your issue is related to a plugin, **do not report here, contact the plugin's original author** instead.

**Comment by dktapps** [comment]
Please review the contribution guidelines before opening an issue.

[Contribution guidelines](https://github.com/pmmp/PocketMine-MP/blob/master/CONTRIBUTING.md)
