### ISSUE TITLE
The BossEventPacket is missing 4 breaks

### ISSUE THREAD

**Issue by intagaming** [pmmp/PocketMine-MP#1021]
### Issue description

src\pocketmine\network\mcpe\protocol\BossEventPacket.php
As title, in the decode() and encode(). This causes TYPE_SHOW to run as 3 types including itself.

### Steps to reproduce the issue

1. Open file
2. Navigate to the function decode() and encode(), 

### OS and versions

* PocketMine-MP: 29e88d8
* PHP: 7.0
* Server OS: Any
* Game version: PE/Win10

### Crashdump, backtrace or other files

* ...

**Comment by intagaming** [comment]
Works as intended only if you have provided the unknownShort for it. So if I only want to show it why do I need to do the UNKNOWN_6 or the custom "TEXTURE" ?

**Comment by dktapps** [comment]
It is written like that by design. You understand how a case statement works, yes?

**Comment by intagaming** [comment]
That's confusing without an documentation. The default value is not there to be created with the boss bar. I can't seem to find anywhere the API instruction for an appropriate way to initialize a BossEventPacket, without posting a forum topic.

**Comment by TheDiamondYT1** [comment]
@intagaming Post a forum topic...thats what the forum is for.

https://forums.pmmp.io
