### ISSUE TITLE
Can't break blocks

### ISSUE THREAD

**Issue by SerezhaIvanov** [pmmp/PocketMine-MP#1022]
### Issue description
I can't break block in world.

### Steps to reproduce the issue
Place block and break.

### OS and versions

* PocketMine-MP: 1.6.2dev
* PHP: 7
* Server OS: Ubuntu
* Game version: PE

### Crashdump, backtrace or other files
No errors
* ...

**Comment by dktapps** [comment]
Without knowing your PocketMine-MP version, OS, PHP, Client version, or plugins and how the issue occurred, the issue cannot begin to be solved.
A pre-formatted template is provided that shows the required information to begin to find, test and solve an issue.
Until the adequate template and information is provided, the issue will be closed; it may be reopened if you update the ticket with the correct template and required information.

[Contribution guidelines](https://github.com/pmmp/PocketMine-MP/blob/master/CONTRIBUTING.md)

**Comment by Qimie** [comment]
People are stupid these days. Like Linux

**Comment by dktapps** [comment]
@Qimie would you mind at least behaving semi-professionally on our issue tracker? This is a place for issue tracking, not for stirring up fights.
