### ISSUE TITLE
Error when you're sending  a PlayerPacket ?

### ISSUE THREAD

**Issue by Misteboss** [pmmp/PocketMine-MP#1027]
### Issue description

1. Send a PlayerPacket
2. Check the console

### OS and versions

* PocketMine-MP: Latest commit of api3\branch
* PHP: 7.0.2
* Server OS: Debian
* Game version: PE/Win10 1.1.0.55

### Crashdump, backtrace or other files

* ...
![capture d ecran 2017-06-07 a 13 17 44](https://user-images.githubusercontent.com/17687222/26875992-88461b44-4b84-11e7-93a9-580ddbfe8e6d.png)
![capture d ecran 2017-06-07 a 13 18 35](https://user-images.githubusercontent.com/17687222/26875993-886eeb8c-4b84-11e7-8249-8ae3dc4d2cac.png)

**Comment by dktapps** [comment]
Please use the [forums](https://forums.pmmp.io) for plugin development help.

**Comment by Misteboss** [comment]
Check the console it's a binary stream error, and i am sending packets you can just do it using plugins

**Comment by dktapps** [comment]
No, the BinaryStream error is telling you _you_ have done something wrong. This issue does not occur without plugins, therefore it is something your code is doing wrong.

Also, for what it's worth, the `eid` field in AddPlayerPacket no longer exists.

**Comment by JackNoordhuis** [comment]
@Misteboss The error is triggered by your plugin not using the server's API properly, this is not caused by the server and no one else us to blame but you.

**Comment by Misteboss** [comment]
@dktapps Sorry i didn't see they have changed.. but this error didn't tell me how to fix it and i didn't see any API change (3.0.0-APLHA6)

**Comment by dktapps** [comment]
The strict type rules only affect your code if your code was previously causing undefined behaviour. Current branches are heavily in development and a new release is a way off the horizon yet.

**Comment by JackNoordhuis** [comment]
Ask for help on the [forums](//forums.pmmp.io/).

**Comment by dktapps** [comment]
also, I'm not surprised it doesn't tell you how to fix it... you don't have debug output enabled, how do you expect to be able to debug the issue?

**Comment by Misteboss** [comment]
I forgot username field too this the the cause of the error x)
