### ISSUE TITLE
Constant server crash - API3/Blocks

### ISSUE THREAD

**Issue by kabluinc** [pmmp/PocketMine-MP#1030]
### Issue description

I tried the API3/blocks branch today however for the last 5 hours I'm getting these crashes. Sorry if its against the rules to open issues of branches that aren't master.

### Steps to reproduce the issue

Happens randomly. Almost every 15 mins

### OS and versions

* PocketMine-MP: 1.6.2 dev API3/blocks branch 10803d91d05114f50b6a49203f363dff55dcfa0e
* PHP: 7.0.14
* Server OS: Windows 10
* Game version: PE 1.1.0.55

### Crashdump, backtrace or other files
`PocketMine-MP Crash Dump Wed Jun 7 18:47:08 BST 2017

Error: __clone method called on non-object
File: /src/pocketmine/item/Item
Line: 294
Type: notice

Code:
[285] * @param CompoundTag|string $tags
[286] *
[287] * @return Item
[288] */
[289] public static function get(int $id, int $meta = 0, int $count = 1, $tags = "") : Item{
[290] try{
[291] $class = self::$list[$id][$meta] ?? self::$list[$id][0] ?? null;
[292] if($class !== null){
[293] /** @var Item $item */
[294] $item = clone $class;
[295] $item->setDamage($meta);
[296] $item->setCount($count);
[297] $item->setCompoundTag($tags);
[298] 
[299] return $item;
[300] }else{
[301] return (new Item($id, $meta, $count))->setCompoundTag($tags);
[302] }
[303] }catch(\RuntimeException $e){
[304] return (new Item($id, $meta, $count))->setCompoundTag($tags);

Backtrace:
#0 /src/pocketmine/item/Item(1147): pocketmine\item\Item::get(integer 444, integer 0, integer 1)
#1 /src/pocketmine/tile/Chest(116): pocketmine\item\Item::nbtDeserialize(pocketmine\nbt\tag\CompoundTag pocketmine\nbt\tag\CompoundTag{.pocketmine\nbt\tag\ShortTag:444.pocketmine\nbt\tag\ByteTag:1.pocketmine\nbt\tag\ShortTag:0.pocketmine\nbt\tag\ByteTag:2.})
#2 /src/pocketmine/tile/Chest(53): pocketmine\tile\Chest->getItem(integer 2)
#3 /src/pocketmine/tile/Tile(90): pocketmine\tile\Chest->__construct(pocketmine\level\Level object, pocketmine\nbt\tag\CompoundTag pocketmine\nbt\tag\CompoundTag{.pocketmine\nbt\tag\ListTag:pocketmine\nbt\tag\ListTag{.pocketmine\nbt\tag\CompoundTag:pocketmine\nbt\tag\CompoundTag{.pocketmine\nbt\tag\ShortTag:340.pocketmine\nbt\tag\ByteTag:2.pocketmine\nbt\tag\ShortTag:0.pocketmine\nbt\tag\ByteTag:0.}.pocketmine\nbt\tag\CompoundTag:pocketmine\nbt\tag\CompoundTag{.pocketmine\nbt\tag\ShortTag:5.pocketmine\nbt\tag\ByteTag:64.pocketmine\nbt\tag\ShortTag:1.pocketmine\nbt\tag\ByteTag:1.}.pocketmine\nbt\tag\CompoundTag:pocketmine\nbt\tag\CompoundTag{.pocketmine\nbt\tag\ShortTag:444.pocketmine\nbt\tag\ByteTag:1.pocketmine\nbt\tag\ShortTag:0.pocketmine\nbt\tag\ByteTag:2.}.pocketmine\nbt\tag\CompoundTag:pocketmine\nbt\tag\CompoundTag{.pocketmine\nbt\tag\ShortTag:155.pocketmine\nbt\tag\ByteTag:64.pocketmine\nbt\tag\ShortTag:0.pocketmine\nbt\tag\ByteTag:3.}.pocketmine\nbt\tag\CompoundTag:pocketmine\nbt\tag\CompoundTag{.pocketmine\nbt\tag\ShortTag:155.pocketmine\nbt\tag\ByteTag:64.pocketmine\nbt\tag\ShortTag:0.pocketmine\nbt\tag\ByteTag:4.}.pocketmine\nbt\tag\CompoundTag:pocketmine\nbt\tag\CompoundTag{.pocketmine\nbt\tag\ShortTag:155.pocketmine\nbt\tag\ByteTag:64.pocketmine\nbt\tag\ShortTag:0.pocketmine\nbt\tag\ByteTag:5.}.pocketmine\nbt\tag\CompoundTag:pocketmine\nbt\tag\CompoundTag{.pocketmine\nbt\tag\ShortTag:53.pocketmine\nbt\tag\ByteTag:64.pocketmine\nbt\tag\ShortTag:0.pocketmine\nbt\tag\ByteTag:6.}.pocketmine\nbt\tag\CompoundTag:pocketmine\nbt\tag\CompoundTag{.pocketmine\nbt\tag\ShortTag:53.pocketmine\nbt\tag\ByteTag:64.pocketmine\nbt\tag\ShortTag:0.pocketmine\nbt\tag\ByteTag:7.}.pocketmine\nbt\tag\CompoundTag:pocketmine\nbt\tag\CompoundTag{.pocketmine\nbt\tag\ShortTag:53.pocketmine\nbt\tag\ByteTag:64.pocketmine\nbt\tag\ShortTag:0.pocketmine\nbt\tag\ByteTag:8.}.pocketmine\nbt\tag\CompoundTag:pocketmine\nbt\tag\CompoundTag{.pocketmine\nbt\tag\ShortTag:330.pocketmine\nbt\tag\ByteTag:64.pocketmine\nbt\tag\ShortTag:0.pocketmine\nbt\tag\ByteTag:9.}.pocketmine\nbt\tag\CompoundTag:pocketmine\nbt\tag\CompoundTag{.pocketmine\nbt\tag\ShortTag:53.pocketmine\nbt\tag\ByteTag:64.pocketmine\nbt\tag\ShortTag:0.pocketmine\nbt\tag\ByteTag:10.}.pocketmine\nbt\tag\CompoundTag:pocketmine\nbt\tag\CompoundTag{.pocketmine\nbt\tag\ShortTag:53.pocketmine\nbt\tag\ByteTag:64.pocketmine\nbt\tag\ShortTag:0.pocketmine\nbt\tag\ByteTag:11.}.pocketmine\nbt\tag\CompoundTag:pocketmine\nbt\tag\CompoundTag{.pocketmine\nbt\tag\ShortTag:155.pocketmine\nbt\tag\ByteTag:1.pocketmine\nbt\tag\ShortTag:0.pocketmine\nbt\tag\ByteTag:12.}.pocketmine\nbt\tag\CompoundTag:pocketmine\nbt\tag\CompoundTag{.pocketmine\nbt\tag\ShortTag:53.pocketmine\nbt\tag\ByteTag:62.pocketmine\nbt\tag\ShortTag:0.pocketmine\nbt\tag\ByteTag:13.}.pocketmine\nbt\tag\CompoundTag:pocketmine\nbt\tag\CompoundTag{.pocketmine\nbt\tag\ShortTag:330.pocketmine\nbt\tag\ByteTag:2.pocketmine\nbt\tag\ShortTag:0.pocketmine\nbt\tag\ByteTag:14.}.pocketmine\nbt\tag\CompoundTag:pocketmine\nbt\tag\CompoundTag{.pocketmine\nbt\tag\ShortTag:50.pocketmine\nbt\tag\ByteTag:64.pocketmine\nbt\tag\ShortTag:0.pocketmine\nbt\tag\ByteTag:15.}.pocketmine\nbt\tag\CompoundTag:pocketmine\nbt\tag\CompoundTag{.pocketmine\nbt\tag\ShortTag:280.pocketmine\nbt\tag\ByteTag:5.pocketmine\nbt\tag\ShortTag:0.pocketmine\nbt\tag\ByteTag:16.}.}.pocketmine\nbt\tag\StringTag:Chest.pocketmine\nbt\tag\IntTag:531.pocketmine\nbt\tag\IntTag:6.pocketmine\nbt\tag\IntTag:-614.})
#4 /src/pocketmine/level/format/Chunk(740): pocketmine\tile\Tile::createTile(string Chest, pocketmine\level\Level object, pocketmine\nbt\tag\CompoundTag pocketmine\nbt\tag\CompoundTag{.pocketmine\nbt\tag\ListTag:pocketmine\nbt\tag\ListTag{.pocketmine\nbt\tag\CompoundTag:pocketmine\nbt\tag\CompoundTag{.pocketmine\nbt\tag\ShortTag:340.pocketmine\nbt\tag\ByteTag:2.pocketmine\nbt\tag\ShortTag:0.pocketmine\nbt\tag\ByteTag:0.}.pocketmine\nbt\tag\CompoundTag:pocketmine\nbt\tag\CompoundTag{.pocketmine\nbt\tag\ShortTag:5.pocketmine\nbt\tag\ByteTag:64.pocketmine\nbt\tag\ShortTag:1.pocketmine\nbt\tag\ByteTag:1.}.pocketmine\nbt\tag\CompoundTag:pocketmine\nbt\tag\CompoundTag{.pocketmine\nbt\tag\ShortTag:444.pocketmine\nbt\tag\ByteTag:1.pocketmine\nbt\tag\ShortTag:0.pocketmine\nbt\tag\ByteTag:2.}.pocketmine\nbt\tag\CompoundTag:pocketmine\nbt\tag\CompoundTag{.pocketmine\nbt\tag\ShortTag:155.pocketmine\nbt\tag\ByteTag:64.pocketmine\nbt\tag\ShortTag:0.pocketmine\nbt\tag\ByteTag:3.}.pocketmine\nbt\tag\CompoundTag:pocketmine\nbt\tag\CompoundTag{.pocketmine\nbt\tag\ShortTag:155.pocketmine\nbt\tag\ByteTag:64.pocketmine\nbt\tag\ShortTag:0.pocketmine\nbt\tag\ByteTag:4.}.pocketmine\nbt\tag\CompoundTag:pocketmine\nbt\tag\CompoundTag{.pocketmine\nbt\tag\ShortTag:155.pocketmine\nbt\tag\ByteTag:64.pocketmine\nbt\tag\ShortTag:0.pocketmine\nbt\tag\ByteTag:5.}.pocketmine\nbt\tag\CompoundTag:pocketmine\nbt\tag\CompoundTag{.pocketmine\nbt\tag\ShortTag:53.pocketmine\nbt\tag\ByteTag:64.pocketmine\nbt\tag\ShortTag:0.pocketmine\nbt\tag\ByteTag:6.}.pocketmine\nbt\tag\CompoundTag:pocketmine\nbt\tag\CompoundTag{.pocketmine\nbt\tag\ShortTag:53.pocketmine\nbt\tag\ByteTag:64.pocketmine\nbt\tag\ShortTag:0.pocketmine\nbt\tag\ByteTag:7.}.pocketmine\nbt\tag\CompoundTag:pocketmine\nbt\tag\CompoundTag{.pocketmine\nbt\tag\ShortTag:53.pocketmine\nbt\tag\ByteTag:64.pocketmine\nbt\tag\ShortTag:0.pocketmine\nbt\tag\ByteTag:8.}.pocketmine\nbt\tag\CompoundTag:pocketmine\nbt\tag\CompoundTag{.pocketmine\nbt\tag\ShortTag:330.pocketmine\nbt\tag\ByteTag:64.pocketmine\nbt\tag\ShortTag:0.pocketmine\nbt\tag\ByteTag:9.}.pocketmine\nbt\tag\CompoundTag:pocketmine\nbt\tag\CompoundTag{.pocketmine\nbt\tag\ShortTag:53.pocketmine\nbt\tag\ByteTag:64.pocketmine\nbt\tag\ShortTag:0.pocketmine\nbt\tag\ByteTag:10.}.pocketmine\nbt\tag\CompoundTag:pocketmine\nbt\tag\CompoundTag{.pocketmine\nbt\tag\ShortTag:53.pocketmine\nbt\tag\ByteTag:64.pocketmine\nbt\tag\ShortTag:0.pocketmine\nbt\tag\ByteTag:11.}.pocketmine\nbt\tag\CompoundTag:pocketmine\nbt\tag\CompoundTag{.pocketmine\nbt\tag\ShortTag:155.pocketmine\nbt\tag\ByteTag:1.pocketmine\nbt\tag\ShortTag:0.pocketmine\nbt\tag\ByteTag:12.}.pocketmine\nbt\tag\CompoundTag:pocketmine\nbt\tag\CompoundTag{.pocketmine\nbt\tag\ShortTag:53.pocketmine\nbt\tag\ByteTag:62.pocketmine\nbt\tag\ShortTag:0.pocketmine\nbt\tag\ByteTag:13.}.pocketmine\nbt\tag\CompoundTag:pocketmine\nbt\tag\CompoundTag{.pocketmine\nbt\tag\ShortTag:330.pocketmine\nbt\tag\ByteTag:2.pocketmine\nbt\tag\ShortTag:0.pocketmine\nbt\tag\ByteTag:14.}.pocketmine\nbt\tag\CompoundTag:pocketmine\nbt\tag\CompoundTag{.pocketmine\nbt\tag\ShortTag:50.pocketmine\nbt\tag\ByteTag:64.pocketmine\nbt\tag\ShortTag:0.pocketmine\nbt\tag\ByteTag:15.}.pocketmine\nbt\tag\CompoundTag:pocketmine\nbt\tag\CompoundTag{.pocketmine\nbt\tag\ShortTag:280.pocketmine\nbt\tag\ByteTag:5.pocketmine\nbt\tag\ShortTag:0.pocketmine\nbt\tag\ByteTag:16.}.}.pocketmine\nbt\tag\StringTag:Chest.pocketmine\nbt\tag\IntTag:531.pocketmine\nbt\tag\IntTag:6.pocketmine\nbt\tag\IntTag:-614.})
#5 /src/pocketmine/level/Level(2533): pocketmine\level\format\Chunk->initChunk(pocketmine\level\Level object)
#6 /src/pocketmine/level/Level(2185): pocketmine\level\Level->loadChunk(integer 33, integer -39, boolean 1)
#7 /src/pocketmine/level/Level(2779): pocketmine\level\Level->getChunk(integer 33, integer -39, boolean 1)
#8 /src/pocketmine/Player(860): pocketmine\level\Level->populateChunk(integer 33, integer -39)
#9 /src/pocketmine/Player(1759): pocketmine\Player->sendNextChunk(boolean)
#10 /src/pocketmine/Server(2422): pocketmine\Player->checkNetwork(boolean)
#11 /src/pocketmine/Server(2184): pocketmine\Server->tick(boolean)
#12 /src/pocketmine/Server(2066): pocketmine\Server->tickProcessor(boolean)
#13 /src/pocketmine/Server(1648): pocketmine\Server->start(boolean)
#14 /src/pocketmine/PocketMine(501): pocketmine\Server->__construct(BaseClassLoader object, pocketmine\utils\MainLogger object, string phar://E:\UserFiles\TC03428615845884033855301\PocketMine-MP.phar/, string E:\UserFiles\TC03428615845884033855301\, string E:\UserFiles\TC03428615845884033855301\plugins\)
#15 (1): require_once(string phar://E:/UserFiles/TC03428615845884033855301/PocketMine-MP.phar/src/pocketmine/PocketMine.php)

PocketMine-MP version: 1.6.2dev #0 [Protocol 113; API 3.0.0-ALPHA6]
Git commit: 0000000000000000000000000000000000000000
uname -a: Windows NT NS306121 6.1 build 7601 (Windows Server 2008 R2 Standard Edition Service Pack 1) i586
PHP Version: 7.0.10
Zend version: 3.0.0
OS : WINNT, win`

**Comment by Muqsit** [comment]
THAT BRANCH IS STILL IN DEVELOPMENT. You should've read the recently closed issues.

**Comment by kabluinc** [comment]
Okay. sorry
