### ISSUE TITLE
Furnace Error

### ISSUE THREAD

**Issue by vardoOTORI** [pmmp/PocketMine-MP#1031]
### Issue description

When player touched working furnace, the error happened.

### Steps to reproduce the issue

1. Player touch working furnace.
2. The error

### OS and versions

* PocketMine-MP: 1.6.2dev 「Unleashed」 implementing API version 3.0.0-ALPHA5  29e88d8
* PHP: 7.0.9
* Server OS: Linux
* Game version: 1.1.0.55

### Crashdump, backtrace or other files

TypeError: "Argument 1 passed to pocketmine\utils\Binary::writeVarInt() must be of the type integer, float given, called in .../src/pocketmine/utils/BinaryStream.php on line 301" (EXCEPTION) in "/src/pocketmine/utils/Binary" at line 496

**Comment by dktapps** [comment]
How amusing... somebody tried to `floor` a value that is always an integer. Unfortunately for that somebody, `floor`ing anything returns a float.
