### ISSUE TITLE
Vine meta ErrorException

### ISSUE THREAD

**Issue by Awzaw** [pmmp/PocketMine-MP#1032]
### Issue description

Placing vines on the sides of a block will throw these errors on 2 sides:

[Server thread/CRITICAL]: ErrorException: "Undefined offset: 8" (EXCEPTION) in "/src/pocketmine/block/Vine" at line 155

and

[Server thread/CRITICAL]: ErrorException: "Undefined offset: 1" (EXCEPTION) in "/src/pocketmine/block/Vine" at line 155

-->

### Steps to reproduce the issue
Place vine on all sides of a block

### OS and versions

* PocketMine-MP: PocketMine-MP 1.6.2dev 「Unleashed」 implementing API version 3.0.0-ALPHA5 for Minecraft: PE v1.1.0.55 (protocol version 113)

**Comment by Driesboy** [comment]
yep i have this to in downloaded worlds

**Comment by dktapps** [comment]
I saw this the other day on a vanilla MCPE world, forgot to debug it.
