### ISSUE TITLE
Potions bug

### ISSUE THREAD

**Issue by SerezhaIvanov** [pmmp/PocketMine-MP#1035]
### Issue description

I drink potion but nothing happens.

### Steps to reproduce the issue

1. Drink the potion

### OS and versions

* PocketMine-MP: 1.6.2dev
* PHP: 7
* Server OS: Ubuntu
* Game version: PE

### Crashdump, backtrace or other files

No errors

**Comment by dktapps** [comment]
This isn't a bug, they just aren't implemented yet.

**Comment by SerezhaIvanov** [comment]
Implement please
