### ISSUE TITLE
Bug?

### ISSUE THREAD

**Issue by SerezhaIvanov** [pmmp/PocketMine-MP#1038]
### Issue description

I use InventoryTransactionEvent and I check if player click the item with id 264, server send message to player, but when server send message is duplicated.

### Steps to reproduce the issue

Use my code:

public function transactionEvent(\pocketmine\event\inventory\InventoryTransactionEvent $e){
foreach($e->getTransaction()->getTransactions() as $transaction){
foreach($e->getTransaction()->getInventories() as $inv){
if($inv->getHolder() instanceof \pocketmine\Player) $p = $inv->getHolder();
elseif($inv->getHolder() instanceof \pocketmine\tile\Chest) $chest = $inv->getHolder();
if($transaction->getTargetItem()->getId() == 264){
$p->sendMessage("message");
}}}}
### OS and versions

* PocketMine-MP: 1.6.2dev
* PHP: 7
* Server OS: Ubuntu
* Game version: PE/Win10

### Crashdump, backtrace or other files

No errors

**Comment by dktapps** [comment]
Use the [forums](https://forums.pmmp.io) for help with plugin development.
