### ISSUE TITLE
Block respawn back when mined using efficiency 10

### ISSUE THREAD

**Issue by XDqrkneZ** [pmmp/PocketMine-MP#1041]
### Issue description

 The block is respawning back when it was mined by efficiency 10 pickaxe, I believe this is because of the anti cheat, it would be amazing if you add something where we can enable/disable instant breaking and such in pocketmine.yml

### Steps to reproduce the issue

1. ...
2. ...

### OS and versions

* PocketMine-MP: PocketMine-MP 1.6.2dev-165 「Unleashed」 implementing API version 3.0.0-ALPHA5 for Minecraft: PE v1.1.0.55 (protocol version 113)
* PHP: 7.0.1
* Server OS: Linux
* Game version: PE/Win10 (delete as appropriate)

### Plugins
- Test on a clean server without plugins: is the issue reproducible without any plugins loaded?

If the issue is **not** reproducible without plugins:
- Have you asked for help on our forums before creating an issue?
- Can you provide sample, *minimal* reproducing code for the issue? If so, paste it in the bottom section
- Paste your list of plugins here (use the 'plugins' command in PocketMine-MP)

### Crashdump, backtrace or other files

* ...

**Comment by akaSnapy** [comment]
It will have a fix i guess, but don't even tink that fix will be soon cause dk is working on other stuff

**Comment by SOF3** [comment]
@akaSnapy Everything will have a fix. This is not a forum. If you don't have anything to say related to the issue, I cordially ask you to shut up please.

**Comment by SuperMaXAleX** [comment]
Enchantments aren’t fully implanted.

**Comment by dktapps** [comment]
Such an option is already present in pocketmine.yml.
