### ISSUE TITLE
Sleeping in a bed causes error in console

### ISSUE THREAD

**Issue by NML32** [pmmp/PocketMine-MP#1046]
### Issue description

Sleeping in a bed caused an error in console.
Tested in Creative mode.

[11:21:26] [Server thread/CRITICAL]: TypeError: "Argument 1 passed to pocketmine\utils\BinaryStream::putBool() must be of the type boolean, null given, called in phar://C:/Users/Mark/Desktop/1.1/PocketMine-MP.phar/src/pocketmine/network/mcpe/protocol/SetSpawnPositionPacket.php on line 63" (EXCEPTION) in "/src/pocketmine/utils/BinaryStream__64bit" at line 92

### Steps to reproduce the issue

1. Wait for night
2. Sleep in bed

### OS and versions

* PocketMine-MP:  PocketMine-MP 1.6.2dev-168
* PHP: 7
* Server OS: Win 10
* Game Version: PE/Win10 (delete as appropriate)

### Plugins
- Test on a clean server without plugins: is the issue reproducible without any plugins loaded?
Yes

If the issue is **not** reproducible without plugins:
- Have you asked for help on our forums before creating an issue?
- Can you provide sample, *minimal* reproducing code for the issue? If so, paste it in the bottom section
- Paste your list of plugins here (use the 'plugins' command in PocketMine-MP)

### Crashdump, backtrace or other files

* N/A

**Comment by Misteboss** [comment]
It's because spawnForced field isn't filled
https://github.com/pmmp/PocketMine-MP/blob/master/src/pocketmine/network/mcpe/protocol/SetSpawnPositionPacket.php#L41
https://github.com/pmmp/PocketMine-MP/blob/d358e13868c0f3c341c6cb681d319dc5fcbd6a19/src/pocketmine/Player.php#L1186
