### ISSUE TITLE
where is callbackTask?

### ISSUE THREAD

**Issue by vardoOTORI** [pmmp/PocketMine-MP#1049]
### Issue description

My plugin uses "CallbackTask" but it doesn't find in /pocketmine/scheduler.

### Steps to reproduce the issue

none

### OS and versions

* PocketMine-MP: v1.1.0.55 (4a7abb70)
* PHP: 7
* Server OS: Linux(Ubuntu)
* Game version: 1.1.0.55

### Plugins
the problem is plugin's source.

### Crashdump, backtrace or other files

none

**Comment by DaPigGuy** [comment]
That no longer exists.

**Comment by vardoOTORI** [comment]
Is there a plan to adds?

**Comment by DaPigGuy** [comment]
Nope.

**Comment by vardoOTORI** [comment]
oh my god
I wanted it if possible...

**Comment by SOF3** [comment]
CallbackTask has never been part of the plugin-usable API.

**Comment by SuperMaXAleX** [comment]
You directly can add the CallbackTask on your plugin.

**Comment by vardoOTORI** [comment]
how to do it...?

**Comment by dktapps** [comment]
CallbackTask was deprecated well over 2 years ago and removed in the PHP7 upgrade in September 2015. Some spoons haven't kept up with core changes and have retained various things that have long since been removed from the PocketMine-MP core code. Learn to use PluginTasks instead.
