### ISSUE TITLE
Can't write text on signs

### ISSUE THREAD

**Issue by HimbeersaftLP** [pmmp/PocketMine-MP#105]
### Issue description

When you place a sign, write text on it and then hit close, the text will disappear...

### Steps to reproduce the issue

1. Get a sign
2. Write text on it
3. Hit the Close Button (X) in the top-right-corner
4. The text will disappear

### OS and versions

* PocketMine-MP: Jenkins build #76
* PHP: PHP_7.0.12_x86-64_Linux (#8 on Jenkins)
* Server OS: Linux
* Game version: PE

### Crashdump, backtrace or other files

* Nothing

#### Edit by @dktapps
This ONLY happens to servers run from Jenkins phars. Servers run from source are not affected. This indicates a preprocessor issue.

**Comment by iPocket** [comment]
@thebigsmileXD 
Haven't you fixed this on March?

**Comment by dktapps** [comment]
@iPocket he's banned from this organisation...

@HimbeersaftLP Would you mind trying running a server from source and see if the issue still occurs? Se have reason to believe it's an issue with the phar preprocessor.

**Comment by iPocket** [comment]
@dktapps It's NBT issue.
Let me try to find that commit...

**Comment by dktapps** [comment]
@iPocket It's because of a preprocessor inlining bug. In case you didn't notice, this does not happen if you build a phar yourself or if you run from source code.

**Comment by HimbeersaftLP** [comment]
Yup, when I run from source it works, when using a phar, not.

Also, I fount another old pocketmine forums link in the issue template, will you fix it, so I don't have to make a PR?

**Comment by dktapps** [comment]
I've disabled the preprocessor inlining to resolve the issue.
