### ISSUE TITLE
strict type issue

### ISSUE THREAD

**Issue by Misteboss** [pmmp/PocketMine-MP#1055]
### Issue description
It's happen when i'm telporting a player in an other world with stuff.

If I wait 60 secs I have an other error in the console.

PS : The Level is already loaded, same for the  chunk of the teleport position

### Steps to reproduce the issue

1. ... Add stuff to a player then teleport him in a other world.
2. ... Check the console.

### OS and versions

* PocketMine-MP: Latest commit of api3\branch
* PHP: 7.0.2
* Server OS: Debian
* Game version: PE/Win10 (The two)

### Plugins
- Test on a clean server without plugins: is the issue reproducible without any plugins loaded?
Can't test without plugins but isn't coming from plugins.

### Crashdump, backtrace or other files

![capture d ecran 2017-06-10 a 11 02 58](https://user-images.githubusercontent.com/17687222/27001541-a4aca2d6-4dcc-11e7-95d8-fd2b15c5a02b.png)
![capture d ecran 2017-06-10 a 11 09 47](https://user-images.githubusercontent.com/17687222/27001568-7e659942-4dcd-11e7-9186-5dc78f141c06.png)

**Comment by dktapps** [comment]
Somehow the Y coordinates of both your player and the item entity managed to become null. That's an... interesting issue. Please try to reproduce this on a local test server without plugins.

**Comment by Misteboss** [comment]
Should i send the code i am using to teleport/load chunks and add Items/Armor ?

**Comment by dktapps** [comment]
The issue template asks you for reproducing code if you can provide it, so yes please.

**Comment by Misteboss** [comment]
I am very very sorry it's coming from me ^^, it was an error in my config.

**Comment by Misteboss** [comment]
So apparently it wasn’t coming from me, and i can’t understand why this is happening :/
I think it’s coming from items i am adding so if it can help you this my code `
$p->setMaxHealth(20);

$p->setMaxHealth($p->getMaxHealth());

if ($p->getAttributeMap() != null) {

$p->setHealth(20);

$p->setFood(20);

}


$player = $p;

$player->getInventory()->clearAll(true);

$player->setAllowFlight(false);

$item = Item::get(Item::DIAMOND_SWORD);

$ench = Enchantment::getEnchantment(9); // sharness

$ench->setLevel(1);

$item->addEnchantment($ench);

$player->getInventory()->addItem($item);

$player->getInventory()->addItem(Item::get(346, 0, 1));

$player->getInventory()->addItem(Item::get(261, 0, 1));

$player->getInventory()->addItem(Item::get(364, 0, 16));

$player->getInventory()->addItem(Item::get(322, 0, 6));

$item = Item::get(Item::DIAMOND_PICKAXE);

$ench = Enchantment::getEnchantment(15); 

$ench->setLevel(5);

$item->addEnchantment($ench);

$player->getInventory()->addItem($item);

$player->getInventory()->addItem(Item::get(4, 0, 64));

$player->getInventory()->addItem(Item::get(262, 0, 64));

$item = Item::get(310, 0, 1);

$ench = Enchantment::getEnchantment(0); 

$ench->setLevel(1);

$item->addEnchantment($ench);

$player->getInventory()->setHelmet($item);

$item = Item::get(311, 0, 1);

$ench = Enchantment::getEnchantment(0); 

$ench->setLevel(1);

$item->addEnchantment($ench);

$player->getInventory()->setChestplate($item);

$item = Item::get(312, 0, 1);

$ench = Enchantment::getEnchantment(0); 

$ench->setLevel(1);

$item->addEnchantment($ench);

$player->getInventory()->setLeggings($item);

$item = Item::get(313, 0, 1);

$ench = Enchantment::getEnchantment(0); 

$ench->setLevel(1);

$item->addEnchantment($ench);

$player->getInventory()->setBoots($item);

$player->getInventory()->sendArmorContents($player);`

**Comment by dktapps** [comment]
You can see from the error logs it's nothing to do with inventory. I already told you that it is saying your player's Y coordinate has become null.

**Comment by Misteboss** [comment]
Are you talking of the first screenshot ?
Because before strict type i hadn’t this issue :|

**Comment by Misteboss** [comment]
I corrected the Y coordinate and now i just have the issue of the first screenshot

**Comment by TheDiamondYT1** [comment]
@Misteboss Also in future use 
\```php
(your code here)
\```
to make it more readable
