### ISSUE TITLE
Fix the bubbles in the top right.

### ISSUE THREAD

**Issue by armagadon159753** [pmmp/PocketMine-MP#1056]
![screenshot_2017-06-10-12-24-14](https://user-images.githubusercontent.com/25569806/27002050-d1ba2ebe-4dd7-11e7-874c-cdeb07075df6.png)

**Comment by dktapps** [comment]
32-bit issue.

**Comment by Sandertv** [comment]
This is likely due to using a 32 bit system. Those are no longer supported.
