### ISSUE TITLE
Disconnect message on shutdown doesn't work / Send Packet on shutdown doesn't work

### ISSUE THREAD

**Issue by Misteboss** [pmmp/PocketMine-MP#1058]
### Issue description
When i stop my server, i didn't receive the shutdown the message while he is displayed in the console;
If you are reporting a regression or unexpected behaviour, please include the below information:
Expected result: What were you expecting to happen?

Actual result: What actually happened?
--> The client is disconnected 5-10 secs after with message : "Disconnect.. (default message setted by mcpe)"

### Steps to reproduce the issue

1. ... Join your server, close it
2. ... Check if youre disconnect message

### OS and versions

* PocketMine-MP: Last api3\branch
* PHP: 7.0.2
* Server OS: Debian
* Game version: PE/Win10 The two

### Plugins
- Tested without plugins, it doesn't work too.
I tried to send a TransferPacket onDisable() it doesn't work too and it as working before.

### Crashdump, backtrace or other files

![capture d ecran 2017-06-10 a 15 54 02](https://user-images.githubusercontent.com/17687222/27003397-0733aa84-4df6-11e7-9614-49b2e9d5ffac.png)

**Comment by dktapps** [comment]
This issue is identical to #1026 .

**Comment by Misteboss** [comment]
It's not on join..

**Comment by dktapps** [comment]
Read the comments, not just the title. The underlying issue is identical.

**Comment by Misteboss** [comment]
Ok and there is no hack to fix it ?

**Comment by dktapps** [comment]
You can remove [these lines](https://github.com/pmmp/RakLib/blob/master/server/Session.php#L533-L534) from RakLib.

**Comment by Misteboss** [comment]
Thanks ! It won't break anything ?

**Comment by dktapps** [comment]
It shouldn't, clients will disconnect themselves when receiving the MCPE DisconnectPacket, although RakLib is very loose and doesn't make behaviour strict... anything could happen.

**Comment by Misteboss** [comment]
Oh and this is why if i send a DisconnectPacket after a TransferPacket, it breaks the Transfer ?

**Comment by dktapps** [comment]
It's a queuing issue in RakLib. The queue doesn't get sent after the session is closed.

**Comment by Misteboss** [comment]
I removed these lines and it doesn't work :/
