### ISSUE TITLE
IP GET ERROR

### ISSUE THREAD

**Issue by Yeba** [pmmp/PocketMine-MP#1062]
### Steps to reproduce the issue

1. ...I am installing
2. ...When it comes to get IP

### OS and versions

* PocketMine-MP:1.1.0.55
* PHP:7
* Server OS:centos 7.3
* Game version: PE
### Plugins
- Test on a clean server without plugins: is the issue reproducible without any plugins loaded?
yes!!!!!!!!!

If the issue is **not** reproducible without plugins:
- Have you asked for help on our forums before creating an issue?
- Can you provide sample, *minimal* reproducing code for the issue? If so, paste it in the bottom section
- Paste your list of plugins here (use the 'plugins' command in PocketMine-MP)

### Crashdump, backtrace or other files

copy from putty:

[*] 正在获得你的外部IP和内部IP

Fatal error: Uncaught TypeError: strip_tags() expects parameter 1 to be string, boolean given in phar:///root/myworld/PocketMine-MP.phar/src/pocketmine/utils/Utils.php:138
Stack trace:
#0 phar:///root/myworld/PocketMine-MP.phar/src/pocketmine/utils/Utils.php(138): strip_tags(false)
#1 phar:///root/myworld/PocketMine-MP.phar/src/pocketmine/wizard/SetupWizard.php(212): pocketmine\utils\Utils::getIP()
#2 phar:///root/myworld/PocketMine-MP.phar/src/pocketmine/wizard/SetupWizard.php(88): pocketmine\wizard\SetupWizard->networkFunctions()
#3 phar:///root/myworld/PocketMine-MP.phar/src/pocketmine/PocketMine.php(489): pocketmine\wizard\SetupWizard->run()
#4 /root/myworld/PocketMine-MP.phar(1): require('phar:///root/my...')
#5 {main}
  thrown in phar:///root/myworld/PocketMine-MP.phar/src/pocketmine/utils/Utils.php on line 138

**Comment by Yeba** [comment]
what's more , both installing automatically and manually have this question！

**Comment by Yeba** [comment]
I know my ip for its on aliyun，but i am wondering weather something is missed if i just restarted it though it does work but anther question showed，so i am going to set a new issue。

**Comment by TheDiamondYT1** [comment]
Shut up.

**Comment by TheDiamondYT1** [comment]
You only need to create the issue and not comment loads on it. @dktapps is sleeping probably. It's 2:12 am for him. Create your issue, and go back to your life. Then come back later and check if anybody has replied. Simple.

**Comment by Yeba** [comment]
thanks ,but one more ,
![image](https://user-images.githubusercontent.com/18240596/27007438-53218e8a-4e86-11e7-920f-782d060b35ae.png)
if this the question?
