### ISSUE TITLE
Console Spam

### ISSUE THREAD

**Issue by ParkChanSol** [pmmp/PocketMine-MP#1063]
### Steps to reproduce the issue

1. Start server

### OS and versions

* PocketMine-MP:61b857a
* PHP: 7.0.4
* Server OS: Linux
* Game version: PE/Win10 (delete as appropriate) PE, Win 10

### Plugins
- Test on a clean server without plugins: is the issue reproducible without any plugins loaded?
Without plugins, doesn't occur error

If the issue is **not** reproducible without plugins:
- Have you asked for help on our forums before creating an issue? no
- Can you provide sample, *minimal* reproducing code for the issue? If so, paste it in the bottom section
- Paste your list of plugins here (use the 'plugins' command in PocketMine-MP)

### Crashdump, backtrace or other files

* server.log
[server.zip](https://github.com/pmmp/PocketMine-MP/files/1066225/server.zip)

**Comment by SuperMaXAleX** [comment]
Euh, can you do a description, steps, and what plugins are used ?

**Comment by SOF3** [comment]
Please paste the console log here directly, and use English version if possible.
