### ISSUE TITLE
Server getTick()

### ISSUE THREAD

**Issue by HipsterAF** [pmmp/PocketMine-MP#1065]
### Issue description

When i start the server i get this error:
Could not load level "survival": Return value of pocketmine\Server::getTick() must be of the type integer, null returned
[19:48:41] [Server thread/CRITICAL]: TypeError: "Return value of pocketmine\Server::getTick() must be of the type integer, null returned" (EXCEPTION) in "/src/pocketmine/Server" at line 652
[19:48:41] [Server thread/INFO]: Preparing level "Mines"
### Steps to reproduce the issue

1. load a world
2. ...

### OS and versions

* PocketMine-MP: 789df94
* PHP: 7.0.3
* Server OS: Win10
* Game version: 1.1 McPE

### Plugins
- Test on a clean server without plugins: is the issue reproducible without any plugins loaded? Yes

If the issue is **not** reproducible without plugins:
- Have you asked for help on our forums before creating an issue?
- Can you provide sample, *minimal* reproducing code for the issue? If so, paste it in the bottom section
- Paste your list of plugins here (use the 'plugins' command in PocketMine-MP)

### Crashdump, backtrace or other files

* ...

**Comment by dktapps** [comment]
Please enable debug output and paste a backtrace.
