### ISSUE TITLE
Error when a player join, it causes server crash

### ISSUE THREAD

**Issue by ExaSonit** [pmmp/PocketMine-MP#1066]
Error: Argument 1 passed to pocketmine\utils\Binary::writeVarLong_64() must be of the type integer, null given, called in phar:///home/gs/gs/data/servers/4009632/PocketMine-MP_1.6.2dev-157_c445db42_API-3.0.0-ALPHA5.phar/src/pocketmine/utils/Binary.php on line 650
File: /src/pocketmine/utils/Binary
Line: 677
Type: notice

Code:
[668] 		return self::writeUnsignedVarLong_32($v);
[669] 	}
[670] 
[671] 	/**
[672] 	 * 64-bit VarLong encoder.
[673] 	 *
[674] 	 * @param int $v
[675] 	 * @return string
[676] 	 */
[677] 	public static function writeVarLong_64(int $v) : string{
[678] 		return self::writeUnsignedVarLong_64(($v << 1) ^ ($v >> 63));
[679] 	}
[680] 
[681] 	/**
[682] 	 * Writes a 64-bit integer as a variable-length long
[683] 	 *
[684] 	 * @param int|string $v
[685] 	 * @return string up to 10 bytes
[686] 	 */
[687] 	public static function writeUnsignedVarLong($v) : string{

Backtrace:
#0 /src/pocketmine/utils/Binary(650): pocketmine\utils\Binary::writeVarLong_64(NULL )
#1 /src/pocketmine/utils/BinaryStream__64bit(343): pocketmine\utils\Binary::writeVarLong(NULL )
#2 /src/pocketmine/network/mcpe/protocol/DataPacket(278): pocketmine\utils\BinaryStream->putVarLong(NULL )
#3 /src/pocketmine/network/mcpe/protocol/AddPlayerPacket(77): pocketmine\network\mcpe\protocol\DataPacket->putEntityUniqueId(NULL )
#4 /src/pocketmine/network/mcpe/RakLibInterface(193): pocketmine\network\mcpe\protocol\AddPlayerPacket->encode(boolean)
#5 /src/pocketmine/Player__64bit(1081): pocketmine\network\mcpe\RakLibInterface->putPacket(pocketmine\Player object, pocketmine\network\mcpe\protocol\AddPlayerPacket object, boolean , boolean )
#6 /Slapper_v1.3.3.phar/src/slapper/entities/SlapperHuman(77): pocketmine\Player->dataPacket(pocketmine\network\mcpe\protocol\AddPlayerPacket object)
#7 /src/pocketmine/Player__64bit(913): slapper\entities\SlapperHuman->spawnTo(pocketmine\Player object)
#8 /src/pocketmine/Player__64bit(861): pocketmine\Player->doFirstSpawn(boolean)
#9 /src/pocketmine/Player__64bit(1743): pocketmine\Player->sendNextChunk(boolean)
#10 /src/pocketmine/Server__64bit(2417): pocketmine\Player->checkNetwork(boolean)
#11 /src/pocketmine/Server__64bit(2179): pocketmine\Server->tick(boolean)
#12 /src/pocketmine/Server__64bit(2061): pocketmine\Server->tickProcessor(boolean)
#13 /src/pocketmine/Server__64bit(1646): pocketmine\Server->start(boolean)
#14 /src/pocketmine/PocketMine(501): pocketmine\Server->__construct(BaseClassLoader object, pocketmine\utils\MainLogger object, string phar:///home/gs/gs/data/servers/4009632/PocketMine-MP_1.6.2dev-157_c445db42_API-3.0.0-ALPHA5.phar/, string /home/gs/gs/data/servers/4009632/, string /home/gs/gs/data/servers/4009632/plugins/)
#15 (1): require(string phar:///home/gs/gs/data/servers/4009632/PocketMine-MP_1.6.2dev-157_c445db42_API-3.0.0-ALPHA5.phar/src/pocketmine/PocketMine.php)

PocketMine-MP version: 1.6.2dev #157 [Protocol 113; API 3.0.0-ALPHA5]
Git commit: 0000000000000000000000000000000000000000
uname -a: Linux ****.******.*** 3.14.32-xxxx-grs-ipv6-64 #5 SMP Wed Sep 9 17:24:34 CEST 2015 x86_64
PHP Version: 7.0.9
Zend version: 3.0.0
OS : Linux, linux

**Comment by dktapps** [comment]
Plugin issue.

**Comment by ExaSonit** [comment]
are you sure? i don't see "This crash is caused by a plugin"

**Comment by KnownUnown** [comment]
> #6 /Slapper_v1.3.3.phar/src/slapper/entities/SlapperHuman(77): pocketmine\Player->dataPacket(pocketmine\network\mcpe\protocol\AddPlayerPacket object)

> Slapper_v1.3.3.phar

**Comment by ExaSonit** [comment]
why it causes error?

**Comment by KnownUnown** [comment]
> Error: Argument 1 passed to pocketmine\utils\Binary::writeVarLong_64() must be of the type integer, null given, called in phar:///home/gs/gs/data/servers/4009632/PocketMine-MP_1.6.2dev-157_c445db42_API-3.0.0-ALPHA5.phar/src/pocketmine/utils/Binary.php on line 650

;)

**Comment by ZizzyZizzy** [comment]
@ExaSonit Because the plugin needs to be updated to match all the changes in v1.1, as do many plugins that are suddenly spitting out errors.

In the future, test WITHOUT plugins before submitting a report. If the issue disappears, it's a plugin and the devs here are **not going to do anything but tell you it's a plugin issue**. so you would be wasting everyone's time opening a bug report here; you would need to contact the Plugin developer.

**Comment by ExaSonit** [comment]
yes, now it works don't worry, thanks for support
