### ISSUE TITLE
Crash when trying to save effect with amplifier >127 to NBT

### ISSUE THREAD

**Issue by XDqrkneZ** [pmmp/PocketMine-MP#1072]
### Issue description

 server crashing randomly

### Steps to reproduce the issue

1. ...
2. ... @dktapps said to remove  plugins that tries to set items with excessive counts into the inventory, which i did but it still crash!

### OS and versions

* PocketMine-MP: PocketMine-MP version: 1.6.2dev #182 [Protocol 113; API 3.0.0-ALPHA5]
* PHP: 7.0.3
* Server OS: LINUX
* Game version: PE/Win10 (delete as appropriate)

### Plugins
- Test on a clean server without plugins: is the issue reproducible without any plugins loaded?

If the issue is **not** reproducible without plugins:
- Have you asked for help on our forums before creating an issue?
- Can you provide sample, *minimal* reproducing code for the issue? If so, paste it in the bottom section
- Paste your list of plugins here (use the 'plugins' command in PocketMine-MP)

### Crashdump, backtrace or other files

* ...

https://pastebin.com/bXjgXTMX
https://pastebin.com/uB5qqeVi

**Comment by SuperMaXAleX** [comment]
That’s sure, you are not’ using the last version.

**Comment by dktapps** [comment]
I swear, if anyone could read backtraces...

**Comment by intagaming** [comment]
I have the same issue, but with the duration ones also. It does not have the input check for IntTag's range, so I ended up don't know what is my plugin's fault. Now whenever the server do auto-save, my server pop-up 2 of these errors:

```
Error: Value 200 is too large!
File: /src/pocketmine/nbt/tag/ByteTag
```
```
Error: Value 9223372036854771444 is too large!
File: /src/pocketmine/nbt/tag/IntTag
```

**Comment by MattWAnderson** [comment]
Issue description

Steps to reproduce the issue

Users joining server cause crash, full reason unknown.
...
OS and versions

PocketMine-MP version: 1.6.2dev #0 [Protocol 113; API 3.0.0-ALPHA5]
PHP: 7.0.18
Server OS: CentOS 6.5 x64
Game version: PE/Win10 (delete as appropriate)
Crashdump, backtrace or other files

`
PocketMine-MP Crash Dump Tue Jun 13 22:19:18 CDT 2017

Error: Value 9223372036854771952 is too large!
File: /src/pocketmine/nbt/tag/IntTag
Line: 68
Type: notice

Code:
[59] /**
[60] * @Param int $value
[61] *
[62] * @throws \TypeError
[63] */
[64] public function setValue($value){
[65] if(!is_int($value)){
[66] throw new \TypeError("IntTag value must be of type int, " . gettype($value) . " given");
[67] }elseif($value < -(2 ** 31) or $value > ((2 ** 31) - 1)){
[68] throw new \InvalidArgumentException("Value $value is too large!");
[69] }
[70] parent::setValue($value);
[71] }
[72] }
[73]
[74]
[75]
[76]
[77]
[78]

Backtrace:
#0 /src/pocketmine/nbt/tag/NamedTag(38): pocketmine\nbt\tag\IntTag->setValue(integer 9223372036854771952)
#1 /src/pocketmine/nbt/tag/IntTag(37): pocketmine\nbt\tag\NamedTag->__construct(string Duration, integer 9223372036854771952)
#2 /src/pocketmine/entity/Entity(777): pocketmine\nbt\tag\IntTag->__construct(string Duration, integer 9223372036854771952)
#3 /src/pocketmine/entity/Living(104): pocketmine\entity\Entity->saveNBT(boolean)
#4 /src/pocketmine/entity/Human(434): pocketmine\entity\Living->saveNBT(boolean)
#5 /src/pocketmine/Player(3734): pocketmine\entity\Human->saveNBT(boolean)
#6 /src/pocketmine/Server(2303): pocketmine\Player->save(boolean 1)
#7 /src/pocketmine/Server(2450): pocketmine\Server->doAutoSave(boolean)
#8 /src/pocketmine/Server(2186): pocketmine\Server->tick(boolean)
#9 /src/pocketmine/Server(2068): pocketmine\Server->tickProcessor(boolean)
#10 /src/pocketmine/Server(1654): pocketmine\Server->start(boolean)
#11 /src/pocketmine/PocketMine(503): pocketmine\Server->__construct(BaseClassLoader object, pocketmine\utils\MainLogger object, string /home/tcagame/pocketminers/15/, string /home/tcagame/pocketminers/15/, string /home/tcagame/pocketminers/15/plugins/)

PocketMine-MP version: 1.6.2dev #0 [Protocol 113; API 3.0.0-ALPHA5]
Git commit: 0000000000000000000000000000000000000000
uname -a: Linux S1.pocketminers.com 3.14.32-xxxx-grs-ipv6-64 #7 SMP Wed Jan 27 18:05:09 CET 2016 x86_64
PHP Version: 7.0.18
Zend version: 3.0.0
OS : Linux, linux

Loaded plugins:
DevTools 1.11.1 by PocketMine Team for API(s) 3.0.0-ALPHA4, 3.0.0-ALPHA5, 3.0.0-ALPHA6
MCPEPlanet_BuildBattle 3 by DragonPlayzMC, MattWAnderson for API(s) 3.0.0-ALPHA5
SecretSauce 1.2 by MattWAnderson for API(s) 3.0.0-ALPHA4, 3.0.0-ALPHA5, 3.0.0-ALPHA6
FactionsPro 1.7 by Tethered_, SpongeHost, PocketMiners.com for API(s) 3.0.0-ALPHA4, 3.0.0-ALPHA5, 3.0.0-ALPHA6
TopVoter 1.7 by SalmonDE for API(s) 3.0.0-ALPHA4, 3.0.0-ALPHA5, 3.0.0-ALPHA6
SAMMY 2 by Humerus,MattWAnderson for API(s) 3.0.0-ALPHA4, 3.0.0-ALPHA5, 3.0.0-ALPHA6
xyz 1.0.1 by unerds for API(s) 3.0.0-ALPHA4, 3.0.0-ALPHA5, 3.0.0-ALPHA6
WorldProtect 2.2.0 by aliuly for API(s) 3.0.0-ALPHA4, 3.0.0-ALPHA5, 3.0.0-ALPHA6
RealTime 2.1.1 by Guillaume351 for API(s) 3.0.0-ALPHA4, 3.0.0-ALPHA5, 3.0.0-ALPHA6
MyPlot 1.1.3 by Wiez, Exxarion, jasonwynn10 for API(s) 3.0.0-ALPHA4, 3.0.0-ALPHA5, 3.0.0-ALPHA6

----------------------REPORT THE DATA BELOW THIS LINE-----------------------

===BEGIN CRASH DUMP===
eNrtWwtz20aS/iuzdKpWchF8iqTEnFwn2/LaW5ats5R13YVbqiEwJBEBGAQzEEWn/N/3654BCOph
+3ZzvqurOKmYmEdPv/vrAfJby8apak37B0eTg35vODpstxJp7GlR6KI1/a1lNzmmW5m2caha7Vaq
jJFLGvqbTEoljgaD4XAy6A3Hh6ODyaR/NBqI2AirtUhksVR/wp5FmSSv4oQ2dVc6VV0byqXE37kO
r5VN40wVptsfdU0RNsa62dx2rVx232T2Ui47+SonYp7QF9diXYLR1nQMeWwhwfr059aTnnhs2zuw
E2Hj3vBwfyq2C2YzrJjNsGQ2c6SDZ0ZZln0vzqxaquIhHeyDgyd98WUu94aTRw+rGAqeXV2FOjO2
KEO7h7/ibCleloW0sc7a4mssDO6xoDIb2033lP/am0wmX5X3X2Jg+BgDb+MbUNrr9w7uMODmZzPH
IdQtb9S755d7c60TJTOmevAY1ddlKrO9g+FjRN2pDxMd3SN6nsiNKmCmR+nxeQ+TG98jd6GKG5Ab
DHvDO+TcQY5ORUT0mczkUTIHo94dMm4meBbpk9LqiwYxJnX4KKn+4fgRUgj76x0iR48S6Y0Pv0Dk
vNAhcocudqj1e4+R649HB4+QM1YWdpfM/VA7559n+Lk3uqfvilLTtZ9Lo14g95m3WkbwaD3/RYW2
vbOvtHFiZrMzGWdv9XLZWOUD48v57fddliflMs5Md7/198/tlvpdM/Z/M8nifMdNa7qQiVHtVqgj
RdyMjkBnZrtPn2L5uMcP4qn491wWMqXsIX64IbZotu9n6fegXmlXhV4bMZtdQjBXlzA/9PNdejjg
h7ycJ3EoFmUWUm4SdZ52J+z/RktHvHRm48Xen2JzBQaqaTc/9vMzy+eKTK2bR+/NWk54wZtEWhor
5krohSC9k0BtMWuJjlgqSyMVdYxgeBnfqGzW2v+Rjpr4oz4raAz8uJXi30SwNxBPn4phf1/owutH
PBN72+EAycHxe/ggv28ybIqjk2JZpkhVp7ehykknYN85gSe6Y/eKr6OKLzxMev4B9gKh6fSuUmnH
xBmO15Pd+AcMlKHu49dB/WtU/xrXvyb1r0P36/MfFfuPiv1Hxf6jYv+/rtjt1lJhWCZUJDNJPVhr
q4Dg7BxKgsAGIYuZfmfcGUTqBoPzMk6i1rSHiltoq0MNCv3+sN2SeYyVw06v0wtO3p6/Phlh9TK2
GOx94x9sKOR1Es9pT+ewQwOlZ+5tnJW34qLfaQrVCXUqhp3+QWc4CG7xJ1gWJojzm3EwPhCIhIuz
c/FRReKviI7BRPQPp73RtHckXpxeikGvPxa3h+Mr1G9Ig+5u2pqA/f4hHj+pLKrEcbNX2lRsYIAf
En6owYchXb5UN5fwM9PQaz20q9I+/sWQLO1KF4bKzdYA4lLJlKzEWv25qVZi9o6WG49j2qQyOU8U
+IefAgtFKoc0dALmjF7Yl82BVBJsqpmczRrsJnBszF1cnny4/IlcYq3mJrYk1Mra3Ey7XVh4Vc7J
EI0A6tY0oJyzF+enSFeZslfPyXmeS2sT1dDPIwsa2hruqOllIZc6owz46exFW5xh+ceTDBFosPZB
nY3+Wa3s0J7Nnj/fKuX8/cXlx/cf3r5sqsUDiAsVFspeyDJsytkcbQjX7wx2xPsGef6HfOC1NhZZ
5I09SZLZ7FWidXGmwafLX18RvfaIHf7JMcgJXkkGxQZJvaGR5uiORiY7GrlUdqUKFV21xUWus6Ui
Rtti628uE3xXXTVYh6rcwzdoyTvIpc7/pq0qGrqoh76giAuZpDp7efpdJa0ORRviWdz++sZwODk7
+89mIPBzQ87dAABEUkVp2v97gQAGUfJPzr4tBT7o8LebTw2J6Wk3+/fuJv8Sbgw2vqeY7sjZDNzx
f74W4Y1c77mFoB91kUSIAgtU05B4Z7gp+qAz4JLaEB29Yplsvqvo7sjZbE1s5o7Nu2nuG8ueTNQv
MosKDZINyBVUaMsWSnVTaRAu3R2tQHkflEwu+Qa8Vlw9tKu0e2DhLyiViUSoDEf976q6ikGnLgbA
35YGzjbniW76iB+4A4s6w11BP8aKPPP09lYWtKjd+kUi0NabLOv3voPkrVNAfp1uTs7fgI4vOjpT
G2LKGGrsZGLOOSlXsIEFg4IqAR/3KNYNQUi6kFLwkYoHbjg6cM1cFTZWhDefnNdP4oXOFvFS0E3Z
rJhlTy5LJf5aogccisFg2j+Y9ifixUtGuRNa4OgFpPnju4VTvC7nwnU4jaW5Luxx/6g/HNBgqlJd
bIIkTmN7PCS0TqPUZqQ6Usf8lMpbeD01puZ45BaYXK6zwAcYrOcWrleQHbSMPdaLBY04cwS/lqrY
HANqbYcKaN+P0M9ODn9D1EbHT/kPTtU2+ppIMst0mYXKsxfIcBWrG0WXU6Zi4SZW6yACTxILj8e8
LUn0Olgk8XJlPQ9OIJnFKYy+M5bqeTWw0AXOqpXjD1jJIgp1UT/nN7lfH8WLRRyWid0c91mt3JtZ
XQRGWYJk5piGE7CcOBM6GyV6Pt9sZ4xSUWMh3f8dv3v/4ezkLZsQMaUDujCo1KkiY+HIoUzCiied
0Z1qsLWpd4Y4P+51+B8ajLMbaI78wcC/zfGQtUV9Up3+Ops0IZcVlCREyN7q74DYaQV0JHY6Tjix
uFwpo0QltJCFEoB+Akwa/JBWhGRJvvKMszApI/R2MV213gkWonWBVpgvRu/TNHKh2kITqjREUswL
Ja/FRpeFpyXihYAS4kXMJ8BsBRwYFQOE36l1Ta4bqYWE4YxY6+zPVsg8V7IQpOoUwkK1yQbsg4nY
OLnXK5WJMl8WMgKBziwjHTti01kmnlyuUC+CBEPgAl3RspRLJeg+m1Xm7WFiPCca9ONPrFTa+mKl
Qi/F7kYwUBUulXXW8XWcqyiWHV0su/TUfQu3v9KLqzcX76/Gw6NgcEX7oMaa0FTMkDOXsxYd9HHF
iFxYDX6ySEBKfwMBMxUyM4m00BtPszaZU0XXyRCMTRqpmzhUYoXKmbCRUxB2cbM9ki/zMW5WpY00
xZh7mUDMuOAWYaKNihxbJxSugtIK3YX4+ituYin+g/IKlnB+qSrzVFDup40XK+yT5KVGgxt/ijOV
9IREaeCEqBNwBJYO9QArUaYi0tN2IgBbczC1JX/KmayiA4kFpQEBd4VHEKvzjfB+hOU+79WzWzU8
+YiSD2PCpWQUiUIZ53nEJt2YgR1pyoLTGt2tzxXpA0pXv5YyIXPwCwD/7mDPH4kSsQ/i7jzkW0WJ
P4A16bpqilk6+V2ZzunyaiFOzCYLL6W5hscX15Ruaf4nGIH9sxKSVq0KFM4SLoHVpi0Yawmf2/gu
GIkaWjNU+1ktqIo0lpYZIoeWMO0LdhnIg+Aq9C0yr1VQAcRhV89q1kirjp03C4pQWkKR2Bax/TM0
ZwveFSkqRuyFd/aKPUgAO4sBaYRlCLyUU3FIoerKIAfqX5B9oVUCC8INC66OlJBStZTzjQU34sLx
0eOTY0O2dWEOgdYxc8WaFlRqfJX1Q4aVsojhK8hRinIuUVkgQVQnOttDkpI9dqkhBLXsrDCcs2Qm
Xdmeit6M8wSnZIs8I6P/4+wTnvoC81RR/yXmUf9yPt/nqZofT80IxBMhDqQYzw2dWbHU7/UGB46t
cwVwysWIIpHea4mQ07Fnr462Ps5CoonIw3hFgGhQLs44iWsAygzxCcVRbnhMr06fQFIJ53eKdLds
xuWWaCD2tnHskhGd8J4SCNU3Xt65v5jk9vgYOsxVSGXQsF6IV6dkt7cWAKpUudmKOex5Oc3+gwx5
qYdO6qUs5nCAINRJ4oAihdiDWmV/Ilb8HuH3IHJTmZVccJtcAIyUcIb9dpUR7niDdweXVReLKjOk
WzfriPeu2vETXGKlyySqGYmRP9aZ2LJOjity5hwCjgkqZ3zQKw6Fe5mRfcXtroVaFMCwPvXQXj8f
NHNSw6YQwpvuris84D+NfYTYw1WZXRun7zOJ9FqmKC10nSEqNEzSCAedXYhsj+B3uI4ux4hgcgGh
m7JKmiD8UruJu1ajzE/wyFGgpZV/ODp+2e8gKlefIATyV05Y7wLVQTRRl+wvkpplmbJkghqvwSMS
V/7m0qK1IPQhCdoaet8pfDbiuHNo1M+6JDRXdSFkFT5ppq1qhuK92Fii3RZBv+HDVPD42MBWrCCb
jMYumWwLLDcFVN0iZ0NCbgw+aC8GPU8d8RrtDtR7DAAMf31x/lMbe8HBHGlnHUd25bI1h3VNPmDy
UzHxaGCLEwwrprG0I04ihNFKJosukL2DLpGCe/mDcKSgjpks3IjDuiQ3aDVA1i2FHEEfmbRdONO5
H+MMyBFSwWsUhxrV95/Os/MKHWxxOgEf2rRGip8RSM/ywD82cRj6NTUvl8762mdKQUWiYH9Wtyos
HcChlEOvkjr1rCGHYNySr/JOnMXERp9Fq1a4UPwoi4yydGMntS4+LxMVT6AtIlQLEma7MpUIzBQW
taTDoszoM0uKYoiTckSDcpXi6TjImAXxIvBj20CowCt/3kHuoqqPOTzwbJy6kDFUzz7NnbPQcwvz
0S52JQAvrGDmmY86+pFvF26mptYW89KyHKEki8mqRIeFNCvmuYHy3Fc/WERy0HlVYBUyNnwgyhM5
1GIrCGGSShamxzNBPdbA3TjomegTjPSwgfoFdoKqV2Czkhy+h5j5eJuybb0Sjegin9oSWaG7DF38
wBqR2R41y1yanbp+TqOPIDVX3ZaqOglOxZG0UIu8cX0k/aovOGiqNqKE+ZHmlLTTSm9eYR7BMSxG
SDGkMLkiQwBiZDpM4lzwTkTQWW2MVN9UTYYpFaUxJAVD/fYcnd41eUYcrthfqVvfwEiuN0/YLRPe
7D3P3bFUFB2bpuF/W2bJh407wTXsxqmEWh6vElOfyXRIMQ22fzduyZ0ks9BICtUdzE4vr6rGTjiP
d7cYvNRn/9L4RjMEPcsFwG8J3JapyOEkN3HCLe5OwgrRPqOWenKcRxmLQS2UNyn4gCs9dqIa7iAZ
uQTdBdG4x2GVp+wMVzDXtYAXVLDIxefSqMZhe32UigdOaYsBJvoPTSgbdva5bBnV5IJj5ZIo041C
ZVKF0uzOIwd1yuK7m+2lDpVCzjjUN5ChZLKWG+NoezoNU7mS7wtglce9Mn2ayUj3yV0g1K5W7VwW
PngFxX3oSaqRe7m/ZJRFRZcTViUbaYWYpAYcYUs/p+KAtn5gBNXYyp6TKXevMleO1FwtKLPyDSQl
NbKPo00Jge8lKyjGVOkTH5dLY7o6UnQVkW/8NZmHaDW85wK64DcXFVrw1X1RJrxMG5tsAkpqcegQ
FleFgu6mLDNfCfqLplsBh62NTBVHM6VAwl0VBq2L+QMAomKZpPQaccOZv0erwIHDn+pXhHoDN7ph
0m9lcmBdIe/aJ3cfHUEvtdftmqb3oG1kAToR3xVxZoaF/Fbv3c4EQyoLdJkclDkytGok/jBR0h3C
9+JbVbx5yQf5VEUJitzHVXIEINBNKrxYwhWyCtjylqbI4kmAmHwiliihZquU7Y1MpZfOfcX48raW
MV+uQbsOdMAR/X5OXTweGHgWY/9/glqu8zLx1Pxvgpd3CM8yzipB7kqlu48P2OHJ1anlgndS1S/q
0b5PcFQnp8L1ZZX/0YdhZT4VR65Zc5HD6c/BMU8LVCY9rgPuBQCIjhx8ooPqQR6T6Tymb1Z5ib99
d5drU5dO6R6QwIxwo86fvQO6UKvRWH0Rik0BXc3W/sEjddHZGQU+JKC13b3S5FgOQDVu6tHNMIOZ
zjYptegczwYKNjWndOfgp8V2mjlmFCKXy0It/bVefWFKjR59THv9iDiOIaJnHmKINOYChY18bzvc
wk1Pawjr4dcWP/Cozhu55QXd9/MFtEp0TrUdWBPIlC5Kqay7jgpoaKEK9LQBZfyMkBwt8miwNIwg
m0SEf4nZQIkl+kZjXcmokrOnRjZy0xX9LYdOK+v1+gGdIGvW6MLDQ6JKW6rehmxC5YlO5EbD76nu
izv1EX6ik6cpOgnNGcHr74vw05dItpt3Xpd9mggY1K1T5ZN37y9Pp/Rux41xuqKbBI/Rfb6iC+0l
Wi1uAeNFTSfUCaTYIrtG28LkfGauEj1qBFCF09DprST85h4ItIM/b6ZpZS+eQkagq8Cp+JlBNLBE
m+8G/04UXV2rAF3zXRJLQPeVBb2O4Uup6s0ddyYP4QJG1gxWDDe53B3BLjEY9UiuwTqfygzwL0Gv
+Ci/cTHfnjYVr96eXE4HP07ao6Pbfnt4O2wPfuz/GAFwudS+R58hhJSGjw97rgK4p4PRPr+6U7cW
UJr6OHpD/wKoovk9JEVZ8zkPd+fNr0ls1ZA/3JwE7lPRT+5LznrNPARyXTVH6KVQFsliZ8z/DyTb
gbJIms+LOOEvpxojdufbzWW085TuTK6Q/NwHOPQhgfEfHRzwYzp3L7Ga69Ow2OR2R1RgPvC8c8jF
+dtd7WR2h+d0AwXxF6X+lxjR1IA0JQJ6ST/qHfQm+PnDG9h3PgpHR71xdDAaKPo1GQ7k0XDeG/UX
w8PBRPUGk4Oj+eFQ/EBfJKxYgQMQHPArWBPf7jDj7y35c9Z+Z9yiz04W/vJtR7BVqnd0ZTj9mHuC
xM0Rq69VhrK8Y5GPaI2QQNkdhvxBx0by++CB/6D2U5y7rz2GHfo647+oGL4/52K8pfP58z8AK0fM
tQ==
===END CRASH DUMP===

`

**Comment by MattWAnderson** [comment]
Was likely the plugin using    $speed->setDuration(PHP_INT_MAX); causing the issue.

**Comment by intagaming** [comment]
Why the value of PHP_INT_MAX is different? I think with the level of knowing how to use PHP_INT_MAX, no one is gonna add some value to PHP_INT_MAX, do they ?

**Comment by KnownUnown** [comment]
PHP_INT_MAX is PHP's maximum supported int value on that architecture. IntTag stores a 32-bit integer. When PHP is running on a 64-bit system, PHP_INT_MAX is outside the bounds of a 32-bit integer.

**Comment by Muqsit** [comment]
The only way to fix this would be using an if statement.
According to http://minecraft.gamepedia.com/Player.dat_format, the current value types are correct.
Id, Amplifier, Show particles and Ambient should be TAG_Byte and Duration should be TAG_Int

**Comment by dktapps** [comment]
@Muqsit the values are correct, but they exceed the bounds because they are unsigned, whereas TAG_* values are always supposed to be signed.

**Comment by Muqsit** [comment]
@dktapps Oh, makes sense now.

**Comment by dktapps** [comment]
```
[12:14:10] [Server thread/CRITICAL]: InvalidArgumentException: "Value 60000 is too large!" (EXCEPTION) in "pocketmine-mp/src/pocketmine/nbt/tag/ShortTag" at line 70
[12:14:10] [Server thread/DEBUG]: #0 pocketmine-mp/src/pocketmine/nbt/tag/NamedTag(38): pocketmine\nbt\tag\ShortTag->setValue(integer 60000)
[12:14:10] [Server thread/DEBUG]: #1 pocketmine-mp/src/pocketmine/nbt/tag/ShortTag(39): pocketmine\nbt\tag\NamedTag->__construct(string Air, integer 60000)
[12:14:10] [Server thread/DEBUG]: #2 pocketmine-mp/src/pocketmine/entity/Entity(775): pocketmine\nbt\tag\ShortTag->__construct(string Air, integer 60000)
[12:14:10] [Server thread/DEBUG]: #3 pocketmine-mp/src/pocketmine/entity/Living(104): pocketmine\entity\Entity->saveNBT(boolean)
[12:14:10] [Server thread/DEBUG]: #4 pocketmine-mp/src/pocketmine/entity/Human(434): pocketmine\entity\Living->saveNBT(boolean)
[12:14:10] [Server thread/DEBUG]: #5 pocketmine-mp/src/pocketmine/Player(3770): pocketmine\entity\Human->saveNBT(boolean)
[12:14:10] [Server thread/DEBUG]: #6 pocketmine-mp/src/pocketmine/Player(3688): pocketmine\Player->save(boolean)
[12:14:10] [Server thread/DEBUG]: #7 pocketmine-mp/src/pocketmine/Server(1991): pocketmine\Player->close(pocketmine\event\TranslationContainer object, string Server closed)
[12:14:10] [Server thread/DEBUG]: #8 pocketmine-mp/src/pocketmine/Server(2073): pocketmine\Server->forceShutdown(boolean)
[12:14:10] [Server thread/DEBUG]: #9 pocketmine-mp/src/pocketmine/Server(1654): pocketmine\Server->start(boolean)
[12:14:10] [Server thread/DEBUG]: #10 pocketmine-mp/src/pocketmine/PocketMine(504): pocketmine\Server->__construct(BaseClassLoader object, pocketmine\utils\MainLogger object, string pocketmine-mp\, string pocketmine-mp\, string pocketmine-mp\plugins\)
[12:14:10] [Server thread/EMERGENCY]: Crashed while crashing, killing process
```
also interesting
