### ISSUE TITLE
Vine Line 155 - Undefined offset: 1

### ISSUE THREAD

**Issue by linuzo** [pmmp/PocketMine-MP#1073]
### Issue description
[Server thread/CRITICAL]: Could not tick level "jungle": Undefined offset: 1
[23:01:25] [Server thread/CRITICAL]: ErrorException: "Undefined offset: 1" (EXCEPTION) in "home/linuzo/PocketMine-MP/src/pocketmine/block/Vine" at line 155

### Steps to reproduce the issue

1. ... Run the latest pocketmine with a jungle biome. Every so often these messages will appear
2. ...

### OS and versions
This server is running PocketMine-MP 1.6.2dev 「Unleashed」 implementing API version 3.0.0-ALPHA5 for Minecraft: PE v1.1.0.55 (protocol version 113)

NOTE: LATEST is not a valid version. PocketMine version should include Jenkins build number and/or git commit hash.

NO support whatsoever will be provided for forks or spoons of PocketMine. Issues relating to non-official distributions will be closed as spam. Please send such issues to whoever is responsible for the fork or spoon you are using.

Note that 32-bit platforms are no longer supported by PocketMine-MP and issues concerning 32-bit platforms will be closed.
-->
* PocketMine-MP:
* PHP:
* Server OS:
* Game version: PE/Win10 (delete as appropriate)

### Plugins
- Test on a clean server without plugins: is the issue reproducible without any plugins loaded?

If the issue is **not** reproducible without plugins:
- Have you asked for help on our forums before creating an issue?
- Can you provide sample, *minimal* reproducing code for the issue? If so, paste it in the bottom section
- Paste your list of plugins here (use the 'plugins' command in PocketMine-MP)

### Crashdump, backtrace or other files

* ...

**Comment by jasonwynn10** [comment]
duplicate #1032

**Comment by dktapps** [comment]
outdated version

**Comment by smakosav** [comment]
It's really absurd! I replaced the obsolete version with the new one, but the error persists, fix it please :(
`[Server thread/CRITICAL]: ErrorException: "Undefined offset: 1" (EXCEPTION) in "/src/pocketmine/block/Vine" at line 155`
