### ISSUE TITLE
api3/blocks: SplashPotion error

### ISSUE THREAD

**Issue by alex2534alex** [pmmp/PocketMine-MP#1075]
### Issue description
See error below

### Steps to reproduce the issue

1. Throw splash potion somewhere

### OS and versions
* PocketMine-MP: 97c0811
* PHP: 7.0.14

### Plugins
- No plugins loaded

### Crashdump, backtrace or other files

> [04:57:53] [Server thread/CRITICAL]: Could not tick level "world": Argument 1 passed to pocketmine\entity\Effect::setDuration() must be of the type integer, float given, called in /home/srv1/src/pocketmine/entity/projectile/SplashPotion.php on line 131

**Comment by Muqsit** [comment]
That branch is still in development, so errors are expected. It's not recommended to use api3/blocks.
