### ISSUE TITLE
Win10: Spam debug messages when player close the client

### ISSUE THREAD

**Issue by matcracker** [pmmp/PocketMine-MP#1077]
### Issue description

This issue happens only in MCPE: Windows 10.
When a player quits the server (without a correct disconnection), there are a spam of debug messages.

### Steps to reproduce the issue

1. Join the server
2. Close the client by clicking the red button "X" xD

### OS and versions

* PocketMine-MP: [bf3868c](https://github.com/pmmp/PocketMine-MP/commit/bf3868c078444a37629bfab231b5f4bed358a13c)
* PHP: 7.0.3
* Server OS: Windows 10
* Game version: Win10

### Plugins
- Test on a clean server without plugins: is the issue reproducible without any plugins loaded? Yes.

### Crashdump, backtrace or other files

* https://pastebin.com/raw/Ps5kKRwi

**Comment by dktapps** [comment]
Nothing the server can do this, we can't detect when a remote host decided to quit. This problem lies at the socket level, there's nothing we can do about this. Also, you created this issue on the wrong repository.
