### ISSUE TITLE
[Server thread/CRITICAL]: pocketmine\plugin\PluginException: "pocketmine\event\entity\EntityDamageByEntityEvent does not have a valid handler list" (EXCEPTION) in "/src/pocketmine/plugin/PluginManager" at line 773

### ISSUE THREAD

**Issue by BIntangPutra404** [pmmp/PocketMine-MP#1078]
* PocketMine-MP:1.6dev Unleashed For MCPE 1.1 Master Branch
* PHP:7.0.3 64bit
* Server OS:Mac Os X and Ubuntu
* Game version: PE/Win10 (BOTH)
Im using EntityDamageByEntityEvent Then Register The event To Plugin Manager

But I Got This

> [Server thread/CRITICAL]: pocketmine\plugin\PluginException: "pocketmine\event\entity\EntityDamageByEntityEvent does not have a valid handler list" (EXCEPTION) in "/src/pocketmine/plugin/PluginManager" at line 773

**Comment by BIntangPutra404** [comment]
Wait, What?

**Comment by dktapps** [comment]
You cannot listen for this event directly, you must listen for EntityDamageEvent.

**Comment by BIntangPutra404** [comment]
then use instanceof?

**Comment by TheDiamondYT1** [comment]
Yes.

> Any more questions can be asked on the forums   @ http://forums.pmmp.io
