### ISSUE TITLE
Packets lagging

### ISSUE THREAD

**Issue by HipsterAF** [pmmp/PocketMine-MP#1079]
### Issue description

Packets are lagging so much
See the pic below
![untitled](https://user-images.githubusercontent.com/25702950/27044478-4f143e7e-4fbb-11e7-81ea-6fe6de6ee905.png)
### Steps to reproduce the issue

1. Have a server open with 40+ players
2. ...

### OS and versions

* PocketMine-MP: bf3868c
* PHP: 7.0.19
* Server OS: Linux
* Game version: McPE 1.1 (delete as appropriate)

### Plugins
- Test on a clean server without plugins: is the issue reproducible without any plugins loaded? Yes

If the issue is **not** reproducible without plugins:
- Have you asked for help on our forums before creating an issue?
- Can you provide sample, *minimal* reproducing code for the issue? If so, paste it in the bottom section
- Paste your list of plugins here (use the 'plugins' command in PocketMine-MP)

### Crashdump, backtrace or other files

* ...

**Comment by Sandertv** [comment]
This is where blaming shoghi comes in handy.

**Comment by Muqsit** [comment]
I don't know why but I think half of the "lag" comes from the Server::getPlayer*() functions becase
* It loops through every player to check whether the player exists
* It's used a lot by too many plugins
But then again, it's probably a < 150 iteration loop and cannot be blamed for anything major as such.

**Comment by dktapps** [comment]
No, it's because of the batching/compression changes in 1.1... how many times have I said this now?

**Comment by TheDiamondYT1** [comment]
@dktapps 69

**Comment by Muqsit** [comment]
@dktapps ...and that!

**Comment by dktapps** [comment]
not to mention the fact that each client spams the server every tick with InteractPackets... one for every player on the map... 1 player, 1 per tick. 2 players, 2 per tick each. 40 players, 40 per tick each... 1600 per tick. You do the maths. Then go spam Mojang and leave our issue tracker alone.
