### ISSUE TITLE
Reason for close()

### ISSUE THREAD

**Issue by HipsterAF** [pmmp/PocketMine-MP#1081]
### Issue description

Players with invalid name or outdated client don't get the message saying 'Invalid name' or 'outdated client' respectively, they just get 'syncing pack with server' and then "disconnected from server" screen.
### Steps to reproduce the issue

1. Login with an invalid name
2. Join with an outdated client

### OS and versions

* PocketMine-MP: 5011198
* PHP: 7.0.19
* Server OS: Linux
* Game version: PE 1.1

### Plugins
- Test on a clean server without plugins: is the issue reproducible without any plugins loaded?

If the issue is **not** reproducible without plugins:
- Have you asked for help on our forums before creating an issue?
- Can you provide sample, *minimal* reproducing code for the issue? If so, paste it in the bottom section
- Paste your list of plugins here (use the 'plugins' command in PocketMine-MP)

### Crashdump, backtrace or other files

* ...

**Comment by Misteboss** [comment]
It's coming form the close() who doesn't work

**Comment by jrodr10** [comment]
Invalid name is one whom has a space in it, joining on an older client is retarded
