### ISSUE TITLE
Broken enchants?

### ISSUE THREAD

**Issue by XDqrkneZ** [pmmp/PocketMine-MP#1082]
### Issue description

 
I did /enchant (myname) 9 ( 9 is sharpness ) 3 ( 3 is the level so im supposed to get sharpness 3 )

I did that and it said "There is no such enchantment with ID 9"

The [Enchant](https://github.com/pmmp/PocketMine-MP/blob/master/src/pocketmine/item/enchantment/Enchantment.php).php says Sharpness' id is 9

and then I did /enchant (myname) sharpness 9 and it gave me Protection IX.

### Steps to reproduce the issue

1. ... Wrong enchant ID
2. ...

### OS and versions

* PocketMine-MP: PocketMine-MP 1.6.2dev-182 「Unleashed」 implementing API version 3.0.0-ALPHA5 for Minecraft: PE v1.1.0.55 (protocol version 113)
* PHP: 7.0.3
* Server OS: Linux
* Game version: PE/Win10 (delete as appropriate)

### Plugins
- Test on a clean server without plugins: is the issue reproducible without any plugins loaded?

If the issue is **not** reproducible without plugins:
- Have you asked for help on our forums before creating an issue?
- Can you provide sample, *minimal* reproducing code for the issue? If so, paste it in the bottom section
- Paste your list of plugins here (use the 'plugins' command in PocketMine-MP)

### Crashdump, backtrace or other files

* ...

**Comment by akaSnapy** [comment]
Related to -> https://github.com/pmmp/PocketMine-MP/issues/1012

Read it, you can close this issue..

**Comment by TheDiamondYT1** [comment]
I believe (but could be wrong) that better enchantment handling was implemented on the [api3/blocks](https://github.com/pmmp/PocketMine-MP/tree/api3/blocks) branch.

**Comment by akaSnapy** [comment]
@TheDiamondYT1 You are right.

**Comment by XDqrkneZ** [comment]
is that api3/blocks different from this? @TheDiamondYT1

**Comment by akaSnapy** [comment]
@XDqrkneZ dm me @glavanmadalin2 and i'll explain you

**Comment by Muqsit** [comment]
Yeah, this was fixed in api3/blocks branch along with new enchantment functions.

**Comment by Qimie** [comment]
Enchanment is not implemented yet in master branch, right?
