### ISSUE TITLE
connect error

### ISSUE THREAD

**Issue by Yeba** [pmmp/PocketMine-MP#1083]
### Issue description

I do as "Installing on Linux/MacOS" ,and succeed. Then log in, and log out,10 minutes later, **failed** to log in. Not noly me, but also my friends have this question.
### Steps to reproduce the issue

1. ...succeed to install
2. ...log in and log out,10 minute later, failed to log in. 

### OS and versions

* PocketMine-MP:1.1.0.55
* PHP:7
* Server OS:centos 7.3 x64
* Game version: PE

### Plugins
- Test on a clean server without plugins: is the issue reproducible without any plugins loaded?
no plugins

If the issue is **not** reproducible without plugins:
- Have you asked for help on our forums before creating an issue?
- Can you provide sample, *minimal* reproducing code for the issue? If so, paste it in the bottom section
- Paste your list of plugins here (use the 'plugins' command in PocketMine-MP)

### Crashdump, backtrace or other files

* ...

**Comment by dktapps** [comment]
Please review the contribution guidelines before opening an issue.

[Contribution guidelines](https://github.com/pmmp/PocketMine-MP/blob/master/CONTRIBUTING.md)
