### ISSUE TITLE
Value 9999999461 is too large!

### ISSUE THREAD

**Issue by BlawoHD** [pmmp/PocketMine-MP#1086]
### Steps to reproduce the issue

1. I join and 3 minutes left the server crash
2. ...

### OS and versions

* PocketMine-MP: 1.6.2dev
* PHP: 7.0.3
* Server OS: Linux
* Game version: PE/Win10 (delete as appropriate)

### Plugins
- Test on a clean server without plugins: is the issue reproducible without any plugins loaded?

If the issue is **not** reproducible without plugins:
- Have you asked for help on our forums before creating an issue?
- Can you provide sample, *minimal* reproducing code for the issue? If so, paste it in the bottom section
- Paste your list of plugins here (use the 'plugins' command in PocketMine-MP)

### Crashdump, backtrace or other files

PocketMine-MP Crash Dump Wed Jun 14 18:03:43 UTC 2017

Error: Value 9999999461 is too large!
File: /src/pocketmine/nbt/tag/IntTag
Line: 68
Type: notice

Code:
[59] 	/**
[60] 	 * @param int $value
[61] 	 *
[62] 	 * @throws \TypeError
[63] 	 */
[64] 	public function setValue($value){
[65] 		if(!is_int($value)){
[66] 			throw new \TypeError("IntTag value must be of type int, " . gettype($value) . " given");
[67] 		}elseif($value < -(2 ** 31) or $value > ((2 ** 31) - 1)){
[68] 			throw new \InvalidArgumentException("Value $value is too large!");
[69] 		}
[70] 		parent::setValue($value);
[71] 	}
[72] }
[73] 
[74] 
[75] 
[76] 
[77] 
[78] 

Backtrace:
#0 /src/pocketmine/nbt/tag/NamedTag(38): pocketmine\nbt\tag\IntTag->setValue(integer 9999999461)
#1 /src/pocketmine/nbt/tag/IntTag(37): pocketmine\nbt\tag\NamedTag->__construct(string Duration, integer 9999999461)
#2 /src/pocketmine/entity/Entity(777): pocketmine\nbt\tag\IntTag->__construct(string Duration, integer 9999999461)
#3 /src/pocketmine/entity/Living(104): pocketmine\entity\Entity->saveNBT(boolean)
#4 /src/pocketmine/entity/Human(434): pocketmine\entity\Living->saveNBT(boolean)
#5 /src/pocketmine/Player(3739): pocketmine\entity\Human->saveNBT(boolean)
#6 /src/pocketmine/Server(2307): pocketmine\Player->save(boolean 1)
#7 /src/pocketmine/Server(2454): pocketmine\Server->doAutoSave(boolean)
#8 /src/pocketmine/Server(2190): pocketmine\Server->tick(boolean)
#9 /src/pocketmine/Server(2072): pocketmine\Server->tickProcessor(boolean)
#10 /src/pocketmine/Server(1654): pocketmine\Server->start(boolean)
#11 /src/pocketmine/PocketMine(501): pocketmine\Server->__construct(BaseClassLoader object, pocketmine\utils\MainLogger object, string phar:///home/BlawoHD/Games/PocketMine-MP.phar/, string /home/BlawoHD/Games/, string /home/BlawoHD/Games/plugins/)
#12 (1): require_once(string phar:///home/BlawoHD/Games/PocketMine-MP.phar/src/pocketmine/PocketMine.php)

PocketMine-MP version: 1.6.2dev #0 [Protocol 113; API 3.0.0-ALPHA5]
Git commit: 0000000000000000000000000000000000000000
uname -a: Linux vps 2.6.32-042stab120.19 #1 SMP Mon Feb 20 20:05:53 MSK 2017 x86_64
PHP Version: 7.0.3
Zend version: 3.0.0
OS : Linux, linux

**Comment by dktapps** [comment]
duplicate of #1072
