### ISSUE TITLE
Possibility to drop items in Spectator mode

### ISSUE THREAD

**Issue by SuperMaXAleX** [pmmp/PocketMine-MP#1087]
### Issue description
The title is saying everything - You can drop items/blocks in Spectator mode.

### Steps to reproduce the issue
1. Be in Spectator mode
2. Try to drop an item/block

### OS and versions
* PocketMine-MP 1.6.2dev 「Unleashed」 implementing API version 3.0.0-ALPHA5 for Minecraft: PE v1.1.0.55 (protocol version 113)
* PHP: 7.0.3
* Server OS: OS X El Capitan
* Game version: PE/W10

### Plugins
- Tested without plugins

### Crashdump, backtrace or other files
* None

**Comment by SuperMaXAleX** [comment]
RIP this issue

**Comment by bettylovedertderrdy** [comment]
genisyspro better !

**Comment by dktapps** [comment]
Fixed in MCPE 1.2 inventory changes.
