### ISSUE TITLE
On world move blocks appear from the previous world

### ISSUE THREAD

**Issue by BenBeri** [pmmp/PocketMine-MP#1088]
When you move to another world e.g with Worlds plugin, doesn't matter what plugin, you can still visually see the blocks from the previous world, but logically these blocks does not exist because when you hover on these blocks you don't see the block's outline, but the new world's blocks outlines under it.
Try it, its a bug with the new 1.1 update.

**Comment by dktapps** [comment]
Without knowing your PocketMine-MP version, OS, PHP, Client version, or plugins and how the issue occurred, the issue cannot begin to be solved.
A pre-formatted template is provided that shows the required information to begin to find, test and solve an issue.
Until the adequate template and information is provided, the issue will be closed; it may be reopened if you update the ticket with the correct template and required information.

[Contribution guidelines](https://github.com/pmmp/PocketMine-MP/blob/master/CONTRIBUTING.md)

**Comment by dktapps** [comment]
#843
