### ISSUE TITLE
php exit on open "127"

### ISSUE THREAD

**Issue by joeybab3** [pmmp/PocketMine-MP#1089]
### Issue description
Write a short description about the issue

Basically I just installed it fresh from the installer, then after opening it it crashes with:
`bin\php\php.exe: Exit 127`

### Steps to reproduce the issue
1. Install using installer
2. Have it not work

### OS and versions
Build #190, can't do "version" command because all it says is "bin\php\php.exe: Exit 127" in red.
* PocketMine-MP: build #190
* PHP: 7.0.3
* Server OS: Windows 8.1
* Game version: PE

### Plugins
None

### Crashdump, backtrace or other files
bin\php\php.exe: Exit 127

**Comment by dktapps** [comment]
Please use our [forums](https://forums.pmmp.io) for setup help and support. Also please read the [README.md](https://github.com/pmmp/PocketMine-MP#setup-help--support-faqs).
