### ISSUE TITLE
I can't seem to find the source of this issue...

### ISSUE THREAD

**Issue by Pizzahaet** [pmmp/PocketMine-MP#1091]
[Server thread/CRITICAL]: Could not tick level "Paris": Argument 1 passed to pocketmine\utils\Binary::writeVarInt() must be of the type integer, float given, called in /root/Desktop/PocketRoyaleNetwork/PocketRoyaleMiniGames/src/pocketmine/utils/BinaryStream.php on line 301
[18:34:17] [Server thread/CRITICAL]: TypeError: "Argument 1 passed to pocketmine\utils\Binary::writeVarInt() must be of the type integer, float given, called in /root/Desktop/PocketRoyaleNetwork/PocketRoyaleMiniGames/src/pocketmine/utils/BinaryStream.php on line 301" (EXCEPTION) in "/src/pocketmine/utils/Binary" at line 496

**Comment by dktapps** [comment]
Without knowing your PocketMine-MP version, OS, PHP, Client version, or plugins and how the issue occurred, the issue cannot begin to be solved.
A pre-formatted template is provided that shows the required information to begin to find, test and solve an issue.
Until the adequate template and information is provided, the issue will be closed; it may be reopened if you update the ticket with the correct template and required information.

[Contribution guidelines](https://github.com/pmmp/PocketMine-MP/blob/master/CONTRIBUTING.md)
