### ISSUE TITLE
RakLib error..?

### ISSUE THREAD

**Issue by mal0ne-23** [pmmp/PocketMine-MP#1092]
[20:05:10] [Server thread/CRITICAL]: [Network] Stopped interface pocketmine\network\mcpe\RakLibInterface due to Value 9223372036854775286 is too large!

No idea how to reproduce, it's random to my knowledge.

### OS and versions
* PocketMine-MP: 5011198a4e8a8585bc493679231115e542e86ae1
* PHP: 7.0.something
* Server OS: ubuntu linux
* Game version: irrelevent

**Comment by DaPigGuy** [comment]
Try latest build.

**Comment by MattWAnderson** [comment]
Duplicate #1072

**Comment by mal0ne-23** [comment]
No, that is a _crash_ that occurs when an NBT value is too high or something. This just shuts down the raklib server and the server stays on.

**Comment by MattWAnderson** [comment]
Yes, but it's the same core issue. From looking at the code in the latest commit it should be fixed however if you try that one.
