### ISSUE TITLE
GoldenApple aren't working

### ISSUE THREAD

**Issue by Misteboss** [pmmp/PocketMine-MP#1094]
### Issue description
GoldenApple aren't working sometimes.
Check the video below

### Steps to reproduce the issue

1. ... Eat a GoldenApple
2. ... Check what happen

### OS and versions

* PocketMine-MP: https://github.com/pmmp/PocketMine-MP/commit/788cb09d53355123e77d2bbc7b216d2dff56db1a
* PHP: 7.0.2
* Server OS: Debian
* Game version: PE/Win10

### Plugins
- Test on a clean server without plugins: is the issue reproducible without any plugins loaded?

If the issue is **not** reproducible without plugins:
- Have you asked for help on our forums before creating an issue?
- Can you provide sample, *minimal* reproducing code for the issue? If so, paste it in the bottom section
- Paste your list of plugins here (use the 'plugins' command in PocketMine-MP)

### Crashdump, backtrace or other files

* ... https://youtu.be/CrkEG4SO7qA

EDITED : There is no errors and i don't know why this is happening

**Comment by dktapps** [comment]
"last" is not a valid version.

**Comment by Misteboss** [comment]
@dktapps fixed

**Comment by dktapps** [comment]
doesn't look fixed to me

**Comment by Misteboss** [comment]
now it is

**Comment by dktapps** [comment]
I don't see what the problem is. What are you expecting it to do? They apply absorption for 2 minutes and regeneration for 5 seconds.

**Comment by dktapps** [comment]
Never mind, reproduced the issue.

**Comment by Misteboss** [comment]
Sorry I hadnt seen the message, thanks for fix !
