### ISSUE TITLE
I can't craft Diamond blocks on W10

### ISSUE THREAD

**Issue by CookieCode** [pmmp/PocketMine-MP#1096]
### Issue description
I can't craft DIamond, Emerald, Gold, Iron, Redstone, Lapis blocks on windows 10....

### OS and versions

* PocketMine-MP: https://github.com/pmmp/PocketMine-MP/commit/eb05f2ecde72bbc844b86b3c8c24175e15376b96
* PHP:
* Server OS:
* Game version: Win10

### Plugins
Without plugins

### Crashdump, backtrace or other files
I don't have error console and Crash dump...

**Comment by dktapps** [comment]
does anyone ever search the issue tracker these days... #45
