### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by XDqrkneZ** [pmmp/PocketMine-MP#1097]
### Steps to reproduce the issue

1. ... give me many error so many times and people can't join the server but its still giving me error in the console
2. ...

### OS and versions

* PocketMine-MP:  PocketMine-MP 1.6.2dev 「Unleashed」 implementing API version 3.0.0-ALPHA6 for Minecraft: PE v1.1.0.55 (protocol version 113)
* PHP: 7.0.3
* Server OS: LINUX
* Game version: PE/Win10 (delete as appropriate)

### Plugins
- Test on a clean server without plugins: is the issue reproducible without any plugins loaded?
 I don't think its a plugin because "pd" is a world and not a plugin
If the issue is **not** reproducible without plugins:
- Have you asked for help on our forums before creating an issue?
- Can you provide sample, *minimal* reproducing code for the issue? If so, paste it in the bottom section
- Paste your list of plugins here (use the 'plugins' command in PocketMine-MP)

### Crashdump, backtrace or other files

* ...
error https://pastebin.com/4xc6QBGw

**Comment by MattWAnderson** [comment]
Is this running the latest build? If not try the latest version and try again.

**Comment by XDqrkneZ** [comment]
@mattwanderson it is the latest build because I just installed it like and hour ago before I posted this

**Comment by dktapps** [comment]
You're running a non-production branch, issues are to be expected.

Please **enable debug** and **paste a stack trace** (how many times have I said this now?)

**Comment by SuperMaXAleX** [comment]
To be correct, over 9999.

**Comment by dktapps** [comment]
Closing due to insufficient information provided.

> version should include Jenkins build number and/or git commit hash.
