### ISSUE TITLE
Building Terrain?

### ISSUE THREAD

**Issue by StormCraftMCPE** [pmmp/PocketMine-MP#1099]
building Terrain And No Play

**Comment by XDqrkneZ** [comment]
what is this?

**Comment by dktapps** [comment]
Without knowing your PocketMine-MP version, OS, PHP, Client version, or plugins and how the issue occurred, the issue cannot begin to be solved.
A pre-formatted template is provided that shows the required information to begin to find, test and solve an issue.
Until the adequate template and information is provided, the issue will be closed; it may be reopened if you update the ticket with the correct template and required information.

[Contribution guidelines](https://github.com/pmmp/PocketMine-MP/blob/master/CONTRIBUTING.md)
