### ISSUE TITLE
cheat max-players in Multicraft

### ISSUE THREAD

**Issue by iagomcs** [pmmp/PocketMine-MP#110]
#### Issue description
Customers can cheat the max-players limit in Multicraft. Isn't a Multicraft bug or problem, it don't happens in SpigotMC or Craftbukkit.

#### Steps to reproduce the issue
1. Start server in Multicraft.
2. Download server.proprierts via FTP.
3. Edit max-players option and upload to FTP.
4. use /reload command on console
Glitch done.

#### OS and versions

* Pocketmine-MP: Any
* PHP: Any
* Server OS: Any
* Game version:  Any

**Comment by dktapps** [comment]
Wow, our software reloads configuration correctly. Wow. This is a Multicraft issue. Go tell them to tighten their security.

**Comment by SOF3** [comment]
@iagomcs If you allow your users to upload plugins, plugins can change max-players easily. And this is impossible to prevent, because one can simply do anything he wants with plugins.
