### ISSUE TITLE
Chest damage returns the chest facing

### ISSUE THREAD

**Issue by matcracker** [pmmp/PocketMine-MP#1102]
### Issue description

I'm not sure if this is an issue or not but when you try to get the damage of a chest (so, `$block->getDamage()`) it returns the facing direction of chest instead of 0

### Steps to reproduce the issue

1. Place a chest.
2. Get its damage value

### OS and versions

* PocketMine-MP: api3/blocks [1458e3c](https://github.com/pmmp/PocketMine-MP/commit/1458e3cbad9692cf6598c298492d2bf2e9fb7770)
* PHP: 7.0.3
* Server OS: Win 10
* Game version: PE/Win10

### Plugins
- Test on a clean server without plugins: is the issue reproducible without any plugins loaded?
Yes

**Comment by dktapps** [comment]
Prefer using the forums to ask questions before making an issue. It's preferable you don't make issues until you've discussed it with someone and you are sure it is an issue. Until then, it is considered a support request and as such will be closed.
