### ISSUE TITLE
doesnt support my device when i tried to create it keep saying this error " [22:17:51] [Server thread/CRITICAL]: Running PocketMine-MP with 32-bit systems/PHP is no longer supported. Please upgrade to a 64-bit system or use a 64-bit PHP binary.  [PE Server] Server was stopped."  any chance of this issue to be fixed? i got android kernel version linux v3.18.19+ and my cpu is ARMv7 processor rev4 (v7l)

### ISSUE THREAD

**Issue by iChaoticSoldier** [pmmp/PocketMine-MP#1103]
### Steps to reproduce the issue

1. ...
2. ...

### OS and versions

* PocketMine-MP:
* PHP:
* Server OS:
* Game version: PE/Win10 (delete as appropriate)

### Plugins
- Test on a clean server without plugins: is the issue reproducible without any plugins loaded?

If the issue is **not** reproducible without plugins:
- Have you asked for help on our forums before creating an issue?
- Can you provide sample, *minimal* reproducing code for the issue? If so, paste it in the bottom section
- Paste your list of plugins here (use the 'plugins' command in PocketMine-MP)

### Crashdump, backtrace or other files

* ...

**Comment by Driesboy** [comment]
help me plz

**Comment by Muqsit** [comment]
The fix is...you just read the error.

**Comment by iChaoticSoldier** [comment]
i dont know how to fix it cuz i got no pc and i cant use 64bit
