### ISSUE TITLE
Teleportation issue

### ISSUE THREAD

**Issue by mal0ne-23** [pmmp/PocketMine-MP#1106]
### Issue description
[17:18:44] [Server thread/CRITICAL]: TypeError: "Argument 1 passed to pocketmine\Player::sendPosition() must be an instance of pocketmine\math\Vector3, null given, called in /home/data/other/src/pocketmine/Player.php on line 2147" (EXCEPTION) in "/home/data/other/src/pocketmine/Player" at line 3958
[17:18:44] [RakLibServer thread/NOTICE]: Blocked XX.XXX.XXX.XX for 5 seconds
[17:18:44] [Server thread/CRITICAL]: TypeError: "Argument 1 passed to pocketmine\Player::sendPosition() must be an instance of pocketmine\math\Vector3, null given, called in /home/data/other/src/pocketmine/Player.php on line 2147" (EXCEPTION) in "/home/data/other/src/pocketmine/Player" at line 3958

### Steps to reproduce the issue

1. Teleport a player to a position with a level specified.

### OS and versions

* PocketMine-MP: 5011198a4e8a8585bc493679231115e542e86ae1
* PHP: 7.0.idk
* Server OS: Linux
* Game version: Irrelevent

### Plugins
You cant teleport players to positions without plugins..?

PS: I looked through issues to see if this was a duplicate, didn't see anything similar. Don't ban me if it is a duplicate I'm sorry xd

**Comment by Muqsit** [comment]
Reproduced, I thought I was the only one..

**Comment by Sandertv** [comment]
I did report it actually, just in the wrong issue.

**Comment by Misteboss** [comment]
Confirmed and same as @Muqsit and @mal0ne-23  i thought i was the only one 😂

**Comment by AppleDevelops** [comment]
Had the same issue, I just worked around it.

**Comment by MattWAnderson** [comment]
Same issue here... figured it was just a plugin issue I had not been able to look at. Started with 1.1
2017-06-17 [00:18:51] [Server thread/CRITICAL]: TypeError: "Argument 1 passed to pocketmine\Player::sendPosition() must be an instance of pocketmine\math\Vector3, null given, called in /home/tcagame/pocketminers/15/src/pocketmine/Player.php on line 2147" (EXCEPTION) in "/src/pocketmine/Player" at line 3953

**Comment by SuperMaXAleX** [comment]
I have this issue too, and this is happening since this [https://github.com/pmmp/PocketMine-MP/commit/e83ffd5afe637982c6b5f9bb5b915fbb235703ad](update)

**Comment by dktapps** [comment]
stupid piece of shit of a delayed-teleport system... it's pathetic

**Comment by mal0ne-23** [comment]
Let's drop it completely!!! :D

**Comment by mal0ne-23** [comment]
Me: Hello, teleport?

PocketMine: Teleport machine broke.

Me: Understandable... Have a nice day.

**Comment by Muqsit** [comment]
Line number update. It's 2150 as of the current commit :3

**Comment by IrishPacks** [comment]
Also reproduced, I switched from Player::teleport() to Player::teleportImmediate() and I've noticed that this error doesn't show up anymore. Although Player::teleportImmediate() was a last resort for me, the chunks seemed to load way faster(maybe it's just the placebo effect :P)

**Comment by Muqsit** [comment]
@IrishPacks Maybe not. I noticed the chunks loading faster too. But timings loops pretty bad

**Comment by dktapps** [comment]
You're deluding yourselves.

**Comment by zKoz210** [comment]
@dktapps Ohh... So many errors with teleportation

```
Невозможно выполнить такт в мире "survival": Movement distance is excessive: dx=-4527.2759, dy=-639.5048, dz=152.3
AssertionError: "Movement distance is excessive: dx=-4527.2759, dy=-639.5048, dz=152.3" (E_ERROR) in "/src/pocketmine/entity/Entity" at line 1527
#0 /src/pocketmine/entity/Entity(1527): assert(boolean , string Movement distance is excessive: dx=-4527.2759, dy=-639.5048, dz=152.3)
#1 /src/pocketmine/Player(1547): pocketmine\entity\Entity->move(double -4527.2759, double -639.5048, double 152.3)
#2 /src/pocketmine/Player(1701): pocketmine\Player->processMovement(integer 1)
#3 /src/pocketmine/level/Level(720): pocketmine\Player->onUpdate(integer 5133)
#4 /src/pocketmine/Server(2272): pocketmine\level\Level->doTick(integer 5133)
#5 /src/pocketmine/Server(2424): pocketmine\Server->checkTickUpdates(integer 5133, double 1498046022.3997)
#6 /src/pocketmine/Server(2189): pocketmine\Server->tick(boolean)
#7 /src/pocketmine/Server(2072): pocketmine\Server->tickProcessor(boolean)
#8 /src/pocketmine/Server(1654): pocketmine\Server->start(boolean)
```

**Comment by dktapps** [comment]
Does anyone actually even think of searching the issue tracker before spamming?

**Comment by MrDoni98** [comment]
Maybe it's stupid, but.
At me this error has appeared at teleportation in PlayerMoveEvent, solved a problem at first having canceled event, and then having teleported the player
