### ISSUE TITLE
CrashDump 

### ISSUE THREAD

**Issue by DavidBrockway** [pmmp/PocketMine-MP#1109]
PocketMine-MP Crash Dump Fri Jun 16 17:44:32 +00 2017

Error: Argument 2 passed to pocketmine\nbt\tag\DoubleTag::__construct() must be of the type float, string given, called in phar://C:/Users/david/OneDrive/Documents/PocketMine-MP/PocketMine-MP.phar/src/pocketmine/entity/Entity.php on line 749
File: /src/pocketmine/nbt/tag/DoubleTag
Line: 38
Type: notice

Code:
[29] 
[30] class DoubleTag extends NamedTag{
[31] 
[32] 	/**
[33] 	 * DoubleTag constructor.
[34] 	 *
[35] 	 * @param string $name
[36] 	 * @param float  $value
[37] 	 */
[38] 	public function __construct(string $name = "", float $value = 0.0){
[39] 		parent::__construct($name, $value);
[40] 	}
[41] 
[42] 	public function getType(){
[43] 		return NBT::TAG_Double;
[44] 	}
[45] 
[46] 	public function read(NBT $nbt, bool $network = false){
[47] 		$this->value = $nbt->getDouble();
[48] 	}

Backtrace:
#0 /src/pocketmine/entity/Entity(749): pocketmine\nbt\tag\DoubleTag->__construct(string , string 542)
#1 /src/pocketmine/entity/Living(104): pocketmine\entity\Entity->saveNBT(boolean)
#2 /src/pocketmine/entity/Human(434): pocketmine\entity\Living->saveNBT(boolean)
#3 /src/pocketmine/Player(3739): pocketmine\entity\Human->saveNBT(boolean)
#4 /src/pocketmine/Server(2307): pocketmine\Player->save(boolean 1)
#5 /src/pocketmine/Server(2454): pocketmine\Server->doAutoSave(boolean)
#6 /src/pocketmine/Server(2190): pocketmine\Server->tick(boolean)
#7 /src/pocketmine/Server(2072): pocketmine\Server->tickProcessor(boolean)
#8 /src/pocketmine/Server(1654): pocketmine\Server->start(boolean)
#9 /src/pocketmine/PocketMine(504): pocketmine\Server->__construct(BaseClassLoader object, pocketmine\utils\MainLogger object, string phar://C:\Users\david\OneDrive\Documents\PocketMine-MP\PocketMine-MP.phar/, string C:\Users\david\OneDrive\Documents\PocketMine-MP\, string C:\Users\david\OneDrive\Documents\PocketMine-MP\plugins\)
#10 (1): require_once(string phar://C:/Users/david/OneDrive/Documents/PocketMine-MP/PocketMine-MP.phar/src/pocketmine/PocketMine.php)

PocketMine-MP version: 1.6.2dev #0 [Protocol 113; API 3.0.0-ALPHA5]
Git commit: 0000000000000000000000000000000000000000
uname -a: Windows NT DESKTOP-VB63TTU 10.0 build 15063 (Windows 10) AMD64
PHP Version: 7.0.18
Zend version: 3.0.0
OS : WINNT, win

Loaded plugins:
DevTools 1.11.2 by PocketMine Team for API(s) 2.0.0, 3.0.0-ALPHA1, 3.0.0-ALPHA2, 3.0.0-ALPHA3, 3.0.0-ALPHA4, 3.0.0-ALPHA5
mwvent_Spleef 1.7.0 by minecraftgenius76 for API(s) 1.12.0, 2.0.0, 3.0.0, 3.0.0-ALPHA1, 3.0.0-ALPHA2, 3.0.0-ALPHA3, 3.0.0-ALPHA4, 3.0.0-ALPHA5

----------------------REPORT THE DATA BELOW THIS LINE-----------------------

===BEGIN CRASH DUMP===
eNrtWm1v20iS/isNOcDac6LeZdkaODhPnOxkL4l9Y+VyuNHCaJEtiWOSzWE3LWsG+e/3VHWTohQ7
e7c7B+wB8ReL/VJd7/VUk7+3bJyq1rQ/Op+cDse9yaDdSqSxr4tCF63p7y27zTHdyrSNQ9Vqt1Jl
jFzR0GWxKlOVWTEQuTRGRcJqkevwXtk0ztR8ni3sfG7laj6/0uUiUTO5mk7v7kKdGVuUoT0+EWlp
rFgooZfCrpWgw8Qy0dK2BdbE2Uqs4geVtUUokwQnxJnI17KYdruvpt2PRhWmG8mHOOpeZ+qqwNLu
lQ6ZK9O9YVbeg5Xg/c3+U4eIdE0Rdnf8drEpttvua/6HFbnQmUgwIyajc0i+LJPkTZyQ6P9nPEBl
XWisWyuM+KCz3bl/czmWEset6fCs3bKFhMmmP7eOeuKrwh5DwJPp37Jd8LJpO2+e2k7j0eAEpx/1
nzvqXfyAdcf93ujgKDc/nztegpdGPqgPP8yOF1onSmZMdfAc1R/LVGbHo+FzRN2pTxMdfkH0JpFb
VRwPJ8PzZ+jxeU+TG31B7lYVDyA3GPYmB+TcQY5ORUT0mcz4WTKj8aGUbiZ4GenL0urbBjEmdfos
qf557xlSCPP7PSKTZ4kgWXyFyE2hQ+QKXexRO3uOWv/0WemMlYXdo3L+peXq0Doe954j1PTfH6RR
r5DpzDstI1UIvfhFhUg7zX2ljRMzn7+XcfZOr1aNVd7p6zwwn3MimM85E8znVSqg8PG5AEZvhv/B
o8sGNeG/j+I/uD1PylWcYdwFck8c96HIQv1axoW601mojg/l/qPz324FJb6T1l8/t1vqWyn6ohT9
78sBFOns25ouZWJUuxXqSJFaB+cghZXDHv6HFBKiJiDUo1VZZMQHmaoIA7/Twr7fMMD/ue1+9x09
DPlBfNfYXKtXFx1aMvJL6Pe4Wv6vuSxkWun4RYaDaP70YJ5NIcSLB5mUvGDiF3Tp4Ywfchwch2JZ
ZqGNobEn6hXTFxdi3pq32p6oo4nBXqd3wgKeMzkQlAVMse8pTKHtN518j+WjHi//TD+9akaDJxla
KTuDXx3zKaOhP6VQtiwygXoync4u/3znFMiURzvKY0/59EnKhZLRMShAwAU8lpIlfiq70cU9JGOT
u1Mn/tQXdh2b4GUlO+0LXoJBd/qxk+zMn//5G5r4hia+oYlvaOL/N5pot1YqU4VMqO5xpZm29siA
VdjWIKNipt857Qwi9YDBRRknUWvaQxEttNWhBoV+f9huyTzGymEHpSO4fHfz4+UYq1exxWDvf/iH
DYW8T+IF7emcdWig9Mx9irNIb1B+Z+Lq9e2/za5vgv/44XQ4m30UfRwpmC/RH/dOh+K4WtzvnYjL
91enIxCi9nHamoC//hkef0Mxr/h1s3fa0DlvP3yYYYAfNgAJNVwwpKor9TBDwJiG2uqhfY31+50B
hmRp17owVC52+hUzJVMyAivt59bAc9HQXn//cbD/ONx/HO0/jom0yiTqC2REXALjRCon+ILTMGf0
0l41B1JJcKgWBd68EwrIgDR1O7v8afaR/GKjFia2JPra2tzAYWHmdbnohDpteFq3pgEVphsgRnt3
mydKLRvK2x/f1+CEddJQILlyWMilhe/GpZmcNlQIhQ94/Z4u/wl0moaryel8voK887lhOZE5+f8N
/OpttlPxzfXt7NP1T++umkrOyiT5TE5I4E9ZVVTncfLtIApzVdhYkb8e3dRP4pXOlvFKEECeF/Ps
6E0Ri7+UqIanoj+ZDs+nw4H4l15PDHr9CS1ItY0u3lcanoqb18Lld5p0hwW5LuxF/7w/HNDgZg0G
gyQ29kIvlzQis0wDh6kgd3VYhutYPSjOWRc6Y0q53GQB5Q7FeO2if8qny0e/yVwMekwrSfQmWCbx
al3Td5tlFqdAcXsEU72oBkjTKRD9BZNZ6gL81GOeEFJkFOqifs4fcr87ipfLOCwTu73oMzVOk8Dt
gVHWIkmbCxpOIFYSkBNfAFgm0W7MKBU1llD3dHH1+s3lx3czGnUuFPxaqmLrj/RDBYpoxQ/97lAD
B+LRxXf8B5UAjAQEbfzGh1htggj6l9D5xRkNUSqr035nmybkFYIqLfUgcIgSwhBMJr8QUI7YL1bZ
kZitlVGiklYA+HMbqDM4lV2jSwjJzNwhxlmYlJFrAb/wR6J1q9OqjzykaeQSzYPGTGGIpFgAud+L
rS4LT0vESwGjxcuYT4C9CvhMsiXCH9SmJteN1FLCYkZsdPYnK2SeK1kI0lYKYalL3VLbSDDfyb1Z
q0yU+aqQEQh05hl5uCM2nWfiaLYuFDwbQ+AikdmqRHctqE1klfloMDGeEw368W+sVNr6aq1CL8X+
RjBQpUuVdTbxfZyrKJYdXay69AQgb+ydXt69vb2+Ox2eB4M72gc11oSmaNZUtkLHhoM+rRXpjvp7
g6QjIKWHKTBTITOTSOvaf69N5hR84JeybFJU9DhUYi2zKGEjpyDsAmZ3JDdMGDfr0qKoItTcZQMx
4xKECBNtVOTYuqSwFZQUGNC4yikeYin+nVweS9j1Az8zFZRKaePtGvskd8oApMKf4kwlPSFRGjgh
0i4cgaW7vHmLlSgQEelpNxGArQWY2pF/zUFW0YHEguJfwF3hEcTqYiu8H2G5D8l6dqeGo08xFK0z
uJSMIqA44zyP2CR4DnakKQvOeQL+tlCkDygdcE8mZA6+PBGu2zz2RyILn4C4Ow+pQFGmDWBNQsdT
zNLJH8p0QVh5KS7NNgtn0twL6moRQB2a/0jXPeSflZC0al1o5GS4BFabtuBkJXxSg8u2oYYUWjNU
dVktKDw0lpYZIoeWMO1bdhnIg+Aq9CMSsFVQAcRhV89q1kirjp23S4pQWkKR2Bax/RM0ZwveFSnK
/+yFB3vFMSSAncWANMIyBF7KKVOiaKVsXmw5Vv+c6AUUS+VXuGF4XxpbykmpWsnF1oIhcetY6fHh
sSHzukiHTJuYGWNlC6o6jk6lf8N6WQKs44dQBFiIyhI5ojrRmR/ClOy0Kw05NIUG6QznrJjJgBmb
it6cUwVnZbumC4t/cvYJynyFeaqm/xDzxuqcz/epqubHUzMCIeXuMytu6MyKpX5vMHJc3agi1lyO
KBYNHRhyQvbc1fHWx1FINRH5GK8IEA/KRRqncZ0hgSFCoTfKDs+p1akTSCjhDE+x7pbNueASDUTf
LpJdOqITrimFUIXj5Z0vF5PYHnBChbkKqRAaVgvx6nTs9tYCQJMqNzsxhz0vpzl5kiEv9dBJvZLF
AvYP0NQlDp1RhD2pVXYnYsXvEX4PYjeVWcklt8kF4EgJXzhpVznhwBm8N7i8ulxWuSHdeVlHXLt6
x0/wiLUuk6hmJEYG2WRixzr5rciZcwh4ivaSZRRHbzgSvsiN7Ctudy3UstBplWJpr58PmlmpYVMI
4U136ApP+E9jH4HfcF1m98bp+71Egi1TFJeMrlAqhEfSCAeSXYTsjiBf8XQ5RASTCwjflEibI8/e
lXYTh1aj3E8AyVGgpZV/ODp+2R8gKtefIERjoJyw3gWqg2iiLtpfJTXP/KVujdjgEYkrgAtp0XkQ
/pAEblH34EY+GXHcOTzqZ10OWqi6FLIKj5pZq5qheC+2lmi3RdBv+DCVPD42sBUryCbjU5dMdiWW
uwKqb5GzIWE3hh+0F4Oep474EY0P1HsBCAx/fXXzsY294GCBtLOJI7t2yZrDuiYfMPmpmHg8sEMK
hhXTWNoRlxHCaC2TZRfY3oGXSMG9/EE4UlBjShZuxGFdlBu0GvDo9SPFHKEfmbRdPNPB/kamI+A2
imONSvzHm+ymAgg7qE7YhzZtkOLnhNOzPPCPTSiGXk0typUzv/apUlCRKNih1aMKS4dxKOfQhU+n
njXkEQxd8nXeibOY2OizbNUKF4ufZJFRmm7spO7FJ2b37osJtEWEckHC7FamEpGZwqSWlFiUGX1i
QmEMcVIOaVCucjwdBxmzIF4GfmwHXwGmXoo+gShfMQkts/wVUmaJKGd6BD33vjZlsTz+NaKLXGJL
RER3FTrfASOR2VkQzTCnmKnrZjRQNHlq1WuoCkdzGoqklejkHlwXRb/q3p+mav4lJEeIK2mdViGO
e/dWgRcGhXAnLqcmRw/N5TXTYRLngnfCed5Dn6Ekz0n1QwWxTakohBEQhrrNBfqcewLkcbhmU1Gv
uoUDuM40YYskvNkr3d00VBQdmw2FNLkl+xl3hOtXjdMJIX6vE1MfyoRIMw2+/zB20TtZySw0AqK6
gdhrZVXV1wj2OuuaeF7qU19pfJ8Vgp7l7Oe3BG7LVOTwkoc44Q5vL1hDdI8oJJ4cJxEGIlALJQ1L
iWPQ88CBCpjDI+QTdJtB4x6EVK6yN1xBPNcB3VK2Jh9fSKMahx33kSefOKUtBpjoPzWhbNg54Zxt
VJMLDpYZUaaGujKpQl1y55GHOmXx1cXuToPqAPe+hJnJUDLZyK1xtD2dhqlcvfPZv8phXpkeBWek
++QQBbSrVXu3P0/ewHAbdplq5B1urxhiUMXhwlbJRlohJqn/RNzST0YM4ugnhg+Nrew5mXLXCgvl
SC3UkioU38NRJSP7ONqUEfh2roFDYEQkCXT04DammxNFnXi+rb42cPikxrZcPJbSWFY1K8uXtmWZ
8DJtbLINKKvFoYMX3I0XdDVjmflK0F80NcUOWBp6+U3RTDmQQEcFwA4tROqoLARcJuShOnP3Pg5i
1E6yr8nek6qUBehEfLPBmRQK9Vu9MzqNDSmN0xVoUObIqKqRl8JESXcI38E2asUVH+QzC+UTsrYr
OogXFOJUeLGEa+8rEMZbmiKLowAhdCRWBaraTim7+4NKL50vFePL0UbGfBX0a6lcfYTf+P2caXg8
MHCEqTj7u6jlOi8TT83/Jih0QHiecRIIclfa3CVywP5JnkntAZwpI0+rR/s+H1FdmwrXQ1TuQi9N
y3wqzl1j4Ryds5VDDp4WqEx6nLbdrTWIjl2lp4PqQR6T6SKmryx4ib/udVdBU5f96NYKllgLN+ow
nXdAFxmHwIFiJqB7xP2RukTsjQLJxNlS71xsrcmv+MhO41oZwJv5y3S2Tamb5Ogz0K+pGaX22E+L
3TQzzKBBrlaFWvk7qPp2j3oS+rzi/mlpHD9EzjzFD+nLhQmb+HA3fMLNTmuo5bHSruPgUZ037iVf
0dU035WqROdUh9tI7flatjEMQeg+2FYdABDMUhXowQJK0hmhL1rkEVxJRkLIN2gJ/8KrgexK9DnG
uixf5VNPjQzlpiv65kA3TsBOnqYApdp5fVqDAQ/niCItr2A4GYWqCZ3GmNjvqW43OzV5P9GkX6nw
q3DRVzS2nHdel32aiBXUrVPj0Yfr2espvYlwY5yuqOv1jZrPV3T9ik424nYlXtZ00K5Cih0QayBs
Juczc9VJogoBBDgNvX6UBLfcA4Fs8OdNNK1sxVPICHRrNRU/M+hF6W/zNdZfiaIrQxX+ar75YAno
aq2glwd8gVK9YOIu5akyzkiYsYXhhow0l8IuMRj1wKvBOp/KDPAvQe+jKL9x7d2dNhVv3l3OpoPv
J+3x+WO/PXwctgff97+PgI9caj+2hcID0vDFWc9VAPc0Gp/wiyb+Io4Uwm/DXwEENF+wL0KAxHVz
hF4/ZJEs9sb8p4z1ALlv83kZJwjn5sga2YjfD9Pb3Rg2f2jO/mL82+MRz6dhsc1tc8HtzbvmYx7u
s/2TWvobkeaocX3u3hBwF4SJmmPp1vya8HcF/pcY09QgQMSLgF61jnuj3gQ/X7yFURbjcHzeO41G
44GiX5PhQJ4PF71xfzk8G0xUbzAZnS/OhuIFaFt9rzIUsz1d/Bbn7mODYYc+t/jNfTtRT+PxkV8B
7tSrUzwOer1hvz+gDyhvrq6b8/C5zJi9LbfcgPzn+z21HZDdRNHjwTTdFewzi8FNER9Y8xM6mII+
CWj1OsMOvYMPyyL5Qqlxc+RmzU5Eb/rpHT5NWzVkEpPAfaZiuDqYPToL93qsObaVLEf1zUDuLxf5
w5B+55S40eldpC1KTHPfas/sq3Tv05L/ojp9fcM4YTf++fN/A1AaXQI=
===END CRASH DUMP===

**Comment by Muqsit** [comment]
don't use old plugins, [especially](https://twitter.com/muqsitrayyan/status/869571143711301634?s=09) mcg67's

**Comment by dktapps** [comment]
bad plugin setting entity position to strings... naughty!
