### ISSUE TITLE
please add this button in pocketmine.yml

### ISSUE THREAD

**Issue by SuperAdam47** [pmmp/PocketMine-MP#1111]
#This setting allows the server to load plugins with Incompatible API
  #Recommanded that it stays "false"
  load-incompatible-api: true

**Comment by TheDiamondYT1** [comment]
I **don't** support this. The API version is there for a reason. Loading incompatible plugin can cause unexpected crashes, which people report to this issue tracker, which annoys @dktapps and there's just no need. if you *really* want to load incompatible plugins, use http://pmt.mcpe.fun.

**Comment by Tee7even** [comment]
They simply won't work. Most likely.

**Comment by SOF3** [comment]
If a user has the knowledge to know all the effects of loading an incompatible plugin, he should have the knowledge to bypass this check himself.
If he can't, this means he doesn't know enough and
