### ISSUE TITLE
Grass doesn't spread to nearby dirt blocks

### ISSUE THREAD

**Issue by joeybab3** [pmmp/PocketMine-MP#1112]
### Issue description
I have afk'ed for about 2 hours now after placing down a bunch of dirt but it doesn't appear grass is spreading to the dirt blocks...

### Steps to reproduce the issue
1. Place dirt near grass
2. Grass doesn't grow...

### OS and versions
* PocketMine-MP: 1.6.2 dev build 977
* PHP: 7.0.3
* Server OS: Windows 8.1
* Game version: PE

### Plugins
None

**Comment by joeybab3** [comment]
![screenshot_20170618-160358](https://user-images.githubusercontent.com/2829457/27264944-f46e9080-543f-11e7-94da-f878abca1a7f.png)

**Comment by joeybab3** [comment]
It's worth noting this is completely unmodified, I didn't add it to the disable-block-ticking or change any of those settings.

**Comment by Muqsit** [comment]
Wait really? It works for me..

**Comment by TheDiamondYT1** [comment]
@Muqsit You can disable it in `pocketmine.yml` afaik

**Comment by joeybab3** [comment]
@TheDiamondYT1 yes, but I haven't done that. Muqsit, what build are you on?

**Comment by dktapps** [comment]
#436

**Comment by joeybab3** [comment]
So just for the record I read through every linked issue but couldn't find what you intended with linking it. It seems that there is not yet a working skylight implementation, and by extension no grass spread?

**Comment by madecode15** [comment]
@joeybab3 Can you read?

#436

> Grass is abundant, and its ticking method is not well optimized, and nor does it work correctly.

Grass ticking is how grass spreads -.-

**Comment by TheDiamondYT1** [comment]
@joeybab3

> its ticking method is not well optimized, and nor does it work correctly

I found that in 2 seconds after clicking the linked issue. Wasnt hard.

**Comment by joeybab3** [comment]
@madecode15 @TheDiamondYT1 
> dktapps commented on Mar 17
Thank you for your concern about whether I can read or not, and as it turns out I can! However I wasn't sure if this was still valid as that issue is over 3 months old. @Muqsit mentioned that it works for him so I was just trying to confirm whether it worked in some cases or not. No need for the hostility.
