### ISSUE TITLE
FloatingTextParticle

### ISSUE THREAD

**Issue by SerezhaIvanov** [pmmp/PocketMine-MP#1117]
### Issue description

Hi, I have a problem with the flying text, when I create the text for some reason they merge into one.

### Steps to reproduce the issue

Use my code:
`        $this->pg->getServer()->getDefaultLevel()->addParticle(new FloatingTextParticle(new Vector3(282 + 0.5, 78, 173 + 0.5), "", "§3-x-"), [$event->getPlayer()]);
        $this->pg->getServer()->getDefaultLevel()->addParticle(new FloatingTextParticle(new Vector3(282 + 0.5, 77 + 0.75, 173 + 0.5), "", "§3-x§6 Кальян§3 x-"), [$event->getPlayer()]);
        $this->pg->getServer()->getDefaultLevel()->addParticle(new FloatingTextParticle(new Vector3(282 + 0.5, 77 + 0.50, 173 + 0.5), "", "§3-x§e Чтобы затянуться, нажми по"), [$event->getPlayer()]);
        $this->pg->getServer()->getDefaultLevel()->addParticle(new FloatingTextParticle(new Vector3(282 + 0.5, 77 + 0.25, 173 + 0.5), "", "§3-x§e кальяну§7 (варочной стойке)§3 x-"), [$event->getPlayer()]);
        $this->pg->getServer()->getDefaultLevel()->addParticle(new FloatingTextParticle(new Vector3(282 + 0.5, 77, 173 + 0.5), "", "§3-x-"), [$event->getPlayer()]);`

### OS and versions

* PocketMine-MP: 1.6.2dev
* PHP: 7
* Server OS: ubuntu
* Game version: PE

### Plugins

[20:42:52] [Server thread/INFO]: Плагины (20): DevTools v1.11.3, Casino_by_SerezhaIvanov v1, Warn_by_SerezhaIvanov v1, WorldEdit+ v0
01, AutoMine v1, ManyWorlds v2.1.0, Bosses v1, TicTacToe v1.0.0, WorldGuardian v2.0, PurePerms v1.4.0-INDEV, ColoringRod v2, images
1, Economy v1, PotionShop v1, Quests v1, ChestShop v3, Clans v1.3.7, Chat v1, DonateCases v4.8, API v1
### Crashdump, backtrace or other files

No errors

**Comment by dktapps** [comment]
This is not a support forum. Use the [forums](https://forums.pmmp.io) for questions.

**Comment by SuperMaXAleX** [comment]
How many times did you say this sentence?
