### ISSUE TITLE
Undefined offset: 0

### ISSUE THREAD

**Issue by Obamavn99** [pmmp/PocketMine-MP#1123]
### Steps to reproduce the issue

i have this problem when player join my server
 [Server thread/CRITICAL]: ErrorException: "Undefined offset: 0" (EXCEPTION) in "/src/pocketmine/Player" at line 3029
[09:08:13] [RakLibServer thread/NOTICE]: Blocked 189.234.178.217 for 5 seconds

### OS and versions

* PocketMine-MP:
* PHP:
* Server OS:
* Game version: PE/Win10 (delete as appropriate)

### Plugins
- Test on a clean server without plugins: is the issue reproducible without any plugins loaded?

If the issue is **not** reproducible without plugins:
- Have you asked for help on our forums before creating an issue?
- Can you provide sample, *minimal* reproducing code for the issue? If so, paste it in the bottom section
- Paste your list of plugins here (use the 'plugins' command in PocketMine-MP)

### Crashdump, backtrace or other files

* ...

**Comment by SuperMaXAleX** [comment]
#45 Before open an issue, read the others ones. Stop spamming.
