### ISSUE TITLE
Event priority detection is not working

### ISSUE THREAD

**Issue by intagaming** [pmmp/PocketMine-MP#1126]
### Issue description

My HIGHEST event still runs after the HIGH event.

### Steps to reproduce the issue

1. Look at the regex at this line: https://github.com/pmmp/PocketMine-MP/blob/master/src/pocketmine/plugin/PluginManager.php#L721
2. Go to http://www.phpliveregex.com , and type it in the regex
3. The priority is not detected with this string:
```
/**
* @param PlayerChatEvent $e
* @priority HIGHEST
*/
```

### OS and versions

* PocketMine-MP: 89ca2ac
* PHP: 7.0.9
* Server OS:
* Game version: PE/Win10

### Plugins
- Test on a clean server without plugins: is the issue reproducible without any plugins loaded?  - No

If the issue is **not** reproducible without plugins:
- Have you asked for help on our forums before creating an issue?  - Yes, they made this facepalm though
- Can you provide sample, *minimal* reproducing code for the issue? If so, paste it in the bottom section  - Fine
- Paste your list of plugins here (use the 'plugins' command in PocketMine-MP)  - It is just 2 functions then.

### Crashdump, backtrace or other files

![image](https://user-images.githubusercontent.com/16471365/27441555-138df748-5798-11e7-8ce6-235a5dce7a2f.png)

* ...

**Comment by dktapps** [comment]
Your doc-comment formatting is wrong. It expects spaces before the `*`.

**Comment by intagaming** [comment]
@dktapps Even I debug the getDocComment() to input to the site it still not working, please help me..

**Comment by intagaming** [comment]
@dktapps Can you just test it for me and give me the screenshot please?
https://github.com/PurePlugins/PureChat/blob/master/src/_64FF00/PureChat/PCListener.php#L68

**Comment by intagaming** [comment]
@dktapps Why can't I get an answer though? Is that so dumb to ask a question? Is my question doesn't meet your requirement to be answered?

**Comment by dktapps** [comment]
There's nothing wrong with it. Your code is wrong. https://regex101.com/r/Dh6jSP/1
