### ISSUE TITLE
How to fix this bug ?

### ISSUE THREAD

**Issue by SuperAdam47** [pmmp/PocketMine-MP#1128]
![screenshot_20170623-073217](https://user-images.githubusercontent.com/16169771/27466850-4c5a690a-57e6-11e7-88d5-3e3d9b8da315.png)

**Comment by SuperAdam47** [comment]
Please help @dktapps

**Comment by Driesboy** [comment]
How you run this on android ANDROID IS 32BIT

**Comment by SuperAdam47** [comment]
Server running on linux

**Comment by Sandertv** [comment]
The issue template is there for a reason. Providing insufficient information will very likely get your issue closed.
