### ISSUE TITLE
FooooooBAR

### ISSUE THREAD

**Issue by Humerus** [pmmp/PocketMine-MP#113]
### Issue description

Write a short description about the issue
FOOOBAR!
### Steps to reproduce the issue

1. ...
2. ...
HI FOOBAR
### OS and versions

* PocketMine-MP:
* PHP:
* Server OS:
* Game version: PE/Win10 (delete as appropriate)

### Crashdump, backtrace or other files

* ...

**Comment by dktapps** [comment]
😂
