### ISSUE TITLE
Uncaught ErrorException: Constant pocketmine\PATH already defined

### ISSUE THREAD

**Issue by Aericio** [pmmp/PocketMine-MP#1130]
### Issue description

I am trying to startup the server but it keeps telling me `Fatal error: Uncaught ErrorException...`
1003 to 1011 builds worked fine, but any builds after that gave me that error.  I also downloaded 7.0.3 x64 binaries from bintray, same result. Fresh installation for each test. Build 1012 was when it stopped working after this commit https://github.com/pmmp/PocketMine-MP/commit/4b4f2af9e3dff37beb01e75dad449e459d959118. 7.0.20 bins from [this](https://forums.pmmp.io/threads/pocketmine-mp-1-6-2-installer-windows.2022/) installer, but same result using 7.0.3 binaries so I don't think it's the bins problem.

### Steps to reproduce the issue
1. Replace phar with 1018.
2. Start server.

### OS and versions
* PocketMine-MP: 1012-1018
* PHP: 7.0.20 x64
* Server OS: Windows 10
* Game version: unknown

### Crashdump, backtrace or other files
```
Fatal error: Uncaught ErrorException: Constant pocketmine\PATH already defined in phar://C:/Users/aericio/Desktop/Minecraft PE/PocketMine-MP.phar/src/pocketmine/PocketMine.php:121
Stack trace:
#0 [internal function]: pocketmine\{closure}(8, 'Constant pocket...', 'phar://C:/Users...', 121, Array)
#1 phar://C:/Users/aericio/Desktop/Minecraft PE/PocketMine-MP.phar/src/pocketmine/PocketMine.php(121): define('pocketmine\\PATH', 'phar://C:/Users...')
#2 C:\Users\aericio\Desktop\Minecraft PE\PocketMine-MP.phar(1): require_once('phar://C:/Users...')
#3 {main}
  thrown in phar://C:/Users/aericio/Desktop/Minecraft PE/PocketMine-MP.phar/src/pocketmine/PocketMine.php on line 121
bin\php\php.exe: Exit 255.
```

**Comment by dktapps** [comment]
This was caused by a bug in Poggit which was copied from DevTools.

**Comment by dktapps** [comment]
Prefer using Jenkins builds, we don't actually offer Poggit as a primary build source. The auto-updater will also not work correctly with Poggit builds.

**Comment by Aericio** [comment]
Thanks, Jenkins build works fine.

**Comment by dktapps** [comment]
Bumped Poggit, build 1023 has the issue fixed. The bugfix went in after the most recent commit, so there was no new build without the bug.
