### ISSUE TITLE
/effect values are switched

### ISSUE THREAD

**Issue by Aericio** [pmmp/PocketMine-MP#1131]
### Issue description
Name and seconds values are switched in /effect.

Expected result: doing `/effect (name) (effect) (level) (seconds)` should say `Gave (effect) * (level) to (name) for (seconds) seconds`
Actual result: (go bottom)

### Steps to reproduce the issue

1. Use /effect

### OS and versions
* PocketMine-MP: 1018
* PHP: 7.0.20
* Server OS: Windows 10
* Game version: Win10

### Plugins
- DevTools v1.12.0

### Crashdump, backtrace or other files

![image](https://user-images.githubusercontent.com/16523741/27504842-e02641da-582d-11e7-8638-5e2ae6bce47d.png)
Other users that see you using that command is correct though.
![image](https://user-images.githubusercontent.com/16523741/27504853-1c3b109c-582e-11e7-8a32-93c19965a865.png)

**Comment by AppleDevelops** [comment]
https://github.com/pmmp/PocketMine-MP/issues/207

**Comment by dktapps** [comment]
pmmp/PocketMine-Language#19

(the issue tracker on that repo was disabled for a time, so you wouldn't have seen it)
