### ISSUE TITLE
getFloorY()

### ISSUE THREAD

**Issue by Driesboy** [pmmp/PocketMine-MP#1132]
### Steps to reproduce the issue

1. ...use $ev->getTo()->getFloorY() < 3
2. ...

### OS and versions

* PocketMine-MP: https://poggit.pmmp.io/ci/pmmp/PocketMine-MP/~/dev:1025
* PHP:7.0.3
* Server OS:Windows 7
* Game version: PE/Win10

### Plugins
- Test on a clean server without plugins: is the issue reproducible without any plugins loaded?

If the issue is **not** reproducible without plugins:
- Have you asked for help on our forums before creating an issue?
- Can you provide sample, *minimal* reproducing code for the issue? If so, paste it in the bottom section
- Paste your list of plugins here (use the 'plugins' command in PocketMine-MP)

### Crashdump, backtrace or other files

* ...

**Comment by TheDiamondYT1** [comment]
*This issue is invalid.*

Please specify what the actual issue *is*, and not just giving us steps to reproduce.

**Comment by dktapps** [comment]
he hasn't even provided that.

**Comment by TheDiamondYT1** [comment]
@dktapps

> ...use $ev->getTo()->getFloorY() < 3

**Comment by dktapps** [comment]
I have no idea what event he's talking about or under what circumstances the bug occurred. This issue is therefore useless.
