### ISSUE TITLE
getFloorY()

### ISSUE THREAD

**Issue by Driesboy** [pmmp/PocketMine-MP#1133]
### Steps to reproduce the issue

1. ...use $ev->getTo()->getFloorY() in a plugin
2. ...go to that place

### OS and versions

* PocketMine-MP: https://poggit.pmmp.io/ci/pmmp/PocketMine-MP/~/dev:1025
* PHP:7.0.3
* Server OS:Windows 7
* Game version: PE/Win10

### Plugins
- Test on a clean server without plugins: is the issue reproducible without any plugins loaded?

If the issue is **not** reproducible without plugins:
- Have you asked for help on our forums before creating an issue?
- Can you provide sample, *minimal* reproducing code for the issue? If so, paste it in the bottom section
- Paste your list of plugins here (use the 'plugins' command in PocketMine-MP)

### Crashdump, backtrace or other files

`[Server thread/CRITICAL]: TypeError: "Argument 1 passed to pocketmine\utils\BinaryStream::putLFloat() must be of the type float, string given, called in C:\Users\PC\Desktop\GameCraftPE\Skywars\src\pocketmine\network\mcpe\protocol\DataPacket.php on line 354" (EXCEPTION) in "src/pocketmine/utils/BinaryStream" at line 188`
* ...

**Comment by Driesboy** [comment]
sorry i forgot to paste the error ;)

**Comment by dktapps** [comment]
you also didn't answer any part of the Plugins section.

**Comment by dktapps** [comment]
This is not a plugin development support forum. 

1. read the template
2. use our forums, since that is what they are for.

**Comment by TheDiamondYT1** [comment]
Also use the handy edit button instead of creating new issues.
