### ISSUE TITLE
Infinite generation of the world

### ISSUE THREAD

**Issue by Misteboss** [pmmp/PocketMine-MP#1135]
### Issue description

After 15~20 mind it’s impossible to join my server, when you join you stay blocked in generation of the world.
Tested with 10 differents player, we all stayed blocked in generation of the world.
I checked the console during this issue, the server detects them but isn’t doing anyhing.
I don’t have any errors.

### Steps to reproduce the issue

1. ... Start your server, let run him 25~30 mins.
2. ... Try to join it.

### OS and versions

* PocketMine-MP: last commit of api3\blocks
* PHP: 7.0.2
* Server OS: Debian
* Game version: PE/Win10 (the two)

### Crashdump, backtrace or other files

* ...

**Comment by dktapps** [comment]
How many times do I have to say that "last" is not a valid version?

**Comment by TheDiamondYT1** [comment]
https://github.com/pmmp/PocketMine-MP/commit/e6c1713bee77c26801d04cdeab99a5f10b97ff67

**Comment by Misteboss** [comment]
@dktapps fixed

**Comment by dktapps** [comment]
I don't have half an hour to spend debugging somebody else's issue. I suggest you try and find the cause of this yourself.

**Comment by Misteboss** [comment]
OK let's try but when you don't have any erros..
