### ISSUE TITLE
disable anti fly?

### ISSUE THREAD

**Issue by XDqrkneZ** [pmmp/PocketMine-MP#1136]
### Steps to reproduce the issue

1. ... remove anti fly
2. ... I want it remove because its ruining my minigame server,

### OS and versions

* PocketMine-MP:  PocketMine-MP 1.6.2dev-204 「Unleashed」 implementing API version 3.0.0-ALPHA5 for Minecraft: PE v1.1.0.55 (protocol version 113)
* PHP: 7.0.3
* Server OS: LINUX
* Game version: PE/Win10 (delete as appropriate)

### Plugins
- Test on a clean server without plugins: is the issue reproducible without any plugins loaded?

If the issue is **not** reproducible without plugins:
- Have you asked for help on our forums before creating an issue?
- Can you provide sample, *minimal* reproducing code for the issue? If so, paste it in the bottom section
- Paste your list of plugins here (use the 'plugins' command in PocketMine-MP)

### Crashdump, backtrace or other files

* ...

**Comment by jojoe77777** [comment]
`allow-flight` in server.properties
