### ISSUE TITLE
Remote server on Win10 can't be connected to by Win10 clients

### ISSUE THREAD

**Issue by bc3tech** [pmmp/PocketMine-MP#114]
### Issue description
I've got a server hosted on the web that is running Windows 10. I have installed PM 1.4.1 and it launches and is "ready" w/o any (perceived) issues. However, when I try to connect to the server with the Windows 10 Pocket Edition Beta, it never connects to the server. In the server list, "locating..." just sits there and never resolves, and when I try to connect anyway it says "locating server..." and then goes to a blank screen w/ the brick background; never loading the actual terrain/world.

### Steps to reproduce the issue

1. Install v1.4.1 on a **remote** Windows 10 PC
2. Attempt to connect to the server with Windows 10 Pocket Edition Beta

### OS and versions

* PocketMine-MP: `PocketMine-MP version 1.4.1-980 「絶好(Zekkou)ケーキ(Cake)」 (Implementing API version 1.11.0 for Minecraft: PE v0.10.5 alpha protocol version 20)`
* PHP: (from what i can tell this is embedded on PMMP for Windows in a `php` subfolder)
```
PS C:\Users\bc3tech\Downloads\PocketMine-MP\bin\php> .\php.exe -version
PHP 5.6.6 (cli) (built: Feb 18 2015 16:02:19)
Copyright (c) 1997-2015 The PHP Group
Zend Engine v2.6.0, Copyright (c) 1998-2015 Zend Technologies
    with Zend OPcache v7.0.4-dev, Copyright (c) 1999-2015, by Zend Technologies
    with Xdebug v2.2.6, Copyright (c) 2002-2014, by Derick Rethans
```
* OS: Windows 10.14393.447

### Crashdump, backtrace or other files
```
12:43:46 [INFO] Starting Minecraft: PE server version v0.10.5 alpha
12:43:46 [INFO] Loading pocketmine.yml...
12:43:46 [INFO] Loading server properties...
12:43:46 [INFO] Starting remote control listener
12:43:46 [INFO] RCON running on 0.0.0.0:19132
12:43:46 [INFO] Starting Minecraft PE server on 0.0.0.0:19132
12:43:46 [INFO] This server is running PocketMine-MP version 1.4.1-980 "絶好(Zekkou)ケーキ(Cake)" (API 1.11.0)
12:43:46 [INFO] PocketMine-MP is distributed under the LGPL License
12:43:48 [INFO] Preparing level "world"
12:43:48 [INFO] Starting GS4 status listener
12:43:48 [INFO] Setting query port to 19132
12:43:48 [INFO] Query running on 0.0.0.0:19132
12:43:48 [INFO] Default game type: CREATIVE
12:43:48 [INFO] Done (3.321s)! For help, type "help" or "?"
```
![](http://content.screencast.com/users/bc3tech/folders/Snagit/media/ae5d3e7e-1618-4212-acdc-d30be423b303/11.18.2016-13.39.png)

When I then close Minecraft (because there's no way out of the blank screen) the server will report
```
12:41:04 [INFO] [/xx.xxx.xx.xxx:19132] logged out due to timeout
```
after a few seconds

I have opened the port range 19130-19140 on the server's NAT and am forwarding it on. For proof I can RCON in to the server on 19132 just fine:
![](http://content.screencast.com/users/bc3tech/folders/Snagit/media/bc238a52-bc87-4f70-a8c2-55be7e0dc847/11.18.2016-13.47.png)

If you guys need anything else to troubleshoot/help me out just LMK and I'll do my best to get it.

Thanks!

**Comment by robske110** [comment]
I quote 

> for Minecraft: PE **v0.10.5** alpha protocol version 20)

Please read the instructions here https://pmmp.gq/get.html to update your installation.
Close this issue.

**Comment by robske110** [comment]
If you need further help please open a thread at: https://forums.pmmp.gq/

**Comment by bc3tech** [comment]
I quote
>Instructions below were written with Linux in mind
So those instructions are pointless and the [installer downloaded from the website](https://www.pocketmine.net/#windows-install) doesn't work OOB, yes?

**Comment by bc3tech** [comment]
@robske110 i can't open a thread because my acct has to be manually approved; i'm still waiting.

**Comment by ebmarquez** [comment]
@robske110 I get the exact some symptoms on a reaspberrypi.

**Comment by robske110** [comment]
Please open a thread on the [Forums](https://forums.pmmp.gq/). You did install a way outdated version.

Also, to my knowledge a reaspberrypi does not exist :P

**Comment by brandonh-msft** [comment]
i did start a thread on the forums.

and i installed the newest *Windows* version available at the time.

**Comment by bc3tech** [comment]
I did create a [thread ](https://forums.pmmp.gq/threads/remote-server-on-win10-cant-be-connected-to-by-win10-clients.91/#post-1201) on the forums.

Also, I installed the latest *Windows* version available at the time.
