### ISSUE TITLE
Add isFslling

### ISSUE THREAD

**Issue by xXSirGamesXx** [pmmp/PocketMine-MP#1142]
### Steps to reproduce the issue

1. ...Use an anti cheat plugin
2. ... Fall from an area and it'll kick you

### OS and versions

* PocketMine-MP: 1.6.2 (Unleashed)
* PHP: 7.0.18
* Server OS: Windows 10
* Game version: PE

### Crashdump, backtrace or other files

* ...i think in pocketmine\Player.php there should be a function isFalling() to test whether the player is falling or not.

**Comment by TheDiamondYT1** [comment]
```php
/** @var Player $player */
if(!$player->onGround) {
    // not on ground
}
```
/close

**Comment by xXSirGamesXx** [comment]
For some anticheat plugins that wouldnt work bc they use getInAirTicks. So it wouldnt work.

**Comment by KnownUnown** [comment]
This is a plugin issue to be solved by the anti-cheat plugins. Why? What constitutes as "falling" is heavily subjective and does not belong in the core. How would you calculate "falling"? How will you differentiate it from flying? How will you differentiate that from client lag? How will this function be better than an anti-cheat plugin's implementation of their own, using getInAirTicks as they want to?
