### ISSUE TITLE
sendHeldItem

### ISSUE THREAD

**Issue by LewBr** [pmmp/PocketMine-MP#1148]
### Issue description
Bug on HeldItem send..

### Steps to reproduce the issue

1. 28.06 13:41:55 [Server] Server thread/CRITICAL Error: "Call to a member function sendHeldItem() on null" (EXCEPTION) in "src/pocketmine/Player" at line 2499

### OS and versions

* PocketMine-MP: This server is running PocketMine-MP 1.6.2dev-243 「Unleashed」 implementing API version 3.0.0-ALPHA6 for Minecraft: PE v1.1.0.55 (protocol version 113)
* PHP: 7
* Server OS: MultiCraft
* Game version: Win10

### Code
- $item = $player->getInventory()->getItemInHand();

If the issue is **not** reproducible without plugins:
- Have you asked for help on our forums before creating an issue?
- Can you provide sample, *minimal* reproducing code for the issue? If so, paste it in the bottom section
- Paste your list of plugins here (use the 'plugins' command in PocketMine-MP)

### Crashdump, backtrace or other files

* 28.06 13:41:55 [Server] Server thread/CRITICAL Error: "Call to a member function sendHeldItem() on null" (EXCEPTION) in "src/pocketmine/Player" at line 2499

**Comment by dktapps** [comment]
This is not a plugin support forum. Use the [forums](https://forums.pmmp.io) for development help.

**Comment by LewBr** [comment]
This is not a error from my Plugin wtf..

**Comment by LewBr** [comment]
28.06 13:41:55 [Server] Server thread/CRITICAL Error: "Call to a member function sendHeldItem() on null" (EXCEPTION) in "src/pocketmine/Player" at line 2499
