### ISSUE TITLE
[API3/Blocks] Update blocks in inventory

### ISSUE THREAD

**Issue by madecode15** [pmmp/PocketMine-MP#1149]
Type "1" in search.
<img width="625" alt="capture" src="https://user-images.githubusercontent.com/25398804/27679265-2c728ed4-5c86-11e7-9f90-8ed8c6c76d89.PNG">

Version: https://github.com/pmmp/PocketMine-MP/commit/347994a6e65abe48de99c5266f2e5e681ac78d1a

**Comment by dktapps** [comment]
the inventory data on that branch is for 1.1.3.
