### ISSUE TITLE
Backgrounding app doesn't disconnect

### ISSUE THREAD

**Issue by daterrell** [pmmp/PocketMine-MP#115]
### Issue description
Backgrounding Minecraft disconnects from the server, but client remains active

### Steps to reproduce the issue
1. Join server
2. Background app (hit home button)
3. Notice disconnection on console
4. Re-aunch Minecraft
5. Tap Resume Game button

### OS and versions
* PocketMine-MP: PocketMine-MP 1.6.1dev 「Unleashed (source 8ced6547f20a1510d823dc316febe87bf7837a94)
* PHP: PHP 7.0.3 (cli) (built: Feb  2 2016 14:41:12) ( ZTS )
* Server OS: Windows 10 Home
* Game version: PE/iOS 10

### Crashdump, backtrace or other files
* ...

**Comment by robske110** [comment]
This is not a pocketmine issue, the server simply recieved no packet in over 30s, and closes the connection to the client. The client weirdly doesn't notice this, it should timout.

**Comment by daterrell** [comment]
That's too bad. Gotta wait on Mojang 👍🏼
