### ISSUE TITLE
PocketMine-MP.phar is broken.

### ISSUE THREAD

**Issue by CodyTronHD** [pmmp/PocketMine-MP#1154]
### Issue description

I was setting up PocketMine and all of sudden this message pops up:
Fatal error: Cannot use pocketmine\nbt\tag\Float as Float because 'Float' is a special class name in phar:///Users/CodyTran/Documents/PocketminePE/PocketMine-MP.phar/src/pocketmine/Server.php on line 71
### Steps to reproduce the issue

1. ...
2. ...

### OS and versions

* PocketMine-MP:(I don't Know)
* PHP:7
* Server OS:
* Game version: PE

### Plugins
- Test on a clean server without plugins: is the issue reproducible without any plugins loaded?

If the issue is **not** reproducible without plugins:
- Have you asked for help on our forums before creating an issue?
- Can you provide sample, *minimal* reproducing code for the issue? If so, paste it in the bottom section
- Paste your list of plugins here (use the 'plugins' command in PocketMine-MP)

### Crashdump, backtrace or other files

* ...

**Comment by SuperMaXAleX** [comment]
*facepalm*

**Comment by CodyTronHD** [comment]
Im sorry mate but I'm a noob
