### ISSUE TITLE
Creative Inventory Glitch

### ISSUE THREAD

**Issue by playzydoesgames** [pmmp/PocketMine-MP#1155]
Everytime i try to get an item from the creative inventory it just flashes in my hotbar then goes and i cant place anything in creative unless from the survival inventory please fix ive restarted the server and reloged please fix im using win10 but its effecting all the players

**Comment by dktapps** [comment]
Without knowing your PocketMine-MP version, OS, PHP, Client version, or plugins and how the issue occurred, the issue cannot begin to be solved.
A pre-formatted template is provided that shows the required information to begin to find, test and solve an issue.
Until the adequate template and information is provided, the issue will be closed; it may be reopened if you update the ticket with the correct template and required information.

[Contribution guidelines](https://github.com/pmmp/PocketMine-MP/blob/master/CONTRIBUTING.md)
