### ISSUE TITLE
Creative inventory Bug

### ISSUE THREAD

**Issue by playzydoesgames** [pmmp/PocketMine-MP#1157]
### Issue description
Everytime i try to get a item from creative inventory it appears in my hotbar for half a second then disapears, it happens too all my players and i dont think its lagg as everything else runs smothly, plz help

 Expected it to work normally but it did not

### Steps to reproduce the issue

1. ... Join The server
2. ... switch to creative mode and try obtain any item or block

### OS and versions

* PocketMine-MP: 1.6.2
* PHP: 7
* Server OS: Win10
* Game version: PE/Win10 (delete as appropriate)

### Plugins
- Test on a clean server without plugins: is the issue reproducible without any plugins loaded? Unsure but i think so 

If the issue is **not** reproducible without plugins:
- Have you asked for help on our forums before creating an issue?
- Can you provide sample, *minimal* reproducing code for the issue? If so, paste it in the bottom section
- Paste your list of plugins here (use the 'plugins' command in PocketMine-MP)

### Crashdump, backtrace or other files

* ...

**Comment by dktapps** [comment]
you could edit issue instead of spamming new ones.

**Comment by dktapps** [comment]
I cannot reproduce this, so please provide the following information:

- A full version number including a Jenkins build number or a git hash
- Were you using classic GUI or Pocket GUI when the bug occurred?
- Any specific items this issue occurs with?
- Is this reproducible without plugins? Don't say "unsure", _test it_ without plugins or provide a plugins list.

**Comment by BrianZP** [comment]
Cannot reproduce. Just do as @dktapps suggested. Remove or rename your plugins folder and try without any plugins installed. Because in most of the cases its a plugin issue. Also be sure to be using the latest PocketMine-MP.phar file obtained from jenkins.

**Comment by playzydoesgames** [comment]
@dktapps @BrianZP I have fixed it now as i did what you said and found the plugin causing it and removed it, thank you
