### ISSUE TITLE
Chat bug

### ISSUE THREAD

**Issue by XDqrkneZ** [pmmp/PocketMine-MP#1158]
### Issue description

 players can't see others message when they are in different worlds

### Steps to reproduce the issue

1. ...
2. ...

### OS and versions

* PocketMine-MP:  PocketMine-MP 1.6.2dev-154 「Unleashed」 implementing API version 3.0.0-ALPHA5 for Minecraft: PE v1.1.0.55 (protocol version 113)
* PHP: 7.0.3
* Server OS: LINUX
* Game version: PE/Win10 (delete as appropriate) tested on win10 and mobile

### Plugins
- Test on a clean server without plugins: is the issue reproducible without any plugins loaded?

If the issue is **not** reproducible without plugins:
- Have you asked for help on our forums before creating an issue?
- Can you provide sample, *minimal* reproducing code for the issue? If so, paste it in the bottom section
- Paste your list of plugins here (use the 'plugins' command in PocketMine-MP)

### Crashdump, backtrace or other files

* ...

**Comment by dktapps** [comment]
The plugins section of the template is not optional, and this is not reproducible without plugins
