### ISSUE TITLE
Error detected

### ISSUE THREAD

**Issue by MrSmileCH** [pmmp/PocketMine-MP#1159]
Issue description
30.06 16:19:37 [Server] Server thread/CRITICAL TypeError: "Argument 1 passed to pocketmine\entity\Living::setAbsorption() must be of the type integer, float given, called in phar:///custom-phar.phar/src/pocketmine/entity/Entity.php on line 921" (EXCEPTION) in "src/pocketmine/entity/Living" at line 99

Steps to reproduce the issue

The error is produced when the player eats a golden apple of notch and has absorption effect does not receive any damage by another player

OS and versions

PocketMine-MP: 1.6.2dev-249
PHP: 7
Server OS: Win10
Game version: PE/Win10 

plugins (0)

**Comment by Sandertv** [comment]
Please search the issue tracker before opening an issue. This issue has been reported multiple times already and it fixed on a non-production branch.

**Comment by totor29** [comment]
Hi,

Please find this log critical error  setAbsorption
same issue or not ?
thanks

-------------------------------------------------------------------------------------------------------------------
PocketMine-MP_1.6.2dev-336_17be06a5_API-3.0.0-ALPHA7.phar
--

2017-07-31 [15:52:17]  [Server thread/CRITICAL]: TypeError: "Argument 1 passed to pocketmine\entity\Living::setAbsorption() must be of the type integer, float given, called in phar:///home/gsp_7524/g7.hmservr.eu-19548/PocketMine-MP.phar/src/pocketmine/entity/Entity.php on line 926" (EXCEPTION) in "src/pocketmine/entity/Living" at line 100
