### ISSUE TITLE
No way to disable server.log writing

### ISSUE THREAD

**Issue by madecode15** [pmmp/PocketMine-MP#1164]
Currently there is no possible way to disable server.log writing. This is a waste of CPU on large production servers that don't need this feature. Would be useful if there was a config option or server.properties option to allow users to choose to enable this or not.

Although it does write on a separate thread, threads still use CPU

PocketMine-MP: (All versions)
PHP: irrelevant
MCPE version: irrelevant

**Comment by dktapps** [comment]
Do you have any concept of how threads work?

> This is a waste of CPU

No. Noobs want to believe it will improve their server performance. As a matter of fact blocking operations on threads don't take any CPU cycles at all... all it has to do is wait for the operation to complete. In the meantime the thread will be suspended and the CPU will do something else.

**Comment by dktapps** [comment]
Since you're so concerned about one little log file, I'd like to remind you, and readers, once again, that level I/O is done on the main thread. _That_ is a waste of CPU time because the main thread then has to wait for disk operations to complete. That is a much bigger problem than a log file.

**Comment by TheDiamondYT1** [comment]
Then do level I/O in a seperate thread ?

**Comment by dktapps** [comment]
@TheDiamondYT1 congratulations Captain Obvious. I'm making the point that the server log is completely insignificant compared to that problem.

**Comment by thebigsmileXD** [comment]
Bump

"This will waste " - disk space. My testing server generates almost 1GB data per week, i have to delete it quite often. I am wondering why there is no option to disable it yet.
