### ISSUE TITLE
Can't join time out error

### ISSUE THREAD

**Issue by EmreTr1** [pmmp/PocketMine-MP#1166]
![screenshot_20170704-104925](https://user-images.githubusercontent.com/13833030/27820603-f18e5e9e-60a7-11e7-9a34-6da6d7b1ef47.png)

**Comment by dktapps** [comment]
You can clearly see that is a plugin issue.

**Comment by EmreTr1** [comment]
![screenshot_20170704-111807](https://user-images.githubusercontent.com/13833030/27821317-88a6c684-60aa-11e7-844e-a683fbf4e0e7.png)
What is this?
