### ISSUE TITLE
api3/blocks clone crash

### ISSUE THREAD

**Issue by Matthww** [pmmp/PocketMine-MP#1168]
### Issue description

I have no idea how to reproduce but my server crashes when using api3/blocks

### Steps to reproduce the issue

1. ...
2. ...

### OS and versions

* PocketMine-MP: b6014c2
* PHP: 7.0.20
* Server OS: Linux Debian

### Plugins
- Test on a clean server without plugins: is the issue reproducible without any plugins loaded?

If the issue is **not** reproducible without plugins:
- Have you asked for help on our forums before creating an issue?
- Can you provide sample, *minimal* reproducing code for the issue? If so, paste it in the bottom section
- Paste your list of plugins here (use the 'plugins' command in PocketMine-MP)

### Crashdump, backtrace or other files

https://gist.github.com/Matthww/62fd3c4a992f3e7f136ecd0d5a7ca377

**Comment by dktapps** [comment]
lots of incompatible plugins there... tried getting rid of the Elytra one in particular?
