### ISSUE TITLE
Server freeze on teleport

### ISSUE THREAD

**Issue by QuanFromChina** [pmmp/PocketMine-MP#1171]
### Issue description
I teleport player and server froze.. new bug only happens with https://github.com/pmmp/PocketMine-MP/commit/394f4200597f6061bf5b92e748532531ae2479a7

### Steps to reproduce the issue

1. ... teleport the player to the unloaded chunk..
2. ... freeze server !
3. ... console frozen too !
-->
* PocketMine-MP: #266
* PHP: 7.0.3
* Server OS: Windows
* Game version: both

### Crashdump, backtrace or other files
console frozen

**Comment by dktapps** [comment]
Without knowing your PocketMine-MP version, OS, PHP, Client version, or plugins and how the issue occurred, the issue cannot begin to be solved.
A pre-formatted template is provided that shows the required information to begin to find, test and solve an issue.
Until the adequate template and information is provided, the issue will be closed; it may be reopened if you update the ticket with the correct template and required information.

[Contribution guidelines](https://github.com/pmmp/PocketMine-MP/blob/master/CONTRIBUTING.md)

**Comment by QuanFromChina** [comment]
Updated issue... i will try provide map maybe soon..

**Comment by QuanFromChina** [comment]
Update: It only happen when do $player->teleport(x, y, z);

**Comment by xxFlare** [comment]
I was able to reproduce this on my test server. It's identical to the teleport freeze bug that was in a popular spoon last summer.

You really just have to keep teleporting far away until it happens, as if it happens randomly.

**Comment by dktapps** [comment]
It's not random, I can reproduce it by teleporting a moving player.

**Comment by dktapps** [comment]
I recommend you enable movement checks for the time being to prevent this issue occurring.

**Comment by QuanFromChina** [comment]
@dktapps wow ! thank you for temporary fix ! you are the best!!
