### ISSUE TITLE
Can't craft without it being reverted

### ISSUE THREAD

**Issue by kaasci** [pmmp/PocketMine-MP#1172]
Using 1.6.2dev188 for MCPE 1.1.x on a Windows 10 computer
Stuff on the server crafts but the inventory and position revert back to just beofre the item was crafted after five seconds

> [Server thread/CRITICAL]: ErrorException: "Undefined offset: 0" (EXCEPTION) in "/src/pocketmine/Player__64bit" at line 3026

followed by

> [RakLibServer thread/NOTICE]: Blocked player_ip for 5 seconds

where the player_ip is the affected player's ip without port

**Comment by dktapps** [comment]
#45
