### ISSUE TITLE
How I can run PocketMine on Raspberry 3?

### ISSUE THREAD

**Issue by Borduni** [pmmp/PocketMine-MP#1173]
### Issue description

 I can't run PocketMine and im expecting, that PocketMine should run on a 32 bit system/bin like GenisysPro

### Steps to reproduce the issue

1. Buy a raspberry
2. Install Raspbian OS 32 Bit
3. Install PocketMine, download the last phar and let it run

### OS and versions

* PocketMine-MP: newest
* PHP: 7.0.6 32bit
* Server OS: Raspbian OS 32bit
* Game version: that not matter (delete as appropriate)

### Plugins
- Test on a clean server without plugins: is the issue reproducible without any plugins loaded?

If the issue is **not** reproducible without plugins:
- Have you asked for help on our forums before creating an issue?
- Can you provide sample, *minimal* reproducing code for the issue? If so, paste it in the bottom section
- Paste your list of plugins here (use the 'plugins' command in PocketMine-MP)

### Crashdump, backtrace or other files

* no need to

**Comment by dktapps** [comment]
This is not a support forum.

**Comment by Borduni** [comment]
Reopen this
