### ISSUE TITLE
Bug with Living (absorption)

### ISSUE THREAD

**Issue by Rateek** [pmmp/PocketMine-MP#1174]
### Issue description
[Server thread/CRITICAL]: TypeError: "Argument 1 passed to pocketmine\entity\Living::setAbsorption() must be of the type integer, float given, called in /home/mcpe/src/pocketmine/entity/Entity.php on line 926" (EXCEPTION) in "src/pocketmine/entity/Living" at line 101

Bug with Absorption.

### OS and versions
This server is running PocketMine-MP 1.6.2dev 「Unleashed」 implementing API version 3.0.0-ALPHA6 for Minecraft: PE v1.1.0.55 (protocol version 113)

* PocketMine-MP: https://github.com/pmmp/PocketMine-MP/commit/1a5e3b2ad0ea097ef75a73c15f1e017fb3addfd4
* PHP: 7.1
* Server OS: Debian 8 64 bits
* Game version: Win10 & PE

### Plugins
0 plugins

**Comment by Rateek** [comment]
Im sorry (use api3/blocks for debug)

**Comment by dktapps** [comment]
duplicate of #1071
