### ISSUE TITLE
Shadows on some places of the world since minecraft pe v_1.1.0.55

### ISSUE THREAD

**Issue by killer549** [pmmp/PocketMine-MP#1175]
Write a short description about the issue
When I join the server the black shadows take over the world, But this doesn't happen everywhere.
I searched before posting this issue and I've found that this was reported before in 17 APRIL. 2017.
 #843 but this problem happened to me since 1.1.0.55

![screenshot_20170707-040342](https://user-images.githubusercontent.com/11447051/27939090-36499b82-62cb-11e7-85d1-e00b1221da5a.png)
![screenshot_20170707-040347](https://user-images.githubusercontent.com/11447051/27939093-3650cbe6-62cb-11e7-8d5c-151ed100f7c8.png)
![screenshot_20170707-040429](https://user-images.githubusercontent.com/11447051/27939092-364ecf4e-62cb-11e7-8d0a-d7e2b467c96e.png)
![screenshot_20170707-040442](https://user-images.githubusercontent.com/11447051/27939091-364cc24e-62cb-11e7-8d2d-0f9ebc96a79a.png)

### Steps to reproduce the issue

1. Join the server
2. Move around and you will find it

### OS and versions

* PocketMine-MP: #1170
* PHP:  7.0.3
* Server OS: Windows 10 
* Game version: PE

### Plugins
- Test on a clean server without plugins: is the issue reproducible without any plugins loaded?
Yes and tested on empty world too

**Comment by HimbeersaftLP** [comment]
Has the world been generated in a version before 1.1? If so, take a look at this: https://forums.pmmp.io/threads/recalculating-lights.2572/

**Comment by Driesboy** [comment]
i dont have this bug in my server

**Comment by dktapps** [comment]
This is the same issue as #843

**Comment by ProCOmpTEAM** [comment]
I have this bug already

**Comment by killer549** [comment]
I tried both.. Old and new generated world but the problem still apply

**Comment by killer549** [comment]
I have fixed the problem when I saw this https://forums.pmmp.io/threads/recalculating-lights.2572 I have edited the code and Enabled Light updates. but this method isn't practical. Thanks for the help.
