### ISSUE TITLE
These messages are shown from nowhere

### ISSUE THREAD

**Issue by ProCOmpTEAM** [pmmp/PocketMine-MP#1176]
what is it?
![default](https://user-images.githubusercontent.com/24737193/27948313-188735a0-6302-11e7-8f28-ce7f82547c89.PNG)

**Comment by dktapps** [comment]
Without knowing your PocketMine-MP version, OS, PHP, Client version, or plugins and how the issue occurred, the issue cannot begin to be solved.
A pre-formatted template is provided that shows the required information to begin to find, test and solve an issue.
Until the adequate template and information is provided, the issue will be closed; it may be reopened if you update the ticket with the correct template and required information.

[Contribution guidelines](https://github.com/pmmp/PocketMine-MP/blob/master/CONTRIBUTING.md)

**Comment by ProCOmpTEAM** [comment]
when I joined to server and while I playing*

**Comment by ProCOmpTEAM** [comment]
@dktapps 
* PocketMine-MP: 1.6.2dev-267 "Unleashed" (API 3.0.0-ALPHA6)
* PHP: 7
* Server OS: win 7
* Game version: PE v1.1.0.55

**Comment by ProCOmpTEAM** [comment]
@dktapps **plugin only one. it is my plugin. it worked on version 1.0.x is normally**

**Comment by Sandertv** [comment]
Then it's your own fault. Update it according to the recent API. Make sure to cast your types correctly.
