### ISSUE TITLE
snow drops incorrect

### ISSUE THREAD

**Issue by MCPEChicken** [pmmp/PocketMine-MP#1177]
should be changed to 

1
--
declare(strict_types=1);
  |  
  | namespace pocketmine\block;
  |  
  | use pocketmine\item\Item;
  | use pocketmine\item\Tool;
  |  
  | class Snow extends Solid{
  |  
  | protected $id = self::SNOW_BLOCK;
  |  
  | public function __construct($meta = 0){
  | $this->meta = $meta;
  | }
  |  
  | public function getHardness(){
  | return 0.2;
  | }
  |  
  | public function getToolType(){
  | return Tool::TYPE_SHOVEL;
  | }
  |  
  | public function getName(){
  | return "Snow Block";
  | }
  |  
  | public function getDrops(Item $item){
  | return [
  | [Item::SNOW_BALL, 0, 4],
  | ];
  | }
  | }

**Comment by MCPEChicken** [comment]
or something of that similar sort.

**Comment by SuperMaXAleX** [comment]
This """issue""" will be closed in some minutes for sure
