### ISSUE TITLE
/timings paste domain suspende

### ISSUE THREAD

**Issue by XDqrkneZ** [pmmp/PocketMine-MP#1178]
### Steps to reproduce the issue

1. ...
2. ...

### OS and versions

* PocketMine-MP:  PocketMine-MP 1.6.2dev-154 「Unleashed」 implementing API version 3.0.0-ALPHA5 for Minecraft: PE v1.1.0.55 (protocol version 113)
* PHP: 7.0.3
* Server OS: LINUX
* Game version: PE/Win10 (delete as appropriate)

### Plugins
- Test on a clean server without plugins: is the issue reproducible without any plugins loaded?

If the issue is **not** reproducible without plugins:
- Have you asked for help on our forums before creating an issue?
- Can you provide sample, *minimal* reproducing code for the issue? If so, paste it in the bottom section
- Paste your list of plugins here (use the 'plugins' command in PocketMine-MP)

### Crashdump, backtrace or other files

* ...

**Comment by XDqrkneZ** [comment]
;-;

**Comment by TheDiamondYT1** [comment]
How is this invalid?

**Comment by dktapps** [comment]
does timings.pmmp.io look suspended to you?

**Comment by TheDiamondYT1** [comment]
Oh no lol

**Comment by XDqrkneZ** [comment]
why did it give me different link instead of timings.pmmp.io?

**Comment by TheDiamondYT1** [comment]
@XDqrkneZ Usually when you say `it gave me a different link` you tell us the link, or we cant help you

**Comment by XDqrkneZ** [comment]
fixed.

**Comment by SOF3** [comment]
Note that timings.pmmp.io is only a display. The actual data are sent to paste.ubuntu.com, and timings.pmmp.io does not receive any data from the server directly.
