### ISSUE TITLE
Joining with the same name as someone else.

### ISSUE THREAD

**Issue by Matthww** [pmmp/PocketMine-MP#1179]
### Issue description

Tested this on api3/blocks

You can join with the same in a server even though that person is also online on the server.

### Steps to reproduce the issue

1. Have 2 devices
2. Join the server with the same username.

### OS and versions

* PocketMine-MP: 1a5e3b2
* PHP: 7.0.20
* Server OS: Debian

### Plugins
- Test on a clean server without plugins: is the issue reproducible without any plugins loaded?

If the issue is **not** reproducible without plugins:
- Have you asked for help on our forums before creating an issue?
- Can you provide sample, *minimal* reproducing code for the issue? If so, paste it in the bottom section
- Paste your list of plugins here (use the 'plugins' command in PocketMine-MP)

This is tested on a server without any plugins

### Crashdump, backtrace or other files

* ...

**Comment by dktapps** [comment]
This is only reproducible in the short space of time between logging in and spawning.

**Comment by Matthww** [comment]
Do you know of any quick fix? I tried cancelling prelogin etc. But it all doesn't work

**Comment by madecode15** [comment]
@Matthww 

Try sending a disconnection packet using the directDataPacket API method, then make sure to cancel the event so the server stops processing the player.

**Comment by thebigsmileXD** [comment]
You can do this in sinleplayer too by the way.

**Comment by Matthww** [comment]
@thebigsmileXD Because singleplayer handles this differently. It uses the DeviceID or something similiar to see them different while on PMMP they are seen as the same person they share the same data such as Inventory.

**Comment by dktapps** [comment]
Singleplayer is completely irrelevant. This issue targets a bug in PocketMine-MP.

**Comment by CortexPE** [comment]
Try closing the connection instead of cancelling it.
```close()```

**Comment by CortexPE** [comment]
This is what I meant btw.

**Comment by dktapps** [comment]
Another copy-paste job... you see that Debugged label? We know full well what's causing the problem -
I just haven't decided how best to fix it. Copy-pasting code however, is an idiot's solution.
