### ISSUE TITLE
Server Nor Appearing Online To Others Players

### ISSUE THREAD

**Issue by RenanGamerz** [pmmp/PocketMine-MP#118]
### Issue description
Server Not Appear Online To Other Players

### Steps to reproduce the issue
1. Start Server
2. Connect To Other Wi-Fi
3. Add IP and PORT
4. Server Not Appear Online

### OS and versions
This server is running PocketMine-MP 1.6.1dev-#82 「Unleashed」 implementing API version 2.1.0 for Minecraft: PE v0.16.0.5 alpha (protocol version 91)
* PocketMine-MP: PocketMine-MP 1.6.1dev-#82
* PHP:7
* Server OS: Windows 10
* Game version: PE

**Comment by SOF3** [comment]
Your own setup issue. Please use the forums for further help.
