### ISSUE TITLE
Can't turn on the server because of debug at the world?

### ISSUE THREAD

**Issue by LewBr** [pmmp/PocketMine-MP#1180]
### Issue description
OMG???

### Steps to reproduce the issue

1. NBT
2. ...

### OS and versions

* PocketMine-MP: PMMP-1.6.2dev-268
* PHP: 7.0
* Server OS: MultiCraft (NetherBox)
* Game version: PE/Win10

I've been tested whitout any of my plugins, so please don't say thats my Core or Plugin error..

### Crashdump, backtrace or other files

* 07.07 16:00:15 [Server] Server thread/ERROR Could not load level "Hub": zlib_decode(): data error
07.07 16:00:15 [Server] Server thread/CRITICAL ErrorException: "zlib_decode(): data error" (EXCEPTION) in "src/pocketmine/nbt/NBT" at line 211

**Comment by LewBr** [comment]
How can i update my Map?

**Comment by mal0ne-23** [comment]
I think it's a corrupt map

**Comment by LewBr** [comment]
i have seen what happened, my level.dat are whit nothing..
i turn my server on and then i see my level.dat is whit 0 KB WTF?? 
it's a PMMP issue or what?

**Comment by killer549** [comment]
not sure but, have u killed your server while writing something?

**Comment by LewBr** [comment]
i have now fixed this, thanks to all, i have uploaded my old level.dat
but this is not good because i do nothing and my level.dat has been reseted..
killer what you mean killed? i think no..

**Comment by killer549** [comment]
I mean closed the console without stopping the server by /stop. But you fixed the problem so congratulations.  :smile:
