### ISSUE TITLE
Sign update lines while you writing it (with SignChangeEvent)

### ISSUE THREAD

**Issue by ProCOmpTEAM** [pmmp/PocketMine-MP#1185]
### Steps to reproduce the issue

1. Made sign with form:
 [shop]
 id
 count
 name

2. SignChangeEvent runned and added false data to database

### OS and versions

* PocketMine-MP: 1.6.2dev "Aurora" (API 3.0.0-ALPHA6)
* PHP: 7
* Server OS: Win 7
* Game version: PE

### Crashdump, backtrace or other files

* ...

**Comment by dktapps** [comment]
duplicate of #956

**Comment by dktapps** [comment]
Duplicate of #956
