### ISSUE TITLE
API issue..

### ISSUE THREAD

**Issue by QuanFromChina** [pmmp/PocketMine-MP#1189]
```php
public function onMove(PlayerMoveEvent $event){
        if(!$this->canMove($event->getPlayer())){
            if((int) $event->getTo()->getX() !== (int) $event->getFrom()->getX() || (int) $event->getTo()->getZ() !== (int) $event->getFrom()->getZ()){
                if(SERVERVERSION === POCKETMINE){
                    $event->getPlayer()->teleport($this->disableMovement[$event->getPlayer()->getId()]); //Hack for PMMP
                }
                else{
                    $event->setTo($event->getFrom()); //Steadfast
                }
            }
        }
}
```

$event->setTo($event->getFrom()); is suppose to revert movement and it use to work on pmmp a while ago... now it lets players move small bit by bit (if player keeps trying).. evidently correct behavior happens on steadfast (player cannot move)

before this work perfectly fine (months ago).. not sure what the change

so i implemented teleport hack for pmmp until fixed in API

**Comment by dktapps** [comment]
You shouldn't rely on that because players can move up to 0.01 blocks without any event being fired (for performance reasons). You should correctly keep track of the position you want to lock them at and send that to them instead of using the event.

**Comment by QuanFromChina** [comment]
@dktapps oh ... sorry i did not know api did the change for the performance.. my fault 🤦‍♂️
