### ISSUE TITLE
QueryRegenerationEvent needs call on server startup

### ISSUE THREAD

**Issue by QuanFromChina** [pmmp/PocketMine-MP#1190]
I use global player count system ..

example:
server 1 -> 50 players
server 2 -> 100 players

150 total = global count

when pocketmine do the startup, queryregenerationevent not called. this make player global player count show as "0" for some time

lets consider:
```
public function regenerate(QueryRegenerateEvent $event){
        var_dump("debug-stacktrace### called");
        if($this->firstQueryEventCalled){ //we need global count instanty, cannot wait for callback..
            $this->firstQueryEventCalled = false;
            $this->playerCount = @file_get_contents("www.xxxxx.com/restapi/endpoint");
            if($this->playerCount === false){
                $this->tweetTwitterUpdate("Server restapi having some issues, sorry");
                return;
            }
            $this->playerCount = json_decode($this->playerCount);
        }
        $event->setExtraData(["serverplayercount" => count($this->getServer()->getOnlinePlayers())]); //restapi need static data, not including globalcount
        $event->setPlayerCount($this->playerCount);
        $this->getServer()->getScheduler()->scheduleAsyncTask(new UpdatePlayerCountTask($this->getPluginProperty("server-ip")));
    }

    public function setGlobalPlayerCount($c){ //callback from the worker...
        $this->playerCount = $c;
    }
```

it not called on startup (dump test)... 

small issue? yes,, but persists

**Comment by dktapps** [comment]
This makes no sense whatsoever. When the server has just started there will be no players online regardless.

**Comment by QuanFromChina** [comment]
@dktapps right

but if 50 player on another server you have, it cannot set at server startup..

server 1> 0 players
server 2> 50
global count: 50 (on startup should be set)

maybe i not clear ? RESTAPI uses sockets to gather player counts from all servers

if server just start, it not mean there are 0 players on the "network" because the game servers have other players

**Comment by Driesboy** [comment]
same issue with Hormones

Op 11-jul.-2017 12:41 schreef "QuanFromChina" <notifications@github.com>:

**Comment by SOF3** [comment]
@Driesboy Hormones loads lymphatic data asynchronously, so Hormones can't handle it in startup anyway.
This is only an individual issue, though &mdash; Hormones does not represent all plugins, and some plugins can reasonably modify player count in startup.
