### ISSUE TITLE
Nether has the name of the generator "normal"?

### ISSUE THREAD

**Issue by GamakCZ** [pmmp/PocketMine-MP#1193]
### Issue description

Nether has the name of the generator "normal"?

### Steps to reproduce the issue

1. ... -
2. ... -

### OS and versions

* PocketMine-MP: branch master
* PHP: 7
* Server OS:
* Game version: PE/Win10 (delete as appropriate)

### Crashdump, backtrace or other files

Nether Generator Name: https://github.com/pmmp/PocketMine-MP/blob/master/src/pocketmine/level/generator/hell/Nether.php#L84
Normal Generator Name:  https://github.com/pmmp/PocketMine-MP/blob/master/src/pocketmine/level/generator/normal/Normal.php#L93

**Comment by dktapps** [comment]
If you want to make a PR to fix that, I'd be happy to review it.
