### ISSUE TITLE
Resource packs are broken

### ISSUE THREAD

**Issue by IrishPacks** [pmmp/PocketMine-MP#1197]
### Issue description
While messing around with AsyncTasks, I found out that ResourcePacks have been broken, every texture pack that I tried(yes I downloaded them via Google Chrome just to double check) always gave me the same result(manifest.json not found). The manifest was in all of them, yet none were found? I tried both zip and mcpack(although they are the same thing), yet failed.

### Steps to reproduce the issue

1. ...
2. ...

### OS and versions

* PocketMine-MP: 83471aa
* PHP: 7.0.3
* Server OS: Windows 10
* Game version: v1.1.0.55

### Plugins
- Test on a clean server without plugins: is the issue reproducible without any plugins loaded? Yes, I removed all of the plugins to double check.

If the issue is **not** reproducible without plugins:
- Have you asked for help on our forums before creating an issue?
- Can you provide sample, *minimal* reproducing code for the issue? If so, paste it in the bottom section
- Paste your list of plugins here (use the 'plugins' command in PocketMine-MP)

### Crashdump, backtrace or other files

*
```
[19:36:43] [Server thread/CRITICAL]: InvalidStateException: "Could not load reso
urce pack from C:\Users\Matt\Documents\Test Server\resource_packs\\SuchPvP16x.mc
pack: manifest.json not found" (EXCEPTION) in "src/pocketmine/resourcepacks/Zipp
edResourcePack" at line 79
[19:36:43] [Server thread/DEBUG]: #0 src/pocketmine/resourcepacks/ResourcePackMa
nager(89): pocketmine\resourcepacks\ZippedResourcePack->__construct(string C:\Us
ers\Matt\Documents\Test Server\resource_packs\\SuchPvP16x.mcpack)
[19:36:43] [Server thread/DEBUG]: #1 src/pocketmine/Server(1591): pocketmine\res
ourcepacks\ResourcePackManager->__construct(pocketmine\Server object, string C:\
Users\Matt\Documents\Test Server\resource_packs\)
[19:36:43] [Server thread/DEBUG]: #2 src/pocketmine/PocketMine(511): pocketmine\
Server->__construct(BaseClassLoader object, pocketmine\utils\MainLogger object,
string C:\Users\Matt\Documents\Test Server\, string C:\Users\Matt\Documents\Test
 Server\, string C:\Users\Matt\Documents\Test Server\plugins\)
[19:36:43] [Server thread/DEBUG]: Successfully loaded 0 resource packs
[19:36:43] [Server thread/INFO]: Loading DevTools v1.11.3
[19:36:43] [Server thread/INFO]: Enabling DevTools v1.11.3
[19:36:43] [Server thread/INFO]: Loading source plugin TestPlugin v1
[19:36:43] [Server thread/INFO]: [DevTools] Registered folder plugin loader
[19:36:43] [Server thread/INFO]: Preparing level "buildWorld"
[19:36:43] [Server thread/INFO]: Enabling TestPlugin v3
[19:36:43] [Server thread/INFO]: [TestPlugin] The core has been enabled!
[19:36:43] [Server thread/INFO]: Starting GS4 status listener
nager(89): pocketmine\resourcepacks\ZippedResourcePack->__construct(string C:\Users\Matt\Documents\Test Server\resource_packs\\SuchPvP16x.mcpack)
[19:36:43] [Server thread/DEBUG]: #1 src/pocketmine/Server(1591): pocketmine\resourcepacks\ResourcePackManager->__construct(pocketmine\Server object, string C:\Users\Matt\Documents\T
est Server\resource_packs\)
[19:36:43] [Server thread/DEBUG]: #2 src/pocketmine/PocketMine(511): pocketmine\Server->__construct(BaseClassLoader object, pocketmine\utils\MainLogger object, string C:\Users\Matt\D
ocuments\Test Server\, string C:\Users\Matt\Documents\Test Server\, string C:\Users\Matt\Documents\Test Server\plugins\)

```

**Comment by dktapps** [comment]
Mind linking a sample resource pack that has this problem? I have resource packs on my development server that have been there for months and I have no trouble with those.

**Comment by Driesboy** [comment]
same problem

**Comment by Driesboy** [comment]
http://mcpedl.com/faithful-pe/ 
32x32

**Comment by dktapps** [comment]
Works fine for me.

**Comment by Driesboy** [comment]
i have force resource packs turned off

**Comment by SuperMaXAleX** [comment]
Same issue. Is the compression’s system on macOS is different as Windows (this is happening when I’m trying to ZIP a pack) ?

**Comment by Driesboy** [comment]
i tested on macosx

**Comment by dktapps** [comment]
@SuperMaXAleX do you have any specific resource pack that this can be reproduced with? I tried the Faithful one above on three different systems and had no issue.

**Comment by SuperMaXAleX** [comment]
There isn't specific resource pack. This is happening when you are compressing a pack with macOS and install it on your server, you have got this problem.
If you downloaded a pack with the format .mcpack or .zip who has been compressed on Windows, this will work. 
I suppose when something is compressed on macOS, files directories are different.

**Comment by dktapps** [comment]
Could you send me a link to one of these resource packs compressed on Mac that you're having problems with?

**Comment by SuperMaXAleX** [comment]
No problem

**Comment by SuperMaXAleX** [comment]
Very basic resource pack : https://www.dropbox.com/s/z1rixxcft08obkv/stained-glass.zip?dl=0

**Comment by dktapps** [comment]
Ah, the problem is obvious straight away.

![image](https://user-images.githubusercontent.com/14214667/28160228-6eeeabee-67b7-11e7-98a3-f99fa7da6775.png)

The manifest.json must be in the root of the resource-pack zip, but your pack has everything inside its own folder. Don't select and compress the folder, you should enter the folder, select all the files and _then_ create the zip.

**Comment by dktapps** [comment]
MCPE also reports the same problem when it parses that pack, so it also doesn't tolerate that.

![image](https://user-images.githubusercontent.com/14214667/28160350-d9d22e54-67b7-11e7-850d-ce368d724d8f.png)

**Comment by SuperMaXAleX** [comment]
Wtf, when I added this pack on my iPad, I didn't have any error

**Comment by dktapps** [comment]
Also that pack is still using the old `pack_manifest.json` format. PocketMine-MP only supports the 1.0.4 format and later using the `manifest.json`.

**Comment by SuperMaXAleX** [comment]
I didn't touch this pack since 2 months, since this, there were many changes

**Comment by SuperMaXAleX** [comment]
And thank you for giving me the solution !

**Comment by IrishPacks** [comment]
Ah yes, it's the pack_manifest.json, small little things like that you miss, but thanks for the help!

![image](https://user-images.githubusercontent.com/13668008/28170808-778957c0-67b4-11e7-9a6f-c1db70167281.png)
