### ISSUE TITLE
Can not see other players armor when changing worlds

### ISSUE THREAD

**Issue by thebigsmileXD** [pmmp/PocketMine-MP#1203]
### Issue description

Quite difficult to explain. Player data saving is turned off.
You and another player join, both without armor.
The other player (from now on: P2) changes to another level and puts on armor.
You teleport into the level P2 is in, and tp to P2.
P2 will not wear armor, though damage ETC is calculated fine, you simply won't see P2's armor.

### Steps to reproduce the issue

1. 2 levels
2. Explained above

### OS and versions

* PocketMine-MP: https://github.com/pmmp/PocketMine-MP/commit/906f58e9cef939b9931448b6ae162742c1a552a9 This server is running PocketMine-MP version 1.6.2dev "Unleashed" (API 3.0.0-ALPHA6)
* PHP:
* Server OS: Windows Server 2012 R2

### Plugins
- Test on a clean server without plugins: is the issue reproducible without any plugins loaded?

If the issue is **not** reproducible without plugins:
- Have you asked for help on our forums before creating an issue?
- Can you provide sample, *minimal* reproducing code for the issue? If so, paste it in the bottom section
- Paste your list of plugins here (use the 'plugins' command in PocketMine-MP)
Plugins[1]: ManyWorlds

**Comment by dktapps** [comment]
I can't reproduce this using the steps you've given. Are you sure this is not because of modifications you have made?

**Comment by thebigsmileXD** [comment]
Its a freshly fetched pmmp, i test with clean server cores, not like others. I know how annoying invalid issues are.

**Comment by thebigsmileXD** [comment]
Pre-closing for now, it suddenly is not reproduceable to me either
