### ISSUE TITLE
Block/Hopper?/Can it be added

### ISSUE THREAD

**Issue by SourSmirnoff** [pmmp/PocketMine-MP#1207]
Just kinda a question and request.. idk how hard it would be, but are hoppers added? if not what am i doing wrong when /giving them, because i place it and it automatically disappears.

**Comment by SourSmirnoff** [comment]
why was this closed so fast and nobody bothered to even give me an explanation?

**Comment by SuperMaXAleX** [comment]
Because issue !== suggestion
