### ISSUE TITLE
MOTD still doing weird whenever it's custom

### ISSUE THREAD

**Issue by Matthww** [pmmp/PocketMine-MP#1208]
### Issue description

When I try to set a custom MOTD with
```
$this->getServer()->getNetwork()->setName("Server MOTD");
```
The Server would appear "offline" and shows the MOTD somewhere else

### Steps to reproduce the issue

1. Change the MOTD with a plugin

### OS and versions

* PocketMine-MP: 58214bb
* PHP: 7.0.20
* Server OS: Linux Debian
* Game version: PE/Win10 (delete as appropriate) Win10

### Plugins
- Test on a clean server without plugins: is the issue reproducible without any plugins loaded?

If the issue is **not** reproducible without plugins:
- Have you asked for help on our forums before creating an issue?
- Can you provide sample, *minimal* reproducing code for the issue? If so, paste it in the bottom section
- Paste your list of plugins here (use the 'plugins' command in PocketMine-MP)

### Crashdump, backtrace or other files

* ...

**Comment by SuperMaXAleX** [comment]
It's happening sometimes, I can confirm

**Comment by VCraftMCPE** [comment]
i can confirm too

**Comment by Muqsit** [comment]
Yeah I can confirm too. The game shows as if it's offline, but you can still join the server.

**Comment by Driesboy** [comment]
got the same error
