### ISSUE TITLE
Stair kick you..

### ISSUE THREAD

**Issue by QuanFromChina** [pmmp/PocketMine-MP#1211]
![image_uploaded_from_ios_720](https://user-images.githubusercontent.com/29927587/28241318-61b80786-6960-11e7-9828-1390570627c1.jpg)
![image_uploaded_from_ios-1](https://user-images.githubusercontent.com/29927587/28241321-6b7933bc-6960-11e7-9875-fdd0b34f00b5.jpg)

PocketMine-MP: Build #300
OS: Window
PHP: 7

**Comment by TheDiamondYT1** [comment]
Related to #169

**Comment by TheDiamondYT1** [comment]
Why the downvote?

**Comment by dktapps** [comment]
It's because stairs are considered to have the same bounding box area as slabs do (due to lack of implementation of complex AABBs).

**Comment by QuanFromChina** [comment]
@dktapps hi can we hack stair BB to full block ?

**Comment by Tarik02** [comment]
@QuanFromChina no because then you will get "moven wrongly" while moving on the stairs

**Comment by QuanFromChina** [comment]
@Tarik02 But this is criticial issue it make gameplay impossible !

**Comment by masterofmcpe** [comment]
same issue, this why i use genyisys pro... pmmp never fix bugs until api3/blocks merged

**Comment by Tarik02** [comment]
@QuanFromChina you won't able to move on stairs if you will do it.

**Comment by TheDiamondYT1** [comment]
@QuanFromChina We do not *'hack'* things unless it is absolutely essentials that we do. If you want to use hacky, buggy, and possibly slow server softwares then be my guest — but if you want to use a server software that is frequently updated, feature rich, and fast, then stay here and stop complaining.
