### ISSUE TITLE
Enchantments cause armor to not work

### ISSUE THREAD

**Issue by ManiakMCPE** [pmmp/PocketMine-MP#1212]
When having an armor piece enchanted it doesn't block ANY damage at all.

**Comment by TheDiamondYT1** [comment]
Without knowing your PocketMine-MP version, OS, PHP, Client version, or plugins and how the issue occurred, the issue cannot begin to be solved.
A pre-formatted template is provided that shows the required information to begin to find, test and solve an issue.
Until the adequate template and information is provided, the issue will be closed; it may be reopened if you update the ticket with the correct template and required information.

[Contribution guidelines](https://github.com/pmmp/PocketMine-MP/blob/master/CONTRIBUTING.md)

**Comment by SuperMaXAleX** [comment]
The api3/block branch does it.
