### ISSUE TITLE
Item despawn

### ISSUE THREAD

**Issue by MrReskill** [pmmp/PocketMine-MP#1214]
Hey, Some item despawn from Chest in the branch API 3 Block.

I tried to fix this problem, but I did not find the bug.

**Comment by dktapps** [comment]
Without knowing your PocketMine-MP version, OS, PHP, Client version, or plugins and how the issue occurred, the issue cannot begin to be solved.
A pre-formatted template is provided that shows the required information to begin to find, test and solve an issue.
Until the adequate template and information is provided, the issue will be closed; it may be reopened if you update the ticket with the correct template and required information.

[Contribution guidelines](https://github.com/pmmp/PocketMine-MP/blob/master/CONTRIBUTING.md)

**Comment by MrReskill** [comment]
Yah, i use Debian 8 (vps), PHP 7.1, the 1.1.2 MCPE Verson and i use the last version of PMMP branch called " BranchApi3 block". 

When player place items into a chest, the item can despawn a minute after player have place into the chest

Sorry for my bad english, I'm french.

**Comment by SuperMaXAleX** [comment]
Alban, utilise le template par défaut des issues, Dylan ne va pas le réouvrir sinon

**Comment by MrReskill** [comment]
Grrrr
