### ISSUE TITLE
cant craft

### ISSUE THREAD

**Issue by articrevised** [pmmp/PocketMine-MP#1216]
i read that this was a common issue but that was a issue in December 2016 its 2017 and its still not fixed?

 ErrorException: "Undefined offset: 0" (EXCEPTION) in "src/pocketmine/Player" at line 2870

**Comment by Misteboss** [comment]
Stop duplicating issues and learn to use the search box.
Duplicate of #45

**Comment by articrevised** [comment]
this "workaround"   doesnt work
As a way to work around this problem, you can switch W10 Edition to Pocket GUI mode.

Game settings -> Video -> Show Advanced Video Settings ->UI Profile -> Select "Pocket"

This is obviously not a fix, it's simply a workaround until we get around to tackling the problem. (Waiting for shoghicp to finish his work with vanilla inventory transactions.)





is there gonna be fix or is there one

**Comment by Misteboss** [comment]
The PMMP Team does not plan to work on inventory problems because the 1.2 will change everything about the managing of the inventory so it would be a waste of time.

Now you should close this issue and wait for the 1.2 to be released.

**Comment by articrevised** [comment]
so you saying i have to wait from update 1.1.3 to 1.2

wait how do the big servers make servers then?

**Comment by articrevised** [comment]
i will go somewhere else and try to make a server then :(
