### ISSUE TITLE
Harassment By PMMP Fanboys

### ISSUE THREAD

**Issue by MasterOfTheRealm** [pmmp/PocketMine-MP#1219]
This is a request to tell all your fanboys to stop harassing forks. GenisysPro Issue Section was spammed over a 100 times by "pmmp-bot". Honestly this is ridiculous on how they keep constantly attacking us when we have done absolutely nothing to them. If something is so wrong about making a server software that can be used on production till PMMP rewrite is done then tell them to not use forks at all and ignore their existence. PMMP is a great software but some people prefer forks with extended features to be used on servers. That's all. Nothing more, nothing less. Again I'm not telling that the professional devs here causes the attacks but i made this issue so everyone can see it. And also we will add on our readme asking our users to not bother plugin devs for fork compatibility but ask us to make it compatible.

**Comment by MasterOfTheRealm** [comment]
Hopefully all this drama can end and we both can work in peace.

**Comment by dktapps** [comment]
Do you really think we're that stupid? This person has nothing to do with PMMP. This isn't a forum.
