### ISSUE TITLE
Player quit crash - Human::getRawUniqueId()

### ISSUE THREAD

**Issue by gizanopatrica** [pmmp/PocketMine-MP#1220]
### Issue description
Sometimes, when a player quits, the server crashes

### Steps to reproduce the issue
1. Start your server and let players join
2. Wait for a player to quit the server
3. Check if the server crashes

### OS and versions
* PocketMine-MP: https://github.com/pmmp/PocketMine-MP/commit/cca9cf2c8683fe14c3698d8da52bfd45a2febb8d
* PHP: 7.02
* Server OS: Linux
* Game version: PE

### Plugins
Reproducible on a server without plugins.

### Crashdump, backtrace or other files
```
PocketMine-MP Crash Dump Thu Jul 20 03:08:54 EDT 2017

Error: Return value of pocketmine\entity\Human::getRawUniqueId() must be of the type string, null returned
File: src/pocketmine/entity/Human
Line: 103
Type: notice

Code:
[94] 	 */
[95] 	public function getUniqueId(){
[96] 		return $this->uuid;
[97] 	}
[98] 
[99] 	/**
[100] 	 * @return string
[101] 	 */
[102] 	public function getRawUniqueId() : string{
[103] 		return $this->rawUUID;
[104] 	}
[105] 
[106] 	/**
[107] 	 * @param string $str
[108] 	 * @param string $skinId
[109] 	 */
[110] 	public function setSkin($str, $skinId){
[111] 		if(!Player::isValidSkin($str)){
[112] 			throw new \InvalidStateException("Specified skin is not valid, must be 8KiB or 16KiB");
[113] 		}

Backtrace:
#0 src/pocketmine/Server(2276): pocketmine\entity\Human->getRawUniqueId()
#1 src/pocketmine/Player(3523): pocketmine\Server->removeOnlinePlayer(pocketmine\Player object)
#2 src/pocketmine/Server(2313): pocketmine\Player->close(string , string Login timeout)
#3 src/pocketmine/Server(2481): pocketmine\Server->checkTickUpdates(integer 343, double 1500534534.4492)
#4 src/pocketmine/Server(2243): pocketmine\Server->tick()
#5 src/pocketmine/Server(2122): pocketmine\Server->tickProcessor()
#6 src/pocketmine/Server(1704): pocketmine\Server->start()
#7 src/pocketmine/PocketMine(511): pocketmine\Server->__construct(BaseClassLoader object, pocketmine\utils\MainLogger object, string phar:///home/minecraft/multicraft/servers/server1178/custom-phar.phar/, string /home/minecraft/multicraft/servers/server1178/, string /home/minecraft/multicraft/servers/server1178/plugins/)
#8 /home/minecraft/multicraft/servers/server1178/custom-phar.phar(1): require_once(string phar:///home/minecraft/multicraft/servers/server1178/custom-phar.phar/src/pocketmine/PocketMine.php)

PocketMine-MP version: 1.7 #0 [Protocol 113; API 3.0.0-ALPHA7]
Git commit: 0000000000000000000000000000000000000000
uname -a: Linux crux.minersplanet.com 2.6.32-642.6.1.el6.x86_64 #1 SMP Wed Oct 5 00:36:12 UTC 2016 x86_64
PHP Version: 7.0.20
Zend version: 3.0.0
OS : Linux, linux
```

**Comment by dktapps** [comment]
This and various other bugs occur when a player times out when trying to login. Likely someone attempted to join with an outdated client version. This causes the player to be closed with most of their fields not yet initialized due to LoginPacket not yet having been handled.

**Comment by jarne** [comment]
This happens very often on my server, it crashes after about 5 minutes. Also, the error only occurs since I've updated PocketMine to cca9cf2c8683fe14c3698d8da52bfd45a2febb8d. Unfortunately, I don't know on which commit I was before, but it shouldn't be more than 50 commits before this one.

**Comment by dktapps** [comment]
It was amongst the ALPHA7 changes. If you want a quick hack you could remove the string typehint from Human::getRawUniqueId().

**Comment by teracube** [comment]
crashdump tonight

PocketMine-MP Crash Dump Mon Jul 24 18:49:37 CEST 2017

Error: Return value of pocketmine\entity\Human::getRawUniqueId() must be of the type string, null returned
File: src/pocketmine/entity/Human
Line: 103
Type: notice

Code:
[94] 	 */
[95] 	public function getUniqueId(){
[96] 		return $this->uuid;
[97] 	}
[98] 
[99] 	/**
[100] 	 * @return string
[101] 	 */
[102] 	public function getRawUniqueId() : string{
[103] 		return $this->rawUUID;
[104] 	}
[105] 
[106] 	/**
[107] 	 * @param string $str
[108] 	 * @param string $skinId
[109] 	 */
[110] 	public function setSkin($str, $skinId){
[111] 		if(!Player::isValidSkin($str)){
[112] 			throw new \InvalidStateException("Specified skin is not valid, must be 8KiB or 16KiB");
[113] 		}

Backtrace:
#0 src/pocketmine/Server(2254): pocketmine\entity\Human->getRawUniqueId()
#1 src/pocketmine/Player(3489): pocketmine\Server->removeOnlinePlayer(pocketmine\Player object)
#2 src/pocketmine/Server(2291): pocketmine\Player->close(string , string Login timeout)
#3 src/pocketmine/Server(2459): pocketmine\Server->checkTickUpdates(integer 489723, double 1500914977.4925)
#4 src/pocketmine/Server(2221): pocketmine\Server->tick()
#5 src/pocketmine/Server(2100): pocketmine\Server->tickProcessor()
#6 src/pocketmine/Server(1682): pocketmine\Server->start()
#7 src/pocketmine/PocketMine(501): pocketmine\Server->__construct(BaseClassLoader object, pocketmine\utils\MainLogger object, string phar:///home/gsp_1485/g3.hmserv.eu-19144/PocketMine-MP.phar/, string /home/gsp_1485/g3.hmserv.eu-19144/, string /home/gsp_1485/g3.hmserv.eu-19144/plugins/)
#8 /home/gsp_1485/g3.hmserv.eu-19144/PocketMine-MP.phar(1): require(string phar:///home/gsp_1485/g3.hmserv.eu-19144/PocketMine-MP.phar/src/pocketmine/PocketMine.php)

PocketMine-MP version: 1.6.2dev #308 [Protocol 113; API 3.0.0-ALPHA7]
Git commit: f32e8805420c177ac491912108b0815627808421
uname -a: Linux ns3023271.ip-151-80-230.eu 4.4.19-mod-std-ipv6-64 #1 SMP Mon Aug 22 13:05:01 CEST 2016 x86_64
PHP Version: 7.0.17
Zend version: 3.0.0
OS : Linux, linux

Loaded plugins:
PurePerms 1.4.1-dev1 by 64FF00 & ProjectInfinity for API(s) 3.0.0-ALPHA7
BlockPets 1.1.0 by BlockHorizons for API(s) 3.0.0-ALPHA7
ItemCasePE 1.1.0-dev1 by aliuly for API(s) 3.0.0-ALPHA7
FactionsPro 1.4.4-dev1 by Tethered_, HostingItAll.com for API(s) 3.0.0-ALPHA7
SignPortal 1.1.3-dev1 by 99leonchang for API(s) 3.0.0-ALPHA7
AlwaysSpawn 2.2.3-dev1 by Philip Shilling for API(s) 3.0.0-ALPHA7
Cameraman 1.1.0-dev by ChalkPE for API(s) 3.0.0-ALPHA7
TreasureChest 1.2.1 by Awzaw for API(s) 3.0.0-ALPHA7
SimpleAuth 1.8.1-dev1 by PocketMine Team, shoghicp, awzaw for API(s) 3.0.0-ALPHA7
SimpleAuthHelper 2.0.5-dev1 by aliuly for API(s) 3.0.0-ALPHA7
PiggyCustomEnchants 1.0.2 by DaPigGuy for API(s) 3.0.0-ALPHA7
essentialsTP 1.1.1-dev2 by  for API(s) 3.0.0-ALPHA7
ChatToDiscord 1.1.0 by eDroid for API(s) 3.0.0, 3.0.0-ALPHA6, 3.0.0-ALPHA7
Parkour 1.5.3 by jdcraft for API(s) 3.0.0-ALPHA7

----------------------REPORT THE DATA BELOW THIS LINE-----------------------

===BEGIN CRASH DUMP===
eNrtO9ty20aWv9KhUjtyiiABXsRLSqlVZHusXTvmWvL6IZhSNYEm2RGAhtENUXTK/77nnG6AAE05
noy2ah7iFxF9Ofc74N87RqaiMw/Gvj8LRrPJpNtJuDYvikIVnfnvHbPLYbuTKSMj0el2UqE1X+PS
O2HKImP3PCkFUyuWq+hOmFRmIgxFZqTZheGrMuXZfL4W5h3fvs/kx1JcxafPWFpqw5Z0zWwEQyRM
m0Jm6y7LyiRhBQEXMWBcwfNLmSDKfMOLeb/f36hU9Nc6vw1G03F/PextUi2K+54ovQC4GPUXRMsb
oMV7s+jhtb4uov6exL6lsE8EwoEcEVkkXzkIhxJYA3H5w27HFBxEMv+1c+Kzg0vXQI0oTgeD8ejZ
/HHJeD8dSgYwnASH0BYJ3wG04Wg6O4Bm8Xg/FSJV9+JthtS5081jdomp5W8iMoRj8CjFs+AAh73s
/RQlSotTqyXWdepir9VaZgyNSJUW9PAx0KPxY+RHGxHd3cjo7n0ecyP0qcyMWAPFwPFkMOyyWJXL
RLC9lfZGs8GY0I0e5WQQPIIOTPnOinr82OXA979yeVGoCPxAFRbK2SNQgrPp4BEo2vDC2NuTL9Rd
G+/p2H+Mh9vbSGWggzIypz9zLS7Ba/VrxeNaz93WvdLIRIfhGy4zUNm6ccop8l/xrRrIH9/+J47m
SQm2pfskpSn7M5SdovgK8bGURW26TxhE9icwhDzr/ONztyP+jSLnPxXQgHYr8c58xRMtup1IxQI5
mY0ASmjYD304PxvTQw4OKSO2KrPISJUxIHRP5e947ozOhcYSxL43G6m9n8pSxj/i9oS2P+PPKfzE
vzNa6v/wAzyAAzqk7D8dBMsm7QUNggJ/8BhFbdHNHYTf6dLwKHkF3Hh/9fxHOjKqSQz8saUx8M9a
RE5qInNe8LQy7u/hL+1PH9u/k9lVTEdmTV4C/ygvWphruHGKcLvVbRJzEASOEbk6/c7G6vlc6v/l
iYzrO8/c2YE7GxqzKdSWZWLLwvAqu6fTBmLvi4dI5IjzNOxc5yKSKylihgiZ1AyMmdHZbm2I0/+W
PzNVsOAMfoSdZyS6oJLu587nvxLlX4nyr0T5V6JsJcpuZy0yUfAE80vGsQXptMAAK6A+DYEIdoLe
WW8Qi3tYXJYyiTvzoT+FdFUooyIFMCDgdDs8l3B22PN7vnfxevHqYgLn19LA4mo4ENOpPx4N/CiY
THg0mgHpYLzTpT8NxmeDydSfjgYBXCj4XSKXcMfvTXs+LJSOvNcyKx9Ypof+YDiYBD2Ze8E48Ka+
Nxj6IAw26o16wcxLVexpE3syvz/zzkYMwtT1mwV7A2H8olyzwYAFw7k/nvsBu3xxfcMGfnDGHqZn
t2cjwIatyLwzASYCJP+TyOKKKbt7q3RFDCzQQ0IPdf7WKNNFWYiFKFLdFHC91hYukO2BdJF7XpqN
KjQG67PRy5e+z/6DgROjA1xlK5lBSEblkah/bcsalkXGIfoAweBuUD/EIgfyERjsabUyz5sLKcdS
o3Nr8UD4rKhr/MT6BFwVaX97ffPh7bvXz2FpK5ZaGuRoY0yuwUZBy5ty2YtU2qe7ziH2cEA4Pydg
XwthmhLZr7UlEpC0G8Kgg69UIT9BMHliCbRgh2FNUxjaMPVHQkDmroxILyG6LV40uGssfsHeEYVD
Xi+Tp1avBRqGQGoaAS25sLH1W5h6yan60WCADa6aq4d2PDrC1o2AQrkQ8W2XvVLaQGS7MhdJgsby
xLw2KAtD9/CtvF7LdbZQhWlFxMbioQKHRzidzRKhsmjDoUp+Ws5quLMZZNaaqm9T5REnbVDabzAJ
crhItnynr3O+zRqCaK42JTHoDY5KYrGRiczZNfxJ5JNLIyfo2gEPQ07UaaTuS5+9vrl4d/N+8YXC
L4Ez6Ah4k8392lF/bfN4ueHJHbj20/IWIdQwjCpKwrBJ1B/qGdRMEHrQ+wKTN4XgGoLw5UZo02C0
vd5mdtA7UObF9hPfPnVYQpghdn9ER4R0fHtgupZpnogLILHlrPVim6Hp0fS6r3bYjeApbOqNWm9k
hKNI/v/A8p4+dOEGrV8x1GP5taa734DSEsorkeSiOCoat9X2Yb83ftJ01FTFN6SmDdH0p2MZT8Rv
PIsLBeAaNa9XVeVgY6Kfcm1E0f9CECC3hVyvd5fQTav0BYXEVoVybLdtXn5v0Bbccw6X/l4+dSY/
Qsm3eww0gdjQ80TfLBrctZYPYx55TZu3p+WoiT0MD2j5Q5Yg/pob9VzqSBVxM4i31v+grhTPCyXj
Q03BmQZ/Z+3HP88u4YKA3iQwDNOWCh9LVwte3Kmy6dTVSpvDcW/Y5vC3OCr4yjyxMTqoYZhbKr7V
ErFJwkGcAG+sUNCgoAfNJDikkQI7qpNF/cQuFTQ+a4bD1LAIsxNs5P6rTNhgxIIBdHHz4b6Rm+CJ
VJn4PCx9n09m9k9i/9x99539sap+RNWPgtm/wl24gZR7WS4Fmz9nLVBfg4HILTdeDgXVOXXnRJFI
VbHzEplKcz7wB6M3uLrdgFRgUZtztVrhCs8yVWYRxi4aZfFoI8W9SMEv9LnKCD5WOR523oLq2/Nx
QBj4g7ukz8c+wUoStfVWiVxvavj2Ms9kCl7WApiqZbWw5khuLM4JzEoVQE+95gBteBGD9dbP+X3u
bsdytZJRmZjd+YCg0ZjBqMLTwmDxr89xOQG2Eg8t+XyriiTer2kh4sYRHLCfP3/x8uL96xtctcbq
fSxFsXMo3VIRgTQcPfi7l3OtAXh8/gP9A5GURnma34uKdasrmZ83hyq4o2hA6TVZvpdi68WgLA4K
Op/iEg4E6nzT26UJWi5DR2ARGW0JnOP4GG2XgSRZa8QCtsxuoPARrBIN44Wg1woqA8M3ECdYhDZB
g16ZRUkZixh+sC98BmFdq7R6L3EIU/OV6DKFjZhGkGwJhdcd24HnOlhMrhiwa8fNgEoVUJUZSM8A
+BexrcH1Y7HioF7Ntir7m2E8zwUvGIo2BWYjMLsdkM9wnG/53m5Exsp8XfAYAPTCDAVvgc3DjJ3c
bCBBewksARUJdCQlXwuG7z5IZE5JWsIzdOZQNHwioeLVSxzHWi7aF4GAqlIQWW8r72QuYsl7qlj3
8an/GhR5q1a3V9dvb8+GM29wi/dAjDWgOQshMq7DDiL6sKEmlhkF9GQxAy7deBDUVPBMJ9yA3Gib
pEmUCpzLA2OkUsilMhIM8nackJJTAGy9a4+SXvzAut6UJlbol/alFRJjB6qMptuxJesCfZxhBKF5
oS142L3k7H/QP+AI+UlVCs0ZRni8eL2BexytVCugxmGxquIOECs1GCFkAzAE4u5icQUnIbHEKKf9
hgdkLYGoPfgX5JEVHOCYYbBgYK5gEUjqcsecHcFx57/17l4MJx+gxQNlgknxOGaF0NbykEwcbwM5
1D5ggMTXI0uB8gChi48lT1Ada3kvqjd9pw4lJIpnANzig7ghMFh7oE2cNs9hFzH/UqZLnD2v2IXe
ZdEN13dg8cUdOFAP99+DEsg+Kybx1KZQEMDBJOC07jKKbMxFQDDZLoghBalpzNYkFkiNuJaWGXgO
HiHY12QywA84V6EeIFobASIAdsjUs5o0lKol52qFHopH0BO7TJq/geRMQbdigcmCrPDgLjsFDkDP
bIASIR48x+WcIKG32uxFvvr3RC1BsFgVMLvMKKlhTErFmi93Bghi15YUn5BLjeq1ng48bSURRsJm
mKJccnRLmuSykmAuEKYgBWQEagUxosJo1Q/MlGS0awV8KHQNlBngWRORNtvOmR9SqKCobCDU8Pjf
nHyssL5CPKbef4l4aCBywu9CVU2Pg6YZuBTmTogyjhrEWZEUQPliqVqIQipKR+iLGhHS+7GKutrf
AkAFoSZGG6MTHviDsJ5GYVxB3Z+Bh4LcMDo8JlYrTiibEorw6Ov2WEgJF2GA9+092YYjxPAWQwhm
ODre+/Iwsu3qYBChe++qSSxIq5WxvVszAJIUud6zOfQdn/rZUYIc10PL9ZoXS9C/F6kksaUcethR
qZI5ISnuDnN3wHdTnpWUcptUQDlSgi0861Yx4cAYnDXYuLpaVbEh3VtZj721+Y6ewCI2qkzimhAJ
EWSbsT3paLcsJ8qBwTPftzyyk5fkCV/ERrIVe7tmalWotAqxeNfte82o1NApMOFUd2gKR+yncQ8r
5WhTZnfayvsNhwBbppBcMnwlWVV4yA2zFbX1kD0KtBUHl1yEETgP65sSwubIkfdc2Y1DrWHsxwLJ
QsCjlX1YOO7YE7BK+ceLOE7XiFlnAhUi3KiT9ldBhVkmDKqgrtjAIhKbAJfcQJuC9QfH4hbyHpiR
C0bkd7Yedbs2Bi1FnQpJhCfNqFXtoL8XO7Ohb2u8oGHDmPIIrWcqUiCajM9sMNmnWGohML/FVodY
u1H5gXdh0dHUY6+gSwLxnkMJDPZ6uXjfhbtAwRLCzlbGZmODNbl1Dd4j8HM2cfXAvlLQJJjG0R67
iMGNNjxZ9aG2t8VLLMC8HCJAybB1Rg03/LBOyg1YjfLoxQP6HFY/POlaf0bEH2QGxSOwBWYjyNcw
xb9fZIuqQNiX6lj74KUthPgQ6/Qs99xjsxSDxk4sy7VVv3KhkmGSKMigxYOISlvjYMzB16a9elej
RVDpkm/ynswkkhEQb9UJ64sfeJFhmG7cxO7FBWaE4gB0WQzpApnZn0w5eGYKKjUoxKLM8FsPdGNg
JyWXBshVjEd0wGPmyZXn1vaeUNWv9I0O2ouoPspxtWcD64pLED0ZNXXcTC0N6A9vkS1B7QUniHii
o3Z/CLgru1ND67JlaYiPiKPGeJWio4LrDdHcKPTsR2JwCPlAfJVnFVxqQgj5CS1qtWcEa5KKF4JH
O1691rAtQPQTC7CSdGUDtgxkBFW7QGpFPlwbETqHm5NunRA160NANSWEhf46sg4E2oj1HlWY2Tg7
ty2dglYCxVw1XKJqJigWx9yAWPi9bSXxVz0twa1aiRzUD3FOcDOv5OYE5io4qozBp6im0LlARUCN
kakI31zRTfCgN7Uy8Lsl12foUmAcg6igseVe4gtjtAwZbchesWHfgZJse56QWSZ02Vmenc1UEC2Z
DYE0qUUj1haFbdq1lQm2PU4mukZKgFAyDbqfjFy0J04kNKJCNbNp9fOiau6YNXk7yaCjLv6X2jWb
EcAzlALcFc9embMcrOReJtTmtiIWvbUUFTiKpFSNgVgwcqL3QWXpqifM4rYoQ5vA+Q+uu0qsMpXW
clXn2jbwGlMW2viSa9FAdhpAsjiCpcsGsBEc2xAm6j2jxKVFkwpyFvymjKYKlUoFJGeLDy3UCovm
N/vBDiZDCjnYOKCi7HtQC9vBaajKJn2XAqtA7oTp4kyGsk8OS6Fudao1Ajs6hqJe9CJVEHypx6Q6
C9MuRayKN5QKEolNOPgt/qSyiZ28oxqqcZUsJxN2trIUFtRSrDC00uQSoxrqx8LGiEDzzEYxBkqE
IGGDqcTxkcBxRL6rPuG1RVpd4FMGXdHroqpecPl9VSZ0TGmT7DyMajKyNRalhQLnU4aIrxj9TeFk
wFbXmqeCvBljIFZeVRW6D7lHaoiKZmTTicQuZ26YVtUHtgQVH8HXzRdKRwlXSod6l/FDDeX2O0GQ
TG13beX4R7XDC4AT08SIgjPoyF119m2VMMTMgHNor7SfTe55jhLBLRIahO9HSFfPCZELVhii0IBs
MgcXhAInZY4tZnNZVdzSlSbL7MQDrzxha8iiei+U/VymkkvvS8G4DLflkkZsIF5bd4ApuvsUvGjd
02Bbczb9U9BylZeJg+Z+Y4l5ADjMKK54uc2WdpLvkcmjsWPbBfaJib+oVwMX4jBVzpntzSoLBOln
ZT5nM9uwWd+hAGgrMgcLoIzpmsO4f95yRFWvBvZQupTgp1WrS/HVTtnmNqbiQBBLGmZXrU07G7T+
dliTocF7OKJtr9SJp7UKRSJWW3sr2yg0LVtFNSb20NMQfZnKdik26uTTGkSsa0Jx8uC22X6bCKZS
hK/XhVi78V49OMV2D7+6vjvOjaUHwelj9KC8rKeQlg9vg1nY3XldxboKbF/C0qrKGyPfS5z60xha
JCrH7A7lJhSnOC7FxG67KiiIVqKAvtbDmJ9hMYeHXEFYaioim0CYe/nYKBRL6B21sUmjCs8OGmrI
blfw9YFQttvtEZFA3KzrC1chIlS8UrU3qBFMUIiReg13p5oa92oUbqOXpyk0EzTirOT31QrUJUlS
m7NcG32aRTBAN1aUJ7+8vXkxxzc8do3CFU4TXJnu4hWOtdfQbVEbKFc1nEglwMW+tmt0LgTOReaq
Q4ckAXWFldCLB44VnH3Auh3oc2qaV/qiLYgIOA2cs1+pjoZqokvjwX8gRJvZqpKu+UaJOMCRZYEv
ZWgwVb3lo+bkWGVAxTWVK5oaXWqQQC8SCHW1XIN0wkoE0C+GLwUxvlE632Obs5evL27mgx8n3fHs
IegOH4bdwY/BjzGUXDa0n+LXHxGG4fOpbzOAfRqNn9ELPPFgoJjGVg5frV9CXdH8/Be9rPmcR+19
/TGRRgzpa+WJ+0Tsk/18uT6zjKB23TRX8NVQFvOiteb+u9J+oSyS5vNKJka0rqxM61Plddx6Slub
Gwh99msVePhN1x9s4mO6dP+zp3E+jYpdbpor14vXbUlkpkUfVoXAU4uIXGn50FpwA0X6pDro4ZcV
78TKTcVa0DapajGgKSboFo07ED99nu1+sTFuDVAPzMPPAcb+yJ/Az++vwHqW42g888/i0Xgg8Ndk
OOCz4dIfB6vhdDAR/mAymi2nQ/Y9wF5sSD0D93WPUXcigyTckv8HaIUgXJLyh/TZxY7TO+CB+4bk
k8ztVyfD3riiV+4hfP78fznCcsM=
===END CRASH DUMP===

**Comment by dktapps** [comment]
This issue was fixed in 6ff92f2adf785a7c3b279081f8901841211ba850, however I'm leaving this open due to the wide range of potential other issues that could arise due to the current bad design.

**Comment by teracube** [comment]
Hi,

Is the bug fixed because today my server crashed with  :

PocketMine-MP_1.6.2dev-311_7d777510_API-3.0.0-ALPHA7.phar

Error : 

2017-07-26 [13:09:17] [Server thread/CRITICAL]: TypeError: "Return value of pocketmine\entity\Human::getRawUniqueId() must be of the type string, null returned" (EXCEPTION) in "src/pocketmine/entity/Human" at line 103
2017-07-26 [13:09:31] [Server thread/CRITICAL]: [Network] Stopped interface pocketmine\network\mcpe\RakLibInterface due to Return value of pocketmine\Player::getDisplayName() must be of the type string, null returned
2017-07-26 [13:10:19] [Server thread/INFO]: [CONSOLE: Stopping the server]

Thanks

**Comment by dktapps** [comment]
@gizanopatrica 
`version: 1.7`
For future reference, we will not provide support for third-party modified variants of PocketMine-MP.

**Comment by gizanopatrica** [comment]
@dktapps Yes, apologies for that - I use my own fork in which I edited the version and support for any plugin API version...

**Comment by bettylovedertderrdy** [comment]
genisyspro better !
