### ISSUE TITLE
Players can pickup dropped items before dying of fall damage

### ISSUE THREAD

**Issue by eternalharvest** [pmmp/PocketMine-MP#1226]
### Issue description

Player can take item entity even if player is already dead.
And there are items u have taken after die in ur inventory slot after respawn.

**Expected Result:**
No item in the inventory after any user was respawned.

### Steps to reproduce the issue

1. dig a very deep hole enough to die
2. drop all items u have into the hole
3. jump into the hole

From now on, u would be die and take item entity which u dropped in the bottom of the hole...

4. Choose respawn on the screen

There are some items in ur inventory which has taken after die  O.o

### OS and versions

* PocketMine-MP: master branch 1a7f567a70c58b0848def59118aad16557750ff3
* PHP: php7.0.3
```
PHP 7.0.3 (cli) (built: Feb  7 2016 21:08:57) ( ZTS )
Copyright (c) 1997-2016 The PHP Group
Zend Engine v3.0.0, Copyright (c) 1998-2016 Zend Technologies
```
* Server OS: Ubuntu 16.04 LTS
* Game version: PE v1.1.3 (iOS)

### Plugins
- Test on a clean server without plugins: is the issue reproducible without any plugins loaded?

Yes, I tested it on a clean server (newly created world).
here is the result of /plugin command.
```
plugins
[00:05:01] [Server thread/INFO]: Plugins (0):
```
### Crashdump, backtrace or other files

There is no crashdump or backtrace related to this issue.

**Comment by dktapps** [comment]
This is because death due to fall damage does not occur until and unless the player has had their movement processed, and there is no additional checks for whether the player is dead at that point.
