### ISSUE TITLE
logged out dut to login timeout

### ISSUE THREAD

**Issue by projectgus23** [pmmp/PocketMine-MP#1228]
### Issue description
Im brand new to creating a pocketmine server. its a fresh install no plugins, port forwarding is done, anytime i try to connect to the server my phone says disconected from server and the server says logged out dut to login timeout. any help would be greatly appreciated.

### Steps to reproduce the issue
start server
try to login from iphone
get disconected

* PocketMine-MP: ? um 1.6
* PHP: ? i believe 7

This server is running PocketMine-MP 1.6dev-# πÇî[REDACTED]πÇì implementing API version 2.0.0 for Minecraft: PE v0.15.0.0 alpha (protocol version 81)

* Server OS: windows 10
* Game version: PE
playing on iphone ios 10.3.0 
using app minecraft pocket edition v1.1.4

**Comment by dktapps** [comment]
This is not a support forum. Read the README.

**Comment by projectgus23** [comment]
ok where is the README

**Comment by SalmonDE** [comment]
Your PocketMine version just seems to be outdated. Please doublecheck that next time.
Also, you can usually get the latest version from the pmmp jenkins: https://jenkins.pmmp.io/job/PocketMine-MP/

**Comment by projectgus23** [comment]
Thank you I will go to those places. And I'm sorry too. I'm new to all this and forums in geaneral.
