### ISSUE TITLE
Allow us to unregister default commands via plugins

### ISSUE THREAD

**Issue by mal0ne-23** [pmmp/PocketMine-MP#1229]
I think default commands should be able to be unregistered

`$map = $this->getServer()->getCommandMap();
foreach(["help", "me"] as $name){
 $cmd = $map->getCommand($name);
 $cmd->unregister($map);
}`

That does nothing, but it should unregister that command? This method works for plugin registered commands, why not defaults?

Right now I just // comment the lines out that register them in my source code because I really don't want them registered. And if I do want to override them I don't want to have to do it all in one spot in my plugin, as that just looks ugly. I wanna register it where I want to in my plugin.

**Comment by xinghao2003** [comment]
```
$commandMap = $this->getServer()->getCommandMap();
$commandToOverride = $commandMap->getCommand("help");
$commandToOverride->setLabel("help_disabled");
$commandToOverride->unregister($commandMap);
$this->getServer()->getCommandMap()->register("help", new HelpCommand());
```
This code works well

**Comment by Sandertv** [comment]
https://github.com/LegendOfMCPE/EssentialsPE/blob/EssentialsPE-3.0.0-Rewrite/EssentialsPE/src/EssentialsPE/Commands/Override/BaseOverrideCommand.php#L14-L17

**Comment by SalmonDE** [comment]
Another good place to look at: https://forums.pmmp.io/threads/is-it-possible-to-unregister-a-default-command.429/

**Comment by Muqsit** [comment]
He probably meant to literally unregister it (without overriding).

**Comment by Sandertv** [comment]
If you don't want a default command nor do you plan to overwrite it, you can just overwrite it with an empty alias in the pocketmine.yml.

**Comment by mal0ne-23** [comment]
I would like to remove the commands without having to do all this hacky stuff. I don't want the commands appearing in the command list, and I don't want to have to override them with another command. I want to completely remove these commands.

**Comment by MattWAnderson** [comment]
I know it isn't a code fix, but on production machines that I don't want these on I just remove them from the simple command map.

**Comment by TheDiamondYT1** [comment]
@MattWAnderson Why?

**Comment by MattWAnderson** [comment]
Simple way to remove it from the command listings and disallow use without coding something to overwrite, or allows me to use it for other reasons in my plugins for custom banning tied to mysql db of player accounts, and banning with logging of who and for what reason.

**Comment by TheDiamondYT1** [comment]
@MattWAnderson I just use this:
```php
private function setupCommands() {
		$commandMap = $this->getServer()->getCommandMap();	
		$this->unregisterCommands([
			"ban",
			"version"
		]);
		$commandMap->registerAll("example", [
			new CommandVersion($this),
			new CommandBan($this)
		]);
	}
	
	private function unregisterCommands(array $names) {
		$commandMap = $this->getServer()->getCommandMap();
		foreach($names as $name) {
			$command = $commandMap->getCommand($name);
			$command->setLabel($name . "_disabled");
			$command->unregister($commandMap);
		}
	}

```

Ignore the bad indentinf

**Comment by MichaelM04** [comment]
@mal0ne-23 Might not be the solution your looking for, but what I did to do this is add to my custom Player::class under sendCommandData() check if the command name is in an array of disabled commands, if so, unset the command from the packet, therefore the disabled command doesn't appear to the client.

**Comment by mad-hon** [comment]
Thank you!
