### ISSUE TITLE
It looks like spawning of most creatures does not work 

### ISSUE THREAD

**Issue by jrhagaky** [pmmp/PocketMine-MP#123]
### Issue description

When using Minecraft PE v0.16.2 and connecting to a PocketMine server I am not able to spawn creatures or animals.  

### Steps to reproduce the issue

1. ...
2. ...

### OS and versions

* PocketMine-MP:
* PHP:
* Server OS: This server is running PocketMine-MP 1.6.1dev 「Unleashed」 implementing API version 2.1.0 for Minecraft: PE v0.16.0.5 alpha (protocol version 91)

* Game version: PE v0.16.2

### Crashdump, backtrace or other files

* Game ignores request to spawn Entities
* Noticed that by adding the correct NETWORK_ID of the creatures to the existing entity classes, registering the Entity in Server, and implementing some methods such as getName and spawnTo appeared to get the creatures onto the map.

**Comment by JackNoordhuis** [comment]
There is no AI for any of the mobs so there is no point registering them just so people can spawn what is effectively just a model (knock back won't even be applied properly sometimes).

You're going to have to wait for mob AI to be implemented or find a plugin to implement its own AI. The development team is focused on keeping the software up to date and fixing bugs right now.

**Comment by jrhagaky** [comment]
Understood.  Needs Mob AI or it wouldn't be as fun.

**Comment by IISweePII** [comment]
There is many issues with entities, even when testing em, especially a few mobs like witches that glitch when hit (fall down to void)

**Comment by dktapps** [comment]
Entity re-implementation is a TODO for a future 1.6.x release as per PocketMine/PocketMine-MP#3149

**Comment by IISweePII** [comment]
Interesting, I did notice a weird event with bats, they can move up and down normally, except they only move in 1 direction, and are completely in-animated

**Comment by IISweePII** [comment]
At least it will be implemented correctly in the future, except what happens when another new update comes after xD

**Comment by Sandertv** [comment]
Try this plugin:https://github.com/RevivalPMMP/PureEntitiesX
I'm actively  wokring on it with @Magicode1 , so it'll be made better in quite a short time.
