### ISSUE TITLE
Impossible to craft something

### ISSUE THREAD

**Issue by SuperMaXAleX** [pmmp/PocketMine-MP#1230]
### Issue description
[ONLY ON THE api3/blocks]
The title says everything. I can't craft something, expecting planks.

### Steps to reproduce the issue
1. Try to craft something (not planks)
2. This will be cancelled

### OS and versions
* PocketMine-MP: https://github.com/pmmp/PocketMine-MP/commit/e39276a3ef4530c04cfdea0b86ad92f3717fb0f4
* PHP: 7.0.3
* Server OS: Mac OS X 
* Game version: PE

### Plugins
Tested with & without plugins.

### Crashdump, backtrace or other files
* An exemple, when I'm trying to craft a crafting table : 
`[Server thread/DEBUG]: Unmatched recipe 02395836-a24b-37db-87c0-33ae2135a762 from player SuperMaXAleX: expected Item Crafting Table (58:0)x1, got Item Oak Wood Planks (5:0)x4, using: Item Oak Wood (17:0)x1, Item Air (0:0)x0, Item Air (0:0)x0, Item Air (0:0)x0, Item Air (0:0)x0, Item Air (0:0)x0, Item Air (0:0)x0, Item Air (0:0)x0, Item Air (0:0)x0, Item Oak Wood (17:0)x1, Item Air (0:0)x0, Item Air (0:0)x0, Item Air (0:0)x0, Item Air (0:0)x0, Item Air (0:0)x0, Item Air (0:0)x0, Item Air (0:0)x0, Item Air (0:0)x0, Item Oak Wood (17:0)x1, Item Air (0:0)x0, Item Air (0:0)x0, Item Air (0:0)x0, Item Air (0:0)x0, Item Air (0:0)x0, Item Air (0:0)x0, Item Air (0:0)x0, Item Air (0:0)x0, Item Oak Wood Planks (5:?)x1, Item Oak Wood Planks (5:?)x1, Item Air (0:0)x0, Item Oak Wood Planks (5:?)x1, Item Oak Wood Planks (5:?)x1, Item Air (0:0)x0, Item Air (0:0)x0, Item Air (0:0)x0, Item Air (0:0)x0, Item Oak Wood Planks (5:?)x1, Item Oak Wood Planks (5:?)x1, Item Air (0:0)x0, Item Oak Wood Planks (5:?)x1, Item Oak Wood Planks (5:?)x1, Item Air (0:0)x0, Item Air (0:0)x0, Item Air (0:0)x0, Item Air (0:0)x0, Item Oak Wood Planks (5:?)x1, Item Oak Wood Planks (5:?)x1, Item Air (0:0)x0, Item Oak Wood Planks (5:?)x1, Item Oak Wood Planks (5:?)x1, Item Air (0:0)x0, Item Air (0:0)x0, Item Air (0:0)x0, Item Air (0:0)x0, Item Oak Wood Planks (5:?)x1, Item Oak Wood Planks (5:?)x1, Item Air (0:0)x0, Item Oak Wood Planks (5:?)x1, Item Oak Wood Planks (5:?)x1, Item Air (0:0)x0, Item Air (0:0)x0, Item Air (0:0)x0, Item Air (0:0)x0, Item Oak Wood Planks (5:?)x1, Item Oak Wood Planks (5:?)x1, Item Air (0:0)x0, Item Oak Wood Planks (5:?)x1, Item Oak Wood Planks (5:?)x1, Item Air (0:0)x0, Item Air (0:0)x0, Item Air (0:0)x0, Item Air (0:0)x0, Item Oak Wood Planks (5:?)x1, Item Oak Wood Planks (5:?)x1, Item Air (0:0)x0, Item Oak Wood Planks (5:?)x1, Item Oak Wood Planks (5:?)x1, Item Air (0:0)x0, Item Air (0:0)x0, Item Air (0:0)x0, Item Air (0:0)x0`

* After debugging the CraftingEventPacket, the problem is coming from there [LINE: ~2751 on Player.php] : 
```
if($item->getCount() > 0){
	$canCraft = false;
	break;
}
```

**Comment by dktapps** [comment]
Please revert 03416061ef1f179ee8f6c80eddd385e3435ccedf and tell if the issue still occurs.

**Comment by SuperMaXAleX** [comment]
@dktapps I still have the problem.

**Comment by dktapps** [comment]
I can reproduce the bug, but reverting commit 03416061ef1f179ee8f6c80eddd385e3435ccedf fixes the issue for me.

**Comment by SuperMaXAleX** [comment]
I'll try again, maybe I did something wrong

**Comment by SuperMaXAleX** [comment]
I reinstalled PocketMine, revert the commit, but I still have the issue. Really really strange.
I tried to debug again and I have the same debug message, and it is happening at the same line.

**Comment by SuperMaXAleX** [comment]
I still have the issue.

**Comment by dktapps** [comment]
Please join our Discord at https://discord.gg/p6AfR so we can discuss this.
