### ISSUE TITLE
SetEntityMotionPacket is break?

### ISSUE THREAD

**Issue by Pab450** [pmmp/PocketMine-MP#1238]
### Issue description

Info: Starting Minecraft: PE server version v1.1.0.55, This server is running PocketMine-MP version 1.6.2dev "Unleashed" (API 3.0.0-ALPHA7).

Error: Argument 3 passed to pocketmine\network\mcpe\protocol\DataPacket::putVector3f() must be of the type float, null given, called in /Users/Pab45O/Desktop/PocketMine-MP-master/src/pocketmine/network/mcpe/protocol/SetEntityMotionPacket.php on line 46

SetEntityMotionPacket.php line 46: $this->putVector3f($this->motionX, $this->motionY, $this->motionZ);

My code:
` $pk = new SetEntityMotionPacket();

            $pk->entityRuntimeId = 1000000 + $i; 

            $pk->motionX = 10.6; //float ? 
            $pk->motionY = 10.6; //float ?
            $pk->motionY = 10.6; //float ?

            foreach($this->getServer()->getOnlinePlayers() as $all){
                $all->dataPacket($pk);

            }`

($pk->entityRuntimeId = ItemEntityPacket entityRuntimeId)

Actual result: What actually happened?
- Send Error "Critical"

### Steps to reproduce the issue
- Use this code.

### OS and versions
- his server is running PocketMine-MP 1.6.2dev 「Unleashed」 implementing API version 3.0.0-   ALPHA7 for Minecraft: PE v1.1.0.55 (protocol version 113).

* PocketMine-MP: PocketMine-MP 1.6.2dev
* PHP: php7
* Server OS: MAC OS X EL CAPITAIN 10.11.6
* Game version: PE and Win10

**Comment by dktapps** [comment]
You've written to motionY twice and not set motionZ. Do not use the issue tracker for plugin help requests or you will be banned from the repository.

**Comment by Pab450** [comment]
IM STUPIDD  FUCK MY BRAIN IM SOO SORRY
