### ISSUE TITLE
Player head rotation is ignored

### ISSUE THREAD

**Issue by dktapps** [pmmp/PocketMine-MP#124]
### Issue description
See comments on https://github.com/pmmp/PocketMine-MP/commit/8d842732e00f6404b0c63c72bc421d971ecff9f1 . This is here as a reminder.

### Steps to reproduce the issue

1. Login.
2. Move your player's head, and watch from another client

### OS and versions

* PocketMine-MP: 1.6.1dev-#87
* PHP: 7.0.12
* Server OS: Windows 10 Pro x64
* Game version: all

**Comment by iPocket** [comment]
You've made that, though.

**Comment by dktapps** [comment]
@iPocket yes, I know... genius you are for noticing that. I can't fix it now because my working dir is full of 0.17 mess.
