### ISSUE TITLE
(api3/blocks) Potion bugs

### ISSUE THREAD

**Issue by IrishPacks** [pmmp/PocketMine-MP#1241]
### Issue description
Drinking more than one potion with multiple open hotbar slots results in glass bottles glitching out and fake stacking until you open and close your inventory.

Expected result: What were you expecting to happen? The glass bottles to stack
Actual result: What actually happened? They move inventory slots and look like they stack, but really just glitch out until you refresh your hotbar.

### Steps to reproduce the issue

1. Have an empty hotbar(put the potions further down in your hotbar)
2. Drink more than one potion

### OS and versions
* PocketMine-MP: db12657
* PHP: 7.0.3
* Server OS: Linux
* Game version: PE/Win10

### Plugins
- Test on a clean server without plugins: is the issue reproducible without any plugins loaded? Yes

### Crashdump, backtrace or other files
N/A

**Comment by Megalunchbox** [comment]
Yeah this happens all of the time in potpvp i can confirm

**Comment by thebigsmileXD** [comment]
As far as i can tell this seems to be fixed.

**Comment by IrishPacks** [comment]
Potions aren't implemented on the master branch, as this is a branch-specific problem. Although, it could be fixed with the new inventory changes, but I wouldn't put money on it.

**Comment by thebigsmileXD** [comment]
If you need it branch-independent: https://share.wolvesfortress.de/potions_v0.1.0.phar

**Comment by IrishPacks** [comment]
I'm okay, I know how to make plugins.
