### ISSUE TITLE
non of ban commands are working!

### ISSUE THREAD

**Issue by optimusprime338** [pmmp/PocketMine-MP#1242]
### Issue description

 ban commands are not working.

### Steps to reproduce the issue
(dawn to up):-
```
25.07 22:41:33 [Server] Server thread/DEBUG #10 /PocketMine-MP.phar(1): require_once(string phar:///PocketMine-MP.phar/src/pocketmine/PocketMine.php)
25.07 22:41:33 [Server] Server thread/DEBUG #9 src/pocketmine/PocketMine(511): pocketmine\Server->__construct(BaseClassLoader object, pocketmine\utils\MainLogger object, string phar:///PocketMine-MP.phar/, string /, string /plugins/)
25.07 22:41:33 [Server] Server thread/DEBUG #8 src/pocketmine/Server(1680): pocketmine\Server->start()
25.07 22:41:33 [Server] Server thread/DEBUG #7 src/pocketmine/Server(2098): pocketmine\Server->tickProcessor()
25.07 22:41:33 [Server] Server thread/DEBUG #6 src/pocketmine/Server(2219): pocketmine\Server->tick()
25.07 22:41:33 [Server] Server thread/DEBUG #5 src/pocketmine/Server(2442): pocketmine\Server->checkConsole()
25.07 22:41:33 [Server] Server thread/DEBUG #4 src/pocketmine/Server(1918): pocketmine\Server->dispatchCommand(pocketmine\command\ConsoleCommandSender object, string ban steve)
25.07 22:41:33 [Server] Server thread/DEBUG #3 src/pocketmine/Server(1933): pocketmine\command\SimpleCommandMap->dispatch(pocketmine\command\ConsoleCommandSender object, string ban steve)
25.07 22:41:33 [Server] Server thread/DEBUG #2 src/pocketmine/command/SimpleCommandMap(237): pocketmine\command\defaults\BanCommand->execute(pocketmine\command\ConsoleCommandSender object, string ban, array Array())
25.07 22:41:33 [Server] Server thread/DEBUG #1 src/pocketmine/command/defaults/BanCommand(55): pocketmine\permission\BanList->addBan(string steve, string , NULL , string CONSOLE)
25.07 22:41:33 [Server] Server thread/DEBUG #0 src/pocketmine/permission/BanList(105): pocketmine\permission\BanEntry->setExpires(NULL )
25.07 22:41:33 [Server] Server thread/CRITICAL TypeError: "Argument 1 passed to pocketmine\permission\BanEntry::setExpires() must be an instance of DateTime, null given, called in phar:///PocketMine-MP.phar/src/pocketmine/permission/BanList.php on line 105" (EXCEPTION) in "src/pocketmine/permission/BanEntry" at line 74
25.07 22:41:33 [Server] Server thread/CRITICAL Unhandled exception executing command 'ban steve' in ban: Argument 1 passed to pocketmine\permission\BanEntry::setExpires() must be an instance of DateTime, null given, called in phar:///PocketMine-MP.phar/src/pocketmine/permission/BanList.php on line 105
```
### OS and versions

* PocketMine-MP: 1.6.2dev+poggit.1256 「Unleashed」 (got commit:- db12657)
* PHP: 7.0.3
* Server OS: Linux
* Game version: PE/Win10 (delete as appropriate)

### Plugins
- Test on a clean server without plugins: is the issue reproducible without any plugins loaded? 
Yes

If the issue is **not** reproducible without plugins:
- Have you asked for help on our forums before creating an issue?
- Can you provide sample, *minimal* reproducing code for the issue? If so, paste it in the bottom section
- Paste your list of plugins here (use the 'plugins' command in PocketMine-MP)
- No plugins

### Crashdump, backtrace or other files
- Do not paste crashdumps into an issue - please use our Crash Archive at https://crash.pmmp.io for submitting crash reports to not spam the issue tracker. Add links to your reports in the Crash Archive here.
- Please use gist or anything else to add other files and add links here 
I tried alternate plugins like megaban,. client ban etc too . they are not also working . showing same errors.
* ...

**Comment by Driesboy** [comment]
Do not paste crashdumps into an issue - please use our Crash Archive at https://crash.pmmp.io for submitting crash reports to not spam the issue tracker. Add links to your reports in the Crash Archive here.

**Comment by optimusprime338** [comment]
that's debug report .. wdym?

**Comment by TheDiamondYT1** [comment]
True @Driesboy

**Comment by TheDiamondYT1** [comment]
Its not a crashdump

**Comment by TheDiamondYT1** [comment]
Also @optimusprime338 put your console log into code blocks
```
```
```
```
