### ISSUE TITLE
Critical Error: "Call to a member function getBlock() on null" (EXCEPTION) in "src/pocketmine/entity/Entity" at line 1411 

### ISSUE THREAD

**Issue by teracube** [pmmp/PocketMine-MP#1243]
### Issue description
Critical Errors :
2017-07-26 [11:47:00]  [Server thread/CRITICAL]: Could not tick level "world": Call to a member function getBlock() on null 
2017-07-26 [11:47:00]  [Server thread/CRITICAL]: Error: "Call to a member function getBlock() on null" (EXCEPTION) in "src/pocketmine/entity/Entity" at line 1411 
 
### Steps to reproduce the issue
unknown

### OS and versions
* PocketMine-MP:
PocketMine-MP_1.6.2dev-311_7d777510_API-3.0.0-ALPHA7.phar
--

### Plugins
PurePerms 1.4.1-dev1; BlockPets 1.1.0; ItemCasePE 1.1.0-dev1; FactionsPro 1.4.4-dev1; SignPortal 1.1.3-dev1; AlwaysSpawn 2.2.3-dev1; Cameraman 1.1.0-dev; TreasureChest 1.2.1; PureEntitiesX 0.2.2_dev; SimpleAuth 1.8.1-dev1; SimpleAuthHelper 2.0.5-dev1; PiggyCustomEnchants 1.0.2; essentialsTP 1.1.1-dev2; ChatToDiscord 1.1.0; Parkour 1.5.3

- Test on a clean server without plugins: is the issue reproducible without any plugins loaded?
no, sorry

Thanks for your job

**Comment by Driesboy** [comment]
I also have this error
