### ISSUE TITLE
Freeze server!

### ISSUE THREAD

**Issue by xISRAPILx** [pmmp/PocketMine-MP#1245]
### Issue description
The server just hangs, does not respond to commands, on other cores everything is fine!
There are no errors, debug nothing showed anything.

### Steps to reproduce the issue

1. ...
2. ...

### OS and versions
Debian 8 x64

NOTE: LATEST is not a valid version. PocketMine version should include Jenkins build number and/or git commit hash.

NO support whatsoever will be provided for forks or spoons of PocketMine. Issues relating to non-official distributions will be closed as spam. Please send such issues to whoever is responsible for the fork or spoon you are using.

Note that 32-bit platforms are no longer supported by PocketMine-MP and issues concerning 32-bit platforms will be closed.
-->
* PocketMine-MP:
* PHP: 7
* Server OS: Debian 8 x64
* Game version: PE/Win10 (delete as appropriate)

### Plugins
- Test on a clean server without plugins: is the issue reproducible without any plugins loaded?

If the issue is **not** reproducible without plugins:
- Have you asked for help on our forums before creating an issue?
- Can you provide sample, *minimal* reproducing code for the issue? If so, paste it in the bottom section
- Paste your list of plugins here (use the 'plugins' command in PocketMine-MP)

### Crashdump, backtrace or other files
- Do not paste crashdumps into an issue - please use our Crash Archive at https://crash.pmmp.io for submitting crash reports to not spam the issue tracker. Add links to your reports in the Crash Archive here.
- Please use gist or anything else to add other files and add links here 

* ...

**Comment by dktapps** [comment]
Without knowing your PocketMine-MP version, OS, PHP, Client version, or plugins and how the issue occurred, the issue cannot begin to be solved.
A pre-formatted template is provided that shows the required information to begin to find, test and solve an issue.
Until the adequate template and information is provided, the issue will be closed; it may be reopened if you update the ticket with the correct template and required information.

[Contribution guidelines](https://github.com/pmmp/PocketMine-MP/blob/master/CONTRIBUTING.md)

**Comment by xISRAPILx** [comment]
#1246

**Comment by xISRAPILx** [comment]
@dktapps This is not a modification, the error was before, why did you close the question?
