### ISSUE TITLE
Server sleep!

### ISSUE THREAD

**Issue by xISRAPILx** [pmmp/PocketMine-MP#1246]
### Issue description
The server just hangs, does not respond to commands
There are no errors, debug nothing showed anything.

### Steps to reproduce the issue

1. Enable server
2. whait...

### OS and versions
Debian 8, 6a191b506933cc32c54db47784cf854fb02db0c1

* PocketMine-MP:
* PHP: 7
* Server OS: Debian 8 x64
* Game version: PE/Win10 (delete as appropriate)

### Plugins
null

### Crashdump, backtrace or other files
null

* ...

**Comment by xISRAPILx** [comment]
#1245

**Comment by dktapps** [comment]
Your version is nearly two weeks out of date. Can you reproduce this with the latest master?

**Comment by xISRAPILx** [comment]
No, I chose the most optimal variant of the kernel. I've made changes to the kernel, adding blocks and more, but there can not be a mistake because of this, because it was before, but I did not pay attention! @dktapps

**Comment by dktapps** [comment]
We do not provide support for third-party modified builds of PocketMine-MP, nor outdated development versions.
