### ISSUE TITLE
Level->getSafeSpawn() crash with non-solid blocks

### ISSUE THREAD

**Issue by xXSirGamesXx** [pmmp/PocketMine-MP#1248]
### Issue description

Sometimes when you join it will crash the player and give out an error message in console. Only way to fix is by deleting data profile or wait a few hours for some reason.

There isnt a great way to reproduce this issue. it occurs on its own.
### Steps to reproduce the issue

1. ...Join server

### OS and versions

* PocketMine-MP: 1.6.2 (api3:blocks
* PHP: 7.0.18
* Server OS: Windows 10
* Game version: PE iOS

### Plugins
- Test on a clean server without plugins: is the issue reproducible without any plugins loaded?

If the issue is **not** reproducible without plugins:
- Have you asked for help on our forums before creating an issue?
- Can you provide sample, *minimal* reproducing code for the issue? If so, paste it in the bottom section
- Paste your list of plugins here (use the 'plugins' command in PocketMine-MP)
`[15:16:22] [Server thread/CRITICAL]: TypeError: "Argument 1 passed to pocketmine\math\AxisAlignedBB::__construct() must be of the type float, null given, called in C:\Users\xXSir\Downloads\BCN\src\pocketmine\block\Block.php on line 877" (EXCEPTION) in "src/pocketmine/math/AxisAlignedBB" at line 43
[15:16:22] [RakLibServer thread/NOTICE]: Blocked 161.187.52.126 for 5 seconds
` Thats the backtrace, i tested without plugins.
### Crashdump, backtrace or other files
- Do not paste crashdumps into an issue - please use our Crash Archive at https://crash.pmmp.io for submitting crash reports to not spam the issue tracker. Add links to your reports in the Crash Archive here.
- Please use gist or anything else to add other files and add links here 

* ...

**Comment by dktapps** [comment]
#1213 . I forgot about this issue.

**Comment by xXSirGamesXx** [comment]
I also get a similar error when trying to teleport to worlds

**Comment by xXSirGamesXx** [comment]
I figured it out that it only happens when a player goes to a certain world.

**Comment by dktapps** [comment]
The "Debugged" label indicates that we already know the cause of the bug, but it has yet to be fixed.

**Comment by xXSirGamesXx** [comment]
Ok thanks. :)
