### ISSUE TITLE
#2011 Value 34970 is too large!

### ISSUE THREAD

**Issue by totor29** [pmmp/PocketMine-MP#1251]
### Issue description
server crash
critical error  #2011 Value 34970 is too large!

https://crash.pmmp.io/view/2011

-->
* PocketMine-MP: 1.6.2dev-315

### Plugins
cf
https://crash.pmmp.io/view/2011

### Crashdump, backtrace or other files
- https://crash.pmmp.io/view/2011

* ...

**Comment by Sandertv** [comment]
I'm quite confident this is because of PureEntitiesX.

**Comment by totor29** [comment]
Update

another critical error 
#2012 Value 32849 is too large!

https://crash.pmmp.io/view/2012

**Comment by dktapps** [comment]
Wow, two identical critical errors. That's amazing.

**Comment by totor29** [comment]
update :
 no bug on a clean server without plugins
i think it's a plugin probleme but which ?

**Comment by totor29** [comment]
Hi,

Please, find another crashdump about Value 33044 is too large!
https://crash.pmmp.io/view/2073

bug PocketMine or not, i don't know ?
pureentitiesx plugin were removed

PocketMine Version: | 1.6.2dev-319
PHP version: | 7.0.17
Linux ns3023271.ip-151-80-230.eu 4.4.19-mod-std-ipv6-64 #1 SMP Mon Aug 22 13:05:01 CEST 2016 x86_64

**Comment by dktapps** [comment]
This is not reproducible on a clean server without plugins. Therefore this is not a PocketMine-MP issue.

**Comment by SuperMaXAleX** [comment]
@totor29 Please, fix just your plugin(s). You did something wrong with packets.

**Comment by totor29** [comment]
@ SuperMaXAleX
thanks for your help
You think it comes from what plugin ?

Loaded plugins:
PurePerms 1.4.1-dev1 by 64FF00 & ProjectInfinity for API(s) 3.0.0-ALPHA7
BlockPets 1.1.0 by BlockHorizons for API(s) 3.0.0-ALPHA7
FactionsPro 1.4.4-dev1 by Tethered_, HostingItAll.com for API(s) 3.0.0-ALPHA7
AlwaysSpawn 2.2.3-dev1 by Philip Shilling for API(s) 3.0.0-ALPHA7
SimpleAuth 1.8.1-dev1 by PocketMine Team, shoghicp, awzaw for API(s) 3.0.0-ALPHA7
SimpleAuthHelper 2.0.5-dev1 by aliuly for API(s) 3.0.0-ALPHA7
PiggyCustomEnchants 1.0.2 by DaPigGuy for API(s) 3.0.0-ALPHA7
essentialsTP 1.1.1-dev3 by  for API(s) 3.0.0-ALPHA7
ChatToDiscord 1.1.0 by eDroid for API(s) 3.0.0, 3.0.0-ALPHA6, 3.0.0-ALPHA7
Parkour 1.5.3 by jdcraft for API(s) 3.0.0-ALPHA7

**Comment by SuperMaXAleX** [comment]
Maybe BlockPets, I really don't know.

**Comment by Sandertv** [comment]
It might be... I don't know though, I haven't ever seen that pop up from BlockPets yet though.

**Comment by Driesboy** [comment]
same

Op 30-jul.-2017 13:11 schreef "Sandertv" <notifications@github.com>:

**Comment by dktapps** [comment]
Take error trouble shooting to the forums, do not spam our issue tracker.
