### ISSUE TITLE
ErrorException: "Undefined variable: tickDiff" (EXCEPTION) in "src/pocketmine/entity/Entity" at line 1255

### ISSUE THREAD

**Issue by totor29** [pmmp/PocketMine-MP#1255]
### Issue description
Server thread/CRITICAL]: ErrorException: "Undefined variable: tickDiff" (EXCEPTION) in "src/pocketmine/entity/Entity" at line 1255

### Steps to reproduce the issue
?

### OS and versions

* PocketMine-MP: PocketMine-MP_1.6.2dev-317_87c16dab
*PHP version: | 7.0.17
*Linux ns3023271.ip-151-80-230.eu 4.4.19-mod-std-ipv6-64 #1 SMP Mon Aug 22 13:05:01 CEST 2016 x86_64

### Plugins
- Test on a clean server without plugins: is the issue reproducible without any plugins loaded?
no

PurePerms 1.4.1-dev1; BlockPets 1.1.0; AlwaysSpawn 2.2.3-dev1; SimpleAuth 1.8.1-dev1; SimpleAuthHelper 2.0.5-dev1;; essentialsTP 1.1.1-dev3; ChatToDiscord 1.1.0; Parkour 1.5.3

**Comment by AppleDevelops** [comment]
Why are you reporting a plugin issue to PM issue tracker? This isn’t a support forum, ask questions on forums.pmmp.io

**Comment by totor29** [comment]
sorry but witch issue plugin do you mean error came ?
thanks
