### ISSUE TITLE
Generator::getSpawn is not used

### ISSUE THREAD

**Issue by Tarik02** [pmmp/PocketMine-MP#1258]
### Issue description
Expected result: When override Generator::getSpawn and return any coordinates, level spawn will be there.
Actual result: Level spawn is always on coordinates 256x70x256(https://github.com/pmmp/PocketMine-MP/blob/master/src/pocketmine/level/format/io/region/McRegion.php#L255)

### Steps to reproduce the issue
1. Create custom generator with getSpawn returns `new Vector3(0, 35, 0)`
2. Generate world with the generator
3. Try to login to the server: you will be spawned on 256x70x256

### OS and versions
* PocketMine-MP: https://github.com/pmmp/PocketMine-MP/commit/aa6eef26e985ab9fc0c10e641666a4c5d0c37992
* PHP: PHP 7.0.17 (cli) (built: Mar 18 2017 15:12:04) ( ZTS )
* Server OS: Linux Ubuntu
* Game version: PE/Win10

### Plugins
- VoidGeneratorTest

### Crashdump, backtrace or other files

* [VoidGeneratorTest](https://gist.github.com/Tarik02/f7dc05c81553635965b52e16ddb5fe71)

**Comment by Ad5001** [comment]
Found a workaroud this, you can check if the player teleports to the world and set his spawn.

**Comment by Tarik02** [comment]
@Ad5001, YOU ARE GENIUS. I did this more than year ago...

**Comment by jasonwynn10** [comment]
Maybe `Generator::getSpawn()` should be made static for this to be fixed. I don't think it would break much in comparison to all the other API changes happening...

**Comment by Tarik02** [comment]
@jasonwynn10, no. It should not be static because server uses generator instance. Avoid static.

**Comment by dktapps** [comment]
This function was removed by 86a5a50330c5555e71aba73e5192a29f979de465, so this is no longer relevant.
