### ISSUE TITLE
My server was destroyed for a stupid bug caused by a bucket of water.

### ISSUE THREAD

**Issue by smakosav** [pmmp/PocketMine-MP#1264]
I accidentally dropped a little water, when it exceeds the limit, it appears again at the top, making it an infinite loop.
I do not know how to do I'm desperate.

# screenshot:
http://imgur.com/a/SRNjI

**Comment by dktapps** [comment]
Without knowing your PocketMine-MP version, OS, PHP, Client version, or plugins and how the issue occurred, the issue cannot begin to be solved.
A pre-formatted template is provided that shows the required information to begin to find, test and solve an issue.
Until the adequate template and information is provided, the issue will be closed; it may be reopened if you update the ticket with the correct template and required information.

[Contribution guidelines](https://github.com/pmmp/PocketMine-MP/blob/master/CONTRIBUTING.md)

**Comment by smakosav** [comment]
Updated post,
 information provided.

**Comment by dktapps** [comment]
You are using a third-party modified build. We don't provide support for modified builds.

**Comment by smakosav** [comment]
I do not think I need a support, because my reporting describes a bug, it is your priority fix this bug at present very serious,
good luck.
