### ISSUE TITLE
The installation script has down!

### ISSUE THREAD

**Issue by smakosav** [pmmp/PocketMine-MP#1266]
I need to be helped, supported! Because of your problem

`-sL https://get.pmmp.io | Bash -s -` or `wget -q -O - https://get.pmmp.io | bash -s -`
The installation script has down! I've lost a lot of time (more than 3 months) is it can not end like that.
Now, without a whim, can you tell me if there is a way to install it on my mac with this command line?
`Curl -sL https://get.pmmp.io | Bash -s - `.
Stuff.
### error message
[!] Couldn't download version automatically from Jenkins server

**Comment by TheDiamondYT1** [comment]
Jenkins is down, not the install script. Please download from [Poggit](http://poggit.pmmp.io) instead

**Comment by dktapps** [comment]
there's nothing wrong with jenkins...

**Comment by TheDiamondYT1** [comment]
Oh is it back up

**Comment by smakosav** [comment]
I have a mac, things are different, I do not have the pocketmine-mp ios / android app, via poggit you can download the .phar file, not the full file.
More detailed procedure?

**Comment by TheDiamondYT1** [comment]
@smakosav The PocketMine / iOS apps aren't supported anyway

**Comment by dktapps** [comment]
This issue has been created on the wrong repository. Please open an issue on the php-build-scripts repo.

**Comment by TheDiamondYT1** [comment]
@smakosav The Android / iOS apps aren't supported anyway.
