### ISSUE TITLE
Cauldron - tile

### ISSUE THREAD

**Issue by FerroDump** [pmmp/PocketMine-MP#127]
### Issue description
Cauldron isn't tile

### Steps to reproduce the issue
$block = $event->getBlock(); // Cauldron 
$level->getTile($block); // NULL

### OS and versions
PHP version: 7.0.5
API: 2.1.0
Minecraft PE v0.16.0.5 alpha (protocol version 91)

### Crashdump, backtrace or other files

* ...

**Comment by dktapps** [comment]
Not implemented.
