### ISSUE TITLE
.phar I NEED HELP

### ISSUE THREAD

**Issue by AyyItzJ4y** [pmmp/PocketMine-MP#1271]
How do We make the .zip pocketminephar to a .phar

**Comment by totor29** [comment]
Create Zip to  Phar :

http://pmt.mcpe.fun/

Please close this issue

**Comment by xZeroMCPE** [comment]
@AyyItzJ4y You're asking a question in the issue section which is not dedicated for that specific reason. Did you not read the issue guidelines when creating it? I advised you to carry this question over to https://forums.pmmp.io/ and to avoid doing this again.

**Comment by SOF3** [comment]
Please do not answer invalid issues. This will encourage people to continue doing that.
