### ISSUE TITLE
server shutdown when the fist player connect

### ISSUE THREAD

**Issue by totor29** [pmmp/PocketMine-MP#1274]
### Issue description
server shutdown when the first player joined the game
issue verified with v351,v352,v353
not verified with 341>version<351
no error log fund

no problem with PocketMine-MP_1.6.2dev-340

### OS and versions
* PocketMine-MP: 1.6.2dev-353
* PHP: 7.0.17
* Server OS: Linux ns3023271.ip-151-80-230.eu 4.4.19-mod-std-ipv6-64 #1 SMP Mon Aug 22 13:05:01 CEST 2016 x86_64
* Game version: PE/Win10

### Plugins
- Test on a clean server without plugins: is the issue reproducible without any plugins loaded?
no, but same plugin tested with Pocketmine v340 (OK) and with Pocketmine v351-352-353 (KO server shutdown at the first player connected) 

### Crashdump, backtrace or other files
no log
no crashdump found

sorry for my bad english

**Comment by totor29** [comment]
I downgraded server on v340dev for the moment.

**Comment by Muqsit** [comment]
send a screenshot of the log

**Comment by totor29** [comment]
all is fine with PocketMine-MP_1.6.2dev-359
