### ISSUE TITLE
Doesn't appear to work/listen on OpenVZ network interfaces

### ISSUE THREAD

**Issue by jacnoc** [pmmp/PocketMine-MP#1279]
### Issue description

Tried to install this on my OpenVZ server (from Ramnode). Installs and starts up fine. But it's not listening on the IP/port. I have a suspicion that pocketmine has issues with not supporting OpenVZ. I tested PocketMine on a free google cloud server that I have (not OpenVZ) and it worked just fine.

### Steps to reproduce the issue

1. ...
2. ...

### OS and versions

* PocketMine-MP: 1.6.2dev-340 "Unleashed" (API 3.0.0-ALPHA7)
* PHP: 7
* Server OS: debian 8 (openvz virtualization)
* Game version: Win10 (delete as appropriate)

### Plugins
- Test on a clean server without plugins: is the issue reproducible without any plugins loaded?

If the issue is **not** reproducible without plugins:
- Have you asked for help on our forums before creating an issue?
- Can you provide sample, *minimal* reproducing code for the issue? If so, paste it in the bottom section
- Paste your list of plugins here (use the 'plugins' command in PocketMine-MP)

### Crashdump, backtrace or other files
- Do not paste crashdumps into an issue - please use our Crash Archive at https://crash.pmmp.io for submitting crash reports to not spam the issue tracker. Add links to your reports in the Crash Archive here.
- Please use gist or anything else to add other files and add links here 

* ...

**Comment by TheDiamondYT1** [comment]
You mean OpenVZ has issues with not supporting PocketMine.

**Comment by HimbeersaftLP** [comment]
Explain how my server is working just fine then, I think it's either you or your host....

![screenshot of cp](https://cdn140.picsart.com/239785304012202.png)

**Comment by dktapps** [comment]
Please take this to our [forums](https://forums.pmmp.io). Do not use our issue tracker for support requests.
