### ISSUE TITLE
/timings paste is broken

### ISSUE THREAD

**Issue by itabxt** [pmmp/PocketMine-MP#1280]
### Issue description

An error happened while pasting the report

I have tried wireshark trace.
In Chrome 
```
Status Code:302 FOUND
With a location header
```

Use cURL
Request:
```
Expect: 100-continue
```
```
100 continue
Without a Location header.
```

I modified the request header in TimingsCommand and it seems don't work.

### Steps to reproduce the issue

1. /timings on
2. /timings paste

### OS and versions

* PocketMine-MP: 44f1dedbf866f0f200d68a3789e3672c430150dc
* PHP: 7.0.4
* Server OS: Windows 10
* Game version: All

**Comment by SOF3** [comment]
"latest" is an invalid version.

**Comment by dktapps** [comment]
what is your timings host in pocketmine.yml?

**Comment by itabxt** [comment]
timings.pmmp.io
