### ISSUE TITLE
Crash server using wrong packet

### ISSUE THREAD

**Issue by FaigerSYS** [pmmp/PocketMine-MP#1281]
### Issue description
Someone can crash your server by sending wrong packet using fake client

### Steps to reproduce the issue
1. Send (for example) CommandStepPacket using non-array Json for input field (i.e. string)
2. Server crashed!

Maybe another packets is vurenable too

### OS and versions
PocketMine-MP: 06083d6d

**Comment by dktapps** [comment]
The server won't crash because all packet handling exceptions are handled by the network interface. Sending something like that will simply cause the server to log an exception and to block the IP address.
