### ISSUE TITLE
MCPE 1.2 Signs

### ISSUE THREAD

**Issue by Awzaw** [pmmp/PocketMine-MP#1283]
https://github.com/pmmp/PocketMine-MP/blob/2ba601b6e9091a44811156b089de0f4594c8a1b8/src/pocketmine/tile/Sign.php#L59

(mcpe1.2 branch, rev no. 1e539c4e3b4b3360ce94e5591047d6351e644b6f)

If a level from earlier versions has a 2 line sign with line1 = '[WORLD]', line2 = 'flat', and lines 3 and 4 both empty

$nbt->Text->getValue() at line 40 returns

`"[WORLD]\nflat\n\n\n"`

however $this->text for the foreach at line 59 is

`["[WORLD]","","flat","","",""]`

which then throws InvalidArgumentException: "Index must be in the range 0-3!" when unloading chunks at line 95

Another example for a sign from pre 1.2 (and maybe corrupt, since "hj" isn't even on the sign) with lines "[WORLD]", "", "hjv" and "":

$nbt->Text->getValue() on line 40 returns `"[WORLD]\n\nhjv\n\nhj\n\n\n"`
which gives `["[WORLD]","","hjv","","hj","",""]` for $this->text at line 59.

**Comment by dktapps** [comment]
Could you retest this with the latest commit? It won't crash anymore, but it's worrying that there were too many entries in there at all.

**Comment by Awzaw** [comment]
All working now

**Comment by jakobbouchard** [comment]
Hey @dktapps how would I go about setting up a server for the 1.2 version? I seem to be able to setup a server for the 1.1.0.55. I know this probably isn't the place to ask, but yeah, I didn't want to open a new issue
