### ISSUE TITLE
EntityDamageByEntityEvent doesn't recognize Arrow

### ISSUE THREAD

**Issue by matcracker** [pmmp/PocketMine-MP#1287]
### Issue description

When a player hits a another player with a arrow, the damager is always the player.

### Steps to reproduce the issue

1. Take a bow and shoot a player

### OS and versions

EDIT: Tested with last commit and happened too
* PocketMine-MP: https://github.com/pmmp/PocketMine-MP/commit/0c798222a4af61fd5dac719466469dd336453466
* PHP: 7.0
* Server OS: Windows 10
* Game version: PE/Win10 (delete as appropriate)

### Plugins
- It needs a plugin:
```
public function onEntityDamageByEntity(EntityDamageEvent $event)
    {
        $entity = $event->getEntity();
        
        if($entity instanceof Player){
            if ($event instanceof EntityDamageByEntityEvent) {
                $damager = $event->getDamager();
                if ($damager instanceof Player) {
                    print_r("The damager is a player!");
                }else if($damager instanceof Arrow){
                    print_r("The damager is an arrow!");
                }
            }
        }
    }
```
### Crashdump, backtrace or other files
- Do not paste crashdumps into an issue - please use our Crash Archive at https://crash.pmmp.io for submitting crash reports to not spam the issue tracker. Add links to your reports in the Crash Archive here.
- Please use gist or anything else to add other files and add links here 

* ...

**Comment by Muqsit** [comment]
According to this line https://github.com/pmmp/PocketMine-MP/blob/d358e13868c0f3c341c6cb681d319dc5fcbd6a19/src/pocketmine/entity/Projectile.php#L86, the damager is the Projectile, can you show your imports?

**Comment by matcracker** [comment]
@Muqsit 
```
use pocketmine\event\entity\EntityDamageByEntityEvent;
use pocketmine\event\entity\EntityDamageEvent;
use pocketmine\entity\Arrow;
use pocketmine\Player;
```

**Comment by Muqsit** [comment]
Use the forum for this discussion, seems like a you-only issue.

**Comment by matcracker** [comment]
Sorry... I see now that exist EntityDamageByChildEntityEvent
