### ISSUE TITLE
Add unregister method to CommandMap (feature request)

### ISSUE THREAD

**Issue by mad-hon** [pmmp/PocketMine-MP#1293]
### Issue description
Plugins that dynamically register new commands don't seem to have a clean way to properly unregister them.

### Steps to reproduce the issue

1. From a plugin, register new command via $this->plugin->getServer()->getCommandMap()->register("mycommand", $cmd);
2. Now there's no unregister method in the CommandMap class to reverse the previous step

### OS and versions
* PocketMine-MP: 1.6.2dev
* PHP: 7.0.3 (but not relevant)
* Server OS: macOS 10.12.6 (but not relevant)
* Game version: PE

### Plugins
- MadCommands ;-)

### Crashdump, backtrace or other files
- No crash

Just hoping to see the `unregister` method added to the `CommandMap` class at some point, so that I can implement `/cmd delete` in my plugin in a better way.

**Comment by Sandertv** [comment]
https://github.com/pmmp/PocketMine-MP/issues/1229
