### ISSUE TITLE
Memory leak

### ISSUE THREAD

**Issue by GamakCZ** [pmmp/PocketMine-MP#1294]
### Issue description

When I turn on the server, write / status sends me that the virtual memory is 581. I will try again for a few seconds and the virtual memory is 587. If I wait for an hour and I only have a server for 1GB ram after some time of the server crash. (Up to 10 players online).

### Steps to reproduce the issue

1. Start server
2. Wait hour and few minutes

### OS and versions

- down

### Plugins
- Tested without plugins

### Crashdump, backtrace or other files
- https://crash.pmmp.io/view/2995

![minecraft_ windows 10 edition 15 08 2017 15_04_32](https://user-images.githubusercontent.com/17053298/29317738-a23dbb68-81cd-11e7-9c08-d3ab9fd9ede8.png)

**Comment by robske110** [comment]
Which version are you using?
Could you test on a clean new server with the same worlds and then test with a freshly generated one?

**Comment by dktapps** [comment]
If you could obtain a memory dump when the server has nearly exhausted its memory limit, that would help debugging the problem.

**Comment by GamakCZ** [comment]
I do not know if I did everything right...  link: https://files.fm/u/dhh4eqaa

**Comment by dktapps** [comment]
how high was the memory usage when you created this memory dump?

**Comment by GamakCZ** [comment]
1100MB

**Comment by matcracker** [comment]
But... Take a look to the world chunks. They passed from ~200 to ~700. I think it's normal this memory usage.

**Comment by dktapps** [comment]
700 chunks does not consume over a gigabyte of RAM.

**Comment by dktapps** [comment]
@GamakCZ I cannot identify the cause of your issue from tbe memory dump you've given. The dump needs to be performed when the server main thread memory is near its limit.

**Comment by matcracker** [comment]
I tested it in my server and it happens too. After half hour the total memory goes from 800-850 MB (stable) to 6 GB and it crashes. I will send you the dump memory result.

**Comment by matcracker** [comment]
@dktapps where can I send you privately the files? (Crash dump, dumpmemory and images)

**Comment by dktapps** [comment]
Upload it somewhere and then PM me the link on the forums if you want.

**Comment by dktapps** [comment]
I pushed a commit to add memory limits for AsyncWorkers, would you guys mind testing it?

**Comment by TDMidkwhatisxd** [comment]
Until is fixed, you could use RestartMe plugin, to restart server at a interval.

**Comment by dktapps** [comment]
Closing this due to lack of response.

**Comment by ChikoTridipa** [comment]
No fixed
