### ISSUE TITLE
Walking on top of fences triggers anti-flight

### ISSUE THREAD

**Issue by dktapps** [pmmp/PocketMine-MP#1299]
### Issue description
Level->getCollisionCubes() doesn't account for the possibility that blocks can have an AABB bigger than 1x1x1 (such as fences or fence-gates). Not sure how best to fix this (an extra +/- 1 blocks in each direction for collision checks would work, but that's not an ideal solution).

Expected result: not to get kicked for flight on fences
Actual result: got kicked

### Steps to reproduce the issue

1. place a fence
2. walk along the top of it

**Comment by nikipuh** [comment]
please fix!
