### ISSUE TITLE
idk whats this but crashing server

### ISSUE THREAD

**Issue by optimusprime338** [pmmp/PocketMine-MP#1309]
### Issue description
```
Error: Call to a member function getName() on null
File: src/pocketmine/level/Level
Line: 2741
Type: notice

Code:
[2732] 		return $this->time;
[2733] 	}
[2734] 
[2735] 	/**
[2736] 	 * Returns the Level name
[2737] 	 *
[2738] 	 * @return string
[2739] 	 */
[2740] 	public function getName() : string{
[2741] 		return $this->provider->getName();
[2742] 	}
[2743] 
[2744] 	/**
[2745] 	 * Returns the Level folder name
[2746] 	 *
[2747] 	 * @return string
[2748] 	 */
[2749] 	public function getFolderName() : string{
[2750] 		return $this->folderName;
[2751] 	}

Backtrace:
#0 src/pocketmine/Server(2327): pocketmine\level\Level->getName()
#1 src/pocketmine/Server(2459): pocketmine\Server->checkTickUpdates(integer 4050, double 1503466046.9455)
#2 src/pocketmine/Server(2221): pocketmine\Server->tick()
#3 src/pocketmine/Server(2100): pocketmine\Server->tickProcessor()
#4 src/pocketmine/Server(1682): pocketmine\Server->start()
#5 src/pocketmine/PocketMine(511): pocketmine\Server->__construct(BaseClassLoader object, pocketmine\utils\MainLogger object, string phar:///home/sky/PocketMine-MP.phar/, string /home/sky/, string /home/sky/plugins/)
#6 /home/sky/PocketMine-MP.phar(1): require_once(string phar:///home/sky/PocketMine-MP.phar/src/pocketmine/PocketMine.php)

PocketMine-MP version: 1.6.2dev #0 [Protocol 113; API 3.0.0-ALPHA7]
Git commit: 0000000000000000000000000000000000000000
uname -a: Linux SkyBlocks 2.6.32-48-pve #1 SMP Fri Dec 23 10:22:54 CET 2016 x86_64
PHP Version: 7.0.3
Zend version: 3.0.0
OS : Linux, linux
```

### Steps to reproduce the issue

1. ...
2. ...

### OS and versions

* PocketMine-MP:
* PHP:
* Server OS:
* Game version: PE/Win10 (delete as appropriate)

### Plugins
- Test on a clean server without plugins: is the issue reproducible without any plugins loaded?

If the issue is **not** reproducible without plugins:
- Have you asked for help on our forums before creating an issue?
- Can you provide sample, *minimal* reproducing code for the issue? If so, paste it in the bottom section
- Paste your list of plugins here (use the 'plugins' command in PocketMine-MP)

### Crashdump, backtrace or other files
- Do not paste crashdumps into an issue - please use our Crash Archive at https://crash.pmmp.io for submitting crash reports to not spam the issue tracker. Add links to your reports in the Crash Archive here.
- Please use gist or anything else to add other files and add links here 

* ...

**Comment by Driesboy** [comment]
haha nice issue template

**Comment by optimusprime338** [comment]
sorry and I saw logs everytime server crash .. a player was kicked from game saying 'flying is not enabled on this server'

**Comment by Muqsit** [comment]
Are you using a custom level generator? The problem lies in Level->provider

**Comment by optimusprime338** [comment]
I am using skyblocks Plugins and I turned allow flight on and server no more crashing!
