### ISSUE TITLE
not work color text on sign

### ISSUE THREAD

**Issue by Bruno99** [pmmp/PocketMine-MP#1323]
### Issue description

The color text on the sign does not work
### Steps to reproduce the issue

1. Place sign
2. Write color text, example: §1Hello
3. Enter/click

### OS and versions

* PocketMine-MP: Jenkins -> PocketMine-MP -> number 488
* PHP: 7.0.3
* Server OS: Linux
* Game version: PE (1.1.5)

### Plugins
DevTools from jenkins pmmp 488
### Crashdump, backtrace or other files
Null

**Comment by dktapps** [comment]
By default only operators can write coloured text. If you opped yourself you need to relog to be able to write coloured text.

**Comment by Bruno99** [comment]
@dktapps I played with OP, I built myself a spawn
