### ISSUE TITLE
I would like to know if this what you show in the video would affect the servers

### ISSUE THREAD

**Issue by MrSmileCH** [pmmp/PocketMine-MP#1325]
Issue description
Please see the following video and tell me if there is any solution so that this does not happen inside the servers
Link: https://youtu.be/FQ8An5n2rQU

Steps to reproduce the issue:
Start server
Join server
OS and versions:
All 
Plugins:
0

**Comment by dktapps** [comment]
Every time a vanilla client joins your world they are downloading chunks. I could do this to any server I feel like without any need for a proxy.
