### ISSUE TITLE
Config parse error with "txt" format

### ISSUE THREAD

**Issue by Cansll** [pmmp/PocketMine-MP#1327]
https://github.com/pmmp/PocketMine-MP/blob/badd669b3d74e04ca773130048a1826664a9fe95/src/pocketmine/utils/Config.php#L202

When I using this format of config files I found:
If my array is like this:
```php
array("xxxa","xxxb","xxxc")
```
It will write to config this:
```
0
1
2
```
Because `array_keys` returned array indexes but not values.

Sorry for my poor English...

**Comment by SOF3** [comment]
You are using Config incorrectly. Config(ENUM) always stores the enum in the _keys_ instead of the _values_ of the backing array for fasting searching.

This issue may remain open as a reminder to add an extra `$keys` parameter in the `setAll()` method to use `array_fill_keys` for setting data.

**Comment by Cansll** [comment]
Thanks. :)
