### ISSUE TITLE
Possible hack

### ISSUE THREAD

**Issue by Tarik02** [pmmp/PocketMine-MP#1329]
### Issue description

As you can see here https://github.com/pmmp/PocketMine-MP/commit/a5f5502380d713e74cff4735883954e5f5727dcc#diff-cdbb30931af8bd92d19ac4be15dc4f3bR53 the player can shoot without arrows(cheats).

### Steps to reproduce the issue

1. ...
2. ...

### OS and versions

* PocketMine-MP:
* PHP:
* Server OS:
* Game version: PE/Win10 (delete as appropriate)

### Plugins
- Test on a clean server without plugins: is the issue reproducible without any plugins loaded?

If the issue is **not** reproducible without plugins:
- Have you asked for help on our forums before creating an issue?
- Can you provide sample, *minimal* reproducing code for the issue? If so, paste it in the bottom section
- Paste your list of plugins here (use the 'plugins' command in PocketMine-MP)

### Crashdump, backtrace or other files
- Do not paste crashdumps into an issue - please use our Crash Archive at https://crash.pmmp.io for submitting crash reports to not spam the issue tracker. Add links to your reports in the Crash Archive here.
- Please use gist or anything else to add other files and add links here 

* ...

**Comment by dktapps** [comment]
Fixed, thanks!

**Comment by Tarik02** [comment]
No mention :-)
