### ISSUE TITLE
Flow calculations need a total rewrite

### ISSUE THREAD

**Issue by dktapps** [pmmp/PocketMine-MP#133]
### Issue description
We recently fixed a CPU leak relating to still water bodies. Flow calculations are still TERRIBLE for performance and need rewriting.

### OS and versions

* PocketMine-MP: 756760a
* PHP: 7.0.13 x64
* Server OS: Linux
* Game version: irrelevant

### Crashdump, backtrace or other files

* ...

**Comment by Landy005** [comment]
in creative its hard to escape the water sometimes u cant fly up out of the water

**Comment by dktapps** [comment]
Seems a part of the reason for the bad performance is to do with the fact that liquid flow triggers lighting updates. #456

**Comment by dktapps** [comment]
Liquid blocks are also repeatedly being set and subsequently updated even after they have stopped flowing anywhere, which is wasting CPU time.
