### ISSUE TITLE
Incorrectly used event in Bucket

### ISSUE THREAD

**Issue by zKoz210** [pmmp/PocketMine-MP#1339]
### Issue description

I think it uses wrong event (PlayerBucketEmptyEvent) and would be great to get variable $targetBlock
It would be very useful to add some properties to the block, such as Metadata
### Steps to reproduce the issue

1. https://github.com/pmmp/PocketMine-MP/blob/master/src/pocketmine/item/Bucket.php#L73

### OS and versions

* PocketMine-MP: https://github.com/pmmp/PocketMine-MP/commit/82fd3b540eb8b252a236187ab566bd091db84674
* PHP: 7.0.2
* Server OS: Windows/Linux

**Comment by dktapps** [comment]
I thought I fixed this bug already. Maybe it was on a different branch.

**Comment by zKoz210** [comment]
@dktapps you can add getTargetBlock()?
