### ISSUE TITLE
The sign doesn't work.

### ISSUE THREAD

**Issue by Mintos74** [pmmp/PocketMine-MP#1346]
### Issue description
If you write the poster on the sign, it says "Text 1, Text 2.."
I don't really have to explain this to myself...
-->
* PocketMine-MP: Last commit
* PHP: 7.2
* Server OS: linux
* Game version: PE

### Plugins
- Test on a clean server without plugins: is the issue reproducible without any plugins loaded?

If the issue is **not** reproducible without plugins:
- Have you asked for help on our forums before creating an issue?
- Can you provide sample, *minimal* reproducing code for the issue? If so, paste it in the bottom section
- Paste your list of plugins here (use the 'plugins' command in PocketMine-MP)

### Crashdump, backtrace or other files 

* ...

**Comment by dktapps** [comment]
"Last" is not a valid version. Read the issue template.

**Comment by Mintos74** [comment]
Modified. Please reprocess it.

**Comment by dktapps** [comment]
Fixed, thanks.
