### ISSUE TITLE
Craft with custom name

### ISSUE THREAD

**Issue by FerroDump** [pmmp/PocketMine-MP#135]
### Issue description
Impossible object with a Custom name crafted anything.
For example, oak with the name "Test" not make Wood Planks

### Steps to reproduce the issue
1. To set a custom name to the item
2. Make something out of it

### OS and versions
PocketMine-MP: 756760a
PHP: 7.0.13 x64
Server OS: Linux
Game version: 0.15 - 0.16
* ...

Console-debug:
Unmatched recipe edd2c4d2-5995-3f32-87a3-63a6a3014756 from player Steve: client does not have enough items, using: Item Birch Wood (17:2)x1, Item Air (0:0)x0, Item Air (0:0)x0, Item Air (0:0)x0, Item Air (0:0)x0, Item Air (0:0)x0, Item Air (0:0)x0, Item Air (0:0)x0, Item Air (0:0)x0

**Comment by dktapps** [comment]
```
[22:05:38] [Server thread/CRITICAL]: TypeError: "Argument 1 passed to pocketmine\nbt\NBT::matchTree() must be an instance of pocketmine\nbt\tag\CompoundTag, null given, called in /data/data/com.termux/files/home/src/pocketmine/item/Item.php on line 755" (EXCEPTION) in "/src/pocketmine/nbt/NBT" at line 107
```
encountered while testing...

**Comment by dktapps** [comment]
This has been fixed on a development branch and will be closed automatically when it is merged (no date of merge can be provided).
