### ISSUE TITLE
PLEASE HELP THE LAG SITUATION

### ISSUE THREAD

**Issue by bettywhatislove** [pmmp/PocketMine-MP#1350]
HI ,

there is bad lag spikes on our spoon

i talk to dertderry and he said he not sure how to fix , can you guys help us fix spoon lag ? this will benifit our community a lot.

thank you

**Comment by mal0ne-23** [comment]
this are not spoon, make issue on spoon pls tnx

**Comment by bettywhatislove** [comment]
also getname crash ... not fixed
