### ISSUE TITLE
Signs don't work

### ISSUE THREAD

**Issue by EinDaw** [pmmp/PocketMine-MP#1352]
![screenshot_20170902-155232](https://user-images.githubusercontent.com/24544089/29998695-7823efa4-8ff7-11e7-9dfa-f75d1c4d9175.png)

No matter what I write, this text won't go away.

**Comment by dktapps** [comment]
Outdated version, did not follow issue template and duplicate issue.

**Comment by robske110** [comment]
I take full responsibility! Sorry :( Blame robske_110
