### ISSUE TITLE
Crops not growing

### ISSUE THREAD

**Issue by PragaKart67z** [pmmp/PocketMine-MP#1357]
### Steps to reproduce the issue

1. ... Hoe farmland and plant a crop
2. ... Wait for it to grow very slowly.

### OS and versions

* PocketMine-MP: #1098 on travis
* PHP: 7.0.21
* Server OS: Ubuntu
* Game version: PE/Win10 (delete as appropriate)

### Plugins
- Test on a clean server without plugins: is the issue reproducible without any plugins loaded?

If the issue is **not** reproducible without plugins:
- Have you asked for help on our forums before creating an issue?
- Can you provide sample, *minimal* reproducing code for the issue? If so, paste it in the bottom section
- Paste your list of plugins here (use the 'plugins' command in PocketMine-MP)

### Crashdump, backtrace or other files
- Do not paste crashdumps into an issue - please use our Crash Archive at https://crash.pmmp.io for submitting crash reports to not spam the issue tracker. Add links to your reports in the Crash Archive here.
- Please use gist or anything else to add other files and add links here 

* ...

**Comment by dktapps** [comment]
Farming isn't implemented yet. I'll be surprised if it works at all.
