### ISSUE TITLE
The game crashes when trying to download Resource pack

### ISSUE THREAD

**Issue by killer549** [pmmp/PocketMine-MP#1358]
### Issue description

![screenshot_20170905-161358](https://user-images.githubusercontent.com/11447051/30063895-cd0f86dc-9258-11e7-9624-14c106ed8065.png)
here you can see that resource pack is about 500000.0 GB, When i Press Download and join , The game Crashes and The console send Player logged out due to timeout.

### Steps to reproduce the issue

1. join the server
2. click Download and join

### OS and versions

* PocketMine-MP: PocketMine-MP 1.7dev-11 commit: c9ee206
* PHP: 7.2
* Server OS: Windows 10
* Game version: PE

### Plugins
- Test on a clean server without plugins: is the issue reproducible without any plugins loaded?
yes
If the issue is **not** reproducible without plugins:
- Have you asked for help on our forums before creating an issue?
- Can you provide sample, *minimal* reproducing code for the issue? If so, paste it in the bottom section
- Paste your list of plugins here (use the 'plugins' command in PocketMine-MP)

### Crashdump, backtrace or other files
- Do not paste crashdumps into an issue - please use our Crash Archive at https://crash.pmmp.io for submitting crash reports to not spam the issue tracker. Add links to your reports in the Crash Archive here.
- Please use gist or anything else to add other files and add links here 

* ...

**Comment by dktapps** [comment]
is this issue random or does it occur every time?

**Comment by killer549** [comment]
It occurs everytime. I tried this on different devices but it's still the same

**Comment by dktapps** [comment]
do you have a sample resource pack that this can be reproduced with?

**Comment by killer549** [comment]
yeah..
SSPE Lightweight Shader
i tried a coordinates resource pack too 

Both of them are 945384.0GB

**Comment by dktapps** [comment]
Using [this](http://mcpedl.com/sspe-shader/) I can't reproduce the bug.

**Comment by jasonwynn10** [comment]
I've reproduced this bug before on my home server with multiple texture packs

**Comment by killer549** [comment]
Well, I recorded what happened exactly.
[screenrecorder.20170905191549.mp4.zip](https://github.com/pmmp/PocketMine-MP/files/1278132/screenrecorder.20170905191549.mp4.zip)

This time is Tried [this](http://mcpedl.com/paper-cut-out-craft/) Resource pack.

**Comment by Driesboy** [comment]
cant confirm this with my own texture pack

**Comment by dktapps** [comment]
This must be something to do with your actual server, I can't reproduce this at all.

**Comment by TanToan99** [comment]
Update your php >= 7.2 can fix issue

**Comment by dktapps** [comment]
reading the issue properly can help not to say dumb things

**Comment by killer549** [comment]
I tried this on a new clean server and the issue still reproduce :confused:

**Comment by killer549** [comment]
@TanToan99 This pocketmine version only allows PHP >=7.2

**Comment by SleepSpace9** [comment]
Did you run pmmp from source or from jenkins phar? I had the same issue when running from phar, but it worked for me running from source.

**Comment by dktapps** [comment]
@SleepSpace9 you're a legend... reproduced

**Comment by killer549** [comment]
@SleepSpace9 Nice...I tried to run it from the source.. Everything worked fine 👍
