### ISSUE TITLE
Spam

### ISSUE THREAD

**Issue by getnamecrashedonpmmp** [pmmp/PocketMine-MP#1366]
FOR THOSE WHO DONT KNOW 

1) CLICK DOWNLOAD ZIP ON GENISYSPRO
2) REPLACE PHAR WITH SRC
3) RUN GENISYS PRO !

GET NAME CRASH FIXED ! YES!

**Comment by dktapps** [comment]
Maybe @DerddyDert could also teach his student to stop spamming our issue tracker. That'd be just great.
