### ISSUE TITLE
Installer script installs php 7.0 but pmmp needs php 7.2

### ISSUE THREAD

**Issue by SuperOP535** [pmmp/PocketMine-MP#1369]
^ title... I have no idea how to update to 7.2 tho

**Comment by dktapps** [comment]
> I have no idea how to update to 7.2 tho

[Reading the documentation](http://pmmp.readthedocs.io/en/rtfd/installation.html#installing-manually) would be a good place to start.

**Comment by SuperOP535** [comment]
Uhm but you should update the installer script

**Comment by dktapps** [comment]
... and since it hasn't been updated **yet** I linked you to the documentation so you can set up manually without waiting.

**Comment by dktapps** [comment]
Closing this since it's on the wrong repository.
