### ISSUE TITLE
Some problems with TranslationContainer()

### ISSUE THREAD

**Issue by zKoz210** [pmmp/PocketMine-MP#1374]
### Issue description
Colors placed in `TranslationContainer()` that interferes with normal translation

### Steps to reproduce the issue
1. Use command random command. For example: /aaaaa

Invalid:
```
$sender->sendMessage(new TranslationContainer(TextFormat::RED . "%commands.generic.player.notFound"));
```
Valid:
```
$sender->sendMessage(TextFormat::RED . new TranslationContainer("%commands.generic.player.notFound"));
```
### OS and versions
* PocketMine-MP: https://github.com/pmmp/PocketMine-MP/commit/16cb75ef384fbcf5c74912427f33c32295fd4d5b (MCPE 1.2 branch)
* PHP: 7.0.2
* Server OS: Windows/Linux

### Crashdump, backtrace or other files
![image](https://user-images.githubusercontent.com/28255085/30247432-5deaf2be-961d-11e7-836f-8eeb22be04c7.png)

**Comment by dktapps** [comment]
This is nothing to do with the colours, it's because that language string doesn't exist client-side anymore.

**Comment by zKoz210** [comment]
@dktapps So translation is taken from the PocketMine-MP. Just try to change it and make sure that this is so
