### ISSUE TITLE
server crash when player1 give non existence item (38527) to player 2

### ISSUE THREAD

**Issue by teracube** [pmmp/PocketMine-MP#1376]
### Issue description

server crash when player1 give item 38527 to player2 because of non existence item

## Steps to reproduce the issue

1. use PocketMine-MP: 1.6.2dev #563 [Protocol 113; API 3.0.0-ALPHA7]
2. operator execute command : /give player2 38527 64
player1 and player2 are operators

### OS and versions
* PocketMine-MP: 1.6.2dev #563 [Protocol 113; API 3.0.0-ALPHA7]
* PHP: 7.0.17
* Server OS: Linux
* Game version: PE/Win10 (delete as appropriate)

### Plugins
- Test on a clean server without plugins: is the issue reproducible without any plugins loaded?
sorry i have not another server test, so i can't try to reproduce this issue without plugin loaded

If the issue is **not** reproducible without plugins:
- Have you asked for help on our forums before creating an issue?
yes I related this on poggit forum  :
https://forums.pmmp.io/threads/server-crash-steeve-given-unknown-38527-0-64-to-james.3742/#post-35792

- Paste your list of plugins here (use the 'plugins' command in PocketMine-MP)
show the crashdump
https://crash.pmmp.io/view/3925

### Crashdump, backtrace or other files
Console :
2017-09-09 [19:42:04] [Server thread/INFO]: [Steeve: Given Unknown (38527:0) * 64 to James]
2017-09-09 [19:42:12] [Server thread/CRITICAL]: InvalidArgumentException: "Value 38527 is too large!" (EXCEPTION) in "src/pocketmine/nbt/tag/ShortTag" at line 70
2017-09-09 [19:42:12] [Server thread/EMERGENCY]: An unrecoverable error has occurred and the server has crashed. Creating a crash dump
2017-09-09 [19:42:12] [Server thread/EMERGENCY]: Please upload the "/home/gsp_1587/g6.hmserv.eu-19537/crashdumps/Sat_Sep_9-19.42.12-CEST_2017.log" file to the Crash Archive and submit the link to the Bug Reporting page. Give as much info as you can.

CrashDump :
https://crash.pmmp.io/view/3925

* thank you very much and sorry for my bad english

**Comment by Muqsit** [comment]
https://github.com/pmmp/PocketMine-MP/issues/1101?

**Comment by bettysmackedsof3** [comment]
@Muqsit THIS HAPPEN BECAUSE DERDERDDY TELL ME THAT SAY , DKTAPPS SOLD PMMP TO NETFLIX  FOR PROFIT !

**Comment by jasonwynn10** [comment]
@bettysmackedsof3 I want to ask you some questions before you get blocked from the repo. Do you have a discord?

**Comment by bettysmackedsof3** [comment]
@jasonwynn10 DKTAPPS SOLD THE NETFLIX FOR PROFIT! VERY DISRESPECTFUL , THIS WHY WE SHOULD USE GENISYS PRO !

We have good devs including :+1:
- @derddydert
- @cortexpe
- @AppleDevelops 
and @masteroftherealms

our team make genisyspro very efficent and good , and we not sell for profit . we have made optimizations for cpu improvment usage , you can test it by downloading our src , its fast (load all chunks in less minute)

our team always uptoday , and we support multi api for plugin !

**Comment by jasonwynn10** [comment]
I’ll take that as a no. Second question: do you know and understand the origin of PocketMine-MP software? Do you understand how it relates to Genesis?

**Comment by CortexPE** [comment]
@jasonwynn10 Betty doesn't have a life so...
Don't even bother asking her.
(She's the kid who spammed both GenisysPro and PMMP repos)

**Comment by bettysmackedsof3** [comment]
@jasonwynn10 pmmp steal genisys software from pmmp , genisys original and best, but has new team now ,

includes 

    @DerddyDert
    @CortexPE
    @AppleDevelops
    and @masteroftherealms

**Comment by bettysmackedsof3** [comment]
@cortexpe hi , is getname bug fixes ?

**Comment by TheDiamondYT1** [comment]
@bettysmackedsof3 Fuck off, you wouldnt be anywhere without PMMP. PocketMine has never been sold, ever.

GenisysPro is full of your low quality bullshit which you copied off other server softwares. Stop spamming PMMP and just get on with your sad little life. Why don't you contribute to PMMP, and instead make spoons?

Integrating DevTools is just dumb. **They are developer tools**, for use with developers only.

> Most of the code was originally written by members of iTXTech.

What the fuck if wrong with you? Genisys was **BASED OFF OF POCKETMINE** — and here you are bitching about how bad it is. You try and make a server software from scratch.

**I fucking dare you**

---

Oh, and you do realise @dktapps (pmmp lead) was the main developer for Genisys for a while? He basically coded your whole server software and you have copied some code from plugins and claimed it as your own.

**Comment by bettysmackedsof3** [comment]
@TheDiamondYT1 DERTDERRDY SAY PMMP SOLD FOR PROFIT !

**Comment by jasonwynn10** [comment]
@bettysmackedsof3 I hate to tell you, but your information is incorrect. PMMP the organization forked PocketMine-MP from the PocketMine organization.
Question 3: How much do you know about programming? Have you ever worked with php before?

**Comment by TheDiamondYT1** [comment]
@bettysmackedsof3 Don't listen to other people without getting the facts. PMMP is open source, anyone can download it. On the website there is a donate button but thats optional.

**Comment by JackNoordhuis** [comment]
STOP SPAMMING USELESS CRAP AND SPAMMING OUR NOTIFICATIONS @bettysmackedsof3

**Comment by bettysmackedsof3** [comment]
@jasonwynn10 @TheDiamondYT1 

thanks for concern , 

PMMP SOLD FOR PROFIT !

@JackNoordhuis woud you like to join genisyspro team  ? i may discuss with dertderddy

**Comment by JackNoordhuis** [comment]
Sure, add me as an owner ¯\_(ツ)_/¯ @bettysmackedsof3

**Comment by bettysmackedsof3** [comment]
@JackNoordhuis i will discuss future posibilty wwith dertderddyg (he not sell pmmp for profits like pmmp)

**Comment by TheDiamondYT1** [comment]
@bettysmackedsof3 WHERE ARE YOU GETTING THIS INFORMATION? IT'S WRONG. I'VE BEEN IN THE COMMUNITY SINCE 0.8.1 AND THEY HAVE NEVER SOLD A THING. YOU CAN EVEN SEEN ARCHIVES OF THE OLD SITE AND YOU CAN DOWNLOAD IT WITH THE CLICK OF A BUTTON.

PMMP TEAM ARE LOSING MONEY, DUE TO THEM HAVING TO HOST SERVERS FOR POGGIT, JENKINS, FORUMS, AND MORE. THEY ARE PROVIDING YOU WITH FREE RESOURCES SO BE **FUCKING** GRATEFUL.

**Comment by bettysmackedsof3** [comment]
@CortexPE your get name spoon detectotor bypass cause crash !

**Comment by bettysmackedsof3** [comment]
@TheDiamondYT1 hi , genisyspro will look into open source poggit to have multi api plugin host support, thank for concerns.

**Comment by TheDiamondYT1** [comment]
@bettysmackedsof3 Then keep he server name as PocketMine-MP. Simple. I always hated the idea of SpoonDetector anyway

**Comment by CortexPE** [comment]
@TheDiamondYT1 , Just let @dktapps lock this dumb convo.

**Comment by bettysmackedsof3** [comment]
@cortexpe you not test your own buggy pull requests ?

https://github.com/GenisysPro/GenisysPro/pull/821
https://github.com/GenisysPro/GenisysPro/pull/821
https://github.com/GenisysPro/GenisysPro/pull/821
https://github.com/GenisysPro/GenisysPro/pull/821

**Comment by TheDiamondYT1** [comment]
@bettysmackedsof3 Don't you dare host poggit yourself. It ruins the idea of it.

@CortexPE Sorry, but i'm fucking sick of these 5 year olds spamming wrong information, then not accepting that they're wrong. I will gladly delete every comment of mine if @dktapps wants it.

**Comment by bettysmackedsof3** [comment]
@TheDiamondYT1 genisyspro will look into spooon the poggit , for future possibility of multi api plugin support , help

thanks

**Comment by CortexPE** [comment]
@bettysmackedsof3 the "spoon detector bypass" commit was reverted because it got updated...
now ffs just stop spamming my emails -_-

**Comment by TheDiamondYT1** [comment]
@CortexPE check twitter

**Comment by dktapps** [comment]
Fixed in https://github.com/pmmp/PocketMine-MP/commit/f7ee78233b7b64323ebfba26ac5a4623f4082952 . Thanks.
