### ISSUE TITLE
Inventory: can't select any item/block

### ISSUE THREAD

**Issue by kenygamer** [pmmp/PocketMine-MP#1400]
### Issue description

Expected result: Be able to select a block/item to place it.
Actual result: Unable to select a block/item from the inventory, therefore also unable to place blocks.
### Steps to reproduce the issue

1. Open the inventory (tested only in creative mode).
2. Find an item/block you would like to select.
3. Try to select it (won't let you)

### OS and versions

* PocketMine-MP: 1.6.2-dev [ Unleashed ] implementing API version 3.0.0-ALPHA6 for Minecraft PE v1.1.5 (protocol version 113)
* PHP: 7.0.1
* Server OS: Linux Ubuntu 16.04 TLS 
* Game version: PE

### Plugins
- Test on a clean server without plugins: is the issue reproducible without any plugins loaded?
Yes, it still remains. I tried also generating a new world, but still having the issue.
If the issue is **not** reproducible without plugins:
- Have you asked for help on our forums before creating an issue?
- Can you provide sample, *minimal* reproducing code for the issue? If so, paste it in the bottom section
- Paste your list of plugins here (use the 'plugins' command in PocketMine-MP)
- I'm unable to access PMMP Forums due to previous rule breaking issues.
- No code is reproducing the issue.
- Plugins (24): DevTools v1.12.0, MineReset v3.0.2, Slapper v1.3.5, MultiWorld v1.3.1, SimpleAuth v2.0.0-alpha7, PlayerInfo v1.2.3, PlayerVaults vv1.0, StaffChat v1.1.1, PurePerms v1.4.1-dev2, AlwaysSpawn v2.2.3-dev1, FactionsPro v1.3.11-1.alpha7, BadWordBlocker v1.0.4, KillMoney v1.1.3, HungerGames vBuild-16.2, CustomBar v0.8, ItemCasePE v1.1.0-dev1, PocketVote vv2.0.0, iProtector v4.0.3#3.1b, SimpleAuthHelper v2.0.6, TopVoter v2.2.1, CapsLimiter v1.2, EconomyAPI v5.7.1-dev1, PureChat v1.4.10-dev2, WalkingParticles v1.1.0
### Crashdump, backtrace or other files
- Do not paste crashdumps into an issue - please use our Crash Archive at https://crash.pmmp.io for submitting crash reports to not spam the issue tracker. Add links to your reports in the Crash Archive here.
- Please use gist or anything else to add other files and add links here 
No crashdumps.
* ...

**Comment by dktapps** [comment]
you're using an outdated version. We're not supporting ALPHA6 anymore.

**Comment by kenygamer** [comment]
@dktapps I'll update my PocketMine version and open the issue when done.
