### ISSUE TITLE
Can't craft anything

### ISSUE THREAD

**Issue by chenxuuu** [pmmp/PocketMine-MP#1404]
### Issue description
I can't craft anything

### Steps to reproduce the issue
for example,when I get a wood,I want to make it to planks.
I can bing planks out of the crafting table,but when I click it to my inventory,it will be missing.
then if I press "E",the wood will back to my inventory
you can try on `dx.sweetcreeper.com:14444`

### OS and versions

* PocketMine-MP:1.7dev-73
* PHP:7.2.0RC2
* Server OS:windows server 2008 R2
* Game version: test on win10 pc and win10 mobile

### Plugins
no any plugin at all

### Crashdump, backtrace or other files
nothing

**Comment by BlawoHD** [comment]
This was fixed

Use this: https://jenkins.pmmp.io/job/PocketMine-MP/lastSuccessfulBuild/artifact/PocketMine-MP_1.7dev-77_3c02a6a8_API-3.0.0-ALPHA8.phar

**Comment by chenxuuu** [comment]
@BlawoHD thanks!
