### ISSUE TITLE
its not join game on android outdated server

### ISSUE THREAD

**Issue by nakutooshi** [pmmp/PocketMine-MP#1405]
plz fix no one everyone kick

**Comment by nakutooshi** [comment]
why is close ?

packet byties not read correct on for older android device, 1.2 player have not be able login

**Comment by optimusprime338** [comment]
Yea i have seen this issue lots of players get kicked for outaded Server but I am latest .. don't know the reason!!

**Comment by Sandertv** [comment]
This is not directly a PocketMine issue. Seeing players getting kicked for outdated server means the client is outdated, which might sound weird.

**Comment by madecode15** [comment]
I have this issue too on TwixPE and many server owners have also mentioned this issue to me

**Comment by dktapps** [comment]
If someone is prepared to create an issue that actually provides useful information, please feel free. This issue contains nothing more than "have issue, pls fix".

**Comment by optimusprime338** [comment]
I am suspecting this reason of server with 1.2 went hell dawn .. 100+ players server have 0 players now..is not it lil surprising

**Comment by dktapps** [comment]
Fine, standard reply it is:

Without knowing your PocketMine-MP version, OS, PHP, Client version, or plugins and how the issue occurred, the issue cannot begin to be solved.
A pre-formatted template is provided that shows the required information to begin to find, test and solve an issue.
Until the adequate template and information is provided, the issue will be closed; it may be reopened if you update the ticket with the correct template and required information.

[Contribution guidelines](https://github.com/pmmp/PocketMine-MP/blob/master/CONTRIBUTING.md)

**Comment by nakutooshi** [comment]
version: 1.7
problem: not join game
template: filled
contribute guidlines: read & works
reply: true

issue:
not join game

soultion:
needs dktapps fix it to after debug

**Comment by TheDiamondYT1** [comment]
@nakutooshi Please edit your issue content and fill out the template:

```
### Issue description
<!---
THIS ISSUE TRACKER IS FOR BUG REPORTING, NOT FOR HELP & SUPPORT. If you need help, use the links below. 
- http://pmmp.readthedocs.io/en/rtfd/ - Documentation
- https://forums.pmmp.io - PMMP Forums
-->
<!--- Any issues requesting updates to new versions of MCPE will be treated as spam. We do not need issues to tell us that there is a new version available. -->
<!--- 
Write a short description about the issue

If you are reporting a regression or unexpected behaviour, please include the below information:
Expected result: What were you expecting to happen?
Actual result: What actually happened?
-->

### Steps to reproduce the issue
<!--- help us find the problem by adding steps to reproduce the issue -->
1. ...
2. ...

### OS and versions
<!--- use the 'version' command in PocketMine-MP

NOTE: LATEST is not a valid version. PocketMine version should include Jenkins build number and/or git commit hash.

NO support whatsoever will be provided for forks or spoons of PocketMine. Issues relating to non-official distributions will be closed as spam. Please send such issues to whoever is responsible for the fork or spoon you are using.

Note that 32-bit platforms are no longer supported by PocketMine-MP and issues concerning 32-bit platforms will be closed.
-->
* PocketMine-MP:
* PHP:
* Server OS:
* Game version: PE/Win10 (delete as appropriate)

### Plugins
- Test on a clean server without plugins: is the issue reproducible without any plugins loaded?

If the issue is **not** reproducible without plugins:
- Have you asked for help on our forums before creating an issue?
- Can you provide sample, *minimal* reproducing code for the issue? If so, paste it in the bottom section
- Paste your list of plugins here (use the 'plugins' command in PocketMine-MP)

### Crashdump, backtrace or other files
- Do not paste crashdumps into an issue - please use our Crash Archive at https://crash.pmmp.io for submitting crash reports to not spam the issue tracker. Add links to your reports in the Crash Archive here.
- Please use gist or anything else to add other files and add links here 

* ...
```
