### ISSUE TITLE
Is this for bedrock edition

### ISSUE THREAD

**Issue by Shiny-andKittens** [pmmp/PocketMine-MP#1409]
I'm sorry if this is against the rules/annoying/spammed a lot, but is this compatible for Bedrock Edition?

**Comment by ZizzyZizzy** [comment]
@Shiny-andKittens 
Check out the latest release notes:
https://github.com/pmmp/PocketMine-MP/releases/tag/api/3.0.0-ALPHA8

Right at the top:

> For Minecraft: Bedrock Edition 1.2.0.81

**Comment by Shiny-andKittens** [comment]
Thanks
