### ISSUE TITLE
PHP 7.2 windows binaries require VC++ runtime 2010

### ISSUE THREAD

**Issue by erichexter** [pmmp/PocketMine-MP#1410]
### Issue description

I am trying to get pmmp running in a windows container, I am able to do that with the latest stable and beta versions, but I am not able to do that with the development builds.  the root cause is php.exe will not execute. In order to troubleshoot this I had to revert to a windows virtual machine with GUI so that I could run additional diagnostic tools to determine what was missing. 

I installed the latest 7.2 windows binaries from https://ci.appveyor.com/project/pmmp/php-build-scripts/build/artifacts ( 07407d8d ) 
### Steps to reproduce the issue

1. ... download to new windows server, 2016 datacenter with gui experience.,
2. ... unzip packages.
3. install vc++ runtime 2017
4. run php.exe -version 
RESULT: nothing executs.
Expected behavior php executes and returns the version header for the build.

 

### OS and versions
![image](https://user-images.githubusercontent.com/114692/30892000-cfe96040-a2fb-11e7-98e3-bbdbb81d5fbb.png)

I was able to track down that php.exe was trying to load msvcr1000.dll which is part of the vc++ runtime for 2010.  It is also loading the 2017 vc runtime, but will not execute unless both dlls are present.

**Comment by TheDiamondYT1** [comment]
`master` is the only branch you need. It's for the 1.2 update.

**Comment by erichexter** [comment]
yes, but the php 7.2 rc from windows.php.net does not require VC runtime 2010.  it requires vc runtime 2017.  The pmmp 7.2 windows dlls require both vc runtime 2010 and 2017.  I assume this is because the build script is out of date ?  It looks like I am not the only one who discovered this.  If this is on purpose, I can submit a pull request to update the documentation. ( on this page. https://github.com/pmmp/pmmp.rtfd.io/blame/rtfd/source/installation.rst#L49)

**Comment by dktapps** [comment]
This is likely something to do with the prebuilt pthreadVC2.dll that's in use. I didn't notice any such issue because I have vcredist 2010 installed anyway. Will take a look later. Thanks.

**Comment by dktapps** [comment]
I'm going to close this and open a corresponding issue on https://github.com/pmmp/php-build-scripts , since that's where the issue cause is.

**Comment by zyvf** [comment]
You just need vc++2015.
