### ISSUE TITLE
BaseInventory->addItem() with a list of separate, stackable items puts each stack in its own slot

### ISSUE THREAD

**Issue by dktapps** [pmmp/PocketMine-MP#1412]
### Issue description
```
$inventory->addItem(
    Item::get(Item::PLANKS, 0, 16),
    Item::get(Item::PLANKS, 0, 16),
    Item::get(Item::PLANKS, 0, 16),
    Item::get(Item::PLANKS, 0, 16)
);
```
will put each of the stacks in a separate slot instead of combining them as expected.

### Steps to reproduce the issue

1. use the above code
2. profit

**Comment by jasonwynn10** [comment]
Why should the stacks combine instead of be individual?

**Comment by dktapps** [comment]
because that is vanilla behaviour. The current behaviour is off and quite annoying. You can see it when you close a crafting grid after failing to craft something.

**Comment by NTT1906** [comment]
this is old now but is this fixed?

**Comment by dktapps** [comment]
If it was fixed, the issue wouldn't still be open.

**Comment by jasonwynn10** [comment]
Isn't this fixed on API 4?
