### ISSUE TITLE
Missing items

### ISSUE THREAD

**Issue by matatacmca** [pmmp/PocketMine-MP#1414]
### Issue description

There seems to be a ton of missing items from the inventory, most mechanical Redstone items are missing (dropper, dispenser, pistons, etc) as well as the beacon. I can give a player a beacon and when placed, the item gets used and then just returns to the hotbar.

I tried seeing if these have not been released onto the server yet, or if i missed something in the config, but yielded no results

### Steps to reproduce the issue

1. connect to the server-> integratedza.ndns.co.za
2. check inventory (game default is in creative

### OS and versions

* PocketMine-MP:  [23:27:15] [Server thread/INFO]: This server is running PocketMine-MP 1.7dev-83 「[REDACTED]」 implementing API version 3.0.0-ALPHA8 for Minecraft: PE v1.2.0.81 (protocol version 137)
* PHP: 7.4 (as installed by installer)
* Server OS: Ubuntu 16.04.3 LTS (GNU/Linux 4.4.0-96-generic x86_64)
* Game version: PE

### Plugins
- Test on a clean server without plugins: is the issue reproducible without any plugins loaded?

If the issue is **not** reproducible without plugins:
- Have you asked for help on our forums before creating an issue?
- Can you provide sample, *minimal* reproducing code for the issue? If so, paste it in the bottom section
- Paste your list of plugins here (use the 'plugins' command in PocketMine-MP)

### Crashdump, backtrace or other files
- Do not paste crashdumps into an issue - please use our Crash Archive at https://crash.pmmp.io for submitting crash reports to not spam the issue tracker. Add links to your reports in the Crash Archive here.
- Please use gist or anything else to add other files and add links here 

* ...

**Comment by matatacmca** [comment]
No Respose?

**Comment by TheShinPin** [comment]
These items have not been implemented yet, this is an invalid issue, stuff like this may get implemented in the feature, you can also writw a plugin to implement such features of you would like.

**Comment by TheShinPin** [comment]
Also in some of the latest dev build stuff like concrete has been implemented.

**Comment by matatacmca** [comment]
Thanks for the feedback. Much appreciated
