### ISSUE TITLE
Blocks

### ISSUE THREAD

**Issue by Landy005** [pmmp/PocketMine-MP#142]
### Issue description
Write a short description about the issue

BLOCKS;
(http://hydra-media.cursecdn.com/minecraft.gamepedia.com/c/c6/DataValuesPE.png)
The following blocks are missing; All new wooden doors, hoppers,cauldron, pistons,repeater (all kind), slime block, wet sponge (instead there are 2 normal sponges in the inventory), beacon, prismarine (all kind), sea lantern, quartz ore block,,dropper, dedection block (these are the one i found).

The following blocks have a bad orientation (when placed); Trapdoors (both),lever,button (both), torches (both),tripwire, rails (and they also dont connect)

Flowers in flower pot dissapear after placed in. 

When placing 2 tall grass the top block of the 2 dissappears.

OVERAL;
Chunks don't load itself but only when you go over to chunks they start loading. So standing still wont load your surrounding blocks even when changing settings and pocketmine.yml.

When you pick a block in front of you it sometimes doesn't work. It never works with stairs and leaves. 

### Steps to reproduce the issue

1. Join server
2. Check inventory, or try to worldedit it and there will be an error. Upload a map with those blocks and the blocks dissapear.

### OS and versions

* PocketMine-MP: PocketMine-MP 1.6.1dev-#103
* PHP: 7.0.13
* Server OS: Linux (tested on 2 servers)
* Game version: PE/Win10 (all) 0.16.2

### Crashdump, backtrace or other files
* ...

**Comment by Landy005** [comment]
... why it is invalid i thought i did it following your style?

**Comment by dktapps** [comment]
There are several issues combined into one here, which is confusing. At initial glance I thought this was a feature request, but reading the whole issue I see valid points but with lack of organisation, which is hard to manage. Please do not paste lots of issues into one.

1. we are aware these are missing/not implemented, a new API is in design and these may not be added until after the new API is done.
2. see 1
3. please open a separate issue with details
4. I don't understand what you mean
5. client issue
6. unimplemented, Win10 Edition is not yet fully supported.

**Comment by Landy005** [comment]
For 4 i mean that when you place tall grass for instance it should be in total 2 blocks high normally. But when i place that block it only is 1 block high, this is for every 2 block plant. I'll open a new issiue for 3 (flower pots). The chunks bug (5 client issue) wasn't there on clearsky so i thought it was only for pmmp but i see genisys has it too.

**Comment by JOrlex** [comment]
for 4, all you ahev to do its chuck some bonemeal at it and it will go initially to 2 blocks high
