### ISSUE TITLE
Bug with show Title

### ISSUE THREAD

**Issue by zKoz210** [pmmp/PocketMine-MP#1422]
### Issue description

After re-join is not displayed title

### Steps to reproduce the issue

1. Join to first time (OK)
2. Re-join - title don't show

### OS and versions

* PocketMine-MP: https://github.com/pmmp/PocketMine-MP/commit/c448f4a3b54ac1371591e4c0f4e7153e852c9963
* PHP: 7.2
* Game version: PE/Win10

### Crashdump, backtrace or other files
```
    public function onPlayerJoinEvent(PlayerJoinEvent $event)
    {
        $player = $event->getPlayer();
        $player->addTitle("123", "456");
    }
```

**Comment by SuperMaXAleX** [comment]
This is not a support forum.

**Comment by jasonwynn10** [comment]
This is due to the order of which the player logs in. Use a delayed task to send the title after a player logs in

**Comment by zKoz210** [comment]
@SuperMaXAleX This is PM-MP problem, and then forum?

**Comment by zKoz210** [comment]
@jasonwynn10 The first time you enter it works, where did the pending tasks?

**Comment by jasonwynn10** [comment]
The client's world generation speed on servers is inconsistent due to internet speed. A delayed task will always create the title after the player can read it. Please use the forums at froums.pmmp.io for further support, and close this issue

**Comment by zKoz210** [comment]
@jasonwynn10 God, if you're dumb, you can just be silent?
