### ISSUE TITLE
Mobs and Fallingsand don't have name tags

### ISSUE THREAD

**Issue by ManiakMCPE** [pmmp/PocketMine-MP#1426]
I am using the latest version of the [Slapper plugin](https://github.com/jojoe77777/Slapper) and when I create an NPC that is a Mob or Fallingsand it has no tag even if I set the name visibility to always. It works fine with player entities.

**Delete this if it is a Slapper bug and I'm stupid**

**Comment by Muqsit** [comment]
This is purely a sleeper or a game issue

**Comment by ManiakMCPE** [comment]
Yeah, figured out it is a game issue.
Closing issue.
