### ISSUE TITLE
Unable to place blocks in the server worlds

### ISSUE THREAD

**Issue by kenygamer** [pmmp/PocketMine-MP#1428]
### Issue description

Expected result: Be able to place blocks.
Actual result: Unable to place blocks.

### Steps to reproduce the issue

1) Join the server.
2) Go on creative mode.
3) Select any block and try to place it. (Notice that the block dissapears every time you try to select it)

### OS and versions

* PocketMine-MP: 1.7dev-27 [REDACTED]
* PHP: 7.2
* Server OS: Linux Ubuntu 16.04.3 TLS
* Game version: PE

### Plugins
- Test on a clean server without plugins: is the issue reproducible without any plugins loaded?
The problem continues to occur, but now the touched block duplicates and doesn't place the requested block.
If the issue is **not** reproducible without plugins:
- Have you asked for help on our forums before creating an issue?
- Can you provide sample, *minimal* reproducing code for the issue? If so, paste it in the bottom section
- Paste your list of plugins here (use the 'plugins' command in PocketMine-MP)

### Crashdump, backtrace or other files
- Do not paste crashdumps into an issue - please use our Crash Archive at https://crash.pmmp.io for submitting crash reports to not spam the issue tracker. Add links to your reports in the Crash Archive here.
- Please use gist or anything else to add other files and add links here 

* ...

**Comment by dktapps** [comment]
your version is outdated, again.

**Comment by kenygamer** [comment]
@dktapps I see.

**Comment by kenygamer** [comment]
@dktapps I just installed the latest PocketMine-MP release and I continue to present exactly the same issue, without and with plugins.

**Comment by kenygamer** [comment]
@dktapps Please reopen this issue, it’s now valid.

**Comment by dktapps** [comment]
and you're sure you're not just inside the spawn protection radius? I can't reproduce this
