### ISSUE TITLE
Test Xbox suggestion

### ISSUE THREAD

**Issue by TDMidkwhatisxd** [pmmp/PocketMine-MP#1430]
Hi, please hear me out.

I think there should be a /online command.
This should check if the server force xbox auth. Example Message "Xbox auth on" or something like that.
Why should this command be added.
Maybe some download a bad plugin, or just a glitch happen, or you turned it off and forget to turn on online mode.

If this is a spam, please don't ban me , I will keep ideas for me. It just that right now I think its a great idea , and maybe I'm wrong.

**Comment by dktapps** [comment]
write a plugin...

**Comment by TDMidkwhatisxd** [comment]
I'm sorry ^^ .

**Comment by dktapps** [comment]
no need to be sorry, there just isn't any reason to put this into PocketMine-MP itself when this can be implemented as a plugin. Non-vanilla features like this should generally stay out of the core.

There are also startup messages to warn you if authentication is not enabled.
