### ISSUE TITLE
Minecraft Windows 10 can't connect to locally hosted PocketMine server

### ISSUE THREAD

**Issue by CCF100** [pmmp/PocketMine-MP#1432]
### Steps to reproduce the issue

1. Create PocketMine server on hosted computer
2. Try to connect to server using localhost, local ip, public ip, or domain name linking to public ip

### OS and versions

* PocketMine-MP: PocketMine-MP 1.7dev-83 「[REDACTED]」 implementing API version 3.0.0-ALPHA8 for Minecraft: PE v1.2.0.81 (protocol version 137)
* PHP: 7.2.0RC2 (Could be wrong)
* Server OS: Windows 10 Home
* Game version: Win10

### NOTE:
I can connect on MCPE

**Comment by dktapps** [comment]
If you need help, use the links below. 
- http://pmmp.readthedocs.io/en/rtfd/ - Documentation

**Comment by CCF100** [comment]
Thank you! 👍

**Comment by TDMidkwhatisxd** [comment]
Launch Window PowerShell as an administrator and run the following:
CheckNetIsolation LoopbackExempt -a -n="Microsoft.MinecraftUWP_8wekyb3d8bbwe"

is a copypasta from someone that helped me.
