### ISSUE TITLE
Raklib Interface

### ISSUE THREAD

**Issue by HipsterAF** [pmmp/PocketMine-MP#1433]
### Issue description

Crash on start.
### Steps to reproduce the issue

1. ...
2. ...

### OS and versions

* PocketMine-MP:  9cd7f39
* PHP: 7.2
* Server OS: Windows 10
* Game version: PE

### Plugins
- Tested on a clean server

### Crashdump, backtrace or other files
https://crash.pmmp.io/view/8694

* ...

**Comment by dktapps** [comment]
outdated submodule version
