### ISSUE TITLE
No fire lighting sound

### ISSUE THREAD

**Issue by TheShinPin** [pmmp/PocketMine-MP#1434]
### Issue description
When trying to light a fire with flint and steel, their is no sound.
1. ...get on da server
2. ...try an light a fire man... no sound

### OS and versions
<!--- PocketMine-MP version 1.7dev-123 "[REDACTED]" (API 3.0.0-ALPHA9)

**Comment by dktapps** [comment]
please fill in the issue template with the required information next time.

**Comment by TheShinPin** [comment]
Sorry, I thought it was pretty self-explanatory.

**Comment by jasonwynn10** [comment]
what build of PocketMine are you using?

**Comment by dktapps** [comment]
it doesn't matter what version he's using because I know it's an issue in latest builds.
