### ISSUE TITLE
Tips for commands don't work

### ISSUE THREAD

**Issue by rdstonech** [pmmp/PocketMine-MP#1435]
### Issue description

1. I don't have tips for commands when I write a command
2. I don't have default commands in tips

### Steps to reproduce the issue

1. Write command to chat

### OS and versions

* PocketMine-MP: https://github.com/pmmp/PocketMine-MP/commit/42dd9d6abd4e7a66611cd171abd0f8f7969166c1
* PHP: 7.2.0 RC3
* Server OS: Ubuntu 16.04

### Plugins
- Test on a clean server without plugins: is the issue reproducible without any plugins loaded? Yeah
* ...

**Comment by dktapps** [comment]
This is not implemented yet. Please do not create issues for missing gameplay features.

**Comment by rdstonech** [comment]
@dktapps hm, why you closed this issue? This issue is not fixed. You'll close this issue when fixed
