### ISSUE TITLE
addTile() on null

### ISSUE THREAD

**Issue by HipsterAF** [pmmp/PocketMine-MP#1436]
### Issue description

addTile() on null when i try to spawn
### Steps to reproduce the issue

1. ...
2. ...

### OS and versions

* PocketMine-MP: c32b75fa
* PHP: 7.0.3
* Server OS: linux
* Game version: PE

### Crashdump, backtrace or other files
https://crash.pmmp.io/view/3826
* ...

**Comment by dktapps** [comment]
outdated version
