### ISSUE TITLE
Command /help not working

### ISSUE THREAD

**Issue by zKoz210** [pmmp/PocketMine-MP#1438]
### Issue description

With version Minecraft: Bedrock Edition 1.2 command /help does not work

### Steps to reproduce the issue

1. Join to server
2. Use command /help

### OS and versions

* PocketMine-MP: https://github.com/pmmp/PocketMine-MP/commit/afa37bd2aa5921def6234310f5d9d81245f32854
* PHP: 7.2
* Game version: PE/Win10

### Crashdump, backtrace or other files
![image](https://user-images.githubusercontent.com/28255085/31053962-c1783a0a-a6b0-11e7-9d02-98956da50ab7.png)

**Comment by TheDiamondYT1** [comment]
`/help` is now forced by the client and the server has no control over it.

You can run `./help` as a workaround until Mojang get their sh1t together

**Comment by optimusprime338** [comment]
@TheDiamondYT1 sorry to interrupt but same work on nukkit as it used to..!! Don't know the reason but just saying..

**Comment by TDMidkwhatisxd** [comment]
who else crash wen using commands? Is it random?

**Comment by dktapps** [comment]
The /help command is client-side. The reason commands don't show up is because the command sending is not implemented yet.

**Comment by LewBr** [comment]
I want to cancel /help command -.-

**Comment by optimusprime338** [comment]
@TDMidkwhatisxd  u dont only crash on /help command ,,it crashes on other commands , mainly when you type space after a command then it crashes then app but its not like it crashes on every command. dont know when but players keep crashing!

**Comment by thebigsmileXD** [comment]
Might be related to the client issue: Commands, that are known by the client, for example /effect will not use the server-side reply, instead send client sided message that the command is used wrong.

**Comment by dktapps** [comment]
A partial implementation of this has been done on `mcpe-1.2.5`.
