### ISSUE TITLE
Flowers in flowerpots dissapear

### ISSUE THREAD

**Issue by Landy005** [pmmp/PocketMine-MP#144]
## Issue description

Flowers in flower pot dissapear after placed in. When placed in they show for a moment untill it a certain moment then it dissapears. When implementing a map with flower pots the flowers are out of it too.

## Steps to reproduce the issue
Join server
Place flowerpot and a flower. Go away from it and come back.

## OS and versions
PocketMine-MP: PocketMine-MP 1.6.1dev-#103
PHP: 7.0.13
Server OS: Linux (tested on 2 servers)
Game version: PE/Win10 (all) 0.16.2

**Comment by dktapps** [comment]
Just a note: flower pot spawn compound in PC is different to what it is in PE, so flower pots in imported worlds will not work correctly.

**Comment by Landy005** [comment]
Yes, but it also was with imported mcr maps not only mca maps, but idk if that makes a diffrence?

**Comment by dktapps** [comment]
Those are both PC formats. Any PC world will have that issue.

**Comment by dktapps** [comment]
Is this still reproducible with the current `mcpe-1.0` development branch?

**Comment by dktapps** [comment]
Closing due to lack of response.
