### ISSUE TITLE
Where I can found pmmp code style for phpstorm?

### ISSUE THREAD

**Issue by Frago9876543210** [pmmp/PocketMine-MP#1441]
### Issue description
Read the title. @dktapps Can you place code style on [site](https://pmmp.io/) for pull requests?

**Comment by Frago9876543210** [comment]
why? I want do pull

**Comment by HimbeersaftLP** [comment]
https://github.com/pmmp/PocketMine-MP/blob/master/CONTRIBUTING.md#code-syntax
