### ISSUE TITLE
Server Stopped when i join

### ISSUE THREAD

**Issue by VoxCeleste** [pmmp/PocketMine-MP#1443]
PocketMine-MP Crash Dump Mon Oct 2 11:19:04 UTC 2017

Error: Argument 1 passed to pocketmine\network\mcpe\protocol\DataPacket::putVector3Obj() must be an instance of pocketmine\math\Vector3, null given, called in phar:///home/gs/gs/data/servers/7426497/PocketMine-MP_1.7dev-128_afa37bd2_API-3.0.0-ALPHA9.phar/src/pocketmine/network/mcpe/protocol/AddEntityPacket.php on line 95
File: src/pocketmine/network/mcpe/protocol/DataPacket
Line: 446
Type: notice

Code:
[437] 		}
[438] 	}
[439] 
[440] 	/**
[441] 	 * Writes a floating-point Vector3 object
[442] 	 * TODO: get rid of primitive methods and replace with this
[443] 	 *
[444] 	 * @param Vector3 $vector
[445] 	 */
[446] 	public function putVector3Obj(Vector3 $vector){
[447] 		($this->buffer .= (\pack("g", $vector->x)));
[448] 		($this->buffer .= (\pack("g", $vector->y)));
[449] 		($this->buffer .= (\pack("g", $vector->z)));
[450] 	}
[451] 
[452] 	public function getByteRotation() : float{
[453] 		return (float) ((\ord($this->get(1))) * (360 / 256));
[454] 	}
[455] 
[456] 	public function putByteRotation(float $rotation){

Backtrace:
#0 src/pocketmine/network/mcpe/protocol/AddEntityPacket(95): pocketmine\network\mcpe\protocol\DataPacket->putVector3Obj(NULL )
#1 src/pocketmine/network/mcpe/protocol/DataPacket(98): pocketmine\network\mcpe\protocol\AddEntityPacket->encodePayload()
#2 src/pocketmine/network/mcpe/RakLibInterface(208): pocketmine\network\mcpe\protocol\DataPacket->encode()
#3 src/pocketmine/Player(1139): pocketmine\network\mcpe\RakLibInterface->putPacket(pocketmine\Player object, pocketmine\network\mcpe\protocol\AddEntityPacket object, boolean , boolean )
#4 src/pocketmine/Player(1101): pocketmine\Player->sendDataPacket(pocketmine\network\mcpe\protocol\AddEntityPacket object, boolean , boolean )
#5 PureEntitiesX-master/src/revivalpmmp/pureentities/entity/BaseEntity(218): pocketmine\Player->dataPacket(pocketmine\network\mcpe\protocol\AddEntityPacket object)
#6 src/pocketmine/Player(874): revivalpmmp\pureentities\entity\BaseEntity->spawnTo(pocketmine\Player object)
#7 src/pocketmine/level/Level(2425): pocketmine\Player->sendChunk(integer 79, integer 59, pocketmine\network\mcpe\protocol\BatchPacket object)
#8 src/pocketmine/level/format/io/ChunkRequestTask(91): pocketmine\level\Level->chunkRequestCallback(integer 79, integer 59, pocketmine\network\mcpe\protocol\BatchPacket object)
#9 src/pocketmine/scheduler/AsyncPool(164): pocketmine\level\format\io\ChunkRequestTask->onCompletion(pocketmine\Server object)
#10 src/pocketmine/scheduler/ServerScheduler(342): pocketmine\scheduler\AsyncPool->collectTasks()
#11 src/pocketmine/Server(2512): pocketmine\scheduler\ServerScheduler->mainThreadHeartbeat(integer 1572)
#12 src/pocketmine/Server(2257): pocketmine\Server->tick()
#13 src/pocketmine/Server(2136): pocketmine\Server->tickProcessor()
#14 src/pocketmine/Server(1718): pocketmine\Server->start()
#15 src/pocketmine/PocketMine(556): pocketmine\Server->__construct(BaseClassLoader object, pocketmine\utils\MainLogger object, string phar:///home/gs/gs/data/servers/7426497/PocketMine-MP_1.7dev-128_afa37bd2_API-3.0.0-ALPHA9.phar/, string /home/gs/gs/data/servers/7426497/, string /home/gs/gs/data/servers/7426497/plugins/)
#16 /home/gs/gs/data/servers/7426497/PocketMine-MP_1.7dev-128_afa37bd2_API-3.0.0-ALPHA9.phar(1): require(string phar:///home/gs/gs/data/servers/7426497/PocketMine-MP_1.7dev-128_afa37bd2_API-3.0.0-ALPHA9.phar/src/pocketmine/PocketMine.php)

PocketMine-MP version: 1.7dev #128 [Protocol 137; API 3.0.0-ALPHA9]
Git commit: 0000000000000000000000000000000000000000
uname -a: Linux ca39.server.pro 3.14.32-xxxx-grs-ipv6-64 #9 SMP Thu Oct 20 14:53:52 CEST 2016 x86_64
PHP Version: 7.2.0RC2
Zend version: 3.2.0-dev
OS : Linux, linux

**Comment by dktapps** [comment]
plugin issue.
