### ISSUE TITLE
Multiple Mobs By A Spawn Egg.

### ISSUE THREAD

**Issue by MasterOfTheRealm** [pmmp/PocketMine-MP#1444]
### Issue description

Spawning Mobs From Spawn Eggs While Player Is Moving Spawns 7-8 Mobs At Once.

### Steps to reproduce the issue

1. Spawn A Mob (Zombie, Villager) While Player Is Moving.

### OS and versions

* PocketMine-MP: PocketMine-MP 1.7dev-65 「[REDACTED]」 implementing API version 3.0.0-ALPHA8 for Minecraft: PE v1.2.0.81 (protocol version 137)
* PHP: 7.2
* Server OS: Windows 10
* Game version: Win10

### Plugins
- Test on a clean server without plugins: is the issue reproducible without any plugins loaded?

  Yes

**Comment by matcracker** [comment]
Unfortunately, this is a client bug and can't be solved by PMMP team. Please, be patient for future MC:BE updates.

**Comment by MasterOfTheRealm** [comment]
Oh i see. Thanks
