### ISSUE TITLE
Server keeps crashing

### ISSUE THREAD

**Issue by BajanVlogs** [pmmp/PocketMine-MP#1445]
02.10 17:17:19 [Server] Server thread/CRITICAL TypeError: "Argument 2 passed to pocketmine\nbt\tag\StringTag::__construct() must be of the type string, null given, called in phar:///pmmp_65_1.2.phar/src/pocketmine/entity/Entity.php on line 778" (EXCEPTION) in "src/pocketmine/nbt/tag/StringTag" at line 38

**Comment by dktapps** [comment]
Without knowing your PocketMine-MP version, OS, PHP, Client version, or plugins and how the issue occurred, the issue cannot begin to be solved.
A pre-formatted template is provided that shows the required information to begin to find, test and solve an issue.
Until the adequate template and information is provided, the issue will be closed; it may be reopened if you update the ticket with the correct template and required information.

[Contribution guidelines](https://github.com/pmmp/PocketMine-MP/blob/master/CONTRIBUTING.md)
