### ISSUE TITLE
Cannot place slabs in half-block gaps

### ISSUE THREAD

**Issue by dktapps** [pmmp/PocketMine-MP#145]
### Issue description
![screenshot_2016-12-03-19-17-52](https://cloud.githubusercontent.com/assets/14214667/20869530/2f88f99e-ba6c-11e6-95e3-9d77bd476f2d.png)
Try to place a slab as indicated in the screenshot and it will vanish.

### Steps to reproduce the issue

1. try and place a slab on the face of another slab in a half-block gap (I think?)

### OS and versions

* PocketMine-MP: 4674d34
* PHP: 7.0.13 x64
* Server OS: Linux
* Game version: PE/Win10

**Comment by archie426** [comment]
I think this was to do with the security thing that @shoghicp added? Sorry for not being specific, but I seem to remember something like this being on the olod forums

**Comment by Sandertv** [comment]
#31

**Comment by TheUSBFlash** [comment]
Well, singleplayer has the same issue, you can only place them when tapping a block side (in your case the iron block at the right)

**Comment by dktapps** [comment]
This is an issue with Block->getSide() on the inner-half face of the slab returning the _next_ block. If the block in the next space is not replaceable, this bug will occur.

**Comment by Muqsit** [comment]
I remember this one when I first started playing factions on PE servers. Can't believe no one has fixed it yet ._.

**Comment by dktapps** [comment]
@Muqsit welcome to my world...

**Comment by dktapps** [comment]
This has been fixed on a development branch and will be closed when the fix is merged to master (no ETAs will be given).
