### ISSUE TITLE
[FIXED] Invalid session

### ISSUE THREAD

**Issue by Akuroma** [pmmp/PocketMine-MP#1454]
### Issue description

Players can't join. Error: "Invalid session (Try restarting your game)".

- Expected result: Players can join and play
- Actual result: Players can't join. Errormessage: "Invalid session (try restarting your game)

### Steps to reproduce the issue

1. Install server and run it
2. Try to join onto this server

### OS and versions

* PocketMine-MP: PocketMine-MP 1.7dev-171 「[REDACTED]」
* PHP: 7.0
* Server OS: Linux (Ubuntu 14.04.)
* Game version: PE

### Plugins
- Error is there without plugins and with plugins

### Crashdump, backtrace or other files

[20:49:18] [Server thread/INFO]: LokiBurrito2713[/79.212.215.13:36686] loggte sich wegen "Invalid session" aus

* ...

**Comment by dktapps** [comment]
is your server time correct?

**Comment by Akuroma** [comment]
Well in PocketMine it's 20:54 and in Germany where I live it's 21:56.

**Comment by dktapps** [comment]
the tokens are valid for several days, so check the date is correct as well.

**Comment by Akuroma** [comment]
But how? I don't know how to do this. Could you give me an instruction?
