### ISSUE TITLE
Change unknown byte in entity links

### ISSUE THREAD

**Issue by thebigsmileXD** [pmmp/PocketMine-MP#1465]
### Issue description

The software still names the 4th parameter in SetEntityLinkPacket as unknown, though it's usage is already known for a ~~while now: which seat the entity will be linked to.~~ _EDIT: see @dktapps reply below, was mistaken there_

Entities that can be ridden can have multiple seats, example: boats. Boats have a front and a back seat. The byte decides where you sit at, and combined with `DATA_CONTROLLING_RIDER_SEAT_NUMBER` it can be used to make passengers + "drivers"

- Expected result: What were you expecting to happen?
- Actual result: What actually happened?

### Steps to reproduce the issue

1. ...
2. ...

### OS and versions

* PocketMine-MP: *
* PHP: 7.2
* Server OS: *

### Plugins
- Test on a clean server without plugins: is the issue reproducible without any plugins loaded?

If the issue is **not** reproducible without plugins:
- Have you asked for help on our forums before creating an issue?
- Can you provide sample, *minimal* reproducing code for the issue? If so, paste it in the bottom section
- Paste your list of plugins here (use the 'plugins' command in PocketMine-MP)

### Crashdump, backtrace or other files
- Do not paste crashdumps into an issue - please use our Crash Archive at https://crash.pmmp.io for submitting crash reports to not spam the issue tracker. Add links to your reports in the Crash Archive here.
- Please use gist or anything else to add other files and add links here 

* ...

**Comment by dktapps** [comment]
Actually, it is a boolean which determines whether the rider should be directly removed or flagged to be removed later.

**Comment by thebigsmileXD** [comment]
WTF, why would you remove someone "later"
