### ISSUE TITLE
Attributes exceeds range error

### ISSUE THREAD

**Issue by JackNoordhuis** [pmmp/PocketMine-MP#147]
### Issue description
After applying a speed effect to a player with an amplifier higher than 127 the server acts fine. When the player whom has the effect leaves and then joins the server again (while retaining the effect) an error will be thrown when the server tries to apply the saved effect.

[View Error](https://gist.github.com/JackNoordhuis/0ecc6333789fc09c2bd7b4b9942d9b16)

### Steps to reproduce the issue
1. Apply a speed effect to yourself with a high value (/effect {player} speed 1000 128)
2. Leave the server
3. Join the server
4. Profit!

### OS and versions
* PocketMine-MP: 1.6.1dev 「Unleashed」 implementing API version 2.1.0 for Minecraft: PE v0.16.0.5 alpha (protocol version 91) 
* Commit: https://github.com/pmmp/PocketMine-MP/commit/4674d34469584c60816fedeb292cbbd7376fb019
* PHP: 7
* Server OS: Doesn't matter (MacOS if you really wanna know)

### Crashdump, backtrace or other files
Error: https://gist.github.com/JackNoordhuis/0ecc6333789fc09c2bd7b4b9942d9b16

**Comment by dktapps** [comment]
Happens all the time spawning squid too.

**Comment by JackNoordhuis** [comment]
The error is triggered due to the value being -1.02 when it should be 200 so the integers value is being changed somewhere in the process of being saved and loaded.

**Comment by dktapps** [comment]
The number I always see with speed is -2.46, but here's how it happens:
- Amplifier is stored as a ByteTag, and you've given it amplifier 128, which then becomes _-128_
- When restored, attributes are processed and modified based on the amplifier of the effect
- Speed by default is 0.1, so this happens:

`attribute level = 0.1 * (1 + 0.2 * -128);`

which comes out as -2.46

Something similar will apply for slowness.

**Comment by MCPEPIG** [comment]
Um, this is still open.

**Comment by jojoe77777** [comment]
@MCPEPIG It hasn't been merged yet (https://github.com/pmmp/PocketMine-MP/pull/191)

**Comment by dktapps** [comment]
Yep, our translation system is a heap of crap, we're working on fixing it. That pull request requires new language additions.

**Comment by dktapps** [comment]
This has been fixed on a development branch. The fix will be merged to master at a later date (no date of merge can be given).
