### ISSUE TITLE
Buckets fill whole stacks at once

### ISSUE THREAD

**Issue by jasonwynn10** [pmmp/PocketMine-MP#1472]
### Issue description

When a water source block is tapped on by a stack of empty buckets in the player's hand, the entire stack of buckets is filled.

- Expected result: Only one bucket would be filled, and it would be moved into it's own slot. The remaining buckets stay stacked in their slot
- Actual result: All buckets in the stack were filled, and no buckets were moved into their own slot

### Steps to reproduce the issue

1. In creative mode, add a stack of empty buckets to your inventory
2. Change to survival mode
3. Tap on a water or lava source with the stack of empty buckets
4. Profit!

### OS and versions

* PocketMine-MP: 1.7dev-269 「[REDACTED]」 implementing API version 3.0.0-ALPHA9 for Minecraft: PE v1.2.0.81 (protocol version 137)
* PHP: 7.2.0RC4
* Server OS: Windows 10
* Game version: PE

### Plugins
- Test on a clean server without plugins: is the issue reproducible without any plugins loaded?
Yes
If the issue is **not** reproducible without plugins:
- Have you asked for help on our forums before creating an issue?
- Can you provide sample, *minimal* reproducing code for the issue? If so, paste it in the bottom section
- Paste your list of plugins here (use the 'plugins' command in PocketMine-MP)

### Crashdump, backtrace or other files
- Do not paste crashdumps into an issue - please use our Crash Archive at https://crash.pmmp.io for submitting crash reports to not spam the issue tracker. Add links to your reports in the Crash Archive here.
- Please use gist or anything else to add other files and add links here 
* https://photos.app.goo.gl/SptM7FXg34dZo1z73
* https://photos.app.goo.gl/sXCFq56xumB3z1XM2

**Comment by dktapps** [comment]
Technically speaking this is just a non-implemented feature, since the core code doesn't currently allow stacking buckets. However, the creative issue _is_ a bug.
