### ISSUE TITLE
entity stepping doesn't work correctly

### ISSUE THREAD

**Issue by dktapps** [pmmp/PocketMine-MP#1475]
- step height is hardcoded to 0.5
- doesn't account for stepping multiple times in one movement, e.g. players running up stairs

**Comment by jasonwynn10** [comment]
This makes so much more sense now...

**Comment by Driesboy** [comment]
s

**Comment by KennFatt** [comment]
I have a little proof, you can see this video: [Here](https://www.youtube.com/watch?v=t0UMWTkIcWE)
Disguise has normal motion and movement before (on 0.8.1). I had this issue since 0.1x.x i guess.

**Comment by dktapps** [comment]
problem n.2 doesn't exist in vanilla conditions, and only exists in PM for players because of #1215

**Comment by dktapps** [comment]
n.1 is fixed by https://github.com/pmmp/PocketMine-MP/commit/89fe8f7f10716fed6193646984a7e2d28f6f6ce5.

n.2 seems to be an issue regardless of how movement is processed, so I'm leaving this issue open for now.
