### ISSUE TITLE
Zombies Drop Feathers

### ISSUE THREAD

**Issue by thebigsmileXD** [pmmp/PocketMine-MP#1479]
### Issue description

https://github.com/pmmp/PocketMine-MP/blob/master/src/pocketmine/entity/Zombie.php#L43

- Expected result: What were you expecting to happen?
- Actual result: What actually happened?

### Steps to reproduce the issue

1. ...
2. ...

### OS and versions

* PocketMine-MP:
* PHP:
* Server OS:
* Game version: PE/Win10 (delete as appropriate)

### Plugins
- Test on a clean server without plugins: is the issue reproducible without any plugins loaded?

If the issue is **not** reproducible without plugins:
- Have you asked for help on our forums before creating an issue?
- Can you provide sample, *minimal* reproducing code for the issue? If so, paste it in the bottom section
- Paste your list of plugins here (use the 'plugins' command in PocketMine-MP)

### Crashdump, backtrace or other files
- Do not paste crashdumps into an issue - please use our Crash Archive at https://crash.pmmp.io for submitting crash reports to not spam the issue tracker. Add links to your reports in the Crash Archive here.
- Please use gist or anything else to add other files and add links here 

* ...

**Comment by thebigsmileXD** [comment]
Quoted from https://minecraft.gamepedia.com/Zombie#History,l 0.11

> Zombies now drop rotten flesh.

**Comment by thebigsmileXD** [comment]
You might hate me for saying it, but: they also drop random stuff like: Iron ingots, potatos, carrots

**Comment by Sandertv** [comment]
> thebigsmileXD: You might hate me for saying it, but: they also drop random stuff like: Iron ingots, potatos, carrots

Yeah because this code produces some delicious cake drops:
```php
if(mt_rand(0, 199) < 5){
	switch(mt_rand(0, 2)){
		case 0:
			$drops[] = ItemFactory::get(ItemItem::IRON_INGOT, 0, 1);
			break;
		case 1:
			$drops[] = ItemFactory::get(ItemItem::CARROT, 0, 1);
			break;
		case 2:
			$drops[] = ItemFactory::get(ItemItem::POTATO, 0, 1);
			break;
	}
}
```

**Comment by thebigsmileXD** [comment]
[Resolution: Fixed] ;)
