### ISSUE TITLE
./ and / crash the game

### ISSUE THREAD

**Issue by TDMidkwhatisxd** [pmmp/PocketMine-MP#1481]
### Issue description

Hi, using ./ or / , may cause the client to crash, even me and players crash sometimes.
I don't know why we crash even by using "./" , maybe client have a strange reaction to it?
So, I suggest changing ./ to  ':' , ';' , '!' or @ .
Sorry if this issue is useless, its just that I'm tired of client crashes.

- Expected result: What were you expecting to happen?
no client crash
- Actual result: What actually happened?
client crashed
### Steps to reproduce the issue

1. ... stay some time in a server with your friends
2. ... try using commands

### OS and versions

* PocketMine-MP:
* PHP:
* Server OS:
* Game version: PE/Win10 (delete as appropriate)

### Plugins
- Test on a clean server without plugins: is the issue reproducible without any plugins loaded?

If the issue is **not** reproducible without plugins:
- Have you asked for help on our forums before creating an issue?
- Can you provide sample, *minimal* reproducing code for the issue? If so, paste it in the bottom section
- Paste your list of plugins here (use the 'plugins' command in PocketMine-MP)

### Crashdump, backtrace or other files
- Do not paste crashdumps into an issue - please use our Crash Archive at https://crash.pmmp.io for submitting crash reports to not spam the issue tracker. Add links to your reports in the Crash Archive here.
- Please use gist or anything else to add other files and add links here 

* ...

If you close the issue can  you tell me why is happening? On windows10 , game start to use 4gb ram and pc freeze instead of game crash 0-0 .

I'm sorry in advance if this issue is useless.

**Comment by dktapps** [comment]
This is a client-sided bug related to chat in general, check https://bugs.mojang.com . Nothing we can do about this, sorry.

**Comment by TDMidkwhatisxd** [comment]
thanks a lot for info .
