### ISSUE TITLE
Inventory items are duplicated when players are killed in PlayerQuitEvent

### ISSUE THREAD

**Issue by Bluzzi** [pmmp/PocketMine-MP#1482]
Hello, when I disconnect, then reconnects, here is what happens (watch gif), kill the player when disconnected.

Sorry for my bad english i'm french :/

Gif: http://www.hostingpics.net/viewer.php?id=205605GifDupli.gif

* PocketMine-MP: https://github.com/pmmp/PocketMine-MP/commit/bc7ba3b3c10d48a37e1e8493e91a72e6e41a4af2
* PHP: 7.2
* Server OS: Debian
* Game version: Win10 and Android phone.

**Comment by Bluzzi** [comment]
(Watch the diamond)

**Comment by matcracker** [comment]
The issue can't be reproduced without plugins. This means that you're probably adding one diamond (and one paper) everytime the player join.

**Comment by Bluzzi** [comment]
@matcracker 

No, I do not give any stuff, and I do not give any stuff when a player joins.

**Comment by Bluzzi** [comment]
No, I do not give any stuff, and I do not give any stuff when a player joins.

**Comment by Bluzzi** [comment]
@matcracker No, I do not give any stuff, and I do not give any stuff when a player joins.

**Comment by dktapps** [comment]
then where does the paper come from?

**Comment by Bluzzi** [comment]
@dktapps The player with me has to drop it, try for yourself just kill the player in onQuit, and deco with stuff, reconnecting, the stuff will be doubled.

**Comment by dktapps** [comment]
This is because player data is now saved before PlayerQuitEvent is called.

**Comment by Bluzzi** [comment]
@dktapps Hmm... and how can I fix that?

**Comment by optimusprime338** [comment]
well this started happening after you fixed double chest glitch thingy

**Comment by dktapps** [comment]
@Bluzzi Try cancelling PlayerDataSaveEvent for that player, then save their data manually in PlayerQuitEvent using `Player->save()` AFTER you kill them.

**Comment by Bluzzi** [comment]
@dktapps It does not work :/

`
public function onSavePlayer(PlayerDataSaveEvent $event){
        if(isset($this->dcombat[$event->getPlayer()->getName()])){
            $event->setCancelled(true);
        }
    }

    public function onQuit(PlayerQuitEvent $event){
        $player = $event->getPlayer();
        $name = $player->getName();

        foreach($this->plugin->getServer()->getOnlinePlayers() as $players){
			$players->sendPopup("§c- ".$name." -");
        }

        if(isset($this->dcombat[$name])){
            $player->kill();
            $player->save();
        }
        
        $this->plugin->unsetAll($player);
        $event->setQuitMessage(null);
    }
`

**Comment by MasterOfTheRealm** [comment]
I had the same problem and using `$player->save();` works.

**Comment by matcracker** [comment]
Instead of kill the player, try to use $player->getInventory()->dropContents($player->getLevel(), $player->asVector3());

**Comment by optimusprime338** [comment]
I had this problem with custome Enchats plugin but without it I don't get that issue
