### ISSUE TITLE
PHP 7.2 with GLIBC <= 2.12 or just add PHP 7.0 support back?

### ISSUE THREAD

**Issue by fengberd** [pmmp/PocketMine-MP#1483]
### Issue description
I'm trying to run pmmp on one of my linux server with CentOS 6.9,as is know to all there's only GLIBC 2.12 for CentOS6,for some reason it's really hard to upgrade to CentOS7.
When I use the PHP 7.2 from [PMMP Jenkins](https://jenkins.pmmp.io/job/PHP-7.2-Linux-x86_64/),it just exit with the following message:
```
./php: /lib64/libm.so.6: version `GLIBC_2.15' not found (required by ./php)
./php: /lib64/libc.so.6: version `GLIBC_2.14' not found (required by ./php)
./php: /lib64/libc.so.6: version `GLIBC_2.14' not found (required by /root/bin/php7/bin/../lib/libz.so.1)
./php: /lib64/libc.so.6: version `GLIBC_2.14' not found (required by /root/bin/php7/bin/../lib/libyaml-0.so.2)
./php: /lib64/libc.so.6: version `GLIBC_2.14' not found (required by /root/bin/php7/bin/../lib/libcurl.so.4)
./php: /lib64/libc.so.6: version `GLIBC_2.17' not found (required by /root/bin/php7/bin/../lib/libcurl.so.4)
```
After some research I found that is caused by the GLIBC too old.Then I tried to build PHP7.2 on that server but failed with some code syntax error(?).

### Steps to reproduce the issue

1. Use any linux with GLIBC<=2.12 like CentOS6
2. Download PHP binary from pmmp jenkins
3. Run the PHP binary with any parameters.

### OS and versions
* PocketMine-MP: Any
* PHP: 7.2 from PMMP Jenkins
* Server OS: CentOS release 6.9 (Final)
* Game version: Any

### Plugins
Nope.

### Crashdump, backtrace or other files
```
./php: /lib64/libm.so.6: version `GLIBC_2.15' not found (required by ./php)
./php: /lib64/libc.so.6: version `GLIBC_2.14' not found (required by ./php)
./php: /lib64/libc.so.6: version `GLIBC_2.14' not found (required by /root/bin/php7/bin/../lib/libz.so.1)
./php: /lib64/libc.so.6: version `GLIBC_2.14' not found (required by /root/bin/php7/bin/../lib/libyaml-0.so.2)
./php: /lib64/libc.so.6: version `GLIBC_2.14' not found (required by /root/bin/php7/bin/../lib/libcurl.so.4)
./php: /lib64/libc.so.6: version `GLIBC_2.17' not found (required by /root/bin/php7/bin/../lib/libcurl.so.4)
```

* ...

**Comment by KnownUnown** [comment]
php <7.2 isn't supported anymore due to instability with the pthreads extension in these versions. If you have a problem with PHP compilation, open an issue at pmmp/php-build-scripts.

**Comment by dktapps** [comment]
have you tried compiling your own using https://github.com/pmmp/php-build-scripts/blob/master/compile.sh ? CentOS is not amongst our currently tested platforms, so right now there's not much I can do to help.

**Comment by fengberd** [comment]
pmmp/php-build-scripts don't support issue when I submit this one...
I tried to compile it by the script,also failed...pthreads gave me a bunch
of error messages.

**Comment by Awzaw** [comment]
The best solution for this is to update to CentOS7. If that's not an option, refer to [this thread](https://forums.pmmp.io/threads/unable-to-launch-server-glibc_2-17-not-found.3976/#post-37694)

**Comment by dschwartz783** [comment]
I run this on CentOS 6.9, and it works flawlessly. Admittedly, I compiled PHP myself manually, so I could enable certain features that the script disables.
