### ISSUE TITLE
ItemFactory::fromString() returns air wether it actually is air or a misspelled/not existing item

### ISSUE THREAD

**Issue by thebigsmileXD** [pmmp/PocketMine-MP#1487]
### Issue description

ItemFactory::fromString() always returns air as last option, instead of null (aka not existing).

Example: 
`
ItemFactory::fromString("socks")`
ItemFactory function:

`if(defined(Item::class . "::" . strtoupper($b[0]))){`
-> No, it is not defined, continue
`}elseif(is_numeric($b[0])){`
-> No, "socks" is not numeric, continue
```
}else{
$item = self::get(Item::AIR, 0, 0);
}
```
-> get air, though the item "socks" does not exist, so not an item

The check inside of the isdefined check:
`$item = self::get(constant(Item::class . "::" . strtoupper($b[0])), $meta);`
-> constant() would throw an E_WARNING -> THIS could be used as actual check

`if($item->getId() === Item::AIR and strtoupper($b[0]) !== "AIR" and is_numeric($b[0])){`

atleast tries to check if it is air, but will never be called for unknown items
This check is unlogical anyways, is_numeric AND strtoupper does not work together (you can not strtoupper a number), it will always return false

- Expected result: What were you expecting to happen?
Probably getting null or atleast an error/warning
- Actual result: What actually happened?
Always getting air

### Steps to reproduce the issue

1. see above

### OS and versions

* PocketMine-MP: PocketMine-MP 1.7dev 3.0.0-ALPHA9 [REDACTED] 
* PHP: 7.2.0RC4

### Plugins
- Test on a clean server without plugins: is the issue reproducible without any plugins loaded?

If the issue is **not** reproducible without plugins:
- Have you asked for help on our forums before creating an issue?
- Can you provide sample, *minimal* reproducing code for the issue? If so, paste it in the bottom section
- Paste your list of plugins here (use the 'plugins' command in PocketMine-MP)

### Crashdump, backtrace or other files
- Do not paste crashdumps into an issue - please use our Crash Archive at https://crash.pmmp.io for submitting crash reports to not spam the issue tracker. Add links to your reports in the Crash Archive here.
- Please use gist or anything else to add other files and add links here 

Here is a fix i've been working on:

```php


			if (is_numeric($b[0])){
				$item = ItemFactory::get(((int)$b[0]) & 0xFFFF, $meta);
			} elseif (defined(Item::class . "::" . strtoupper($b[0]))){
				$item = ItemFactory::get(constant(Item::class . "::" . strtoupper($b[0])), $meta);
				if ($item->getId() === Item::AIR and strtoupper($b[0]) !== "AIR"){
					$item = null;
				}
			} else{
				$item = null;
			}
```

**Comment by dktapps** [comment]
The point of air's existence is to be a null, so I don't take your point. Changing this behaviour would additionally potentially break a lot of plugins using this with vanilla items which are legitimately not implemented yet.

**Comment by thebigsmileXD** [comment]
The reason i made this issue and complained about it is this function:
```php
public static function blockParser(string $fullstring, array &$messages, bool &$error){
		$blocks = [];
		foreach (self::fromString($fullstring, true) as $item){
			var_dump($item);
			$block = $item->getBlock();
			if ((!$item instanceof Item) || ($item->getId() !== Item::AIR && $block->getId() === Block::AIR)){
				$error = true;
				$messages[] = Loader::$prefix . TextFormat::RED . "Could not find a block for " . $item;
			}
			$blocks[] = $block;
			if ($block instanceof UnknownBlock){
				$messages[] = Loader::$prefix . TextFormat::RED . $block . " is an unknown block";
			}
		}

		return $blocks;
	}
```

In it i basically check if you are inserting incorrect names for blocks or the item not having a block. The issue i experience is that this code is inside a world editor plugin, which would place air if you mistyped a name - which makes no sense in this case. I have to be able to place air blocks too though

**Comment by IrishPacks** [comment]
The only solution I can think of at this point would be to add a new parameter that would allow a default return or to return null?

**Comment by dktapps** [comment]
Technically speaking it might be more beneficial to add an UnknownItem implementation for this instead of allowing a null return.

**Comment by thebigsmileXD** [comment]
@dktapps That would be useful.

---
EDIT: new code from above, working and even fetching blocks of normal items that have a block but not are itemblocks (carrot -> carrot block, wheat_seeds -> wheat block etc)
```php

	public static function fromString(string $str, bool $multiple = false){
		if ($multiple === true){
			$blocks = [];
			foreach (explode(",", $str) as $b){
				$blocks[] = self::fromString($b, false);
			}
			return $blocks;
		} else{
			$b = explode(":", str_replace([" ", "minecraft:"], ["_", ""], trim($str)));
			if (!isset($b[1])){
				$meta = 0;
			} else{
				$meta = $b[1] & 0xFFFF;
			}
			if (is_numeric($b[0])){
				$item = ItemFactory::get(((int)$b[0]) & 0xFFFF, $meta);
			} elseif (defined(Item::class . "::" . strtoupper($b[0]))){
				$item = ItemFactory::get(constant(Item::class . "::" . strtoupper($b[0])), $meta);
				if ($item->getId() === Item::AIR and strtoupper($b[0]) !== "AIR"){
					$item = null;
				}
			} else{
				$item = null;
			}
			return [$b[0], $item];
		}
	}
```
```php
			if (($item instanceof ItemBlock) or ($item instanceof Item && $item->getBlock()->getId() !== Block::AIR)){
				$block = $item->getBlock();
				$blocks[] = $block;
			} else{
				$error = true;
				$messages[] = Loader::$prefix . TextFormat::RED . "Could not find a block/item with the " . (is_numeric($name) ? "id: " : "name") . ": " . $name;
				continue;
			}
```

**Comment by dktapps** [comment]
I'm thinking an exception throw when failing to match a constant name would be more appropriate.

**Comment by zKoz210** [comment]
Why not nullable? It will look awful. You have already made a description of Exeption in the documentation in hasPermission().

**Comment by dktapps** [comment]
This function is documented to return Item or Item[], not Item|null[]. Null would require boilerplate code checks everywhere that uses this method. I think it's preferable to allow catching an exception when the developer is aware that GIGO may be occurring.

**Comment by zKoz210** [comment]
Why not make the Item|null? I use this function everywhere for just one item, I think it's superfluous. Vote? Like or dislike?
