### ISSUE TITLE
PocketMine-MP 1.6.2

### ISSUE THREAD

**Issue by dktapps** [pmmp/PocketMine-MP#149]
### Issue description
Minecraft PE & W10 v1.0 are heading for release "soon". PocketMine has a lot of catching up to do.

With reference to the points described at PocketMine/PocketMine-MP#3149, a selection of these are aimed at PocketMine 1.6.2. Due to the fact we now aim to produce some sort of release for every new version of MCPE, the time constraints will not allow all of these tasks to be completed before 1.0 release.

### What's done so far
- [x] Sending, loading and saving of 256-high chunks (capped at 128 for mcregion due to the format not supporting it)
- [x] Supporting the 256-block build height limit (whoohoo!)

### What, where?
On a private branch (**mcpe-1.0**). The changes have not yet been made public for various reasons, the main of which is that the current changes are not remotely stable yet.

### Proposed list of changes
- [ ] Implement dimension generation, loading and saving, transportation (portals)
- [ ] Automated conversion from mcregion to anvil (needed for 256-high world support)
- [ ] Threaded level loading and saving
- [ ] Weather effects and controls?
- [ ] Generator for The End

This list of changes is not final and can be modified at any time. There is no release date nor an estimated time of completion.

**Comment by Pogogo007** [comment]
Maybe you should make the branch public so people can help you with bugs n stuff?

**Comment by Sandertv** [comment]
Would it be any use if I'd make a pull request to make the right hardness, light level, all that stuff for a bunch of missing blocks? I know it doesn't really have a value, but it might just save you guys some work.

**Comment by dktapps** [comment]
@Sandertv Thanks for the offer. A new block API is currently under design, which is why none of that stuff has been added by us. If you want to, feel free and we'll review it.

**Comment by Sandertv** [comment]
Alright, I'll see if I can do something.

**Comment by dktapps** [comment]
This has been closed in favour of #179 .
