### ISSUE TITLE
PreProcessor break joining

### ISSUE THREAD

**Issue by rdstonech** [pmmp/PocketMine-MP#1496]
### Issue description
P.s I write this here because PreProcessor don't have issues
After using PreProcessor i can't join to server

### Steps to reproduce the issue

1. Use PreProcessor
2. Join to server

### OS and versions

* PocketMine-MP: https://github.com/pmmp/PocketMine-MP/commit/716c1f29b4dd65cdb60348bad932d11de3267a5e
* PHP: 7.2.0RC4
* Server OS: Ubuntu 17.10 x64
* Game version: PE (not tested with win10)

### Plugins
- Tested on clean server

### Crashdump, backtrace or other files
![2017-10-24 17-36-33](https://user-images.githubusercontent.com/31804440/31949559-4f102f74-b8e2-11e7-8c55-ddd28ede9852.png)

**Comment by dktapps** [comment]
are you using the `master` branch or `mcpe-1.2` branch of PreProcessor?

**Comment by rdstonech** [comment]
@dktapps Whoops, i used PreProcessor from master branch. I now used PreProcessor mcpe-1.2 and all works fine. Thanks
