### ISSUE TITLE
Detected spam

### ISSUE THREAD

**Issue by alexbgameson** [pmmp/PocketMine-MP#1502]
@dktapps I would like to pay you to update legacy plugins to API 3.0.0Alpha9.

Interested?

**Comment by DaPigGuy** [comment]
This is not the right place.

**Comment by TheDeibo** [comment]
Wow... you made me come off my `Unread Notifications` for this? I now have 1318. Working upto 1337 then stopping. 
Spam issues are not helping me, and even worse, not helping PMMP.

Besides, I can bet my left shoe that dktapps is not interested. 
Go and bother someone else with your stupid request.
