### ISSUE TITLE
potions no work

### ISSUE THREAD

**Issue by Megalunchbox** [pmmp/PocketMine-MP#1503]
### Issue description
they dont work

splash potions dont even pop up

### Steps to reproduce the issue

1. try to use a potion

### OS and versions

all os

PocketMine-MP 1.7dev-83 「[REDACTED]」 implementing API version 3.0.0-ALPHA8 for Minecraft: PE v1.2.0.81 (protocol version 137)

**Comment by Megalunchbox** [comment]
posted this before i tested alpha 9 on accident

**Comment by mal0ne-23** [comment]
Potions and Splash Potions are not implemented into PocketMine yet. This isn't a bug, it just hasn't gotten done _yet_

**Comment by Megalunchbox** [comment]
how come it has to be implemented again?

**Comment by dktapps** [comment]
did you read the issue template?

> Any issues requesting updates to new versions of MCPE will be treated as spam.
> Please do not create issues for missing/un-implemented gameplay features - they will be closed.
