### ISSUE TITLE
Error when try to run on Windows 10

### ISSUE THREAD

**Issue by LewBr** [pmmp/PocketMine-MP#1504]
### Issue description

- Expected result: To start the server.
- Actual result: Error 0xc000007b

### Steps to reproduce the issue

1. I have an error whit the current PMMP binaries when i try to run start.cmd on my Windows 10 i receive that error message: 0xc000007b
2. ...

### OS and versions

* PocketMine-MP: current
* PHP: ci.appveyor.com/project/pmmp/php-build-scripts
* Server OS: Windows 10
* Game version: PE/Win10

### Crashdump, backtrace or other files
- Do not paste crashdumps into an issue - please use our Crash Archive at https://crash.pmmp.io for submitting crash reports to not spam the issue tracker. Add links to your reports in the Crash Archive here.
- Please use gist or anything else to add other files and add links here 

* 
![image](https://user-images.githubusercontent.com/17750435/32030442-b6ad2b1c-b9d9-11e7-8518-2c5c60fbfd62.png)

**Comment by IrishPacks** [comment]
https://www.techcrises.com/how-to/how-to-fix-error-code-0xc000007b-in-windows-7-8-8-1/

**Comment by dktapps** [comment]
setup issue, this isn't a support forum.
