### ISSUE TITLE
Installation

### ISSUE THREAD

**Issue by QuiverlyRivalry** [pmmp/PocketMine-MP#1507]
Not sure if it belongs here but on my panel i get this error.
"Allocating server
Server allocated
Ready to be installed
Installing server
Downloading file https://raw.githubusercontent.com/pmmp/php-build-scripts/master/installer.sh
Executing: chmod +x ./installer.sh
Executing: ./installer.sh
[*] Retrieving latest build data for channel "alpha"
[!] Couldn't download version information automatically from Jenkins server."
And freezes there

**Comment by dktapps** [comment]
this is not a support forum, use the forums.

**Comment by QuiverlyRivalry** [comment]
forums is down though

**Comment by QuiverlyRivalry** [comment]
hello?

**Comment by QuiverlyRivalry** [comment]
@dktapps

**Comment by Thunder33345** [comment]
Like he said before, this is NOT a help forum
nor is intended to be one when it's offline

**Comment by QuiverlyRivalry** [comment]
oh okie
