### ISSUE TITLE
"Outdated Server!"

### ISSUE THREAD

**Issue by MDMCK10** [pmmp/PocketMine-MP#1512]
### Issue description

Today i decided to make a MCPE server, so i used this, but even with the latest phar, i kept getting protocol errors, and "Outdated Server!"

- Expected result: What were you expecting to happen?
for it to work and be able to log on
- Actual result: What actually happened?
"outdated server!"
### Steps to reproduce the issue

1. ... update mcpe to latest
2. ... connect to server

### OS and versions

* PocketMine-MP: https://github.com/pmmp/PocketMine-MP/commit/4a78bfaa18a08b58ae836b86b2500879843f064f
* PHP: 7.0
* Server OS: linux(ubuntu)
* Game version: PE latest

### Plugins
- Test on a clean server without plugins: is the issue reproducible without any plugins loaded?
yes
If the issue is **not** reproducible without plugins:
- Have you asked for help on our forums before creating an issue?
- Can you provide sample, *minimal* reproducing code for the issue? If so, paste it in the bottom section
- Paste your list of plugins here (use the 'plugins' command in PocketMine-MP)
none
### Crashdump, backtrace or other files
- Do not paste crashdumps into an issue - please use our Crash Archive at https://crash.pmmp.io for submitting crash reports to not spam the issue tracker. Add links to your reports in the Crash Archive here.
- Please use gist or anything else to add other files and add links here 

* ...

**Comment by dktapps** [comment]
beta 1.2.5 isn't supported yet.
