### ISSUE TITLE
double chests

### ISSUE THREAD

**Issue by TDMidkwhatisxd** [pmmp/PocketMine-MP#1514]
### Issue description

If u put a chest near another chest it wont change to double chest.
Cant make double chests

- Expected result: What were you expecting to happen?
To make double chest
- Actual result: What actually happened?
There are 2 small chests .
### Steps to reproduce the issue

1. ... Give yourself 2 chests
2. ... Try to make a double chest

### OS and versions

* PocketMine-MP:https://github.com/pmmp/PocketMine-MP/commit/4a78bfaa18a08b58ae836b86b2500879843f064f
* PHP:
* Server OS: Centos 7
* Game version: PE/Win10 (delete as appropriate)

### Plugins
- Test on a clean server without plugins: is the issue reproducible without any plugins loaded?

If the issue is **not** reproducible without plugins:
- Have you asked for help on our forums before creating an issue?
- Can you provide sample, *minimal* reproducing code for the issue? If so, paste it in the bottom section
- Paste your list of plugins here (use the 'plugins' command in PocketMine-MP)

### Crashdump, backtrace or other files
- Do not paste crashdumps into an issue - please use our Crash Archive at https://crash.pmmp.io for submitting crash reports to not spam the issue tracker. Add links to your reports in the Crash Archive here.
- Please use gist or anything else to add other files and add links here 

* ...

**Comment by TDMidkwhatisxd** [comment]
Another info, if I press the chest from left both chests open. But same slots, ill do more tests.

**Comment by Muqsit** [comment]
Are you... sure about this?

**Comment by TDMidkwhatisxd** [comment]
https://youtu.be/7h_iERqOyCQ

**Comment by dktapps** [comment]
possibly related to #1449

**Comment by TDMidkwhatisxd** [comment]
why unconfirmed ^^. Video say it all.

**Comment by TDMidkwhatisxd** [comment]
And double chest didn't work.

**Comment by dktapps** [comment]
It's labelled "unconfirmed" until somebody else, other than the reporter, reproduces the bug, or until somebody finds the cause. I'll investigate this later. Thanks.

**Comment by TDMidkwhatisxd** [comment]
Okay. I tested it on a clean server. Its not main server. I copy, bin, phar and start.sh in a new directory.

**Comment by optimusprime338** [comment]
I have same issue in latest version!

**Comment by dktapps** [comment]
Fixed, thanks!
