### ISSUE TITLE
Unsafe excess use of Level->getBlock() flooding block caches

### ISSUE THREAD

**Issue by dktapps** [pmmp/PocketMine-MP#152]
### Issue description
If something spams Level->getBlock(), the block cache will fill up very rapidly. Since it is only cleared every 5 seconds or so, if something nukes it inside those 5 seconds the server memory will fill up very rapidly and crash of an Out Of Memory Error.

Issues such as iTXTech/Genisys#1788 result from the lack of proper cache size limiting. This is not the root cause of such issues (no doubt plugins misusing getBlock()) but a limitation should be imposed on the allowed size of the caches to prevent this happening.

### Steps to reproduce the issue

1. Spam getBlock(), maybe with a world edit plugin or something
2. Watch the server crash

Easiest to do if you reduce the memory limit.

### Proposed actions
Make the chunk- and block-caches have a fixed size and throw exceptions should the size attempt to exceed these limits.

### OS and versions

* PocketMine-MP: https://github.com/pmmp/PocketMine-MP/commit/5d16ecc0034ed2262ec2f95ccc0e7bbca17f24d5 , but irrespective of version this happens
* PHP: 7.0.13
* Server OS: irrelevant
* Game version: PE/Win10 (delete as appropriate)

### Crashdump, backtrace or other files

iTXTech/Genisys#1788, iTXTech/Genisys#1302

**Comment by Sandertv** [comment]
I'm working on a worldediting plugin, and I'm trying to implement an undo command. What amount of using Level->getBlock() do you think will be maximum? If it is quite small, are there any alternatives for this?

**Comment by dktapps** [comment]
Shit, it seems this can happen with a vanilla installation... :O

**Comment by dktapps** [comment]
Related to #231

**Comment by dktapps** [comment]
```
Fatal error: Allowed memory size of 1073741824 bytes exhausted (tried to allocate 67108864 bytes) in C:\Users\User\Downloads\server\src\pocketmine\level\Level.php on line 1266

Call Stack:
    0.0039     360136   1. {main}() C:\Users\User\Downloads\server\src\pocketmine\PocketMine.php:0
    0.3766     549968   2. pocketmine\Server->__construct() C:\Users\User\Downloads\server\src\pocketmine\PocketMine.php:492
   10.1355   17456544   3. pocketmine\Server->start() C:\Users\User\Downloads\server\src\pocketmine\Server.php:1599
   10.3412   17574192   4. pocketmine\Server->tickProcessor() C:\Users\User\Downloads\server\src\pocketmine\Server.php:1978
  409.2690  828283312   5. pocketmine\Server->tick() C:\Users\User\Downloads\server\src\pocketmine\Server.php:2096
  413.4610  828373504   6. pocketmine\Server->checkTickUpdates() C:\Users\User\Downloads\server\src\pocketmine\Server.php:2336
  413.4610  828373504   7. pocketmine\level\Level->doTick() C:\Users\User\Downloads\server\src\pocketmine\Server.php:2182
  415.0858  819739384   8. pocketmine\Player->onUpdate() C:\Users\User\Downloads\server\src\pocketmine\level\Level.php:667
  415.0862  819739384   9. pocketmine\Player->processMovement() C:\Users\User\Downloads\server\src\pocketmine\Player.php:1588
  415.0862  819739384  10. pocketmine\entity\Entity->move() C:\Users\User\Downloads\server\src\pocketmine\Player.php:1432
  415.0862  819739704  11. pocketmine\level\Level->getCollisionCubes() C:\Users\User\Downloads\server\src\pocketmine\entity\Entity.php:1300
  707.3564 1034154872  12. pocketmine\level\Level->getBlock() C:\Users\User\Downloads\server\src\pocketmine\level\Level.php:1133

[18:25:58] [Server thread/EMERGENCY]: An unrecoverable error has occurred and the server has crashed. Creating a crash dump
[18:25:58] [Server thread/EMERGENCY]: Please upload the "C:\Users\User\Downloads\server\crashdumps/Wed_Jan_25-18.25.58-UTC_2017.log" file to the Crash Archive and submit the link to the Bug Reporting page. Give as much info as you can.
```
This only seems to occur when movement-checks are disabled. 🤔

**Comment by dktapps** [comment]
So, if I teleport from 100 70 100 to 1000 70 1000, my bounding box _somehow_ becomes 900x2x900 blocks...

**Comment by dktapps** [comment]
Fixed the mentioned issue (#231) but the issue outlined in this issue is still important.

**Comment by dktapps** [comment]
Lots of random block updates of grass frequently cause cache overflows. Randomly-ticked blocks should not be caching neighbour results. 🤦‍♂️

**Comment by TheBlackPlague** [comment]
Maybe add a maximum calling limit in a period with cache on.

**Comment by Auerd** [comment]
Yo, there's no level directory and so there is no Level.php file. I think that issue is little bit outdated

**Comment by dktapps** [comment]
The issue still exists, although the affected code is in a different place now.
