### ISSUE TITLE
Lava generates Cobblestone too Slow!

### ISSUE THREAD

**Issue by FunnyBuddys** [pmmp/PocketMine-MP#1520]
### Steps to reproduce the issue

https://youtu.be/jUPlxU88hNs

### OS and versions

Last Commit / https://github.com/pmmp/PocketMine-MP/commit/4437b67178c70ce169d0cf8ddf7815fc22f60a24

**Comment by dktapps** [comment]
Without knowing your PocketMine-MP version, OS, PHP, Client version, or plugins and how the issue occurred, the issue cannot begin to be solved.
A pre-formatted template is provided that shows the required information to begin to find, test and solve an issue.
Until the adequate template and information is provided, the issue will be closed; it may be reopened if you update the ticket with the correct template and required information.

[Contribution guidelines](https://github.com/pmmp/PocketMine-MP/blob/master/CONTRIBUTING.md)
Related issue: #133
