### ISSUE TITLE
Server does not fire event when broadcasting packets

### ISSUE THREAD

**Issue by CodexLandAdmin** [pmmp/PocketMine-MP#1521]
### Issue description
Server::batchPackets and therefore Server::broadcastPacket etc do not fire corresponding event «DataPacketSendEvent». I've dealed with this while catching core's settime packets sending to players by Level. I think, it should be better API.

**Comment by dktapps** [comment]
Batching & broadcasting in general is very messy right now. This is one problem I did notice. It will be dealt with in due course.

**Comment by dktapps** [comment]
This will be resolved in my upcoming network rewrite.
