### ISSUE TITLE
Beds drop in creative if the bottom half is broken

### ISSUE THREAD

**Issue by Frago9876543210** [pmmp/PocketMine-MP#1525]
### Issue description
The bed drop if you break it in the creative

### Steps to reproduce the issue

1. go to the creative
2. place bed
3. break it

### OS and versions

* PocketMine-MP: https://github.com/pmmp/PocketMine-MP/commit/733e61f8150287595ee567770b19b5a7897c4331
* PHP: 7.2 RC5
* Server OS: Linux
* Game version: Win10

**Comment by dktapps** [comment]
this bug again...

**Comment by jasonwynn10** [comment]
must be bottom section of the bed which is broken
