### ISSUE TITLE
Invisible custom tiles

### ISSUE THREAD

**Issue by Frago9876543210** [pmmp/PocketMine-MP#1528]
### Issue description
![im](https://snag.gy/o8vRQd.jpg)

### Steps to reproduce the issue
1. download this https://github.com/CortexPE/TeaSpoon
2. ```/give <player> 130```
3. place ender chest
4. quit the game
5. join again

### OS and versions
* PocketMine-MP: https://github.com/pmmp/PocketMine-MP/commit/733e61f8150287595ee567770b19b5a7897c4331
* PHP: 7.2.0 RC5
* Server OS: Win10
* Game version: Win10

**Comment by dktapps** [comment]
take it up with the plugin author.

**Comment by Frago9876543210** [comment]
@dktapps that core bug

**Comment by dktapps** [comment]
> A Massive PocketMine-MP plugin designed and is aiming to extend PMMP's functionalities

> - Test on a clean server without plugins: is the issue reproducible without any plugins loaded?
>
> If the issue is **not** reproducible without plugins:
> - Have you asked for help on our forums before creating an issue?
>
> - **Can you provide sample, *minimal* reproducing code for the issue? If so, paste it in the bottom section**

Thank you for reading the guidelines.

**Comment by ivan691** [comment]
решил?

**Comment by Frago9876543210** [comment]
@ivan691 no
