### ISSUE TITLE
help i get some kind of error using the newest phar

### ISSUE THREAD

**Issue by mlo40** [pmmp/PocketMine-MP#1529]
when i start my server running phar 1.7 dev 3.0.0 alpha 9 it gives me this error and i can't find php 7.2.0rc3 any ways to fix it and i am running windows 10

[CRITICAL] PocketMine-MP requires PHP >= 7.2.0RC3, but you have PHP 7.2.0RC1.
[CRITICAL] Please use the installer provided on the homepage, or update to a newer PHP version.

thank u for reding this

**Comment by HimbeersaftLP** [comment]
@mlo40 You need to download the new php binary: https://ci.appveyor.com/api/buildjobs/45h78e5l5wx1wu37/artifacts/php-7.2.0RC5-vc15-x64.zip
