### ISSUE TITLE
Signed books ending with blank pages lose the last page

### ISSUE THREAD

**Issue by jasonwynn10** [pmmp/PocketMine-MP#1532]
### Issue description

If a book has 6 pages generated with no text on the last two, when the book is signed, the last page is removed. This is not vanilla behavior

- Expected result: The signed book will have an even number of pages
- Actual result: The signed book has an odd number of pages; one page less than was created with.
### Steps to reproduce the issue

1. Generate 6 pages in a book
2. Write on the first 4. Do not write on 5 or 6
3. Sign the book
4. Open the signed book, and look at the page count.

### OS and versions

* PocketMine-MP: This server is running PocketMine-MP 1.7dev-383 「[REDACTED]」 implementing API version 3.0.0-ALPHA9 for Minecraft: PE v1.2.0.81 (protocol version 137)
* PHP: 7.2.0RC4
* Server OS: Windows 10
* Game version: PE & Win10

### Plugins
- [x] Test on a clean server without plugins: is the issue reproducible without any plugins loaded?

If the issue is **not** reproducible without plugins:
- Have you asked for help on our forums before creating an issue?
- Can you provide sample, *minimal* reproducing code for the issue? If so, paste it in the bottom section
- Paste your list of plugins here (use the 'plugins' command in PocketMine-MP)

### Crashdump, backtrace or other files
- Do not paste crashdumps into an issue - please use our Crash Archive at https://crash.pmmp.io for submitting crash reports to not spam the issue tracker. Add links to your reports in the Crash Archive here.
- Please use gist or anything else to add other files and add links here 

* ...

**Comment by dktapps** [comment]
@Sandertv any comments to add on this?

**Comment by dktapps** [comment]
I can't reproduce this issue.

Steps taken:
1. Get a book
2. Write `this`, `is`, `a`, `test` on pages 1-4.
3. Click the forward arrow to generate blank 5 and 6.
4. Sign the book
5. Open the signed book and 5 and 6 are present and correct.

Is this issue still valid?

**Comment by jasonwynn10** [comment]
It appears to be fixed for me too
