### ISSUE TITLE
Higher memory consumtion for PM core

### ISSUE THREAD

**Issue by Neerdex** [pmmp/PocketMine-MP#1535]
How to allow higher memory consumtion for pocketmine server?
My server PC have 32gb RAM.
Php.exe process using only 200-300mb RAM and Pocketmine server console shows low TPS and 100% LOAD. And of course i have lags on my server. So how to increase memory consumption (like example 10-16gb) and can it helps with my PM server perfomance?

**Comment by dktapps** [comment]
This is not a support forum. Please ask for help on https://forums.pmmp.io
