### ISSUE TITLE
Saved player logs in a block too low

### ISSUE THREAD

**Issue by dschwartz783** [pmmp/PocketMine-MP#1539]
### Issue description

Players whose data have been saved, log in a block lower than they left, resulting in players sometimes falling down beneath floors and whatnot (if the floor is only one block high).

- Expected result: Players log in exactly where they were when the data was saved
- Actual result: Players log in a block lower than they should.

### Steps to reproduce the issue

1. Enable player data saving
2. Log in
3. Note that you're not in the floor
4. Log out
5. Log in
6. Notice that you're now in the floor

### OS and versions
* PocketMine-MP: PocketMine-MP 1.7dev 「[REDACTED]」 implementing API version 3.0.0-ALPHA9 for Minecraft: PE v1.2.0.81 (protocol version 137)
* PHP: 7.2
* Server OS: Ubuntu 16.04.3 LTS (also happens on macOS 10.13.1)
* Game version: PE

### Plugins
This occurs both with and without plugins (completely clean PocketMine-MP, straight out of the repo + composer stuff), therefore this is irrelevant

### Crashdump, backtrace or other files

Here's my save file, but I doubt this is needed. I literally JUST installed this server instance to test.
https://www.dropbox.com/s/yoe3xdg1cfa9xna/stevebobjim.dat?dl=1
* ...

**Comment by dktapps** [comment]
Yes, this has been an issue since ~1.2ish. The position server-side is actually correct, but the client does some black magic on certain platforms which result in it being a tiny bit lower than that. The client then tries to move into the block (hence the spam of "moved wrongly!" when a player spawns).

For example, I have 4 devices with MCPE on them: an LG G5, an LG G Flex 2, my PC running W10, and a Sony Xperia Z2. This bug ONLY occurs on my Z2, and occurs consistently on that one device.

I haven't decided on an effective solution or hack for this yet.

**Comment by HipsterAF** [comment]
Someone's rich :O

**Comment by dschwartz783** [comment]
Must have something to do with floating point rounding errors... That can differ slightly from platform to platform, depending on how things are compiled.

**Comment by dktapps** [comment]
If it wasn't for the fact they compile for generic armv7 architecture I'd probably jump on the fact that the only one of the bunch there that's 32-bit is the Z2 - so maybe machine-dependent size floats. But... all things MCPE are 32-bit, so no real explanation.

**Comment by dschwartz783** [comment]
It's interesting that this occurs on my iPhone 7 then, which is 64-bit. I suppose the question is what do the Z2 and the iPhone 7 have in common, if anything. Can't be too much.

**Comment by dschwartz783** [comment]
Seems that's not entirely accurate, however:
Result of lipo -info on the iOS Minecraft binary:
Architectures in the fat file: /Users/funtimes/Minecraft 1.2.3/Payload/minecraftpe.app/minecraftpe are: armv7 arm64

**Comment by jojoe77777** [comment]
> A decent hack for now would probably be to add 0.01 to the player's position when restoring for a save.

@dschwartz783 it happens for every teleport, not just joining

**Comment by dschwartz783** [comment]
@jojoe77777 Then do that for every teleport. It shouldn't be enough to screw anything up on correctly-operating clients, but it should be enough to keep people from falling through the floor

**Comment by dktapps** [comment]
I've pushed a hack-fix which resolves the problem on my Z2, but this obviously still needs investigating and debugging properly.

**Comment by SashaManori** [comment]
issue has no longer occurring for mcpe
