### ISSUE TITLE
v1.2.3  can't connect

### ISSUE THREAD

**Issue by 911061873** [pmmp/PocketMine-MP#1541]
I'm running PocketMine-MP 1.7dev-383,Game version is 1.2.3.And it can't connect now.
Is it because the software only supports 1.2.0.81?
When will it be updated?
Thanks!

**Comment by 911061873** [comment]
So,Why couldn't it be connected?

**Comment by Muqsit** [comment]
because your issue vaguely written

**Comment by 911061873** [comment]
OO sorry

**Comment by 911061873** [comment]
Can’t connect to localhost Win10 server with Minecraft Win10 Edition
Launch Window PowerShell as an administrator and run the following:

`CheckNetIsolation LoopbackExempt -a -n="Microsoft.MinecraftUWP_8wekyb3d8bbwe"`
[http://pmmp.readthedocs.io/en/rtfd/faq/connecting/win10localhostcantconnect.html](http://pmmp.readthedocs.io/en/rtfd/faq/connecting/win10localhostcantconnect.html)
