### ISSUE TITLE
Game mode is not saved after changes in PlayerQuitEvent

### ISSUE THREAD

**Issue by zKoz210** [pmmp/PocketMine-MP#1543]
### Issue description

Game mode is not saved after changes in PlayerQuitEvent. **Looks like when execute PlayerQuitEvent ANY action with the player not working as setHealth() and so on...**

### Steps to reproduce the issue

1. Write a small plugin
```
    public function onPlayerQuitEvent(PlayerQuitEvent $event)
    {
        $player = $event->getPlayer();
        $change = $player->setGamemode(0);
        $this->getLogger()->notice($change);
    }
```
2. Join to server and set gamemode 3 (/gamemode 3)
3. Re-join
4. Game mode has not changed, although `setGamemode()` returns `true`

### OS and versions

* PocketMine-MP: https://github.com/pmmp/PocketMine-MP/commit/aa399a1109d2213e5df84c5390deeda0746c2717
* PHP: 7.2
* Server OS: CentOS 7
* Game version: PE/Win10

**Comment by zKoz210** [comment]
https://github.com/pmmp/PocketMine-MP/blob/aa399a1109d2213e5df84c5390deeda0746c2717/src/pocketmine/Player.php#L3377 Save need make after PlayerQuitEvent

**Comment by dktapps** [comment]
#1482
