### ISSUE TITLE
Always day option in config

### ISSUE THREAD

**Issue by HipsterAF** [pmmp/PocketMine-MP#1545]
### Issue description

Can there be an always day option in pocketmine.yml or server.properties, because it's a minigame server and there is no need for skylight update tick...

### Steps to reproduce the issue

1. ...
2. ...

### OS and versions

* PocketMine-MP: aa399a1
* PHP: 7.2.0RC5
* Server OS: Linux
* Game version: PE (delete as appropriate)

### Crashdump, backtrace or other files

* ...

**Comment by JackNoordhuis** [comment]
Use a plugin. The goal of pocketmine is to create a vanilla-like server, not add options to configs for everyone's personal needs.

**Comment by HipsterAF** [comment]
How is it personal? it just makes it more user friendly

**Comment by Sandertv** [comment]
It should not be in the config.yml like Jack said, it should instead be a gamerule like it is in vanilla. Gamerules are not implemented yet however, and I'm sure that whoever implements them will take always day as one of the first gamerules.
