### ISSUE TITLE
Can't undo BlockUpdate

### ISSUE THREAD

**Issue by zKoz210** [pmmp/PocketMine-MP#1547]
### Issue description
I can not get the update type (BLOCK_UPDATE_NORMAL, BLOCK_UPDATE_RANDOM, etc)

I disabled the water on my server and would like to cancel the event specified in the example using the BLOCK_UPDATE_RANDOM type, but this does not work. So FARNLAND could farm without water.

### OS and versions
* PocketMine-MP: https://github.com/pmmp/PocketMine-MP/commit/769f3f75cd735710202465149a727dfae5d254f1
* PHP: 7.2
* Server OS: CentOS 7

### Crashdump, backtrace or other files
```
    public function onBlockUpdateEvent(BlockUpdateEvent $event) {
        $block = $event->getBlock();
        if ($block->getId() === Block::FARMLAND) {
            $event->setCancelled(true);
        }
    }
```

* ...

**Comment by dktapps** [comment]
BlockUpdateEvent is called on a block and its neighbours when a block is changed in the world. It is not intended for random block ticking.

It is unlikely there will ever be events for this, as it would significantly degrade performance.

**Comment by dktapps** [comment]
A more viable, less expensive way to do this would be to make use of [this API method](https://github.com/pmmp/PocketMine-MP/blob/master/src/pocketmine/level/Level.php#L912) or [this pocketmine.yml config option](https://github.com/pmmp/PocketMine-MP/blob/master/src/pocketmine/resources/pocketmine.yml#L140).

**Comment by zKoz210** [comment]
@dktapps 
```
 disable-block-ticking:
  #- 2 # grass
  - 60
```
This does not work. FARMLAND becomes DIRT.

**Comment by zKoz210** [comment]
@dktapps 
You need search KEY after delete element
```
if(!isset($dontTickBlocks[array_search($id, $dontTickBlocks)]) and $block->ticksRandomly()){
	$this->randomTickBlocks[$id] = $block;
}
```

**Comment by dktapps** [comment]
fixed, thanks.
