### ISSUE TITLE
Still liquids behave no differently than flowing liquids

### ISSUE THREAD

**Issue by Haxley** [pmmp/PocketMine-MP#1549]
### Issue description

**Still Water (ID:9) flows, and has no discernible difference from flowing water**

- Expected result: **Water to be still**
- Actual result: **Water flows**
### Steps to reproduce the issue

1. ... **Place Still Water block (ID:9)**
2. ... **Watch it flow**

### OS and versions

* PocketMine-MP: **1.2.0.81**
* PHP: **7**
* Server OS: **Linux**
* Game version: **Win10/PE**

### Plugins
- Test on a clean server without plugins: is the issue reproducible without any plugins loaded?
**Yes**

If the issue is **not** reproducible without plugins:
- Have you asked for help on our forums before creating an issue?
- Can you provide sample, *minimal* reproducing code for the issue? If so, paste it in the bottom section
- Paste your list of plugins here (use the 'plugins' command in PocketMine-MP)

### Crashdump, backtrace or other files
- Do not paste crashdumps into an issue - please use our Crash Archive at https://crash.pmmp.io for submitting crash reports to not spam the issue tracker. Add links to your reports in the Crash Archive here.
- Please use gist or anything else to add other files and add links here 

* ...

**Comment by jasonwynn10** [comment]
What is your testing logic? Are you updating the water block?

**Comment by dktapps** [comment]
Yes, this is a known issue (#133). Liquids are implemented completely wrongly.

**Comment by Haxley** [comment]
@dktapps Whoops! I searched "water" and didn't see it. Should have searched "flow". Thanks for working on it :]

**Comment by Haxley** [comment]
@dktapps Now that you've rewritten flow calculations, can we get still_water and still_lava again? Because still_water flows, it's been banned on most servers as a grief weapon. Players are unable to farm unless they build in a lake.

**Comment by dktapps** [comment]
it never worked in the first place. My flow handling rewrite was specifically targeted at making liquid flow work properly, not at fixing the behaviour of still liquids.

Personally I think still liquid blocks are stupid, they make the implementation more complicated than necessary. It would have been nice if Mojang could have implemented it as an extra state or something. As it stands, they don't serve any purpose in PM's liquid implementation.

This is not a high-priority issue sadly.

**Comment by Haxley** [comment]
Any update on this?

**Comment by dktapps** [comment]
I'm closing this as WF because still liquids are useless for the purpose of PM vanilla. My comment from Feb still stands. We don't have any use for them and I don't intend to waste my time on them.

Since this is an internal block, external usages of them are exposed to internals and the behaviour might change unexpectedly anyway, so I consider this unsupported behaviour.
