### ISSUE TITLE
Problems related to books

### ISSUE THREAD

**Issue by ezura573** [pmmp/PocketMine-MP#1550]
### Issue description

Even if you write the following code with your own plugin, the GUI of the signed book will be displayed.
	public function onInteract(PlayerInteractEvent $event){
		$event->setCancelled();
        }

- Expected result: What were you expecting to happen?
Since the event is being canceled, the GUI of the book should not be displayed
- Actual result: What actually happened?
Although the event is canceled, the book's GUI is displayed
### Steps to reproduce the issue

1. ...A plug-in containing the above code is prepared
2. ...Activate plug-in and start server
3. ...Login to server
4. ...Prepare a signed book
5. ...Hold the book in your hand and do the operation to open it

### OS and versions

* PocketMine-MP:1.7dev-383_aa399a11_API-3.0.0-ALPHA9.phar

### Plugins
- Test on a clean server without plugins: is the issue reproducible without any plugins loaded?

If the issue is **not** reproducible without plugins:
- Have you asked for help on our forums before creating an issue?
- Can you provide sample, *minimal* reproducing code for the issue? If so, paste it in the bottom section
- Paste your list of plugins here (use the 'plugins' command in PocketMine-MP)

### Crashdump, backtrace or other files
- Do not paste crashdumps into an issue - please use our Crash Archive at https://crash.pmmp.io for submitting crash reports to not spam the issue tracker. Add links to your reports in the Crash Archive here.
- Please use gist or anything else to add other files and add links here 

* ...

**Comment by dktapps** [comment]
This is impossible to control since the GUI opening is client-sided.

**Comment by ezura573** [comment]
I could do it using Bukkit Server with Minecraft Java Edition, but is it impossible in PE?

**Comment by Thunder33345** [comment]
I could do custom uis on pocketmine server with pocket eidson, but is it impossible on PC?
