### ISSUE TITLE
Illegal Player Movement bug

### ISSUE THREAD

**Issue by GDRGamingzz** [pmmp/PocketMine-MP#1553]
hello developers of pmmp and there is a bug on the anti cheat configuration on players which is...

- Expected result: it was suppose to turn off the anti movement cheat
- Actual result: the anti movement cheat is still turned on players cant move properly even on running into stairs. flying and etc.

* PocketMine-MP: latest
* PHP: 7.2
* Server OS: Ubuntu

- Test on a clean server without plugins: this bug is still there even without plugins

**Comment by jasonwynn10** [comment]
latest is not a valid version number

**Comment by jrodr10** [comment]
not with this software its not lol they update every other min with plugin breaking changes

**Comment by GDRGamingzz** [comment]
this version is what I'm using: https://github.com/pmmp/PocketMine-MP/commit/bda40edebe1c4481034aa5be2801d7a9f095b03b
