### ISSUE TITLE
Chest sound bugged!

### ISSUE THREAD

**Issue by JackMD** [pmmp/PocketMine-MP#1554]
### Issue description

When opening chest you don't hear the opening chest sound. It is played when the chest closes. But the closing chest sound never gets played.

- **Expected result:** Upon opening of chest the opening chest sound should be played and when the chest is closed the closing sound should be played.
- **Actual result:** When the chest is opened no sound is played and when it is closed the opening sound gets played. But the closing chest sound is never played.

### Steps to reproduce the issue

1. Put a chest on the ground,
2. Open it to go to chest inventory. No sound is played.
3. Now get out of chest inventory i.e. simply close the chest and you will hear the opening chest sound.
4. The closing chest sound is not heard at any instant.

### OS and versions

* PocketMine-MP: v1.7dev (v1.2.0.81)
* Protocol: 137
* PHP: 7.2.0RC5
* Server OS: Windows x64bit
* Game version: PE

### Plugins
- Tested on a clean server with no plugins installed.

### Crashdump, backtrace or other files
- No crashdumps.

**Comment by dktapps** [comment]
what version of the client are you using? 1.2.5.0 had this bug.

**Comment by JackMD** [comment]
MCPE v1.2.0.81. Also PocketMine-MP would not let me connect to the server due to protocol difference of v1.2.5.0.

**Comment by dktapps** [comment]
1.2.5.0 didn't have a bump, that's the point.
