### ISSUE TITLE
Add API to access ResourcePack's files

### ISSUE THREAD

**Issue by thebigsmileXD** [pmmp/PocketMine-MP#1559]
### Issue description

Because the ZipArchive is closed inside the constructor, there is no way except messing with `$resourcePack->getPackChunk(0, $resourcePack->getPackSize())` to get the contents of the packs (except creating a new ZipArchive though, which is ~~near impossible~~ pure mess because even the path is not accessible in any proper way).

EDIT:
getters for `$path` and `$fileResource` would actually be enough
```
	/**
	 * @return string
	 */
	public function getPath(): string{
		return $this->path;
	}

	/**
	 * @return resource
	 */
	public function getFileResource(): resource{
		return $this->fileResource;
	}
```

- Expected result: What were you expecting to happen?
Having a way to get the files and read their contents without having to re-initialize them OR atleast getting the path of the files/packs
- Actual result: What actually happened?
a neat `protected` before everything

### Steps to reproduce the issue

1. Trying to get contents of addons/resource packs for plugins
2. Realize: Oops, only a protected fopen stream exists

### OS and versions

* PocketMine-MP: d2416d335e21f4831af6a26a4d91ba9d7b811ff5
* PHP: 7.2 RC4
* Server OS: Windows

### Plugins
- Test on a clean server without plugins: is the issue reproducible without any plugins loaded?
Yes, if you love to modify the SRC code (btw: `reproducible` instead of `reproducable`?)

If the issue is **not** reproducible without plugins:
- Have you asked for help on our forums before creating an issue?
- Can you provide sample, *minimal* reproducing code for the issue? If so, paste it in the bottom section
- Paste your list of plugins here (use the 'plugins' command in PocketMine-MP)

### Crashdump, backtrace or other files
- Do not paste crashdumps into an issue - please use our Crash Archive at https://crash.pmmp.io for submitting crash reports to not spam the issue tracker. Add links to your reports in the Crash Archive here.
- Please use gist or anything else to add other files and add links here 

* ...
By the way: why don't you use `stream_get_contents` in `getPackChunk()` - as it would handle the positions etc?

**Comment by thebigsmileXD** [comment]
These changes still only give the path, but no way to directly access the ZipArchive instead of creating a new one via the path. Better than nothing though, thx.

**Comment by dktapps** [comment]
the zip archive is not retained anyway. It's only used in the constructor to validate the manifest.json.

**Comment by thebigsmileXD** [comment]
But why not? If the ZipArchive would be cached instead, plugins could also validate if files exist in the zip and load it. (or is it a caching issue, that the files would be "locked" in the meanwhile?)
