### ISSUE TITLE
Wrong length of the nickname

### ISSUE THREAD

**Issue by zKoz210** [pmmp/PocketMine-MP#1568]
### Issue description
Wrong the length of the nickname

- Expected result: What were you expecting to happen?
```$len >= 2 and $len <= 15```
- Actual result: What actually happened?
```$len >= 1 and $len <= 16```

https://github.com/pmmp/PocketMine-MP/blob/master/src/pocketmine/Player.php#L185

Max length:

![image](https://user-images.githubusercontent.com/28255085/33221602-d3c97fda-d161-11e7-8171-a8a2cbfefc69.png)

Regex xbox tag:

![image](https://user-images.githubusercontent.com/28255085/33221636-0dbc019a-d162-11e7-879f-421ff98bd753.png)

Link: [js validator ](https://assets.xbox.com/xbcservicewebaccount-1711-13131-0-0-main-rolling/minified/account/js/changegamertag.min.js)

**Comment by dktapps** [comment]
We're not solely bounded by Xbox names, otherwise underscores wouldn't be permitted.
