### ISSUE TITLE
Health regeneration still appears to occur when cancelled by plugins

### ISSUE THREAD

**Issue by AppleDevelops** [pmmp/PocketMine-MP#157]
### Issue description

I'm pretty sure its AnimatePacket.
When a server has regen cancelled via plugins, the health appears to go up after taking damage when it shouldn't. 
### Steps to reproduce the issue

1. Cancel regen via plugin
2. Take damage
3. Watch hearts go up
4. Relog
5. Hearts are back to their original state, but still goes up.

### OS and versions

* PocketMine-MP: 5d16ecc0034ed2262ec2f95ccc0e7bbca17f24d5
* PHP: 7.0.13
* Server OS: Windows 10/Ubuntu
* Game version: PE/Win10 (delete as appropriate)

### Crashdump, backtrace or other files

* ...

**Comment by dktapps** [comment]
I'm going to close this and combine it with #23 to keep the issue tracker clear.
