### ISSUE TITLE
Sounds broken since 0.16

### ISSUE THREAD

**Issue by dktapps** [pmmp/PocketMine-MP#158]
### Issue description
Title says it all... lots of other sounds missing too. 😢 
### Steps to reproduce the issue

1. place TNT
2. turn your volume up, light it, notice it doesn't flash, no particles on explosion either

### OS and versions

* PocketMine-MP: https://github.com/pmmp/PocketMine-MP/commit/ae6e0773ef77e531d763c02900a29af32702b8ae
* PHP: 7.0.13 x64
* Server OS: Win10 Pro x64
* Game version: PE/Win10

**Comment by Driesboy** [comment]
https://github.com/pmmp/PocketMine-MP/commit/5e6d4526783041fbbcbf6e445d5bbeae93577b18

**Comment by dktapps** [comment]
Sound issues will be fixed for the 1.6.2 release.

**Comment by Goodstuff4UonYT** [comment]
When will it be done?

**Comment by archie426** [comment]
@Goodstuff4UonYT Don't ask for ETAs (Well, @dktapps says that)

**Comment by dktapps** [comment]
TNT issues have been resolved for MCPE 1.1, as have the block placing sound being missing.
