### ISSUE TITLE
Give Command - invalid

### ISSUE THREAD

**Issue by jasonwynn10** [pmmp/PocketMine-MP#159]
### Issue description

The give command is not able to include spaces in the NBT data
### Steps to reproduce the issue

1. type `give <username> diamond 2 {display:{Name:"Vote Diamond"}}` in the console
2. Make sure to include a space in the item name label
3. read error output

### OS and versions

* PocketMine-MP: 763ef7f
* PHP: 7.0.13
* Server OS: Windows 10
* Game version: PE

### Crashdump, backtrace or other files

* None

**Comment by TheDeibo** [comment]
Did you add the amount of diamonds you wanted? Looking at your issue you didn't... So, this below is a corrected version.
`give TheDeibo diamond 1 {display:{Name:"Vote Diamond"}}`
