### ISSUE TITLE
require_once error on startup

### ISSUE THREAD

**Issue by DarkWav** [pmmp/PocketMine-MP#16]
### Issue description

Write a short description about the issue

a Fatal error on startup

### Steps to reproduce the issue

1. ... download the github master.
2. ... extract the github master.
3. ... add the bin folder (into the master)
4. ... run start.cmd.

### OS and versions

* PocketMine-MP: latest github version (commit de28ddabdba885878b07302416e69d73caa7a345)
* PHP: 7.0.9
* OS: Windows 10 Pro

### Crashdump, backtrace or other files

* ... Warning: require_once(C:\Users\Plasma\Desktop\pmmp\src/spl/ClassLoader.php): failed to o07
Fatal error: require_once(): Failed opening required 'C:\Users\Plasma\Desktop\pmmp\src/s line 107
bin\php\php.exe: Exit 255

**Comment by dktapps** [comment]
Use git to clone, or download the submodules as well.

**Comment by DarkWav** [comment]
ok thanks.
