### ISSUE TITLE
PHP Update to 7.1.0

### ISSUE THREAD

**Issue by jasonwynn10** [pmmp/PocketMine-MP#162]
### Issue description

This is just a recommendation to update the the latest php 7.1.0 build that came out on Dec 1

### Steps to reproduce the issue

none

### OS and versions

* PocketMine-MP: 763ef7f
* PHP: 7.0.13 ->7.1.0
* Server OS: Windows 10
* Game version: PE

### Crashdump, backtrace or other files

http://php.net/archive/2016.php#id2016-12-01-3

**Comment by ishitatsuyuki** [comment]
# DANGER ZONE
:stuck_out_tongue: calm down, just joking.

The fact: pthreads doesn't have a proper release for 7.1, and the git version cause a crash in PocketMine so far.
Since both project has poor code quality (blame shoghicp and krakjoe), I'm not sure where the fault is.

**Comment by dktapps** [comment]
¯\_(ツ)_/¯ If you figure out how to compile pthreads with 7.1.0, do let us know. Otherwise, I'm going to close this, since we have attempted to do so already.

**Comment by Muqsit** [comment]
Looks like I'm not the only one who can't compile php7.1 with pthreads.
