### ISSUE TITLE
Creative Bucket Spamming

### ISSUE THREAD

**Issue by jasonwynn10** [pmmp/PocketMine-MP#165]
### Issue description

Creative inventory is filled when a player taps on water blocks with an empty bucket

### Steps to reproduce the issue

1. Set player to creative
2. Get empty bucket from creative inventory
3. Tap on water blocks repeatedly until the player throws out items
### OS and versions

* PocketMine-MP: 763ef7f
* PHP: 7.0.13
* Server OS: Windows 10
* Game version: PE

### Crashdump, backtrace or other files

none

**Comment by robske110** [comment]
Probably related to this https://github.com/pmmp/PocketMine-MP/blob/master/src/pocketmine/item/Bucket.php#L73

**Comment by dktapps** [comment]
This exact same issue occurs in vanilla 0.16.2 singleplayer. I'm going to close this, since it's either a client bug or intentional, I'm not sure which.

**Comment by jasonwynn10** [comment]
will it be fixed if it is decided to be a bug in vanilla?

**Comment by robske110** [comment]
You may want to report it to mojang.
