### ISSUE TITLE
Block bounding boxes and collision boxes

### ISSUE THREAD

**Issue by dktapps** [pmmp/PocketMine-MP#169]
### Issue description
According to PocketMine-MP, there are a large number of blocks which do not have any bounding box. This includes blocks such as tallgrass, water, signs, and many more.

This is plain wrong.

_All_ blocks have bounding boxes. The only exception to that rule is air, which is a null block. What those blocks don't have is _collision_ boxes, i.e. entities can walk through them.

This issue came to my eye while working on a basic pressure plate implementation. Pressure plates would have to be implemented by making them nonsolid but with an entity collision, like how water works. The issue with this is that because the server thinks these blocks have no bounding box, the intersection of an entity bounding box with that of, for example, a pressure plate, cannot be detected.

The best that can currently be done is to fire Block->onEntityCollide() when the entity enters the block's allocated full block area. That is _wrong_. It should be done when the entity's bounding box intersects with the pressure plate's, otherwise you would be able to trigger pressure plates by hovering above them.

### OS and versions

* PocketMine-MP: https://github.com/pmmp/PocketMine-MP/commit/5ce6c6227ff6ec512d89bf08cb163b3433ccb1ed
* PHP: 7.0.13
* Server OS: irrelevant
* Game version: PE/Win10

**Comment by dktapps** [comment]
TODO: implement complex bounding boxes for stairs and other blocks with non-cuboid shapes.

**Comment by dktapps** [comment]
Issues arising from this problem include lava setting you on fire when you're stood next to it and not in it.

**Comment by FunnyBuddys** [comment]
Can you not disable the Movement check temporarily?

**Comment by SalmonDE** [comment]
@FunnyBuddys you can do that yourself https://github.com/pmmp/PocketMine-MP/blob/master/src/pocketmine/resources/pocketmine.yml#L101

**Comment by kenygamer** [comment]
This issue is so stressing..and it's still not fixed.
