### ISSUE TITLE
Commands do not display description

### ISSUE THREAD

**Issue by Rover656** [pmmp/PocketMine-MP#175]
### Issue description

Commands don't display descriptions in the chat

### Steps to reproduce the issue

1. Enter in a command 
2. Don't press enter, look at the description. It says something like [args: string] 

### OS and versions

* PocketMine-MP: Any
* PHP: 7.0
* Server OS: Windows 10
* Game version: Win10

**Comment by dktapps** [comment]
This is a hack from 0.16 to avoid breaking old plugins. A new commands API will be implemented at a later date to allow this functionality to be used (no ETAs can be given).
