### ISSUE TITLE
Slow chat in windows 10

### ISSUE THREAD

**Issue by isoz** [pmmp/PocketMine-MP#1758]
What changed recently? it wasn't doing it before, when I type characters take some time to appear, making it really frustrating.

**Comment by dktapps** [comment]
Likely something to do with client-sided command parsing. Try commenting this https://github.com/pmmp/PocketMine-MP/blob/master/src/pocketmine/Player.php#L684

This was only recently implemented in PM recently (for the 1.2.5 update).

If that fixes your issue, then all I can say is blame the client.

**Comment by isoz** [comment]
I don't have that line on my source yet, so I guess blame the client.

**Comment by dktapps** [comment]
what client version are you using? (the issue template seems to be missing)

All PocketMine-MP versions supporting 1.2.5 have the command lists enabled. Check the `sendCommandData()` method if the line numbers don't match.

**Comment by isoz** [comment]
This server is running PocketMine-MP 1.7dev 「[REDACTED]」 implementing API version 3.0.0-ALPHA9 for Minecraft: PE v1.2.5.15 (protocol version 141)

```
public function sendCommandData(){
        //TODO: this needs fixing
        /*
        $data = [];
        foreach($this->server->getCommandMap()->getCommands() as $command){
            if(count($cmdData = $command->generateCustomCommandData($this)) > 0){
                $data[$command->getName()]["versions"][0] = $cmdData;
            }
        }

        if(count($data) > 0){
            //TODO: structure checking
            $pk = new AvailableCommandsPacket();
            $pk->commands = json_encode($data);
            $this->dataPacket($pk);
        }*/

    }
```

**Comment by dktapps** [comment]
so you're still running a beta version. In that case, I have no idea what could cause this, but I'm pretty sure this isn't a server-sided issue, so I'm going to close this.

**Comment by TheDeibo** [comment]
Just to add to this:
I believe it is the client. 

When it uses too much resources on my laptop, it slows down. A LOT. 
Restart the game and try again: it's all fine.

**Comment by optimusprime338** [comment]
It not an PMMP issue guys !! Happens every where.go to realm or survival world!! You have same issue with chat !! Fully client sided

**Comment by isoz** [comment]
Realized if I type slower it doesn't give the problem, extremely annoying, mojang get your shit together.

**Comment by TheDeibo** [comment]
If somebody checks JURA, and check if there is still a open issue. If there is, then use that. :)
