### ISSUE TITLE
Impossible to disable the revert movement

### ISSUE THREAD

**Issue by zKoz210** [pmmp/PocketMine-MP#1765]
### Issue description

PocketMine-MP config - `allow-movement-cheats: true`

Check the logic, if 1482 is true, then revert cannot be reversed in PlayerIllegalMoveEvent

https://github.com/pmmp/PocketMine-MP/blob/2cb81b5f8d851b5442fdca3bba0252e4dc66067e/src/pocketmine/Player.php#L1479-L1483

https://github.com/pmmp/PocketMine-MP/blob/2cb81b5f8d851b5442fdca3bba0252e4dc66067e/src/pocketmine/Player.php#L1498

Duble check `$revert`
https://github.com/pmmp/PocketMine-MP/blob/2cb81b5f8d851b5442fdca3bba0252e4dc66067e/src/pocketmine/Player.php#L1511

https://github.com/pmmp/PocketMine-MP/blob/2cb81b5f8d851b5442fdca3bba0252e4dc66067e/src/pocketmine/Player.php#L1498

### Dublicate
https://github.com/pmmp/PocketMine-MP/issues/1333

### OS and versions
* PocketMine-MP: https://github.com/pmmp/PocketMine-MP/commit/c3017888647a585b834b48dc61ad1a93ac136a8c
* PHP: 7.2
* Server OS: CentOS 7
* Game version: PE/Win10

**Comment by dktapps** [comment]
The distance check isn't anti-cheat, it's a safety check. Without it malicious players would be able to kill your server by sending stupid movements and confusing it into doing huge collision checks and loading lots of chunks.

**Comment by dktapps** [comment]
Sadly this distance check doesn't always work correctly due to various factors like server lag, client bad network, not sending positions every tick, and various other possibilities. That's already documented in another issue.

**Comment by zKoz210** [comment]
@dktapps God, that looks terrible, can we disable the ability to display messages? This flood in logs
![image](https://user-images.githubusercontent.com/28255085/34319927-ffcef3d6-e7fe-11e7-92b7-88c82f73be0d.png)
