### ISSUE TITLE
Invalid Session

### ISSUE THREAD

**Issue by iagomcs** [pmmp/PocketMine-MP#1776]
**Issue description**

Players can't join. Error: "Invalid session (Try restarting your game)".

Expected result: Players can join and play
Actual result: Players can't join. Errormessage: "Invalid session (try restarting your game)

**Steps to reproduce the issue**
Install server and run it
Try to join onto this server

**OS and versions**
PocketMine-MP: PocketMine-MP 1.7dev-473 "[REDACTED]" (API 3.0.0-ALPHA10)
PHP: 7.2.0RC3
Server OS: Linux
Game version: PE

**Plugins**
Error is there without plugins and with plugins

**Crashdump, backtrace or other files**
05.12 14:49:17 [Server] Server thread/INFO imcs95[/186.203.206.78:63784] logged out due to Invalid session

**Comment by dktapps** [comment]
Check closed issues before opening a new one. You can also seek support on our [forums](https://forums.pmmp.io).
