### ISSUE TITLE
Fire burns an incredibly long time

### ISSUE THREAD

**Issue by zKoz210** [pmmp/PocketMine-MP#1779]
### Issue description
- Expected result: Fire must be extinguished within 30-40 seconds
- Actual result: Fire is burning more than a few minutes

### Steps to reproduce the issue

1. join to server
2. Click flint and steel on any block

### OS and versions
* PocketMine-MP: https://github.com/pmmp/PocketMine-MP/commit/51cec525eeca1d57f525cbe75f7cb4d8a4bdff4f

**Comment by dktapps** [comment]
Fire updating and spread isn't implemented yet.

**Comment by zKoz210** [comment]
@dktapps It is implemented, but works bad https://github.com/pmmp/PocketMine-MP/blob/584810780a95002b3e98bac1f88022052f5e2e8a/src/pocketmine/block/Fire.php#L97-L109

**Comment by jasonwynn10** [comment]
That isn't fire spreading. What you see is the code which puts out a fire if it isn't on a sustainable block type
