### ISSUE TITLE
PHP error after installation

### ISSUE THREAD

**Issue by mstrop** [pmmp/PocketMine-MP#1783]
I have just installed the server on Centos 6. When I run ./start.sh, I get this error:

PHP Parse error:  syntax error, unexpected T_CLASS, expecting T_STRING or T_VARIABLE or '$' in phar:///home/minecraft/PocketMine-MP.phar/src/pocketmine/PocketMine.php on line 164

**Comment by dktapps** [comment]
This is not a support forum. Please seek assistance on the [forums](https://forums.pmmp.io).
