### ISSUE TITLE
Timings site

### ISSUE THREAD

**Issue by zKoz210** [pmmp/PocketMine-MP#1787]
### Issue description
Warning: Division by zero in /var/www/html/timings/legacy/index.php on line 544

### Crashdump, backtrace or other files
![image](https://user-images.githubusercontent.com/28255085/33779993-277b5afa-dc60-11e7-83db-86da844c56c5.png)

**Comment by jojoe77777** [comment]
https://github.com/pmmp/timings

**Comment by zKoz210** [comment]
@SOF3 Thank you that opened possibility to create an issue
