### ISSUE TITLE
Items will not be cleared from crafting menu

### ISSUE THREAD

**Issue by zKoz210** [pmmp/PocketMine-MP#1788]
### Issue description
Items will not be removed and will appear in your inventory again

### Steps to reproduce the issue

1. place items in crafting menu (2x2)
2. use console command /kill PlayerName

### OS and versions
* PocketMine-MP: https://github.com/pmmp/PocketMine-MP/commit/49dbd8b2c84b243230c6fc5b7a7a545a4f27ba62

**Comment by dktapps** [comment]
#1567
