### ISSUE TITLE
Entities are saved on wrong chunks in negative coordinates

### ISSUE THREAD

**Issue by dktapps** [pmmp/PocketMine-MP#1789]
### Issue description
Bad typecasts. An entity at (-16.5, 4, -91.5) should be saved on chunk (-2, -6), and instead is saved on (-1, -6). This is because int typecasts and flooring are not the same thing on negatives.

This problem also exists with bitshifts on possible floats, since float operands of bitshifts are silently casted to ints.

**Comment by dktapps** [comment]
Not sure how to fix this without breaking compatibility with existing worlds previously saved by PM (fixing the bug will prevent entities saved on wrong chunks being loaded).

**Comment by zKoz210** [comment]
It will only affect the saved entity? It's just better to fix now than to waste time, I think so.

**Comment by dktapps** [comment]
https://github.com/pmmp/PocketMine-MP/blob/master/src/pocketmine/level/format/Chunk.php#L740

**Comment by dktapps** [comment]
Correction on the above: It will cause entities in the bounds of undefined areas (-16.0 > w > -17.0, -32 > w > -33, etc) to be deleted, not all entities in negative chunks would be affected.
