### ISSUE TITLE
Break time for cobweb with sword is incorrect

### ISSUE THREAD

**Issue by zKoz210** [pmmp/PocketMine-MP#1790]
### Issue description
Cobweb won't be broken normally, if `allow-instabreak: false`. Also, cobweb breaks down very long, although in single player this is a super fast

There are times when you miss the whole interface

### Steps to reproduce the issue

1. Place cobweb
2. Try to break with a sword

### OS and versions
* PocketMine-MP: https://github.com/pmmp/PocketMine-MP/commit/2e62c084a46db3112eb1bd569108aa7da95e886a
* Game version: PE/Win10

**Comment by dktapps** [comment]
Swords are strange snowflakes. They provide double breaking speed for any block.

**Comment by HimbeersaftLP** [comment]
> any block.

huh? https://minecraft.gamepedia.com/Sword#Sword_breaking_times

**Comment by dktapps** [comment]
For reference purposes: Try breaking stone in vanilla by hand, vs using a sword.

**Comment by optimusprime338** [comment]
Well this issue is same as when you enchant a pic with efficiency 20+ . You can't break blocks if instant break is off.

**Comment by dktapps** [comment]
that's because the efficiency enchantment isn't implemented yet.

**Comment by optimusprime338** [comment]
After certain tries I am able to break cobweb with wooden sword though

**Comment by dktapps** [comment]
The referenced PR should fix this bug, would anyone like to test?

**Comment by zKoz210** [comment]
@dktapps Yes, it works great, thanks
