### ISSUE TITLE
Arrow Can be dublicated using right hand!

### ISSUE THREAD

**Issue by optimusprime338** [pmmp/PocketMine-MP#1793]
### Issue description

Actually It doesn't duplicates directly but you can use unlimited arrows with it. On placing some amount
of arrows on right hand duplicates the arrow and if you leave those arrows on right hand and throw  other arrows you can use them/shoot them as usual!     

- Expected result: Arrows should not duplicate when placed on right hand
- Actual result: The are dublicating

### Steps to reproduce the issue

1. Take arrows from 1-64
2. Place them on right hand then remove other arrows from inventory
3. shoot and will be able to use them as normal

### OS and versions

* PocketMine-MP: 1.7dev-490 「[REDACTED]」 implementing API version 3.0.0-ALPHA10
* PHP: 7.2
* Server OS: Linux and windows
* Game version: PE/Win10 

### Plugins
- Test on a clean server without plugins: is the issue reproducible without any plugins loaded?
No plugins loaded

If the issue is **not** reproducible without plugins:
- Have you asked for help on our forums before creating an issue?
- Can you provide sample, *minimal* reproducing code for the issue? If so, paste it in the bottom section
- Paste your list of plugins here (use the 'plugins' command in PocketMine-MP)

### Crashdump, backtrace or other files
- Do not paste crashdumps into an issue - please use our Crash Archive at https://crash.pmmp.io for submitting crash reports to not spam the issue tracker. Add links to your reports in the Crash Archive here.
- Please use gist or anything else to add other files and add links here 

* ...

**Comment by dktapps** [comment]
The off-hand isn't implemented yet. Whatever you're seeing is client-sided ghosting. It's impossible (citation needed) for server-side duplication since the transaction system would detect it.

**Comment by optimusprime338** [comment]
Ohk!
