### ISSUE TITLE
Several blocks make player suffocate

### ISSUE THREAD

**Issue by thebigsmileXD** [pmmp/PocketMine-MP#181]
### Issue description

Most new blocks added since 0.13 are mass clones of solids.

### Steps to reproduce the issue

1. Place new Door types. You suffocate when walking through.
2. Place redstone torch at head height. You suffocate when walking through.
3. Place Itemframe. Same as above

### OS and versions

* PocketMine-MP: branch 1.0, commit https://github.com/pmmp/PocketMine-MP/commit/187ef1a270c17f007e88ff25ec380f2bb99e274f
* PHP: Provided bin on bitbucket
* Server OS: irrelevant

Labels: todo, 1.0, new api

**Comment by dktapps** [comment]
![image](https://cloud.githubusercontent.com/assets/14214667/21345214/32aadfb6-c697-11e6-8caa-233bd1937a43.png)
Please read... 

The suffocation issue has already been noted at #169 .

**Comment by thebigsmileXD** [comment]
It has nothing to do with the block's BB anyways.

**Comment by dktapps** [comment]
Well, it actually does, because of the use of the wrong hierarchy causes them to have wrong bounding boxes (i.e. a full block). But I re-read that issue and noticed I didn't actually mention the suffocation issue at all. :facepalm:

**Comment by thebigsmileXD** [comment]
Happens. And Entity.php checks if the player's BB collides with a solid block

**Comment by Dog2puppy** [comment]
Last I checked, buttons also caused you to suffocate.
