### ISSUE TITLE
Level block cache doesn't get cleaned up properly when chunks are set/replaced

### ISSUE THREAD

**Issue by dktapps** [pmmp/PocketMine-MP#1813]
### Issue description
https://forums.pmmp.io/threads/weird-block-glitch-on-interact.4658/#post-44516

### Steps to reproduce the issue

1. generate a new world
2. TP to somewhere not generated yet
3. click blocks around you and see if they vanish

### OS and versions

* PocketMine-MP: 67a576722c778939baba5274fd9ec797588409fd
* PHP: 7.2.0
* Server OS: win

**Comment by Fad3dD3V** [comment]
DONT SELL PMMP !

**Comment by Fad3dD3V** [comment]
DONT SELL PMMP !

**Comment by Fad3dD3V** [comment]
DONT SELL PMMP !

**Comment by Fad3dD3V** [comment]
DONT SELL PMMP !

**Comment by Fad3dD3V** [comment]
DONT SELL PMMP !

**Comment by Fad3dD3V** [comment]
DONT SELL PMMP !

**Comment by Fad3dD3V** [comment]
DONT SELL PMMP !

**Comment by Fad3dD3V** [comment]
DONT SELL PMMP !

**Comment by Fad3dD3V** [comment]
DONT SELL PMMP !

**Comment by Fad3dD3V** [comment]
DONT SELL PMMP !

**Comment by Fad3dD3V** [comment]
DONT SELL PMMP !

**Comment by Fad3dD3V** [comment]
DONT SELL PMMP !

**Comment by Fad3dD3V** [comment]
DONT SELL PMMP !

**Comment by Fad3dD3V** [comment]
DONT SELL PMMP !

**Comment by Fad3dD3V** [comment]
DONT SELL PMMP !

**Comment by Fad3dD3V** [comment]
DONT SELL PMMP !

**Comment by Fad3dD3V** [comment]
DONT SELL PMMP !

**Comment by Fad3dD3V** [comment]
DONT SELL PMMP !

**Comment by Fad3dD3V** [comment]
DONT SELL PMMP !

**Comment by Fad3dD3V** [comment]
DONT SELL PMMP !

**Comment by Fad3dD3V** [comment]
DONT SELL PMMP !

**Comment by Fad3dD3V** [comment]
DONT SELL PMMP !

**Comment by Fad3dD3V** [comment]
DONT SELL PMMP !

**Comment by Fad3dD3V** [comment]
DONT SELL PMMP !

**Comment by Fad3dD3V** [comment]
DONT SELL PMMP !

**Comment by Fad3dD3V** [comment]
DONT SELL PMMP !

**Comment by Fad3dD3V** [comment]
DONT SELL PMMP !

**Comment by Fad3dD3V** [comment]
DONT SELL PMMP !

**Comment by Fad3dD3V** [comment]
DONT SELL PMMP !

**Comment by Fad3dD3V** [comment]
DONT SELL PMMP !

**Comment by Fad3dD3V** [comment]
DONT SELL PMMP !

**Comment by Fad3dD3V** [comment]
DONT SELL PMMP !

**Comment by Fad3dD3V** [comment]
DONT SELL PMMP !

**Comment by Fad3dD3V** [comment]
DONT SELL PMMP !

**Comment by Fad3dD3V** [comment]
DONT SELL PMMP !

**Comment by Fad3dD3V** [comment]
DONT SELL PMMP !

**Comment by Fad3dD3V** [comment]
DONT SELL PMMP !

**Comment by Fad3dD3V** [comment]
DONT SELL PMMP !

**Comment by Fad3dD3V** [comment]
DONT SELL PMMP !

**Comment by Fad3dD3V** [comment]
DONT SELL PMMP !

**Comment by Fad3dD3V** [comment]
DONT SELL PMMP !

**Comment by Fad3dD3V** [comment]
DONT SELL PMMP !

**Comment by Fad3dD3V** [comment]
DONT SELL PMMP !

**Comment by Fad3dD3V** [comment]
DONT SELL PMMP !

**Comment by Fad3dD3V** [comment]
DONT SELL PMMP !

**Comment by Fad3dD3V** [comment]
DONT SELL PMMP !

**Comment by Fad3dD3V** [comment]
DONT SELL PMMP !

**Comment by Fad3dD3V** [comment]
DONT SELL PMMP !

**Comment by Fad3dD3V** [comment]
DONT SELL PMMP !

**Comment by Fad3dD3V** [comment]
DONT SELL PMMP !

**Comment by Fad3dD3V** [comment]
DONT SELL PMMP !

**Comment by Fad3dD3V** [comment]
DONT SELL PMMP !

**Comment by Fad3dD3V** [comment]
DONT SELL PMMP !

**Comment by Fad3dD3V** [comment]
DONT SELL PMMP !

**Comment by Fad3dD3V** [comment]
DONT SELL PMMP !

**Comment by Fad3dD3V** [comment]
DONT SELL PMMP !

**Comment by Fad3dD3V** [comment]
DONT SELL PMMP !

**Comment by Fad3dD3V** [comment]
DONT SELL PMMP !

**Comment by Fad3dD3V** [comment]
DONT SELL PMMP !

**Comment by Fad3dD3V** [comment]
DONT SELL PMMP !

**Comment by Fad3dD3V** [comment]
DONT SELL PMMP !

**Comment by Fad3dD3V** [comment]
DONT SELL PMMP !

**Comment by Fad3dD3V** [comment]
DONT SELL PMMP !

**Comment by Fad3dD3V** [comment]
DONT SELL PMMP !

**Comment by Fad3dD3V** [comment]
DONT SELL PMMP !

**Comment by Fad3dD3V** [comment]
DONT SELL PMMP !

**Comment by Fad3dD3V** [comment]
DONT SELL PMMP !

**Comment by Fad3dD3V** [comment]
DONT SELL PMMP !

**Comment by Fad3dD3V** [comment]
DONT SELL PMMP !

**Comment by Fad3dD3V** [comment]
DONT SELL PMMP !

**Comment by Fad3dD3V** [comment]
DONT SELL PMMP !

**Comment by Fad3dD3V** [comment]
DONT SELL PMMP !

**Comment by Fad3dD3V** [comment]
DONT SELL PMMP !

**Comment by Fad3dD3V** [comment]
DONT SELL PMMP !

**Comment by Fad3dD3V** [comment]
DONT SELL PMMP !

**Comment by Fad3dD3V** [comment]
DONT SELL PMMP !

**Comment by Fad3dD3V** [comment]
DONT SELL PMMP !

**Comment by Fad3dD3V** [comment]
DONT SELL PMMP !

**Comment by Fad3dD3V** [comment]
DONT SELL PMMP !

**Comment by Fad3dD3V** [comment]
DONT SELL PMMP !

**Comment by Fad3dD3V** [comment]
DONT SELL PMMP !

**Comment by Fad3dD3V** [comment]
DONT SELL PMMP !

**Comment by Fad3dD3V** [comment]
DONT SELL PMMP !

**Comment by Fad3dD3V** [comment]
DONT SELL PMMP !

**Comment by Fad3dD3V** [comment]
DONT SELL PMMP !

**Comment by Fad3dD3V** [comment]
DONT SELL PMMP !

**Comment by Fad3dD3V** [comment]
DONT SELL PMMP !

**Comment by Fad3dD3V** [comment]
DONT SELL PMMP !
