### ISSUE TITLE
Metadata is not cleared after setBlock()

### ISSUE THREAD

**Issue by zKoz210** [pmmp/PocketMine-MP#1822]
### OS and versions
* PocketMine-MP: https://github.com/pmmp/PocketMine-MP/commit/d93ded90471d078a535862e2be3c0388a2558884

**Comment by dktapps** [comment]
Please fill the issue template correctly. You haven't provided sufficient information for me to understand what the problem is.

**Comment by zKoz210** [comment]
@dktapps updated

**Comment by dktapps** [comment]
As far as I understand it, block metadata merely attaches to a certain block position in the world, so it may be intentional for it not to be removed on block change. However, I'm not sure how your issue can be solved (maybe BlockUpdateEvent?)
