### ISSUE TITLE
question

### ISSUE THREAD

**Issue by Andrew1481432** [pmmp/PocketMine-MP#184]
### Issue description
Redstone whether added to the core pmmp?
### OS and versions

* PocketMine-MP:
* PHP: 7.0.6
* Server OS: Debian
* Game version: PE/Win10
* ...

**Comment by dktapps** [comment]
Not yet. Please do not use our issue tracker for support requests and questions; use the [forums](https://forums.pmmp.io) instead.

**Comment by Andrew1481432** [comment]
ok, thank)
