### ISSUE TITLE
Interactions in adventure mode are excessively limited

### ISSUE THREAD

**Issue by SalmonDE** [pmmp/PocketMine-MP#1848]
### Issue description

The server seems to cancel interactions for adventure mode players, although they should be able to do things like open doors.

- Expected result: What were you expecting to happen?
Doors and trapdoors can be opened in adventure mode.
- Actual result: What actually happened?
You can neither open doors nor trapdoors.

### Steps to reproduce the issue

1. Place any door in front of you
2. Use "/gamemode 2" to put yourself in adventure mode
3. Try to open the door. (Doesn't matter if emtpy hand or not)

### OS and versions

* PocketMine-MP: ddbc5cf960e6553b24f19eb530f3a0b9061bb1ef
* PHP: 7.2.0
* Server OS: Linux Ubuntu Server 17.10 / Windows 10

### Plugins
- DevTools

**Comment by thebigsmileXD** [comment]
@SalmonDE remember, that the AdventureSettingsPacket defines, what you are actually allowed to do. Doors+Switches are a specific setting.

**Comment by dktapps** [comment]
Note however that with the bugfix in the referenced commit, players will be able to use flint&steel and buckets. You might want to check interactions and cancel them in the meantime before this is fixed.

**Comment by thebigsmileXD** [comment]
@dktapps that is actually worse than not being able to open doors. I already see spam like "lava and fire on my server"..
