### ISSUE TITLE
Single source plugin doesn't load unless phar is with it

### ISSUE THREAD

**Issue by v0idst4r** [pmmp/PocketMine-MP#1849]
If you only have one source plugin in the plugins directory, it won't even attempt to load it unless a phar is in the plugins directory as well. Affected release: 1.7dev-516 with API 3.0.0-ALPHA10

**Comment by Sandertv** [comment]
Source/folder plugins aren't loaded by the core; Devtools is used to load folder plugins.

**Comment by v0idst4r** [comment]
Ah, my bad. I thought the core did this.
