### ISSUE TITLE
Force Language doesn't work

### ISSUE THREAD

**Issue by Misteboss** [pmmp/PocketMine-MP#185]
### Issue description

When i set the option "force-language" to true in pocketmine.yml it doesn't do anything in game, the things aren't translated by the server
### Steps to reproduce the issue

1. ... Put "force-language" to true in pocketmine.yml
2. ... Restart your server

### OS and versions

* PocketMine-MP: branch 1.0, commit 187ef1a
* PHP: 7.0.2
* Server OS: Debian
* Game version: PE/Win10 for the two

### Crashdump, backtrace or other files

* ...

**Comment by dktapps** [comment]
May I ask what language you have set on the server-side?

**Comment by dktapps** [comment]
That commit also doesn't exist on the 1.0 branch, please check with a valid version before continuing.

**Comment by dktapps** [comment]
I'm unable to reproduce this with `eng` and force-language enabled, with commit https://github.com/pmmp/PocketMine-MP/commit/300a3d5ccd523a9aa6d26f0a93464654158d9861

**Comment by Misteboss** [comment]
I used eng. ini and do you try yo do a command who doesn't exist ? does it send you a custom message

**Comment by dktapps** [comment]
I'm sorry, that is related to the new-style commands in 0.16. There's nothing we can do about that, since command parsing is handled client-side. If the command isn't in the list of commands that the client sees in their list, it will simply not send anything to the server, so this can't be fixed.
