### ISSUE TITLE
Living::applyDamageModifiers() is called before EntityDamageEvent is fired

### ISSUE THREAD

**Issue by Muqsit** [pmmp/PocketMine-MP#1851]
### Issue description

Armor defense points are applied to EntityDamageEvent before plugins modify the damage in EntityDamageEvent. This has the possibility of gaining the victim HP than losing.
```php
object(pocketmine\event\entity\EntityDamageByEntityEvent)#29755 (8) {
  ["damagerEntityId":"pocketmine\event\entity\EntityDamageByEntityEvent":private]=>
  int(71)
  ["knockBack":"pocketmine\event\entity\EntityDamageByEntityEvent":private]=>
  float(0.4)
  ["cause":"pocketmine\event\entity\EntityDamageEvent":private]=>
  int(1)
  ["modifiers":"pocketmine\event\entity\EntityDamageEvent":private]=>
  array(3) {
    [0]=>
    float(4)
    [1]=>
    float(-6.4)
    [5]=>
    float(-0)
  }
  ["originals":"pocketmine\event\entity\EntityDamageEvent":private]=>
  array(1) {
    [0]=>
    int(8)
  }
  ["entity":protected]=>
  object(specter\network\SpecterPlayer)#35966 (0) {
  }
  ["eventName":protected]=>
  NULL
  ["isCancelled":"pocketmine\event\Event":private]=>
  bool(false)
}
```
The following is entity damage from sword being set to 4, the victim is equipped in full diamond armor.
```php
$event->setDamage(4);
```
### Steps to reproduce the issue

1. Call EntityDamageEvent and modify the damage depending on the armor defense points.

### OS and versions

* PocketMine-MP: c64b9ad
* PHP: 7.2.0
* Server OS: Ubuntu 14.04
* Game version: Bedrock Edition (in general)

**Comment by dktapps** [comment]
This is intended behaviour. You should pass the event to `applyDamageModifiers()` again to ensure the damage is recomputed proportionally. This is why it is public.

**Comment by Muqsit** [comment]
Oh okay, thanks
