### ISSUE TITLE
Unexpected crash

### ISSUE THREAD

**Issue by TheClimbing** [pmmp/PocketMine-MP#1853]
### Issue description

Got unexpected crash

### Steps to reproduce the issue

I don't know how it happend i was just moving around building when it crashed

### OS and versions

 PocketMine-MP:1.7dev-533
PHP:
Server OS:Win 10
Game version: PE
### Plugins
Haven't tested without plugins since i have no time. It's already too late
### Crashdump, backtrace or other files

https://crash.pmmp.io/view/8914

**Comment by dktapps** [comment]
plugin issue.
