### ISSUE TITLE
Problem with signs

### ISSUE THREAD

**Issue by TheClimbing** [pmmp/PocketMine-MP#1854]
### Issue description

Signs are bugged.You can't go on the second line if you haven't filled the spaces for the first line.

I expected to press enter and go on to the second line.

### Steps to reproduce the issue

1. Set a sign
2. Write a short word that won't fill the maximum spaces for the first line (e.g "eggs")
3 .Press enter
### OS and versions

* PocketMine-MP:1.7dev-553
* PHP:
* Server OS:Windows 10
* Game version: PE

### Plugins
I have tested it on clean server the problem persists
### Crashdump, backtrace or other files
NO crashdumps just this error when i spam too many symbols `[Server thread/CRITICAL]: InvalidArgumentException: "Array size must be 4!" (EXCEPTION) in "src/pocketmine/event/block/SignChangeEvent" at line 88`

**Comment by JackMD** [comment]
It happens to me too but after enabling "Use old keyboard input code" that
fixes keyboard bugs after the 0.8.x update in Block Launcher seems to fix
the bug. And after that I am able to write on signs and the keyboard glitch
where during chat, the keyboard seems to come above the field where text is
inserted, gets fixed.

**Comment by dktapps** [comment]
Sign typing on the client side is exceptionally buggy at the moment. This is not a fault of the server.
