### ISSUE TITLE
Generating World

### ISSUE THREAD

**Issue by kenygamer** [pmmp/PocketMine-MP#1855]
### Issue description

The client remains in the Generating World screen while attempting to join the server. This issue is not hapenning to me but to the rest of the world - or if I enable VPN. Remember my last issue concerning the [Building Terrain screen](https://github.com/pmmp/PocketMine-MP/issues/1143)? Well, it's the same thing backwards.

- Expected result: The client should be able to join the server.
- Actual result: The client remains in the Generating World screen and the server, if going to the console, treats the player like it joined. Finally, after a few minutes it disconnects with Unable to connect to world.

### Steps to reproduce the issue

1. Spin up a PocketMine-MP server
2. Try to join the server

### OS and versions

* PocketMine-MP: 1.7dev-516 「[REDACTED]」 implementing API version 3.0.0-ALPHA10 for Minecraft: PE v1.2.7 (protocol version 160)
* PHP: 7.2
* Server OS: Linux Ubuntu 16.04 LTS
* Game version: PE

### Plugins
- Test on a clean server without plugins: is the issue reproducible without any plugins loaded?
Yes.

**Comment by JackMD** [comment]
#1143

**Comment by dktapps** [comment]
not this again...

**Comment by dktapps** [comment]
Please enable debug output and report the MTU size reported in debug on connection for players who can and can't connect correctly. The message looks like this:

```
[11:23:59] [RakLibServer thread/DEBUG]: Created session for 192.168.0.4 39886 with MTU size 1464
```

**Comment by optimusprime338** [comment]
I cant reproduce this issue(used more then 10 vpn locations). Neither have this issue on my server..

**Comment by JackMD** [comment]
Same here. Cannot reproduce this issue.

**Comment by jojoe77777** [comment]
Does the console actually show the yellow message “xxx joined the game”?

**Comment by kenygamer** [comment]
@dktapps Ugh nevermind, I had to configure my game firewall... then it worked.

**Comment by fastmover** [comment]
I had the same issue on a cloud host. Turning down the MTU on the network interface to 1432 helped.
