### ISSUE TITLE
The server does not handle any mob

### ISSUE THREAD

**Issue by Occhioverde** [pmmp/PocketMine-MP#1866]
In version 1.7dev-571 (API 3.0.0-ALPHA 10) for Minecraft: PE v1.2.7 no type of mob is managed, neither peaceful nor hostile. I also tried to use the eggs, but after clicking the right mouse button, nothing happened.

- Windows version: 10 (Creators update) 64x
- PMMP version: 1.7dev-571 (API 3.0.0-ALPHA 10)
- MCPE version: Minecraft: PE v1.2.7

**Comment by IrishPacks** [comment]
Mobs aren't implemented into PMMP as of now, but [here](https://poggit.pmmp.io/p/PureEntitiesX/0.2.8-3.dev3) is a plugin that enables all mobs.

**Comment by Occhioverde** [comment]
@IrishPacks Ok. Thanks you.
