### ISSUE TITLE
PHPDoc fix needed in Enchantment

### ISSUE THREAD

**Issue by Yexeed** [pmmp/PocketMine-MP#1868]
### Issue description

PHPStorm is barking on my code when i'm setting level on enchantment, cause in PHPDoc @return saying that function getEnchantment can return Enchantment or null but it should return EnchantmentInstance or null.

### Steps to reproduce the issue

1. Open PHPStorm. Create plugin.
2.  ``
$ench = Enchantment::getEnchantment(Enchantment::PROTECTION);
$ench->setLevel(2);
``

### OS and versions
* PocketMine-MP: 1.7dev-567 "[REDACTED]"
* PHP: 7.2
* Server OS: Windows 10
* Game version: Win10

### Plugins
- Clean server.

### Crashdump, backtrace or other files
* No crashdumps provided

**Comment by dktapps** [comment]
You're doing it wrong. See https://github.com/pmmp/PocketMine-MP/blob/master/src/pocketmine/command/defaults/EnchantCommand.php#L67-L78 .
