### ISSUE TITLE
XBOX: Space in username is not accepted by Server

### ISSUE THREAD

**Issue by robske110** [pmmp/PocketMine-MP#187]
### Issue description

XBOX users that have a space in their name cannot join due to https://github.com/pmmp/PocketMine-MP/blame/master/src/pocketmine/Player.php#L1859-L1862. I think a space should be replaced with an underscore.

### Steps to reproduce the issue

1. Log in to Xbox with a username that has spaces in it.
2. Try to join a PM server.
3. You will get a nice disconnectionScreen.invalidName translated into your language!

### OS and versions

* PocketMine-MP: 8db4b7116c0e15b4364ed2e86e7bb3bc9eda19a4 (does not play a role)
* PHP: 7.0.13
* Server OS: MacOS (does not play a role)
* Game version: PE/Win10

**Comment by KaoPE** [comment]
hm.. If bad players join the server
admin is difficult to ban bad players
