### ISSUE TITLE
Server crashes on join

### ISSUE THREAD

**Issue by TheRoyalBlock** [pmmp/PocketMine-MP#1874]
## Issue Description
As I tested my plugin on a server, I decided to do some parkour while I waited for other players. After falling a few times and getting "reverting movement" errors in console, the game decided to kick me from flying not enabled. The gist below is from the same error, but with @HimbeersaftLP instead of me. After being kicked, I decide to rejoin and resume testing, but the other server players and me all got the "server closed" message. I check the console and see that the server crashed, but it could not properly crash. Instead, it force killed the threads. Not only do we see both of these issues, but we also see that float vs string issue (although I suspect that's a plugin issue).

## Steps to reproduce the issue

**Note: This is only from my testing. I haven't been able to reproduce it in other ways**
1. Get kicked by pmmp anticheat for reason: flying not enabled on this server
2. Rejoin the server immediately after

## OS and versions

* PocketMine-MP: 1.7dev-571 「[REDACTED]」 implementing API version 3.0.0-ALPHA10 for Minecraft: PE v1.2.7 (protocol version 160)
* PHP: 7.2.0RC3
* Server OS: Windows
* Game version: PE/Win10: Able to be reproduced on Android AND Win10

## Plugins
The issue is currently reproducible without plugins, although the gist below is from an instance of the server *with* plugins

## Crashdump, backtrace or other files
* https://gist.github.com/TheRoyalBlock/1041c877f0f01cff7787d6b48664954a

**Comment by kenygamer** [comment]
I suggest you to use the the [Crash Dump archive](https://crash.pmmp.io).

**Comment by dktapps** [comment]
I doubt it's reproducible without plugins. That's obviously caused by a plugin.

**Comment by TheRoyalBlock** [comment]
@kenygamer There was no crash dump.

@dktapps With all due respect, I was able to reproduce it without plugins as long as allow-flight was set to false in server.properties.
