### ISSUE TITLE
Client crash on server join

### ISSUE THREAD

**Issue by kenygamer** [pmmp/PocketMine-MP#1875]
### Issue description

I crash when I try to join a mc-region world built on Minecraft: Java Edition.

- Expected result: I shouldn't crash, since Minecraft: Java Edition worlds should be compatible with PocketMine.
- Actual result: After joining, one chunk loads and the client crashes.

### Steps to reproduce the issue

1. Try to join the server with this PC-version made world.

### OS and versions

* PocketMine-MP: 1.7dev-516 「[REDACTED]」 implementing API version 3.0.0-ALPHA10 for Minecraft: PE v1.2.7 (protocol version 160)
* PHP: 7.2.0
* Server OS: Ubuntu 16.04 LTS
* Game version: PE

### Plugins
- Test on a clean server without plugins: is the issue reproducible without any plugins loaded?
Yes.

**Comment by jasonwynn10** [comment]
No Console output?

**Comment by kenygamer** [comment]
Nope.

**Comment by Muqsit** [comment]
This is too hard to solve, can you send a screenshot of your screenshot output on your next encounter?

**Comment by dktapps** [comment]
I need a copy of the world used to debug this.

**Comment by kenygamer** [comment]
@dktapps I kindly ask you to send me any contact information such as your email address, due to the fact that this world is for private use.

**Comment by dktapps** [comment]
You can drop an email at dktapps@pmmp.io

**Comment by kenygamer** [comment]
Sent.

**Comment by kenygamer** [comment]
Hi,
Any news?

**Comment by nobody5050** [comment]
doesn't look like it but you might try using a world file converter as there is some out there sorry for not being able to link them

**Comment by kenygamer** [comment]
All of them are outdated and PC worlds should be compatible.

**Comment by Obamavn99** [comment]
i have this problem too

**Comment by kenygamer** [comment]
@dktapps

**Comment by dktapps** [comment]
I haven't had time to investigate this yet.

**Comment by dktapps** [comment]
@kenygamer the world you sent me works fine on my local server with 1.2.8. Not sure what the problem is.

**Comment by dktapps** [comment]
@kenygamer I flew around and inside the whole thing with no issues.

**Comment by kenygamer** [comment]
This issue is still hapenning to me. Could you send  screenshots to me@kenygamer.com?
 Thanks

**Comment by dktapps** [comment]
correction on that: Android doesn't crash, but W10 does.

**Comment by kenygamer** [comment]
Hmm.

**Comment by dktapps** [comment]
It's something to do with bad block metadata. Stripping the metadata, it works fine. Presumably it's some block that can't be rendered (correctly) by MCPE.

**Comment by kenygamer** [comment]
Anyway, I don't know how to do that.

**Comment by dktapps** [comment]
I'm not saying that is what you should do. I'm telling you it's some block which MCPE doesn't support. There's nothing I can do about that.

**Comment by kenygamer** [comment]
Yes I know. Are you going to have to solve this?

**Comment by dktapps** [comment]
> There's nothing I can do about that.

**Comment by kenygamer** [comment]
PC maps should be compatible with MCPE... and it's strange that it only works on Android. I paid $30 for the map and I haven't been able to import it for almost two months.

**Comment by dktapps** [comment]
> PC maps should be compatible with MCPE...

it's well known that they are not.

**Comment by dktapps** [comment]
Rotated observer blocks appear to be a source of crashes. Consider deleting them using Minecraft PC before using the world on a server. (In Minecraft PC they'll be concrete blocks I believe).

Implementing ID mapping is something I plan to do in the future, but not in the near future.

**Comment by kenygamer** [comment]
Follow up.
I did what you said. I converted all blocks with ID 251, 252, and 218. I can at least fly through the map for a few seconds until I crash (again).

**Comment by kenygamer** [comment]
@dktapps

**Comment by optimusprime338** [comment]
@kenygamer check your world or change world it self! I tried to reproduce it! I think everything is fine!
I have experienced mcpc maps decreases fps on lower end devices though no idea why but try to use region created by pmmp it self:)

**Comment by kenygamer** [comment]
@optimusprime338 I don't understand.

**Comment by kenygamer** [comment]
![](https://i.imgur.com/bdIq5.png)

**Comment by kenygamer** [comment]
> It's something to do with bad block metadata. Stripping the metadata, it works fine. Presumably it's some block that can't be rendered (correctly) by MCPE.
It worksm but you still crash at some point.

**Comment by YaBoiLewis** [comment]
Like @dktapps mentioned above, "There is nothing he can do about that." -

Chances are, the windows 10 version & MC-Android & MC-iOS are done differently and thus, have different files. 

Android amazingly (although I highly doubt my hypothesis), may be able to render this block (not sure if Mojang missed a check); while iOS and Windows 10 versions can't. This is highly unrelated to Pocketmine in any possible way, but something related to MC. Mojang won't fix it as it is tested on a Pocketmine server (a third-party testing ground) and as far as they know, the bug isn't their fault. Neither can you blame them, Java worlds were never meant for Bedrock. 

You're lucky you found about this earlier, the console versions could have had an even bigger disaster. 

One thing that does come up here is an option for a PM feature. On map loading, it already loads each chunk separately. While loading, have it check whether the chunk has an invalid block that isn't present in MC-Bedrock. If so, have it give the position (a 3D value, [x, y, z] - not implying the object) of the block. This could help solve future issues relating to this much quicker. However, this is a debug feature. 

I'll leave this here as a suggestion if dktapps chooses to accept it - chances are he won't as he already dislikes me.. but whatever. 

I hope you fix your issue though @kenygamer - or try implementing this check yourself.

**Comment by dktapps** [comment]
Removed spam.
