### ISSUE TITLE
Unhandled InventoryTransactionPacket

### ISSUE THREAD

**Issue by KennFatt** [pmmp/PocketMine-MP#1883]
### Issue description

- Actual result: Unhandled InventoryTransactionPacket while player (Windows 10) right clicking other player.

Clicker: Windows 10 (1.2.8)
Dummy: Minecraft PE (1.2.7)

### Steps to reproduce the issue

1. Right click to another player with any items or any gamemode (tested already)
2. Debug message 'Unhandled InventoryTransactionPacket'

### OS and versions

* PocketMine-MP: f963dbd10dbf316c2653b4b585343e696d1aaee3
* PHP: 7.2
* Server OS: Windows 10
* Game version: PE/Win10

### Plugins
- DevTools

### Crashdump, backtrace or other files
`
> Unhandled InventoryTransactionPacket received from iKennz15: 0x1e0000030003000600f8a77e431fd7b340f5297f43d8827f43015fb640cc1d8043
> Unhandled InventoryTransactionPacket received from iKennz15: 0x1e0000030003000600f8a77e431fd7b340f5297f43d8827f43663bb3405daa7f43
> Unhandled InventoryTransactionPacket received from iKennz15: 0x1e0000030003000600f8a77e431fd7b340f5297f43d8827f4336a2b240c2a47f43
> Unhandled InventoryTransactionPacket received from iKennz15: 0x1e0000030003000600f8a77e431fd7b340f5297f43d8827f4336a2b240c2a47f43
> Unhandled InventoryTransactionPacket received from iKennz15: 0x1e0000030003000600f8a77e431fd7b340f5297f43d8827f434562aa40ebb87f43
`

**Comment by dktapps** [comment]
This isn't a bug, it's just not implemented yet.
