### ISSUE TITLE
Bucket with water not shown as full

### ISSUE THREAD

**Issue by Taraman17** [pmmp/PocketMine-MP#1884]
### Issue description
When you fill a bucket with water, the water filled bucket is briefly shown as full, then the empty-bucket-sprite is returning.
Bucket is definitely full and can be emptied elswhere.

- Expected result: Bucket is shown as full in inventory
- Actual result: Bucket is shown empty despite it is full

### Steps to reproduce the issue
1. get a bucket
2. fill it by clicking on a water block

### OS and versions
* PocketMine-MP: Version 3.0.0-ALPHA10 der API für Minecraft:PE v1.2.7 (Protokoll Version 160)MP 1.7dev-516 ▒[REDACTED]▒
* PHP: PHP 7.2.0 (cli) (built: Dec 30 2017 16:56:51) ( ZTS )
* Server OS: Raspi3 debian buster Linux 4.5.0+ aarch64
* Game version: PE 1.2.8 on Android

### Plugins
none

### Crashdump, backtrace or other files
N.A.

**Comment by dktapps** [comment]
This has already been fixed in the latest development builds.

**Comment by Taraman17** [comment]
Sorry guys, don't have time to torture my kids with the dev-builds. ;-)

**Comment by dktapps** [comment]
No problem, we don't expect you to.
