### ISSUE TITLE
crash when no players are on

### ISSUE THREAD

**Issue by nobody5050** [pmmp/PocketMine-MP#1890]
### Issue description

crash when no players online

- Expected result: What were you expecting to happen?
the server to run
- Actual result: What actually happened? 
crash

### Steps to reproduce the issue

1. ...start the server
2. ...kick all players

### OS and versions

* PocketMine-MP:
* PHP:
* Server OS:

### Plugins
- Test on a clean server without plugins: is the issue reproducible without any plugins loaded?
 AllSigns v1.0.6, BuycraftPM v0.5.0-2, CrateUI v1, EconomyAPI v5.7.1-4, EconomyPShop v2.0.2-5, EssentialsPE v2.0.0, essentialsTP v1.2.0-5, iProtector v3.1.0-8, ItemCase v1.2.1-1, ItemCloud v1.3.0-2, MagicTelePortal v1.3.2-4, PiggyCustomEnchants v1.1.0, PurePerms v1.4.1-3, ShopUI v1.0.1, SignPortal v1.1.3-3, SimpleAuth v2.1.2-5, SimpleAuthHelper v2.0.6-5, Slapper v1.3.7, VoteReward v3.0.2-4, MagicWE v0.2.7, Worlds v1.0.13, FactionsPro v1.3.11-8

If the issue is **not** reproducible without plugins:
- Have you asked for help on our forums before creating an issue?
- Can you provide sample, *minimal* reproducing code for the issue? If so, paste it in the bottom section
- Paste your list of plugins here (use the 'plugins' command in PocketMine-MP)

### Crashdump, backtrace or other files
- Do not paste crashdumps into an issue - please use our Crash Archive at https://crash.pmmp.io for submitting crash reports to not spam the issue tracker. Add links to your reports in the Crash Archive here.
- Please use gist or anything else to add other files and add links here 

* ...

**Comment by dktapps** [comment]
Without knowing your PocketMine-MP version, OS, PHP, Client version, or plugins and how the issue occurred, the issue cannot begin to be solved.
A pre-formatted template is provided that shows the required information to begin to find, test and solve an issue.
Until the adequate template and information is provided, the issue will be closed; it may be reopened if you update the ticket with the correct template and required information.

[Contribution guidelines](https://github.com/pmmp/PocketMine-MP/blob/master/CONTRIBUTING.md)

**Comment by nobody5050** [comment]
plz reopen now sorry for being unclear before

**Comment by kenygamer** [comment]
@nobody5050 So you are using PHP 2?

**Comment by DrewD3V** [comment]
@kenygamer Who doesn’t use PHP 2?

**Comment by kenygamer** [comment]
@DrewD3V PHP 2 is an outdated version of PHP and is not supported by PocketMine. Not even when PocketMine was released for the first time, it was PHP 5.

**Comment by DrewD3V** [comment]
Maybe I should’ve added /s to emphasize sarcasm...

**Comment by kenygamer** [comment]
I have noticed

**Comment by nobody5050** [comment]
PHP 2.0 is what I'm using

**Comment by kenygamer** [comment]
@nobody5050 If you are really using PHP 2.0 then clearly the problem is due to your PHP version.

**Comment by nobody5050** [comment]
I updated my PHP binary and it made the server more stable but now when loading new chunks the server crashes

**Comment by kenygamer** [comment]
Try to reproduce the issue without plugins.

**Comment by optimusprime338** [comment]
This not a personal help center. please go here:- https://forums.pmmp.io/

**Comment by nobody5050** [comment]
im reporting a bug where the server crashes loading new chunks

**Comment by optimusprime338** [comment]
Its you world! No idea where you got that from! We are not getting that issue.. + You did not followed issue submitting procedure so its point less to talk here!

**Comment by nobody5050** [comment]
im reporting a bug where the server crashes loading new chunks

**Comment by nobody5050** [comment]
I tried to follow what did I do wrong
