### ISSUE TITLE
Lava sets fire to the player if he stands next

### ISSUE THREAD

**Issue by zKoz210** [pmmp/PocketMine-MP#1892]
### Issue description
Lava sets fire to the player if he stands next

### Steps to reproduce the issue

1. Place block of lava
2. Go to a distance of one block

### OS and versions
* PocketMine-MP: https://github.com/pmmp/PocketMine-MP/commit/4d2549b50ab245649b40367c4070294251de6419
* Game version: PE/Win10

Video: [1234.zip](https://github.com/pmmp/PocketMine-MP/files/1610042/1234.zip)

**Comment by dktapps** [comment]
#1880 resolves this.
