### ISSUE TITLE
Items disappearing from hand on use

### ISSUE THREAD

**Issue by Yexeed** [pmmp/PocketMine-MP#1893]
### Issue description
- Expected result: Item was used
- Actual result: Item disappeared from hand but slot doesnt changed in hotbar

### Steps to reproduce the issue

1. Take any item
2. Try to use it

### OS and versions

* PocketMine-MP: commit b6811b6
* PHP: 7.2
* Server OS: Win10
* Game version: Win10

### Plugins
- Clean server

### Crashdump, backtrace or other files
* Video
[Video.zip](https://github.com/pmmp/PocketMine-MP/files/1612212/Video.zip)

**Comment by dktapps** [comment]
I can't reproduce this. What client version are you using? This looks like a client-sided glitch to me.

**Comment by Yexeed** [comment]
![image](https://user-images.githubusercontent.com/32373441/34682374-d40104e8-f4af-11e7-97fd-73560144235d.png)
1.2.8

**Comment by Yexeed** [comment]
I cant reproduce this too, lol. I think this glitch was caused by adding namedTagEntry to item, because i just tried to reproduce this again and i cant get this glitch since I just dont giving namedtagentry to item anymore. I tried it again with entry but still cant reproduce, i dont know what was changed.

**Comment by Yexeed** [comment]
You can close this issue if you want
