### ISSUE TITLE
Crash on connect

### ISSUE THREAD

**Issue by LestaD** [pmmp/PocketMine-MP#19]
### Issue description
Crash on connect

### Steps to reproduce the issue
1. Install php
2. Clone master 6b06e407c63971c6f03967e494a93d0b76b72e04
3. Run server and start with default params
4. Try to connect from android device

### OS and versions
* PocketMine-MP: `1.6dev 「Unleashed」 implementing API version 2.0.0 for Minecraft: PE v0.15.10.0 alpha (protocol version 84)`
* PHP: `7.0.11`
* OS: `Ubuntu 14.04.1`
* Application: `Nexus 6P, Android 7.0, Minecraft PE v0.15.90 alpha build 1`

### Crashdump, backtrace or other files
![screenshot from 2016-10-12 02 46 04](https://cloud.githubusercontent.com/assets/5620073/19292619/6ce4ff62-902e-11e6-8c0c-f1efed60fa43.png)

**Comment by legoboy0215** [comment]
How did you install PHP? To my eyes, it seems like you don't have the bcmath extension compiled.

**Comment by robske110** [comment]
You need plenty of php extensions for PM. I wonder why there is no check in PocketMine.php for this extension...

**Comment by LestaD** [comment]
@legoboy0215 thankyou, it solve my problem
