### ISSUE TITLE
Do not shoot the bow, if a player jumps

### ISSUE THREAD

**Issue by vzlomka76** [pmmp/PocketMine-MP#190]
### Issue description
Do not shoot the bow, if a player jumps
It's fixed on Genisys, not fixed on pmmp

### OS and versions
* PocketMine-MP: mcpe-1.0
* PHP: 7.0.6
* Server OS: ubuntu 16.04
* Game version: PE/Win10 (delete as appropriate)

**Comment by dktapps** [comment]
This has been fixed on a development branch and will be merged at a later date (no date of merge can be provided).
