### ISSUE TITLE
in gamemode 1, you die at the end of the world

### ISSUE THREAD

**Issue by VCraftMCPE** [pmmp/PocketMine-MP#1909]

**Comment by dktapps** [comment]
Without knowing your PocketMine-MP version, OS, PHP, Client version, or plugins and how the issue occurred, the issue cannot begin to be solved.
A pre-formatted template is provided that shows the required information to begin to find, test and solve an issue.
Until the adequate template and information is provided, the issue will be closed; it may be reopened if you update the ticket with the correct template and required information.

[Contribution guidelines](https://github.com/pmmp/PocketMine-MP/blob/master/CONTRIBUTING.md)

**Comment by VCraftMCPE** [comment]
@dktapps

**Comment by kenygamer** [comment]
@VCraftMCPE Answer kik

**Comment by kenygamer** [comment]
I can reproduce this too, but I'm not sure if it's an issue.

**Comment by TDMidkwhatisxd** [comment]
` Without knowing your PocketMine-MP version, OS, PHP, Client version, or plugins and how the issue occurred, the issue cannot begin to be solved.
A pre-formatted template is provided that shows the required information to begin to find, test and solve an issue.
Until the adequate template and information is provided, the issue will be closed; it may be reopened if you update the ticket with the correct template and required information.
Contribution guidelines`

Is that a bot?

**Comment by kenygamer** [comment]
I can reproduce this too.

**Comment by dktapps** [comment]
Not sure I know what you're talking about. There is no End dimension yet.

**Comment by kenygamer** [comment]
@dktapps  He means you die at the void, and that's not a bug anyways.

**Comment by dktapps** [comment]
In MCPE creative you don't die in the void, but then in MCPE creative, /kill doesn't work either. I'm going to assume both are MCPE bugs.

**Comment by VCraftMCPE** [comment]
@dktapps in MiNET works fine

**Comment by dktapps** [comment]
I fail to see what relevance MiNET has here. We're working to match vanilla, not for MiNET.
