### ISSUE TITLE
PlayerCommandPreprocessEvent is not working

### ISSUE THREAD

**Issue by kenygamer** [pmmp/PocketMine-MP#1916]
### Issue description

PlayerCommandPreprocessEvent is being ignored, cannot override /help. Heard that /help is now client side, so how do you override it?

- Expected result: Override /help
- Actual result: /help shows the command list

### Steps to reproduce the issue

Listen to PlayerCommandPreprocessEvent

### OS and versions

* PocketMine-MP: 1.7dev-516 「[REDACTED]」 implementing API version 3.0.0-ALPHA10 for Minecraft: PE v1.2.7 (protocol version 160)
* PHP: 7.2.0
* Server OS: Ubuntu 16.04 LTS
* Game version: PE

### Plugins
- Test on a clean server without plugins: is the issue reproducible without any plugins loaded?
It needs to be reproduced with a plugin.

**Comment by dktapps** [comment]
This is not a plugin support forum. Please use the [forums](https://forums.pmmp.io) for support.
