### ISSUE TITLE
Tutorial(For beta pmmp 1.0) How to install plugins with 3.0.0 api

### ISSUE THREAD

**Issue by ondraczsk** [pmmp/PocketMine-MP#192]
Tired with incopatible api? Try this!
How to install plugins on server with api 3.0.0

1.Download plugin what do you want
2. Convert to zip at pmt.mcpe.me
3.Unpack
4.In plugin.yml, replace old api to new ( api: [3.0.0-ALPHA1] or api: [1.11.0, 2.0.0, 3.0.0-ALPHA1] )
5.Save
6.Convert to zip
7.Go to pmt.mcpe.me and convert it to phar or use devtools 
8.Install to plugin folder

I edit plugin ServerAuth and WORKING! Yayy :D 

Sorry for my english :P

**Comment by SOF3** [comment]
WTF

**Comment by ondraczsk** [comment]
xD tutorial for noobs

**Comment by dktapps** [comment]
Tutorial for noobs? Noobs shouldn't be using development builds.
