### ISSUE TITLE
Problem with this

### ISSUE THREAD

**Issue by Adam1609** [pmmp/PocketMine-MP#1922]
### Issue description

I know that it is not invalid but, I tried almost every single code about setKeepInventory() but it seems to not working, I don't understand why :(

- Expected result: What were you expecting to happen?
- Actual result: What actually happened?

### Steps to reproduce the issue

1. Try writing the code with setKeepInventory(true)
2. See if your inventory is gone or kept

### OS and versions

* PocketMine-MP: 1.7dev-625
* PHP: 7.2
* Server OS: Windows Server 2008 Standard R2 64-bit
* Game version: PE

### Plugins
- Test on a clean server without plugins: is the issue reproducible without any plugins loaded?

If the issue is **not** reproducible without plugins:
- Have you asked for help on our forums before creating an issue?
- Can you provide sample, *minimal* reproducing code for the issue? If so, paste it in the bottom section
- Paste your list of plugins here (use the 'plugins' command in PocketMine-MP)

### Crashdump, backtrace or other files
- Do not paste crashdumps into an issue - please use our Crash Archive at https://crash.pmmp.io for submitting crash reports to not spam the issue tracker. Add links to your reports in the Crash Archive here.
- Please use gist or anything else to add other files and add links here 

* ...

**Comment by dktapps** [comment]
This is not a support forum. Please use the [forums](https://forums.pmmp.io) for support.
