### ISSUE TITLE
Arrow velocity

### ISSUE THREAD

**Issue by Encritary** [pmmp/PocketMine-MP#1931]
### Issue description

In MC:BE and MC:JE base arrow velocity is 3, but here it is 2. Why?

### Steps to reproduce the issue

Just use bow in vanilla and on pmmp server.
### OS and versions

* PocketMine-MP: beb5bf6ddac4a9beb705ff2e789537d37efe6bcc
* PHP: 7.2
* Server OS: Ubuntu 16.04
(it isn't necessary)

### Plugins
No plugins.
### Crashdump, backtrace or other files
None.

**Comment by dktapps** [comment]
> In MC:BE and MC:JE base arrow velocity is 3, but here it is 2. Why?

![](https://upload.wikimedia.org/wikipedia/commons/3/31/Webcomic_xkcd_-_Wikipedian_protester.png)

**Comment by dktapps** [comment]
On the contrary, it is exactly the same.
