### ISSUE TITLE
Launching projectiles throws an error - Called Projectile::setOwningEntity() on null

### ISSUE THREAD

**Issue by Muqsit** [pmmp/PocketMine-MP#1942]
### Issue description

- Expected result: What were you expecting to happen?
- Actual result: What actually happened?

After the Entity data property refactoring, the server throws an error whenever you try to launch a projectile. Due to calling `setOwningEntity()` before `Entity::__construct()` in Projectile class.

### Steps to reproduce the issue

1. Throw a projectile

### OS and versions

* PocketMine-MP: 8f92891
* PHP: 7.2
* Server OS: Ubuntu 17.04
* Game version: Win10

### Plugins
Not tested without plugins, but logically speaking, it's a Projectile issue.
Tested with every projectile.
_Update:_ Tested on a clean server.

### Crashdump, backtrace or other files

* https://pastebin.com/rBZh6BY1

**Comment by dktapps** [comment]
should be a one-liner to fix - projectiles are the odd ones out there anyway. If you want to PR and fix it, please feel free. If not, I'll fix it later.
