### ISSUE TITLE
Is "server-name" option affect on something?

### ISSUE THREAD

**Issue by Yexeed** [pmmp/PocketMine-MP#1944]
### Issue description

- Expected result: "server-name" affects on something.
- Actual result: "server-name" field wasnt found in Server.php class and it doesnt affect something.

I dont think that any description needed. I just saw that on Nukkit "server-name" affects on this field:
![image](https://user-images.githubusercontent.com/32373441/35186752-5697eb1e-fe2a-11e7-8418-0722e723ac67.png)
But on PMMP it doesn't

**Comment by Yexeed** [comment]
Someone can say that "server-name" doesnot provided by server generator by default:
![image](https://user-images.githubusercontent.com/32373441/35186765-a04b5d40-fe2a-11e7-968a-5ab0abdb74bc.png)
But SetupWizard does
![image](https://user-images.githubusercontent.com/32373441/35186767-b02dd9cc-fe2a-11e7-9591-93d5aeb50523.png)

**Comment by dktapps** [comment]
Legacy code. That property is deprecated.

**Comment by Yexeed** [comment]
thanks
