### ISSUE TITLE
Kill the instabreak anti-cheat - silly idea

### ISSUE THREAD

**Issue by zKoz210** [pmmp/PocketMine-MP#1945]
### Issue description
In fact you made things worse, for all the cheaters now there is an opportunity super fast to break blocks. 

Now all users will NEED to make a separate plugin to fix this problem. 
The best option was to leave it standard, if someone didn't like it, it was the switch in pocketmine.yml
Really, thanks to you, I got ruined the world of survival and now have to do the cleaning map.

Ex js code:
```
Entity.addEffect(Player.getEntity (), 3, 5000000, 999, true); 
```

Video: https://www.dropbox.com/s/vhtupu5lzvanigd/mobizen_20180120_230710.mp4?dl=0

### OS and versions
* PocketMine-MP: https://github.com/pmmp/PocketMine-MP/commit/29e06e30b2296b66f19041a715c52f9822f777eb
* PHP: 7.2
* Game version: PE/Win10)

**Comment by dktapps** [comment]
Such a plugin already exists. And you chose to use a bleeding-edge build with it removed. You have nobody to blame but yourself.

**Comment by zKoz210** [comment]
Let's remove anti-cheat motion, which delivers more of a pain in the ass. After all, it is also possible to add a plugin.
