### ISSUE TITLE
Server start but port show it closed, Not have firewall installed.

### ISSUE THREAD

**Issue by mario0582** [pmmp/PocketMine-MP#1963]
Good night, I decided to create this topic because I have a problem and I can not find a solution, I'm trying to host the server in a cloud in OVH. the server installs and starts normally but I can not get into the world. no player can either.

The game reports that it can not connect to the server.

I used a tool to check and it says that port 19123 is closed, but the server does not have an active firewall and I have manually added the ports in IPTables, but I still do not succeed.

I've tried using other ports, disable the firewall, tried out a PHP application, and it works normally, but the server does not allow access through the game.

I used: https://www.yougetsignal.com/tools/open-ports/

and this tool says that the door is closed, but I already applied all possible procedures to open doors and nothing worked.

Steps to reproduce the issue
Unfortunately, I was not able to understand the cause of this problem.

OS and versions
PocketMine-MP: a4ca3f1
Steadfast2: Hydreon / Steadfast2 @ 42fd893
PHP: 7.2.0RC4
Server OS: CentOS 7.4.1708
Game version: PE / Win10
Plugins
Not have plugins

Debug logs not show errors.

**Comment by dktapps** [comment]
This is not a support forum. Please use the [forums](https://forums.pmmp.io) for support.

**Comment by mario0582** [comment]
The forum does not allow me to post.

**Comment by mario0582** [comment]
Please forgive me for bringing this problem here, but I can not post on the forum even though I am registered.

**Comment by optimusprime338** [comment]
@mario0582 go to control panel -> IP(from left)-> click setting icon left side of IP in IP list->config game firewall! 
you need to set it up no matter if firewall is on or off!
