### ISSUE TITLE
Incorrect world loading of mcregion worlds due to glob() not working on some systems

### ISSUE THREAD

**Issue by dktapps** [pmmp/PocketMine-MP#197]
### Issue description
An MCRegion world can be mis-loaded as Anvil due to glob() returning an empty array or false on some systems. This is due to Anvil::isValid() using glob() to scan the directory for mcr files.

### Steps to reproduce the issue

1. Run a server on Android for example
2. Generate, build in and save an mcregion world, and reboot the server
3. Notice all your building is gone, and that there are now a mixture of mcr and mca in your region folder for that world

### Solutions
- scandir()
- [insert other solutions here]

### OS and versions

* PocketMine-MP: 1.6.2dev @ https://github.com/pmmp/PocketMine-MP/commit/363b24c6636dbf0edd20f93c8ecd95aaa433039e, but the code causing this is identical on master
* PHP: 7.0.13 aarch64
* Server OS: Android
* Game version: PE/Win10 (delete as appropriate)

### Crashdump, backtrace or other files

* ...

**Comment by flaxues** [comment]
This might help for the solution "[insert other solutions here]"
http://stackoverflow.com/questions/12599768/php-glob-alternatives

Just delete if it doesn't help

**Comment by flaxues** [comment]
Great job! I really love your work
