### ISSUE TITLE
Saplings Do Not Need Space To Grow

### ISSUE THREAD

**Issue by Haxley** [pmmp/PocketMine-MP#1972]
### Issue description

Saplings do not need adjacent space to grow. Saplings can grow trees touching each other without space in between them.

- Expected result: What were you expecting to happen?
Expecting saplings needed adjacent space to grow. 

- Actual result: What actually happened?
Saplings do not need adjacent space to grow.

### Steps to reproduce the issue

1. ... Plant saplings next to eachother.
2. ... Use bone meal to make them grow.
3. ... Observe them not needing adjacent space to grow.

### OS and versions

* PocketMine-MP: 1.7dev-516
* PHP: 7
* Server OS: Linux
* Game version: PE/Win10 

### Plugins
- Test on a clean server without plugins: is the issue reproducible without any plugins loaded?
Same results on clean server.

If the issue is **not** reproducible without plugins:
- Have you asked for help on our forums before creating an issue?
- Can you provide sample, *minimal* reproducing code for the issue? If so, paste it in the bottom section
- Paste your list of plugins here (use the 'plugins' command in PocketMine-MP)

### Crashdump, backtrace or other files
- Do not paste crashdumps into an issue - please use our Crash Archive at https://crash.pmmp.io for submitting crash reports to not spam the issue tracker. Add links to your reports in the Crash Archive here.
- Please use gist or anything else to add other files and add links here 

* ...

**Comment by dktapps** [comment]
This actually behaves the same way in vanilla PC:
![image](https://user-images.githubusercontent.com/14214667/39915585-3bd43e72-5500-11e8-8be9-45b691a36cac.png)
![image](https://user-images.githubusercontent.com/14214667/39915608-47d1a854-5500-11e8-811b-f9e7d31456bd.png)

However, PocketMine-MP does not account for a) light level (which has to be >= 8), and b) randomness when using bonemeal (not implemented).

**Comment by dktapps** [comment]
and also in vanilla PE as it happens:
![image](https://user-images.githubusercontent.com/14214667/39915713-90f9cdc2-5500-11e8-90d6-7b2c45748b02.png)

Closing this since it matches vanilla behaviour. Some other tweaks do need to be made, but this issue is invalid.

**Comment by Haxley** [comment]
The versions your testing on are either not working as intended or in creative mode. Everyone who plays single-player on PE **cannot** grow trees adjacent to each other (unless it's a 2x2 tree or creative mode). I can't speak for Java but if so, it's probably not working as intended (or in creative mode) as every web search returns requirements for tree spacing. Tree farms on my server literally look like huge solid log blocks.

**Comment by JackNoordhuis** [comment]
@Haxley it is possible to grow trees in vanilla bedrock survival directly next to each other with bonemeal (a lot of it at that) however, the chances of it happening naturally would be extremely low. I haven't tested it on the Java edition or taken the time to see if it can happen naturally but testing it on PE survival with bonemeal works fine.

**Comment by dktapps** [comment]
With normal growth it's dependent on light levels. Saplings under trees don't grow because they don't have sufficient light available, not because there is not sufficient space.

I tested this in both creative and survival, and also looked at reverse engineered PC code to verify. Sorry, but you're simply wrong.
