### ISSUE TITLE
Dark Oak and Acacia Saplings do not grow

### ISSUE THREAD

**Issue by Haxley** [pmmp/PocketMine-MP#1973]
### Issue description

Dark Oak and Acacia Saplings Grow to Regular Oak

- Expected result: What were you expecting to happen?
Saplings to grow into their associated tree type.
- Actual result: What actually happened?
Dark Oak and Acacia Saplings Grow to Regular Oak
### Steps to reproduce the issue

1. ... Place Dark Oak or Acacia Sapling
2. ... Use Bone Meal on the Saplings
3. ... Observe them grow into regular Oak

### OS and versions

* PocketMine-MP: 1.7dev-516
* PHP: 7
* Server OS: Linux
* Game version: PE/Win10

### Plugins
- Test on a clean server without plugins: is the issue reproducible without any plugins loaded?
Yes, tested on clean server.

If the issue is **not** reproducible without plugins:
- Have you asked for help on our forums before creating an issue?
- Can you provide sample, *minimal* reproducing code for the issue? If so, paste it in the bottom section
- Paste your list of plugins here (use the 'plugins' command in PocketMine-MP)

### Crashdump, backtrace or other files
- Do not paste crashdumps into an issue - please use our Crash Archive at https://crash.pmmp.io for submitting crash reports to not spam the issue tracker. Add links to your reports in the Crash Archive here.
- Please use gist or anything else to add other files and add links here 

* ...

**Comment by dktapps** [comment]
Dark oak and acacia trees aren't implemented yet. The default is to grow an oak tree, as seen here:

https://github.com/pmmp/PocketMine-MP/blob/master/src/pocketmine/level/generator/object/Tree.php#L64

**Comment by Haxley** [comment]
Ok thanks

**Comment by YaBoiLewis** [comment]
It is recommended that you use `if ()` loop rather than `switch ()` - for `if ()` executing faster. Improves performance. @dktapps

**Comment by dktapps** [comment]
Removed spam.

**Comment by dktapps** [comment]
Superseded by #5756
