### ISSUE TITLE
Can't transfer more than one item at a time between inventories.

### ISSUE THREAD

**Issue by dschwartz783** [pmmp/PocketMine-MP#1977]
### Issue description
The normal "hold down to transfer multiple items" feature isn't working at all. Seems to always transfer a single item, no matter how many you have, or how long you hold down the item. Even if the green bar fills to 100%, only a single item is transferred.

- Expected result: Multiple items should be transferred from inventory to inventory.
- Actual result: Only a single item is transferred.

### Steps to reproduce the issue
1. Transfer stuff from one inventory to another, by holding down a stack of items until the green bar fills, and release.

### OS and versions
* PocketMine-MP commit: b03b2366ded5605c567706c4927205ec7432aa0d
* PHP: 7.2
* Server OS: CentOS 6.9 and macOS 10.13
* Game version: PE

### Plugins
- None

**Comment by optimusprime338** [comment]
I think its client side? https://bugs.mojang.com/browse/MCPE-30215

**Comment by dschwartz783** [comment]
This glitch only allows a single item, while there it seems to allow two or three... Also, it sounds like that one's Android-only. My client is the iOS version. It's possible that whatever is causing that bug in the client, is related to what's going on here though. It would be an awfully big coincidence otherwise.

**Comment by dschwartz783** [comment]
But, it may just be manifesting itself differently on my device, so who knows.
