### ISSUE TITLE
Can you give us the choice to enable 128 or 256 world height ? It makes our server too much laggy

### ISSUE THREAD

**Issue by Misteboss** [pmmp/PocketMine-MP#198]
### Issue description
**_Suggestion_**
I think (if it's possible) you should add an option like "world.height : 128 or 256" so we will be able to add no load issues

**Comment by SOF3** [comment]
> It makes our server too much laggy 
Citation needed.

**Comment by dktapps** [comment]
The server performance issues with Anvil is nothing to do with build height; it's due to the YZX -> XZY data re-ordering on the main thread. I haven't gotten around to making it asynchronous yet.
