### ISSUE TITLE
EntityInventory/ArmorChangeEvents are spammed when loading inventory from NBT

### ISSUE THREAD

**Issue by dktapps** [pmmp/PocketMine-MP#1986]
### Issue description
This is strange and undesired behaviour. The inventory is not "changing" when loading items from save data.

**Comment by mal0ne-23** [comment]
credit to @Muqsit and I for pointing it out :D

**Comment by dktapps** [comment]
I'm thinking of implementing an InventoryViewer/Listener interface. This could then be solved by attaching a viewer after slots are set in the inventory, and then have the viewer call inventory change events.
