### ISSUE TITLE
Windows 10 Memory Info Values Is Not Setting (?)

### ISSUE THREAD

**Issue by Heroata** [pmmp/PocketMine-MP#1987]
### Issue description

- Expected result: Actually not an emergency patch as result. Need an info about it.
- Actual result: Maybe I have misunderstood about memory infos. But even my memory limit is 1024 (or 0 as unlimited IDK) in pocketmine.yml, its very low like 34-64 MB. Sometimes the server is overloading. Is the overloading happening on the Total virtual memory that i see in cmd or 1024 that i set in pocketmine.yml? If I misunderstood memory infos, how can I understand it?

### OS and versions

* PocketMine-MP: Build #671
* PHP: 7.2.0
* Server OS: Windows 10 Pro

### Crashdump, backtrace or other files

![image](https://user-images.githubusercontent.com/10375421/35731144-91efa0a8-0825-11e8-97ca-19ed8da50080.png)

**Comment by dktapps** [comment]
that's the maximum memory currently allocated, not its limit.

**Comment by Heroata** [comment]
Thanks. Then how is overloading happening?

**Comment by dktapps** [comment]
I have no idea what you're talking about. Also this is not an issue. Please take it to the forums.

**Comment by Heroata** [comment]
Cool then. The issue side of this issue was my misunderstanding about /status log. Thanks btw.
