### ISSUE TITLE
Entity save at wrong position

### ISSUE THREAD

**Issue by rdstonech** [pmmp/PocketMine-MP#1988]
### Issue description
Sometimes entity spawn at wrong position

But... It can their position can differ on different clients (for me the villager from the screen is at the right place)

### Steps to reproduce the issue

1. Spawn entity
2. unload level
3. load level

### OS and versions
* PocketMine-MP: https://github.com/pmmp/PocketMine-MP/commit/9014eb72e90f7f81c8188c793a01b55f3ff36a15
* PHP: https://github.com/pmmp/php-build-scripts/commit/27c476758888343cd628b0346c7e099fad05ab62
* Server OS: Ubuntu 16.04 x64

### Plugins
- Tested only with BedWars written by me, in it there is nothing associated with the entity, except for the spawn of a villager

### Crashdump, backtrace or other files
![7xffhuawr44](https://user-images.githubusercontent.com/31804440/35740122-dd394ab8-0844-11e8-8320-d8b7236df13f.jpg)

**Comment by dktapps** [comment]
Is this reproducible without plugins?

**Comment by rdstonech** [comment]
@dktapps Maybe, I can't test it. In the past game villager was generally far from the island, and at the same time we saw him both

**Comment by dktapps** [comment]
is your code public?

**Comment by rdstonech** [comment]
No, but I can say, that I create nbt with Entity::createBaseNBT (...). I registered entity with Entity::registerEntity (...);

**Comment by dktapps** [comment]
Unless this can be confirmed to be reproducible without plugins, this issue is invalid.
