### ISSUE TITLE
Player Data

### ISSUE THREAD

**Issue by LagHD** [pmmp/PocketMine-MP#1990]
### Issue description
A player is able to join server for first time, but after logging out of server, they can no longer join, it's stuck on locating server
- Expected result: Be able to join server again
- Actual result: Not able to join server after first time
### Steps to reproduce the issue

1: Join server
2: break something or pick up something
3: leave server
4: try joining again

### OS and versions

* PocketMine-MP: Most recent Jenkins Build
* PHP: 7
* Server OS:
* Game version: PE

### Crashdump, backtrace or other files
-no crash dumps, console doesn't show what's wrong

**Comment by dktapps** [comment]
Without knowing your PocketMine-MP version, OS, PHP, Client version, or plugins and how the issue occurred, the issue cannot begin to be solved.
A pre-formatted template is provided that shows the required information to begin to find, test and solve an issue.
Until the adequate template and information is provided, the issue will be closed; it may be reopened if you update the ticket with the correct template and required information.

[Contribution guidelines](https://github.com/pmmp/PocketMine-MP/blob/master/CONTRIBUTING.md)

**Comment by LagHD** [comment]
Server OS: CubedHost
PocketMine-MP: Dev Build #673

**Comment by robske110** [comment]
Server OS means Server Operating System (Windows, Linux, Mac...)
Also, your PHP version is too undescriptive.

**Comment by LagHD** [comment]
Server OS: Windows
Client Version: 1.2.7

**Comment by LagHD** [comment]
Bug fixed ty

**Comment by zKoz210** [comment]
It is a bug of the client, it is since time immemorial
