### ISSUE TITLE
Map Size (.mcapm)

### ISSUE THREAD

**Issue by IllegalerKater** [pmmp/PocketMine-MP#1992]
* PocketMine-MP: PocketMine-MP Build 674
* Server OS: Linux Debian
* Game version: PE/Win10

Problem: When I build something sometimes it get corrupted when I try to load this World on an other Server.
For me that means that I can not upload maps on my website which is a problem for me. I know it ist something with the .mcapm Files but idk what ._.

Below are useful Files :)

Is there any way to fix this annoying bug?

Attachments:
https://cathesda.de/downloads/console.log
https://cathesda.de/downloads/Spawn_0001.zip

**Comment by dktapps** [comment]
This is not a support forum. Please use the [forums](https://forums.pmmp.io) for support.

**Comment by IllegalerKater** [comment]
._. For me it is also a bug ...
