### ISSUE TITLE
Big values for motion can cause reverting

### ISSUE THREAD

**Issue by rdstonech** [pmmp/PocketMine-MP#1994]
### Issue description
If I set big values in setMotion (...), then I get move reverting and message in console: 
"*anyone* moved too fast, reverting movement"

### Steps to reproduce the issue

1. set motion to player with big values
2. see reverting

### OS and versions

* PocketMine-MP: https://github.com/pmmp/PocketMine-MP/commit/9014eb72e90f7f81c8188c793a01b55f3ff36a15
* PHP: php7.2.1
* Server OS: Ubuntu 16.04

### Plugins
- It's not reproducible without plugins, because pmmp don't have command for set motion to player

### Crashdump, backtrace or other files
"*anyone* moved too fast, reverting movement"

**Comment by rdstonech** [comment]
Why resolution is invalid? What's invalid? I really can't control it. Maybe you can add API for setting "revert" to any value

**Comment by dktapps** [comment]
It's a safety check. If you set the player motion to an absurdly high value then obviously it is going to trigger the safety check. This is a no-brainer.

**Comment by rdstonech** [comment]
I set this motion: new Vector3 (-3.7, 1.7, 3.7). Sometimes player revert.
