### ISSUE TITLE
Support for v0.15.90

### ISSUE THREAD

**Issue by LestaD** [pmmp/PocketMine-MP#20]
When when support for v0.15.90 will be added?

**Comment by robske110** [comment]
Move to here: https://github.com/pmmp/PocketMine-MP

**Comment by robske110** [comment]
It already is...

**Comment by LestaD** [comment]
@robske110 i tested on nexus 6p android 7.0 minecraft pe `v0.15.90 alpha build`
Do not connect with: `Server is outdated`

**Comment by dktapps** [comment]
0.15.90 is in beta, no official support is provided. Stop spamming.
