### ISSUE TITLE
[1.0] $chunk->getHighestBlock() console error.

### ISSUE THREAD

**Issue by Muqsit** [pmmp/PocketMine-MP#200]
### Issue description

Write a short description about the issue
While using Chunk::getHighestBlockAt(int $x, int $z), I get an error.

### Steps to reproduce the issue

Teleport a player to $x, (highest block at $x and $z in chunk $chunk), $z.

```php
//Player $issuer
$x = mt_rand(-25000,25000);
$z = mt_rand(-25000,25000);
$level = $this->getServer()->getDefaultLevel();
$chunk = $level->getChunk($issuer->getX() >> 4, $issuer->getZ() >> 4);
$y = $chunk->getHighestBlockAt($x, $z, false);//Generic Chunk issue, line 258, if arg 3 is true.
$issuer->teleport(new Position($x, $y + 1, $z, $level));
```

### OS and versions

* PocketMine-MP: e2bbb76
* PHP: 7.0.14
* Server OS: Ubuntu 14.04
* Game version: Win10

### Crashdump, backtrace or other files

* Uninitialized string offset: 850911 in /root/testify/src/pocketmine/level/format/generic/SubChunk.php on line 165.

**Comment by dktapps** [comment]
no wonder... you're not supposed to use those methods directly, they are internal.

Chunk block coordinates are always within the bounds of 0-15. The code isn't designed to be used like that. Use the provided API methods in Level for this.

**Comment by Muqsit** [comment]
I had used this since $level->getHighestBlockAt($x, $z) always returned 0. I'll try again anyways.
Thanks.
