### ISSUE TITLE
moving multiple items (by stack) to chests does not work

### ISSUE THREAD

**Issue by Alderander** [pmmp/PocketMine-MP#2005]
### Issue description

- Expected result: to move multiple items at once from the same stack
- Actual result: flips only one item each time

### Steps to reproduce the issue

1.  move item to any chest by stack
2. ...

### OS and versions

* PocketMine-MP: 1.7dev-698
* PHP: PHP-7.2-Linux-x86_64
* Server OS: Ubuntu 16.04.3 LTS
* Game version: PE 1.2.10

### Plugins
- Tested without plugins

**Comment by dktapps** [comment]
I'm pretty sure this is a client bug.
