### ISSUE TITLE
Using PlayerInventory->setItemInHand() during BlockBreakEvent later gets overridden

### ISSUE THREAD

**Issue by LolNova** [pmmp/PocketMine-MP#2010]
the issue there is because pocketmine sets your item in hand to the item you used with an increased item damage. It overrides your setItemInHand.

PocketMine-MP: PocketMine-MP version 1.7dev-698 "[REDACTED]" (API 3.0.0-ALPHA11)
PHP: 7.2
Game version: PE
Tested on a clean server with only the plugin and it still didn't work

**Comment by dktapps** [comment]
This is not a support forum. Please use the [forums](https://forums.pmmp.io) for plugin support.

**Comment by LolNova** [comment]
I know im just letting you know cause Muq said to post it here to inform you

**Comment by dktapps** [comment]
This issue is too undescriptive. Muqsit doesn't usually tell people to post here about plugin development issues. Please provide more detail.

**Comment by LolNova** [comment]
getItemInHand

If you try to get a tool in getItemInHand for the BlockBreakEvent it will not work as pocketmine sets your tool in hand to the tool you used with a increased damage so it overrides setiteminhand

**Comment by dktapps** [comment]
I'm not really sure what can be done about this - the code responsible for this issue doesn't know that the item in question is the player's held item. The best I can think of is some kind of equality check before setting the updated item back into the inventory.

Alternatively, a `BlockBreakEvent->setItem()` could be added to provide an alternative way to do this.

**Comment by LolNova** [comment]
I found a fix instead of using getItemInHand just use getItem()
