### ISSUE TITLE
IP block when Joining via Windows 10

### ISSUE THREAD

**Issue by tropiix** [pmmp/PocketMine-MP#2013]
Issue:
My friend hosts a mc:pe server on his android phone. When i tried to connect on it via the Minecraft Windows 10 version, it doesent work. In his console it says "Blocked *IP* for 5 seconds". It wont let me join the server on Windows 10.

* PocketMine-MP:1.7dev-708m / using version 3.0.0-alpha11 api for mc:pe v1.2.10 (protocoll version 201)
* PHP: 7.2
* Server OS: android / 1.2.10
* Game version: server hosted on android, i wanted to connect via minecraft windows 10 version

(Sorry i couldnt really understand the template, if this is wrong again then idk)

**Comment by dktapps** [comment]
Hosting on Android is not technically speaking supported, so I'm not surprised you're having problems.

Please enable debug output in pocketmine.yml (set `debug.level` to 2) and try and reproduce the issue.

**Comment by tropiix** [comment]
![img-20180212-wa0053](https://user-images.githubusercontent.com/31164636/36118120-3ad44c00-103c-11e8-93b5-79d8e98b8029.jpg)

**Comment by dktapps** [comment]
That's an issue with your PHP build (no IPv6 support).
