### ISSUE TITLE
ArmorInventory is not sent to player after ArmorInventory::setItem()

### ISSUE THREAD

**Issue by intagaming** [pmmp/PocketMine-MP#2014]
### Issue description

Players will have no armor until sendContents() is triggered

- Expected result: Players have armor
- Actual result: Players don't have armor

### Steps to reproduce the issue

1. I used ArmorInventory::setHelmet() to set a helmet to a player
2. Nothing will happen. Now trigger sendContents() to that player
3. Player will have armor now.

### OS and versions

* PocketMine-MP: 6e7a693
* PHP: 7.2
* Server OS: Windows 10
* Game version: Win10

### Plugins
- Test on a clean server without plugins: yes

### Crashdump, backtrace or other files

**Comment by dktapps** [comment]
> Test on a clean server without plugins: yes

> I used ArmorInventory::setHelmet() to set a helmet to a player
> Nothing will happen. Now trigger sendContents() to that player

make your mind up, are you using a plugin or not? If you are, please give example code to demonstrate.

**Comment by intagaming** [comment]
I'm kind of using plugins to run codes. Here I'm just changing one lines, that should work out without problem:

Please ignore plugin versions, all modified to be compatible:
![image](https://user-images.githubusercontent.com/16471365/36143507-db7538c6-10dd-11e8-9f63-083d7a942b2c.png)

I'm working with this chunk of codes:

```
$player->getPlayer()->removeAllEffects();
$inv = $player->getArmorInventory();
$player->getInventory()->clearAll();
$inv->clearAll();
foreach ($this->items as $type => $item) {
	if ((int)$type === $type) $player->getInventory()->addItem($item);
	elseif ($type === "helmet") $inv->setHelmet($item);
	elseif ($type === "chestplate") $inv->setChestplate($item);
	elseif ($type === "leggings") $inv->setLeggings($item);
	elseif ($type === "boots") $inv->setBoots($item);
}
var_dump("For issue:");
$inv->sendContents($player);
if (isset($this->data["commands"]) and is_array($this->data["commands"])) {
	foreach ($this->data["commands"] as $cmd) {
		$this->ak->getServer()->dispatchCommand(new ConsoleCommandSender(), str_replace("{player}", $player->getName(), $cmd));
	}
}
foreach ($this->effects as $effect) {
	$player->addEffect($effect);
}
```

Here's one without sendContents():
![image](https://user-images.githubusercontent.com/16471365/36143689-5ebee09c-10de-11e8-9ae3-a06875b4984a.png)
With sendContents():
![image](https://user-images.githubusercontent.com/16471365/36143749-8ebe99f4-10de-11e8-8956-d199f8490f3f.png)

**Comment by dktapps** [comment]
That's an odd one... I'm not sure why that doesn't crash the client. Regardless, it's fixed. Thanks!
