### ISSUE TITLE
[Suggestion] Please let PlayerPreLoginEvent implement Await

### ISSUE THREAD

**Issue by fuyutsuki** [pmmp/PocketMine-MP#2019]
### Issue description

The login plugin I'm trying to create calls webAPI with AsyncTask, but the player logs in before AsyncTask finishes running.  
I'd like you to implement await to keep players waiting before logging in.  

Or should I not call webAPI with AsyncTask?

### Steps to reproduce the issue

This is a suggestion. none

### OS and versions

* PocketMine-MP: githash 4a85311c5fcc6bdae17ec15982c766299a4a2bad
* PHP: 7.2.2
* Server OS: Win10Home
* Game version: Win10

### Plugins
none

### Crashdump, backtrace or other files
none

**Comment by dktapps** [comment]
#1881

**Comment by fuyutsuki** [comment]
Sorry, thank you.
