### ISSUE TITLE
Item frames are not protected by spawn protection

### ISSUE THREAD

**Issue by dktapps** [pmmp/PocketMine-MP#2025]
### Issue description
Players are able to remove items from item frames in spawn-protection radius.

Apparently "that's long-known though amongst server owners", which is irritating since nobody has ever bothered to report it. This bug might be old, but it is news to me.

Readers, if you find a bug, please actually report it. If you don't report bugs, bugs will not get fixed. Do not assume that it is already a known issue unless there isn't a report for it/it's not explicitly stated somewhere.

### OS and versions
* PocketMine-MP: https://github.com/pmmp/PocketMine-MP/commit/3b632c2870618ecf9c8c9c6af1781e28459fe820

**Comment by JackMD** [comment]
Thanks alot @dktapps for fixing this bug.
