### ISSUE TITLE
Tiemout by resource pack

### ISSUE THREAD

**Issue by ProCOmpTEAM** [pmmp/PocketMine-MP#2026]
**Disconnection:** my resource pack have 7.1MB size and I have this error 

* PocketMine-MP: latest
* PHP: 7.2
* Server OS: Ubuntu
* Game version: PE

![default](https://user-images.githubusercontent.com/24737193/36325841-1d26e128-136a-11e8-9544-5c040e9123ec.png)

**Comment by dktapps** [comment]
Without knowing your PocketMine-MP version, OS, PHP, Client version, or plugins and how the issue occurred, the issue cannot begin to be solved.
A pre-formatted template is provided that shows the required information to begin to find, test and solve an issue.
Until the adequate template and information is provided, the issue will be closed; it may be reopened if you update the ticket with the correct template and required information.

[Contribution guidelines](https://github.com/pmmp/PocketMine-MP/blob/master/CONTRIBUTING.md)
