### ISSUE TITLE
Timeout by resource pack

### ISSUE THREAD

**Issue by ProCOmpTEAM** [pmmp/PocketMine-MP#2027]
### Issue description

- Expected result: What were you expecting to happen?
- Actual result: What actually happened?

### Steps to reproduce the issue

1. updated resources
2. connected to server

If resourcepack(RP) have size < 4 MB - have connection
else timeout screen

in client i have RP downloading from 0 to 4 MB and client returned to main screen 

### OS and versions

* PocketMine-MP: 1.7DEV-717
* PHP: 7.2
* Server OS: ubuntu
* Game version: PE 1.2.10

### Plugins
- Test on a clean server without plugins: is the issue reproducible without any plugins loaded?
yes

If the issue is **not** reproducible without plugins:
- Have you asked for help on our forums before creating an issue?
- Can you provide sample, *minimal* reproducing code for the issue? If so, paste it in the bottom section
- Paste your list of plugins here (use the 'plugins' command in PocketMine-MP)

### Crashdump, backtrace or other files
- Do not paste crashdumps into an issue - please use our Crash Archive at https://crash.pmmp.io for submitting crash reports to not spam the issue tracker. Add links to your reports in the Crash Archive here.
- Please use gist or anything else to add other files and add links here 

* ...
![default](https://user-images.githubusercontent.com/24737193/36326384-ee7169d2-136b-11e8-9bec-8ed45a2da98b.png)

**Comment by dktapps** [comment]
Please enable debug mode and reproduce the bug, to get a stack trace.

A link to an example resource pack which causes this issue would also be helpful.

**Comment by ProCOmpTEAM** [comment]
From localhost i have not timeout screen(WIN10, 4GB), only vds(Ubuntu, 1GB)

**Comment by dktapps** [comment]
Closing due to not reproducible and lack of useful information.
