### ISSUE TITLE
Teleporting away from XP Orbs targetted on you freezes server

### ISSUE THREAD

**Issue by mal0ne-23** [pmmp/PocketMine-MP#2028]
### Issue Description

Teleporting away from an experience orb after it's targetted on you will cause motion to be excessively high, due to the orb checking for player distance every 20 ticks

- Expected result: What were you expecting to happen?
- Actual result: What actually happened?

### Steps to reproduce the issue

1. ...
2. ...

### OS and versions

* PocketMine-MP: since xp orbs
* PHP: 7.2.2
* Server OS: doesnt matter
* Game version: PE/Win10 (delete as appropriate)

intense tests were done to find out why my server was crashing. ask @dktapps 

i want my 🍪

**Comment by TheAz928** [comment]
Same thing happened to my server, couldn't find the reason. Thanks for finding this out
