### ISSUE TITLE
Color not Colour at BossEventPacket

### ISSUE THREAD

**Issue by sero583** [pmmp/PocketMine-MP#203]
Yeah, in constants you guys better should use always AE, instead of BE, or even better in general in pmmp.
Here it is still colour:
https://github.com/pmmp/PocketMine-MP/blob/81807ce67cac7cc18d56325975c292145e3cb6f2/src/pocketmine/network/protocol/BossEventPacket.php#L37

I know that isn't really a issue, but well.

**Comment by Muqsit** [comment]
UK FTW

**Comment by robske110** [comment]
Btw @dktapps is BE so he probably won't listen to that...

**Comment by SOF3** [comment]
Debate about dialects is very opinion-based and should not happen on this issue tracker.
