### ISSUE TITLE
Armor durability never goes down

### ISSUE THREAD

**Issue by mal0ne-23** [pmmp/PocketMine-MP#2032]
### Issue description

Armor durability won't go down. Damage a player and it stays full always.

- Expected result: What were you expecting to happen?
- Actual result: What actually happened?

### Steps to reproduce the issue

1. ...
2. ...

### OS and versions

* PocketMine-MP: eeaf75ac854f38a3afc5944fcae6be40b2129b0e
* PHP: 7.2.2
* Server OS: Ubuntu
* Game version: PE/Win10 (delete as appropriate)

### Plugins
- Test on a clean server without plugins: is the issue reproducible without any plugins loaded?

If the issue is **not** reproducible without plugins:
- Have you asked for help on our forums before creating an issue?
- Can you provide sample, *minimal* reproducing code for the issue? If so, paste it in the bottom section
- Paste your list of plugins here (use the 'plugins' command in PocketMine-MP)

### Crashdump, backtrace or other files
- Do not paste crashdumps into an issue - please use our Crash Archive at https://crash.pmmp.io for submitting crash reports to not spam the issue tracker. Add links to your reports in the Crash Archive here.
- Please use gist or anything else to add other files and add links here 

* ...

**Comment by dktapps** [comment]
This is not implemented yet.

**Comment by mal0ne-23** [comment]
Oh, I thought it has done that before.

**Comment by 95CivicSi** [comment]
It did until this commit
https://github.com/pmmp/PocketMine-MP/commit/efca9f0450fed2c660ca450718670ca71b2c0d82#diff-be0be6071c2c2f0abecaa7dd4e16e2f1

**Comment by dktapps** [comment]
No, it has never been implemented. @95CivicSi that commit has no bearing on armor whatsoever, unless you used a plugin to make it work. It's still yet to be implemented into the core code, as seen [here](https://github.com/pmmp/PocketMine-MP/blob/master/src/pocketmine/entity/Living.php#L443) (look at the documentation) and in subclasses overriding that method.

(P.S. Until recently armor did not even work for anything except PvP. The implementation is incomplete.)
