### ISSUE TITLE
Teleport issue

### ISSUE THREAD

**Issue by Creeperface01** [pmmp/PocketMine-MP#204]
### Issue description

Player are getting stuck in the air after teleport sometimes.

### Steps to reproduce the issue

1. Teleport player and then teleport them again
2. Teleport player and then send MovePlayerPacket with mode 0
3. Sometimes happen randomly

### OS and versions

* PocketMine-MP: idk what is current version
* PHP: 7
* Server OS: debian
* Game version: PE/Win10

**Comment by dktapps** [comment]
"idk what is current version" isn't particularly helpful. If you want us to help you solve your problem, please provide adequate information to help us solve it. I don't even know what branch you're using, it could be 0.16 or 1.0. Both no doubt have their respective issues.
