### ISSUE TITLE
Server freezing

### ISSUE THREAD

**Issue by TheAz928** [pmmp/PocketMine-MP#2040]
### Issue description
Server freezes sometime without any errors/backtrace

- Expected result: Server to run
- Actual result: Server froze

### Steps to reproduce the issue

1. ... Currently unknown, but it happens randomly when 30+ players joined 
2. ...

### OS and versions

* PocketMine-MP: https://github.com/pmmp/PocketMine-MP/commit/a3fa8adf4a21d5242fc0ab924a9685f67ba562c3
* PHP: 7.2
* Server OS: Linux/Ubuntu
* Game version: PE/Win10 (delete as appropriate)

### Plugins
- Has plugins, but these plugins were there since the ALPHA8 release

### Crashdump, backtrace or other files
- Do not paste crashdumps into an issue - please use our Crash Archive at https://crash.pmmp.io for submitting crash reports to not spam the issue tracker. Add links to your reports in the Crash Archive here.
- Please use gist or anything else to add other files and add links here 

* ...

**Comment by dktapps** [comment]
> Has plugins, but these plugins were there since the ALPHA8 release

what does this have to do with anything? Core changes require that plugins be updated also. Please **provide your plugin list**, as asked.

**Comment by dktapps** [comment]
As stated in the last issue you created, this issue lacks sufficient information to do anything about this issue. Please read [Contributing: Creating an issue](https://github.com/pmmp/PocketMine-MP/blob/master/CONTRIBUTING.md#creating-an-issue).

> **No generic issue reports.** For bugs, it is the issue author's responsibility to provide us an issue that is **trackable**, **debuggable**, **reproducible**, reported professionally and is an actual bug. 

> Valid issue reports must include instructions how to reproduce the issue or a crashdump/backtrace (unless the cause of the issue is obvious). 

> If you do not provide us with a summary or instructions on how to reproduce the issue, it will be treated as spam and will therefore be closed. 

> In simple words, if the issue cannot be properly confirmed to be valid or lacks required information, the issue will be closed until further information is provided.

You should therefore investigate this issue yourself (since you can reproduce it) and then create an issue once you have sufficient information to reproduce it. #2028 is an example of a helpful issue.
