### ISSUE TITLE
get player object using uuid

### ISSUE THREAD

**Issue by SalmonDE** [pmmp/PocketMine-MP#2047]
### Issue description

Since uuids should be the prefered way to identify players by now, I suggest adding a function to PocketMine, which would return the player object of an online player and expect an uuid as parameter. Similar to this one: [Server::getPlayer()](https://github.com/pmmp/PocketMine-MP/blob/aa11dbb928f6a0f6e298876beab655c2634c9b91/src/pocketmine/Server.php#L842)

- Expected result: What were you expecting to happen?
I was expecting to be able to get the corresponding player object of an uuid using the PocketMine API.

- Actual result: What actually happened?
I was not able to do so.
### Steps to reproduce the issue

No steps whatsoever can be provided, because I leave it up to you how it could be implemented.

### OS and versions

* PocketMine-MP: aa11dbb928f6a0f6e298876beab655c2634c9b91
* PHP: PHP 7.2.2
* Server OS: Linux Debian 9.3

### Plugins
- DevTools v1.12.9
- ManyWorlds v2.1.0
- EnderPearl v1.0.7
- PlutoBE v1.1.0

**Comment by Smarticles101** [comment]
Can I implement this? @dktapps
