### ISSUE TITLE
Resistance effect levels > 5 give the player absorption hearts when taking damage

### ISSUE THREAD

**Issue by zKoz210** [pmmp/PocketMine-MP#2052]
### Issue description
Resistance effect gives a lot of hearts

### Steps to reproduce the issue

1. /effect zKoz210 11 200 200
2. Get any damage (Jump with 5 blocks)

### OS and versions
* PocketMine-MP: https://github.com/pmmp/PocketMine-MP/commit/3de5e132a2edddfccb371332fa7bcccae1847f89
* PHP: 7.2.2
* Server OS: CentOS 7
* Game version: PE/Win10 

![image](https://user-images.githubusercontent.com/28255085/36616520-24079786-18f5-11e8-9d94-1b165ac6d36b.png)

**Comment by dktapps** [comment]
It would appear that this is caused by getFinalDamage() here being negative due to resistance effect. Any resistance level > 5 will cause this  bug. https://github.com/pmmp/PocketMine-MP/blob/master/src/pocketmine/entity/Living.php
