### ISSUE TITLE
Invalid item NBT string given

### ISSUE THREAD

**Issue by daniktheboss** [pmmp/PocketMine-MP#2066]
### Issue description
- Expected result: What were you expecting to happen?
run the server
- Actual result: What actually happened?
did not run the server

### Steps to reproduce the issue
run the server

### OS and versions
* PocketMine-MP: https://github.com/pmmp/PocketMine-MP/commit/28e601bbb967ea4ae214e1c1789c4629d0978472
* PHP: 7.2
* Server OS: windows 10

### Crashdump, backtrace or other files
[18:46:47] [Server thread/CRITICAL]: InvalidArgumentException: "Invalid item NBT string given, it could not be deserialized" (EXCEPTION) in "src/pocketmine/item/Item" at line 71

**Comment by dktapps** [comment]
Update your Composer dependencies.

**Comment by daniktheboss** [comment]
Ah OK, sorry. Thanks
