### ISSUE TITLE
[RakLibServer thread/NOTICE]: Blocked 45.79.134.18 for 5 seconds

### ISSUE THREAD

**Issue by austina1212** [pmmp/PocketMine-MP#2067]
So, I installed everything from http://pmmp.readthedocs.io/en/rtfd/installation.html onto my VPS properly and it loads up and everything but every like 2 seconds it says "[RakLibServer thread/NOTICE]: Blocked 45.79.134.18 for 5 seconds" any ideas?

**Comment by dktapps** [comment]
Without knowing your PocketMine-MP version, OS, PHP, Client version, or plugins and how the issue occurred, the issue cannot begin to be solved.
A pre-formatted template is provided that shows the required information to begin to find, test and solve an issue.
Until the adequate template and information is provided, the issue will be closed; it may be reopened if you update the ticket with the correct template and required information.

[Contribution guidelines](https://github.com/pmmp/PocketMine-MP/blob/master/CONTRIBUTING.md)
