### ISSUE TITLE
Translations

### ISSUE THREAD

**Issue by dktapps** [pmmp/PocketMine-MP#207]
### Issue description

Translation system sucks, no proper synchronization, generally a total mess.

### PRs requiring translations
#191 (critical bugfix, merged)

**Comment by dktapps** [comment]
TODO: rewrite everything to use sprintf, and add support for using vanilla language files

**Comment by zKoz210** [comment]
@dktapps I would like to see support `TranslationContainer()` in popups.

Because for send messages about the deaths I have to add extra code, which could be avoided in plugins.

```
if ($message instanceof TextContainer) {
    if ($message instanceof TranslationContainer) {
        $messageParams = $message->getParameters();
    }
    $message = $message->getText();
    $message = $this->plugin->getServer()->getLanguage()->translateString($message, $messageParams ?? []);
}
```

**Comment by fuyutsuki** [comment]
I tried to fix this issue, but rather than using `sprintf`, we can write it more concisely by using `vsprintf`.  
However, since `$onlyPrefix` can not be handled with only `vsprintf`, `str_replace` must be used after processing with `vsprintf`.  

eg.
```php
// input: string()"This is test %s"

$baseText = vsprintf($baseText, ["value"]);
var_dump($baseText);

// output: string()"This is test value"
```
Also, we need to support .lang files, not .ini files.

**Comment by SOF3** [comment]
This is not a real issue as it does not specify the exact problems or how to improve clearly. This sounds more like a project than an issue. If this is to be fixed, a motel clearly specified issue should be created (or create a project for this).
