### ISSUE TITLE
"fake" login

### ISSUE THREAD

**Issue by MrReskill** [pmmp/PocketMine-MP#2074]
### «Fake Login»

#When I join the server, it indicates in the console that I am connected but on the game I am on the loading screen and those on more than 20 minutes before being disconnected.

I have tried several times to reconnect etc and it still does not work ... I have access to other servers!

- Expected result: That my player connects normally
- Actual result: My player does not connect

1. Join the world

* PocketMine-MP:  LATEST (update w/ composer)
* PHP: 7.2
* Server OS: Debian
* Game version: Win10

No plugins/crashdumps

**Comment by dktapps** [comment]
Without knowing your PocketMine-MP version, OS, PHP, Client version, or plugins and how the issue occurred, the issue cannot begin to be solved.
A pre-formatted template is provided that shows the required information to begin to find, test and solve an issue.
Until the adequate template and information is provided, the issue will be closed; it may be reopened if you update the ticket with the correct template and required information.

[Contribution guidelines](https://github.com/pmmp/PocketMine-MP/blob/master/CONTRIBUTING.md)

**Comment by MrReskill** [comment]
Update PMMP version.

(Thx @Sandertv )

**Comment by MrReskill** [comment]
@dktapps

**Comment by MrReskill** [comment]
I wait answer @dktapps
