### ISSUE TITLE
EntityRegainHealthEvent bug or me?

### ISSUE THREAD

**Issue by Pab450** [pmmp/PocketMine-MP#2077]
### Issue description
[https://forums.pmmp.io/threads/entityregainhealthevent-bug-or-me.5383/](url)

EntityRegainHealthEvent can't be cancelled.

- Expected result: cancel the event
- Actual result: not cancelled

### Steps to reproduce the issue

`public function RegainHealth(EntityRegainHealthEvent $event){`
`$event->setCancelled(true);`
` }`

### OS and versions

* PocketMine-MP: PocketMine-MP 1.7dev-759
* PHP: 7.2.1
* Server OS: OS X MAC
* Game version: PE/Win10 

### Plugins

* ...

### Crashdump, backtrace or other files

* ...

**Comment by dktapps** [comment]
```php
	public function onHealth(EntityRegainHealthEvent $ev) : void{
		$ev->setCancelled();
		$e = $ev->getEntity();
		if($e instanceof \pocketmine\Player){
			$e->sendMessage("health: " . $e->getHealth());
		}
	}
```
This works as expected for me, but does not show correctly on the client. This is a known Minecraft client bug with client-sided regeneration (see #23, #157, and https://bugs.mojang.com/browse/MCPE-20507).

Sorry, but there's nothing we can do about this.
