### ISSUE TITLE
Doxygen document is broken

### ISSUE THREAD

**Issue by fuyutsuki** [pmmp/PocketMine-MP#2079]
### Issue description

The layout of the doxygen document built with jenkins is broken  
- Sidebar is not displayed

### Steps to reproduce the issue

Access [this site](https://jenkins.pmmp.io/job/PocketMine-MP-doc/doxygen/)

### OS and versions

* PocketMine-MP: unrelated
* PHP: unrelated
* Server OS: unrelated
* Game version: unrelated

### Plugins
none

### Crashdump, backtrace or other files
none

**Comment by dktapps** [comment]
It's because of the content security policy. It breaks every time Jenkins gets restarted. Likelihood is that it'll have to be hosted somewhere else in future.

**Comment by fuyutsuki** [comment]
I understand. Since it can be used by downloading the file, if seems to be known, there is no problem.

**Comment by fuyutsuki** [comment]
Should I close this?

**Comment by dktapps** [comment]
leave it open for now, the issue is not solved yet.

**Comment by fuyutsuki** [comment]
Ok, please fix it at your favorite timing. thank you 👍

**Comment by nathfreder** [comment]
@dktapps How about build it with Travis then publish to gh-pages here or on another repo
