### ISSUE TITLE
Item::fromString is not flexible enough

### ISSUE THREAD

**Issue by Sandertv** [pmmp/PocketMine-MP#208]
### Issue description

In a plugin I am working on, I use the Item::fromString() function. This however is not exactly compatible with the names of some of the item/block classes. Take wooden planks as an example. The class name is Planks, making it only gettable with fromString() if the string is 'planks' too. This does not work with the getName() function of Planks though, which will return something like 'Oak wooden planks', thus using fromString() on that will just return air and get you nowhere.

### Steps to reproduce the issue

1. Get the item name of wooden planks, for example $wooden_planks->getName()
2. Try using Item::fromString() on the string you get from that
3. Test the code and watch air flop out

### OS and versions

* PocketMine-MP: 6a066cdf312dc9ec4080f08b7749186a27b8694f
* PHP: 7.0
* Server OS: Any
* Game version: PE/Win10 

### Crashdump, backtrace or other files

* No errors of course, just air.

**Comment by dktapps** [comment]
Item::fromString() uses the Minecraft unique identifiers, it's intended to be this way.
