### ISSUE TITLE
Newest version of mc crashes server

### ISSUE THREAD

**Issue by brexmania123** [pmmp/PocketMine-MP#2086]
### Issue description

So Minecraft Bedrock edition updated earlier today, but when i try to join the server i help on the whole server just crashes. I looked at the crashdumps but nothing is appearing there. I tried erasing my own player data just in case

- Expected result: What were you expecting to happen?
I was expecting to join the server i help on
- Actual result: What actually happened?
Server shut down (running)
09.03 22:07:47 [Multicraft] Restarting crashed server in 5 seconds
09.03 22:07:47 [Multicraft] Server stopped
appears in the console, and then restarts the server. 
### Steps to reproduce the issue

1. ... run MCBE version 1.2.11
2. ... run server from envious
3. ... try to join server
4. ... server crashes
5. ... erase everything
6. ... try to join again
7. ... server crashes

### OS and versions

* PocketMine-MP: This server is running PocketMine-MP 1.7dev-743 「[REDACTED]」 implementing API version 3.0.0-ALPHA11 for Minecraft: PE v1.2.10 (protocol version 201)
* PHP: 7.2 i believe 
* Server OS: envious host 
* Game version: PE/Win10 (delete as appropriate) 1.2.11

### Plugins
- Test on a clean server without plugins: is the issue reproducible without any plugins loaded?
yes
If the issue is **not** reproducible without plugins:
- Have you asked for help on our forums before creating an issue?
- Can you provide sample, *minimal* reproducing code for the issue? If so, paste it in the bottom section
- Paste your list of plugins here (use the 'plugins' command in PocketMine-MP)

### Crashdump, backtrace or other files
- Do not paste crashdumps into an issue - please use our Crash Archive at https://crash.pmmp.io for submitting crash reports to not spam the issue tracker. Add links to your reports in the Crash Archive here.
- Please use gist or anything else to add other files and add links here 

* ...

**Comment by Muqsit** [comment]
When you say "... run server from envious", not everyone has a subscription to envoiushost, and it proves nothing other than it's a hosting issue and not PocketMine's. Anyway, do you happen to have a console log which covers the messages right before you get the "Restarting crashed server in 5 seconds"? Have you checked your crashdump folder?

**Comment by JackMD** [comment]
Might be a plugin issue. Plus you haven't filled out the template format
correctly.
