### ISSUE TITLE
korean commands which has more than one args is not working

### ISSUE THREAD

**Issue by djdisodo** [pmmp/PocketMine-MP#2087]
### Issue description

- Expected result: What were you expecting to happen?
- Actual result: What actually happened?

### Steps to reproduce the issue

1. make plugin (that uses korean command and uses more than one args)
2. load plugin and run korean command with two args
3. any message isn't showing

### OS and versions

* PocketMine-MP: 
* PHP: 7.2
* Server OS: Windows 10
* Game version: Win10

### Plugins
- Test on a clean server without plugins: is the issue reproducible without any plugins loaded?
DevTools v1.12.9, autofixapi v0.1.1-patch, BlockParticle v1, delivery vbeta, deloSkill v10.0.3.3-nonrelease, EconomyAPI v2.0.9, EssentialsPE v2.0.0, FloatingTexter v1.0, InfiniteBlock v0.9-alpha, Mana v3.2.0, MIE_Protector v1.0.2, NoAutoMining v0.0.1, NoExplode v1, PmChair v2.0, 1vs1 v0.0.4, Popper v1.0.0, SimpleArea v2.0.0.30, SItemDB v0.0.2, SkyWarsForPE v1.9.1 Delta F20, Slapper v1.3.7, SMarket v0.1.0, SOLOCodeMaster v빌드3, SOLOMotionBlock v빌드1, SOLOWarp v빌드10, updowngame v1.0.0, SteveWarn v1.0-alpha, ZMusicBox v3.0.0
(some plugins need purchase, but it will be same with no plugins)

### Crashdump, backtrace or other files
there was no errors....
* ...

**Comment by nnnlog** [comment]
This issue tracker is not a support forum. Please use the <a href="https://forums.pmmp.io/">forums</a> for support.

**Comment by djdisodo** [comment]
@nnnlog 엔로그님 한국분인거 아니까 한국어로 말하는겁니다
deloSkill말하는건데 구버전에선 한국어일때 명령어 옵션 갯수가 2개 이상이여도 작동이 됬었는데
현재 버전에선 무슨 방법을 써도 그게 작동이 안되는것 같습니다

In old version, when it was Korean, even if there were more than 2 command options, it worked fine.
In the current version, it does not seem to work even if I use any method

**Comment by nnnlog** [comment]
@djdisodo 포럼쓰세요, 이슈란은 질문하는 곳이 아닙니다.
Plz use forum, This issue tracker is not a support forum.
