### ISSUE TITLE
Players can't join, Raklib blocks them

### ISSUE THREAD

**Issue by PotatoeTrainYT** [pmmp/PocketMine-MP#2088]
### Issue description

When certain players try joining the server, it doesn't let them and in console it says they have been blocked for 5 seconds

- Expected result: What were you expecting to happen?
- Actual result: What actually happened?

### Steps to reproduce the issue

1. ... Make someone join the server i guess
2. ...

### OS and versions

* PocketMine-MP: 
* PHP:
* Server OS: 
* Game version: PE/Win10 (delete as appropriate)

This server is running PocketMine-MP 1.7dev-698 「[REDACTED]」 implementing API version 3.0.0-ALPHA11 for Minecraft: PE v1.2.10 (protocol version 201)

### Plugins
- Test on a clean server without plugins: is the issue reproducible without any plugins loaded?
Yep, it still happens with no plugins

If the issue is **not** reproducible without plugins:
- Have you asked for help on our forums before creating an issue?
- Can you provide sample, *minimal* reproducing code for the issue? If so, paste it in the bottom section
- Paste your list of plugins here (use the 'plugins' command in PocketMine-MP)

### Crashdump, backtrace or other files
- Do not paste crashdumps into an issue - please use our Crash Archive at https://crash.pmmp.io for submitting crash reports to not spam the issue tracker. Add links to your reports in the Crash Archive here.
- Please use gist or anything else to add other files and add links here 
``RakLibServer thread/NOTICE Blocked 45.79.134.18 for 5 seconds``
* ...

**Comment by dktapps** [comment]
You're using an outdated version. Update your version and try again.
