### ISSUE TITLE
Division by zero

### ISSUE THREAD

**Issue by kenygamer** [pmmp/PocketMine-MP#2092]
### Issue description

The console logs are showing up a division by zero error when **Explosion::explodeB()** is called. Also, **Explosion::A()** returns `false`

- Expected result: The explosion to ocurr.
- Actual result: Error is triggered in console logs, and nothing happens in the server.

### Steps to reproduce the issue

```php
$position = new \pocketmine\level\Position(0, 100, 0, \pocketmine\Server::getInstance()->getDefaultLevel());
$size = 10;

$explosion = new \pocketmine\level\Explosion($position, $size);
$explosion->explodeA(); //returns false
$explosion->explodeB(); //error is triggered here
```
### OS and versions
* PocketMine-MP: 1.7dev-743 「[REDACTED]」 implementing API version 3.0.0-ALPHA11 for Minecraft: PE v1.2.10 (protocol version 201)
* PHP: 7.2.0RC3
* Server OS: Linux Ubuntu 17.10.3
* Game version: PE

**Comment by SOF3** [comment]
Please show the exact error.

**Comment by kenygamer** [comment]
Updated issue description.

**Comment by SOF3** [comment]
You did not pass in $size = 10 into Explosion constructor. You passed in $size = 0. This is your plugin's error.
