### ISSUE TITLE
Inventory: Items dropped cannot be tracked through events in resetCraftingGridType() 

### ISSUE THREAD

**Issue by zKoz210** [pmmp/PocketMine-MP#2098]
### Issue description

- Expected result: Prevent items from falling out of the creative, if there is not enough space
- Actual result: There is no way to limit the drop of item.

### Steps to reproduce the issue

1. Open inventory and add a lot of items
![image](https://user-images.githubusercontent.com/28255085/37319464-3265ccec-2680-11e8-85f5-fe10a915712f.png)

2. Close the inventory
![image](https://user-images.githubusercontent.com/28255085/37319469-3b9c7efa-2680-11e8-9df7-f238fe5de97c.png)

It is assumed that there should be some event: https://github.com/pmmp/PocketMine-MP/blob/master/src/pocketmine/Player.php#L3788
### OS and versions
* PocketMine-MP: https://github.com/pmmp/PocketMine-MP/commit/8a0414f306e2a840029542a7fc8a672442cd6023
* PHP: 7.2.2
* Server OS: CentOS 7
* Game version: PE/Win10

**Comment by zKoz210** [comment]
This is certainly great, but then the players on my server get stuff from creative and give ordinary players.

**Comment by dktapps** [comment]
This is intentionally irreversible because the crafting inventory is destroyed after closing the inventory. Try working with ItemSpawnEvent instead.

**Comment by zKoz210** [comment]
However, you handle an event where inventory is full and can be tracked through DropItemAction. This is a strange logic than the action with full inventory is different from the current one?
