### ISSUE TITLE
Updated PHP compiler

### ISSUE THREAD

**Issue by legoboy0215** [pmmp/PocketMine-MP#21]
This is not an issue. Sorry, but I have no other way of telling you guys. You should create a new compile script repo for the updated compile scripts. I fixed the script, maybe just use it?

https://github.com/legoboy0215/php-compile-script/blob/master/compile.sh

I tested it and it works, if @dktapps is asking 👍 .

**Comment by dktapps** [comment]
@legoboy0215 what was broken?

**Comment by SOF3** [comment]
> Sorry, but I have no other way of telling you guys.

Please read the [contribution guidelines](CONTRIBUTING.md). Enough information are provided there.

**Comment by legoboy0215** [comment]
@dktapps @SOF3 A libpng version. And some paths were kinda wrong.
