### ISSUE TITLE
Redstone glowing make server freeze

### ISSUE THREAD

**Issue by KennFatt** [pmmp/PocketMine-MP#2104]
### Issue description

Breaking or even just touching with Redstone Ore make server freeze and disconnecting all players.

- Expected result: Glowing and breaking as normal.
- Actual result: Just touching on it, server freeze and then all players got disconnected.

### Steps to reproduce the issue

1. Fine or place some Redstone Ore
2. Touching with any items or break it
3. Freeze till server restart

### OS and versions

* PocketMine-MP: [ddc9dca8b483e21a2be8e336043759f387a361ae](https://github.com/pmmp/PocketMine-MP/commit/ddc9dca8b483e21a2be8e336043759f387a361ae)
* PHP: 7.2.3
* Server OS: Windows 10 and Ubuntu 16.04 64-bit
* Game version: PE/Win10 (any game version)

### Plugins
- With or without any plugins.

### Crashdump, backtrace or other files
- There is no backtrace or crashdump for this issue. On Windows 10, it's show a dialog like (CLI Program not responding -> Closing program) then the console showing message 'Press any key to continue...'
* ...

**Comment by KennFatt** [comment]
**Additional Information(s)**
World Format: Anvil

**Comment by KennFatt** [comment]
![image](https://user-images.githubusercontent.com/10755895/37434783-67a817c2-2813-11e8-866c-b493b2915324.png)

**Comment by dktapps** [comment]
Does the bug occur prior to 86eee429bb6c22336cdc69793374dbe7494bd024 ?

**Comment by KennFatt** [comment]
@dktapps it might be. I've debug this issue by putting some messages inside onUpdate() function of GlowingRedstone but the message does'nt occur to the log and nothing changes.

Then I try to remove some setBlock() statements inside of RedStoneOre block (So, there is no setBlock(GlowingRedstone); on it).

And everything is okay. So, I used that hacky way for now.

I thought it was an infinite loop or repeating task and affected to resources usage.

_Sent from my Redmi Note 3 using [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_

**Comment by dktapps** [comment]
The culprit is here: https://github.com/pmmp/PocketMine-MP/blob/master/src/pocketmine/block/RedstoneOre.php#L57

GlowingRedstoneOre extends from RedstoneOre but doesn't override this method. The result is an infinite loop of set-block and block updates, leading to this crash.

This bug was introduced in https://github.com/pmmp/PocketMine-MP/commit/86eee429bb6c22336cdc69793374dbe7494bd024.
