### ISSUE TITLE
Only commands aliases shown in available commands.

### ISSUE THREAD

**Issue by Yexeed** [pmmp/PocketMine-MP#2106]
Expected:
Not only aliases shown in command aliases
Got:
Only aliases shown in command aliases
Main thread:
https://forums.pmmp.io/threads/why-only-command-aliases-shows-in-availablecommands.5393/
Steps to reproduce:
1. Create command and set aliases of it using plugin.yml or use new class
2. Try to type full command in Minecraft command prompt. 
3. You will not see it full name in available commands 

P.s. Sorry if I wasn't used the issue template bcs my GitHub Android client doesn't support issue templates

**Comment by dktapps** [comment]
This is quite a stupid bug indeed. It appears to be the client doing strange things with aliases overwriting names which the server doesn't account for.

When an alias is given in vanilla, the aliases don't sit next to the normal command name as you would expect. It instead _removes_ the original and installs the aliases instead. Thus the aliases have to include the original command name for this to work correctly. (See https://gist.github.com/dktapps/050fd9b985d993bead412c6934b9538a#file-commands_decoded-json-L4305-L4306 for an example vanilla dump.)

I'll add a fix for this to PocketMine-MP later. I don't know whether this would be considered a client bug or not.
