### ISSUE TITLE
Parsing docComment error for priority leaves trailing trimmable characters

### ISSUE THREAD

**Issue by KennFatt** [pmmp/PocketMine-MP#2110]
### Issue description

There is an error while parsing docComment.

I'm trying to declare **@priority** by this way:

> /**
     * @priority HIGHEST
     * @param PlayerIllegalMoveEvent $event
     */

and HIGHEST also known as [here](https://github.com/pmmp/PocketMine-MP/blob/49fbbea7bf552574606f67ce0b1e7ffecb76e894/src/pocketmine/event/EventPriority.php#L67).
As we can see, HIGHEST has 7 characters (H, I, G, H , E, S, T) **Remember this point**.

- Expected result: Dumping '$tags["priority"]' must return valid string length and string value.
- Actual result: Invalid string value, **i.e. "HIGHEST " or "LOW " and so on**. It contains 1 space at the end, then string length are invalid.

### Steps to reproduce the issue

1. Just fix the regular expression.

### OS and versions

* PocketMine-MP: [49fbbea](https://github.com/pmmp/PocketMine-MP/commit/49fbbea7bf552574606f67ce0b1e7ffecb76e894)
* PHP: 7.2.3
* Server OS: Windows 10 64-bit
* Game version: PE and Win10

### Plugins
- Specter (for testing), DevTools, and 1 plugin (Only contains Listener).

### Crashdump, backtrace or other files
For HIGHEST priority:
`
pocketmine\plugin\PluginException: "Event handler specter\Specter->onIllegalMove() declares invalid/unknown priority "HIGHEST "" (EXCEPTION) in "src/pocketmine/plugin
luginManager" at line 739
`

For LOW priority:
`pocketmine\plugin\PluginException: "Event handler specter\Specter->onIllegalMove() declares invalid/unknown priority "LOW "" (EXCEPTION) in "src/pocketmine/plugin/Plu
ginManager" at line 739`

* ...

**Comment by dktapps** [comment]
Interesting. I wonder if this bug was also in effect prior to subevent-handler merge.

**Comment by KennFatt** [comment]
I thought it was not a 'space' character there, because I've just tried to replace it with empty character and still error.
