### ISSUE TITLE
Level::getSafeSpawn() doesnt giving a really safe spawn

### ISSUE THREAD

**Issue by Yexeed** [pmmp/PocketMine-MP#2112]
### Issue description

I'm trying to do a random teleportation so i want to teleport players on random X and Z and on normal floor (grass or something)

- Expected result: Player has been teleported on safe spawn
- Actual result: Player has been teleported on unsafe spawn (ex. under blocks or in high air)

### Steps to reproduce the issue

1. Here's the code i used:
 ```
$x = mt_rand(-1500, 1500);
$z = mt_rand(-1500, 1500);
$pos = $sender->getLevel()->getSafeSpawn(new Vector3($x, 30, $z));
$sender->teleport($pos); 
```
Result: i've been teleported under blocks 
![image](https://user-images.githubusercontent.com/32373441/37774038-2fd677a2-2df0-11e8-955a-fd869dc1ced6.png)

2. Another code example:
```
$x = mt_rand(-1500, 1500);
$z = mt_rand(-1500, 1500);
$pos = $sender->getLevel()->getSafeSpawn(new Vector3($x, 80, $z));
$sender->teleport($pos); 
```
Result: i've been telepored in high air
![image](https://user-images.githubusercontent.com/32373441/37774118-6be6c5b2-2df0-11e8-85db-dd136012cf2b.png)

### OS and versions
* PocketMine-MP: 1.7-dev865
* PHP: 7.2.2 (downloaded from dktapps appveyor)
* Server OS: Win 10
* Game version: Win10

### Plugins
- Only one plugin, which teleporting players on random position

**Comment by dktapps** [comment]
This is because you are trying to teleport into unloaded chunks. getSafeSpawn() only operates on loaded chunks. All other times, it simply returns the position you gave it to start with.

**Comment by Yexeed** [comment]
thx

**Comment by Moadassam** [comment]
$x = mt_rand(-1500, 1500);
$y = mt_rand(1, 256);
$z = mt_rand(-1500, 1500);
$pos = $sender->getLevel()->getSafeSpawn(new Vector3($x, $y, $z));
$sender->teleport($pos);

try that ;)
