### ISSUE TITLE
Painting ticking performance issue

### ISSUE THREAD

**Issue by zKoz210** [pmmp/PocketMine-MP#2117]
### Issue description
Using a paintings greatly impairs the performance of the server. It's too much load for such basic things, it needs to be optimized.

### Steps to reproduce the issue

1. Place 5, 10, 20, 30, 40 and 50 pictures and watch the performance

### OS and versions
* PocketMine-MP: https://github.com/pmmp/PocketMine-MP/commit/2b37b4a65970f81d9bfb2689d738af33144d8271
* PHP: 7.2.3
* Server OS: CentOS 7
* Game version: PE/Win10

### Plugins
- Test on a clean server without plugins

### Crashdump, backtrace or other files
Timings link: http://timings.pmmp.io/?url=p%2F7QtkY9N8Mw

On a normal server where players place the painting in many chunks, this situation is much worse
**64 paitings:**
![image](https://user-images.githubusercontent.com/28255085/37872954-e5e2260a-301a-11e8-8047-964275bee664.png)

**Comment by Sandertv** [comment]
Do you have timings to assure it's actually the paintings causing this?

**Comment by zKoz210** [comment]
@Sandertv Sorry, can't provide a link to the timings at the moment, only a screenshot 
![image](https://user-images.githubusercontent.com/28255085/37873009-25178d64-301c-11e8-9710-86046db71208.png)

**Comment by dktapps** [comment]
That's not a CPU leak, just a performance issue.

**Comment by dktapps** [comment]
https://github.com/pmmp/PocketMine-MP/blob/master/src/pocketmine/entity/object/Painting.php#L95-L97

**Comment by dktapps** [comment]
The cause of this is not what I expected. I'm not entirely sure why this bug is in effect at all.
