### ISSUE TITLE
You can't get a paiting, or other entity using the middle mouse button

### ISSUE THREAD

**Issue by zKoz210** [pmmp/PocketMine-MP#2119]
### Issue description
You can't get a paiting, or other entity using the middle mouse button. Also we can not get the egg essence, such as villager.

### Steps to reproduce the issue

1. Join to server and place painting 
2. Hover over the painting and click the middle mouse button

### OS and versions
* PocketMine-MP: https://github.com/pmmp/PocketMine-MP/commit/2b37b4a65970f81d9bfb2689d738af33144d8271
* PHP: 7.2.3
* Server OS: CentOS 7
* Game version: PE/Win10

### Plugins
- Test on a clean server without plugins

**Comment by dktapps** [comment]
This is an un-implemented feature, not a bug.
