### ISSUE TITLE
Knock back not working correctly

### ISSUE THREAD

**Issue by TheShinPin** [pmmp/PocketMine-MP#2128]
So when a player keeps hitting another player, and they are in the air, once in a while they get teleported back to the group (almost like an anti fly protection) not sure if this is a bug with pocket mine or just a server problem. please let me know.

- Expected result: What were you expecting to happen?
the player to be knocked back normally 
- Actual result: What actually happened?
knockback gets messed up/canceled

### Steps to reproduce the issue

1. ... have a player hit another player over and over fast enough so they are in the air, it may take a few hits for the bug to happen, and there was even a few times where i thought it was gone but it wasn't. its noticeable mainly from the players perspective who is getting hit, but you can also see it from the player who is hitting.

### OS and versions
Pocketmine-MP 1.7dev-902 ALPHA11

### Plugins
- Test on a clean server without plugins: is the issue reproducible without any plugins loaded?
Yes

**Comment by Megalunchbox** [comment]
disable flight in server.properties
