### ISSUE TITLE
Blocks bad ids

### ISSUE THREAD

**Issue by MrReskill** [pmmp/PocketMine-MP#2129]
Issue description

When I put a block is the bad that appears

    Expected result: Normally the appropriate block must appear
    Actual result: The blocks are not good example: craft table = redstone

Steps to reproduce the issue

    Get any blocks on inventory
    Place it in the map
    Check the result, this is not the good blocks !

OS and versions

    PocketMine-MP: 960a04d
    PHP: 7.2.1
    Server OS: Windows 10
    Game version: Both

Plugins

    Test on a clean server without plugins: is the issue reproducible without any plugins loaded?

There are no plugins loaded.
If the issue is not reproducible without plugins:

    Have you asked for help on our forums before creating an issue?
    Can you provide sample, minimal reproducing code for the issue? If so, paste it in the bottom section
    Paste your list of plugins here (use the 'plugins' command in PocketMine-MP)

Crashdump, backtrace or other files

    Do not paste crashdumps into an issue - please use our Crash Archive at https://crash.pmmp.io for submitting crash reports to not spam the issue tracker. Add links to your reports in the Crash Archive here.
    Please use gist or anything else to add other files and add links here

    ...

**Comment by dktapps** [comment]
You're using an unsupported branch.
