### ISSUE TITLE
Door Damage

### ISSUE THREAD

**Issue by BlawoHD** [pmmp/PocketMine-MP#213]
### Issue description

If you go through a door you get hurt

### Steps to reproduce the issue

1. ...
2. ...

### OS and versions

* PocketMine-MP: 1.6.2dev-#61
* PHP: -
* Server OS: 
* Game version: PE/Win10 (delete as appropriate)

### Crashdump, backtrace or other files

* ...

**Comment by JackNoordhuis** [comment]
Please check the issue tracker before opening more issues :) All these are relegated to the same issue: #119, #169, #181

**Comment by dktapps** [comment]
^
