### ISSUE TITLE
Nametag + Killbox going down.

### ISSUE THREAD

**Issue by Enrick3344** [pmmp/PocketMine-MP#2135]
### Issue description
Nametags sometimes go down to the lower body of the skin and brings the kill box with him! Which means when we try to hit a player that his nametag is down to his pants can't be hit upper than the tag.

### Steps to reproduce the issue

1. I've noticed it happends when someone dies and respawn but not confirmed and does not happend each time.

### OS and versions

* PocketMine-MP: 3134fa2
* PHP: 7.2.3
* Server OS: Ubuntu 16.04 LTS
* Game version: PE/Win10

### Crashdump, backtrace or other files
![capture](https://user-images.githubusercontent.com/24282136/38326638-46388bc4-3814-11e8-8bbf-a5342d3383a9.PNG)

**Comment by dktapps** [comment]
... ugh.

**Comment by dktapps** [comment]
I can't reproduce this. Please provide more information.

**Comment by dktapps** [comment]
never mind, I reproduced it... it appears to happen when the player clicks respawn before the death animation ends. I'm not very clear why that happens. It looks like this may be a client-sided bug.

**Comment by Enrick3344** [comment]
Okay! if you need more informations let me know.

**Comment by dktapps** [comment]
Did this happen prior to MCPE version 1.2.13?

**Comment by Enrick3344** [comment]
No never happend before! I've only seen it happend with the new version

**Comment by Enrick3344** [comment]
Can It be causing also that my pure chat plugin after a while doesnt show any rank next to the nametag?
