### ISSUE TITLE
Latest Build PHAR 1.2.14

### ISSUE THREAD

**Issue by JustinTDR** [pmmp/PocketMine-MP#2139]
When I start the server it will be fine for five minutes.
After a few minutes goes by my console get's this error and restarts the server over again.
--
05.04 20:56:57 [Server] Server thread/ERROR Error while unloading a chunk: Return value of pocketmine\tile\Sign::getLine() must be of the type string, null returned
05.04 20:56:57 [Server] Server thread/CRITICAL TypeError: "Return value of pocketmine\tile\Sign::getLine() must be of the type string, null returned" (EXCEPTION) in "src/pocketmine/tile/Sign" at line 124
05.04 20:56:57 [Server] Server thread/DEBUG #0 src/pocketmine/tile/Sign(67): pocketmine\tile\Sign->getLine(integer 3)
05.04 20:56:57 [Server] Server thread/DEBUG #1 src/pocketmine/level/format/io/region/Anvil(78): pocketmine\tile\Sign->saveNBT()
05.04 20:56:57 [Server] Server thread/DEBUG #2 src/pocketmine/level/format/io/region/McRegion(374): pocketmine\level\format\io\region\Anvil->nbtSerialize(pocketmine\level\format\Chunk object)
05.04 20:56:57 [Server] Server thread/DEBUG #3 src/pocketmine/level/format/io/BaseLevelProvider(132): pocketmine\level\format\io\region\McRegion->writeChunk(pocketmine\level\format\Chunk object)
05.04 20:56:57 [Server] Server thread/DEBUG #4 src/pocketmine/level/Level(2762): pocketmine\level\format\io\BaseLevelProvider->saveChunk(pocketmine\level\format\Chunk object)
05.04 20:56:57 [Server] Server thread/DEBUG #5 src/pocketmine/level/Level(440): pocketmine\level\Level->unloadChunk(integer 9, integer 6, boolean )
05.04 20:56:57 [Server] Server thread/DEBUG #6 src/pocketmine/level/Level(576): pocketmine\level\Level->close()
05.04 20:56:57 [Server] Server thread/DEBUG #7 src/pocketmine/Server(969): pocketmine\level\Level->unload(boolean 1)
05.04 20:56:57 [Server] Server thread/DEBUG #8 src/pocketmine/Server(2032): pocketmine\Server->unloadLevel(pocketmine\level\Level object, boolean 1)
05.04 20:56:57 [Server] Server thread/DEBUG #9 src/pocketmine/Server(2230): pocketmine\Server->forceShutdown()
05.04 20:56:57 [Server] Server thread/DEBUG #10 src/pocketmine/Server(2165): pocketmine\Server->crashDump()
05.04 20:56:57 [Server] Server thread/DEBUG #11 src/pocketmine/Server(1703): pocketmine\Server->exceptionHandler(ErrorException object)
05.04 20:56:57 [Server] Server thread/DEBUG #12 src/pocketmine/PocketMine(305): pocketmine\Server->__construct(BaseClassLoader object, pocketmine\utils\MainLogger object, string /, string /plugins/)
05.04 20:56:57 [Server] Server thread/DEBUG #13 /custom-php7.2.phar(1): require(string phar:///custom-php7.2.phar/src/pocketmine/PocketMine.php)

**Comment by TDMidkwhatisxd** [comment]
1.2.14 is not a beta build?
