### ISSUE TITLE
Items don't burn when thrown in fire

### ISSUE THREAD

**Issue by killer549** [pmmp/PocketMine-MP#2143]
### Issue description

I tried to burn some blocks and items in fire. The items disappeared but when I stood up on the block where the flames were existing, all the items returned to my inventory.

- Expected result: burned items disappear and never be held up again
- Actual result: Items returned back to the inventory.

### Steps to reproduce the issue

1. Using flint and steal, lit some fire.
2. Throw some items from your inventory in the fire
3. turn off the fire using your hand or even walk into the fire.
4. check your inventory, you will find all the items you've just thrown

### OS and versions

* PocketMine-MP: 1.7dev-920 for Minecraft: PE [REDACTED] (protocol version 3.0.0-ALPHA11 commit: 08d8adae5bb5c4fb328b2453bc0a45143e1ab2cc
* PHP: 7.2.3
* Server OS: Windows 10
* Game version: PE/Win10 (delete as appropriate)

### Plugins
- Test on a clean server without plugins: is the issue reproducible without any plugins loaded?
yes
If the issue is **not** reproducible without plugins:
- Have you asked for help on our forums before creating an issue?
- Can you provide sample, *minimal* reproducing code for the issue? If so, paste it in the bottom section
- Paste your list of plugins here (use the 'plugins' command in PocketMine-MP)

### Crashdump, backtrace or other files
- Do not paste crashdumps into an issue - please use our Crash Archive at https://crash.pmmp.io for submitting crash reports to not spam the issue tracker. Add links to your reports in the Crash Archive here.
- Please use gist or anything else to add other files and add links here

* ...

**Comment by killer549** [comment]
I've also noticed that items will disappear forever if the server stopped or shut down

**Comment by daniktheboss** [comment]
I can confirm. If you drop items, and tap with flint and steel, the items will disappear but when you walk over you collect them.

**Comment by dktapps** [comment]
This is the result of a combination of bugs:

- Items don't have FIRE_TICK damage applied
- Fire sets things on fire for 8 seconds. Fire-tick damage doesn't kick in until 1 second after the initial ignition, but the item is getting its fire time reset every tick, so fire-tick damage never applies to it.
