### ISSUE TITLE
My server crashes after a few minutes..

### ISSUE THREAD

**Issue by GoldenExorcist** [pmmp/PocketMine-MP#2152]
### Issue description
I opened my server and after about 3 minutes it crashes for some reason.. i'm not sure if it only happens to me but it isn't the plugins.

- Expected result: I was expecting the server to run until i closed it myself.
- Actual result: It crashed after only a few minutes..

### Steps to reproduce the issue

1. start the server.
2. wait a while..
3. it crashes.

### OS and versions

* PocketMine-MP: PocketMine-MP 1.7dev-941 for Minecraft: PE [REDACTED] (protocol version 3.0.0-ALPHA12) Git commit: 532269a484417967549b8dd918156ae23b707f49
* PHP: 7.2.4
* Server OS: Windows 10
* Game version: PE/Win10 (delete as appropriate)

### Plugins
- Test on a clean server without plugins: is the issue reproducible without any plugins loaded?
Yes
If the issue is **not** reproducible without plugins:
- Have you asked for help on our forums before creating an issue?
- Can you provide sample, *minimal* reproducing code for the issue? If so, paste it in the bottom section
- Paste your list of plugins here (use the 'plugins' command in PocketMine-MP)

### Crashdump, backtrace or other files
- Do not paste crashdumps into an issue - please use our Crash Archive at https://crash.pmmp.io for submitting crash reports to not spam the issue tracker. Add links to your reports in the Crash Archive here.
- Please use gist or anything else to add other files and add links here
https://crash.pmmp.io/view/307224
* ...

**Comment by TheAz928** [comment]
Test without plugins, to be clear, THE ERROR IS BECAUSE OF YOUR PLUGINS.
My server works fine with 30 plugins ... (Yes, I'm using the latest commit build)

**Comment by robske110** [comment]
no, the error is not because of his plugins, he doesn't even have any. Did you read the crashdump/crasharchive link? Please refrain from making useless comments when he explicitly stated that he tested without plugins: 

> Test on a clean server without plugins: is the issue reproducible without any plugins loaded?
> Yes

**Comment by kenygamer** [comment]
Could be a corrupted sign, try resetting your tiles.

**Comment by teracube** [comment]
no problem on my server with latest build dev 941 and 30 plugins.

**Comment by dktapps** [comment]
Likely what is happening here is [this](https://github.com/pmmp/PocketMine-MP/blob/master/src/pocketmine/tile/Sign.php#L45) is splitting a string containing less than 3 newlines. This could happen if the world is corrupted, or if some format change in MCPE changed how the lines are stored.

A copy of the subject world would be useful for debugging.

**Comment by GoldenExorcist** [comment]
[level.zip](https://github.com/pmmp/PocketMine-MP/files/1925794/level.zip)
