### ISSUE TITLE
Changing packets that will be batched.

### ISSUE THREAD

**Issue by Frago9876543210** [pmmp/PocketMine-MP#2153]
### Issue description
- Expected result: Opportunity changing LevelEventPacket in DataPacketSendEvent and other packets.
- Actual result: Instead, I get a BatchPacket. 

### Steps to reproduce the issue
1. Use the code I gave below.
2. Join the server and start breaking the blocks, but you will not see anything.

### Plugins
Minamal code to reproduce this issue:
```php
class Main extends PluginBase implements Listener{

	public function onEnable() : void{
		$this->getServer()->getPluginManager()->registerEvents($this, $this);
	}

	public function onDataPacketSend(DataPacketSendEvent $e) : void{
		$pk = $e->getPacket();
		if($pk instanceof LevelEventPacket){
			$this->getLogger()->notice(__METHOD__);
			//However, it is not called
		}
	}
}

**Comment by dktapps** [comment]
#1521

**Comment by Frago9876543210** [comment]
Then which way can I solve this?

**Comment by Frago9876543210** [comment]
> Events are not called like you expect for performance reasons

Why not send to the event only those packets that require it?

**Comment by dktapps** [comment]
There's no distinction between a batch and any other packet. Even if there was, it wouldn't solve this issue.

The real problem is that there is no way to intercept broadcasted packets, as described in #1521 .

**Comment by Frago9876543210** [comment]
But still it's rather silly to decode each ButchPacket and then encode it again.

**Comment by dktapps** [comment]
that's a workaround, not a solution. Besides, in a lot of cases you are actually modifying pre-encoded packets anyway. Messing around with packets at this layer is never going to work well.
