### ISSUE TITLE
Elytra Inventory Issues

### ISSUE THREAD

**Issue by Haxley** [pmmp/PocketMine-MP#2155]
### Issue description

-Elytra, if stacked, cannot be split.
-Equipped Elytra causes all inventory changes to revert. 

- Expected result: What were you expecting to happen?
Expected Elytra stacks to be split. Expected inventory to work when Elytra equiped.
- Actual result: What actually happened?
Elytra, if stacked, cannot be split.
Equipped Elytra causes all inventory changes to revert. 

### Steps to reproduce the issue

1. ... Add Elytra to Inventory
2. ... Test splitting
3. ... Equip Elytra
4. ... Test changing inventory. 

### OS and versions

* PocketMine-MP: 
* PHP: 7.2
* Server OS: Linux
* Game version: Both PE & Win10

### Plugins
- Test on a clean server without plugins: is the issue reproducible without any plugins loaded?
Tested Clean

If the issue is **not** reproducible without plugins:
- Have you asked for help on our forums before creating an issue?
- Can you provide sample, *minimal* reproducing code for the issue? If so, paste it in the bottom section
- Paste your list of plugins here (use the 'plugins' command in PocketMine-MP)

### Crashdump, backtrace or other files
- Do not paste crashdumps into an issue - please use our Crash Archive at https://crash.pmmp.io for submitting crash reports to not spam the issue tracker. Add links to your reports in the Crash Archive here.
- Please use gist or anything else to add other files and add links here
No Crashdump
* ...

**Comment by Muqsit** [comment]
Elytra is not implemented.
