### ISSUE TITLE
Bow is held weird.

### ISSUE THREAD

**Issue by TheShinPin** [pmmp/PocketMine-MP#2168]
The bow is held very oddly, and takes up alot of space on the screen.

- Expected result: What were you expecting to happen?
The bow to be held normally, on the right side of the screen
- Actual result: What actually happened?
Item is held off to the left.

### Steps to reproduce the issue

1. Get a bow and try to aim with it.
### OS and versions
commit ae0c1c185fdfac46b6f5cf7c9f3e91a1870c92ea 

- Test on a clean server without plugins: is the issue reproducible without any plugins loaded?
Yes.

**Comment by dktapps** [comment]
You haven't provided sufficient information - I can't reproduce this on beta. Fill out the template fully, don't delete parts of it. 

There are issue reports on https://bugs.mojang.com for bugs like this, so check there as well.
