### ISSUE TITLE
Unbanning dead players on hardcore server does not work

### ISSUE THREAD

**Issue by dktapps** [pmmp/PocketMine-MP#2175]
### Issue description
As reported by @Muqsit , dead players will get re-banned from the server if they get unbanned and try to join the server again. This occurs because the player's saved health is zero, causing the respawn sequence to be executed again, causing the player to get banned again.

### Steps to reproduce the issue
- die on a hardcore server
- quit
- get unbanned
- try to join again

### OS and versions

* PocketMine-MP: https://github.com/pmmp/PocketMine-MP/commit/2a0a2134d135808075e1ed5087926e5f2190cd19

**Comment by dktapps** [comment]
This is rather a tricky bug to fix because of how messed up respawning is right now - #1567 is a key showstopper here.

**Comment by MalakasPlayzMC** [comment]
You can check on PlayerPreLoginEvent if the hardcore is enabled && if the player's health is <= 0. If it is you will do @rmdir("players/".$event->getPlayer()->getName().".dat");

No hacks or tricks

**Comment by MalakasPlayzMC** [comment]
Can't you do this when you load the player data?

**Comment by Muqsit** [comment]
@MalakasPlayzMC I don't think you know how hardcore servers work. The player data is still very needed. It contains the player's skindata and other things. Deleting it would be too much to lose aside from it being a hacky measure.

**Comment by FreeGamingHere** [comment]
Uhh, I din;t know that. Maybe healing the player instead of removing the stats?

**Comment by FreeGamingHere** [comment]
didn't*
@Muqsit

**Comment by dktapps** [comment]
Relates to #1567
