### ISSUE TITLE
Permission Not working

### ISSUE THREAD

**Issue by xXNiceAssasinl0** [pmmp/PocketMine-MP#2188]
### Issue description
When I set player to permission it still say you do not have permission 

### Steps to reproduce the issue

1. Join Server
2. Type /setuperm <player> permission

**Comment by dktapps** [comment]
this isn't a plugin support forum, /setuperm isn't a core command...

**Comment by xXNiceAssasinl0** [comment]
I know @dktapps but when I set permission it wouldn’t work is it pmmp problem or PurePerms?

**Comment by dktapps** [comment]
> this isn't a plugin support forum

_drops mic_
