### ISSUE TITLE
Kick messages are not being shown to the client

### ISSUE THREAD

**Issue by kenygamer** [pmmp/PocketMine-MP#2196]
### Issue description
When a player gets kicked, no message is shown to the client. Instead, the client is sent to the server list menu, making it impossible to determine the reason of the kick.

- Expected result: Kick message being shown to the client.
- Actual result: Client is sent to the server list menu.

### OS and versions
* PocketMine-MP: 1.7dev-1000
* PHP: 7.2.0
* Server OS: Ubuntu 16.04.3 LTS
* Game version: PE

### Plugins
- Test on a clean server without plugins: is the issue reproducible without any plugins loaded?
Yes, it is.

**Comment by dktapps** [comment]
this is a client bug, and you're running an outdated version.

**Comment by kenygamer** [comment]
@dktapps So the issue will clearly not be resolved updating the version?
