### ISSUE TITLE
Minecraft Clinet cannot detect server status when server is turned on

### ISSUE THREAD

**Issue by Tommy131** [pmmp/PocketMine-MP#2199]
### Issue description
Minecraft Clinet cannot detect server status when server is turned on.
v1.2.13 can detect server's Motd, but now v1.4.0 cannot.
branch #5552704

### OS and versions
* PocketMine-MP: 3.0.0-ALPHA12 v1.4.0
* PHP: 7.2.0
* Server OS: Windows 10 1803
* Game version: Win10  v1.4.0

### Plugins
No Plugins loaded.

**Comment by PeratX** [comment]
Typo: Clinet

**Comment by Tommy131** [comment]
mmp,草泥马死全家
