### ISSUE TITLE
Missing doors

### ISSUE THREAD

**Issue by GamakCZ** [pmmp/PocketMine-MP#220]
### Issue description

Missing doors in inventory

### Steps to reproduce the issue

1. Join to server
2. Open your inventory

### OS and versions

* PocketMine-MP:
* PHP: 7
* Server OS: PocketMine  - don t know (when iam write in console /version: pocketmine.server.info.extended)
* Game version: Debain 7

### Crashdump, backtrace or other files

-

**Comment by dktapps** [comment]
Read existing issues before opening a new one. #167
