### ISSUE TITLE
Resource packs not working

### ISSUE THREAD

**Issue by puppyfacetreat** [pmmp/PocketMine-MP#2201]
### Issue description

Recource packs wont load on a server and will be skipped due to directory recource packs currently unsupported.

- Expected result: Load the resource pack successfully.
- Actual result: Pack Activation was Skipped.

### Steps to reproduce the issue

1. Import a recource pack.
2. add its name to the recource_packs.yml
3. Restart the server

### OS and versions

* PocketMine-MP: PocketMine-MP 1.7dev-1001 「[REDACTED]
* PHP: dev-1001
* Server OS: 
* Game version: PE/Win10 (delete as appropriate)

### Plugins
- Test on a clean server without plugins: is the issue reproducible without any plugins loaded? 
Yes.

If the issue is **not** reproducible without plugins:
- Have you asked for help on our forums before creating an issue?
No.
- Can you provide sample, *minimal* reproducing code for the issue? If so, paste it in the bottom section

[Server thread/WARNING]: Skipped resource entry SpawnPainting due to directory resource packs currently unsupported

- Paste your list of plugins here (use the 'plugins' command in PocketMine-MP)

### Crashdump, backtrace or other files
- Do not paste crashdumps into an issue - please use our Crash Archive at https://crash.pmmp.io for submitting crash reports to not spam the issue tracker. Add links to your reports in the Crash Archive here.
- Please use gist or anything else to add other files and add links here

* ...

**Comment by Sandertv** [comment]
Please use https://forums.pmmp.io for support questions. PocketMine currently only supports zipped resource packs with a .zip or .mcpack extension.
