### ISSUE TITLE
The falling block is not displayed

### ISSUE THREAD

**Issue by MrDoni98** [pmmp/PocketMine-MP#2203]
### Issue description
The falling_block(entity) is not displayed

### Steps to reproduce the issue

1. Place the anvil on the wall
2. See how she falls

### OS and versions
* PocketMine-MP:  PocketMine-MP 1.7dev-1036「 [REDACTED]」, version API 3.0.0-ALPHA12 for Minecraft: PE v1.4.0 (protocol version 261)
* PHP: 7.2
* Server OS: Ubuntu 16.04.4 LTS 

### Plugins
- Test on a clean server without plugins: is the issue reproducible without any plugins loaded?
The problem is reproduced without plugins.

**Comment by TheAz928** [comment]
I think you need to create tiles on every block on the falling path...

**Comment by dktapps** [comment]
This is fixed by 1.5, but 1.5 sucks...
