### ISSUE TITLE
Stopped when two people access Xbox One Minecraft

### ISSUE THREAD

**Issue by ryanmoongit** [pmmp/PocketMine-MP#2205]
**Issue description**

I installed pmmp using the docker.
Two people connected to pmmp using lan game on xbox. One was normally connected, but the other one was not connected. In "xbox one s", two people can play two people at the same time. However, the pmmp server has only one connection.

**Steps to reproduce the issue**
1. Run PMMP
2. Connecting two xbox pads
3. Running xbox minecraft
4. Connect PMMP server from "frend> lan game" in xbox minecraft to main pad
5. Select "A" on the other pad to connect minecraft
6. Stop at "Creating World> Creating Terrain ..."

**OS and versions**
* PocketMine-MP : 8c1c8f3
* PHP : PHP 7.2 distribution from PMMP
* Server OS : ubuntu:latest
* Game version : XBox One S Minecraft
* docker : https://hub.docker.com/r/cscheide/pocketmine-mp/
* This server is running PocketMine-MP 1.7dev-100
1 「[REDACTED]」 implementing API version 3.0.0-ALPHA12 for Minecraft: PE v1.4.0
 (protocol version 261)       

**Plugins**

Test on a clean server without plugins: is the issue reproducible without any plugins loaded?
The problem is reproduced without plugins.

**Crashdump, backtrace or other files**

[Server thread/DEBUG]: Unhandled SubClientLoginPacket received from VerticalBanjo95: 0x5e0001ade2023a0300007b22636861696e223a5b2265794a68624763694f694a46557a4d344e434973496e673164534936496b31495758644651566c4953323961535870714d454e4255566c47537a5246525546445355525a5a304646636e4e7863334249566b395961327079536a6c6e62337035616a56544d31567661457859634441784e465a425.....

**Comment by dktapps** [comment]
Sorry, split screen is unsupported. There are no plans to implement it because of the technical penalties it would involve (things that would harm performance).
