### ISSUE TITLE
No Click limitation?

### ISSUE THREAD

**Issue by Tumeden** [pmmp/PocketMine-MP#2209]
### Issue description

No click limitation/Multiple hit registers I've been finding this issue a lot lately, whether its during a vanilla PVP experience or with plugins which require you to interact with signs or other objects.
You can click **as fast as you like** and the hits **will all register**, yet the animation can't keep up.  It's really bizarre and makes ios/android _nearly impossible_ to keep up to a windows 10 user in combat.

On top of this, any interactions with a plugin with a command shop sign for a great example, a single click will register multiple times.

If for example i click 'shop' to BUY something for 10 dollars,  a **single click** would make me tap that sign 3-6 times consistently. 

### Steps to reproduce the issue

1. Click fast during pvp (can hit up to **50cps+** with autoclicker which breaks game sound)
or dont
2. Click any type of interactive object, or 'shop' with a plugin - a single click registers 3-6 times consistently.

### OS and versions

All recent versions of PMMP,  I've used stable versions as well as experimental.
I didn't list the version numbers because It's been consistent over at least the past 100 builds.

### Plugins
- Test on a clean server without plugins: is the issue reproducible without any plugins loaded?
Yes, there's no click limiter. :( 

* ...

**Comment by dktapps** [comment]
it's down to a bug in the client. Try right-click-hold, it will have the same spammy effect.

There is a limitation for hits pee aecond on PvP, but not for block clicks (because it would interfere with building). Please search for or create an issue on https://bugs.mojang.com.
