### ISSUE TITLE
Chunks to binary

### ISSUE THREAD

**Issue by Nickleog** [pmmp/PocketMine-MP#222]
### Issue description

I am getting this error
Error: "Call to undefined method pocketmine\level\format\generic\GenericChunk::toBinary()" (EXCEPTION) 
Why was the method removed?
### Steps to reproduce the issue

1. ...
2. ...

### OS and versions

* PocketMine-MP: 25b9581
* PHP: 7.0.10
* Server OS: Linux
* Game version: PE

### Crashdump, backtrace or other files

* ...

**Comment by dktapps** [comment]
That method isn't intended for plugin use, it's a core method used for chunk saving. It was removed in API 3.0.0-ALPHA1 due to implementation of a new in-memory chunk format.

**Comment by Nickleog** [comment]
yea i see where you are going with that, fastSerialize() and fastDeserialize() is the new method, naughty boy
