### ISSUE TITLE
Client Intermittently Crashes after World Transfer

### ISSUE THREAD

**Issue by 95CivicSi** [pmmp/PocketMine-MP#2222]
### Issue description

When players are transferred from one world to another, the client will occasionally crash while loading chunks for the new world. Seems to be more prominent when looking around immediately after transfer.

- Expected result: What were you expecting to happen?  Players should be able to transfer to different worlds and stay connected while loading chunks in the new area.
- Actual result: What actually happened?  Clients intermittently crash during chunk loading.

### Steps to reproduce the issue

1. Log onto the server.
2. Transfer to a different world (using plugin)
3. Bug intermittently happens when first loading chunks around the player.

### OS and versions

* PocketMine-MP: `PocketMine-MP version 1.7dev-1001`
* ~~PHP:  PHP 7.0.30-0ubuntu0.16.04.1 (cli) ( NTS )~~
* PHP:  `PHP 7.2.2 (cli) (built: Feb  4 2018 10:31:23) ( ZTS )`

* Server OS: Ubuntu 16.0.4
* Game version: PE/Win10 (both)

### Plugins
- Test on a clean server without plugins: is the issue reproducible without any plugins loaded?
No, a plugin is required to transfer the player from one world to another.

If the issue is **not** reproducible without plugins:
- Have you asked for help on our forums before creating an issue? N
- Can you provide sample, *minimal* reproducing code for the issue? If so, paste it in the bottom section Y
- Paste your list of plugins here (use the 'plugins' command in PocketMine-MP)
TestWorldTransfer v0.0.1 (Code provided below)

### Crashdump, backtrace or other files
- Do not paste crashdumps into an issue - please use our Crash Archive at https://crash.pmmp.io for submitting crash reports to not spam the issue tracker. Add links to your reports in the Crash Archive here.
- Please use gist or anything else to add other files and add links here

 ```
<?php

namespace FiberglassCivic\TestWorldTransfer;

use pocketmine\Player;
use pocketmine\plugin\PluginBase;
use pocketmine\command\CommandSender;
use pocketmine\command\Command;

class Main extends PluginBase{
	

	public function onCommand(CommandSender $sender, Command $command, string $label, array $args) : bool{
		switch($command->getName()){
			case "go":
				if(isset($args[0]) and $sender instanceof Player){
					if(($level = $this->getServer()->getLevelByName($args[0]))){
						$pos = $level->getSafeSpawn();
						$sender->teleport($pos);
					}
				}
				return true;
			default:
				return false;
		}
	}
}
```

**Comment by dktapps** [comment]
> PHP 7.0.30-0ubuntu0.16.04.1 (cli) ( NTS )

PM requires PHP 7.2 ZTS, this looks wrong...

**Comment by 95CivicSi** [comment]
You are correct, I forgot to include the ./ when I ran the command.  Actual version is 
`PHP 7.2.2 (cli) (built: Feb  4 2018 10:31:23) ( ZTS )`
OP has been updated to include the corrected information.

**Comment by lukeeey** [comment]
Do you mean immediately?

**Comment by SonsaYT04** [comment]
Same as [this](https://github.com/pmmp/PocketMine-MP/issues/2159) ??

**Comment by 95CivicSi** [comment]
Yes @SonsaYT04, except it doesn't matter for me what the world types are.  I first noticed this problem on a SkyBlock server that I was running where player's islands are in their own world.  It became more prominent recently when I started working on a new mini-game that teleports players to arenas in different worlds.  During my initial testing many of the players (myself included) repeatedly crashed when being teleported to an arena.  

It seems that the problem is lessened if the player stays in the first world long enough to load all of the chunks around them within their view distance before teleporting.

**Comment by Muqsit** [comment]
@95CivicSi does that world have a "void" generator?

**Comment by 95CivicSi** [comment]
Settings from pocketmine.yml for `worlds` in the test example.
```
worlds:
 #These settings will override the generator set in server.properties and allows loading multiple levels
 #Example:
 #world:
 # seed: 404
 # generator: FLAT:2;7,59x1,3x3,2;1;decoration(treecount=80 grasscount=45)
 world2: []
 world3: []
```

The minigame server I am testing on has the following:
```
worlds:
 #These settings will override the generator set in server.properties and allows loading multiple levels
 #Example:
 #world:
 # seed: 404
 # generator: FLAT:2;7,59x1,3x3,2;1;decoration(treecount=80 grasscount=45)
 lobby:
   generator: FLAT:2;0;1;
 arena1:
   generator: FLAT:2;0;1;
 arena2:
   generator: FLAT:2;0;1;
```

**Comment by JackMD** [comment]
I have also faced this issue where when teleporting to different worlds while chunks aren't loaded and looking around causes the client to crash.

**Comment by Muqsit** [comment]
Hmm, I'm sensing a pattern here. I'm using the following generation technique:
```php
class VoidGenerator extends Generator{
    public function generateChunk(int $chunkX, int $chunkZ) : void
    {
    }

    public function populateChunk(int $chunkX, int $chunkZ) : void
    {
    }
}
```
and have faced a client crash today while teleporting FROM the world using the VoidGenerator to the default world using the default generator (with no `pocketmine.yml` mods).

**Comment by SonsaYT04** [comment]
@95CivicSi it happens to me when I use win10, but for pe it works fine.

**Comment by JackMD** [comment]
@SonsaYT04 I have faced this on Android.

**Comment by Kjenium** [comment]
i also have this problem on my server. It happens when i transfer from a world to another. It happens more frequently on win10 client. I don't know how to fix

**Comment by TWZeroK** [comment]
Same problem on any device.
NEED HELP!

**Comment by MrDoni98** [comment]
same problem

**Comment by dktapps** [comment]
I'm going to close this as WF since it's a bug in the client. It's also triggered by large block updates and chunk regeneration. It's been reported to Mojang, but there's nothing else we can do about this. My recommendation is to have your multi worlds separated by large distances (like we used to have to do in the 1.0 and 1.1 days).

**Comment by 95CivicSi** [comment]
Thanks.  That's helpful information.

**Comment by dktapps** [comment]
It seems that 1.8 addresses this problem, the crash hasn't been seen in a while.
