### ISSUE TITLE
Cannot get the inventory of a monster

### ISSUE THREAD

**Issue by FreeGamingHere** [pmmp/PocketMine-MP#2223]
### Issue description

I cannot get the inventory of a monster. I can do that with players. I know this is not implemented yet, but it would be nice to be. Zombies, skeletons, wither skeletons and other monsters can be armored in vanilla Minecraft BE, if I have the difficulty to the max level.

- Expected result: Make the monster get equiped with armor and get an item
- Actual result: The monster did not get equiped with armor and did not get the item

### Steps to reproduce the issue

1. Spawn a Wither Skeleton mob (example)
2. Try $mob->getInventory()

### OS and versions

* PocketMine-MP: 1.7dev #1112
* PHP: 7.2RC3
* Server OS: Linux
* Game version: Both are same but I tested it with PE

### Plugins
WSkeletonBotPvP v1.0.0 
(The plugin name I tried that)

### Crashdump, backtrace or other files
Nope
* ...

**Comment by JackMD** [comment]
Shouldn't it be `getArmorInventory()`?

**Comment by FreeGamingHere** [comment]
Nope, it is not a support request. It is a feature request. And @JackMD I said an example, I know that this has changed since 3.0.0-ALPHA7

**Comment by dktapps** [comment]
your code is wrong and you didn't read the issue template before opening an issue. If you want to armour a mob you already have the capability to do so.
