### ISSUE TITLE
Incorrect display of items in water

### ISSUE THREAD

**Issue by zKoz210** [pmmp/PocketMine-MP#2227]
### Issue description
From version 1.4 things in the water have changed their logic and now items are displayed incorrectly.

### Steps to reproduce the issue
1. Throw the item into the water and wait until it rises up
2. You can't pick it up because the server thinks it is at the bottom

### OS and versions
* PocketMine-MP: https://github.com/pmmp/PocketMine-MP/commit/47742d74c8dbd68a968fccb1e15fff52fa7ff73d
* PHP: 7.2
* Server OS: CentOS 7
* Game version: PE/Win10

### Crashdump, backtrace or other files
![image](https://user-images.githubusercontent.com/28255085/41193571-9862d2ac-6c16-11e8-8a3b-61909e938d50.png)

![image](https://user-images.githubusercontent.com/28255085/41193586-bd781962-6c16-11e8-96df-a2a78ff2e841.png)

**Comment by dktapps** [comment]
Water physics in general haven't been implemented yet, so this is just an additional pain in the ass. Items have always been problematic.

You can work around this for now by setting the `DATA_FLAG_NO_AI` generic flag on item entities to disable the client-sided floating.

**Comment by zKoz210** [comment]
Are you planning on adding this flag as a "hack"?

**Comment by dktapps** [comment]
I haven't decided yet. The problem with setting this flag is that it makes item movement stuttery (no interpolation), so that's not good for appearance's sake. The correct fix is to implement proper water physics, but that's going to have to wait for now.

**Comment by dktapps** [comment]
I found a hack for this which can be used to prevent the floating without the jittering. Fix coming soon.
