### ISSUE TITLE
Incorrect display of some characters in the terminal

### ISSUE THREAD

**Issue by zKoz210** [pmmp/PocketMine-MP#2228]
### Issue description
I have long noticed that when you delete russian characters in the console message is displayed incorrectly and it is wildly annoying, more than sure that this problem occurs with other languages. If I was wrong or this is a php problem, then I apologize in advance.

### Steps to reproduce the issue
1. Write on any message, for example "say Привет!!!!!"
![image](https://user-images.githubusercontent.com/28255085/41200468-95c710d4-6cad-11e8-94e0-1ae7d4c57b76.png)

2. Tap to "backspace" and remove a few characters, for example "say Привет!"
![image](https://user-images.githubusercontent.com/28255085/41200470-9df8cebe-6cad-11e8-9059-fdc660a9e8e7.png)

3. Result:
![image](https://user-images.githubusercontent.com/28255085/41200476-a841132c-6cad-11e8-9b3b-ec5f803adadb.png)

CentOS 7 (Same steps):
![image](https://user-images.githubusercontent.com/28255085/41200494-1e236aa4-6cae-11e8-8c4e-ab2b12c9be65.png)

I highlighted in red the new changed text, "ЗА?" it was before the removal.
![image](https://user-images.githubusercontent.com/28255085/41200609-98b39382-6cb0-11e8-8cf2-f00fd18a885e.png)

###  How it works on different operating systems:
You may notice that messages are not received by the console at all unless they contain special characters. (Example with command /say)
![image](https://user-images.githubusercontent.com/28255085/41200570-a98cd23c-6caf-11e8-95ec-701de5e311fc.png) (Only Windows, CentOS 7 works with this remarkably)

**Windows 10** displays a message that will ACTUALLY be displayed to players.
**CentOS 7** displays the message correctly after the change, but players will see only part of the message

### OS and versions
* PocketMine-MP: https://github.com/pmmp/PocketMine-MP/commit/89643ff9afc2cd102ebc365226d097a67b91d6f8
* PHP: 7.2
* Server OS: CentOs7, Windows 10

**Comment by zKoz210** [comment]
And what about CentOS? Here is an example, copy it to the terminal and then delete the words before the first space and send the message

Ex: "Привет, как дела? Зачем мне это?" => "Привет, как дела? Зачем"

Remains a residual message that looks strange
![image](https://user-images.githubusercontent.com/28255085/41200698-581a9440-6cb2-11e8-8942-781f36590fa3.png)

**Comment by dktapps** [comment]
I haven't checked linux yet. This is a very peculiar bug.

For the Windows problem, `fgets()` is returning a string which has those characters zeroed out already, and I have no idea why or how to prevent it doing that. It does not look like it's a PM-caused issue, but it's an issue nonetheless. I'm trying to find similar bugs.

**Comment by dktapps** [comment]
```
php -r 'var_dump(fgets(STDIN));'
say Привет!!!!!
string(17) "say       !!!!!
"
```
I have to conclude that the Windows issue is a PHP bug of some form, since it also happens with the predefined `STDIN` constant.

**Comment by dktapps** [comment]
I cannot reproduce the linux bug. I expect that has something to do with your terminal.

**Comment by zKoz210** [comment]
I have now specially downloaded the newest version of PuTTY - 0.70

![image](https://user-images.githubusercontent.com/28255085/41200947-d986216c-6cb6-11e8-82f5-c2debe97978a.png)

**Comment by Frago9876543210** [comment]
I have same on Debian 9.4

**Comment by SOF3** [comment]
Please be sure to distinguish the problem in your terminal and the issue in PHP. For example, try running `cat` and type Russian characters to see if they can echo out correctly.

**Comment by Frago9876543210** [comment]
@SOF3 Yes, this problem exists even if use ```cat```

**Comment by nnnlog** [comment]
So is Korean language

**Comment by SOF3** [comment]
@Frago9876543210 then it is your terminal's problem. Nothing to do with PHP or PocketMine at all.

**Comment by zKoz210** [comment]
If this is a problem with our terminal, what are you using?

**Comment by Efudix** [comment]
I only use windows 7

**Comment by Efudix** [comment]
I only use window 7
