### ISSUE TITLE
Dropped items don't appear to save with the world

### ISSUE THREAD

**Issue by dktapps** [pmmp/PocketMine-MP#223]
### Issue description

Dropped items aren't saved. This affects all branches, not just mcpe-1.0

### Steps to reproduce the issue

1. drop an item
2. save the world
3. restart the server
4. dropped items aren't there anymore

### OS and versions

* PocketMine-MP: 88e36ed
* PHP: 7.0.13 ARM 32-bit
* Server OS: Android
* Game version: PE/Win10

**Comment by Muqsit** [comment]
Yeah, I think this *feature* wasn't ever implemented.
