### ISSUE TITLE
AddEntityPacket has null value for entityUniqueId

### ISSUE THREAD

**Issue by djdisodo** [pmmp/PocketMine-MP#2232]
### Issue description

`[10:53:02] [Server thread/CRITICAL]: TypeError: "Argument 1 passed to pocketmine\network\mcpe\NetworkBinaryStream::putEntityUniqueId() must be of the type integer, null given, called in phar:///root/seed/PocketMine-MP.phar/src/pocketmine/network/mcpe/protocol/AddEntityPacket.php on line 93" (EXCEPTION) in "src/pocketmine/network/mcpe/NetworkBinaryStream" at line 286`

- Expected result: What were you expecting to happen?
- Actual result: What actually happened?

### Steps to reproduce the issue
i used this code to make lightning
`$pk = new AddEntityPacket();
            $pk->type = 93;
            $pk->entityRuntimeId = Entity::$entityCount++;
            $pk->metadata = [];
            $motion = new Vector3(0, 0, 0);
            $pk->motion = $motion;
            $pk->position = $pos;
            $this->lightningPacket = $pk;
			foreach ( $pos->getLevel ()->getPlayers () as $p ) {
				$p->dataPacket ( $pk );
			}`
### OS and versions

* PocketMine-MP: This server is running PocketMine-MP 1.7dev-1136 「[REDACTED]」 implementing API version 3.0.0-ALPHA12 for Minecraft: PE v1.4.0 (protocol version 261)
* PHP:
* Server OS:linux
* Game version: PE

### Plugins
- Test on a clean server without plugins: is the issue reproducible without any plugins loaded?

If the issue is **not** reproducible without plugins:
- Have you asked for help on our forums before creating an issue?
- Can you provide sample, *minimal* reproducing code for the issue? If so, paste it in the bottom section
- Paste your list of plugins here (use the 'plugins' command in PocketMine-MP)

### Crashdump, backtrace or other files
- Do not paste crashdumps into an issue - please use our Crash Archive at https://crash.pmmp.io for submitting crash reports to not spam the issue tracker. Add links to your reports in the Crash Archive here.
- Please use gist or anything else to add other files and add links here

* ...

**Comment by dktapps** [comment]
then your code is defective... https://github.com/pmmp/PocketMine-MP/blob/master/src/pocketmine/network/mcpe/protocol/AddEntityPacket.php#L93

this is not a support forum, please do not use it as one.
