### ISSUE TITLE
"logged out due to Outdated server!"

### ISSUE THREAD

**Issue by benyanke** [pmmp/PocketMine-MP#224]
### Issue description

Setup the server using the install script

### Steps to reproduce the issue

1. Started Server
2. Tried to log in with android client
3. Received log message:
`[14:58:48] [Server thread/INFO]: [/10.10.10.129:19132] logged out due to Outdated server!`

### OS and versions

* PocketMine-MP:
* PHP:
* Server OS:
* Game version: PE/Win10 (delete as appropriate)

### Crashdump, backtrace or other files

* ...

**Comment by robske110** [comment]
This is no issue, you installed the wrong version, please refer to the forums ( forums.pmmp.io )

**Comment by dktapps** [comment]
Please remember to specify what client version you're using. If it's MCPE 1.0, there is no stable build available yet.
