### ISSUE TITLE
is this PocketMine-MP bug?

### ISSUE THREAD

**Issue by treehousemc1** [pmmp/PocketMine-MP#2240]
13.06 12:30:06 [Server] Server thread/CRITICAL Could not pass event 'pocketmine\event\server\DataPacketReceiveEvent' to 'EggWars v1.0.0-beta1': Argument 1 passed to pocketmine\utils\BinaryStream::putUnsignedVarInt() must be of the type integer, null given, called in phar:///custom.phar/src/pocketmine/network/mcpe/protocol/UpdateBlockPacket.php on line 68 on eggwars\arena\listener\ArenaListener
13.06 12:30:06 [Server] Server thread/CRITICAL TypeError: "Argument 1 passed to pocketmine\utils\BinaryStream::putUnsignedVarInt() must be of the type integer, null given, called in phar:///custom.phar/src/pocketmine/network/mcpe/protocol/UpdateBlockPacket.php on line 68" (EXCEPTION) in "vendor/pocketmine/binaryutils/src/BinaryStream" at line 230
13.06 12:30:06 [Server] Server thread/DEBUG #0

**Comment by Driesboy** [comment]
nope

**Comment by Muqsit** [comment]
It's not if you don't send the full error.

**Comment by treehousemc1** [comment]
Heres full error:

13.06 12:47:21 [Server] Server thread/CRITICAL Could not pass event 'pocketmine\event\server\DataPacketReceiveEvent' to 'EggWars v1.0.0-beta1': Argument 1 passed to pocketmine\utils\BinaryStream::putUnsignedVarInt() must be of the type integer, null given, called in phar:///custom.phar/src/pocketmine/network/mcpe/protocol/UpdateBlockPacket.php on line 68 on eggwars\arena\listener\ArenaListener
13.06 12:47:21 [Server] Server thread/CRITICAL TypeError: "Argument 1 passed to pocketmine\utils\BinaryStream::putUnsignedVarInt() must be of the type integer, null given, called in phar:///custom.phar/src/pocketmine/network/mcpe/protocol/UpdateBlockPacket.php on line 68" (EXCEPTION) in "vendor/pocketmine/binaryutils/src/BinaryStream" at line 230
13.06 12:47:21 [Server] Server thread/DEBUG #0 src/pocketmine/network/mcpe/protocol/UpdateBlockPacket(68): pocketmine\utils\BinaryStream->putUnsignedVarInt(NULL )
13.06 12:47:21 [Server] Server thread/DEBUG #1 src/pocketmine/network/mcpe/protocol/DataPacket(93): pocketmine\network\mcpe\protocol\UpdateBlockPacket->encodePayload()
13.06 12:47:21 [Server] Server thread/DEBUG #2 src/pocketmine/network/mcpe/RakLibInterface(218): pocketmine\network\mcpe\protocol\DataPacket->encode()
13.06 12:47:21 [Server] Server thread/DEBUG #3 src/pocketmine/Player(3090): pocketmine\network\mcpe\RakLibInterface->putPacket(pocketmine\Player object, pocketmine\network\mcpe\protocol\UpdateBlockPacket object, boolean , boolean )
13.06 12:47:21 [Server] Server thread/DEBUG #4 src/pocketmine/Player(3110): pocketmine\Player->sendDataPacket(pocketmine\network\mcpe\protocol\UpdateBlockPacket object, boolean , boolean )
13.06 12:47:21 [Server] Server thread/DEBUG #5 EggWars/src/eggwars/arena/listener/ArenaListener(248): pocketmine\Player->dataPacket(pocketmine\network\mcpe\protocol\UpdateBlockPacket object)
13.06 12:47:21 [Server] Server thread/DEBUG #6 src/pocketmine/plugin/MethodEventExecutor(38): eggwars\arena\listener\ArenaListener->onWindowClose(pocketmine\event\server\DataPacketReceiveEvent object)
13.06 12:47:21 [Server] Server thread/DEBUG #7 src/pocketmine/plugin/RegisteredListener(98): pocketmine\plugin\MethodEventExecutor->execute(eggwars\arena\listener\ArenaListener object, pocketmine\event\server\DataPacketReceiveEvent object)
13.06 12:47:21 [Server] Server thread/DEBUG #8 src/pocketmine/plugin/PluginManager(699): pocketmine\plugin\RegisteredListener->callEvent(pocketmine\event\server\DataPacketReceiveEvent object)
13.06 12:47:21 [Server] Server thread/DEBUG #9 src/pocketmine/network/mcpe/PlayerNetworkSessionAdapter(91): pocketmine\plugin\PluginManager->callEvent(pocketmine\event\server\DataPacketReceiveEvent object)
13.06 12:47:21 [Server] Server thread/DEBUG #10 src/pocketmine/network/mcpe/protocol/BatchPacket(114): pocketmine\network\mcpe\PlayerNetworkSessionAdapter->handleDataPacket(pocketmine\network\mcpe\protocol\ContainerClosePacket object)
13.06 12:47:21 [Server] Server thread/DEBUG #11 src/pocketmine/network/mcpe/PlayerNetworkSessionAdapter(92): pocketmine\network\mcpe\protocol\BatchPacket->handle(pocketmine\network\mcpe\PlayerNetworkSessionAdapter object)
13.06 12:47:21 [Server] Server thread/DEBUG #12 src/pocketmine/Player(3036): pocketmine\network\mcpe\PlayerNetworkSessionAdapter->handleDataPacket(pocketmine\network\mcpe\protocol\BatchPacket object)
13.06 12:47:21 [Server] Server thread/DEBUG #13 src/pocketmine/network/mcpe/RakLibInterface(153): pocketmine\Player->handleDataPacket(pocketmine\network\mcpe\protocol\BatchPacket object)
13.06 12:47:21 [Server] Server thread/DEBUG #14 vendor/pocketmine/raklib/server/ServerHandler(98): pocketmine\network\mcpe\RakLibInterface->handleEncapsulated(string 115.135.188.124 15771, raklib\protocol\EncapsulatedPacket object, integer 0)
13.06 12:47:21 [Server] Server thread/DEBUG #15 src/pocketmine/network/mcpe/RakLibInterface(94): raklib\server\ServerHandler->handlePacket()
13.06 12:47:21 [Server] Server thread/DEBUG #16 src/pocketmine/network/Network(89): pocketmine\network\mcpe\RakLibInterface->process()
13.06 12:47:21 [Server] Server thread/DEBUG #17 src/pocketmine/Server(2495): pocketmine\network\Network->processInterfaces()
13.06 12:47:21 [Server] Server thread/DEBUG #18 src/pocketmine/Server(2243): pocketmine\Server->tick()
13.06 12:47:21 [Server] Server thread/DEBUG #19 src/pocketmine/Server(2119): pocketmine\Server->tickProcessor()
13.06 12:47:21 [Server] Server thread/DEBUG #20 src/pocketmine/Server(1701): pocketmine\Server->start()
13.06 12:47:21 [Server] Server thread/DEBUG #21 src/pocketmine/PocketMine(305): pocketmine\Server->__construct(BaseClassLoader object, pocketmine\utils\MainLogger object, string /, string /plugins/)
13.06 12:47:21 [Server] Server thread/DEBUG #22 /custom.phar(1): require(string phar:///custom.phar/src/pocketmine/PocketMine.php)
