### ISSUE TITLE
Generation of grass under water

### ISSUE THREAD

**Issue by zKoz210** [pmmp/PocketMine-MP#2241]
### Issue description
At the moment, the generation is far from perfect, but when generating the world, we get an additional load when grass ticking update. I thought you fixed that problem a long time ago.

### OS and versions
* PocketMine-MP: https://github.com/pmmp/PocketMine-MP/commit/a9b7cd1699fe30ace853e18998159b77cc6cfbe1
* PHP: php 7.2
* Server OS: CentOS 7
* Game version: PE/Win10

### Crashdump, backtrace or other files
![image](https://user-images.githubusercontent.com/28255085/41414441-b65d07f6-6fee-11e8-972d-c91b448577d1.png)

**Comment by dktapps** [comment]
This was already fixed a few days ago. Existing terrain will not be affected by the fix.

**Comment by zKoz210** [comment]
I'm sorry, I didn't notice, but now it's like this... It doesn't look normal. In some places, just dirt, and somewhere grass.

And on such blocks is not generated snow layer.

![image](https://user-images.githubusercontent.com/28255085/41417637-9937a156-6ff6-11e8-982d-7fa87c25f3b5.png)

![image](https://user-images.githubusercontent.com/28255085/41417419-f8c6d584-6ff5-11e8-966a-e8eb55582fb5.png)

**Comment by dktapps** [comment]
While not entirely desirable, this is currently expected behaviour. The generator will be improved in the future.
