### ISSUE TITLE
Crash in start server "Server__64bit.php" | Multicraft

### ISSUE THREAD

**Issue by JavituRec** [pmmp/PocketMine-MP#2242]
Hello,

Today I have started to install pocketmine to offer my clients the possibility of expanding into other sectors.

I have had several problems and I have managed to solve it, when everything was ready I was involved in another error that I am not able to solve.

I have been searching in forum and github some solution but I could not find.

Basically what happens is that when you start the server there is a route that does not find and therefore the server does not finish loading and ends up crashing.

I leave the log and my relevant data.

All the best.

server 4: Loading server properties
server 4: Starting server!
server 4: Loading server config from PocketMine-MP.phar.conf
server 4: Loaded config for "PocketMine-MP"
server 4: Stream encoding for subprocess: UTF-8 in, UTF-8 out, latin-1 file
server 4: Server start command: "/home/mc/multicraft/jar/pocketmine/bin/php7/bin/php" "/home/mc/multicraft/jar/PocketMine-MP.phar" "--no-wizard" "--memory-limit=1000M" "--disable-ansi" "--data="/home/mc/multicraft/servers/server4"" "--plugins="/home/mc/multicraft/servers/server4/plugins"" "--level-name="world"" "--server-ip=0.0.0.0" "--server-port=25565" "--max-players=1"
server 4: Updating eula.txt file
server 4: Server started, PID: 11121
server 4: [Server] INFO **Warning: mkdir(): No such file or directory in phar:///home/mc/multicraft/jar/PocketMine-MP.phar/src/pocketmine/Server__64bit.php on line 1413**
server 4: [Server] Server thread/INFO Loading pocketmine.yml...
server 4: [Server] Server thread/INFO Loading server properties...
server 4: [Server] Server thread/INFO Selected English (eng) as the base language
server 4: [Server] Server thread/INFO Starting Minecraft: PE server version v0.15.0.0 alpha
server 4: [Server] Server thread/INFO Opening server on 0.0.0.0:25565
server 4: [Server] Server thread/INFO This server is running PocketMine-MP version 1.6dev "[REDACTED]" (API 2.0.0)
server 4: [Server] Server thread/INFO PocketMine-MP is distributed under the LGPL License
server 4: [Server] Server thread/INFO Loading recipes...
server 4: [Server] Server thread/INFO Preparing level ""world""
server 4: [Server] Server thread/INFO Starting GS4 status listener
server 4: [Server] Server thread/INFO Setting query port to 25565
server 4: [Server] Server thread/INFO Query running on 0.0.0.0:25565
server 4: [Server] Server thread/INFO Default game type: Survival Mode
server 4: [Server] Startup Done (0.269s)! For help, type "help" or "?"
server 4: Received pong from server
Communication with instance 4/17 completed
server 4: Server shut down (running)
server 4: **Restarting crashed server in 5 seconds**
server 4: Server stopped

* PocketMine-MP: PocketMine-MP version 1.6dev "[REDACTED]" (API 2.0.0)
* PHP: 7
* Server OS: Centos 7
* Game version: v0.15.0.0 alpha

**Comment by Muqsit** [comment]
`server 4: [Server] Server thread/INFO Starting Minecraft: PE server version v0.15.0.0 alpha` 🤔
