### ISSUE TITLE
Why can't use any block in creative mode?

### ISSUE THREAD

**Issue by OtorisanVardo** [pmmp/PocketMine-MP#2244]
### Issue description

In creative mode, we can't use any block.
Hmm...

MOVIE
https://imgur.com/a/BbumOIi

- Expected result: What were you expecting to happen?
- Actual result: What actually happened?

### OS and versions

* PocketMine-MP: cc97f76ec99431ffed2829e79bc6f8d71ec725ac
* PHP: 7.2
* Server OS: Linux
* Game version: PE/Win10 (delete as appropriate)

### Plugins
- Test on a clean server without plugins: is the issue reproducible without any plugins loaded?
LOOK THE MOVIE!!

If the issue is **not** reproducible without plugins:
- Have you asked for help on our forums before creating an issue?
- Can you provide sample, *minimal* reproducing code for the issue? If so, paste it in the bottom section
- Paste your list of plugins here (use the 'plugins' command in PocketMine-MP)

### Crashdump, backtrace or other files
- Do not paste crashdumps into an issue - please use our Crash Archive at https://crash.pmmp.io for submitting crash reports to not spam the issue tracker. Add links to your reports in the Crash Archive here.
- Please use gist or anything else to add other files and add links here

* ...

**Comment by zKoz210** [comment]
Download: https://github.com/pmmp/BedrockData

Copy to: /pocketmine/resource/vanilla/

**Comment by OtorisanVardo** [comment]
Oh... sorry...
Thank you very much!
