### ISSUE TITLE
Reduce the complexity of the `Plugin` interface

### ISSUE THREAD

**Issue by dktapps** [pmmp/PocketMine-MP#2249]
### Issue description
`pocketmine\plugin\Plugin` contains a large number of methods which are not necessary to be declared as interface methods. Most of these methods are only used internally by `PluginBase` (for example `reloadConfig()`, `saveDefaultConfig()`, etc). A lot of these methods should not even be public because they are expected to only be used inside plugins themselves (again, look at the config methods, or even `onEnable()`/`onDisable()`.

This issue proposes changes to the API of `Plugin` and `PluginBase` to:
- reduce the complexity of the public API
- reduce the leakiness of the API

These changes should not affect plugins or plugin interoperability significantly. However, any changes made are likely to break backwards compatibility, and for that reason should target PocketMine-MP 4.

**Comment by dktapps** [comment]
`getScheduler()` was introduced in 3.0 which is only used by the `PluginManager`. There should be a better way of managing schedulers which doesn't require every `Plugin` implementation to have `getScheduler()`.

**Comment by SOF3** [comment]
This issue is too broad and cannot be precisely defined. I recommend converting this to a project rather than an issue.

**Comment by SOF3** [comment]
"Complex" is an abstract adjective. It is impossible to define when this issue can be closed. I am closing this issue since [Project 6](https://github.com/pmmp/PocketMine-MP/projects/6) describes the same thing anyway.
