### ISSUE TITLE
Restarting PocketMine causes the console to become unresponsive

### ISSUE THREAD

**Issue by jasonwynn10** [pmmp/PocketMine-MP#2251]
### Issue description

Restarting PocketMine causes the console to become unresponsive

- Expected result: What were you expecting to happen? The console would work as normal
- Actual result: What actually happened? The console output an error, then became unresponsive to input.

### Steps to reproduce the issue

1. Start server
2. Stop server
3. Start server from same console

### OS and versions

* PocketMine-MP: PocketMine-MP 3.0.1 for Minecraft: PE v1.4.0 (protocol version 261)
* PHP: 7.2.1
* Server OS: Windows 10
* Game version: N/A

### Plugins
- Test on a clean server without plugins: is the issue reproducible without any plugins loaded? Yes

If the issue is **not** reproducible without plugins:
- Have you asked for help on our forums before creating an issue?
- Can you provide sample, *minimal* reproducing code for the issue? If so, paste it in the bottom section
- Paste your list of plugins here (use the 'plugins' command in PocketMine-MP)
Devtools
### Crashdump, backtrace or other files
- Do not paste crashdumps into an issue - please use our Crash Archive at https://crash.pmmp.io for submitting crash reports to not spam the issue tracker. Add links to your reports in the Crash Archive here.
- Please use gist or anything else to add other files and add links here

* ...

![screenshot 26](https://user-images.githubusercontent.com/16521025/41621484-c5bd815e-73da-11e8-83ef-a06622508858.png)
![screenshot 28](https://user-images.githubusercontent.com/16521025/41621486-c5d45726-73da-11e8-8af5-3a434783bcdf.png)

**Comment by dktapps** [comment]
You're using an out of date PHP build.
