### ISSUE TITLE
Help me

### ISSUE THREAD

**Issue by oGalatico** [pmmp/PocketMine-MP#2252]
Server::getInstance()->getScheduler()->cancelTask($this->getTaskId());

error

I'm a beginner, I need to know what I can do to replace this code.

**Comment by kenygamer** [comment]
This issue tracker is not a support forum. Please use the forums for support.

**Comment by oGalatico** [comment]
link ?

**Comment by MisterTurtleYt** [comment]
forums.pmmp.io

**Comment by kenygamer** [comment]
the way of scheduling tasks has changed, you can consult for help in the forum; the link has been previously posted by @Misteboss
