### ISSUE TITLE
Added crafting items that are not implemented

### ISSUE THREAD

**Issue by zKoz210** [pmmp/PocketMine-MP#2260]
### Issue description
CraftingManager registers all crafting, even those things that are not yet implemented. You can craft any item even though the server doesn't support it.
Ex. Shulker Box, Armor Stand and etc.

It seems to me that this should be taken into account and players should not get access to those items that are not implemented.

### Steps to reproduce the issue
1. Try craft any item that is not implemented.

### OS and versions
* PocketMine-MP: https://github.com/pmmp/PocketMine-MP/commit/d67149376d8034cb428e7b145f004791e89eb703

**Comment by kenygamer** [comment]
specifically what items are you talking about

**Comment by TDMidkwhatisxd** [comment]
Please read issue before comment 0-0

**Comment by dktapps** [comment]
I've considered doing something about this, but I didn't see it being worth the hassle. You can also obtain some un-implemented items from the creative inventory (for example spawn eggs, note block, redstone lamp, etc), so I don't consider this a relevant issue.

**Comment by zKoz210** [comment]
@dktapps 
Hmm... However, these things have classes, perhaps you didn't understand me?

![image](https://user-images.githubusercontent.com/28255085/41807454-e16a2cae-76d7-11e8-9ad5-1776f2799560.png)

**Comment by dktapps** [comment]
I understood you perfectly fine. Having a class doesn't automatically mean that it works. Like I said, I don't consider it worth the hassle filtering those out when half of the stuff that _does_ have known names doesn't work either.

**Comment by zKoz210** [comment]
For example, do Shulker Box
![image](https://user-images.githubusercontent.com/28255085/41807672-e2a78352-76da-11e8-9bc6-b626598577d8.png)


Let's say they are different colors, although I place only purple (It is normal for not implemented items)
![image](https://user-images.githubusercontent.com/28255085/41807676-ef2bcc46-76da-11e8-89d6-fd1025be0fdf.png)


(Quit and /gc to clean the chunks)
![image](https://user-images.githubusercontent.com/28255085/41807706-7a1ada04-76db-11e8-9d98-8652afa8c5d9.png)


Now I can't put blocks next to the workbench, they just don't want to place there

**Comment by torko1** [comment]
So is there nothing from the aquatic update on the servers??
