### ISSUE TITLE
DoubleChestInventory doesn't send updates to all viewers

### ISSUE THREAD

**Issue by Muqsit** [pmmp/PocketMine-MP#2261]
### Issue description

DoubleChestInventory attempts to send updates to viewers of the left/right side depending on the slot you put or remove an item from.
When you view a DoubleChestInventory, the DoubleChestInventory's `$viewers` count is `1` and the left and right chest inventories' `$viewers` count is `0`. [`DoubleChestInventory::setItem()`](https://github.com/pmmp/PocketMine-MP/blob/30a83544a0d4be47ad3cb77c91fb771d554fe337/src/pocketmine/inventory/DoubleChestInventory.php#L67) calls `ChestInventory::setItem()` (ChestInventory = left chest or right chest) which sends the slot update to viewers of THAT chest.

- Expected result: All viewers of DoubleChestInventory should be sent item updates.
- Actual result: Only the person who set an item in the double chest inventory gets the update.

### Steps to reproduce the issue

1. View a double chest from two clients.
2. Set an item in the double chest from any one client.
3. The other client can't see the item unless they re-open the inventory.

### OS and versions

* PocketMine-MP: 76174f192036cad1436e9f8f085d92bf3f472db0
* PHP: 7.2.3
* Server OS: Ubuntu 18.04
* Game version: Windows 10

### Plugins
- Test on a clean server without plugins: is the issue reproducible without any plugins loaded? Yes

**Comment by dktapps** [comment]
I remember fixing this a long time ago in Genisys. The problem as I recall is that DoubleChestInventory instances are not shared.
