### ISSUE TITLE
Load Chunks or Generate new world

### ISSUE THREAD

**Issue by TepBG** [pmmp/PocketMine-MP#2263]
Issue description:
Error: "Access to undeclared static property: pocketmine\scheduler\AsyncWorker::$store" (EXCEPTION) in "src/pocketmine/scheduler/AsyncWorker" at line 93

Steps to reproduce the issue:
load chunks or generate new world crashed server

OS and versions
PocketMine-MP: 3.0.3
PHP: 7.2.6
Server OS: Windows

**Comment by dktapps** [comment]
https://github.com/pmmp/PocketMine-MP/commit/edd150971ea3da9c54a357ca6667cce41b1b3bb5#commitcomment-29472474
