### ISSUE TITLE
Can't place blocks where player has died (untill respawn or quit)

### ISSUE THREAD

**Issue by DancingXXL** [pmmp/PocketMine-MP#2265]
### Issue description
Title describes everything. You can not put blocks in the space that the player occupied before death

### Steps to reproduce the issue
1. Kill player 1
2. Player 2 must try to put blocks where the player1 has died

### OS and versions
* PocketMine-MP: fc8dc8a

### Plugins
No plugins

### Crashdump, backtrace or other files
No errors

**Comment by dktapps** [comment]
Fix will be in the following upcoming versions:
- 3.0.5
- 3.1.0
- 4.0.0 (as of build 1226 on Jenkins)
