### ISSUE TITLE
Blocks shifted vertically in builds after e85d6d1 (mcpe-1.0)

### ISSUE THREAD

**Issue by markkrueg** [pmmp/PocketMine-MP#227]
### Issue description
I'm noticing structures built using glass blocks/windows are jumbled up (blocks moved up by one or many levels vertically). I don't know if this is effecting other blocks as well. I will upload pictures below to better explain. This is an mcregion world.

The world looks fine as of commit e85d6d1. The problem is occurring in a build as of commit 0d062fe. So the bug likely happened in commit 69061ba or after

The bug is still occurring in 1df070e. 

If I go back to build as of e85d6d1, everything correct itself.

### Steps to reproduce the issue
I have not tested reproducing this with a clean world. But I would suggest that building a similar structure to the one shown using e85d6d1 and then moving to a build as of 0d062fe might show similar results. 

### OS and versions
* PocketMine-MP: PocketMine-MP 1.6.2dev 「Unleashed」 implementing API version 3.0.0-ALPHA1 for Minecraft: PE v1.0.0.16 (protocol version 100) (commit 0d062fe)
* PHP: 7.0.10
* Server OS: Ubuntu 16.04.1 LTS
* Game version: Android 1.0.0

### Crashdump, backtrace or other files
![before](https://cloud.githubusercontent.com/assets/12489897/21615108/e96f7794-d190-11e6-9b4f-4530b956bbc1.jpg)
![after](https://cloud.githubusercontent.com/assets/12489897/21615124/f5754906-d190-11e6-94b7-01ecb620075c.jpg)

**Comment by dktapps** [comment]
Forget professionalism. WTF?

**Comment by dktapps** [comment]
Reproduced with Nether generator with PMAnvil.
![screenshot_2017-01-03-17-10-33](https://cloud.githubusercontent.com/assets/14214667/21616009/d25f4786-d1d7-11e6-81a2-d2be7feb16e0.png)

**Comment by markkrueg** [comment]
I was able to easily re-create it with a clean new mcregion world also. World enclosed.

[world.zip](https://github.com/pmmp/PocketMine-MP/files/682852/world.zip)

**Comment by dktapps** [comment]
Do you get any peculiar lighting in worlds used while this bug occured?

**Comment by markkrueg** [comment]
re: lighting  Not that I am noticing. But I am probably not the best judge of correct lighting.

**Comment by markkrueg** [comment]
6c0bbc4 Seems to have fixed any problems I am aware of. OK to close this? Or are you still seeing some issues?

**Comment by dktapps** [comment]
Semi-related issues to do with lighting, particularly with Nether generator.
