### ISSUE TITLE
SendBlocks  not call InteractEvent

### ISSUE THREAD

**Issue by sc00scoc** [pmmp/PocketMine-MP#2270]
### Issue description

It seems that the blocks that are sent to the player with the "sendBlocks" function do not pass for the interact event when for onBreak is work

- Expected result: What were you expecting to happen?
- Actual result: What actually happened?

### Steps to reproduce the issue

1. $player->getLevel()->sendBlocks([$player], [$block], UpdateBlockPacket::NETWORK_ID, true);
2. ...

### OS and versions

* PocketMine-MP: 
* PHP:
* Server OS:
* Game version: PE/Win10 (delete as appropriate)

### Plugins
- Test on a clean server without plugins: is the issue reproducible without any plugins loaded?

If the issue is **not** reproducible without plugins:
- Have you asked for help on our forums before creating an issue?
- Can you provide sample, *minimal* reproducing code for the issue? If so, paste it in the bottom section
- Paste your list of plugins here (use the 'plugins' command in PocketMine-MP)

### Crashdump, backtrace or other files
- Do not paste crashdumps into an issue - please use our Crash Archive at https://crash.pmmp.io for submitting crash reports to not spam the issue tracker. Add links to your reports in the Crash Archive here.
- Please use gist or anything else to add other files and add links here

* ...

**Comment by sc00scoc** [comment]
why

**Comment by sc00scoc** [comment]
There are hundreds of thousands of blocking bugs on pmmp. That you can not find, give space to these issues not be afraid of new issues. If you are frustrated, take a break

**Comment by dktapps** [comment]
I don't know what you expect to happen. It appears you don't understand the usage of that function. As such this is a support request, which is not desired on this issue tracker.
