### ISSUE TITLE
SendBlocks, the problem that you cant see.

### ISSUE THREAD

**Issue by sc00scoc** [pmmp/PocketMine-MP#2271]
You can kindly test this function and verify that it has problems!
- Do not spray blocks (Especially in task or too quickly).
- It is not called by the interact, but by the on break yes (WTF).
- Create errors unknown to here I can not give explanations like:
"Trying to get property" x "of non-object" (EXCEPTION) in "src / pocketmine / level / Level" at line 892 "

P.S.
I know you would like to keep the issues under 70. But if there are thousands of bugs this is not possible!

**Comment by dktapps** [comment]
you're very condescending and your explanation was (and still is) unclear. Also, you have not correctly filled out the issue template.

**Comment by dktapps** [comment]
Without knowing your PocketMine-MP version, OS, PHP, Client version, or plugins and how the issue occurred, the issue cannot begin to be solved.
A pre-formatted template is provided that shows the required information to begin to find, test and solve an issue.
Until the adequate template and information is provided, the issue will be closed; it may be reopened if you update the ticket with the correct template and required information.

[Contribution guidelines](https://github.com/pmmp/PocketMine-MP/blob/master/CONTRIBUTING.md)

**Comment by sc00scoc** [comment]
ok updated now you can open :)

**Comment by dktapps** [comment]
>  your explanation was (and still is) unclear.

**Comment by sc00scoc** [comment]
https://youtu.be/3XKXOXP6zpQ

**Comment by sc00scoc** [comment]
ok updated now you can open :))

**Comment by dktapps** [comment]
You can see that the blocks exist because of the wireframe outlines. This is therefore clearly nothing to do with PocketMine-MP. Judging by the code you posted in the other issue, you're using incorrect flags to send the blocks.

Please seek support on the forums. This is not a plugin support forum.

**Comment by sc00scoc** [comment]
i tested all flag same problem

**Comment by sc00scoc** [comment]
and why doesnt call interact sendBlocks?
