### ISSUE TITLE
Can pickup Arrows Shot From a infinity Bow

### ISSUE THREAD

**Issue by r7vmc** [pmmp/PocketMine-MP#2277]
### Issue description

in Vanilla Minecraft When you Shoot a Arrow with Infinity Bow You can't Pickup the Arrow You have shot, but in PMMP you can pick it up

- Expected result: What were you expecting to happen?
Becoming Unable to pickup the arrow

- Actual result: What actually happened?
A picked it up
### Steps to reproduce the issue

1. ... Enchanted a Bow with Infinity
2. ... Shot a Arrow

### OS and versions

* PocketMine-MP:  4.0.0+dev.1225
* PHP: 7.2
* Server OS: Windows
* Game version: PE/Win10 (delete as appropriate)

### Plugins
- Test on a clean server without plugins: is the issue reproducible without any plugins loaded?

If the issue is **not** reproducible without plugins:
- Have you asked for help on our forums before creating an issue?
- Can you provide sample, *minimal* reproducing code for the issue? If so, paste it in the bottom section
- Paste your list of plugins here (use the 'plugins' command in PocketMine-MP)

### Crashdump, backtrace or other files
- Do not paste crashdumps into an issue - please use our Crash Archive at https://crash.pmmp.io for submitting crash reports to not spam the issue tracker. Add links to your reports in the Crash Archive here.
- Please use gist or anything else to add other files and add links here

* ...

**Comment by dktapps** [comment]
*in creative.

**Comment by Driesboy** [comment]
https://youtu.be/-by9t832cew

**Comment by dktapps** [comment]
@Driesboy that looks like a vanilla bug to me. Historically it was not possible to do that. The wiki also details that they are only pickupable in creative (as per PC I would assume) so that's the behaviour I implemented.

**Comment by r7vmc** [comment]
You shouldn't to be able to pick it up in Survival
