### ISSUE TITLE
Xbox auth can be faked

### ISSUE THREAD

**Issue by DancingXXL** [pmmp/PocketMine-MP#2281]
### Issue description
Look at the title. If at least one JWT in chainData is signed, authentication status wil be OK. You can inject any signed JWT, and then write data you want in next JWTs (i.e. fake nickname, XUID etc.)

### OS and versions
* PocketMine-MP: 4ccbb8b
* Game version: Android

**Comment by dktapps** [comment]
I don't think you understand how the JWT chain works. Please do not waste our time with unverified claims.

Additionally, if you have discovered a security vulnerability (and we already know of a couple) then you should report it privately instead of on a public issue tracker.

**Comment by DancingXXL** [comment]
How can I report it privately?

**Comment by dktapps** [comment]
You can send me a message on https://forums.pmmp.io/
