### ISSUE TITLE
!spam

### ISSUE THREAD

**Issue by ATMG** [pmmp/PocketMine-MP#2283]
pls switch to a real language php is such a meme language like please stop using php

**Comment by lukeeey** [comment]
pls switch to a real game like fortnite minecraft is a meme game like please stop playing minecraft

**Comment by Sandertv** [comment]
This is an *issue* tracker. If you want to express your opinion on something, go to the forums. (forums.pmmp.io) If you're too lazy to sign up, then don't bother shitposting the issue tracker. Thanks :+1:
