### ISSUE TITLE
Change Player chatting abilities to be controlled by permissions

### ISSUE THREAD

**Issue by dktapps** [pmmp/PocketMine-MP#2288]
### Issue description
Currently non-operators are not permitted to use colour codes in chat. When a player is opped, this is not updated. This can be easily fixed of course, but this gave me ideas on ways to improve this.

Additionally, to alter this behaviour it is necessary to have a bespoke plugin which specifically overrides this. I think it would be preferable to have this managed by permissions instead, so that permission management plugins can control it.

Additionally, there is currently no simple way to deny permission to chat ("mute"), short of cancelling `PlayerChatEvent` for every chat message from selected players.

This proposes the addition of a new permission node `pocketmine.chat` to allow permission plugins to control chat abilities.

### Steps to reproduce the issue
1. op a player
2. notice that player can't use colour codes until they rejoin

### OS and versions
* PocketMine-MP: https://github.com/pmmp/PocketMine-MP/commit/9c80e349cede7857154c053450c5de801fdbb5b1

**Comment by lukeeey** [comment]
Or you could implement the built in permissions that are shown when clicking a player in the player list

**Comment by dktapps** [comment]
That's just a frontend. This issue is talking about how to handle the backend permission system.

**Comment by hartleyterw** [comment]
How do you go about overriding this with a plugin? PureChat doesn't seem to cut it anymore.

**Comment by Landy005** [comment]
Is there a way to give non operators the ability to use § then? Because for pureperms operators need to be disabled.
