### ISSUE TITLE
Written_Book created with NBT tags crashes client

### ISSUE THREAD

**Issue by JUSTaMod** [pmmp/PocketMine-MP#2291]
### Issue description

Creating a written book in NBT with /give, then having a player attempt to open said book, will crash the client.

example - /give usernamehere written_book 1 {title:"Book Title",author:"Author Name",pages:["Page 1"]}

- Expected result: Open the book, see the pages and text.
- Actual result: Client crashed.

### Steps to reproduce the issue

1. run the command provided in the issue description.
2. Open the book.

### OS and versions

* Server Versions: PocketMine-MP 3.0.5 for Minecraft: PE v1.4.0 (protocol version 261)
                             PocketMine-MP 4.0.0+dev.1236 for Minecraft: PE v1.4.0 (protocol version 261)
* PHP: 7.2.5
* Server OS: Windows Server Datacenter, version 1803 build 17134
* Game version: PE/Win10 (this bug applies to both - aren't they technically the same now anyway???)

### Plugins

- Tested on a clean server without plugins. Check.

### Crashdump, backtrace or other files

The feedback to the server is simply - userhere -- logged out due to timeout

**Comment by dktapps** [comment]
You've structured the NBT incorrectly. See https://github.com/pmmp/PocketMine-MP/blob/master/src/pocketmine/item/WritableBook.php#L114 for an example.

**Comment by JUSTaMod** [comment]
Got it.

**Comment by lukeeey** [comment]
Shouldn't the server check the structure to prevent these crashes in the future?

**Comment by ZizzyZizzy** [comment]
Java version server allows the same command to be used without issue. Book doesn't crash the client though.

Go ahead, shoot yourself in the foot, apparently.

**Comment by dktapps** [comment]
There's no end of special cases that will crash the client. I have no more intention of taping over this one than any other. This is Mojang's issue to fix.
