### ISSUE TITLE
Don't spawn at spawnpoint

### ISSUE THREAD

**Issue by Philipp97714** [pmmp/PocketMine-MP#2295]
Using PocketMine-MP 3.0.5

If I enter "/tp -70 70 150" in Minecraft, everything is fine and I can teleport myself. If I enter "/setworldspawn -70 70 150" and then "/kill" and respawn, I spawn at (18.5, 0, -58.5) and fall out of world. I'm in creative mode. At the servers console I see

> [18:15:20] [Server thread/INFO]: [myUsername: Set the world spawn point to (-70, 70, 140)]

**Comment by lukeeey** [comment]
These commands always confuse me. You can use /spawnpoint for your personal spawn point

**Comment by Philipp97714** [comment]
/spawnpoint seems to be used to set a spawn point for only one player. This is different from /setworldspawn

**Comment by dktapps** [comment]
This bug is a result of improper handling of async generation. `Level->getSafeSpawn()` sees an empty (not yet generated) chunk and spawns you at the bottom of it as a result. Similar bugs _may_ happen during the first login if your machine is slow enough (or by chance).
