### ISSUE TITLE
No block light population during chunk generation

### ISSUE THREAD

**Issue by dktapps** [pmmp/PocketMine-MP#230]
### Issue description
Generated lava in the Overworld for example, appears completely black until locally updated.

### Steps to reproduce the issue

1. generate a world with the HELL generator
2. look at the lava

### OS and versions

* PocketMine-MP: 934fe8c
* PHP: 7.0.13
* Server OS: Android
* Game version: PE

**Comment by thebigsmileXD** [comment]
Just a note by me, you may concider not removing it and insulting me for trying to help:
Chunk border light may not be able to be calculated, if a chunk next to it still doesn't exist.

**Comment by dktapps** [comment]
This is no longer valid for two reasons:

1) Lighting is no longer calculated ahead of time, but instead done on the fly as-needed (89cce4c7498bffe0695e416f53543845381bc210).
2) Block light calculation has since been implemented (1859dac7895c8d7e92ce6011d566279f074a5b56).
