### ISSUE TITLE
slowness does not going off if amplifier is bigger than 5

### ISSUE THREAD

**Issue by djdisodo** [pmmp/PocketMine-MP#2304]
### Issue description

slowness does not going off if amplifier is bigger than 5

### Steps to reproduce the issue

1. type /effect <player> slowness 3 6
2. effect is not showing on inventroy. but still moves slowly

### OS and versions

* PocketMine-MP: 4.0.0+dev.1213
* PHP:
* Server OS: linux
* Game version: PE

**Comment by dktapps** [comment]
Duplicate of #1551
