### ISSUE TITLE
Teleporting long distances to another player causes a total server freeze

### ISSUE THREAD

**Issue by dktapps** [pmmp/PocketMine-MP#231]
### Steps to reproduce the issue

1. get 2 players on a server
2. teleport one of them ~500,000 blocks away from the other
3. teleport the other player to the first player
4. server freezes

The server will max out one CPU core, become unresponsive to commands and slowly leak memory (0.1MB/s)

### OS and versions

* PocketMine-MP: 6351cac
* PHP: 7.0.13 64-bit
* Server OS: Windows 10
* Game version: PE/Win10

### References
https://github.com/iTXTech/Genisys/issues/1889

**Comment by dktapps** [comment]
Related to movement checks, this occurs every teleport if movement checks are removed. With the checks it occurs rarely.

**Comment by legoboy0215** [comment]
Sorta off-topic, but for some reason my VPS (not my PM server) has been crashing/rebooting very often recently, and I am afraid this might be the issue.

**Comment by Infernus102** [comment]
Confirmed

**Comment by dktapps** [comment]
Related to #152

**Comment by dktapps** [comment]
Fixed in the referenced commit.
