### ISSUE TITLE
ArrayOutOfBoundsException: "Undefined index: api_version"

### ISSUE THREAD

**Issue by nsoutter** [pmmp/PocketMine-MP#2313]
Hey all!

Installed the windows version on a fully up to date Windows 10 machine, on a G drive (put less commonly used apps there). Install went smoothly.

However the app won't run. Everytime I get an exception right out of the gate (hasn't even run once):

15:16:55 [INFO] Starting Minecraft: PE server version v0.10.5 alpha
15:16:55 [INFO] Loading pocketmine.yml...
15:16:55 [INFO] Loading server properties...
15:16:55 [INFO] Starting Minecraft PE server on 0.0.0.0:19132
15:16:56 [INFO] This server is running PocketMine-MP version 1.4.1-980 "絶好(Zekkou)ケーキ(Cake)" (API 1.11.0)
15:16:56 [INFO] PocketMine-MP is distributed under the LGPL License
15:16:59 [NOTICE] ArrayOutOfBoundsException: "Undefined index: api_version" (E_NOTICE) in "/src/pocketmine/updater/AutoUpdater" at line 68
15:16:59 [EMERGENCY] An unrecoverable error has occurred and the server has crashed.

Any thoughts? Thanks in advance.

### Issue description

- Expected result: What were you expecting to happen?
- Actual result: What actually happened?

### Steps to reproduce the issue

1. ...
2. ...

### OS and versions

* PocketMine-MP: 
* PHP:
* Server OS:
* Game version: PE/Win10 (delete as appropriate)

### Plugins
- Test on a clean server without plugins: is the issue reproducible without any plugins loaded?

If the issue is **not** reproducible without plugins:
- Have you asked for help on our forums before creating an issue?
- Can you provide sample, *minimal* reproducing code for the issue? If so, paste it in the bottom section
- Paste your list of plugins here (use the 'plugins' command in PocketMine-MP)

### Crashdump, backtrace or other files
- Do not paste crashdumps into an issue - please use our Crash Archive at https://crash.pmmp.io for submitting crash reports to not spam the issue tracker. Add links to your reports in the Crash Archive here.
- Please use gist or anything else to add other files and add links here

* ...

**Comment by Thunder33345** [comment]
sir, you are using an old version of PMMP
please get it via https://pmmp.io
also please use https://forums.pmmp.io for support
