### ISSUE TITLE
PluginManager::isCompatibleAPI() Does not properly evaluate plugin declared API version number.

### ISSUE THREAD

**Issue by 95CivicSi** [pmmp/PocketMine-MP#2335]
### Issue description

When attempting to load a plugin that declares a patch level specific number, PocketMine-MP will fail to properly evaluate that number if the plugin declares a lower minor level version than the current server version.  

Example: Attempting to load a plugin which declares api: 3.0.7 on PocketMine-MP 3.1.1 will result with the plugin not being loaded and an error message given.
`Could not load plugin <plugin_name>: Incompatible API version (plugin requires one of: 3.0.7)`

- Expected result: Any plugin declaring a patch level requirement, should load if the minor level requirement is exceeded, regardless of the patch level requirement.
Examples:
   - 3.0.0 plugin loads on Server 3.1.1
   - 3.0.1 plugin loads on Server 3.1.1
   - 3.0.2 plugin loads on Server 3.1.1
   - 3.0.3 plugin loads on Server 3.1.1

- Actual result: What actually happened? Plugins declaring a patch level requirement will not load if the declared patch level is higher than the server patch level, and the minor level of the server is higher than the plugin declared minor level. 
Examples:
   - 3.0.0 plugin loads on Server 3.1.1
   - 3.0.1 plugin loads on Server 3.1.1
   - 3.0.2 plugin does not load on Server 3.1.1
   - 3.0.3 plugin does not load on Server 3.1.1

### Steps to reproduce the issue

1. Attempt to start a PocketMine-MP server with a plugin that declares a specific patch level.
2. Make sure the server version has a minor level, higher than the minor level declared by the plugin.
3. Make sure the  server version has a patch level lower than the patch level declared by the plugin.
4 Plugin will fail to load.

### OS and versions

* PocketMine-MP: 3.0.0 - 3.1.1
* PHP: 7.2.5
* Server OS: Windows 10, Linux, Mac
* Game version: NA

### Plugins
- Test on a clean server without plugins: is the issue reproducible without any plugins loaded?

If the issue is **not** reproducible without plugins:
- Have you asked for help on our forums before creating an issue?
- Can you provide sample, *minimal* reproducing code for the issue? If so, paste it in the bottom section
- Paste your list of plugins here (use the 'plugins' command in PocketMine-MP)

### Crashdump, backtrace or other files
- Do not paste crashdumps into an issue - please use our Crash Archive at https://crash.pmmp.io for submitting crash reports to not spam the issue tracker. Add links to your reports in the Crash Archive here.
- Please use gist or anything else to add other files and add links here

* ...

**Comment by dktapps** [comment]
oh... so `3.0.7` would only load on `3.1.7` and up, `3.2.7` and up, etc?

that's a rather amusing bug.

**Comment by 95CivicSi** [comment]
Lol, I don't know if I would describe it as amusing, but otherwise, your statement is correct.
