### ISSUE TITLE
Players can lag out any server /:

### ISSUE THREAD

**Issue by artulloss** [pmmp/PocketMine-MP#2337]
### Issue description

Players can lag out any server using this method /: my server gets targeted by this 8 times a day (competeting server does it to steal our players) and it's very stressful. Server stops replying to Ctrl c ect. Muqsit said this behavior is caused by too many packets coming in from a player at once and to simply turn on built in anticheat in that case. Didn't seem to make a difference at all, players still did it to us. Seems to be from too many packets spamming the server at once. At the very least there needs to be an open source plugin to kick for this /: it seriously hurts uptime.

- Expected result: What were you expecting to happen?
- Actual result: What actually happened?

### Steps to reproduce the issue

1. Here is a video some malicious player made to spread how to do it
2. https://youtu.be/jgVvRRZanjA

### OS and versions

* PocketMine-MP: 
* PHP: 7.2
* Server OS: Ubuntu 16
* Game version: Win10 can do this

### Plugins
- Test on a clean server without plugins: is the issue reproducible without any plugins loaded?
Seems to work on every server, personally never done it to anyone /:

Plugins are listed in this timings report

https://timings.pmmp.io/?id=55

If the issue is **not** reproducible without plugins:
- Have you asked for on our forums before creating an issue?
- Can you provide sample, *minimal* reproducing code for the issue? If so, paste it in the bottom section
- Paste your list of plugins here (use the 'plugins' command in PocketMine-MP)

### Crashdump, backtrace or other files
- Do not paste crashdumps into an issue - please use our Crash Archive at https://crash.pmmp.io for submitting crash reports to not spam the issue tracker. Add links to your reports in the Crash Archive here.
- Please use gist or anything else to add other files and add links here

* ...

**Comment by dktapps** [comment]
Known issue... and do you really think it is a good idea to report a server attack vector on a public issue tracker? You've just notified nearly 200 people of this. Congratulations.
