### ISSUE TITLE
Network: some players cannot connect the the server

### ISSUE THREAD

**Issue by TheAz928** [pmmp/PocketMine-MP#2346]
### Issue description
Some players cannot connect to the server (yet again), I've saw this issue in past, never happened to me, but now its suddenly happening.

Console has no log even with debug enabled.

- Expected result: What were you expecting to happen?
- Actual result: What actually happened?

### Steps to reproduce the issue

1. Some players try to join but "unable to connect"
2. ...

### OS and versions

* PocketMine-MP:  5492495
* PHP: 7.2
* Server OS: Ubuntu
* Game version: PE/Win10 

### Plugins
- Tested on a clean server 

### Crashdump, backtrace or other files
- none

* ...

**Comment by dktapps** [comment]
If you have no debug output whatsoever, then this is more likely an issue with your connection than anything else, so I'm closing this.
