### ISSUE TITLE
Value 37467 is too large!

### ISSUE THREAD

**Issue by toOXaUL** [pmmp/PocketMine-MP#2348]
* PocketMine-MP: 3.1.2 - release
* PHP: 7.2
* Server OS: Ubuntu 16.04

Hello, i dont know how to fix this problem but here is crashdump: https://pastebin.com/v1frp1Dt
If someone know how to fix it, please help.
Additional information: https://crash.pmmp.io/view/586547

**Comment by Eren5960** [comment]
You must be go to forums.pmmp.io

**Comment by lukeeey** [comment]
This crash is probably caused by one of your plugins. Please test on a clean server without any plugins and if the problem persists then tell us, otherwise remove your plugins one by one to find the broken one.

**Comment by toOXaUL** [comment]
Problem was in SAC plugin(Shadow Anti Cheat), i think it check every tick players and server crashes. Ty all
