### ISSUE TITLE
Is it possible to detect if the player is using Win10 ? If not can you add the possibility to ?

### ISSUE THREAD

**Issue by Misteboss** [pmmp/PocketMine-MP#235]
### Issue description

This things should help server to organize themselves, for exemple PvP servers they can make one arena for Win10 players and an other for mobile players.
@dktapps

**Comment by dktapps** [comment]
This is not a support forum. Please use https://forums.pmmp.io for that purpose.

To answer your question, no reliable method. If you search threads at forums.pocketmine.net, you will find this question has been asked many times before.

Please review the [contribution guidelines](CONTRIBUTING.md) before opening an issue in future.

**Comment by Misteboss** [comment]
Ok so are going to add it ? Or can you explain me how can i do that ? @dktapps

**Comment by Misteboss** [comment]
Btw i opened a thread on the forum

**Comment by archie426** [comment]
@Misteboss Please do not keep persist with the question when the issue is closed
