### ISSUE TITLE
Aquatic update missing and features from v1.5 

### ISSUE THREAD

**Issue by torko1** [pmmp/PocketMine-MP#2351]
### Issue description

Hi, there seems to be an issue with getting current items from new updates. Such as a "carrot on a stick" and other from the aquatic update. But yet it says its running on v1.5!?! Is there something wrong in my install or is it server software? 

kind regards
Aaron

**Comment by dktapps** [comment]
> Please do not create issues for missing/un-implemented gameplay features - they will be closed.

please read the issue template...
