### ISSUE TITLE
DoubleChestInventory: get contents on null

### ISSUE THREAD

**Issue by TheAz928** [pmmp/PocketMine-MP#2359]
### Issue description
When executing `$doubleChestTile->getInventory()->getContents()` after running the command /gc, left or right side Chest tile gets closed giving get contents on null error.

I've no issues with Chest tile (single chest)

NOTE: This issue only happens when executed in certain situations
I've made a Hopper plugin, and seems like after /gc command I get this error.

My code is here just in case you think it's my code:

if(($tr = $this->getLevel()->getTile($thisHopper->getSide($thisHopper->getDamage()))) instanceof Container){
			if(($k = $this->getFirstOccupied($this)) !== -1){
				$sending = clone $inv->getItem($k);
				$sending->setCount(1);
				
				if($tr->getInventory()->canAddItem($sending)){ // $tr is double chest tile
					$inv->removeItem($sending);
					$tr->getInventory()->addItem($sending);
					
					$this->cd = 8;
				}
			}
		}

public function getFirstOccupied(Container $tile) : int{
		foreach($tile->getInventory()->getContents(true) as $key => $item){
			if($item->isNull() == false){
				return $key;
			}
		}
		
		return -1;
	}

If you still want to take a look at the plugin, I can send you it. But most likely it's not the plugins fault.

- Expected result: What were you expecting to happen?
- Actual result: What actually happened?

### Steps to reproduce the issue

1. Create a inventory which transfers items from one to another inventory
2. run /gc

### OS and versions

* PocketMine-MP: Release 3.1.2
* PHP: 7.2
* Server OS: Ubuntu
* Game version: PE/Win10

### Plugins
- Hopper implemention

### Crashdump, backtrace or other files
- none

**Comment by dktapps** [comment]
There isn't sufficient information here for me to consider this anything other than a plugin support request.

The code you pasted does not contain a call to `getContents()`. This is too vague to be of any use.

**Comment by TheAz928** [comment]
@dktapps check carefully, it contains
 check "public function getFirstOccupied"

**Comment by jasonwynn10** [comment]
@TheAz928 it would be much easier if the code was in code brackets 😐

**Comment by PixelzChris** [comment]
How to add items on a double chest GUI though??
