### ISSUE TITLE
Command usage output issue on the client

### ISSUE THREAD

**Issue by dktapps** [pmmp/PocketMine-MP#236]
### Issue description
Sometime since 0.16, it seems the specific command usage strings such as `commands.effect.usage`, `commands.kick.usage`, etc. have been removed from the client language files, resulting in an issue in usage output on the client. This seems to be because those strings are no longer necessary with the new commands implementation in 0.16.

### Steps to reproduce the issue

1. run a vanilla command with wrong params
2. output is something like `ommands.effect.usage` (no, that's not a typo)

### OS and versions

* PocketMine-MP: 02ddcef
* PHP: 7.0.13
* Server OS: Ubuntu
* Game version: PE/Win10

### Solutions
- Wait for new commands API server-side for proper commands support
- Translate strings server-side before sending.

**Comment by flaxues** [comment]
Yup reproduced

**Comment by TheDiamondYT1** [comment]
I hope the new command system adds back those usage messages and not the lazy `Invalid command syntax`.

**Comment by dktapps** [comment]
the new system doesn't need them... the command suggestions are all the usage message you need.

**Comment by TheDiamondYT1** [comment]
True. I didn't think of that since PocketMine doesn't send those suggestions to the client yet.

It will be interesting to see if/how PocketMine commands will be handled. It seems a bit ugly and long the way @Sandertv does it.

**Comment by TheDiamondYT1** [comment]
In 1.2, it seems it uses a mixture of messages.

Generally if you type something like `/tp @p x y` it will say something like "Syntax error: unexpected something at something"

But if you type `/give @p elytra 2 1` it will say something like "The highest amount you can give is 1" or something (cba to check the messages now)
