### ISSUE TITLE
NetworkBinaryStream::putByteRotation() must be of the type float, null given

### ISSUE THREAD

**Issue by FreeGamingHere** [pmmp/PocketMine-MP#2360]
### Issue description

I am using slapper and slapper rotation, both working with 4.0.0, 1.5 updated. Slapper rotation spams the console with the error above

- Expected result: The entity moving its head
- Actual result: The entity moved its head but there was a console spam

### Steps to reproduce the issue

1. Spawn a villager with slapper
2. Move

### OS and versions
* PocketMine-MP: PocketMine-MP 4.0.0+dev.1353
* PHP: 7.2
* Server OS: Linux

### Plugins
I used slapper, and slapper rotation (slapper rotation causes the bug)

### Crashdump, backtrace or other files
`[18:05:02] [Server thread/CRITICAL]: Could not tick level "Lobby": Argument 1 passed to pocketmine\network\mcpe\NetworkBinaryStream::putByteRotation() must be of the type float, null given, called in phar:///home/gs/gs/data/servers/7069490/PocketMine-MP.phar/src/pocketmine/network/mcpe/protocol/MoveEntityAbsolutePacket.php on line 64
[18:05:02] [Server thread/CRITICAL]: TypeError: "Argument 1 passed to pocketmine\network\mcpe\NetworkBinaryStream::putByteRotation() must be of the type float, null given, called in phar:///home/gs/gs/data/servers/7069490/PocketMine-MP.phar/src/pocketmine/network/mcpe/protocol/MoveEntityAbsolutePacket.php on line 64" (EXCEPTION) in "src/pocketmine/network/mcpe/NetworkBinaryStream" at line 407`
* ...

**Comment by FreeGamingHere** [comment]
It is a pocketmine bug.

**Comment by dktapps** [comment]
no, it is not. you just don't know what you're doing.

**Comment by FreeGamingHere** [comment]
Ok, thanks.
