### ISSUE TITLE
Binary error

### ISSUE THREAD

**Issue by SuperAdam47** [pmmp/PocketMine-MP#2369]
### Issue description

./bin/php7/bin/php: error while loading shared libraries: libmvec.so.1: cannot open shared object file: No such file or directory

- Expected result: run ./start.sh
- Actual result: 

### Steps to reproduce the issue

1. Run server
2. ./bin/php7/bin/php: error while loading shared libraries: libmvec.so.1: cannot open shared object file: No such file or directory

### OS and versions

* PocketMine-MP: 4.0.0
* PHP: 7.2.8
* Server OS: Linux
* Game version: Win10

### Plugins
- Test on a clean server without plugins: is the issue reproducible without any plugins loaded?

If the issue is **not** reproducible without plugins:
- Have you asked for help on our forums before creating an issue?
- Can you provide sample, *minimal* reproducing code for the issue? If so, paste it in the bottom section
- Paste your list of plugins here (use the 'plugins' command in PocketMine-MP)

### Crashdump, backtrace or other files
- Do not paste crashdumps into an issue - please use our Crash Archive at https://crash.pmmp.io for submitting crash reports to not spam the issue tracker. Add links to your reports in the Crash Archive here.
- Please use gist or anything else to add other files and add links here

* ...

**Comment by Muqsit** [comment]
Pocketmine version?

**Comment by SuperAdam47** [comment]
4.0.0

**Comment by dktapps** [comment]
this is the reason why I disabled gd2 in the Jenkins builds...

You need to compile your own binary on the target machine using https://github.com/pmmp/php-build-scripts/blob/master/compile.sh. The Jenkins builds are linked against libraries that don't exist on older Linux distros.
