### ISSUE TITLE
MCPE-1.0: Worlds crash iOS and Android players

### ISSUE THREAD

**Issue by XFuryMCPE** [pmmp/PocketMine-MP#237]
### Issue description

I can join fine on Windows 10, but android and iOS users crash before the world loads.

### Steps to reproduce the issue

1. Generate a world (any format)
2. Try to join on Android or iOS

I have a test server that it happens on, lmk if you need a copy of the world aswell. factions.immortalspe.com : 19132

### OS and versions

* PocketMine-MP: 02ddcef24ec5d8fb189ef4ebe40a0e531baee480
* PHP: 7.0.3
* Server OS: Ubuntu
* Game version: PE

### Crashdump, backtrace or other files

* ...

**Comment by dktapps** [comment]
A copy of the world would be more helpful please.

**Comment by XFuryMCPE** [comment]
https://expirebox.com/download/fb4f4115ca1627db35819a04c2205c9a.html

**Comment by dktapps** [comment]
works fine for me locally, but I crash when joining the server you mentioned... any coordinates you can suggest? Have you also tried without plugins?

**Comment by HittmanA** [comment]
Just a question. Do you get an error in the console, something about a missing class exception in GenericChunk? I keep getting that error when I join some worlds.

**Comment by XFuryMCPE** [comment]
You spawned at 255, 66, 256 and then timed out

**Comment by dktapps** [comment]
that's exactly the coordinates I spawned at locally, and it's working perfectly locally. Please try and reproduce on a clean server without plugins.

**Comment by XFuryMCPE** [comment]
Ooh, it works without plugins, that's odd. I only have 3 plugins, devtools, factionspro and then a core with a ton of features, but that does nothing on join, I'll look into FactionsPro, it's probably doing something to crash the player

**Comment by HittmanA** [comment]
I know FactionsPro has been crashing my server. I did only bump the api though so...

**Comment by XFuryMCPE** [comment]
It seems to be the BossBar, I was making an item entity have the boss bar on join, that is probably crashing them because i removed it and now they can join fine.

**Comment by dktapps** [comment]
I'll close this then, it's clearly not a core issue.

**Comment by XFuryMCPE** [comment]
Alright, thanks

**Comment by Muqsit** [comment]
From what I've learnt from crashes, implementing the unimplemented tiles (Beacon, Dispenser etc) fixed it for my "pc-ported" worlds.

**Comment by jojoe77777** [comment]
@Muqsit read the comments?
