### ISSUE TITLE
Server Crashes

### ISSUE THREAD

**Issue by TheFixerDevelopment** [pmmp/PocketMine-MP#2373]
### Issue description

My server was fine earlier, but now, the keeps crashing, and during those periods, I have not added any new plugins and such.

- Expected result: What were you expecting to happen?
For the server to start normally
- Actual result: What actually happened?
The server crashed.

### Steps to reproduce the issue

* PocketMine-MP: 3.1.3
* PHP: php7.2
* Server OS: Hosted using a paid service
* Game version: PE/Win10 (delete as appropriate)

### Plugins
- Test on a clean server without plugins: is the issue reproducible without any plugins loaded?
As I said, this hasn’t got any relations to Plugins, as before and after the server crashes, I haven’t added anything new to the server.
If the issue is **not** reproducible without plugins:
- Have you asked for help on our forums before creating an issue?
- Can you provide sample, *minimal* reproducing code for the issue? If so, paste it in the bottom section
- Paste your list of plugins here (use the 'plugins' command in PocketMine-MP)
I can’t, as the server can’t startup. Therefore, I can’t show it.
### Crashdump, backtrace or other files
- Do not paste crashdumps into an issue - please use our Crash Archive at https://crash.pmmp.io for submitting crash reports to not spam the issue tracker. Add links to your reports in the Crash Archive here.
Server thread/CRITICAL ErrorException: "zlib_decode(): data error" (EXCEPTION) in "vendor/pocketmine/nbt/src/NBTStream" at line 104
13.08 21:52:37 [Server] Server thread/DEBUG #0 (): pocketmine\utils\Utils::errorExceptionHandler(integer 2, string zlib_decode(): data error, string phar:///custom-php7.2.phar/vendor/pocketmine/nbt/src/NBTStream.php, integer 104, array Array())
13.08 21:52:37 [Server] Server thread/DEBUG #1 vendor/pocketmine/nbt/src/NBTStream(104): zlib_decode(string )
13.08 21:52:37 [Server] Server thread/DEBUG #2 src/pocketmine/level/format/io/BaseLevelProvider(51): pocketmine\nbt\NBTStream->readCompressed(string )
13.08 21:52:37 [Server] Server thread/DEBUG #3 src/pocketmine/level/format/io/BaseLevelProvider(45): pocketmine\level\format\io\BaseLevelProvider->loadLevelData()
13.08 21:52:37 [Server] Server thread/DEBUG #4 src/pocketmine/Server(1029): pocketmine\level\format\io\BaseLevelProvider->__construct(string /worlds/world/)
13.08 21:52:37 [Server] Server thread/DEBUG #5 src/pocket
NOTE - I can’t submit the crash report to the website because it’s currently down as of posting this.
- Please use gist or anything else to add other files and add links here

* ...

**Comment by TheAz928** [comment]
invalid issue, no errors provided

**Comment by TheFixerDevelopment** [comment]
They’re errors right here. Read before commenting

**Comment by dktapps** [comment]
that's an indication your world is corrupted. I've seen a lot of things in the crash archive that result from hosts deleting worlds without unloading it first.

**Comment by TheFixerDevelopment** [comment]
So how do I fix this then?

**Comment by dktapps** [comment]
this isn't a support forum sunshine... without further evidence to the contrary, this is a support request. I hope you had backups.

**Comment by TheFixerDevelopment** [comment]
Okay..
