### ISSUE TITLE
Mined Coal Ore Drops XP Orbs with Silk Touch

### ISSUE THREAD

**Issue by Haxley** [pmmp/PocketMine-MP#2374]
### Issue description

XP orbs are dropped when coal ore is mined with silk touch. Silk touch does not drop xp orbs on any other ore. Players can dupe XP orbs by repeatedly placing and mining coal ore with silk touch.

- Expected result: What were you expecting to happen?
Mined coal ore with silk touch does not drop XP orb.

- Actual result: What actually happened?
Mined coal ore with silk touch does drop XP orbs.

### Steps to reproduce the issue

1. ... Place coal ore.
2. ... Mine with silk touch.

### OS and versions

* PocketMine-MP: 3.1.1
* PHP:
* Server OS: Linux
* Game version: PE/Win10 

### Plugins
- Test on a clean server without plugins: is the issue reproducible without any plugins loaded?
Not tested on clean server.

If the issue is **not** reproducible without plugins:
- Have you asked for help on our forums before creating an issue?
- Can you provide sample, *minimal* reproducing code for the issue? If so, paste it in the bottom section
- Paste your list of plugins here (use the 'plugins' command in PocketMine-MP)

### Crashdump, backtrace or other files
- Do not paste crashdumps into an issue - please use our Crash Archive at https://crash.pmmp.io for submitting crash reports to not spam the issue tracker. Add links to your reports in the Crash Archive here.
- Please use gist or anything else to add other files and add links here

* ...

**Comment by dktapps** [comment]
Fixed, thanks!
