### ISSUE TITLE
Class pocketmine\level\generator\GenericChunk not found

### ISSUE THREAD

**Issue by HittmanA** [pmmp/PocketMine-MP#238]
### Issue description

I am trying to use a world I downloaded but whenever I tp to it I get `Class pocketmine\level\generator\GenericChunk not found` and the server crashes. It is an mcpc world, but mcpe and mcpc use the same mcregion format so that is not the problem I do not think.

### Steps to reproduce the issue

1. Download a map
2. Upload it to server and try to join.

### OS and versions

* PocketMine-MP: 1.6.2dev-#61
* PHP: Some version of 7 (7.0.0 I think)

### Crashdump, backtrace or other files

* http://pastebin.com/fNQcRaeW

**Comment by robske110** [comment]
>THIS CRASH WAS CAUSED BY A PLUGIN

**Comment by HittmanA** [comment]
Which plugin. I see no plugin mentioned.

**Comment by dktapps** [comment]
Outdated version.

**Comment by HittmanA** [comment]
Outdated version of what?

**Comment by HittmanA** [comment]
@dktapps

**Comment by archie426** [comment]
An outdated plugin, please do not put tags in separate messages
