### ISSUE TITLE
Resetting health attribute of player does not affect health of player

### ISSUE THREAD

**Issue by DaPigGuy** [pmmp/PocketMine-MP#2384]
### Issue description

When resetting the health attribute, it does not update the health of the player, as Player::getHealth() returns the health property and not the attribute value, rendering changes to health attribute useless. Health is the only attribute in which this issue occurs.

- Expected result: Changes to health attribute set player health.
- Actual result: Changes to health attribute are sent to the player, before being reverted, as attribute change does not set health.

### Steps to reproduce the issue

1. Reset health attribute of player

### OS and versions

* PocketMine-MP: Release 3.1.4
* PHP:  7.2.7
* Server OS: Windows 10
* Game version: All Versions of MC: BE

### Plugins
- Test on a clean server without plugins: is the issue reproducible without any plugins loaded?

If the issue is **not** reproducible without plugins:
- Have you asked for help on our forums before creating an issue?
- Can you provide sample, *minimal* reproducing code for the issue? If so, paste it in the bottom section
- Paste your list of plugins here (use the 'plugins' command in PocketMine-MP)

### Crashdump, backtrace or other files
- Do not paste crashdumps into an issue - please use our Crash Archive at https://crash.pmmp.io for submitting crash reports to not spam the issue tracker. Add links to your reports in the Crash Archive here.
- Please use gist or anything else to add other files and add links here

```php        
foreach ($player->getAttributeMap()->getAll() as $attribute) {
    $attribute->resetToDefault();
}
```

**Comment by Frago9876543210** [comment]
Try `$player->sendAttributes();`

**Comment by dktapps** [comment]
why are you messing with attributes directly anyway...?

**Comment by dktapps** [comment]
I'm closing this as WF because it's not expected that plugins mess with attributes for setting health anyway. Currently the health attribute is only synced as far as it is necessary to make health work correctly on the client. It is not used internally for anything other than this.
