### ISSUE TITLE
Lava bucket disappeared when using Furnace

### ISSUE THREAD

**Issue by Adam1609** [pmmp/PocketMine-MP#2385]
### Issue description

Putting a lava bucket in the Furnace will not leave the empty bucket as in Vanilla

- Expected result: I expect that the lava bucket will turn into empty bucket like Vanilla
- Actual result: Lava bucket is gone, along with the bucket

### Steps to reproduce the issue

1. Putting the Lava Bucket inside the Furnace
2. The Lava Bucket disappeared, not leaving any trace behind

### OS and versions

* PocketMine-MP:  3.1.4 commit 17f7dc3
* PHP: 7.2
* Server OS: Windows Server 2008 R2 64-bit
* Game version: PE/Win10

### Plugins
- Test on a clean server without plugins: is the issue reproducible without any plugins loaded?

If the issue is **not** reproducible without plugins:
- Have you asked for help on our forums before creating an issue?
- Can you provide sample, *minimal* reproducing code for the issue? If so, paste it in the bottom section
- Paste your list of plugins here (use the 'plugins' command in PocketMine-MP)

### Crashdump, backtrace or other files
- Do not paste crashdumps into an issue - please use our Crash Archive at https://crash.pmmp.io for submitting crash reports to not spam the issue tracker. Add links to your reports in the Crash Archive here.
- Please use gist or anything else to add other files and add links here

* ...

**Comment by dktapps** [comment]
It doesn't look like this was ever implemented.
