### ISSUE TITLE
 water bucket does not disappear

### ISSUE THREAD

**Issue by TepBG** [pmmp/PocketMine-MP#2389]
Issue description

when using the bucket the water is placed in the block,
 but it still does not disappear from the bucket

 Steps to reproduce the issue

- when using the bucket, water does not disappear

OS and versions
PocketMine-MP: 3.1.4 commit 17f7dc3
PHP: 7.2
Server OS: CentOS 7.x
Game version: PE/Win10

Plugins
Test on a clean server without plugins: is the issue reproducible without any plugins loaded?
If the issue is not reproducible without plugins:

Have you asked for help on our forums before creating an issue?
Can you provide sample, minimal reproducing code for the issue? If so, paste it in the bottom section
Paste your list of plugins here (use the 'plugins' command in PocketMine-MP)
Crashdump, backtrace or other files
Do not paste crashdumps into an issue - please use our Crash Archive at https://crash.pmmp.io for submitting crash reports to not spam the issue tracker. Add links to your reports in the Crash Archive here.
Please use gist or anything else to add other files and add links here
...

**Comment by dktapps** [comment]
Cannot reproduce. Please test without plugins, and ensure you're actually using the version you say you are (there was a similar bug on the 4.0 dev line, which has since been fixed).
