### ISSUE TITLE
Tapping blocks count as a UseItemPacket, leads to the Unlimited Item issue

### ISSUE THREAD

**Issue by intagaming** [pmmp/PocketMine-MP#239]
### Issue description

So when you are holding nothing in the hand and tap a block, it sends a UseItemPacket (The code for debugging is attached below), which leads to Unlimited Item issue. This issue allows player to use it permanently without decrease the count of the Item. The item that I've used to reproduce this is Snowball. The snowball when I tapped the ground has been shot, while the count stack of the snowball didn't seem to decrease. So you have an unlimited amount of Snowball to kill some Blaze!

### Steps to reproduce the issue

1. Add a debug code to some kind of plugin
2. Hold a Snowball with any amount
3. Tap the ground
4. The amount isn't decreasing.

### OS and versions

* PocketMine-MP: 4ace4b9
* PHP: 7.1
* Server OS: Linux & Windows 10
* Game version: PE (Note that it won't work with W10 Edition!)

### Crashdump, backtrace or other files

```
public function debugy(DataPacketReceiveEvent $event) {
    $pk = $event->getPacket();
    if ($pk instanceof UseItemPacket) {
        echo "Kaboom";
    }
}
```

**Comment by Muqsit** [comment]
Because the UseItemPacket, by itself won't decrease the count of an item. You should code it yourself.
#Close

**Comment by Muqsit** [comment]
Also, this is an MCPE packet, very slightly (or not) modified by PocketMine.
This is a packet and not a self-made piece of code from PocketMine's.
When you say you're holding nothing, you're still holding AIR. You can add a condition statement such as...
if ($pk->item->getId() !== Item::AIR) {
//do something...
}

**Comment by archie426** [comment]
@Muqsit Can you not edit your original message?

**Comment by intagaming** [comment]
@Muqsit I don't get this bug in vanilla Minecraft PE. So what makes this bug happen? 
I'm sure Mojang not gonna look out for this.

**Comment by dktapps** [comment]
Snowballs aren't _supposed_ to decrease stack size when tapping the ground. If you want this to happen you will have to code it yourself.

**Comment by MrPowerGamerBR** [comment]
Maybe I'm reading something wrong, but isn't this a issue, because...

1. Get a snowball
2. Tap on the ground
3. The snowball is thrown, however the snowball count isn't decreased, allowing you to shoot infinite snowballs.

Because, AFAIK this isn't the vanilla behavior when you are interacting with snowballs. (I didn't test this bug, so...)

**Comment by intagaming** [comment]
@dktapps So why? The snowballs shoot but doesn't decrease the count is not a bug?

**Comment by dktapps** [comment]
It's not a bug because it doesn't happen. This is your bug, not ours.

**Comment by intagaming** [comment]
You should add a Can't reproduced next time instead of telling this is not a bug :/

**Comment by dktapps** [comment]
I should add a label when this is clearly a plugin issue? This is _your_ bug. This does not happen when running a clean server without plugins.

**Comment by archie426** [comment]
Correction: Plugins bug
