### ISSUE TITLE
Title Tick: causing console beep (^G) on Windows 10

### ISSUE THREAD

**Issue by SamJakob** [pmmp/PocketMine-MP#2391]
### Issue description

When starting the server with the PocketMine setting `console.title-tick` enabled, on a Windows machine it causes constant beeping because of the unsupported escape control characters - in this case the ^G character - and as it doesn't set the console title, what should have gone in the title ends up spamming the console.

- Expected result: What were you expecting to happen?
- Actual result: What actually happened?

### OS and versions

* PocketMine-MP:
```
[Server thread/INFO]: This server is running PocketMine-MP 3.1.4  version 274)
```
* PHP:
```
C:\>php --version
PHP 7.2.9 (cli) (built: Aug 15 2018 23:10:01) ( ZTS MSVC15 (Visual C++ 2017) x64 )
Copyright (c) 1997-2018 The PHP Group
Zend Engine v3.2.0, Copyright (c) 1998-2018 Zend Technologies
```
* Server OS:
```
C:\>ver

Microsoft Windows [Version 10.0.16299.309]
```
* Game version: PE/~~Win10~~ (delete as appropriate)

### Plugins
None

### Extra Information
![image](https://user-images.githubusercontent.com/37072691/44368179-f922f680-a4c9-11e8-8775-93b06a1224e5.png)

**Comment by dktapps** [comment]
As I recall, the title ticker is disabled by default if your terminal doesn't support it. If you've manually enabled it and it's caused this problem, then this is a WF issue since it's out of our control.

**Comment by SamJakob** [comment]
It was enabled by default. This is a fresh installation of PocketMine on a machine that I haven't used PocketMine on before.

**Comment by dktapps** [comment]
that's a pain... I expected that the `sapi_windows_vt100_support()` check would deal with this. I've never met a console that supported ANSI colour codes but not other escape codes.

**Comment by JUSTaMod** [comment]
Out of curiosity... what console are you using @SamJakob?

**Comment by SamJakob** [comment]
There, I used Windows' `cmd.exe` however I also had the issue with PowerShell, MinGW and Cygwin.

**Comment by JUSTaMod** [comment]
Huh. Yea... I don't know whats going on there. I've been unable to replicate this. Have you attempted to update windows? You are using a March 14th build. .. I know this shouldn't affect anything... but it's worth a shot.

**Comment by lukeeey** [comment]
After a quick google apparently ^G is supposed to make it beep?

**Comment by SamJakob** [comment]
@lukeeey Yeah, I mentioned that.
The problem is that it shouldn't be produced.

**Comment by lukeeey** [comment]
I'm not sure if `cli_set_process_title('title')` works on windows because it didnt work for me on Android in Termux. Just found it in the PHP docs. 
Also why cant you just execute the `title` command in for Windows?

**Comment by dktapps** [comment]
@SamJakob I just spotted a sneaky `>` readline prompt there on your console window. Please try running the server with `php PocketMine-MP.phar --disable-ansi` and try again.

ext/readline has known issues with output corruption on Windows, which is why we don't ship it with our PHP builds. You can get a proper PMMP-supported build for Windows from [here](https://ci.appveyor.com/project/pmmp/php-build-scripts/build/php-7.2-appveyor258/artifacts).

**Comment by SamJakob** [comment]
Oh interesting. Okay I'll give that a go.




Thanks, Sam Mearns







On Wed, Sep 26, 2018 at 11:51 AM +0100, "Dylan K. Taylor" <notifications@github.com> wrote:












@SamJakob I just spotted a sneaky > readline prompt there on your console window. Please try running the server with php PocketMine-MP.phar --disable-ansi and try again.


ext/readline has known issues with output corruption on Windows, which is why we don't ship it with our PHP builds. You can get a proper PMMP-supported build for Windows from here.

**Comment by dktapps** [comment]
I made a typo which you might see in the email - I meant `--disable-readline` not `--disable-ansi`.

**Comment by dktapps** [comment]
https://github.com/pmmp/PocketMine-MP/commit/d1a20ecb4a72b89b9cb92b9aa3c7682e51bef8ba makes readline disabled by default on Windows, which should solve the problem.

**Comment by SamJakob** [comment]
Ohhhh yeah that makes more sense
    	
    	

    	Get Outlook for iOS
    
  




On Wed, Sep 26, 2018 at 2:12 PM +0100, "Dylan K. Taylor" <notifications@github.com> wrote:












d1a20ec makes readline disabled by default on Windows, which should solve the problem.
