### ISSUE TITLE
Event GiveMoney on BreakBlockEvent

### ISSUE THREAD

**Issue by Magical123** [pmmp/PocketMine-MP#2398]
Hi, i need help for making an event who give player money by destroyng a Sponge block here what i'm doing:

public function onBreak(BlockBreakEvent $event) {
     
        if($event->getBlock()->getId() == 19) {
            $player = $event->getPlayer();
            $rdm = rand(1, 7);
            $player->getLevel()->addSound((new \pocketmine\level\sound\AnvilFallSound($player)), [$player]);
            $this->dropItems($event, $player, $rdm);
        }
    }
   
    public function dropItems($event, $player, $rdm){
        switch($rdm){
            case "1":
                $drop1 = array(Item::get(56, 0, 10));
                $event->setDrops($drop1);
            break;
            case "2":
                $drop1 = array(Item::get(116,0, 1),Item::get(47,0,16));
				$event->sendTip("Wow1! che fortuna!");
                $event->setDrops($drop1);
            break;
            case "3":
                $drop1 = array(Item::get(122,0,1));
                $event->setDrops($drop1);
            break;
            case "4":
                $drop1 = array(Item::get(138,0,1),Item::get(41,0,10));
                $event->setDrops($drop1);
            break;
            case "5":
                $drop1 = array(Item::get(0,0,1),Item::get(0, 0,1));
                $event->setDrops($drop1);
				$event->sendTip("Ops, sei stato sfortunato :(!");
            break;
            case "6":
                $drop1 = array(Item::get(49,0,20));
                $event->setDrops($drop1);
            break;
            case "7":
                $drop1 = array(Item::get(83,0,15));
                $event->setDrops($drop1);
            break;
			case "8":
                $drop1 = array(Item::get(52,0,1));
				$event->sendTip("Wow1! che fortuna!");
                $event->setDrops($drop1);
            break;
			case "9":
                $drop1 = array(Item::get(0,0,1));
                $event->setDrops($drop1);
				$event->
            break;
			case "10":
                $drop1 = array(Item::get(332,0,8));
                $event->setDrops($drop1);
            break;
            default:
            break;
        }
	}

**Comment by Eren5960** [comment]
Can you go to forums.pmmp.io

**Comment by Magical123** [comment]
Sure!
