### ISSUE TITLE
Enchantment: Unbreaking forgotten slot

### ISSUE THREAD

**Issue by TheAz928** [pmmp/PocketMine-MP#2399]
I've noticed, when registering "unbreaking" in Enchantment.php, there's no Enchantment::SLOT_SWORD on both primary and secondary item slots.

I think it's a very easy to fix and should be fixed.

**Comment by AkmalFairuz** [comment]
I don't know Your PocketMine-MP version

**Comment by TheAz928** [comment]
This issue is not related to game play nor features, so why should I use template?

**Comment by dktapps** [comment]
the template exists for a reason, it should always be used.

**Comment by lukeeey** [comment]
I think the issue templates are garbage. GitHub should introduce a more interactive way to create issues.
