### ISSUE TITLE
Nametag not working

### ISSUE THREAD

**Issue by AkmalFairuz** [pmmp/PocketMine-MP#2400]
I use :

    Software : PocketMine-MP 3.1.4 (Release) (Link  : https://github.com/pmmp/PocketMine-MP/releases/download/3.1.4/PocketMine-MP.phar )
    OS : Ubuntu 16.04
    PHP : 7.2
    Protocol Version : 274 // Minecraft Bedrock Edition 1.5.X
    
   *Bug*
 ```// Don't working change Nametag use PureChat or This code```
```
<?php

namespace Bug;

use pocketmine\plugin\PluginBase;
use pocketmine\event\Listener;

class Main extends PluginBase implements Listener{

public function onEnable(){
   $this->getServer()->getPluginManager()->registerEvents($this, $this);
}
public function onJoin(pocketmine\event\player\PlayerJoinEvent $event){
      $player = $event->getPlayer();
      $player->setNameTag("PocketMine");
}
}
```
If ***Player Join, NameTag not change to "PocketMine"*** and This bug not show debug to console.
Help!

**Comment by drewsucksatlife** [comment]
Client sided bug

**Comment by dktapps** [comment]
duplicate of #2387 , and indeed this is a client bug... nothing doing, sorry

**Comment by FunnyBuddys** [comment]
How should this error be client-side if it works with other server softwares such as Altay?
