### ISSUE TITLE
Leaves that disappear

### ISSUE THREAD

**Issue by CupidonSauce173** [pmmp/PocketMine-MP#2401]
Leaves that has been placed by players disappear after a time.

Pocketmine versaion 3.1.4

**Comment by CupidonSauce173** [comment]
Not if placed by a player.

**Comment by lukeeey** [comment]
That is true, the wiki confirms it

**Comment by dktapps** [comment]
there's specifically a flag that is set for player-placed leaves, they aren't supposed to decay if it's set.

I haven't had chance to test this bug yet, if someone else could independently verify (without plugins) that would be appreciated.

**Comment by JUSTaMod** [comment]
@CupidonSauce173 How long did they take to start decaying?

I've tried everything under the sun in my test server (on which I've just done a fresh install of PM) to get these to start decaying. I've been unable to replicate this with any of the types of leaves. Have I got to wait longer than 30 minutes?

**Comment by CupidonSauce173** [comment]
@JUSTaMod around 15 minutes. I was a massive tree (30-40 blocks high) with a lot of leaves.

**Comment by Sandertv** [comment]
Are you sure these were placed manually or through a world editing tool?

**Comment by dktapps** [comment]
Closing due to not reproducible and lack of response.

**Comment by SAiFGamerYT** [comment]
I also suffer from the same problem so far the leaves fall out automatically
