### ISSUE TITLE
Remove Item (In Hand)

### ISSUE THREAD

**Issue by SonsaYT04** [pmmp/PocketMine-MP#2403]
### Issue description

Removing item from hand is not working properly if you have 2 swords
For example, I have
Sword with custom name in slot 1
Normal Sword in slot 2
If I hold normal sword and remove item using
`$player->getInventory()->removeItem($player->getInventory()->getItemInHand());`
It actually remove the sword in slot 1

### Steps to reproduce the issue

1. ... Add support for removing item in hand or
2. ... Add support for removing item with custom name, id, damage, count

### OS and versions
* PocketMine-MP: PocketMine-MP 3.1.4 
* PHP: 7.2
* Server OS: Linux
* Game version: PE/Win10

### Plugins
- I only use 1 plugin that give sword with custom name and remove function

**Comment by DaPigGuy** [comment]
Just set the item in your hand to air...
