### ISSUE TITLE
Support LevelDB Format v8

### ISSUE THREAD

**Issue by MatSeifert** [pmmp/PocketMine-MP#2404]
I just rent a server for MC:PE, but since I played a lot at a local network, I did not want to start all over again, so I'd like to upload the curent map to the server. When I did so, I noticed a difference in the file structrure of the generated world and mine, but I tried anyway, because I payed the first month of the server, and they said it would be no problem to upload my map.

- Expected result: The server should start
- Actual result: The server crashed on start

### Steps to reproduce the issue

1. Copy world files from a recently generated world to PocketMine worlds folder
2. start the server

### OS and versions
* PocketMine-MP: 4.0.0
* PHP: 7.2.8
* Server OS: unspecified Linux
* Game version: Win10

### Plugins
- DevTools 1.13.0

### Crashdump, backtrace or other files
```
Error: Specified LevelDB world format version (8) is not supported by PocketMine-MP
File: src/pocketmine/level/format/io/leveldb/LevelDB
Line: 113
Type: pocketmine\level\LevelException

Code:
[104] 		$levelData = $nbt->read(\substr(\file_get_contents($this->getPath() . "level.dat"), 8));
[105] 		if($levelData instanceof CompoundTag){
[106] 			$this->levelData = $levelData;
[107] 		}else{
[108] 			throw new LevelException("Invalid level.dat");
[109] 		}
[110] 
[111] 		$version = $this->levelData->getInt("StorageVersion", INT32_MAX, \true);
[112] 		if($version > self::CURRENT_STORAGE_VERSION){
[113] 			throw new LevelException("Specified LevelDB world format version ($version) is not supported by " . \pocketmine\NAME);
[114] 		}
[115] 	}
[116] 
[117] 	protected function fixLevelData() : void{
[118] 		$db = self::createDB($this->path);
[119] 
[120] 		if(!$this->levelData->hasTag("generatorName", StringTag::class)){
[121] 			if($this->levelData->hasTag("Generator", IntTag::class)){
[122] 				switch($this->levelData->getInt("Generator")){ //Detect correct generator from MCPE data
[123] 					case self::GENERATOR_FLAT:

Backtrace:
#0 src/pocketmine/level/format/io/BaseLevelProvider(45): pocketmine\level\format\io\leveldb\LevelDB->loadLevelData()
#1 src/pocketmine/level/format/io/leveldb/LevelDB(97): pocketmine\level\format\io\BaseLevelProvider->__construct(string /home/zap370772/g47015/minecraft-pe/worlds/world/)
#2 src/pocketmine/Server(1035): pocketmine\level\format\io\leveldb\LevelDB->__construct(string /home/zap370772/g47015/minecraft-pe/worlds/world/)
#3 src/pocketmine/Server(1701): pocketmine\Server->loadLevel(string world)
#4 src/pocketmine/PocketMine(245): pocketmine\Server->__construct(BaseClassLoader object, pocketmine\utils\MainLogger object, string /home/zap370772/g47015/minecraft-pe/, string /home/zap370772/g47015/minecraft-pe/plugins/)
#5 /home/zap370772/g47015/minecraft-pe/PocketMine-MP.phar(1): require(string phar:///home/zap370772/g47015/minecraft-pe/PocketMine-MP.phar/src/pocketmine/PocketMine.php)

PocketMine-MP version: 4.0.0+dev.1409 [Protocol 274]
Git commit: 91064b32096a493781f05686b330169426cb883b
uname -a: Linux 76031 4.9.0-7-amd64 #1 SMP Debian 4.9.110-3+deb9u1 (2018-08-03) x86_64
PHP Version: 7.2.8
Zend version: 3.2.0
OS : Linux, linux

Loaded plugins:
DevTools 1.13.0 by PocketMine Team for API(s) 3.0.0, 4.0.0
```

**Comment by dktapps** [comment]
Thanks for the report. This is a known issue and not likely to be solved in the near future because of architectural changes needed to make this happen. Please see https://github.com/pmmp/PocketMine-MP/projects/7 for progress on this.

**Comment by reense** [comment]
@MatSeifert , have you found any solution to your problem? Did you downgrade your world to use another version or anything like that?

**Comment by dktapps** [comment]
Downgrading isn't possible, strictly speaking. The legacy format doesn't support everything that the new format does.

I'm planning to deal with this upgrade over the Christmas break if I can find time. However, only 4.0 will support this, which isn't expected to be released until Jan/Feb 2019.

**Comment by reense** [comment]
@dktapps  thank you for replying, looking forward to it. Since I am a PHP developer myself, I might take a look into the source code, see if I can contribute anything..

**Comment by ntwiles** [comment]
Has there been any headway here? I can't find any reference to this issue in 2020.
