### ISSUE TITLE
Iron doors don't work correctly

### ISSUE THREAD

**Issue by Cloud241** [pmmp/PocketMine-MP#2411]
When i try to place an iron door, It opens like a normal door. I can click and open it just like an oak door!
Steps to reproduce issue: Place an iron door and click/tap on it.
Version: 3.15
Edition: PE And Windows 10 (Happens on both)
Thank You!

**Comment by dktapps** [comment]
Thanks for the report. This is old but expected behaviour, since redstone isn't implemented yet. This behaviour will remain until redstone is implemented.
