### ISSUE TITLE
Script plugin classes are not loaded in AsyncTask

### ISSUE THREAD

**Issue by FaigerSYS** [pmmp/PocketMine-MP#2415]
### Issue description
When trying to access class that located in script plugin inside AsyncTask it crashes with error "Class not found". I just tried to create a simple generator using script plugin but it's not working because of this bug.

### Steps to reproduce the issue
1. Create a script plugin
2. Create AsyncTask that uses classes from script plugin (inside onRun()) and submit it

### OS and versions
* PocketMine-MP: 9553df0
* PHP: 7.2.8

### Crashdump, backtrace or other files
* Script plugin example: https://gist.github.com/FaigerSYS/b3e7717dfec1fd337bd6b75b13fb3889

**Comment by dktapps** [comment]
That's a WF. Classes are not inherited by the worker threads, and because your classes don't follow the PSR autoloader conventions, the autoloader is not able to see where the class is. You need to write a proper plugin and put the required class in a file matching its classname.
