### ISSUE TITLE
ToggleFlight does not seem to be working

### ISSUE THREAD

**Issue by FunnyBuddys** [pmmp/PocketMine-MP#2416]
### Issue description

- Expected result: Players who fly in the air should be deprived of their flight rights and fall off.
- Actual result: Player loses flight rights but can continue to fly as long as he does not touch the ground

### Steps to reproduce the issue

1. Try to Fly with the code below

### OS and versions

* PocketMine-MP: https://github.com/pmmp/PocketMine-MP/commit/9553df0f033486ce4c956c457e41ef771c310a34
* PHP: 7.2
* Server OS: Debian

### Plugins
- DoubleJump

```php 
public function onFly(PlayerToggleFlightEvent $event){
	    $player = $event->getPlayer();
            if($player->getGamemode() == 0){
               $player->setAllowFlight(false);
               $player->setFlying(false);
               $direction = $player->getDirectionVector();
               $dx = $direction->getX();
               $dz = $direction->getZ();
               $player->knockBack($player, 0, $dx, $dz, 0.6);
            }
    }
```

**Comment by Muqsit** [comment]
Why aren't you cancelling or modifying the event instead? Calling setFlying() in that event isn't right. There's already a `PlayerToggleFlightEvent::setFlying()` which will override your `setFlying()` call.

**Comment by FunnyBuddys** [comment]
I tried to cancel it before but it doesen´t work too

**Comment by dktapps** [comment]
Cannot reproduce. Blame your code.

Working:
```php
	public function onJoin(PlayerJoinEvent $event){
		$event->getPlayer()->setAllowFlight(true);
	}

	public function onToggleFlight(PlayerToggleFlightEvent $event) : void{
		$event->getPlayer()->setFlying(false);
		var_dump("double jump");
		$event->setCancelled();
	}
```
