### ISSUE TITLE
Minecraft crash when i enter the server

### ISSUE THREAD

**Issue by KnifeDev** [pmmp/PocketMine-MP#2417]
I use PHP 7.2.
I use the 1.6 PocketMine-MP (last build).
Steps to reproduce this issue:
1.Have 1.6 (last build) PMMP
2.Have 1.6 (last update from Google Play) MCPE-client
3.Enter to the server.
4.When the process of sending chunk loaded minecraft crashing.
5.I true this with and without map (empty generated map by last build) and without plugins.

**Comment by dktapps** [comment]
Thanks for the report. I've been experiencing intermittent crashes myself but I haven't been able to reproduce it directly when attempting to debug. If you could provide an address to a server which crashes you when joining, it would be appreciated.

**Comment by KnifeDev** [comment]
not server, the game crashes (minecraft client)

**Comment by dktapps** [comment]
I understood you perfectly fine. The problem is that I cannot reproduce this reliably enough to debug it.

**Comment by Eren5960** [comment]
This problem is happening to me too

**Comment by Prisane** [comment]
Windows 10 edition does not have this problem either. I think only pocket edition

**Comment by dktapps** [comment]
"me too" posts add nothing but spam to the discussion. If you don't have anything to add other than that, then don't bother.

@Prisane yes, I have observed the same. But as I said I can't reproduce it reliably enough to debug it.

**Comment by MisteFr** [comment]
iOS devices seems to not be affected too, this issue is probably client side.

**Comment by FienixEC** [comment]
IP: wafflegalaxy.com 19132
Experiencing client crash intermittently around hub(not as often) but almost everytime when switching worlds, mainly plot worlds but happens in non plot worlds as well.
No Console output other than: 
2018-08-30 [17:21:37] [Server thread/INFO]: fienix8[/73.109.116.246:55751] logged out due to timeout

Crashes started after updating to
PMMP Version: This server is running PocketMine-MP 3.2.0 for Minecraft: Bedrock Edition v1.6.0 (protocol version 282)

Hope this helps!

**Comment by iRainFlop** [comment]
The issue is only for phone edition players, most likely just android too. I haven't seen an IOS player crash from this yet on my server. Kinda fing annoying, my players keep getting mad at me

**Comment by iRainFlop** [comment]
Also sometimes Android player can actually connect, If you are experiencing this issue with your players just get them to keep trying until they get on. (usually takes 15 times max)

**Comment by FienixEC** [comment]
@Frago9876543210 could you provide link to fixed phar? i used latest release and still crash when changing worlds, please and thanks!

**Comment by dktapps** [comment]
world change crash is not related to this issue, see #2222

**Comment by FienixEC** [comment]
Thanks! @dktapps
