### ISSUE TITLE
Enchanted removes from item if held

### ISSUE THREAD

**Issue by PrimusLV** [pmmp/PocketMine-MP#242]
### Issue description

If you enchant an item and after try to hold in, the enchantment disappears.

### Steps to reproduce the issue

1. Enchant an item
2. Hold it
3. See that enchantment no longer exists on particular item

### OS and versions
* PocketMine-MP: #8902992
* PHP: -
* Server OS: -
* Game version: Both

**Comment by Muqsit** [comment]
Maybe #244

**Comment by dktapps** [comment]
I cannot reproduce this, can you provide any further details?

**Comment by Chris-Prime** [comment]
/enchant works. The issue occures when you try to enchant an issue while in creative mode.

**Comment by Chris-Prime** [comment]
More problems:
+ if you close the enchanting window too fast, the item gots thrown out
+ Some times item duplicates and original stays

**Comment by dktapps** [comment]
Enchanting tables are not implemented, that issue is not valid.

**Comment by Chris-Prime** [comment]
Exuse me. Since I was able to open it's Inventory, I assumed that it was.

**Comment by dktapps** [comment]
Closing due to lack of response and cannot reproduce.
