### ISSUE TITLE
Arrow: Server crash when saving NBT

### ISSUE THREAD

**Issue by zKoz210** [pmmp/PocketMine-MP#2420]
### Issue description
Server crash when saving NBT

### Steps to reproduce the issue
To be honest, I can't write an exact algorithm to reproduce the problem, but it has something to do with the new enchantments (Flame?) of items (Bow)

### OS and versions
* PocketMine-MP: https://github.com/pmmp/PocketMine-MP/commit/f466fd55686a3af79e154931af25f5e4aa80643b
* PHP: 7.2.9
* Server OS: CentOS 7
* Game version: PE/Win10

### Plugins
- Test on a clean server without plugins

### Crashdump, backtrace or other files
Crashdump: https://gist.github.com/zKoz210/c9c802aa75924126cc57e15847e9195c

**Comment by dktapps** [comment]
This crashdump is incomplete, plugins list is missing and crash.pmmp.io is full of near-identical crashdumps, none reproducible with a clean server.

**Comment by dktapps** [comment]
(yes, I have spent months trying to find the cause of this issue and concluded that this cannot and does not happen without plugins, so go check them... TeaSpoon is a common culprit.)

**Comment by zKoz210** [comment]
@dktapps I found the problem

Use this to debug:
```
	public function setOnFire(int $seconds) : void{
		$ticks = $seconds * 20;
		if($ticks > $this->fireTicks){
			$this->fireTicks = $ticks;
		}

		$this->setGenericFlag(self::DATA_FLAG_ONFIRE, true);

		if($this->fireTicks >= 1081873){
			throw new Exception("Value $this->fireTicks is too large!");
		}
	}
```

```
[Server thread/CRITICAL]: Exception: "Value 1082000 is too large!" (EXCEPTION) in "src/pocketmine/entity/Entity" at line 1064
[Server thread/DEBUG]: #0 src/pocketmine/item/Bow(82): pocketmine\entity\Entity->setOnFire(integer 54100)
[Server thread/DEBUG]: #1 src/pocketmine/Player(2593): pocketmine\item\Bow->onReleaseUsing(pocketmine\Player object)
```

Bow.php (60 line):

```
$nbt->setShort("Fire", $player->isOnFire() ? 45 * 60 : 0);
```
Result: 2700

Bow.php (82 line):

```
$entity->getFireTicks() * 20 + 100
```
Result: 54100

```
	public function setOnFire(int $seconds) : void{
		$ticks = $seconds * 20;
		if($ticks > $this->fireTicks){
			$this->fireTicks = $ticks;
		}

		$this->setGenericFlag(self::DATA_FLAG_ONFIRE, true);
	}
```
Result: 1082000

**Comment by dktapps** [comment]
It is intended to be +100 seconds, but it appears I forgot that `setOnFire()` accepts seconds and not ticks... I must have been tired when I wrote that code...
