### ISSUE TITLE
Server is Randomly crashing with no errors at all.

### ISSUE THREAD

**Issue by AlexPads** [pmmp/PocketMine-MP#2431]
### Steps to reproduce the issue

1. ...i did nothing just added the new phar put up today 3.2.3
2. ...

### OS and versions

* PocketMine-MP: 3.2.3
* PHP: 7.2
* Server OS: Linux
* Game version: Win10 6.0.0

### Plugins
- Test on a clean server without plugins: is the issue reproducible without any plugins loaded?

this issue was occurring without any plugins!!!

* ...

**Comment by dktapps** [comment]
this is a very undescriptive issue... without more detail and/or reproducing steps this cannot be solved. I'm closing this until more information is provided.
