### ISSUE TITLE
Attempted to tick a level which has been closed = crashed

### ISSUE THREAD

**Issue by CaptainDuck** [pmmp/PocketMine-MP#2434]
### Issue description

Server crashes when someone gets kicked for 'flying'.
Error given before crash:
````
14.09 04:48:06 [Server] Server thread/INFO ClearEcho1[/172.116.102.224:54684] logged out due to Kicked by admin. Reason: Flying is not enabled on this server 14.09 04:48:06 [Server] Server thread/CRITICAL Level "world" was unloaded during a tick 14.09 04:48:06 [Server] Server thread/CRITICAL InvalidStateException: "Attempted to tick a Level which has been closed" (EXCEPTION) in 
````
This ain't good for production servers.

- Expected result: Player was kicked and server didn't crash.
- Actual result: Server crashed.

### Steps to reproduce the issue

1. Download a Fly plugin. When people are pvping, the plugin will then disable the player's fly ability then the server kicks the player for flying.
2. I have a SkyBlock plugin that when all the members of the island are not there, the level unloads or closes.
3. Then the error, 'Attempted to tick a level which has been closed.'
4. I really think this is bad and if you can, I hope we can configure if the server crashes when the error starts.

### OS and versions

* PocketMine-MP:  3.2.3
* PHP: 7.2.8
* Server OS:
* Game version: PE/Win10 (delete as appropriate)

### Plugins
- Test on a clean server without plugins: is the issue reproducible without any plugins loaded?

If the issue is **not** reproducible without plugins:
- Have you asked for help on our forums before creating an issue?
- Can you provide sample, *minimal* reproducing code for the issue? If so, paste it in the bottom section
- Paste your list of plugins here (use the 'plugins' command in PocketMine-MP)

### Crashdump, backtrace or other files
- Do not paste crashdumps into an issue - please use our Crash Archive at https://crash.pmmp.io for submitting crash reports to not spam the issue tracker. Add links to your reports in the Crash Archive here.
- Please use gist or anything else to add other files and add links here

* ...

**Comment by dktapps** [comment]
This occurs when you unload the level during a level tick (for example when an event fires). You should use a delayed task to avoid this. See #1527 .
