### ISSUE TITLE
Half-doors can be placed at y=255

### ISSUE THREAD

**Issue by dktapps** [pmmp/PocketMine-MP#2441]
### Issue description
![image](https://user-images.githubusercontent.com/14214667/45598078-af94d100-b9cd-11e8-9d13-b7f4947f3ebb.png)

This is an image of /setblock in vanilla, but the same effect can be produced by using a door item at y=255 where there isn't enough space for the top half of the door.

When opening the door, the game crashes. With that said, it shouldn't be possible to place a door up here anyway.

### Steps to reproduce the issue
1. create a platform of blocks at y=254
2. place a door at y=255
3. notice a half-door is created

### OS and versions
* PocketMine-MP: f7f06c993d908b714feb3b10dd92a1f5b0bcad2b
* PHP: 7.2.9
* Server OS: windows

**Comment by QimieGames** [comment]
It is possible to make a check on place? Like check whats the coords of the door is placed at. If its 255. then just cancel event for the placement. Just asking. Im new to this community

**Comment by dktapps** [comment]
It's possible but not the best solution, since every double block would have to have such a check (double tallgrass and tall flowers for example), so this isn't a good solution..
