### ISSUE TITLE
Falling blocks don't drop on some fence-like blocks.

### ISSUE THREAD

**Issue by matcracker** [pmmp/PocketMine-MP#2449]
### Issue description

When you place a falling block on the top of a fence-like block, it doesn't drop the falling block.

- Expected result: Falling block dropped
- Actual result: Falling block not dropped, bugged in air.

### Steps to reproduce the issue

1. Place a falling block two blocks above the fence-like blocks (e.g. fence gates, fences)/ with height > 1.0

### OS and versions
* PocketMine-MP: 3.2.3
* PHP: 7.2
* Server OS: Windows/Linux
* Game version: PE/Win10

**Comment by dktapps** [comment]
This is a peculiar bug. What appears to be happening is:
- Falling block falls, lands on top of fence
- Block above fence block + 1 gets set to block
- Block falls again
- repeat process.

The bug here is that the wrong block is getting set when a falling block lands on top of a fence.

**Comment by dktapps** [comment]
This appears to have been caused by some changes I made to support concrete powder correctly.
