### ISSUE TITLE
I found a bug? Can you fix it?

### ISSUE THREAD

**Issue by refly2119** [pmmp/PocketMine-MP#2451]
[https://files.fm/down.php?cf&i=asbwyhfs&n=Thu_Sep_20-06.50.57-WIB_2018.log](url)

**Comment by SOF3** [comment]
Without knowing your PocketMine-MP version, OS, PHP, Client version, or plugins and how the issue occurred, the issue cannot begin to be solved.
A pre-formatted template is provided that shows the required information to begin to find, test and solve an issue.
Until the adequate template and information is provided, the issue will be closed; it may be reopened if you update the ticket with the correct template and required information.

[Contribution guidelines](https://github.com/pmmp/PocketMine-MP/blob/master/CONTRIBUTING.md)

**Comment by refly2119** [comment]
I have given the log file the crash!

**Comment by jasonwynn10** [comment]
@refly2119 click on that link you sent 🤦‍♂️

**Comment by dktapps** [comment]
This bug will be solved by the upcoming 3.1.8 and 3.2.4 patch updates.
