### ISSUE TITLE
Detected spam

### ISSUE THREAD

**Issue by barbraPuffs** [pmmp/PocketMine-MP#2458]
Betty - mi daughter, new parent with recent born baby named "betatititada" !
Babroos - Betty's puppy
Barbra - Me, Betties mom
Bert - Betty's dad
Bobo - Betty's brother

together , we are interested in blogging on the GitHub issue tracker for pmmp server software . we recently discover old pocketmine died, so we have did the migration . non profit pump for all !

**Comment by drewsucksatlife** [comment]
Hi betty’s mom, are you single?

**Comment by barbraPuffs** [comment]
Hi betty’s mom, are you single?

**Comment by barbraPuffs** [comment]
oops

**Comment by barbraPuffs** [comment]
@drewsucksatlife NO FUCK I AM NOT
