### ISSUE TITLE
Arrows do not light on fire by Fire

### ISSUE THREAD

**Issue by jasonwynn10** [pmmp/PocketMine-MP#2467]
### Issue description

When firing an arrow through a fire block, the arrow does not become lit.

- Expected result: The arrow lights on fire.
- Actual result: The arrow did not light on fire.

### Steps to reproduce the issue

1. Fire arrow through fire block

### OS and versions

* PocketMine-MP: This server is running PocketMine-MP 3.2.4+dev for Minecraft: Bedrock Edition v1.6.0 (protocol version 282)
* PHP: 7.2.9
* Server OS: Windows
* Game version: PE/Win10

### Plugins
- Test on a clean server without plugins: is the issue reproducible without any plugins loaded? Yes

If the issue is **not** reproducible without plugins:
- Have you asked for help on our forums before creating an issue?
- Can you provide sample, *minimal* reproducing code for the issue? If so, paste it in the bottom section
- Paste your list of plugins here (use the 'plugins' command in PocketMine-MP)

### Crashdump, backtrace or other files
- Do not paste crashdumps into an issue - please use our Crash Archive at https://crash.pmmp.io for submitting crash reports to not spam the issue tracker. Add links to your reports in the Crash Archive here.
- Please use gist or anything else to add other files and add links here

The issue can be traced back to this piece of code which directly prevents arrows from lighting on fire.
https://github.com/pmmp/PocketMine-MP/blob/release/3.2/src/pocketmine/block/Fire.php#L69L71

**Comment by dktapps** [comment]
This is not a bug. From the [wiki](https://minecraft.gamepedia.com/Arrow):

> Arrows shot through lava **(but not fire)** will catch on fire and show an appropriate animation until they pass through water. Like arrows shot from a bow with the Flame enchantment, they can set other entities they hit on fire for 5 seconds and ignite TNT.

**Comment by dktapps** [comment]
If you had looked at the blame for the code you wanted to remove, you would have found [this commit](https://github.com/PocketMine/PocketMine-MP/commit/0b06a4f70392a51d41aad58cacb7f36e5059d846).

**Comment by jasonwynn10** [comment]
👌 My mistake
