### ISSUE TITLE
It does not work FloatingTextParticle

### ISSUE THREAD

**Issue by ProCOmpTEAM** [pmmp/PocketMine-MP#247]
```
FloatingText shown only in one place. It should be within.
I checked a few plugins and your own code - does not work.
```

What do you advise?

### OS and versions
* PocketMine-MP: 1.0.0
* PHP: 7
* Server OS: Windows 10
* Game version: PE

**Comment by robske110** [comment]
Please elaborate further, I cannot make any sense out of your description.

**Comment by dktapps** [comment]
Not reproducible, I was literally testing this yesterday and had no such issues. (Damn things got annoying actually since I hijacked PlayerInteractEvent, they were _everywhere_...)

**Comment by ProCOmpTEAM** [comment]
@robske110 The core of the latest build. Can tell me what to do?
On one map several particles do not work. Only one. Plugins MyTag, aFloatTexts and others are working only in one place. It made me also work.

**Comment by ProCOmpTEAM** [comment]
@robske110 world is MCRegion - Flat

**Comment by archie426** [comment]
How many times? Why write multiple messages about the same thing?

**Comment by ProCOmpTEAM** [comment]
@archie426 it's first in this repository. Now I use official PocketMine-MP API.

**Comment by archie426** [comment]
@ProCOmpTEAM How do you mean, 'first in this repository', I am not talking about the API at all.....
