### ISSUE TITLE
pmmp game breaking bug 

### ISSUE THREAD

**Issue by Croc3ll** [pmmp/PocketMine-MP#2476]
### Issue description

having any spawn plugin will make the world not load properly after dying 

- Expected result: What were you expecting to happen?
- Actual result: What actually happened?

### Steps to reproduce the issue

1. ... any setspawn plugin
2. ... kill yourself where spawn is 

### OS and versions

* PocketMine-MP: 
* PHP:
* Server OS:
* Game version: PE/Win10 (delete as appropriate)

### Plugins
- Test on a clean server without plugins: is the issue reproducible without any plugins loaded?

If the issue is **not** reproducible without plugins:
- Have you asked for help on our forums before creating an issue?
- Can you provide sample, *minimal* reproducing code for the issue? If so, paste it in the bottom section
- Paste your list of plugins here (use the 'plugins' command in PocketMine-MP)

### Crashdump, backtrace or other files
- Do not paste crashdumps into an issue - please use our Crash Archive at https://crash.pmmp.io for submitting crash reports to not spam the issue tracker. Add links to your reports in the Crash Archive here.
- Please use gist or anything else to add other files and add links here

* ...
![image](https://user-images.githubusercontent.com/36170420/46639599-250b4180-cb35-11e8-8193-6000771397c3.png)

**Comment by iZeaoGamer** [comment]
You need to fill out the correct format. As you can see here, you haven’t written it out fully.

**Comment by dktapps** [comment]
This is not a plugin support forum. If you're reporting a core issue triggered by a plugin, code samples are required.

**Comment by kenygamer** [comment]
@dktapps I've also had that bug. It ocurrs when you teleport a player at the time of respawn. The only solution to this that worked for me, was something similar I did when I need to send forms on player join: delay the action by two or three seconds.

**Comment by Nerahikada** [comment]
I solved this in this way; teleport the player far away and then return.
