### ISSUE TITLE
Server crash when joining.

### ISSUE THREAD

**Issue by FreeGamingHere** [pmmp/PocketMine-MP#2478]
### Issue description

- Expected result: Join the server.
- Actual result: Server crashed dropping an error.

### Steps to reproduce the issue

1. Join the server.

### OS and versions

* PocketMine-MP: This server is running PocketMine-MP 4.0.0+dev.1551 for Minecraft: Bedrock Edition v1.6.0 (protocol version 282)
* PHP: 7.2
* Server OS: Linux

### Plugins
- Test on a clean server without plugins: is the issue reproducible without any plugins loaded?

If the issue is **not** reproducible without plugins:
- Have you asked for help on our forums before creating an issue?
- Can you provide sample, *minimal* reproducing code for the issue? If so, paste it in the bottom section
- Paste your list of plugins here (use the 'plugins' command in PocketMine-MP)

I tested that without any plugin installed.

### Crashdump, backtrace or other files
- Do not paste crashdumps into an issue - please use our Crash Archive at https://crash.pmmp.io for submitting crash reports to not spam the issue tracker. Add links to your reports in the Crash Archive here.
- Please use gist or anything else to add other files and add links here
https://pastebin.com/csvU4ZcL
* ...

**Comment by dktapps** [comment]
The latest build is 1554. Did you think to try an updated build before creating an issue?

**Comment by FreeGamingHere** [comment]
I was not able to change the build. Thank you for your time.
