### ISSUE TITLE
Issue caused when closing Minecraft on IOS

### ISSUE THREAD

**Issue by JUSTaMod** [pmmp/PocketMine-MP#2479]
**Description:**
Closing down out of the Minecraft app completely while in my server on iOS crashes my account on Win10. (Intermittently - I find this kind of hard to reproduce, but once it does - it happens every time.) This then causes issues when trying to rejoin the server - my iOS account could join back after a few minutes, but I still can't join 15 minutes later on Win10. Even after restarting the server.

*One thing to note - I could ONLY reproduce this with my own servers. For a leet server (on an older version of PM) leaving did not crash my Win10 client.

**How to Reproduce:**
Again - hard to make happen the first time which is odd.

Join on Win10 first.
Join using an iOS device and close out of the app relatively quickly.
Maybe the Win10 client will crash.

**OS and versions**

* PocketMine-MP: 3.2.4
                              4.0.0+dev.1554
* PHP: 7.2.11 (cli) (built: Oct 10 2018 02:04:04)
* Server OS: Microsoft Windows [Version 10.0.14393] (DataCenter)
                    Microsoft Windows [Version 10.0.17134.345] (Enterprise)
* Game version: Win10

**Plugins**
Tested on clean and not clean servers. Affects all.

Creates no console stuffs.

**Comment by dktapps** [comment]
All clients are rather unstable today, so this is hardly surprising, and nor would I be sure that the issue is caused by PM.

If you are sure it's a PM issue, then a set of affected versions would be helpful so that this can be checked.
Additionally, it would be most helpful if you can get the Android version to crash - we can't debug crashes produced by any other version because they don't have symbols, so their crashdumps can't be decoded.

**Comment by JUSTaMod** [comment]
An update on this - I was able to consistently reproduce this. the iOS character needs to be VERY close to the Win10 player - like half a block away. 

_Not sure if this is helpful, but heres what VS tells me about the client crash - and what line it happened on._

Unhandled exception at 0x00007FF9F0914623 (d3d11.dll) in Minecraft.Windows.exe: 0xC0000005: Access violation reading location 0xFFFFFFFFFFFFFFFF.

00007FF9F0914623 49 8B 50 10          mov         rdx,qword ptr [r8+10h] 

IDK. At this point that flys far over my head.

**Comment by dktapps** [comment]
Nope, VS is unhelpful without debugging symbols. That's why I asked for it to be reproduced on the Android version.

**Comment by JUSTaMod** [comment]
This isn't PM's problem. Just tested this on a LAN game. I should have tested that first now that I think about it. Sorry!
