### ISSUE TITLE
Performance issue with sendRecipeList.

### ISSUE THREAD

**Issue by xxFlare** [pmmp/PocketMine-MP#248]
### Issue description
This function is taking too long to execute when players join the game (by default, not from plugin).
https://github.com/pmmp/PocketMine-MP/blob/master/src/pocketmine/Server.php#L2169

You can confirm this with timings.

It seems steadfast fixed the problem with this solution:
https://github.com/Hydreon/Steadfast2/blob/master/src/pocketmine/Server.php#L2337

### Steps to reproduce the issue
1. Turn on server.
2. Run /timings on
3. Join and leave multiple times.
4. paste timings

You can then see it takes a significant amount of time to execute.

### OS and versions
* PocketMine-MP: https://github.com/pmmp/PocketMine-MP/commit/57f3f9b4edd117fac180c8c468a73d1b1eb7fc9d
* PHP: 7.0.3
* Server OS: Linux
* Game version: PE

**Comment by dktapps** [comment]
maybe, but there's one large and unfortunate flaw with caching it like that. One word: _plugins_.

**Comment by dktapps** [comment]
I do not trust your observation of the supposed "1.4" codebase. Steadfast2 is not PocketMine-MP 1.4, it is _BASED_ on 1.4. I expect evidence that this actually existed in PocketMine.

If it did, it also raises the question of: why was it removed? Plugin problems aside, if caching the packet has such a significant performance benefit, there has to be a reason why it was removed.

**Comment by robske110** [comment]
I just did a little bit of research as to if it existed, and found out that it did never.  The packet was introduced in 0.12 and there was never a cache.

**Comment by dktapps** [comment]
https://github.com/Hydreon/Steadfast2/commit/81d4b063e3dfc24904811c622464338180cd54a4

You would do better to check your facts before commenting.

**Comment by dktapps** [comment]
It's also a well-known fact that player joins are one of the most resource-intensive times for PocketMine, due to various things including chunk sending, permissible calculation and various other things. Timings of join/quit mean nothing, since there is so much happening on player join that this will go unnoticed.

**Comment by xxFlare** [comment]
@dktapps You should be able to see the timings for this packet by clicking more results on the timings page.

How about deleting the cache after the plugin modifies a recipes?

And yes, you are correct. It was not in PocketMine, I assumed incorrectly.

**Comment by dktapps** [comment]
I performed some tests locally, and discovered that creating this packet takes 80-90 ms on my device. While my test subject is relatively underpowered, the results are somewhat alarming. If you have a big server with lots of players continually coming and going, this really would hurt performance.
