### ISSUE TITLE
ItemFactory makes Unknown Item

### ISSUE THREAD

**Issue by Nerahikada** [pmmp/PocketMine-MP#2483]
### Issue description
Items such as TieredTool and Durable will be unknown item.
These items are not working.

### Steps to reproduce the issue

1. Use a item(tool).
2. Change slot of item.

### OS and versions
* PocketMine-MP: e52b1142bc6d73eadcc0c87a26f9940476e8a1ff
* PHP: 7.2.8
* Server OS: Windows and Linux
* Game version: PE and Win10

### Plugins
- Test on a clean server without plugins: is the issue reproducible without any plugins loaded?

If the issue is **not** reproducible without plugins:
- Have you asked for help on our forums before creating an issue?
- Can you provide sample, *minimal* reproducing code for the issue? If so, paste it in the bottom section
- Paste your list of plugins here (use the 'plugins' command in PocketMine-MP)

### Crashdump, backtrace or other files
- Do not paste crashdumps into an issue - please use our Crash Archive at https://crash.pmmp.io for submitting crash reports to not spam the issue tracker. Add links to your reports in the Crash Archive here.
- Please use gist or anything else to add other files and add links here

* ...

**Comment by Nerahikada** [comment]
https://github.com/pmmp/PocketMine-MP/blob/master/src/pocketmine/item/ItemFactory.php#L350
This happens because the tool damage is not in $sublist[].

**Comment by dktapps** [comment]
Fixed, thanks.
