### ISSUE TITLE
When the computer is forcibly shut down, levels becomes corrupted

### ISSUE THREAD

**Issue by Yexeed** [pmmp/PocketMine-MP#2484]
### Issue description
- Expected result: Levels not becomes corrupted (or some chunks gets corrupted), i can load server again with no crashes
- Actual result: Levels becomes corrupted, i can't load server again without crash

### Steps to reproduce the issue
1. Load level (ex. default world)
2. Force your computer to shut down (not recommended)
3. After starting up, try to load server

### OS and versions
* PocketMine-MP: 3.3.0 release 
* PHP: 7.2.9
* Server OS: Windows 10 (1803)
* Game version: Win10 1.7.0

### Plugins
- Empty

### Crashdump, backtrace or other files
- I can't paste my crdump to crash.pmmp.io (teapot error), so i pasted it to hastebin: [here](https://hastebin.com/gavuqiboto.cs)

**Comment by dktapps** [comment]
What did you expect to happen? Would you be so blase about shutting your computer down forcibly during a system update?

**Comment by 95CivicSi** [comment]
Depending on what was happening when you lost power, you may be able to just recreate the level.dat file to get the world to load.  Usually, even when you do this, there will be missing or corrupted chunks.

Good luck.
