### ISSUE TITLE
AddTitle bug

### ISSUE THREAD

**Issue by skilastic** [pmmp/PocketMine-MP#2486]
When a title sends over and over when in a onRun function, It looses the bottom title and the top part of the title stays.

First title...
Top: Starting
Bottom: 5

Then title 2...
Top: Starting
Bottom: 

If this is a bug, that's good to hear.
thanks

**Comment by dktapps** [comment]
Without knowing your PocketMine-MP version, OS, PHP, Client version, or plugins and how the issue occurred, the issue cannot begin to be solved.
A pre-formatted template is provided that shows the required information to begin to find, test and solve an issue.
Until the adequate template and information is provided, the issue will be closed; it may be reopened if you update the ticket with the correct template and required information.

[Contribution guidelines](https://github.com/pmmp/PocketMine-MP/blob/master/CONTRIBUTING.md)

**Comment by skilastic** [comment]
I was on the latest version :(

**Comment by skilastic** [comment]
This server is running PocketMine-MP 3.3.0 for Minecraft: Bedrock Edition v1.7.0 (protocol version 291)

**Comment by skilastic** [comment]
Gee, thanks for the help :/

**Comment by jasonwynn10** [comment]
> I was on the latest version :(
You missed the point. There is an issue template already in the text box when you go to create an issue. You need to fill that out so we can get all the needed information to help you

**Comment by skilastic** [comment]
I created another issue and rewrote it. I has all the information you need to fix

**Comment by skilastic** [comment]
its called subtitle bug
