### ISSUE TITLE
Subtitle Bug Rewritten

### ISSUE THREAD

**Issue by skilastic** [pmmp/PocketMine-MP#2487]
when most minigames run on my server, Titles are sometimes in the run function. When a title sends more then 1 time, it looses its subtitle.

This bug is present on all Operating systems.
I'm using a bedwars plugin, but I know that its not the issue.
I'm running Minecraft Bedrock Edition 1.7.0 latest. 
The pocketmine version is PocketMine-MP 3.3.0 for Minecraft: Bedrock Edition v1.7.0 (protocol version 291)
php version is 7.2

thanks.

**Comment by TheAz928** [comment]
I can confirm that it happens

**Comment by dktapps** [comment]
Please provide reproducing code.

**Comment by skilastic** [comment]
Im not near my computer, please wait.

**Comment by skilastic** [comment]
public function onRun($currentTick) {
  
        foreach ($this->getPlugin()->game as $group => $key) {
           
            $signcoord = $this->getPlugin()->game[$group]["sign"];
            $sign = $this->getPlugin()->getServer()->getLevelByName($signcoord["levelName"])->getTile(new Vector3($signcoord["x"], $signcoord["y"], $signcoord["z"]));
            $status = $this->getPlugin()->api->getStatus($group);
            if ($status == "lobby") {
                $status = "§aWaiting§r";
            } elseif ($status == "game") {
                $status = "§cIn Game§r";
            }
             $sign->setText("§d§lBEDWARS", "§b " . $group, $status, "§d§l" . $this->getPlugin()->api->getArenaPlayerCount($group) . "/" . $this->getPlugin()->api->getArenaPlayerMaxCount($group));
            if ($this->getPlugin()->api->getStatus($group) == "lobby") {
                if ($this->getPlugin()->api->getArenaPlayerCount($group) >= $this->getPlugin()->game[$group]["minP"]) {
                    $lobbycountdown = $this->getPlugin()->game[$group]["lobbyCountDown"];
                    if ($lobbycountdown > 0) {
                        foreach ($key["players"] as $pl) {
                            $player = $this->getPlugin()->getServer()->getPlayer($pl);
                            if ($lobbycountdown <= 5) {
                                $player->getLevel()->addSound(new PopSound(new Vector3($player->getX(), $player->getY(), $player->getZ())), null);
                                $player->addTitle(C::YELLOW . $lobbycountdown . C::RESET, Main::PREFIX);
                            } else {
                                if ($lobbycountdown == 20) {
                                    $player->sendMessage(Main::PREFIX . "20 seconds left");
                                } elseif ($lobbycountdown == 10) {
                                    $player->sendMessage(Main::PREFIX . "10 seconds left");
                                }
                                $player->addTitle("§7Starting§r", Main::PREFIX, 200);
                            }
                        }
                        $this->getPlugin()->game[$group]["lobbyCountDown"] --;
                    } else {
                        $this->getPlugin()->api->startMatch($group);
                    }
                } else {
                    foreach ($key["players"] as $pl) {
                        $player = $this->getPlugin()->getServer()->getPlayer($pl);
                        $player->addTitle("§7Waiting for players§r", Main::PREFIX, 200);
                    }
                    $this->getPlugin()->game[$group]["lobbyCountDown"] = 20;
                }

**Comment by skilastic** [comment]
Heres the code.

**Comment by TheAz928** [comment]
@dktapps can be reproduced by adding subtitle and title to a player via repeating task.

This issue doesn't seem to appear when old-sent title has been vanished/disappeared

**Comment by dktapps** [comment]
Well, there's nothing I can do about that... sorry, nothing doing.

**Comment by TheAz928** [comment]
If old title was still displaying and sent a new one, this happens (to be more specific)
