### ISSUE TITLE
BlockFactory may not be initialized when a LightPopulationTask is run

### ISSUE THREAD

**Issue by dktapps** [pmmp/PocketMine-MP#2488]
### Issue description
Since the changes to make the generator not be initialized until needed now, LightPopulationTask may silently produce wrong results due to the BlockFactory not being initialized, since it previously allowed GeneratorRegisterTask to do this on its behalf. This was not noticed until now because PHP doesn't mind doing array access on null variables and doesn't bother to warn about it.

### Steps to reproduce the issue
1. have a world with no light saved
2. load some chunks without generating chunks prior

**Comment by drewsucksatlife** [comment]
oof
