### ISSUE TITLE
Shutdown hangs at "Stopping CommandReader thread" on some systems

### ISSUE THREAD

**Issue by dktapps** [pmmp/PocketMine-MP#25]
### Issue description

On Windows, shutdown will hang at "Stopping CommandReader thread" until another input is received, such as hitting the Enter key.
### Why this happens

`stream_set_blocking()` does not work on Windows. This results in the `fgets()` call to stdin to block the thread until another input is received. This issue does not occur on Linux as far as I can tell.
### Possible solutions

This is a rather difficult problem to resolve cleanly. Since `Thread::kill()` was removed from pthreads in v3, the thread cannot be forcefully killed.
I have made a previous attempt to resolve this with an implementation using `stream_select` which _also_ fails on Windows (returns 1 when no streams have changed >:-[)
### Steps to reproduce the issue

1. Shut down a PocketMine server on Windows using /stop
### OS and versions

- PocketMine-MP: https://github.com/pmmp/PocketMine-MP/commit/2fba1073ddf4965eb5d2bbbbbfb4a5c5f9377db3
- PHP: 7.0+
- OS: Any Windows version
### References

https://github.com/PocketMine/PocketMine-MP/issues/3990
https://bugs.php.net/bug.php?id=34972

**Comment by iPocket** [comment]
I've already reported that to @PEMapModder before in Feb :P

**Comment by PrimusLV** [comment]
Can't we just fake the input?

**Comment by dktapps** [comment]
@PrimusLV I tried, it either fails or segfaults.

**Comment by TDMidkwhatisxd** [comment]
Confirmed on linux too

**Comment by robske110** [comment]
I don't have this in macosx, can't believe this happening on linix

**Comment by TDMidkwhatisxd** [comment]
It happens on centos! If i stop server , i need to write a letter and submit , to stop! Didnt try to simply press enter xd!

**Comment by legoboy0215** [comment]
This strangely doesn't happen to me.

**Comment by robske110** [comment]
So me.

**Comment by TDMidkwhatisxd** [comment]
On genisys , this does not happens to me ;)

**Comment by archie426** [comment]
@TDMidkwhatisxd Please do not advertise Nukkit here.

**Comment by dktapps** [comment]
THIS IS NOT A FORUM. Continue to treat it as one and bans will start getting handed out.

**Comment by dktapps** [comment]
Reproduced on other platforms (circumstances unknown).

**Comment by Muqsit** [comment]
This doesn't happen when I use the php binary folder @ /use/local/bin/php

Only happens when I use the downloaded (traditional php-build-scripts' generated) binary (bin) folder...atleast for me.

**Comment by Falkirks** [comment]
`stream_set_blocking()` only works on Mac and maybe some Linux versions, but it is mainly a Mac thing. We had a discussion about this a while ago.

**Comment by robske110** [comment]
https://github.com/robske110/pmmp-PocketMine-MP/commit/91d63dafc1ee4bdc18163d1947f559b28e2bf2c8
Maybe just a hack for not waiting so long for the logger?

**Comment by dktapps** [comment]
Found the cause of the `stream_select` issue, seems to be a MINTTY bug. Running in PowerShell or CMD it works perfectly.

**Comment by dktapps** [comment]
Correction: not a MINTTY bug, just bad implementation. PHP CLI sees MINTTY as a pipe instead of an actual console. Reference: https://github.com/mintty/mintty/issues/56
