### ISSUE TITLE
Memory Leak

### ISSUE THREAD

**Issue by mal0ne-23** [pmmp/PocketMine-MP#250]
### Issue description

Random server freezes, haven't found the cause

### Steps to reproduce the issue
I don't know.. It just randomly happens

### OS and versions

* PocketMine-MP: 7.0.3
* PHP: 7.0.3
* Server OS: Ubuntu
* Game version: PE and Win10

### Crashdump, backtrace or other files

* PocketMine-MP Crash Dump Wed Jan 11 16:32:24 EST 2017

Error: Allowed memory size of 1073741824 bytes exhausted (tried to allocate 4096 bytes)
File: /src/pocketmine/level/Level
Line: 1250
Type: E_ERROR

Code:
[1241] 		$index = Level::blockHash($pos->x, $pos->y, $pos->z);
[1242] 		if($cached and isset($this->blockCache[$index])){
[1243] 			return $this->blockCache[$index];
[1244] 		}elseif($pos->y >= 0 and $pos->y < $this->provider->getWorldHeight() and isset($this->chunks[$chunkIndex = Level::chunkHash($pos->x >> 4, $pos->z >> 4)])){
[1245] 			$fullState = $this->chunks[$chunkIndex]->getFullBlock($pos->x & 0x0f, $pos->y & Level::Y_MASK, $pos->z & 0x0f);
[1246] 		}else{
[1247] 			$fullState = 0;
[1248] 		}
[1249] 
[1250] 		$block = clone $this->blockStates[$fullState & 0xfff];
[1251] 
[1252] 		$block->x = $pos->x;
[1253] 		$block->y = $pos->y;
[1254] 		$block->z = $pos->z;
[1255] 		$block->level = $this;
[1256] 
[1257] 		return $this->blockCache[$index] = $block;
[1258] 	}
[1259] 
[1260] 	public function updateAllLight(Vector3 $pos){

Backtrace:
#0 (): pocketmine\Server->crashDump(boolean)

PocketMine-MP version: 1.6.2dev #0 [Protocol 100; API 2.0.0]
Git commit: 0000000000000000000000000000000000000000
uname -a: Linux vps103390 4.4.0-57-generic #78-Ubuntu SMP Fri Dec 9 23:50:32 UTC 2016 x86_64
PHP Version: 7.0.3
Zend version: 3.0.0
OS : Linux, linux

Loaded plugins:
DevTools 1.11.0 by PocketMine Team for API(s) 2.0.0
FactionsCore 1.0.0 by mal0ne_23 for API(s) 2.0.0, 3.0.0
FactionsPro 1.3.6 by mal0ne_23, Tethered for API(s) 2.0.0

----------------------REPORT THE DATA BELOW THIS LINE-----------------------

===BEGIN CRASH DUMP===
eNrNWvtvG8cR/lcWlNFIBY/imxJTGVBtuXErx6ol1yjMQFje7ZFb3Su3eyLpIP97v5ndOx5luS3a
/FDDiLmvee3MNzN7+aVjdao688H4bDyY9UfjcbejyjIvO/NfOnZXYKlzdX/14cP7D51uJ1XGyBXN
XSZJvlGRSFWalzth9Bcl8lgM+rPRbDw4G47FcmeVEWq7lpWx2HlsS41/bC4kzobSKjHun0/dvhMQ
j3VClE9NGZ4WefigbKozdZqoR5WcXtN/sSnBFKQdTvq/djtFUq101pnHMjGq2wnzSJHYg+F4AEIL
u7AvdBaprbgQfH4+X4Lzww/SrI9fFLkJXm67wv3Y1T++nHwPNiAx9CR0fPwilOEassssEtoYZY9f
2LXGZib3ihY/O04/nZz84o6P/PGFLZWtykx884jnN/YHflVQhpg6ucTLC9FnzvXEH2pSRZk/6kiV
wcuVsp/yMol+UHq1tscnX0sarqvswXx+wf++PTQKz7WNIl6+FOPGIDw62Ws2aTR7EVdJcmvpKi/E
Nxn9xPK9wdY/ku4Nk9+J/rYfNxeAsZfn7/fvLm//sufvNtb3Mm3byYs0e16kvj9yVh9xw3MM+dek
X7sJ3wpOhEmeqYOrYlrQZ0+XxInj2N/bZNBQGx5QIxUvvA5bv3f0ZMeu2bHzO8ZPdnxpdnzxOyZP
dnB81Pb3e6aNTLVl/p0TEgGe9RScyZzBJo3Bps5gRbVMdCjiKgutzjNRFREMA0i4Zvf7mwptXo5Y
bjgNAtWWMkRofu4c9cXxyVzsw3uxuFXlI/lwWMIDX1dpcbzM80TJ7KTzU7ezUpkqZUJhjV0G3CDB
oDftDSP1CJmWlU6izrwPMChzm4c5tg76GMpCY+ew1+/1sW2lLUb9//APDpTyIdFLOtM7YwpVJgkn
O9c6q7bisTCD/mh03hfj3rjXDyazgCWFVY5mZ8HHZZXZSty+uxFvSi1eq1Cci+FoPunPR0Px8e6V
GPYHU7E9m95PxyBerAuQnkHYEUZfVAaVOiMvOxbvc1OzxgQPEh40IGjIQq/V4x1sx7+9uM1U98B+
gwGTlpVd56Whm7nhK3mHKxF3SqZkezbhZ29DjFUml4mCaLasALeRKiAoHcaayWP7uj2RSkLmhv9i
0ZIkySUpeHt3+eHu4w0mNmpptCV519YWZn56igtbV8temKene8lOGxrQ+41k5zOv8lK1FD6YPlS6
/1TnVCb9TN0PR19p2/XW/y+1bguxWDwRyWt/8/727tP7D9ev2/pnQJmWbjdl/oxqNHuo2ag3/ZZm
3c6dsmtVQoPf6EpbYjS6vaOl/0A18ldZQh2rypoNx38P4Vuo0mpFzn1004zEqzyL9UpQdbAoF9nR
JyTiP8tMDAZiMJ0PJ3PUGle3dxRRM9qQ5ja6cD7zNkVxYlEciFpm2uAYBmTUi2bHzdVzewosXgzO
B6MhTa4kVTuRuugzH7kNikTuoMgFEIdPFXKTBQREiknV85s1LBAk2lh31Fk9+LlS5e4iz1pTZYhT
eRzTlMyyHAirPJcAcK2B9anKrPGnqJLaBHFCsOunnAwy03ABczCX5st6Is5L0G308QzXsoxC+Gg9
Lh4Lvz/ScazDKrG7iwFbglEZIB+gxLA6W5kLmuZU5Ay7oXJkP2eUilpbqLC8eH315vLj9R3Nktq9
QhqDY9HF7/kPtKtsHhj5qLwUhIVN4ujt0oQ8RZDriZCdpIJMlI/IVwR0FHvoCN7dwHfE3VoZJWqh
hSyVQHAIJH2DH9KKkKxuxVIJnYVJFcHZQP4rHyVat3nKNa/9mqaRseqKnOLOEEmxLJV8ELu8Kj0t
oWMB2+tYMweYvYTPJDsi/KPaNOROIxVLGN6ITZ59Z4UsCiVLQaZJoWwID9hBfEF53em9WSvKyKtS
RiDQW2TkzY7YfJGJo7t1qeCMmIIUicxWFSp6QbUzm8x7vkFhKahMT/QXNiodfbVWodfi8CAEqIFb
Zb2NftCFirTs5eXqlEan1/D9+zy+f3v7/n46Og+G93QOZmwIzcUCaLRadIjRpzVjFjULBvhDHYMw
6B/IvqglMpNI63oJb02WFHLgl7J8pSgPdKjEGpVwwpecgrDz+z1Lbhwwb9aVjXKKEdfgkDCuLqGK
0KjIicVNj6A4hiTCJ17xqKX4K4UytnBIB35lLghV6eDtGuckealBaSM8F3dV0hMSlYETAoHhCKzd
5c1b7ASkR2Sn/UIAsZYQak/+isGjpkO1P4WxgLvCI0jU5U54P8J2DzXN6t4MR580DJ1ncCkZRaJU
xnkeiQlfe4A40lQlQxDaC0QJ2QNGVz9XMqHrWOlH7H2USaXEsWcJZD4BcccPEKcIVQPc5mqlyjlW
ifOPVbqEtRFOl2aXhXfSPMDjywcEUI/WP+IS2D9rJWnXuswBkXAJ7DZdwZgjPDbBZbswQwqrGcqT
bBYkI5pLqwyRQ1uY9i27DPRBcJX5FshpFUwAddjVs0Y0sqoT521MEcrNLCKxK7T9DpazJZ+KFOE/
e+GTs+IYGuCexZAswjoEXss5U6JodS01x+qfknwJw1ImrjvtRKfaEialaiW5d+6JWydKn5lrQ9fr
Ih06bTQLxsYWlC0cndr+hu0Sa7gLYArgnDGpGBhRc3TXD2UqdtpVDj1yCg2yGfisWMiABZuL/oKh
glHZAmpk9H8uPlU1/0J4Sor/k/DG5gXz91DVyOOpGYGQotwHlPHSEM9apEF/OHZS3aC9yDkdUSwa
YhgyIHvpmngbgBWgJiIf4x0B4kG5SGMYzzMAGCIUdiN0+JZZnTlRvCSM8BTrbtuCEy7RQPTtI9nB
EXF4TxBCGY63977eTGr72hMmLFRIidCwWUhWZ2N3tlEAllSF2as56ns9zcmzAnmtR07rlSyXuP8A
HWLiqjOKsGetyu5Eovgzwp9B7KYyqzjltqVAOVLRG1a3xoQnzuC9weFqHNfYkO69rCfeu3zHI3jE
Oq+SqBFEA0E2mdiLTn4rCpYcCk7RsrKO4ugNR8JX2Mi+4k43SsVlntYQS2f9etBGpdadQgl/dU9d
4Rn/aZ2jMtm9CTl7X7PXEyDyJElGXQNpI1yh2+XwLFGAGLcpoBqAapk9LSJVX7MPlPOpl/N17o49
vT5KAlQpuWNtCo6L3/Yb6MyJKOBHQ6e194WaES002ftfklpkmbJ0F03pBtdIXCZcSouOgAoRSVUu
EiD8yaMSB6ArTP2qA6OlanIiw81RG77qFQr8cmeJdlcEg5YzU+5jtoGtRQGsTKYOVfa51r1JVZSz
Ge78BbqzmPQy9cQP6Fxg3gvUwnDcVzcfuzgLCZbAn42O7NqhNsd3Qz5g8nMx84XBvmQwbJjW1p64
jBBPa5nEp/Syx1VMpOBnnhFYOv/Ls3ZANtm5RatVJ11tKfioDJJJ1wU2Mf6kM1SRUAtuo9i1Kdd/
vMlu6kphX7NTEUSHNsD6BRXsWRH4YbsmQ++lltXKXX/uMVNQtijZodVWhZUrdgh86Omo16wa8giu
YYp10dOZJjEGvn55KQZUt/gkRQUqc6qLUz5LMOWL1oW/1bkj4EpOI06NlbaC752uQndLgMhoX/qi
i+Sgnrv+IUfdSi5RV/eqrlxpj4ikleidHl3fQr+a5peW9mFRN5UHbY2qa1wyKwztGjre6r2/Mr7m
DnHHlgPAHwnckbko0rAydE/Zo068pfhthOyAsEAgMXDKAyZAd+oabUsGKGe/FolxhN3r6Mf3d1dz
wZkBf8MKDWCGBpAJ6bRIuMpmGT3nRsbGDS8PPCpErwO08wqzp3PahCTk2Za8e9j3aY7g1mVPcnVq
tGnep0x/d4fTNc66ev2WIIUUXEqjWsyOBwjmZ7h0xRALg+cWlA17JwwsRrWlYD+7I8rU/vmnFqEA
no4flSfuOrnR3nfgBFbcqVGFR44kk43cGUfb02kF2EGOYV+6TPMqaycp4+vKWggSn6hRWwPnpJ9z
Mf72UVliNnKyOxqHmVEMzofPnmbvypTrdZfKUVuqmNCSX3UIVekaGqruracFzw6dbxFLcFoAg6aW
XlGLWOz884XPl03RxWAWS2PZqmwXD7VxlfC23MBVA4p9Hbp0x21iSW8GcAyQrU31j5y6NRcbRqbk
KynjOSXBRv8nl0EGrS/jndwK+dQu6NNCzmF7fzi8C3bSDzLSlWkd8/cga8ChIHVHvd/RflRUBHb0
pha4Lxt7AUWYKOmY8HveHpKc4Pvms5a997XwHlg3UvM7ws+VqpS/X3+ew57nA/qyOhdn/xW1Ii+q
xFPzvyl9PiG8yDgmg8KhtHs6DNiPDFmSTJkiCVh6FvKzAw8PBNFz4QrQ+krp201VoCBzValzSAYP
Vwx5WqAyo1OeIRGd0HAjiVEzyXMyXWp4vtviHwbdO8LcgRE9edD3I+FmXR3gncR5r+82GnAjvw7o
EepwpskpB7NInzqL870brHO6e2bZa71Jolhj+bI826XUinCEGNjXNIJSb+WXxX6ZBeb8J1erEu2l
y+nN0xDVsfQV7eF5bZw8RM48Jw/Zy7kyX/HT0/AJtzp3F1Bmgc/6+yqVZ/Oi9aj1it41+aFNJXlB
2aqLMTSgV0Rbl4uonmJU8wrGRn7KqICgTT61VnQ7iMcWEeE/bLSKkwpFsbEuwdWA56nRDbnlmr55
YpTNZvOcSRKNdONu5WorKd+6AVVCoO+FmNfS8BKcnbr5ufjMpQmSTJfb+5+IokPBuhZpvwizEnVP
4xrL+v2ci7bnHpi5AecsZrhiILVTFBIagvoU3xKdubIA/EvQczuFLqekPbe5eHN9eTcffj/rTs63
g+5oO+oOvx98HyETO9Q6tqXCAAhzcdYXK/i3caPx5IQf4NXWqowMwh8Z3be35sMluVBrWIQHq+bn
RFs14m+qs8B9vv3iPrLWW5Yhypl1a4JedbNIlu0p/3+lNOOqTFrDWCfw8vaEbX9bXUXtQdpeWiOY
3XdCDP5h/Ke1MQ/TpXt+bm1Pw3JX2NbE7c31gfKo5traW0mKtNkXudHb9ti3//ztd9CbYOqDin3r
2ia1TvO24Ia927Rl28HY/BHZ/xITrAyGZHUR0KeySX/cn+Hni7dwlHhyrpaz6SxWg5mcTmfnk7Pz
5STsz6bReSzPzqJRNEae7YsXoH2z5uugT4hDDG3+oDKkkrbJPyn5gLDnmx7xrp3krzX83fHDqxnd
vC7cl+iRMzDJqRsav/76T17rio0=
===END CRASH DUMP===

**Comment by dktapps** [comment]
This relates to #152. While this is not exactly a duplicate, we already have an issue to track this bug, so this one will be closed. In the meantime, I recommend you carefully check your plugins for excess usage of getBlock(), as that will cause this issue.

**Comment by mal0ne-23** [comment]
Ah, pretty sure I know the problem with my code triggering this, thanks I'll make some changes to fix it temporarily for me
