### ISSUE TITLE
DoubleChestInventory: Call to a member function getHolder() on null 

### ISSUE THREAD

**Issue by zKoz210** [pmmp/PocketMine-MP#2502]
### Issue description
Long enough, I noticed this error when I shut down (/stop), the similar errors appear after prolonged operation of the server (3-4 days).

### Steps to reproduce the issue
I was unable to find possible and quick ways to reproduce the problem. This occurs after 3-4 days of active server with 40-50 people online with the type of server - survival

### OS and versions
* PocketMine-MP: 3.4 https://github.com/pmmp/PocketMine-MP/commit/af5637e0504d52469bc906432a1395ba0a21451c
* PHP: 7.2.9
* Server OS: CentOS 7

### Plugins
Tested on the server with the plugins that have nothing to do with the chests directly, just cancel the PlayerInteractEvent

### Crashdump, backtrace or other files
https://gist.github.com/zKoz210/882f37a51d5b15db1a51a83090e3eafe

**Comment by dktapps** [comment]
This bug has been around for a while but I've never gotten to the bottom of it. I would theorize that a player is opening a chest on a chunk border which previously was connected to a chest in an unloaded chunk, and then the chunk unload caused the other chest to invalidate the shared inventory object. However, I'm not very clear why this is the case.
