### ISSUE TITLE
Crash error

### ISSUE THREAD

**Issue by corndan** [pmmp/PocketMine-MP#2514]
<img width="641" alt="image" src="https://user-images.githubusercontent.com/21024123/47956333-dcb83580-dfb3-11e8-8369-b4fead664ca4.png">
| can fix this crash error?

**Comment by dktapps** [comment]
Without knowing your PocketMine-MP version, OS, PHP, Client version, or plugins and how the issue occurred, the issue cannot begin to be solved.
A pre-formatted template is provided that shows the required information to begin to find, test and solve an issue.
Until the adequate template and information is provided, the issue will be closed; it may be reopened if you update the ticket with the correct template and required information.

[Contribution guidelines](https://github.com/pmmp/PocketMine-MP/blob/master/CONTRIBUTING.md)

**Comment by ZizzyZizzy** [comment]
Also, the error in the screen shot is pretty self-explanatory. Your server ran out of memory.
