### ISSUE TITLE
PlayerDuplicateLoginEvent crash

### ISSUE THREAD

**Issue by corndan** [pmmp/PocketMine-MP#2519]
<img width="1101" alt="image" src="https://user-images.githubusercontent.com/21024123/48214557-3f814680-e391-11e8-8a78-be27f838721f.png">

**Comment by dktapps** [comment]
Please provide the full crashdump, plugins and version information, not just a screenshot.

**Comment by corndan** [comment]
Sorry, has attached

[Thu_Nov_8-05.39.22-MSK_2018.log](https://github.com/pmmp/PocketMine-MP/files/2562786/Thu_Nov_8-05.39.22-MSK_2018.log)

**Comment by dktapps** [comment]
Not sure what would cause this. A player should have been removed from this list on quit. Do you have any console logs that might help identify the problem?

**Comment by corndan** [comment]
It happens that there is an error in the console spam, but here it is crash.

Also, after this method, the player does not allow until restart:
`$sender->close("...")`

**Comment by dktapps** [comment]
The crash does not tell me what the cause of the bug is. I can prevent the crash, but this just hides the bug and doesn't fix it. I need whatever console errors were logged to identify the cause of the bug.

**Comment by dktapps** [comment]
Closing due to not reproducible and lack of response.
