### ISSUE TITLE
Raklib crash on more players

### ISSUE THREAD

**Issue by corndan** [pmmp/PocketMine-MP#2522]
If server online players = +-130 (no lags), raklib crash with error:
<img width="759" alt="image" src="https://user-images.githubusercontent.com/21024123/48302802-70d55000-e512-11e8-9368-ac4e3b0902e9.png">

My server feature:
<img width="741" alt="image" src="https://user-images.githubusercontent.com/21024123/48302832-d0cbf680-e512-11e8-9ac6-4ed46c2d4cd3.png">

It's not my fail, It's bug

**Comment by corndan** [comment]
<img width="1013" alt="image" src="https://user-images.githubusercontent.com/21024123/48302843-f9ec8700-e512-11e8-880f-29acc5dc6a34.png">

Error file

**Comment by ZizzyZizzy** [comment]
Not for nothing, that first screenshot contains the exact reason for the crash, and it's not a bug. (Not to mention you didn't follow the bug reporting guidelines.)

Hint: **Your server ran out of memory.**

**Comment by corndan** [comment]
16 GB is not enough?
What????

**Comment by dktapps** [comment]
You need to fix your `memory_limit` directive in `php.ini` file. You can see it's crashing out at 128MB.

**Comment by corndan** [comment]
I'm sorry to distract you, but there is no hope for another :(

It?
`opcache.memory_consumption=128`
