### ISSUE TITLE
Debug commands enabled and hidden by default

### ISSUE THREAD

**Issue by SOF3** [pmmp/PocketMine-MP#2528]
Disabling debug commands by default is not good, in case the user suddenly wants to capture a memory dump , or some support guy tells them to run /status to check things. This is not possible without restarting the server , and it causes side effects.
This issue proposes that debug commands are always enabled, but are not listed in /help nor sent to the client. Optionally also limit execution permissions to console for safety. This will prevent those not understanding these commands from executing them, while allowing users to run these commands when actually needed.

**Comment by dktapps** [comment]
As I recall these permissions are already confined to operator-only, so they could simply just be always enabled.
