### ISSUE TITLE
World generation

### ISSUE THREAD

**Issue by corndan** [pmmp/PocketMine-MP#2536]
In the last build, no trees appear in the generation of the world, but if you use the last stable build, they are generated.

No plugins.

**Comment by dktapps** [comment]
Without knowing your PocketMine-MP version, OS, PHP, Client version, or plugins and how the issue occurred, the issue cannot begin to be solved.
A pre-formatted template is provided that shows the required information to begin to find, test and solve an issue.
Until the adequate template and information is provided, the issue will be closed; it may be reopened if you update the ticket with the correct template and required information.

[Contribution guidelines](https://github.com/pmmp/PocketMine-MP/blob/master/CONTRIBUTING.md)
