### ISSUE TITLE
No trees in generation

### ISSUE THREAD

**Issue by corndan** [pmmp/PocketMine-MP#2538]
I'm use build #1668

**Version:**
This server is running PocketMine-MP 4.0.0+dev.1668 for Minecraft: Bedrock Edition v1.7.0 (protocol version 291)
**OS:**
Debian 8
**Plugins:**
Not use

**Problem:**
There are no trees in the generation of the world.

![image](https://user-images.githubusercontent.com/21024123/48984147-3a4e2680-f109-11e8-98b1-e791c2d28fa1.png)

**Comment by dktapps** [comment]
Have you considered the possibility that you are perhaps not in a forest biome?

**Comment by corndan** [comment]
I put the same map on a stable core and trees appeared
