### ISSUE TITLE
Uninitialized string offset in "vendor/pocketmine/binaryutils/src/Binary"

### ISSUE THREAD

**Issue by 95CivicSi** [pmmp/PocketMine-MP#2559]
### Issue description

When trying to craft items, players get disconnected from the game with "Internal server error."  This is accompanied by an error in the console that is similar to this:
```
ErrorException: "Uninitialized string offset: 1681" (EXCEPTION) in "vendor/pocketmine/binaryutils/src/Binary" at line 448
```

- Expected result: What were you expecting to happen?
  Expected crafting tables and inventory craft slots to respond with matching recipes and final crafted objects.
- Actual result: Client gets disconnected and loses whatever items are in the crafting slots.

### Steps to reproduce the issue

1. Setup and run a clean copy of PocketMine on release/3.5, commit https://github.com/pmmp/PocketMine-MP/commit/5946ec8819a7ade258667aaf4a39bd67219a07a9
2. Attempt to craft items on a crafting table or in your inventory (usually requires trying to place 2 items).

### OS and versions

* PocketMine-MP: https://github.com/pmmp/PocketMine-MP/commit/5946ec8819a7ade258667aaf4a39bd67219a07a9
* PHP: 7.2
* Server OS: Tested on Windows 10 and Ubuntu 18.04
* Game version: PE/Win10

### Plugins
- Test on a clean server without plugins: is the issue reproducible without any plugins loaded?
Yes
If the issue is **not** reproducible without plugins:
- Have you asked for help on our forums before creating an issue?
- Can you provide sample, *minimal* reproducing code for the issue? If so, paste it in the bottom section
- Paste your list of plugins here (use the 'plugins' command in PocketMine-MP)

### Crashdump, backtrace or other files
- Do not paste crashdumps into an issue - please use our Crash Archive at https://crash.pmmp.io for submitting crash reports to not spam the issue tracker. Add links to your reports in the Crash Archive here.
- Please use gist or anything else to add other files and add links here
https://gist.github.com/95CivicSi/be701816206de1b339c4c47a4d89c541
* ...

**Comment by isoz** [comment]
This is still happening to me.

**Comment by isoz** [comment]
also some players are getting "logged out due to Internal server error" once the error happens.

**Comment by ilyasafr** [comment]
This is still happening to me too.

**Comment by xinghao2003** [comment]
It also happening to me
``
2018-12-13 [15:40:14] [Server thread/CRITICAL]: Error: "Cannot write non-existing field "pitch"" (EXCEPTION) in "src/pocketmine/network/mcpe/protocol/DataPacket" at line 146
``

**Comment by dktapps** [comment]
"still happening" isn't helpful. I need reproducing steps and backtraces.

**Comment by dktapps** [comment]
Please open new issues for any fresh bugs you're encountering, since the one that caused this one specifically is already fixed.
