### ISSUE TITLE
TNT on fire will set damaged players on fire

### ISSUE THREAD

**Issue by Thunder33345** [pmmp/PocketMine-MP#2561]
### Issue description

- Expected result: Player get damaged without begin on fire
- Actual result: Player got damaged and set on fire

### Steps to reproduce the issue
1. light a tnt block to turn tnt block into tnt entity
2. set tnt entity on fire
3. let it explode and set you on fire

**Comment by dktapps** [comment]
This appears to be because `EntityDamageByEntityEvent` does not make any distinction between melee entity-vs-entity and other types of entity "attack".
