### ISSUE TITLE
Useless magic number for crafting-grid

### ISSUE THREAD

**Issue by 95CivicSi** [pmmp/PocketMine-MP#2562]
### Issue description

When trying to craft items, players get disconnected with "Internal server error" and an error is thrown in the console similar to this:
```UnexpectedValueException: "Useless magic number for crafting-grid type was -100, expected -2" (EXCEPTION) in "src/pocketmine/network/mcpe/protocol/types/NetworkInventoryAction" at line 114```

- Expected result: What were you expecting to happen?
- Actual result: What actually happened?

### Steps to reproduce the issue

1. Load a clean copy of PocketMine-MP with release 3.5.0.
2. Attempt to craft items in player inventory or on a crafting table.  I tested trying to craft various doors and crafting tables.

### OS and versions

* PocketMine-MP: 3.5.0
* PHP: 7.2
* Server OS: Ubuntu 18.04
* Game version: PE/Win10 Both with 1.8 clients

### Plugins
- Test on a clean server without plugins: is the issue reproducible without any plugins loaded?
Yes
If the issue is **not** reproducible without plugins:
- Have you asked for help on our forums before creating an issue?
- Can you provide sample, *minimal* reproducing code for the issue? If so, paste it in the bottom section
- Paste your list of plugins here (use the 'plugins' command in PocketMine-MP)

### Crashdump, backtrace or other files
- Do not paste crashdumps into an issue - please use our Crash Archive at https://crash.pmmp.io for submitting crash reports to not spam the issue tracker. Add links to your reports in the Crash Archive here.
- Please use gist or anything else to add other files and add links here
<script src="https://gist.github.com/95CivicSi/8232953e46541b2af95eae6498895f46.js"></script>
* ...

**Comment by dktapps** [comment]
Already fixed in a later commit.
