### ISSUE TITLE
Error build phar file

### ISSUE THREAD

**Issue by VityaVar** [pmmp/PocketMine-MP#2565]
Hello > 

I tried to assemble the core, but it did not work out for me ( it gives me:

[ERROR] Selected PHP binary (C:\Users\root\De
xe) does not satisfy some requirements.
 - Unable to find the cURL (curl) extension.
 - Unable to find the Multibyte String (mbstr
 - Unable to find the OpenSSL (openssl) exten
 - Unable to find the pthreads (pthreads) ext
 - Unable to find the Sockets (sockets) exten
 - Unable to find the YAML (yaml) extension.

where can i get them :?

**Comment by VityaVar** [comment]
Waiting

**Comment by 95CivicSi** [comment]
Quote from the issue template

THIS ISSUE TRACKER IS FOR BUG REPORTING, NOT FOR HELP & SUPPORT. If you need help, use the links below.


- http://pmmp.readthedocs.io/en/rtfd/ - Documentation
- https://forums.pmmp.io - PMMP Forums
