### ISSUE TITLE
Crash

### ISSUE THREAD

**Issue by ManiakMCPE** [pmmp/PocketMine-MP#2567]
Backtrace:
#0 src/pocketmine/network/mcpe/protocol/AddEntityPacket(210): pocketmine\utils\Utils::errorExceptionHandler(integer 8, string Undefined offset: -1, string phar:///home/minecraft/multicraft/servers/server21/PocketMine-MP.phar/src/pocketmine/network/mcpe/protocol/AddEntityPacket.php, integer 210, array Array())
#1 src/pocketmine/network/mcpe/protocol/DataPacket(92): pocketmine\network\mcpe\protocol\AddEntityPacket->encodePayload()
#2 src/pocketmine/network/mcpe/RakLibInterface(228): pocketmine\network\mcpe\protocol\DataPacket->encode()
#3 src/pocketmine/Player(3100): pocketmine\network\mcpe\RakLibInterface->putPacket(pocketmine\Player object, pocketmine\network\mcpe\protocol\AddEntityPacket object, boolean , boolean )
#4 src/pocketmine/Player(3120): pocketmine\Player->sendDataPacket(pocketmine\network\mcpe\protocol\AddEntityPacket object, boolean , boolean )
#5 src/pocketmine/entity/Entity(1948): pocketmine\Player->dataPacket(pocketmine\network\mcpe\protocol\AddEntityPacket object)
#6 src/pocketmine/entity/Entity(1958): pocketmine\entity\Entity->sendSpawnPacket(pocketmine\Player object)
#7 PiggyCustomEnchants_v1.4.1.phar/src/DaPigGuy/PiggyCustomEnchants/Entities/PiggyProjectile(72): pocketmine\entity\Entity->spawnTo(pocketmine\Player object)
#8 src/pocketmine/entity/Entity(1816): DaPigGuy\PiggyCustomEnchants\Entities\PiggyProjectile->spawnTo(pocketmine\Player object)
#9 src/pocketmine/entity/projectile/Projectile(266): pocketmine\entity\Entity->checkChunks()
#10 src/pocketmine/entity/Entity(1381): pocketmine\entity\projectile\Projectile->move(double -0.33839034465309, double -0.74423011809034, double 2.6645509612738)
#11 src/pocketmine/level/Level(795): pocketmine\entity\Entity->onUpdate(integer 1871)
#12 src/pocketmine/level/Level(740): pocketmine\level\Level->actuallyDoTick(integer 1871)
#13 src/pocketmine/Server(2380): pocketmine\level\Level->doTick(integer 1871)
#14 src/pocketmine/Server(2529): pocketmine\Server->checkTickUpdates(integer 1871, double 1544747050.9881)
#15 src/pocketmine/Server(2275): pocketmine\Server->tick()
#16 src/pocketmine/Server(2139): pocketmine\Server->tickProcessor()
#17 src/pocketmine/Server(1715): pocketmine\Server->start()
#18 src/pocketmine/PocketMine(249): pocketmine\Server->__construct(BaseClassLoader object, pocketmine\utils\MainLogger object, string /home/minecraft/multicraft/servers/server21/, string /home/minecraft/multicraft/servers/server21/plugins/)
#19 /home/minecraft/multicraft/servers/server21/PocketMine-MP.phar(1): require(string phar:///home/minecraft/multicraft/servers/server21/PocketMine-MP.phar/src/pocketmine/PocketMine.php)

**Comment by DaPigGuy** [comment]
This is not a problem with PMMP. Close the issue, and I'll get this fixed later.

**Comment by ManiakMCPE** [comment]
Okay, thanks.
