### ISSUE TITLE
Drop invisible (mcpe-1.0)

### ISSUE THREAD

**Issue by Andrew1481432** [pmmp/PocketMine-MP#257]
### Issue description

In version 1.0 there was the problem became drop becomes invisible after 5 minutes (sorry my english bad)

Plugin using: https://github.com/onebone/EconomyS/tree/master/EconomyShop and https://github.com/onebone/EconomyS/tree/master/EconomySell

-->
* PocketMine-MP: (mcpe-1.0)
* PHP: 7.0.6
* Server OS: Debian 8
* Game version: PE/Win10
![screenshot_2017-01-13-20-25-32](https://cloud.githubusercontent.com/assets/17208982/21942276/cee9a658-d9e5-11e6-82e7-19bc4347b95a.png)

**Comment by dktapps** [comment]
I have no idea what your issue is. Please describe in more detail.

**Comment by Muqsit** [comment]
He means that the Item entities became invisible after 5 minutes.
I think he means "despawned" but he thinks it's an error :/

**Comment by Muqsit** [comment]
@Andrew1481432
That's how Minecraft works. Except that the items will "vanish" away in 1 minute. Dropped items cannot stay on the ground for more than a minute. So, #close?
