### ISSUE TITLE
Enchantment desk error

### ISSUE THREAD

**Issue by Anders233** [pmmp/PocketMine-MP#2570]
PHP:7.2.9
PocketMine-MP 3.5.0 Minecraft: Bedrock Edition v1.8.0 (Protocol version 313) 

Problem description:
When I try to place my tool on the enchantment table, it always shows: "Internal server error" and kicks me out of the server.

Console error:
[  19:28:36  ] [ Server thread/CRITICAL ]: UnexpectedValueException: "Useless magic number for crafting-grid type was -15, expected -2" (EXCEPTION) in "src/pocketmine/network/mcpe/protocol/types/NetworkInventoryAction" at line 114 
[  19:28:36  ] [ Server thread/DEBUG ]: #0 src/pocketmine/network/mcpe/protocol/InventoryTransactionPacket(76): pocketmine\network\mcpe\protocol\types\NetworkInventoryAction->read(pocketmine\network\mcpe\protocol\InventoryTransactionPacket object) 
[  19:28:36  ] [ Server thread/DEBUG ]: #1 src/pocketmine/network/mcpe/protocol/DataPacket(74): pocketmine\network\mcpe\protocol\InventoryTransactionPacket->decodePayload() 
[  19:28:36  ] [ Server thread/DEBUG ]: #2 src/pocketmine/network/mcpe/PlayerNetworkSessionAdapter(90): pocketmine\network\mcpe\protocol\DataPacket->decode() 
[  19:28:36  ] [ Server thread/DEBUG ]: #3 src/pocketmine/network/mcpe/protocol/BatchPacket(114): pocketmine\network\mcpe\PlayerNetworkSessionAdapter->handleDataPacket(pocketmine\network\mcpe\protocol\InventoryTransactionPacket object) 
[  19:28:36  ] [ Server thread/DEBUG ]: #4 src/pocketmine/network/mcpe/PlayerNetworkSessionAdapter(98): pocketmine\network\mcpe\protocol\BatchPacket->handle(pocketmine\network\mcpe\PlayerNetworkSessionAdapter object) 
[  19:28:36  ] [ Server thread/DEBUG ]: #5 src/pocketmine/Player(3044): pocketmine\network\mcpe\PlayerNetworkSessionAdapter->handleDataPacket(pocketmine\network\mcpe\protocol\BatchPacket object) 
[  19:28:36  ] [ Server thread/DEBUG ]: #6 src/pocketmine/network/mcpe/RakLibInterface(162): pocketmine\Player->handleDataPacket(pocketmine\network\mcpe\protocol\BatchPacket object) 
[  19:28:36  ] [ Server thread/DEBUG ]: #7 vendor/pocketmine/raklib/src/server/ServerHandler(98): pocketmine\network\mcpe\RakLibInterface->handleEncapsulated(string 49.92.218.70 50153, raklib\protocol\EncapsulatedPacket object, integer 0) 
[  19:28:36  ] [ Server thread/DEBUG ]: #8 src/pocketmine/network/mcpe/RakLibInterface(102): raklib\server\ServerHandler->handlePacket() 
[  19:28:36  ] [ Server thread/DEBUG ]: #9 src/pocketmine/network/Network(94): pocketmine\network\mcpe\RakLibInterface->process() 
[  19:28:36  ] [ Server thread/DEBUG ]: #10 src/pocketmine/network/mcpe/RakLibInterface(92): pocketmine\network\Network->processInterface(pocketmine\network\mcpe\RakLibInterface object) 
[  19:28:36  ] [ Server thread/DEBUG ]: #11 vendor/pocketmine/snooze/src/SleeperHandler(120): pocketmine\network\mcpe\RakLibInterface->pocketmine\network\mcpe\{closure}() 
[  19:28:36  ] [ Server thread/DEBUG ]: #12 vendor/pocketmine/snooze/src/SleeperHandler(82): pocketmine\snooze\SleeperHandler->processNotifications() 
[  19:28:36  ] [ Server thread/DEBUG ]: #13 src/pocketmine/Server(2278): pocketmine\snooze\SleeperHandler->sleepUntil(double 1544786916.3544) 
[  19:28:36  ] [ Server thread/DEBUG ]: #14 src/pocketmine/Server(2139): pocketmine\Server->tickProcessor() 
[  19:28:36  ] [ Server thread/DEBUG ]: #15 src/pocketmine/Server(1715): pocketmine\Server->start() 
[  19:28:36  ] [ Server thread/DEBUG ]: #16 src/pocketmine/PocketMine(249): pocketmine\Server->__construct(BaseClassLoader object, pocketmine\utils\MainLogger object, string C:\MyServer\server\server_core\Pocketcraft\, string C:\MyServer\server\server_core\Pocketcraft\plugins\) 
[  19:28:36  ] [ Server thread/DEBUG ]: #17 C:/MyServer/server/server_core/Pocketcraft/PocketMine-MP.phar(1): require(string phar://C:/MyServer/server/server_core/Pocketcraft/PocketMine-MP.phar/src/pocketmine/PocketMine.php)

**Comment by dktapps** [comment]
Outdated version.

**Comment by JackMD** [comment]
Enchanmtment tables are not supported by pmmp. I could only imagine you implementing it yourself or using teaspoon.

**Comment by CortexPE** [comment]
The InventoryTransactionPacket wasn't modified by teaspoon... That's for
sure 👀😂😂😂

**Comment by SOF3** [comment]
@PEMapModder is stupid. Just ignore him and `base64 -d` the text. I'll fix it later.

**Comment by dktapps** [comment]
this is still an invalid issue.

**Comment by Anders233** [comment]
How can I close it?

**Comment by Anders233** [comment]
How should I run PocketMine-MP from source?
Because I think this is very cool, and I need to do this.
--- This passage is translated by machine. If there is a grammatical error, please forgive me.

**Comment by Anders233** [comment]
> 这仍然是一个无效的问题。

How can I close it?

> this is still an invalid issue.

How can I close it?
