### ISSUE TITLE
setBlock dont work and crash server

### ISSUE THREAD

**Issue by KnifeDev** [pmmp/PocketMine-MP#2575]
I am use a last-build PMMP. When i use setBlock this happened.
![default](https://user-images.githubusercontent.com/30533957/50042440-e5506100-0073-11e9-8436-32b20841503f.PNG)
I am use a code https://pastebin.com/VUgkW0Zk, this is worked code on a old versions (on 1.7 or 1.1 example).
Software: PMMP Last-build
OS: Debian 8.
Steps to reproduce:
1.Use a setblock on onEnable (load: POSTWORLD enabled on plugin.yml) or with task.
2.This crash happened.
3.I try to use setBlock with delayedRepeatingTask this is not help me, server start and crash after delay.

**Comment by INSANEIRON** [comment]
I can’t help four

**Comment by dktapps** [comment]
Without knowing your PocketMine-MP version, OS, PHP, Client version, or plugins and how the issue occurred, the issue cannot begin to be solved.
A pre-formatted template is provided that shows the required information to begin to find, test and solve an issue.
Until the adequate template and information is provided, the issue will be closed; it may be reopened if you update the ticket with the correct template and required information.

[Contribution guidelines](https://github.com/pmmp/PocketMine-MP/blob/master/CONTRIBUTING.md)
