### ISSUE TITLE
Crashes server

### ISSUE THREAD

**Issue by INSANEIRON** [pmmp/PocketMine-MP#2576]
PocketMine-MP Crash Dump Sat Dec 15 06:20:09 EST 2018

Error: include(phar:///home/gs/gs/data/servers/11072116/plugins/AlwaysSpawn.phar/src/philipshilling/alwaysspawn/Loader.php): failed to open stream: phar error: Cannot open temporary file for decompressing phar archive "/home/gs/gs/data/servers/11072116/plugins/AlwaysSpawn.phar" file "src/philipshilling/alwaysspawn/Loader.php"
File: vendor/pocketmine/spl/BaseClassLoader
Line: 126
Type: ErrorException

Code:
[117] 	 * Called when there is a class to load
[118] 	 *
[119] 	 * @param string $name
[120] 	 *
[121] 	 * @return bool
[122] 	 */
[123] 	public function loadClass($name){
[124] 		$path = $this->findClass($name);
[125] 		if($path !== \null){
[126] 			include($path);
[127] 			if(!\class_exists($name, \false) and !\interface_exists($name, \false) and !\trait_exists($name, \false)){
[128] 				return \false;
[129] 			}
[130] 
[131] 			if(\method_exists($name, "onClassLoaded") and (new ReflectionClass($name))->getMethod("onClassLoaded")->isStatic()){
[132] 				$name::onClassLoaded();
[133] 			}
[134] 			
[135] 			$this->classes[] = $name;
[136] 

Backtrace:
#0 vendor/pocketmine/spl/BaseClassLoader(126): pocketmine\utils\Utils::errorExceptionHandler(integer 2, string include(phar:///home/gs/gs/data/servers/11072116/plugins/AlwaysSpawn.phar/src/philipshilling/alwaysspawn/Loader.php): failed to open stream: phar error: Cannot open temporary file for decompressing phar archive "/home/gs/gs/data/servers/11072116/plugins/AlwaysSpawn.phar" file "src/philipshilling/alwaysspawn/Loader.php", string phar:///home/gs/gs/data/servers/11072116/PocketMine-MP.phar/vendor/pocketmine/spl/BaseClassLoader.php, integer 126, array Array())
#1 vendor/pocketmine/spl/BaseClassLoader(126): include()
#2 (): BaseClassLoader->loadClass(string philipshilling\alwaysspawn\Loader)
#3 (): spl_autoload_call(string philipshilling\alwaysspawn\Loader)
#4 src/pocketmine/plugin/PluginManager(155): class_exists(string philipshilling\alwaysspawn\Loader, boolean 1)
#5 src/pocketmine/plugin/PluginManager(320): pocketmine\plugin\PluginManager->loadPlugin(string /home/gs/gs/data/servers/11072116/plugins/AlwaysSpawn.phar, array Array())
#6 src/pocketmine/Server(1650): pocketmine\plugin\PluginManager->loadPlugins(string /home/gs/gs/data/servers/11072116/plugins/)
#7 src/pocketmine/PocketMine(249): pocketmine\Server->__construct(BaseClassLoader object, pocketmine\utils\MainLogger object, string /home/gs/gs/data/servers/11072116/, string /home/gs/gs/data/servers/11072116/plugins/)
#8 /home/gs/gs/data/servers/11072116/PocketMine-MP.phar(1): require(string phar:///home/gs/gs/data/servers/11072116/PocketMine-MP.phar/src/pocketmine/PocketMine.php)

PocketMine-MP version: 3.5.1 [Protocol 313]
Git commit: b42132a7c36903608008697b38d96ed026db3ab3
uname -a: Linux 3825e7bceb48 4.15.0-24-generic #26-Ubuntu SMP Wed Jun 13 08:44:47 UTC 2018 x86_64
PHP Version: 7.2.8
Zend version: 3.2.0
OS : Linux, linux

Loaded plugins:

----------------------REPORT THE DATA BELOW THIS LINE-----------------------

===BEGIN CRASH DUMP===
eNrtWm1z27aT/yqonJna/xH1bEtWx5lzHeeaa1L7Ymfyoux4IBKU2JAgS5C21U6++/12AT5IcXtJ
e/Ofe5FOphZBYLFP2P3tEn/0oqxIZXl3rwoTZ7q3HPd7ZZwq/DiezRbzyWJ02u8l0pSXRZEVveUf
vXKb43WPny8fA5WXtLDfS5Uxck2vYh0kVagO840slsPhcJOlarg29C+UpRwaVdB+w/F4NJ+MxyfD
PKnWsTbD8+RBbs1NLh/0gBYPTREM802cxLnB/5NYr4eS5xiaM3ydyVAVmJofLUUk40SFosxElist
TFkomS4F0RGKmF2KC6l1Vtr3pUrzrJDFVkRYJ6AHEaogS/MCcmAju1AWwSa+V8Lv/X0p/J7dwu99
tjh+DwqNqiR5iYXQ6Gdr8joLPqjyTayV9+ba6vBe6TArhjm/SfFmaPJk+L006gJ2Ne2mtKXd7rOW
YDokIE+ZnMBpChng98+9g5H4rOWHWAartZN8vyrjxPj+O/qzXKodB/tB6jDBqliXaq0KMemThclO
X73tn3tbo8x/i6P1RW1Fch1IXcitOKf/Hx4dwa0Oxl/kQrUD8NKJOMTQ3kTveYK/PHDYCNpVjO93
NOP7dhXTmzI9bH4nqzIjMneBTJIvJTMTbI1WHGu+4TX/eSM1IifkOT7GZgHxeaceY1N+Cbt9scqy
REktxrzl8WdtOZ2M9k6hneb7O/OsBu1QzdPf99GnbH6yz+4NUzscnxx/MYfmy1lkHub7PLRefjiZ
ne6xYRn0nt/dBZnGhlVQHu45nshWv6qg7D8V5t7IWL/O1uvOrM/m+gum7gi4EH/nZB+OIXmhfqvi
Qh3+HwSKP1Uyx9beLx/7PfUVbfy70cbfTP0wlmWlt4xkYlS/F2ShItONx3MQ9EvxL6giIW09bEgV
G1UoERshbaQjHdLRBdHxeOFW8MNpvfw/clnItPb5Z1oCoGLCZNSZPRk3swtVVoXmcMhvJu7NkJ+m
/JRXqyQORFTpgDxKtAmCyR/9wXNnPNcvn+Wy3Igz8azcxMZ7HsV6Z/J3PPnYTY6jQzv/m7Mz4fsa
MM6RO3EzMMc5LU906+ft2+jwG9/fyQO8UR/kWMlHAnBIYA4l0iIC9Ppf5gGexeWfzHHMLZrtMdtq
0M2w7J027z/S85SUzz/GXb59P1XlJgv39+plunWg0O9Zzg61ehBvVZQotkJXp0fe8zWiAhM7/HS5
9zw2N6Us4+DQCTCddARgGsvlzqpDq+fpdE+QWfPMj8fNo7M220GZn38hByC6lgwZs/fxK/L9iny/
It+vyPcr8v2KfP858u331kqrQiaEnxjmLHs7ZCDKCopu+3W96eB4MKbhKk5CILL5ZNLvxeYuVPcN
IsuLrMwCoKHldDzFHnGJhavZBDlTzoPpyeloejJajEaLk9P5aroIT09UOJqchKupXE1Bu5AfkniF
NaPBeDIYYaRyzL2OdfUopovJsZqvArWaLcRsMD4ejLzJzGNZALIOJifeu1Wly0rcvLkW75E9/qvC
YZ2K0WI5my1nc/Hu9kJMRuOFeFyc3J3MsAM1pJa9+WAyWODpd0RFFtZuj5d3man3xwA/JPzQAFIM
/QyNMnZUgEn03PvUKKR1a7sB9JSroowVUTu4bp7ERaajeM3pxdcHL4tYvFCBmIvR8XKKf2NxeXPL
/Pt6jc1SIOCzka+VlqtEeQVOyVkWRb5+2MSl8hLEN/uM7cMgK5R9StS9SjzS7NlDViShr1P56OWJ
3IL5swkIUiT2jLzHAu1rDoIeGdfCp7PxCHPSrAzP/Go0kvMT8fb8px9vxPnbS/H9+cWP34ACMjMw
r3JkPYm8i21TpUvTISp1nMJ3OiNptjKWTaRwrG/kpCn5fc5/wziK4qBKyu3ZGKpgXy6zwjOqBORd
m7NaSKNU2DxQjXf24vLl+bvXt74mbQ1yBBLoIDz7F//n6/tYPXghFCfB/Bn0/LjKHj3oY8MbIzFl
D16UxOtNyQPw/CSUKeKjZfp8T+5fs1jzRECRFAjrbpXAM86sxaD5QoWmzLRqRxKp1xXRU0hDtWl/
q1SxPUMEVCS84bEkW5Oj2H2tZ3mAQOXZbDRdnPhUvbYxYLBNE3I2QUFRBOxnFZRGNUkDmHacFg4o
bjfKKFFrFTlFUVklwC/KqY0sRWAR2ErVGCHED/GJmxOtG8QxkUVEYJ+mkRGwe0YVmyGSYgWs90Fs
s6pwtEQcCXhBHMW8A3y5gC8mWyL8E7B9TW4YqkjCL4x4yPS3pZB5rgj2wZ9TAvGw1pY4JMRt5eZa
scrXhQxBYOCTIzpiS1+Lg9tNoaBrDIGL2jaCak9WmdO7ifEMy8ok/p2VSksvNipwUuwuhM43ZZkb
hHelBw/xhzhXYSwHWbEe0tPwNRzwLovuXt1c3Z1MT73JHa2DGhtCS8BPcpAebfR+o0h3hJUNApiA
lC59wUyF1CaRpYXSTpvMKfjAL1WySRHG40CJDRcBNJKCsD2B7ZYc5jFuNlUZZnRYbXeEmLG5GtAq
M1Q4EVvndFgERSHOZzZYivtYiv8md8YUdmvPvVkK69/i4GaDdZK81ABvCbeLNZV0hESFWglsA98H
LN359Stha0LSU/vCA1srMNWSv+QzVdOh+pBio4C7wiOI1dVWOD/CdHcCm7etGg7eAyzCmHApGYbI
38Z6HncfYpg+VdJUBQc9akSsFOkDSkeilwmZY41aRIt7mVRKHLotEd+PQNzuh6Cu6Ex7sCYBmaWg
8CwOfqrSFcGaSJybrQ5upfkAjy8+4AAN6P07GIH9sxaSZm2KDMEJLoHZpi849gsXPOGyfdGUS5lV
y4Na0VhaaZwcmsK0b9hlqLGSg8lHBPBSQQUQh11dN6yRVi07ryI6oTSFTiKqk/JbaK4seFWoKK+w
F+6tFYeQAHYWE9IIy+A5KZdMac/5OTqLotKarBhS0M9y1j6jFjNAOr13v0VKMVwEhTSbfjfgOG8k
bRRFlZd21CqLlJKCMysUG7WgIhN7hPaAyfssDsHz0wyQb5CnZdAxnGrQuhfmenZO7afIsEh8xZaj
0H8m2QouY7KoFHYY5yqNS4plqVrL1baEqsWNVfKI1WrThI1hYPQhZpWzGwnKYpZO7VmGhYsAQPFD
gHPNpCJEv3rHuq0G8eg4rjNYKKNDT96AfdbMpMeMLcXI5yDI+aZEEJXh/3P2U3D6F8wThvpHzCPP
57y/C8INP46aEQgWBEgIBVhuaM+apfFoMrNc8ZF/z+fAMWe+/efs8Ulgfig+iKBCitVIsUI9qqDi
EJ5Zfu0RpJTczFaPAZCWacXhIHV1e7kUtz+8uhGvX715dYsQff361eWNuL58K95fvf3x8m1fYJK4
vcKsS/H+h6vXl+L67dXF5c3NYO/E7+hicnxiVXEN4J8x5qCAyz3egLOu00QTVMfQOvJJSIGEZ3gI
esqGU87VmYaICMNwIRL1zzzMehbwdcJpnOKNneYzqiIaCLFtuK7Psji4ojxBMIanDz6dTB7gUCDM
lauA0I5VKfFq7WnXNgLAqVRuWjGnIyenOXqSISf11Eq9lsUKR8FDyeY6oxRsntQqnyxixa0Rbg0C
NGBtxbiqywUwZwW/O+rXgX/P8Zzn2eQZRaBkJU3bEzcQVzawWxcH6siqJGw4iZEnHrRoeaczLHJm
HRKejEZWSHHwkqPCJxmQncWubqSKiiytEymtde+9rid2jAopnO32feEJB+o6w00Nf8lERcY9p9pn
wyrNLRCzgNSNezRu7fOCZrjZzDGzV/ONJ2RunGj5hEqRiZHPQP6evo2YStHpLzew0roGzhSWaK+W
pX5tOJv3HT4m1njin2mHqspgU+kPxrJ9IXMai9MqRdrU1L2pKy2ym7Alk2WgVSYdC6dBPhifuhNK
hpyZ4c08QvIV0ujMmehFZl/suy6hHIpoljZNrQ+JpeOmdQRiEOAFqGWVE+kFOGDQAQBI+gJTFilY
ErmkgkrYFVawVigsYw26cs5tSlMbqAqdJVS/OJp/Reav/M3XWpVknqaiwVlKLEBcyRKlOeFz5tVQ
61i4nMEhy9Zr7q1NFSvVQEXOVQddo9RvKFQW25Jo94U37tiLbMXbemXNigvpFIdbCMpVO+E/90WP
ahuG57QWg46ngfgBUA6Oc8bYTFxcv+tjLThY4RA9xCHcm1M+R8SGvMfkl2Lu8HKLpA0rpjN1IM5D
BKCNTKIhal8L7kMFd3UbYUv+skf+1DluTQrr0OqUD5ePFK0IHsqkb0Mhbfw+1iiuIBZii+IoRRD4
3bW+rgF0W8pSbUCLHpAcfapjde65x91S5Y07dyb+XTUWJqBdG9ZQXnNwCEDc+ksnf85OJ3bR0UBc
uzWJLNa8QLqK2nkHbRgVck2iwU5UJucJIxIqQVP6SIvTLguy3UUSU0+Iy37qgCpTije375hRA4FI
5lVVCmozsHnb3Wy1MHCRJi0rjxYtmddOnad0UGxze9wjQd0NQB0A0VpGVMjUTYK+iehGUqIXcQrF
lGRP2IgvLyJK9ZkTWPKeWd6QGhBvOQQjEUuO4sba2cIFzC2d15IcyjY5XKSztdGLK8ZAL17dnH8P
+MNwqdLsVhSpK4qTFCRDiwRi8s9Y32fJPcJhW0C0UrbnPlSram3PfObmCcKXBSvD4Toq/ChHU+tz
0LylPVw9tMkHsY6J/zE7dD3DRsD3stAEazorqaXjgAxRcQSQRACvyIPbmancdjSNwo3uhHY1TpRr
TETbwbG1F0eeG2treuS152JMlaUD29RCYPnr9oGxfR9VtxV8F2CWLJZzFiOG0HVZIQwO14ENGNS2
M81R8rU13tJ2eLLMcGOiLkFV3VvgVEYNe2HkvcuW1FGtG4P0qmFfQnAkACVLq1RIY1vqddnDhbJz
PBwmYG12L50FSZwLXomz9AbqDCRFizS7r9sOlONZd7Z3Wb+x23WqzbphutP7UnUjRNgLvLbrx1Pd
aa+Ma8wEiHglpwO3xLNLliKHBu/jhEuXnegV4CgjHztyHFUZ1EJWiqIlRdLJyIFQQggW25LCqEFN
4w7Q1nrcGW6qhZHLURYP0YeNzmaHYySOJ3bpiwlejJ96ocpgcMRJzKguF+xIt0SZOnDukAuFtG33
I/NZZdkw0DRBwxpGUFzjyoe/51najk7HAy1UcOmwPt9Oma641KT7ZB9m9etZO23uJ1u2HJvO06yi
tBBZPOOyBLmik420Qkz6HCeZXwZe4uAto7DOUvYcrWybZKUsqZWKKKZz65+D5KY+O3Rc+IPADpyz
ktM2teRIbELuswkxAgYnrfJ3ORw9yaIsQCfkFiMfXzDqljojW06mFDqoe+RVOY6xak0jAoJr1mzU
9+zEpxe8EXf/DScz0qINdPBDZPxUOLGE7bPVuJCXdEUWBx5c80CsUbCbViltI6/Wy+BTxbgQ+CBj
LuiRbm1MXlFTKq8Sd4Ldb0JJPMUl1gXtxsfBy20EpANHUW0p6nqLj6BtWi7tsaP+KvcW7KhFV85C
9Km9TmFtNCfP9qjjvTvSxKadUaSXWEdZawNEJM+21+t5m4xMwUwM8jRFOsqYVZ3pbUrVMcV8alMH
puGZ8rd7LdrX9l4JRXW5Xhdq7RqnTUuaygu6qPNhTzDmDcf06sUVfeh1+cuBJgoID8rWZFLQVSXa
0DDbDfc8NOh80AF8afRt/ZAtsq9LmNC+XTb50yXAtsrg0ayjMJRqmnyi08HsIyblGwkIpCA9Qbqy
xvLIS5EqUJ15FF00pVSa5NKy7YXKnW6o+6zcSdcVKhYgPw5PdSBw1MjQ9nVNf9+yVsCuaYEjmizm
kjRRpOk1oCZLUhik3RjouDV1H3/QkHcvuvRrFf4lCHCh2BrTOn+ni1Z/3Sjj0qqx7pdt3BjHA6qH
XcnlAgJ9aEAlGzJCjKOGDspVSGHRF8WXDmxici701ekeYBXZy2ro8lGmeeIeCDmBP2eiZW0rfgUP
pS7mUvzMUAY5q89tzV+IIhepDXDofuNjCai2KOgzGXeR6k+2DD2fyj+MbzgpGi6tuBsBu8Rg1CGG
Duu8KzPAvwR996Uwz6mo3W0pXr4+v11Ovpv3j08fx/3p47Q/+W78Hd0Us7HzsCwUHhA1zxYjG2Lt
0+z4yII/+62q08Sxp5hyBVTreqkMwrgZClsFW2Evr1RFHWzrorZoPkNxUAEdpJ6AcbOpdeXVH8jg
AVztHLzkaMI78fQdGlwwuJG7zojHkHPQNH2z3FUBdAvKtQKCD1Q5Gq59oY5VjKptaxtEPM/eBoRD
JzY78CGxIjJ1QIqiCcS9fk89ovrhaogumlwg1XfuWtCZ7TzSLT5jks5IHuzMN7+BGzXt3tawt0Xq
x1UAaLnpDNBHTh3KojtERVLGV0ymfJ8lcDe/mwlV0eXhV8O3X8aDE74QEsUJ4mznfVR2r4+sw+5D
2n2FunLDhIgM13PQdOf9zfXrzhM7eGivwkyYz3Rlv+h2JqVbqITvq7hf4nhAN2foY5Lw6J7I8Wg2
muPns1fUEl1ESk5m0WQxm0dyfjw+HY3GKzU9HQWnC6lGMpCRmi7m4hnrXpddPVxvWI0TbDDZuVhw
x8iCb1zZizv24kxm4seuKV0Tl+/WjAdzujXU77U3crtm3qRZV3GGtzJdxzGsyMngBA/xehVrWWwd
c3MMldkHpQFYunbaSr7/UPP/e5wzjfHxYFprMm6mf/z4P5xN1GU=
===END CRASH DUMP===

**Comment by INSANEIRON** [comment]
What’s tmp permissions

**Comment by ZizzyZizzy** [comment]
http://bfy.tw/LMgc
