### ISSUE TITLE
'ban-ip' command has problems about calling method.

### ISSUE THREAD

**Issue by nnnlog** [pmmp/PocketMine-MP#2578]
### Issue description
- Expected result: What were you expecting to happen? 
  > The person who used the command remains on the server.
- Actual result: What actually happened?
  > Deported by server after using the command.

### Steps to reproduce the issue

1. enter "/ban-ip <username>"

### OS and versions

* PocketMine-MP: `This server is running PocketMine-MP 4.0.0+dev.1715 for Minecraft: Bedrock Edition v1.8.0 (protocol version 313)` ,  git hash: c5262fd
* PHP: 7.2.8
* Server OS: Ubuntu 16.04
* Game version: both PE 1.8 and Windows 10

### Plugins
- Test on a clean server without plugins: is the issue reproducible without any plugins loaded? Tested, It still is.

If the issue is **not** reproducible without plugins:
- Have you asked for help on our forums before creating an issue?
- Can you provide sample, *minimal* reproducing code for the issue? If so, paste it in the bottom section
- Paste your list of plugins here (use the 'plugins' command in PocketMine-MP)

### Crashdump, backtrace or other files
- Do not paste crashdumps into an issue - please use our Crash Archive at https://crash.pmmp.io for submitting crash reports to not spam the issue tracker. Add links to your reports in the Crash Archive here.
- Please use gist or anything else to add other files and add links here
https://gist.github.com/nnnlog/b48020d07d0d3337cf090d41b5e24607

**Comment by dktapps** [comment]
This bug only seems to occur when IP-banning by name.
