### ISSUE TITLE
Plugin crashes are not detected if a plugin file didn't directly cause the error

### ISSUE THREAD

**Issue by dktapps** [pmmp/PocketMine-MP#2584]
When an uncaught error is triggered in core code because of a plugin fault, the fault is not detected as being caused by a plugin. Crashes like [this one](https://crash.pmmp.io/view/2064568) are not detected as being caused by plugins, even though it's clearly obvious that a plugin caused the crash from the backtrace.

**Comment by dktapps** [comment]
The crux of this issue is that PM can't tell the difference between a caller-induced crash and a callee error.

For example

**Comment by SonsaYT04** [comment]
The plugin support other CE plugin, and this CE have issue in 1.8. That's why it's trying to add null enchantment. 

Can you add function that ignore null enchant or should I check if it exist before adding enchants to an item?

**Comment by SonsaYT04** [comment]
The plugin support CE plugin, and this CE plugin have issue on 1.8 and the plugin is trying to add null enchant that's why it crashed and it won't detect the plugin who caused the crashed.

**Comment by dktapps** [comment]
Resolved by 2cdf97b7b50bb458f1bec252f59dea8c57155cf7 and 22a6b817d7e12c1b7167a0b3b9d89152b13865a3.
