### ISSUE TITLE
Display not working

### ISSUE THREAD

**Issue by BlueSkyTech21** [pmmp/PocketMine-MP#2589]
### Issue description

- Expected result: What were you expecting to happen?
I was expecting to see a Minecraft game start up
- Actual result: What actually happened?
I got a black screen and there was no Minecraft I couldn’t play
Is this a fake software or something?

### Steps to reproduce the issue

1. Download software
2. Run start.cmd

### OS and versions

* PocketMine-MP: 3.5.0
* PHP: 7.2
* Server OS: Windows
* Game version: win10

### Plugins
- Test on a clean server without plugins: is the issue reproducible without any plugins loaded? Yea

If the issue is **not** reproducible without plugins:
- Have you asked for help on our forums before creating an issue?
- Can you provide sample, *minimal* reproducing code for the issue? If so, paste it in the bottom section
- Paste your list of plugins here (use the 'plugins' command in PocketMine-MP)

### Crashdump, backtrace or other files
- Do not paste crashdumps into an issue - please use our Crash Archive at https://crash.pmmp.io for submitting crash reports to not spam the issue tracker. Add links to your reports in the Crash Archive here.
- Please use gist or anything else to add other files and add links here

* ...

**Comment by dktapps** [comment]
Back to your cave, troll.
