### ISSUE TITLE
Unable to join 3.5.1 release server on Android

### ISSUE THREAD

**Issue by ZizzyZizzy** [pmmp/PocketMine-MP#2590]
### Issue description
Cannot connect from Android client v1.8.0.  (Windows 10 client works fine.)

It appears to connect, then hangs on "Generating world" with "Locating server" showing in the client.

The server shows the connection and says the player has logged in:

> [10:12:59] [Server thread/INFO]: Loading pocketmine.yml...
> [10:12:59] [Server thread/INFO]: Loading server properties...
> [10:12:59] [Server thread/INFO]: Selected English (eng) as the base language
> [10:12:59] [Server thread/INFO]: Starting Minecraft: Bedrock Edition server version v1.8.0
> [10:12:59] [Server thread/NOTICE]: Online mode is enabled. The server will verify that players are authenticated to Xbox Live.
> [10:12:59] [Server thread/NOTICE]: To disable authentication, set "xbox-auth" to "false" in server.properties.
> [10:12:59] [Server thread/INFO]: Opening server on 0.0.0.0:19132
> [10:12:59] [Server thread/INFO]: This server is running PocketMine-MP version 3.5.1
> [10:12:59] [Server thread/INFO]: PocketMine-MP is distributed under the LGPL License
> [10:12:59] [Server thread/INFO]: Loading resource packs...
> [10:12:59] [Server thread/INFO]: Preparing level "world"
> [10:12:59] [Server thread/INFO]: Default game type: Survival Mode
> [10:12:59] [Server thread/INFO]: Done (0.16s)! For help, type "help" or "?"
> version
> [10:13:01] [Server thread/INFO]: This server is running PocketMine-MP 3.5.1 for Minecraft: Bedrock Edition v1.8.0 (protocol version 313)
> [10:13:16] [Server thread/NOTICE]: Player data not found for "zizzy", creating new profile
> [10:13:17] [Server thread/INFO]: zizzy[/xx.xx.xx.xx:xxxxx] logged in with entity id 1 at (world, 256, 67, 256)
> 

- Expected result: Player joins server.
- Actual result: Player never joins server.

### Steps to reproduce the issue
1. Install 3.5.1 release .phar file
2. Start it up with PHP 7.2
3. Attempt to join on Android over wi-fi.

### OS and versions
* PocketMine-MP: 3.5.1 release #b42132a
https://github.com/pmmp/PocketMine-MP/releases/tag/3.5.1

* PHP: PHP 7.2.9 (cli) (built: Aug 30 2018 10:03:30) ( ZTS )
Copyright (c) 1997-2018 The PHP Group
Zend Engine v3.2.0, Copyright (c) 1998-2018 Zend Technologies

* Server OS: CentOS Linux release 7.5.1804 (Core)
Linux xxxx 3.10.0-862.3.3.el7.x86_64 #1 SMP Fri Jun 15 04:15:27 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux

* Game version: Minecraft v1.8.0 on Android

### Plugins
No plugins.

### Errors
No errors

**Comment by dktapps** [comment]
Cannot reproduce. Can you reproduce this by joining `dev1.ams.pmmp.io` port 19132?

**Comment by ZizzyZizzy** [comment]
Unable to connect to that server on Android, but it shows a different issue. Tries to connect, then eventually gives up and says "unable to connect to world".

Windows 10 client on wired connection works fine with that server.

Android client on wi-fi shows 2 bars and that the server is running v3.5 build a7f11813.

**Comment by dktapps** [comment]
Do you have a server I can try to test?

**Comment by ZizzyZizzy** [comment]
Well crappy McCrapster. I just created one and it works fine there. OS is more up to date with RPM's, however.

Must be a newer library or Kernel. PHP version is identical. I'll comment here when I find it.

**Comment by dktapps** [comment]
It might also have to do with configuration, so make sure you check that as well.

**Comment by Frago9876543210** [comment]
Check you firewall.

**Comment by ZizzyZizzy** [comment]
@Frago9876543210  thanks, but not helpful. I already stated that it works fine with Windows 10 clients, which means it cannot be the firewall.

I still have no idea what's causing this. Fresh install of CentOS 7.6.1810 with kernel 3.10.0-957.1.3.el7.x86_64 has the exact same issue.  I'm building PHP 7.2.13 now to see if that makes any difference.

This only started with the 3.5.1 release. It was working perfectly before that.

**Comment by ZizzyZizzy** [comment]
OK, this is odd. A three-year old tablet running Android 6.0.1 connected fine. A little slow at first, but it works.

It's the Pixel 2 on Android 9 that won't connect.

- Uninstall Minecraft
- Fresh install
- Start it up - Black screen
- Force Close, start again
- Server list still there. WTF?
- Still will not connect
- Remove all app data & force Close
- Uninstall
- Reboot
- Reinstall
- Launch..Black F*ING screen again
- FC & restart
- Give my soul to Microsoft Live again
- Server list still there. HOWISTHISPOSSIBLE!?
- Still cannot connect.

Tried connecting to Lifeboat (from the ever-growing list of Featured servers in the client.) Works fine. As does Mineplex.

Ideas? Clearly the server is working, just not for this phone for some reason.

**Comment by dktapps** [comment]
Try `amsterdam1.zone.pocketmine.net` port 19132. I can connect to this fine with a Pixel 1 XL.

**Comment by ZizzyZizzy** [comment]
Works perfectly and instantly, but that's running 3.5.2.

OS? PHP ver?

**Comment by ZizzyZizzy** [comment]
@dktapps  try 193.70.80.2:19132
That one is in your neck of the woods. I can't connect to it on Pixel 2. Works fine on everything else I tried.

**Comment by dktapps** [comment]
That one works fine for me.

There are insignificant changes between 3.5.1 and 3.5.2 that don't relate to network, so that should not affect anything. The only other thing I can suggest is try rolling back to 3.5.0 and see if the bug goes away. 3.5.1 introduced a change which makes spawning (which is when the `joined the game` message is sent) only happen after the client sends `SetLocalPlayerAsInitializedPacket`.

**Comment by ZizzyZizzy** [comment]
Same issue on 3.5.0 server with this phone. If I could rollback the version of Minecraft, I would test on the older (< 1.8.0) server version. It worked fine back then. It's not rooted, so even if I could locate the APK...

At this point it looks to be a bug either in the client, or something with the phone.

**Comment by dktapps** [comment]
have you modified any settings on the server?

**Comment by ZizzyZizzy** [comment]
Nope. Deleted all .yml files and let it create them per default.

**Comment by dktapps** [comment]
This sounds like something specific to either your device, the remote server or your connection. Have you tried anything other than PocketMine-MP and experienced the same issue?
