### ISSUE TITLE
Error: Index invalid or out of range

### ISSUE THREAD

**Issue by ManiakMCPE** [pmmp/PocketMine-MP#2598]
Error: Index invalid or out of range
File: src/pocketmine/inventory/BaseInventory
Line: 94
Type: RuntimeException

Code:
[85] 	}
[86] 
[87] 	abstract public function getDefaultSize() : int;
[88] 
[89] 	public function getMaxStackSize() : int{
[90] 		return $this->maxStackSize;
[91] 	}
[92] 
[93] 	public function getItem(int $index) : Item{
[94] 		return $this->slots[$index] !== \null ? clone $this->slots[$index] : ItemFactory::get(Item::AIR, 0, 0);
[95] 	}
[96] 
[97] 	/**
[98] 	 * @param bool $includeEmpty
[99] 	 *
[100] 	 * @return Item[]
[101] 	 */
[102] 	public function getContents(bool $includeEmpty = \false) : array{
[103] 		$contents = [];
[104] 		$air = \null;

Backtrace:
#0 src/pocketmine/inventory/BaseInventory(165): pocketmine\inventory\BaseInventory->getItem(integer 45)
#1 AuctionHouseUpgraded_v1 (3).phar/src/SonsaYT/AuctionHouseUpgraded/Main(503): pocketmine\inventory\BaseInventory->setItem(integer 45, pocketmine\item\Item object)
#2 AuctionHouseUpgraded_v1 (3).phar/src/SonsaYT/AuctionHouseUpgraded/Main(250): SonsaYT\AuctionHouseUpgraded\Main->addAuctionItems(pocketmine\Player object, pocketmine\inventory\ChestInventory object)
#3 AuctionHouseUpgraded_v1 (3).phar/src/SonsaYT/AuctionHouseUpgraded/Task/AHAuction(21): SonsaYT\AuctionHouseUpgraded\Main->openAuctionHouse(pocketmine\Player object)
#4 src/pocketmine/scheduler/TaskHandler(159): SonsaYT\AuctionHouseUpgraded\Task\AHAuction->onRun(integer 58019)
#5 src/pocketmine/scheduler/TaskScheduler(199): pocketmine\scheduler\TaskHandler->run(integer 58019)
#6 src/pocketmine/plugin/PluginManager(665): pocketmine\scheduler\TaskScheduler->mainThreadHeartbeat(integer 58019)
#7 src/pocketmine/Server(2522): pocketmine\plugin\PluginManager->tickSchedulers(integer 58019)
#8 src/pocketmine/Server(2275): pocketmine\Server->tick()
#9 src/pocketmine/Server(2139): pocketmine\Server->tickProcessor()
#10 src/pocketmine/Server(1715): pocketmine\Server->start()
#11 src/pocketmine/PocketMine(249): pocketmine\Server->__construct(BaseClassLoader object, pocketmine\utils\MainLogger object, string /home/minecraft/multicraft/servers/server19/, string /home/minecraft/multicraft/servers/server19/plugins/)
#12 /home/minecraft/multicraft/servers/server19/PocketMine-MP.phar(1): require(string phar:///home/minecraft/multicraft/servers/server19/PocketMine-MP.phar/src/pocketmine/PocketMine.php)

PocketMine-MP version: 3.5.1 [Protocol 313]
Git commit: b42132a7c36903608008697b38d96ed026db3ab3
uname -a: Linux jordan 2.6.32-042stab120.18 #1 SMP Fri Jan 13 10:32:04 MSK 2017 x86_64
PHP Version: 7.2.7
Zend version: 3.2.0
OS : Linux, linux

**Comment by dktapps** [comment]
You can clearly see this is caused by a plugin. Please stop spamming the issue tracker.
