### ISSUE TITLE
Sign memory leak

### ISSUE THREAD

**Issue by archie426** [pmmp/PocketMine-MP#26]
### Issue description

Write a short description about the issue
Sign memory problem
### Steps to reproduce the issue

1. ...Place a sign and take a certain amount of time writing (any other steps are welcome)

### OS and versions

* PocketMine-MP: Latest
* PHP: Latest
* OS: Windows 10 Pro 64-bit

### Crashdump, backtrace or other files

* No crashes are shown

**Comment by archie426** [comment]
I reckon this is a bug, it happens on nukkit as well

**Comment by dktapps** [comment]
This is unlikely to be a memory leak and does not provide any useful information about how to reproduce. And "latest" is not a valid version.

**Comment by SOF3** [comment]
If you indeed believe this is a problem, please provide a fair test, where you duplicate the server, change to a different port, start the two servers at the same time, join both servers at the same time with two clients, and only edit a sign on one server (and to make a control setup to make the test even more fair, place a block on the other server, and place a chest when you finish editing).
