### ISSUE TITLE
Characters issue

### ISSUE THREAD

**Issue by MSG100TC** [pmmp/PocketMine-MP#2602]
### Issue description

--
Characters for like 
"»" and "«" cannot be typed, or pasted in chat. Its displayed as " instead.

- Expected result: It should work fine because I have seen this character used with slappers on many other servers.
- Actual result: It didn't work

### Steps to reproduce the issue

1. ...
2. ...

### OS and versions

* PocketMine-MP: This server is running PocketMine-MP 3.5.1 for Minecraft: Bedrock Edition v1.8.0 (protocol version 313)
* PHP: 7
* Server OS:
* Game version: Win10 

### Plugins
- Test on a clean server without plugins: is the issue reproducible without any plugins loaded?

If the issue is **not** reproducible without plugins:
- Have you asked for help on our forums before creating an issue?
- Can you provide sample, *minimal* reproducing code for the issue? If so, paste it in the bottom section
- Paste your list of plugins here (use the 'plugins' command in PocketMine-MP)

### Crashdump, backtrace or other files
- Do not paste crashdumps into an issue - please use our Crash Archive at https://crash.pmmp.io for submitting crash reports to not spam the issue tracker. Add links to your reports in the Crash Archive here.
- Please use gist or anything else to add other files and add links here

* ...

**Comment by dktapps** [comment]
Test in vanilla. It works the same there.

**Comment by MSG100TC** [comment]
No, like in chat. When you type »« it turns into ””

**Comment by MSG100TC** [comment]
I tested it in vanilla, it appears to have the same issue... Is there an alternative way to type »« ? For ex, like when naming Slappers?
