### ISSUE TITLE
Internal Server Error while Pvping and Joining server

### ISSUE THREAD

**Issue by MrLukePotatoes** [pmmp/PocketMine-MP#2605]
A lot of players told me that when they join my server they get the internal server error and sometimes they can join and when they go to pvp and they pvp they get the internal server error. Please find a solution for this asap.

**Comment by dktapps** [comment]
Without knowing your PocketMine-MP version, OS, PHP, Client version, or plugins and how the issue occurred, the issue cannot begin to be solved.
A pre-formatted template is provided that shows the required information to begin to find, test and solve an issue.
Until the adequate template and information is provided, the issue will be closed; it may be reopened if you update the ticket with the correct template and required information.

[Contribution guidelines](https://github.com/pmmp/PocketMine-MP/blob/master/CONTRIBUTING.md)

**Comment by JackMD** [comment]
More like you delete your plugins to fix the bug ASAP
