### ISSUE TITLE
Crafting Error

### ISSUE THREAD

**Issue by ZackyVN** [pmmp/PocketMine-MP#2609]
When i put something like a wood plank the server kicked me out with a message "Internal Server Error"

PocketMine-MP: 3.5.1 release #b42132a
https://github.com/pmmp/PocketMine-MP/releases/tag/3.5.1

PHP: PHP 7.2.9 (cli) (built: Aug 30 2018 10:03:30) ( ZTS )
Copyright (c) 1997-2018 The PHP Group
Zend Engine v3.2.0, Copyright (c) 1998-2018 Zend Technologies

Server OS: Windows

Game version: Minecraft v1.8.0 on Android

**Comment by dktapps** [comment]
Without knowing your PocketMine-MP version, OS, PHP, Client version, or plugins and how the issue occurred, the issue cannot begin to be solved.
A pre-formatted template is provided that shows the required information to begin to find, test and solve an issue.
Until the adequate template and information is provided, the issue will be closed; it may be reopened if you update the ticket with the correct template and required information.

[Contribution guidelines](https://github.com/pmmp/PocketMine-MP/blob/master/CONTRIBUTING.md)
