### ISSUE TITLE
Server freezes.

### ISSUE THREAD

**Issue by xISRAPILx** [pmmp/PocketMine-MP#2618]
### Issue description
The server hangs, does not respond to commands in the console, and does not start players on the server, although DEBUG messages exists.

### Steps to reproduce the issue
I don't know why this happens, sometimes right after a reboot, sometimes after a while.

### OS and versions
* PocketMine-MP: 39c0fa6103d8cdfb52129c5ccf7f339ef40b1919
* PHP: 7.2
* Server OS: Ubuntu 18.04.1
* Game version: PE/Win10 

### Plugins
It happens without plugins, but much less often.

### Crashdump, backtrace or other files
![image](https://user-images.githubusercontent.com/28113262/50549297-6100ff00-0c6b-11e9-8094-2dc8375ec338.png)

**Comment by dktapps** [comment]
When did you start experiencing this bug? Does it occur on release builds?

**Comment by xISRAPILx** [comment]
@dktapps, I've been noticing this for a week. Today the server freezes very often. There is a suspicion that these are bots, but I'm not sure.

**Comment by xISRAPILx** [comment]
Here is again freezed, only that. https://imgur.com/a/6jMcJxy

**Comment by dktapps** [comment]
The debug messages you see indicate that the main thread is stuck, while other threads are still active. The question is why it's getting stuck.

How long does it typically take to freeze?

**Comment by xISRAPILx** [comment]
@dktapps, until I kill the process.

**Comment by MihaSmit** [comment]
This occurs either immediately after the start in a few minutes or 30 minutes later, or generally ideally an hour.
Worth assembly release 120 under 1.8
ps translator google

**Comment by MihaSmit** [comment]
I also want to draw your attention to the problem.

Even without plug-ins, the server lagged heavily due to
 ussr - syncChunkLoad

![default](https://user-images.githubusercontent.com/16068635/50554879-eb7d4900-0cd3-11e9-8a44-f1064a6a5965.png)

I tried to put an old backup card at which everything worked well, but did not help

**Comment by dktapps** [comment]
@MihaSmit please copy and paste the output from the `version` command

**Comment by MihaSmit** [comment]
![default](https://user-images.githubusercontent.com/16068635/50558331-3ca23280-0cfe-11e9-926e-3a9cdc54eb4f.png)

**Comment by MihaSmit** [comment]
сервер лежит но еще отсылает сообщения

![default](https://user-images.githubusercontent.com/16068635/50558972-5eea7f00-0d03-11e9-8252-8a14826d425a.png)

**Comment by Infernus101** [comment]
reproduced on v3.5 on v1.8, v3,4 worked fine for v1.7

**Comment by TheClimbing** [comment]
Are you guys sure you've disabled win 10 quick edit mode?

**Comment by dktapps** [comment]
> Server OS: Ubuntu 18.04.1

...

**Comment by TheClimbing** [comment]
Oopssie nvm that, I doubt they pressed ctrl s to pause the terminal but at least when it freezes you can open another terminal then use
 ps axo pid,wchan:32,cmd
Take the pid and and use it in
sudo strace -p (PID here) 
Then paste the result here so we can get an insight

**Comment by dktapps** [comment]
@xISRAPILx could you provide a list of plugins in use on the affected server?

**Comment by dktapps** [comment]
Closing due to lack of response.

**Comment by AidanSpeakss** [comment]
Hello I am having the same issue and I am willing to do whatever I can to debug this and provide information. First off the debug logs, these logs vary in size, I'm using a debug level of 4. And what happens is either the server recieves are large amount of these lines in the log and the server completely crashes or just a few lines which then kicks players from the server at random. I've contacted my host, and they feel it's a bot attack. Here's the log:

```
24.07 01:37:18 [Server] RakLibServer thread/DEBUG Ignored connected packet from 99.251.38.35 62592 due to no session opened (0x84)
24.07 01:37:18 [Server] RakLibServer thread/DEBUG Ignored connected packet from 99.251.38.35 62592 due to no session opened (0x84)
24.07 01:37:18 [Server] RakLibServer thread/DEBUG Ignored connected packet from 45.51.66.154 60202 due to no session opened (0x84)
24.07 01:37:18 [Server] RakLibServer thread/DEBUG Ignored connected packet from 99.251.38.35 62592 due to no session opened (0x84)
24.07 01:37:18 [Server] RakLibServer thread/DEBUG Ignored connected packet from 99.251.38.35 62592 due to no session opened (0x84)
24.07 01:37:18 [Server] RakLibServer thread/DEBUG Ignored connected packet from 99.251.38.35 62592 due to no session opened (0x84)
24.07 01:37:18 [Server] RakLibServer thread/DEBUG Ignored connected packet from 45.51.66.154 60202 due to no session opened (0x84)
24.07 01:37:18 [Server] RakLibServer thread/DEBUG Ignored connected packet from 99.251.38.35 62592 due to no session opened (0x84)
24.07 01:37:18 [Server] RakLibServer thread/DEBUG Ignored connected packet from 99.251.38.35 62592 due to no session opened (0x8c)
24.07 01:37:18 [Server] RakLibServer thread/DEBUG Ignored connected packet from 99.251.38.35 62592 due to no session opened (0x84)
24.07 01:37:18 [Server] RakLibServer thread/DEBUG Ignored connected packet from 99.251.38.35 62592 due to no session opened (0x8c)
24.07 01:37:18 [Server] RakLibServer thread/DEBUG Ignored connected packet from 45.51.66.154 60202 due to no session opened (0x84)
24.07 01:37:18 [Server] RakLibServer thread/DEBUG Ignored connected packet from 99.251.38.35 62592 due to no session opened (0x84)
24.07 01:37:18 [Server] RakLibServer thread/DEBUG Ignored connected packet from 99.251.38.35 62592 due to no session opened (0x84)
```

What can I do to give you more information?

**Comment by toplineeae** [comment]
Hi, could you help me? I have a recent Naruto theme server on mcpe, and my server is freezing for nothing, the console does not leave any error messages or anything, the server just freezes and no one gets in unless it is restarted. Could you help me with this problem? I'm losing a lot of players because of that. An acquaintance commented that there could be many worlds of the multiworld plugin created, but I deleted several and it still freezes ...

**Comment by toplineeae** [comment]
Hi, could you help me? I have a recent Naruto theme server on mcpe, and my server is freezing for nothing, the console does not leave any error messages or anything, the server just freezes and no one gets in unless it is restarted. Could you help me with this problem? I'm losing a lot of players because of that. An acquaintance commented that there could be many worlds of the multiworld plugin created, but I deleted several and it still freezes ...

**Comment by SOF3** [comment]
This is not a support channel. Please review our [guidelines](https://github.com/pmmp/PocketMine-MP/blob/stable/CONTRIBUTING.md) for support channels.
