### ISSUE TITLE
Pocketmine dont see update

### ISSUE THREAD

**Issue by Michaelloitalliano** [pmmp/PocketMine-MP#2623]
### Issue description
i update pocketmine from 3.5.2 to 3.5.3 and it says i need update to 3.5.3
### Steps to reproduce the issue
1. update core:D
2. ...

### OS and versions

* PocketMine-MP: 3.5.3
* PHP: 7.3
* Server OS: Win
* Game version: PE/Win10 
### Crashdump, backtrace or other files
 Этот сервер работает под управлением PocketMine-MP, версии 3.5.3
...
 ----- PocketMine-MP Auto Updater -----
 Your version of PocketMine-MP is out of date. Version 3.5.3 was released on Sun Dec 30 09:50:36 2018
 Details: https://jenkins.pmmp.io/job/PocketMine-MP/1733/
 Download: https://jenkins.pmmp.io/job/PocketMine-MP/1733//artifact/PocketMine-MP.phar
* ...
its from log

**Comment by dktapps** [comment]
Did you use a Jenkins phar or build your own?

**Comment by dktapps** [comment]
It seems there's a mismatch in the build numbers because different build jobs were used to create the build. If you use Jenkins build 1733, the bug doesn't appear.

**Comment by dktapps** [comment]
The release has been updated with the correct phar. Please redownload.
