### ISSUE TITLE
Black banners

### ISSUE THREAD

**Issue by Frago9876543210** [pmmp/PocketMine-MP#2624]
### Issue description
When you put a banner of any color it becomes black
![default](https://user-images.githubusercontent.com/13465245/50556761-58054180-0cee-11e9-9b62-3239dc600619.png)

### OS and versions
* PocketMine-MP: 8415e49a7fcfb5e33f8edd66b93906d71dc79d13
* PHP: 7.2.13
* Server OS: Ubuntu 18.04

**Comment by fuyutsuki** [comment]
Banner color is not implemented yet

**Comment by Frago9876543210** [comment]
@fuyutsuki before it worked

**Comment by dktapps** [comment]
Is this also happening on the release, or only master?

**Comment by Frago9876543210** [comment]
IDK, tested on master

**Comment by Frago9876543210** [comment]
![default](https://user-images.githubusercontent.com/13465245/50558287-c8678f00-0cfd-11e9-9753-b5e1ca1f96c7.png)

**Comment by JUSTaMod** [comment]
Release 3.5.3 running on a Windows box has expected behavior. red is red. blue is blue. colors is colors.
