### ISSUE TITLE
PlayerInteractEvent isn't called in spectator mode

### ISSUE THREAD

**Issue by Driesboy** [pmmp/PocketMine-MP#2627]
### Issue description

- Expected result: What were you expecting to happen?
PlayerInteractEvent works in Spectator mode
- Actual result: What actually happened?
PlayerInteractEvent doesn't work in Spectator mode
### Steps to reproduce the issue

1. echo on PlayerInteractEvent
2. set yourself into Spectator mode

### OS and versions

* PocketMine-MP: https://github.com/pmmp/PocketMine-MP/commit/d33acc4fd0b7e7a19d6016939b01cb33e51272ed
* PHP: 7.2.12
* Server OS: Linux
* Game version: PE/Win10

### Plugins
- Test on a clean server without plugins: is the issue reproducible without any plugins loaded?
Yes, sir

If the issue is **not** reproducible without plugins:
- Have you asked for help on our forums before creating an issue?
- Can you provide sample, *minimal* reproducing code for the issue? If so, paste it in the bottom section
- Paste your list of plugins here (use the 'plugins' command in PocketMine-MP)

### Crashdump, backtrace or other files
- Do not paste crashdumps into an issue - please use our Crash Archive at https://crash.pmmp.io for submitting crash reports to not spam the issue tracker. Add links to your reports in the Crash Archive here.
- Please use gist or anything else to add other files and add links here

* ...

**Comment by dktapps** [comment]
This isn't actually a bug, it's just an excessive restriction. I remember lots of issue reports about players being able to do things in spectator that they shouldn't have been able to, so it was a blanket restriction I put in place when 1.2 brought the InventoryTransactionPacket.

However, it is clearly too heavy a restriction and more fine-tuning is required.

**Comment by dktapps** [comment]
It turns out there are more problems with this than I initially thought. The blanket restriction hides a lot of bugs.
