### ISSUE TITLE
Address useless parameters on Living->knockBack()

### ISSUE THREAD

**Issue by dktapps** [pmmp/PocketMine-MP#2634]
Many developers have been complaining about this since 2014, but it still hasn't been addressed. This is due to concerns over backwards compatibility.

References:
PocketMine/PocketMine-MP#3427

I particularly take issue with [this comment](https://github.com/PocketMine/PocketMine-MP/pull/3427#issuecomment-136413879). Knockback is simply "knocking back" from an origin location, and can be applied irrelevant of any entity. The argument about child implementations using it is fallacious because no such methods exist in either PocketMine-MP or MCJE (where the code was originally ripped off from).

**Comment by lukeeey** [comment]
Just wondering if this is gonna be addressed in 4.0 (might as well make the most of the chance to add BC breaks)
