### ISSUE TITLE
"moved too fast, reverting movement" moves player above ground (mcpe-1.0)

### ISSUE THREAD

**Issue by markkrueg** [pmmp/PocketMine-MP#264]
### Issue description
When a player activates the "moved too fast" check and is underground, the "reverting movement" will place them above ground.

Also the "moved too fast" check may be overly sensitive?

### Steps to reproduce the issue
1. Create steps going deep into the ground. Regular blocks, not stairs blocks.
2. Run down the steps.
3. Console will read "xxxxxx moved too fast, reverting movement"
4. Player will be transported above ground.

### OS and versions
* PocketMine-MP: PocketMine-MP 1.6.2dev 「Unleashed」 implementing API version 3.0.0-ALPHA2 for Minecraft: PE v1.0.0.16 (protocol version 100) commit bcf049a
* PHP: 7.0.10
* Server OS: Ubuntu 16.04.1 LTS
* Game version: Android 1.0.0

**Comment by dktapps** [comment]
In most cases it is a false-positive, I added that message so we know when the server is doing weird stuff. If you would like to test #259, please feel free. Do be aware that walking on stairs may still cause issues due to their bounding boxes not being properly implemented server-side.

**Comment by dktapps** [comment]
References: #258

**Comment by markkrueg** [comment]
> If you would like to test #259, please feel free.

Early testing looks good. I believe commit 2046a02 from #259 may have fixed this issue.

**Comment by markkrueg** [comment]
Is it OK for me to close this? I haven't been able to reproduce it since applying 2046a02.

**Comment by dktapps** [comment]
It'll be closed when the PR is merged, doing some housework on it at the moment.

**Comment by dktapps** [comment]
Fixed in #259
