### ISSUE TITLE
Switching between to items while hitting someone gives you an extra hit

### ISSUE THREAD

**Issue by T14Raptor** [pmmp/PocketMine-MP#2642]
### Issue description
While switching between two items in your hotbar while hitting someone theirs a chance that you will hit them twice when your suppose to only hit them once. This has been an issue in many PvP servers.

### Steps to reproduce the issue
1. Switch between two items in your hotbar multiple times
2. While switching start hitting someone
3. Keep doing it until it happens

### OS and versions
* PocketMine-MP: 3.5.4
* PHP: 7.2.13
* Server OS: Windows
* Game version: Win10 (Not tested on PE)

**Comment by T14Raptor** [comment]
[switchingrepoduc.zip](https://github.com/pmmp/PocketMine-MP/files/2729418/switchingrepoduc.zip)

here is a vid of a repoduction of it ^

**Comment by T14Raptor** [comment]
Here is a better sufficient reproduction of the bug, https://www.mediafire.com/file/ap47biviq06jbop/AD89819B-21FD-4DA0-8E3E-F29ECA6AC183.MOV/file

**Comment by Vrysed** [comment]
> This is not sufficient information to reproduce the problem. Do you have a video or further details?

Take a sword in slot #1 and have nothing in #2 hit someone rapidly while switching between those 2 fast rapidly

**Comment by dktapps** [comment]
.... why close this?
