### ISSUE TITLE
Cobble turns to Dirt when broken (mcpe-1.0)

### ISSUE THREAD

**Issue by markkrueg** [pmmp/PocketMine-MP#265]
### Issue description
When breaking cobblestone blocks, they will occasionally change to unbroken dirt blocks at the point of breaking.

### Steps to reproduce the issue
1. Use the included world file (it is freshly generated with only this stairway created).
2. Break blocks as shown in the video with diamond pickaxe.

### OS and versions
* PocketMine-MP: PocketMine-MP 1.6.2dev 「Unleashed」 implementing API version 3.0.0-ALPHA2 for Minecraft: PE v1.0.0.16 (protocol version 100) commit bcf049a
* PHP: 7.0.10
* Server OS: Ubuntu 16.04.1 LTS
* Game version: Android 1.0.0

### Crashdump, backtrace or other files
https://youtu.be/Ttjv8LZi43U
[world.zip](https://github.com/pmmp/PocketMine-MP/files/706891/world.zip)

**Comment by markkrueg** [comment]
As a sanity check, I went back into the zipped world and tried to reproduce. Now I cannot reproduce it. It happened maybe 5 or 6 times before I shot the video and compressed the world, and it's clearly occurring in the video. But now I can't seem to make it happen again. Maybe it was specific to the memory situation during that run? I stopped the server shortly after. No plugins running; just fresh git clone of branch mcpe-1.0 as of bcf049a.

I will keep trying, but I understand if you want to close this for not being reproducable :-(

**Comment by dktapps** [comment]
I believe this may only happen in a freshly-generated world. May be something to do with ore population and changed chunks not getting resent.

**Comment by dktapps** [comment]
This issue is similar to that of the half-trees problem. Seems to be chunks sent before they are populated, causing visual discrepancies. Rejoining will show an area that was previously apparently stone to actually be dirt. Will investigate.

**Comment by dktapps** [comment]
Would anybody like to test the referenced commit (`issues/265`)?
