### ISSUE TITLE
Splash potion effect fluctuation?

### ISSUE THREAD

**Issue by artulloss** [pmmp/PocketMine-MP#2650]
### Issue description

- Expected result: I expected the same amount of health per potion.
- Actual result: Fluctuates, talked about in the discord and this fluctuation should be done based off the eye height rather than the feet.

### Steps to reproduce the issue
1. Throw a splash potion
2. Health regained from a health potion fluctuates based on how far it is from feet rather than the players eye height, tons of health from a health splash potion if thrown directly up.

### OS and versions

* PocketMine-MP: 3.5.X ?
* PHP: 7.2
* Server OS: Linux
* Game version: All, video is from a PE player

### Plugins

- If you remove all plugins, does the issue still occur? Yes, nothing modified splash potion entities
- If the issue is **not** reproducible without plugins:
  - Have you asked for help on our forums before creating an issue?
  - Can you provide sample, *minimal* reproducing code for the issue? If so, paste it in the bottom section

### Video of a player who reported it

https://m.youtube.com/watch?v=ApcxNqvbu5U

**Comment by dktapps** [comment]
I'm unsure what the problem is here, since an entity hit by the potion will always receive 100% intensity hit, as seen here: https://github.com/pmmp/PocketMine-MP/blob/3380aa3ac2b25692882738b6d94bd4856788801d/src/pocketmine/entity/projectile/SplashPotion.php#L94

**Comment by dktapps** [comment]
I observed today that a splash potion thrown at a wall when right up against the wall only delivers 60% of the effect duration. Night vision splash delivers 6min for a full hit, yield 3:38 when thrown at a block directly in front of the face when pressed against a wall.

**Comment by dktapps** [comment]
@artulloss I'm not able to reproduce the problem shown in the video. In vanilla PM a splash potion of instant health delivers 4 hearts of health, exactly as expected. I can only assume you have a plugin which is interfering with it.

You can test it on `dev1.ams.pmmp.io` if you want to verify.

I'll leave this issue open since there are indeed problems with splash potion durations, but the video demonstration is invalid.
