### ISSUE TITLE
LevelSoundEventPacket error???

### ISSUE THREAD

**Issue by SiNo195** [pmmp/PocketMine-MP#2656]
The value in the disableRelativeVolume field continues to sound relative volume.

//// my source ////
$pk = new LevelSoundEventPacket();
        $pk->sound = LevelSoundEventPacket::SOUND_CAMERA_TAKE_PICTURE;
        $pk->disableRelativeVolume = true;
        $pk->position = $player->asVector3();
        $player->sendDataPacket($pk);

I want the ability to hear sounds anytime, anywhere. But it's not working.

**Comment by dktapps** [comment]
Was the first issue getting closed not sufficient? ...
