### ISSUE TITLE
Top Snow & Air Ticks bug

### ISSUE THREAD

**Issue by SonsaYT04** [pmmp/PocketMine-MP#2657]
### Issue description
getInAirTicks run when standing on top snow with 4 layers and above

### Steps to reproduce the issue
1. ... Place 4 layers of Top Snow
2. ... Stand on it

### OS and versions
* PocketMine-MP: This server is running PocketMine-MP 3.5.4 for Minecraft: Bedrock Edition v1.8.0 (protocol version 313)
* PHP: 7.2
* Server OS: Linux
* Game version: PE/Win10

![minecraft 11_01_2019 11_09_31 pm](https://user-images.githubusercontent.com/31030234/51042266-d28b6680-15f6-11e9-9837-d892c4fed1ad.png)

**Comment by JBGamer1** [comment]
idk

**Comment by dktapps** [comment]
Multi-layer snow isn't implemented yet. The collision box is supposed to increase in size as the layer count increases.
