### ISSUE TITLE
Bow inconsistent between Java, Vanilla Bedrock and Pocketmine

### ISSUE THREAD

**Issue by artulloss** [pmmp/PocketMine-MP#2660]
This video posted by the discord user Andrew#3801 does a good job demonstrating this issue.

Java left, Pocketmine right, bottom is Vanilla Bedrock.

https://viewsync.net/watch?v=JfRvHm7OQ7Q&t=7&v=v0kuRRjEpyw&t=18&v=Lh1pBjnVrEA&t=4

**Comment by dktapps** [comment]
[for posterity's sake]
Initial investigation of the issue indicates that vanilla arrows are fired with 50% more force than PM's arrows due to incorrect multiplier. It's expected that PM arrows should approximately match JE arrows since that's where shoghi initially ripped the code from.

**Comment by dktapps** [comment]
Some more detailed tests - fully charged bow shot from 10 block tall tower, with a yaw and pitch of 0:
- MCPE: ~100 blocks
- MCJE: ~50 blocks
- PM: ~30 blocks

So...there's definitely a problem there. However, the discrepancy between PC and PE is very large, so we may have also identified a bug in MCPE.
