### ISSUE TITLE
Chest bugg

### ISSUE THREAD

**Issue by WeLove1Coder** [pmmp/PocketMine-MP#2662]
my crates are invisible but i can not open them i try that i will be thrown from the server with the reason Internel Server Error. I try to mine the crate I will be kicked. Therefore, the error comes I have the first here created an issue xD

**Comment by dktapps** [comment]
**Without knowing your PocketMine-MP version, OS, PHP, Client version, or plugins and how the issue occurred, the issue cannot begin to be solved.**
A pre-formatted template is provided that shows the required information to begin to find, test and solve an issue.
Until the adequate template and information is provided, the issue will be closed; it may be reopened if you update the ticket with the correct template and required information.

[Contribution guidelines](https://github.com/pmmp/PocketMine-MP/blob/master/CONTRIBUTING.md)
