### ISSUE TITLE
Block ID -148 is out of bounds

### ISSUE THREAD

**Issue by SiNo195** [pmmp/PocketMine-MP#2674]
### OS and versions

* PocketMine-MP: 3.5.5
* PHP: 7.2
* Server OS: Ubuntu 16.04
* Game version: PE/Win10 (delete as appropriate)

### Crashdump, backtrace or other files
File: src/pocketmine/block/BlockFactory
Line: 397
Type: InvalidArgumentException

Code:

Backtrace:
#0 src/pocketmine/item/ItemBlock(47): pocketmine\block\BlockFactory::get(integer -148, integer 0)
#1 src/pocketmine/item/ItemBlock(43): pocketmine\item\ItemBlock->getBlock()
#2 src/pocketmine/item/ItemFactory(324): pocketmine\item\ItemBlock->__construct(integer -148, integer 0)
#3 src/pocketmine/item/Item(973): pocketmine\item\ItemFactory::get(integer -148, integer 0, integer 2)
#4 src/pocketmine/tile/ContainerTrait(52): pocketmine\item\Item::nbtDeserialize(pocketmine\nbt\tag\CompoundTag object)
#5 src/pocketmine/tile/Chest(61): pocketmine\tile\Chest->loadItems(pocketmine\nbt\tag\CompoundTag object)
#6 src/pocketmine/tile/Tile(167): pocketmine\tile\Chest->readSaveData(pocketmine\nbt\tag\CompoundTag object)
#7 src/pocketmine/tile/Spawnable(61): pocketmine\tile\Tile->__construct(pocketmine\level\Level object, pocketmine\nbt\tag\CompoundTag object)
#8 src/pocketmine/tile/Tile(112): pocketmine\tile\Spawnable->__construct(pocketmine\level\Level object, pocketmine\nbt\tag\CompoundTag object)
#9 src/pocketmine/level/format/Chunk(729): pocketmine\tile\Tile::createTile(string Chest, pocketmine\level\Level object, pocketmine\nbt\tag\CompoundTag object)
#10 src/pocketmine/level/Level(2803): pocketmine\level\format\Chunk->initChunk(pocketmine\level\Level object)
#11 src/pocketmine/level/Level(2385): pocketmine\level\Level->loadChunk(integer 12, integer 24, boolean 1)
#12 src/pocketmine/level/Level(3066): pocketmine\level\Level->getChunk(integer 12, integer 24, boolean 1)
#13 src/pocketmine/Player(1045): pocketmine\level\Level->populateChunk(integer 12, integer 24)
#14 src/pocketmine/Player(1819): pocketmine\Player->sendNextChunk()
#15 src/pocketmine/Server(2599): pocketmine\Player->checkNetwork()
#16 src/pocketmine/Server(2344): pocketmine\Server->tick()
#17 src/pocketmine/Server(2207): pocketmine\Server->tickProcessor()
#18 src/pocketmine/Server(1783): pocketmine\Server->start()
#19 src/pocketmine/PocketMine(249): pocketmine\Server->__construct(BaseClassLoader object, pocketmine\utils\MainLogger object, string /home/skhidc/pm2/, string /home/skhidc/pm2/plugins/)
#20 (1): require(string phar:///home/skhidc/pm2/PocketMine-MP.phar/src/pocketmine/PocketMine.php)

**Comment by dktapps** [comment]
You need to update submodules and composer dependencies after switching git branches.

**Comment by SiNo195** [comment]
How to update submodules and composer dependencies?
