### ISSUE TITLE
An unknown error

### ISSUE THREAD

**Issue by hachkingtohach1** [pmmp/PocketMine-MP#2679]
![screenshot 470](https://user-images.githubusercontent.com/29000265/51434357-6dd4a980-1c91-11e9-92a3-6fc35d954ca6.png)

**Comment by hachkingtohach1** [comment]
it keeps repeating without bringing the player to death. ?

**Comment by 95CivicSi** [comment]
This looks like a plugin error @hachkingtohach1

**Comment by dktapps** [comment]
Without knowing your PocketMine-MP version, OS, PHP, Client version, or plugins and how the issue occurred, the issue cannot begin to be solved.
A pre-formatted template is provided that shows the required information to begin to find, test and solve an issue.
Until the adequate template and information is provided, the issue will be closed; it may be reopened if you update the ticket with the correct template and required information.

[Contribution guidelines](https://github.com/pmmp/PocketMine-MP/blob/master/CONTRIBUTING.md)
