### ISSUE TITLE
Missing effects

### ISSUE THREAD

**Issue by drewsucksatlife** [pmmp/PocketMine-MP#268]
### Issue description

Write a short description about the issue
(I'm sure you guys already know about it) PocketMine-MP is missing some effects. The missing effects are healing, absorption, and harming.
### Steps to reproduce the issue

1. Do /effect (name) effectname

### OS and versions

* PocketMine-MP: https://github.com/pmmp/PocketMine-MP/commit/cb187be1a1b86e0200a9c6bb3583374c4841cbb0
* PHP: 7.0.14
* Server OS: Windows 10
* Game version: PE/Win10

### Crashdump, backtrace or other files

* ...

**Comment by dktapps** [comment]
Wait, effect names work in the command? AFAIK they didn't...

**Comment by AppleDevelops** [comment]
I've been able to do /effect (name) healing on my version of PM. (Mine isn't much different all I did on mine is add missing effects and potions)

**Comment by dktapps** [comment]
Please ensure you do testing against the official repository as opposed to forks to avoid causing confusion.

**Comment by AppleDevelops** [comment]
I am using the official PMMP PocketMine just my modded version for my server.

**Comment by flaxues** [comment]
I'm able to do /effect name regeneration without any plugins or modifications...

**Comment by dktapps** [comment]
It was enchanting I was thinking of. My bad.

**Comment by dktapps** [comment]
The missing effects noted here have been implemented on a development branch. However new ones have been added since, and there are others which will not work correctly due to anti-cheat interference and lack of server-side implementation. Will leave this open for that reason.
