### ISSUE TITLE
Missing chat

### ISSUE THREAD

**Issue by ReicitoE** [pmmp/PocketMine-MP#2687]
I've got plugins, so that may be it. but the chat does not update when players chat. they can see server messages but not Other player messages

**Comment by SOF3** [comment]
Cannot reproduce on a vanilla server. Most likely a plugin issue.

**Comment by dktapps** [comment]
Without knowing your PocketMine-MP version, OS, PHP, Client version, or plugins and how the issue occurred, the issue cannot begin to be solved.
A pre-formatted template is provided that shows the required information to begin to find, test and solve an issue.
Until the adequate template and information is provided, the issue will be closed; it may be reopened if you update the ticket with the correct template and required information.

[Contribution guidelines](https://github.com/pmmp/PocketMine-MP/blob/master/CONTRIBUTING.md)
