### ISSUE TITLE
Can't log in to the local server

### ISSUE THREAD

**Issue by MaxLucky26** [pmmp/PocketMine-MP#2691]
### Issue description

- Expected result: Thought I would log onto the server

- Actual result: The client token matched the server, so I couldn't log in

### Steps to reproduce the issue
1. Start the server
2. Login to client
3. Click on local server

### OS and versions

* PocketMine-MP: 3.5.7
* PHP: 7.2
* Server OS: Windows 10
* Game version: Win10

### Plugins

1. DevTools v1.13.1

- If you remove all plugins, does the issue still occur? (yes)

### Crashdump, backtrace or other files

1. https://imgur.com/a/8MZyiqk
2. https://imgur.com/a/TZ7puoD

**Comment by nnnlog** [comment]
Did you check your client's time?

**Comment by MaxLucky26** [comment]
> Did you check your client's time?

How to view the client's time? If you are talking about the device, it is the same as on the running local server. Because the local server is on the same device as the client.

**Comment by dktapps** [comment]
Is the message not self explanatory? Your system time is wrong.

3.5.7 is more tolerant of wrong time, but if your clock is more than 1 minute fast or slow you need to fix it.

**Comment by MaxLucky26** [comment]
> Is the message not self explanatory? Your system time is wrong.
> 
> 3.5.7 is more tolerant of wrong time, but if your clock is more than 1 minute fast or slow you need to fix it.

Really. Sorry for spam.
