### ISSUE TITLE
Canceling Projectile Launch Event does not return items to Player's inventory.

### ISSUE THREAD

**Issue by 95CivicSi** [pmmp/PocketMine-MP#2693]
### Issue description
If a listener is used to cancel ProjectileLaunchEvent, the player's inventory is still reduced.
- Expected result: When canceling a ProjectileLaunchEvent, items such as splash potions or snow balls should return to the player's inventory.
- Actual result: Player's inventory is reduced even if the event is canceled.

### Steps to reproduce the issue
1. Create a basic plugin with a listener that cancels all `ProjectileLaunchEvent`s
2. Give the player an item that can be thrown or a bow and arrow.
3. Attempt to throw the item or shoot the bow.  Notice that the projectile despawns but the item does not return to the player's inventory.

### OS and versions

* PocketMine-MP: 3.5.8-dev
* PHP: 7.2.13
* Server OS: Windows / Ubuntu 18.04
* Game version: PE/Win10 (both)

### Plugins

[00:03:31] [Server thread/INFO]: Plugins (2): DevTools v1.13.1, TestPlugin v0.0.1
- If you remove all plugins, does the issue still occur?
- If the issue is **not** reproducible without plugins: This is not reproducible without plugins. See below.
  - Have you asked for help on our forums before creating an issue?
  - Can you provide sample, *minimal* reproducing code for the issue? If so, paste it in the bottom section

### Crashdump, backtrace or other files

```php
<?php

declare(strict_types=1);

namespace FiberglassCivic\TestPlugin;

use pocketmine\event\entity\ProjectileLaunchEvent;
use pocketmine\event\Listener;
use pocketmine\plugin\PluginBase;

class Main extends PluginBase implements Listener {

    public function onEnable(): void {
        $this->getServer()->getPluginManager()->registerEvents($this, $this);
    }

	public function onProjectileLaunch(ProjectileLaunchEvent $event) {
        $event->setCancelled();
    }
}

```

It may be helpful to note that when canceling `EntityShootBowEvent`, the arrow properly returns to the player.

**Comment by dktapps** [comment]
Worth nothing that `ProjectileLaunchEvent` is independent from any thrower or source.
