### ISSUE TITLE
Error when opening a single chest after the explosion of a double chest

### ISSUE THREAD

**Issue by luca28pet** [pmmp/PocketMine-MP#2701]
### Issue description

- Expected result: What were you expecting to happen? You can open a chest after an explosion with no errors
- Actual result: What actually happened? Client gets disconnected with "Internal server error"; error shows up in console: Error: "Call to a member function getBlock() on null" (EXCEPTION) in "src/pocketmine/block/Chest" at line 116

### Steps to reproduce the issue
1. Place a double chest
2. Place a TNT block near it, so it is 4/5 blocks away from the double chest
3. Ignite the TNT, the explosion should only break one block of the double chest, leaving the remaining one placed as a single chest
4. Open the remaining chest
5. Get disconnected with "Internal server error"

### OS and versions

* PocketMine-MP: 3.5.7
* PHP: 7.2.13
* Server OS: Windows 10 / Ubuntu 18.04
* Game version: Both

### Plugins

- If you remove all plugins, does the issue still occur? Yes, the issue occurs on a fresh installation
- If the issue is **not** reproducible without plugins:
  - Have you asked for help on our forums before creating an issue?
  - Can you provide sample, *minimal* reproducing code for the issue? If so, paste it in the bottom section

### Crashdump, backtrace or other files
Error and backtrace: https://pastebin.com/yLc2SKZ0
Video on how to reproduce: https://youtu.be/AlC7JJm593E

**Comment by dktapps** [comment]
I believe the problem is here: https://github.com/pmmp/PocketMine-MP/blob/4b9a142a5d9d5bfa8f2097b5414fa49d8b6991c1/src/pocketmine/level/Explosion.php#L222
The double chest will not be unpaired if `$yieldDrops` is `false`.

**Comment by dktapps** [comment]
The referenced commit will prevent the issue from occurring in future explosions, but chests which are already affected will continue to crash when opened. You can delete and recreate them to fix this issue.

This issue is pending automatic detection of destroyed pairs. The pair handling code is abhorrent right now.
