### ISSUE TITLE
Unable to detect the IP properly if there's more than one adapter

### ISSUE THREAD

**Issue by Johnmacrocraft** [pmmp/PocketMine-MP#2702]
### Issue description

- Expected result: The server was supposed to be able to port-forward with UPnP without any problems
- Actual result: The server fails to detect its proper internal IP, failing to UPnP port-forward while the process was successful.

As mentioned on Discord, this also happens with install wizard ip detection.

### Steps to reproduce the issue
1. Have more than one IP (network adapter) on the machine
2. Enable UPnP port-forwarding on pocketmine.yml
3. Run server
4. The server says the port-forwarding was successful but you can't join nor see MOTD
5. Disable other network adapters except the main one
6. Run server again
7. The UPnP works like a charm

### OS and versions

* PocketMine-MP: 3.5.7
* PHP: 7.2.14
* Server OS: Windows 10
* Game version: PE/Win10 (delete as appropriate)

### Plugins

- If you remove all plugins, does the issue still occur? Yes
- If the issue is **not** reproducible without plugins:
  - Have you asked for help on our forums before creating an issue?
  - Can you provide sample, *minimal* reproducing code for the issue? If so, paste it in the bottom section

**Comment by dktapps** [comment]
To clarify, this problem only occurs when your desired network adapter does not have the highest priority on the list. I personally experienced this with a VirtualBox adapter that jumped to the top of a list of several adapters, and UPnP would not work as expected until that adapter was disabled.

**Comment by dktapps** [comment]
Turns out the cause is pretty obvious... you can't map a port to more than 1 IP at a time. This means it's necessary to find some other way to identify the correct internal IP address.
