### ISSUE TITLE
Knockback is so much

### ISSUE THREAD

**Issue by phoshp** [pmmp/PocketMine-MP#2707]
### Issue description
Knockback is so much according to vanilla mcpe

### Steps to reproduce the issue
1. Place a entity (ex: villager)
2. Get a enchanted item with knockback
3. Attack to entity
4. Compare this with vanilla mcpe

### OS and versions

* PocketMine-MP: 3.5.x
* PHP: 7.2.0
* Server OS: Windows 10
* Game version: Win10 1.8

### Crashdump, backtrace or other files

[in pmmp](https://youtu.be/h4PciGEe-Ck)
[in vanilla](https://youtu.be/_oT3zWWgFk0)

**Comment by dktapps** [comment]
[for readers] In case anyone is reading this and thinks the fix is simple: you're right.
However, we want to avoid more problems like #2315 . Knockback is a delicate area, so any fix needs to be treated with caution.

**Comment by dktapps** [comment]
This is fixed for PM4. The fix won't be backported due to potential BC break.
