### ISSUE TITLE
Thrown items bounce on slabs

### ISSUE THREAD

**Issue by AppleDevelops** [pmmp/PocketMine-MP#271]
### Issue description

Write a short description about the issue
When you throw items on half slabs they bounce on the slabs

### Steps to reproduce the issue

1. Place a half slab
2. Throw an item
3. Watch the magic :)

### OS and versions

* PocketMine-MP: https://github.com/pmmp/PocketMine-MP/commit/162b993e65f2e15b25d1997af3b0e77db2bc2de7
* PHP: 7.0.14
* Server OS: Windows 10
* Game version: PE/Win10

### Crashdump, backtrace or other files

* ...

**Comment by dktapps** [comment]
Yep, this bug is years old. Bounding box issues.

**Comment by Whatevr** [comment]
if im not mistaken it also works on stairs, just telling

**Comment by dktapps** [comment]
PocketMine-MP thinks stairs have the same bounding boxes as slabs do, so that's expected. (That's also why movement checks kick in when you run up stairs.) Any partial block (farmland for example) has this issue. Related to #169 .

**Comment by ICrashHD** [comment]
www.pornhub.com/pornstar/leah-gottiwww.pornhub.com/pornstar/leah-gottiwww.pornhub.com/pornstar/leah-gottiwww.pornhub.com/pornstar/leah-gottiwww.pornhub.com/pornstar/leah-gottiwww.pornhub.com/pornstar/leah-gottiwww.pornhub.com/pornstar/leah-gottiwww.pornhub.com/pornstar/leah-gottiwww.pornhub.com/pornstar/leah-gottiwww.pornhub.com/pornstar/leah-gottiwww.pornhub.com/pornstar/leah-gottiwww.pornhub.com/pornstar/leah-gottiwww.pornhub.com/pornstar/leah-gottiwww.pornhub.com/pornstar/leah-gottiwww.pornhub.com/pornstar/leah-gottiwww.pornhub.com/pornstar/leah-gottiwww.pornhub.com/pornstar/leah-gottiwww.pornhub.com/pornstar/leah-gottiwww.pornhub.com/pornstar/leah-gottiwww.pornhub.com/pornstar/leah-gottiwww.pornhub.com/pornstar/leah-gotti

**Comment by dktapps** [comment]
This appears to be an issue with Entity->move() not taking partial blocks into account.

**Comment by dktapps** [comment]
https://github.com/pmmp/PocketMine-MP/blob/master/src/pocketmine/entity/Entity.php#L864 the issue is located within this function.

**Comment by dktapps** [comment]
This is because of the code checking for solid blocks when attempting to "push" the item entity out of blocks. However, the code assumes that any blocks that the item entity is colliding with is a full 1x1x1 cube, resulting in the item entity being _pushed_ upwards "out" of the block.

**Comment by Driesboy** [comment]
WHOHO FINALY
