### ISSUE TITLE
Unwanted behavior of sugarcane

### ISSUE THREAD

**Issue by JackMD** [pmmp/PocketMine-MP#2714]
### Issue description

If a block is placed on top of a sugarcane and the the sugar cane is given some bonemeal, the sugarcane grows on top of the block as see in the screenshot attached below.

- Expected result: What were you expecting to happen? 
Sugar cane to not grow on the block when given bonemeal.
- Actual result: What actually happened?
Sugar cane skips the block and grows on top of it.

### Steps to reproduce the issue
1. Place down a sugarcane.
2. Place a block directly on top of the sugar cane.
3. Bonemeal the sugar cane.
4. Watch it grow on top of the block.

### OS and versions

Tested on PocketMine Public Dev Server.
IP: dev1.ams.pmmp.io 

### Screenshot

![screenshot_20190129-210817_toolbox for minecraft](https://user-images.githubusercontent.com/32965703/51923601-1fe84000-240d-11e9-958f-d650a4593f61.jpg)

**Comment by dktapps** [comment]
This code is written in such a dumb way it's hardly surprising. In fact it almost looks like it was designed to do this.
