### ISSUE TITLE
Regeneration randomly stops

### ISSUE THREAD

**Issue by artulloss** [pmmp/PocketMine-MP#2716]
### Issue description

- Expected result: The player to keep getting regeneration for the length that they have the effect.
- Actual result: The player keeps the effect, however their hearts stop going up the same way as they do when they have regen, instead, they go up slowly as if they don't have the effect.

### Steps to reproduce the issue
1. Give 2 players regeneration?
2. Attack one of them and repeat a few times until the weird behavior happens

### OS and versions

* PocketMine-MP:
* PHP: 7.2
* Server OS: 3.5.7
* Game version: All

### Plugins

- If you remove all plugins, does the issue still occur?
- If the issue is **not** reproducible without plugins:
  - Have you asked for help on our forums before creating an issue?
  - Can you provide sample, *minimal* reproducing code for the issue? If so, paste it in the bottom section

### Crashdump, backtrace or other files
No

### Video demonstrating the issue

https://www.youtube.com/watch?v=ZBTPt9KVOC0&feature=youtu.be

Notice that the player attacking does not regen very fast, unlike the person they're hitting who regens fast enough to not take any damage. Also notice that the regen level is 3, so it's not like this is a super low regen level. Both players are getting the same kit so the effects should be identical.

**Comment by dktapps** [comment]
I haven't been able to reproduce this in my initial tests. Please try reproducing it on dev1.ams.pmmp.io:19132 .

**Comment by dktapps** [comment]
I tested this on the dev server with a 0 tick cooldown and the bug doesn't reproduce.

**Comment by artulloss** [comment]
Ok, that's really odd. Try it with 2 as the cooldown maybe? This issue is really bothering me, I haven't modified any effects and I'm running the latest release phar.
