### ISSUE TITLE
Incorrectly structured generator settings produce unexpected behaviour instead of erroring out

### ISSUE THREAD

**Issue by dktapps** [pmmp/PocketMine-MP#2717]
### Issue description
Using a bad preset that can't be parsed results in a void world being generated instead of parsing errors being reported.

### Steps to reproduce the issue
1. Use a flatworld preset like this: `2;bedrock,dirt,log;1`
2. Join the world and notice it's completely devoid of blocks

### OS and versions

* PocketMine-MP: 3.5.7
* PHP: 7.2.13
* Server OS: linux

**Comment by dktapps** [comment]
This should be handled in the same manner as level corruption (for existing worlds).

**Comment by dktapps** [comment]
In addition the flatworld preset parser permits generating unknown / invalid blocks, which shouldn't be possible.

**Comment by thebigsmileXD** [comment]
On an additional note, there should be a generator option parser/builder class.
As mentioned on Discord, the advantage of using a string is easier pthreads passing.
