### ISSUE TITLE
Request Support for 1.9.0 (Quick Plz)

### ISSUE THREAD

**Issue by RainMa22** [pmmp/PocketMine-MP#2737]
As we can see 1.9.0 of minecraft Bedrock is here, we need a quick upgrade so that we can let players play in our servers again.
thank you for all the work!!!

**Comment by drewsucksatlife** [comment]
Don’t open issues asking for support for newer versions of Minecraft, that’s spam. Instead, wait patiently for PM to update.

**Comment by RainMa22** [comment]
Ok sorry about that...
