### ISSUE TITLE
Add option to disable RakLib notices ~ Blocked <IP address> for <seconds> seconds

### ISSUE THREAD

**Issue by Xenophilicy** [pmmp/PocketMine-MP#2741]
## Description
When a server list website (such as [Minecraft PE Servers](https://minecraftpeservers.org/)) pings the server, it sends a RakLibServer blocking message to the console and logs it, like this: Blocked <IP address> for <seconds> seconds

## Example
```[10:49:10] [RakLibServer thread/NOTICE]: Blocked 45.79.134.18 for 5 seconds```

## Justification
There should be an option to disable this because server chat is difficult to monitor with the unnecessary constant blue notice messages coming up, that way the message no longer shows unless it is needed. I run 5 servers, all of which have this message come up on them (mainly the lobby, the one attached to each server list site) and it gets a bit annoying when trying to read player chat.

## Alternative methods
I have tried to search the forums for ways that this can be prevented and I have found nothing, hence why I am here requesting an option. This is definitely not first priority, just an idea for convenience that I suppose can be easily implemented in the upcoming API updates.

Thanks!

**Comment by dktapps** [comment]
Just ban the IP permanently. Problem solved.

**Comment by Xenophilicy** [comment]
I guess that works too lol, thanks.

**Comment by Xenophilicy** [comment]
@dktapps I have just done this to my lobby server and while your method does in fact stop the messages, I am being indicated as offline on the server site now. Is there any other way to get around the issue?

**Comment by dktapps** [comment]
Yes, boycott that site and use a different one. They've received a large number of complaints about this and they've done nothing about it.

**Comment by Xenophilicy** [comment]
Ok, sounds good. Thanks for the help
