### ISSUE TITLE
Eating a golden apple while hunger bar is full

### ISSUE THREAD

**Issue by L3ice** [pmmp/PocketMine-MP#276]
### Issue description

You cannot eat a golden apple if you have full hunger bars.

### Steps to reproduce the issue

1. Make sure your hunger bars are full
2. Try to eat a golden apple

### OS and versions

* PocketMine-MP: 52748fcf64830453967fab4b43d6e823aeb37ecf (1.0)
* PHP: 7.0.14
* Server OS: Windows 10
* Game version: Win10
### Crashdump, backtrace or other files

* ...

**Comment by AppleDevelops** [comment]
Easy fix but I'd rather not commit
