### ISSUE TITLE
Ice Block Gravity

### ISSUE THREAD

**Issue by SuperAdam47** [pmmp/PocketMine-MP#2762]
### Issue description
- https://youtu.be/LAwEI92eIPk

### OS and versions

* PocketMine-MP: 3.6.1
* PHP: 7.2
* Server OS: Windows 10
* Game version: W10 1.9.0

**Comment by dktapps** [comment]
This is a vanilla bug, not PM. Look it up on https://bugs.mojang.com. Please test gameplay bugs in vanilla before reporting them in future.
