### ISSUE TITLE
Add behavior pack support

### ISSUE THREAD

**Issue by SuperAdam47** [pmmp/PocketMine-MP#2765]
## Description
behavior packs need for pm servers

**Comment by dktapps** [comment]
When a template is provided, we expect you to fill it out appropriately, not delete half of it.

Come back when there is something you can do with a behaviour pack that can't be done with a plugin. As of now, no such thing exists (except possibly scripting, which is experimental).

**Comment by MrRagtime** [comment]
there are more behavior packs then plugins for [Poggit](https://poggit.pmmp.io/)
like backpack, a wither storm like pack, player graves, expansive biomes, etc.

## Here is a list of them
https://mcpedl.com/category/addons/
