### ISSUE TITLE
Explosions create half-doors

### ISSUE THREAD

**Issue by dktapps** [pmmp/PocketMine-MP#2767]
### Issue description
![image](https://user-images.githubusercontent.com/14214667/52904261-703f0a80-3221-11e9-8740-14e942d3aed0.png)

- Expected result: Both halves of the door should be destroyed
- Actual result: Only the top half was destroyed, likely due to explosion proximity.

### Steps to reproduce the issue
1. Place a door
2. Set off TNT approximately 4 blocks away from the top half
3. If you're lucky, profit.

### OS and versions

* PocketMine-MP: b252be1c7a0976a91030f93360eaa17731e1374b
* PHP: 7.2.15
* Server OS: linux

**Comment by Driesboy** [comment]
Same happens to beds.

**Comment by dktapps** [comment]
yup, and any other double block. Not sure exactly how to address this off the hop... I suspect world transactions are going to become ubiquitous in the near future 😏
