### ISSUE TITLE
Hearts are not shown correctly after respawn when max health is manipulated

### ISSUE THREAD

**Issue by onebone** [pmmp/PocketMine-MP#2771]
### Issue description

- Expected result: Health should be full after respawn when max health is manipulated
- Actual result: Some health hearts are shown empty

The actual health value on server seems to set correctly but hearts are not shown correctly to client. If player gets damaged then the client gets the correct value of hearts.

### Steps to reproduce the issue
1. Set max health of player
2. Kill player and respawn

### OS and versions

* PocketMine-MP: 3.6.3+dev e16d8e31af714b78e8f7931825cf2dd717398485
* PHP: 7.2.13
* Server OS: Windows WSL
* Game version: Win10

### Plugins

There is only one plugin which manipulates health and max health which is used to reproduce the issue.

### Crashdump, backtrace or other files

N/A

**Comment by Del-Los-Leones** [comment]
He would say, Works On My Machine (?)

**Comment by dktapps** [comment]
it would be appreciated if you could provide some example code so I don't have to write my own :)

**Comment by onebone** [comment]
@dktapps 
```php

class Test extends PluginBase implements Listener {
	public function onEnable() {
		$this->getServer()->getPluginManager()->registerEvents($this, $this);
	}

	public function onPlayerInteract(PlayerInteractEvent $event) {
		$event->getPlayer()->setMaxHealth($event->getPlayer()->getMaxHealth() + 20);
	}
}
```

This is the test code I've tested. You can use /kill command to get respawned after setting adding health.

**Comment by dktapps** [comment]
I'm not sure what the problem is here. The attribute default is still 20 half-hearts, regardless of how much you increase the maximum. When the player dies, the attribute is reset to its default value. If you want to change that, you need to set the default value of the attribute to meet your expected behaviour.

**Comment by dktapps** [comment]
never mind... I see what the problem is.

**Comment by onebone** [comment]
:+1:

**Comment by Del-Los-Leones** [comment]
Now, it does work on our machine :)
