### ISSUE TITLE
Rcon not working

### ISSUE THREAD

**Issue by Nicolas-PL** [pmmp/PocketMine-MP#2784]
### Issue description

Hello !

Since last update on rcon protocol, i can't send command, i have this error : 

2019-02-22 [23:33:32] [RCON thread/INFO]: Disconnected client: /IP:PORT (ip of my game panel)

For information i use GSP-PANEL for manage servers. (the panel is not host on the game server)

2019-02-22 [23:36:03] [Server thread/INFO]: RCON running on 54.37.177.48:19149
2019-02-22 [23:36:03] [Server thread/INFO]: Opening server on g3.hmserv.eu:19149

### Steps to reproduce the issue
1. Set enable-rcon true / set rcon password in server.properties
2. Reboot (for save modification)
3. Send command 

### OS and versions
* PocketMine-MP:  PocketMine-MP version 3.6.3
* PHP:  7.2.15
* Server OS: Debian 9

### Plugins
I don't have plugins.

### Crashdump, backtrace or other files
No crash

Thanks !

**Comment by dktapps** [comment]
Postmortem: This issue came from a bad RCON client implementation in a control panel which relied on a password length reading bug fixed in January. Normal RCON clients (such as those used to connect to normal PC servers) are unaffected by the bug fix.

**Comment by Nicolas-PL** [comment]
Hi, Thanks for your research !

**Comment by TeamRazen** [comment]
I have the same issue!! please HELP thanks;
