### ISSUE TITLE
I can't leading-in myself world

### ISSUE THREAD

**Issue by 2680409985** [pmmp/PocketMine-MP#2785]

**Comment by ZizzyZizzy** [comment]
You apparently also can't follow instructions.

You know all that text you deleted to type in your unintelligible question? That said the same thing they will tell you here. **This is not a support forum.** This is for software bug reporting only.

The more non-bug related garbage they have to deal with, the less time they have to work on Pocketmine code updates. That means **YOU ARE SCREWING IT UP FOR EVERYONE**, so please stop it, read the instructions, and then post questions for support in the actual support forum. (Or maybe you like putting gasoline in your oil can...what do I know?)

**Comment by dktapps** [comment]
hey @ZizzyZizzy don't lose your cool my dude, we have automations with canned responses for exactly this reason :)
