### ISSUE TITLE
When can I see animals in server? 

### ISSUE THREAD

**Issue by 2680409985** [pmmp/PocketMine-MP#2786]
When can I see animals in server?

**Comment by drewsucksatlife** [comment]
February 31, 2019

**Comment by ZizzyZizzy** [comment]
**Please close this so the devs don't have to waste their time doing so.**

THIS IS NOT A SUPPORT FORUM. Go to the Pocketmine forums and post your questions there. In this case, this exact question has been asked probably 100 times, so you should search first.
