### ISSUE TITLE
PocketMine-SPL

### ISSUE THREAD

**Issue by Pav155** [pmmp/PocketMine-MP#279]
OS: Linux Ubuntu Server 16.04 (LATEST)
PocketMine: 1.0 (LATEST)
Binary: Installed by installer in PHP-BUILD-SCRIPTS (LATEST)

When I want to start server with a command ./start.sh it say to me this - [CRITICAL] Unable to find the PocketMine-SPL library. [CRITICAL] Please use provided builds or clone the repository recursively.

Can anyone help me with this?

**Comment by robske110** [comment]
>Please use provided builds or clone the repository recursively.

**Comment by dktapps** [comment]
THIS IS NOT A SUPPORT FORUM. Next time you will receive a ban, I had enough of you at iTX.

> Please use provided builds or clone the repository recursively.
