### ISSUE TITLE
Dropped items do not de-spawn after 5m if player disconnects (mcpe-1.0)

### ISSUE THREAD

**Issue by markkrueg** [pmmp/PocketMine-MP#280]
### Issue description
When items are dropped, and the player logs out, the items do not de-spawn after 5 minutes. This causes thousands of entities to build up on server over time. An example would be a player dying and deciding not to return to the game.

I have confirmed the below procedure. I have unconfirmed reports that items are still there days later.

### Steps to reproduce the issue
1. Dig some dirt and pick it up
2. Drop it in front of you
3. Log off
4. Wait 5 minutes
5. Log on
6. Dirt should still be there.
7. Wait another 5 minutes while watching it
8. Dirt de-spawns

### OS and versions
* PocketMine-MP: PocketMine-MP 1.6.2dev 「Unleashed」 implementing API version 3.0.0-ALPHA2 for Minecraft: PE v1.0.0.16 (protocol version 100) (commit b222327)
* PHP: 7.0.10
* Server OS: Ubuntu 16.04.1 LTS
* Game version: Android 1.0.2

**Comment by dktapps** [comment]
This is in line with vanilla behaviour. Dropped items in unloaded chunks do not age over time. For example in PC you can die thousands of blocks from home, and then travel back to the point of your death and find the items still sitting there. They are only despawned after they have been ticked 6000 times.

**Comment by markkrueg** [comment]
Ah, that makes sense. Sorry for the incorrect issue post. I guess it's time for a new ClearLagg type plugin for this edge case. Off I go to figure that out.

re: PC behavior. Wow, all these years I've been rushing back to my point of death and giving up when I knew it was way more than 5  minutes. Good to know! I can't believe I'm still learning stuff like this about minecraft after playing so many thousands of hours.

**Comment by robske110** [comment]
@markkrueg the need of ClearLagg is not existent, if you're just concerned about Lag. ClearLagg can only remove LOADED entities, and those are usually ticked, which means they will be removed anyways. The unloaded entities (in unloaded chunks) will just sit on the disk and do nothing to performance.

**Comment by markkrueg** [comment]
@robske110 Doh! Of course! Because unloaded chunks aren't being ticked anyway. Thanks for clarifying this *puts away old ClearLagg code*.
