### ISSUE TITLE
FallingBlock: Pos is outside of the world bounds

### ISSUE THREAD

**Issue by Muqsit** [pmmp/PocketMine-MP#2803]
Link to crashdump: https://pastebin.com/raw/by3rkDEE

### Additional comments
Commit: https://github.com/pmmp/PocketMine-MP/commit/5017e61cb2ef839231330b60f084044d81cea11f
The knockback faced by falling sand entities is manually altered through plugins this way:
```php
$sand->setMotion($sand->subtract($tnt)->normalize()->multiply(1.1));
```

**Comment by dktapps** [comment]
[for posterity] It appears this bug cannot occur without plugin involvement, since the falling block would have to move above the top of the world for this to happen, which does not happen under normal vanilla circumstances.
