### ISSUE TITLE
Reload is using chached files, instead of reading those again.

### ISSUE THREAD

**Issue by sero583** [pmmp/PocketMine-MP#2804]
### Issue description

- Expected result: It should read the file, not using the chached one.
- Actual result: It used a chached file, did not recognize any changes. Occurs on other plugins (for me!) also.

### Steps to reproduce the issue
1. Use a plugin, change the config and reload the server.

### OS and versions

* PocketMine-MP: PocketMine-MP 3.6.4 for Minecraft: Bedrock Edition v1.9.0 (protocol version 332)
* PHP: /
* Server OS: Windows 10
* Game version: Not related, but Win10

### Plugins

- EconomyAPI
- Own plugin
- PurePerms
- If you remove all plugins, does the issue still occur?
Cant confirm, since this is actually only testable afaik with plugins.
- If the issue is **not** reproducible without plugins:
  - Have you asked for help on our forums before creating an issue?
No.
  - Can you provide sample, *minimal* reproducing code for the issue? If so, paste it in the bottom section
… create a config.

**Comment by dktapps** [comment]
I'm closing this as WF because it is unreasonable to fix. We can only address the `config.yml` issue, but as far as other config files go, this is not realistically fixable, which would just introduce inconsistencies in the behaviour.

It is planned to remove /reload in the next major version.

**Comment by ZizzyZizzy** [comment]
The /reload command should have been removed from all versions of Minecraft years ago. It causes nothing but problems.

Plugin developers also don't code the feature properly, so you can end up with memory leaks and crashing, among other issues.

Good riddance, /reload.
