### ISSUE TITLE
Interact issue for mobile users in water.

### ISSUE THREAD

**Issue by xDanub** [pmmp/PocketMine-MP#2809]
Steps to reproduce:
1. Log onto a server while playing on a mobile device.
2. Have gapples in your hand.
3. Try to move and eat

**Comment by dktapps** [comment]
Without knowing your PocketMine-MP version, OS, PHP, Client version, or plugins and how the issue occurred, the issue cannot begin to be solved.
A pre-formatted template is provided that shows the required information to begin to find, test and solve an issue.
Until the adequate template and information is provided, the issue will be closed; it may be reopened if you update the ticket with the correct template and required information.

[Contribution guidelines](https://github.com/pmmp/PocketMine-MP/blob/master/CONTRIBUTING.md)
