### ISSUE TITLE
Grass can replace itself when placed by players

### ISSUE THREAD

**Issue by Johnmacrocraft** [pmmp/PocketMine-MP#2813]
### Issue description
Players can replace grass (this also includes tallgrass) with any of grasses. This does not happen in vanilla.

### Steps to reproduce the issue
1. Place any type of grass
2. Try to place any of the grasses again (the same type works too, but the other one is recommended for an easier look) in the same position
3. Notice that you hear the sound of placing and the grass being replaced

### OS and versions

Tested on PocketMine-MP master branch server
* Game version: PE/Win10 (delete as appropriate)

### Plugins

Once again, tested on PocketMine-MP master branch server

- If you remove all plugins, does the issue still occur?
- If the issue is **not** reproducible without plugins:
  - Have you asked for help on our forums before creating an issue?
  - Can you provide sample, *minimal* reproducing code for the issue? If so, paste it in the bottom section

**Comment by jasonwynn10** [comment]
Dead bushes should also not be able to replace grass

**Comment by dktapps** [comment]
I doubt that's intentional behaviour. Dead bush is non-replaceable, and non-replaceable pretty much always takes precedence over replaceable from what I've seen.

I'd recommend testing in PC 1.13 and not MCPE. (this doesn't imply that I've tested this myself, but as a side note.)

**Comment by dktapps** [comment]
re to the bush issue: In PC 1.14 snapshots they are only placeable on dirt, but can replace tallgrass.

**Comment by dktapps** [comment]
As far as I can tell, the behaviour is that any replaceable block can be replaced by anything except itself. This is a little difficult to implement in PM due to how block placement currently works. It will necessitate block transactions.

**Comment by dktapps** [comment]
Fixed by 334bf1277d6897cbc237b7be5f7c5f6ad7d8e8f1.
