### ISSUE TITLE
slab on fire

### ISSUE THREAD

**Issue by UnknownOre** [pmmp/PocketMine-MP#2819]
### Issue description
if you use flint and steel you can set the slab on fire
[Youtube video](https://youtu.be/tBuYzKd0p5c)

### Steps to reproduce the issue
1. use flint and steel to set slab on fire

### OS and versions

* PocketMine-MP:PocketMine-MP 3.6.5 for Minecraft: Bedrock Edition v1.9.0 (protocol version 332)
* PHP: 7.1
* Server OS: Linux

### Plugins
clean server

### Crashdump, backtrace or other files

**Comment by dktapps** [comment]
It appears the correct logic for this is if the block either
a) has a solid top face
b) is flammable.

Amusingly a similar bug exists in vanilla: 
![image](https://user-images.githubusercontent.com/14214667/59211384-9d843f80-8ba7-11e9-857f-7c8fe4effa61.png)

We don't currently have the logic needed to determine whether a face of a block is solid.
