### ISSUE TITLE
The server does not generate world

### ISSUE THREAD

**Issue by Frago9876543210** [pmmp/PocketMine-MP#2821]
### Issue description
See title

### Steps to reproduce the issue
1. Remove current world
2. Generate new
3. Join to server

### OS and versions
* PocketMine-MP: cc78c9ef1849938a6d7cbbc349f3457117b20e66
* PHP: 7.2.16
* Server OS: Ubuntu 18.04 LTS

### Plugins
Tested on clean server (master)

**Comment by dktapps** [comment]
This appears to be related to the specific generator behaviour. Flat world types are unaffected.
