### ISSUE TITLE
Disallow non-startup plugin loading

### ISSUE THREAD

**Issue by SOF3** [pmmp/PocketMine-MP#2825]
## Description
Following #2823, it is now possible to further regularize plugin loading lifecycle.

Plugins must not be (or requested to be) enabled after server startup.

It is still possible for plugins to request enabling another plugin as long as the server is still starting up (generally equivalent to the `Done (%gs)` message not yet emitted). However, plugins should not be enabled after server starts. In particular, no plugins can be loaded after any player has joined.

Plugins being disabled before server stop is another business.

## Pros
- More optimizations become possible
  - E.g. Handler lists might no longer need to support online insertion
- Reduces code complexity
  - Can force more things to happen before startup, less cases to consider
- Plugins no longer need to check for players already online when the server starts
- Plugin mutual dependency can be addressed properly
  - E.g. if A uses a feature from B and B uses a feature from A, their load order doesn't matter; instead, they can initialize the components required from each other during enable and perform interaction in a just-before-startup hook.
- Plugin load order can be correctly tuned. Plugins can now be confident that they are never enabled while their `loadbefore` plugins have already been enabled, and never have `softdepend` plugins starting up after they have been enabled.
- STARTUP plugins should not be allowed to load after server start anyway

## Cons
- Plugin managers can no longer immediately enable a plugin after a plugin is installed
  - But note that there aren't many people using plugin managers
  - Even less people want to enable plugins immediately
  - Not to mention cases where plugin does not work the first time (e.g. need configuration)
  - It is not a big deal to restart a server immediately or schedule a restart, given that many servers restart regularly (although they don't really need to)
  - Someone is usually on the console in case the plugin doesn't work

**Comment by SOF3** [comment]
Another issue is that plugins often cache their dependencies in startup. It is common to see something like this:

```php
public function onEnable() {
    $this->purePerms = $this->getServer()->getPluginManager()->getPlugin("PurePerms");
}
```

This may end up using the incorrect instance if *only* PurePerms is reloaded.

**Comment by dktapps** [comment]
To summarise internals discussions on this topic:

The real problem that this RFC is intended to solve is that there is currently no way to say "this plugin must ONLY load at startup and no other time". It's not a very good solution for this problem; it imposes restrictions on all plugins to prevent issues with a small subset of plugins which are actually affected by this problem. TL;DR: It's a hamfisted approach.

The solution I would suggest instead is this:

- Make STARTUP and POSTWORLD plugins only load during startup, at the points they are currently allowed at, and never any other time.
- Add a new ANYTIME load order which will allow plugins to load at any point during server runtime. Most of my own plugins would use this, since they don't care about server state.

There are also ongoing discussions about removing POSTWORLD in favour of some kind of `StartupDoneEvent`, but that's a topic for another RFC.

**Comment by dktapps** [comment]
To directly rebut the points of this RFC:

#### More optimizations become possible

_E.g. Handler lists might no longer need to support online insertion_
_E.g. we can finalize the event lists, permission graph and other possible optimizations duting startup_

None of these optimisations benefit the server in any way, and permissions and event lists still need to be dynamic anyway regardless of whether plugins may load after startup or not.

We agreed internally that "optimisations" is not really a reason for this change.

#### Reduces code complexity
_Can force more things to happen before startup, less cases to consider_

This is technically true, but not really. The server doesn't really care when a plugin is loaded, and plugin dependencies should be addressed with proper load orders anyway.

#### Plugins no longer need to check for players already online when the server starts
As previously stated, this only affects a specific subset of plugins with certain functionality.

#### Plugin mutual dependency can be addressed properly
_E.g. if A uses a feature from B and B uses a feature from A, their load order doesn't matter; instead, they can initialize the components required from each other during enable and perform interaction in a just-before-startup hook._

Internal discussion suggested that this is not a sensible use case anyway.

#### Plugin load order can be correctly tuned. Plugins can now be confident that they are never enabled while their `loadbefore` plugins have already been enabled, and never have `softdepend` plugins starting up after they have been enabled.

This is a problem non-specific to this RFC, and this RFC doesn't fix it anyway - plugins loading other plugins during startup can currently break these assumptions. Real solution to this is #4464.

#### STARTUP plugins should not be allowed to load after server start anyway

Again, a problem non-specific to the RFC which can be addressed in a more delicate way.
