### ISSUE TITLE
setImmobile doesnt work

### ISSUE THREAD

**Issue by KnifeDev** [pmmp/PocketMine-MP#2831]
setImmobile not work.
Steps to reproduce:
1. Create a event with setImmobile, for example PlayerJoinEvent.
2. Set immobile doesnt work and isImmobile return false, i has no error in console.
3. Event exists and registered.

**Comment by dktapps** [comment]
Without knowing your PocketMine-MP version, OS, PHP, Client version, or plugins and how the issue occurred, the issue cannot begin to be solved.
A pre-formatted template is provided that shows the required information to begin to find, test and solve an issue.
Until the adequate template and information is provided, the issue will be closed; it may be reopened if you update the ticket with the correct template and required information.

[Contribution guidelines](https://github.com/pmmp/PocketMine-MP/blob/master/CONTRIBUTING.md)
