### ISSUE TITLE
Please show the link that where can download binary.

### ISSUE THREAD

**Issue by OtorisanVardo** [pmmp/PocketMine-MP#2836]
Recently, My friend consulted me "Where did you get this binary?".
Why didn't you write on README.md?
PLEASE WRITE IT.

PHP binary download link > https://jenkins.pmmp.io/job/PHP-7.2-Aggregate/

**Comment by fuyutsuki** [comment]
[here](https://pmmp.readthedocs.io/en/rtfd/installation/installing-manually.html)

**Comment by OtorisanVardo** [comment]
Thank you very much :D
