### ISSUE TITLE
Lack of documentation for API methods related to Explosion

### ISSUE THREAD

**Issue by Ifera** [pmmp/PocketMine-MP#2837]
## Description

The current API methods for summoning an Explosion are both confusing and poorly documented. The main examples being `explodeA()` and `explodeB()`. 

## Justification

What those and the other methods do are unclear as they lack proper documentation and naming.

- `explodeA()` calculates the blocks that will be destroyed.
- `explodeB()` destroys the blocks, summons particles, plays sounds and etc.

No sane person without having to reverse engineer the code could tell what those methods do.
So its requested that API methods be renamed and be well documented.

**Comment by lukeeey** [comment]
Have fun breaking 50% of plugins https://github.com/search?q=%24explosion-%3EexplodeA%28%29&type=Code

**Comment by dktapps** [comment]
yeah I'm sure there's a disproportionately large number of plugins that use this specific thing, as compared to all the other API changes...

**Comment by dktapps** [comment]
Fixed by 247875e3d5956c8436624e3ad28b79377f930916.
