### ISSUE TITLE
Crafting inventory is sent while crouching

### ISSUE THREAD

**Issue by Wumpotamus** [pmmp/PocketMine-MP#2844]
### Issue description

- Expected result: Crafting inventory not being sent while crouching, like vanilla.
- Actual result: It opened up a crafting menu that won't craft anything.

### Steps to reproduce the issue
1. Place a crafting table
2. Crouch
3. Tap on crafting table
4. Profit

### OS and versions

* PocketMine-MP: 3.7.0
* PHP: 7.2
* Server OS: Linux
* Game version: PE & Win10

### Plugins

- If you remove all plugins, does the issue still occur?
- If the issue is **not** reproducible without plugins:
  - Have you asked for help on our forums before creating an issue?
  - Can you provide sample, *minimal* reproducing code for the issue? If so, paste it in the bottom section

**Comment by dktapps** [comment]
The crafting menu opening is client side, there's nothing to be done about this. Report it to Mojang if you think it's a bug.
