### ISSUE TITLE
FORTUNE Enchant

### ISSUE THREAD

**Issue by EnesTNTm** [pmmp/PocketMine-MP#2847]
We're stepping on a Fortune spell
pocketmine\item\Enchantment : 	public const FORTUNE = 18;

1 $pickaxe = ItemFactory::get(276,0,1);
2  $fortune = Enchantment::getEnchantment(18);
3  $fortune = new EnchantmentInstance($fortune, 2);
4  $pickaxe->addEnchantment($fortune);
5  $player->getInventory()->addItem($pickaxe);

ssh in ./start.sh
ID 18 in Error

**Comment by dktapps** [comment]
Without knowing your PocketMine-MP version, OS, PHP, Client version, or plugins and how the issue occurred, the issue cannot begin to be solved.
A pre-formatted template is provided that shows the required information to begin to find, test and solve an issue.
Until the adequate template and information is provided, the issue will be closed; it may be reopened if you update the ticket with the correct template and required information.

[Contribution guidelines](https://github.com/pmmp/PocketMine-MP/blob/master/CONTRIBUTING.md)

**Comment by UnknownOre** [comment]
Fortune enchantment isn't implemented (yet)
