### ISSUE TITLE
Change toggleSneak() not working

### ISSUE THREAD

**Issue by zKoz210** [pmmp/PocketMine-MP#2850]
### Issue description

- Expected result: The player must sit down or stand up
- Actual result: Nothing happens

### Steps to reproduce the issue
1. Use the code below
2. Go in game
3. Tap on block

### OS and versions
* PocketMine-MP: https://github.com/pmmp/PocketMine-MP/commit/8e9f787d3310c589df5362974e90e168244c2625
* Game version: PE/Win10

### Crashdump, backtrace or other files
```
	public function onPlayerInteractEvent(PlayerInteractEvent $event)
	{
		$player = $event->getPlayer();
		$player->toggleSneak(!$player->isSneaking());
	}
```

**Comment by Frago9876543210** [comment]
Maybe it's client side?

**Comment by dktapps** [comment]
this method is not supposed to be used by plugins except very specialised circumstances. you probably want setSneaking() instead.

this method is expected to only be used by the network layer and plugins like specter which want to create fake players (i.e. any player controller), not by general plugins.

**Comment by zKoz210** [comment]
Okay, setSneaking() doesn't work either.

**Comment by dktapps** [comment]
try joining with two devices and see if one device can see the other device sneak. If it can, then that's a client sided bug, not a PM bug.

**Comment by dktapps** [comment]
apparently the properties are not up-to-date with 1.10.

**Comment by dktapps** [comment]
I've tested this and it appears the client is automatically unsneaking, so there's nothing to be done about this.
