### ISSUE TITLE
Server Crashed URGENT

### ISSUE THREAD

**Issue by dadodasyra** [pmmp/PocketMine-MP#2864]
Link to crashdump: https://pastebin.com/Ui6iEZRY

### Additional comments (optional)

Sorry your link for crash report is doesnt work
The crashdump (begin crash dump and end crash dump) : https://pastebin.com/Ui6iEZRY
The full crashdump (without begin and end crash dump) : https://pastebin.com/0rmgqZxT

The error in server.log : https://pastebin.com/RH1zUWTC
### 
Thanks for all response ! 

Edit : The server crash during the boot
I already tried a new version of pocketmine-mp

**Comment by dktapps** [comment]
your world is corrupted.

**Comment by dadodasyra** [comment]
Mhh sorry all world is corrupted ???
