### ISSUE TITLE
Disabling critical glitch

### ISSUE THREAD

**Issue by CupidonSauce173** [pmmp/PocketMine-MP#2866]
### Issue description
- Disabling the critials -> no more criticals
- It does remove the criticals but there is a health glitch, it does the opposite, health go up when we hit someone.

### Steps to reproduce the issue
1. Make a plugin with this line :
 $event->setModifier(0.0, EntityDamageByEntityEvent::MODIFIER_CRITICAL);
2. Drop it in /plugins, reboot / start the server and pvp someone, make it so there is walls around you.

### OS and versions
* PocketMine-MP: 3.7.1
* PHP: 7.2
* Server OS: Ubuntu / Centos 7 (tested on both OS) 
### Plugins

- If you remove all plugins, does the issue still occur? Yes
bottom section

### Crashdump, backtrace or other files
There is nothing, no error, no debug, nothing.

**Comment by dktapps** [comment]
I cannot reproduce this with the given code.
