### ISSUE TITLE
3.7.2 won't load custom world

### ISSUE THREAD

**Issue by kdurrance** [pmmp/PocketMine-MP#2872]
### Issue description

3.7.2 now does not load my default world, worked fine in 3.7.1 and earlier. Emergency log entry below.

2019-04-16 [07:46:16] [Server thread/ERROR]: Could not load world "SpawnHub": Unknown generator "largeBiomes"                               
2019-04-16 [07:46:16] [Server thread/EMERGENCY]: No default world has been loaded                                                           

No crashdump, exists gracefully.

### OS and versions

* PocketMine-MP: 3.7.2
* PHP: 7.2
* Server OS: macOS 10.12.6

**Comment by dktapps** [comment]
This works exactly as intended. The error is self explanatory.

**Comment by CupidonSauce173** [comment]
Use NBTExplorer, open your level.dat and change largebiome for normal.

**Comment by kdurrance** [comment]
> Use NBTExplorer, open your level.dat and change largebiome for normal.

Very helpful, thx!

**Comment by 95CivicSi** [comment]
@dktapps A note here about previous discussion on this topic. Many server owners are likely to be using custom generated worlds, where the original generator is not available, and the server owner expects that PocketMine will not be able to continue generating matching terrain in new chunks.

An option in pocketmine.yml under the `worlds` section, where server owners can override this behavior per world, would be preferable to having them try to update their maps with an NBT editor.

**Comment by LegoFan48737** [comment]
@dktapps
I agree with @95CivicSi as most of the worlds i have loaded for Factions are custom terrain made with PC Mods. I get the reasoning behind this, but it needs to be toggleable.

**Comment by CupidonSauce173** [comment]
I do not understand your points @LegoFan48737 and @95CivicSi, using mods / custom world generator, MCPC maps made with EpicWorldGenerator for example, all of these aren't working on pmmp. Means that if you throw your world in ur worlds folder, when you will reach the end of the mcpc pre generated world, it will just start to gen a normal world. As said yesterday, just use NBTExplorer and change the .dat settings for normal, this is what I did or just make a hacky patch if you want it to work.

**Comment by CupidonSauce173** [comment]
It takes around 15 seconds per world to change a a .dat using ssh connection with bitvise.

**Comment by LegoFan48737** [comment]
@CupidonSauce173 For now we will, but that process could get old. BTW, does the generator name need to be `normal` or something else?

**Comment by CupidonSauce173** [comment]
@LegoFan48737 needs to be normal, in fact, only normal is allowed now, I think flat and void aren't too.

**Comment by dktapps** [comment]
The known generators are `normal`, `default` (same as `normal`), `flat`, `hell` and `nether`.

I am aware that this bug fix has caused some disruption for users of custom maps, and I'm investigating a solution involving a superficial runtime generator override. For now you should use an NBT editor to change this. If you want void-like generation, use the `flat` generator with a preset of `2;minecraft:air;1`.

**Comment by Spectaz** [comment]
> This works exactly as intended. The error is self explanatory.

Can u justify how was it intended to be I mean how am I supposed to upload world ?
