### ISSUE TITLE
1.11 IS OUT

### ISSUE THREAD

**Issue by Fenek912** [pmmp/PocketMine-MP#2879]
1.11 IS OUT SO PLEASE UPDATE PMMP TO 1.11 BECAUSE 1.11 IS OUT

**Comment by dktapps** [comment]
1.11 IS OUT GUYS UPDATE PMMP PLS

**Comment by JackMD** [comment]
1.11 EVERYBODY

**Comment by CortexPE** [comment]
# 1.11 IS OUT

**Comment by CortexPE** [comment]
# 1.11 IS OUT

**Comment by CortexPE** [comment]
# 1.11 IS OUT
