### ISSUE TITLE
Lighting source not light

### ISSUE THREAD

**Issue by ibookcc** [pmmp/PocketMine-MP#288]
### Issue description
lighting system not light, when you walk to another far chunk(about 2 chunk).
the lighting about light source will not light like normal block.

### Steps to reproduce the issue
1. join the game
2. place a light source block
3. walk about more than 2 chunk about you.
4. leaving the game
5. join game again
5. walk to the old light source's chunk
6. you will find the light source not light 

### OS and versions
* PocketMine-MP: 1.0.2
* PHP: 7.0.1
* Server OS: centOS
* Game version: PE and Win10

**Comment by dktapps** [comment]
Please provide a valid PocketMine-MP version (git hash or Jenkins build number).

**Comment by ibookcc** [comment]
PocketMine-MP 1.6.2dev-#90 「Unleashed」 @dktapps

**Comment by ibookcc** [comment]
@dktapps But why i can't download last build from jenkins, it's saying that 'Error 522 Ray ID: 326c0a0a188c540e • 2017-01-25 13:23:21 UTC' and jenkins.pmmp.io
Host
Error

**Comment by archie426** [comment]
@ibookcc This is off-topic. And also, as dktapps mentioned, this is not a support forum

**Comment by angusbeefsteak** [comment]
I also have this issue on my server, is there going to be any fix for this bug?

**Comment by dktapps** [comment]
No, going to leave it broken for the fun of it... just like I leave this issue open for an issue I'm not going to fix, just for fun... 🤦‍♂️

**Comment by Haxley** [comment]
This is the same bug that I fixed with Sea Lanterns by changing them to Transparent. Any light-source block that extends Solid (and is not liquid nor ice) will lightFilter 1 instead of whatever the Block's class says to lightFilter to.

**Comment by Haxley** [comment]
This is actually still an issue. My fix didn't work.
