### ISSUE TITLE
Furnace

### ISSUE THREAD

**Issue by DrZocker** [pmmp/PocketMine-MP#2881]
### Issue description

- Expected result: Furnaces should cook items like ores or food.
- Actual result: Furnaces don't cook items like ores or food.

### Steps to reproduce the issue
1. Place a furnace.
2. Put iron_ore (for example) and coal inside the furnace.

### OS and versions
* PocketMine-MP: 3.8.0
* PHP: 7.2 (I think(?) - no matter, because the error comes through PMMP)
* Server OS: Debian 9.0
* Game version: PE/Win10 (both)

### Plugins
- does not have to be specified, because the error also occurs on servers without plugins

### Crashdump, backtrace or other files
- the error does not cause any crashs

**Comment by Wumpotamus** [comment]
Reproduced as well.

**Comment by usser1976** [comment]
Yes, that's the same with us

**Comment by dktapps** [comment]
Guys, if you have nothing better to say than "me too", please don't bother. It just fills the comment thread (and people's notifications) with noise.

**Comment by dktapps** [comment]
There are some problems with the crafting data I generated thanks to unnoticed format changes in the crafting data. I'm unsure if this problem is related to the one we're facing here, but it seems likely.

**Comment by degoad** [comment]
Hello I was woundering if you guys where Goin to add the new items in 1.11 to your server??

**Comment by dktapps** [comment]
To clarify the state of things: The bug has been fixed on the `stable` branch, but the fix has not yet made it to a tagged release. This will happen in the next day or two. Thank you for your patience.
