### ISSUE TITLE
How to run the console without the case

### ISSUE THREAD

**Issue by NotBuilderJustChris** [pmmp/PocketMine-MP#2883]

**Comment by ZizzyZizzy** [comment]
Please close this and read the instructions before wasting the developers time here.

The pre-filled form you erased clearly states that **this is not a support form**. This is for **reporting bugs** with Pocketmine. By posting support requests here, you're wasting the dev's time they could be using to fix bugs that help everyone.

Don't be so selfish. Slow down& read the rules.
