### ISSUE TITLE
Constants: Move to using final classes + private constructors instead of interfaces

### ISSUE THREAD

**Issue by dktapps** [pmmp/PocketMine-MP#2885]
## Description
Interfaces which only contain constants should be converted to final classes with private constructors.

## Justification
Constant interfaces commonly cause confusion amongst plugin developers. An interface is designed to be implemented, but here they are being abused to store constants. This misleads plugin devs into thinking such interfaces are necessary to implement in places where they aren't.

**Comment by lukeeey** [comment]
How about abstract classes

**Comment by dktapps** [comment]
Abstract invites extension, which creates the same confusion problem.
