### ISSUE TITLE
brewing stand won't work

### ISSUE THREAD

**Issue by BSC-GoldN** [pmmp/PocketMine-MP#2893]
After installing manually according to the website, I started/connected to the server with an off-network computer (Win10 Edition).

Crafting tables/furnaces work fine, but right-clicking a brewing stand does not open the brewing UI.

Is this normal for PMMP? If so, is there a plugin available that could re-enable the use of brewing stands?

**Comment by Gianluxx** [comment]
TeaSpoon. Close issue because duplicate/not issue format
