### ISSUE TITLE
setImmobile() on PlayerJoinEvent does not work

### ISSUE THREAD

**Issue by JackMD** [pmmp/PocketMine-MP#2894]
### Issue description

- Expected result: What were you expecting to happen?
setImmobile() to immobilize the player.
- Actual result: What actually happened?
Player is not immobilized.

### Steps to reproduce the issue
1. `setImmobile(true)` the player on PlayerJoinEvent.
2. Join the server and the player can move just fine.

### OS and versions

* PocketMine-MP: 3.8.1
* PHP: 7.2
* Server OS: Windows
* Game version: PE/Win10 

### Plugins

Only one plugin with the following code.

```php
public function onJoin(PlayerJoinEvent $event){
  $event->getPlayer()->setImmobile();
}
```

### Side notes:

For what its worth. Using a delayed task of 0 ticks on join event works fine.

**Comment by dktapps** [comment]
for posterity: this was caused by https://github.com/pmmp/PocketMine-MP/commit/a99e15012caecf565759bc13b9a761e0c4952ff8. The bug does not exist on bleeding edge.
