### ISSUE TITLE
XBL player can't see non XBL player

### ISSUE THREAD

**Issue by Frago9876543210** [pmmp/PocketMine-MP#2897]
### Issue description
XBL player screen:
![i1](https://media.discordapp.net/attachments/373199722573201410/573050514099666944/unknown.png)
Non XBL player screen:
![i2](https://media.discordapp.net/attachments/373199722573201410/573050537788833792/Screenshot_20190501-103724.png)

### Steps to reproduce the issue
1. `xbox-auth=off`
2. join from phone
3. join from PC (with XBL)
Perhaps somehow depends on the skin. You also can quit server from PC and change skin to another.

### OS and versions
* PocketMine-MP: 67e75d6c0ac8dc26c13dc0bbf8868dd9f1ae882d
* PHP: 7.2.16
* Server OS: Ubuntu 18.04

**Comment by Frago9876543210** [comment]
BTW, after what time the problem is solves

**Comment by dktapps** [comment]
Does this bug also appear on stable builds?

**Comment by dktapps** [comment]
I'm experiencing the reverse issue, so this is likely nothing to do with XBL itself.

**Comment by Frago9876543210** [comment]
I reproduced direct and reverse issue
