### ISSUE TITLE
StopCommand don't call PlayerQuitEvent

### ISSUE THREAD

**Issue by aoakeake** [pmmp/PocketMine-MP#2903]
### Issue description

- Expected result: What were you expecting to happen?
    StopCommand call PlayerQuitEvent
- Actual result: What actually happened?
   StopCommand don't call PlayerQuitEvent. Code in my plugin on PlayerQuitEvent don't work.

### Steps to reproduce the issue
1. join server
2. stop server
3. plugin don't work

### OS and versions
* PocketMine-MP: PocketMine-MP 3.8.2
* PHP: 7
* Server OS: Linux
* Game version: PE and Win10

**Comment by SOF3** [comment]
Plugins are disabled before players are kicked for server stop. This may change with #2826, but this is the current expected behaviour - plugins may be disabled even if server doesn't stop, so plugins should clean up all player sessions when they disable without assuming player quits.
