### ISSUE TITLE
Async plugin loading

### ISSUE THREAD

**Issue by SOF3** [pmmp/PocketMine-MP#2905]
Add an `onEnableAsync` method that accepts a callback to invoke when the plugin completes loading, or an error callback.
This works better with `PluginException`, and makes #2826 possible.
Alternatively, if an asynchronous programming framework like await-generator is adopted, the method signature could be something like `onEnableAsync() : Generator`.

**Comment by dktapps** [comment]
I don't even ... what is the use case for this?

**Comment by SOF3** [comment]
Maybe it could be more useful if it allows multiple plugins to start up simultaneously.

**Comment by lukeeey** [comment]
What if one plugin depends on another plugin? or if it doesnt depend on a plugin but is intended to be loaded after a certain plugin for some reason?

**Comment by SOF3** [comment]
@lukeeey plugin loading order is undefined unless explicitly specified, then it can be easily controlled using a dependency graph polling.

**Comment by SOF3** [comment]
This issue is a bit different from what I originally expected, because it would require extra mechanism to trigger the callback from the main thread. I am closing this as what I originally plotted did not make sense. (but this does not mean async plugin loading is an invalid concept)
