### ISSUE TITLE
World: add API to get current time of day

### ISSUE THREAD

**Issue by dktapps** [pmmp/PocketMine-MP#2908]
## Description
This proposes adding some sugar like `getTimeOfDay()` to `World` (sorry, `Level`).

## Justification
Currently it's necessary to do `getTime() % Level::TIME_FULL` whenever you want the time of day and not the global time. This is easy to screw up and less easy to refactor when used frequently.

**Comment by lukeeey** [comment]
Can this be added by literally doing
```php
public function getTimeOfDay() {
    return $this->getTime() % self::TIME_FULL;
}
```
Or does it require more work?

**Comment by dktapps** [comment]
more or less, I just haven't gotten around to doing it yet. If you want to do it yourself, target the next-minor branch.
