### ISSUE TITLE
Crashdumps gets stored in wrong path

### ISSUE THREAD

**Issue by sero583** [pmmp/PocketMine-MP#291]
### Issue description
Crashdumps gets directly stored into /server/ insteadof creating a "crashdumps" folder (/server/crashdumps/)

### Steps to reproduce the issue
Let pmmp crash.

### OS and versions
* PocketMine-MP: [Server thread/INFO]: This server is running PocketMine-MP 1.6.2dev 「Unleashed」 implementing API version 3.0.0-ALPHA2 for Minecraft: PE v1.0.0.16 (protocol version 100)
* PHP: 7.0
* Server OS: Ubuntu 16.04
* Game version: PE

**Comment by dktapps** [comment]
1. cannot reproduce
2. this is not a bug, it has always been so
3. I would expect that if you were using an up to date build, https://github.com/pmmp/PocketMine-MP/commit/8bf8e2e22f633770f93463e834554e6412a4db73 would have your crashdumps in the expected place.
