### ISSUE TITLE
Liquid updates do not resume after chunk reloading

### ISSUE THREAD

**Issue by Govdim** [pmmp/PocketMine-MP#2912]
- Expected result: Constant updating of liquids
- Actual result: Often liquids stop updating(Especially lava)

More about the problem:

Quite often, water and lava stop flowing. Especially often this happens on SkyBlock when the server restarts, but this is not so brittle. The worst thing is when players mine a cobblestone in the generator and the lava suddenly stops flowing. Removing and re-spilling the lava does not solve the problem, you need to carry the generator.
Please fix the bug.

* PocketMine-MP: 3.8.1
* PHP: 7.2
* Server OS: Linux/Ubuntu
* Game version: PE/Win10

**Comment by dktapps** [comment]
relates to #2099

**Comment by Govdim** [comment]
And how to make after saving lava and water continue to be updated? There is no such problem in vanilla

**Comment by dktapps** [comment]
I'm aware. Read the referenced issue.

**Comment by dktapps** [comment]
Closing this in favour of #2099, which is the core issue.
