### ISSUE TITLE
Server crashed

### ISSUE THREAD

**Issue by AlicanCopur** [pmmp/PocketMine-MP#2916]
PocketMine-MP Crash Dump Fri May 10 17:39:46 EAT 2019

Error: Argument 2 passed to pocketmine\nbt\tag\DoubleTag::__construct() must be of the type float, boolean given, called in phar:///root/pm/PocketMine-MP.phar/src/pocketmine/entity/Entity.php on line 936
File: vendor/pocketmine/nbt/src/tag/DoubleTag
Line: 40
Type: TypeError

**Comment by dktapps** [comment]
Without knowing your PocketMine-MP version, OS, PHP, Client version, or plugins and how the issue occurred, the issue cannot begin to be solved.
A pre-formatted template is provided that shows the required information to begin to find, test and solve an issue.
Until the adequate template and information is provided, the issue will be closed; it may be reopened if you update the ticket with the correct template and required information.

[Contribution guidelines](https://github.com/pmmp/PocketMine-MP/blob/master/CONTRIBUTING.md)
