### ISSUE TITLE
Bad/annoying things happen when the server is lagging heavily due to client/server ticks out of sync

### ISSUE THREAD

**Issue by dktapps** [pmmp/PocketMine-MP#292]
### Issue description
We've all seen it happen where you fly a distance when the server is lagging a lot, and then boom you're dragged back to point A. It's really irritating.

This is because when the server is under heavy load, ticks may _not_ accurately represent 50 milliseconds, while client-side they still do. Let's say you move from 0,60,0 to 50,60,50 while the server is frozen. Because of the overload, those position changes will not be processed until the current heavy-load issue is out of the way. But the server still thinks that took _1 tick_. Result: the server thinks you moved ~70 blocks in a single tick - nope, get your ass back here.

The long and short of it is that server main thread times and ticks cannot be trusted to provide an accurate representation of time difference, and this causes issues when handling clients who aren't lagging at all.

### Steps to reproduce the issue

1. lag your server
2. fly a long distance
3. get yanked back

### OS and versions

* PocketMine-MP: https://github.com/pmmp/PocketMine-MP/commit/740a8ad436272327fded022d6558713ad0566a75
* PHP: 7.0.14
* Server OS: Windows 10
* Game version: not relevant

**Comment by Muqsit** [comment]
"nope, get your ass back here" 😁

**Comment by dktapps** [comment]
Contrary to this issue's original thoughts, this is more often the result of network lag as opposed to the server lagging behind. That's an issue that can't be completely fixed, only worked around (see "blink" hacks on PC servers).
