### ISSUE TITLE
Server crashed

### ISSUE THREAD

**Issue by LamKietCrack** [pmmp/PocketMine-MP#2924]
TypeError: "Argument 1 passed to pocketmine\item\enchantment\EnchantmentInstance::__construct() must be an instance of pocketmine\item\enchantment\Enchantment, null given, called in
(EXCEPTION) in "src/pocketmine/item/enchantment/EnchantmentInstance" at line 41

I enter id 18 Fortune enchant and get an error code

code plugins
				$id = 18;
				$lv = $this->getLevel($p)/3;
				$i->addEnchantment(new EnchantmentInstance(Enchantment::getEnchantment($id), $lv));

hope admin can help me

**Comment by Gianluxx** [comment]
$i->addEnchantment(new EnchantmentInstance(Enchantment::getEnchantment(Enchantment::FORTUNE), $lv));
