### ISSUE TITLE
Rcon not working

### ISSUE THREAD

**Issue by keke1229488344** [pmmp/PocketMine-MP#2928]
Hello there!
When I recently started the MC server with the 1.11 version of pocketmine, I found that RCON could not be used.
Specifically, it can be detected that the RCON port is running, but after sending the command, there is no return and the connection is automatically disconnected.
In order to eliminate the problem, I found the old version of the pocketmine-mp (PocketMine-MP_Installer_1.4.1_x86) software, and run the test, the test results are not in the previous 0.10.5 version of the problem, rcon is working properly.So I think it has some problem in Rcon(1.11 version)
Please solve it, thank you!

**Comment by jasonwynn10** [comment]
https://github.com/pmmp/PocketMine-MP/issues/2686

**Comment by dktapps** [comment]
This is more likely to do with defects in your client. Older versions implemented the protocol incorrectly, and some clients are known to have implemented the protocol incorrectly based on these defects in PM. Those flaws have now been fixed. See #2784 .
