### ISSUE TITLE
Cant set CompoundTag on a BlockItem

### ISSUE THREAD

**Issue by sero583** [pmmp/PocketMine-MP#293]
### Issue description

I try to set on a Diamond ItemBlock a Compound Tag, but it doesnt work; because it says that the function on the Diamond class doesnt exists
### Steps to reproduce the issue

Set per a plugin a CompoundTag on a BlockItem

### OS and versions

* PocketMine-MP: Current commit of mcpe-1.0 branch, can't say version output due to language errors which happens on me, probably because the folder "lang" or whatever is missing.
* PHP: 7.0
* Server OS: Ubuntu 16.04
* Game version: PE

**Comment by dktapps** [comment]
Therefore, your code is incorrect. Please read the source code and do not misuse our issue tracker. And for God's sake stop using "Download as Zip".

**Comment by sero583** [comment]
@dtkapps I didn't used Download as Zip I have a git-client which bugs on cloning and I'm lazy to update it lol, I will look in the code, but in every fils from the Diamond class eithet the classes its implements or extends, it doesn't contains a setCompoundTag($tag); function.

**Comment by dktapps** [comment]
That's because blocks are blocks, not items. Blocks in item form are ItemBlocks, which _extend_ Item, so if your code was correct you wouldn't be having any issues.

**Comment by sero583** [comment]
@dktapps Ohh I also figured in meanwhile my Object is a Block object not a Item one, well pretty dumb from me.
