### ISSUE TITLE
LevelDB not supported

### ISSUE THREAD

**Issue by micahlt** [pmmp/PocketMine-MP#2930]
Link to crashdump: /aternos/server/crashdumps/Mon_May_20-07.54.41-CDT_2019.log

### Additional comments (optional)
I uploaded a world exported from Minecraft PE to Aternos in place of my current world.  I’m getting the error: `Specified LevelDB world format version (8) is not supported by PocketMine-MP" (EXCEPTION) in "src/pocketmine/level/format/io/leveldb/LevelDB" at line 132`

How can I fix this?  Did I make a mistake when compiling the world, or is it corrupted?  I’m running PM-MP version 3.8.2 and Minecraft PE version 1.11.

**Comment by dktapps** [comment]
The error is self explanatory. The world format isn't supported by that version of PM.

**Comment by micahlt** [comment]
Wait- so does another PM version support it then?

**Comment by dktapps** [comment]
Yes, but not a production-ready version. The upcoming 4.0 release will support such worlds.

**Comment by iliyian** [comment]
When will 4.0 been released?
