### ISSUE TITLE
Bows don't work on master

### ISSUE THREAD

**Issue by Wumpotamus** [pmmp/PocketMine-MP#2931]
### Issue description
I noticed that bows did not work on master, one of the problems is `isUsingItem` on [Line 1817 Player.php](https://github.com/pmmp/PocketMine-MP/blob/master/src/pocketmine/Player.php#L1817) and the other is when the arrow is being spawned in bow.

- Expected result: Using a bow will shoot the arrow.
- Actual result: The bow did not shoot the arrow

### Steps to reproduce the issue
1. Join server
2. Get bow
3. Shoot bow
4. Notice that bow does not shoot anything

### OS and versions

* PocketMine-MP: 4.0.0dev
* PHP: 7.3
* Server OS: Windows
* Game version: PE/Win10

### Plugins

Plugins make no difference

**Comment by Gianluxx** [comment]
Do you have any area plugin that blocks InteractEvent?

**Comment by dktapps** [comment]
This was caused by https://github.com/pmmp/PocketMine-MP/commit/c21a25efb951d42897da8bf686fa9992162b08d5.
