### ISSUE TITLE
Arrows are added to inventory in creative

### ISSUE THREAD

**Issue by buchwasa** [pmmp/PocketMine-MP#2932]
### Issue description
Using the master branch, picking up the arrow in creative causes the arrow to get added to the inventory.
- Expected result: The arrow getting picked up and not added to the player inventory.
- Actual result: The arrow gets picked up and is added to the player inventory.

### Steps to reproduce the issue
1. Get an arrow entity to spawn
2. Go to pick up the arrow in creative mode
3. Tada! It's added to your inventory!

### OS and versions

* PocketMine-MP: 4.0.0dev
* PHP: 7.3
* Server OS: Windows
* Game version: PE/Win10

**Comment by dktapps** [comment]
I'm not sure what the behaviour should be here when taking `InventoryPickupArrowEvent` into consideration. If the item is simply destroyed without being added to the player inventory, this could cause unexpected behaviour for plugins reacting to the event. The same problem holds for `InventoryPickupItemEvent`.

**Comment by dktapps** [comment]
Fixed by 08f3c18de930d00240867f719c0fd1d2b59cdb45 (courtesy of new and improved `EntityItemPickupEvent`).
