### ISSUE TITLE
Remove $fallbackPrefix from CommandMap->register()

### ISSUE THREAD

**Issue by SOF3** [pmmp/PocketMine-MP#2935]
The fallback prefix should be detected from the Plugin context of a command, not to allow plugins submit random prefixes.

**Comment by dktapps** [comment]
I'm not sure how you want to achieve this without coupling plugin and command systems together.

**Comment by lukeeey** [comment]
But then what if you have an obscure plugin name? I would prefer adding an entry to the /version command that displays the fallback prefix for the specified plugin

**Comment by lukeeey** [comment]
Obscure was probably the wrong word, i mean a plugin name like `ExtremelySimpleGodMod` (thats a real bukkit plugin, and the names a bit long)

so like /extremelysimplegodmod:help vs /esgm:help

**Comment by SOF3** [comment]
As I have previously suggested, let Server and Plugin implement a common Context interface that provides methods like getNane and isEnabled. This idea used to be attractive in the past, but if we have changed like #2825 and #2826, this idea might be less attractive. But otherwise, I've always thought that there needs to exist some kind of interface independent from everything else that's used to identify a subsystem of some component of the server.

**Comment by SOF3** [comment]
@lukeeey this does not solve the problem. What if two plugins have identical prefix? If you are to be worried about typing long plugin names, maybe you should simply have requested the plugins to adopt a different command name.
That being said, it might be a useful feature (or a plugin) to change existing command named. (Maybe the aliases attribute in pocketmine.yml?)

Anyway, if we were to support short names for fallback prefixes, we would be implementing yet another alias system, which would be an overkill. Name collision is something that rarely happens anyway, and needing to type a prefix is already troublesome enough.
Imo fallback prefix isn't intended for ordinary usage. It is intended for people who have the ability to set alias and use it to disambiguate within the config.

**Comment by dktapps** [comment]
This doesn't make any sense to me. I don't see any advantage to it.
