### ISSUE TITLE
Extract a ResourceLoader unit from PluginBase

### ISSUE THREAD

**Issue by dktapps** [pmmp/PocketMine-MP#2942]
## Description
The methods `getResource()` and `getResources()` of `PluginBase` should be extracted to a separate unit / interface.

## Justification
Currently resource handling is hard-baked into the core of PluginBase. This is problematic because resource data accessing requires specialized logic to retrieve information which depends on the plugin loader.

This has been partially addressed with the use of access protocol on plugin loaders, but this limits the methods by which resources can be loaded to things addressable as file paths relative to the plugin's own root file.

It has been discussed that a plugin may not _have_ a "root file" to begin with, since this is actually not necessary for the design of a plugin.

In addition, it is currently not possible to modify the way that, for example, a script plugin accesses its resources (it can't).

We propose extracting a `ResourceLoader` interface, implemented by a `FilesystemResourceLoader` which is used for folder and phar plugins. A `NullResourceLoader` can be implemented for script plugins. This will be injected via the constructor, replacing the path parameter.

**Comment by SOF3** [comment]
Resolved in b5805c2d0a328d0af557318e31dd69bd5bf38230
