### ISSUE TITLE
Plugin dependency is not reliable

### ISSUE THREAD

**Issue by SOF3** [pmmp/PocketMine-MP#2944]
Due to complex problems such as plugin load orders, late plugin enabling, etc., plugin dependencies might sometimes not be satisfied.

In addition, disabling a dependency plugin does not disable the corresponding dependents, leading to instability.

**Comment by dktapps** [comment]
The first listed problems do not have any evidence.

The second problem could be resolved with #2826 .

**Comment by dktapps** [comment]
Closing this in favour of #2825 and #2826 .
