### ISSUE TITLE
Shuffle plugins before loading

### ISSUE THREAD

**Issue by SOF3** [pmmp/PocketMine-MP#2945]
In general, plugin load order is undefined unless constrained by `load`, `depend`, `softDepend`, `loadBefore`.
However, due to OS/filesystem level reasons, plugin load order is usually based on lexicographical order. This causes some bugs to stop being noticed, e.g. a plugin starting with "Z" rarely needs to explicitly declare dependency on other plugins.
This issue proposes the shuffling of plugin loading. By randomizing the order that plugin files are scanned by PocketMine, lexicographical order of plugin files/names would have no effect on loading order, thus revealing these long-undisclosed issues.

**Comment by dktapps** [comment]
there is an unresolved discussion over whether to introduce this change on its own to a stable line. at this point it's not clear if this will have any side effects which would break the expected specification.
