### ISSUE TITLE
Return value of pocketmine\Player::getNetworkSession() is null

### ISSUE THREAD

**Issue by rdstonech** [pmmp/PocketMine-MP#2952]
Link to crashdump: https://pastebin.com/WDmjWRF4

### Additional comments (optional)
It's appeared when low-hp player has attacked other player (which has armor with thorns).

**Comment by dktapps** [comment]
This is caused by a plugin kicking a player during an event.

**Comment by rdstonech** [comment]
@dktapps No, it's not affected by a plugin. All plugins on the server is my, and I don't have kicking on EntityDamageEvent. I write because this bug appears again and again. And it manifests itself in the usual pvp (at the moment when the player hits the other). It happens quite rarely
