### ISSUE TITLE
cancelling EntityDamageEvent Doesn't cancel fall damage 

### ISSUE THREAD

**Issue by UnknownOre** [pmmp/PocketMine-MP#2954]
### Issue description

- entity die when falling even if the damage event is cancelled
### Steps to reproduce the issue
1. make a zombie fall from a really high area

### OS and versions

* PocketMine-MP:This server is running PocketMine-MP 3.8.1 for Minecraft: Bedrock Edition v1.11.0 (protocol version 354)
* PHP:7.2
* Server OS:Windows 10

### Plugins
```
public function onDamage(EntityDamageEvent $event){
    if (!$event instanceof EntityDamageByEntityEvent) return;
    $victim = $event->getEntity();
    if ($victim instanceof Player or !$victim instanceof Living) return;
    $event->setCancelled(true);
}

```

**Comment by UnknownOre** [comment]
``` 
if (!$event instanceof EntityDamageByEntityEvent) return;
```
*facepalm*

**Comment by lukeeey** [comment]
Just to add, Player is an instance of Living anyway so the extra check is not needed.

(**Player** extends **Human** extends **Creature** extends **Living** extends **Entity**)
