### ISSUE TITLE
Ender Pearls break sprint

### ISSUE THREAD

**Issue by Vrysed** [pmmp/PocketMine-MP#2956]
### Issue description

- Expected result: When throwing a pearl while sprinting your sprint should stay even if you have over 100ms
- Actual result: When throwing a pearl while you sprint your sprint stops if you have 100ms or more. (Might be cause ender pearling resets motion on teleport)

### Steps to reproduce the issue
1. Get 100ms on your server
2. Throw a pearl while sprinting

### OS and versions
* PocketMine-MP:
* PHP:
* Server OS:

**Comment by dktapps** [comment]
Cannot reproduce, and you haven't provided any version information.

**Comment by Vrysed** [comment]
I'm using the latest PocketMine phar you need to have 100ms on the server to reproduce this.
You can't reproduce it on a LAN server because your latency is low
