### ISSUE TITLE
Call to a member function getHolder() on null

### ISSUE THREAD

**Issue by SonsaYT04** [pmmp/PocketMine-MP#2957]
### Issue description

- Expected result: What were you expecting to happen? Just open a double chest inv
- Actual result: What actually happened? Sometimes it crashed

### Steps to reproduce the issue
1. Make plugin that adds Double Chest Inv to player

### OS and versions
* PocketMine-MP: 3.8.3

### Plugins
I've already searched in google. No related issue or solution about it.
```
if($this->inventory !== null){
    if($this->inventory->getHolder() !== null){
	$this->player->addWindow($this->inventory);
    }
}
```

## Crashdump
Call to a member function getHolder() on null
Info
File: src/pocketmine/inventory/DoubleChestInventory
Line: 62

**Comment by lukeeey** [comment]
That code literally makes no sense. If inventory is null, then the getHolder() code will not run and cannot produce an error?

**Comment by dktapps** [comment]
This error means you're trying to add a double inventory belonging to a chest that either doesn't exist anymore or has been unloaded.
