### ISSUE TITLE
armor inventory bug (most likely)

### ISSUE THREAD

**Issue by BaconOFBurger** [pmmp/PocketMine-MP#2961]
### Issue description

- Expected result: get the player inventory
- Actual result: randomly giving an error like this:
[07:50:18] [Server thread/CRITICAL]: TypeError: "Return value of pocketmine\entity\Living::getArmorInventory() must be an instance of pocketmine\inventory\ArmorInventory, null returned" (EXCEPTION) in "src/pocketmine/entity/Living" at line 450

### Steps to reproduce the issue
1. use $player->getArmorInventory()
2. and try hard to get it, because I think that is rare and quite random

### OS and versions

* PocketMine-MP: 3.8.4
* PHP: 7.2
* Server OS: WINDOWS 10
* Game version: both

### Plugins

Plugins (6): DevTools v1.13.3,  iProtector v1.0.0-BETA, PurePerms v1.4.2-c2a, Parties v1.0.2,  AdvancedKits v5.2.4, BrokenMC-Loader v1.7rc

 some data:
PocketMine-MP Crash Dump Wed Jun 12 07:50:18 BST 2019

Error: Return value of pocketmine\entity\Living::getArmorInventory() must be an instance of pocketmine\inventory\ArmorInventory, null returned
File: src/pocketmine/entity/Living
Line: 450
Type: TypeError

A PLUGIN WAS INVOLVED IN THIS CRASH (u sure, the code given under come from pocketmine\entity\Living)
BAD PLUGIN: BrokenMC-Loader v1.7rc

Code:
[441] 		}
[442] 
[443] 		return $result;
[444] 	}
[445] 
[446] 	/**
[447] 	 * @return ArmorInventory
[448] 	 */
[449] 	public function getArmorInventory() : ArmorInventory{
[450] 		return $this->armorInventory;
[451] 	}
[452] 
[453] 	public function setOnFire(int $seconds) : void{
[454] 		parent::setOnFire($seconds - (int) min($seconds, $seconds * $this->getHighestArmorEnchantmentLevel(Enchantment::FIRE_PROTECTION) * 0.15));
[455] 	}
[456] 
[457] 	/**
[458] 	 * Called prior to EntityDamageEvent execution to apply modifications to the event's damage, such as reduction due
[459] 	 * to effects or armour.
[460] 	 *

Backtrace:
#0 plugins/BrokenMC-Loader/src/ElixirCore/Modules/GameManager/games/BaseGame(72): pocketmine\entity\Living->getArmorInventory()
#1 plugins/BrokenMC-Loader/src/ElixirCore/Modules/GameManager/games/Duel(69): ElixirCore\Modules\GameManager\games\BaseGame->giveKit(object pocketmine\Player)
#2 plugins/BrokenMC-Loader/src/ElixirCore/Modules/GameManager/games/Duel(102): ElixirCore\Modules\GameManager\games\Duel->start()
#3 plugins/BrokenMC-Loader/src/ElixirCore/Modules/GameManager/GameManager(87): ElixirCore\Modules\GameManager\games\Duel->tick()
#4 src/pocketmine/scheduler/TaskHandler(159): ElixirCore\Modules\GameManager\GameManager->onRun(integer 7541)
#5 src/pocketmine/scheduler/TaskScheduler(199): pocketmine\scheduler\TaskHandler->run(integer 7541)
#6 src/pocketmine/plugin/PluginManager(689): pocketmine\scheduler\TaskScheduler->mainThreadHeartbeat(integer 7541)
#7 src/pocketmine/Server(2559): pocketmine\plugin\PluginManager->tickSchedulers(integer 7541)
#8 src/pocketmine/Server(2335): pocketmine\Server->tick()
#9 src/pocketmine/Server(2195): pocketmine\Server->tickProcessor()
#10 src/pocketmine/Server(1774): pocketmine\Server->start()
#11 src/pocketmine/PocketMine(266): pocketmine\Server->__construct(object BaseClassLoader, object pocketmine\utils\MainLogger, string[76] C:\Users\BaconOFBurger\Desktop\BrokenMC\BrokenMC\BrokenMC-ID(REE-FACTORING)\, string[84] C:\Users\BaconOFBurger\Desktop\BrokenMC\BrokenMC\BrokenMC-ID(REE-FACTORING)\plug)
#12 (1): require(string[131] phar://C:/Users/BaconOFBurger/Desktop/BrokenMC/BrokenMC/BrokenMC-ID(REE-FACTORIN)

PocketMine-MP version: 3.8.4 [Protocol 354]
Git commit: a42f68d3cf368535d205d35d4bf7d1c201fbb3d8
uname -a: Windows NT DESKTOP-EFCOQ2Q 10.0 build 17763 (Windows 10) AMD64
PHP Version: 7.2.13
Zend version: 3.2.0
OS : WINNT, win

Loaded plugins:
DevTools 1.13.3 by PocketMine Team for API(s) 3.4.0
iProtector 1.0.0-BETA by LDX for API(s) 3.0.0, 3.0.1, 3.0.2, 3.0.3, 3.0.4, 3.0.5
PurePerms 1.4.2-c2a by 64FF00 & ProjectInfinity for API(s) 3.0.0
Parties 1.0.2 by Didah for API(s) 3.0.0
AdvancedKits 5.2.4 by luca28pet for API(s) 3.0.0
BrokenMC-Loader 1.7rc by BaconOFBurger for API(s) 3.0.0

**Comment by dktapps** [comment]
It's not random, and it's not a core fault either. You're dealing with a disconnected player.
