### ISSUE TITLE
!spam

### ISSUE THREAD

**Issue by Alfree101** [pmmp/PocketMine-MP#2971]
## `I want this update because i like the Minecraft Bedrock Edition 1.12.0.4 better. And my friends are playing on MC BE 1.12.0.4 and they dont want to change versions.`

**Comment by Wertzui123** [comment]
Is 1.12 official released or an beta?

**Comment by Alfree101** [comment]
Beta

**Comment by Wertzui123** [comment]
Then they won't add it. I think
