### ISSUE TITLE
Proposal: change protected properties in Color class to public

### ISSUE THREAD

**Issue by eternalharvest** [pmmp/PocketMine-MP#2973]
## Description
I'm currently working on BigBrother project to improve ItemFrame implementation with FilledMap.
In PMMP, FilledMap contain the true-color bitmap data (8bit for each RGBA component).
But, MCPC(Java) version only support predefined 8-bit color table for FilledMap item.
So, I need to calculate the color distance between for each color in pre-defined color table and for each pixels in square of 128x128.
And I need to choose nearest color.
This is bit heavy task because we need to call getter method of each color component for each pixel (128x128x4 times).

here is code example
```php
/** @var Color[][] $colors */
$target = [1, 2, 3]; /* rgb color */

for ($y=0; $y<128; ++$y) {
  for ($x=0; $x<128; ++$x) {
    // This costs too much (I want to direct access)
    $r = $colors[$y][$x]->getR();
    $g = $colors[$y][$x]->getG();
    $b = $colors[$y][$x]->getB();

    $distance = ($r-$colors[0])**2 + ($g-$colors[1])**2 + ($b-$colors[2]);
  }
}
```

## Justification
I know that getter method is a good practice.
But...

* It costs too much to access each component of color
* It is not dangerous even if properties are public

## Reference
* https://github.com/pmmp/PocketMine-MP/blob/stable/src/pocketmine/utils/Color.php#L33-L39
* https://github.com/BigBrotherTeam/BigBrother/pull/141

**Comment by lukeeey** [comment]
What the hell are you talking about

**Comment by SOF3** [comment]
Sounds like premature optimization. What if we one day want to switch to HSL-based storage?
In fact, we're considering making Vector3 coordinates getters as well due to issues like mutability. And Vector3 is much more performance sensitive then Color.

Did you profile your code and actually measure the improvement from accessing the properties directly?

**Comment by SOF3** [comment]
> It costs too much to access each component of color

Citation needed. Please give actual numbers.

> It is not dangerous even if properties are public

How is happening mutability when not expected "not dangerous"?

**Comment by dktapps** [comment]
Not happening. We have enough problems with mutable public things already. You'll have to deal with it.
