### ISSUE TITLE
 Protocol Version from source is 0.16.0

### ISSUE THREAD

**Issue by GGinChi-Ibook** [pmmp/PocketMine-MP#298]
### Issue description
Version from source is 0.16.0
why, where i can get version-1.0.0?please tell me.
and official jenkins is fall to in(erro 503).

### Steps to reproduce the issue
1. download the code from source
2. start console.

### OS and versions
* PocketMine-MP: the newest source Before sending
* PHP: No association
* Server OS: No association
* Game version: No association

**Comment by GGinChi-Ibook** [comment]
text from document web:http://pmmp.readthedocs.io/en/rtfd/installation.html
Using .phar
Create a new directory for PocketMine-MP.
Download PocketMine-MP.phar from Jenkins.
Rename the .phar to PocketMine-MP.phar.
Place it in the PocketMine-MP directory you just created.

**Comment by HimbeersaftLP** [comment]
You must clone it from the mcpe-1.0 branch

**Comment by GGinChi-Ibook** [comment]
@HimbeersaftLP how? Do you have a link？

**Comment by GGinChi-Ibook** [comment]
@HimbeersaftLP I looking for a long time, since jenkins fall 503

**Comment by HimbeersaftLP** [comment]
git clone --recursive https://github.com/pmmp/pocketmine-mp.git pocketmine-mp.git --branch mcpe-1.0

Use this to download the source code of the 1.0 branch

**Comment by GGinChi-Ibook** [comment]
@HimbeersaftLP amazing! I never see it before....so stupid

**Comment by GGinChi-Ibook** [comment]
@HimbeersaftLP I using Github 1 years to report bug but not saw it before.....
