### ISSUE TITLE
Some way (event) to set player first spawn position

### ISSUE THREAD

**Issue by Tarik02** [pmmp/PocketMine-MP#2981]
I need a way to set player's first spawn position (and world) before he spawns. In current architecture, this event should happen between PlayerLoginEvent and PlayerPreLoginEvent.

## Justification
This is very useful for servers which has multiple worlds and especially one of the is lobby. If I teleport player after PlayerJoinEvent, he already has terrain loaded and other players see him.

## Alternative methods
- Teleport player inside PlayerJoinEvent. Described above.
- Trying to teleport inside PlayerLoginEvent. Causes crash (crash archive does not work for me).

**Comment by Frago9876543210** [comment]
Should be in `NetworkSession::onTerrainReady()`

**Comment by Tarik02** [comment]
@Frago9876543210, no it shouldn't. If `NetworkSession::onTerrainReady()` is called, then terrain is already loaded.

**Comment by dktapps** [comment]
You should be writing a bug report, not making a feature request. As it happens, this bug is already detailed in #2933 .
