### ISSUE TITLE
custom crafting recepies

### ISSUE THREAD

**Issue by DrZocker** [pmmp/PocketMine-MP#2984]
### Issue description

- Expected result: That I can craft an item with a custom recipe
- Actual result: The item disappears and I get the Ingredients back

### Steps to reproduce the issue
1. register a shapedrecipe
2. try to craft that item
3. try to get the item (output) from the workbench

### OS and versions

* PocketMine-MP: 3.8.4
* PHP: 7.2
* Server OS: Debian 9.0
* Game version: Win10

### Plugins
MultiWorld v1.5.1-beta1, DevTools v1.13.1, Z-CityBuild v1.0.0, Clans v1.0.0, Cloud v1.0.0, Groups v1.0.0, EChestSlots v1.0.1

### Crashdump, backtrace or other files
- the server doesn't crash

### Code
$this->ender = new ShapedRecipe(
		        ["abc","def","ghi"],
		        [
		        "a" => Item::get(41,0,1),
		        "b" => Item::get(57,0,1),
            "c" => Item::get(41,0,1),
            "d" => Item::get(57,0,1),
		        "e" => Item::get(130,0,1),
            "f" => Item::get(57,0,1),
            "g" => Item::get(41,0,1),
		        "h" => Item::get(57,0,1),
            "i" => Item::get(41,0,1)
		        ],
		        [Item::get(130,0,1)->setCustomName("§r§6mobile Endertruhe")->setLore(["§r§l§6mobile Endertruhe"])]);
		    $this->getServer()->getCraftingManager()->registerRecipe($this->ender);
    }

**Comment by dktapps** [comment]
This is a bug tracker, not a plugin development forum.
