### ISSUE TITLE
Passing binary string into TextFormat::tokenize() crashes server

### ISSUE THREAD

**Issue by Muqsit** [pmmp/PocketMine-MP#2986]
Link to crashdump: 
https://pastebin.com/raw/vTBpq35p

### Additional comments (optional)
While trying to log binary strings, server crashes due to
```
TypeError: Return value of pocketmine\utils\TextFormat::tokenize() must be of the type array, bool returned in /home/dev/src/pocketmine/utils/TextFormat.php:77
```
This issue could be triggered by error/exceptions. An undefined binary string index for example:
```php
$array = [];
$value = $array[UUID::fromRandom()->toBinary()];
```
The server crashes due to TypeError in `TextFormat::tokenize()` before the undefined index error could be logged and that doesn't let the server print the source of error.

**Comment by dktapps** [comment]
This is a rat's nest of problems. It's possible to patch this by cleaning the text before emitting the text, but this results in the wrong index being printed (unprintable characters are replaced by `?`). In addition, crashdumps are unprepared to deal with this problem.
