### ISSUE TITLE
PlayerJoinEvent->setJoinMessage() does not work!

### ISSUE THREAD

**Issue by Oneclassik** [pmmp/PocketMine-MP#3001]
### OS and versions

* PocketMine-MP: 3.8.5
* PHP: 7.2
* Server OS: Windows 10 Pro
* Game version: All

### Plugins

Plugins (3): BuilderTools v1.2.0-beta1, DevTools v1.13.4, MyPlugin v1

- If you remove all plugins, does the issue still occur? - Yes

My code:
public function onJoin (\pocketmine\event\player\PlayerJoinEvent $e){
  $e->setJoinMessage("TEST");
}

**Comment by lukeeey** [comment]
Well actually if you test on a clean server without plugins it wont work because you need a plugin to set the join message...

I assume you havent registered the events properly or at all

**Comment by Oneclassik** [comment]
> Well actually if you test on a clean server without plugins it wont work because you need a plugin to set the join message...
> 
> I assume you havent registered the events properly or at all

I use My plugin where:
 public function onJoin (\pocketmine\event\player\PlayerJoinEvent $e){
    $e->setJoinMessage("TEST");
 }
But, this does not work.

**Comment by lukeeey** [comment]
Thats not registering the events.

**Comment by Oneclassik** [comment]
> Thats not registering the events.

I know, My code have registering the events:
` $this->getServer()->getPluginManager()->registerEvents($this, $this);`
