### ISSUE TITLE
Some particles are broken

### ISSUE THREAD

**Issue by Encritary** [pmmp/PocketMine-MP#3002]
### Issue description

- Expected result: Every single particle working correctly.
- Actual result: Some particles don't appear.

They've moved a lot of particle effects from ``LevelEventPacket`` to ``SpawnParticleEffectPacket`` already. We'll get even more broken particles after updating to 1.12. (e.g. redstone and some others).

### Steps to reproduce the issue
1. Spawn portal or entity flame particle.
2. You won't see it.

### OS and versions

* PocketMine-MP: `3.8.6` and `4.0.0`
* PHP: `7.3.6`
* Server OS: `Ubuntu 18.04`
* Game version: `1.11.*`

### Plugins

- If you remove all plugins, does the issue still occur?

Of course, it doesn't. The pure pmmp doesn't use any of broken particles by itself.

- If the issue is **not** reproducible without plugins:
  - Have you asked for help on our forums before creating an issue?
  - Can you provide sample, *minimal* reproducing code for the issue? If so, paste it in the bottom section

```php
$player->getLevel()->addParticle(new PortalParticle($player->add(0, 3, 0)));
```

(and then look up)

### Crashdump, backtrace or other files

No crashes

**Comment by dktapps** [comment]
This has nothing to do with the protocol, it's simply down to client sided bugs. See #2572 for precedent.
