### ISSUE TITLE
Player starves while in creative mode

### ISSUE THREAD

**Issue by T14Raptor** [pmmp/PocketMine-MP#3005]
### Issue description

- Expected result: Players hunger should never change while in creative mode
- Actual result: Players hunger goes down while in creative mode

### Steps to reproduce the issue
1. Get into creative mode
2. Run around until you can't sprint

### OS and versions

Was tested on dev1.ams.pmmp.io

**Comment by matcracker** [comment]
I found how to reproduce the issue, follow these steps:

1. Be in survival mode and be sure to have food level < max;
2. Change gamemode to creative;
3. Quit and join the game; **(Important step)**
4. Fly at max speed and after some seconds you will fly automatically at normal speed.
5. Change again your gamemode to survival and you will see you food bar is decreased.

**Comment by Frago9876543210** [comment]
This is due to the fact that `Player::setGamemode` is not called when a player joined.

**Comment by Frago9876543210** [comment]
https://github.com/pmmp/PocketMine-MP/blob/484f2f43c0437acdf38d87097691be9eef206d40/src/pocketmine/player/Player.php#L356-L360
Notice that it does not disable hunger. This happens only here.
https://github.com/pmmp/PocketMine-MP/blob/484f2f43c0437acdf38d87097691be9eef206d40/src/pocketmine/player/Player.php#L1187-L1215
