### ISSUE TITLE
[Window 10 Edition] Outdated Server Error

### ISSUE THREAD

**Issue by ki918** [pmmp/PocketMine-MP#3008]
### Issue description

- Expected result: What were you expecting to happen?
I want connect Pmmp world
- Actual result: What actually happened?
Win10 show "Outdated server error", but PE connect normally

### Steps to reproduce the issue
1. open server
2. Windows10 Edition is connect server

### OS and versions

* PocketMine-MP: 3.8.6
* PHP: 7.1.9
* Server OS: Mac
* Game version: Win10

### Plugins

- If you remove all plugins, does the issue still occur? yes
- If the issue is **not** reproducible without plugins:
  - Have you asked for help on our forums before creating an issue?
  - Can you provide sample, *minimal* reproducing code for the issue? If so, paste it in the bottom section

**Comment by SOF3** [comment]
PHP 7.1.9? It was never even supported.

**Comment by ki918** [comment]
> PHP 7.1.9? It was never even supported.

I do not know what you mean by the not support.
server is run perfect. becuase 2days ago Win10 and PE all connect server.
but, from yesterday win10 is not connect. PE is still connect.

**Comment by SOF3** [comment]
You are not running PHP 7.1. If you did, your server can't even start.
On the other hand, if you don't explain what changed that makes your server no longer working, this is not a reproducible bug. This is most likely your own issue.
