### ISSUE TITLE
Server crashed

### ISSUE THREAD

**Issue by belohnung** [pmmp/PocketMine-MP#3013]
Link to crashdump: https://pastebin.com/Hp6cFbZ8

**Comment by dktapps** [comment]
Looks like an incorrectly built phar. You should use an official one from the releases.

**Comment by belohnung** [comment]
i did

**Comment by dktapps** [comment]
This bug, if it was caused by the core, would happen on every run. This leads me to believe you have a plugin which is tampering with something it shouldn't be (redstone plugin perhaps?). I suggest you remove your plugins and re-add them one by one until you find the culprit.

**Comment by belohnung** [comment]
Oh i am so sorry it was a plugin :(
