### ISSUE TITLE
Server crashed

### ISSUE THREAD

**Issue by Anders233** [pmmp/PocketMine-MP#3014]
Link to crashdump: 
### Additional comments (optional) 

Error: zlib_decode(): data error
File: vendor/pocketmine/nbt/src/NBTStream
Line: 117
Type: ErrorException Code:
[108] /**
[109] * Decodes NBT from the given compressed binary string and returns it. Anything decodable by zlib_decode() can be
[110] * processed.
[111] *
[112] * @param string $buffer
[113] *
[114] * @return NamedTag|NamedTag[]
[115] */
[116] public function readCompressed(string $buffer){
[117] return $this->read(zlib_decode($buffer));
[118] }
[119] [120] /**
[121] * @param NamedTag|NamedTag[] $data
[122] *
[123] * @return bool|string
[124] */
[125] public function write($data){
[126] $this->offset = 0;
[127] $this->buffer = ""; Backtrace:
#0 (): pocketmine\utils\Utils::errorExceptionHandler(integer 2, string[25] zlib_decode(): data error, string[67] C:\home\Servers\vendor\pocketmine\nbt\src\NBTStream.php, integer 117, array[1])
#1 vendor/pocketmine/nbt/src/NBTStream(117): zlib_decode(string[0] )
#2 src/pocketmine/level/format/io/BaseLevelProvider(57): pocketmine\nbt\NBTStream->readCompressed(string[0] )
#3 src/pocketmine/level/format/io/BaseLevelProvider(51): pocketmine\level\format\io\BaseLevelProvider->loadLevelData()
#4 src/pocketmine/Server(1108): pocketmine\level\format\io\BaseLevelProvider->__construct(string[42] C:\home\Servers\worlds/....../)
#5 src/pocketmine/Server(1760): pocketmine\Server->loadLevel(string[6] ......)
#6 src/pocketmine/PocketMine(274): pocketmine\Server->__construct(object BaseClassLoader, object pocketmine\utils\MainLogger, string[28] C:\home\Servers\, string[36] C:\home\Servers\plugins\) PocketMine-MP version: 3.9.0 [Protocol 361]
Git commit: 0000000000000000000000000000000000000000
uname -a: Windows NT 172_30_0_5 10.0 build 14393 (Windows Server 2016) AMD64
PHP Version: 7.2.9
Zend version: 3.2.0
OS : WINNT, win

**Comment by Anders233** [comment]
The error occurred after my disk space was full
I want to know how to solve

**Comment by SOF3** [comment]
Your file is now corrupted, possibly due to write errors after disk space full.
It is a bit troublesome to recover the data, so automatic data recovery is not going to be implemented in the core. If you need help with your particular file, this is not the place.
