### ISSUE TITLE
Chunk tracking system needs a complete re-write

### ISSUE THREAD

**Issue by madecode15** [pmmp/PocketMine-MP#302]
### Issue description
I haven't used PocketMine much since late 2014, so when I came back to it I got shocked a the amount of RAM it uses.

My PocketMine 1.4 server would never exceed 200mb.

In a memory leak, memory.. gets leaked. PocketMine is different.

With some players on my server (about 100), I noticed 750mb of RAM was being used, and with SteadFast, 1.4 based, the RAM being used was around 130MB.

I figured to let the server continue until it reaches my memory limit to get a back trace of what was causing the memory leak... And, it did not crash. The memory stops exceeding at 750MB and everything continues.

I doubt this is a memory leak, I think it is more of chunk loading taking too much memory with 1.5s ChunkLoader system.

For example:
https://github.com/pmmp/PocketMine-MP/blob/478a62e17bf5ff3876d692dc54d6a1ccd80659ea/src/pocketmine/level/Level.php#L569

Uses more memory then:
https://github.com/pmmp/PocketMine-MP/blob/754e0dbb4935f83ca4115efac15e23e639631d46/src/pocketmine/level/Level.php#L406

Anyways, chunk tracking needs a complete re-write and is a total mess.

**Here is a link to the original PM issue for some legacy: https://github.com/PocketMine/PocketMine-MP/issues/3153**

### Steps to reproduce the issue
1. Start server.
2. Get 50-100 players joined, let them load chunks, etc

* PocketMine-MP: https://github.com/pmmp/PocketMine-MP/commit/0535acf211f9f306a610307f71b29349b5e156d2
* PHP: 7.0.3
* Server OS: Linux
* Game version: PE

**Comment by madcode15** [comment]
Added a update because my root cause seems incorrect (my fault). The issue is still persistent, however. PM is no stranger to memory leaks, I'm really looking forward to the 1.0.0 branch because of how much cleaner @dktapps re-wrote and re-fractured level provider code which will make working off level related leaks easier.

**Comment by robske110** [comment]
Wait, doChunkGarbageCollection is not called on schedule currently. The PR adds that.

**Comment by madcode15** [comment]
@robske110 That clears up the confusion. I look forward to testing your PR.

**Comment by dktapps** [comment]
I've played around with various configuration options and haven't been able to reproduce this leak. Can you provide any more detail on the environment and configuration you are using?

**Comment by madcode15** [comment]
@dktapps I'll try to list more steps and upload my config when I get enough time to test again.

**Comment by madcode15** [comment]
@dktapps Updated issue, the entire chunk tracking system is complete crap on PocketMine.

**Comment by dktapps** [comment]
oic, is this related to #304 then?

**Comment by madcode15** [comment]
@dktapps Haven't tested that branch but I think it would be good to add rewrite chunk tracking on there.

https://github.com/pmmp/PocketMine-MP/blob/478a62e17bf5ff3876d692dc54d6a1ccd80659ea/src/pocketmine/level/Level.php#L569

It's sort of ridiculous the entire chunk tracking system uses three arrays, while 1.4 or earlier versions used one, a simple "usedChunks" array.

**Comment by dktapps** [comment]
For reference, that's due to the implementation of the ChunkLoaders [here](https://github.com/pmmp/PocketMine-MP/commit/d6ebff412c4b174fbe2f2d8d5a18b1e9ac304c68). It provides more scalability to not have to restrict chunk loading to players only.
