### ISSUE TITLE
The behavior of the bow is strange

### ISSUE THREAD

**Issue by Rush1533** [pmmp/PocketMine-MP#3021]
### Issue description

- Expected result: Arrows fly straight like MCPE Vanilla
- Actual result: Do not fly straight

### Steps to reproduce the issue
1. Shoot a bow

### OS and versions

* PocketMine-MP: 3.9.0
* PHP: 7.2
* Server OS: PocketMine-MP
* Game version: PE/Win10

**Comment by dktapps** [comment]
This issue is too vague to be worth investigating. You write like it should be obvious there is a problem, but if there is, nobody has noticed it nor reported it, including myself.
