### ISSUE TITLE
Resource pack Bug

### ISSUE THREAD

**Issue by SuperAdam47** [pmmp/PocketMine-MP#3023]
### Issue description

- Resource pack do not downloading
- Kicking server

"maybe 1.12.0 bug"

### Steps to reproduce the issue
1. 
![image](https://user-images.githubusercontent.com/16169771/61175537-1832e700-a5ba-11e9-87dd-124d77f0a4f0.png)

2. 
![image](https://user-images.githubusercontent.com/16169771/61175534-07827100-a5ba-11e9-9713-52f5a6b1a81a.png)

### OS and versions

* PocketMine-MP: 3.9
* PHP: 7.2
* Server OS: Windows
* Game version: Win10

**Comment by ProCompTEAM** [comment]
Oooh, now my players have this problem (I can download our pack, but he can't after update)
![изображение](https://user-images.githubusercontent.com/24737193/61182555-92587f80-a63d-11e9-95d4-c26256fc60ce.png)

**Comment by LeoBdt** [comment]
It also happens when i use LTE (4G). It block my ip.

**Comment by YumikoMC** [comment]
For me too

**Comment by AlicanCopur** [comment]
Pls fix this @dktapps

**Comment by ProCompTEAM** [comment]
@dktapps what about build on https://jenkins.pmmp.io/ ?
