### ISSUE TITLE
Please, some words about this bug (resources / mobs.json)

### ISSUE THREAD

**Issue by ProCompTEAM** [pmmp/PocketMine-MP#3024]
https://forum.mcmodding.ru/threads/mobs-json-%D0%B2-mcbe-1-12-%D0%BF%D0%B5%D1%80%D0%B5%D1%81%D1%82%D0%B0%D0%BB%D0%B8-%D0%BE%D1%82%D0%BE%D0%B1%D1%80%D0%B0%D0%B6%D0%B0%D1%82%D1%8C%D1%81%D1%8F-%D0%BC%D0%BE%D0%B1%D1%8B.24548/

(Picture A - PM 1.11) https://forum.mcmodding.ru/attachments/1%D0%9D%D0%95%D0%A1%D0%94%D0%9E%D0%A5-jpg.5810/
(Picture B - PM 1.12) https://forum.mcmodding.ru/attachments/1%D0%A1%D0%94%D0%9E%D0%A5-jpg.5809/

sorry, i don't know where I can get information about it

**Comment by ProCompTEAM** [comment]
OS and versions

    PocketMine-MP: 3.9
    PHP: 7.2
    Server OS: Windows
    Game version: Win10

**Comment by dktapps** [comment]
This issue does not provide sufficient information to give any idea what you're talking about, and I have zero intention of registering on a Russian forum I've never heard of to find out. If you want a bug fixed, you need to make it as easy as possible for maintainers to identify.

**Comment by ProCompTEAM** [comment]
@dktapps do I need to make a new issue based on your template?

**Comment by dktapps** [comment]
You need to describe, in English, what the problem is, and provide appropriate environment and version information asked for by the template. Don't send me links to some forum I can't read that I have to sign up to in order to see the information.

**Comment by ProCompTEAM** [comment]
@dktapps sorry, now correct
