### ISSUE TITLE
Changed resource pack mobs models are displayed incorrectly

### ISSUE THREAD

**Issue by ProCompTEAM** [pmmp/PocketMine-MP#3025]
### Issue description

- Invalid models
- Cars, models of dino and all kinds of custom models in 1.12 are invalid

### Steps to reproduce the issue
1. Login
2. I saw
![1СДОХ](https://user-images.githubusercontent.com/24737193/61175766-93e26300-a5bd-11e9-8f4e-2111199940c4.jpg)

### OS and versions

* PocketMine-MP: 3.9
* PHP: 7.2
* Server OS: window 10
* Game version: PE/Win10

**Comment by ProCompTEAM** [comment]
(normal view) PM 1.11
![1НЕСДОХ](https://user-images.githubusercontent.com/24737193/61175775-bbd1c680-a5bd-11e9-8b0e-7ca5668a4632.jpg)

**Comment by ProCompTEAM** [comment]
Steadfast and Nukkit also have this problem now

**Comment by dktapps** [comment]
In that case it's most likely the problem is with your resource pack and not PM, particularly since PM does not interact with resource packs and geometry beyond sending them over network.

**Comment by ProCompTEAM** [comment]
@dktapps i tested a lot of resources with changed mobs textures, all textures are invalid

**Comment by ProCompTEAM** [comment]
@dktapps where can I go for help?

**Comment by JackMD** [comment]
https://forums.pmmp.io

**Comment by ProCompTEAM** [comment]
https://forums.pmmp.io/threads/changed-resource-pack-mobs-models-are-displayed-incorrectly.8289/

**Comment by ProCompTEAM** [comment]
@dktapps we tried to set up mob's packs to client except server, textures are correctly

**Comment by ProCompTEAM** [comment]
But my friends server owners with mob's resources packs have the similar problem as https://github.com/pmmp/PocketMine-MP/issues/3023
