### ISSUE TITLE
Player can't see particle

### ISSUE THREAD

**Issue by AkmalFairuz** [pmmp/PocketMine-MP#3026]
### Issue description
Player can't see particle or receive particle.

### Steps to reproduce the issue
1. Use plugins
2. Execute the code, and player can't see particle

### OS and versions
* PocketMine-MP: 3.9.0 (Github Release)
* PHP: 7.2
* Server OS: Ubuntu 16.04
* Game version: PE

### Plugins
`$level->addParticle(new FlameParticle(new Vector3(1, 1, 1)), [$player]);`

### Crashdump, backtrace or other files
Console not send crashdump/backtrace.

**Comment by Encritary** [comment]
they changed a lot of values in ``ParticleIds`` and also they bricked a lot of them. but the same time, they added a lot of new particles to ``SpawnParticleEffectPacket``.

**Comment by AkmalFairuz** [comment]
But why pocketmine not changing this on  Level->addParticle

**Comment by Encritary** [comment]
@AkmalFairuz don't know. I opened the same issue, but for 1.11 and another broken particles. I don't know, if this can be counted as a duplicate.

**Comment by AkmalFairuz** [comment]
I try this code working on 1.11 with not bug , but 1.12 not working.

**Comment by dktapps** [comment]
This is fixed by 3fae57508bf85f35bd3e05639cbfd4ffe21922eb and will be in the 3.9.1 release.
