### ISSUE TITLE
PocketMine closed crash

### ISSUE THREAD

**Issue by derrenrafa** [pmmp/PocketMine-MP#3027]
Here i got this crashdump file if u want to see it

_ _ _ crashdump
PocketMine-MP Crash Dump Sun Jul 14 02:08:25 UTC 2019

Error: Unknown NBT tag type 12
File: vendor/pocketmine/nbt/src/NBT
Line: 87
Type: InvalidArgumentException

Code:
[78] 			case self::TAG_String:
[79] 				return new StringTag();
[80] 			case self::TAG_List:
[81] 				return new ListTag();
[82] 			case self::TAG_Compound:
[83] 				return new CompoundTag();
[84] 			case self::TAG_IntArray:
[85] 				return new IntArrayTag();
[86] 			default:
[87] 				throw new \InvalidArgumentException("Unknown NBT tag type $type");
[88] 		}
[89] 	}
[90] }

Backtrace:
#0 vendor/pocketmine/nbt/src/NBTStream(167): pocketmine\nbt\NBT::createTag(integer 12)
#1 vendor/pocketmine/nbt/src/tag/CompoundTag(445): pocketmine\nbt\NBTStream->readTag(object pocketmine\nbt\ReaderTracker)
#2 vendor/pocketmine/nbt/src/ReaderTracker(47): pocketmine\nbt\tag\CompoundTag->pocketmine\nbt\tag\{closure}()
#3 vendor/pocketmine/nbt/src/tag/CompoundTag(450): pocketmine\nbt\ReaderTracker->protectDepth(object Closure)
#4 vendor/pocketmine/nbt/src/NBTStream(169): pocketmine\nbt\tag\CompoundTag->read(object pocketmine\nbt\BigEndianNBTStream, object pocketmine\nbt\ReaderTracker)
#5 vendor/pocketmine/nbt/src/tag/CompoundTag(445): pocketmine\nbt\NBTStream->readTag(object pocketmine\nbt\ReaderTracker)
#6 vendor/pocketmine/nbt/src/ReaderTracker(47): pocketmine\nbt\tag\CompoundTag->pocketmine\nbt\tag\{closure}()
#7 vendor/pocketmine/nbt/src/tag/CompoundTag(450): pocketmine\nbt\ReaderTracker->protectDepth(object Closure)
#8 vendor/pocketmine/nbt/src/NBTStream(169): pocketmine\nbt\tag\CompoundTag->read(object pocketmine\nbt\BigEndianNBTStream, object pocketmine\nbt\ReaderTracker)
#9 vendor/pocketmine/nbt/src/tag/CompoundTag(445): pocketmine\nbt\NBTStream->readTag(object pocketmine\nbt\ReaderTracker)
#10 vendor/pocketmine/nbt/src/ReaderTracker(47): pocketmine\nbt\tag\CompoundTag->pocketmine\nbt\tag\{closure}()
#11 vendor/pocketmine/nbt/src/tag/CompoundTag(450): pocketmine\nbt\ReaderTracker->protectDepth(object Closure)
#12 vendor/pocketmine/nbt/src/NBTStream(169): pocketmine\nbt\tag\CompoundTag->read(object pocketmine\nbt\BigEndianNBTStream, object pocketmine\nbt\ReaderTracker)
#13 vendor/pocketmine/nbt/src/NBTStream(91): pocketmine\nbt\NBTStream->readTag(object pocketmine\nbt\ReaderTracker)
#14 vendor/pocketmine/nbt/src/NBTStream(120): pocketmine\nbt\NBTStream->read(string[48779] ......Level...Status..full...zPos.......LastUpdate......<x...Biomes.............)
#15 src/pocketmine/level/format/io/region/Anvil(100): pocketmine\nbt\NBTStream->readCompressed(string[9049] x..}.pSW....d?..\.......M.zz..$..t..=.@ .HFv..= ...@..$.1.-.?..$.zk.6.......fvH.)
#16 src/pocketmine/level/format/io/region/McRegion(392): pocketmine\level\format\io\region\Anvil->nbtDeserialize(string[9049] x..}.pSW....d?..\.......M.zz..$..t..=.@ .HFv..= ...@..$.1.-.?..$.zk.6.......fvH.)
#17 src/pocketmine/level/format/io/BaseLevelProvider(170): pocketmine\level\format\io\region\McRegion->readChunk(integer -1, integer 0)
#18 src/pocketmine/level/Level(2822): pocketmine\level\format\io\BaseLevelProvider->loadChunk(integer -1, integer 0)
#19 src/pocketmine/level/Level(2415): pocketmine\level\Level->loadChunk(integer -1, integer 0, boolean )
#20 src/pocketmine/level/Level(2431): pocketmine\level\Level->getChunk(integer -1, integer 0, boolean )
#21 src/pocketmine/level/Level(2966): pocketmine\level\Level->getChunkAtPosition(object pocketmine\math\Vector3, boolean )
#22 src/pocketmine/Server(831): pocketmine\level\Level->getSafeSpawn()
#23 src/pocketmine/Player(2038): pocketmine\Server->getOfflinePlayerData(string[12] derrenrafa17)
#24 src/pocketmine/Player(2024): pocketmine\Player->processLogin()
#25 src/pocketmine/network/mcpe/VerifyLoginTask(166): pocketmine\Player->onVerifyCompleted(object pocketmine\network\mcpe\protocol\LoginPacket, NULL , boolean 1)
#26 src/pocketmine/scheduler/AsyncPool(319): pocketmine\network\mcpe\VerifyLoginTask->onCompletion(object pocketmine\Server)
#27 src/pocketmine/Server(2573): pocketmine\scheduler\AsyncPool->collectTasks()
#28 src/pocketmine/Server(2345): pocketmine\Server->tick()
#29 src/pocketmine/Server(2205): pocketmine\Server->tickProcessor()
#30 src/pocketmine/Server(1784): pocketmine\Server->start()
#31 src/pocketmine/PocketMine(274): pocketmine\Server->__construct(object BaseClassLoader, object pocketmine\utils\MainLogger, string[34] /storage/emulated/0/PocketMine-MP/, string[42] /storage/emulated/0/PocketMine-MP/plugins/)
#32 (1): require(string[89] phar:///storage/emulated/0/PocketMine-MP/PocketMine-MP.phar/src/pocketmine/Pocke)

PocketMine-MP version: 3.8.8 [Protocol 361]
Git commit: 0000000000000000000000000000000000000000
uname -a: Linux localhost 3.18.31-perf-g0eab32e #1 SMP PREEMPT Sat Dec 9 01:50:23 CST 2017 aarch64
PHP Version: 7.2.6
Zend version: 3.2.0
OS : Linux, android

Loaded plugins:
BuilderTools 1.2.0-beta1 by CzechPMDevs, VixikCZ for API(s) 3.0.0

----------------------REPORT THE DATA BELOW THIS LINE-----------------------

===BEGIN CRASH DUMP===
eNrtW41P48a2/1dG2Upln2InToCE9LH3UmBvVw9K7sJ2pddUq4k9SXxxbNczDmSr/d/v75wZOwYC
pa9V+64EK7H2fJzvOV9jfmnNsmIpzaeVKnScpa1Rr90y8VK1RsHefr876AbdvXYrkdqcFkVWtEa/
tMw6x3TrXbqSSRwdFfNyqVJzehuq3BCIdmuptJZzWvQhvU6zm1R8/+2VMHIuaK8IelgzK5PkbZzQ
onwhi1Gn09EmK7Cto5ZlIo2KOt3OOAuvlTmPU+Wdj++++bSts1JplBWdnGeWmOmkU9PRRdgBSizJ
CZVF8+RSLEsw1BoNBxBAIUM8/th61RVP7ro0hZLLnWB/8HokNksmE6yZTLBgNAqxwqgrOd+JU6Pm
qgD7r4HtVfAEaIiqc5wt86xMI9q6u7v3CAJLgfcGv3llNv2XCs3Dpe8xr4orMHatCsbfewL/ndU7
u1u5A42TSYNI7832Jb+ESabLQn3ZYbT938L2Xncb5jvUAW2RGfB8AvNbVPwfW5yMcfeZOjx4Hpck
6UfF/G08P02jWKY14LZ4vkr2/mKT2P9rTGLwp5vE8D/GJA7+YpMIun+NTQTBn24UQe8/xiqC/rNI
PQj+eHt4pjftdZ+BekebIk7nP+4OB4ODn4TPP2dqpRL8f2mkKbXvU6KA18/jTPtuBbKRD3mEsGrf
//sWv76NM6QdfvPHErwniLQGtQkh6Ni8pxNnnULNkbZ0jtJVnOwE3ecQTnoukOSomoWD7i44ACFf
/PzyI2GP/ub7k4kj5dz//Nn3v/J94/uH/t+F/93bFZ6I5b/TeOB7/t/o4fO1v+/2zFbfORb2n8nC
efieH3b6B717XPCOycRumUzibDKxmyYTZtx7Az5PlFZFjKzus/pT+Br8Gl/fSq3YHsZFtophijvB
oPt8zip5OKUtyvS6zsK8oC2q564lZ7idHCZgpzfsPUOmDwj23iTZM1AfPIl6N9jbjprnfxVFW0yz
LFEyFTbx6z6NrB88iWyuzG/AFTyJ62B//1m4jgxOf0zVxTZXBekvJpMfMJwV/fsE9O4TcKkKFDs7
w19n81LO1GUub1Ibknr9+6DGiVwDVK/bH96DZZEwlIvZjCoLu/ZEGlkdraD3k4CFFCot5EwGA4tk
91Ekvd17SOwMB7YQzugsm8cVqQ+cXqrMTVZcd5Zhrjo/4JTP1rz+SuprhLT9R0BnqV1LDi9RqMm2
hgoLG4oA8MmE4mwWZiRKwjCm4GHa4vsPZ2dio53AEvrAtelwoaIyUUXnSK/TcIzlO/3gQci9i/Ie
Q0S3o/gRk7H6sSQMHrGQ3t6gfw9tTRy8ZkWd9wa8JkBAmLWT//AxmP0HOVplKiYOr93ug8d297pP
7R5bO8gKV2l1HwETDIa7j4DRRhbGbX9wdDfl905v8BiET5/CLIWFl6GpBE9O8TiRZKGUTmxNdEoT
JxoeW8Yp1DinVe6Y9Hd/Er/eGqiX7/aeszxPStiK7lhOe2KHnEGhfi7jog59QwS+39Oa2Ca9162f
vrRb6g9upfy2/gYIsOx/itNVlqwU4cT+NMN8uxVmkSLaBkOMTQz9C6FAoVUyG42ujv7x6ZLlM8La
wUG9ZoL0yJRFKlJ1I+wKyixff4Nlw+5joM5ibQjQMNgOiOY3YHqPganybgbV3w6qWTBYcLuPgXuX
mqOikGsGt7cdXLVmA26/XhipmSwTy9igsd0siuyGd08mj+l8Z7Jd01/R70nLoqpU84VerA7o8YDk
/KX15aWD9dLBeulgvXSwXjpYLx2slw7WSwfrpYP10sF66WC9dLBeOlgvHayXDtZLB+t3drDarblK
VSETahOlkj4Wat3ZDZKmkNjmo6JW3x/6Qxou4yRqjbrtVqw/RWrVGs1kolW7VR251qi/HwBBTB2p
7jN/ALiQ10k8pT1+0PNppHSUncVpeSuSLJTJItNG9P1g6PcDL1fFzJt3lZz2e0q8CsTl+ViM35+e
no+vxKU04kSF4kB0g9FedwTPeXx5JXpdRHwpi3CxvwsU9HnRqDXwe/4+3j4jq2RWLX5Mfsp0RQAG
+EWmUZHFUatuwmkS4rckFqSpOIy6IdQ7w+3WRpwB4fCmysgA47I0i6zQ1O45/qzCxfj8RK1oww/x
bXx9/L+kMZnHNN/3uyAO7yqV00SBXtg5xB+pHNQTCMzpbEY1xmZgCZsG1pCA50uoDXY+tbQZog1Z
w11KKZyTUVxcXn28eH92gqEbNUX8I64WxuQaJgkdL8qpH2bLToPszh1QX0hOsoA4jLIc/l8MGeg9
L828m/izLCJ+08oYHBHtW0F4YMpjlvRhwAvcuEx1zO/kE+D3fRMbDJOzwkISFnsNH/YLgzKxIiW/
Gtdv4jhLZ/FcUI92UkxS5C7BgdcdeChDugej7v5ob0jjy8xEh3coF9Yf0aTF4eVZYQ6Dg6Dfo8Gb
BcTpJbE2h9lsRiMyTVG6hcrLbeyT4SJWtr2rD5FNEiRKBjxXR8KWDoN9xi5v3SZ92OvSyBwiX2aR
OuQ3JIgAW485fJBsFGZF/Z6vcocmimezOCwTsz4MGBr7CyiulvshDXO+4pGxH55l0+l6M6aVihpL
qPd5eELvTi0/l6pYO2RuqICGKkro2c/hrxFio8P/4h/IpzSZp+VKuY2rWN14EQQoIbRDVsPtNLv1
6Dy5JYlM5yWs7VClc3qnc107RH+9TEjbgny+CFnRJdiEXFnfAmITd3QK/YurheJms5WDkIUSZqFE
lsJYzAJ+JyQ9GjFVyEnDpIxUhAfxwM4I1iUqRpHNCMB9mBqpH+IUZgpNIMUUFcS1WGdl4WCJeCag
zngWMwZosoBRJGsC/L26qcF1XDtbi5ss/doImedKFoKkibw1hl9N1kShWcTa8n2zUKko83khIwDw
JymZsAU2mqRCvPq4UESYMBmwpJEACBf9IIMCZ45Ptp1mUtl9g1U8KcPywoGNQyUWcKgJS3BJkK2h
VlobCY4uNKEXpYky2L67UBmJScseMEFtGxVNWkzZUZJkN4JOFYgRzkWLVSzFP8nkaA3bnuemRoIc
KG+9XGCnFM5RCIfICkM6UKLUUDO8LUTNLB6N32El/HekCchmxgNpUxDWQHDKhl5BAuOCTp+ASUDq
RO50LZyuaL07F/V0QxqvPsaQeJZCcTKKkDZoq18ilVwbSJLUVSLXIaDVqSKpQPrIL2RCepnHK6xd
yaRUYschRXh8TdAtRpxIRR7Lg14pHRphmnF/Xy6nEDvMljNQSjoFpcIwVJ8XfIA6+OxUnNKyRZHB
u8E8KEdt04YkEs6v4MC1IQvb0aDTR7JBwKGxZZnCRGmJBX7J9gOeYMZFdhvDhBXEAJb4aKQ1cSRb
R9C7GR0GWkNGj1rRfA3xmYK3RYp8Kdvkvc1iBzxA4aLHYmE2PMfpiEHdPwySra8o05TUGZHvy3JW
go1NPpKSlXsWy3i+gLcopF60m6fbWSZJpCjK3NhRKzASzBK0Ob5YuTA4iAnH0J44uUJ+ArK3U0A2
QjaXQdCwLr9haJsQWlsaIgsiRrG2p/4fSTaF9VB6Iew4DtoyNuQ8lmoup2sDiYtLK+ouCzfWBJu3
X5HWbmKWPFsUvMKNZwFVRqaZwxlyYDwIUJ8yrFmhVIXSGjm0VfLxnGdQVEZ+gKyCEM2ZTI9JG4ku
cQHs7OPNgtow/+85oHztKfopcP8++pGE5UyC8881SQ6cFnAfFIDhWCuCCGtFVdDt7TrC2Al85FPh
6NNf/wEU8rlgkshjiLCkNgWim1C3KizZu2eWZHsiKRrWq9VtiAREbziyjuvi6nQkrr57dynO3p2/
u4LzHp+9O70U49P3Annu/5y+bwssElcXWHUqPn53cXaKkuLi+PTy0r/vAu7Io7e378QxVkWcccQn
R6yJQZTs7JJZGrWzRXGLg5tG7Ft4iQdXqKybZVBIPcEnHDSsifh9zNiskSGfpAib0jKHjCFbIHC9
G0duIxLjuKAYQokEb/AfriZbcMUG1JarkPINK1ki1+rV7q15gHmpXG9YpT4A86pfbyfJcd53nM9l
McXJ8FxbA76fHdB26fJRI3LcLuF2wXcvZVpydtOkBJlfCRt83a5iwn0jrMzQhtfZDLAsv8vNEfTF
hfX51uCRnmRlEtW0xAgiN6nY0K8t4JzJB6P7qHotr8D2lp3FgyDJpmMh1LzNimxZBVu7263wmqbZ
1DBx4zT5wDbEFpO6Yx2XVUZKKiuAiczQGXJULnObvtkcUbgJjyYqfZ3QIreBaWcyKw7whjCPwy63
CBhBG4EPGFYwMq1LRY7BLKC1eZXOktMibBuq2pUibY7gslbfUkNLH5UTlVAhdXp1RfuxzGk0XpZL
xFiE10JUxQYpUtiCy1KxkSudFydKPjEPbQzZfO4oYoQepdklgu5urbGTzE7dt2nKjcjrWfh2cXWE
LCy3sMkZZw5eiGpS1bydgBTOVZA+kvRAnU0wLJScO6bC7rEcbrjDNidPy0+FmRZvsl0SYEJ1hoP7
NKin7HCSul7ryIUIpGaLLLEp5lQaVMmU6jPJmi4ChAsy7NtsaeVmbWiZqjrZtOHtVVNL1RS51WJt
CHhbeEFDgaw8RuyZihgXAthrb/JYrn4phYws51QscaJPmzHoyPLFd8gFYUuHnNyJ4/GHNvaChinO
100cwew5V7Des4bvMfyRGFRp9yYj1yydxlpfHEVwVAuZzDqoVW2ZECnYsEMFpIL6PmRgjYO4CXsN
YM1S5PSWvBqlmDJpW6dJqD/GKeo1sAbvo9iXUSb9YZyOqzx8U3xSmUGbbhBRCWaZp7nn3u8VPufu
QOr4s6pVTRl7pWFNsdBlU8joreU0ou7uQc9ueu2LsduTyGLOG6Srgp2ZMMZZIefEHdQFtnSecDJD
pe0SxJMfkAWp8DiJqVHDtTr1cZU24vzqA1OqwRKxPS2NoN4Aa3mDztYdfuWGlqb0aNeIqaUDEKlp
OR9VtcwbQfddxmVyVLXyfFWxalvMq6qSpW3OUAICZv2WhXa8yFCjknFWJYyqilR2bpE0Umi5qpwo
dV+q9hTNbc67REyHJ1DSVD4GlNrmcJUyc7kFE+J0RefI0Dh9SbMwiXPBeyHHc7mGDMlYltmqqmDJ
/TufyX7Lq+YsSr3xFlX/qdmuuOJ+gzUAe1dqOzW81mm71K7Ut5/LRbaa5z2e3TMSORKKVZwQGuvz
3Hl2WMhpy3ReJ9UpbUvux452tepO+2pri8hWeUfLrCSbnlnn7EycRGk7fhyM6Dhz7Q7F0DNHE2x+
z7GlsZkZT5WtFafKApuqGVkkdxc5HCwqC2Clc9PxTpSy7BOimn2cTCHvk+ouBoFNIQBso7K7nUxZ
0Fcs3HdhQwSx1Wb6v6amz9ZNlbRX8gcZuuEtQgpAjIj7rI1WzLsTRjZNMsoi6UiSPFVBmkZeC9e1
FI474ToPVbTjPXdYBzxP9MQrMUfNojfi2XQ3agn5D0XkDuuNjLmogeNAxm91k2e57ZGzzOwLuX1e
41zEkPBxMkw3IoyInCsd1JGo0kzunNp2zsgFPOo+cYllh228cOoCHZu+QLQRG5m7R98X3xuqT9vd
4XyBzGyWNRSCQ+bZ64N6Jd3pjCwpfr5c5n6cMcVplq6XVCLgfBhq54V6QzrVPW5ebOaZBfZYcj4v
UGzaxlLduaNEij6svb7PH9OHA3xxckF3cO7uwIUC8gk3yuahkj/+JYyaCd8wwGN+o7eMyFNL3lqm
Vc4DoUKfdt7ZEoJeWt1WNNMpHs+aokOGmpKZNLo8bbjHfCHbgu6WOF6ZOmOB553RZT9UCAeUUjyw
s1VcsT0jeadr5O6sGvGmRHaG0MZOrPIVDiBr3s5XOB5o2vLaVLVBCV27aheQCCjf9rm8gTRL/pIQ
cjvMbapan/4GgZtpYqik+XTIc17bateeikaXoWoL8/2R3+wnLNwgOwwqCFyO6RwGtWeRxkecZMWz
GhAydTBim/3kgKoi27q46pJqE9hkEkvtMngkXZI+LnBvlAOARqerUaU0Owe7pW7PSPzIwRvhs83t
n58IKCfnmyjZvIRgNiiRKuLIFdjVLRBXztsCFsdzDtCac0kuzKCfGLS6aNsk3+JlGuyjoHsjCgo2
eG0wjsTbs6OrUe+bQXvv4DZo92/77d43wTeRCjPrYndMofAC33o47FpPbN92917brMf2+5t1rT3h
FFogY9d24syD+0bQWrgW9kOCsqh8cpXMF3Ujnz0O4CBShXwToyuBedUtA2zBpnev3rKrYVS8/g6Q
khMF98cdjRGPcy1/0yHL+E8NhLqF49OuDgqvKV3WnPNDItMYieralsy8jvgFKcjSbRSxZ8ZyyfCR
ixS1r261W+rWqJTsiK+0j5EgNC7L6RA3XmEAqdZJYyQP76zXP4Mc1W9et9v7/up1GtJHVI0BujBK
I1k0h9zf29TvZdFE+S/tLtf3+QL/cnzWJFi7e/eh/Ysb+OPG7Mw0vwSYL5tvC4Qm3ktAKVuL6BJ6
M7+c2quv5tAa/PLXBO5J7Pn0YQP12IVHnyHsdXe7Azx+9Y7aQcOZkr3dWW+4O5jJwV5w0O0GU9U/
6IYHQ6m6MpQz1R8OxFcV7PiOpFPTFMN4wULrAWOP7zt1fNtc7npW7lOHgL7iaLfeq5lrMDSVtlhm
TUloDm+6MRLPp3Eqi7XDR7I12bVKkZo0xbuWfNNKS+i7i89xzgIN9kDhly//BmR6lsE=
===END CRASH DUMP===

**Comment by AkmalFairuz** [comment]
It caused by corrupted world not pmmp.

**Comment by derrenrafa** [comment]
Thanks
