### ISSUE TITLE
Ability to enable/disable chemistry behavior pack

### ISSUE THREAD

**Issue by Frago9876543210** [pmmp/PocketMine-MP#3029]
### Issue description
Relying on this gist server should have ability to disable/enable chemistry behavior pack
https://gist.github.com/dktapps/26d138197db44af82cbe18ff29281815

- Expected result: See title
- Actual result: ![im](https://media.discordapp.net/attachments/373199722573201410/599984590060257310/unknown.png)

### Steps to reproduce the issue
- Open creative inventory

### OS and versions
* PocketMine-MP: f637f14e4af8d649bfb712ede06149a21a7f7326
* PHP: 7.3.7
* Server OS: Ubuntu 18.04 LTS

**Comment by dktapps** [comment]
Chemistry textures are enabled by default as of 774e6fe8a3cc509c987aaa394a3959aa19347e1d. Since we unconditionally support chemistry blocks (we can't delete them if they were already used), it makes more sense to have this always active.
