### ISSUE TITLE
Player sometimes can't move when walking on stairs. If allow-movement-cheats: false

### ISSUE THREAD

**Issue by AkmalFairuz** [pmmp/PocketMine-MP#3033]
### Issue description
When player move walking on stairs sometimes player can't move. 

## Steps to reproduce the issue
1. Edit `pocketmine.yml`, find `allow-movement-cheats` and change to `allow-movement-cheats: false`
2. Change gamemode to survival or adventure
3. Try walking on stairs

### OS and versions
* PocketMine-MP: 3.9.1
* PHP: 7.2
* Server OS: Ubuntu 16.04
* Game version: PE

### Plugins
Not use plugins

### Crashdump, backtrace or other files
Console not send crashdump/backtrace

**Comment by dktapps** [comment]
We're aware. That's why it's disabled by default. Many man-hours were wasted trying to fix it. It's slated for removal in 4.0.
