### ISSUE TITLE
Spam PlayerInteractEvent::RIGHT_CLICK_BLOCK

### ISSUE THREAD

**Issue by yoraze** [pmmp/PocketMine-MP#3034]
### Issue description

- Expected result: 1 call PlayerInteractEvent.(Or more, but very little)
- Actual result: Begins spam PlayerInteractEvent::RIGHT_CLICK_BLOCK.

### Steps to reproduce the issue
1. Put on the server plugin with Listener. Add a handler for the PlayerInteractEvent event.(And for example, add 1 item to your inventory when processing PlayerInteractEvent.)
2. Join to the server.(WITH PC)
3. Hold the right mouse button, start to move and turn his head.
4. See the result.

### OS and versions
* PocketMine-MP: 3.9.0
* PHP: 7.2.8
* Server OS: Linux
* Game version: Win10 only

### Plugins
Anyone listening to PlayerInteractEvent.

### Crashdump, backtrace or other files
No

### Extra
 - Maybe it should be, I don't know.
 - The information was **NOT collected by ME**, so it may not be accurate or incorrect.
 - As usual I warn you that I used a translator because I don't know English. He can translate something not as it would be desirable.

**Comment by dktapps** [comment]
This stems from a client sided bug and a hack I put in place to eliminate it. the hack is intended to produce minimal effect to building but has some side effects like this.
