### ISSUE TITLE
Remove remaining usages of {} for string offset access

### ISSUE THREAD

**Issue by dktapps** [pmmp/PocketMine-MP#3035]
It's looking likely that {} will be deprecated in PHP 7.4, and since it's used throughout the PM core we have some work to do to avoid a mess when that happens.

https://wiki.php.net/rfc/deprecate_curly_braces_array_access

**Comment by SOF3** [comment]
Also note the presence of a migration script along with the RFC.

**Comment by DenielWorld** [comment]
https://gist.github.com/theodorejb/763b83a43522b0fc1755a537663b1863
A migration script from the curly braces, don't know if it'll help just thought I'll post it here for you.

**Comment by dktapps** [comment]
no idea why github didn't auto-close this ...

**Comment by fuyutsuki** [comment]
FYI: GitHub doesn't close issues until commits with auto-close messages are merged into the master brunch

**Comment by dktapps** [comment]
False, they have to be merged into the default branch, which is currently `stable`.

**Comment by fuyutsuki** [comment]
Umm, [please refer this page](https://help.github.com/en/articles/closing-issues-using-keywords#closing-an-issue-in-the-same-repository)

> If the commit is in a non-default branch, the issue will remain open and the issue will be referenced with a tooltip.

**Comment by dktapps** [comment]
that's exactly what i said ...

**Comment by fuyutsuki** [comment]
Lol my extremely fault
