### ISSUE TITLE
Requested force ID 0 already in use

### ISSUE THREAD

**Issue by Fenek912** [pmmp/PocketMine-MP#3036]
### Issue description

- Expected result: Player can normally join
- Actual result: Player was kicked with text "Internal server error" and there was some logs in console

### Steps to reproduce the issue
1. click the server on servers list
2. quickly cancel joining
3. quickly try to join again

### OS and versions

* PocketMine-MP: 3.9.1
* PHP: 7.3.6
* Server OS: Ubuntu Server 16.04 LTS 64-bit
* Game version: PE/Win10

### Plugins

without plugins

### Crashdump, backtrace or other files
https://pastebin.com/Zt1zgsat

**Comment by AkmalFairuz** [comment]
It caused by client not pmmp

**Comment by Fenek912** [comment]
i think there should be a better info in the console than a bunch of errors

**Comment by dktapps** [comment]
it's not that simple. The reason this error is able to occur in the first place is because of poor network architecture. This problem has been resolved on the 4.0 branch, but it comes with significant API changes and won't land in production for several months at least.

**Comment by DenielWorld** [comment]
@Fenek912 the info given in the console is as organized as it is, and if you had common sense you would probably understand it. No offense, just stating out some facts.

**Comment by dktapps** [comment]
there's no need for that thank you ...

**Comment by dktapps** [comment]
This is not likely to be resolved before 4.0 release, but I'll leave this open in case others run into this issue.

**Comment by teracube** [comment]
On my server i have only this issue using TeaSpoon plugin
no error with others plugins

InvalidArgumentException: "Requested force ID 3 already in use" (EXCEPTION) in "src/pocketmine/Player" at line 3893

https://pastebin.com/VVD9ZggU
