### ISSUE TITLE
NetworkBlockAddressEvent

### ISSUE THREAD

**Issue by KCodeYT** [pmmp/PocketMine-MP#3050]
Add "NetworkBlockAddressEvent" so that some addresses cannot be banned.

It could be used to not block a proxy

I had to write my own Raklib interface

**Comment by dktapps** [comment]
This is impractical because IP bans are managed from multiple threads. It's not practical to synchronize everything for something like this.

**Comment by KCodeYT** [comment]
But then how am I supposed to do that a proxy shouldn't be blocked?

**Comment by dktapps** [comment]
That's your problem to solve, not mine.

**Comment by yoraze** [comment]
You can unblock the address if you really need it.
```php
$server->getNetwork()->unblockAddress($address);
```
