### ISSUE TITLE
Cannot eat or use enchanted golden apples

### ISSUE THREAD

**Issue by soupdudez** [pmmp/PocketMine-MP#3053]
### Issue description

- Expected result: As this item is implemented in PM, to be able to eat enchanted golden apples and receive the appropriate effects

- Actual result: You cannot eat them, they do not display as enchanted golden apples in the inventory regardless of gamemode (look exactly like golden apples), and the item name is not correct

### Steps to reproduce the issue
- Go to creative inventory and search for enchanted golden apple or /give player 466
- Try eating the apple

### OS and versions

* PocketMine-MP: PocketMine-MP 3.9.1+dev
* PHP: 7.2
* Server OS: CentOS 7
* Game version: Win10

### Plugins
Issue still occurs without plugins

**Comment by dktapps** [comment]
I cannot reproduce this running 3.9.2.
