### ISSUE TITLE
Custom name not setting

### ISSUE THREAD

**Issue by AppleDevelops** [pmmp/PocketMine-MP#306]
### Issue description

Write a short description about the issue
I was taking a look at one of my older plugins that worked back in 0.15 - 0.16 with custom names, and now when I try to add them, they don't appear with their name until I relog or the server reboots.
### Steps to reproduce the issue

1. Use a plugin that sets a custom name
2. Watch the pain happen

### OS and versions

* PocketMine-MP: https://github.com/pmmp/PocketMine-MP/commit/17102058caf031536680ee5914e4f750f70f67d9
* PHP: 7.0.3
* Server OS: Windows 10
* Game version: PE/Win10

### Crashdump, backtrace or other files

* ...

**Comment by dktapps** [comment]
Are you _certain_ you are up to date? I fixed an issue exactly like this a couple of weeks ago.

**Comment by jasonwynn10** [comment]
I tried something like this using the give command instead of a plugin, the items shows as being names until the server stopped

**Comment by AppleDevelops** [comment]
I'm certain that it's up to date, like @jasonwynn10 says, it doesn't work until server reboot. I know it's working as well with the custom name because I've set up the interact event to work with the custom name only.

**Comment by Muqsit** [comment]
Can you send us the code you're using to set custom name?

**Comment by dktapps** [comment]
Using the below code:
```
		public function onClick(\pocketmine\event\player\PlayerInteractEvent $e){
			$item = $e->getPlayer()->getInventory()->getItemInHand();
			$item->setCustomName("SomeName");
			$e->getPlayer()->getInventory()->setItemInHand($item);
		}
```
I am unable to reproduce this issue. I can only assume a fault in your code. Do note that modifying the item directly will not work, since you'll be modifying a clone. You need to get the item, do stuff to it, and then set that item back into the inventory.
