### ISSUE TITLE
You cannot cancel the garbage from the explosion of TNT

### ISSUE THREAD

**Issue by Saehing** [pmmp/PocketMine-MP#3062]
## Description
In the file "pocketmine\level\Explosion" there is a defect in the function "explodeB" can not cancel the drop from the explosion.

## Justification
I want to cancel the creature's garbage :)

## Alternative methods
```php
$entity->attack($ev);
if($ev->isCancelled()) continue;
$entity->setMotion($motion->multiply($impact));
```

**Comment by lukeeey** [comment]
Override EntityExplodeEvent and call $event->setBlockList([]);

**Comment by Saehing** [comment]
You did not understand me correctly, the creature is discarded when it is blown up and this cannot be canceled.

**Comment by dktapps** [comment]
English translation: He wants to prevent mobs from dropping items when killed by explosion.

This can be done using `EntityDeathEvent` and `Entity->getLastDamageCause()`. Check for any of the `EXPLOSION` cause types.

**Comment by Saehing** [comment]
You did not understand me correctly, the creature is discarded when it is blown up and this cannot be canceled.

**Comment by Saehing** [comment]
I use a translator, immediately izvenyus

**Comment by dktapps** [comment]
whatever you're trying to do, it can be done with `EntityDamageEvent` and/or `EntityDeathEvent`.

**Comment by Saehing** [comment]
How do I cancel "$entity->setMotion($motion->multiply($impact));" in "pocketmine\level\Explosion", the function "explodeB"?

**Comment by SleepSpace9** [comment]
You could cancel EntityMotionEvent, the challenge is doing this only when an explosion tries to move the entity. Maybe you listen also to EntityDamageEvent (is triggered before EntityMotionEvent on explodeB) and use an array containing a timestamp to cancel motions of the entity within a short period of time. Hope you get what I mean, otherwhise just ask again in the pmmp forum.
