### ISSUE TITLE
Protection enchantments doesn't work and do buggy item

### ISSUE THREAD

**Issue by Eren5960** [pmmp/PocketMine-MP#3066]
# Steps
1 - add protection enchant to a armor
2 - open your inventory
3 - click/drop armor

>  Note: player on rejoin, enchant removing

# Information
php: 7.3.7
pmmp git hash: b4c55a8c370c2b00336c98f9fc10e8ffeec22c77 (master)
OS: centos

**Comment by Gianluxx** [comment]
Show the code to enchant
