### ISSUE TITLE
Mob doesn't drop cooked meet

### ISSUE THREAD

**Issue by Barlaf** [pmmp/PocketMine-MP#3069]
### Issue description

- Expected result: Mobs drop cooked meet when death by fire or lava 
- Actual result: Mobs drop meet not cooked

### Steps to reproduce the issue
1. Spawn a mob (sheep, cox, pig, ...)
2. Kill this mob by lava or item fire espect or flint
3. See the drop

### OS and versions

* PocketMine-MP: 3.9.3
* PHP: 7.2
* Server OS: Debian 9
* Game version: PE/Win10 1.12.0

### Plugins

Not caused by plugins

### Crashdump, backtrace or other files
No crashdump for this problem

**Comment by dktapps** [comment]
those mobs aren't even implemented ...
