### ISSUE TITLE
HugeExplodeParticle isn't working

### ISSUE THREAD

**Issue by intagaming** [pmmp/PocketMine-MP#307]
### Issue description

HugeExplodeParticle doesn't show anything. Maybe the client protocol has changed.

### Steps to reproduce the issue

1. Use the code below to initialize a HugeExplodeParticle

### OS and versions

* PocketMine-MP: 1710205
* PHP: 7.0.3
* Server OS: Windows 10
* Game version: Win10 1.0.2

### Crashdump, backtrace or other files

```
/** @var Player $player */
$player->level->addParticle(new HugeExplodeParticle($player));
```

**Comment by dktapps** [comment]
Works fine. Naturally you need to look down to see it, since it will spawn at your feet. This also isn't the huge boom it was before, if you're after a TNT-style explosion particle, use HugeExplodeSeedParticle.

**Comment by intagaming** [comment]
@dktapps Also! Where can i get the Explode of Ender Dragon's dead ?
