### ISSUE TITLE
ResourcePacks client side merging bug

### ISSUE THREAD

**Issue by gioiann** [pmmp/PocketMine-MP#3071]
### Issue description
A client downloading 2 completely different resource packs (different uuid, name, version, etc) at the same time from the server will eventually result in the resourcepacks being merged into 1 on the client side.

- Expected result: The client downloading 2 different resource packs
- Actual result: The client sometimes downloads the resourcepacks in the same folder resulting in the packs being "merged" and files with the same name overwritten so in case you delete one of the resource packs on the server side, client side both packs will still be applied

### Steps to reproduce the issue
1. Create 2 small resource packs with only a manifest, icon and a custom block texture so you can tell if it's applied. For example in the first resouce pack changing the dirt texture and in the 2nd the grass texture.
2. Join a localhost (must be localhost if you need more chances to reproduce) server and download the packs.
3. Check the client resource packs cache at /packcache/resource/ (root needed on android), if there are 2 different folders for each of the rpacks then delete the packs from the in game storage settings and retry to download again, eventually both the packs will be downloaded in the same folder. If you can't check /packcache/resource/ then simply restart the game and open Settings->Storage, you will only find one of the downloaded packs here if they merged, otherwise retry downloading

The resource packs cache folder name client side seems like to be a base64 encoded hash which strictly depends on the time the resource pack is downloaded.

I will soon provide resource packs and probably a video

### OS and versions

* PocketMine-MP: [3.9.3](https://github.com/pmmp/PocketMine-MP/tree/3.9.3) 
* PHP: 7.3.7
* Server OS: Ubuntu 18.04
* Game version: Android/Win10

### Plugins
No plugins loaded

**Comment by dktapps** [comment]
This seems more like it belongs on https://bugs.mojang.com, no?

**Comment by gioiann** [comment]
Yes, definitely since I also tried using the official mojang server and it still happens. But I don't have time to open an issue there. It can be temporarily be "fixed" by delaying the ResourcePackDataInfoPacket sending

**Comment by dktapps** [comment]
well you're opening in the wrong place, this isn't the mojang issue tracker ...
