### ISSUE TITLE
Entity::DATA_TYPE_SLOT

### ISSUE THREAD

**Issue by yoraze** [pmmp/PocketMine-MP#3072]
### Issue description

- Expected result: Entity::DATA_TYPE_SLOT works correctly, the fireworks are working fine.
- Actual result: The explosion of fireworks is not visible.(example)

### Steps to reproduce the issue
Using any plugin, create fireworks. Make it explode.(ActorEventPacket::FIREWORK_PARTICLES)

### OS and versions

* PocketMine-MP: 3.9.4
* PHP: 7.2.8
* Server OS: Linux
* Game version: PE/Win10

### Plugins
For Example TeaSpoon.

### Crashdump, backtrace or other files
No.

### Additional
You can watch Nukkit. There instead of an Item the server sends the NBT to the player.

[Nukkit: Bedrock 1.12](https://github.com/NukkitX/Nukkit/commit/69b440a86c822f571732256593e61f9d3b7fdf72#diff-ba46dab7b32a1a92d589c59ee3975732R128)

**Comment by Encritary** [comment]
I can confirm that fireworks work wih NBT metadata type.
