### ISSUE TITLE
MOTD doesn't follow formatting rules - color codes do not reset formatting

### ISSUE THREAD

**Issue by ZizzyZizzy** [pmmp/PocketMine-MP#3076]
### Expected Behavior
1. When using formatting codes in the MOTD, a color code should reset all other formatting tags.
2. If a reset code is not used a the end of the MOTD and an obfuscated tag was not reset previously, the server version should still be visible after the MOTD text.

This is according to the Minecraft wiki and Vanilla behavior.

From the wiki: "If a color code is used after a formatting code, the formatting code will be disabled beyond the color code point."

### Actual Behavior
1. Other non-color formatting codes are maintained after the color code, forcing the need for excess reset codes.
2. If a previous obfuscated formatting code was not reset before the end of the MOTD text, the server version displayed after the MOTD is also obfuscated.

### Steps to Reproduce
In server.properties:
motd=§e§ki|li|l §c§n§o§lPMMP §fServer!  §e§ki|li|l

That should show obfuscated yellow text, then a red,italic,bold "PMMP", white "Server!" then scrambled yellow text again. Instead, the obfuscated, italic and bold attributes carry through to the end of the MOTD without being reset.

The same motd line works perfectly on vanilla.

Affects all versions of PMMP tested.

**Comment by dktapps** [comment]
PM does nothing out of the ordinary with MOTD. I don't see any reason for a difference between PM and MCPE.

You did test this on a MCPE vanilla server, correct?

**Comment by yoraze** [comment]
This is not a bug of pmmp...

And nothing prevents to put at the end of §r...

**Comment by ZizzyZizzy** [comment]
I hadn't thought this all the way through when I posted. The client GUI is responsible for interpreting the MOTD formatting codes, not the server. The Windows 10 Pocketmine/Bedrock client doesn't match the vanilla client behavior. I'll have the wiki owner update the MOTD entry accordingly.
