### ISSUE TITLE
EntityArmorChangeEvent

### ISSUE THREAD

**Issue by UnknownOre** [pmmp/PocketMine-MP#3085]
### Issue description

- Expected result: What were you expecting to happen?
- Actual result: What actually happened?

### Steps to reproduce the issue
https://images-ext-1.discordapp.net/external/1agnf6Y33kveSIr0ZQOC94md9kIwUfPXxeE99A0cm28/https/cdn.discordapp.com/attachments/373199722573201410/609090230770728960/VID_20190808_212534.mp4

### OS and versions

* PocketMine-MP:This server is running PocketMine-MP 3.9.0 for Minecraft: Bedrock Edition v1.12.0 (protocol version 361)
* PHP: 7.3
* Server OS: Windows 10

### Plugins
- UnknownCore
- Specter
- PocketMineDevtools

### Crashdump, backtrace or other files

```
$item = $event->getNewItem();
        if($item->getNamedTag()->hasTag('head')){
            $event->setCancelled();
        }
```

**Comment by dktapps** [comment]
That's expected, given the implementation of the event. It's been scrapped for 4.0.
