### ISSUE TITLE
Player is healing but EntityRegainEvent is cancelled

### ISSUE THREAD

**Issue by Erkam246** [pmmp/PocketMine-MP#3090]
### Issue description

- Expected result: Player Stops to regain health
- Actual result: Player regenerate health but if he get damage health will set to before regenerate health

### Steps to reproduce the issue
1. Cancel Entityregainhealthevent
2. Get Damage
3. Wait

### OS and versions

* PocketMine-MP: 3.9.3
* PHP: 7.2.20
* Server OS: Debian
* Game version: Win10

**Comment by SOF3** [comment]
Without knowing your PocketMine-MP version, OS, PHP, Client version, or plugins and how the issue occurred, the issue cannot begin to be solved.
A pre-formatted template is provided that shows the required information to begin to find, test and solve an issue.
Until the adequate template and information is provided, the issue will be closed; it may be reopened if you update the ticket with the correct template and required information.

[Contribution guidelines](https://github.com/pmmp/PocketMine-MP/blob/master/CONTRIBUTING.md)

**Comment by SOF3** [comment]
This is likely to be an issue in your own plugin rather than in PocketMine. Please consider asking on the help channels as mentioned in the README.
