### ISSUE TITLE
Unregister Help Command

### ISSUE THREAD

**Issue by joaonunes12** [pmmp/PocketMine-MP#3096]
I'm trying to unregister the "help" command, I did the following: 

$this->getServer()->getCommandMap()->getCommand("help")->setLabel("help_disabled"); 
$this->getServer()->getCommandMap()->getCommand("help")->unregister($this->getServer()->getCommandMap());
$this->getServer()->getCommandMap()->register("HelpCustom", new Help($this));
$this->getServer()->getCommandMap()->register("HelpCustom", new Help($this), "?");

I'm trying to do / help on Form api, this code unregister only "./help" and "./?" within the game, I need to unregister "/help" and "/?". How to do this?

**Comment by yoraze** [comment]
@joaonunes12 That isn't possible. The help command is on the player's side.
