### ISSUE TITLE
Left hand item texture goes black

### ISSUE THREAD

**Issue by KenMizz** [pmmp/PocketMine-MP#3098]
### Issue description

- Expected result: What were you expecting to happen?
Left hand item texture be as same as right hand
- Actual result: What actually happened?
Left hand item texture goes black
### Steps to reproduce the issue
1. ... put a item that allow to put on left hand

### OS and versions

* PocketMine-MP: 3.9.3
* PHP: 7.3
* Server OS: Windows 10
* Game version: Win10

### Plugins

PingTag v0.4, MoreCommands v1, TeaSpoon v1.2.0, AllSigns v1.0.11, MultiWorld v1.5.1, MagicWE2 v5.7.2, DevTools v1.13.3, EC-TableUI v1.1.1-pre, SizePlayer v1.1.0, MyPlot v1.6.3, Monk v1.0.0, StarWars v1.0.1, Forgive v1.1.1
- If you remove all plugins, does the issue still occur?
yes

### Crashdump, backtrace or other files

![image](https://user-images.githubusercontent.com/16635884/63025276-6ac63280-bedb-11e9-80dc-243e954263b7.png)

**Comment by yoraze** [comment]
This is not a bug of pmmp...

**Comment by KenMizz** [comment]
@yoraze whats the exact problem, I test on the client and everything works fine :/

**Comment by dktapps** [comment]
Offhand isn't supported.
