### ISSUE TITLE
Skinpacks support

### ISSUE THREAD

**Issue by yoraze** [pmmp/PocketMine-MP#3099]
### Issue description

- Expected result: Skin packs working properly.
- Actual result: The player leaves the server with the message "Error while downloading packs from server. Please try again.".

### Steps to reproduce the issue
1. Place the skinpack in the resourcepacks folder.
2. Start the server, try to join the server.
3. See "Actual result"

### OS and versions

* PocketMine-MP: 3.9.4
* PHP: 7.2.8
* Server OS: Linux
* Game version: PE

### Plugins
Without plugins.

### Crashdump, backtrace or other files
Without crashdumps.

## Additional
[I think it's because of that.](https://github.com/pmmp/PocketMine-MP/blob/stable/src/pocketmine/network/mcpe/protocol/ResourcePackDataInfoPacket.php#L49)

**Comment by Virvolta** [comment]
skinpack !== resourcepacks

**Comment by yoraze** [comment]
> skinpack !== resourcepacks

But on older versions of pmmp they worked well.

**Comment by dktapps** [comment]
Loading a skin pack as a resource pack makes no sense.
