### ISSUE TITLE
Slabs unable to be placed on another slab when block above it

### ISSUE THREAD

**Issue by Sandertv** [pmmp/PocketMine-MP#31]
### Issue description
When you place a slab and place another block on it, you will be unable to place another slab on the slab you just placed.

### Steps to reproduce the issue

1. Place down a slab of any kind
2. Place any block above this slab
3. Place a slab on the first slab (under the block)
4. Watch it disappear

### OS and versions

* PocketMine-MP: 8f3b95164a1aae99a38553fd4b01d7053e7c02d6
* PHP: Does not matter
* OS: Both PE and Windows 10

**Comment by SOF3** [comment]
What is "Version: PocketMine-MP: Any"? Does this issue exist in future versions when a fix comes? Does this issue exist in previous versions when slabs weren't even supported? Please always clarify.

**Comment by Sandertv** [comment]
Sorry, will edit.

**Comment by SOF3** [comment]
"Currently available" isn't clear either... Please either use the build number or the SHA of the commit that your build is created from (or the version number, although might be unclear).

**Comment by Sandertv** [comment]
Okay like this?

**Comment by XShockinFireX** [comment]
Confirmed.

**Comment by SOF3** [comment]
Please use the reaction :+1: if you reproduced the same issue. It is difficult to track the severity of an issue by counting the number of comments.

**Comment by Sandertv** [comment]
Cool, thanks Intyre! :)
