### ISSUE TITLE
Outdated website link

### ISSUE THREAD

**Issue by BaconOFBurger** [pmmp/PocketMine-MP#3106]
As noted in the title, Pocketmine still uses deprecated website links (http://www.pocketmine.net/) for their License instead of new one (https://pmmp.io/).

You can find this outdated link in all pocketmine classes at line 17.

Please also apologize, I did not find the type of problem between them because it's not a bug, it's not an API change request, nor a vulnerability, nor any of these issues templates that you have provided.

It's not a major change request, it does not affect anything, so I understand if this issue get closed.
Thank you!

**Comment by nathfreder** [comment]
```py
import glob

files = glob.glob('**/*.php', recursive=True)

for file in files:
	contents = open(file, 'r').read()
	contents = contents.replace('@link http://www.pocketmine.net/', '@link https://pmmp.io/')
	open(file, 'w').write(contents)
```
