### ISSUE TITLE
Dark Oak and Acacia

### ISSUE THREAD

**Issue by Akuroma** [pmmp/PocketMine-MP#3107]
### Issue description

- Expected result: Able to give Acacia Wood and Dark Oak Wood via /give or via plugin
- Actual result: Got Oak Wood and Spruce Wood

### Steps to reproduce the issue
1. use /give Name 17:4 1 (you should get Oak Wood instead of Acacia)
2. use /give Name 17:5 1 (you should get Spruce Wood instead of Dark Oak)

### OS and versions

* PocketMine-MP: 3.9.4
* PHP: 7.2
* Server OS: Ubuntu
* Game version: PE/Win10 (delete as appropriate)

### Crashdump, backtrace or other files
YouTube-Video: https://youtu.be/2lyd58tqqVc

**Comment by dktapps** [comment]
Have fun with magic numbers. As strange as it seems, this works as intended.
I suggest using my [GiveMapper](https://github.com/dktapps-pm-pl/GiveMapper) plugin for some sanity, and don't use magic IDs.

**Comment by Akuroma** [comment]
Is this also fixing the issue with trying to give these items to players via $inventory->addItem().?

**Comment by dktapps** [comment]
There's nothing to fix. The numbers you listed don't correspond to the items you think they do.

**Comment by Akuroma** [comment]
Thx. Didn't see that there are two classes for wood. Blame on me. ^^
