### ISSUE TITLE
Movement distance assertion failure for Y axis movement

### ISSUE THREAD

**Issue by kabluinc** [pmmp/PocketMine-MP#311]
### Issue description

When I hit a player and they fall into the void I get this error in console

### Steps to reproduce the issue
hit a player into the void

### OS and versions
-->
* PocketMine-MP: Pocketmine-MP 1.6.2 just downloaded
* PHP: 7.0.14
* Server OS: Windows 10
* Game version: MCPE 1.0.0.6

### Crashdump, backtrace or other files
`Warning: assert(): Movement distance is excessive: dx=0, dy=-23.6435, dz=-0.0048999999999921 failed in C:\Desktop\New folder (10)\src\pocketmine\entity\Entity.php on line 1300

Warning: assert(): Movement distance is excessive: dx=0, dy=-26.1262, dz=-0.0014000000000181 failed in C:\Desktop\New folder (10)\src\pocketmine\entity\Entity.php on line 1300
`

**Comment by dktapps** [comment]
You should not have assertions enabled in a production environment.

**Comment by zKoz210** [comment]
Will it be actually fixed?

**Comment by dktapps** [comment]
This issue cannot occur anymore unless the source code has been modified (instead the infamous rubber band pullback will be tripped). That's a separate issue and arguably unfixable, but it's well known regardless.
