### ISSUE TITLE
Player was disconnected before their login could be verified  and Login timeout

### ISSUE THREAD

**Issue by dadodasyra** [pmmp/PocketMine-MP#3116]
### Issue description
- When connecting to the server in normal times it works
- Except that a lot of the players have this error during their 2nd connection since the last reboot:
[21:30:28] [Server thread / ERROR]: PLAYERNAME player was disconnected before their login could be verified

### Steps to reproduce the issue
My theory is:
1. Disconnect in a chunk being loaded
2. Try to reconnect
3. The bug is there

### OS and versions
* Pocketmine: 3.9.4
* PHP: 7.2
* OS: Debian 9
* Game Version: 1.12.0

### Plugins
Plugins (90): ItemRename v1.0.0, PurePerms v1.4.2, LuckyBlock v1, FormAPI v1.3.0, Advan
cedKits v5.2.4, Worlds v2.0.3, WorldLoader v1.0.0, v1 DualPickaxe, itemID_DoDo v1.1.0, Furnace v0.0.1, GrapplingHook v1.
0.3, RepairCommands virvolta_1.0, AutoClearLagg v3.0.0, EcCommand v1.0.0, Broadcaster v1.5, WhatTheServer v0.2.2, Random
 v1.0.0, Spy v1.0.0, AimTP v0.0.1, ItemEffect v0.1, KillCollection v1, SkyEnchant v1.0.1, CustomCraftPlus virvolta_0.1,
AntiVoid v1.0.0, DevTools v1.13.1, SkyBox v2.0.0, ChestFinder v1.5, CombatLogger v0.0.6, FactionsPro v1.3.20, SkySeed v1
, GlobalMute v1.0.0, MapImageEngine v1.1.2, BetterVoting v1.5.0, BuilderTools v1.2.0-beta2, BadWordBlocker v1.2.7, Myste
ryCrate v9.1.1, MultiWorld v1.5.1, CommandDisabler v1.0.0, CaveBlock v1.5.2, KickBasic v0.1, Slapper v1.5.0, iProtector
v4.0.3 # 3.1b, DiamondWarner v1.0.0, EasyHomes v1.0.2, MSpawns v2.2, Dynamite v0.1, NameSpaceRemover v1.0.0, BlazinFly v1.
8.3, EconomyAPI v5.7.2, BlockCMD v1.0.0-beta, MuteUI v2.3, CustomAlerts v2.1, InvSee v1.0.0, ObsiDestroy v1, Craft v2, S
eeDevice v0.0.7, MultiPort v1.0.0, AllAPILoader v1.0.0, BlazinVanish v1.0.3, v1 Core, BanItem v2.3.3, Boss v1, TextRepla
Cer v1.0.0, LiveXYZ v0.7.0, PlayerSelectors v1, ChestRefill v1.1, MCPEToDiscord v1.4, QuestTpUi v0.1, VanillaEnchantment
s v4.0.0, HoodHelmet v1, essentialsTP v1.2.2, WorldBorder v1.0.0-3.0.0, TempBanUI v1, Ah v1, EmeraldWarp v1.0.1, SkySell
 v1.2.0, PureChat v1.4.11, ProtectArmor v1.0.0, NewPlayerAlert v1.0.0, Hammer v0.1, ItemCommands v1.0.0, StaffChat v1.1.
2, TpCmd v1, MineReset v3.3.0, SymphSword v1, ModdedApple v1.5.2, ArmorModded v1, ChunkLoader v0.0.1, SkyShop v1.2.0, Sk
yQuest v1

### DESCRIPTION
Normally it happens when it's a player who cracked minecraft except that it happens to me even. At each reboot the bug is solved for about 15 minutes.

The fact of tested without plugins is useless because no one will want to connect to a server without plugin. The bug occurs when connecting to the server multiple times.
There is no error but just: [21:30:28] [Server thread / ERROR]: Player PLAYER was disconnected before their login could be verified
[21:30:30] [Server thread / INFO]: PLAYER [/ *] disconnected due to Login timeout

According to my unloaded chunk theory I tried a plugin that would load the chunk prelogin but it does not change anything. This bug appeared when I migrated from an offer of a host with a panel to a vps. The 2 machines have the same OS which is Debian 9. This is not a performance problem because as the following timing shows the load of the server is not very high
https://timings.pmmp.io/?id=5563
(Night timings so very few players otherwise 40 of Average Player and never exceed 70% of Server load)

**Comment by dadodasyra** [comment]
So it's not a support request it's a bug with Pocketmine 😑 and your forum doesn't work : 
![image](https://user-images.githubusercontent.com/44753923/64480523-bb266c80-d1c9-11e9-9143-8fd6c00aa5a3.png)

**Comment by lukeeey** [comment]
The point of testing without plugins is to make sure that plugins are not the cause of the issue.

Also you may be posting in a category that is protected,  such as announcements (or something havent used forums in a while).

You can also join the discord for spport

**Comment by dadodasyra** [comment]
So i'm sure it's not the plugin because it's the same on the 2 machine.
For the discord i have already use so i don't have receive response

**Comment by lukeeey** [comment]
I dont care, test it without plugins and i recommend you do not reply to the issue again unless the problem persists without plugins or the issue will be locked.
