### ISSUE TITLE
Blocks does not appear in the hand for other palyers

### ISSUE THREAD

**Issue by bajimu** [pmmp/PocketMine-MP#312]
I saw interesting bug. This bug consists in not appearing items in player hand (only for other players) when player pick up entity item (from world) in the hand slot.

Instruction to reproduce bug :
1) Needs 2 or more players. I will call them main and viewer. I used 2 my phones for show this bug.
2) The main's player inventory is fully empty.
![image](https://cloud.githubusercontent.com/assets/19263759/22484388/e0571344-e809-11e6-9004-a215ca52bebf.png)
![image](https://cloud.githubusercontent.com/assets/19263759/22484463/33a0b8d4-e80a-11e6-9b06-7d19775d67dd.png)
![image](https://cloud.githubusercontent.com/assets/19263759/22484505/656edd8c-e80a-11e6-92d5-961fb1564d35.png)
3) Player must pick up some drop in the empty hand slot. (after pick uping player should not change hand slot because bug can pass away to next time).
![image](https://cloud.githubusercontent.com/assets/19263759/22484563/adeea40c-e80a-11e6-8c39-9786b50b917f.png)
![image](https://cloud.githubusercontent.com/assets/19263759/22484735/70263fda-e80b-11e6-9595-7d039bad7c2e.png)
[But if main player try to change item in hand that the new item will be showed to viewer]
if you will do it right that other player will be see nothing in your hand, but you can pick up sword, lighter and other to trolling.

* PocketMine-MP:the latest version from Master
* PHP:7
* Server OS:Windows
* Game version: PE 1.0.2

**Comment by dktapps** [comment]
Fixed as of 132e04fdbbe4364f3997144f334d7b7df3548851
