### ISSUE TITLE
Water potion client side bug

### ISSUE THREAD

**Issue by Frago9876543210** [pmmp/PocketMine-MP#3122]
### Steps to reproduce the issue
1. /give <insert player name> 373
2. Consume potion. After this player will get two glass bottles (server side and client side). 
When trying to use client side item you will get this:
```
Failed to execute inventory transaction: Action pocketmine\inventory\transaction\action\SlotChangeAction is not valid in the current transaction
Actions: [{"sourceType":0,"windowId":124,"sourceFlags":0,"inventorySlot":0,"oldItem":{"id":0,"count":0},"newItem":{"id":374}},{"sourceType":0,"windowId":0,"sourceFlags":0,"inventorySlot":1,"oldItem":{"id":374},"newItem":{"id":0,"count":0}}]
```

### OS and versions
* PocketMine-MP: 15694279c75b00660e5b168ee25557c5284f6566
* PHP: 7.3.9
* Server OS: Ubuntu 18.04 LTS

**Comment by dktapps** [comment]
I'm closing this as WF because it's a client bug. Nothing to be done here.

**Comment by Frago9876543210** [comment]
Expected to use a different slot on server side after the client has consumed water

**Comment by dktapps** [comment]
I'm fully aware of the problem I'm telling you that it's not the server's fault. The fault lies in the client-side predictions.
