### ISSUE TITLE
Ejection of items does not work correctly

### ISSUE THREAD

**Issue by bajimu** [pmmp/PocketMine-MP#313]
I saw a strange bug. It is difficult to recreate and it you can create it a variety of ways. Item (entity) or item ejection does not work correctly. Sometimes you can try to ejection some item from inventory but item does not appear in the world and disappears from inventory. Also if you reconnect to server you can see lost item in your inventory. Also sometimes after ejection you can not see item entity but other player can see it and pick up too. Also you can see this bug often when server has more then 1 player.
PocketMine-MP:the latest version from Master
PHP:7
Server OS:Windows
Game version: PE 1.0.2

**Comment by Sandertv** [comment]
For the first part of the issue, have you made sure there isn't a plugin installed that cancels dropping items?

**Comment by dktapps** [comment]
I probably ought to make a mass-issue with a collection of all the inventory bugs... soon as shoghicp's transactions get here, I'm going to rewrite the lot.

**Comment by dktapps** [comment]
For the record, this is yet another very old irritating inventory bug along with myriad others. Please don't create issues for every one you find, otherwise our issue tracker is going to flood. :)

(Surprised nobody mentioned that issue with putting items in chests...)

**Comment by bajimu** [comment]
"For the first part of the issue, have you made sure there isn't a plugin installed that cancels dropping items?" - no, i tested this bug on fully clean server. There are 0 plugins, fully pm mp core and new world created by generator.

**Comment by bajimu** [comment]
@dktapps do you will reswrite the inventory system and when?

**Comment by dktapps** [comment]
I'm expecting MCPE 1.1 will feature the inventory upgrades. I don't want to do it twice.

**Comment by bajimu** [comment]
@dktapps also i fixed bug with  https://github.com/pmmp/PocketMine-MP/issues/283 . Try to transfer using of PlayerStatusPacket, DismentionPacket and dome other from Genysis (Player.php) and also you can transfer setHealth funcrion from there. It is fixed bug with tp between worlds.

**Comment by dktapps** [comment]
Fixed on mcpe-1.2 branch with 1.2 inventory changes.
