### ISSUE TITLE
Remove trailing directory separators from paths provided by the API

### ISSUE THREAD

**Issue by dktapps** [pmmp/PocketMine-MP#3136]
## Description
API methods which return directory paths, e.g.:
- `PluginBase->getDataFolder()`
- `Server->getDataPath()`
- `Server->getResourcePath()`

should **not** return paths with trailing directory separators.

## Justification
A common source of confusion and uneasiness when writing plugins is that it's not clear whether a function will return a path with a trailing `DIRECTORY_SEPARATOR` or not. Since a path is valid either way, there is no requirement to have a trailing slash.

It is common for developers to add their own `DIRECTORY_SEPARATOR`s to paths, regardless of whether the API claims to or not. For example:
```php
$myFilePath = $this->getDataFolder() . '/my_file.yml';
```
This gives certainty that you're not going to get some mash of `MyPluginmy_file.yml`, and because `MyPlugin//my_file.yml` is valid, there is no need to assume that `getDataFolder()` carries a trailing separator.

It makes more sense to allow devs to do this for their own peace of mind. As such, it does _not_ make sense to have the separator implied and always be wondering "is this code actually doing what it's supposed to?"

#### Ramifications
This change will break code that currently uses the above methods and assumes the presence of a trailing separator. Since the behaviour is not documented anywhere, it's technically not a BC break according to the spec, but it would nonetheless break plugins. Therefore, this change would need to be targeted at a major version.

**Comment by dktapps** [comment]
It would be nice if people who disagree with this would give a reason why instead of silently voting against it.

**Comment by SOF3** [comment]
Developers tend to find it difficult to check whether they are affected by this change. Indeed they can have a simple check through something like `git grep -E getDataFolder\|getResourcePath\|getDataPath`, but if they forgot, it might not be obvious to notice the bugs. Developers who already have a branch for 4.0.0 might *forget* to tackle this non-critical issue. In some cases, it might even cause security issues, e.g. plugins that use `$server->getResourcePath() . "../$string"` might accidentally lead to exposure of files beyond the server, which could create a greater vulnerability. (This example is problematic anyway, but this indeed greatly increases the risk of vulnerabilities)

It is suggested that a modern path-handling library like [pathogen](https://github.com/eloquent/pathogen) (not sure why it has been archived, perhaps look for alternatives?) be used. This adds type-level protection to code sanity, especially when developers wanted to avoid having double slashes in places where the user can see the full path.

**Comment by dktapps** [comment]
Closing this due to the potential for silent BC breaks it presents without practical benefit (a duplicated directory separator has the same effect as a single one).
