### ISSUE TITLE
API version accepts invalid numeric types

### ISSUE THREAD

**Issue by SOF3** [pmmp/PocketMine-MP#3140]
On docker image 3.9.5 tag

Run a plugin declaring API "3.0.0, 4.0.0". This works on 3.x but it shouldn't. This is a likely consequence of native int cast interpreting `0, 4.0.0` as zero without raising errors. This is unexpected and misleading behavior.

**Comment by dktapps** [comment]
for posterity's sake, I'm pretty sure this does not work on 4.0.

**Comment by dktapps** [comment]
Fixing this on PM3 is slightly more complicated than it should be because it's necessary to use customized regex that can understand stuff like `3` and `3.0` in addition to `3.0.0`. I'm not sure whether this can be classed as a bug or not.

**Comment by dktapps** [comment]
It's not worth the effort to address this on PM3. This has long since been fixed on PM4 (doing this will cause the plugin to fail to load with the message `Invalid API version`).
