### ISSUE TITLE
crash after canceling EntityDamageEvent after $player->transfer();

### ISSUE THREAD

**Issue by Saehing** [pmmp/PocketMine-MP#3149]
TypeError: "Return value of pocketmine\network\mcpe\NetworkSession::getInvManager() must be an instance of pocketmine\network\mcpe\InventoryManager, null returned" (EXCEPTION) in "src/network/mcpe/NetworkSession" at line 810

Decision:
 Player.php
 18003:

$entity->attack($ev);

if($ev->isCancelled()){
return false;
}

$entity->attack($ev); to put after the condition

crashdump: https://pastebin.com/MXLWp6fa

**Comment by dktapps** [comment]
duplicate of #1239

**Comment by dktapps** [comment]
whoops, wrong issue ... duplicate of #3139

**Comment by Saehing** [comment]
I'm sorry I didn't notice
