### ISSUE TITLE
Commands synchronization

### ISSUE THREAD

**Issue by Frago9876543210** [pmmp/PocketMine-MP#3153]
### Issue description
We currently have method `syncAvailableCommands` which sends command list for autocomplete to client. However, the problem is that the server does not check if this command is available when it is processed.

### OS and versions
* PocketMine-MP: d456cb24196b5bffe595de5a12dff0b45709f528
* PHP: 7.3.9
* Server OS: Ubuntu 18.04

**Comment by dktapps** [comment]
This issue makes roughly zero sense. I have no idea what you're trying to say.
