### ISSUE TITLE
Missing Items/Commands

### ISSUE THREAD

**Issue by Siah2x** [pmmp/PocketMine-MP#3163]
### Issue description

- Expected result: I expected to be able to use /gamerule and other commands, and be able to use command blocks, beacons, and some other redstone related items.
- Actual result: What actually happened? A TON of commands and items are gone from my creative inventory, and you cannot spawn them in. How can I fix this, I can't find anything online.

### Steps to reproduce the issue
The issue is always occurring.

### OS and versions
Version: 3.9.4
* PocketMine-MP:
* PHP:
* Server OS:
* Game version: PE/Win10 

### Plugins
- The issue is the same regardless of whether I have no plugins, or have plugins installed.

**Comment by DenielWorld** [comment]
@Siah2x Sir, you are looking for Bedrock Server Software. Please proceed out of PMMP if your server's main goal is vanilla features.
