### ISSUE TITLE
Make PocketMine-MP Vanilla-Like

### ISSUE THREAD

**Issue by ItzLightyHD** [pmmp/PocketMine-MP#3164]
This can be a good idea because making PocketMine-MP look like vanilla, can change all:
- First, the generation can be improved (This is the most important)
- Make redstone usable in PocketMine-MP
- Make all Minecraft logics working
- Make the imported Java worlds not corrupted, making the blocks and items use the Java IDs
- Make a Mob AI.
I know that these are implemented on a plugin named TeaSpoon, but are buggy.

**Comment by SOF3** [comment]
Thank you Captain obvious.
