### ISSUE TITLE
127.0.0.1 Can't Be Connect

### ISSUE THREAD

**Issue by akmvihfan** [pmmp/PocketMine-MP#3165]
Connecting Problem
I can't join my own server.
Idk why
Might glitch
Any one teach me how to fix it?

IP : 127.0.0.1
Port 19132

Am i doing wrong

**Comment by HimbeersaftLP** [comment]
https://pmmp.readthedocs.io/en/rtfd/faq/connecting/win10localhostcantconnect.html
