### ISSUE TITLE
Action not found in vanilla MCPE

### ISSUE THREAD

**Issue by Rush1533** [pmmp/PocketMine-MP#3168]
(I use Google Translate)
### Issue description

- Expected result: When attacked by a burned player, the attacked player does not burn in vanilla MCPE
- Actual result: PocketMine-MP burns the attacked player

### Steps to reproduce the issue
1. ... Attacked by a burning player

### version

* PocketMine-MP: Latest stable version

**Comment by dktapps** [comment]
Without knowing your PocketMine-MP version, OS, PHP, Client version, or plugins and how the issue occurred, the issue cannot begin to be solved.
A pre-formatted template is provided that shows the required information to begin to find, test and solve an issue.
Until the adequate template and information is provided, the issue will be closed; it may be reopened if you update the ticket with the correct template and required information.

[Contribution guidelines](https://github.com/pmmp/PocketMine-MP/blob/master/CONTRIBUTING.md)
