### ISSUE TITLE
Action not found in vanilla MCPE

### ISSUE THREAD

**Issue by Rush2927** [pmmp/PocketMine-MP#3170]
(I use Google Translate)
### Issue description

- Expected result: When attacked by a burned player, the attacked player does not burn in vanilla MCPE
- Actual result: PocketMine-MP burns the attacked player

### Steps to reproduce the issue
1. ... The attacking side must burn, so burn with flint
2. ... Attack the player while maintaining that state
3. ... Attacked player burns

### OS and versions

* PocketMine-MP: 3.9.3
* PHP: 7.2.19
* Server OS: Linux
* Game version: PE/Win10

### Plugins
`Plugins (0):`

**Comment by ItzLightyHD** [comment]
R.I.P.
