### ISSUE TITLE
FK SHOG!

### ISSUE THREAD

**Issue by 13358172372** [pmmp/PocketMine-MP#318]
I LOVE SHOG SO I'll FK YOU ALL!

**Comment by Sandertv** [comment]
Wtf?

**Comment by dktapps** [comment]
https://github.com/PocketMine/PocketMine-MP/issues/4322

I thought Dan was childish...

**Comment by 13358172372** [comment]
@Sandertv yes fk u

**Comment by 13358172372** [comment]
@dktapps u too.
