### ISSUE TITLE
Server crashed

### ISSUE THREAD

**Issue by WatermelonAM** [pmmp/PocketMine-MP#3188]
PocketMine doesn't support LevelDB! When it will support! I build i big town and i wanted to host it on a server but it is LevelDB

**Comment by ManiakMCPE** [comment]
You have to convert it

**Comment by WatermelonAM** [comment]
Oh... Can you help me with it? Where i can find converter?

**Comment by WatermelonAM** [comment]
> You have to convert it

Oh... Can you help me with it? Where i can find converter?

**Comment by TheBlackPlague** [comment]
This is not a bug, hence the issue tracker isn't the right place for this.

Secondly, a little research beforehand doesn't hurt. A quick Google search: "PMMP LevelDB", got me an answer to your question. Please refer to the forum thread [here](https://forums.pmmp.io/threads/leveldb-extension.7423/).
