### ISSUE TITLE
An SOS from your favourite lead PocketMine-MP developer

### ISSUE THREAD

**Issue by dktapps** [pmmp/PocketMine-MP#3189]
Yesterday my phone suffered a catastrophic collision with a floor, which led to the utter destruction of its screen. The touch and visuals are completely destroyed. The net result is that

- My ability to produce code is now entirely screwed
- I am locked out of any accounts which did not have a connected SMS phone number (including Discord, Twitter, forums and more)
- My contactability is now heavily impaired (I am reachable via [keybase](https://keybase.io/dktapps) in case you think this is a scam)

I do not currently have the funds to replace the device's screen and no other way to access the files on the device, where the majority of my 2FA backup codes are stored. Even with the required funds, it will still take weeks to get a replacement screen and get back into my accounts.

I am posting this here because I have no other way to achieve wide outreach and let the community know what has occurred.

**Comment by dktapps** [comment]
I have created a Discord alt `XiaomiMiPaperweightPro#9349` which will be reachable via the community Discord in approximately 3 minutes.

**Comment by Encritary** [comment]
lol

**Comment by dktapps** [comment]
Access to my accounts is now restored thanks to MS Authenticator backup (first attempt (7 days ago) to restore failed due to a glitch, second attempt (yesterday) succeeded).

Nonetheless, my contributions to PocketMine-MP are now halted indefinitely (including code review) due to lack of access to a reliable & capable device - the phone I am currently using struggles with the most basic of things, and I have very limited access to PCs currently.
