### ISSUE TITLE
Missing block (ID: 207)

### ISSUE THREAD

**Issue by HerryYT** [pmmp/PocketMine-MP#3196]
The addition of the frosted ice

because it add more block selection in game (better for builders)
![728abea7-bfca-4dc1-a34f-8da62b685af9](https://user-images.githubusercontent.com/34418030/69814388-64429900-11f4-11ea-97f3-a6b62306f1cc.jpg)

**Comment by yoraze** [comment]
Dylan asked to close this issue.(if it’s not difficult for you, help him: solve this problem yourself)
I advise you to add this block using the plugin.

**Comment by HerryYT** [comment]
By the way it makes no sense, i expect a software with all game features implemented into it and then plugins override them... bruh

**Comment by yoraze** [comment]
Do you know that when your project becomes a lot of features - you have to support them all? This requires a lot of free time, which could be spent on really important things for software.

**Comment by HerryYT** [comment]
Why not, nukkit is supporting all of them and still works for latest...
