### ISSUE TITLE
Jenkins is down

### ISSUE THREAD

**Issue by Touficbatache** [pmmp/PocketMine-MP#320]
Hello,
I was trying to access the Jenkins server but it seems like a CloudFlare page with the error 520 and a host error. If you could fix this it would be really great...
Thank you!

**Comment by Touficbatache** [comment]
Sorry, I mean error 522

**Comment by dktapps** [comment]
It's been down for weeks, an issue with our service provider. We did already have an issue here about this, but the author closed it for some unknown reason.

**Comment by Touficbatache** [comment]
I think that it can be fixed easily. I can try to help you...

**Comment by Touficbatache** [comment]
Email me touficbatache[at]gmail[dot]com

**Comment by SOF3** [comment]
Fixed already.
