### ISSUE TITLE
Validate command permissions when assigned

### ISSUE THREAD

**Issue by dktapps** [pmmp/PocketMine-MP#3200]
## Description
`Command->setPermission()` should validate that the permissions given have been registered, and throw exceptions if they haven't.

## Justification
This is somewhat related to #2862 .
It's possible to set a permission to a command which doesn't exist, which can silently cause unexpected behaviour. However, applying #2862 isn't enough, because it will cause errors to be raised when the faulty permissions are used, which would only happen when the command is executed.

The ideal behaviour is to have an error raised when trying to assign the permission to begin with.

**Comment by dktapps** [comment]
This will require changes to the startup sequence, since command permissions are currently not registered until after plugins are enabled.

**Comment by SOF3** [comment]
> It's possible to set a permission to a command which doesn't exist
A command which doesn't exist, or a permission which doesn't exist?

**Comment by dktapps** [comment]
Implemented in the referenced commit.
