### ISSUE TITLE
Skin was invisible after change Skin with UltraCapes or SlashSkin

### ISSUE THREAD

**Issue by Crasher508** [pmmp/PocketMine-MP#3206]
### OS and versions

* PocketMine-MP: 3.10.1
* Server OS: PocketMine-MP
* Game version: 1.13.1 Win10

### Plugins
- PocketMine-DevTools
- SlashSkin
- UltraCape

When I add a Cape on my Skin with UltraCapes, they was invisible. When I Change the Skin with SlashSkin they was too invisible.

**Comment by dktapps** [comment]
There is no 3.10.1.

**Comment by Crasher508** [comment]
Sorry, I mean 3.10.0

**Comment by Crasher508** [comment]
> There is no 3.10.1.
Sorry, I mean 3.10.0
