### ISSUE TITLE
Jenkins alternative

### ISSUE THREAD

**Issue by Touficbatache** [pmmp/PocketMine-MP#321]
Hello,
Today I have opened a Jenkins issue because it is down but I found an alternative that Genisys uses. Gitlab! For an example, I forked this repository and sent it to gitlab. Here's a phar of the newest version here https://gitlab.com/touficbatache/PocketMine-MP/builds/9883170/artifacts/download.
Thank you.

**Comment by dktapps** [comment]
Thank you, we are _aware_ of this. I am a Genisys developer myself. We do not use GitLab because it's a pain in the butt to maintain synchronization, and GitLab is unreliable.
