### ISSUE TITLE
Crafting Table Error

### ISSUE THREAD

**Issue by RedBull572** [pmmp/PocketMine-MP#3211]
### Issue description

When I craft something, it will become but when it is held it will disappear!

### OS and versions

* PocketMine-MP: 3.10.1
* PHP: 7.3
* Server OS: Ubuntu
* Game version: PE

**Comment by jasonwynn10** [comment]
Please clarify and or link a video with the issue

**Comment by RedBull572** [comment]
https://drive.google.com/file/d/1-fRtG9qXHyzB71oDYOk1usCRFNd3lV3q/view?usp=drivesdk

**Comment by dktapps** [comment]
Without knowing your PocketMine-MP version, OS, PHP, Client version, or plugins and how the issue occurred, the issue cannot begin to be solved.
A pre-formatted template is provided that shows the required information to begin to find, test and solve an issue.
Until the adequate template and information is provided, the issue will be closed; it may be reopened if you update the ticket with the correct template and required information.

[Contribution guidelines](https://github.com/pmmp/PocketMine-MP/blob/master/CONTRIBUTING.md)
