### ISSUE TITLE
Crafting Error and skin

### ISSUE THREAD

**Issue by TimKunG1007** [pmmp/PocketMine-MP#3212]
I can't craft item in craft table and Skin Bug
Fighting✌✌✌✌🤘🤞
### OS and versions

* PocketMine-MP: 1.13.1
* PHP: 7.3
* Server OS: Windows 2012
* Game version: 1.13.1

**Comment by DenielWorld** [comment]
Read changelog, the skin issue isn't a bug. Try crafting items without any plugins, crafting should work just fine. PocketMine-MP and Game version are not the same thing.

**Comment by dktapps** [comment]
duplicate of #3211 and still nobody figured out that **all** information in the template is required...
