### ISSUE TITLE
We Can't craft

### ISSUE THREAD

**Issue by RubyTemple** [pmmp/PocketMine-MP#3215]
we can't craft with the last pmmp version! please solve this [16:10:17] [Server thread/INFO]: Questo server gira su PocketMine-MP 3.10.1 per Minecraft: Edizione Bedrock v1.13.0 (protocollo versione 388)

**Comment by dktapps** [comment]
this is the fifth duplicate which didn't follow the template or provide useful information...

Without knowing your PocketMine-MP version, OS, PHP, Client version, or plugins and how the issue occurred, the issue cannot begin to be solved.
A pre-formatted template is provided that shows the required information to begin to find, test and solve an issue.
Until the adequate template and information is provided, the issue will be closed; it may be reopened if you update the ticket with the correct template and required information.

[Contribution guidelines](https://github.com/pmmp/PocketMine-MP/blob/master/CONTRIBUTING.md)
