### ISSUE TITLE
Implement native UPnP support

### ISSUE THREAD

**Issue by dktapps** [pmmp/PocketMine-MP#3216]
Currently UPnP forwarding is only supported on Windows because we use .NET bindings to use C# API for forwarding (com_dotnet). It's possible to implement forwarding natively in PHP without .NET, by introducing dependency on XML extensions (which are now provided with our PHP builds by default).

**Comment by HimbeersaftLP** [comment]
> Currently UPnP forwarding is only supported on Linux

I think you wanted to say "Windows"?

**Comment by dktapps** [comment]
thanks, brain bug caught me out yet again...
