### ISSUE TITLE
No complex data stored for this async task

### ISSUE THREAD

**Issue by ManiakMCPE** [pmmp/PocketMine-MP#3224]
CONSOLE LOG:
11.12 21:32:23 [Server] Server thread/CRITICAL InvalidStateException: "No complex data stored for this async task" (EXCEPTION) in "src/pocketmine/scheduler/AsyncTask" at line 303
11.12 21:32:23 [Server] Server thread/DEBUG #0 src/pocketmine/scheduler/AsyncTask(273): pocketmine\scheduler\AsyncTask->peekLocal()
11.12 21:32:23 [Server] Server thread/DEBUG #1 src/pocketmine/network/mcpe/VerifyLoginTask(163): pocketmine\scheduler\AsyncTask->fetchLocal()
11.12 21:32:23 [Server] Server thread/DEBUG #2 src/pocketmine/scheduler/AsyncPool(321): pocketmine\network\mcpe\VerifyLoginTask->onCompletion(object pocketmine\Server)
11.12 21:32:23 [Server] Server thread/DEBUG #3 src/pocketmine/scheduler/AsyncPool(355): pocketmine\scheduler\AsyncPool->collectTasks()
11.12 21:32:23 [Server] Server thread/DEBUG #4 src/pocketmine/Server(2125): pocketmine\scheduler\AsyncPool->shutdown()
11.12 21:32:23 [Server] Server thread/DEBUG #5 src/pocketmine/Server(2318): pocketmine\Server->forceShutdown()
11.12 21:32:23 [Server] Server thread/DEBUG #6 src/pocketmine/Server(2246): pocketmine\Server->crashDump()
11.12 21:32:23 [Server] Server thread/DEBUG #7 src/pocketmine/Server(1787): pocketmine\Server->exceptionHandler(object ErrorException)
11.12 21:32:23 [Server] Server thread/DEBUG #8 src/pocketmine/PocketMine(272): pocketmine\Server->__construct(object BaseClassLoader, object pocketmine\utils\MainLogger, string[43] /, string[51] /plugins/)
11.12 21:32:23 [Server] Server thread/DEBUG #9 src/pocketmine/PocketMine(295): pocketmine\server()
11.12 21:32:23 [Server] Server thread/DEBUG #10 (1): require(string[94] phar:///jar/pocketmine/pocketmine.phar/src/pocketmine/)

**Comment by ZizzyZizzy** [comment]
FILL OUT THE FORM that was presented if you expect anything constructive to happen.

Not doing so is just wasting the developers time to have to come in here, tell you that the information is missing, and then close the issue. Wouldn't you rather they be spending time fixing legitimate issues?
