### ISSUE TITLE
Crafted Items not usable

### ISSUE THREAD

**Issue by darknessatnoon** [pmmp/PocketMine-MP#3230]
### Issue description

If you craft something and take it in Hand then you lose your crafted Item and get back your Materials before crafting.

### OS and versions

* PocketMine-MP:3.11.1
* PHP:7
* Server OS:debian
* Game version: PE/Win10 (delete as appropriate)

**Comment by Wumpotamus** [comment]
delete teaspoon

**Comment by teracube** [comment]
https://twitter.com/dktapps/status/1203695593798979584
