### ISSUE TITLE
Crafting Table, Items produced de-spawn

### ISSUE THREAD

**Issue by xXRyzen** [pmmp/PocketMine-MP#3231]
### Issue description

- Expected result: Items being crafted to be produced and given to crafter when grabbing from table output
- Actual result: When placing items in crafting table, item produced disappears when trying to grab output item and original items placed in table are given back to inventory bar

### Steps to reproduce the issue
1. Place crafting table
2. Place items in crafting table to produce any appropriate item then grab item from table output

### OS and versions

* PocketMine-MP: Latest Version 3.11.1 for 1.14 protocol 389
* PHP: 7.2
* Server OS: Linux
* Game version: PE/Win10, Android, IOS have confirmed same issue 

### Plugins

Plugins (54): ScoreHud v4.0.0, TeaSpoon v1.2.0, EconomyAPI v5.7.2, TopVoter v3.1.0, TimeCommander v1.0.2, Repair v1.0.1, DevTools v1.13.0, CombatLogger v0.0.6, EconomyLand v2.1.2, SimpleHome v1.0.3, GappleCooldown v2.0.1, Festival v1.1.3, CustomShopUI v4.0.4, PurePerms v1.4.2-c2a, KitUI v1.3.4, Parkour v1.5.7, xPlayerInventories v1.0.1, SellAll v1.2.0, Bounty v1.1.2, GroupJoin v0.0.1, PureChat v1.4.11, WorldProtect v2.3.8, AntiSpamPro v1.4.1, VoteReward v3.0.3, TapToDo v2.3.0, SlapperRotation v1.2.1, PvpKillRate v1, MyPlot v1.4, SignChanger v1, AntiAntiSwearFilter v0.1.0, StaffChat v1.1.1, PortalsPE v1.1.1, KDR v1.0.0, EmotionsPE v1, ManyWorlds v2.2.0, BanItem v2.3.3, MOTDShuffle v1.1.6, ClearLagg v1.1.0, CoolCrates v1.4, ChatTagPE v1.0.1, MSpawns v2.2, MagicWE2 v7.0.0, essentialsTP v1.2.1, BlockSniffer v1.0.0, EC-TableUI v1.0.0-pre, Slapper v1.5.0, FormAPI v1.3.0, MCPEToDiscord v1.4, superBAR v2.0.0, ShellyEssentials v1.1.0, BPSignShop v1, ChatScrambler v1.0.0, FactionsPro v1.3.15

- If you remove all plugins, does the issue still occur?
- If the issue is **not** reproducible without plugins:
  - Have you asked for help on our forums before creating an issue?
  - Can you provide sample, *minimal* reproducing code for the issue? If so, paste it in the bottom section

**Comment by Wumpotamus** [comment]
Delete teaspoon

**Comment by teracube** [comment]
https://twitter.com/dktapps/status/1203695593798979584

**Comment by xXRyzen** [comment]
Thank you. And sorry dk
