### ISSUE TITLE
Chunks Not Saving

### ISSUE THREAD

**Issue by TotherMeteor** [pmmp/PocketMine-MP#3233]
### Issue description

- Expected result: I was expecting the server to save chunks normally.
- Actual result: The server reverts chunks to their prior state once they're unloaded.

### Steps to reproduce the issue
1. I literally just ran the server, mined a few blocks, relogged and it acted as if i never did anything, the blocks still appeared in my inventory though.
2. Maybe it had something to do with the map we where using, I don't know how big it was, but I do know it was fairly large.

### OS and versions

* PocketMine-MP: 3.11.1
* PHP: I don't know.
* Server OS: Linux Ubuntu 18
* Game version: PE/Win10 (delete as appropriate)

### Plugins

- If you remove all plugins, does the issue still occur?
yes
- If the issue is **not** reproducible without plugins:
  - Have you asked for help on our forums before creating an issue?
  - Can you provide sample, *minimal* reproducing code for the issue? If so, paste it in the bottom section

**Comment by dktapps** [comment]
Spawn protection is enabled by default, turn it off in server.properties.
