### ISSUE TITLE
Server crashes when a certain player joins

### ISSUE THREAD

**Issue by TotherMeteor** [pmmp/PocketMine-MP#3237]
[Sat_Dec_14-03.54.37-CET_2019.log](https://github.com/pmmp/PocketMine-MP/files/3963525/Sat_Dec_14-03.54.37-CET_2019.log)

Link to crashdump: https://pastebin.com/Qat4FnnN

### Additional comments (optional)

Originally when my friend would join, the server would crash, he had to make a new account to play. I made a new server and now I'm the one crashing it. I don't know why but I hope you're able to fix this.

**Comment by jasonwynn10** [comment]
fixed by 2cb6990698e2575e0b64fef7e5172d9dd9694ff6
