### ISSUE TITLE
Contributing guidelines on PR base branch selection

### ISSUE THREAD

**Issue by SOF3** [pmmp/PocketMine-MP#3243]
There is no updated document that explains the branching policy in PocketMine. In particular, when a developer opens a pull request, which branch should it be targeted against? This should be added to `CONTRIBUTING.md`. Currently I am seeing different pull requests targeting master, stable and next-minor.

**Comment by dktapps** [comment]
Done in https://github.com/pmmp/PocketMine-MP/commit/4650a3bb22237c9987d2317737258d117fa4983a.
