### ISSUE TITLE
Tripwire hook, button, pressure plate BUG

### ISSUE THREAD

**Issue by padreon** [pmmp/PocketMine-MP#3245]
### Issue description

- when placing a **Tripwire hook**, **Tripwire hook** does not follow in the direction of the block
- when a block is destroyed, the **button** or **pressure plate** is not destroyed

### Steps to reproduce the issue
[watch this video](https://youtu.be/R0beh445qGc)

### OS and versions

* PocketMine-MP: 3.11.1
* Server OS: Windows10
* Game version: 1.14.0

**Comment by dktapps** [comment]
This is a known issue already documented here: https://github.com/pmmp/PocketMine-MP/projects/14
