### ISSUE TITLE
Player eats consecutive items without delay

### ISSUE THREAD

**Issue by Saehing** [pmmp/PocketMine-MP#3246]
PocketMine-MP version: 4.0.0+dev [Protocol 389]
Git commit: 2cb6990698e2575e0b64fef7e5172d9dd9694ff6
uname -a: Windows NT DESKTOP-MN4377B 10.0 build 18362 (Windows 10) AMD64
PHP Version: 7.3.12
Zend version: 3.3.12
OS : WINNT, win
No plugins.

In the second video, when a player eats something, the second player has particles

https://youtu.be/dCgqznPeURw
https://youtu.be/Ba59ZaqslKM

**Comment by SOF3** [comment]
"latest pmmp 4.0" is not a valid version. Please specify.

**Comment by Saehing** [comment]
> "latest pmmp 4.0" is not a valid version. Please specify.

Is that better?
