### ISSUE TITLE
Login Timeout, when player.dat existing

### ISSUE THREAD

**Issue by Crasher508** [pmmp/PocketMine-MP#3249]
### OS and versions
* PocketMine-MP: 3.11.1
* Server OS: PocketMine-MP/ Linux
* Game version: 1.14 Win10

### Plugins
- Devtools, PurePerms, EconomyAPI

When Player join a PocketMine-MP Server at the first time (Player.dat will not exist) they hadn't became a Login time. When they join again and the Player.dat exist, they became a Login timeout.

**Comment by dktapps** [comment]
Cannot reproduce. Check your plugins.
