### ISSUE TITLE
Particle Bug

### ISSUE THREAD

**Issue by GabrielJose10** [pmmp/PocketMine-MP#3257]
API has a bug in Particle rendering

**Comment by Encritary** [comment]
Informative 100

**Comment by GabrielJose10** [comment]
![Screenshot_20191225-202728](https://user-images.githubusercontent.com/52938157/71456081-85a48f80-2776-11ea-9d09-beabd5356cdd.png)

No It works

**Comment by SOF3** [comment]
Without knowing your PocketMine-MP version, OS, PHP, Client version, or plugins and how the issue occurred, the issue cannot begin to be solved.
A pre-formatted template is provided that shows the required information to begin to find, test and solve an issue.
Until the adequate template and information is provided, the issue will be closed; it may be reopened if you update the ticket with the correct template and required information.

**Comment by DinoDuckVN** [comment]
Nice infomation
