### ISSUE TITLE
Particle ID's maybe wrong

### ISSUE THREAD

**Issue by Erkam246** [pmmp/PocketMine-MP#3258]
### Issue description
- Expected result: What were you expecting to happen?

To spawn DustParticle or the given one

- Actual result: What actually happened?

If you spawn some particles you will get some brown / yellow slime particle which makes a weird sound

### Steps to reproduce the issue
1. Level -> addParticle( DustParticle ) or some other

### OS and versions

* PocketMine-MP: 3.11.1
* PHP: 7.3.11
* Server OS: Debian 10

### Plugins

Works only with plugins

### Crashdump, backtrace or other files

There is no crashdump

**Comment by dktapps** [comment]
fixed in 3.11.2
