### ISSUE TITLE
server freeze

### ISSUE THREAD

**Issue by RubyTemple** [pmmp/PocketMine-MP#3260]
### Issue description

- Expected result: the task doesn't crash and that the server correctly sends the chunks. 
- Actual result: server freeze and isn't possible stop the server. 

### Steps to reproduce the issue
Idk I have only started the server. 

### OS and versions

* PocketMine-MP: 3,11,1
* PHP: 7.3
* Server OS: Ubuntu18.04lts
* Game version: PE/Win10

### Plugins

pl
 TopVoter v3.2.0, FormAPI v1.3.0, VoidGenerator v1.0.0, DEVirion v1.2.5-ALPHA12, DevTools v1.13.0, GuiShop v1.0.0-ALPHA1, EssentialsPE v2.1.0, WorldProtect v2.3.8, PiggyCustomEnchants v1.4.3, AntiSpamPro v1.4.1, Alias v1.2.3, BlockSniper v3.2.3, iProtector v3.1.1, PurePerms v1.4.2, ScoreboardAPI v1.0.0, EconomyAPI v2.0.9, MobStacker v2.0.0, SlapperRotation v1.2.1, BedrockPick v1.3.0, CrateKey v1, ManyWorlds v2.2.0, MCBEMusic v1, BankNotes v2.0.3, InvSee v1.0.0, Trader v1.0.0, BuilderTools v1.2.0-beta2, FactionsPro v1.3.18, Slapper v1.5.0, KnockbackFFA v1.8.0, VoteReward v3.0.3, TempBan v1, PiggyCustomEnchantsShop v1.2.1, PlayerVaults v3.0, ClearLaggPE v2.0.0, BuycraftPM v1.1.0, Mobs v0.0.1, Scoreboard v0.0.1, Cps v0.0.1, onl v1.0, AdvancedKits v5.2.5, RedstoneCircuit v2.0.0, PerWorldInventory v0.0.1, Core v3.0.0, SellAll v1.3.0, CustomCrafting v0.2, PureChat v1.4.11, Table v1.1.1, CombatLogger v0.0.5, Afterlife v4.0.0

### Crashdump, backtrace or other files
2019-12-29 [00:10:39] [Server thread/CRITICAL]: Could not execute asynchronous task ChunkRequestTask: Task crashed
2019-12-29 [00:10:39] [Server thread/ERROR]: Failed to prepare chunk -4 18 for sending, retrying
2019-12-29 [00:10:39] [Asynchronous Worker #2 thread/CRITICAL]: Error: "Class 'pocketmine\network\mcpe\protocol\LevelChunkPacket' not found" (EXCEPTION) in "src/pocketmine/level/format/io/ChunkRequestTask" at line 59
2019-12-29 [00:10:39] [Asynchronous Worker #2 thread/DEBUG]: #0 src/pocketmine/scheduler/AsyncTask(75): pocketmine\level\format\io\ChunkRequestTask->onRun()
2019-12-29 [00:10:39] [Asynchronous Worker #2 thread/DEBUG]: #1 (): pocketmine\scheduler\AsyncTask->run()

**Comment by RubyTemple** [comment]
server freeze and isn't possible sto the server

**Comment by RubyTemple** [comment]
![IMG_20191229_012718_436](https://user-images.githubusercontent.com/28711906/71550865-5e4dfc80-29da-11ea-9e72-6792aff8386f.jpg)
This is the server when this error appear

**Comment by AkmalFairuz** [comment]
Try to running your server at another device.

**Comment by jasonwynn10** [comment]
Run your server without plugins and tell if you get the same issue

**Comment by dktapps** [comment]
Cannot reproduce. It's possible this may be pthreads-related, so update your PHP binary (and PM version too), and see if the issue persists.

**Comment by RubyTemple** [comment]
> Cannot reproduce. It's possible this may be pthreads-related, so update your PHP binary (and PM version too), and see if the issue persists.

i have already last binary and pmmp ver

**Comment by jasonwynn10** [comment]
How many workers/threads are set in your Pocketmine.yml?

**Comment by RubyTemple** [comment]
> How many workers/threads are set in your Pocketmine.yml?

i have all standard

**Comment by jasonwynn10** [comment]
Set threads/workers equal to your logical core count And try again

**Comment by RubyTemple** [comment]
ok i will try

**Comment by RubyTemple** [comment]
> Set threads/workers equal to your logical core count And try again

ok i will try thanks
