### ISSUE TITLE
Server crashed

### ISSUE THREAD

**Issue by ElectroGamesYT** [pmmp/PocketMine-MP#3263]
[Pterodactyl Daemon] Checking size of server data directory...
[Pterodactyl Daemon] Disk Usage: 310M / 0M
[Pterodactyl Daemon] Ensuring file permissions.
[Pterodactyl Daemon] Running server preflight.
[Pterodactyl Daemon] Starting server container.
Warning: require(phar:///home/container/PocketMine-MP.phar/src/pocketmine/PocketMine.php): failed to open stream: phar "/home/container/PocketMine-MP.phar" has a broken signature in /home/container/PocketMine-MP.phar on line 1
Fatal error: require(): Failed opening required 'phar:///home/container/PocketMine-MP.phar/src/pocketmine/PocketMine.php' (include_path='.:') in /home/container/PocketMine-MP.phar on line 1
[Pterodactyl Daemon] Server marked as OFF
[Pterodactyl Daemon] ---------- Detected server process in a crashed state! ----------
[Pterodactyl Daemon] Exit Code: 255
[Pterodactyl Daemon] Out of Memory: false
[Pterodactyl Daemon] Error Response:
[Pterodactyl Daemon] Aborting automatic reboot due to crash within the last 60 seconds.

**Comment by HimbeersaftLP** [comment]
@ElectroGamesYT If your .phar has a broken signature, that means the file is corrupted. Try downloading it again.
