### ISSUE TITLE
Chunks Not Loading

### ISSUE THREAD

**Issue by ElectroGamesYT** [pmmp/PocketMine-MP#3264]
- Expected result: Chunks to load
- Actual result: Chunks arent loading, /spawn or /warps do not work becuase it says the chunks arent loaded.

### Steps to reproduce the issue
1. I do not know, it was working in PocketMine-MP 3.11.1

### OS and versions

* PocketMine-MP: PocketMine-MP 3.11.2
* PHP: Idk
* Server OS: IDK
* Game version: PE/Win10

### Plugins

It is not any plugins, it also happens to other people and ive talked to a pocketmine developer and they said "pmmp updated since than and it caused alot of chunk and plugin bugs"
So im just reporting it.

### Crashdump, backtrace or other files
No crashes.

**Comment by ZizzyZizzy** [comment]
Not for nothing - if you can't provide steps to reproduce the issue, then you're just wasting your time and the developers time chasing a ghost that may or may not exist. They will just close this issue.
