### ISSUE TITLE
Can't place banners gived by comand

### ISSUE THREAD

**Issue by Invy55** [pmmp/PocketMine-MP#3265]
### Issue description

- Expected result:
The banner placed is white with a black mojang logo on it.
- Actual result: 
The banner get placed, but the server kicks me (when placing it) and when I return in the server the banner is invisible and the hitbox is only for the bottom part.

### Steps to reproduce the issue
1. /give PLAYER minecraft:banner 1 {BlockEntityTag:{Base:15,Patterns:[{Pattern:bri,Color:0}]}}
2. Place the banner and get kicked

### OS and versions

* PocketMine-MP: 3.11.2 for Minecraft: Bedrock Edition v1.14.0 (protocol version 389)
* PHP: 7.4
* Server OS: Windows 10 pro
* Game version: Win10 and PE

### Plugins

BuilderTools v1.2.0-beta2, VanishV2 v1.3, InvSee v1.0.0, DevTools v1.13.5, Slapper v1.5.2, MultiWorld v1.5.2, MapImageEngine v1.1.3, PurePerms v1.4.3, FormAPI v1.3.0, PureChat v1.4.11, VoidTP v1.0.2, SlapperRotation v1.2.1, RedstoneCircuit v1.0.1, SlashSkin v1.0.0, Banner v0.0.1 (simple plugin made from me that uses form api to gen the command), MIE_Converter v1.0.2, pluginp v1.1.0, iProtector v3.1.1, SlapperCache v2.0.1

- If you remove all plugins, does the issue still occur? Yes

### Crashdump, backtrace or other files

It is not a crash but a CRITICAL ERROR so I can't paste on that website... I'll use pastebin: https://pastebin.com/gAxp3K8S

_Sorry for my bad english_

**Comment by dktapps** [comment]
does not reproduce, and we don't support 7.4 yet ...

**Comment by dktapps** [comment]
also, the pattern is bricks, not the mojang logo.

**Comment by Invy55** [comment]
> also, the pattern is bricks, not the mojang logo.

Yes, so what can I do?

**Comment by Invy55** [comment]
> does not reproduce, and we don't support 7.4 yet ...

Mhh... I've tried with php 7.3 on debian 10 still not working........
