### ISSUE TITLE
Cobblestone generator stops after server restart

### ISSUE THREAD

**Issue by Erkam246** [pmmp/PocketMine-MP#3273]
### Issue description
Cobblestone generator doesn't creates cobblestone

### Steps to reproduce the issue
Build an Cobblestone generator

### OS and versions

* PocketMine-MP: 3.11.3
* PHP: 7.3.11
* Server OS: Debian 10

**Comment by dktapps** [comment]
duplicate of #2912 , #2943 , #2099
