### ISSUE TITLE
Abnormal resource usage

### ISSUE THREAD

**Issue by nnnlog** [pmmp/PocketMine-MP#3274]
### Issue description

- Expected result: Chunk loading performed in a reasonable time
- Actual result: The chunk is loaded for a long time, during which the CPU usage is 100%.

### Steps to reproduce the issue
1. join the server or teleport to other worlds.

### OS and versions

* PocketMine-MP: 43601e57bf242a87ca5ca0028deae97d93bb29ba
* PHP: 7.3.13
* Server OS: Ubuntu 18.04

### Plugins
* Same thing with or without the plugin.

### Crashdump, backtrace or other files
https://timings.pmmp.io/?id=7809

**Comment by dktapps** [comment]
There's no problem with chunk loading in that timings report.

**Comment by nnnlog** [comment]
@dktapps Looking at resource usage using htop when moving from one world to another, it seems that PMMP's async task is reaching 100% CPU usage. I do not believe PMMP measures asynchronous operations.

**Comment by dktapps** [comment]
This isn't abnormal, it's just a consequence of using the new chunk format. The paletted format is more expensive to encode.
