### ISSUE TITLE
Improper case checking of command aliases in pocketmine.yml

### ISSUE THREAD

**Issue by Muqsit** [pmmp/PocketMine-MP#3281]
### Issue description
The checks in `SimpleCommandMap::registerServerAliases()` disallowing registration of recursive commands can be bypassed due to pocketmine's case insensitive validation but lowercasing before registration.

- Expected result:
Mapping `Help` as an alias of `help` in `pocketmine.yml` should display a recursion warning.
- Actual result: What actually happened?
Server maps `Help` as an alias of `help` and executing `help` results in a Segmentation Fault.

### Steps to reproduce the issue
Modify `pocketmine.yml` like so:
```yaml
aliases:
  Help: help
```
Run command `help` - Results in segmentation fault.

### OS and versions

* PocketMine-MP: 8184a6b and 5955ff5
* PHP: 7.3.11
* Server OS: Ubuntu 18.04.1 LTS
* Game version: Win10

### Plugins

- If you remove all plugins, does the issue still occur?
Yes

**Comment by dktapps** [comment]
This is two separate bugs in one issue.

**Comment by Muqsit** [comment]
Split into #3289.
