### ISSUE TITLE
PlayerDropItemEvent not fired when server-side drop of crafting grid contents occurs

### ISSUE THREAD

**Issue by DontHave480** [pmmp/PocketMine-MP#3284]
### Issue description
In creative when I put things in the crafting and inventory is full, the items drop.
Even if cancelling dropevent.
https://youtu.be/D9kVTBlzUuE
### Steps to reproduce the issue
1. Cancell dropevent

### OS and versions

* PocketMine-MP: 13f28d8
* PHP: 7.3.12
* Server OS: Ubuntu 18.04
* Game version: PE/Win10

### Plugins

LimitedCreative v1.0.0

### Crashdump, backtrace or other files

There is no crashdump

**Comment by Crypt97** [comment]
@dktapps 
When will this be ready? That would be important enough.

**Comment by Crypt97** [comment]
@dktapps 
I also pay for it just do it please. xD

**Comment by DontHave480** [comment]
@dktapps 
Something news?
This issue opened in January. Six months ago.

**Comment by dktapps** [comment]
The problem with this is that there's nowhere for the items to go if the event is cancelled, so any items that were left in the crafting grid would be destroyed if the drop was cancellable.

**Comment by dktapps** [comment]
Fixed by 082f0f2d5732a1d005bbf6ec70004970cc06d8f8.
