### ISSUE TITLE
Server-Crash

### ISSUE THREAD

**Issue by NxtUser-HD** [pmmp/PocketMine-MP#3286]
### Issue description

- Expected result: What were you expecting to happen?
- Actual result: What actually happened?

### Steps to reproduce the issue
1. ...
2. ...

### OS and versions

* PocketMine-MP:
* PHP:
* Server OS:
* Game version: PE/Win10 (delete as appropriate)

### Plugins

- If you remove all plugins, does the issue still occur?
- If the issue is **not** reproducible without plugins:
  - Have you asked for help on our forums before creating an issue?
  - Can you provide sample, *minimal* reproducing code for the issue? If so, paste it in the bottom section

### Crashdump, backtrace or other files

![Unbenannt](https://user-images.githubusercontent.com/50436997/73143668-3c10d280-409d-11ea-8a62-5062270c5cff.png)

**Comment by NxtUser-HD** [comment]
OS and versions
PocketMine-MP: Newest version of branch stable
PHP: 7.3
Server OS: Debian 9

**Comment by jasonwynn10** [comment]
That's whatcha get for running from source without knowing what you're doing. Use a phar release instead
