### ISSUE TITLE
Aliases in pocketmine.yml override registered commands

### ISSUE THREAD

**Issue by Muqsit** [pmmp/PocketMine-MP#3289]
### Issue description

- Expected result
Mapping a registered command to another command issue a warning like other warnings that could occur while parsing `aliases` in `pocketmine.yml` (`pocketmine.command.alias.illegal`, `pocketmine.command.alias.recursive`, `pocketmine.command.alias.notFound`).
- Actual result
Server silently overrides the already existing command.

### Steps to reproduce the issue
Map an already registered command's name to a command in `pocketmine.yml`
```yml
aliases:
  help: kill
```
Running command `help` runs `kill`.

### OS and versions

* PocketMine-MP: 8184a6b and 5955ff5
* PHP: 7.3.11
* Server OS: Ubuntu 18.04.1 LTS
* Game version: Win10

### Plugins

- If you remove all plugins, does the issue still occur?
Yes

**Comment by dktapps** [comment]
This appears to work as intended, and even supports using an empty alias to null-route a command.

**Comment by dktapps** [comment]
Note that the original `help` command would still be available as `pocketmine:help` or `?`.
