### ISSUE TITLE
Crafting table sometimes returns an error.

### ISSUE THREAD

**Issue by MistakingManx** [pmmp/PocketMine-MP#3290]
### Issue description

- Expected result: The crafting table should open.
- Actual result: Sometimes randomly instead of opening it just says in chat `<error> errorcode 1` (or something similar), but it works if you click it again.

### Steps to reproduce the issue
1. Tap/Click a crafting table.
2. it's random but sometimes it happens, not too often but its noticble, for multiple pocketmine servers that ive been playing on. (including my own)

### OS and versions
* PocketMine-MP: 3.11.4 [Also happens on older versions starting on 3.11]
* PHP: Multiple version of php im assuming, this happens on servers that also aren't mine.
* Server OS: Ubuntu

### Plugins
Plugins don't seem to be the issue as it happens on multiple servers with different plugins on them.
[and some servers have nearly 100 plugins so i dont want to get them all..]
- If you remove all plugins, does the issue still occur?
Yes, I've tested it on my own server.
### Crashdump, backtrace or other files
None.

**Comment by dktapps** [comment]
the crafting window is client sided, there's nothing to be done here.
