### ISSUE TITLE
Splash Potion Makes Drinking Sound

### ISSUE THREAD

**Issue by Wumpotamus** [pmmp/PocketMine-MP#3291]
### Issue description
When using a splash potion, it does the slurp noise of drinking a potion.
- Expected result: No slurp noise
- Actual result: Slurp noise

### Steps to reproduce the issue
1. Get splash potion
2. Splash it
3. Profit

### OS and versions

* PocketMine-MP: 3.11.4
* PHP: 7.3.13
* Server OS: Windows 10
* Game version: PE/Win10

### Plugins

- If you remove all plugins, does the issue still occur?
- If the issue is **not** reproducible without plugins:
  - Have you asked for help on our forums before creating an issue?
  - Can you provide sample, *minimal* reproducing code for the issue? If so, paste it in the bottom section

**Comment by dktapps** [comment]
have you tested this in vanilla?

**Comment by Wumpotamus** [comment]
No, but I'm also now unable to reproduce it, so I'm closing it.
