### ISSUE TITLE
PlayerItemConsumeEvent falsely called with food items

### ISSUE THREAD

**Issue by Xenophilicy** [pmmp/PocketMine-MP#3293]
### Issue description

- Expected result: When an item (like food) is consumed (like steak being eaten or rotten flesh for example) the event should be called.
- Actual result: The event is called when the hunger bar is full (when the player's food attribute equals 20) and the food item is NOT consumed.

### Steps to reproduce the issue
1. Be sure your food bar is completely full
2. Write a simple function to show when a food item is consumed like so:
```php
public function onItemConsume(PlayerItemConsumeEvent $event){
        $player = $event->getPlayer();
        $item = $event->getItem();
        $this->getLogger()->info($player." consumed ".$item->getName()." with ".$player->getFood()." food");
    }
```
3. Look in console and you will see that the item is still consumed even if the player's food is 20:
```log
[19:07:07] [Server thread/INFO]: [ConsumeExample] Player(1) consumed Steak with 20 food
[19:07:07] [Server thread/INFO]: [ConsumeExample] Player(1) consumed Steak with 20 food
[19:07:08] [Server thread/INFO]: [ConsumeExample] Player(1) consumed Steak with 20 food
[19:07:09] [Server thread/INFO]: [ConsumeExample] Player(1) consumed Cooked Porkchop with 20 food
[19:07:10] [Server thread/INFO]: [ConsumeExample] Player(1) consumed Cooked Porkchop with 20 food
```

### OS and versions
* PocketMine-MP: 1.11.5
* PHP: 7.3
* Server OS: Windows 10
* Game version: Windows 10

### Plugins
None; using test server with DevTools enabled

### Crashdump, backtrace or other files
Example plugin to reproduce the bug:
```php
<?php

namespace Xenophilicy\ConsumeExample;

use pocketmine\plugin\PluginBase;
use pocketmine\event\Listener;
use pocketmine\event\player\PlayerItemConsumeEvent;

class ConsumeExample extends PluginBase implements Listener {

    public function onEnable(){
        $this->getServer()->getPluginManager()->registerEvents($this, $this);
    }

    public function onItemConsume(PlayerItemConsumeEvent $event){
        $player = $event->getPlayer();
        $item = $event->getItem();
        $this->getLogger()->info($player." consumed ".$item->getName()." with ".$player->getFood()." food");
    }
}
```

**Comment by Xenophilicy** [comment]
There is a small "hack" you can use to overcome this issue but that's beside the point. You can easily check if the player's food equals 20, then cancel it. 

For instance:
```php
public function onItemConsume(PlayerItemConsumeEvent $event){
    $player = $event->getPlayer();
    if($player->getFood() === 20){
        $event->setCancelled();
    }
    else{
        // run code for event here
    }
}
```

This does solve the issue but it would be better to fix the problem at the source rather than trying to fix it in every use case...

**Comment by lukeeey** [comment]
This is correct behavior because you can eat stuff like golden apples with full hunger and if your change were to be added then the event would not get fired for such foods

**Comment by Xenophilicy** [comment]
But should it happen for all food types?

**Comment by lukeeey** [comment]
Yes because a plugin may want to know when the player attempts to eat the food for some reason

**Comment by Xenophilicy** [comment]
So I would need to ignore the event if the food attribute is 20?

**Comment by lukeeey** [comment]
```php
if($player->getFood() === 20) {
    return;
}
// your code
```

**Comment by Xenophilicy** [comment]
Okay cool
