### ISSUE TITLE
Tall grass populator may crash the server at the height limit

### ISSUE THREAD

**Issue by dktapps** [pmmp/PocketMine-MP#3294]
### Issue description
Tall grass populator doesn't check world bounds. If it tries to grow on top of a block at y=255, the server will experience errors.

### OS and versions

* PocketMine-MP: 3.11.5, master
* PHP: 7.3.13

**Comment by dktapps** [comment]
As it turns out, the tall grass populator may not generate such structures because the generator won't place structures any higher than y=127. However, a crash may potentially still occur when using bonemeal on grass at y=255.

**Comment by jasonwynn10** [comment]
Is this still deemed a valid issue?

**Comment by DebHugo** [comment]
When we use bone meal on grass, bone meal can't produce double tall grass. So the bug describe in this issues is invalid

**Comment by dktapps** [comment]
> When we use bone meal on grass, bone meal can't produce double tall grass. So the bug describe in this issues is invalid

That's incorrect, you can try it yourself in vanilla

**Comment by DebHugo** [comment]
> That's incorrect, you can try it yourself in vanilla

In vanilla, bone meal can produce double tall grass but not in pocketmine

**Comment by dktapps** [comment]
Right, good point.
