### ISSUE TITLE
Button,Presure plates etc can be placed on another button

### ISSUE THREAD

**Issue by provsalt** [pmmp/PocketMine-MP#3299]
### Issue description

- Expected result: Button does not place
- Actual result: Button places snd look like this 
![Screenshot_2020-02-08-23-20-03-53_5c8300b655012b1930f2e0a7b81bf6a9](https://user-images.githubusercontent.com/39023494/74087787-89bb1100-4a87-11ea-87ac-b51f4d13f22c.png)

### Steps to reproduce the issue
1. Sneak
2. and then place a button on the button.
3. you will realize that you can place a button on that button

### OS and versions

* PocketMine-MP: 3.11.5
* PHP: 7.2
* Server OS: Linux, Ubuntu 18.04 LTS
* Game version: PE

### Plugins

Plugins (0):

### Crashdump, backtrace or other files

None

**Comment by dktapps** [comment]
yes, there's a TODO in the code.

**Comment by dktapps** [comment]
Relates to #4856, fixed by #4886
