### ISSUE TITLE
Incorrect exception message (Line 285, Class: Block)

### ISSUE THREAD

**Issue by TheBlackPlague** [pmmp/PocketMine-MP#3302]
## Description
The exception message at line 285 of `Block.php` should be corrected to "expected > 0" to accurately meet the condition.

## Justification
The condition for which this exception is thrown defines to be `<= 0`, meaning even `0` is considered [bad value]. The exception message states that the expected value was `>= 0`, meaning even `0` is expected. Hence, the contradiction.

**Comment by dktapps** [comment]
Given the vagueness, lack of version information or even a link to explain what you're talking about, I'm not going to waste my time on this. The only thing on Block.php line 285 is a closing brace.
