### ISSUE TITLE
Players don't see when an another has been moved since 1.14.3 Update

### ISSUE THREAD

**Issue by NxtUser-HD** [pmmp/PocketMine-MP#3304]
### Issue description

- Expected result: What were you expecting to happen?
- Actual result: What actually happened?

### Steps to reproduce the issue
1. Join Server with 2 accounts
2. Move

### OS and versions

* PocketMine-MP: 3.11.5
* PHP: 7.2
* Server OS: Debian 9
* MCPE-Version: 1.14.3

### Plugins

- If you remove all plugins, does the issue still occur?
- If the issue is **not** reproducible without plugins:
  - Have you asked for help on our forums before creating an issue?
  - Can you provide sample, *minimal* reproducing code for the issue? If so, paste it in the bottom section

**Comment by NxtUser-HD** [comment]
Players they are using 1.14.2 can see when an another Player has been moved

**Comment by dktapps** [comment]
This is a client issue, nothing to do here until we find out why.

**Comment by PetteriM1** [comment]
> This is a client issue, nothing to do here until we find out why.

You can look how they fixed it on Nukkit :)

**Comment by dktapps** [comment]
I know there is a workaround for it, you don't need to advertise it at me. I am just not applying the workaround until I find out why this problem occurred to start with.
