### ISSUE TITLE
You can drink buckets

### ISSUE THREAD

**Issue by Wumpotamus** [pmmp/PocketMine-MP#3306]
### Issue description
This is actually the problem I had in [this issue](https://github.com/pmmp/PocketMine-MP/issues/3291), I never noticed the bucket actually disappeared.
- Expected result: Not be able to drink buckets.
- Actual result: Drank a bucket.

### Steps to reproduce the issue
1. Get a water or lava bucket.
2. Go in survival.
3. Right click air with the bucket.
4. Potion sound effects and bucket is empty.
5. Profit!

### OS and versions

* PocketMine-MP: 3.11.4
* PHP: 7.3.13
* Server OS: Windows 10
* Game version: Win10

### Plugins

No plugins are needed

**Comment by dktapps** [comment]
it seriously took over two years for someone to notice this bug ???

**Comment by mote166** [comment]
i mean who would even think of drinking a lava bucket ?

**Comment by kenygamer** [comment]
@mote166 It comes to my attention to see that you would keep up my dead `pmmp-plugins` repository.

**Comment by Wumpotamus** [comment]
> 
> 
> @mote166 It comes to my attention to see that you would keep up my dead `pmmp-plugins` repository.

Please don't comment on this unless it regards the issue, thanks.
