### ISSUE TITLE
Frozen Players

### ISSUE THREAD

**Issue by ManiakMCPE** [pmmp/PocketMine-MP#3308]
Within the 1.14.3 update, players are completely frozen (client side). For players who are not updated, they can play normally. Players who are on 1.14.3 cannot see anyone moving.

**Comment by ManiakMCPE** [comment]
Sorry if this has already been patched, just want to make sure this fix can be in the next release.

**Comment by TwistedAsylumMC** [comment]
Duplicate of #3304

**Comment by ManiakMCPE** [comment]
Alright, sorry. I will close this issue now.
