### ISSUE TITLE
Slabs

### ISSUE THREAD

**Issue by bubbakadriu** [pmmp/PocketMine-MP#3313]
So when i walk from a grass block up a set of stairs made from slabs, i (and every other player) get some sort of lag back and glitch inside of the slabs causing them to fall through/under the stairs. Removing all plugins did not fix this and i have also used the test servers provided by my host and it occurs there also. My hosts conclusion to this issue was that it is a issue with pocketmine and told me to report it here.
- Bubba

**Comment by dktapps** [comment]
The issue is in the (deprecated) movement anti cheat, it's disabled by default. Ask your host to disable it.
