### ISSUE TITLE
I know that this is a duplicate...

### ISSUE THREAD

**Issue by minijaham** [pmmp/PocketMine-MP#3316]
Hey, I know that this is a duplicate of several previous issues on Player Movement Glitch, but I really, seriously need this issue to be fixed. Currently, I am hosting a server but players cannot see any players moving, but they can hear them hitting/moving/playing&breaking blocks. This has been a serious issue since the 1.14.20 update, and is negatively impacting the current server owners. Please please please fix the issue as soon as possible, and if there’s a workaround for it, please consider doing so and then look for the cause of this glitch. Thank you!

**Comment by CortexPE** [comment]
https://github.com/CortexPE/NonDrinkableAntiFreeze

click the poggit badge for a phar download, and close this issue xd

**Comment by minijaham** [comment]
I love you
