### ISSUE TITLE
Why was this needed?

### ISSUE THREAD

**Issue by ManiakMCPE** [pmmp/PocketMine-MP#3318]
Why was this necessary?
Removed raw NBT storage from Item internals. The following methods are now deprecated:
Item::setCompoundTag()

Please revert this change, NBT is needed for multiple plugins to work.

**Comment by lukeeey** [comment]
It’s deprecated, not removed. Plugins ideally shouldn’t depend on nbt anyway, which is where the master branch is headed

**Comment by dktapps** [comment]
You have no idea what you're talking about, please stop spamming issues.
