### ISSUE TITLE
Utils::getURL() and Utils::postURL() do not detect cURL errors

### ISSUE THREAD

**Issue by SalmonDE** [pmmp/PocketMine-MP#332]
### Issue description
if an error occurs with curl during Utils::getURL(), you can't see what the error is

### Steps to reproduce the issue
1. Use Utils::getURL() in a way which results into an error
2. Try to get the error from cURL (You can't)

### OS and versions
* PocketMine-MP: 2a4fb93a92e06ae25aeacf67e8a72d830675432d
* PHP: 7.0.13 x64
* Server OS: Windows 10

**Comment by SOF3** [comment]
Possible solution: Detect any errors in the getURL/postURL functions, throw an exception if `curl_error` returns `""`.

**Comment by dktapps** [comment]
You can only see that _something_ broke, right? by virtue of the fact that Utils::getURL() will return `false` if an error occurs.
