### ISSUE TITLE
Cocoa drop cocoa blocks

### ISSUE THREAD

**Issue by dadodasyra** [pmmp/PocketMine-MP#3326]
### Issue description

- Expected result: Cocoa drop nothing or cocoa beans
- Actual result: This drops the item of the block (an item normally nonexistent)

### Steps to reproduce the issue
1. Upload a map with cocoa beans or set cocoa beans with BuilderTools
2. Break cocoa beans
3. It drops many cocoa "blocks"(with a fairly ... special texture) with the name "Cocoa" and the id 127: 11

### OS and versions

* PocketMine-MP: 3.11.6
* PHP: 7
* Server OS: version 389 or v1.14.0 ?
* Game version: Win10 (delete as appropriate)

### Plugins

Don't need plugin go to BuilderTools if you don't go through a map

- If you remove all plugins, does the issue still occur?
Yes !

### Crashdump, backtrace or other files

Screenshot of the cocoa in the inventory : [here](https://cdn.discordapp.com/attachments/594278610659966976/681492613555159060/unknown.png)
I have a pack texture but it doesn't change the cocoa beans at all

**Comment by dktapps** [comment]
I blame @Intyre  for this. They are not fully implemented, only a stub class is present.

This bug doesn't appear on the master branch.

**Comment by dktapps** [comment]
If someone wants to make a PR for this feel free, but I don't plan to address it myself.
