### ISSUE TITLE
Server crash when collecting an item

### ISSUE THREAD

**Issue by Saehing** [pmmp/PocketMine-MP#3329]
gitcommit: 5c2ae0257c33076ad9dde94f6c2c1d4d1ffb0af9
pmmp: 4.0
crash: https://pastebin.com/wsT0yhsX

What should I do to reproduce the problem?
- Pick up a dropped item

Why is this happening?
- I suppose that's why: 10317527e4012fb1dbb1661f2f7fc33b05a7a6d1 and https://github.com/pmmp/PocketMine-MP/blob/04581e2700d6b5bc1285adc0f51f1463096cae70/src/pocketmine/inventory/BaseInventory.php#L254 https://github.com/pmmp/PocketMine-MP/blob/04581e2700d6b5bc1285adc0f51f1463096cae70/src/pocketmine/inventory/BaseInventory.php#L257

Alternative:
- https://pastebin.com/ab76F3T3

**Comment by dktapps** [comment]
fixed in 53067c26d78d629f9980ac3269edb72f7bc4878a
