### ISSUE TITLE
Allow a single world to have multiple provider layers

### ISSUE THREAD

**Issue by dktapps** [pmmp/PocketMine-MP#3332]
## Description
As per title, it should be possible to create a world which is served by multiple world providers.

## Justification
It's desirable, but currently impractical, to be able to store worlds in layers.

### Case study: Diff-based shared world storage
Consider a single world (prefab or pregenerated) which is used by many servers on the same machine. Every server gets its own copy of the world to play with. If the world is large, lots of disk space is wasted.

Being able to have multiple providers would solve this problem. A read-only world provider could be used to serve from the prefab, and then a second provider on top of this would store any modifications or differences from the original base world.

A real world example can be seen on LEET.CC, where a template world has to be copied to every server that uses it. In this system, the template world could be served as a base, and only changed chunks would need to be separately stored.

**Comment by jasonwynn10** [comment]
Possible use for dimensions?

**Comment by dktapps** [comment]
No, apples and oranges. Dimensions are effectively worlds within worlds, not the same thing.

**Comment by lukeeey** [comment]
Why not store dimensions how they are stored in vanilla bedrock?

**Comment by SOF3** [comment]
This somehow reminds me of the old MCPE world format which exactly stores chunks twice, the original version the first time, then user changes appended.

**Comment by dktapps** [comment]
again, this has nothing to do with dimensions.

**Comment by dktapps** [comment]
It's possible to write a custom WorldProvider which does this, so I don't think there's any need for something this specialized to be used in the core.
