### ISSUE TITLE
BlockUpdateEvent doesn't cancelled when block is "Water Block"

### ISSUE THREAD

**Issue by alvin0319** [pmmp/PocketMine-MP#3334]
### Issue description

- Expected result: What were you expecting to happen? BlockUpdateEvent does cancelled.
- Actual result: What actually happened? BlockUpdateEvent doesn't cancelled.

### Steps to reproduce the issue
1. Join the game.
2. Get water block with command "/give [playerName] 8 1"
3. Place the Water Block.

[Youtube Link](https://youtu.be/9xjC88MsGgs)

### OS and versions

* PocketMine-MP: https://github.com/pmmp/PocketMine-MP/commit/46ac4cbca146bac9245e6eb115a9e7335033ba4c
* PHP: 7.3.0
* Server OS: Windows10
* Game version: PE/Win10 (delete as appropriate)

### Plugins

```php
<?php
/**
 * @name DIsableBlockTIck
 * @author alvin0319
 * @main DisableBlockTick\DisableBlockTick
 * @version 1.0.0
 * @api 3.0.0
 */
declare(strict_types=1);
namespace DisableBlockTick;

use pocketmine\block\BlockIds;
use pocketmine\event\block\BlockUpdateEvent;
use pocketmine\event\Listener;
use pocketmine\plugin\PluginBase;

class DisableBlockTick extends PluginBase implements Listener{

	public function onEnable() : void{
		$this->getServer()->getPluginManager()->registerEvents($this, $this);
	}

	public function onBlockUpdate(BlockUpdateEvent $event){
		$block = $event->getBlock();

		if(in_array($block->getId(), [
			BlockIds::GRASS, BlockIds::WATER, BlockIds::STILL_WATER, BlockIds::FLOWING_WATER
		])){
			$event->setCancelled();
			$this->getLogger()->info("Cancelled Block Update: " . $block);
		}
	}
}
```

- If you remove all plugins, does the issue still occur?
- If the issue is **not** reproducible without plugins:
  - Have you asked for help on our forums before creating an issue?
  - Can you provide sample, *minimal* reproducing code for the issue? If so, paste it in the bottom section

**Comment by matcracker** [comment]
You need to use BlockSpreadEvent.

**Comment by alvin0319** [comment]
but it works on 4.0.0

**Comment by dktapps** [comment]
This is because of a behavioural change in the internals. It wasn't backported due to potential disruption to functionality.

You should use BlockSpreadEvent as suggested above.
