### ISSUE TITLE
Return value of pocketmine\player\Player::getNetworkSession() must be an instance of pocketmine\network\mcpe\NetworkSession, null returned

### ISSUE THREAD

**Issue by AndreasHGK** [pmmp/PocketMine-MP#3336]
Link to crashdump: 
https://pastebin.com/wrB1BKZn

### Additional comments (optional)

I am using pocketmine 4.0.0 from this commit https://github.com/pmmp/PocketMine-MP/commit/2ca10bf84b62838dada79214e3fe17377af84d2c

The issue occurs regularly on the server and I don't know what causes this other than that its when someone leaves the server.

**Comment by dktapps** [comment]
how long has this been occurring?

**Comment by AndreasHGK** [comment]
The first time this happened was february the 23rd. A similar crash sometimes also happens when doing /kick

**Comment by dktapps** [comment]
do you have any plugins that use `Entity->spawnTo()`?

**Comment by AndreasHGK** [comment]
No, I don't.

**Comment by dktapps** [comment]
The only way this bug can occur is if the player was considered as a viewer by an entity that the player was unaware of and therefore didn't remove itself from on disconnect. A common cause of such issues is plugins abusing `spawnTo()`, but if that isn't the case here, we have some more sinister bug in the mix.

**Comment by AndreasHGK** [comment]
I checked, because i still get this error from time to time, and that does not seem to be the case.
![image](https://user-images.githubusercontent.com/36563463/101969601-7b98cc80-3c25-11eb-95a7-c19dcaa471bc.png)
Here you can see all the code occurances. The first and second one both arent actually in the production server rn, the last 2 ones werent there when i submitted this report but they are now of course. However I do not think they abuse spawnToAll() as this gets called only once on mob spawn.

**Comment by AndreasHGK** [comment]
https://pastebin.com/NDridQRL here is another crashdump since the old one expired, this might be in different circumstances but such thing still does occur here. Yes, I am using a modified player class but that should not affect the networkSession in any way, in fact this occured before i had a modified player class anyway.
I currently do not know how to reproduce this as it seems to happen seemingly at random.

**Comment by dktapps** [comment]
I don't have enough information to investigate this problem. Given the fact you have a variety of private plugins whose code I can't review, it's likely that this problem is caused by something your plugins are doing, because I've never seen this problem appear in the wild.
