### ISSUE TITLE
Inventory not fully cleaned using clearAll()

### ISSUE THREAD

**Issue by HerryYT** [pmmp/PocketMine-MP#3340]
### Issue description

- Expected result: All inventory empty
- Actual result: Slot in hand (i think, i was using the first hotbar slot in my case) keeps old item

### Steps to reproduce the issue
1. Make a plugin that gives you a item (test with wooden sword in hand, better if you give one different for each slot), then teleports you in another world and then clear inventory with clearAll()
2. You see the other slots cleaned but the first one in hand no

### OS and versions

* PocketMine-MP: 3.11.6
* PHP: 7.3
* Server OS: Windows
* Game version: Win10 

### Plugins

Just the private core that does the same as i wrote ahead

- If you remove all plugins, does the issue still occur? cannot reproduce a clearAll() without plugins
- If the issue is **not** reproducible without plugins:
  - Have you asked for help on our forums before creating an issue? no
  - Can you provide sample, *minimal* reproducing code for the issue? If so, paste it in the bottom section

**Comment by Kjenium** [comment]
I also have the same problem

**Comment by dktapps** [comment]
once again, if you have nothing better to say than "me too", please just shut up, or give the issue a thumbsup if you must... commenting like this pollutes everyone's notifications for no good reason

**Comment by TheNewHEROBRINEX** [comment]
This bug happens if you clear the inventory in EntityDamageByEntityEvent and I think it is because the server sends the item again to update its meta: https://github.com/pmmp/PocketMine-MP/blob/stable/src/pocketmine/Player.php#L2567-L2572

**Comment by dktapps** [comment]
thanks for the insight. I would surmise that this issue is in the same lane as #2010.
