### ISSUE TITLE
Enchantment not working

### ISSUE THREAD

**Issue by minijaham** [pmmp/PocketMine-MP#3341]
### Issue: enchantments such as looting does not work.

- Expected result: Was supposed to work, according to the code(enchantments)
- Actual result: Did not work, cannot enchant through the command, nor other plugins. But other enchantments works though. Just looting.

### Steps to reproduce the issue
1. Hold an item
2. Do /enchant (name) looting(or it’s id)

### OS and versions

* PocketMine-MP: 3.11.6
* PHP: 7.3
* Server OS: Windows
* Game version: PE/Win10 

### Plugins

- Still occurs with/without plugins
- If the issue is **not** reproducible without plugins:
  - Have you asked for help on our forums before creating an issue? - No, not Yet

**Comment by dktapps** [comment]
It's not implemented yet.
