### ISSUE TITLE
Inventory item drop bug with creative mode

### ISSUE THREAD

**Issue by b1zey** [pmmp/PocketMine-MP#3342]
Hello, i have a bug with dropping item when player have a creative mode.
**Steps to reproduce:**
1) Give player gamemode 1.
2) Open inventory and give you some item.
3) Drop this item into outside the inventory (as you dropping item in the classic type of interface).
I check this bug into classic type of UI, i dont known if it works with pocket-interface type.

In console i have a message:
![image](https://user-images.githubusercontent.com/30533957/75917715-7a06d080-5e6b-11ea-86c8-ed60c16e8215.png)

I think the reason of this bug it is returning null.
![image](https://user-images.githubusercontent.com/30533957/75917827-acb0c900-5e6b-11ea-89d5-41389a650587.png)

Version of MCBE: 1.14.30

**Comment by dktapps** [comment]
It's not a bug, just the network system filtering out some garbage.
