### ISSUE TITLE
I can't load my world

### ISSUE THREAD

**Issue by reidperrett** [pmmp/PocketMine-MP#3346]
Well whenever I try to load a world onto a pocketmine server it says this ": Specified LevelDB world format version (8) is not supported" but when I asked my server host they said it was a bug and to report it to you guys.

Well I hope that it gets fixed because I want to upload my world onto a server where I can use plugins.

### Steps to reproduce the issue
1. You try loading a world onto a pocketmine server(I used apex hosting)
2.Look at the console

### OS and versions

* PocketMine-MP:3.11.6 for Minecraft: 
* PHP:
* Server OS:
* Game version: Bedrock Edition v1.14.0

### Plugins

09.03 02:11:07 [Server] Server thread/INFO Plugins (0):

**Comment by dktapps** [comment]
it's not a bug, the error message tells you all you need to know ...
