### ISSUE TITLE
RakLib Thread Error after recent update: Android

### ISSUE THREAD

**Issue by AthasGames** [pmmp/PocketMine-MP#3352]
Upon startup, the server loads normally, then instantly crashes and shuts down.

Re-installing the previous version of the app seems to clear the issue.

It registers the error in the source code of the Pocketmine-MP.phar file, which cannot be opened properly on an Android device, and I do not have the time to go digging on my PC for the error.

**Comment by TwistedAsylumMC** [comment]
The PocketMine app is not official and you will not receive any help for it on here.

**Comment by dktapps** [comment]
If you don't have time to provide any actual error information, I don't have time to help you. Besides, we don't have any app.
