### ISSUE TITLE
Missing blocks

### ISSUE THREAD

**Issue by Spaldam** [pmmp/PocketMine-MP#336]
### Issue description
When placing a beacon on top of a pyramid stack of diamond blocks that are on top of bedrock, directly underneath the spawn point, it almost instantly disappears.

### Steps to reproduce the issue
I placed the diamond blocks onto of the bedrock at the bottom of the world map right under the spawn point.  I'm logged in as the administrator so I can break blocks in the spawn area, even though it's setup to not allow this. Everything is working as expected until I try to place the beacon.

### OS and versions
* PocketMine-MP: 1.6.2dev "Unleashed" (API 3.0.0-ALPHA3)
* PHP: 7.0
* Server OS: Ubuntu 16.04.01 - Linux Spaldam 4.4.0-31-generic #50-Ubuntu SMP Wed Jul 13 00:07:12 UTC 2016 x86_64 x86_64 x86_64 GNU/Linux
* Game version: PE 1.0.2 MCPE on Android Nugget 7.0

### Crashdump, backtrace or other files
https://youtu.be/2Gpp3ND1asA

**Comment by robske110** [comment]
Beacons are not implemented yet.

**Comment by AppleDevelops** [comment]
Beacons are added as blocks, but in order to work properly, there has to be beacon tiles as well.

**Comment by jasonwynn10** [comment]
that doesn't really explain the disappearance though

**Comment by AppleDevelops** [comment]
Oops didn't read the issue lol

**Comment by Spaldam** [comment]
I'm noticing it happening with other blocks as well when placed in the spawn area. Such as coldrins. Maybe it's an issue with how the spawn protection is setup, some blocks aren't being allowed to be placed by an admin?

**Comment by KnownUnown** [comment]
There also are other blocks such as cauldrons which aren't implemented yet. A short (probably not exhaustive) list of everything that doesn't work is redstone-related blocks, cauldrons, beacons, brewing, and minecart and rail related things.

**Comment by infinity-pe** [comment]
Why are Purpur Blocks, Elytra and Prismarine missing?

**Comment by Sandertv** [comment]
Because @dktapps is working on a better way to implement blocks, and it would be a waste of time to add them using the current way.

**Comment by infinity-pe** [comment]
When will @dktapps add the better way? Soon?

**Comment by infinity-pe** [comment]
I really hope PMMP will add the missing things/blocks soon. I need them for my server and shops!

**Comment by eternalharvest** [comment]
I found that IronDoor can be opened by hand.

There is `IronDoor` class in the PMMP code-base.
But, It seems the behaviour is not fully implemented yet.
IronTrapDoor may have same issue though i'm not tested yet.

Is it because redstone-related problem?
Please tell me whether if I should create new issue or not.

**Comment by dktapps** [comment]
Redstone is not implemented yet, but iron doors and trapdoors were available in PocketMine long before 0.12. shoghicp added them and made them openable as a fancy feature.

**Comment by eternalharvest** [comment]
Ok, I understand. thank you.
