### ISSUE TITLE
Creative Items

### ISSUE THREAD

**Issue by Kymchi-77** [pmmp/PocketMine-MP#3369]
I have PocketMine for my server but certain items e.g. elytra, observer, do not show in the creative and was also wondering if you might be able to update the 3.11.17 with the new honey featured items such as honeycmobs and Bee-hives for they ar enot in the game with the mod. I think this just adds to the overall use of the mod and the availability of the items.

**Comment by dktapps** [comment]
no, that won't be possible, and even if it were, patch versions are reserved for bug fixes, not feature additions.
