### ISSUE TITLE
onInteract repeats on Win10

### ISSUE THREAD

**Issue by ethaniccc** [pmmp/PocketMine-MP#3370]
### Issue description
When looking at a block and interacting with a plugin that uses onInteract, the function is repeated when right clicked.
- Expected result: What were you expecting to happen?
For the event to happen once, just like on mobile devices.
- Actual result: What actually happened?
The event repeated itself.

### Steps to reproduce the issue
1. Make a plugin that uses onInteract, for example the following:
`public function onInteract(PlayerInteractEvent $event){
   $player = $event->getPlayer();
   $in = $event->getPlayer()->getInventory()->getItemInHand()->getCustomName();
   if($in == "Test"){
      $player->sendMessage("Hi);
   }
}`

2. Go in-game and while staring at a block, interact with the item on Win10 by right clicking the item with the custom name

3. Try multiple times (if needed) until you get more than one output.

### OS and versions

* PocketMine-MP: 3.11.6
* PHP: 7.2
* Server OS: Windows 10
* Game version: PE/Win10 (delete as appropriate)

### Plugins

CombatLogger v0.0.6, SimpleNickCommand v1, MultiWorld v1.5.2, BuilderTools v1.2.0-beta2, AlwaysSpawn v2.2.4, Mavoric v1.0.4, DevTools v1.13.5, Bot v1.0.0, PurePerms v1.4.3, VanishV2 v1.5, SkylineKitPvP v1.0.0, StaffMode v1, AltFinder v1
- If you remove all plugins, does the issue still occur?
A: Cannot be reproduced without plugins.
- If the issue is **not** reproducible without plugins:
  - Have you asked for help on our forums before creating an issue?
   A: No
  - Can you provide sample, *minimal* reproducing code for the issue? If so, paste it in the bottom section
A: Look above in reproduction steps.

**Comment by dktapps** [comment]
This is a client sided bug which has already been worked around. If the existing workaround doesn't work, there's nothing more I can do that won't break other functionality.

**Comment by ethaniccc** [comment]
Something I noticed: The glitch/bug doesn't occur when the Win10 player interacts with the item while looking into the air
