### ISSUE TITLE
Dos with InventoryTranasctionPacket

### ISSUE THREAD

**Issue by vujonycoder** [pmmp/PocketMine-MP#3373]
### Dos with InventoryTranasctionPacket

- Expected result: Works fine
- Actual result: Too much "Unhandled InventoryTransactionPacket received from not_a_bot: HgMApgIBAKAEghD//wEKAAMGRGFtYWdlCAAAAN/iSERij7RB+t0QxAAAAAAAAAAAAAAAAA==" in debug-mode. The server falls asleep for a while (about 10 seconds). Then wakes up. And all in loop until the bot-attack stops
 
### Steps to reproduce the issue
1. Write your own client.
2. Send too much InventoryTransactionPacket with buffer like this "HgMApgIBAKAEghD//wEKAAMGRGFtYWdlCAAAAN/iSERij7RB+t0QxAAAAAAAAAAAAAAAAA=="

### OS and versions
* PocketMine-MP: PocketMine-MP 3.11.6
* PHP: PHP 7.2.9 (cli) (built: Sep 26 2018 16:34:49) ( ZTS )
* Server OS: Debian GNU/Linux 8.11
### Plugins

Plugins do not affect

### Crashdump, backtrace or other files

**Comment by dktapps** [comment]
I'm impressed. You missed two warnings not to post security issues on a public issue tracker.
> Please DO NOT report security vulnerabilities here. Instead, send an email to team@pmmp.io or contact a developer directly, IN PRIVATE.

**Comment by vujonycoder** [comment]
It's very fast method to fix.

**Comment by vujonycoder** [comment]
You don't fix that?

вт, 24 мар. 2020 г. в 02:40, Dylan T. <notifications@github.com>:

**Comment by ZizzyZizzy** [comment]
Of course they do. The point is not to let THE ENTIRE WORLD know about security issues before the devs have a chance to fix them.

Slow down. READ. Use common sense.

**Comment by vujonycoder** [comment]
Sorry, my server don’t work, because he on attack.

вт, 24 марта 2020 г. в 02:51, ZizzyZizzy <notifications@github.com>:
