### ISSUE TITLE
When the arguments are too long, there is no more argument

### ISSUE THREAD

**Issue by BaleineSanguine** [pmmp/PocketMine-MP#3374]
### Issue description

- Expected result: Get the arguments (see bottom)
- Actual result: Got nothing (see bottom)

### Steps to reproduce the issue
1. Type a command and put a very loooong argumen

### OS and versions

* PocketMine-MP: 3.11.6
* PHP: 7
* Server OS: Windows
* Game version: PE

### Plugins

- If you remove all plugins, does the issue still occur?
- If the issue is **not** reproducible without plugins: No
  - Have you asked for help on our forums before creating an issue? No
  - Can you provide sample, *minimal* reproducing code for the issue? If so, paste it in the bottom section. Yes

### Crashdump, backtrace or other files

```Php
public function onCommand(CommandSender $sender, Command $command, string $label, array $args) : bool{
		switch($command->getName()){
			case "bounty":
				if (isset($args[0])) {
					$args[0] = strtolower($args[0]);
				}
				if (count($args) !== 2) {
					echo count($args) . "\n";
					$sender->sendMessage("Invalid arguments!");
					return false;
```

When I enter a little bit of args :
```
bounty BaleineSanguine 500
```
The code continues
But when I enter more :
```
bounty BaleineSanguine 5000000
[15:53:43] [Server thread/INFO]: Invalid arguments!
[15:53:43] [Server thread/INFO]: Erreur!
[15:53:43] [Server thread/INFO]: Usage: /bounty <player> <amount>
```
And no numer is outputted wich should be 2.

**Comment by lukeeey** [comment]
Don't use `echo`....

**Comment by kenygamer** [comment]
@BaleineSanguine `echo` gave you the answer, your doing `/bounty bounty BaleineSanguine 5000000` and it is `/bounty BaleineSanguine 5000000`. Your code isn't wrong. The command syntax is.
