### ISSUE TITLE
Windows pre-built PHP 7.3.8 binaries missing xmlwriter - "composer install" fails

### ISSUE THREAD

**Issue by ZizzyZizzy** [pmmp/PocketMine-MP#3375]
### Issue description
A fresh Windows install of stable build **dfe68c9** fails at the "composer install" stage due to missing xmlwriter extension in the Windows PHP 7.3.8 pre-built download.

### Steps to reproduce the issue

- git clone --recursive https://github.com/pmmp/PocketMine-MP.git
-  download https://jenkins.pmmp.io/job/PHP-7.3-Aggregate/lastSuccessfulBuild/artifact/PHP-7.3-Windows-x64.zip
- Extract pre-built Windows PHP zip to PocketMine-MP/bin/
- cd PocketMine-MP
- bin\php\php.exe bin\composer.phar install

>  Problem 1
>     - Installation request for irstea/phpunit-shim 8.5.2 -> satisfiable by irstea/phpunit-shim[8.5.2].
>     - irstea/phpunit-shim 8.5.2 requires ext-xmlwriter * -> the requested PHP extension xmlwriter is missing from your system.

### OS and versions
* PocketMine-MP: stable build dfe68c9
* PHP: Pre-compiled download from here:
https://jenkins.pmmp.io/job/PHP-7.3-Aggregate/lastSuccessfulBuild/artifact/PHP-7.3-Windows-x64.zip
* Server OS: Windows 10
Microsoft Windows [Version 10.0.17134.1365]
* Game version: N/A

### Crashdump, backtrace or other files
```
PocketMine-MP>bin\php\php.exe -version
PHP 7.3.8 (cli) (built: Aug 16 2019 11:30:39) ( ZTS MSVC15 (Visual C++ 2017) x64 )
Copyright (c) 1997-2018 The PHP Group
Zend Engine v3.3.8, Copyright (c) 1998-2018 Zend Technologies

PocketMine-MP>bin\php\php.exe -m | find "xml"
libxml
xml
```

### Work-around
Nuke all references to **phpunit-shim** in composer.json, composer.lock and phpstan.neon.dist

**Comment by dktapps** [comment]
The latest version on Jenkins is 7.3.14, not 7.3.8. You're ages out of date.

**Comment by ZizzyZizzy** [comment]
Bahh, what is this sourcery?

I used link to "Prebuilt binaries" on this page:
https://github.com/pmmp/PocketMine-MP/blob/stable/BUILDING.md

Which goes to:
https://jenkins.pmmp.io/job/PHP-7.3-Aggregate

That page shows the latest build as 12 from Feb, not 13 from March.

This link:
https://jenkins.pmmp.io/job/PHP-7.3-Aggregate/lastSuccessfulBuild/artifact/

Also goes straight to build 12 instead of 13

Something on Jenkins is broken or mislabeled. Those links should both take you to the actual latest build 13. The only way I could find to even show build 13 is to go to this link:
https://jenkins.pmmp.io/

and THEN click on the link for PHP-7.3-Aggregate:
https://jenkins.pmmp.io/job/PHP-7.3-Linux-x86_64/

**Comment by dktapps** [comment]
It's right there where you're looking. I don't know where you got your original build from, but it's very outdated.

**Comment by sewek333** [comment]
php 7.3 link did not work
