### ISSUE TITLE
Missing item lantern. Once created unable to put on

### ISSUE THREAD

**Issue by CryptoBeginner** [pmmp/PocketMine-MP#3387]
### Issue description

- Expected result: Unable to find lantern
- Actual result: Lantern was manually created but does not apply (cannot put on)

### Steps to reproduce the issue
1. ... Missing Item on creative
2. ... Unable to use

### OS and versions

* PocketMine-MP: PocketMine-MP version 3.11.6
* PHP: 7+
* Server OS: Ubuntu
* Game version: PE/Win10 

### Plugins
Clean install no plugin

### Crashdump, backtrace or other files
In game not working.

**Comment by dktapps** [comment]
Lanterns aren't implemented.
