### ISSUE TITLE
No block API for handling left-clicks

### ISSUE THREAD

**Issue by dktapps** [pmmp/PocketMine-MP#339]
### Issue description
ItemFrameDropItemPacket is _only_ supposed to be used for dropping the item, just like DropItemPacket is _only_ used for players throwing items away, _not_ for removing items from the inventory. The item removal should be handled on item-frame left-click, but there is no API to do this currently. This causes issues in creative, since before 1.0, clients used to send ItemFrameDropItemPacket with an Air item in creative, but now they don't send anything, which means that item removal cannot be detected in creative with the current implementation.

### Steps to reproduce the issue

1. place an item frame
2. stick an item in it
3. try to remove the item in creative
4. interact with item frame, item reappears

### OS and versions

* PocketMine-MP: 595fffc
* PHP: 7.0.15
* Server OS: Windows 10
* Game version: PE/Win10

**Comment by dktapps** [comment]
Seems the item frame issue is indeed a client bug. Reference: https://bugs.mojang.com/browse/MCPE-20070

**Comment by dktapps** [comment]
The item frames issue has been fixed in 1.0.4.1 beta.

**Comment by Muqsit** [comment]
#someoneForgotToCloseThisIssue

**Comment by dktapps** [comment]
> No block API for handling left-clicks

This hasn't been resolved. Mojang just fixed their old hack.

**Comment by thebigsmileXD** [comment]
Note @#1488
