### ISSUE TITLE
Cobblestone generators breaks down after a while

### ISSUE THREAD

**Issue by Eren5960** [pmmp/PocketMine-MP#3390]
### Issue description
- Cobblestone generators breaks down after a while

### Steps to reproduce the issue
1. Make a cobblestone generator [Like](https://cdn.discordapp.com/attachments/480650036972224513/695299077734137937/unknown.png)
2. Start to break it ... after [see](https://cdn.discordapp.com/attachments/480650036972224513/695299579481948220/unknown.png)

### OS and versions

* PocketMine-MP: ` 4.0.0+dev for Minecraft: Bedrock Edition v1.14.0 (protocol version 389`
* PHP: 7.3
* Server OS: Windows 10
* Game version: PE & Win10 

### Plugins

no plugins

**Comment by junxiesky** [comment]
Did you install the red stone?

**Comment by IceCruelStuff** [comment]
> Did you install the red stone?

Cobblestone generators don't need redstone

**Comment by junxiesky** [comment]
> > Did you install the red stone?
> 
> Cobblestone generators don't need redstone

This Redstone plugin will cause the cobblestone generator to not work 
https://poggit.pmmp.io/ci/tedo0627/RedstoneCircuit_PMMP-Plugin/RedstoneCircuit

**Comment by junxiesky** [comment]
> > Did you install the red stone?
> 
> Cobblestone generators don't need redstone

This Redstone plug-in will cause the cobblestone generator to stop working after working for a while 
https://poggit.pmmp.io/ci/tedo0627/RedstoneCircuit_PMMP-Plugin/RedstoneCircuit

**Comment by IceCruelStuff** [comment]
> > > Did you install the red stone?
> > 
> > 
> > Cobblestone generators don't need redstone
> 
> This Redstone plug-in will cause the cobblestone generator to stop working after working for a while
> https://poggit.pmmp.io/ci/tedo0627/RedstoneCircuit_PMMP-Plugin/RedstoneCircuit
It says no plugins

**Comment by junxiesky** [comment]
> > > > 您安装了红色石头吗？
> > > 
> > > 
> > > 鹅卵石发生器不需要红石
> > 
> > 
> > 此Redstone插件会在工作一段时间后使鹅卵石生成器停止工作
> > https://poggit.pmmp.io/ci/tedo0627/RedstoneCircuit_PMMP-Plugin/RedstoneCircuit
> 
> 它说没有插件
> 
> > 没有插件

oh....okay
