### ISSUE TITLE
Build to phar

### ISSUE THREAD

**Issue by PechenkaPM** [pmmp/PocketMine-MP#3391]
* PocketMine-MP: last(was cloned 10 minuted ago)
* PHP: 7.3(https://dev.azure.com/pocketmine/PHP-Builds/_build/results?buildId=157&view=artifacts&type=publishedArtifacts)
* Server OS: Ubuntu 18.04

Can't pack in phar, i catch error.

To install, I used:
1. git clone --branch=master --recursive https://github.com/pmmp/PocketMine-MP.git
2. Install bin PHP7.3 from https://dev.azure.com/pocketmine/PHP-Builds/_build/results?buildId=157&view=artifacts&type=publishedArtifacts
3. Install composer from https://getcomposer.org/composer.phar
4. sudo bin/php7/bin/php composer.phar install
5. sudo bin/php7/bin/php build/server-phar.php
6. Catch error

![image](https://user-images.githubusercontent.com/47981825/78456685-cd0fb580-76ad-11ea-9ed1-00ba1f679d66.png)
![image](https://user-images.githubusercontent.com/47981825/78456680-c2edb700-76ad-11ea-81cd-82c84557ada8.png)
![image](https://user-images.githubusercontent.com/47981825/78456586-4955c900-76ad-11ea-97dc-5078fa123416.png)

**Comment by yoraze** [comment]
Try this and close this issue:
`php -dphar.readonly=0 build/server-phar.php`

**Comment by PechenkaPM** [comment]
![image](https://user-images.githubusercontent.com/47981825/78500691-abbbd180-7760-11ea-9f60-fe34abff64dc.png)
