### ISSUE TITLE
--disable-readline command-line option does not work

### ISSUE THREAD

**Issue by dktapps** [pmmp/PocketMine-MP#34]
### Issue description
`readline` cannot be disabled with `--disable-readline` if the extension is present.

### Steps to reproduce the issue

1. Run a server on a Linux box with `readline` PHP extension, with `--disable-readline` option.

### OS and versions

* PocketMine-MP: https://github.com/pmmp/PocketMine-MP/commit/d53810c6bc5676233cf85cfe3abc15dea3c8482a
* PHP: 7.0.10 with readline extension
* Server OS: Any Linux distro
* Game version: irrelevant

**Comment by legoboy0215** [comment]
Off-topic: Why would you want to disable readline? Or is there no particular reason?

**Comment by dktapps** [comment]
We initially discovered this issue in Travis with a spam of > > > > >

**Comment by SOF3** [comment]
Clarification: `--disable-readline` is to disable use of the extension readline's function [`readline()`](//php.net/manual/en/function.readline.php), not to disable stdin.

**Comment by legoboy0215** [comment]
Oh ok.
