### ISSUE TITLE
Critical: [network] getSpawn () - help

### ISSUE THREAD

**Issue by Pyszko** [pmmp/PocketMine-MP#340]
Hello :)
I know, this is not place to help, but you must help me :/

When i have error:
[Server thread/CRITICAL]: [Network] Stopped interface pocketmine\network\RakLibInterface due to Call to a member function getSpawn() on null

Can make auto restart server? I use linux :)
In start.sh i set loop to "yes", but auto restart work when server go off.

I use one plugin, and sometimes get this critical error...
If you help me i be really happy :D 

Regards.

**Comment by jasonwynn10** [comment]
I recommend asking the forums

**Comment by dktapps** [comment]
^

If you have an issue, be sure to fill out the template next time. Thank you.
