### ISSUE TITLE
getEnchantment() bug in pocketmine/item/enchantment/Enchantment.php

### ISSUE THREAD

**Issue by TungstenVn** [pmmp/PocketMine-MP#3400]
### Issue description

- Expected result: It will return an enchantment
- Actual result: code bug

### Steps to reproduce the issue
1. Use this code : $ench = Enchantment::getEnchantment($id);
2. And it throw a error "getSize() on array"
the old version dont get that error
- Old version: https://github.com/pmmp/PocketMine-MP/blob/3.11.0/src/pocketmine/item/enchantment/Enchantment.php#L158
- Newest version: https://github.com/pmmp/PocketMine-MP/blob/stable/src/pocketmine/item/enchantment/Enchantment.php#L154

### OS and versions

* PocketMine-MP: 3.11.6 (newest)
* PHP: 7.3
* Server OS: Window 10
* Game version: PE/Win10

### Plugin
Still happen without any plugin, using default command /enchant still get that bug

**Comment by dktapps** [comment]
Don't expect to get help when you provide verifiably false information. This issue is caused by a plugin.
