### ISSUE TITLE
Crouched Players Can't Place Certain Items

### ISSUE THREAD

**Issue by HyperFlareMC** [pmmp/PocketMine-MP#3401]
### Issue description
When players are crouched, they can't interact with certain items. For example, using fence gates, doors, placing water, and picking up water.
- Expected result: We are expecting it to be able to open and close these doors, and place/retrieve liquid with buckets.
- Actual result: Expected action gets reverted.

### Steps to reproduce the issue
1. Crouch and stay crouched,
2. Attempt to interact with doors and liquid items.

### OS and versions

* PocketMine-MP: 3.11.7
* PHP: PHP 7.2.24-0ubuntu0.18.04.3 (cli) (built: Feb 11 2020 15:55:52) ( NTS )
* Server OS: ubuntu18.04
* Game version: PE/Win10 

### Plugins

None.
- If you remove all plugins, does the issue still occur?
Yes.

- If the issue is **not** reproducible without plugins:
  - Have you asked for help on our forums before creating an issue?
  - Can you provide sample, *minimal* reproducing code for the issue? If so, paste it in the bottom section

**Comment by HimbeersaftLP** [comment]
Not being able to use doors while crouching is normal vanilla behaviour, it's so you can place signs and stuff on doors.

**Comment by dktapps** [comment]
see also: #1904

This is an old issue which hasn't become priority for a while. If someone else would like to take the time to fix it, please consider making a PR.
