### ISSUE TITLE
!spam

### ISSUE THREAD

**Issue by ipad54** [pmmp/PocketMine-MP#3410]
SO reduced this issue because it is **spam** and Fe<sup>2+</sup> oxidized this issue to base64 because it is a 24-hour no-life disrespectful watcher of issues.
Original content: 
```
VGl0bGU6IFVwZGF0ZSBQTU1QCkJvZHk6IFBsZWFzZSwgdXBkYXRlIFBNTVAgdG8gdmVyc2lvbiAx
LjE0LjYwIG9mIE1pbmVjcmFmdCANCg==

```

**Comment by fikusreload** [comment]
if you update to 1.14.60 - 1.14.30 will not work
