### ISSUE TITLE
!spam

### ISSUE THREAD

**Issue by leopoldo321** [pmmp/PocketMine-MP#3417]
SO reduced this issue because it is **spam** and Fe<sup>2+</sup> oxidized this issue to base64 because it is a 24-hour no-life disrespectful watcher of issues.
Original content: 
```
VGl0bGU6IHdoZW4gd2lsbCBpdCBiZSBhdmFpbGFibGUgZm9yIHZlcnNpb24gMS4xNC42PwpCb2R5
OiBIZWxsbywgSSBob3BlIHlvdSBhcmUgd2VsbCwgbXkgcXVlc3Rpb24gaXMgd2hlbiB3aWxsIGl0
IGJlIGF2YWlsYWJsZSBmb3IgdmVyc2lvbiAxLjE0LjYNCmhhdmUgYSBuaWNlIGRheSBoaXMgd29y
ayBpcyBhbWF6aW5n

```

**Comment by xZeroMCPE** [comment]
#3412

**Comment by Taylarity** [comment]
Just wait for it, watch this repo for update notification or simply join the official Discord server.
Hopefully it will be available in a few days.
