### ISSUE TITLE
No Supported Plug-ins

### ISSUE THREAD

**Issue by DarkLord063** [pmmp/PocketMine-MP#3424]
Please update of Plug-ins, the are telling me they are not supported, this is for Minecraft 1.14.60

**Comment by AGTHARN** [comment]
**Facepalm**

**Comment by Taylarity** [comment]
Updating plugins and make them compatible is not PocketMine's responsibility. Please contact plugin developers to have them updated.

**Comment by DarkLord063** [comment]
Oh ok

**Comment by jasonwynn10** [comment]
Yeah, its not really up to pocketmine to keep all the plugins made by other people updated, please close this issue and ask the other developers on the forums or in discord 👍
