### ISSUE TITLE
Signs go blank after typing

### ISSUE THREAD

**Issue by madecode15** [pmmp/PocketMine-MP#343]
### Issue description
Signs sometimes go blank after typing text. This is a extremely old PocketMine bug since MCPE 0.10.5.

### Steps to reproduce the issue
1. Place sign
2. Type
3. It will go blank upon finishing.

Note: I mostly get this if I make a lot of edits with backspacing, re-typing, and changing lines.

### OS and versions
* PocketMine-MP: https://github.com/pmmp/PocketMine-MP/commit/f5e39ea9ad54a4bd501b8594524124303e424bae
* PHP: 7
* Server OS: Mac
* Game version: PE

### Crashdump, backtrace or other files

* ...

**Comment by dktapps** [comment]
Have you actually tested this? A similar bug was fixed months ago.

**Comment by jasonwynn10** [comment]
I think this is due to a slow connection. The longer it takes to set the text, the higher the chance of it going blank

**Comment by madecode15** [comment]
@dktapps I got this yesterday on the latest build.

**Comment by dktapps** [comment]
I haven't been able to reproduce it since September.

**Comment by madecode15** [comment]
@jasonwynn10 Slow connection should have nothing to do it, raklib makes sure packets are sent reliably. If packet loss occurs raklib will send the packet again, and if your connection is really slow you will timeout.

**Comment by robske110** [comment]
I have tried to reproduce this, but I really really can't.
It would be if you can
1) record a video of mcpe showing the disappearing text.
2) Throw this  [PacketLogger.php.zip](https://github.com/pmmp/PocketMine-MP/files/768279/PacketLogger.php.zip) plugin into your /plugins/ folder and send us the file it generated, when you have reproduced this bug.

![file_0](https://cloud.githubusercontent.com/assets/16020100/22852268/c66ffe3c-f038-11e6-8b90-c398a8b17464.jpg)

**Comment by jarne** [comment]
@jasonwynn10 @madecode15 I also had this problem sometimes when the server was really overloaded

**Comment by Apqu** [comment]
I have seen this a few times but only when I have some plugins installed, I think it could be a plugin causing this rather than vanilla PMMP

**Comment by robske110** [comment]
Again, if you can reproduce it at an somewhat acceptable rate, please follow the steps i outlined in my last post.

**Comment by madecode15** [comment]
Will close for now, I'll try to get a video recording of it.

**Comment by remotevase** [comment]
This is definitely a problem, although I cannot get a recording, it is definitely vanilla PMMP but only occurs when typing for a long time and when the server is partially overloaded.
8ddacd86e58504e959628acd9f5d23dbc8a430ab
550d14fff380c897f27d830f00ac50e0494f1ee5
73fe9c319b5b6a8fd90df07c8b81795a5b5dc80c

**Comment by Apqu** [comment]
I have also now replicated this in vanilla PMMP it seems to occur when taking a long time to write a sign even on an empty server, seems time related mostly, haven't tried the fixes mentioned above yet.

**Comment by dktapps** [comment]
Excuse me. Thank you for not advertising on our repository. Banned.
