### ISSUE TITLE
Minecraft freezes for unknown reasons

### ISSUE THREAD

**Issue by fuyutsuki** [pmmp/PocketMine-MP#3431]
### Issue description

- Expected result: normal gameplay
- Actual result: Minecraft becomes inoperable during the game.

### Steps to reproduce the issue

Investigating...

### OS and versions

* PocketMine-MP: 3.12.0
* PHP: 7.3.13
* Server OS: Ubuntu 19.10
* Game version: PE

### Plugins

- none

### Crashdump, backtrace or other files

![image0](https://user-images.githubusercontent.com/16377174/80049885-20f41880-854f-11ea-83a2-599a93699c8d.png)

**Comment by dktapps** [comment]
there's really no point filing an issue without any indication of how to reproduce it...

**Comment by Endermanbugzjfc** [comment]
# Blame Microjang
