### ISSUE TITLE
Call to a member function getServer() on null" (EXCEPTION) in "src/pocketmine/event/entity/EntityDamageByEntityEvent" at line 65

### ISSUE THREAD

**Issue by kenygamer** [pmmp/PocketMine-MP#3432]
### Issue description

- Expected result: The `EntityDamageByEntityEvent->getDamager()` to return the entity that caused the damage
- Actual result: `EntityDamageByEntityEvent->getDamager()` results in a error.

### Steps to reproduce the issue
1. Create a listener to `EntityDamageByEntityEvent`
2. Call `EntityDamageByEntityEvent->getDamager()`

### OS and versions

* PocketMine-MP: 3.12.1+dev for Minecraft: Bedrock Edition v1.14.60 (protocol version 390)
* PHP: 7.3.14 (cli) (built: Feb 7 2020 13:10:31) (ZTS)
* Server OS: Ubuntu 16.04.6 LTS
* Game version: PE

### Plugins

- If you remove all plugins, does the issue still occur?
Cannot reproduce without a plugin, it requires a listener to call `EntityDamageByEntityEvent->getDamager()`

**Comment by TwistedAsylumMC** [comment]
The code you provided does not throw the error you provided in the title

**Comment by TwistedAsylumMC** [comment]
Nevermind I read it wrong, it seems like the event is being called, and the entity who was damaged is in an unloaded/non existing level. Do you call EntityDamageByEntityEvent anywhere?

**Comment by kenygamer** [comment]
> Nevermind I read it wrong, it seems like the event is being called, and the entity who was damaged is in an unloaded/non existing level. Do you call EntityDamageByEntityEvent anywhere?

The code used is similar to
```php
public function onEntityDamageByEntity(EntityDamageByEntityEvent $event){
$entity = $event->getEntity();
if($entity instanceof Player){
    if(mt_rand(0, 1)){
        $entity->attack($event);
    }
}
```
I don't know the circumstances of when it happened but I found the error. Doesn't normally happen.

I have to check if $entity (Player) level is null? I have had Player->$level null errors before when the player disconnects and I check if the level is not null first to prevent crashes.

**Comment by SOF3** [comment]
> > Nevermind I read it wrong, it seems like the event is being called, and the entity who was damaged is in an unloaded/non existing level. Do you call EntityDamageByEntityEvent anywhere?
> 
> The code used is similar to
> 
> ```
> public function onEntityDamageByEntity(EntityDamageByEntityEvent $event){
>     $entity = $event->getEntity();
>     if($entity instanceof Player){
>         if(mt_rand(0, 1)){
>             $entity->attack($event);
>         }
>     }
> }
> ```
> 
> I don't know the circumstances of when it happened but I found the error. Doesn't normally happen.
> 
> I have to check if $entity (Player) level is null? I have had Player->$level null errors before when the player disconnects and I check if the level is not null first to prevent crashes.

This code makes no sense. When the event is called, the entity is already running `attack($event)`. You seem to be triggering an infinite recursion if not error.

> ### Issue description
> 
>     * Expected result: The `EntityDamageByEntityEvent->getDamager()` to return the entity that caused the damage
> 
>     * Actual result: `EntityDamageByEntityEvent->getDamager()` results in a error.
> 
> 
> ### Steps to reproduce the issue
> 
>     1. Create a listener to `EntityDamageByEntityEvent`
> 
>     2. Call `EntityDamageByEntityEvent->getDamager()`
> 
> 
> ### OS and versions
> 
>     * PocketMine-MP: 3.12.1+dev for Minecraft: Bedrock Edition v1.14.60 (protocol version 390)
> 
>     * PHP: PHP 7.0.33-0ubuntu0.16.04.14 (cli) ( NTS )
> 
>     * Server OS: Ubuntu 16.04.6 LTS
> 
>     * Game version: PE
> 
> 
> ### Plugins
> 
>     * If you remove all plugins, does the issue still occur?
>       Cannot reproduce without a plugin, it requires a listener to call `EntityDamageByEntityEvent->getDamager()`

PHP 7.0.33? PocketMine 3.12.1? Those are incompatible.

**Comment by kenygamer** [comment]
> > > Nevermind I read it wrong, it seems like the event is being called, and the entity who was damaged is in an unloaded/non existing level. Do you call EntityDamageByEntityEvent anywhere?
> > 
> > 
> > The code used is similar to
> > ```
> > public function onEntityDamageByEntity(EntityDamageByEntityEvent $event){
> >     $entity = $event->getEntity();
> >     if($entity instanceof Player){
> >         if(mt_rand(0, 1)){
> >             $entity->attack($event);
> >         }
> >     }
> > }
> > ```
> > 
> > 
> > I don't know the circumstances of when it happened but I found the error. Doesn't normally happen.
> > I have to check if $entity (Player) level is null? I have had Player->$level null errors before when the player disconnects and I check if the level is not null first to prevent crashes.
> 
> This code makes no sense. When the event is called, the entity is already running `attack($event)`. You seem to be triggering an infinite recursion if not error.
> 
> > ### OS and versions
> > ```
> > * PocketMine-MP: 3.12.1+dev for Minecraft: Bedrock Edition v1.14.60 (protocol version 390)
> > 
> > * PHP: PHP 7.0.33-0ubuntu0.16.04.14 (cli) ( NTS )
> > 
> > * Server OS: Ubuntu 16.04.6 LTS
> > 
> > * Game version: PE
> > ```
> 
> PHP 7.0.33? PocketMine 3.12.1? Those are incompatible.

Note the mt_rand() I put, it's not an infinite recursion.....
I updated my PHP version, that was wrong sorry.

**Comment by TwistedAsylumMC** [comment]
You're also using a development build

**Comment by SOF3** [comment]
> > > > Nevermind I read it wrong, it seems like the event is being called, and the entity who was damaged is in an unloaded/non existing level. Do you call EntityDamageByEntityEvent anywhere?
> > > 
> > > 
> > > The code used is similar to
> > > ```
> > > public function onEntityDamageByEntity(EntityDamageByEntityEvent $event){
> > >     $entity = $event->getEntity();
> > >     if($entity instanceof Player){
> > >         if(mt_rand(0, 1)){
> > >             $entity->attack($event);
> > >         }
> > >     }
> > > }
> > > ```
> > > 
> > > 
> > > I don't know the circumstances of when it happened but I found the error. Doesn't normally happen.
> > > I have to check if $entity (Player) level is null? I have had Player->$level null errors before when the player disconnects and I check if the level is not null first to prevent crashes.
> > 
> > 
> > This code makes no sense. When the event is called, the entity is already running `attack($event)`. You seem to be triggering an infinite recursion if not error.
> > > ### OS and versions
> > > ```
> > > * PocketMine-MP: 3.12.1+dev for Minecraft: Bedrock Edition v1.14.60 (protocol version 390)
> > > 
> > > * PHP: PHP 7.0.33-0ubuntu0.16.04.14 (cli) ( NTS )
> > > 
> > > * Server OS: Ubuntu 16.04.6 LTS
> > > 
> > > * Game version: PE
> > > ```
> > 
> > 
> > PHP 7.0.33? PocketMine 3.12.1? Those are incompatible.
> 
> Note the mt_rand() I put, it's not an infinite recursion.....
> I updated my PHP version, that was wrong sorry.

ok it is not infinite recursion except to an $2^{-\infty}$ probability. But calling attack inside an event still makes no sense.

**Comment by kenygamer** [comment]
@dktapps I didn't notice this got closed until now. You all were getting me wrong, this is an actual bug. The reason is because level is nulled when the entity is closed. The fix is ​​easy:
https://github.com/pmmp/PocketMine-MP/blob/stable/src/pocketmine/event/entity/EntityDamageByEntityEvent.php#L65

Change:
```php
$this->getEntity()->getLevelNonNull()->getServer()->findEntity($this-damagerEntityId);
```

To:
```php
Server::getInstance()->findEntity($this->damagerEntityId);
