### ISSUE TITLE
Creative inventory not giving item

### ISSUE THREAD

**Issue by provsalt** [pmmp/PocketMine-MP#3436]
### Issue description

- Expected result: Gives the item when I move to my inventory
- Actual result: It cancels and not give the item

### Steps to reproduce the issue
1. Go to gamemode creative
2.Take anything out of the creative inventory

### OS and versions

* PocketMine-MP: 4.0.0+DEV commit 1f7f33d35d6674f3fdf118a0c39901d0b75e00b5
* PHP: 7.3.15
* Server OS: Win10
* Game version: Win10 (delete as appropriate)

### Plugins

[11:06:48.438] [Server thread/INFO]: Plugins (0):

Issue continues to happen without plugins.

### Crashdump, backtrace or other files

None

**Comment by dktapps** [comment]
fixed by the referenced commit
