### ISSUE TITLE
No hear walking sounds other players

### ISSUE THREAD

**Issue by Govdim** [pmmp/PocketMine-MP#3438]
No hear walking sounds other players
But i know how to fix it
MovePlayerPacket has global variable "onGround", default = false
Because of this, the client thinks that the player is in the air and does not play the sound of walking
Sorry for my English :(

PocketMine-MP: 3.12.0
Server OS: Ubuntu 18.04
Game version: PE/Win10

**Comment by dktapps** [comment]
this is probably an easy fix, feel free to make a PR if you want.
