### ISSUE TITLE
Outdated server

### ISSUE THREAD

**Issue by infinity-pe** [pmmp/PocketMine-MP#344]
### Issue description

Every time I try to connect to my server
`Cloud not connect: Outdated server!`

How can I update? Plus, I cannot find a PocketMine-MP.phar file in my FTP.

### Steps to reproduce the issue

Trying to connect to the server

### OS and versions

I don't know any of these, I cannot get into my server.
* PocketMine-MP:
* PHP: 
* OS: iOS only - Windows 7 Computer

### Crashdump, backtrace or other files

`[Server thread/INFO]: [/80.187.122.129:27172] logged out due to Outdated server!`

**Comment by RTGDaCoder** [comment]
You can use my compiled version from the 1.0.3 branch: https://drive.google.com/file/d/0Bz1cqtEoOkZqM3pxekRjcExvR2s/view?usp=sharing

**Comment by dktapps** [comment]
Compile your own or run from source-code with a recursive git clone.

**Comment by infinity-pe** [comment]
Where shall I put the PHAR? I'm using Multicraft.

**Comment by SalmonDE** [comment]
@infinity-pe try compressing the phar file. It reduced the filesize from my phar from 3mb to 1mb.

**Comment by infinity-pe** [comment]
@SalmonDE How can I do that?

**Comment by Awzaw** [comment]
This isn't a forum, you should post on https://forums.pmmp.io/ instead

**Comment by infinity-pe** [comment]
Where shall I upload the .phar? I'm using Multicraft.
