### ISSUE TITLE
pocketmine\level\particle\BubbleParticle doesn't showing

### ISSUE THREAD

**Issue by AkmalFairuz** [pmmp/PocketMine-MP#3440]
### Issue description
When addParticle BubbleParticle the particle doesn't show.

### Steps to reproduce the issue
1. $level->addParticle(new BubbleParticle($vec3));

### OS and versions

* PocketMine-MP: 3.12.0
* PHP: 7.2
* Server OS: Ubuntu 16.04 64 bit 
* Game version: Win10

### Plugins

- If you remove all plugins, does the issue still occur? Yes

**Comment by TheKnightGamer** [comment]
The particle won't show when your on the surface but if you enter the water it will show
