### ISSUE TITLE
No translation on client on entity when use setNameTag

### ISSUE THREAD

**Issue by benda95280** [pmmp/PocketMine-MP#3442]
### Issue description

- Expected result: Should be translated to the client language
- Actual result: No translation at all, show "tile.heavy_weighted_pressure_plate.name"

### Steps to reproduce the issue

Do not work :
$entity->setNameTag(new TranslationContainer("tile.heavy_weighted_pressure_plate.name"));
$entity->setNameTagVisible(true);

Work :
$receiver->sendMessage(new TranslationContainer("tile.heavy_weighted_pressure_plate.name"));

### OS and versions

* PocketMine-MP: 1.14.60
* PHP: 7.2
* Server OS: Win 10 - 1909
* Game version: Win10

### Plugins
Tried with or without

- If you remove all plugins, does the issue still occur? Yes
- If the issue is **not** reproducible without plugins: N/A

### Crashdump, backtrace or other files
N/A

**Comment by dktapps** [comment]
This is not a bug, it's never been designed to work this way.

**Comment by benda95280** [comment]
Is it possible to know if there is another way ?
