### ISSUE TITLE
My skin changes and i can use my actual skin

### ISSUE THREAD

**Issue by cubicalcoyote75** [pmmp/PocketMine-MP#3451]
![Screenshot_20200428-001444_Minecraft](https://user-images.githubusercontent.com/64455790/80449777-9bbd8a80-88e5-11ea-8229-7409787309ec.jpg)
![Screenshot_20200428-001448_Minecraft](https://user-images.githubusercontent.com/64455790/80449782-9fe9a800-88e5-11ea-8f90-b9a27365eefc.jpg)

**Comment by SOF3** [comment]
Do not submit duplicate issues. #3450

**Comment by SOF3** [comment]
Without knowing your PocketMine-MP version, OS, PHP, Client version, or plugins and how the issue occurred, the issue cannot begin to be solved.
A pre-formatted template is provided that shows the required information to begin to find, test and solve an issue.
Until the adequate template and information is provided, the issue will be closed; it may be reopened if you update the ticket with the correct template and required information.

**Comment by provsalt** [comment]
https://github.com/pmmp/PocketMine-MP/blob/stable/changelogs/3.10.md#note-about-skins
Hope this helps.
