### ISSUE TITLE
Inconsistent naming conventions for particles and sounds

### ISSUE THREAD

**Issue by dktapps** [pmmp/PocketMine-MP#3461]
## Description
Some particles have corresponding sounds because they are usually part of the same event, e.g. breaking a block. However, the naming conventions used are inconsistent, for example `BlockBreakSound` vs `DestroyBlockParticle` - the subject and action are in reversed order.

This came to mind today while attempting to add a `PunchBlockSound`, because it's not clear whether the naming should follow other sounds such as `BlockBreakSound`, or its corresponding particle `PunchBlockParticle`.

Problems like this will cause confusion for plugin developers no matter which naming is chosen, so this issue proposes that we choose a standard and change the existing non-conforming names to match.

**Comment by dschwartz783** [comment]
My coding style would put Block first. It makes autocompletion easier. Even if you don't remember the exact verb used, chances are you'll be able to figure out that the particle or sound you're looking for starts with Block, if that's what you're dealing with. It works well as a general category for things.

BlockPunchSound
BlockPunchParticle
BlockBreakSound
BlockDestroyParticle

As a side note, isn't Break and Destroy really the same thing? Probably should figure out which we want to use. Break is the more common lingo, as far as I know.
