### ISSUE TITLE
Add disable / enable RakLib blocking IP Address

### ISSUE THREAD

**Issue by AkmalFairuz** [pmmp/PocketMine-MP#3467]
## Description
We know many server are using WaterDog proxy for support Fast Transfer feature.
Add on pocketmine.yml enable/disable RakLib blocking ip address.

## Justification
Sometime RakLib blocking IP Address for 300 seconds and proxy can't connect to server.

**Comment by dktapps** [comment]
You can use a plugin for this, and there are API additions in the next feature release to make it easier. See #3398

**Comment by AkmalFairuz** [comment]
how? , plugin can unblock address on Network class only.

**Comment by SOF3** [comment]
Read the pull request. It allows plugins to increase the packet limit that triggers blocking IP address.

**Comment by dktapps** [comment]
Waterdog is now deprecated (and using a proxy over RakLib backend makes no sense anyway). I don't think this issue has any particular value. If someone needs to change this limit for some reason, they can use the provided APIs.
