### ISSUE TITLE
EnderPearl not working in close range

### ISSUE THREAD

**Issue by ItsMax123** [pmmp/PocketMine-MP#3471]
### Issue description

- Expected result: What were you expecting to happen?
When you are right up against a wall and throw an enderpearl at it, it should teleport you (and break your fall if you are falling) 
- Actual result: What actually happened?
When you throw an enderpeal in an area you are already in, it doesnt do anything

### Steps to reproduce the issue
1. Make a big 1x1 hole to bedrock
2. Get enderpearls
3. Fall and throw them while looking straight (not up, not down)

### OS and versions

* PocketMine-MP: 3.12.0
* PHP: php7
* Server OS: Not so sure? I use WitherHosting to host...
* Game version: Win10 

### Plugins

Repair v1.0.1, PCFly v3.0.0, Tebex-PMMP v2.1.0, CombatLogger v0.0.6, AutoClearLagg v3.0.0, BanItem v2.3.3, CompassXYZ v1.0, essentialsTP v1.2.2, EconomyAPI v5.7.2, EasyKits v1.1.3, AuctionHouse v1.0.9, SellAll v1.3.0, FormAPI v1.3.0, WorldBorder v1.0.0-3.0.0, AntiSpamPro v1.4.1, EnderPearlCooldown v0.0.2, CustomShopUI v4.0.5, ChatMuffler v1.0.2, CommandSpy v1.0.0, BuilderTools v1.2.0-beta2, PurePerms v1.4.3, WorldGuard v1.1.0, BetterVoting v1.6, TeaSpoon v1.2.0, BlazinFly v1.8.7, PlayerVaults v3.2.0, TempBanUI v2.3, WorldProtect v2.3.8, StaffChat v1.1.4, qvpGM v1.0.0, RulesUI v1.0.0, BurgerSpawners v0.0.9, FactionsPE v1.2.4, TimeCommander v1.0.2, AutoRestarter v1.0.0, GappleCooldown v2.0.0, PiggyCrates v2.0.5, PureChat v1.4.6

- If you remove all plugins, does the issue still occur? I cannot test because all my plugins are set up and I dont want to delete the setup... sorry...
- If the issue is **not** reproducible without plugins:
  - Have you asked for help on our forums before creating an issue? no
  - Can you provide sample, *minimal* reproducing code for the issue? If so, paste it in the bottom section

### Crashdump, backtrace or other files

Not a crash

**Comment by ItsMax123** [comment]
I will maybe try to test without the Enderpearl cooldown plugin

**Comment by ZizzyZizzy** [comment]
> I cannot test because all my plugins are set up and I dont want to delete the setup... sorry...

Seriously? It takes 5 minutes. Rename plugins to plugins.disabled, restart the server and test. When finished, delete the plugins folder that was created and rename plugins.disabled to plugins.

How do you expect the developers to waste their time trying to recreate a problem when you won't spend 5 minutes to follow the rules and test yourself first?

**Comment by dktapps** [comment]
Hi, if you want us to help you, you need to help us by doing what we ask as the basic steps for identifying a bug. That means testing without plugins so that our developers don't get their free time wasted on issues that don't have anything to do with our work.

**Comment by ItsMax123** [comment]
ah okay didn't know I could do that @ZizzyZizzy I will try right now

**Comment by ItsMax123** [comment]
Not a pocketmine problem, my fault sorry
