### ISSUE TITLE
Server randomly emergency restart 

### ISSUE THREAD

**Issue by b1zey** [pmmp/PocketMine-MP#3481]
Last request deleted by bot, but this is no support request and in new version of PMMP this bug appears.
I test this with clear server, but it cannot be consired as correctly testing.
This bug appears on a public server with online and plugins.

Server works and in randomly moments emergency stoped and not save world or leave message to connected players (players see just disconnect, no message as usual restart).
The emergency stop not leave a crashdump, server fast restarting and doesn't save anything.
I don't know how to reproduce this bug because it random bug. Server can work fine 10 minutes or 40 minutes and randomly this bug happening.

Software: PocketMine-MP 3.11.6. Protocol version: 390.
OS: Debian 8 jessie.
PHP version: 7.3.7

In memory limit (php.ini) i tried to set -1 or 8192M or 1024M and it not give a result: this bug was happened again and again.
In date.timezone i set from CEST to MSK, but i don't think that this could be a problem.

**Comment by b1zey** [comment]
I don't know steps to reproduce of this bug, but it does mean that he is not and it NOT support request. 
If i promise with issue theme - okay, i am sorry.

**Comment by SOF3** [comment]
Please do not duplicate issues. #3480

**Comment by kenygamer** [comment]
> Last request deleted by bot, but this is no support request and in new version of PMMP this bug appears.
> I test this with clear server, but it cannot be consired as correctly testing.
> This bug appears on a public server with online and plugins.
> 
> Server works and in randomly moments emergency stoped and not save world or leave message to connected players (players see just disconnect, no message as usual restart).
> The emergency stop not leave a crashdump, server fast restarting and doesn't save anything.
> I don't know how to reproduce this bug because it random bug. Server can work fine 10 minutes or 40 minutes and randomly this bug happening.
> 
> Software: PocketMine-MP 3.11.6. Protocol version: 390.
> OS: Debian 8 jessie.
> PHP version: 7.3.7
> 
> In memory limit (php.ini) i tried to set -1 or 8192M or 1024M and it not give a result: this bug was happened again and again.
> In date.timezone i set from CEST to MSK, but i don't think that this could be a problem.

I can help you. DM in Discord kv#1234, don't open an issue until you know it is not a plugin.
