### ISSUE TITLE
Server crashed

### ISSUE THREAD

**Issue by mote166** [pmmp/PocketMine-MP#3482]
Link to crashdump: https://pastebin.com/Ub6XFg4g

### Additional comments (optional)
i don't know what is happening or how but it suddenly started crashing with this error

**Comment by dktapps** [comment]
This crashdump is incomplete, but it appears that your data is corrupted and contains repeated NBT tags where there shouldn't be any. While this shouldn't crash the server, it's a problem with your world anyway.

**Comment by mote166** [comment]
thank you for letting me know, i will check the last worlds i added in these 3 days and remove the world that is causing it.
