### ISSUE TITLE
Allow plugins to use PSR-4 autoloading standard

### ISSUE THREAD

**Issue by dktapps** [pmmp/PocketMine-MP#3484]
## Description
Plugins are currently required to abide by a PSR-0-esque (not entirely PSR-0, but the essence is there) autoloading system where the directory path relative to `src` has to match the class FQN.

It's very tiresome to have to deal with these long subdirectory chains, especially when you're working on the CLI.

Example: I'm SSH'ing into my development server and want to modify my test plugin. I write:
```
vi plugins/test/src/dktapps/test/Main.php
```

With a PSR-4-like system, this could be reduced to
```
vi plugins/test/src/Main.php
```
and the namespace `dktapps\\test` would be mapped to `src`.

This would be accompanied by a `plugin.yml` directive to setup the mappings, e.g.:
```
namespace-map:
    dktapps\\test: src #looks in src/Main.php for dktapps\\test\\Main instead of src/dktapps/test/Main.php
```
or perhaps a more limited but less breakable not-completely-PSR-4-but-gives-main-benefits:
```
namespace-prefix: dktapps\\test
```

In addition to the advantages written above, this may result in more compliance with the `author\\pluginname\\Stuff` standard since plugin devs will be less tempted to skip the `author` section just to save themselves a subdirectory.

## Compatibility
It's _theoretically_ possible to implement this without BC breaks; however, we'd need a new, separate autoloader because `pocketmine/classloader` provides an autoloader which is strictly PSR-0 and changing that would require BC breaks.

## Future scope
It might be desirable to allow plugins to use their own autoloaders entirely, e.g.
```
autoload-file: path/to/my/custom/autoloader.php
```
This would allow plugins to more easily make use of the Composer autoloader to have more flexibility.
## Alternative methods
We could stick to the current system; however, given the full advantage-taking of PSR-4 on the master branch, it seems reasonable to afford plugins some of the same benefits, since they need it more than we do.

**Comment by SOF3** [comment]
One thing that troubles me is the duplication of the namespace in `main` and `namespace-prefix`. Is it feasible to allow `main` to be resolved relatively to the `namespace-prefix`? That is,
```yaml
namespace-prefix: Foo\Bar
main: Main
```
would resolve the main class as `Foo\Bar\Main`. If under the rare scenario that it is necessary to use a class not in the source folder (why would that even be the case? A library class?), the `main` attribute could start with `\` to indicate an absolute path, just like PHP's inline name qualification rules.

Furthermore, the attribute `namespace-prefix` is a bit long, especially given that plugin.yml is often typed up manually (I don't think many people actually use DevTools to generate a plugin skeleton). Is it possible to change it to something like simply `psr4`?

**Comment by dktapps** [comment]
re to resolving relative: Theoretically, as long as it doesn't make the learning curve too steep. I'm thinking about this in a Composer-like context, so that hadn't really crossed my mind. Though I wonder if the inconsistency of needing a `\` or not depending on the presence of another directive might make things confusing.

The choice of namespace map vs prefix really depends on how much use case there is for having more than 1 prefix. The only place I can currently think of where it might be useful is DevTools (it's 2 plugins in 1 package).

As for shortening the name: I don't know if I'd be happy with it considering that `psr4` is a less self-explanatory name to plugin devs. Usually the way plugin devs in this space learn is by copying other devs, so code really needs to explain itself if we want devs to adopt new standards.
