### ISSUE TITLE
Unable to use getResource in plugin files ending with backslashes 

### ISSUE THREAD

**Issue by SOF3** [pmmp/PocketMine-MP#3497]
### Issue description

- Expected result: `getResource()` should return a valid file handle
- Actual result: `getResource()` returns null

### Steps to reproduce the issue
Use this setup in `plugins` folder:
```
plugins
├── Asshole\
│   ├── plugin.yml
│   ├── resources
│   │   └── config.yml
│   └── src
│       └── Asshole.php
└── DevTools.phar
```

The main class contains only this function:
```php
  public function onEnable(){
    $fh = $this->getResource("config.yml");
    var_dump(stream_get_contents($fh));
    fclose($fh);
  }
```

Leads to this error:
```
[14:21:38] [Server thread/CRITICAL]: ErrorException: "stream_get_contents() expects parameter 1 to be resource, null given" (EXCEPTION) in "plugins/Asshole//src/Asshole" at line 5
```

### OS and versions

* PocketMine-MP: 3.12.1
* PHP: PHP 7.3.14 (cli) (built: Feb  7 2020 13:10:31) ( ZTS )

* Server OS: Linux 5.3.0-51-generic #44~18.04.2-Ubuntu SMP Thu Apr 23 14:27:18 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux

### Plugins
Explained above.

### Crashdump, backtrace or other files

```
[14:21:38] [Server thread/CRITICAL]: ErrorException: "stream_get_contents() expects parameter 1 to be resource, null given" (EXCEPTION) in "plugins/Asshole//src/Asshole" at line 5
```

### Debugged cause
Use of `rtrim($file, "/\\")` would remove trailing backslashes in valid filenames on Linux.

**Comment by dktapps** [comment]
I don't understand the problem. Are you saying Linux allows `\` in filenames?

**Comment by SOF3** [comment]
Yes it does.
