### ISSUE TITLE
Burning Players Ignite Arrows

### ISSUE THREAD

**Issue by Wumpotamus** [pmmp/PocketMine-MP#3504]
### Issue description
To reproduce this issue, I would step into lava, walk away and shoot an arrow. I've done some testing on where the issue could be located, no results yet.

- Expected result: Burning players have no effect on arrows.
- Actual result: Burning players set arrows on fire.

### Steps to reproduce the issue
1. Catch fire.
2. Shoot a bow.
3. Profit!

### OS and versions

* PocketMine-MP: 3.12 (Happens on any 3.x and 4.0 build)
* PHP: 7.3.14
* Server OS: Windows 10
* Game version: PE/Win10

### Plugins
Can be reproduced without plugins.

**Comment by dktapps** [comment]
I believe this behaviour was implemented intentionally, judging by this code:
https://github.com/pmmp/PocketMine-MP/blob/8f5db7c29759b9dfa4bab015604236905b02a2f9/src/pocketmine/item/Bow.php#L62
