### ISSUE TITLE
Stripping wood, Barrels, etc. don't work!

### ISSUE THREAD

**Issue by BazookaB3n** [pmmp/PocketMine-MP#3514]
Hi, I'm Ben.
I am starting a small bedrock server and I am using PocketMine-MP. my younger brother was trying to strip some wood, but every time he did it would undo. also, every time I would place a barrel, it would undo. I Don't Know if this is a scripting issue or if the server I am using is not the right fit. Thanks for your time!

**Comment by IceCruelStuff** [comment]
Those items and blocks are not implemented yet.

**Comment by BazookaB3n** [comment]
Thank You!
