### ISSUE TITLE
EntityDamageEvent bug

### ISSUE THREAD

**Issue by ipad54** [pmmp/PocketMine-MP#3515]
### Issue description

- Expected result: The player will not light up
- Actual result: The player will light up

### Steps to reproduce the issue
1. If you cancel the EntityDamageEvent, and shoot the player with a bow to enchant set fire, the player will light up

### OS and versions

* PocketMine-MP: 3.12.2
* PHP: 7.3
* Server OS: Linux
* Game version: PE/Win10 

### Plugins

- Plugins(0)

### Crashdump, backtrace or other files
No

**Comment by dktapps** [comment]
Use `ProjectileHitEntityEvent`.
