### ISSUE TITLE
Landing sounds are played in spectator mode

### ISSUE THREAD

**Issue by dktapps** [pmmp/PocketMine-MP#3516]
### Issue description
Recently on PM4, landing sounds became server-sided. However, they don't take into account that spectator players should make no noise (and nor do they take the SILENT data flag into effect).

### Steps to reproduce the issue
1. Switch to spectator mode
2. Fly down through a block

### OS and versions

* PocketMine-MP: 3bb53658daf73f2f19f31bfd16377cbf3e6b968f
* PHP: 7.3.16
* Server OS: windows
* Game version: Win10

**Comment by Gianluxx** [comment]
Also when a spectator hits air or an entity. Other players can hear the noise and the DamageEvent is actually called

**Comment by dktapps** [comment]
The damage event is supposed to be called. It's cancelled by default.

**Comment by Gianluxx** [comment]
what about the sound?
