### ISSUE TITLE
VanillaItems not cloning items

### ISSUE THREAD

**Issue by Muqsit** [pmmp/PocketMine-MP#3519]
### Issue description

- Expected result: What were you expecting to happen?
Fetching item instances from VanillaItems return a cloned instance (i.e `VanillaItems::DIAMOND() !== VanillaItems::DIAMOND()`)

- Actual result: What actually happened?
Items returned by VanillaItems are not cloned.

### Arising issues
* Diamond ores dropping more than 1 diamond:
  1. Break a diamond ore with pickaxe. It drops 1 diamond.
  2. Break a `nether_reactor` with pickaxe. It drops 3 diamonds.
  3. Break a diamond ore with pickaxe. It drops 3 diamonds instead of 1 diamond.

  Diamond ore drops `VanillaItems::DIAMOND()` whereas nether reactor core drops `VanillaItems::DIAMOND()->setCount(3)` (modifying the same Item instance in the process).

### OS and versions

* PocketMine-MP: 7aca41a530580f0f5f4d94bf27e26a0b1478ddd1-dirty
* PHP: 7.3.18
* Server OS: Linux s159235 4.15.0-72-generic #81-Ubuntu SMP Tue Nov 26 12:20:02 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux
* Game version: Win 10

### Plugins

- If you remove all plugins, does the issue still occur?
Yes

**Comment by dktapps** [comment]
god I hate mutability...

**Comment by dktapps** [comment]
Fixed, thanks!
