### ISSUE TITLE
The server crashes when it tries to connect to RCON

### ISSUE THREAD

**Issue by Akak72** [pmmp/PocketMine-MP#3525]
When I try to connect to the server via RCON, the server immediately crashes without any information (it doesn't even turn off plugins).

**Comment by dktapps** [comment]
Without knowing your PocketMine-MP version, OS, PHP, Client version, or plugins and how the issue occurred, the issue cannot begin to be solved.
A pre-formatted template is provided that shows the required information to begin to find, test and solve an issue.
Until the adequate template and information is provided, the issue will be closed; it may be reopened if you update the ticket with the correct template and required information.

[Contribution guidelines](https://github.com/pmmp/PocketMine-MP/blob/master/CONTRIBUTING.md)

**Comment by Akak72** [comment]
Updated
