### ISSUE TITLE
Commands Are not disabled after plugin disable (PluginIdentifiableCommand)

### ISSUE THREAD

**Issue by Kjenium** [pmmp/PocketMine-MP#3531]
### Issue description

- Expected result: What were you expecting to happen?
I expected to see the command disabled
- Actual result: What actually happened?
It is still registered and can be executable

### Steps to reproduce the issue
1. Make your plugin crash with an error
2. Perform a command registered by it

### OS and versions

* PocketMine-MP:
3.12.2
* PHP:
7.x.x
* Server OS:
I'm using a web platform so idk
* Game version: PE/Win10 (delete as appropriate)

### Plugins

- If you remove all plugins, does the issue still occur?
yes
- If the issue is **not** reproducible without plugins:
  - Have you asked for help on our forums before creating an issue?
  - Can you provide sample, *minimal* reproducing code for the issue? If so, paste it in the bottom section

**Comment by Eren5960** [comment]
With which code do you close the plugin?

**Comment by dktapps** [comment]
"crashing by error" causes the server to enter undefined state. Simply don't crash in the first place.
