### ISSUE TITLE
close() and kick() crashes server

### ISSUE THREAD

**Issue by ethaniccc** [pmmp/PocketMine-MP#3532]
Link to crashdump: https://crash.pmmp.io/view/4239196

### Additional comments (optional)
used `$player->close()` in a plugin and server crashed

**Comment by ZizzyZizzy** [comment]
@ethaniccc Dude..seriously? Did you even READ the instructions?

```
Crash
**Report a crash in PocketMine-MP (not plugins)**
```

Report plugin issues to the guys that actually wrote the plugin and don't waste the time of PMMP developers.

**Comment by ethaniccc** [comment]
Except it's my plugin and I never use the method `getBlockAt()` in it

**Comment by TwistedAsylumMC** [comment]
The error is because you are directly calling Player->close()

**Comment by ethaniccc** [comment]
Isn't `$player->close("", $reason);` correct usage though?

**Comment by TwistedAsylumMC** [comment]
https://github.com/pmmp/PocketMine-MP/blob/2eb62c85f69ebd22b36f29cfb513a579ea570b0c/src/pocketmine/Player.php#L3457-L3458

**Comment by ethaniccc** [comment]
ah

**Comment by ethaniccc** [comment]
even with that, it still gave the error, reopening
new crash log with using kick(): https://crash.pmmp.io/view/4239380

**Comment by TwistedAsylumMC** [comment]
What does your ``Mockingbird`` plugin do? It's an issue with this

**Comment by ethaniccc** [comment]
It's a little AntiCheat, when the VL gets to 65, the player gets kicked from the server

**Comment by TwistedAsylumMC** [comment]
Can you show the code where it checks if the player is inside of a block

**Comment by ethaniccc** [comment]
> Can you show the code where it checks if the player is inside of a block
That's the problem: it doesn't
