### ISSUE TITLE
Abandoned dependency: pthreads

### ISSUE THREAD

**Issue by seanlynch** [pmmp/PocketMine-MP#3541]
### Issue description

- Expected result: PocketMine-MP doesn't depend on abandoned software.

- Actual result: PocketMine-MP does depend on abandoned software.

### Steps to reproduce the issue
1. Look at upstream PocketMine-MP dependencies, in particular pthreads: https://github.com/krakjoe/pthreads
2. Note that the aforementioned project is archived and hasn't had a release since 2016

### OS and versions
* PocketMine-MP: 3.12.2
* PHP: 7.3.18
* Server OS: Alpine Linux 3.12
* Game version: PE

### Plugins
None

- If you remove all plugins, does the issue still occur? Yes

**Comment by dktapps** [comment]
we use our own fork of pthreads and have for 2 years already.
