### ISSUE TITLE
Infinite Generating World screen on player void death

### ISSUE THREAD

**Issue by EerieAlchemist** [pmmp/PocketMine-MP#3542]
### Issue description

- Expected result: What were you expecting to happen? The player should respawn normally.
- Actual result: What actually happened? When a player tries to respawn, they are greeted with an infinite "generating world" screen and are forced to restart their client to fix.

### Steps to reproduce the issue
1. Fall into the void (when using a plug-in that uses PlayerRespawnEvent and/or PlayerDeathEvent.
2. Receive the generating world screen.

### OS and versions

* PocketMine-MP: 3.12.2
* PHP: 7.4.5
* Game version: Windows 10 1.14.6

### Plugins
 Skywars by GamakCZ

- If you remove all plugins, does the issue still occur? No
- If the issue is **not** reproducible without plugins:
  - Have you asked for help on our forums before creating an issue? Yes
  - Can you provide sample, *minimal* reproducing code for the issue? If so, paste it in the bottom section. N/A

**Comment by UnEnanoMas** [comment]
Do not close this, the problem happens to many people, it would be good to fix it at once
