### ISSUE TITLE
Absorption making people invincible

### ISSUE THREAD

**Issue by Unickorn** [pmmp/PocketMine-MP#3546]
### Issue description

- Expected result: Taking damage after getting absorption effect (by eating a golden apple)
- Actual result: I took zero damage from all kinds of damage sources until my effect expired

### Steps to reproduce the issue
1. Get absorption effect
2. Do anything that'd damage you

### OS and versions

* PocketMine-MP: 3.12.3
* PHP: 7.3
* Server OS: Windows

- If you remove all plugins, does the issue still occur? Yes

**Comment by dktapps** [comment]
hmm, that's a problem... is this new to 3.12.3?

**Comment by Unickorn** [comment]
yep.
