### ISSUE TITLE
Hit delay is completely gone

### ISSUE THREAD

**Issue by Wumpotamus** [pmmp/PocketMine-MP#3549]
### Issue description

- Expected result: Hitting players with some delay.
- Actual result: When you hit players you can hit them a ton with no delay.

### Steps to reproduce the issue
1. Join server with another person.
2. Hit them a lot.

### OS and versions

* PocketMine-MP: 3.12.4
* PHP: 7.3
* Server OS: Windows
* Game version: PE/Win10

### Plugins
Plugins make no difference.

**Comment by dktapps** [comment]
please try the latest commit on the stable branch

**Comment by dktapps** [comment]
Fixed by 915224c8e55e39aaf049efeedf999fda984a51d3.
