### ISSUE TITLE
Walking sounds are heard in spectator mode

### ISSUE THREAD

**Issue by MonoAdrian23** [pmmp/PocketMine-MP#3553]
### Issue description
In Gamemode Spectator/3, you can hear Walking sounds.

### Steps to reproduce the issue
1. ...Choose Gamemode 3
2. ...Walk 

### OS and versions

* PocketMine-MP: 3.12.5
* PHP: 7
* Server OS: Debian 10 Buster
* Game version: PE/Win10 (delete as appropriate) PE

### Plugins
 No Plugins

- If you remove all plugins, does the issue still occur?
- If the issue is **not** reproducible without plugins:
  - Have you asked for help on our forums before creating an issue?
  - Can you provide sample, *minimal* reproducing code for the issue? If so, paste it in the bottom section

**Comment by dktapps** [comment]
ladies and gentlemen, this is what happens when I break the sacred rule "don't trust people who say they tested their change".

caused by #3492
