### ISSUE TITLE
"Switching" isn't fixed

### ISSUE THREAD

**Issue by knzv97** [pmmp/PocketMine-MP#3558]
### Issue description

The bug that was described in #2939 was not fixed (check video)

### OS and versions

* PocketMine-MP: 3.13.0
* PHP: 7.3.18
* Server OS: Debian 10
* Game version: Windows 10

### Plugins

`Plugins (0):`

### Crashdump, backtrace or other files

Video: https://youtu.be/8ZnYBzbCBE4

**Comment by dktapps** [comment]
You're switching between two tools with different levels if damage. Therefore, this is WAI; the difference is that the lower previous damage is subtracted from the higher damage if it's bypassing a cooldown, so that the damage isn't overpowered anymore.

**Comment by Nerahikada** [comment]
This may be compliant with vanilla behavior, but this was not what we wanted :joy:

**Comment by dktapps** [comment]
If you want something else, you can do it yourself with a plugin.

**Comment by Nerahikada** [comment]
finally fixed(?) with this commit: d70a7d34a7f70b9d7325d168fa43ba30382ba640
