### ISSUE TITLE
 logged out due to Invalid session. Reason: Token can't be used yet - check the server's date/time matches the client

### ISSUE THREAD

**Issue by JayDanYt** [pmmp/PocketMine-MP#3568]
logged out due to Invalid session. Reason: Token can't be used yet - check the server's date/time matches the client
how do I fix this

**Comment by Encritary** [comment]
As it says, you have to check that your local time matches the server time (± 60 seconds).

**Comment by JayDanYt** [comment]
> As it says, you have to check that your local time matches the server time (± 60 seconds).

yah I did but nothing works
