### ISSUE TITLE
Add BlockDecayEvent instead LeavesDecayEvent

### ISSUE THREAD

**Issue by AkmalFairuz** [pmmp/PocketMine-MP#3578]
## Description
Add event to handle block decay event include Flowing Water and Flowing Lava decay.

## Justification
We cannot handle flowing water or lava when decay, only Leaves can handle

## Alternative methods
Register new Water Block then put custom event when setBlock into air

**Comment by dktapps** [comment]
Lava and water don't decay. Lumping this behaviour in with Leaves decay would be wrong and misleading.

**Comment by AkmalFairuz** [comment]
I mean Flowing Water and Lava

**Comment by dktapps** [comment]
I know what you mean. My point stands.

**Comment by AkmalFairuz** [comment]
So , May I create pull request about this issue?

**Comment by dktapps** [comment]
Asking if you can create a pull request kind of defeats the object of making a pull **request**...
