### ISSUE TITLE
Jenkins is BROKEN!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!

### ISSUE THREAD

**Issue by JimboCoder61** [pmmp/PocketMine-MP#358]
### Steps to reproduce the issue

1A. Run the automated installer on your website: wget -q -O - https://raw.githubusercontent.com/pmmp/php-build-scripts/master/installer.sh | bash -s -
1B. Goto jenkins.pmmp.io

### Crashdump, backtrace or other files

Results in: [!] Couldn't download version automatically from Jenkins server
Or if you goto your jenkins, I get 502 error

**Comment by dktapps** [comment]
Stop spamming and search the issue tracker. #320

**Comment by JimboCoder61** [comment]
So why is jenkins broken?

**Comment by jasonwynn10** [comment]
As @dktapps already stated in #320
> It's been down for weeks, an issue with our service provider. We did already have an issue here about this, but the author closed it for some unknown reason.
