### ISSUE TITLE
Grass Block Changing color bug 

### ISSUE THREAD

**Issue by JohnnyX071** [pmmp/PocketMine-MP#3584]
Hello, i have this problem where sometimes random grass blocks change color and i have to reconnect to my server to fix them, everyone in my server has this problem not only me, can you fix it?

I don't know how to reproduce this bug, it just happens randomly

![Screenshot_2](https://user-images.githubusercontent.com/63922728/84585954-98427c00-ae1d-11ea-95ce-78e3365d68b8.png)

**Comment by DimBis** [comment]
It's a client-side bug.

**Comment by JohnnyX071** [comment]
no, it happens to almost everyone i have asked

**Comment by dktapps** [comment]
it's still a client bug

**Comment by JohnnyX071** [comment]
This is another players perspective so its not client bug
![Screenshot_2](https://user-images.githubusercontent.com/63922728/85230442-d1b85000-b3f8-11ea-9d69-4bda6c310a99.png)

**Comment by JohnnyX071** [comment]
and its so weird!
![Screenshot_3](https://user-images.githubusercontent.com/63922728/85230464-fad8e080-b3f8-11ea-9956-b88db3d4f583.png)

**Comment by dktapps** [comment]
Happening to multiple players doesn't mean it's not a bug in the client.

**Comment by JohnnyX071** [comment]
we are on different devices
first one on phone and second on PC

**Comment by EmeraldTorch** [comment]
both of those are clients
