### ISSUE TITLE
Where is Smooth Stone?

### ISSUE THREAD

**Issue by Crasher508** [pmmp/PocketMine-MP#3589]
The Smooth Stone is missing into BlockIds.php. When a player melts smooth stone in the oven, they became the item, but they can't place them because Pocketmine don't know what's Smooth Stone

## Justification
I want to add SmoothStone, but Pocketmine is missing the ID of them

**Comment by dktapps** [comment]
It's not supported because PM3 uses the legacy chunk format which doesn't support blocks with IDs >= 256.
