### ISSUE TITLE
Eaten cake appears after clicking on the block on which it stood

### ISSUE THREAD

**Issue by ghost** [pmmp/PocketMine-MP#3591]
### Issue description

- Expected result: nothing happens after clicking block on which cake stood
- Actual result: cake appears

### Steps to reproduce the issue
1. eat cake
2. click on the block on which it stood

### OS and versions

* PocketMine-MP: 3.13.0/4.0.0 dev
* PHP: stable test server/canary test server
* Server OS: stable test server/canary test server
* Game version: PE/Win10

### Crashdump, backtrace or other files
Video from the presentation of the problem:
https://cdn.discordapp.com/attachments/546255162222706696/722447906241642586/Minecraft_2020-06-16_15-49-32.mp4

**Comment by NTT1906** [comment]
Is this really fixed?
