### ISSUE TITLE
Button is not solid block

### ISSUE THREAD

**Issue by gistrec** [pmmp/PocketMine-MP#360]
There is no function 'isSolid()' in button class 
And when Player stay near button, it causes damage

Solution: add function 'isSolid()' in StoneButton.php && WoodenButton.php:

```php
public function isSolid(){
    return false;
}

**Comment by dktapps** [comment]
#181 

I'm not messing with crap I'm going to rewrite. If you want to make a PR to fix this yourself, feel free.
