### ISSUE TITLE
Mobs werden nicht gespawnt.

### ISSUE THREAD

**Issue by Seqxii3001** [pmmp/PocketMine-MP#3601]
kann mir jemand weiterhelfen und habe schon mehrmals den server neu aufgesetzt selbst ohne plugins werden keine tiere oder monster gespawnt PocketMine 1.14.60+

**Comment by mmm545** [comment]
please talk english

**Comment by mmm545** [comment]
ok apparently you are talking about mobs not spawning, mobs are not added in pocketmine *yet*
