### ISSUE TITLE
[Server thread/CRITICAL]

### ISSUE THREAD

**Issue by WoollenPanda275** [pmmp/PocketMine-MP#3608]
Could not execute asynchronous task CheckUpdateTask: Task crashed

**Comment by dktapps** [comment]
Without knowing your PocketMine-MP version, OS, PHP, Client version, or plugins and how the issue occurred, the issue cannot begin to be solved.
A pre-formatted template is provided that shows the required information to begin to find, test and solve an issue.
Until the adequate template and information is provided, the issue will be closed; it may be reopened if you update the ticket with the correct template and required information.

[Contribution guidelines](https://github.com/pmmp/PocketMine-MP/blob/master/CONTRIBUTING.md)

**Comment by WoollenPanda275** [comment]
pocketmine version 3.13.0, (OS) windows client version v1.14.60
![Capture](https://user-images.githubusercontent.com/65177508/85331317-d13db900-b4cd-11ea-9177-3426ed2a83e8.PNG)
