### ISSUE TITLE
[Server thread/CRITICAL]

### ISSUE THREAD

**Issue by WoollenPanda275** [pmmp/PocketMine-MP#3609]
Could not execute asynchronous task CheckUpdateTask: Task crashed
pocketmine version 3.13.0, (OS) windows 10 client version v1.14.60
![Capture](https://user-images.githubusercontent.com/65177508/85332165-55dd0700-b4cf-11ea-8f90-4fa4898ae61b.PNG)

**Comment by dktapps** [comment]
Without knowing your PocketMine-MP version, OS, PHP, Client version, or plugins and how the issue occurred, the issue cannot begin to be solved.
A pre-formatted template is provided that shows the required information to begin to find, test and solve an issue.
Until the adequate template and information is provided, the issue will be closed; it may be reopened if you update the ticket with the correct template and required information.

[Contribution guidelines](https://github.com/pmmp/PocketMine-MP/blob/master/CONTRIBUTING.md)

**Comment by WoollenPanda275** [comment]
Ive fixed it anyway
