### ISSUE TITLE
get auto update

### ISSUE THREAD

**Issue by nmo0ory** [pmmp/PocketMine-MP#361]
hello, i am getting the .phar file form https://poggit.pmmp.io/ci/pmmp/PocketMine-MP/PocketMine-MP#
but is there any link i can use that download last file all the time ?

**Comment by dktapps** [comment]
Currently no. Please use our [forums](https://forums.pmmp.io) for questions.

**Comment by Awzaw** [comment]
Poggit recently added this direct link to the most recent build: https://poggit.pmmp.io/get.pmmp

**Comment by nmo0ory** [comment]
thanks that what i was looking for <3
