### ISSUE TITLE
Issue with sendBlocks() with glass blocks

### ISSUE THREAD

**Issue by Kjenium** [pmmp/PocketMine-MP#3610]
### Issue description

- Expected result: What were you expecting to happen?
I'd expect to see the blocks i sent
- Actual result: What actually happened?
You can't see them if they are of the glass family, until you try breaking them
### Steps to reproduce the issue
1.send a player or a group of player some blocks using sendBlocks()

### OS and versions

* PocketMine-MP:
3.13.0
* PHP:
7.x.x
* Server OS:
i don't know bc i use a webs platform

### Plugins

- If you remove all plugins, does the issue still occur?
yes
- If the issue is **not** reproducible without plugins:
  - Have you asked for help on our forums before creating an issue?
  - Can you provide sample, *minimal* reproducing code for the issue? If so, paste it in the bottom section

**Comment by dktapps** [comment]
sendBlocks is an internal function that shouldn't be used by plugins. The most likely cause is that you didn't provide the flags parameter (you need FLAG_ALL).

**Comment by Kjenium** [comment]
WIth the ALL_FLAG flag i have another problem. The texture of the glass doesn't disappear when i send that block as air.
