### ISSUE TITLE
Server crashed because of memory

### ISSUE THREAD

**Issue by justarty** [pmmp/PocketMine-MP#3612]
Link to crashdump:  https://pastebin.com/c18wFC0z

### Additional comments (optional)

This crash is happening to my server whenever there are more than 80 people for about 30 minutes.

I know about this thread https://github.com/pmmp/PocketMine-MP/issues/3052

The memory always says that it's 134 megabytes but I have changed it everywhere to be more than that.

Here is from my log file:

`2020-06-23 [05:24:26] [Server thread/EMERGENCY]: Fatal error: Allowed memory size of 134217728 bytes exhausted (tried to allocate 1052672 bytes) in phar:///pro/bin/mcpe/pocketmine-stable-1.14.60/PocketMine-MP.phar/vendor/pocketmine/raklib/src/server/Session.php on line 492`

Because of this I can't have more than 100 players on my server for longer than 30 minutes.

**Comment by debian44** [comment]
No this isn't a support request RakLib crashes for no reason in my new server memory is free memory_limit is 2048M its also 1.4GB free and port 19132 is ready I have no clue why raklib crashes im using release 3.11.7 no plugin no unnecessary change

**Comment by ZizzyZizzy** [comment]
@justarty I want some of whatever you're smoking. You do NOT have 80 concurrent players with only 128 Megabytes of memory allocated. You would be lucky to have a single player with that small amount of memory.

This is clearly a support request based just on the error message, which is clear as day. Something is misconfigured. Go to the forums and open a thread there.

**Comment by justarty** [comment]
> @justarty I want some of whatever you're smoking. You do NOT have 80 concurrent players with only 128 Megabytes of memory allocated. You would be lucky to have a single player with that small amount of memory.
> 
> This is clearly a support request based just on the error message, which is clear as day. Something is misconfigured. Go to the forums and open a thread there.

Well thats the thing. I don't have 134 megabytes of memory allocated. I have 12 gigs.

I worked with my hosting support for a long time to figure out what might be the issue. We even moved my server from France to Germany to check if it was the hostings error but it wasn't. Also my hosting is server.pro
I have **12gb of ram and 4 cores** server (which is the best option they provide) 
This hosting doesn't let me edit php.ini (I saw that in threas https://github.com/pmmp/PocketMine-MP/issues/3052)

Also here is what server.pro support said:

> Thanks for getting back to us. After reviewing your server there does
not appear to be anything of concern that we would like to highlight.
Pocketmine is still a very new server software that is being updated
regularly with bug fixes and performance improvements, at the moment
it's likely the issue is with the server software not being able to
handle this many players as it's not very well optimised software at
the moment. We have switched IPs (which also involves switching the
machine that the server is on) so this has ruled out any issues on our
end with any hardware, and you do have plenty of resources available
for your server. The crash dump does contain errors, but nothing that
relates to specific plugins, but rather the server software.

We would recommend that you seek further advice in regards to this on
either the PMMP forums or the PMMP Discord, here you will be able to
get in touch with the developers for the server software who will be
able to advise further and help you resolve this problem. Please note
that Pocketmine is not developed by ourselves, it is developed by
third party developers.

Also here is my **pocketmine.yml** file. I have hard-memory limit set to 12000 and soft memory limit to 350 to basically always enable low-memory triggers.

I came up with these settings by testing it on my server with daily online of 75 - 160 people.

`# Main configuration file for PocketMine-MP
# These settings are the ones that cannot be included in server.properties
# Some of these settings are safe, others can break your server if modified incorrectly
# New settings/defaults won't appear automatically in this file when upgrading.

settings:
  #Whether to send all strings translated to server locale or let the device handle them
  force-language: false
  shutdown-message: "§cНе волнуйтесь! §2Это обычная перезагрузка! §lЗаходи через 10 секунд :)"
  #Allow listing plugins via Query
  query-plugins: true
  #Show a console message when a plugin uses deprecated API methods
  deprecated-verbose: true
  #Enable plugin and core profiling by default
  enable-profiling: false
  #Will only add results when tick measurement is below or equal to given value (default 20)
  profile-report-trigger: 20
  #Number of AsyncTask workers.
  #Used for plugin asynchronous tasks, world generation, compression and web communication.
  #Set this approximately to your number of cores.
  #If set to auto, it'll try to detect the number of cores (or use 2)
  async-workers: auto
  #Whether to allow running development builds. Dev builds might crash, break your plugins, corrupt your world and more.
  #It is recommended to avoid using development builds where possible.
  enable-dev-builds: false

memory:
  #Global soft memory limit in megabytes. Set to 0 to disable
  #This will trigger low-memory-triggers and fire an event to free memory when the usage goes over this
  global-limit: 350

  #Main thread soft memory limit in megabytes. Set to 0 to disable
  #This will trigger low-memory-triggers and fire an event to free memory when the usage goes over this
  main-limit: 350

  #Main thread hard memory limit in megabytes. Set to 0 to disable
  #This will stop the server when the limit is surpassed
  main-hard-limit: 12000

  #AsyncWorker threads' hard memory limit in megabytes. Set to 0 to disable
  #This will crash the task currently executing on the worker if the task exceeds the limit
  #NOTE: THIS LIMIT APPLIES PER WORKER, NOT TO THE WHOLE PROCESS.
  async-worker-hard-limit: 0

  #Period in ticks to check memory (default 1 second)
  check-rate: 60

  #Continue firing low-memory-triggers and event while on low memory
  continuous-trigger: true

  #Only if memory.continuous-trigger is enabled. Specifies the rate in memory.check-rate steps (default 30 seconds)
  continuous-trigger-rate: 30

  garbage-collection:
    #Period in ticks to fire the garbage collector manually (default 30 minutes), set to 0 to disable
    #This only affects the main thread. Other threads should fire their own collections
    period: 72000

    #Fire asynchronous tasks to collect garbage from workers
    collect-async-worker: true

    #Trigger on low memory
    low-memory-trigger: true

  #Settings controlling memory dump handling.
  memory-dump:
    #Dump memory from async workers as well as the main thread. If you have issues with segfaults when dumping memory, disable this setting.
    dump-async-worker: true

  max-chunks:
    #Cap maximum render distance per player when low memory is triggered. Set to 0 to disable cap.
    chunk-radius: 4

    #Do chunk garbage collection on trigger
    trigger-chunk-collect: true

  world-caches:
    #Disallow adding to world chunk-packet caches when memory is low
    disable-chunk-cache: true
    #Clear world caches when memory is low
    low-memory-trigger: true


network:
  #Threshold for batching packets, in bytes. Only these packets will be compressed
  #Set to 0 to compress everything, -1 to disable.
  batch-threshold: 100
  #Compression level used when sending batched packets. Higher = more CPU, less bandwidth usage
  compression-level: 35
  #Use AsyncTasks for compression. Adds half/one tick delay, less CPU load on main thread
  async-compression: true
  #Experimental, only for Windows. Tries to use UPnP to automatically port forward
  upnp-forwarding: true
  #Maximum size in bytes of packets sent over the network (default 1492 bytes). Packets larger than this will be
  #fragmented or split into smaller parts. Clients can request MTU sizes up to but not more than this number.
  max-mtu-size: 1492

debug:
  #If > 1, it will show debug messages in the console
  level: 10

player:
  #Choose whether to enable player data saving.
  save-player-data: true
  anti-cheat:
    #If false, will try to prevent speed and noclip cheats. May cause movement issues.
    allow-movement-cheats: true

level-settings:
  #The default format that levels will use when created
  default-format: pmanvil

chunk-sending:
  #To change server normal render distance, change view-distance in server.properties.
  #Amount of chunks sent to players per tick
  per-tick: 4
  #Radius of chunks that need to be sent before spawning the player
  spawn-radius: 4

chunk-ticking:
  #Max amount of chunks processed each tick
  per-tick: 40
  #Radius of chunks around a player to tick
  tick-radius: 1
  light-updates: true
  clear-tick-list: true
  #IDs of blocks not to perform random ticking on.
  disable-block-ticking:
    - 2 # grass

chunk-generation:
  #Max. amount of chunks in the waiting queue to be populated
  population-queue-size: 4

ticks-per:
  autosave: 12000

auto-report:
  #Send crash reports for processing
  enabled: true
  send-code: true
  send-settings: true
  send-phpinfo: false
  use-https: true
  host: crash.pmmp.io

anonymous-statistics:
  #Sends anonymous statistics for data aggregation, plugin usage tracking
  enabled: false #TODO: re-enable this when we have a new stats host
  host: stats.pocketmine.net

auto-updater:
  enabled: false
  on-update:
    warn-console: true
    warn-ops: true
  #Can be development, alpha, beta or stable.
  preferred-channel: stable
  #If using a development version, it will suggest changing the channel
  suggest-channels: true
  host: update.pmmp.io

timings:
  #Choose the host to use for viewing your timings results.
  host: timings.pmmp.io

console:
  #Choose whether to enable server stats reporting on the console title.
  #NOTE: The title ticker will be disabled regardless if console colours are not enabled.
  title-tick: true

aliases:
  #Examples:
  #showtheversion: version
  #savestop: [save-all, stop]

worlds:
  #These settings will override the generator set in server.properties and allows loading multiple levels
  #Example:
  #world:
  # seed: 404
  # generator: FLAT:2;7,59x1,3x3,2;1;decoration(treecount=80 grasscount=45)

plugins:
  #Setting this to true will cause the legacy structure to be used where plugin data is placed inside the --plugins dir.
  #False will place plugin data under plugin_data under --data.
  #This option exists for backwards compatibility with existing installations.
  legacy-data-dir: false
`

**Comment by dktapps** [comment]
server.pro support clearly doesn't know anything about PM.

> Pocketmine is still a very new server software 

This is bullshit, it's nearly 8 years old.

This problem comes from your php.ini which they aren't allowing you to edit. This is not a PM problem, and even if it was, this is not the right place to get help with PM problems.

I'd suggest using something other than server.pro, or consider self-hosting.
