### ISSUE TITLE
support for 1.16

### ISSUE THREAD

**Issue by Blackjack200** [pmmp/PocketMine-MP#3614]
I tried to delete protocol limit(in handlelogin and raknet) but lt is not work(may be because of startgamepacket.please support 1.16 ❤️
Documentation: http://pmmp.rtfd.io
Forums: https://forums.pmmp.io
Discord: https://discord.gg/bmSAZBG

**Comment by ZizzyZizzy** [comment]
@Blackjack200 Dont' waste the developers time they could be spending on updating the code. You and TENS OF THOUSANDS of other people are waiting **patiently** for the developers to update the code. It will be done when it's done.

Adding a support request like this and asking "when will it be done?" does not help at all. **They know the new version is out**. They are painfully aware yet. This is the equivalent of asking your parents "are we there yet" five hundred and thirty times during a road trip.

Quit being selfish and close this ticket ASAP.

**Comment by Blackjack200** [comment]
> @Blackjack200 Dont' waste the developers time they could be spending on updating the code. You and TENS OF THOUSANDS of other people are waiting **patiently** for the developers to update the code. It will be done when it's done.
> 
> Adding a support request like this and asking "when will it be done?" does not help at all. **They know the new version is out**. They are painfully aware of this fact. This is the equivalent of asking your parents "are we there yet" five hundred and thirty times during a road trip.
> 
> Quit being selfish and close this ticket ASAP.

sorry :(
