### ISSUE TITLE
!spam

### ISSUE THREAD

**Issue by WoollenPanda275** [pmmp/PocketMine-MP#3618]
@I know your probably busy with it now but any idea on when PM will support 1.16? its unplayable at the moment on some platforms.

**Comment by ManiakMCPE** [comment]
This update broke some shit as usual. So it will be at least a few days to weeks.

**Comment by tunikakeks** [comment]
Yes i really need it. The new Protocol is 400.

**Comment by ruslantopchik** [comment]
I'm waiting too update core

**Comment by mmm545** [comment]
stop asking, close the issue
have a nice day
