### ISSUE TITLE
The fences are not properly connected.

### ISSUE THREAD

**Issue by alvin0319** [pmmp/PocketMine-MP#3625]
### Issue description

- Expected result: What were you expecting to happen? When fences are installed in succession, they are connected to each other.
- Actual result: What actually happened? The fence is not connected.

### Steps to reproduce the issue
1. Join the server.
2. Install fences in a row.

### OS and versions

* PocketMine-MP: https://github.com/pmmp/PocketMine-MP/commit/c267137fde9b59ffd6951099f64117fd18af8e2e
* PHP: PHP 7.3.14 (cli)
* Server OS: Linux
* Game version: PE/Win10 (delete as appropriate)

### Plugins

- If you remove all plugins, does the issue still occur?
- If the issue is **not** reproducible without plugins:
  - Have you asked for help on our forums before creating an issue?
  - Can you provide sample, *minimal* reproducing code for the issue? If so, paste it in the bottom section

### Crashdump, backtrace or other files

![Minecraft 2020-06-26](https://user-images.githubusercontent.com/32565818/85869904-4e876780-b807-11ea-9029-4c8e58eedb85.png)

**Comment by jasonwynn10** [comment]
You didn’t read the release notes did you 🤦‍♂️

**Comment by alvin0319** [comment]
> You didn’t read the release notes did you 🤦‍♂️

Oh sorry
