### ISSUE TITLE
No skins are displayed

### ISSUE THREAD

**Issue by Gaprix** [pmmp/PocketMine-MP#3627]
### Issue description
No skins are displayed
- Expected result: Skins displayed
- Actual result: Steve skin

### Steps to reproduce the issue
1. Go to the server with a friend
2. Look at his skin

### OS and versions

* PocketMine-MP: 3.14.0
* PHP: 7.3
* Server OS: Windows 10

### Plugins
None

### Crashdump, backtrace or other files
![Screenshot_32](https://user-images.githubusercontent.com/45711510/85875183-81683600-b7dc-11ea-82d2-e84dd7381437.png)

**Comment by dktapps** [comment]
This is caused by the client's "trusted skin" setting.
