### ISSUE TITLE
Spectator players can destroy blocks client-side

### ISSUE THREAD

**Issue by Blackjack200** [pmmp/PocketMine-MP#3636]
### Issue description
In 1.16 you can break the block in gamemode 3(just in client)
- Expected result: What were you expecting to happen?
- Actual result: What actually happened?

### Steps to reproduce the issue
1. ...
2. ...

### OS and versions

* PocketMine-MP:3.14.0
* PHP:7.13.4
* Server OS:Ubuntu18.06
* Game version: Android and Win10 

### Plugins

none
- If you remove all plugins, does the issue still occur?
- If the issue is **not** reproducible without plugins:
  - Have you asked for help on our forums before creating an issue?
  - Can you provide sample, *minimal* reproducing code for the issue? If so, paste it in the bottom section

**Comment by dktapps** [comment]
After some research I've concluded that this is a client-sided bug. There hasn't been any protocol changes involving this area of the code, so that means that it's simply broken client-side.
Since PM correctly denies the block-breaking anyway, there's nothing to do here.
