### ISSUE TITLE
Bug

### ISSUE THREAD

**Issue by ipad54** [pmmp/PocketMine-MP#3637]
### Issue description
For many, when the join to the server with 1.16 internal server error
- Expected result: 
- Actual result: Internal server error on join

### Steps to reproduce the issue
1. Join to the server
2. ...

### OS and versions

* PocketMine-MP: 3.14.0
* PHP: 7.3
* Server OS: Ubuntu
* Game version: PE/Win10

### Plugins

My plugins do not conflict with this
- If you remove all plugins, does the issue still occur?
- If the issue is **not** reproducible without plugins:
  - Have you asked for help on our forums before creating an issue?
  - Can you provide sample, *minimal* reproducing code for the issue? If so, paste it in the bottom section

### Crashdump, backtrace or other files
](url)

**Comment by Bavfalcon9** [comment]
Please fill in the fields that will help developers identify your issue:Plugins
My plugins do not conflict with this

> **If you remove all plugins, does the issue still occur?**
> **If the issue is not reproducible without plugins:**
Can you provide sample, minimal reproducing code for the issue? If so, paste it in the bottom section
**Crashdump, backtrace** or other files
](url)

**Comment by dktapps** [comment]
![download](https://user-images.githubusercontent.com/14214667/85917569-17d73e80-b853-11ea-9f51-baeec966cca6.jpeg)
