### ISSUE TITLE
Chunk issue

### ISSUE THREAD

**Issue by Infernus101** [pmmp/PocketMine-MP#3641]
### Issue description

- Expected result: What were you expecting to happen? Seeing the empty void
- Actual result: What actually happened? Hitbox kinda structure is seen

### Steps to reproduce the issue
1. create an empty world
2. lookout for hitbox structure like [this](https://imgur.com/zmpTGRT)
### OS and versions

* PocketMine-MP: 3.14.0
* PHP: 7.3
* Server OS: Linux
* Game version: PE

### Plugins

- If you remove all plugins, does the issue still occur?
- If the issue is **not** reproducible without plugins:
  - Have you asked for help on our forums before creating an issue?
  - Can you provide sample, *minimal* reproducing code for the issue? If so, paste it in the bottom section

**Comment by dktapps** [comment]
Without knowing your PocketMine-MP version, OS, PHP, Client version, or plugins and how the issue occurred, the issue cannot begin to be solved.
A pre-formatted template is provided that shows the required information to begin to find, test and solve an issue.
Until the adequate template and information is provided, the issue will be closed; it may be reopened if you update the ticket with the correct template and required information.

[Contribution guidelines](https://github.com/pmmp/PocketMine-MP/blob/master/CONTRIBUTING.md)

**Comment by dktapps** [comment]
I can't reproduce this, so I'm assuming this is caused by a plugin.

**Comment by Infernus101** [comment]
https://imgur.com/a/kM8Ns1I
What even is this?
