### ISSUE TITLE
Server crashed

### ISSUE THREAD

**Issue by ZenZenXDz** [pmmp/PocketMine-MP#3646]
Hello but I need help alot my pocketmine is acting weird some say its outdated its 2.3.0 it still has the green bars when i re download it on play store it will still be the same my plugins dont work when i do /pl or /plugins it will just show some basic commands like /op 
![Screenshot_2020-06-28-12-25-51-27_87c2225eebc34d2513fa0e7ad5b93cfc](https://user-images.githubusercontent.com/66781695/85938005-b939bf80-b93b-11ea-9155-b4453b82e11b.png)
![Screenshot_2020-06-28-11-11-55-32_3686cb59f45a8f4a2b1e8d6e99664d6d](https://user-images.githubusercontent.com/66781695/85938009-c191fa80-b93b-11ea-9090-5917f6528945.png)

**Comment by ZenZenXDz** [comment]
![Screenshot_2020-06-28-11-11-59-70_846b44643ec609f507828878741e1f9a](https://user-images.githubusercontent.com/66781695/85938019-d4a4ca80-b93b-11ea-9430-1d8bed0a48c4.png)

**Comment by ZenZenXDz** [comment]
It still has the same but the worlds, plugins doesnt work

**Comment by DragonfireHD** [comment]
Why you have on the spawn-protection: -1 set this on 0

This the problem you have a Config error

**Comment by dktapps** [comment]
Without knowing your PocketMine-MP version, OS, PHP, Client version, or plugins and how the issue occurred, the issue cannot begin to be solved.
A pre-formatted template is provided that shows the required information to begin to find, test and solve an issue.
Until the adequate template and information is provided, the issue will be closed; it may be reopened if you update the ticket with the correct template and required information.

[Contribution guidelines](https://github.com/pmmp/PocketMine-MP/blob/master/CONTRIBUTING.md)

![download](https://user-images.githubusercontent.com/14214667/85941794-035f7880-b91d-11ea-95dd-d0d34656c4fc.jpeg)
