### ISSUE TITLE
Black screen on crafting

### ISSUE THREAD

**Issue by Infernus101** [pmmp/PocketMine-MP#3647]
### Issue description

- Expected result: Craft properly with no black screen.
- Actual result: Screen just goes full black randomly when trying to craft. I do not know if this is a mc bug, pardon me. 

### Steps to reproduce the issue
https://cdn.discordapp.com/attachments/539138552080891907/726585504040091699/video0.mov

### OS and versions

* PocketMine-MP: 57b6451 3.14.0
* PHP: 7.3.0
* Server OS: Linux/Ubuntu
* Game version: PE

### Plugins

- If you remove all plugins, does the issue still occur?
- If the issue is **not** reproducible without plugins:
  - Have you asked for help on our forums before creating an issue?
  - Can you provide sample, *minimal* reproducing code for the issue? If so, paste it in the bottom section

**Comment by dktapps** [comment]
Already fixed in 8480ee82eabec0ae4009d5049f7e471e5fda82df.
