### ISSUE TITLE
Mysqli not working

### ISSUE THREAD

**Issue by noremac09** [pmmp/PocketMine-MP#365]
Hello, mysql does not work in all plug-ins installed according to instructions. Sorry for the spelling errors, if any.

* PocketMine-MP: 1.0.3
* PHP: Lastest 
* Server OS: Debian

### Crashdump, backtrace or other files

* ...
ClassNotFoundException: "Class mysqli not found" (EXCEPTION) in "/src/spl/BaseClassLoader" at line 144

**Comment by dktapps** [comment]
You need to compile PHP with the mysqli extension included.
