### ISSUE TITLE
Crafting Table

### ISSUE THREAD

**Issue by vanysha7d** [pmmp/PocketMine-MP#3650]
I change the stack of gold blocks to Gold Ingot, for a quick exchange I clamp the shift (Windows 10 Edition)
Gotta get stacks of Gold Ingot, but I get minecraft crash

PocketMine-MP 3.14.1+dev

I would like to know if this is a bug of minecraft or core PM
![image](https://user-images.githubusercontent.com/40440946/85946707-a973a880-b946-11ea-8e08-a4d2397f05fa.png)

**Comment by dktapps** [comment]
Without knowing your PocketMine-MP version, OS, PHP, Client version, or plugins and how the issue occurred, the issue cannot begin to be solved.
A pre-formatted template is provided that shows the required information to begin to find, test and solve an issue.
Until the adequate template and information is provided, the issue will be closed; it may be reopened if you update the ticket with the correct template and required information.

[Contribution guidelines](https://github.com/pmmp/PocketMine-MP/blob/master/CONTRIBUTING.md)
