### ISSUE TITLE
Crafting issue

### ISSUE THREAD

**Issue by Infernus101** [pmmp/PocketMine-MP#3655]
### Issue description

- Expected result: Perfectly return the crafted items
- Actual result: It reverts and closes the window

### Steps to reproduce the issue
When crafting something that you have less than the stack of that item in your inventory and the crafting output is more than the stack, it closes the UI instead of filling that stack and making a new one.
VID: https://cdn.discordapp.com/attachments/677349923599024159/727150501032099891/Minecraft_2020-06-29_08-15-17.mp4

### OS and versions

* PocketMine-MP: 3.14.0 57b6451
* PHP: 7.3
* Server OS: Linux/ubuntu
* Game version: Win10

### Plugins

- If you remove all plugins, does the issue still occur?
- If the issue is **not** reproducible without plugins:
  - Have you asked for help on our forums before creating an issue?
  - Can you provide sample, *minimal* reproducing code for the issue? If so, paste it in the bottom section

**Comment by Govdim** [comment]
Also faced with such a problem

**Comment by dktapps** [comment]
> Please don't bother writing anything if all you have to say is "me too". It adds nothing of value to the discussion and sends useless notifications to everyone watching the repo.

**Comment by GamakCZ** [comment]
I've got similar problem, but it crashes the game. 
Video: https://streamable.com/ctwpdc

**Comment by dktapps** [comment]
has anyone tried this in vanilla?

**Comment by GamakCZ** [comment]
I will try it.

**Comment by GamakCZ** [comment]
With BDS it doesn't crash the game

**Comment by Infernus101** [comment]
doesn't crash in vanilla. Tested

**Comment by MonoAdrian23** [comment]
Same Problem, it happens mostly with Redstone and Coal when you craft much of this.

**Comment by dktapps** [comment]
Is there any debug output on the console when this happens?

**Comment by Infernus101** [comment]
`[00:34:39] [Server thread/DEBUG]: Failed to execute inventory transaction from Infern101: Action pocketmine\inventory\transaction\action\SlotChangeAction is not valid in the current transaction
[00:34:39] [Server thread/DEBUG]: Actions: [{"sourceType":0,"windowId":124,"sourceFlags":0,"inventorySlot":50,"oldItem":{"id":323,"count":6},"newItem":{"id":0,"count":0},"newItemStackId":null},{"sourceType":0,"windowId":0,"sourceFlags":0,"inventorySlot":7,"oldItem":{"id":0,"count":0},"newItem":{"id":323,"count":6},"newItemStackId":null}]
[00:34:39] [Server thread/DEBUG]: Unhandled InventoryTransactionPacket received from Infern101: HgAAAAIA+AEyhgUMAAAAAAAAAAcAhgUMAAAAAA==`

**Comment by dktapps** [comment]
It seems like this has something to do with some overlooked "magic output slot" behaviour in 1.16. When the outputs can't all fit onto the target slot, the remainder goes to "UI" slot 50.
It doesn't look like there's a straightforward way to fix this, and since the better solution appears to be to migrate to the new system, this isn't likely to get a fix in the immediate future.

**Comment by GamakCZ** [comment]
In nukkit this error doesn't appear for me

**Comment by dktapps** [comment]
That is irrelevant. This isn't the Nukkit repository.
