### ISSUE TITLE
Cannot remove fixed window 0

### ISSUE THREAD

**Issue by EinBexiii** [pmmp/PocketMine-MP#3656]
Link to crashdump: https://hastebin.com/yiguwecaca.m

### Additional comments (optional)
https://github.com/NukkitX/Nukkit/pull/1514/commits/8f047b50ce282372cfc1be052c273341ea5ab8c5
"this.getInventory().close(this);".

Through this commit, the player is kicked from the server and blocked for 5 seconds. This happens when a player is sent by Waterdog from a Pocketmine server to a Nukkit server.

**Comment by dktapps** [comment]
You seem to be lost. This is not the Nukkit repository.

**Comment by EinBexiii** [comment]
"You seem to be lost", thats not a nukkit bug. Could you actually be a little nicer?

**Comment by EinBexiii** [comment]
Thats a crash dump from pocketmine, and not from nukkit dude.
