### ISSUE TITLE
Players Inventory Cleared Bug

### ISSUE THREAD

**Issue by DragonfireHD** [pmmp/PocketMine-MP#3658]
### Issue description

- Expected result: What were you expecting to happen?
- Actual result: What actually happened?

### Steps to reproduce the issue
1. ...Inventory Bug
2. ... Inventory dont save players inventory by server join or leaving

### OS and versions

* PocketMine-MP: lastest
* PHP: lastest
* Server OS: lastest
* Game version: PE 1.16

Bug Report

The Problem is players Inventory dont save by leaving or join the server EnderChest and completely The main inventory is cleared pls fix this

**Comment by dktapps** [comment]
Without knowing your PocketMine-MP version, OS, PHP, Client version, or plugins and how the issue occurred, the issue cannot begin to be solved.
A pre-formatted template is provided that shows the required information to begin to find, test and solve an issue.
Until the adequate template and information is provided, the issue will be closed; it may be reopened if you update the ticket with the correct template and required information.

[Contribution guidelines](https://github.com/pmmp/PocketMine-MP/blob/master/CONTRIBUTING.md)
