### ISSUE TITLE
Report 2.0 for Inventory Cleared Automatically on Join or Leave or on keepinventory settings

### ISSUE THREAD

**Issue by DragonfireHD** [pmmp/PocketMine-MP#3660]
Issue description
Expected result: What were you expecting to happen?
Actual result: The Inventory Cleared automatically on join or leave
Steps to reproduce the issue
...Inventory Bug
... Inventory dont save players inventory by server join or leaving
OS and versions
PocketMine-MP: 1.16
PHP: 3.14.0
Server OS: 1.16
Game version: PE 1.16
Plugins
PocketMine-MP 3.14.0: Report 1.1; Powertools 1.0.0; ChangeDisplayName 1.0.0; Anvil 1.0.0; CommandBlockerX 1.0.0; TransferMe 1.0.0; CommandCreator 1.0.1; MIE_Protector 1.0.4; KillStreak 1.0.0; DeathCost 1.0.0; MCPEToDiscord 1.4; JobUI 1.0.2; FormImagesFix 0.0.1; WorldProtect 2.3.8; Dragons 1.0.0; UltraCapes 1.7.1; DGVoteKick 1; CompassBar 1.2; Elevator 1.0; Pickle 1.0.0-beta1; MoneyUI 2.0.0; Clothes 2.1.0; SizeUI 0.0.4; Worlds 3.0.3; CosmeticMenu 2.1; PurePerms 1.4.2; DragonGM 2.0.0; BlockParty 1.0.1_BETA; SignIt 1.1.0; SkyBlock 3.0.1; TopVoter 3.2.0; PerWorldPlayer 0.1.0; SizePlayer 1.1.0; Slapper 1.5.3; ScoreHud 5.2.0; DG-EnderChest 2.0.0; StairSeat 1.5.2; PiggyCustomEnchants 2.3.0; BossAnnouncement 2.0.4; AutoClearLagg 3.0.0; EasyHomes 3.9.0; Fishing 0.2; VRZ-MultiProtocol 1; FlyingElytra 1.0.0; DG-Friend 1.1.0; Broadcaster 1.5; Bank 2; Emotes 1.0.0; AutoEXP 0.0.1; ImageConverter 2.3.0; DG-Regeln 1; MagicTelePortal 1.3.5; DoorBell 1.0.0; DG-CommunityEvent 1.0.0; DG-ItemRepair 1.5.0; AntiVoid 1.1.0; iControlU 1.4.0; SpitzNamen 2; Gomoku 0.7.0; SimpleWarp 4.0.1; PECollide 1; DG-Booster 2.0.0; SkyBlockUI 1.1.0; Vehicles 0.1.6; KDR 1.0.0; FeedHealCMD 1; DG-EventSounds 0.4.2; DropEvent 1; DG-AntiOPkick 2; BowSound 1.1.2; CommandTracker 1.2.0; ProfileUI 4.2.2; BuilderTools 1.2.0-beta2; PlayerSelectors 1.0.7; PlayerMovements 0.0.1; BurgerLootProtection 0.0.1; EasyCommandAutofill 1.0.0-beta1; FormAPI 1.3.0; RangShopUI-DG 1.0.0; AntiSpamPro 1.4.1; NameSpaceRemover 1.0.0; VanishV2 1.4.5; EconomyAPI 5.7.2; DG-ChestShop 6.6.7; DG-PlayerClear 2.1.1; DGTempBanUI 2.3; ShulkerBox 1.0.2; EnderChestSlots 1.0.3; DG-JukeBox 1.0.1; FloatingText 1.0.0; WarpUI 3.3.1; AntiToolbox 1.0; AntiHack 1.0.0; DragonPerks 1.0.0; BetterVoting 1.6; DGSystem 1; ChatMuffler 1.0.1; SRegionProtector 1.0; DG-Crates 2.0.2; KeyMining 1.0.0; CustomAlerts 2.1; SimpleBanner 0.0.2; DG-Heads 2.4; 1vs1 1.0.1; MultiWorld 1.5.2; AlwaysAllowColorChat 0.1.0; DGRepRenMenu 1.0.2; BedrockClans 2; ProjectileTrails 2.0.0; Sheep 5.2.3; RealTime 1.1.0; RangInfo 1; DEVirion 1.2.7; PiggyCustomEnchantsShop 1.3.4; DG-Crossbow 1.1.0; AlwaysSpawn 2.2.4; PureEntitiesX 0.6.7; SeeDevice 1.1.0; Mockingbird 1; AntiCheat 1; UnderCoverTool 1.5.3; EnchantUI 0.5; MOTDShuffle 1.1.7; DG-TPA 0.0.1; RedstoneCircuit 2.0.0; MIE_Converter 1.0.2; MapImageEngine 1.1.3; DG-EPShop 2.0.0; StatsPE 1.0.0; ShadowAntiCheat 3.6.5; InvSee 1.0.0; DG-Blut 1.0.2; SlapperPlus 1.0.3; CommandSpy 1.0.0; DG-SignShop 2; PCEBookShop 1.0.0; MyPlot 1.7.0; Texter 3.4.8; PlotVote 1.1.0; PureChat 1.4.11; DG-ChatEvent 1.0.0; DG-Fly 2.0.2; OreEarn 2.0.1; PlayerWarps 1.0.1; MyPlotMenu 1.0.0; MyPlotBorders 0.1.0; MyPlotPlotHomes 0.1.0; MyPlotDumper 0.1.0

Bug Report

The Problem is players Inventory dont save by leaving or join the server EnderChest and completely The main inventory is cleared pls fix this

No Crushdumps
No Errors

**Comment by dktapps** [comment]
Cannot reproduce. Check that you have player data saving enabled in pocketmine.yml.
