### ISSUE TITLE
Server crashing

### ISSUE THREAD

**Issue by Kills4MeYT** [pmmp/PocketMine-MP#3662]
Ever since we installed the update, when ever we press something we get a internal error, even now, we can't join, we get disconnected and it says internal error on console. I got help and they said it was the event listener? Wrong code I believe, am not sure tho!

**Comment by jasonwynn10** [comment]
Event Listeners are plugin problems. Make sure your plugins are compatible with the update. It's not a PocketMine problem

**Comment by Kills4MeYT** [comment]
> Event Listeners are plugin problems. Make sure your plugins are compatible with the update. It's not a PocketMine problem

![image2](https://user-images.githubusercontent.com/67616115/86075200-7835ce00-ba55-11ea-9953-c05d36e05916.png)

So that's a pl problem, that's just part of the code but that's where I see event listener?

**Comment by Kills4MeYT** [comment]
> Event Listeners are plugin problems. Make sure your plugins are compatible with the update. It's not a PocketMine problem

Also, if it is a plug-in problem, should we just remove the plugins and wait for them to be updated or is there something we could do?

**Comment by jasonwynn10** [comment]
It's usually best to wait for an update or not update the server until the plugins support the changes. DaPigGuy is pretty quick about updates though so I'd recommend asking him about it in their discord on on their respository.

**Comment by DaPigGuy** [comment]
Already fixed on PiggyCE v2.3.0 available on Poggit =)

**Comment by SOF3** [comment]
This is not a support channel. Plugin issues are not to be discussed on this issue tracker.
