### ISSUE TITLE
Player randomly kick from server and he cannot join

### ISSUE THREAD

**Issue by b1zey** [pmmp/PocketMine-MP#3674]
I use PMMP last stable build.
Situation:
Players playing on the server and at a random moment players kick from the server and he cannot join. He got the message, in console it displayed as if player left himsef, but he not exit the game.

I check the packets, and if player have this bug server receives a unique packet - Packet Violation Warning Packet. Maybe it can help.

I use PHP 7.3 and Debian 8, PMMP last stable build. I use plugins, but this issue does not apply to them because it happened on random moments.

**Comment by dktapps** [comment]
Without knowing your PocketMine-MP version, OS, PHP, Client version, or plugins and how the issue occurred, the issue cannot begin to be solved.
A pre-formatted template is provided that shows the required information to begin to find, test and solve an issue.
Until the adequate template and information is provided, the issue will be closed; it may be reopened if you update the ticket with the correct template and required information.

[Contribution guidelines](https://github.com/pmmp/PocketMine-MP/blob/master/CONTRIBUTING.md)
