### ISSUE TITLE
RCON accepted host settings?

### ISSUE THREAD

**Issue by Crasher508** [pmmp/PocketMine-MP#3680]
##  Description
Can you add a Setting for RCON, if a client can connect from outside the Host Server or only localhost clients can connect 

## Justification
The feature brings more security for everyone who only wants to use RCON, for example, exchange between many servers on one host, but do not want the connection from outside

**Comment by jasonwynn10** [comment]
RCON is being removed from PocketMine in API 4 and moved into a separate plugin. This would be better posted there due to API 3 being in feature freeze.

**Comment by dktapps** [comment]
It doesn't really have anything to do with the API ...

**Comment by Crasher508** [comment]
Is there a release date of PocketMine API 4 ? :)

**Comment by dktapps** [comment]
It's an open source project. Giving release dates is foolish.

**Comment by Crasher508** [comment]
Where I can find it?
