### ISSUE TITLE
Hoppers affect plugins,please update

### ISSUE THREAD

**Issue by cookievirus1190** [pmmp/PocketMine-MP#3688]
Plugins that uses hopper ui/gui like minion, when i  do something like upgrade on minion plugin my Minecraft crashes,it also happens on other plugins that uses hoppers,please answer as soon as possible

**Comment by ZizzyZizzy** [comment]
@cookievirus1190 If you can't be bothered to **FOLLOW THE BUG SUBMITTING INSTRUCTIONS**, why do you expect anyone to help you?

All you're doing is wasting the time of developers that could actually be fixing bugs that someone took the time to submit in the required format. You know, all that text you erased in a selfish attempt to fix your own problem with no regard to anyone else?

Close this immediately and re-submit a proper bug report.
