### ISSUE TITLE
Crash when a player leaves the game

### ISSUE THREAD

**Issue by 2hamed** [pmmp/PocketMine-MP#369]
There is a crash everytime a player leaves the game which I have to restart the server so that I can login again.
`[Network] Stopped interface pocketmine\network\RakLibInterface due to Tried to save closed player`

My version:
`This server is running PocketMine-MP 1.6.2dev 「Unleashed」 implementing API version 3.0.0-ALPHA3 for Minecraft: PE v1.0.3.0 (protocol version 101)`

I use MineCraft PE v1.0.3

**Comment by dktapps** [comment]
This issue was fixed a couple of days ago.
