### ISSUE TITLE
Crash on join

### ISSUE THREAD

**Issue by TotherMeteor** [pmmp/PocketMine-MP#3691]
When I load pmmp and try joining I get an error and the server crashes.
the error reads: 
[07:21:54] [Server thread/CRITICAL]: UnexpectedValueException: "Duplicate key "BurnTime"" (EXCEPTION) in "vendor/pocketmine/nbt/src/tag/CompoundTag" at line 452

[crash log below]
[Wed_Jul_8-06.50.34-CEST_2020.log](https://github.com/pmmp/PocketMine-MP/files/4901122/Wed_Jul_8-06.50.34-CEST_2020.log)

**Comment by dktapps** [comment]
Your data is corrupted.

**Comment by TotherMeteor** [comment]
as in player data?

**Comment by dktapps** [comment]
Chunk data.

**Comment by TotherMeteor** [comment]
Okay, thanks
