### ISSUE TITLE
Player Can't Join

### ISSUE THREAD

**Issue by irpanXstrome** [pmmp/PocketMine-MP#3693]
![Screenshot_2020-07-11-14-08-02-984_com server auditor ssh client](https://user-images.githubusercontent.com/64006049/87219307-36c1ee80-c384-11ea-89ec-cb28133ee7e1.jpg)

**Comment by dktapps** [comment]
Without knowing your PocketMine-MP version, OS, PHP, Client version, or plugins and how the issue occurred, the issue cannot begin to be solved.
A pre-formatted template is provided that shows the required information to begin to find, test and solve an issue.
Until the adequate template and information is provided, the issue will be closed; it may be reopened if you update the ticket with the correct template and required information.

[Contribution guidelines](https://github.com/pmmp/PocketMine-MP/blob/master/CONTRIBUTING.md)
