### ISSUE TITLE
Stone wall doesn't connect

### ISSUE THREAD

**Issue by PadawanNico21** [pmmp/PocketMine-MP#3694]
### Issue description

- Expected result: Stone wall connect with other stone wall
- Actual result: Stone wall doesn't connect with other stone wall -> ![image](https://user-images.githubusercontent.com/63717504/87227690-0aff3280-c39d-11ea-87f8-47c16414e769.png)

### Steps to reproduce the issue
1. place two stone wall next to it
2. and observe

### OS and versions

* PocketMine-MP: 3.14.1 for PE
* PHP: 7.3
* Server OS: ubuntu
* Game version: Win10

**Comment by alvin0319** [comment]
https://github.com/pmmp/PocketMine-MP/blob/3.14.0/changelogs/3.14.md#known-issues-please-dont-open-issues-for-these
