### ISSUE TITLE
RakLibServer thread/NOTICE Blocked x.x.x.x for 300 seconds

### ISSUE THREAD

**Issue by minijaham** [pmmp/PocketMine-MP#3695]
### Issue description

This is so frustrating. All of a sudden, I get disconnected from my own server, saying that RakLibServer has blocked my **Own** IP Address.

Add a way to disable this stupid IP block. It's annoying as hell

**Comment by dktapps** [comment]
Without knowing your PocketMine-MP version, OS, PHP, Client version, or plugins and how the issue occurred, the issue cannot begin to be solved.
A pre-formatted template is provided that shows the required information to begin to find, test and solve an issue.
Until the adequate template and information is provided, the issue will be closed; it may be reopened if you update the ticket with the correct template and required information.

[Contribution guidelines](https://github.com/pmmp/PocketMine-MP/blob/master/CONTRIBUTING.md)
