### ISSUE TITLE
TNT doesn't ignite in a collision with an arrow in the top side

### ISSUE THREAD

**Issue by luverelle** [pmmp/PocketMine-MP#3696]
- Expected result: TNT must ignite in a collision with an arrow from above
- Actual result: By the collision arrow doesn't ignite TNT in the top side

### Steps to reproduce the issue
1. Give yourself bow with flame enchantment
2. Place TNT on the ground
3. Shoot from a bow by TNT in the top side

###version
* PocketMine-MP: 3.14.1

### Plugins

- If you remove all plugins, does the issue still occur? Yes
- If the issue is **not** reproducible without plugins:
  - Have you asked for help on our forums before creating an issue? No
[https://youtu.be/1d7vbs0ZzNc](url)

**Comment by dktapps** [comment]
Yes, this is currently not implemented.

**Comment by dktapps** [comment]
As it turns out, this was previously implemented, but incorrectly, due to a misunderstanding of `onEntityCollide` (since renamed to `onEntityInside`).

Fixed in PM5 by d0067cfac556c62bac464a3a8aadff4b70274847.
