### ISSUE TITLE
BaseInventory::contains() does not work with custom item names

### ISSUE THREAD

**Issue by Sandertv** [pmmp/PocketMine-MP#37]
### Issue description

Write a short description about the issue
I'm not sure if this is actually a bug or not, but I thought I'd just report it anyways. When coding a plugin I struggled with contains() when using a custom item name. I executed some code on interact when a player has a certain block in his inventory, and found out that it DOES work with normal name items, and it Doesn't work with custom named items. I haven't found a way yet to make it work properly. (I don't want to foreach the inventory as it will execute my code more times if the player has more of the item)

### Steps to reproduce the issue

1. Write a plugin using contains(), in this case I use it in a command
```php
case "finish":
    if($p->getInventory()->contains(Item::get(Item::STONE, 0, 1))){

    $this->getOwner()->finishQuest($p, $args[1]);
    $p->sendMessage (TF::GREEN . "You completed quest " . $args[1] . "!");
    return true;
    break;
```
2. Try to execute the code in two ways, one when you have the item with the default name, and one with the same item but with custom name. 
3. When executing with a custom item name it does not work. It does however work with $inventory->getContents() but I have a reason to not use it as I mentioned above.

### OS and versions

* PocketMine-MP: e7e476b65e457c3b5d322d05a4789d9303c362c9
* PHP: 7 (any version of it)
* Server OS: Linux
* Game version: PE (Windows 10 probably has the same issue but I didn't test that yet)

### Crashdump, backtrace or other files

* No errors or crashdumps available

**Comment by Sandertv** [comment]
Sorry for the code block not exactly working out...

**Comment by legoboy0215** [comment]
Because of this, I had to resort to other methods like iterating through the player's inventory.

**Comment by SOF3** [comment]
Why would you run `break;` after a `return true;` statement :confused: it is dead code.

**Comment by Intyre** [comment]
It works fine for me.
```
public function onCommand(CommandSender $sender, Command $command, $label, array $args){
    if(!($sender instanceof Player)){
       $this->getLogger()->info("Not a Player!");
       return true;
    }
    switch($command->getName()){
        case "ic":
           $item = Item::get(Item::STONE, 0, 1);
           if(!$sender->getInventory()->contains($item)){
               $this->getLogger()->info("Item not found");
               $sender->getInventory()->addItem(clone $item);
           }

           $item->setCustomName("Not stone");
           if(!$sender->getInventory()->contains($item)){
               $this->getLogger()->info("Item with custom name not found");
               $sender->getInventory()->addItem(clone $item);
           }
           return true;
        case "ci":
           $sender->getInventory()->clearAll();
           return true;
        default:
           return false;
    }
}
```

**Comment by Sandertv** [comment]
Hmmm I must have done something wrong then...
