### ISSUE TITLE
Can't create more than one FloatingTextParticle's

### ISSUE THREAD

**Issue by sero583** [pmmp/PocketMine-MP#370]
### Issue description
When I tried to create two FloatingTextParticle it didn't worked and it just showed me one, no error message or anything else came though. Also every entity has a flying emerald on it, except player probably it's height is that big that it gets invisible, during use of elytra (tested on other forks) it's visible.

### Steps to reproduce the issue
Create more than one FloatingTextParticle

### OS and versions
* PocketMine-MP: This server is running PocketMine-MP 1.6.2dev 「Unleashed」 implementing API version 3.0.0-ALPHA3 for Minecraft: PE v1.0.4.0 beta (protocol version 101)
* PHP: 7.0.3
* Server OS: Ubuntu 16.04
* Game version: PE and Win10

### Off-topic (not part of the issue)
Are minecarts etc. planned?

**Comment by MrPowerGamerBR** [comment]
As far as I know this is a 1.0.4.0 issue, doesn't happen in 1.0.3.0.

**Comment by dktapps** [comment]
1.0.4 is in beta, it is not supported.

**Comment by sero583** [comment]
@MrPowerGamerBR That with the floating text particle or that with the emeralds?

**Comment by MrPowerGamerBR** [comment]
@sero583 the emeralds, I remember dktapps asking if anyone had this issue in 1.0.4.0 at MiNET's gitter, so I assume it is a 1.0.4.0 issue.
