### ISSUE TITLE
Armor dont save after Quiting from server and rejoin the Armor is gone😕

### ISSUE THREAD

**Issue by DragonfireHD** [pmmp/PocketMine-MP#3700]
### Issue description

- Expected result: The Armor mus save after Quiting ?

### Schritte zum Reproduzieren des Problems
1. https://youtu.be/QPvUJsCOvOo
2. Armor BUG armor dont save after quiting from server

### OS and versions

* PocketMine-MP: 3.14.2
* PHP: dont now but have all Lastest Version
* Server OS: Lastest Version
* Game version: PE 

### Plugins
 I removed all Inventory Plugins but Nothing changed players leave the server for this bug

### Crashdump, backtrace or other files
No Crush dumps but i have video from bug 
https://youtu.be/QPvUJsCOvOo

Sorry for the music in this Video

**Comment by dktapps** [comment]
Test for the bug without **any** plugins. Don't just remove the ones you think could be the problem.
