### ISSUE TITLE
ps4 players can't play

### ISSUE THREAD

**Issue by mote166** [pmmp/PocketMine-MP#3706]
### Issue description

- Expected result: ps4 players being able to play
- Actual result: they only join then disconnect due to timed out and thier client crashes, all my plugins are untouched since mcpe 1.14.0 but after updating to 1.16 it started to happen.

### Steps to reproduce the issue
1. join via a ps4
2. you will join then the client will crash

### OS and versions

* PocketMine-MP: 3.14.2
* PHP: 7.3
* Server OS: linux
* Game version: PS4

### Plugins

- If you remove all plugins, does the issue still occur? i didn't try since i haven't changed anything in the plugins since mcpe 1.14.60 (when they could join and play without issues)
- If the issue is **not** reproducible without plugins:
  - Have you asked for help on our forums before creating an issue? no
  - Can you provide sample, *minimal* reproducing code for the issue? If so, paste it in the bottom section

**Comment by dktapps** [comment]
I can't join via PS4, I don't have one.

**Comment by dktapps** [comment]
Closing this since there's nothing I can do about it. Try removing your plugins.
