### ISSUE TITLE
Can break block in item farmes when BlockBreakEvent is Cancelled

### ISSUE THREAD

**Issue by TanToan99** [pmmp/PocketMine-MP#371]
### Issue description
Can break block in item farmes when BlockBreakEvent is Cancelled
### Steps to reproduce the issue
Use plugin with BlockBreakEvent setCancelled(true);
put item in item frames and break it
Item in item farmes will drop 
### OS and versions
* PocketMine-MP: 
* PHP: 7.0.3
* Server OS: linux
* Game version: PE/Win10 1.0.3

### Crashdump, backtrace or other files

* ...

**Comment by dktapps** [comment]
This issue is not valid, item frame item removal != block break. That was a stupid Genisys hack.

**Comment by daniktheboss** [comment]
Then what do we use

**Comment by MrPowerGamerBR** [comment]
@daniktheboss ItemFrameDropItemEvent

**Comment by dktapps** [comment]
ItemFrameDropItemEvent doesn't exist in PocketMine-MP, and I don't plan to add it since Mojang have stated that item frame removal interaction will be altered. In the meantime, you could use DataPacketReceiveEvent.
