### ISSUE TITLE
Add Level name in crash report

### ISSUE THREAD

**Issue by dadodasyra** [pmmp/PocketMine-MP#3711]
The errors related to chunk etc errors contain the region number but not the name of the Level, only a variable not understood by a human.
The name of the level concerned should be added to the Backtrace.
For example I have a problem with a corrupted slapper and here is the most important info of the Backtrace:
`#9 src/pocketmine/level/Level(2543): pocketmine\level\Level->sendChunkFromCache(integer 13, integer 11)`

Much easier to deal with the problem knowing where it is, don't you think?

**Comment by dktapps** [comment]
Not really. A Level works the same way regardless of what its name is.
