### ISSUE TITLE
Hardcore BAN

### ISSUE THREAD

**Issue by AlexSima003** [pmmp/PocketMine-MP#3713]
### Issue description

- Expected result: What were you expecting to happen?
- Actual result: What actually happened?

### Steps to reproduce the issue
1. I was expecting to respawn.
2. I jumped in the void and i got banned. (It's happening only when hardcore is enabled in settings)

### OS and versions
 This server is running PocketMine-MP 3.14.2 for Minecraft: Bedrock Edition v1.16.0 (protocol version 407)
* PocketMine-MP: 3.14.2
* PHP: 7.3
* Server OS: Android
* Game version: PE/Win10 

### Plugins
 Plugins (8): DevTools v1.14.0, LionChatInterval v1.0.1, LionEssentials v1, LionJoin v1.1.0, LionMCTitle v0.0.1, LionMOTD v0.0.1, LionXYZ v0.7.0, SpawnLion v0.0.1

- If you remove all plugins, does the issue still occur? Yes.
- If the issue is **not** reproducible without plugins:
  - Have you asked for help on our forums before creating an issue?
  - Can you provide sample, *minimal* reproducing code for the issue? If so, paste it in the bottom section

**Comment by ZizzyZizzy** [comment]
@AlexSima003 Perhaps you're unfamiliar with how hardcore mode works?

https://minecraft.gamepedia.com/Hardcore

**Comment by AlexSima003** [comment]
Oh, now i understand
Still..hardcore exist for servers..why? 
I mean..
