### ISSUE TITLE
Player in Spectator gamemode hits air and sound is heard by other players

### ISSUE THREAD

**Issue by Gianluxx** [pmmp/PocketMine-MP#3715]
### Issue description

- Expected result: Sound is not heard by players
- Actual result: Sound is heard by players

### Steps to reproduce the issue
1. Set gamemode 3 (spectator)
2. Hit air near other players
3. Listen from the other players

### OS and versions

* PocketMine-MP: 3.14.1
* PHP: 7
* Server OS: Linux
* Game version: PE and Win10

**Comment by dktapps** [comment]
This is fixed by 0b92e96e14a30fd3537ff35cc4cd0edd506ba75a. (Sorry, I won't be backporting the fix to 3.x.)
