### ISSUE TITLE
The player does not spend food

### ISSUE THREAD

**Issue by agentboy** [pmmp/PocketMine-MP#3716]
### Issue description

- Expected result: The food level does not have to regenerate indefinitely.
- Actual result: Food level is infinitely regenerated and not wasted, which also leads to infinite health recovery.

### Steps to reproduce the issue
1. Just run, take damage, etc.

### OS and versions
* PocketMine-MP: PocketMine-MP 3.14.2
* PHP: 7.3
* Server OS: Ubuntu 20.04

**Comment by Gianluxx** [comment]
NoHunger plugin? Level difficulty?

**Comment by agentboy** [comment]
Level difficulty, sorry
