### ISSUE TITLE
BlockPlaceEvent is still fired when placement might fail

### ISSUE THREAD

**Issue by AyzrixYTB** [pmmp/PocketMine-MP#3719]
### Issue description

- Expected result: What were you expecting to happen? Just give money when a player place a seed on a FarmLand 
- Actual result: What actually happened? The player win money if he try to place it on an another block

### Steps to reproduce the issue
1. Make a simple plugin when u var_dump($event->isCancelled()) in a BlockPlaceEvent
2. Try to place a seed on a block ( Not a simple FarmLand ) you can try on a log , wool , glass,...
3. Look your var_dump , the event is not cancelled.

### OS and versions

* PocketMine-MP: 3.14.2
* PHP: 7.3.19
* Server OS: Debian 9
* Game version: PE/Win10

### Plugins

Plugins (3): AllAPILoader v1.0.0, DevTools v1.13.5, PluginTest v1 (PluginTest is just the step)
- If you remove all plugins, does the issue still occur? Yes

**Comment by SOF3** [comment]
PHP 7.0? Are you sure?

**Comment by AyzrixYTB** [comment]
> PHP 7.0? Are you sure?

Oupsi :') 7.2 i know

**Comment by Gianluxx** [comment]
Can't you just check if getBlock() is farmland in your plugin?

**Comment by dktapps** [comment]
relates to #1760

This is not an easy nut to crack because block placement may be aborted due to not being able to find a valid state (e.g. torch with no supporting block) and it's not clear what the result should be in cases where it's uncancelled.

**Comment by dktapps** [comment]
I think the more logical behaviour in this case would be to not fire the event in the first place. If a plugin wants items to be placed by a plugin that wouldn't ordinarily, they can use PlayerInteractEvent and setBlock.

**Comment by dktapps** [comment]
This was fixed in 4.0.0 as a side effect of d96fc17339fe45f01ebc8fedcd7872de4158aa65.
