### ISSUE TITLE
list command bug when player locks an unlocks phone

### ISSUE THREAD

**Issue by dunklesToast** [pmmp/PocketMine-MP#372]
### Issue description
When a Player joins the server, list says 1/50 players - everything ok.
When he locks (and i think in multitasking too) the server says disconnected and lists 0/50.
When he unlock his phone he is still on the server and can play but isn't listed!

### Steps to reproduce the issue
1. Join the Server
2. Lock your phone - wait until it says 'left the game'
3. Unlock your phone - you are still on server but it doesnt prints 'joined the game'

### OS and versions
* PocketMine-MP: 1.6.2dev
* PHP: 7.0.16-1dotdeb+8.1
* Server OS: debian
* Game version: iOS Version 1.0.3 - tested on iPhone 7+

**Comment by dktapps** [comment]
If you wait long enough the game will tell you you have been disconnected. If not, then that's most likely an issue with your client.

**Comment by robske110** [comment]
This is iOS specific. For some reason the client doesn't notice it has disconnected and just continues as if it is an SP game. (Well, not really it doesn't generate chunks etc.) It will never timeout though.
