### ISSUE TITLE
Missing Items

### ISSUE THREAD

**Issue by JamesLian-exe** [pmmp/PocketMine-MP#3724]
## Description
There are missing items in the game as of right now.
-Lantern
-Soul Lantern
-Soul Torch
-Ancient Debris
-Crying Obsident
-Netherite scrap
-Campfire
-Stripped Logs
And more.

## Justification
My friend really wants the torches and the lanterns, plus a lot of the stuff is required to beat the game. Plus we want people to play together in the new update, but none of the items are in the game.

**Comment by IceCruelStuff** [comment]
Those items are not implemented yet

**Comment by dktapps** [comment]
This is not an API change request. Also, see https://github.com/pmmp/PocketMine-MP/blob/stable/changelogs/3.14.md#known-issues-please-dont-open-issues-for-these
