### ISSUE TITLE
If you break a bed the player stills sleeping

### ISSUE THREAD

**Issue by JohnnyX071** [pmmp/PocketMine-MP#3725]
Hello, today I saw in my server that if its night time and a player goes to sleep, another player breaks his bed, he stills sleeping he doesnt wake up check those sceenshots for proof:
![Screenshot_5](https://user-images.githubusercontent.com/63922728/88381067-59a1c900-cdae-11ea-8fbd-5138b3cb1341.png)
![Screenshot_6](https://user-images.githubusercontent.com/63922728/88381072-5ad2f600-cdae-11ea-86ef-db6a034336d9.png)
![Screenshot_7](https://user-images.githubusercontent.com/63922728/88381077-5c042300-cdae-11ea-8201-26f4648f2963.png)
![Screenshot_8](https://user-images.githubusercontent.com/63922728/88381082-5eff1380-cdae-11ea-80ed-88895d8ca484.png)

**Comment by JohnnyX071** [comment]
Umm sorry my  faoult, 1st screenshot doesnt have to do with the bug!

**Comment by dktapps** [comment]
Without knowing your PocketMine-MP version, OS, PHP, Client version, or plugins and how the issue occurred, the issue cannot begin to be solved.
A pre-formatted template is provided that shows the required information to begin to find, test and solve an issue.
Until the adequate template and information is provided, the issue will be closed; it may be reopened if you update the ticket with the correct template and required information.

[Contribution guidelines](https://github.com/pmmp/PocketMine-MP/blob/master/CONTRIBUTING.md)
