### ISSUE TITLE
Everyone’s skin is Steve. 

### ISSUE THREAD

**Issue by Dapro718** [pmmp/PocketMine-MP#3727]
### Issue description

- Expected result: Everyone’s skin should be seen as the skin the choose in the Minecraft Character Creator.
- Actual result: Each player can see the correct skin on themselves, but everyone else appears to have the Steve skin. 

### Steps to reproduce the issue
1. Join a server using the pocketmine software (no spoon)/
2. Look at someone else not using the Steve skin, and you will see the Steve skin.

### OS and versions

* PocketMine-MP: 3.14.2
* PHP: 7.3.19
* Server OS: Windows
* Game version: PE/Win10

### Plugins

Plugins (26): PerWorldPlayer v0.1.2, RankText v1.0.0, DevTools v1.14.0, DoEmote v1.0.0, WorldTP v1.0.0, ScoreHud v5.2.0, SimpleWarp v4.0.1, BravoClan v1.0, MyPlot v1.7.1, Vehicles v0.1.6, VanishV2 v1.10, status v1.0.0, PurePerms v1.4.3, RenameItems v2.0, PureChat v1.4.11, MultiWorld v1.5.2, BlocksConverter v2.1.0, BlockSniper v3.2.3, SizePlayer v1.1.0, BuilderTools v1.2.0-beta2, Football v1.1.0, CommandLogger v0.0.2, PlayerTags v1.0.7, SlapperPlayerCount v2.1.3, SocialSpy v1.0.0, Slapper v1.6.0

- If you remove all plugins, does the issue still occur? Yes

**Comment by dktapps** [comment]
Make sure to disable `Only Allow Trusted Skins` in your device settings.

**Comment by AdamWelles** [comment]
Where do I find the device settings?

**Comment by Erkam246** [comment]
![IMG_20200726_010744](https://user-images.githubusercontent.com/16340573/88467903-79370f80-cedc-11ea-9182-e49cecaad948.jpg)
Disable this Option

**Comment by AdamWelles** [comment]
Thank you.  I was looking for a device setting file on my server.
