### ISSUE TITLE
No border?

### ISSUE THREAD

**Issue by daniktheboss** [pmmp/PocketMine-MP#373]
Just an idea, what if we add a border limit a user can change? PC has it why not PE.

**Comment by MrPowerGamerBR** [comment]
Why add it to PocketMine-MP if plugins can already do that?

It will only be added to PocketMine-MP if vanilla has it, if it doesn't, then there is no reason to add it.

**Comment by dktapps** [comment]
Since there is no actual way to limit the world in PE (no nice border effects in PE yet,) I don't think adding hacks for this to the core is a good idea, especially as when stated above ^ a good plugin developer could write an implementation of this on their own.

**Comment by daniktheboss** [comment]
Just has an idea... I know plugins can do this.. OK thx
