### ISSUE TITLE
Bug with an item in hand

### ISSUE THREAD

**Issue by Govdim** [pmmp/PocketMine-MP#3730]
### Issue description

- Expected result: The item in hand is updated for other players
- Actual result: The item in some situations does not change in hand for other players

If the player changes the slots of the hotbar or the setItemInHand() function is used, then everything works correctly.
But if the item has hit the player's hand from the ground or was issued by the addItem() function, these changes are not visible to other players.

### OS and versions
* PocketMine-MP: 4.0.0
* PHP: 7.3
* Server OS: Ubuntu 18.04
* Game version: PE/Win10

### Plugins
Nope

**Comment by dktapps** [comment]
I've known about this bug for a while.

**Comment by dktapps** [comment]
This was fixed by 01c867b60853511443868724c97ba7ffe28aa74a.
