### ISSUE TITLE
update.pmmp.io/api is down

### ISSUE THREAD

**Issue by SergeShkurko** [pmmp/PocketMine-MP#3732]
1. `update.pmmp.io`  is down
<img width="800" alt="Снимок экрана 2020-07-27 в 20 23 06" src="https://user-images.githubusercontent.com/18213789/88571969-1910ac80-d047-11ea-802f-36631bbbf777.png">

2. I also have a question, is there a source code repository for `update.pmmp.io/api`?

**Comment by SOF3** [comment]
Duplicate of #3731
