### ISSUE TITLE
login timeout/packet processing error when use glub-glub headwear skin

### ISSUE THREAD

**Issue by padreon** [pmmp/PocketMine-MP#3733]
### Issue description

- Expected result: can join the server
- Actual result: login timeout on PM3 and Packet processing error (Error ID: 0b429a2235be on) PM4

### Steps to reproduce the issue
1. add Glub Glub Headwear on your skin
2. join pocketmine server

### OS and versions

tested on test.pmmp.io:19132/19133

![image](https://user-images.githubusercontent.com/19891373/88674545-86424180-d11c-11ea-98ea-cadda309373e.png)
![image](https://user-images.githubusercontent.com/19891373/88674615-99551180-d11c-11ea-92b5-e2eb80d22e80.png)

**Comment by UnknownOre** [comment]
i can confirm this

**Comment by dktapps** [comment]
My initial investigation shows that this skin's data is larger than the 2 MB decompression size limit (which was imposed to prevent zip bomb attacks).

**Comment by Govdim** [comment]
> My initial investigation shows that this skin's data is larger than the 2 MB decompression size limit (which was imposed to prevent zip bomb attacks).

This problem occurs with other skins as well.

**Comment by TarochanChannel** [comment]
In my case, I got "Login timeout" and could not join.
Here is another skin.

**Comment by Grantrocks** [comment]
OMG i am so glad i found this im wearing a complete custom skin

**Comment by dktapps** [comment]
This should be fixed by https://github.com/pmmp/PocketMine-MP/commit/b77193b9876fe44bfde9eb6adc30fa48ae494a23

**Comment by jarne** [comment]
@dktapps I was able to reproduce this on latest PocketMine 5.37.3 with client v1.21.124. When a player joins with the skin on the attached screenshot, the client fails to connect and shows a packet processing error:

```
[11:57:49.330] [Server thread/INFO]: [NetworkSession: 1.2.3.4 9690] Session opened
[11:57:50.147] [Server thread/INFO]: [NetworkSession: 1.2.3.4 9690] Session closed: Bad packet: Compressed packet batch decode error: Failed to decompress data (Error ID: 0548-ccfc-a371)
[11:57:50.176] [RakLib thread/NOTICE]: Blocked 1.2.3.4 for 5 seconds
```

Problematic skin:

<img width="1197" height="718" alt="Image" src="https://github.com/user-attachments/assets/b2738a53-43da-410b-b4a1-3addce93bfaf" />

The player is able to join the server after switching to a "default" skin.

**Comment by dktapps** [comment]
There's always gonna be absurd skins that run into the limit. For now the limit is high enough for most people not to be affected. If it continues to be raised, it becomes useless as a denial-of-service prevention measure.

Also, please don't necropost...
