### ISSUE TITLE
Reversing hits

### ISSUE THREAD

**Issue by IamMagesticChicen** [pmmp/PocketMine-MP#3740]
Reverse hits, reversing hits. 

- Expected result: Hit the player, player gets hit
- Actual result: Hit reverts onto the player entirely, if you hit them it hits you not them turns on you 

### Steps to reproduce the issue
Non existent, spontaneous bug

### OS and versions
* PocketMine-MP: Most recent 3.14.2
* PHP: Unkown
* Server OS: Uknown
* Game version: IOS, Win10, Android

- If you remove all plugins, does the issue still occur? Uknown
- If the issue is **not** reproducible without plugins: Unknown
  - Have you asked for help on our forums before creating an issue? No
  - Can you provide sample, *minimal* reproducing code for the issue? If so, paste it in the bottom section

Cant

### Crashdump, backtrace or other files

No crash

**Comment by IamMagesticChicen** [comment]
Sorry for minimal info

**Comment by dktapps** [comment]
Test it without plugins before opening an issue.
