### ISSUE TITLE
Android app issue

### ISSUE THREAD

**Issue by G4-Synix** [pmmp/PocketMine-MP#3751]
### Issue description

- Expected result: app to create a folder
- Actual result: the app won't create the folder with all the files, so it can't start the server

### Steps to reproduce the issue
1. Download the app
2. Open it
3. Start the server

### OS and versions

* PocketMine-MP: 3.3.0
* PHP:idk
* Server OS:android
* Game version: PE/Win10

### Plugins
none

- If you remove all plugins, does the issue still occur?
- If the issue is **not** reproducible without plugins:
  - Have you asked for help on our forums before creating an issue?
  - Can you provide sample, *minimal* reproducing code for the issue? If so, paste it in the bottom section

**Comment by dktapps** [comment]
We don't have an app. Whatever you're using is made by a third party.
