### ISSUE TITLE
Craft Stack Error

### ISSUE THREAD

**Issue by ZEHNNNN** [pmmp/PocketMine-MP#3754]
I Cant Craft Item More Than 63 if I craft 63 i cant craft the same item more than 1 if i craft 2 it will dispear and go back to the original block example i have 1stack block of gold i put 1 stack block of gold to crafting table i can craft only 63 item and all item will go to block of gold

**Comment by dktapps** [comment]
Without knowing your PocketMine-MP version, OS, PHP, Client version, or plugins and how the issue occurred, the issue cannot begin to be solved.
A pre-formatted template is provided that shows the required information to begin to find, test and solve an issue.
Until the adequate template and information is provided, the issue will be closed; it may be reopened if you update the ticket with the correct template and required information.

[Contribution guidelines](https://github.com/pmmp/PocketMine-MP/blob/master/CONTRIBUTING.md)

**Comment by ZEHNNNN** [comment]
Pocketmine Ver 1.16.0 And i just move my plugins to another folder and it still not working

**Comment by ZEHNNNN** [comment]
Client Version 1.16.0
