### ISSUE TITLE
Pocketmine doesn't work for beta versions

### ISSUE THREAD

**Issue by DimBis** [pmmp/PocketMine-MP#3755]
### Issue description

- Expected result: Let you join
- Actual result: Did not let you join

### Steps to reproduce the issue
1. the video below explains

### OS and versions

* PocketMine-MP: 3.14.2 
* PHP: 7.3
* Server OS: Android

### Plugins
- If you remove all plugins, does the issue still occur? Yes

### Crashdump, backtrace or other files
- https://youtu.be/ckY0p-_Iw2E

Notice: That video is not mine.

**Comment by dktapps** [comment]
Betas aren't supported.
