### ISSUE TITLE
Fatal error: Encountered unknown non-copyable constant type in Unknown on line 0

### ISSUE THREAD

**Issue by EzzyKillS** [pmmp/PocketMine-MP#3759]
### Issue description
i got this error when i open a server "Fatal error: Encountered unknown non-copyable constant type in Unknown on line 0"
port forwarding i have good configured because normal bedrock server work fine and now idk what is wrong any solutions? 
![image](https://user-images.githubusercontent.com/69380231/89703990-6eef2980-d950-11ea-824d-c6fde73606a4.png)
when i click any key console shutdown help

### OS and versions

* PocketMine-MP: 3.14.2
* PHP: 7.3
* Server OS: win10

**Comment by NaufalBlaze** [comment]
mkdir pmmp && cd pmmp && wget https://jenkins.pmmp.io/job/PHP-7.3-Linux-x86_64/lastSuccessfulBuild/artifact/PHP_Linux-x86_64.tar.gz && tar -xvf PHP_Linux-x86_64.tar.gz && rm PHP_Linux-x86_64.tar.gz && wget https://github.com/pmmp/PocketMine-MP/releases/download/3.14.2/PocketMine-MP.phar && wget https://github.com/pmmp/PocketMine-MP/releases/download/3.14.2/start.sh && chmod +x ./start.sh && ./start.sh

**Comment by NaufalBlaze** [comment]
Copy And Paste In You Linux

**Comment by dktapps** [comment]
Please set `debug.level` to `2` in your `pocketmine.yml` and run the server again. I need to see what debug stuff is logged.

**Comment by dktapps** [comment]
Fixed by pmmp/pthreads@45579e1e622acd80f9c880f3a025ba3b98b8ebef, thanks.
