### ISSUE TITLE
Kick for flying

### ISSUE THREAD

**Issue by bioaim4** [pmmp/PocketMine-MP#376]
Please fix this issue or make an option to turn it off.
Players are getting kick for flying when jumping multiple times or when server lags it thinks where flying and we get kicked please fix this issue asap players hate it.

**Comment by dktapps** [comment]
1. there _is_ an option, you clearly haven't looked hard enough.
2. you did not follow the issue template. The issue template is provided to show you what information we require to find, test and resolve an issue.
