### ISSUE TITLE
I have a Chunk Problem on My Server 

### ISSUE THREAD

**Issue by DragonfireHD** [pmmp/PocketMine-MP#3761]
I have a Chunk Problem on my Server the Chunks load to long. i Spawn in the Lobby but i have for 3 Sekunds a Whitescreen the Chunks load so Long Players left the Game

Can anybody someone help or what i can do for the Problem

The other players have exactly the same problem

**Comment by DragonfireHD** [comment]
![Screenshot_20200807_214943_com mojang minecraftpe](https://user-images.githubusercontent.com/50929188/89720230-37c05d00-d9d0-11ea-97bc-eb3834f6a322.jpg)


Chunk Picture after Spawning

**Comment by Willoxey** [comment]
How much RAM does your server has?
Maybe it's cuz of your host specs.
