### ISSUE TITLE
1.16.20 Release on AppStore |We can not join we server 😕

### ISSUE THREAD

**Issue by DragonfireHD** [pmmp/PocketMine-MP#3768]
## Description
the Minecraft app have a new UPDATE 1.16.20 but now we can not join our server i come to you for ask if you can implement the new Update? 

## Justification
It is good because othee people can join for the new Update  the Server and can play on the Server

**Comment by ZizzyZizzy** [comment]
@DragonfireHD Quit being selfish.

You completely ignored all the text that explains how to open an issue and that **THIS IS NOT FOR SUPPORT**.

Close this immediately and quit wasting the developers' time. We all want them to update ASAP, but having to deal with this selfish, non-issue BS only slows them down.

**Comment by dktapps** [comment]
same shit, different update...
