### ISSUE TITLE
Various blocks (mostly plants) crash the server if grown at the top of the world

### ISSUE THREAD

**Issue by dktapps** [pmmp/PocketMine-MP#3775]
### Issue description
The following types of plant make no effort to check for world bounds, leading to undefined behaviour on PM3 and crashes on PM4:
- sugarcane
- tallgrass
- cactus

On PM4, we address this problem using a `BlockTransaction`.

**Comment by buchwasa** [comment]
May want to do something about this issue: https://github.com/pmmp/PocketMine-MP/issues/3294

**Comment by dktapps** [comment]
This is fixed by de6d260b760e8c9e29fe6d9835f5b4d351af84e2 and 014317381fffa89257b5c6fb5ccbeb9abf9b3bc7.
