### ISSUE TITLE
You can put out the fire from blocks in GM3

### ISSUE THREAD

**Issue by Willoxey** [pmmp/PocketMine-MP#3778]
### Issue description

- Expected result: What were you expecting to happen? Try to put out the fire from a block in Spectator Mode(/gamemode 3) and the fire does not turn off/put out.
- Actual result: What actually happened? The fire went out

### Steps to reproduce the issue
1. Place a block
2. Light the block
3.- /gamemode 3
4. Hit the upper side of the block(where the actual fire is)
5. The fire will turn off 

### OS and versions

* PocketMine-MP: 3.15.0
* PHP: 7.3
* Server OS: Linux
* Game version: Tried it on Android and Windows 10. Got same result.

### Plugins

It has been tested on a fresh server without plugins, so.

- If you remove all plugins, does the issue still occur? Yes
- If the issue is **not** reproducible without plugins:
  - Have you asked for help on our forums before creating an issue?
  - Can you provide sample, *minimal* reproducing code for the issue? If so, paste it in the bottom section

**Comment by UnknownOre** [comment]
i can confirm it
