### ISSUE TITLE
Cannot play local MCPE worlds from an Android Tablet on PocketMine-MP

### ISSUE THREAD

**Issue by n0tabug** [pmmp/PocketMine-MP#378]
### Issue description

I am unable to upload a world from MCPE on my Android Table for use with PocketMine-MP.  I have tried several versions of Picket-Mine-MP v0.11 thru v.014, I have upgraded and downgraded MCPE on my Android tablet thru different versions supported by PocketMine-MP.  Each time I connect to the server the world I have transfered from my tablet to the server does not load.  Instead some completely different world is loaded.

### Steps to reproduce the issue

1. On your android table navigate to your MCPE world folder, take a copy of all the files contained in this folder and upload it to the PocketMine-MP world directory
2. Now Restart PocketMine-MP so the world is loaded
3. Connect to the server from your MCPE Android Tablet and try to play the world you just uploaded

Instead of seeing the world as you would see it locally on your tablet, you are in some completely different world.

I have verified and re-verified all the server.properties settings are correct and have tried every conceivable combination of server software and MCPE version trying to get this working but it seems the server cannot read or understand the local MCPE file format from the Android tablet.

Its as though Pocket-Mine-MP cannot read or understand the raw file format of a MCPE world coming straight off the Android filesystem.

### OS and versions
* PocketMine-MP: 1.0.0.16 AND 1.0.3.0
* Server OS: CentOS 6
* Game version: MCPE on Android Tablet 1.0.0 and 1.0.3

**Comment by robske110** [comment]
yes, PM is _currently_ not able to read leveldb worlds (the worlds the mcpe client creates). This is because porting&compiling the extension for PHP7.0 is still a WIP and highly time consuming and frustrating. https://github.com/pmmp/PocketMine-MP/projects/1

**Comment by dktapps** [comment]
@robske110 incorrect, support for LevelDB is present.

However, the LevelDB PHP extension must be compiled with your server PHP in order to use this feature.

**Comment by n0tabug** [comment]
@dktapps thanks for the reply, are you saying that this does work but that I have just missed a step of compiling the LevelDB PHP extension?  Is there any more information you can share on this?  I would love to get this working.

**Comment by dktapps** [comment]
Yes, but compiling leveldb can be a bit of a headache, regardless of platform. The extension is also unstable, which is why we don't currently package it with our PHP builds. WIP.

**Comment by n0tabug** [comment]
@dktapps - WIP, understood, thanks all for the efforts and for the fast replies too.  Looking forward to one day having working support for these worlds, lots of time spent creating them locally would be amazing to be able to host and play them on a Linux server.  Very much appreciate all the effort and hard work.  Cheers!

**Comment by benwelch** [comment]
@dktapps could you, or anyone else, please explain to me how I compile php with the leveldb bindings. I don't really know what I'm doing and someone pointing me in the right direction would be greatly appreciated.
