### ISSUE TITLE
Installation bug

### ISSUE THREAD

**Issue by anton2007** [pmmp/PocketMine-MP#3783]
### Issue description

- Expected result: What were you expecting to happen?
- Actual result: What actually happened?

### Steps to reproduce the issue
1. ...
pmmp can't be installed
2. ...
not running without installer

### OS and versions

* PocketMine-MP: 1.4.1
* PHP: 7.4.9
* Server OS: Linux 4.6.1.3
* Game version: PE 0.10.5

### Plugins

- If you remove all plugins, does the issue still occur?
- If the issue is **not** reproducible without plugins:
  - Have you asked for help on our forums before creating an issue?
  - Can you provide sample, *minimal* reproducing code for the issue? If so, paste it in the bottom section

### Crashdump, backtrace or other files

![Screenshot_2020-08-20_205030](https://user-images.githubusercontent.com/37032392/90780213-7cc98500-e328-11ea-8736-a3e7f0058ad7.jpg)
![Screenshot_2020-08-20_183648](https://user-images.githubusercontent.com/37032392/90780437-8c48ce00-e328-11ea-8177-4971c719b361.jpg)

**Comment by dktapps** [comment]
We don't support those old versions.
