### ISSUE TITLE
Tool damages are calculated incorrectly

### ISSUE THREAD

**Issue by dktapps** [pmmp/PocketMine-MP#379]
Hitting a mob with shears, bow or flint&steel will cause the item to take damage, this is not vanilla behaviour.

**Comment by dktapps** [comment]
This has been fixed in https://github.com/pmmp/PocketMine-MP/commit/fe4322bea957b422ea8596712ccaf022a388c9b7

**Comment by jasonwynn10** [comment]
This causes mobs to burn when hit with flint and steel?

**Comment by Qimie** [comment]
Bow takes dmg when hit mobs or player? Idk maybe too
