### ISSUE TITLE
I Can't Choose A Language

### ISSUE THREAD

**Issue by PIANOCRAFT6000** [pmmp/PocketMine-MP#380]
When I clicked start.cmd says choose language, and I typed eng. It shows can't find the language, so I can't start my server. Please fix this. Thank you

Exact thing showed:

> [*] PocketMine-MP set-up wizard
[*] Please select a language:
[?] Language (eng): eng
[!] Couldn't find the language
[?] Language (eng):

**Comment by AppleDevelops** [comment]
Try en

**Comment by PIANOCRAFT6000** [comment]
en does not work too.

> [*] PocketMine-MP set-up wizard
[*] Please select a language:
[?] Language (eng): en
[!] Couldn't find the language
[?] Language (eng): en
[!] Couldn't find the language
[?] Language (eng):

**Comment by robske110** [comment]
We are using 3 letter identifiers. The correct thing to enter would be 'eng'.

**Comment by Muqsit** [comment]
Leave it blank else, (just press enter without typing anything)

**Comment by dktapps** [comment]
It shows you a list of language codes when you start the server. You must use one of those. PocketMine-MP uses ISO-639-2 language codes.

**Comment by SOF3** [comment]
The problem is that your installation of PocketMine is incorrect. `eng` is not working because you installed PocketMine incorrectly such that no language files, including `eng`, are present.

**Comment by PIANOCRAFT6000** [comment]
I'll check, I'll maybe re-install PocketMine, I might have installed it incorrectly
