### ISSUE TITLE
Server crashed

### ISSUE THREAD

**Issue by laigelplayz** [pmmp/PocketMine-MP#3808]
pocketmine\network\mcpe\NetworkBinaryStream::putString() must be of the type string, int given, called in phar:///home/container/PocketMine-MP.phar/src/pocketmine/network/mcpe/protocol/AddActorPacket.php on line 211" (EXCEPTION) in "src/pocketmine/network/mcpe/NetworkBinaryStream" at line 62

So What happen is everytime i click a block it will cost internal server error!
Link to crashdump: 

it is only internal server error so there is no crushdump

**Comment by dktapps** [comment]
Without knowing your PocketMine-MP version, OS, PHP, Client version, or plugins and how the issue occurred, the issue cannot begin to be solved.
A pre-formatted template is provided that shows the required information to begin to find, test and solve an issue.
Until the adequate template and information is provided, the issue will be closed; it may be reopened if you update the ticket with the correct template and required information.

[Contribution guidelines](https://github.com/pmmp/PocketMine-MP/blob/master/CONTRIBUTING.md)
