### ISSUE TITLE
Server crashed

### ISSUE THREAD

**Issue by mmdkvz** [pmmp/PocketMine-MP#3809]
===BEGIN CRASH DUMP===
eNrtW2tz3DaW/StYOVUj7Yotvh+dUkoe29m4xg+tpay3Jp1ygQDYzRGbZPjQw6n89z0XALvZspzZ
3cyH/TBTU1ETBC7u89x7QfjXo6Lptnz4dKu6vmzqo2VwejSUW3W09KIszeIsjZLTo4r3w6uua7qj
5a9Hw0OL10ev7oVqB1pzerRVfc/XNPqB37wpc3a96RSXTHS83yiJGcVYVd+XFU1pN7xbnp29WJ79
2GPXs+dyW9ZlP3R8aLqzl6q/GZr27LIRN2p4W9bKeXvp9APPK3U4uCBCZ30nzlo9DCrqrFbDXdPd
nG1Fq84MM6/rQXUFFwoLWmLFsPG/WIhFFeZAJ54P9XQ0tPzp6JnLvkLknfl77LnZyZLtJ6xWdsZq
RfusVo82cr5ru0ZAmccn2POZ95j+lepgqGM/SJOv0bVb7yjtaFua/tdoelH4iKZ543w3lOLGLA6+
stjLst9bfGlYaTpDJfwalShNv0IF9u8Gszp6vHrvFMd+EnyFwKdPoqnhY6MYjpv8b0oM7M+8Vy/g
2f2bhkvVnTI7Pl8+DmXVr1ZveVm/adZrmgUiZb3+KfJ/Zi+Wq5X24dXqwIlXK+vFq9VTbrxa7ajE
7h+g0lbjuqyxTOsl/h29BO5j8/RG5Xplwo49D+879ctYdurY8ua5yc/sHx2sJ0c//3Z6pP4Ylvyh
AMb2RnGfyvq2qW7VVtUDyNVNTfNEIxVx5rkBBjHguSF+rIZ2zKtSsGKsBXHKejVMYW7/sm8sDye/
6nWRXrcavhk2Ze98Z1+y8928b/W0WE/7Tf9Opj3TJ/fcoQNbstumlGafzO5zt4Fiju1u5R5TNryW
lbrkpKrjk5Nf9Vaea7fyPLu8LI7/xS7utPpApP8w1jWcATuCCPvy/dVmHGRzVxNdTc231FbDsOma
O1arO7Za7Qx8vHrarKujE60NL7DrDZPhXjdeNDEcP6kbUTW9uoJ2aBfjwuybUsK4ZVHuA5d9g237
pj5QoZfsdVD2sOykxbbiD3D7n2aEfp4kTXeSfmOmkWW/vsyIl+0WjfVsn/28/qe+rT4ZKPq0gW6O
LfWTn42GfPdpEk+yalZ4f3fT5y/+8tRC/7GIzndazce7x7Ua3ih+q96aqD0+Od0p+Nuj3/6ZLP+Z
LP+ZLP9Isjw9WqtadbyinFRzKsyPDuaCpxy22RfwR8HCixYujY9lJZHzUg9Ffdl/kur2aFnwqldI
gV0zNKIB2dBNsUlJKZCHWZq7oRfx3Fey8NLAdcPElYWKpZf6QeIXfuRlRHu0vHwsa8B/z95ds4+v
3zmXV+/jl2H4Z+zJ4kXANAssi12XHU9TjZcx3/V89sFnVwMyC+8keyVLAvIT9vztyzjEHlSuL4+S
RbAAgp0efVa11OLZZ7z+1PTEw+t3764xoB/uylpn8W0LnOo+VWXe8a5UPemPyw1k7tTZ34BPDubY
1O8uvIV7kYZh6iaxG2RBmhVRlBZBxqUbRQHneZrIPChSL/aIswZZa1uO/VmLpArYc6z2iQFvES28
C08GfhD6eSo8lSPSokCkaZqIIAaFJA+FL3mcBILk2HthXta8e9BxZNnyvAuVijyOZO7lSZalSuV5
EmS554eFz9GiFSpNQFXlh6QEr6oc3Dm3vColOaDmDTQvQq6KOM/9qMgS6eawcs7dPCziOA3C3OOZ
SONCZPwRQYr+Skf/TmWhEFCLq8K0cEGlENBXmOcu991UemBWxAHgLjikVDVrTcEHBRVluZJ5JLFM
5Rn34zhMRE6Kwh+/4InPpSz4FxScdtAFRL9jJstzoWAzuLAXpgnPQQg24DFP3ChMfJ9jCzdODkmh
+d1YbsKL3BN+mvtBLIsU2o5kkruxKNLQ94osi31onYvQcw9J1PlgKXggEXhSwC5hGAR+KsKc50ks
hZenoYDlA5FAYN9VhyRQUMFTjSj+Ir2AVXkSBwXM4Psyd9NAhZGfypALWMwLpKt4GvDwkEpfN81n
ZRXiX6Tg25U8kFkQwH9EHijlSyUKGakojEAkSqSQxSMibaUphPCUosCUDM6hQg/KgxcGcYAQSRIv
Em6RJomfgo8UFGQjCAnVGUAWET2UO5cLiFAQAUZcP05V5oZRlqggl5kI4zQSUaBcFQRBoRSZefsA
T8v7M6lUixhtHzQRjxw3i7Pc92AKHnmce0UsXE960oc/R7EkinRooSJQqcubEgC/aZ2Wd7122dtw
kVKYiyhVCEAZFkGaIqb92PN4rrjwVZGLQMIfkzTRBgIMO2UDH6nLQvVkZV9HUBr5caQKGfAiyXkg
eJj73BdBKBEDUZKmUvqZFwQzGnN8hqtcCERgnPqRVEWaKZcHvu9Do2kQJEUqFC+8LIkK7hqgg3ZH
AiukkU4VldIlr0YwTdLXseRJ1xNhJkMlY0JqztOQJ2HCJcwfcS/O/DCGE/8eSYzmFZwBRCNNNPAS
F8BYREkMp/SyIoxiLwkkMRqEyi0Kcm3jRAdEqbVzOtVTizU5AuI9TVLuISgjP4yKXCVpkbqpq4BA
AQVskCNY48jie98qGLFr2o0S1g/w/4vcd10glYIJhEScF3nsCh5wPxM5/hNmHMDgxVZ35I5n9u8U
YUFyESkvhhQKyOlLWBxUJNYpAbJ+LgA8CpCY8i+JOPg71uUwEfNiqB6+R0nSy90oyKTikZBBouCQ
YcyLPM1RICgveYIYFRBicLqxUv1EMQSYpbFC6kgSAAaMliofyOa73PW4j9ySSEQhj4yXam60s1P3
iv9A46aFzgAEAQCfoDEALiPkC18lXhiAwyJJ4BeRF4gc/uyp8BEx6rOdEhWxDWVy3PACaQNqj3LA
exAJGBL1dVIoF7kxDDniSXgUh485o2b7RhkyhNYJT6M8jrkQYSq4KApAbiKB9UGcheAQIJyEfpY+
IjOo+wH/2aL/GJSNR/8iLgokLcVDaMZD0k0LUSSh8oFzXqx8EXkCWch/LCAddHba0ymowUkGl04S
eBGSmp8XQJkQPICtnJA8L7LQU8khEesIGbw7ukjQpeauiwySE77EPk+CNIpEFnsRxJKISjeGcCDR
w+V7oGR9pm1myVCCji5QM/iyQP4QmRu5lPWB+R7gEkWAG6BbhYuCqPs0GQQdgY1yqqa5GdudkhSU
USBJugJ+z5GeAoQa8kKAljL1swJhKXmKDvWQ6hYAah0gBJ3gQgogKPIPsjKHpYpM+gKQDGzwfQ+Q
wJEolRcWX9Cp1H05PFh+gCwBojemjB/FIkacFImbwvBhqBDGYR5KoaSbJQd0ZFkUlhP/wkMyAZIX
0BJHJRML5Lsc+UBlEpCO9YCagI4U5hRUfVt2TW1Lv0hnSpcnUSJ4nskoT1QBAImBdB6FSSwyJG8k
OxD1Dwndt003qG7HTpR4MvE9maPAEilw10V1E4PFLAo5zKngQMiBh+ysqybnFbUB2p8jrRrUKiqO
A5FFXi4F8AQ6RWGq8BswoCRBXfZYNXTC1TtN4ZgjLO1LAFxy5NiPixCVWQSEE0EKt8xT1EUhsFyF
mUsOdUDKNHeOqgHmc+NDU0lYKOlLl8fSTQGhSSIl8lWGyAPtPEjDzAP1p8jZNKOpGZf0/ITD7jFA
MwlRYlBPEAUAI1TaMgrdWMYCyHzo6J0So86lELQmPNgzF/t+4EFc+ECeIWuJsOBwjTgMcsA9nFx4
noyDR+T6ZuyEcpqWZLVVfGAJRkHipaAR+xlKwQiADtREAQMekafJHsp/5GD2TJNyMiqFOMsQzXkQ
hGEsZBarGGx5KfAhh/tGyA2+gPseUDisFbwLmC9KUaVEKPtk4KE8RoEbIP9FqJkTVNAgE3HdTPQP
26KpH9DaVg/A78oRlp1bJM6UGhMBaItJ6UBxN3GBUyjCwJYLb0V5jFwe52FEUDlsVK8UMjmAuy4/
2yxORUEChQQiCIDhCcpBFLshSgs3iRR3eeEiy/hUr5JUdyrfNp95N5yhfVCdAbmMkjgvRJwJjlpM
hhmcvJCoKzM3RVUXcBQXKcFwmh1Wp/ufzrbdNbsX/+PO9bfd8a/uCF+q2+umqfpZd70bOj3a2wHK
C3VPzcdh03Q9nWjt23B2rfiWenXelvQmoDIloAFVU3ePtnXoRnTdUrVoYmk13vVNMbycD2x5Wc8Y
oCONHSvUeOHd1fXzD9c/Xhq99qWGjM0wtP3y7Aw9/GbMF0Da2WnC2Y4GBH87VkP5senoVGAn72zw
UOJwERwK/OKzEpvLt6BIHP1neV/evPjrgdgAHOf5m8sfnhMyzR7Tw8fs8FH3U/Nn79GzPz3/X1W6
JRnvSMbV6kBeq9bL91fXH99/ePPy7yl2poKzGSHtVUiTW4V88Mg5pvMc4t0cJC2ookUo6FOJo2eX
uyf2oqmLcs2o8Fp1q/rZ26Zmz8c1CzzmJcsgW4YB+zc3DFzmu75LUyper0fUeueqXtPzthnk+Wp0
kdFuFouF+dWZP/Ivt5+Z+cnNIcxsItYa7hzyi/PtVt7cfp6NUq4799DU+DS4xpwt0sy5pzfl9449
fj43bPUtv0Od3DWD6SvOHT3xbgPNOlXZD+dNUdCIsabzy6i6h/Omng11QPdpFq/rZqyB0fbYmYtN
qcyXm96uKhrC8B1fdiH0LunEZ3pub1s7nwqJUsCED+dGIn3MhuTk9GoYynrdn2v9YpvKqMT4z24M
0ChnUwhmz79/8/yahoj3RQvAwxp5/q/6f5BiHBqn57fKsnBbqjtHltQFCHWe0tB93tw7FHITwwfo
t3jYUm/+jNERKxPaWUaTs7TPMCiBHXgefIhdE4yzSSrGO8WA7KxBtYAffGCC1DuwXLGyFtUolcQP
9oWvEq2rZouVBRu+pNnzQp2yBm+6nkiyvFP8hj0guVparCwYjENfGGgH2AWpfKgeiPA7dbcjh9a/
4LBMz+6a+k8D422reMdIfVsISydbD8QhfcUwct9tVM3Gdt1xCQKLVU1ua4gtVzVjzz5uFDHGhga7
1JKBhD1Vhg46XvfUTkjzWrOKHpiDMPRZqUHrS6rbUihmPqbRyJYoG7ebonDJ9PEqvejthzHHfs9c
stWRPfnUn1Dk6khz9ryqmjtGIUEfp2xqYrclZ/9BMUFzdHA49tWSEe7ppa90oNg1+vscuTp9JIRS
iFr+wKwqab6Nq93rGbPPPqJUgEdAr+jAGEoio35SK32TYFvF+7HTAceg9FwR01CO+mXkFaltXd5i
7i2vRsWO7aYAqROibnakwwACEQdqp48DS7zWe78btzm0Aq963j/U4pr3N4y+ysCPFnrCj9CWdu1J
Upq2QQ3fjLAepvenTAcns0GMeDhl1HF05nOg1g1wnca2aJGEnmKIX2nzQiZ4Wdfcl/AwBTVAJO25
9Y450q1l6HVBvkpzyCdPWTn8CeobOr1MKsI87TKPFrNjyDAibnytFi2GYyVdalKPfZVr5+jMN1jy
QOi91UbQB+v9giET2d9sW643g/meejoPPus4pJGuG9vBjBqFkWK24M3KpY2LoNQn49IEBKevpGD7
aQ7IR8jnGiga3rWYORomO2bSztOQKgDP3YMJyn/XrQ+jpM3MOOJgWw4U21u15vnDAI2zK6NqVyu3
7PXnHFp+TVa7K7XmtUchaO8cQ2hysl5LWJRgEYgE7mtNq+iUmrY0Tg5rjRSmbN3AUHSAor2CNrId
mmZtyVySArtrCDZH0P/vJaAq6Pf4pyz5x/jvh6bVLFj43LFkyfUM8EEJEbg3MUS7Tlz5bphaxjQI
fNRRYfnr//QP4FDHhWaJEIOhheygSkS6ukc/qcG3MSybiKRktZut7gWyfb+XyADX++tXS3b9w+sr
9ub129fX7Pnl5ZvXr67Y5asPDOXkX159OGWYxK7fY9Yr9vGH929escsP71+8urpaPIaAQ31EsVXH
perKRidkAuKeBBQbpSFZa2MHth50j5JAamzRUxxAoTIwq0mhuoScAGh4E8n7NWczTqZvk5BOCILM
NE3ZEAH07oHcZCS9x3vKIZTn9YLFl7PJF2wJD7O1SlA5YDRL7Bq7mrU7GeBequ33oqL+NbL2J0+z
ZCUPrORr3uX0lU40lT3n1gD0tHZ1qBE7dhWzq4DdW16PuviYc4LCbIQPnpxOOeGxE05uaNJrUYCW
kXe7D8EFe28w3zg8qodmrOSOlxJJ5K5me/57Q7jV7ENQdO9WVuz2vQaLL5Kkdh1DYSdb0TXbKdma
1XaGM3fNuYVJGmvJL3yDPeFSB95xNRWMZLIOO5EbWkeW47Y11ZUp4Zh94dCLyV4vaZJdoHnXbE4S
4AlpHsHOn1AwkjYSH3a4hZP1/agIGIYNrLaeqk0CLdptz9XpZEhTI9iicmG4oalf1RP1RGIz1jf9
xPsL3tJouR23yLFIrx2bin8yJLOXiDQXe71SvFhV6oj50sdQbLeWI72hQ1XwiKQb7iz2sjGvHvs0
1UaEeoa+mTyFkKFlJ84l05WDI9CDqZ1sL8GKrlVQPpL2wJ0pMAyVVt89Y2aNkXAvHZZZfRp5pp1p
8r7aJQVW1AZYur9P6vf8cFXb+z9LmyJQmm2aypSYOR/QW1IlrllG1QQXsklGY5vpfOxbk1pytSs2
TXp7NrfS9IpgtXsYiPgpc7yZAbXx9MbOMDFjU4BG7X0dq1tNKiGlkZx6GV3o02IMWrYW7AfUgvpC
GhV37MXlj6dYCx5yxNddKeH2ulYw6Lmj72j6S5ZMZfe+Iu+1dmZzF+y5BFBteFWcoZU0bYJU8GG7
FTZldLxCDjYLxH3amxGbtyKv7gnVqMTk1akBTdra3h5ZsOtO54tGV9I/XtaXUx2+7w2pzaBFd8io
RHNs69axz48an7c2IPvys9qZmir2ycI95UJbTaGit3c491k3zHyz6GTBLu2aindrvYDbJtW6id6x
6PiapIO5IFbfVrqYoc5zC+YJB3hHJnxRlXS8oVtpumyk+oG9vf5Rc9pDJBI7HwdGrbu28n4703cs
JhjaDqNDq5aaWwoAqfJxvZx6me+YRz2MreQ2iGL9ntnOtTe9Njl53Tcmp1lH8YiYwS1D7cWmQW9L
zjm1MGpqUjW4ST5w1vPbCUTpNGQ61KF3+3inKwRAAsWHCWPAqbm8NJXMut1qO1Ou9C0qNF2+1I2o
ypbptdDjW/4AHZKzbJvbqYMl+LeYqXHLmd6ZLfs9WkyHPfPThGt9HGAcwPz7CXOQoudaa4+9PZYQ
8PrB4IJd45g1S9aioLgtK9rGYJ6NZ7sLgTav17uiuqZl1ePccTrNOjhOevIEx3R5z7fNSD5dGHC2
Lk6qNEd4OhlROOveHYah3zqbYPEHnVtmi7XgtTK9Yq4MsVwV5JH6FFCng83kAdro+nDwIEsZ8Wmj
nfiITMYfs2rvaWI3hQTwFJfu02zyDpTgH5MjgtlpMf3dcRNo76ZO2hlbeKTqZ2ghKAHpjfQZ5uwo
5vVLvZm+OtHrkCR9qo4sjboW0LVlVjpmTx6mbKfXHIgOeg7z2TO2Rs/S79WzP93YaWjxpYpssN7x
Ujc1AA5U/MY2bdOO1eSM9oFgX8+xEBFogNDVsNPasCZ0pUhdsqnO1EeZ5jxnaTNebe9yMzNsEoa1
FxjZHwzIvd7I3/XnykdDu3A7HG43KM2KZmYRRJljjul3MzcNWUazsmi323ZRNprjuqkfttQj0KdW
Om4T/Z51anzse7Z/r0XQkMXX6w7dpjlZssdQptumC843j+XT/CGC3798TzdFHQuCJhcQKNwpU4hy
fT+eduw143sB9NhidvaL1LPTvHFNY5wvlAqDmvfWmZD19KdSwu55PaXHm7nqUKLW5CezY55T4GO7
4acYhhooYQ27kgXQWyi00TAhEKimhGBv29rEYg6N+MGxkf3CNEs4I8oz5DaNYhNYWILa8ub9tMcX
ljayzk09oIfeYbXNSESU5k+FA1mWAJM21OdhdtF09rnYb2DfzHeYtPn7Oc/CtrGuiYrZMYOlAfKD
1ed0oLCxgxoxqCOwRaZFDDqfRR0vdZVVFjtCKNUhiDmMJwSaumyDcaBnIXLKbLwqeW9LeFRdnC5o
2CcqAsCjtdVyMpp5B7+l454l+0lnb+TPU33+8zMR1dX5Pk3OPxJoMaiS6kppO+zpm4tunZ/KWDqh
6wzd62JSd2b03Q282nQ7Z9/sq3kwPxl9paGsYLLXfsclo281S//b5DTK7r3T4D449b/1vpVKNAZj
j4dO4QHgep66BorNUxidmLLHnMfPG1sT4ZRboGN77qRLD31wBKuJB2bu1Y/dBMpTNd/tTvI14oAO
UpXQX0r6SWHO9BUAvmDqu2ffa6jRW+n5B0RGXSnYf+40G3F0sbXYH5E1+h/nMHUP4OttIyRuqF7u
ddEPjeQlKtUH0zPreSSvvuxZmTRiYsZIqemjGOl2WH10eqTuB1Xba9K/Hr1AhTC/3p0LexV3N0Jf
YOhq+MFYs/0kmwFgeDBqLznsB8aumj9Lc7tm91yUlbm5sxtZbw8um9O/vJk/l4iy2/kAXSHXn8kT
fS9gm5vPSfMpvb3ZPh9rxaHUH3ZXLw9WatjvD4dQoGznI1eXb+aP24f+l0rfkLe/mL7W5tM5PHPo
un3khm6Cn9+8RkgkQuD/dB8liYpYJr6KROEWdK0l1Pd6BN2X9gP2Dd0Emd0A2W34wPXXSJ+u89H1
/LI1FyWiBV0e+WzuM+9m4/F+e2iThsShq5ye59OVgMuX7w9UJZtPWpTHgxgqD80JuKj7/mDiVUmA
8F9vD3T0iAM8Ukt6KBYG77rykXfMLpsHdK+H/ikFGN4cOuc+W3/Sxdj8Ij+pqFybC/72EiSpSfb2
Ug0pQAOazKfL5OTH3UM7NHog0ANr+YXNywM30boJ5kO7+1Lr0TjjxM5fqWZ7f6mPUvYLfvvtvwH8
jZtl
===END CRASH DUMP===

**Comment by mmdkvz** [comment]
stoped pocketmine server when my world was load , how can i fix it ? please help me

**Comment by mmdkvz** [comment]
http://s11.picofile.com/file/8407372734/Untitled.png this is my error

**Comment by dktapps** [comment]
You're running multiple things on the same port.

**Comment by mmdkvz** [comment]
do i have to change my port ?

**Comment by mmdkvz** [comment]
for example from 19132 to 1 ?
