### ISSUE TITLE
Creative players get picked up by AntiCheat for flight

### ISSUE THREAD

**Issue by GlacierShard92** [pmmp/PocketMine-MP#381]
### Issue description
AntiCheat is activating on creative mode players in flight mode.

### Steps to reproduce the issue
1. Go into /gamemode creative
2. Fly up and sprint fly
3. Check server logs when you're lagged back
(It may take a few times for it to work)

### OS and versions
* PocketMine-MP: 1.6.2dev [Unleased]
* PHP: 7
* Server OS: Windows 10
* Game version: PE/Win10

### Crashdump, backtrace or other files
From console:
[00:15:30] [Server thread/WARNING]: jokester4690 moved wrongly!
[00:21:10] [Server thread/WARNING]: jokester4690 moved too fast, reverting movement

**Comment by TanToan99** [comment]
set `allow-movement-cheats: true `in pocketmine.yml

**Comment by dktapps** [comment]
This is discussed in #292 .
