### ISSUE TITLE
Unlimited Arrow

### ISSUE THREAD

**Issue by NamkiFx** [pmmp/PocketMine-MP#3817]
### Issue description

- Expected result: I Was testing plugin, this plugin
Will add sound to owner of the entity(arrow)
- Actual result: Unlimited Arrow

### OS and versions

* PocketMine-MP: version
* PHP: 3.0.0
* Server OS: PocketMine-MP Apk
* Game version: PE

### Plugins
- If you remove all plugins, does the issue still occur? Yes

**Comment by dktapps** [comment]
Without knowing your PocketMine-MP version, OS, PHP, Client version, or plugins and how the issue occurred, the issue cannot begin to be solved.
A pre-formatted template is provided that shows the required information to begin to find, test and solve an issue.
Until the adequate template and information is provided, the issue will be closed; it may be reopened if you update the ticket with the correct template and required information.

[Contribution guidelines](https://github.com/pmmp/PocketMine-MP/blob/master/CONTRIBUTING.md)
