### ISSUE TITLE
Low TPS when loading chunks in converted world

### ISSUE THREAD

**Issue by Gaprix** [pmmp/PocketMine-MP#3822]
### Issue description
When I enter the world, chunks start to load for a very long time and a small TPS

### Steps to reproduce the issue
1. Upload the world in anvil format to the server
2. Turn on the server and wait for the conversion to leveldb
3. Join the server
4. Check tps while flying around the world

### OS and versions
* PocketMine-MP: 4.0.0+dev
* PHP: 7.3
* Server OS: Ubuntu

### Plugins
none

### Crashdump, backtrace or other files
https://youtu.be/jrEmDeWDMek

**Comment by dktapps** [comment]
Make sure you're using the latest version of PM. A fix for performance issues with chunk loading was fixed just a few days ago.

**Comment by Gaprix** [comment]
You're right. The problem has been resolved. thank

**Comment by Gaprix** [comment]
Chunks are loaded many times faster, but during this TPS is still reduced to 10
