### ISSUE TITLE
ItemFrame cannot be installed on the ceiling or floor.

### ISSUE THREAD

**Issue by alvin0319** [pmmp/PocketMine-MP#3826]
### Issue description

- Expected result: ItemFrame is installed on the ceiling and floor.
- Actual result: ItemFrame is not installed on the ceiling and floor.

### Steps to reproduce the issue
1. Join the server
2. Install ItemFrame on the floor and ceiling.
### OS and versions

* PocketMine-MP: https://github.com/pmmp/PocketMine-MP/commit/9d0ac297bbeb4b9a4330685b24c4045f7fb0c5e9
* PHP: 7.4
* Server OS: Windows 10
* Game version: PE/Win10

### Plugins

- If you remove all plugins, does the issue still occur? Yes
- If the issue is **not** reproducible without plugins:
  - Have you asked for help on our forums before creating an issue?
  - Can you provide sample, *minimal* reproducing code for the issue? If so, paste it in the bottom section

**Comment by DerDevHD** [comment]
Thats a MC:Java feature I guess

**Comment by alvin0319** [comment]
> Thats a MC:Java feature I guess

No, it was added few versions ago

**Comment by DerDevHD** [comment]
Ah yes, sorry.

**Comment by ConnorHopper** [comment]
no

**Comment by dktapps** [comment]
Implemented by 27d767227351cbd21a925e1db0f577b42203cdcc.
