### ISSUE TITLE
Unknow error 

### ISSUE THREAD

**Issue by TanToan99** [pmmp/PocketMine-MP#383]
### Issue description
Console :
Warning: assert(): Movement distance is excessive: dx=0.76609999999999, dy=43.9597, dz=-1.7229 failed in phar:///home/ftech/PocketMine-MP.phar/src/pocketmine/entity/Entity.php on line 1314

### OS and versions
Player join server and move
Console show error
* PocketMine-MP: https://github.com/pmmp/PocketMine-MP/commit/cfb6856634f91930f6e013e7b98edb638dea15d9
* PHP: 7.0.3
* Server OS: linux
* Game version: PE/Win10 1.0.3

### Crashdump, backtrace or other files
No plugins and no crashdump
* ...

**Comment by dktapps** [comment]
Duplicate of #311
