### ISSUE TITLE
Use only of 1 cpu core

### ISSUE THREAD

**Issue by JohnnyX071** [pmmp/PocketMine-MP#3830]
For some reason, my pcoketmine server uses only 1 CPU core

**Comment by dktapps** [comment]
Yes, we know.

**Comment by JohnnyX071** [comment]
so could you fix that?

**Comment by dktapps** [comment]
It's not a bug and this has been reported so many times that I'm tired of hearing it. See https://github.com/pmmp/PocketMine-MP/issues/1905.

**Comment by JohnnyX071** [comment]
So why you don't fix it to sto hearing it because most people have more than 1 core and it's useless to pocketmine. It would be greatly appreciated if you amde it so it will us was many cores as you have!

**Comment by mmm545** [comment]
https://github.com/pmmp/PocketMine-MP/issues/1905#issuecomment-356997544
