### ISSUE TITLE
Walls don't join each other

### ISSUE THREAD

**Issue by Eren5960** [pmmp/PocketMine-MP#3832]
### Issue description
![image](https://user-images.githubusercontent.com/35738714/93898400-da703900-fcfb-11ea-8f3b-c8c20afcccc6.png)

### Steps to reproduce the issue
1. Place wall
2. Place wall the side

### OS and versions

* PocketMine-MP: ae9e931849685e02f57cece02caf3f61d6fc9ed4
* PHP: 7.4
* Server OS: Debian 10
* Game version: PE/Win10

### Plugins
no
### Crashdump, backtrace or other files
no

**Comment by dktapps** [comment]
https://github.com/pmmp/PocketMine-MP/blob/stable/changelogs/3.15.md#known-issues-please-dont-open-issues-for-these
