### ISSUE TITLE
Give negative Item ID crash client

### ISSUE THREAD

**Issue by benda95280** [pmmp/PocketMine-MP#3833]
### Issue description

- Expected result: Trying to get Chemistry block
- Actual result: Client crash, cannot join anymore

### Steps to reproduce the issue
1. /give benda95280 Elemental_29
2. Player is kicked
3. Player cannot join anymore

### OS and versions

* PocketMine-MP: 3.15.1
* PHP: 7.3.21.0
* Server OS: W10 2004
* Game version: W10 1.16.40

### Plugins
A lot
- If you remove all plugins, does the issue still occur? Yes
- If the issue is **not** reproducible without plugins:
  - Have you asked for help on our forums before creating an issue?
  - Can you provide sample, *minimal* reproducing code for the issue? If so, paste it in the bottom section

### Crashdump, backtrace or other files
[Server thread/INFO]: [benda95280: 64 Unknown (-29:0) à(ont) été(s) donné(s) à benda95280]
Nothing else in console

**Comment by dktapps** [comment]
Chemistry blocks aren't supported, and this isn't the fault of the server.

**Comment by benda95280** [comment]
@dktapps No fix to prevent this bug ? :(

**Comment by xezo360hye** [comment]
Hello, did you find the solution? You should just switch off in game settings "show arm" and indicators (idk how it's in English; hotbar). So now you could join the server and clear your inventory. Done!

P.S. It's not only this item, there's a group. I call them "I4B" (item-for-ban)

**Comment by kenygamer** [comment]
> Hello, did you find the solution? You should just switch off in game settings "show arm" and indicators (idk how it's in English; hotbar). So now you could join the server and clear your inventory. Done!
> 
> P.S. It's not only this item, there's a group. I call them "I4B" (item-for-ban)

It is your fault because you are giving items with negative id, which, as @dktapps said, are not currently supported, on PM3
