### ISSUE TITLE
Chunk generation might cause repeated attempted loading and unloading of chunks (synchronously)

### ISSUE THREAD

**Issue by dktapps** [pmmp/PocketMine-MP#3839]
### Issue description
`PopulationTask` may cause adjacent chunks to be (attempted) to be loaded from disk. However, it doesn't use a `ChunkLoader` to do this, meaning that the loaded chunks may be discarded before the end of the population, and then loaded again at the end.

This bug is at the root of a big spam of "will be unloaded at the next available opportunity" debugs when joining a newly generated world on both PM3 and PM4.

### Steps to reproduce the issue
1. Create a new server with debug.level=2
2. Join the server.
3. Observe a whole bunch of console spam as new chunks are generated.

### OS and versions

* PocketMine-MP: 75e3a0aa0fd649e0f7dab4d481521b30c7d4a55e
* PHP: 7.4.10
* Server OS: windows

**Comment by ConnorHopper** [comment]
no
