### ISSUE TITLE
snow issue

### ISSUE THREAD

**Issue by GlacierShard92** [pmmp/PocketMine-MP#384]
### Issue description
Snow regenerates after unloading chunks with snow and loading them back in

### Steps to reproduce the issue
1. Find a snow biome, destroy some snow
2. Teleport far away
3. Go back to the snow biome
4. The snow is back, and some may be double stacked. Snow is only suppose to come back during snowy weather.

### OS and versions
* PocketMine-MP: 1.6.2dev [Unleashed] 3.0.0ALPHA4 Release Download
* PHP: 7
* Server OS: Windows
* Game version: PE/Win10

### Crashdump, backtrace or other files
Not needed

**Comment by Muqsit** [comment]
Blame MCPE (or am I wrong?)

**Comment by JackNoordhuis** [comment]
The snow isn't handled by the server, the client likes to populate snow biomes with snow layers itself.

**Comment by dktapps** [comment]
This is a client issue, it also occurs in vanilla multiplayer and on Realms. https://bugs.mojang.com/browse/MCPE-16103
