### ISSUE TITLE
/clear command

### ISSUE THREAD

**Issue by jaylac2000** [pmmp/PocketMine-MP#3840]
## Description

/clear 

## Justification

i know many servers including my own have this most likely written in our private cores, however i think it should be add here since it is a vanilla mc command

**Comment by dktapps** [comment]
Being vanilla doesn't constitute a reason to add it. It can be very easily done by a plugin.

**Comment by jaylac2000** [comment]
yes but  it is a feature which should be added to here. since it is usually a server software feature - just my opionion. pmmp is the only server software without it

not like i can make a PR cuz u prob won;t accept it

**Comment by dktapps** [comment]
> it is usually a server software feature

also doesn't constitute a reason to add it. I don't add features just because someone else did. I need a rationale.

Again, I don't see why this is necessary when a simple plugin can do the same thing (and already have been doing for years).

> not like i can make a PR cuz u prob won;t accept it

This defeatist attitude is the reason why there are so few third party contributors. Instead of complaining, change my mind.

**Comment by lukeeey** [comment]
I think what Dylan is trying to say is that if you make a good quality PR and write up a good description for it then yeah, he might accept it, but he's not going to go out of his way to implement something that isn't a priority and can be done in plugins.

**Comment by dktapps** [comment]
@lukeeey nailed it, thank you

**Comment by dadodasyra** [comment]
> also doesn't constitute a reason to add it
if I am not mistaken, software such as paper, bukkit and spigot have a / clear implemented and it remains a vanilla feature which is not present and easy to do, we often forget it but there are a lot of server running while the server has no developer, and besides yes it is possible via a plugin but a lot of people are doing tests on pocketmine vanilla without plugin so as not to have any "interference" problem and to prove for example a bug on the github, in short it is easy to do and practical so I do not see why it is not even added yet.

**Comment by jaylac2000** [comment]
not everyone is a developer or have developers

**Comment by dktapps** [comment]
It's not added yet for the same reason <insert random feature here> is not implemented yet - it hasn't been done yet.

Again, being vanilla isn't a reason to add something. Every piece of development costs time and right now my resources are committed elsewhere.

Funny, I don't see anyone else cares enough to do it either, can't be that important ... 🤔

**Comment by lukeeey** [comment]
I’m a fan of implementing vanilla features into third party server softwares, it just gets it that little bit closer to being more usable for most people. However, a lot of people do not have time for this (dylan included) and you should respect that. You can run your server without the /clear command.

If I can be bothered, I will implement this and create a PR. Don’t get your hopes up, and please don’t keep complaining.

**Comment by dktapps** [comment]
Implemented in c4b47c6c067528454b685d68af61c705ddd8ce49.
