### ISSUE TITLE
ErrorTypeToStringMap::get() must be of the type int, string given php 7.4

### ISSUE THREAD

**Issue by Eren5960** [pmmp/PocketMine-MP#3845]
### Issue description
```
Error: Uncaught TypeError: Argument 1 passed to pocketmine\errorhandler\ErrorTypeToStringMap::get() must be of the type int, string given, called in /root/sky/src/utils/MainLogger.php on line 174 and defined in /root/sky/vendor/pocketmine/errorhandler/src/ErrorTypeToStringMap.php:54
File: vendor/pocketmine/errorhandler/src/ErrorTypeToStringMap
Line: 54
Type: E_ERROR
```

### OS and versions
* PocketMine-MP: ae9e931849685e02f57cece02caf3f61d6fc9ed4
* PHP Version: 7.4.10
* Zend version: 3.4.0

**Comment by dktapps** [comment]
Without knowing your PocketMine-MP version, OS, PHP, Client version, or plugins and how the issue occurred, the issue cannot begin to be solved.
A pre-formatted template is provided that shows the required information to begin to find, test and solve an issue.
Until the adequate template and information is provided, the issue will be closed; it may be reopened if you update the ticket with the correct template and required information.

[Contribution guidelines](https://github.com/pmmp/PocketMine-MP/blob/master/CONTRIBUTING.md)

**Comment by Eren5960** [comment]
No debug, I have already specified other things that will not help specifying plugins.

**Comment by Eren5960** [comment]
```Fatal error: Uncaught TypeError: Argument 1 passed to pocketmine\errorhandler\ErrorTypeToStringMap::get() must be of the type int, string given, called in /home/eren/Desktop/StormGames/SkyBlock/src/utils/MainLogger.php on line 175 and defined in /home/eren/Desktop/StormGames/SkyBlock/vendor/pocketmine/errorhandler/src/ErrorTypeToStringMap.php:54
Stack trace:
#0 /home/eren/Desktop/StormGames/SkyBlock/src/utils/MainLogger.php(175): pocketmine\errorhandler\ErrorTypeToStringMap::get('HY000')
#1 /home/eren/Desktop/StormGames/SkyBlock/src/utils/MainLogger.php(155): pocketmine\utils\MainLogger::printExceptionMessage(Object(Illuminate\Database\QueryException))
#2 [internal function]: pocketmine\utils\MainLogger->pocketmine\utils\{closure}()
#3 /home/eren/Desktop/StormGames/SkyBlock/src/utils/MainLogger.php(219): Threaded->synchronized(Object(Closure))
#4 /home/eren/Desktop/StormGames/SkyBlock/src/utils/MainLogger.php(165): pocketmine\utils\MainLogger->buffer(Object(Closure))
#5 /home/eren/Desktop/StormGames/SkyBlock/src/Server.ph in /home/eren/Desktop/StormGames/SkyBlock/vendor/pocketmine/errorhandler/src/ErrorTypeToStringMap.php on line 54```

```
Fatal error: Uncaught ErrorException: socket_select(): supplied resource is not a valid Socket resource in /home/eren/Desktop/StormGames/SkyBlock/plugins/Others/others/RconServer/src/pmmp/RconServer/RconThread.php:167
Stack trace:
#0 [internal function]: pocketmine\errorhandler\ErrorToExceptionHandler::handle(2, 'socket_select()...', '/home/eren/Desk...', 167, Array)
#1 /home/eren/Desktop/StormGames/SkyBlock/plugins/Others/others/RconServer/src/pmmp/RconServer/RconThread.php(167): socket_select(Array, NULL, NULL, 5, 0)
#2 /home/eren/Desktop/StormGames/SkyBlock/src/thread/CommonThreadPartsTrait.php(73): pmmp\RconServer\RconThread->onRun()
#3 [internal function]: pocketmine\thread\Thread->run()
#4 {main}
  thrown in /home/eren/Desktop/StormGames/SkyBlock/plugins/Others/others/RconServer/src/pmmp/RconServer/RconThread.php on line 167
```

**Comment by Eren5960** [comment]
The code string in the PDOException class is returned.
https://www.php.net/manual/tr/class.pdoexception.php
