### ISSUE TITLE
commands usage message

### ISSUE THREAD

**Issue by GlacierShard92** [pmmp/PocketMine-MP#385]
### Issue description
When you do a command for example, like "/effect" it doesn't say the usage, it says "Usage: ommands.effect.usage". No, "ommands" isn't a typo, it's what it says.

### Steps to reproduce the issue
1. Run a command like /effect, /tp etc

### OS and versions
* PocketMine-MP: 1.6.2dev [Unleashed] 3.0.0-ALPHA4 Release download
* PHP: 7
* Server OS: Windows
* Game version: PE/Win10

### Crashdump, backtrace or other files
Not Needed

**Comment by Muqsit** [comment]
wow so original.
https://github.com/pmmp/PocketMine-MP/issues/236

**Comment by GlacierShard92** [comment]
oops, didn't see that.

**Comment by dktapps** [comment]
Please **search the issue tracker** before opening an issue.
