### ISSUE TITLE
Players take no knockback

### ISSUE THREAD

**Issue by buchwasa** [pmmp/PocketMine-MP#3858]
### Issue description

- Expected result: Players take knockback
- Actual result: They take no knockback

### Steps to reproduce the issue
1. Join server with friend
2. Attack friend

### OS and versions

* PocketMine-MP: 4.0.0 commit cbc6ebebad2b4df8aa29085b85f3eac41c17dc12
* PHP: 7.4.11
* Server OS: Ubuntu 20.04
* Game version: PE & Windows 10

### Plugins

Can be reproduced without plugins.

**Comment by dktapps** [comment]
Fixed by a91710b199a0e73e3639b89643f2535b2e4cd751.
