### ISSUE TITLE
What about PHP 8 and PocketMine

### ISSUE THREAD

**Issue by GamingFR91** [pmmp/PocketMine-MP#3860]
<h4>I want to know what will happen for PocketMine Update when PHP 8 will release the 26th November</h4>

<h4>Much persons said the Library will completly change with PHP 8</h4>

**Comment by SOF3** [comment]
GitHub is not a discussion forum. For highly open-ended discussions, please use our forums or discord.

(Also GitHub is not Reddit, no need to :+1: yourself)
