### ISSUE TITLE
LowMemoryEvent error

### ISSUE THREAD

**Issue by BillBlackwood** [pmmp/PocketMine-MP#3863]
Why can't I cancel LowMemoryEvent?

- Expected result: I expected to be able to cancel the event and there would be enough memory on my server to continue working
- Actual result: Got an error

### Steps to reproduce the issue
1. Create listener, and listen LowMemoryEvent
2. Attempt to cancel it

### OS and versions

* PocketMine-MP: 3.15.2
* PHP: 7.3
* Server OS: Ubuntu 19
* Game version: PE

# Plugins: AntiMemoryFiller v1

**Comment by dktapps** [comment]
![image](https://user-images.githubusercontent.com/14214667/95478095-00930b80-0981-11eb-8dff-145b616096e5.png)

**Comment by thebigsmileXD** [comment]
> Why can't I cancel LowMemoryEvent?

For the same reason a car can not go another mile when it ran out of fuel

Head to https://downloadmoreram.com/ to fix your issue
