### ISSUE TITLE
Players take a large amount of fall damage when comboed

### ISSUE THREAD

**Issue by buchwasa** [pmmp/PocketMine-MP#3866]
### Issue description

- Expected result: Players to not take a lot of fall damage
- Actual result: Players take a lot of fall damage.

### Steps to reproduce the issue
1. Join with a friend
2. Combo them for a while (10-15s is a good amount)
3. Stop, and let them take fall damage

### OS and versions

* PocketMine-MP: 3.x & 4.0
* PHP: 7.4
* Server OS: Linux
* Game version: PE & Win10

### Plugins
Can be done without plugins

**Comment by dktapps** [comment]
For posterity: My theory for this behaviour is that comboing prevents the player from touching the ground for a while, and the downwards movements they make while being comboed all stack together, while the upwards movements have no effect.

**Comment by ZizzyZizzy** [comment]
@dktapps I've seen this exact behavior when testing the limits of hacked clients and anti-cheat plugins.

One of the hack that lets you fly on a PMMP server with anti-cheat still keeps track of the height every time you "air jump", so even if you're 1/2 block up from the last air jump, you still die from falling. The only way to prevent the death is to land in water.

**Comment by dktapps** [comment]
Yeah, I've noticed the same, but I didn't think anything of it because I didn't realize it might occur in non-cheat scenarios.
