### ISSUE TITLE
/whitelist on should kick non-whitelisted online players

### ISSUE THREAD

**Issue by SOF3** [pmmp/PocketMine-MP#3868]
When the server whitelist is enabled, people who got into the server in time should be kicked. It does not seem reasonable to want to enable whitelist without kicking everyone already online not in the whitelist.

This changes behaviour and may be appropriate in major.next.

**Comment by CortexPE** [comment]
We already depend on this current behavior that prevent more players from
joining without kicking everyone, especially when we're whitelisting the
server in the middle of the day to host "last man standing" games/events.

I suppose there should be an optional Boolean toggle `/whitelist on
[kick=false]` to kick existing non-whitelisted players if this were to be
implemented?

**Comment by dktapps** [comment]
If we add toggles for this, nobody will use them and it'll still be a circus of users asking why players don't go away when using /whitelist. You should implement your own logic instead of depending on the built-in whitelist.

**Comment by ConnorHopper** [comment]
no
