### ISSUE TITLE
Using a MCPE world in my server

### ISSUE THREAD

**Issue by benwelch** [pmmp/PocketMine-MP#387]
So I have a mcpe world created on 1.0.3 minecraft which I want to use in my pocketmine server. It can be downloaded here.

I tried converting it using leveldb to anvil but it didn't work. I found a thread somewhere saying that levels created on 1.x minecraft aren't supported. I don't know if that's true or not but if someone who knows what they are doing with leveldb to anvil could tell me what I'm doing wrong or do it for me it would be great. My world is in the folder with the start.bat and the converter.jar and I have a folder called worldanvil. When I run start.bat it says done but no output is created.

I also tried pmimporter but it says no worlds from 0.9 or higher are supported so I wasn't suprised when it said format not recognised. I wondered is there a way to convert my mcpe 1.0 map into a mcpe 0.8 map and then convert it using pmimporter?

Next tried mcedit. I downloaded it from mcedit.net but when I opened my mcpe world to export it, the whole thing was blank. Like an empty chunck or something. I don't know whether this is a problem with mcedit, my computer or my world but the world runs perfectly on my phone.

I heard that worlds from earlier versions of mcpe could just be put into a pocketmine server like normal. I don't understand why this isn't implemented as a feature for the more recent versions. If anyone could show me or even make a plugin so that people can use mcpe worlds in their mcpe server then that would be great.

Any help is appreciated as I want to get this done asap. Thanks

**Comment by dktapps** [comment]
Please search the issue tracker before opening a new issue. #378
