### ISSUE TITLE
The glass pane BBs seem to be off at edges

### ISSUE THREAD

**Issue by radondev** [pmmp/PocketMine-MP#3877]
### Issue description

- Expected result: no collision
- Actual result: collision detected

### Steps to reproduce the issue
Call something similar to `$player->getWorld()->getCollisionBlocks($player->getBoundingBox())` from a plugin and walk into glass panes as seen in [this video](https://youtu.be/8wpYKOEllJY).

### OS and versions
* PocketMine-MP: 4.0.0+dev
* PHP: 7.4
* Server OS: Windows 10
* Game version: PE/Win10

### Plugins
Calling `$player->getWorld()->getCollisionBlocks($player->getBoundingBox())` when the player is standing near glass panes.
In the video, I did it using the `PlayerChatEvent`.

**Comment by dktapps** [comment]
A better way to check is shoot arrows at the empty space near the glass and see if they stick when there's nothing to collide with.

**Comment by radondev** [comment]
Not your approach, but similar: https://imgur.com/a/TVyluS2

**Comment by dktapps** [comment]
That's not really helpful. That only tells me what the client thinks is going on.

**Comment by radondev** [comment]
Sorry, I somehow misunderstood the issue itself 😅
