### ISSUE TITLE
Blocks/things missing!

### ISSUE THREAD

**Issue by infinity-pe** [pmmp/PocketMine-MP#388]
### Issue description

Blocks and things like Elytra Wings, Purpur Blocks, Red Sandstone, Beacon, Slime Block, etc... are missing! Why? Can they be added?

* PocketMine-MP: This one here
* Server OS: Minecraft PE 1.0.3
* Game version: PE

**Comment by dktapps** [comment]
Please see existing issues before opening a new one. This has already been discussed.
