### ISSUE TITLE
Block placing is very laggy since Update

### ISSUE THREAD

**Issue by MonoAdrian23** [pmmp/PocketMine-MP#3888]
### Issue description

- Expected result: What were you expecting to happen?
- Actual result: What actually happened?
After i Update my Pocketmine Version to 3.15.2 block placing and consume food gives laggs

### Steps to reproduce the issue
1. ... Install Pocketmine 3.15.2
2. ... Place Blocks fast on a world for example, Citybuild

### OS and versions

* PocketMine-MP: 3.15.2
* PHP: 7.3
* Server OS: Debian 10 Buster
* Game version: PE/Win10 (delete as appropriate)

### Plugins
 Only Multiworld is installed

- If you remove all plugins, does the issue still occur? Yes
- If the issue is **not** reproducible without plugins:
  - Have you asked for help on our forums before creating an issue? Yes
  - Can you provide sample, *minimal* reproducing code for the issue? If so, paste it in the bottom section

**Comment by dktapps** [comment]
I can't reproduce this and there's nothing in the changeset that would make a change here.
