### ISSUE TITLE
Add more debug levels

### ISSUE THREAD

**Issue by dktapps** [pmmp/PocketMine-MP#389]
### Issue description
Currently there are only debug levels 1 (no debug) and 2 (all debug spam).

### Proposed changes
Debug levels:
- 1: No debug
- 2: Plugin debugging
- 3: Core
- 4: Network?

**Comment by madecode15** [comment]
How will you add this without an ugly API?

Example: `$sever->getLogger()->debugNetwork("ugly API");`

**Comment by jasonwynn10** [comment]
The API shouldn't change. It will just display different things depending on what is set in the config, Right?

**Comment by SuperPuperSteve** [comment]
@madecode15 
`$sever->getLogger()->debug($message, $level);` default level: current level

**Comment by dktapps** [comment]
It seems like it would be a better idea to split up the global logger into multiple sub loggers which can each have their own debug level. Since work is already underway to de-globalise logging, this might be possible to introduce along the way.

**Comment by yoraze** [comment]
What for? The idea is not bad :(

**Comment by dktapps** [comment]
The idea is terrible, and makes no sense. Subsystem-specific logging configurations offer more flexibility, but that isn't the topic of this issue.

**Comment by SOF3** [comment]
The main reason is about not conforming to PSR-3.

It actually makes sense to have multiple levels of log displaying, but that's something we have already done with log levels, and multiple debug levels simply reinvented the log level hierarchy with less sound definitions.
