### ISSUE TITLE
Error on transferring between certain worlds made by WorldPainter

### ISSUE THREAD

**Issue by minijaham** [pmmp/PocketMine-MP#3891]
### Issue description

Server thread/ERROR An error occurred while teleporting player between worlds: Unknown NBT tag type 12 (at line: 82 , file: phar:///PMMP-Latest-Stable.phar/vendor/pocketmine/nbt/src/NBT.php)

Transferring between certain worlds made with WorldPainter doesn't seem to work.

**Comment by dktapps** [comment]
PC worlds newer than 1.12 aren't supported.
