### ISSUE TITLE
Pick block bug

### ISSUE THREAD

**Issue by Dapro718** [pmmp/PocketMine-MP#3892]
### Issue description

- Expected result: When you pick block, it should be placed into the next free slot in your hot bar. If your hot bar is full, the item in the slot currently selected should move into the inventory, and the item being picked should be placed into that slot.
- Actual result: The block being picked replaces the item in the selected slot on the hot bar.

### Steps to reproduce the issue
1. Pick any block, tile, or item and it will happen.

### OS and versions

* PocketMine-MP: 3.15.2
* PHP: 7.4.10
* Server OS: Windows
* Game version: PE/Win10 - 1.16.5

### Plugins

No plugins

- If you remove all plugins, does the issue still occur? Yes
- If the issue is **not** reproducible without plugins:
  - Have you asked for help on our forums before creating an issue?
  - Can you provide sample, *minimal* reproducing code for the issue? If so, paste it in the bottom section

**Comment by dktapps** [comment]
It's not technically a bug, just the way it was implemented.
This has been fixed on PM4, along with the inability to pick-block in survival.
