### ISSUE TITLE
Removing the tag

### ISSUE THREAD

**Issue by davidgamingzz** [pmmp/PocketMine-MP#3893]
https://github.com/pmmp/PocketMine-MP/blob/beb6a50883e10cf7eec0926a1973ec0eac9034c9/src/item/Item.php#L320

**Comment by davidgamingzz** [comment]
It would be removing a non-existent tag. The custom name tag should be removed during this occasion.

**Comment by dktapps** [comment]
I'll fix this tomorrow. If you want it sooner, PR is welcome.

**Comment by dktapps** [comment]
Fixed by b059e0b475b50db0fb2a47df4a7a0bbb3e400555.
