### ISSUE TITLE
Can't compile leveldb extension with php

### ISSUE THREAD

**Issue by benwelch** [pmmp/PocketMine-MP#390]
### Issue description
So I'm trying to compile the leveldb extension on my raspberry pi pocketmine server so I can use mcpe worlds. It's using php 7. Whenever I try to do this using the compile.sh ([here](https://github.com/PocketMine/php-build-scripts)) with the argument -l and the target as rpi (raspberry pi) it does it but when I run my server it says "Couldn't find a working PHP 7 binary, please use the installer." I'm using windows 10.

**Comment by jarne** [comment]
This is related to https://github.com/pmmp/php-build-scripts. But when I'm right, Level DB doesn't work on PHP 7 yet.

**Comment by dktapps** [comment]
Closing due to issue on wrong repository.
