### ISSUE TITLE
/version crashes server when author is an array

### ISSUE THREAD

**Issue by SOF3** [pmmp/PocketMine-MP#3902]
### Issue description
When a plugin declares `author: [array, of, strings]`, PocketMine still loads the plugin, but it crashes the server when `/version $PLUGIN_NAME` is run.

This opens a vulnerability for adversaries to induce crashes on a server by running `/version` on plugins known to have incorrectly formatted plugin.yml

Reported by @Kygekraqmak

### Steps to reproduce the issue
1. Create a plugin with this line in plugin.yml: `author: [array]`
2. Start the server
3. Run command `/version $PLUGIN_NAME`

### OS and versions

* PocketMine-MP: 3.15.4
* PHP: PHP 7.4.11 (cli) (built: Nov 10 2020 17:50:51) ( ZTS )
* Server OS: Linux (Docker image)

### Plugins
Reproduced with only DevTools + aforementioned example plugin

### Crashdump, backtrace or other files
Example crash: https://crash.pmmp.io/view/4634552

**Comment by Kygekraqmak** [comment]
Thanks!
