### ISSUE TITLE
Force async compression during the login sequence

### ISSUE THREAD

**Issue by dktapps** [pmmp/PocketMine-MP#3907]
## Description
Async compression is currently disabled by default due to the extra latency it creates during gameplay. However, many packets don't suffer from added latency at all, because they don't have visual or audio effects.

Specifically, the entire login sequence pre-spawn can utilize async compression with no adverse side effects, since the player can't see anything that's going on anyway. This would significantly reduce the performance cost of spawning a new player with near zero negative side effects.

Long term, the goal should obviously be to make compression always be threaded, and to also fix the latency issues created by using AsyncTasks for compression, but in the near term this should be easy to implement.

**Comment by jasonwynn10** [comment]
Would it be reasonable to add a way to specify which packets can be async-processed and which should not be? Doing so would allow the setting’s removal altogether and allow PocketMine to handle everything without the need for user input

**Comment by dktapps** [comment]
That's not granular enough. Some packets might only need to be sync-processed in certain circumstances (for example LevelEvent delivering a particle/sound needs to be as fast as possible, but a weather update being delayed by 50ms doesn't really make any difference).
