### ISSUE TITLE
Crash Dump, Call to a member function getEntities()on null

### ISSUE THREAD

**Issue by DoseOfNone** [pmmp/PocketMine-MP#391]
**Steps to reproduce the issue:**
1. I have no idea, I think its when we walk too far then a crash just builds.

**VERSION:**
PocketMine-MP: 1.6.2dev #0 [Protocol 101; API 3.0.0-ALPHA4]
PHP: 7.0.2
Server OS: Linux Ubuntu 14.0.1
Game version: PE/Win10 

**CRASHDUMP:**

PocketMine-MP Crash Dump Tue Feb 28 13:04:53 CST 2017
Error: Call to a member function getEntities() on null
File: /src/pocketmine/Player
Line: 680
Type: notice

Code:
[671] 			$this->dataPacket($pk);
[672] 		}
[673] 	}
[674] 
[675] 	private function unloadChunk($x, $z, Level $level = null){
[676] 		$level = $level === null ? $this->level : $level;
[677] 		$index = Level::chunkHash($x, $z);
[678] 		if(isset($this->usedChunks[$index])){
[679] 			$chunk = $level->getChunk($x, $z);
[680] 			foreach($chunk->getEntities() as $entity){
[681] 				if($entity !== $this){
[682] 					$entity->despawnFrom($this);
[683] 				}
[684] 			}
[685] 
[686] 			if($level !== $this->level){
[687] 				$pk = new FullChunkDataPacket();
[688] 				$pk->chunkX = $x;
[689] 				$pk->chunkZ = $z;
[690] 				$pk->data = chr($chunk->getSubChunkSendCount());

Backtrace:
#0 /src/pocketmine/Player(1605): pocketmine\Player->orderChunks(boolean)
#1 /src/pocketmine/Server(2327): pocketmine\Player->checkNetwork(boolean)
#2 /src/pocketmine/Server(2084): pocketmine\Server->tick(boolean)
#3 /src/pocketmine/Server(1966): pocketmine\Server->tickProcessor(boolean)
#4 /src/pocketmine/Server(1587): pocketmine\Server->start(boolean)
#5 /src/pocketmine/PocketMine(491): pocketmine\Server->__construct(BaseClassLoader object, pocketmine\utils\MainLogger object, string phar:///home/servers/Prison/PocketMine-MP.phar/, string /home/servers/Prison/, string /home/servers/Prison/plugins/)
#6 (1): require_once(string phar:///home/servers/Prison/PocketMine-MP.phar/src/pocketmine/PocketMine.php)

PocketMine-MP version: 1.6.2dev #0 [Protocol 101; API 3.0.0-ALPHA4]
Git commit: 0000000000000000000000000000000000000000
uname -a: Linux ubuntu 3.13.0-32-generic #57-Ubuntu SMP Tue Jul 15 03:51:08 UTC 2014 x86_64
PHP Version: 7.0.2
Zend version: 3.0.0
OS : Linux, linux

**Comment by DoseOfNone** [comment]
https://www.imageupload.co.uk/image/BY6w

Image of the crash provided.

**Comment by Muqsit** [comment]
It returns null if no entities are present in the world, which is normal.

**Comment by DoseOfNone** [comment]
So, its EmptyWorld causing errors and the crash?

**Comment by Muqsit** [comment]
What I'm saying is, you didn't need to provide a background of every error you're seeing on your console.

**Comment by DoseOfNone** [comment]
Well im showing what the console said and all those errors were brought together I wasnt aware of which one was causing the crash. The crash dump is above for someone from pm to review.

**Comment by dktapps** [comment]
Plugin issue, biome colour API methods were removed in API 3.0.0-ALPHA1.
