### ISSUE TITLE
Rename Server->getPlayer to Server->getPlayerByPrefix

### ISSUE THREAD

**Issue by SOF3** [pmmp/PocketMine-MP#3910]
## Description
Refactor the method name `getPlayer` to `getPlayerByPrefix`. Everything else can be unchanged.

## Justification
Some plugins use player name to check whether a specific player is online, e.g. after the completion of an AsyncTask. This might easily lead to security vulnerabilities in which another player is incorrectly identified because the plugin incorrectly used `getPlayer` instead of `getPlayerExact`. Renaming the method ensures that developers are aware of this behaviour.

This issue is similar to `World->getName()` vs `World->getFolderName()`.

## Alternative methods
We should have used UUID to identify a player anyway...

**Comment by Kygekraqmak** [comment]
Can we use XUID instead?

**Comment by SOF3** [comment]
> Can we use XUID instead?

That's totally irrelevant. We are just renaming an AIP method. `getPlayerByPrefix` shall be primarily intended for use in commands.

**Comment by dktapps** [comment]
Players don't always have XUIDs. This has been discussed dozens of times before. Besides, that's outside the scope of this issue.

**Comment by Kygekraqmak** [comment]
> > Can we use XUID instead?
> 
> That's totally irrelevant. We are just renaming an AIP method. `getPlayerByPrefix` shall be primarily intended for use in commands.

AIP? Or API?
