### ISSUE TITLE
Version Update

### ISSUE THREAD

**Issue by TubboInnit** [pmmp/PocketMine-MP#3914]
## Description
Please update the version to the newest version - 1.16.100 so we can play the servers!

## Justification
Many people update their Minecraft version and they can't play the servers now!

**Comment by iTzMeFlorian** [comment]
wait for this f*cking update and don't open an issue for this. PMMP will update to 1.16.100 asap

**Comment by SOF3** [comment]
@iTzMeFlorian please don't micro mod this issue tracker.
