### ISSUE TITLE
Segmentation fault BUG

### ISSUE THREAD

**Issue by cokll** [pmmp/PocketMine-MP#392]
### Issue description

Write a short description about the issue

### Steps to reproduce the issue

1./home/pocketmine/php7015/bin/php /home/pocketmine/src/pocketmine/PocketMine.php --disable-ansi --no-wizard

* PocketMine-MP:
PHP:php7015
Server OS: centos 7.3.1611
Game version: 1.0.3.0

### Crashdump, backtrace or other files

* [04:53:58] [Server thread/INFO]: Stopping other threads

*** Error in `PocketMine-MP 1.6.2dev': corrupted double-linked list: 0x0000000002536f80 ***
======= Backtrace: =========
/lib64/libc.so.6(+0x7bc02)[0x7f07db2cbc02]
/lib64/libc.so.6(+0x7c3e6)[0x7f07db2cc3e6]
PocketMine-MP 1.6.2dev[0x7b07d4]
PocketMine-MP 1.6.2dev(php_module_shutdown+0x33)[0x7462b3]
PocketMine-MP 1.6.2dev[0x435cab]
/lib64/libc.so.6(__libc_start_main+0xf5)[0x7f07db271b35]
PocketMine-MP 1.6.2dev[0x435ea2]
======= Memory map: ========
00400000-00c3a000 r-xp 00000000 fd:02 317349074                          /home/pocketmine/php7015/bin/php
00e39000-00ed1000 r--p 00839000 fd:02 317349074                          /home/pocketmine/php7015/bin/php
00ed1000-00eeb000 rw-p 008d1000 fd:02 317349074                          /home/pocketmine/php7015/bin/php
00eeb000-00f0d000 rw-p 00000000 00:00 0 
024f9000-027e0000 rw-p 00000000 00:00 0                                  [heap]
7f073f600000-7f073fc00000 rw-p 00000000 00:00 0 
7f0740000000-7f0740021000 rw-p 00000000 00:00 0 
7f0740021000-7f0744000000 ---p 00000000 00:00 0 
7f074c000000-7f074c021000 rw-p 00000000 00:00 0 
7f074c021000-7f0750000000 ---p 00000000 00:00 0 
7f0750000000-7f0750127000 rw-p 00000000 00:00 0 
7f0750127000-7f0754000000 ---p 00000000 00:00 0 
7f0756e00000-7f0757000000 rw-p 00000000 00:00 0 
7f07571f9000-7f07571fe000 r-xp 00000000 fd:00 201638179                  /usr/lib64/libnss_dns-2.17.so
7f07571fe000-7f07573fd000 ---p 00005000 fd:00 201638179                  /usr/lib64/libnss_dns-2.17.so
7f07573fd000-7f07573fe000 r--p 00004000 fd:00 201638179                  /usr/lib64/libnss_dns-2.17.so
7f07573fe000-7f07573ff000 rw-p 00005000 fd:00 201638179                  /usr/lib64/libnss_dns-2.17.so
7f0758000000-7f07580d7000 rw-p 00000000 00:00 0 
7f07580d7000-7f075c000000 ---p 00000000 00:00 0 
7f075c000000-7f075c0d7000 rw-p 00000000 00:00 0 
7f075c0d7000-7f0760000000 ---p 00000000 00:00 0 
7f0760000000-7f0760143000 rw-p 00000000 00:00 0 
7f0760143000-7f0764000000 ---p 00000000 00:00 0 
7f0764000000-7f07640d7000 rw-p 00000000 00:00 0 
7f07640d7000-7f0768000000 ---p 00000000 00:00 0 
7f0768be9000-7f0768bfe000 r-xp 00000000 fd:00 201431993                  /usr/lib64/libgcc_s-4.8.5-20150702.so.1
7f0768bfe000-7f0768dfd000 ---p 00015000 fd:00 201431993                  /usr/lib64/libgcc_s-4.8.5-20150702.so.1
7f0768dfd000-7f0768dfe000 r--p 00014000 fd:00 201431993                  /usr/lib64/libgcc_s-4.8.5-20150702.so.1
7f0768dfe000-7f0768dff000 rw-p 00015000 fd:00 201431993                  /usr/lib64/libgcc_s-4.8.5-20150702.so.1
7f0768dff000-7f0768e00000 ---p 00000000 00:00 0 
7f0768e00000-7f0769600000 rw-p 00000000 00:00 0 
7f0769800000-7f0769c00000 rw-p 00000000 00:00 0 
7f076a5ea000-7f076a5f6000 r-xp 00000000 fd:00 201328484                  /usr/lib64/libnss_files-2.17.so
7f076a5f6000-7f076a7f5000 ---p 0000c000 fd:00 201328484                  /usr/lib64/libnss_files-2.17.so
7f076a7f5000-7f076a7f6000 r--p 0000b000 fd:00 201328484                  /usr/lib64/libnss_files-2.17.so
7f076a7f6000-7f076a7f7000 rw-p 0000c000 fd:00 201328484                  /usr/lib64/libnss_files-2.17.so
7f076a7f7000-7f076a7fd000 rw-p 00000000 00:00 0 
7f076a7fd000-7f076a7fe000 ---p 00000000 00:00 0 
7f076a7fe000-7f076affe000 rw-p 00000000 00:00 0 
7f076affe000-7f076afff000 ---p 00000000 00:00 0 
7f076afff000-7f076b7ff000 rw-p 00000000 00:00 0 
7f076c000000-7f076c0d7000 rw-p 00000000 00:00 0 
7f076c0d7000-7f0770000000 ---p 00000000 00:00 0 
7f0770000000-7f07700e9000 rw-p 00000000 00:00 0 
7f07700e9000-7f0774000000 ---p 00000000 00:00 0 
7f0774000000-7f07740d7000 rw-p 00000000 00:00 0 
7f07740d7000-7f0778000000 ---p 00000000 00:00 0 
7f0778000000-7f07780d7000 rw-p 00000000 00:00 0 
7f07780d7000-7f077c000000 ---p 00000000 00:00 0 
7f077c000000-7f077c0d7000 rw-p 00000000 00:00 0 
7f077c0d7000-7f0780000000 ---p 00000000 00:00 0 
7f0780000000-7f0780149000 rw-p 00000000 00:00 0 
7f0780149000-7f0784000000 ---p 00000000 00:00 0 
7f0788000000-7f07880d7000 rw-p 00000000 00:00 0 
7f07880d7000-7f078c000000 ---p 00000000 00:00 0 
7f078c000000-7f078c0d7000 rw-p 00000000 00:00 0 
7f078c0d7000-7f0790000000 ---p 00000000 00:00 0 
7f0790000000-7f0790148000 rw-p 00000000 00:00 0 
7f0790148000-7f0794000000 ---p 00000000 00:00 0 
7f0794000000-7f07940d7000 rw-p 00000000 00:00 0 
7f07940d7000-7f0798000000 ---p 00000000 00:00 0 
7f0798000000-7f07980d7000 rw-p 00000000 00:00 0 
7f07980d7000-7f079c000000 ---p 00000000 00:00 0 
7f079c000000-7f079c0ea000 rw-p 00000000 00:00 0 
7f079c0ea000-7f07a0000000 ---p 00000000 00:00 0 
7f07a4000000-7f07a4132000 rw-p 00000000 00:00 0 
7f07a4132000-7f07a8000000 ---p 00000000 00:00 0 
7f07a8000000-7f07a8149000 rw-p 00000000 00:00 0 
7f07a8149000-7f07ac000000 ---p 00000000 00:00 0 
7f07ac000000-7f07ac149000 rw-p 00000000 00:00 0 
7f07ac149000-7f07b0000000 ---p 00000000 00:00 0 
7f07b0000000-7f07b0141000 rw-p 00000000 00:00 0 
7f07b0141000-7f07b4000000 ---p 00000000 00:00 0 
7f07b4000000-7f07b4132000 rw-p 00000000 00:00 0 
7f07b4132000-7f07b8000000 ---p 00000000 00:00 0 
7f07bc000000-7f07bc0be000 rw-p 00000000 00:00 0 
7f07bc0be000-7f07c0000000 ---p 00000000 00:00 0 
7f07c0000000-7f07c0149000 rw-p 00000000 00:00 0 
7f07c0149000-7f07c4000000 ---p 00000000 00:00 0 
7f07c4000000-7f07c40bb000 rw-p 00000000 00:00 0 
7f07c40bb000-7f07c8000000 ---p 00000000 00:00 0 
7f07ca20b000-7f07ca20c000 ---p 00000000 00:00 0 
7f07ca20c000-7f07caa0c000 rw-p 00000000 00:00 0 
7f07d46a5000-7f07d46d4000 r-xp 00000000 fd:02 316598404                  /home/pocketmine/php7015/bin/opcache.so
7f07d46d4000-7f07d48d4000 ---p 0002f000 fd:02 316598404                  /home/pocketmine/php7015/bin/opcache.so
7f07d48d4000-7f07d48d5000 r--p 0002f000 fd:02 316598404                  /home/pocketmine/php7015/bin/opcache.so
7f07d48d5000-7f07d48d6000 rw-p 00030000 fd:02 316598404                  /home/pocketmine/php7015/bin/opcache.so
7f07d48d6000-7f07d48d7000 rw-p 00000000 00:00 0 
7f07d48d7000-7f07dae00000 r--p 00000000 fd:00 134323010                  /usr/lib/locale/locale-archive
7f07dae00000-7f07db000000 rw-p 00000000 00:00 0 
7f07db04d000-7f07db04f000 r-xp 00000000 fd:00 201328030                  /usr/lib64/libfreebl3.so
7f07db04f000-7f07db24e000 ---p 00002000 fd:00 201328030                  /usr/lib64/libfreebl3.so
7f07db24e000-7f07db24f000 r--p 00001000 fd:00 201328030                  /usr/lib64/libfreebl3.so
7f07db24f000-7f07db250000 rw-p 00002000 fd:00 201328030                  /usr/lib64/libfreebl3.so
7f07db250000-7f07db406000 r-xp 00000000 fd:00 201328482                  /usr/lib64/libc-2.17.so
7f07db406000-7f07db606000 ---p 001b6000 fd:00 201328482                  /usr/lib64/libc-2.17.so
7f07db606000-7f07db60a000 r--p 001b6000 fd:00 201328482                  /usr/lib64/libc-2.17.so
7f07db60a000-7f07db60c000 rw-p 001ba000 fd:00 201328482                  /usr/lib64/libc-2.17.so
7f07db60c000-7f07db611000 rw-p 00000000 00:00 0 
7f07db611000-7f07db6d2000 r-xp 00000000 fd:02 894397449                  /home/pocketmine/php7015/lib/libcurl.so.4.4.0
7f07db6d2000-7f07db8d2000 ---p 000c1000 fd:02 894397449                  /home/pocketmine/php7015/lib/libcurl.so.4.4.0
7f07db8d2000-7f07db8d7000 r--p 000c1000 fd:02 894397449                  /home/pocketmine/php7015/lib/libcurl.so.4.4.0
7f07db8d7000-7f07db8d9000 rw-p 000c6000 fd:02 894397449                  /home/pocketmine/php7015/lib/libcurl.so.4.4.0
7f07db8d9000-7f07db8dc000 rw-p 00000000 00:00 0 
7f07db8dc000-7f07db8f3000 r-xp 00000000 fd:00 202246421                  /usr/lib64/libpthread-2.17.so
7f07db8f3000-7f07dbaf2000 ---p 00017000 fd:00 202246421                  /usr/lib64/libpthread-2.17.so
7f07dbaf2000-7f07dbaf3000 r--p 00016000 fd:00 202246421                  /usr/lib64/libpthread-2.17.so
7f07dbaf3000-7f07dbaf4000 rw-p 00017000 fd:00 202246421                  /usr/lib64/libpthread-2.17.so
7f07dbaf4000-7f07dbaf8000 rw-p 00000000 00:00 0 
7f07dbaf8000-7f07dbb0e000 r-xp 00000000 fd:00 201534092                  /usr/lib64/libnsl-2.17.so
7f07dbb0e000-7f07dbd0d000 ---p 00016000 fd:00 201534092                  /usr/lib64/libnsl-2.17.so
7f07dbd0d000-7f07dbd0e000 r--p 00015000 fd:00 201534092                  /usr/lib64/libnsl-2.17.so
7f07dbd0e000-7f07dbd0f000 rw-p 00016000 fd:00 201534092                  /usr/lib64/libnsl-2.17.so
7f07dbd0f000-7f07dbd11000 rw-p 00000000 00:00 0 
7f07dbd11000-7f07dbd13000 r-xp 00000000 fd:00 201534088                  /usr/lib64/libdl-2.17.so
7f07dbd13000-7f07dbf13000 ---p 00002000 fd:00 201534088                  /usr/lib64/libdl-2.17.so
7f07dbf13000-7f07dbf14000 r--p 00002000 fd:00 201534088                  /usr/lib64/libdl-2.17.so
7f07dbf14000-7f07dbf15000 rw-p 00003000 fd:00 201534088                  /usr/lib64/libdl-2.17.so
7f07dbf15000-7f07dc015000 r-xp 00000000 fd:00 201534090                  /usr/lib64/libm-2.17.so
7f07dc015000-7f07dc215000 ---p 00100000 fd:00 201534090                  /usr/lib64/libm-2.17.so
7f07dc215000-7f07dc216000 r--p 00100000 fd:00 201534090                  /usr/lib64/libm-2.17.so
7f07dc216000-7f07dc217000 rw-p 00101000 fd:00 201534090                  /usr/lib64/libm-2.17.so
7f07dc217000-7f07dc21e000 r-xp 00000000 fd:00 202246763                  /usr/lib64/librt-2.17.so
7f07dc21e000-7f07dc41d000 ---p 00007000 fd:00 202246763                  /usr/lib64/librt-2.17.so
7f07dc41d000-7f07dc41e000 r--p 00006000 fd:00 202246763                  /usr/lib64/librt-2.17.so
7f07dc41e000-7f07dc41f000 rw-p 00007000 fd:00 202246763                  /usr/lib64/librt-2.17.so
7f07dc41f000-7f07dc44f000 r-xp 00000000 fd:02 894397450                  /home/pocketmine/php7015/lib/libpng16.so.16.28.0
7f07dc44f000-7f07dc64e000 ---p 00030000 fd:02 894397450                  /home/pocketmine/php7015/lib/libpng16.so.16.28.0
7f07dc64e000-7f07dc64f000 r--p 0002f000 fd:02 894397450                  /home/pocketmine/php7015/lib/libpng16.so.16.28.0
7f07dc64f000-7f07dc650000 rw-p 00030000 fd:02 894397450                  /home/pocketmine/php7015/lib/libpng16.so.16.28.0
7f07dc650000-7f07dc666000 r-xp 00000000 fd:00 202246423                  /usr/lib64/libresolv-2.17.so
7f07dc666000-7f07dc866000 ---p 00016000 fd:00 202246423                  /usr/lib64/libresolv-2.17.so
7f07dc866000-7f07dc867000 r--p 00016000 fd:00 202246423                  /usr/lib64/libresolv-2.17.so
7f07dc867000-7f07dc868000 rw-p 00017000 fd:00 202246423                  /usr/lib64/libresolv-2.17.so
7f07dc868000-7f07dc86a000 rw-p 00000000 00:00 0 
7f07dc86a000-7f07dc887000 r-xp 00000000 fd:02 894397440                  /home/pocketmine/php7015/lib/libyaml-0.so.2.0.5
7f07dc887000-7f07dca86000 ---p 0001d000 fd:02 894397440                  /home/pocketmine/php7015/lib/libyaml-0.so.2.0.5
7f07dca86000-7f07dca87000 r--p 0001c000 fd:02 894397440                  /home/pocketmine/php7015/lib/libyaml-0.so.2.0.5
7f07dca87000-7f07dca88000 rw-p 0001d000 fd:02 894397440                  /home/pocketmine/php7015/lib/libyaml-0.so.2.0.5
7f07dca88000-7f07dca9d000 r-xp 00000000 fd:02 894397493                  /home/pocketmine/php7015/lib/libz.so.1.2.8
7f07dca9d000-7f07dcc9c000 ---p 00015000 fd:02 894397493                  /home/pocketmine/php7015/lib/libz.so.1.2.8
7f07dcc9c000-7f07dcc9d000 r--p 00014000 fd:02 894397493                  /home/pocketmine/php7015/lib/libz.so.1.2.8
7f07dcc9d000-7f07dcc9e000 rw-p 00015000 fd:02 894397493                  /home/pocketmine/php7015/lib/libz.so.1.2.8
7f07dcc9e000-7f07dcca6000 r-xp 00000000 fd:00 201534086                  /usr/lib64/libcrypt-2.17.so
7f07dcca6000-7f07dcea5000 ---p 00008000 fd:00 201534086                  /usr/lib64/libcrypt-2.17.so
7f07dcea5000-7f07dcea6000 r--p 00007000 fd:00 201534086                  /usr/lib64/libcrypt-2.17.so
7f07dcea6000-7f07dcea7000 rw-p 00008000 fd:00 201534086                  /usr/lib64/libcrypt-2.17.so
7f07dcea7000-7f07dced5000 rw-p 00000000 00:00 0 
7f07dced5000-7f07dcef5000 r-xp 00000000 fd:00 201484222                  /usr/lib64/ld-2.17.so
7f07dd013000-7f07dd023000 rwxp 00000000 00:00 0 
7f07dd092000-7f07dd0e9000 rw-p 00000000 00:00 0 
7f07dd0f2000-7f07dd0f4000 rw-p 00000000 00:00 0 
7f07dd0f4000-7f07dd0f5000 r--p 0001f000 fd:00 201484222                  /usr/lib64/ld-2.17.so
7f07dd0f5000-7f07dd0f6000 rw-p 00020000 fd:00 201484222                  /usr/lib64/ld-2.17.so
7f07dd0f6000-7f07dd0f7000 rw-p 00000000 00:00 0 
7fffbe063000-7fffbe084000 rw-p 00000000 00:00 0                          [stack]
7fffbe11a000-7fffbe11c000 r-xp 00000000 00:00 0                          [vdso]
ffffffffff600000-ffffffffff601000 r-xp 00000000 00:00 0                  [vsyscall]

**Comment by dktapps** [comment]
Blame pthreads, nothing we can do about this.
