### ISSUE TITLE
Server crash 1.16.100

### ISSUE THREAD

**Issue by mri4ards** [pmmp/PocketMine-MP#3920]
### Issue description

- Expected result: Expected normal play after kernel update to 1.16.100
- Actual result: When a player logs into the server, the minecraft game closes or just crashes from the server

### Steps to reproduce the issue
1. when the player enters the server after 10 seconds
2. the server crashes

### OS and versions

* PocketMine-MP: 3.16.0 for Bedrock Edition 1.16.100 (protocol 419)
* PHP: 7.3
* Server OS: Linux
* Game version: PE/Win10 (delete as appropriate)

### Plugins
plugins are ok

### Crashdump, backtrace or other files
![image](https://user-images.githubusercontent.com/64589323/99889624-0a8a7880-2c68-11eb-912f-47f5521e2fd2.png)

**Comment by dktapps** [comment]
> plugins are ok

I'll be the judge of that.

You still haven't provided the full crashdump. If this is a problem with homemade multiversion I won't help you.
