### ISSUE TITLE
you cannot access the server from mobile data 3g, 4g, 5g, LTE, although the slider for this is enabled "Use cellular network for data transfer"

### ISSUE THREAD

**Issue by mri4ards** [pmmp/PocketMine-MP#3922]
you cannot access the server from mobile data 3g, 4g, 5g, LTE, although the slider for this is enabled "Use cellular network for data transfer"
![image](https://user-images.githubusercontent.com/64589323/99890385-ae2b5700-2c6f-11eb-8143-5b5001a7de7e.png)
![image](https://user-images.githubusercontent.com/64589323/99890404-dc109b80-2c6f-11eb-8a23-a76e48717b88.png)

**Comment by Jviguy** [comment]
This issue isn't pmmp issue that is minecraft. Pocketmine has nothing to do with you LTE network

**Comment by dktapps** [comment]
duplicate of #3921
