### ISSUE TITLE
Inventory Bug

### ISSUE THREAD

**Issue by Sonsa04** [pmmp/PocketMine-MP#3925]
### Issue description
Player can't open chest or their player inventory when player is viewing the chest and you teleported it.

### Steps to reproduce the issue
1. Ask someone to open a chest
2. Then teleport it to you

### OS and versions

* PocketMine-MP: 3.16.0
* PHP:
* Server OS: Linux
* Game version: PE/Win10 (delete as appropriate)

**Comment by dktapps** [comment]
This is a bug in the client approximately equivalent to the old ContainerClosePacket crash.
