### ISSUE TITLE
Crash on Start up (with a Crashdump)

### ISSUE THREAD

**Issue by Khaogamermain01** [pmmp/PocketMine-MP#3926]
### Issue description
The server crashes and makes a crash dump

### Steps to reproduce the issue
1. Do the steps of setting up the server
2. starting the server

### OS and version
* PocketMine-MP: 3.16.0
* Server OS: Macbook Air
* Game version: PE/Win 10

### Plugins
- Test on a clean server without plugins: is the issue reproducible without any plugins loaded? Yes

### Crashdump, backtrace or other files
https://crash.pmmp.io/view/4658933

**Comment by goliath7860** [comment]
..

**Comment by Khaogamermain01** [comment]
And how to stop the other server and make a new one? @dktapps
