### ISSUE TITLE
Interact Event Doesnt Run on Left Click air

### ISSUE THREAD

**Issue by opticalPvPX** [pmmp/PocketMine-MP#3928]
### Issue description

- Expected result: I expected the interact event to fire off when I left click air
- Actual result: Nothing

### Steps to reproduce the issue
1. Make a function that calls for all interact events and Broadcasts a message
2. Right click ground, right click air, left click ground, and left click air and see which doesnt work

### OS and versions

* PocketMine-MP: 3.16.0
* PHP: 7.4
* Server OS: Ubuntu 18.04
* Game version: PE/Win10/Xbox

**Comment by mr-zinkil** [comment]
Same with me

**Comment by dktapps** [comment]
It won't fire if you aren't holding any item. This is out of PM's control.

**Comment by opticalPvPX** [comment]
????

**Comment by opticalPvPX** [comment]
It doesnt fire in general

**Comment by opticalPvPX** [comment]
And it isnt client sided, bc i just fixed it with a sound packet.......

**Comment by Endermanbugzjfc** [comment]
Isn’t there a left click air huh

**Comment by dktapps** [comment]
There's no action bound to left-click on air, so the client never sends it. Using a sound packet is unreliable because it's not only sent in that circumstance, so you can drop your condescending attitude.

**Comment by dktapps** [comment]
Duplicate of #4598
