### ISSUE TITLE
Spawn egg bug with iron_golem or snow_golem

### ISSUE THREAD

**Issue by Danding1314** [pmmp/PocketMine-MP#3932]
* PocketMine-MP: 3.16.0
* PHP: 7.3.0
* Server OS: Win10
* Game version: Win10

Plugins: (1)：DevTools v1.13.0

When player type /give ID 383:20 <count>   the spawn egg will not send correctly with its shape.
![pa](https://user-images.githubusercontent.com/45899122/100494306-7cd4ee80-317b-11eb-93c2-a77728122ab9.PNG)

**Comment by dktapps** [comment]
These entities never had spawn eggs to begin with, so I don't know what the expected behaviour for this was in the first place.
