### ISSUE TITLE
Implement Vanilla Dropped Item entities merge into a single stack.

### ISSUE THREAD

**Issue by BenHeroPH** [pmmp/PocketMine-MP#3936]
## Description
- Item entities that represent a stack of more than one item appear as several items stuck together. Stacks of 2-16 appear as two items, 17–32 as three, 33-48 as four, and 49+ as five.
- When two stackable items of the same type come within 3/4 of a block of each other, they merge into a single stack if the resulting stack size does not exceed that item's maximum stack size.

## Steps to reproduce the issue
1. Drop Blocks on the ground
2. In Vanilla the item will merge into a single stack.

## Justification
- I belived Implementing this will reduce lagg for some low-end devices such as mobile users.

![image](https://user-images.githubusercontent.com/66245928/100537662-3f4c9000-3265-11eb-869e-ad6e40c09e77.png)

**Comment by BenHeroPH** [comment]
Pocketmine: 
![image](https://user-images.githubusercontent.com/66245928/100540363-f81bca80-3277-11eb-8f14-9ab3adbf0ae1.png)

**Comment by dktapps** [comment]
We've been over this before. The performance cost of having item entities scanning for other item entities to merge with is higher than the cost of just letting them sit where they are. Until we have an event-driven mechanism for entity collisions I have no intention of implementing this. It's counterproductive.
