### ISSUE TITLE
All players on PM Windows server have same ips

### ISSUE THREAD

**Issue by bajimu** [pmmp/PocketMine-MP#394]
if you start server on windows and invite some players with different ips that they all will have same ip (they ip will be as server ip).

**Comment by dktapps** [comment]
Without knowing your PocketMine-MP version, OS, PHP, Client version, or plugins and how the issue occurred, the issue cannot begin to be solved.
A pre-formatted template is provided that shows the required information to begin to find, test and solve an issue.
Until the adequate template and information is provided, the issue will be closed; it may be reopened if you update the ticket with the correct template and required information.

[Contribution guidelines](https://github.com/pmmp/PocketMine-MP/blob/master/CONTRIBUTING.md)
