### ISSUE TITLE
Server crashed

### ISSUE THREAD

**Issue by Smoked58** [pmmp/PocketMine-MP#3943]
Link to crashdump: 

### Additional comments (optional)
[Wed_Dec_2-21.18.40-UTC_2020.log](https://github.com/pmmp/PocketMine-MP/files/5632117/Wed_Dec_2-21.18.40-UTC_2020.log)

HELP PLEASE i kill a mob and it crashs how do i fix

**Comment by dktapps** [comment]
This is caused by a plugin.
