### ISSUE TITLE
Item Particle Bug

### ISSUE THREAD

**Issue by Govdim** [pmmp/PocketMine-MP#3945]
### Issue description

- Expected result: Effects must match the texture of the item
- Actual result: Effects do not match item texture

### Steps to reproduce the issue
1. I gave myself some bread
2. I started eating bread
3. Saw the effects of an iron pickaxe ._.

### OS and versions
* PocketMine-MP: 4.0.0
* PHP: 7.4
* Server OS: Ubuntu 20.04
* Game version: PE/Win10

### Plugins
NO

**Comment by dktapps** [comment]
Fixed by 37b969484512ca1757343dd921a3d7cb6a6d5456.
