### ISSUE TITLE
/kill's and $player -> setHealth (0) bug

### ISSUE THREAD

**Issue by bajimu** [pmmp/PocketMine-MP#395]
If player dies (and he would not press button "Respawn" or "Main menu") that he will be spawn smoke particle infinitely.
![image](https://cloud.githubusercontent.com/assets/19263759/23551495/92309ac2-001f-11e7-8f7b-b953166a6ff8.png)

**Comment by dktapps** [comment]
Without knowing your PocketMine-MP version, OS, PHP, Client version, or plugins and how the issue occurred, the issue cannot begin to be solved.
A pre-formatted template is provided that shows the required information to begin to find, test and solve an issue.
Until the adequate template and information is provided, the issue will be closed; it may be reopened if you update the ticket with the correct template and required information.

[Contribution guidelines](https://github.com/pmmp/PocketMine-MP/blob/master/CONTRIBUTING.md)
