### ISSUE TITLE
Place a block in ungenerated chunks crashes server

### ISSUE THREAD

**Issue by ipad54** [pmmp/PocketMine-MP#3951]
### Issue description

- Actual result: If I break or place a block in an ungenerated chunk, the server crashes. Player can place or break a block in ungenerated chunk if he fly very fast and will be place or break blocks (Sorry for my English, i use Google Translator)

### Steps to reproduce the issue
1. Place or break a block in ungenerated chunk

### OS and versions
* PocketMine-MP: 4.0.0
* PHP: 7.4
* Server OS: Ubuntu 18.04
* Game version: PE/Win10

### Plugins
None

**Comment by Blackjack200** [comment]
Actual result: change a block which in ungenerated chunk, the server will crash

**Comment by jasonwynn10** [comment]
Please provide a crash dump from your server.log file or a link to the crash on http://crash.pmmp.io

**Comment by dktapps** [comment]
Fixed by 1c49cedc8cc378a8a1cc62cd25ef33efa7110bbc.
