### ISSUE TITLE
Too many packet in single Batch

### ISSUE THREAD

**Issue by RinoXz** [pmmp/PocketMine-MP#3954]
Issue description

When I a craft a lot of Block at once from minerals (Lapis, diamond...).

### Steps to reproduce the issue
1. Give a lot of mineral
2. Open Crfating table
3. Craft a lot of Block at once fromp the minerals (with shift-click on computer or crafting menu on mobile.

### OS and versions
PocketMine-MP: 3.16.0
PHP: 7.3
Server OS:Debian 9
Game version: Win10 1.16.101

### Plugins
- No plugins used (expect DevTools)

### Crashdump, backtrace or other files
![Capture](https://user-images.githubusercontent.com/61470324/101241178-3db31a00-36f4-11eb-8a04-b958b70a7679.PNG)

### More 
Use default pocketmine.yml

**Comment by dktapps** [comment]
I don't plan on fixing this directly since that limit is in place to prevent DoS attacks. Instead, it's better fixed by implementing #3899.
