### ISSUE TITLE
Sky light level of water is not correctly calculated at the top of the world

### ISSUE THREAD

**Issue by dktapps** [pmmp/PocketMine-MP#3959]
### Issue description
https://github.com/pmmp/PocketMine-MP/blob/c4b47c6c067528454b685d68af61c705ddd8ce49/src/world/light/SkyLightUpdate.php#L154

This code silently fails when `currentHeight` is `256`, which occurs when there is a non-fully-transparent block at y=255.
This is a problem because it means that light from above the top of the chunk will not be propagated into that block, which is an issue for partially transparent blocks like water.

In particular, this case is affected, because there's no other way for light to reach the water except from directly up: 
![image](https://user-images.githubusercontent.com/14214667/101285699-81824e00-37de-11eb-954b-f4a9a96ae28d.png)
![image](https://user-images.githubusercontent.com/14214667/101285717-9c54c280-37de-11eb-8092-1e276b365898.png)
The expected result (which is correctly calculated on blockupdate) is this:
![image](https://user-images.githubusercontent.com/14214667/101285733-b5f60a00-37de-11eb-82d9-432d720802fb.png)

### Steps to reproduce the issue
1. Place water at the height limit, surrounded by solid blocks.
2. Restart the server (or quit and wait for the chunk to be unloaded).
3. Rejoin and observe the light levels.

### OS and versions

* PocketMine-MP: c4b47c6c067528454b685d68af61c705ddd8ce49

**Comment by dadodasyra** [comment]
I allow myself to add the fact that the water becomes flat instantly on the side where there is a diagonal bloc.
![image](https://user-images.githubusercontent.com/44753923/101533697-6d814c80-3996-11eb-82ec-8bd1082d7659.png)
![image](https://user-images.githubusercontent.com/44753923/101533726-77a34b00-3996-11eb-94ba-dc7c677a01b0.png)

**Comment by dktapps** [comment]
That has nothing to do with this issue. Besides, this is a rendering bug on the client, nothing to do with the server.

**Comment by ConnorHopper** [comment]
no
