### ISSUE TITLE
Hoe doesnt lose durability

### ISSUE THREAD

**Issue by JohnnyX071** [pmmp/PocketMine-MP#3962]
Hoes do not lose durability when you break sponges.

**Comment by dktapps** [comment]
Without knowing your PocketMine-MP version, OS, PHP, Client version, or plugins and how the issue occurred, the issue cannot begin to be solved.
A pre-formatted template is provided that shows the required information to begin to find, test and solve an issue.
Until the adequate template and information is provided, the issue will be closed; it may be reopened if you update the ticket with the correct template and required information.

[Contribution guidelines](https://github.com/pmmp/PocketMine-MP/blob/master/CONTRIBUTING.md)

**Comment by JohnnyX071** [comment]
I have the latest pocketmine version, I tried it with 0 plugins and still happening, everything is up to date
