### ISSUE TITLE
Hoe doesn't lose duarbility when breaking aponges

### ISSUE THREAD

**Issue by JohnnyX071** [pmmp/PocketMine-MP#3963]
Hoe doesn't lose durability when I break sponges.

PocketMine-MP: latest version
PHP: latest
Game version: Win10
I tried with 0 plugins and this was still happening!

**Comment by dktapps** [comment]
Without knowing your PocketMine-MP version, OS, PHP, Client version, or plugins and how the issue occurred, the issue cannot begin to be solved.
A pre-formatted template is provided that shows the required information to begin to find, test and solve an issue.
Until the adequate template and information is provided, the issue will be closed; it may be reopened if you update the ticket with the correct template and required information.

[Contribution guidelines](https://github.com/pmmp/PocketMine-MP/blob/master/CONTRIBUTING.md)

**Comment by JohnnyX071** [comment]
what do you mean? I said everything is in its latest version

**Comment by mmm545** [comment]
> LATEST IS NOT A VALID VERSION

**Comment by JohnnyX071** [comment]
so what's wrong? I said I have the latest versions

**Comment by JohnnyX071** [comment]
Pocketmine version: 3.17.0
PHP: the newest (i dont know how the newest is called but my dev installed it)
Game version: Win10 (1.16.200)

I tried with 0 plugins and this was still happening!

**Comment by Endermanbugzjfc** [comment]
Huh
