### ISSUE TITLE
Hoes doesn't loose durability when breaking sponges

### ISSUE THREAD

**Issue by JohnnyX071** [pmmp/PocketMine-MP#3965]
Hello, I found a bug where when you break sponges with a hoe, it doesn't lose durability. I tried with 0 plugins and this was still happening.

Pocketmine version: 3.17.0
PHP: newest (7)
Game version: Win10 Pro, Mc version 1.16.200

**Comment by Mohagames205** [comment]
Hey, I have successfully identified the cause of this problem. It seems like the Hoe item class does not have an onDestroyBlock method, which means no damage will be applied when it's used. I'll try to make a PR to fix this.

**Comment by JohnnyX071** [comment]
ok good!
