### ISSUE TITLE
Jenkins docs link doesn't work yet

### ISSUE THREAD

**Issue by jasonwynn10** [pmmp/PocketMine-MP#397]
### Issue description

The link to the [Latest API Documentation](https://jenkins.pmmp.io/job/PocketMine-MP%20Docs/doxygen/)
### Steps to reproduce the issue

1. Click the link in the readme

### OS and versions

* PocketMine-MP: irrelevant
* PHP: irrelevant
* Server OS: irrelevant
* Game version: irrelevant

### Crashdump, backtrace or other files

* None

**Comment by dktapps** [comment]
Yes, we're still in the process of setting things back up.
