### ISSUE TITLE
ServerSettingsResponsePacket error?

### ISSUE THREAD

**Issue by xorbs** [pmmp/PocketMine-MP#3982]
public function onDataPacket(DataPacketReceiveEvent $event) {
		$packet = $event->getPacket();
		if($packet instanceof ServerSettingsRequestPacket) {
			$packet = new ServerSettingsResponsePacket();
			$packet->formData = file_get_contents($this->getDataFolder() . "Setting.json");
			$packet->formId = 3218;
			$event->getPlayer()->dataPacket($packet);
		}
	}

I opened setting, but no response, no error.
I checked ServerSettingsRequestPacket have no problem

**Comment by Jviguy** [comment]
How is this a pmmp issue and you didn't even follow the issue template.

**Comment by Camotoy** [comment]
Actually, this is a Bedrock bug: https://bugs.mojang.com/browse/MCPE-94012. So regardless, nothing can be done (to my knowledge)
