### ISSUE TITLE
Add modded blocks

### ISSUE THREAD

**Issue by PiloudeDakar** [pmmp/PocketMine-MP#3986]
## Description
To be able to add modded blocks in pocketmine.

## Justification
Beceause 99% of pocketmine's server want this add.

## Alternative methods
Use an other world format.

**Comment by Jviguy** [comment]
You can use custom blocks in pocketmine.......

**Comment by PiloudeDakar** [comment]
> You can use custom blocks in pocketmine.......

How

**Comment by Jviguy** [comment]
Forbidden knowledge you must learn yourself.
