### ISSUE TITLE
.phar of pmmp 4

### ISSUE THREAD

**Issue by PiloudeDakar** [pmmp/PocketMine-MP#3987]
Do a pre-built .phar and start of pmmp 4.

To start developing servers for the stable version of pmmp 4.

**Comment by PiloudeDakar** [comment]
And I have a question pmmp is in php 7 or 8

**Comment by Endermanbugzjfc** [comment]
> 
> 
> Do a pre-built .phar and start of pmmp 4.
> 
> 
> 
> 
> 
> 
> 
> To start developing servers for the stable version of pmmp 4.
> 
> 
> 
> 
> 
> 
> 
> ## Alternative methods
> 
> 

There is no stable version for pm4. If there is, Dylan would have already did what you said.
