### ISSUE TITLE
No download to PHP 7.3

### ISSUE THREAD

**Issue by YTElectroGames** [pmmp/PocketMine-MP#3993]
### Issue description

- Expected result: For some reason there is no download for PHP 7.3 at https://jenkins.pmmp.io/job/PHP-7.3-Aggregate/
- Actual result: There is supposed to be a download for PHP 7.3 at https://jenkins.pmmp.io/job/PHP-7.3-Aggregate/

### Steps to reproduce the issue
1. Add the download back

### OS and versions

* PocketMine-MP: 3.x.x
* PHP: 7.3.x
* Server OS: Windows

### Plugins

- If you remove all plugins, does the issue still occur?
- If the issue is **not** reproducible without plugins:
  - It has nothing to do with plugins.

**Comment by Jviguy** [comment]
> There is supposed to be a download for PHP 7.3
Where is it stated that there is meant to be a download there.

**Comment by dktapps** [comment]
We don't supply 7.3 anymore.

**Comment by YTElectroGames** [comment]
> We don't supply 7.3 anymore.

Where do I download it then?

**Comment by YTElectroGames** [comment]
> > There is supposed to be a download for PHP 7.3
> > Where is it stated that there is meant to be a download there.

It says it here https://pmmp.readthedocs.io/en/rtfd/links.html
