### ISSUE TITLE
inventory transaction via hotbar switching flickers if sending attack packet or using item 

### ISSUE THREAD

**Issue by ambiennt** [pmmp/PocketMine-MP#3994]
- Expected result: Hotbat slots reliably switch when interacting with items
- Actual result: hotbar slots flicker and do not switch items if the action is done immediately after using an item or hitting an entity

### Steps to reproduce the issue
1. eat a food
2. switch to any other item as soon as you finish eating the food.
 -> hotbar slot switches back from new item to food item you just ate
 
 also happens with sending and landing an attack packet. 
 1) punch an entity rapidly (use autoclicker to test)
 2) switch to another item
  -> hotbar slot switches back from new slot selected in which you punched an entity
  
  https://www.youtube.com/watch?v=Y2n81_VYrS0&feature=youtu.be 
  example
  
  This bug is detrimental to PVP servers and has been in pocketmine forever. Apologies for the lack of detail here but if this was fixed then PVP servers would be improved greatly.

been in the game for a long time, as far back as 1.12
* Game version: all

 No additional plugins used

**Comment by dktapps** [comment]
Without knowing your PocketMine-MP version, OS, PHP, Client version, or plugins and how the issue occurred, the issue cannot begin to be solved.
A pre-formatted template is provided that shows the required information to begin to find, test and solve an issue.
Until the adequate template and information is provided, the issue will be closed; it may be reopened if you update the ticket with the correct template and required information.

[Contribution guidelines](https://github.com/pmmp/PocketMine-MP/blob/master/CONTRIBUTING.md)
