### ISSUE TITLE
Server Overload

### ISSUE THREAD

**Issue by FlxiBoy1313** [pmmp/PocketMine-MP#4011]
**(Translated by Google Translate)**
Hello, 
I have a Pocketmine server with the latest version so 3.17.3, but since this update it is so that my server is overloaded as soon as 1 player is online, I have just 2 pictures about that. I hope they try to fix it! 

In this picture it is first above:
![Screenshot 2021-01-27 232442](https://user-images.githubusercontent.com/65186341/106062290-de232a80-60f6-11eb-87d1-db390f56c235.png)
te)

This is the cutout from the console:
![Screenshot 2021-01-27 232531](https://user-images.githubusercontent.com/65186341/106062406-06128e00-60f7-11eb-86ff-de646f28b602.png)

I hope that they can do something with it and fix it as soon as possible!

With kind greetings
Felix

**Comment by dktapps** [comment]
Without knowing your PocketMine-MP version, OS, PHP, Client version, or plugins and how the issue occurred, the issue cannot begin to be solved.
A pre-formatted template is provided that shows the required information to begin to find, test and solve an issue.
Until the adequate template and information is provided, the issue will be closed; it may be reopened if you update the ticket with the correct template and required information.

[Contribution guidelines](https://github.com/pmmp/PocketMine-MP/blob/master/CONTRIBUTING.md)
