### ISSUE TITLE
Server Overload

### ISSUE THREAD

**Issue by FlxiBoy1313** [pmmp/PocketMine-MP#4013]
**Overview**
- I was expecting a version that is fixed and has fewer bugs.
- Since the update of Pocketmine-MP 3.17.3 the server is very quickly loaded, it starts already when only 1 player online, below are pictures.

**Fix**
- I don't know how to fix this bug or overload.

**Version**
PocketMine-MP: _3.17.3_
PHP: _8.0_
Server OS: _VServer = Linux = Ubuntu 20.04_

**Plugins**
Plugins (11): BuilderTools v1.2.0-beta2, ClanSystem v1.0.0, Commands v1, DevTools v1.14.2, EconomyAPI v5.7.2, FormAPI v1.3.0, Hub v1.0.0, MSG v1.0.0, MultiWorld v1.5.2, ReportSystem v1.0.0, Scoreboard v1.0.0
(DevTools, Mutliworld, FormAPI, BuilderTools and EconomyAPI come from the Internet, the other plugins from me)

**Picture 1:**
![Screenshot 2021-01-27 232442](https://user-images.githubusercontent.com/65186341/106063921-4a069280-60f9-11eb-93bd-17498360ff8b.png)

**Picture 2:**
![Screenshot 2021-01-27 232531](https://user-images.githubusercontent.com/65186341/106063942-51c63700-60f9-11eb-8daf-f3f61d7fd6e5.png)

(Translate by Google)

**Comment by dktapps** [comment]
Use `timings on` to start timings. Leave it for a couple of minutes (while it's overloaded), and then run `timings paste`. It will give you a link. Paste it here.

**Comment by FlxiBoy1313** [comment]
Yes,
here: https://timings.pmmp.io/?id=103646

**Comment by dktapps** [comment]
This is the fault of one of your plugins. The timings report shows that quite clearly.

**Comment by FlxiBoy1313** [comment]
Okay thanks
