### ISSUE TITLE
Non-stackable Item bug

### ISSUE THREAD

**Issue by Trxgically** [pmmp/PocketMine-MP#4017]
### Issue description

- Expected result: What were you expecting to happen? I was expecting all items to be there separately stacked.
- Actual result: What actually happened? When the player died another XP bottle was made and it overrode all other XP bottles causing them to be deleted.

### Steps to reproduce the issue
https://youtu.be/w4bZ6Yft7tU

https://poggit.pmmp.io/ci/Trxgically/XpBottles/XpBottles

### OS and versions

* PocketMine-MP: 3.17.2
* PHP: 7.4
* Server OS: Windows
* Game version: PE
### Plugins

- If you remove all plugins, does the issue still occur? Yes.
- If the issue is **not** reproducible without plugins:
  - Have you asked for help on our forums before creating an issue?
  - Can you provide sample, *minimal* reproducing code for the issue? If so, paste it in the bottom section

**Comment by dktapps** [comment]
> If you remove all plugins, does the issue still occur? Yes.

in the same issue as:
> https://poggit.pmmp.io/ci/Trxgically/XpBottles/XpBottles

This is your plugin's fault. https://github.com/Trxgically/XpBottles/blob/main/src/Trxgically/XpBottles/Main.php#L56

**Comment by TheNewHEROBRINEX** [comment]
This is a problem with your plugin: https://github.com/Trxgically/XpBottles/blob/6dc30eb5a92f05a13785a8e9f84618457477decd/src/Trxgically/XpBottles/Main.php#L57
Here you should do `$e->setDrops(array_merge($e->getDrops(), [$item]));`

**Comment by Trxgically** [comment]
> This is a problem with your plugin: https://github.com/Trxgically/XpBottles/blob/6dc30eb5a92f05a13785a8e9f84618457477decd/src/Trxgically/XpBottles/Main.php#L57
> Here you should do `$e->setDrops(array_merge($e->getDrops(), [$item]));`

Thank you very much!
