### ISSUE TITLE
PocketMine-MP is not listening at port.

### ISSUE THREAD

**Issue by camelCase-dumb** [pmmp/PocketMine-MP#4018]
### Issue description

- Expected result: The server must listening at port.
- Actual result: It's not listening, it prevents me to portforward.

### Steps to reproduce the issue
1. Must be on linux.
2. Start server.
3. run sudo netstat -tulpn to check what apps are listening and what port.

### OS and versions
* PocketMine-MP: 3.17.3
* PHP: 8.0.1
* Server OS: Linux (Arch Linux)
* Game version: PE/Win10 (delete as appropriate)

### Plugins
No plugins are installed.

### Crashdump, backtrace or other files
No crashes encountered... But I have a screenshot. (At bottom right terminal)
It must be showing "LISTENING" at state section.
![Screenshot from 2021-01-30 13-14-30](https://user-images.githubusercontent.com/56781329/106348102-a25ab180-62fe-11eb-9d62-2dcf776d0b84.png)

**Comment by TheNewHEROBRINEX** [comment]
LISTEN state is shown only for tcp ports. Your PocketMine server is running correctly.

**Comment by camelCase-dumb** [comment]
Wait it is working now, I don't know how did I fix it haha
