### ISSUE TITLE
Ender chest lid closes if 2 players are viewing and one of them closes their ender chest GUI

### ISSUE THREAD

**Issue by dktapps** [pmmp/PocketMine-MP#4021]
### Issue description
Ender chests don't track their own viewer count; instead they allow the inventory to do it, like a regular chest does.

This is problematic because an ender chest inventory is not actually a chest inventory - an ender chest is merely a gateway to a part of the player's own inventory. This means that (under normal circumstances) an `EnderChestInventory` never has more than 1 viewer.

### Steps to reproduce the issue
1. Have 2 players open an ender chest
2. Have one of them close their ender chest GUI.
3. On the other client, you can see that the ender chest lid is now closed.

### OS and versions

* PocketMine-MP: 3.17.4 / 4.0.0 @ d4290837f33655fd0de629bbac1228cedd680526
* PHP: 7.4.14

**Comment by XsexUsexV** [comment]
Javier Leon9966 Kindly shut the fuck up and kill yourself dirty plugin thief.

**Comment by XsexUsexV** [comment]
@everyone

**Comment by XsexUsexV** [comment]
javierleon9966

**Comment by XsexUsexV** [comment]
Hi.

**Comment by XsexUsexV** [comment]
How are you

**Comment by XsexUsexV** [comment]
Yes add my discord xuv#4356
