### ISSUE TITLE
Quick equipping the same armor makes it disappear

### ISSUE THREAD

**Issue by Unickorn** [pmmp/PocketMine-MP#4022]
### Issue description

After right clicking to equip armor while wearing the exact same item, the item disappears instead of swapping with the equipped armor.

### Steps to reproduce the issue
1. Wear any armor.
2. Right click to quick equip the exact same armor.

### OS and versions

* PocketMine-MP: 4.0.0 @ d4290837f33655fd0de629bbac1228cedd680526

### Video
https://streamable.com/9vo1ye

**Comment by dktapps** [comment]
Fixed, thanks!
