### ISSUE TITLE
Bug with updating blocks

### ISSUE THREAD

**Issue by Govdim** [pmmp/PocketMine-MP#4024]
### Issue description

- Expected result: All block changes should be correctly displayed for players
- Actual result: At a random moment in time, the player may not see the block change, including destruction or placing

Players complain about a non-working cobblestone generator, lava does not flow. But in fact, the lava is being prevented from flowing by a cobblestone that for some reason those players did not see.

### Steps to reproduce the issue
1. Use a cobblestone generator
2. Build a pillar from falling blocks and break the lowest one
3. Repeat both actions several times until a bug occurs (preferably in the presence of other players)

### OS and versions
* PocketMine-MP: 4.0.0
* PHP: 7.4
* Server OS: Ubuntu 20.04
* Game version: PE/Win10

**Comment by dktapps** [comment]
Can you create a video to demonstrate?

**Comment by Govdim** [comment]
> Can you create a video to demonstrate?

It will be difficult, but I will try))

**Comment by Govdim** [comment]
Oh, sorry, my own plugin was to blame)
