### ISSUE TITLE
server.log system like Bukkit

### ISSUE THREAD

**Issue by AkmalFairuz** [pmmp/PocketMine-MP#4029]
## Description
- Move server.log to logs/ new folder.
- Backup and compress server.log to .gz every 1 day and rename to date format then create new server.log.

## Justification
Easy find error and lower disk usage.

**Comment by SOF3** [comment]
Also suggested in old repo: https://github.com/PocketMine/PocketMine-MP/pull/3146

**Comment by dktapps** [comment]
I don't think a daily log suits. In many cases it would just fill the disk with tiny archives. The solution I was considering is to archive it when it reaches a certain size.

**Comment by SOF3** [comment]
Edit: this was the original issue. https://github.com/PocketMine/PocketMine-MP/issues/3079#issue-82365382

**Comment by KygekDev** [comment]
> I don't think a daily log suits. In many cases it would just fill the disk with tiny archives. The solution I was considering is to archive it when it reaches a certain size.

Yes, that's a better idea

**Comment by dktapps** [comment]
Implemented by #4032, minus the compression step. (Due to performance considerations, I figured it made more sense to let the user configure external tools like cron to delete or compress the files as they see fit.)
