### ISSUE TITLE
One oak tree log block is missing

### ISSUE THREAD

**Issue by KuriSan-Fox** [pmmp/PocketMine-MP#4034]
### Issue description

In vanilla, the tree has only one leaves(ID: 18) block, but PMMP has two tiers, and one log(ID: 17) block is missing.
PMMP is the latest version and no plugins are installed.
Affects both the tree that is automatically generated in the world and the tree that Sapling (ID: 6) grows and generates.
(I'm sorry it's hard to understand because I can't speak English well)
![Minecraft 2021_02_13 17_39_54](https://user-images.githubusercontent.com/78953997/107845917-9ef91700-6e22-11eb-9719-4eab7def9c67.png)
![Minecraft 2021_02_13 17_18_01](https://user-images.githubusercontent.com/78953997/107845918-a02a4400-6e22-11eb-9963-9ef629222edb.png)

### Steps to reproduce the issue
1. Start Server.
2. use Sapling or go forest

### OS and versions

* PocketMine-MP: 3.17.4
* PHP: 7.4
* Server OS: Windows10

### Plugins

no.

**Comment by dktapps** [comment]
The height is randomised. Not every tree is the same.

**Comment by KuriSan-Fox** [comment]
No, that doesn't mean that.
I know the height is random.
Even if the logs are the same height, they have been replaced with 1 block leaves.
![フォト 2021_02_14 21_32_04](https://user-images.githubusercontent.com/78953997/107876976-c0363200-6f0c-11eb-8ca7-a2bc9bc3e52d.png)
![フォト 2021_02_14 21_32_42](https://user-images.githubusercontent.com/78953997/107876981-c5937c80-6f0c-11eb-80e5-3b387d9c7126.png)
