### ISSUE TITLE
Server crashed - LevelDB (PHP8)

### ISSUE THREAD

**Issue by JaxkDev** [pmmp/PocketMine-MP#4035]
Link to crashdump: 
https://crash.pmmp.io/view/4762023

### Additional comments (optional)
PHP8 Binaries used https://jenkins.pmmp.io/view/PHP/job/PHP-8.0-Aggregate/2/ (Windows)
Pocketmine-mp API 3.17.5-dev (git commit 094102fe)
Obviously this only a problem with leveldb as level provider.

**Comment by dktapps** [comment]
Pull the latest changes. It's already fixed by 18666e5a60f504c31be1d18913d94c672f655b4d.

**Comment by JaxkDev** [comment]
I did.

**Comment by BeetGaming45** [comment]
I do also had the same problem through my minecraft server, I did update to the latestversion of the software but it also display the same error:


2021-02-14 [09:24:29] [Server thread/ERROR]: Could not load world "world": Specified LevelDB world format version (8) is not supported
--
22 | 2021-02-14 [09:24:29] [Server thread/EMERGENCY]: No default world has been loaded

**Comment by JaxkDev** [comment]
Not the same error, and no where near related to this issue.

**Comment by BeetGaming45** [comment]
Well it still related to server crashing..

> > I do also had the same problem to
> > my Minecraft server, I did update to the latest version of the software but it still also display the same error:
> > **2021-02-14 [09:24:29] [Server thread/ERROR]: Could not load world "world": Specified LevelDB world format version (8) is not supported**
> > **-- 22 | 2021-02-14 [09:24:29] [Server thread/EMERGENCY]: No default world has been loaded**
> 
> Not the same error, and no where near related to this issue.

Well the thing is that it still related to server crash..

**Comment by mmm545** [comment]
It's not even a crash, and your error isn't a bug anyway
