### ISSUE TITLE
server-build.php cant compress the pmmp.phar

### ISSUE THREAD

**Issue by ibratabian17** [pmmp/PocketMine-MP#4036]
Fatal error: Uncaught BadMethodCallException: unable to create temporary file in /mnt/e/IbraDev/pmmp4/PocketMine-MP/build/server-phar.php:119
Stack trace:
#0 /mnt/e/IbraDev/pmmp4/PocketMine-MP/build/server-phar.php(119): Phar->compressFiles(4096)
#1 /mnt/e/IbraDev/pmmp4/PocketMine-MP/build/server-phar.php(171): pocketmine\build\server_phar\buildPhar('/mnt/e/IbraDev/...', '/mnt/e/IbraDev/...', Array, Array, '<?php\n\n$tmpDir ...', 2, 4096)
#2 /mnt/e/IbraDev/pmmp4/PocketMine-MP/build/server-phar.php(177): pocketmine\build\server_phar\main()
#3 {main}
  thrown in /mnt/e/IbraDev/pmmp4/PocketMine-MP/build/server-phar.php on line 119

**Comment by dktapps** [comment]
It's a bug in PHP. You can work around it by setting `ulimit -n` to some bigger number, e.g. `8192`.
