### ISSUE TITLE
All entities (without a player) soar on pressure plates

### ISSUE THREAD

**Issue by ipad54** [pmmp/PocketMine-MP#4045]
### Issue description

- Actual result: All entities (without a player) soar on pressure plates

### Steps to reproduce the issue
1. Spawn entity (e.x Zombie) on pressure plate

### OS and versions

* PocketMine-MP: 4.0.0
* PHP: 7.4
* Server OS: Ubuntu 18.04
* Game version: PE/Win10

### Plugins

- If you remove all plugins, does the issue still occur?
- If the issue is **not** reproducible without plugins:
  - Reproduce without plugins

### Crashdump, backtrace or other files
![Screenshot_20210222_131441_com mojang minecraftpe](https://user-images.githubusercontent.com/63200545/108694623-58857580-7510-11eb-9a8c-b6a6a572ba62.jpg)

**Comment by dktapps** [comment]
This happens because entities are assumed to be "on ground" when they are first spawned.

**Comment by dktapps** [comment]
As it turns out, this had nothing to do with "on ground", and everything to do with the fact that pressure plate was assumed to have a 1x1x1 collision box.
