### ISSUE TITLE
$chunk->getBiomeIdArray() returns something strange 

### ISSUE THREAD

**Issue by ConfusedTick** [pmmp/PocketMine-MP#4047]
Pmmp: 3.17.5
Os: Linux(Ubuntu)
Php version: 7.3.21
Ram: 2 Gb

Function getBiomeIdArray in pocketmine\level\Chunk in ChunkPopulateEvent (pocketmine\event\level\ChunkPopulateEvent) returns something strange
Screenshot:

![Screenshot_2021-02-22-21-30-32-0682819376](https://user-images.githubusercontent.com/76158011/108753229-8640dd80-7555-11eb-91bc-43ac680b470e.png)

code:
public function onPopulate(ChunkPopulateEvent $e){
$chunk=$e->getChunk();
$this->getServer()->broadcastMessage("".$chunk->getBiomeIdArray());
}

**Comment by dktapps** [comment]
This is meaningless. The biome IDs array is not fit for human eyes, it's a raw byte array.
