### ISSUE TITLE
Non-source lava which flows down can generate obsidian

### ISSUE THREAD

**Issue by SalmonDE** [pmmp/PocketMine-MP#4050]
### Issue description

- Expected result: What were you expecting to happen?
Obsidian should not be generated by this contraption.

- Actual result: What actually happened?
Obsidian was generated, as seen in the picture.

### Steps to reproduce the issue
![image](https://user-images.githubusercontent.com/15953947/109160792-89ff7a80-7776-11eb-8d2b-2dfc1cf917eb.png)

1. Block the water source and let the lava flow down in a setup like on the picture.
2. Let the water flow.
3. A obsidian block should be generated.

### OS and versions

* PocketMine-MP: PM 4 (master branch) a49ee0d6b01fa34989e04ff7fffc0c3f0d603b42
* PHP: irrelevant it seems, but php 8.0.3RC1
* Server OS: irrelevant, but Raspberry Pi OS (64 bit)

**Comment by dktapps** [comment]
> PHP: irrelevant it seems, but php 8.0.3RC1

JIT has shown us that this assumption can't be made anymore. Thanks for including it.
