### ISSUE TITLE
Player in my hosted world keeps getting banned

### ISSUE THREAD

**Issue by Scottchy800** [pmmp/PocketMine-MP#4055]
hey everyone, new to MC but am hosting own PE on Linux... my friend keeps getting banned and i use the terminal to unban, but each time he logs back in, it bans him again... i unbanned him, pardoned, etc... i even changed his gamertag but now this one gets banned on my own server... no deathbans or plugins... can anyone help?

**Comment by T14Raptor** [comment]
Sounds like #2175

Make sure you have `hardcore` turned off in server.properties

**Comment by Scottchy800** [comment]
Thank you @T14Raptor !!  That was it exactly!!  Thank you very much!!!  :)

**Comment by GangMemberXuvah** [comment]
t14 raptor is a groomer

**Comment by GangMemberXuvah** [comment]
XD

**Comment by GangMemberXuvah** [comment]
tell muqshit to kill himself

**Comment by GangMemberXuvah** [comment]
sex time
