### ISSUE TITLE
Dupe with Itemframe 

### ISSUE THREAD

**Issue by DragonfireHD** [pmmp/PocketMine-MP#4058]
### Issue description

- Expected result: The ItemFrame duped Armor?
- Actual result: I duped Armor from the ItemFrame but i Equiped and the go's in the inventory?

### Steps to reproduce the issue
1. Take a ItemFrame an place that
2. Put a armor in the itemframe 
3. Put in Put out you Equiped the armor and have more armor pieces in your Inventory 

https://youtu.be/hLv1RZRH3N8

### OS and versions

* PocketMine-MP: 1.13.6
* PHP: 7.4.13
* Server OS: idk 🤷‍♂️
* Game version: PE

### Plugins
 the Problem is a Problem with pmmp i try it if no plugins

- If you remove all plugins, does the issue still occur?
- answer: yes
- If the issue is **not** reproducible without plugins:
  - Have you asked for help on our forums before creating an issue?
 - answer: yes 
  - Can you provide sample, *minimal* reproducing code for the issue? If so, paste it in the bottom section
 - answer: no but i have a video for this Problem

### Crashdump, backtrace or other files
No Crushdumps just a Dupe bug

**Comment by DragonfireHD** [comment]
Uploading InShot_20210304_005108915.mp4…

**Comment by DragonfireHD** [comment]
I send link from Video

**Comment by DragonfireHD** [comment]
https://youtu.be/hLv1RZRH3N8

**Comment by thebigsmileXD** [comment]
looks like a plugin issue to me

**Comment by kenygamer** [comment]
> https://youtu.be/hLv1RZRH3N8

I have a question, if you have stated in your issue template that you have removed the ENTIRETY of the plugins, why does your demonstration video show that you are using plugins?

**Comment by DragonfireHD** [comment]
It is 600 mb Server anf i tested this and with plugins and no Plugins I also said it either way that the plugins are not the cause and I hate it when one theories just because I wanted to report a bug

**Comment by DragonfireHD** [comment]
@kenygamer

**Comment by DragonfireHD** [comment]
My English is not good (sorry)

**Comment by dktapps** [comment]
I'm not able to reproduce this, and your video only shows that this occurs _with_ plugins.
