### ISSUE TITLE
/kill's and $player -> setHealth (0) bug

### ISSUE THREAD

**Issue by buggerfinder** [pmmp/PocketMine-MP#406]
If player dies (and he would not press button "Respawn" or "Main menu") that he will be spawn smoke particle infinitely. It cause a very small fps after died.

* PocketMine-MP: https://github.com/pmmp/PocketMine-MP/commit/93896977d0ba5cf23748b8c4a7e108daa196ce8b
* PHP: 7
* Server OS: Win7 64bit
* Game version: MCPE 1.0.3.0

![image](https://cloud.githubusercontent.com/assets/19263759/23551495/92309ac2-001f-11e7-8f7b-b953166a6ff8.png)

**Comment by dktapps** [comment]
This appears to be a client issue. The same also occurs in vanilla multiplayer.

Also note that ban evasion may result in you getting banned from the repository permanently.
