### ISSUE TITLE
Too many backets in a single batch, players player.dat file was reset or removed

### ISSUE THREAD

**Issue by Prim69** [pmmp/PocketMine-MP#4060]
### Issue description

- Expected result: Client to crash with internal server error normally
- Actual result: Client sent too many packets in a single batch, crashed from internal server error, and his player data file was deleted (when he logged back in right after it said player data not found, creating new profile)

### Steps to reproduce the issue
I have no idea

### OS and versions

* PocketMine-MP: 3.17.5
* PHP: 7.4
* Server OS: Ubuntu
* Game version: Player was on Windows 10

### Plugins
Plugins (2): Core, PurePerms

- If you remove all plugins, does the issue still occur?
   Well I have no idea how to reproduce it but the player probably crashed due to auto clicking, I know it's not my core causing it because I don't handle anything packet related, or touch the players data at all. My duel command which was used before the player crashed (but not the cause of it) simply adds the player to an array.

- If the issue is **not** reproducible without plugins:
  - Have you asked for help on our forums before creating an issue?
  - Can you provide sample, *minimal* reproducing code for the issue? If so, paste it in the bottom section

### Crashdump, backtrace or other files

![image](https://user-images.githubusercontent.com/13991048/110176968-2c9ca680-7dd2-11eb-8662-a90f2b19c6a9.png)

**Comment by ethaniccc** [comment]
that PocketMine-MP version looking kind of sus

**Comment by dktapps** [comment]
I can't do anything with this without reproducing information (and you also haven't provided any version).

**Comment by xJustJqy** [comment]
> I can't do anything with this without reproducing information (and you also haven't provided any version).

3.17.5

**Comment by Prim69** [comment]
My bad, I updated it with the version, but still nothing for reproducing. Hopefully someone else encounters this error and knows how to reproduce it.

**Comment by kenygamer** [comment]
When you use a too powerful nuker tool, you are kicked with this exact message.

The "creating new profile" message is because the client logged in, crashed and thus, did not save their NBT. They were simply kicked out before their data was saved.

**Comment by dktapps** [comment]
> The "creating new profile" message is because the client logged in, crashed and thus, did not save their NBT.

This is incorrect. Client crashing doesn't have any bearing on the server saving data.

However

> They were simply kicked out before their data was saved.

This is correct.

Player data is not saved unless the player actually spawned on the server (i.e. PlayerJoinEvent was called). Therefore, if you get kicked for sending a very large batch (as in this case), the server will not generate any data for the player, and it also won't save it. This results in the playerdata being generated the next time the player joins without trying to attack the server.
