### ISSUE TITLE
Server crashed

### ISSUE THREAD

**Issue by Crasher508** [pmmp/PocketMine-MP#4066]
Moin,

My server has a problem with AsyncTask. On the PMMP Discord nobody can find a error.  It must be a Issues in PocketMine-MP/PHP

CrashDump:
https://pastebin.com/2mpa251A

Pictures that you can see that nothing is wrong there
![Screenshot (913)](https://user-images.githubusercontent.com/45127993/110764024-d2c53200-8252-11eb-9703-32025be5d60c.png)
![Screenshot (912)](https://user-images.githubusercontent.com/45127993/110764048-d953a980-8252-11eb-8896-e54871c245f4.png)

**Comment by SalmonDE** [comment]
You mustn't carry a reference to the server instance over into another thread.
In this case, I believe you are indirectly doing so by including one or more Level object(s) within your $daten array.

**Comment by jasonwynn10** [comment]
Your code stores a level object into an array which you are passing to the other thread. The level object contains a server reference, which is causing your crash.
