### ISSUE TITLE
Player cannot connect to server when default gamemode is 3

### ISSUE THREAD

**Issue by leolee3914** [pmmp/PocketMine-MP#4069]
### Issue description

- Expected result: player can connect to server
- Actual result: player cannot connect to server

### Steps to reproduce the issue
1. set gamemode=3 in server.properties
2. start the server and try to connect

### OS and versions

* PocketMine-MP: 3.18.0
* PHP: 7.4.12
* Server OS: Win10
* Game version: PE

### Plugins

- If you remove all plugins, does the issue still occur? yes
- If the issue is **not** reproducible without plugins:
  - Have you asked for help on our forums before creating an issue?
  - Can you provide sample, *minimal* reproducing code for the issue? If so, paste it in the bottom section

**Comment by DaisukeDaisuke** [comment]
This is a video that reproduces this problem.
https://youtu.be/J2yhUZ_f3HY
<details>
<summary>open images</summary>

![20210313-154950-157](https://user-images.githubusercontent.com/17798680/111022094-09967600-8414-11eb-8973-7ff326121364.jpg)
![20210313-155015-282](https://user-images.githubusercontent.com/17798680/111022092-07ccb280-8414-11eb-8417-fba04e79cbaa.jpg)
![20210313-155034-540](https://user-images.githubusercontent.com/17798680/111022093-08fddf80-8414-11eb-9809-589b134e7ccf.jpg)
</details>

**Comment by DaisukeDaisuke** [comment]
There is a possibility that it is incorrect, but it seems that this problem does not occur if the following character string is set to something other than "Spectator".
https://github.com/pmmp/PocketMine-MP/blob/ccc76cf33852fad3e0cca8ab805b8b15cd503f76/src/pocketmine/Server.php#L491
https://github.com/pmmp/PocketMine-MP/blob/ccc76cf33852fad3e0cca8ab805b8b15cd503f76/src/pocketmine/Server.php#L482-L493
May be involved.
https://github.com/pmmp/PocketMine-MP/blob/74bef7f4237dfaf5d80af2d0a493944ade1fd068/src/pocketmine/network/mcpe/RakLibInterface.php#L205-L218

**Comment by dktapps** [comment]
This is probably because of the client validating the pong fields. This is so stupid, it isn't even visible on the UI ...
