### ISSUE TITLE
Server cannot be started if PMMP is in src format (PMMP version 3.18.0) 

### ISSUE THREAD

**Issue by User8539** [pmmp/PocketMine-MP#4070]
ERROR] Composer dependencies and/or autoloader are out of sync.
[ERROR] - Current revision is 0000000000000000000000000000000000000000
[ERROR] - Composer dependencies were last synchronized for revision 3f6490626319152dca07a5c61a1e94f8d5793d56
[ERROR] Out-of-sync Composer dependencies may result in crashes and classes not being found.
[ERROR] Please synchronize Composer dependencies before running the server.

**Comment by DaisukeDaisuke** [comment]
This is the intended behavior.
If you want to run pocketmain-mp from source code in an environment where git is available, please install it using git.
Please see BUILDING.md.
https://github.com/pmmp/PocketMine-MP/blob/stable/BUILDING.md

**Comment by Jviguy** [comment]
It still does this with git as I just cloned it earlier, but yes you should use git, but it seems that the composer dependencies are out of sync in general, which can be fixed with `composer install --no-dev`

**Comment by User8539** [comment]
Where to enter `composer` install `--no-dev`?

**Comment by User8539** [comment]
I am running on a VPS server with OS Ubuntu 18.04
Before the release of PMMP 3.17.6, everything started fine.

**Comment by SOF3** [comment]
> this issue tracker is not intended for support requests

**Comment by dktapps** [comment]
The deps are not out of sync. This happens purely because this user extracted a phar instead of using git sources like a normal person.
