### ISSUE TITLE
The server cannot be started if the src version of PMMP is installed (3.17.6 - 3.18.0) Sorry for repeating the request, I did not understand how this is solved.

### ISSUE THREAD

**Issue by User8539** [pmmp/PocketMine-MP#4071]
This is my first time writing a request on Github, I can admit inaccuracies in creating a request.

`OS: Ubuntu 18.04 (VPS)`
`git and composer not installed in this system`

Before release 3.17.6 everything started fine, on the same system

This error:

[ERROR] Out-of-sync Composer dependencies may result in crashes and classes not being found.
[ERROR] Please synchronize Composer dependencies before running the server.
[ERROR] Composer dependencies and/or autoloader are out of sync.
[ERROR] - Current revision is 0000000000000000000000000000000000000000
[ERROR] - Composer dependencies were last synchronized for revision 3f6490626319152dca07a5c61a1e94f8d5793d56

**If you use the .phar version, everything starts.**

**Regarding src, I use the unpacked .phar version, where there are 2 folders: vendor, src**

**Comment by dktapps** [comment]
Use the git source instead of unpacking the phar. This is an XY problem.

**Comment by User8539** [comment]
Same problem when using source code

**Comment by dktapps** [comment]
This does not occur using git source, otherwise our CI builds would be failing...

**Comment by User8539** [comment]
I don't understand why, I download the source in .zip format, add the vendor folder, the same problem. Also there is a question about the source of the .zip archive. Initially, there is no vendor folder, the kernel swears, that is, you can still start the kernel somehow without it?

**Comment by User8539** [comment]
I'm sorry if I wrote it wrong, I just don't use English as my primary.

**Comment by dktapps** [comment]
> Use the **git source** instead of unpacking the phar. This is an XY problem.

**Comment by User8539** [comment]
The source code in .zip format I use with git. That is, it does not work with unpacking .phar, as well as with the source .zip But before the release of 3.17.6 everything worked ...
