### ISSUE TITLE
Prometheus Exporter

### ISSUE THREAD

**Issue by benyanke** [pmmp/PocketMine-MP#4072]
## Description
I would love to see prometheus metrics for the various things in the server (like connected users, worlds, etc)

## Justification
Provide monitoring for servers, to allow tracking of metrics and monitoring.

## Alternative methods
Custom data scraper.

**Comment by dktapps** [comment]
This can be implemented with a plugin. It's not something that should be in the core (especially since I've never heard of Prometheus).

**Comment by benyanke** [comment]
Thanks! I'll look at plugin development. For what it's worth, it's one of the leading data collection and application monitoring platforms.
