### ISSUE TITLE
Fix your program

### ISSUE THREAD

**Issue by fslinkiboo26** [pmmp/PocketMine-MP#4073]
I've unsubscribed from getting the emails about ur stupid ass minecraft stuff and I still get the emails everyday 

- Expected result: I expect you to fix his bullshit and unsubscribe me 
- Actual result: What actually happened?

### Steps to reproduce the issue
1. ...
2. ...

### OS and versions

* PocketMine-MP:
* PHP:
* Server OS:
* Game version: PE/Win10 (delete as appropriate)

### Plugins

- If you remove all plugins, does the issue still occur?
- If the issue is **not** reproducible without plugins:
  - Have you asked for help on our forums before creating an issue?
  - Can you provide sample, *minimal* reproducing code for the issue? If so, paste it in the bottom section

**Comment by mmm545** [comment]
Blame GitHub!!!

**Comment by dktapps** [comment]
Unsubscribe yourself. It's not rocket science.
