### ISSUE TITLE
Server crashed

### ISSUE THREAD

**Issue by Steellgold** [pmmp/PocketMine-MP#4075]
Link to crashdump: 

### Additional comments (optional)
[Sat_Mar_6-11.36.51-CET_2021.log](https://github.com/pmmp/PocketMine-MP/files/6136653/Sat_Mar_6-11.36.51-CET_2021.log)

**Comment by mmm545** [comment]
`THIS CRASH WAS CAUSED BY A PLUGIN`

**Comment by Steellgold** [comment]
Wrong place :/
