### ISSUE TITLE
Sun Report

### ISSUE THREAD

**Issue by FlxiBoy1313** [pmmp/PocketMine-MP#4078]
### Issue description

- A bug free use of the new Pocketmine API.
- The sun shows weird things

### Steps to reproduce the issue
1. Good Question.

### OS and versions
* PocketMine-MP: 3.18.0
* PHP: 7.4
* Server OS: Windows
* Game version: Win10

### Plugins
Multiworld and FormAPI

### Extra
I don't have a texture pack inside, nothing on the server so from my side it can't be just night vision as an effect with me.

![Screenshot 2021-03-14 211943](https://user-images.githubusercontent.com/65186341/111082895-06ca7c80-850b-11eb-950e-a6c2666c65d1.png)

**Comment by dktapps** [comment]
I can't reproduce this. It's more likely to be a client-sided graphical glitch than a problem with PM. Try and reproduce it in vanilla.

**Comment by FlxiBoy1313** [comment]
Okay thansk.
