### ISSUE TITLE
Incorrect russian translation in /gamemode

### ISSUE THREAD

**Issue by buggerfinder** [pmmp/PocketMine-MP#408]
If player can see private admin's messsages that he can see this mistakes.

* PocketMine-MP: https://github.com/pmmp/PocketMine-MP/commit/93896977d0ba5cf23748b8c4a7e108daa196ce8b
* PHP: 7
* Server OS: Win7 64bit
* Game version: MCPE 1.0.3.0
*Language in pocletmine.yml : rus

![image](https://cloud.githubusercontent.com/assets/26298769/23747641/12bab6f2-04c9-11e7-8b6c-2ca671b28c9f.png)
![image](https://cloud.githubusercontent.com/assets/26298769/23747882/f6121008-04c9-11e7-950f-a2011e25183f.png)

**Comment by dktapps** [comment]
Wrong repository.

**Comment by buggerfinder** [comment]
@dktapps no. "blame mojang" in the Gamemode command file
