### ISSUE TITLE
Armor Bug

### ISSUE THREAD

**Issue by UnknownOre** [pmmp/PocketMine-MP#4080]
### Issue description

- Expected result: Armor moving without the action being reverted
- Actual result: at random times the armor decide to stop moving from the armor slot to the inventory slot and the action keep being reverted

### Steps to reproduce the issue
1. no idea because it happens randomly

### OS and versions
* PocketMine-MP: 3.18.0
* PHP: 7.4
* Server OS: Linux
* Game version: Win10 (idk if it happens on phone)
### Plugins
fresh server

**Comment by dktapps** [comment]
It's not helpful to report this without any reproducing information. I won't waste my time on wild goose chase bug hunts.

**Comment by UnknownOre** [comment]
what about using the transactions system?
