### ISSUE TITLE
PlayerQuitEvent gets called when a player disconnects before fully spawning in

### ISSUE THREAD

**Issue by T14Raptor** [pmmp/PocketMine-MP#4083]
### Issue description

- Expected result: PlayerQuitEvent only getting called whenever the player disconnects and is spawned in (after PlayerJoinEvent)
- Actual result: PlayerQuitEvent getting called whenever the player disconnects, even before spawning in (PlayerJoinEvent isn't called)

### Steps to reproduce the issue
1. Send a client to the server, do login sequence
2. Disconnect right before SetLocalPlayerAsInitializedPacket is sent

### OS and versions
* PocketMine-MP: 3fe0adbd7f486be16d813e46917a49dc8f3fd33b

**Comment by SOF3** [comment]
Can you provide any justification why it shouldn't call PlayerQuitEvent when the player is only spawning in?

**Comment by T14Raptor** [comment]
This change wasn't documented in the 4.0.0 changelog (this change was committed before the first snapshot). I doubt it's intentional.
