### ISSUE TITLE
Server not hosting loacaly

### ISSUE THREAD

**Issue by NFGamerMC** [pmmp/PocketMine-MP#409]
### Issue description

I am unable to join my server on other networks while using my external ip

### Steps to reproduce the issue

1. Install pmmp 
2.portforward
3. Use other network and try to join
4. You won't be able to join

### OS and versions

* PocketMine-MP: API 3.0.0-ALPHA4
* PHP: 7.0
*Computer OS:  Win10
* Server OS: No Server OS, Hosting Localy
* Game version: PE/Win10 (delete as appropriate)

### Crashdump, backtrace or other files

*  New Server, we don't have a crash dump

**Comment by dktapps** [comment]
This is a support request, not an issue. Ask on the [forums](forums.pmmp.io).
