### ISSUE TITLE
Command blocks do not placed

### ISSUE THREAD

**Issue by benjaluth09** [pmmp/PocketMine-MP#4091]
Hi! I use Pocketmine for the plugins but I have a problem, the problem is that the Command Block is placed but removed if it is placed and in the chat says "Given 1× *Unknown* to benjaluth09" but it should say Command Block not Unknown. Please fix that. Thanks!

**Comment by benjaluth09** [comment]
This issue it's an issue not a support request.

**Comment by jasonwynn10** [comment]
Command blocks aren't coded for. We know they aren't coded for, and we don't intent to write code for them. Use a plugin if you want the functionality.
