### ISSUE TITLE
Command block

### ISSUE THREAD

**Issue by benjaluth09** [pmmp/PocketMine-MP#4092]
### Command Block
 Hi I founded a error, the error I'd that the **Command Block** is placed but removed.
And in the chat says that I given me an unknown block Given 64× **Unknown** to benjaluth09.
Fix it. Thanks!
PD: This is not a support request

**Comment by benjaluth09** [comment]
I am telling you not that it is not a support request

**Comment by jasonwynn10** [comment]
Command blocks aren't coded for. We know they aren't coded for, and we don't intent to write code for them. Use a plugin if you want the functionality.
