### ISSUE TITLE
Sign Content does not reload - PM4

### ISSUE THREAD

**Issue by Arthur4848** [pmmp/PocketMine-MP#4095]
### Issue description

- Expected result: What were you expecting to happen?
- Actual result: What actually happened?

### Steps to reproduce the issue
1. Make a plugin thats change the sign content in a task
2. Put it on your server
3. The sign content does not reload

### OS and versions

* PocketMine-MP: 4.0
* PHP: 7.4
* Server OS: Debian 10

### Plugins

- If you remove all plugins, does the issue still occur?
- If the issue is **not** reproducible without plugins:
  - Have you asked for help on our forums before creating an issue?
  - Can you provide sample, *minimal* reproducing code for the issue? If so, paste it in the bottom section

**Comment by dktapps** [comment]
Please provide example code where this doesn't work.

**Comment by Arthur4848** [comment]
yes, wait a second ^^

**Comment by dktapps** [comment]
This isn't a chat forum. Just send it when you have it.

**Comment by Arthur4848** [comment]
```public function reloadSignContent(){
		new SignText();
		
		Main::$count++;
		
		$text = new SignText([
				"Test",
				"§0",
				Main::$count++,
				"§0"
			]);
		$this->getSign()->setText($text);
	}```

Main::$count is by default 0. Every tick it's one more. But the sign doesn't update. (This code has worked with PM3)

**Comment by dktapps** [comment]
Your code is wrong. Like all other block property changes, you have to setBlock() to see the result of the change.

**Comment by Arthur4848** [comment]
Can you send a small example? i am new in plugin development D:
