### ISSUE TITLE
IOS Bug on MCPE WIFI

### ISSUE THREAD

**Issue by flieZ1708** [pmmp/PocketMine-MP#4097]
I can't connect to the linux server (windows server good) from wifi, only from Mobile Internet. From wifi search server only and I can't interrupt.

**Comment by tgwaste** [comment]
Thats weird I just started having a similar problem where I can not connect to a Minecraft server (both current and pm4) via my local network.  I have to go outside the network and back in in order for it to connect.  Wonder if it's related.  Im still looking over network configuration.

**Comment by tgwaste** [comment]
Hopefully this won’t reopen this issue but I solved my problem and wanted to offer the solution in case it helps the OP

Settings -> Minecraft -> Local Network ON

![0705748C-4AF5-44B4-8F0F-2997EAF3A351](https://user-images.githubusercontent.com/690918/111890481-e127f200-89a6-11eb-9f76-da7745c88799.jpeg)

**Comment by flieZ1708** [comment]
No man not local server... check play with wifi join linux server not work .. work only with cellular data.

**Comment by Saehing** [comment]
> No man not local server... check play with wifi join linux server not work .. work only with cellular data.

Can I use the version of your pmmp and linux?

**Comment by flieZ1708** [comment]
No because I rent.

**Comment by Saehing** [comment]
> No because I rent.

Pmmp 4.0 or 3.x?

**Comment by flieZ1708** [comment]
3.18.0  , 1.16.210

**Comment by SOF3** [comment]
@tgwaste The issue tracker is not intended for support requests. If you would like to help users with trouble, please contact them in private.
