### ISSUE TITLE
Biome->getMinElevation returns null instead of int

### ISSUE THREAD

**Issue by deeskayp** [pmmp/PocketMine-MP#4098]
### Issue description

If Elevation is not set yet, the return values of getMinElevation and getMaxElevation might be null. But the functions claim to return an integer.

Error message:
```
TypeError: "Return value of pocketmine\level\biome\Biome::getMinElevation() must be of the type int, null returned" (EXCEPTION) in "pmsrc/src/pocketmine/level/biome/Biome" at line 165 
```

https://github.com/pmmp/PocketMine-MP/blob/stable/src/pocketmine/level/biome/Biome.php#L165

Proposal: Change return type to ?int
```php
public function getMinElevation() : ?int{
	return $this->minElevation;
}

public function getMaxElevation() : ?int{
	return $this->maxElevation;
}
```

**Comment by dktapps** [comment]
They should be set by your constructor. Two bad API design decisions don't make a good one.
