### ISSUE TITLE
changes done to player inventory on Quit Event doesn't save

### ISSUE THREAD

**Issue by UnknownOre** [pmmp/PocketMine-MP#4111]
### Issue description

- Expected result: Items saving in player inventory
- Actual result: items not saving

### Steps to reproduce the issue
1.leave 
2.relog and check your inventory

### OS and versions
* PocketMine-MP: 3.18.0
* PHP: 7.4
* Server OS: Windows 10

### Plugins

```
public function onQuit(PlayerQuitEvent $event){
   $event->getPlayer()->getInventory()->addItem(Item::get(Item::DIRT);
}
```

**Comment by dktapps** [comment]
This is a problem with your code. I guessed as much considering the code you provided is both incomplete and has a syntax error in it, but I tested it to be sure anyway.

**Comment by iRainDropp** [comment]
Pretty sure it's clearly obvious that the syntax error has nothing todo with the problem he's reporting. People aren't perfect and people make mistakes, smh. The way you treat people for TRYING TO HELP YOU is beyond sad.

**Comment by Rqzor** [comment]
You are dead ass lazy Dylan ily no homo even tho the kid who reported this is from india keep going! Ily u kids!!!

**Comment by UnknownOre** [comment]
bruh... what's happening and im not from india wtf?

**Comment by Rqzor** [comment]
Dude stop lying u told me ur from Asia then moved to Africa for Good wifi why you are lying dude

**Comment by Rqzor** [comment]
Your CODES ARE BAD

**Comment by Rqzor** [comment]
FIX UR WIFI

**Comment by T14Raptor** [comment]
> Pretty sure it's clearly obvious that the syntax error has nothing todo with the problem he's reporting. People aren't perfect and people make mistakes, smh. The way you treat people for TRYING TO HELP YOU is beyond sad.

`but I tested it to be sure anyway.`

**Comment by iRainDropp** [comment]
> > Pretty sure it's clearly obvious that the syntax error has nothing todo with the problem he's reporting. People aren't perfect and people make mistakes, smh. The way you treat people for TRYING TO HELP YOU is beyond sad.
> 
> `but I tested it to be sure anyway.`

Ok and he closed it and called it invalid why Mr. Know It All?

**Comment by T14Raptor** [comment]
> > > Pretty sure it's clearly obvious that the syntax error has nothing todo with the problem he's reporting. People aren't perfect and people make mistakes, smh. The way you treat people for TRYING TO HELP YOU is beyond sad.
> > 
> > 
> > `but I tested it to be sure anyway.`
> 
> Ok and he closed it and called it invalid why Mr. Know It All?

I shouldn’t have to answer that as it’s obvious, it didn’t reproduce. I'm not going to argue here as it’s absurd and really not the place. He pointed out the syntax error saying it’s not the code UnknownOre used to "reproduce."
