### ISSUE TITLE
Give item which isn't exists in ItemTranslator mapping crashes server 

### ISSUE THREAD

**Issue by Blackjack200** [pmmp/PocketMine-MP#4112]
Link to crashdump: 
Unmapped ID/metadata combination -666:0 ItemTranslator#L149
https://crash.pmmp.io/view/4849985

### Additional comments (optional)
reproduce: join PM4Server, and give [name] -666(or others which is not valid)

**Comment by dktapps** [comment]
I guess this could be rendered client-side as an update! block instead, but that would break some transaction stuff (items like that wouldn't be able to be moved around the inventory).

**Comment by dktapps** [comment]
This is fixed by 8ac16345a3bc099b62c1f5cfbf3b736e621c3f76.
