### ISSUE TITLE
call InventoryCloseEvent whenever Player->removeWindow() is called

### ISSUE THREAD

**Issue by UnknownOre** [pmmp/PocketMine-MP#4130]
## Description
call InventoryCloseEvent when a window is removed and don't depend on the client packet

## Justification
a the time being InventoryCloseEvent only gets called when the client send ContainerClosePacket which might break some plugins logic depending on InventoryCloseEvent

**Comment by dktapps** [comment]
That's only because the client sends ContainerClose back to the server. That shouldn't be relied on.

**Comment by Dapro718** [comment]
It works with fake inventories being sent as well.
