### ISSUE TITLE
Error Message on PlayerLoginEvent Player kick

### ISSUE THREAD

**Issue by FlxiBoy1313** [pmmp/PocketMine-MP#4131]
### Issue description

- The absence of an error message when logging in
- At the Player Login, an Error made because I kicked the player there.

### Steps to reproduce the issue
1. Fix

### OS and versions
* PocketMine-MP: 3.18.1
* PHP: 7.4
* Server OS: Linux
* Game version: Win10

### Plugins
My Plugin (Sorry this plugin is Private), FormAPI, Multiworld, DevTools, BuilderTools

My Code:
    **public function onLogin(PlayerLoginEvent $event) {**
        **$player = $event->getPlayer();**
        **$player->kick("Player kick.", false);**
    **}**

Error:
![image](https://user-images.githubusercontent.com/65186341/112878642-77a39400-90c8-11eb-86ea-3ddab918458b.png)

**Comment by mmm545** [comment]
you aren't supposed to kick the player during the PlayerLoginEvent, cancel the event to kick the player

**Comment by dktapps** [comment]
Don't kick players during events. #1239

**Comment by Endermanbugzjfc** [comment]
We should have a bhint GitHub action here telling people to use code box for code and errors, so the stack trace in errors don't fricking refer to another issue.
