### ISSUE TITLE
Misc gameplay TODOs

### ISSUE THREAD

**Issue by dktapps** [pmmp/PocketMine-MP#414]
- Enchantments (WIP)
  - [ ] Enchantment effects:
    - [x] Protection
    - [x] Fire Protection
    - [x] Feather Falling
    - [x] Blast Protection
    - [x] Projectile Protection
    - [ ] Thorns
    - [ ] Respiration
    - [ ] Depth Strider (should work OOB since no anti-cheat for moving fast in water)
    - [ ] Aqua Affinity
    - [x] Sharpness (TODO improve handling)
    - [ ] Smite
    - [ ] Bane of Arthropods (first we need actual arthropods)
    - [ ] Fire Aspect
    - [ ] Looting
    - [ ] Efficiency
    - [ ] Silk Touch
    - [x] Unbreaking
    - [ ] Fortune
    - [ ] Power
    - [ ] Punch
    - [ ] Flame
    - [ ] Infinity
    - [ ] Luck of the Sea (TODO fishing)
    - [ ] Lure
    - [ ] Frost Walker
    - [ ] Mending (TODO XP)
  - [ ] Enchantment tables
- Potions + brewing (WIP)
- More effects (WIP)

to be continued

**Comment by Muqsit** [comment]
And oh boy, the enchantment functions in Item.php are a mess.

**Comment by MCPEPIG** [comment]
The nether? 😛

**Comment by Muqsit** [comment]
explodeA() optimization? It takes 0.2 to 0.4μs to execute.

**Comment by MCPEPIG** [comment]
Redstone?
