### ISSUE TITLE
problem in inventory while being inside another entity or player

### ISSUE THREAD

**Issue by UnknownOre** [pmmp/PocketMine-MP#4140]
### Issue description

- Expected result: The inventory action being executed normally
- Actual result: The action gets reverted
### Steps to reproduce the issue
1. hold an item
2. get inside another entity
3. open your inventory and try moving the item you are holding

### OS and versions

* PocketMine-MP: 3.18
* PHP: 7.4
* Server OS: Windows 10

**Comment by dktapps** [comment]
It's not the first time this code has caused such a problem.
