### ISSUE TITLE
Entity spawning to certain players

### ISSUE THREAD

**Issue by WolfDen133** [pmmp/PocketMine-MP#4145]
### Entity spawning to certain players

- Expected result: When you spawn a entity to a certain player when a new player joins the new player cannot see or interact with the entity.

- Actual result: When you spawn a entity to a certain player and a new player joins the new player can also see and interact with the entity.

### Steps to reproduce the issue
1. $player1 joins the server and creates an entity with the function $entity->spawnTo($player); to only spawn it to that player.
2. A new player joins the server and can also see and interact with the entity.

### OS and versions
* PocketMine-MP: 3.18.1
* PHP: 7.3
* Server OS: Windows 10
* Game version: Win10 (It doesn't really matter)

### Plugins
FormAPI v1.3.0, WFT v1.0.0

**Comment by dktapps** [comment]
You're abusing the system for something it wasn't intended for. spawnTo() was never supposed to be used this way.
