### ISSUE TITLE
Internal server error

### ISSUE THREAD

**Issue by Amitminer888** [pmmp/PocketMine-MP#4150]
08:33:58] [Server thread/CRITICAL]: Error: "Undefined property: pocketmine\network\mcpe\protocol\InventoryTransactionPacket::$transactionType" (EXCEPTION) in "pmsrc/src/pocketmine/network/mcpe/protocol/DataPacket" at line 195
[08:33:58] [Server thread/CRITICAL]: #0 plugins/PlayerTags.phar/src/sys/jordan/tags/PlayerTagsListener(71): pocketmine\network\mcpe\protocol\DataPacket->__get(string[15] transactionType)
08:33:58] [Server thread/CRITICAL]: #1 pmsrc/src/pocketmine/plugin/MethodEventExecutor(42): sys\jordan\tags\PlayerTagsListener->handleDataPacketReceive(object pocketmine\event\server\DataPacketReceiveEvent)
08:33:58] [Server thread/CRITICAL]: #2 pmsrc/src/pocketmine/plugin/RegisteredListener(80): pocketmine\plugin\MethodEventExecutor->execute(object sys\jordan\tags\PlayerTagsListener, object pocketmine\event\server\DataPacketReceiveEvent)
08:33:58] [Server thread/CRITICAL]: #3 pmsrc/src/pocketmine/event/Event(88): pocketmine\plugin\RegisteredListener->callEvent(object pocketmine\event\server\DataPacketReceiveEvent)

**Comment by Amitminer888** [comment]
When I join server then Internal server error

**Comment by rem137** [comment]
yes me too I can't do anything because if i do somthing the server crash

**Comment by Amitminer888** [comment]
> yes me too I can't do anything because if i do somthing the server crash

**Comment by Amitminer888** [comment]
Yes me too I can't break or place or move inventory stuff if I do they show internal server error 
Please fix it soon

**Comment by IAmScRay** [comment]
Looks like you're trying to get something from the packet, but that thing just doesn't exist - it's undefined.

The problem lies in the plug-in, not in the PocketMine.

**Comment by Amitminer888** [comment]
Which problem

**Comment by Amitminer888** [comment]
Sorry I'm new in GitHub
