### ISSUE TITLE
plugins err...

### ISSUE THREAD

**Issue by gamegam** [pmmp/PocketMine-MP#4152]
![Screenshot_20210408-203405_PocketMine-MP](https://user-images.githubusercontent.com/48847058/114019903-edb6b080-98a9-11eb-9603-7dd06dc3824f.jpg)

**Comment by gamegam** [comment]
?

**Comment by Endermanbugzjfc** [comment]
Plugin: Error
***Open issue at PocketMine-MP repository***

**Comment by SOF3** [comment]
@Endermanbugzjfc The issue tracker is not a chat forum. Please leave emotional comments to forums or discord and leave the issue tracker only for professional bugtracking. Getting unprofessional issues created does not mean you have to create more of it.
