### ISSUE TITLE
plugons err

### ISSUE THREAD

**Issue by gamegam** [pmmp/PocketMine-MP#4153]
* PocketMine-MP: 3.19.9
* PHP: 
* Server OS:
* Game version: PE/Win10 (delete as appropriate)
![Screenshot_20210408-203405_PocketMine-MP](https://user-images.githubusercontent.com/48847058/114020639-c57b8180-98aa-11eb-83d4-c0456dcfb58e.jpg)

### Plugins

- If you remove all plugins, does the issue still occur?
- If the issue is **not** reproducible without plugins:
  - Have you asked for help on our forums before creating an issue?
  - Can you provide sample, *minimal* reproducing code for the issue? If so, paste it in the bottom section

**Comment by IAmScRay** [comment]
Dude, you're certainly about to get banned if you spam the same (plugin) issue over & over again.

**Comment by SrBanYT2143** [comment]
F

**Comment by SrBanYT2143** [comment]
are you also having this problem?
