### ISSUE TITLE
Itemblock

### ISSUE THREAD

**Issue by SrBanYT2143** [pmmp/PocketMine-MP#4155]
### Issue description

Call to undefined method pocketmine\item\ItemBlock::write()" (EXCEPTION) in "pmsrc/src/pocketmine/network/mcpe/protocol/AddPlayerPacket" at line 132

### OS and versions

* PocketMine-MP: 3.19
* PHP:
* Server OS:
* Game version: PE/Win10 (delete as appropriate)

### Plugins

- If you remove all plugins, does the issue still occur?
- If the issue is **not** reproducible without plugins:
  - Have you asked for help on our forums before creating an issue?
  - Can you provide sample, *minimal* reproducing code for the issue? If so, paste it in the bottom section

**Comment by dktapps** [comment]
Without knowing your PocketMine-MP version, OS, PHP, Client version, or plugins and how the issue occurred, the issue cannot begin to be solved.
A pre-formatted template is provided that shows the required information to begin to find, test and solve an issue.
Until the adequate template and information is provided, the issue will be closed; it may be reopened if you update the ticket with the correct template and required information.

[Contribution guidelines](https://github.com/pmmp/PocketMine-MP/blob/master/CONTRIBUTING.md)
