### ISSUE TITLE
[BUG:] Confused Inventory

### ISSUE THREAD

**Issue by supercrafter333** [pmmp/PocketMine-MP#4159]
### Issue description

when a player opens his inventory (in creative mode) it is very confused.

### Steps to reproduce the issue
1.Open the Inventory in the creative mode

### OS and versions

* PocketMine-MP: 3.19.0
* PHP: 7.4
* Server OS: Linux Ubuntu 20.04
* Game version: PE/Win10

### Plugins

- If you remove all plugins, does the issue still occur?
Yes, this bug is also without plugins.

### Crashdump, backtrace or other files
none

_Look at the screenshot_
<img alt="Inv_Bug.png" src="https://supercrafter333.tk/inv_bug.png" />

**Comment by dktapps** [comment]
I have no idea what you're trying to say, nor what the problem is.

**Comment by supercrafter333** [comment]
The inventory is buggy. Sorry for my bad english :(

**Comment by dktapps** [comment]
You're still not telling me what the problem is.

**Comment by supercrafter333** [comment]
The Inventory, LOOK AT THE IMAGE!!!

**Comment by supercrafter333** [comment]
Beds are not in Nature part

**Comment by DaisukeDaisuke** [comment]
Items such as flags that should originally be on the "items" tab are located in Nature.

### this image is 1.16.220 vanilla
![_20210409_211810](https://user-images.githubusercontent.com/17798680/114179187-a3046980-9979-11eb-94db-36e5a3e7838d.JPG)

### pmmp 3.19.0 (1.16.220) 
![Desktop_Screenshot_2021 04 09_-_20 26 36 44](https://user-images.githubusercontent.com/17798680/114179450-f70f4e00-9979-11eb-8907-73f7ae65dade.png)

### pmmp 3.18.2 (1.16.210) 
![Desktop_Screenshot_2021 04 09_-_20 41 42 11](https://user-images.githubusercontent.com/17798680/114179368-d646f880-9979-11eb-92c3-47631808d600.png)

**Comment by supercrafter333** [comment]
Yes

**Comment by dktapps** [comment]
General consensus is that this is caused by items having associated blockRuntimeIds when they aren't supposed to. This is quite a significant problem to fix, since many PM items which are directly mapped to blocks (for simplicity) are not directly mapped to blocks in vanilla.

**Comment by dktapps** [comment]
For posterity, this was actually caused by my metadata hack adding NBT onto items, which for some reason made the creative inventory go haywire. I've limited the hack to just blockitems, which should be sufficient to address the original bug (blocks losing their metadata), while also limiting (and hopefully eliminating) the creative inventory's rearranging itself for no reason.

**Comment by AIPTU3110** [comment]
![Screenshot_2021-04-26-01-05-06-41_5c8300b655012b1930f2e0a7b81bf6a9](https://user-images.githubusercontent.com/80614251/116004175-bf67fd80-a62b-11eb-9c55-6bf1c22ba1bd.jpg)

some items are still confusing, such as anvil

• PocketMine-MP 3.19.1
• PHP 7.4
• Plugins, none

**Comment by dktapps** [comment]
This should be fully resolved by 6102740ee35c2f03387748bb795fe74b7724655f.
