### ISSUE TITLE
GenericParticle error

### ISSUE THREAD

**Issue by hyunseo777** [pmmp/PocketMine-MP#4160]
### Issue description

- Expected result: I use genericParticle to add Dragon_Block_Break Particle (and another particle too)
- Actual result: Just White Particle (I guess that particle is endrodParticle)

### Steps to reproduce the issue
1. level->addGenericParticle(~~~)
2. just add endrodParticle

### OS and versions

* PocketMine-MP: 3.19.0
* PHP: 7.4
* Server OS: ubuntu 18.04 LTS
* Game version: Win10

### Plugins

- If you remove all plugins, does the issue still occur? It can't happen without Plugin
- If the issue is **not** reproducible without plugins:
  - Have you asked for help on our forums before creating an issue? yes
  - Can you provide sample, *minimal* reproducing code for the issue? If so, paste it in the bottom section
$player->getLevel()->addParticle(new GenericParticle($pos, Particle::TYPE_DRAGON_DESTROY_BLOCK));

**Comment by dktapps** [comment]
This is fixed by 314a8a12978e96f1a46aa9d7e7be8f996bf19ead.
