### ISSUE TITLE
PM-4 Console Command Sender Dispatch

### ISSUE THREAD

**Issue by TheDataLion** [pmmp/PocketMine-MP#4162]
### Issue description

- Expected result: To be able to run all commands via the console command sender.
- Actual result: When running "say hey" in this example I get the message: "You do not have permission to use this command"

### Steps to reproduce the issue

Use:
`$this->getServer()->getCommandMap()->dispatch(new ConsoleCommandSender($this->getServer(), $this->getServer()->getLanguage()), "say hey");
`

### OS and versions

* PocketMine-MP: 4.0.0+dev
* PHP: 7.4.16
* Server OS: Windows 10

### Plugins
- Empty plugin with following code in OnEnable function `$this->getServer()->getCommandMap()->dispatch(new ConsoleCommandSender($this->getServer(), $this->getServer()->getLanguage()), "say hey");
`

**Comment by dktapps** [comment]
You need to `recalculatePermissions()` before using it.
