### ISSUE TITLE
Bug with inventories after death

### ISSUE THREAD

**Issue by Govdim** [pmmp/PocketMine-MP#4177]
### Issue description

- Expected result: Inventories can be opened after death
- Actual result: Inventories cannot be opened after death if...

If at the time of death a player has an open inventory, he will no longer be able to open inventories until he reconnects to the server

### OS and versions
* PocketMine-MP: 4.0.0
* PHP: 7.4
* Server OS: Ubuntu 20.04
* Game version: PE/Win10

### Plugins
NO

**Comment by Mohagames205** [comment]
I've attempted to reproduce and maybe fix the issue. When the player is killed with an open inventory the `ContainerClosePacket` is not handled in the `DeathPacketHandler`. This leads to the container "staying open" and thus disabling the player from opening any other inventories after they respawn. 

I don't know the right way to fix this, but I am attempting to create a PR

**Comment by XsexUsexV** [comment]
python 
class Employee:
    def __init__(self, name, age, salary):
        self.name = name
        self.age = age
        self.salary = salary

    def __repr__(self):
        return f"({self.name}, {self.age}, {self.salary})"


e1 = Employee("David", 24, 20000)
e2 = Employee("Shikhar", 29, 30000)
e3 = Employee("Rohit", 27, 40000)

Why wont this compile

**Comment by XsexUsexV** [comment]
SEX

**Comment by XsexUsexV** [comment]
Why am i banned 😠

**Comment by XsexUsexV** [comment]
stfu xSuper
