### ISSUE TITLE
Dragon Egg is not destroyed

### ISSUE THREAD

**Issue by alvin0319** [pmmp/PocketMine-MP#4179]
### Issue description

- Expected result: What were you expecting to happen? Dragon Egg is destroyed
- Actual result: What actually happened? Dragon Egg is not destroyed and teleported somewhere

Vanilla behavior

https://user-images.githubusercontent.com/32565818/115112786-26e5d380-9fc2-11eb-94e1-76fe58269c62.mp4

PMMP behavior

https://user-images.githubusercontent.com/32565818/115112807-32d19580-9fc2-11eb-96dc-ddd7e057ea50.mp4

### Steps to reproduce the issue
1. Place Dragon Egg
2. Try to destroy Dragon Egg

### OS and versions

* PocketMine-MP: a32eb4ebc3e82d52cd44d4dc03dcd59a965ed75c
* PHP: 7.4
* Server OS: Windows
* Game version: PE/Win10

### Plugins

- If you remove all plugins, does the issue still occur?
- If the issue is **not** reproducible without plugins:
  - Have you asked for help on our forums before creating an issue?
  - Can you provide sample, *minimal* reproducing code for the issue? If so, paste it in the bottom section

**Comment by Mohagames205** [comment]
Yeah that's because pocketmine doesn't check what gamemode the player is in.

https://github.com/pmmp/PocketMine-MP/blob/master/src/block/DragonEgg.php#L59-L62
`
public function onAttack(Item $item, int $face, ?Player $player = null) : bool{
		$this->teleport();
		return true;
}
`
