### ISSUE TITLE
Some chunks sometimes don't get unloaded when teleporting

### ISSUE THREAD

**Issue by dktapps** [pmmp/PocketMine-MP#419]
### Issue description
Players can quit after a crazy teleporting session and some of the chunks they used will remain loaded after they quit. In one test I did I had ~130 extra left-over chunks scattered around the world that just sat there and didn't get unloaded. gc didn't make any difference either. The player loader doesn't get unregistered from the level for the chunks that remain loaded.

**Comment by iPocket** [comment]
How about world teleporting, does it unload them?
So useful for players so they don't need to afk on their farms... but laggy

**Comment by dktapps** [comment]
@iPocket yes, it's supposed to. If you want your chunks to stay loaded, you should attach a custom ChunkLoader to them.
