### ISSUE TITLE
Please add behaviour pack support

### ISSUE THREAD

**Issue by kaydenpang** [pmmp/PocketMine-MP#4190]
I can’t find any oneplayersleep plugins in poggit, but someone pulled it off with a behaviour pack

It is because im making a survival sever,but we sometimes afk,so we need a one player sleep,it also helps alot in other stuff where i cant find in poggit

**Comment by dktapps** [comment]
This is trivial to write a plugin for. Making behaviour packs support is far more complex and not worth the trouble.

**Comment by Endermanbugzjfc** [comment]
> I can’t find any oneplayersleep plugins in poggit, but someone pulled it off with a behaviour pack
> 
> 
> 
> 
> 
> 
> 
> It is because im making a survival sever,but we sometimes afk,so we need a one player sleep,it also helps alot in other stuff where i cant find in poggit
> 
> 

The oneplayersleep addon is a scripted addon. Scripted addon is for bedrock dedicated servers, a server software that made by official Mojang. You can imagine it is the plugin of bedrock dedicated server, and PocketMine don't compatible with it.

Actually there is so is a plugin call SimpleSleep if I remembered correctly, maybe you can try it!
