### ISSUE TITLE
Paintings are invisible when you place it.

### ISSUE THREAD

**Issue by BenHeroPH** [pmmp/PocketMine-MP#4196]
### Issue description

- Expected result: Paintings supposed to be visible when you place it.
- Actual result: Paintings are not visible when you place.

### Steps to reproduce the issue
1. ... Get painting item.
2. ... place it.

### OS and versions

* PocketMine-MP: 3.19.1
* Game version: PE/Win10 1.16.221

**Comment by dktapps** [comment]
Cannot reproduce. A bug was fixed in the .221 release which sounds similar. Make sure your client is up to date.
