### ISSUE TITLE
Arrow critical particle trail should be done via metadata, not broadcasting spam of particles

### ISSUE THREAD

**Issue by dktapps** [pmmp/PocketMine-MP#420]
This currently doesn't work however, seems due to a client-sided bug. When this issue is fixed, Arrow code should be altered.

**Comment by Muqsit** [comment]
The dimensions of arrow might be wrong too,
https://github.com/NiclasOlofsson/MiNET/blob/master/src/MiNET/MiNET/Entities/Projectiles/Arrow.cs

**Comment by dktapps** [comment]
~The dimensions of~ everything is wrong with ~arrows~ entities.

**Comment by dktapps** [comment]
[Vanilla addon data](https://github.com/dktapps/mcpe-default-addon) is a good place to look for that data.

**Comment by Muqsit** [comment]
@dktapps OMG great work 👌👌

**Comment by TheDiamondYT1** [comment]
#420 blaze it

**Comment by xDidntPot** [comment]
420th issue! Nice!
