### ISSUE TITLE
[BUG:] No birch fences

### ISSUE THREAD

**Issue by supercrafter333** [pmmp/PocketMine-MP#4204]
### Issue description

In the creative inventory, brich fences aren't added.

### Steps to reproduce the issue
1. ...
2. ...

### OS and versions

* PocketMine-MP: 3.19.1
* PHP: 7.4
* Server OS: Linux Ubuntu 20.04
* Game version: PE/Win10

### Plugins:
- ExtendedBlocks
- MultiWorld

**Comment by dktapps** [comment]
They are right where they are supposed to be ... 
![image](https://user-images.githubusercontent.com/14214667/116788845-d3848280-aaa3-11eb-8054-73f4fc7cf42e.png)
