### ISSUE TITLE
SnowLayer apply FallDamage

### ISSUE THREAD

**Issue by RinoXz** [pmmp/PocketMine-MP#4208]
How to reproduce :

- Place seven stack Snow Layer (i don't know if the bug work with less/more of 7 SnowLayer)
- Fall with a damaable fall distance on this SnowLayer
- Once you have landed on the snow cover, get down from it.
- You received fall damage

**Comment by dktapps** [comment]
Without knowing your PocketMine-MP version, OS, PHP, Client version, or plugins and how the issue occurred, the issue cannot begin to be solved.
A pre-formatted template is provided that shows the required information to begin to find, test and solve an issue.
Until the adequate template and information is provided, the issue will be closed; it may be reopened if you update the ticket with the correct template and required information.

[Contribution guidelines](https://github.com/pmmp/PocketMine-MP/blob/master/CONTRIBUTING.md)

**Comment by RinoXz** [comment]
<h2>Issue description</h2>

When a player fall on a SnowLayer block and after he get down from it, he receive fall damage .

How to reproduce :

- Place seven stack Snow Layer (i don't know if the bug work with less/more of 7 SnowLayer)
- Fall from a damagable fall distance on this SnowLayer
- Once you have landed on the snow cover, get down from it.
- You received fall damage

<h2>OS and versions</h2>
PocketMine-MP: 3.19.1

PHP: 7.4
Server OS: Ubuntu 20.04 (and local windows server)
Game version: Windows 10 (1.16.220)
Plugins: No plugins
