### ISSUE TITLE
SnowLayer apply falldamage

### ISSUE THREAD

**Issue by RinoXz** [pmmp/PocketMine-MP#4209]
### Issue description

When a player fall on a SnowLayer block and after he get down from it, he receive fall damage .

### Steps to reproduce the issue
1. Place seven stack Snow Layer (i don't know if the bug work with less/more of 7 SnowLayer)
2. Fall from a damagable fall distance on this SnowLayer
3. Once you have landed on the snow cover, get down from it.
4. You received fall damage

### OS and versions

* PocketMine-MP: 3.19.1
* PHP: 7.4
* Server OS: Ubuntu 20.04 (and local windows server)
* Game version: Windows 10 (1.16.220)

### Plugins
Plugins: No plugins

### Crashdump, backtrace or other files

No error, crashdump and backtrace

**Comment by dktapps** [comment]
I suspect this is because the collision box isn't calculated correctly on PM3, which is because layers aren't supported.

This has already been fixed on PM4. If someone wants to PR the same fix to PM3, I'll review it, but fixing this isn't a priority.

**Comment by dktapps** [comment]
Closing this since it's fixed on PM4 and nobody seems to care enough to fix this on PM3.
