### ISSUE TITLE
LevelEventSoundPacket - Disable Relative Volume not working

### ISSUE THREAD

**Issue by minijaham** [pmmp/PocketMine-MP#4210]
### Issue description

- Setting LevelEventSoundPacket->disableRelativeVolume to true should make the sound full volume regardless of the position
- Sound is still not being able to be heard from a distance

### Steps to reproduce the issue
1. Send a LevelSoundEventPacket to a position and put disableRelativeVolume to true
2. Start walking away from the position

### OS and versions

* PocketMine-MP: 3.19.1
* PHP: 7.4
* Server OS: Windows
* Game version: Win10

### Plugins

DevTools v1.14.2, ImageConverter v2.3.0, MiniChat v1.0.0, MiniPerms v1.0.0, MiniRPG v0.0.1-dev, Slapper v1.6.1, SlapperQuery v1.0.0, Specter v0.9
Tried removing all plugins. Still same issue occurs.

### Crashdump, backtrace or other files
```php
$sender->getLevel()->broadcastLevelSoundEvent($sender->getPosition(), LevelSoundEventPacket::SOUND_BLOCK_BEEHIVE_ENTER, -1, -1, false, true);
```

And 

```php
$packet = new LevelSoundEventPacket();
$packet->sound = 290;
$packet->disableRelativeVolume = true;
$packet->position = $sender;
$sender->sendDataPacket($packet);
```
Both doesn't seem to work.

**Comment by dktapps** [comment]
This is a client issue.
