### ISSUE TITLE
AngryVillagerParticle not working

### ISSUE THREAD

**Issue by AkmalFairuz** [pmmp/PocketMine-MP#4218]
### Issue description
AngryVillagerParticle show weird particle.

![Screenshot (743)](https://user-images.githubusercontent.com/35138228/118252599-22cea800-b4d3-11eb-8132-c4f1969bb2fa.png)

### Steps to reproduce the issue
1. Spawn AngryVillagerParticle

### OS and versions

* PocketMine-MP: https://github.com/pmmp/PocketMine-MP/commit/c9b33e2b9f1134e3d7d27b74b333cc1ba8f158bc
* PHP: 7.4
* Server OS: Windows 10

**Comment by DaisukeDaisuke** [comment]
PocketMine-MP may not be up to date.
Could you please update PocketMine-MP to 3.19.1 and try again?
## 3.19.1
![Desktop Screenshot 2021 05 14 - 18 46 20 86](https://user-images.githubusercontent.com/17798680/118255829-b0b48e00-b4e7-11eb-81e6-6b92b9afa033.png)
## 3.19.0
![20210514-190555-233](https://user-images.githubusercontent.com/17798680/118255802-a5616280-b4e7-11eb-9501-6d6039356208.jpg)
## code
<details>
<summary>open code</summary>
<br>

```php
<?php

namespace test;

use pocketmine\event\Listener;
use pocketmine\level\particle\AngryVillagerParticle;
use pocketmine\plugin\PluginBase;
use pocketmine\Server;

class test extends PluginBase implements Listener{
    public function onEnable(){
        $this->getServer()->getPluginManager()->registerEvents($this, $this);
    }
    public function onPlayerInteract(PlayerInteractEvent $event){
        $player = $event->getPlayer();
        $player->getLevelNonNull()->addParticle(new AngryVillagerParticle($event->getBlock()->add(0.5,2,0.5)));
    }
}
```

</details>

**Comment by dktapps** [comment]
Your version is out of date. (and please don't lie about your version ...)
