### ISSUE TITLE
Bug Report for Dark Oak Wood Postion failure

### ISSUE THREAD

**Issue by DragonfireHD** [pmmp/PocketMine-MP#4220]
Pocketmine Version 3.19.1
Php version: 7.4
Game Version: Minecraft PE Version 1.16.220 Android Samsung S20+ 

Bug explain the Block Dark Oak Log Wood if you place the block in a line the block with this texture is in the Wrong Position 

I dort now where the Bug comes maybe the PocketMine-MP Team have a Idea where we Bug Comes 

Bug Video👇

https://user-images.githubusercontent.com/50929188/118529986-cd9dcb00-b74c-11eb-87e0-f79b1ea766e0.mov

**Comment by DragonfireHD** [comment]
Other Wood Logs go's in the right Position just Dark Oak Log is not right

**Comment by davidplayz123** [comment]
wat the

**Comment by dktapps** [comment]
I'm unable to reproduce this. All the logs I was able to acquire place correctly. Without further information, I can only assume this is a plugin issue.
