### ISSUE TITLE
Cannot assign int to property pocketmine\utils\BinaryStream::$offset of type int (PM4)

### ISSUE THREAD

**Issue by despiseYouAll** [pmmp/PocketMine-MP#4230]
When i'm trying to join server it crashes and server closes

crashdump attached
[Sat_May_22-17.30.39-MSK_2021.log](https://github.com/pmmp/PocketMine-MP/files/6528264/Sat_May_22-17.30.39-MSK_2021.log)

**Comment by dktapps** [comment]
Don't use PHP 8.

(or if you can, disable JIT.)
