### ISSUE TITLE
Offhand inventory doesn't sync slots on master branch

### ISSUE THREAD

**Issue by Yexeed** [pmmp/PocketMine-MP#4231]
### Issue description

- Expected result: when I expect to die in-game, the totem must disappear from the second hand after being consumed
- Actual result: totem doesn't disappear, but when I try to take it, it disappears.

### Steps to reproduce the issue
1. /gamemode 0
2. put totem in offhand slot
3. try to die

### OS and versions

* PocketMine-MP: master 2f51ed83a48c6a650743c22743458ae2b49411c5
* PHP: 8.0.5 (cli) (built: May  1 2021 17:03:16)
* Server OS: Windows 10 (10.0.19042)
* Game version: Win10

### No plugins
But this issue can be solved using this *hack*
```php
//PlayerOffHandInventory
//override onSlotChange
protected function onSlotChange(int $index, Item $before): void {
    foreach($this->listeners as $listener){
        $listener->onSlotChange($this, $index, $before);
    }
    foreach($this->viewers as $viewer){
        $viewer->getNetworkSession()->getInvManager()->syncContents($this);
        //$viewer->getNetworkSession()->getInvManager()->syncSlot($this, $index);
    }
}
```

https://user-images.githubusercontent.com/32373441/119360510-5c619900-bcb3-11eb-8eea-81953d1bc683.mp4

**Comment by dktapps** [comment]
This is a problem with the client - it doesn't respond to InventorySlotPacket for the hotbar for some reason.
I guess a workaround specifically for this case could be implemented...
