### ISSUE TITLE
removeItem without a named tag can remove same item with named tag

### ISSUE THREAD

**Issue by Unickorn** [pmmp/PocketMine-MP#4233]
### Issue description

- Expected result: `Inventory->removeItem()` to remove the item that has no named tag
- Actual result: It removed an enchanted version of the item, not comparing named tag value since the item to remove has none

This is caused by https://github.com/pmmp/PocketMine-MP/blob/f68b9e79e1ebadf6b80641292a14208f6d2919a0/src/inventory/InventoryHelpersTrait.php#L211 only checking if the first item has named tag value, though I'm not sure how to approach it, hence this issue exists.

### Steps to reproduce the issue
1. Get two of the same item
2. Enchant one of them (or add anything that results in `hasNamedTag()` to return true)
3. `Inventory->removeItem()` the first item without named tag 

### OS and versions

* PocketMine-MP: 4.0 - pmmp/PocketMine-MP@f68b9e79e1ebadf6b80641292a14208f6d2919a0

**Comment by dktapps** [comment]
This is currently expected behaviour - it matches with contains() and other functions, which also have the same logic.
It's also like this on PM3.
