### ISSUE TITLE
weird error

### ISSUE THREAD

**Issue by UnknownOre** [pmmp/PocketMine-MP#4235]
Link to crashdump:  https://pastebin.com/dntxt55z

### Additional comments (optional)

this happened randomly, i should note that after killing the process it turned on completely fine

**Comment by dktapps** [comment]
Without knowing your PocketMine-MP version, OS, PHP, Client version, or plugins and how the issue occurred, the issue cannot begin to be solved.
A pre-formatted template is provided that shows the required information to begin to find, test and solve an issue.
Until the adequate template and information is provided, the issue will be closed; it may be reopened if you update the ticket with the correct template and required information.

[Contribution guidelines](https://github.com/pmmp/PocketMine-MP/blob/master/CONTRIBUTING.md)
