### ISSUE TITLE
3:2 (Dirt) in world is replaced by "update!" block in api 4.0.0

### ISSUE THREAD

**Issue by Bestaford** [pmmp/PocketMine-MP#4236]
### Issue description
After world convert from Anvil to leveldb dirt with id 3:2 now is replaced by unknown block

### Steps to reproduce the issue
1. install Anvil world to PMMP 4.0.0

### OS and versions
* PocketMine-MP: 4.0.0
* PHP: 7.4
* Server OS: Windows 10
* Game version: Win10

### Crashdump, backtrace or other files
![Снимок экрана (741)](https://user-images.githubusercontent.com/59061055/120121140-80891280-c1aa-11eb-9e49-f1d4e31c47f0.png)

**Comment by Bestaford** [comment]
I think i need convert id 3:2 to minecraft:dirt, is it true?
![image](https://user-images.githubusercontent.com/59061055/120123459-af59b580-c1b7-11eb-9a48-3492b6c774db.png)

**Comment by dktapps** [comment]
There's no such block. This is expected.
