### ISSUE TITLE
Collision boxes are not calculated before block placement

### ISSUE THREAD

**Issue by Yexeed** [pmmp/PocketMine-MP#4248]
### Issue description

- Expected result: BB is calculated correctly and I'm able to place a door (when I'm not standing in it's preliminary BB before placing)
- Actual result: BB calculated in some wrong way, I'm not able to place a door (even I'm not standing in it's preliminary BB). But, I'm able to place when I'm actually standing in it's preparatory BB

### Steps to reproduce the issue
1. Stand in preliminary BB of the door you want to place.
2. Try to place it. (you should have some success)
3. Move out from preliminary BB, but stay in the same block, try to place it again
4. you should not be able to proceed this placement

### OS and versions
* PocketMine-MP: 4.0 2d686e6
* PHP: 8.0.5 (cli) (built: May  1 2021 17:03:16)
* Server OS: Windows 10
* Game version: Win10

### Plugins
No plugins

Video attached.

https://user-images.githubusercontent.com/32373441/121087030-9622bb80-c7ec-11eb-9fb5-2488a125f67b.mp4

**Comment by dktapps** [comment]
A better way to test this is to shoot arrows at the door and see where the tip sticks.

**Comment by Yexeed** [comment]
I guess main problem here is that boxes calculated in wrong way just before placing, because before placing there is no data for `recalculateCollisionBoxes()` (like `facing`, `open` etc). I made a simple plugin and injected some code into World.php: 
```php
//World.php, method useItemOn()
$wrongCollis = false;
foreach($hand->getCollisionBoxes() as $collisionBox){
	if(count($this->getCollidingEntities($collisionBox)) > 0){
	    $wrongCollis = true;
	    break;
            //return false;  //Entity in block
	}
}
if($wrongCollis){
    foreach($hand->getCollisionBoxes() as $box){
        test::drawAxis($box, $this);
        $player->sendMessage($box->__toString());
    }
    return false; //return false moved here
}
```
Here is the code of plugin: https://gist.github.com/Yexeed/df539626a0e7ce5d0b8dd54bca188507
Also I pasted video below that proves the wrong calculation of box

https://user-images.githubusercontent.com/32373441/121587567-a2ea1e00-ca3d-11eb-9c0f-bf3ff52b5204.mp4

**Comment by dktapps** [comment]
In that case, I've known about this problem for a long time. It also affects stairs.

**Comment by Yexeed** [comment]
Also, when I break the door, the *somewhat* pushes me like I'm in that "wrongly calculated/not calculated" area. You can see that at the end of the video
