### ISSUE TITLE
everything loves to break

### ISSUE THREAD

**Issue by IcyEndymion004** [pmmp/PocketMine-MP#4251]
08.06 15:51:34 [Server] CRITICAL ErrorException: "Undefined offset: 2" (EXCEPTION) in "pmsrc/src/pocketmine/network/mcpe/NetworkBinaryStream" at line 714
08.06 15:51:34 [Server] CRITICAL #0 pmsrc/src/pocketmine/network/mcpe/NetworkBinaryStream(714): pocketmine\utils\Utils::errorExceptionHandler(integer 8, string[19] Undefined offset: 2, string[125] phar:///PocketMine-MP.phar/src/po, integer 714, array[3])
08.06 15:51:34 [Server] CRITICAL #1 pmsrc/src/pocketmine/network/mcpe/protocol/GameRulesChangedPacket(44): pocketmine\network\mcpe\NetworkBinaryStream->putGameRules(array[8])
08.06 15:51:34 [Server] CRITICAL #2 pmsrc/src/pocketmine/network/mcpe/protocol/DataPacket(127): pocketmine\network\mcpe\protocol\GameRulesChangedPacket->encodePayload()
08.06 15:51:34 [Server] CRITICAL #3 pmsrc/src/pocketmine/network/mcpe/RakLibInterface(244): pocketmine\network\mcpe\protocol\DataPacket->encode()
08.06 15:51:34 [Server] CRITICAL #4 pmsrc/src/pocketmine/Player(3361): pocketmine\network\mcpe\RakLibInterface->putPacket(object koth\KothPlayer, object pocketmine\network\mcpe\protocol\GameRulesChangedPacket, boolean , boolean )
08.06 15:51:34 [Server] CRITICAL #5 pmsrc/src/pocketmine/Player(3378): pocketmine\Player->sendDataPacket(object pocketmine\network\mcpe\protocol\GameRulesChangedPacket, boolean , boolean )
08.06 15:51:34 [Server] CRITICAL #6 plugins/MultiWorld.phar/src/czechpmdevs/multiworld/api/WorldGameRulesAPI(178): pocketmine\Player->dataPacket(object pocketmine\network\mcpe\protocol\GameRulesChangedPacket)
08.06 15:51:34 [Server] CRITICAL #7 plugins/MultiWorld.phar/src/czechpmdevs/multiworld/EventListener(85): czechpmdevs\multiworld\api\WorldGameRulesAPI::updateGameRules(object koth\KothPlayer)
08.06 15:51:34 [Server] CRITICAL #8 pmsrc/src/pocketmine/plugin/MethodEventExecutor(42): czechpmdevs\multiworld\EventListener->onJoin(object pocketmine\event\player\PlayerJoinEvent)

the newest pocketmine broke

**Comment by VladYuziuk** [comment]
its not stable yet, wait for further builds

**Comment by Mohagames205** [comment]
This isn't because of PocketMine-MP. This is a bug in the MultiWorld plugin. It broke due to the recent protocol updates, you need to ask the plugin author to fix the protocol changes.

**Comment by IcyEndymion004** [comment]
Ok thanks very much
