### ISSUE TITLE
bug formapi

### ISSUE THREAD

**Issue by Willtom999** [pmmp/PocketMine-MP#4256]
formapi bug or does not work when you click on an anvil its opens the normal menu of the anvil and when you close it opens the ui of the plugin and the other is that it does not open the ui of this item

**Comment by Endermanbugzjfc** [comment]
> formapi bug or does not work when you click on an anvil its opens the normal menu of the anvil and when you close it opens the ui of the plugin and the other is that it does not open the ui of this item

# [This plugin](https://poggit.pmmp.io/ci/Muqsit/InvCrashFix/~) may solve your problem.
