### ISSUE TITLE
Server crashed

### ISSUE THREAD

**Issue by vLilly** [pmmp/PocketMine-MP#4257]
[03:14:45] [Server thread/CRITICAL]: ErrorException: "Undefined offset: 2" (EXCEPTION) in "pmsrc/src/pocketmine/network/mcpe/NetworkBinaryStream" at line 714

**Comment by MrXMaster** [comment]
Multiworld, update it or remove it

**Comment by DaisukeDaisuke** [comment]
duplicate https://github.com/pmmp/PocketMine-MP/issues/4251#issuecomment-857090407

**Comment by leoderoin** [comment]
how updtate MultiWorld ?

**Comment by VixikHD** [comment]
This is problem caused by MultiWorld plugin, please, close the issue, as it is not caused by PocketMine
