### ISSUE TITLE
A number of sounds using World->broadcastSound() do not work

### ISSUE THREAD

**Issue by buchwasa** [pmmp/PocketMine-MP#4259]
### Issue description
There is a number of sounds that do not work in PocketMine: EntityLandSound, EntityLongFallSound, EntityShortFallSound, ItemBreakSound, TotemUseSound, XpCollectSound, and XpLevelUpSound. With a small investigation, I noticed the correlation was that they all use broadcastSound() and that they have no viewers when they are called.

- Expected result: The sound to be heard by the client.
- Actual result: No sound was heard at all.

### Steps to reproduce the issue
1. Join a server
2. Have one of the following sounds above play (an easy one is EntityLandSound)
3. Notice that there is no sound

### OS and versions

* PocketMine-MP: 4.0.0 commit: 920eb7cce5d8d1579df7904d689dd8c930c42d8e
* PHP: 8.0.7, JIT disabled
* Server OS: Ubuntu 20.04
* Game version: Windows 10 (but irrelevant)

### Plugins
No plugins were used.

### Crashdump, backtrace or other files
Attached is a simple test to confirm what I noticed, I do not label them, but I do know the two sounds I used.
The sound with viewers is ArrowHitSound when I fired a bow and the sound with no viewers is EntityLandSound.
![image](https://user-images.githubusercontent.com/17461354/121408397-5e239180-c92e-11eb-98ea-07ccea420d75.png)

**Comment by dktapps** [comment]
This needs a similar workaround to this: https://github.com/pmmp/PocketMine-MP/blob/master/src/player/Player.php#L2217-L2220
