### ISSUE TITLE
PocketMine Website Parked by GoDaddy!?

### ISSUE THREAD

**Issue by NFGamerMC** [pmmp/PocketMine-MP#426]
Hello dktapps,
I know you banned me but this is urgent the pocketmine.net website expired and is for sale by GoDaddy! We can access the plugin site or the forums please fix!

This is not spam

**Comment by Sandertv** [comment]
@NFGamerMC Nobody has access over the old PocketMine forums, that's why the new forums have been established. Just in time it seems like.

**Comment by Sandertv** [comment]
Nevermind, it just works. Use http instead of https.

**Comment by NFGamerMC** [comment]
Please take the windows and mac installer from the old site and post it on pmmp

**Comment by dktapps** [comment]
If you'd checked your facts you'd have noticed that the domain was renewed until 9th of March 2018 when it expired.
