### ISSUE TITLE
I can't run many server

### ISSUE THREAD

**Issue by Quaterizer** [pmmp/PocketMine-MP#4265]
Console: Fatal Error Opcode handlers unusable due to ASLR plsease setup opcache.file_cache and opcache.file_cache_fallback directives 
Plae any key to continue...

how fix it.?

**Comment by Endermanbugzjfc** [comment]
> Console: Fatal Error Opcode handlers unusable due to ASLR plsease setup opcache.file_cache and opcache.file_cache_fallback directives
> Plae any key to continue...
> 
> how fix it.?

# Consider reading the [installation document](https://pmmp.readthedocs.io/en/rtfd/faq/installation/opcache.so.html), you might find your solution there!
