### ISSUE TITLE
Item palette problem (Minecraft 1.17)

### ISSUE THREAD

**Issue by AlicanCopur** [pmmp/PocketMine-MP#4267]
There is an item palette problem in PMMP 3.20.0/3.21.0 (for MC 1.17)

For example, the item I had "compass" before the update became "clock" after the update, or the item "snowball" became a "boat".

For more info: https://youtu.be/d0Ij96R2-ok

### OS and versions
* PocketMine-MP: 3.21.0
* PHP: 7.4
* Server OS: CentOS 7 x64

**Comment by dktapps** [comment]
This issue is incomplete. Where's your plugin list?

**Comment by dktapps** [comment]
Without knowing your PocketMine-MP version, OS, PHP, Client version, or plugins and how the issue occurred, the issue cannot begin to be solved.
A pre-formatted template is provided that shows the required information to begin to find, test and solve an issue.
Until the adequate template and information is provided, the issue will be closed; it may be reopened if you update the ticket with the correct template and required information.

[Contribution guidelines](https://github.com/pmmp/PocketMine-MP/blob/master/CONTRIBUTING.md)

**Comment by AlicanCopur** [comment]
> Without knowing your PocketMine-MP version, OS, PHP, Client version, or plugins and how the issue occurred, the issue cannot begin to be solved.
> A pre-formatted template is provided that shows the required information to begin to find, test and solve an issue.
> Until the adequate template and information is provided, the issue will be closed; it may be reopened if you update the ticket with the correct template and required information.
> 
> [Contribution guidelines](https://github.com/pmmp/PocketMine-MP/blob/master/CONTRIBUTING.md)

Updated.
