### ISSUE TITLE
Send Message on 0 online playes

### ISSUE THREAD

**Issue by FlxiBoy1313** [pmmp/PocketMine-MP#4268]
### Issue description

- That this is possible
- The message was sent, but an error was sent immediately afterwards + Server Close

### Steps to reproduce the issue
1. I don't know how you want to fix it, but it would be nice if it happened within 24 hours.

### OS and versions

* PocketMine-MP: 3.21.0
* PHP: 7.4
* Server OS: Windows 10
* Game version: PE/Win10

### Plugins
BuilderTools  v1.2.0-beta4, DevTools v1.14.2, FormAPI v1.3.0, MultiWorld v1.5.3, MyPlot v1.11.1 and MyPlugin v1.0-BETA

### Crashdump, backtrace or other files
![image](https://user-images.githubusercontent.com/65186341/121908216-12595980-cd2d-11eb-8d1a-1405db8a5e31.png)

**Comment by Mohagames205** [comment]
What message are you talking about "the message was sent" ?

How did you trigger this error? Like what did you do to get the error? Could you explain it to us, so we can try and reproduce it.

**Comment by FlxiBoy1313** [comment]
I sent a broadcast, but no one was on the server that's why I got this error.

**Comment by FlxiBoy1313** [comment]
No, I only get this when I send a broadcast to the server.
The Code:
**Server::getInstance()->broadcastMessage("Test");**

**Comment by Mohagames205** [comment]
I can't seem to reproduce the error you get. Is there any other code you're running or any other details we should know?

**Comment by FlxiBoy1313** [comment]
No, that's the only thing that comes and I send.

**Comment by Mohagames205** [comment]
Okay could you try and follow these steps:

* Remove all your plugins one by one to see which one causes the problem. Personally, I think the AntiCheat plugin in your server is causing the crash. 
* Did you edit the PocketMine-MP source code? If yes, you messed something up. You can download the new version again from the GitHub releases and see if that fixes it for you.
* You could also provide us a video of what you're exactly doing to trigger the error.

**Comment by FlxiBoy1313** [comment]
No, I have not recoded PocketMine-MP. I'll try this out with the plugins.

**Comment by FlxiBoy1313** [comment]
Oh, this really comes from the AntiCheat plugin. I will fix this. Thank you for your help.
