### ISSUE TITLE
Player Names With Spaces Allowed (api3/network)

### ISSUE THREAD

**Issue by markkrueg** [pmmp/PocketMine-MP#427]
### Issue description
When using the api3/network branch, player names with spaces are now able to join. This makes many commands fail; including /ban.

### Steps to reproduce the issue
1. Connect to server using player name with space; example "test player"
2. Try to /ban test player

### OS and versions
* PocketMine-MP: PocketMine-MP 1.6.2dev 「Unleashed」 implementing API version 3.0.0-ALPHA5 for Minecraft: PE v1.0.4.11 (protocol version 102) (aip3/network branch commit bb85308)
* PHP: 7.0.16 w/ OpenSSL
* Server OS: Ubuntu Server 16.04.2 LTS
* Game version: Android 1.0.4

**Comment by dktapps** [comment]
MCPE has a method for handling this with the new commands they added in 0.16. Command re-implementation is currently work in progress. Thanks for the report though, that was accidental.

**Comment by dktapps** [comment]
Seems my regex pattern for usernames is being interpreted as a literal string because I forgot escape characters. 🤦‍♂️ Will fix this shortly.
