### ISSUE TITLE
Totem use sound is missing 

### ISSUE THREAD

**Issue by ipad54** [pmmp/PocketMine-MP#4270]
### Issue description

- Actual result: Totem used, but sound is missing

### Steps to reproduce the issue
1. Use totem

### OS and versions
* PocketMine-MP: 4.0.0 (https://github.com/pmmp/PocketMine-MP/commit/532d57eec72e8677a99f3a064737391c8aefd145) 
* PHP: 7.4
* Server OS: Ubuntu 18.04
* Game version: PE/Win10 

### Plugins
None

**Comment by buchwasa** [comment]
Mentioned in https://github.com/pmmp/PocketMine-MP/issues/4259
