### ISSUE TITLE
Setting inventory items during PlayerLoginEvent causes crashes

### ISSUE THREAD

**Issue by Prim69** [pmmp/PocketMine-MP#4275]
### Issue description

- Expected result: Nothing
- Actual result:  TypeError: "pocketmine\network\mcpe\NetworkSession::getInvManager(): Return value must be of type pocketmine\network\mcpe\InventoryManager, null returned" (EXCEPTION) in "pmsrc/src/network/mcpe/NetworkSession" at line 941

### Steps to reproduce the issue
$player->getInventory()->addItem() in PlayerLoginEvent

### OS and versions

* PocketMine-MP: 4.0.0
* PHP: 8.0.7
* Server OS: Windows
* Game version: Win10

### Plugins
Plugins (2): Core v3.2.0, DevTools v1.15.0+dev

- If you remove all plugins, does the issue still occur?
- No
- If the issue is **not** reproducible without plugins:
  - Have you asked for help on our forums before creating an issue?
  - Can you provide sample, *minimal* reproducing code for the issue? If so, paste it in the bottom section
  public function onLogin(PlayerLoginEvent $event) : void {	 
            $player->getInventory()->addItem(VanillaItems::GOLDEN_HOE());
	}

**Comment by xDidntPot** [comment]
Furry

**Comment by xDidntPot** [comment]
I can confirm its crashing, tried it myself.

**Comment by ethaniccc** [comment]
Everything isn’t fully constructed and created at PlayerLoginEvent. Just do whatever you need to do on PlayerJoinEvent or whatnot

**Comment by Prim69** [comment]
Yea I know I just thought it should return ?InventoryManager

**Comment by dktapps** [comment]
Then it would still crash, just in a different place.

**Comment by Prim69** [comment]
Yea but the error would make sense "cannot call function addItem on null", go ahead and close it I guess

**Comment by BlckqFlorian** [comment]
`if (
            !is_null($player->getNetworkSession()) &&
            $player->isConnected() &&
            $player->getNetworkSession()->getInvManager() instanceof InventoryManager
        ) {`

try to add this check @Prim69

**Comment by dktapps** [comment]
A solution I've previously considered to this and other problems is to move the `PlayerLoginEvent` call out of the `Player` constructor.
