### ISSUE TITLE
Swing animations dont broadcast properly (PM4)

### ISSUE THREAD

**Issue by Prim69** [pmmp/PocketMine-MP#4276]
### Issue description

- Expected result: See swinging animations when another player swings at the air (left click)
- Actual result: Swinging animations only display to other players when directly hitting the entity

### Steps to reproduce the issue
1. Get another player or alt
2. Swing your arm at the air on 1 screen and it won't be displayed on the other unless you're hitting the entity

### OS and versions

* PocketMine-MP: 4.0.0
* PHP: 8.0.7
* Server OS: Windows
* Game version: Win10

### Plugins
Plugins (2): Core v3.2.0, DevTools v1.15.0+dev

- If you remove all plugins, does the issue still occur?
 Yes
- If the issue is **not** reproducible without plugins:
  - Have you asked for help on our forums before creating an issue?
  - Can you provide sample, *minimal* reproducing code for the issue? If so, paste it in the bottom section

**Comment by Prim69** [comment]
I will send a video tomorrow

**Comment by CortexPE** [comment]
Encountered this not so long ago, the reasoning for this change along with others of this kind, is to reduce client initiated broadcasts to prevent DDoS attacks from modified clients forcing the server to broadcast tons of non-essential packets.

With the new architectural philosophy behind PM4, it is expected that this would be re-implemented through plugins instead.

**Comment by dktapps** [comment]
Duplicate of #4598 (I know this issue is older, but I'm assigning a central issue for reference purposes)
