### ISSUE TITLE
[PM4] Crash at startup.

### ISSUE THREAD

**Issue by DidntPot** [pmmp/PocketMine-MP#4279]
### Issue description

- Expected result: Nothing
- Actual result: Error: "Class "pocketmine\item\PotionType" not found" (EXCEPTION) in "pmsrc/src/item/ItemFactory" at line 282

### Steps to reproduce the issue
1. Start the server.

### OS and versions
* PocketMine-MP: 4.0 (Latest commit #5d6146a)
* PHP: 8.0
* Server OS: Windows
* Game version: PE/Win10: Win10

### Plugins
Plugins (1): DevTools v1.15.0+dev

- If you remove all plugins, does the issue still occur?
- yes
- If the issue is **not** reproducible without plugins:
  - Have you asked for help on our forums before creating an issue?
  - Can you provide sample, *minimal* reproducing code for the issue? If so, paste it in the bottom section

### Crashdump, backtrace or other files

===BEGIN CRASH DUMP===
eNrtWmlv40aa/isFOUBsrCjxEg8FztixOxvvdLe9sbOd3SgwimRRYsxD4WFbCfLf93mrihIlu7sz
2JkPCySNTovFqve+Wb+P0qoueHv/KOomq8rR3B2P2qwQo7nl2a4V+H5gTkLfNkNvPOrW6pU9sVzf
nXlB4DqBa81mzniU86Z9U9dVPZr/Pmo3a2wbqefxqBBNw5e0coFtDVuM1lX8INoiK8VikbWiWCxu
qhb473BwMWJl1bK06soEh9Muz7/Ncjq9XvF6Pp1ezKc/NKB3etlFPGNxVay7VtTs4SmfXpfiss4e
xfRSNA9ttZ5eVGXLgaeeVg/TKCunWfIwvZHo32HZeHczIbDTpo6nRMn0Cv/7lsdtVW/wZk0UaOwF
7XltH/bkgAXBBDbEV/MYv38aHZlsd6Zrs7yZ3mblMhctGK151h471smcvZTFALTx9f19XJVNW3dx
e3wCTEfWZ6F6n4M6nxf8QShwNnuFsWPPsT8PZCnaK5DGy1jDctjxR0/N5780VQm1iDrjefabOOZ1
zTc/2T/Lo+6AjLjmaQuephf6xztewn7qb+uquOQt/07ka1EfuyGQSSD3BV8fV9EvIm7ZRV41XS2O
bMcdq7c/WQrFbIDiVtQw+eMw8A8I7nEvFp9EriUIvWDHT5bt/Mz+2dYpafYGNO+s9tj2D3WsGNo3
Fy2Rb3gjpOO9rXgi6iN7zPSbIQBpSovFO5DztlqC4SNnzDR/nvczu5gvFpKxxeIlZ4tFzxreKt4g
wJ65xaJ6WCzAHuwhwa8tXN/9p8Jd590yKwFIis7/iOjC8EB0jbIFeShQh44t8sxa/Npl9U7Llvmv
0PLPf4xH4l8SOf+RuAUilPjus/Kxyh9FIcoWp8sKG8ajuEoE0Wf7DhYXLf35ol1ljfF1LZZZA96P
S/HELjdC/ktYrhKAyNIMr9RjM59f/vebMfsi2Yh3fP3TF3GVV7DZLDk++Zn97W9MLVwleGl83VZX
JfTSiuQqOVZvTk7GrD+E4HOZNeucb97zAvGHTSAdwr8Y9ZtOTr4C6bbvfpLkb0TySZK/eXM5fkHZ
n6cI4F9SNPsoRYokXsJajuVWb7t10X6SzPP37998P2bmyVie8wfn/ouXWZ7zb3IYz3brsd4YfHzj
h/O3b+/73XJzuN18cmJ83Yj2gtg63uMuMPWmP+SThSf5w9bLKDkEj1fHO8OVqeQ8zyEz3rAvyAlO
fpdnhtaG1auEnbLdOamPgzzUq0cCUfR8Wv8K3CdN4Ob67ur6/ZhpGqDzxUgdk6qVqDSu2Sdx3cI6
mtWfwHh78/b89rv71xArGOwj+L092fu97IMD2d/VQnxa8uGnnabi7ae95vr8TpMmPeMdX2bx+66I
KNKeDN+85jOAfshZuGdVYW9VYW9V0ykRWJXMMAzGu7YylgJOxBE/2N315XVDL0Z//FWf/VWf/VWf
/VWf/QP12XikIklOBVDJqQMe7XWQICyCDndN9MidmBOTlrssT0ZzczzKmvtEPI7m0LxAqVVXbYWc
iX7bxctlRqWW+Sf/A9xOk/EhK5PqqWHv79h3N8wCUiZRMis0XZsd9+8t84Sdv7v0XJylpnY+CkCh
j6ffBGpFRbCvXt5XDUG+ev/+Dgvy4SkrZQ1YrCsI9T7PoprXmWhIIDxZgZNaTCl8GNijC0drYk3s
szS2U98L/TA1uevyWTqLYpvbkWeaiel7dipM4QeCUEd1Fj9MC96uSBaTEKeTNA19DyAcN/AT146t
JPJn3ImswBR2BKDCt2NBEkk4pM/BbTGNeZ5HPH4wHhHHEt5SZQ2JPZTVU3mm/6XyeFlXTSOmYJk3
JeWTR3viTMwz24QNmo4TO7PUdUxTRN7ME74IRBDE6cxOrMTzQpfK4iLhJcxqKuKYzluk9jPHFbYQ
sRl6UeokccIDyxVB6nlJElpcBD63wUZMJXop2hoRl9fxSsoPcRLBi0BJCzoLoig2bYsHIols4XJf
cDsNeOKmPBRxmMTCTuMoIFA7jyET5vVGBgwpSntinQUx5B0I27W9NLBMsGelduI7kUgtM3UDK+GJ
FydiH9KroiQunTPP9QPfhWo9L4o5KJsFwQzgRTCLbSe2ZyKIZzNuHwCkOJfLOAdI8Aij4FRUnEXc
N+OIR/HMSTzuePEssfzQ9z0RhpDBLExtK3J5eACOyk7No3lmhpHwBPcS30tt4QBQYEGLYWKHsW3H
rhdbvrCSA5Jk77WC6eRCgSIbELHv2pFthiIwZ14UgauZ6YWxK2CSbhz6UDK3wmgfVF4ttxBMh0eW
Y3kJNyMr9APucysOEohcWHABQIgjzxbxCwjGul2hSEuaLV9eJBzXncVuEONExJ3QtlOkxhTBIAKR
MbRneVa6D0p70kDG7iycRTMhQtOzYc6W71h+4IQzK+TwrsCOA/CbpgdMlVG7ZSoMYpebbgTFhtZM
WEEaOIkTmTEkH9mwTwsaTBxrH8Lup1GstQGZ/1ZWhg6YBvqIgWMOTtb8AcFGorccWLEZ2VHgpkHo
woKgbA4LtB0/DePY8ZLAjGPXtn0evQbFyNaxgkSONUst7gbQouPyKIHJ+KkHqVouhAJPT00vif34
QKRNWVW/CQ1kduabkKYfOj43vcCHbh24qmNBkCLyvWTm2WGQ2vGBd6LaPTB9nwcI12loIcClXuLA
wQPPT1PLsk3PcmN4uGn5JNSaF43YkNnnqA9UrqFA65zZAYeB8MhOZ5aFMOlxj4TlijhwzZkv4ONO
FMYDIF2XqcgPAGdx4pqObbom92em6fs2PM4K4sAz3ZBzOpzYduhSnEbAWgP5VGVdWfZvLVXAMFIn
DrjAH27zKJql3PX5LEAICz3ET8SGaBYOwOjIonixAcU5c2PIEfzHIXdhZh65ih2jj3NCzwmtUHie
K2DCBGXVFQ3nPTMvo3yzKdKq3MAG802K3taI9YgFwdomk0ZUSMIZQo0IkzR0gjRJ7Mh0vBB0pjGf
Cc+NTCsWr8EqIiUEDY7i7Mx27EQAmnCQqgiQObODhCPyCt9JIjeceR4iw+gPmrhw6ELABhrqR15O
pan2UNXPBBUDMkMrk+7o6Gb7xFC8pNmS0bBnUS/Ko7tVx/6jK5nlM9uau87c9dn53y/vGNKaRTty
Xi47VMynAlU0nouqTU73cDNVrNJLhd2gcuNze9ZV3Z5aoeXYtLjEiaJKxKkpcfBng5o8cHqK5ENL
Tyv0HkaOlvIUbSwWRMmjXBi/dqLenFZpSmtoV2NhbGHpVUgmoZKjf14/rjWMJEvTLO7ydnOqqFAt
YFVTiKFmoTmVIhCPIldM5VUUbXZrjRDJYAvZyum3b8/vaEk2lQ3qDI3sMRNPRpKpBuvUkgifo+rZ
wMaV3rPn+pNNQa5/xKiIR01KiutqaftSfwzssj0pS42yuxVqBNZzgKZJsHYlWFVC/e2KtyzmJQ3+
IsGyMs67BC0vELywHAXttipwNiUQh1Abngo0H3hTNwSURUhED2xTdbWGxrKUQRXk9YQDWqjhxPlG
gX4vnrYAp4lIOTTRsKeq/LJlVNnwWnbmyEwZVRYbopKGC4r7p5UoWbde1jwBgAmBVOalAM7pgbGj
DytBBLK2Aq4yYQCk+xVIAyVgk8ueX76WJOcVkIFl/BKtlByCbxYLppI+rRQKtjK33kHmLOV5I9Sr
ZtW1KKVLQ49k5zSJUfBjdLQ05NP0ned59cTIsEES0z0Pe8w4+08ybbVLWrmhX84ZdQX6+BvpBvoc
A4WMTJ1BixASQYw2TItWndB+s92wR/bRB8QpWApkzZMEHVOjVEKihhIeWCE4teNUtDMoIhJEPESF
1ornJMQlOqWSIUp3gh1rxIglJwq+wiqMWpD7G1ADtaZzbND41ciH7O282ZTxHW8eYBD1Ayxsoreg
UUuk6fc808ZVXZVVB43iQDOmI+hqtDvDX8aypQM7VD9IKT2JiNaKroRt0ZYe/K1UOniDBdbVcwbr
ExAHWJN2XW4JJDlvibpKyZJpF1nsmGXtlxBkW8uDCWJ2rEzp4Dg7Bh8d/MrWApLMGJrjuQT20o65
NJm6K0tScEKhp1pLlchurpmwS/Gof7MiW67g8jVvVuOhg2pjIsnUdbdu1aoSHAmoAH1b7qSy4bqy
XUuUu/DHKktA/Os0kM2QHaJnymBvkz3jo2pGbdvZsoz7iNv1pvfcf0ewhVE1Vdoy9QZuUmQthYFC
LHm0aaEAdqvkbkpJZw0h0ADuSI1PmVSENDT49pOhQPW210hm0wy0IoCBjVJCS2sheqTK+qG8jjyZ
LSvorSJPJjNRqJaSVEOSN2dmzw9okLFbVej/LzgpQO/n+KCE+n/lo2mrtSRFR90taRpgwxBn0GlT
qNwRRph76izTdgcEynjxQTqOprP58p9CqXQdSRoFFxZ3yGElchgTzyLuZNSuFOnKbSnnbXeL5xgl
QrPjrI9z13dv5uzuu6tb9vbq3dUdO7+5eXv15pbdvPmefbj+/u/0bQab2N01dr1hH767fvuG3Xx/
ffHm9nbyMlbsScaeeQPB3Ig6q2SGpwjeEKvxSshYLuWyjdIWdIEqI9GhSG4yaCLex2cNkOZfWYn4
Dlsj7j9misoEUbhRNi1pm0ap4SswiNq7PDAMBsB0TYmISgh5bPLyBNmJiikJlIkGgSoNJW0iXGlb
nd1yA9MT62bHtmNqvpuTjxGmpeAMpLDkdQQfMna9lQ5br0tcuiWRpc8xfQ7hv+BlJ6ubIUWo/zpY
6Mm4TysvTbQ3UpWt0xTQFOfFzlUn7FolDeUQKEuqLk+21GTIRE8l2/HQ9KDXkgWw7JnmgGvg/FYG
mBc5V5qVgrPlMa2ros/e/Xm9xxga76HeiTOt31fshr1icC8s57avU0mZNXCSoWqDT7pirYq5vm5k
+pVBr3Z6vKSN+pDkRRLdc0RfwJ4EAgR/ReyoB5BPgeURRtg0naBg0q6gzWVf5lLAI3w7ysa9glUB
oivZSU8Pbf6k3KhtildoZpsdDxd8TetZ0RVI4MjdNet7EFIyU22WomYnafIrLVrpWS9tEPX+ekuZ
RGpQId4ho7t7mrys1OtDy6dCjOKmwtJv7x1OQdRbD/mURYoRc/j0gNNLECYLI1SuJFPQqqoZBWvN
qVFi6pTid8crjm2lrPjrKaDtw4KbRJpTZ6Jhfw7c52yV/paiJYXOt6kHleGqylWVG/E2XsnWQDKA
gg1mptOXjI+qMdNvVcqKxLbe7dPn0VCH/UsK0fWmJfBjZlgD9WrVSuRG2xO0TS0yC+wKatn9Uh2b
KElQoyV7DzqORU3chH2HYhTWdiqrS3Zx88MYZ0FHBG98yhI4iKxM+ji8xWBIDHPm7XqAXYPQSDkN
dk/YeYJgt+J5OkXXqzqXRMDSNTogZjRVJgMcuO0wrQ7A7XdIb54pNlKly/MJI0J+uClv+sp/16tS
g0OEPSExq6PdulwbeuVF4/VO+2iT/Sa2GqY+oVdsQ8lUF2voI5TJDJK3G9rq0MmE3egzOa+X8gDX
jbO2Do0zrfmSGIGGIMBmncv6iDrhAixQcOA1ae0iz7BLtfj0EU00LXt394OktQFbxHzUtfI2kVTs
DqHqdya7+FS0nUHn5pLi/SZWlHG9WavIkDKaacjPt1tm0a7TvGbCZN5bcSozWFZAQi1pEnqR11MR
2saSHijwURK+InkgYssgjvTPZTpolHpVsYK9rbZa4kaosYYOj9s27/JaFmWXV7fn36Aek/VbV0qb
onDfUXyl4JqoEiQj49QXpJL9FmjH68AO5ExKRN1yvmsrv2YWtZO6al4hvskdTA8WGjUUIYcvm6qv
DbS7WD1QxUYP9WJVVY0coPQdpeinCDIZJLzlrOGPu+RDYyw9kTPo7d4IAkTKz5SqYtQzpl+qrFQD
DSnAL9mPUfVMIaJmV5fs+Mcfri5PYBCID6AD+5+gTdJXhooC3kO9Zp1shaYqHYip2im1RFj48Zu3
PQbdiQ5WvpToaGwnqxOpd131SA6rfualc/NgGJemGjHeZunGeO6y5EBP/QBwf9p0J8dFyiXVXWkl
Drlb+1/X6OFVjKDT9gFanzLUqbk6kUQ9OpWOdGDdYqPcysvltosq6XB+mOjH/a69EeSrM79e3udF
1VG8SVX21OEHUuylTbUDxVU914Fd0JNO/gDwvSwGBgCkGEqhZgeRUAAjQTeMEHr4k7QWMmSFQdsd
vXhZWChhEMKBMBBBGT8kG5zFMgsyusf0OsXmx0jmNV2NZLz3CxC+A0C/tpQ5L8ZXkbwTBxk3WaIy
EPHHoXHYZdNFQ6ksKTVjh0hUQpYP22QpZ2nadHgci1zeUlLdlS6rj/LsAUio05exLOcQwrKuntqV
ioRAwtlKwRuESQSNpu1TvSTYILn05Bk7IfUMXl02A+4o4JNNKIhMfVDfMrudqfUllTx1oDbANJjN
jkAumv19Be/mdwMdT14qWUfAJ57JbhwJCs2psrJ1te7ynZPpR6oo5C6ditQ3CPorGzbiW2OknE7B
D6XHoBGSo301w5xvyysavcpRgXqhqhJtf5n6dtJH/2QYP8mnDbow+2JxG1wOX6xX6BrSaq+CQFQx
Vm273tu9gn7niqzJuijWk6za8oD4uSmoyUU4aGn8HDdDZigt6h1st0MyJaMnXy5rsdTTVT2KVWMl
ujH38JJjSSti1vXlNd3FMXTOUXUJhcMnofolzuimIOFsJANDVuTqZPCNBLXBnla6Najbqu8VcUP1
as/WAFGP0U0UmT73S335ptoXKTqqkixrMPIcIzOtVxyuJiit1ETlroZGwkpFjT7KoChcUl6mfbvk
qRIX3xui6k/dg8zfoXdA3SUjeR8qNUBtGWpHj+UVO1B8HxpCmxXDDKaLAwJPp8iPKGGR3il9EGo5
KdbH+m8EkyEi/e4QUy/jz5UhOpkpC1DeNJiyaShA0m5l3M/TVnpZhdN62w3pCERfNNCGJrJgy9It
KLoX0tXqoxbFtH6k1Ed6QNRxcNi6oYrkzbYDRWPAi3W+e6ZaDfRqTc57lfZvYek0A52zn2RxhYJ7
LIeiP/fgZYM5LCyGn98kY9QN1DK90GCp/3YpJ0av5XaZG2SL3MjuRw4eoLsMVOsCZZ+VHrekpH9g
9M2Tsmaf6XeY56z/9knL1D4JmkZ+FYkEYfBhPAufwWEpxs5zktXtWIb8rwZFqvq8tT/CUQGCUi9E
ryeyvNMWmkOd8YapC5Jd3Uf9vhOttx/GZMgCHKTGWH6KbHq5Gf1nNRhJ36gcfStjlUQmT+yBkVW+
XrkfrBiyNN6rWCvVzYhnRM9Gt/PxAzWAjWxYET6jDG3XRlWgch/xnNE93Fxlqt61FK8SB2q4ehD8
R+OReEb3IrsZumR3gaJqcGkvivXlnn6BPnCWCa+HS1Vxn1QtwulwUV9+2D53dT54pGgyeEyzvBVD
mMtieHUQ/dqQhgzO9zh4pvtsg8fBXYntEuKA3EPXaehWluy0IMvBnnW8x/n3It3dfOkXG5k9mr0V
lHHFYOH25u0Q8ab5NZf3HvUv1r9pqwdRooQYcr3h8rM93U2h6zO/ZeoOkxVKmn9TF5T6zXh6LvZk
WhEdtmk6lmXTxZeby+shf0l1L4k4WMNKtqcMOH3ZNMNttxn59I/vhpzt48YTjUH2uMHaU53t63Vw
48whLummKghd7RsU1WbyUqHd3/chrS/VbUN9lCQi4Vh0X4zkobqe/h4iwaE2udJXymwlMvRKubI9
eT2LTC051Fc21K+UjjNYQX/ZyXC87JQB9YD+h+q46xs519vu/+OP/wWurRRz
===END CRASH DUMP===

**Comment by xDidntPot** [comment]
Apologies, forgot to install composer after updating files.

**Comment by dktapps** [comment]
PM would have warned you about that, if you hadn't removed the check that makes it warn you ...
