### ISSUE TITLE
Add a way to get damage cause by name

### ISSUE THREAD

**Issue by TheDiamondYT1** [pmmp/PocketMine-MP#428]
It would be nice if https://github.com/pmmp/PocketMine-MP/blob/master/src/pocketmine/Player.php#L3213 was made available to plugins in a seperate function, such as `Player::getDamageCauseByName()` or place it in EntityDamageEvent idk. It would be nice rather than trying to recreate 98% of that function without the death stuff in a plugin.

**Comment by dktapps** [comment]
I don't understand why you'd want to do this. Please elaborate.

**Comment by TheDiamondYT1** [comment]
@dktapps For example if you wanted to make a plugin that displays the damage cause in chat (Such as "You lost a point due to void").  Now i think about it this isint the best idea. Sorry for wasting your time
