### ISSUE TITLE
Entity despawn bug

### ISSUE THREAD

**Issue by LucGamesDE** [pmmp/PocketMine-MP#429]
If I despawn entities, they don't despawn correctly.
They only despawn for the player who joined first. All other players see them.

This happens if I use $entity->kill() or $entity->close();

OS and versions

Tesseract: PocketMine-MP: PocketMine-MP 1.6.2dev 「Unleashed」 implementing API version 3.0.0-ALPHA4 
PHP: 7.0.9
Server OS: Windows 10
Game version: MCPE 1.0.4
Server host: My windows computer

$entity->despawnFromAll() also isn't working

**Comment by robske110** [comment]
Tesseract issues should be posted there: https://github.com/TesseractTeam/Tesseract/issues

Oh, you already posted it there. Why do you duplicate it here then?
