### ISSUE TITLE
Bug arrow

### ISSUE THREAD

**Issue by Willtom999** [pmmp/PocketMine-MP#4298]
Plz fix arrow when flying creatively someone shoots us an arrow we can no longer fly creatively we have to disconnect and reconnect

**Comment by dktapps** [comment]
Without knowing your PocketMine-MP version, OS, PHP, Client version, or plugins and how the issue occurred, the issue cannot begin to be solved.
A pre-formatted template is provided that shows the required information to begin to find, test and solve an issue.
Until the adequate template and information is provided, the issue will be closed; it may be reopened if you update the ticket with the correct template and required information.

[Contribution guidelines](https://github.com/pmmp/PocketMine-MP/blob/master/CONTRIBUTING.md)

**Comment by Willtom999** [comment]
Pocketmine 3.21.0

**Comment by Willtom999** [comment]
Php 7.4

**Comment by Willtom999** [comment]
@dktapps

**Comment by Willtom999** [comment]
Version mcpe Windows 10
