### ISSUE TITLE
PocketMine Master Download!

### ISSUE THREAD

**Issue by TDMidkwhatisxd** [pmmp/PocketMine-MP#43]
Hi!
RakLib and Spl , are empty folders, it only happens here, so i need to copy them from Genisys!

**Comment by SOF3** [comment]
They are not empty folders; they are submodules. Do **not** use the "Download ZIP" button. Use git to recursively clone the repo, or directly download a phar build from [our official Jenkins server](https://jenkins.pmmp.gq/).

**Comment by TDMidkwhatisxd** [comment]
Ok thx and sorry !

**Comment by TDMidkwhatisxd** [comment]
Were i can find 0.16 phar?
Becouse i get broken things wen downloading master :(

**Comment by TDMidkwhatisxd** [comment]
Im testing 0.16 on master , and i think files are missing!
Chating dont work , type.chat.text. message wen chating! And get similar type of messages in , console, /plugins command!
Just how i use 0.16 branch if i cant even download the right files ;-; !

**Comment by TheDeibo** [comment]
After you the master zip, you need to unzip it. Then on GitHub, click 'Src > PocketMine > Lang' and download that too. (GitHub doesn't fill in external projects ) and put that in its corresponding place..

Now go back to the src folder, and do the same with raklib and SPL into their corresponding folders 

Then there you have a fully working unpacked PocketMine.

**Comment by SOF3** [comment]
Please read [I have a question](../blob/master/CONTRIBUTING.md#i-have-a-question).
