### ISSUE TITLE
Double stone slabs are not converted correctly => Fake blocks

### ISSUE THREAD

**Issue by Matze997** [pmmp/PocketMine-MP#4301]
### Issue description

- Expected result: Double stone slab should not change to stone slab
- Actual result: https://youtu.be/aKmXb0P3Ihg (You can see the block id in the scoreboard btw)

### Steps to reproduce the issue
1. Get a world with double stone slabs (44:0 !!) 
2. Click slab block

### OS and versions
* PocketMine-MP: 4.0.0+dev
* PHP: 8.0.7
* Server OS: Ubuntu
* Game version: PE/Win10

### Plugins
CityLife v1, DevTools v1.15.0+dev, JavaMapConverter v1, MagicWE2 v10.1.5, PcntlSignalHandler v0.1.0, WorldManager v1

- If you remove all plugins, does the issue still occur?
Yes

**Comment by dktapps** [comment]
44 is single stone slab ...

**Comment by dktapps** [comment]
I'm not able to reproduce this by any means. I think it's more likely the fault comes from one of your plugins.
