### ISSUE TITLE
How about a seed generators

### ISSUE THREAD

**Issue by deadbushmc** [pmmp/PocketMine-MP#4308]
## Custom World Generators
As per you know spigot, paper, vanilla bedrock has different seeds for worlds and it looks really good. But pmmp has only one kind of world barely any lava source and no mineshaft i mean structures and it doesn't support different seeds and different world generation. So I would like if you added random seed worlds and stuffs and nether too

**Comment by dktapps** [comment]
The world generator is not planned for improvement in the near future due to the large amount of input and very little gain to result. In short, I have more useful things to spend my time on.

**Comment by deadbushmc** [comment]
sad
