### ISSUE TITLE
Giving creative players carte blanche for new items breaks transactions

### ISSUE THREAD

**Issue by dktapps** [pmmp/PocketMine-MP#431]
My bad. shoghi, we need your inventory upgrades asap, inventory is horrible to work with 😞 

Solutions:
- give creative players carte blanche for all inventory transactions
- wait for shoghicp to rewrite inventory so this stuff isn't a problem anymore
- fix broken logic allowing "transactions" to execute with only one slot change (wat)

**Comment by Tarik02** [comment]
@shoghicp

**Comment by dktapps** [comment]
:facepalm: I deliberately didn't ping him, you moron.

**Comment by Muqsit** [comment]
The whole transaction thing is some f-ed up crap. So are the variable names.

**Comment by dktapps** [comment]
@Muqsit yea... but I overdid it when I rewrote Genisys', didn't give enough thought to plugins. But shoghicp's inventory system should be coming sometime around 1.1, so it'll be getting a rewrite on the server-side then. I can't wait 🙏

**Comment by Tarik02** [comment]
;(

**Comment by dktapps** [comment]
The referenced commit allows creative players to do what they want since they can't be tracked without causing stupid bugs. This will be resolved properly in MCPE 1.2.
