### ISSUE TITLE
Pitch changes when pearling while moving

### ISSUE THREAD

**Issue by Prim69** [pmmp/PocketMine-MP#4316]
### Issue description

If you throw an ender pearl while moving and change the angle you're vertically looking at (pitch), when the pearl lands your pitch will be set to something else

- Expected result: Pitch stays the same
- Actual result: Pitch changes

### Steps to reproduce the issue
1. Throw an ender pearl while moving, continue moving and change your pitch
2. Watch as your pitch gets forcefully set to something else

### OS and versions

* PocketMine-MP: 4.0.0
* PHP: 8.0.7
* Server OS: Windows
* Game version: Win10

### Plugins
Plugins (0):

- If you remove all plugins, does the issue still occur?
 Yes this was tested on a vanilla pm server
- If the issue is **not** reproducible without plugins:
  - Have you asked for help on our forums before creating an issue?
  - Can you provide sample, *minimal* reproducing code for the issue? If so, paste it in the bottom section

### Crashdump, backtrace or other files

https://user-images.githubusercontent.com/13991048/126020574-64b1a376-08d8-4e57-bc3d-24f1af0f33c2.mp4

**Comment by dktapps** [comment]
The reason it happens is because your updated yaw/pitch hasn't arrived at the server when it teleports you. There's no realistic way to fix that since we don't have time travel.
