### ISSUE TITLE
Setting players gamemode on Login crashes if their previous gamemode is Spectator

### ISSUE THREAD

**Issue by Prim69** [pmmp/PocketMine-MP#4323]
### Issue description

Setting the players gamemode to Survival in PlayerLoginEvent crashes the server if their previous gamemode was Spectator

TypeError: "pocketmine\network\mcpe\NetworkSession::syncAdventureSettings(): Argument #1 ($for) must be of type pocketmine\player\Player, null given,

- Expected result: Players gamemode to be set to survival
- Actual result: Server crashed

### Steps to reproduce the issue
1. Set the players gamemode to Survival in Login event
2. Set your gamemode to Spectator and rejoin the server

### OS and versions

* PocketMine-MP: 4.0.0
* PHP: 8.0.7
* Server OS: Windows 10
* Game version: PE/Win10 (delete as appropriate)

### Plugins
Plugins (1): Core

- If you remove all plugins, does the issue still occur?
  No
- If the issue is **not** reproducible without plugins:
  - Have you asked for help on our forums before creating an issue?
  - Can you provide sample, *minimal* reproducing code for the issue? If so, paste it in the bottom section
```php
public function onLogin(PlayerLoginEvent $event) : void {
		$player = $event->getPlayer();
		$player->setGamemode(GameMode::SURVIVAL());
}
```

**Comment by DidntPot** [comment]
Weird

**Comment by BlckqFlorian** [comment]
try to set the gamemode in the PlayerJoinEvent

**Comment by Prim69** [comment]
> try to set the gamemode in the PlayerJoinEvent

I dont need a solution the issue is meant to point out the error.

**Comment by BlckqFlorian** [comment]
ah sorry, I misunderstood.

**Comment by dhdjSYS** [comment]
`GameMode::SURVIVAL()` **_?_** 

pretty sure that's not how you call on a constant.

Tried it with `PocketMine-MP version 3.22.1` and there was no issue with the api.

**Comment by Prim69** [comment]
> `GameMode::SURVIVAL()` **_?_**
> 
> pretty sure that's not how you call on a constant.
> 
> Tried it with `PocketMine-MP version 3.22.1` and there was no issue with the api. I suggest this issue to be closed.

It's not a constant and its PM4

**Comment by dhdjSYS** [comment]
> It's not a constant and its PM4

I'm dumb.
