### ISSUE TITLE
Some in-game sound missing

### ISSUE THREAD

**Issue by Blackjack200** [pmmp/PocketMine-MP#4334]
### Issue description

- Expected result: when i click air(left click or PE just a click), there should a sound to react for it.
- Actual result: no sound play in client
### Steps to reproduce the issue
1. setup a bare PM3 server, click air, listen to the sound
2. setup a bare PM4 server, click air, listen to the sound (nop)

### OS and versions
*  PM3: 3bbd088a094c5db05617a64e29943d5b9ce6a009
*  PM4: 1afda04620606e49cd4a8eeb04d08ff3908f2da4
* PHP: 7.4.20
* Server OS: MacOS
* Game version: Android(448)

### Solution

I find that it cause the LevelSoundEventPacket.
PM3
```php
public function handleLevelSoundEvent(LevelSoundEventPacket $packet) : bool{
		//TODO: add events so plugins can change this
		$this->getLevelNonNull()->broadcastPacketToViewers($this, $packet);
		return true;
}
```

PM4
```php
	public function handleLevelSoundEvent(LevelSoundEventPacket $packet) : bool{
		/*
		 * We don't handle this - all sounds are handled by the server now.
		 * However, some plugins find this useful to detect events like left-click-air, which doesn't have any other
		 * action bound to it.
		 * In addition, we use this handler to silence debug noise, since this packet is frequently sent by the client.
		 */
		return true;
	}
```

so i think we can add 
```php
$this->player->getWorld()->broadcastPacketToViewers($this->player->getPosition(), $packet);
```
 in PM4's one to solve this issue.
i tested it, it works.

Sorry for my bad English.

**Comment by dktapps** [comment]
This is intended, for the reason described in the comment of the current code. Left clicking air does nothing, so there is nothing to bind the action to.
