### ISSUE TITLE
Console child process still alived when kill server with signals

### ISSUE THREAD

**Issue by Blackjack200** [pmmp/PocketMine-MP#4335]
### Issue description
i use `kill` command to to kill server, with signals, it is very strange that the child process still alived, 
it reports 
```
Notice: fgets(): read of 8192 bytes failed with errno=5 Input/output error in pmsrc/src/console/ConsoleReader.php on line 66
```
### Steps to reproduce the issue
1. start up a bare PM4 server
2. i use MacOS so i use `kill -2 $(cat server.lock)`
3. input something, see the alerts
### OS and versions
* PocketMine-MP: 1afda04620606e49cd4a8eeb04d08ff3908f2da4
* PHP: 7.4.20
* Using JIT: no
* Server OS: MacOS
* Game version: NO

**Comment by dktapps** [comment]
SIGINT doesn't kill directly, it just tells the process you want it to stop. That causes the server process to close stdin, which interrupts the child's reading of it.
