### ISSUE TITLE
can not break Sweet berries (only 0 ages)

### ISSUE THREAD

**Issue by xerenahmed** [pmmp/PocketMine-MP#4339]
### Issue description

- Expected result: Break and maybe drop sweet berries
- Actual result: Like hiding and after right click to bottom grass, it's back (only 0 ages)

### Steps to reproduce the issue
1. Plant a sweet berry bush
2. Break the sweet berry bush
3. Right click to grass

### OS and versions

* PocketMine-MP: eb23d27004967c7e08ecdedb3747ce3aab662451
* PHP: 8.0.9
* Using JIT: no
* Server OS: Mac & Linux
* Game version: Android/iOS/Win10

### Plugins
tested with no plugins

**Comment by dktapps** [comment]
This looks like some kind of weird client bug. The block destroy action isn't sent when breaking a berry bush for some reason.

**Comment by dktapps** [comment]
Closing this as WF since it's a bug in the client. There's nothing that can be done PM-side to address this.

**Comment by Govdim** [comment]
This problem only occurs in survival mode. When checking on the Bedrock Dedicated Server, this problem does not arise. Therefore, this problem can be solved on the PM side.

**Comment by dktapps** [comment]
The vanilla server uses the so-called server authoritative block breaking. PM uses the legacy method.
