### ISSUE TITLE
DATA_OWNER_EID doesn't work anymore in 1.0.4

### ISSUE THREAD

**Issue by Creeperface01** [pmmp/PocketMine-MP#434]
### Issue description
this property worked until 1.0.3, but since 1.0.4 it doesn't, (tested with fishing hook, property id 5)

### Steps to reproduce the issue
spawn fishing hook and add this property, with your id

### OS and versions
* PocketMine-MP:
* PHP: 7
* Server OS: linux
* Game version: PE/Win10

**Comment by dktapps** [comment]
This is likely related to the changes required to get rid of emeralds in 1.0.4. Players no longer have eid 0, make sure you're using the actual eid.

**Comment by Creeperface01** [comment]
i tested with NPCs

**Comment by dktapps** [comment]
Could you test with the api3/network branch?

**Comment by dktapps** [comment]
Could you clarify what it is you're expecting to happen that doesn't? Having never messed with that property other than identifying it, I don't know what you're expecting to happen.

**Comment by Creeperface01** [comment]
It works probably.
