### ISSUE TITLE
Player can fly after respawn if player was flying

### ISSUE THREAD

**Issue by alvin0319** [pmmp/PocketMine-MP#4341]
### Issue description

- Expected result: What were you expecting to happen? Player cannot fly after respawned
- Actual result: What actually happened? Player can still fly

https://user-images.githubusercontent.com/32565818/127770789-68aca26d-5745-4074-91b5-3d467fb19b75.mp4

### Steps to reproduce the issue
1. Join the server.
2. Change gamemode to creative, or make player can fly.
3. kill yourself using `/kill` command or something else.

### OS and versions

* PocketMine-MP: 4.0.0 (eb23d27004967c7e08ecdedb3747ce3aab662451)
* PHP: 8.0.9
* Using JIT: No
* Server OS: Ubuntu 18.04
* Game version: Android/iOS/Win10/Xbox/PS4/Switch (delete as appropriate)

### Plugins
N/A

- If you remove all plugins, does the issue still occur? Yes
- If the issue is **not** reproducible without plugins:
  - Have you asked for help on our forums before creating an issue?
  - Can you provide sample, *minimal* reproducing code for the issue? If so, paste it in the bottom section

**Comment by alvin0319** [comment]
This also can be reproduced in Win10 edition.

There is no code such as `setFlying(false)` on respawn sequence.

https://github.com/pmmp/PocketMine-MP/blob/041d3141900541decdff0a9b88ccfd871d3d34a9/src/player/Player.php#L2104#L2137

**Comment by dktapps** [comment]
Fixed for 4.0.
