### ISSUE TITLE
Education

### ISSUE THREAD

**Issue by MrHoller** [pmmp/PocketMine-MP#4350]
## Description
Add the ability to disable Education Edition features by setting in pocketmine.yml

## Justification
Not every server needs these blocks and their functionality. They just litter your inventory.

## Alternative methods
If it is possible to add a method for plugins like: 
```
public function onEnable(){
Server::getInstance()->disableEducationEdition();
}
```

**Comment by dktapps** [comment]
They don't really litter your inventory. They take up a handful of slots. Adding a toggle would add a bunch of extra complexity that isn't worth the hassle just for some OCD. If you don't want these items in your creative inventory, you can easily unregister them using a plugin.
