### ISSUE TITLE
Dropping a consumable item mid-animation skips the animation while giving Food points

### ISSUE THREAD

**Issue by CortexPE** [pmmp/PocketMine-MP#4355]
### Issue description

- Expected result: What were you expecting to happen? To cancel the food animation when the item gets dropped and to prevent the player from receiving Food points
- Actual result: What actually happened? After dropping the consumable item, the player is still able to obtain the food points

### Steps to reproduce the issue
1. Make sure your hunger bar is not full in survival
2. Start consuming a consumable item
3. Drop the item mid-animation

### OS and versions
* PocketMine-MP: 4.0.0
* PHP: 8.0.8
* Using JIT: no
* Server OS: Windows 10 / Ubuntu 20.10
* Game version: Win10

### Plugins
- If you remove all plugins, does the issue still occur? Yes

### Crashdump, backtrace or other files

https://user-images.githubusercontent.com/17762324/128637025-1f623916-dc0a-4eb1-8994-d710a3e83cc2.mp4

**Comment by Driesboy** [comment]
This also allows players to "fast eat" their food. Since it actually eats that item & drops another.

**Comment by ItsZodiaX** [comment]
This is true

https://user-images.githubusercontent.com/59441461/130347267-f1fdc30b-f3be-438a-8645-a59ac4e8cb36.mp4

**Comment by dktapps** [comment]
Is this also an issue on PM3?

**Comment by ItsZodiaX** [comment]
No, Only PM4
