### ISSUE TITLE
Cobblestone generators occasionally don't update (PM4)

### ISSUE THREAD

**Issue by sn3akrr** [pmmp/PocketMine-MP#4358]
### Issue description

- Expected result: Cobblestone generator always updates, resulting in possible AFK mining
- Actual result: Cobblestone sometimes doesn't generate, and requires a right click to update the block

### Steps to reproduce the issue
1. Create a big cobblestone generator
2. Try mining multiple blocks from it for awhile

### OS and versions

* PocketMine-MP: 4.0.0
* PHP: 8.0.8 (from Azure, no JIT)
* Server OS: Ubuntu 17.04

### Plugins

Plugins (4): Core v1.9.0, DevTools v1.15.0+dev, SkyBlock v1.7.0, Tebex v0.1.0

My plugins do not interfere with Blocks updating whatsoever, so I'm almost positive this isn't caused by them. They work 100% of the time while using API 3

https://user-images.githubusercontent.com/25047687/128800797-2fd5a033-94e6-49a4-aa09-80126ab83f6b.mov

**Comment by dktapps** [comment]
Can you try with ba2bfe0e1149d98abff6028474bb68adf7f016cb?

**Comment by dktapps** [comment]
I'm not able to reproduce this, with or without the referenced commit. I'm going to need more detail on how to reproduce this.

**Comment by sn3akrr** [comment]
I just updated my skyblock servers to the latest beta release! Will let you know soon if anyone can still reproduce this issue

**Comment by dktapps** [comment]
Any news on this?

**Comment by sn3akrr** [comment]
Haven't heard of this issue since https://github.com/pmmp/PocketMine-MP/commit/ba2bfe0e1149d98abff6028474bb68adf7f016cb , thanks! I'll open another issue if it comes up again
