### ISSUE TITLE
Grass ticking performance issue

### ISSUE THREAD

**Issue by dktapps** [pmmp/PocketMine-MP#436]
### Issue description
Grass is abundant, and its ticking method is not well optimized, and nor does it work correctly. 

References:
https://github.com/PocketMine/PocketMine-MP/pull/3724
https://github.com/pmmp/PocketMine-MP/issues/152

**Comment by markkrueg** [comment]
As an interim workaround; does this feature of pocketmine.yml work? For example:

```
 #IDs of blocks not to perform random ticking on.
 disable-block-ticking:
  - 2  # grass
  - 81 # cactus
```

Will this example stop grass and cactus from ticking? Or am I misunderstanding?

**Comment by jasonwynn10** [comment]
I believe that @dktapps doesn't want to stop the ticking of the block so much as make the ticking use less resources and work properly

**Comment by dktapps** [comment]
@markkrueg yes, that is its intended use.

@jasonwynn10 also correct, but configuration is merely a matter of preference

**Comment by dktapps** [comment]
Fixing grass ticking properly requires a sky-light implementation. #160

**Comment by dktapps** [comment]
This has been fixed on a development branch. This issue will be closed when the changes are merged to master (no ETA can be given).

**Comment by dktapps** [comment]
Oops, this isn't on master yet.
