### ISSUE TITLE
Terminal will crash in some special enviroment

### ISSUE THREAD

**Issue by Blackjack200** [pmmp/PocketMine-MP#4365]
# Enviroment
OS: MacOS(Catalina)
Terminal: bash(embed)
PocketMine-MP: 2782af7e22b2c25b79cca15587233b6eadd854ab

Since 2782af7e22b2c25b79cca15587233b6eadd854ab use typed property, `tput xxx`  may return string|null but not only string, and it will crash the server, and `tput sitm` return null in my system(terminal).

**Comment by Blackjack200** [comment]
localhost:PocketMine-MP michael$ php -r "var_dump(shell_exec('tput sitm'));"
NULL

**Comment by dktapps** [comment]
This can be reproduced by running a server inside `tmux`.
