### ISSUE TITLE
Cannot connect to server

### ISSUE THREAD

**Issue by RedHatMCPE** [pmmp/PocketMine-MP#437]
Players cannot connect to server, as it says unable to connect, and sometimes 'server is full', but I have no players on. I am using the **latest PMMP build** on a Macbook Air running the OS **El Capitan**.

**Comment by dktapps** [comment]
Without knowing your PocketMine-MP version, OS, PHP, Client version, or plugins and how the issue occurred, the issue cannot begin to be solved.
A pre-formatted template is provided that shows the required information to begin to find, test and solve an issue.
Until the adequate template and information is provided, the issue will be closed; it may be reopened if you update the ticket with the correct template and required information.

You may also use our [forums](https://forums.pmmp.io) for support.

[Contribution guidelines](https://github.com/pmmp/PocketMine-MP/blob/master/CONTRIBUTING.md)

**Comment by Sandertv** [comment]
Did you even port-forward?
