### ISSUE TITLE
Bug With Recipes

### ISSUE THREAD

**Issue by galaxytwenty** [pmmp/PocketMine-MP#4378]
There is a Bug with the Crafting Recipes 

für a Bookshell i need 6 Karmesinwood and 3 books.
or Blackstone for a furnance

![Wierd](https://user-images.githubusercontent.com/79281788/129746243-1f84bb06-1f1d-4bba-8b36-42bac8640247.PNG)

Pls can u Fix that ?.

Greetz
GLX20

**Comment by dktapps** [comment]
Without knowing your PocketMine-MP version, OS, PHP, Client version, or plugins and how the issue occurred, the issue cannot begin to be solved.
A pre-formatted template is provided that shows the required information to begin to find, test and solve an issue.
Until the adequate template and information is provided, the issue will be closed; it may be reopened if you update the ticket with the correct template and required information.

[Contribution guidelines](https://github.com/pmmp/PocketMine-MP/blob/master/CONTRIBUTING.md)

**Comment by MonoAdrian23** [comment]
Xd?
Issue Close because Version is Missing!
Pocketmine is a downfall Software
User friendly is a big Problem of Pocketmine.

**Comment by galaxytwenty** [comment]
I used Pockemine Latest, Now i have Teste on a Clean Without Plugins, Still the same like the pic Above.
Os = win10, and tested on Android 
Client Version = 1.17.11
Plugins = 0 Plugins.

Hope now this is the Right Information,
so Many Server have this Bug now, i think comes from Pocketmine.

**Comment by alvin0319** [comment]
`latest` is not a valid version of PocketMine.
> try the `version` command | LATEST IS NOT A VALID VERSION

**Comment by galaxytwenty** [comment]
Pockemine 3.22.1

**Comment by galaxytwenty** [comment]
is This enough Information, i mean.

you can try, i think BY you is the same issue?

**Comment by galaxytwenty** [comment]
can u Reopen @dktapps
