### ISSUE TITLE
When you install a block, it is displayed for a second with a different meta

### ISSUE THREAD

**Issue by PechenkaPM** [pmmp/PocketMine-MP#4382]
### Issue description

- Expected result: display white bed at once
- Actual result: first a red bed appears, and then it turns white

### Steps to reproduce the issue
1. Put a lot of white beds, with some probability you will have time for a second to see red instead of white

### OS and versions
* PocketMine-MP: [3.22.1](https://github.com/pmmp/PocketMine-MP/tree/9477034a4ae58cc5c12b8278c14a8e46a43992b2)
* PHP: 7.4
* Using JIT: no
* Server OS: Linux Ubuntu 20.04
* Game version: Win10

### Plugins
Plugins (0):

### Crashdump, backtrace or other files
https://youtu.be/S4dsp17k0uE

**Comment by PechenkaPM** [comment]
the same problem is observed with the head of the mob, for a second the head of the skeleton appears, instead of the desired

**Comment by PechenkaPM** [comment]
watch video at 0.25x speed

**Comment by celishere** [comment]
#vovakit

**Comment by dktapps** [comment]
I'd suggest checking this in vanilla also. If it immediately appears red when you place it, it's probably not PM's fault, but more likely the client side predictions.

**Comment by PechenkaPM** [comment]
checked in the vanilla world, there is no such bug, most likely PM sends something wrong at the beginning, or it is a protocol error
https://youtu.be/CKvZC9JiqvA

**Comment by dktapps** [comment]
I've been informed that this doesn't happen in PM4, so it's unlikely to get fixed on PM3.

**Comment by Blackjack200** [comment]
i met that and this may stupid client bug

**Comment by dktapps** [comment]
I doubt that, since it's not happening on PM4...

**Comment by dktapps** [comment]
It seems like this is happening because there's a small time delay between when UpdateBlockPacket is sent, and when BlockActorDataPacket is sent to create the tile. Before the tile is created client-side, the bed is rendered as a default red.

On PM4 this doesn't happen because the block and tile are both sent together in the same batch. This is a too-large change for PM3 at this stage, so I don't plan on fixing it.
