### ISSUE TITLE
Players are not notified when the world spawn point changes (compasses don't update)

### ISSUE THREAD

**Issue by PechenkaPM** [pmmp/PocketMine-MP#4383]
### Issue description

- Expected result: the compass should point to the current spawn location
- Actual result: the compass points to the old (which was at the entrance to the server) place of appearance

### Steps to reproduce the issue
1. Change the place of the spawn in the world or your own (using the bed)

### OS and versions
* PocketMine-MP: [3.22.1](https://github.com/pmmp/PocketMine-MP/tree/9477034a4ae58cc5c12b8278c14a8e46a43992b2)
* PHP: 7.4
* Using JIT: no
* Server OS: Linux Ubuntu 20.04
* Game version: Win10

### Plugins
Plugins (0):

### Crashdump, backtrace or other files
https://youtu.be/-XOH0SP7P1o

**Comment by dktapps** [comment]
Using a bed doesn't change your spawn point. Compasses always point to the world spawn, not the player spawn.

**Comment by PechenkaPM** [comment]
I was typing / setworldspawn on the video, why didn't the compass start pointing to this place?

**Comment by dktapps** [comment]
Because players don't receive any notification that the world spawn has changed. It was never implemented.

I'm not saying the issue is invalid; I'm just saying that sleeping in a bed doesn't change compass direction anyway.
