### ISSUE TITLE
I cannot walk normally

### ISSUE THREAD

**Issue by FlxiBoy1313** [pmmp/PocketMine-MP#4392]
### Issue description

- That I can still walk normally
- That I can no longer run normally because the running animation always stops. See video below.

### Steps to reproduce the issue
1. To be honest, I don't know, because php7.4 will soon no longer be supported.

### OS and versions
* PocketMine-MP: 3.22.2
* PHP: 7.4
* Using JIT: no
* Server OS: Windows
* Game version: Win11 respectively Win10. But my PC runs on Win11

### Plugins
Plugin(0): 

### Crashdump, backtrace or other files
Video is here (just the link because the video is too big.): https://www.mediafire.com/file/53qg692tpvwz76b/Minecraft_2021-08-21_21-21-58_Trim.mp4/file

**Comment by dktapps** [comment]
Without knowing your PocketMine-MP version, OS, PHP, Client version, or plugins and how the issue occurred, the issue cannot begin to be solved.
A pre-formatted template is provided that shows the required information to begin to find, test and solve an issue.
Until the adequate template and information is provided, the issue will be closed; it may be reopened if you update the ticket with the correct template and required information.

[Contribution guidelines](https://github.com/pmmp/PocketMine-MP/blob/master/CONTRIBUTING.md)

**Comment by FlxiBoy1313** [comment]
I don't have any further information?

**Comment by mmm545** [comment]
You didn't give steps to reproduce the issue, if you don't have any then the issue can't be solved
