### ISSUE TITLE
Players freezes after teleportations randomly

### ISSUE THREAD

**Issue by Prim69** [pmmp/PocketMine-MP#4394]
### Issue description

- Expected result: Players movement should continue being broadcasted to others
- Actual result: Players movement is temporarily frozen

### Steps to reproduce the issue
1. Throw an ender pearl while running, make sure to stop moving before it lands. Now until you move you're stuck on everyone elses screen.
### OS and versions

* PocketMine-MP: 4.0.0
* PHP: 8.0.7
* Using JIT: no
* Server OS: Ubuntu
* Game version: Win10

### Plugins
Plugins (2): Core, Anticheat

- If you remove all plugins, does the issue still occur?
  Yes
- If the issue is **not** reproducible without plugins:
  - Have you asked for help on our forums before creating an issue?
  - Can you provide sample, *minimal* reproducing code for the issue? If so, paste it in the bottom section
  This fix was given by ZodiaX
  ```php
  // after teleporting a player do this
  $player->broadcastMovement(true);
  $player->broadcastMotion();
    ```

### Crashdump, backtrace or other files
https://youtu.be/_JZ71hPMbtk

**Comment by Prim69** [comment]
Edited it with a reproduction step

**Comment by dktapps** [comment]
Sounds like the teleport isn't being broadcasted (which makes no sense).

**Comment by dktapps** [comment]
What I observe is that the player does in fact teleport to the proper location, but snaps back to their old position immediately afterwards. It's not clear to me why this is happening yet.

**Comment by dktapps** [comment]
Further investigation indicates that the position is indeed being sent correctly, but in the same batch buffer as a regular movement to the old location. I don't understand why this is a problem, but it appears as though the regular move is taking precedence over the teleport, despite being earlier in the buffer.

**Comment by dktapps** [comment]
It appears that removing FLAG_TELEPORT fixes this problem. I'm not very clear on why that is.

**Comment by Prim69** [comment]
If it helps this doesn't occur on pm3

**Comment by dktapps** [comment]
Not really, because every indication I see is that this is a client bug.

**Comment by dktapps** [comment]
It appears the reason this doesn't happen on PM3 is because MovePlayerPacket is used to send movements to viewers, whereas MoveActorAbsolutePacket is used on PM4. So, this boils down to a bug in the way the client is handling MoveActorAbsolute for players.

**Comment by ItsZodiaX** [comment]
> If it helps this doesn't occur on pm3

It happen after 1.17 both pm3 and pm4

**Comment by dktapps** [comment]
No, it doesn't. I tested it myself just hours ago.

**Comment by ItsZodiaX** [comment]
Oh okay my bad

**Comment by ItsZodiaX** [comment]
Does this get fixed? I still freeze on 4.0.0-BETA2

**Comment by dktapps** [comment]
Unless Mojang fixed the client issue without anyone noticing, no.

**Comment by dktapps** [comment]
Further investigation reveals that all entities, not just players, are impacted by this bug. It's a little harder to reproduce with random entities due to their inability to use ender pearls, however this code:
```php

	public function onEntityInteract(PlayerEntityInteractEvent $event) : void{
		$entity = $event->getEntity();
		$location = $entity->getLocation();
		$this->getServer()->broadcastPackets($entity->getViewers(), [MoveActorAbsolutePacket::create(
			$entity->getId(),
			$entity->getOffsetPosition($location),
			$location->pitch,
			$location->yaw,
			$location->yaw,
			(
				($entity->onGround ? MoveActorAbsolutePacket::FLAG_GROUND : 0)
			)
		)]);
		$event->getEntity()->teleport($event->getEntity()->getPosition()->add(10, 0, 0));
	}
```
will reproduce the problem when right-clicking on a mob.

**Comment by dadodasyra** [comment]
https://streamable.com/xxate5
Is it related to this issue ? I don't understand why dylan is saying it's complicated to reproduce.

**Comment by dktapps** [comment]
no, that's a completely different issue.
