### ISSUE TITLE
BlockItemPickupEvent

### ISSUE THREAD

**Issue by ColinHDev** [pmmp/PocketMine-MP#4399]
## Description
The BlockItemPickupEvent would be an event under the pocketmine\event\block namespace and would extend the BlockEvent and implement the Cancellable interface. The contructor could be nearly the same as the constructor of EntityItemPickupEvent except its first parameter, $collector, which needs to be of type Block instead of Entity.
It would be called when a block picks up an item, arrow, etc.

## Justification
With the remove of the InventoryPickupEvent and the addition of the EntityItemPickupEvent through eb9188c30958c8efa4ad8acf1126712a4013d4ca it became no longer possible to implement that blocks which hold inventories can pickup items, for example in case of the Hopper.
To allow this addition in a future PR a BlockItemPickupEvent would be needed to implement.

**Comment by ColinHDev** [comment]
I know, if this event would be implemented, it would be dead code because at the moment, it would never be called.
But since PRs shouldn't be filled with too many changes, the event would be needed to make a PR for Hoppers. (Otherwise we would have Hoppers and the Event in the PR and that could be considered as overfilled.)

**Comment by ColinHDev** [comment]
Just for clarification:
- I am planning to make a PR to add the event but I first wanted to make sure that this idea is good enough
- I know that a PR would basically just add dead code but I am also planning to make a PR to fully implement Hoppers (right now they are half implemented: basically they are just containers right now without any ability to transport items) and to do so this event would be needed.

**Comment by dktapps** [comment]
To be honest, it would have taken a lot less time and effort to just make the PR directly.

**Comment by ColinHDev** [comment]
yeah.. 
I thought I would save time with creating an issue instead of a PR if you don't like the idea

**Comment by dktapps** [comment]
Implemented in #4402.
