### ISSUE TITLE
the transfer works every other time

### ISSUE THREAD

**Issue by SenseiTarzan** [pmmp/PocketMine-MP#4400]
the transfer is activated but the player is disconnected before being transferred.
you could see during the whole video
the ports are all open because we have no firewall

https://youtu.be/nYytZEkjf1k

Version PocketMine-MP 4.0.0

**Comment by dktapps** [comment]
Without knowing your PocketMine-MP version, OS, PHP, Client version, or plugins and how the issue occurred, the issue cannot begin to be solved.
A pre-formatted template is provided that shows the required information to begin to find, test and solve an issue.
Until the adequate template and information is provided, the issue will be closed; it may be reopened if you update the ticket with the correct template and required information.

[Contribution guidelines](https://github.com/pmmp/PocketMine-MP/blob/master/CONTRIBUTING.md)
