### ISSUE TITLE
Server not stopping

### ISSUE THREAD

**Issue by SuperAdam47** [pmmp/PocketMine-MP#441]
![screenshot_2017-03-12-13-29-23](https://cloud.githubusercontent.com/assets/16169771/24079458/1e74cbfc-0c91-11e7-821e-08f19f62d1d6.png)

**Comment by NycuRO** [comment]
Same.

**Comment by dktapps** [comment]
Outdated SPL.

**Comment by NycuRO** [comment]
@dktapps I have same problem.

**Comment by dktapps** [comment]
I could spell it out letter by letter, but I have better things to do with my Sunday morning. Your SPL is out of date. Update it and stop spamming. And for God's sake start either using Git or prebuilt phars.

**Comment by dktapps** [comment]
This is also a duplicate of #413
