### ISSUE TITLE
BlockBreakEvent->setCancelled() not working properly

### ISSUE THREAD

**Issue by minijaham** [pmmp/PocketMine-MP#4420]
### Issue description

- Currently, BlockBreakEvent is being cancelled in a plugin(WorldGuard) with MONITOR priority.
- However, when BlockBreakEvent->isCancelled() is called in another plugin(Core) with LOW priority, it returns false.

### Steps to reproduce the issue
1. Cancel BlockBreakEvent
2. Use $event->isCancelled() in another function

### OS and versions

* PocketMine-MP: 3.22.2
* PHP: 7.4
* Using JIT: no
* Server OS: Windows 10
* Game version: Win10/Android/iOS

### Plugins

Core v1.0.0, WorldGuard v1.1.95

**Comment by ColinHDev** [comment]
https://github.com/pmmp/PocketMine-MP/blob/stable/src/pocketmine/event/EventPriority.php#L30-L37:
```php
/**
 * List of event priorities
 *
 * Events will be called in this order:
 * LOWEST -> LOW -> NORMAL -> HIGH -> HIGHEST -> MONITOR
 *
 * MONITOR events should not change the event outcome or contents
 */
 ```

**Comment by minijaham** [comment]
Ah...yes. It was definitely the misuse of priority flag. 
Thanks @ColinHDev !
