### ISSUE TITLE
Item frames don't work properly.

### ISSUE THREAD

**Issue by serezha13** [pmmp/PocketMine-MP#4422]
### Issue description

Item frames don't work properly.

### Steps to reproduce the issue
Place item frame.

### OS and versions
* PocketMine-MP: Latest 1.17.10 master
* PHP: 8.0

https://user-images.githubusercontent.com/39884693/131355210-d34a5363-afb5-4090-8f28-9888e59fa282.mp4

**Comment by dktapps** [comment]
Without knowing your PocketMine-MP version, OS, PHP, Client version, or plugins and how the issue occurred, the issue cannot begin to be solved.
A pre-formatted template is provided that shows the required information to begin to find, test and solve an issue.
Until the adequate template and information is provided, the issue will be closed; it may be reopened if you update the ticket with the correct template and required information.

[Contribution guidelines](https://github.com/pmmp/PocketMine-MP/blob/master/CONTRIBUTING.md)

**Comment by serezha13** [comment]
> Without knowing your PocketMine-MP version, OS, PHP, Client version, or plugins and how the issue occurred, the issue cannot begin to be solved.
> A pre-formatted template is provided that shows the required information to begin to find, test and solve an issue.
> Until the adequate template and information is provided, the issue will be closed; it may be reopened if you update the ticket with the correct template and required information.
> 
> [Contribution guidelines](https://github.com/pmmp/PocketMine-MP/blob/master/CONTRIBUTING.md)

now is good?

**Comment by celishere** [comment]
No
