### ISSUE TITLE
Item frames don't work properly.

### ISSUE THREAD

**Issue by serezha13** [pmmp/PocketMine-MP#4424]
Issue description
Item frames don't work properly.

Steps to reproduce the issue
Place item frame.

OS and versions
PocketMine-MP: 4.0.0+dev (git hash: 3fe6ce7-dirty)
PHP: 8.0.9
Using JIT: no
Server OS: win
Game version: Win10

https://user-images.githubusercontent.com/39884693/131580732-b0f92d50-9ab3-42bf-9fc2-67b4cfc98363.mp4

**Comment by dktapps** [comment]
I'm not able to reproduce this. Check your plugins (and make sure your git submodules are updated).
