### ISSUE TITLE
The "Thorns" enchantment does not work correctly. Bow shooter get damage

### ISSUE THREAD

**Issue by zpwrd** [pmmp/PocketMine-MP#4425]
### Issue description

The "Thorns" enchantment does not work correctly. If a player is with spikes of level 3 and they try to shoot him with a bow, then the shooter receives damage from the spikes. Logically, this should not be, but should only be when hitting with a sword or other Items.

### Steps to reproduce the issue
1. Enchant our armor on Thorns 1-3
2. Try to shot player wirh that armor/
3. We got the damage (shooter)

### OS and versions

* PocketMine-MP: PocketMine-MP 3.22.1
* PHP: 7.4
* Server OS: Ubuntu 20.04
* Game version: Android/iOS/Win10/Xbox/PS4/Switch (delete as appropriate)

- If you remove all plugins, does the issue still occur? - Yes
- If the issue is **not** reproducible without plugins:
  - Have you asked for help on our forums before creating an issue?
  - Can you provide sample, *minimal* reproducing code for the issue? If so, paste it in the bottom section

**Comment by ColinHDev** [comment]
https://minecraft.fandom.com/wiki/Thorns#Usage
works as intended
