### ISSUE TITLE
Easier way to get players' devices & control schemes

### ISSUE THREAD

**Issue by Xd-pro** [pmmp/PocketMine-MP#4426]
## Description
Currently, the best way to check a player's device or control scheme is through some complex network-related stuff. This is not very intuitive.

## Justification
A lot of servers will want to optimize the experience on a control-scheme or device basis, implement device-based matchmaking, block control schemes in certain areas and more. They are not very easy to do as of right now. I think it will overall improve the quality of most pocketmine servers.

**Comment by Prim69** [comment]
This is made easy in PM4

**Comment by dktapps** [comment]
In PM4 you can get this information via PlayerInfo->getExtraData(). I think that's sufficient.
