### ISSUE TITLE
Furnaces freeze progress after a restart & Requirement of Delayed Block Update queue disk saving

### ISSUE THREAD

**Issue by CortexPE** [pmmp/PocketMine-MP#4430]
## Description
As mentioned in the title, the furnace stops its progress after a restart, only returning back to life once updated. This issue stems from the lack of disk saving for the Delayed Block Update queue.

## Justification
This would allow for better implementation of continuously ticking block tiles and other blocks that require delayed updates (ex: Redstone mechanics).

## Alternative methods
An alternative to this is a third party plugin that will have to keep track of all block tiles needing an update using reflection hacks, saving it on a separate file, and then scheduling a delayed update for each block upon chunk load.

**Comment by dktapps** [comment]
I don't think you're taking "alternative solutions" very seriously. There's an easy solution to this that doesn't require any significant internals changes, which is to have the tile scheduled block updates on creation.

**Comment by CortexPE** [comment]
Well, that would work for furnaces and the like where it continuously ticks...

However if we also take Redstone mechanics into consideration which require specific tick timings to be restored, that wouldn't work unless we also save the tick difference it needs to re-schedule after creation

**Comment by dktapps** [comment]
Redstone doesn't have any relevance to this bug.

**Comment by dktapps** [comment]
This is a regression from PM3, which uses the method I described (scheduling update on creation) to manage this.
