### ISSUE TITLE
Generation point within a tree leaf

### ISSUE THREAD

**Issue by MrBlasyMSK** [pmmp/PocketMine-MP#4436]
### Issue description
When I appeared in the world, my head was stuck in a tree leaf

- Expected result: What were you expecting to happen? Not being stuck inside a sheet
- Actual result: What actually happened? That i was inside

### Steps to reproduce the issue
1. Download Pocketmine 4.0.0 Beta 1
2. Run and enjoy the bug

### OS and versions

* PocketMine-MP: 4.0.0-BETA1 (git hash: 210b9c7b75fe3183600e85f9f4a24ef125fcb1cf)
* PHP: 8.0.9
* Using JIT: not supported
* Server OS: linux
* Game version: Win10

### Plugins

Plugins (2): BuilderTools v1.3.0-beta1, DevTools v1.15.0+dev

- If you remove all plugins, does the issue still occur? Yes
- If the issue is **not** reproducible without plugins:
  - Have you asked for help on our forums before creating an issue?
  - Can you provide sample, *minimal* reproducing code for the issue? If so, paste it in the bottom section

### Crashdump, backtrace or other files

Video
https://streamable.com/3dq9v8

**Comment by dktapps** [comment]
Is this in a newly generated world, or an existing one?

**Comment by MrBlasyMSK** [comment]
It has been generated by default, I have only started the server

**Comment by dktapps** [comment]
What's the seed of the world?

**Comment by dktapps** [comment]
Closing due to lack of response.
