### ISSUE TITLE
Tag "RandomSeed" does not exist

### ISSUE THREAD

**Issue by MrBlasyMSK** [pmmp/PocketMine-MP#4438]
Link to crashdump: 
[Crash.txt](https://github.com/pmmp/PocketMine-MP/files/7123767/Crash.txt)

I have tried to add a world of version 1.17.1 and this crash has appeared

**Comment by dktapps** [comment]
Worlds newer than 1.12 are not currently supported. Unfortunately, PM isn't able to tell the difference between a 1.17 world and a 1.12 world without crashing, so this is currently difficult to fix.

**Comment by dktapps** [comment]
Closing as duplicate of #2653.
