### ISSUE TITLE
Server crashed

### ISSUE THREAD

**Issue by ProtectorYT364** [pmmp/PocketMine-MP#4441]
submit crashdump files to 
Link to crashdump: https://pastebin.com/61EjcnjC

**Comment by ProtectorYT364** [comment]
https://pastebin.com/61EjcnjC

**Comment by ProtectorYT364** [comment]
<!--- submit crashdump files to 
Link to crashdump: https://pastebin.com/61EjcnjC

**Comment by ProtectorYT364** [comment]
submit crashdump files to 
Link to crashdump: https://pastebin.com/61EjcnjC

**Comment by KygekDev** [comment]
I cannot understand what this issue means, at all.

**Comment by Teagokk** [comment]
my server is “stopping” infinite because I went to restart, what do I do?

**Comment by KygekDev** [comment]
> my server is “stopping” infinite because I went to restart, what do I do?

I suggest you to try debugging your crashing issue before making a new issue here.

Crashdumps may help you figuring out what's causing your crashing issue.

**Comment by Teagokk** [comment]
![image](https://user-images.githubusercontent.com/88906106/132499150-42680a9e-ec16-498b-bef4-d91c40190362.png)

**Comment by KygekDev** [comment]
@Teagokk 
Thanks for the very informative screenshot.

**Comment by ProtectorYT364** [comment]
@dktapps How can i fix it ?

**Comment by dktapps** [comment]
Don't unload worlds while they are in use.

**Comment by ProtectorYT364** [comment]
> Don't unload worlds while they are in use.

Its like when they play the world load and when they die the world unload like when they play the world automatically create named duel1 then when they die the world automatically unload called duel1

**Comment by ProtectorYT364** [comment]
![IMG_20210909_111238](https://user-images.githubusercontent.com/86392268/132629538-599f70dd-8bb2-4fc4-bb47-9abbeb60fdfa.jpg)
