### ISSUE TITLE
Blocks are not broken with EFFICIENCY Enchantment

### ISSUE THREAD

**Issue by Prisane** [pmmp/PocketMine-MP#445]
### Issue description

I showed the problem with the video
https://www.youtube.com/watch?v=Jru4svI2zoo&feature=youtu.be

### OS and versions

*  @PocketMine-MP: [c040579](https://github.com/pmmp/PocketMine-MP/commit/c040579e090e3461829e42b62db50d0085b81e5b)
* PHP: 7
* Server OS: linux
* Game version: PE/Win10

**Comment by JackNoordhuis** [comment]
Duplicate of #414

**Comment by Prisane** [comment]
You suggest it a temporary solution?
