### ISSUE TITLE
Add Getter to Player::$playerInfo

### ISSUE THREAD

**Issue by Blackjack200** [pmmp/PocketMine-MP#4450]
Add API to get player clientdata just like gophertunnel.

minecraft.(*Conn).ClientData()

it isn't good to get player info by override player class or use reflection.
(protected PlayerInfo $playerInfo)

## Alternative methods

Player::$playerInfo

```php
$prop = new ReflectionProperty(Player::class,"playerInfo");
$prop->setAccessible(true);
$info = $prop->getValue($player);
```

**Comment by Rush2929** [comment]
You can use this as an alternative.
```php
/** @var Player $player */
$player->getNetworkSession()->getPlayerInfo();
```

**Comment by Blackjack200** [comment]
> You can use this as an alternative.
> 
> ```
> /** @var Player $player */
> $player->getNetworkSession()->getPlayerInfo();
> ```
> 
> (https://github.com/pmmp/PocketMine-MP/blob/master/src/network/mcpe/NetworkSession.php#L267)

so why add a player info in player or not use network session ones.
Network layer API may change anytime, so why not use other layers API for compactability
