### ISSUE TITLE
There's no way to modify ConsoleCommandSender's permissions

### ISSUE THREAD

**Issue by Nerahikada** [pmmp/PocketMine-MP#4456]
## Description
PocketMine-MP 4.0.0 does not have a way to modify ConsoleCommandSender permissions from plugins.

I don't have any ideas for specific API changes, so here is what I have tried.

## Justification
For example, commands that are only available in the console cannot be implemented in plugins.

## Alternative methods
Since there is no direct way to get the ConsoleCommandSender from the server, I tried the following code.
However, since ConsoleCommandSender is created after the plugin, this code did not work.
```php
protected function onEnable() : void{
    foreach($this->getServer()->getBroadcastChannelSubscribers(Server::BROADCAST_CHANNEL_ADMINISTRATIVE) as $subscriber){
        if($subscriber instanceof ConsoleCommandSender){
            $subscriber->setBasePermission("myplugin.permission.console", true);
        }
    }
}
```

**Comment by dktapps** [comment]
You can add the permission as a child of `pocketmine.group.operator`, like it's done here: https://github.com/pmmp/PocketMine-MP/blob/master/src/permission/DefaultPermissions.php#L37
