### ISSUE TITLE
Transfer doesn't work randomly.

### ISSUE THREAD

**Issue by IvanCraft623** [pmmp/PocketMine-MP#4468]
### Issue description
Transferring players to another server does not transfer randomly and only disconnects from the server.

- Expected result: What were you expecting to happen?
The player is transferred to another server successfully.

- Actual result: What actually happened?
The player is only disconnected from the server as if the TransferPacket packet was not sent.

### Steps to reproduce the issue
1. Try to transfer to a server using the `/transferserver` command or with the code `Player->transfer();`
2. In many cases the player is just disconnected.

### OS and versions

* PocketMine-MP: 4.0.0-BETA2
* PHP: 8.0.10
* Using JIT: No 
* Server OS: Ubuntu
* Game version: Android/Win10

### Plugins

No plugins

- If you remove all plugins, does the issue still occur?
Yes
- If the issue is **not** reproducible without plugins:
  - Have you asked for help on our forums before creating an issue?
  - Can you provide sample, *minimal* reproducing code for the issue? If so, paste it in the bottom section

**Comment by IvanCraft623** [comment]
This bug does not happen in PM3

**Comment by dktapps** [comment]
This does occur on PM3, I've seen it for myself. This is a client bug.
