### ISSUE TITLE
Allows Custom LoginPackets (PM4)

### ISSUE THREAD

**Issue by IvanCraft623** [pmmp/PocketMine-MP#4473]
## Description
Currently PM4 does not allow custom LoginPackets, mainly used for proxies.

## Justification
These are very useful for proxy servers, since they allow you to send the XUIDs and more data of the players and be able to use them in the plugins.

## Currently receiving a personalized LoginPacket responds:
`[Server thread/ERROR]: [NetworkSession: 0.0.0.0 11111] Bad packet (error ID 0c083b633f8e): Error processing LoginPacket: JSON property "Waterdog_XUID" does not exist in object of type pocketmine\network\mcpe\protocol\types\login\ClientData`

**Comment by dktapps** [comment]
This is unsupported behaviour. It's a job for Waterdog to stop abusing the Minecraft vanilla protocol. I believe WaterdogPE already addressed this.

**Comment by morcheysha77** [comment]
This problem has been fixed, you can now disable this via the config.yml file

use_login_extras: true to use_login_extras: false
