### ISSUE TITLE
ResourcePack manifest missing key

### ISSUE THREAD

**Issue by TheDataLion** [pmmp/PocketMine-MP#4485]
### Issue description

- Expected result: Be able to load pack with: "capabilities" key in manifest.json
- Actual result: It didn't load and prints the following error: 
`Could not load resource pack "resourcepack.zip": Invalid manifest.json contents: JSON property "capabilities" does not exist in object of type pocketmine\resourcepacks\json\Manifest`

### Steps to reproduce the issue
1. Put this inside of your resoucepack manifest.json: 
```
  "capabilities": [
    "chemistry"
  ]
```
2. Start server and the pack won't load and prints error:
`Could not load resource pack "resourcepack.zip": Invalid manifest.json contents: JSON property "capabilities" does not exist in object of type pocketmine\resourcepacks\json\Manifest`

### OS and versions
* PocketMine-MP: 4.0.0-BETA3+dev
* PHP:  PHP 8.0.10
* Using JIT: no
* Game version: Windows 10

### Source
According to [BDS ](https://www.minecraft.net/en-us/download/server/bedrock) this key should exist.
You can find it inside of: `resource_packs/chemistry/manifest.json`

**Comment by dktapps** [comment]
Seems to be missing from the documentation: https://docs.microsoft.com/en-us/minecraft/creator/documents/resourcepack
I guess this needs further investigation, since it's not documented.
