### ISSUE TITLE
Put item classes into subfolders

### ISSUE THREAD

**Issue by TheDiamondYT1** [pmmp/PocketMine-MP#449]
### Issue description
A nice idea would be to seperate the item classes into subfolders, for example:
```
\pocketmine\item
    tool
        WoodenShovel.php
        ShoghicpIsHoe.php
    food
        Steak.php
```
Well, you tet the idea. This allows for better readability and would be good to implement since items are undergoing a rewrite anyway.

### OS and versions
Irrelevant

**Comment by TheDiamondYT1** [comment]
:(

**Comment by SalmonDE** [comment]
@TheDiamondYT1 Just so you know.
Dylan doesn't try to be rude. It's just that items were moved to a json file, which makes these classes actually useless.

**Comment by TheDiamondYT1** [comment]
@SalmonDE I know he doesnt try to be rude, its just that he could provide even a really short reason as to why it was closed. Not complaining or anything. * "Items have been moved to json so this is irrelevant"*

**Comment by JackNoordhuis** [comment]
He closes that many useless issues and pull requests that if he gave a descriptive reason as to why they were closed, he literally wouldn't have time to develop anything.

Most reasons are pretty obvious but if it isn't, other people are usually pretty helpful in giving you a reason why.
