### ISSUE TITLE
Players can eat items by dropping them (pm4)

### ISSUE THREAD

**Issue by sn3akrr** [pmmp/PocketMine-MP#4491]
### Issue description

- Expected result: Dropping food stops eating process
- Actual result: Eats food and drops one

### Steps to reproduce the issue
1. Start eating food
2. Drop it

### OS and versions
* PocketMine-MP: 4.0.0-BETA4
* PHP: 8.0.7? latest

### Plugins
doesn't matter

- If you remove all plugins, does the issue still occur? yes

https://youtu.be/yLkv9nRrNEs

**Comment by sn3akrr** [comment]
gives windows 10 players an advantage in pvp especially

**Comment by Nerahikada** [comment]
this is a duplicate of #4355

**Comment by sn3akrr** [comment]
oh, well it was never confirmed and made around 2 months ago so i didn't know it existed xd

**Comment by Nerahikada** [comment]
I think this is probably a low priority in dylan's mind
anyway, I recommend closing this issue since it is a duplicate

**Comment by dktapps** [comment]
For future reference, the `version` command on PM4 tells you your PHP version, amongst other things.
