### ISSUE TITLE
Problems crafting with desktop GUI

### ISSUE THREAD

**Issue by admsteck** [pmmp/PocketMine-MP#45]
Using the Windows 10 Edition beta, I am unable to craft anything.  Server consolet shows:
`Notice: Undefined offset: 0 in /opt/pocketmine-src/src/pocketmine/Player.php on line 2598`
It also appears to throw the last selected item in front of the player when closing the crafting screen. 

The same server works correctly with Win10 Mobile version of minecraft PE.
### Steps to reproduce the issue

When running Win10 beta, chop down a block of wood and try to craft planks.  It appears to work, but when you close the crafting window, the planks disappear out of inventory and the wood reappears.  Server console shows the message mentioned above. 
### OS and versions
- PHP: PHP7
- Server OS: Ubuntu 16.04.1 LTS
  Game/PocketMine versions:  Tried with PocketMine master branch(e7e476b65e457c3b5d322d05a4789d9303c362c9) and Minecraft Win10 beta 15.10 and PocketMine 0.16 branch (1680fee764a05441a67c894ffffe83584d3747f2) with Win10 beta v0.16.0

**Comment by dktapps** [comment]
Yes, this is a well-known issue.

**Comment by admsteck** [comment]
Ok, I didn't see it mentioned anywhere so I thought I would log it.

**Comment by am910021** [comment]
the server running on win10 pc.

windows 10 version can not connect to server, but ios version can connect.

**Comment by Tarik02** [comment]
@dktapps, I can help you with this, I can port new inventory transactions from Genisys.

**Comment by dktapps** [comment]
The next person who talks about porting things from Genisys is going to get a smack. This project does not exist to copy from the ugly mess that is Genisys.

**Comment by Tarik02** [comment]
@dktapps, ok!

**Comment by dktapps** [comment]
This MAY be properly fixable in an upcoming update with shoghicp's work on vanilla transactions. Let's hope...

**Comment by IISweePII** [comment]
Hmm, never noticed that before

**Comment by archie426** [comment]
Just saying, this is in the spoon that LBSG uses. Seems like this hasn't been fixed there either

**Comment by Rover656** [comment]
How long till a fix?

**Comment by dktapps** [comment]
We don't set a specific release date for bugfixes. Don't waste your time or ours asking for ETAs.

**Comment by Rover656** [comment]
@dktapps fair enough, sorry

**Comment by dktapps** [comment]
As a way to work around this problem, you can switch W10 Edition to Pocket GUI mode.

Game settings -> Video -> Show Advanced Video Settings ->UI Profile -> Select "Pocket"

This is obviously not a fix, it's simply a workaround until we get around to tackling the problem. (Waiting for shoghicp to finish his work with vanilla inventory transactions.)

**Comment by Rover656** [comment]
@dktapps thank you for the solution!!! You're the best!

**Comment by dktapps** [comment]
This issue should be solved in the upcoming MCPE 1.2 update. (It's taken quite some time)

**Comment by totor29** [comment]
same issue i suppose

017-08-05 [00:24:22] [Server thread/CRITICAL]: ErrorException: "Undefined offset: 0" (EXCEPTION) in "src/pocketmine/Player" at line 2887

**Comment by stormchaser3000** [comment]
i am sorry if i am stating the obvious or already known but now the android client has this issue to because the inventory was changed to be slightly more like windows 10 and xbox one for 1.2. and because of this it is now impossible to craft anything on 1.2 servers using pmmp on any device when using minecraft 1.2

**Comment by teracube** [comment]
@stormchaser3000
i confirm it's impossible to craft for a player op or non op using PMMP 1.2. 
tested with  PocketMine-MP_1.7dev-71_6e961ae8_API-3.0.0-ALPHA8.phar

**Comment by dktapps** [comment]
Thanks, we are indeed already aware of the problem. Work is currently in progress to reimplement crafting and to resolve this issue. Please be patient, and as always don't ask for ETAs. :)

**Comment by stormchaser3000** [comment]
i just tested the latest phar and crafting is still not fixed

**Comment by teracube** [comment]
i tested the latest phar PocketMineMP_1.7dev-75_38ec5da2_API-3.0.0-ALPHA8.phar 
i can craft on mcpe windows 10 but 2 errors appears (see attach file)

[errors.txt](https://github.com/pmmp/PocketMine-MP/files/1327503/errors.txt)

**Comment by dktapps** [comment]
there are problems with recipe-book crafting which I'm already aware of and working on.

**Comment by tribulant** [comment]
I installed PocketMine on one of my servers and connected to it using Minecraft PE and this issue still exists. Inventory items get uncrafted.
