### ISSUE TITLE
command usage error

### ISSUE THREAD

**Issue by skh6075** [pmmp/PocketMine-MP#4509]
### Issue description

- Expected result: I registered the command and wanted it to work normally when I use the command in the game.
- Actual result: The command registration and command are visible, but when you enter the command, an unknown command is displayed.

### Steps to reproduce the issue
1. Command registration
2. Enter the command after connecting to the client

### OS and versions

* PocketMine-MP: 4.0.0 BETA-6
* PHP: 8.0.11
* Using JIT: no
* Server OS: Window
* Game version: Win10

### Plugins

- If you remove all plugins, does the issue still occur?
- If the issue is **not** reproducible without plugins:
  - Have you asked for help on our forums before creating an issue?
  - Can you provide sample, *minimal* reproducing code for the issue? If so, paste it in the bottom section

### Crashdump, backtrace or other files

![image](https://user-images.githubusercontent.com/44698603/137610508-e3f080df-c389-4186-8a71-ffe2f5b88c14.png)
![image](https://user-images.githubusercontent.com/44698603/137610531-61b97d52-6b1b-42bd-98f8-da8c9c4c56ee.png)

**Comment by dktapps** [comment]
I've occasionally encountered this problem myself with core commands. I've yet to understand what's causing it.

**Comment by dktapps** [comment]
Never mind. Seems like the issue I encountered was console-specific. Since you closed this yourself, I assume you already found a problem in your plugin.

**Comment by skh6075** [comment]
This problem is that I cannot use this command if there is a space in the name in the command registration. my problem is right
