### ISSUE TITLE
Lanterns cannot be placed on all transparent blocks

### ISSUE THREAD

**Issue by Nerahikada** [pmmp/PocketMine-MP#4529]
### Issue description
Lanterns can be placed on some permeable blocks.
For example, it can place on certain surfaces of stairs or slabs.

### Steps to reproduce the issue
1. Place lanterns on glass

### OS and versions
* PocketMine-MP: 63dfcc6
* reproduced at test.pmmp.io:19132

**Comment by Nerahikada** [comment]
This problem is not only seen in the lantern but also in some other blocks such as the bed.

**Comment by alvin0319** [comment]
The problem is caused by this code (in case of bed): https://github.com/pmmp/PocketMine-MP/blob/faad2365e2529d4bb6e86fcb26d6f46dc7ee93c9/src/block/Bed.php#L185

**Comment by dktapps** [comment]
That makes no sense. That would allow lanterns to be placed on blocks like tallgrass.

**Comment by dktapps** [comment]
Relates to #4856, fixed by #4886
