### ISSUE TITLE
Cocoa Beans don't call BlockGrowEvent

### ISSUE THREAD

**Issue by ColinHDev** [pmmp/PocketMine-MP#4533]
### Issue description
As cocoa beans are plants, they should call the BlockGrowEvent when they grow.

### Proof
https://github.com/pmmp/PocketMine-MP/blob/master/src/block/CocoaBlock.php#L97-#L99
https://github.com/pmmp/PocketMine-MP/blob/master/src/block/CocoaBlock.php#L120-#L122

### OS and versions
* PocketMine-MP:  4.0.0-BETA9+dev (git hash: c3768b997a835cc3bcc39627e0ef4d4d0ddab8e5-dirty)
* PHP: 8.0.10
* Using JIT: no
* Server OS: linux
* Game version: Win10

### Plugins
- This isn't a bug caused by a plugin.

**Comment by dktapps** [comment]
API change request template would have suited better.

**Comment by ColinHDev** [comment]
oops, I was unsure which I should choose

**Comment by dktapps** [comment]
This seems like an easy PR if anyone wants to try it.

**Comment by ColinHDev** [comment]
Can do, just didn't had time yesterday

**Comment by ColinHDev** [comment]
Resolved by https://github.com/pmmp/PocketMine-MP/pull/4536
