### ISSUE TITLE
 When using ray tracing, player skins turn black.

### ISSUE THREAD

**Issue by HePivnickiy** [pmmp/PocketMine-MP#4537]
Issue description
When using ray tracing, player skins turn black. Everything works fine in single player and on Nukkit servers.

Proof

![Minecraft 02 11 2021 20_10_07](https://user-images.githubusercontent.com/93609783/139913798-8dbf4c81-4be1-4fc7-b99f-122bad94fc6a.png)
![Minecraft 02 11 2021 20_10_01](https://user-images.githubusercontent.com/93609783/139913801-5a6743b8-9f8b-43c3-9cf2-fb17fee8498c.png)

OS and versions
PocketMine-MP: 3.23.1
PHP: 8.0
Using JIT: no
Server OS: linux
Game version: Win10

Plugins
no plugins

**Comment by HePivnickiy** [comment]
Pocketmine 4.0.0 does not have this problem, it is definitely not a client problem.

**Comment by dktapps** [comment]
That's interesting. There's no difference between them as far as skins are concerned, to my memory.
Did you test 1.18 on both PM3 and PM4?

**Comment by HePivnickiy** [comment]
No, I used client version 1.17.30.4, now I will check for 1.18

**Comment by HePivnickiy** [comment]
At 1.18 everything is still

Screenshot from Pocketmine 3.0.0 - https://i.ibb.co/2jFx20d/Minecraft-01-12-2021-0-21-02.png

Screenshot from Pocketmine 3.0.0 - https://i.ibb.co/2qZLMxG/Minecraft-01-12-2021-0-22-14.png

**Comment by dktapps** [comment]
Thanks, I'll investigate this soon. I have no idea why there would be a difference between the two versions, but there must be some reason why ...

**Comment by HePivnickiy** [comment]
OK, thank you
