### ISSUE TITLE
Can't replace/broke block at somewhere

### ISSUE THREAD

**Issue by Xiaoming0313883** [pmmp/PocketMine-MP#4539]
### Issue description
- Can't replace/broke block at somewhere

### OS and versions

* PocketMine-MP: 3.25.2
* PHP: 8.0
* Server OS: window 10

### Plugins
- I test it without any plugin

Here have the file that I used to test it, I tried install the latest core, bin and build the server again but the bug still have ;-;
File
[server.zip](https://github.com/pmmp/PocketMine-MP/files/7465289/server.zip)
Video
https://player.vimeo.com/video/641775291?h=872033a94d&amp

**Comment by dktapps** [comment]
You have spawn protection enabled.
