### ISSUE TITLE
Inconsistency when cancelling growth of plants with fertilizers

### ISSUE THREAD

**Issue by ColinHDev** [pmmp/PocketMine-MP#4545]
## Description
Right now, it is not consistent in pm's code, whether one fertilizer should be removed when trying to grow a plant, even if the BlockGrowEvent / StructureGrowEvent is cancelled.

- Fertilizer is removed even if the event is cancelled:
  - https://github.com/pmmp/PocketMine-MP/blob/master/src/block/Crops.php#L81#L85
  - https://github.com/pmmp/PocketMine-MP/blob/master/src/block/Sapling.php#L80#L82
  - https://github.com/pmmp/PocketMine-MP/blob/master/src/block/Sugarcane.php#L85#L89
  - https://github.com/pmmp/PocketMine-MP/blob/master/src/block/SweetBerryBush.php#L100#L104

- Fertilizer is not removed if the event is cancelled:
  - https://github.com/pmmp/PocketMine-MP/blob/master/src/block/Bamboo.php#L148#L154
  - https://github.com/pmmp/PocketMine-MP/blob/master/src/block/BambooSapling.php#L76#L77
  - https://github.com/pmmp/PocketMine-MP/blob/master/src/block/CocoaBlock.php#L98#L99

## Justification
We should decide whether fertilizers should be removed, even if the event was cancelled, and change it in all upper classes to remove this inconsistency.

**Comment by ColinHDev** [comment]
I am pretty sure, we don't want to blame anyone for that!
(Actually my bad in CocoaBlock class (https://github.com/pmmp/PocketMine-MP/commit/ead8ccf08d3d3792224795728d225e949f33ab9f) and partly my fault in Bamboo and BambooSapling class because of how I implemented StructureGrowEvent (1https://github.com/pmmp/PocketMine-MP/commit/4189fbdaefd5f73485b64c0cc9509d8ad0479f5f))

**Comment by dktapps** [comment]
I think the intuitive behaviour would be not to remove it. If we signal BlockGrow/StructureGrow as the result of fertilisation, it follows that cancelling the fertilisation would refund the fertiliser.

**Comment by ColinHDev** [comment]
Yes, was also my idea, that's why it doesn't get removed when growing cocoa beans.
I hadn't looked at the other plant classes for that.

**Comment by ColinHDev** [comment]
Since PRs shouldn't be too crowded: Would it be a good idea to split these changes into separate PRs?
Sometimes, like in the Crops class, you only need to change a few lines (https://github.com/pmmp/PocketMine-MP/blob/master/src/block/Crops.php#L81#L85), while you would need to remake some parts of the `Sapling::grow()` method to let it return a bool instead of nothing (https://github.com/pmmp/PocketMine-MP/blob/master/src/block/Sapling.php#L111)

**Comment by dktapps** [comment]
All the changes have the same single goal, so they should be together.
