### ISSUE TITLE
On-the-fly block light updating has serious performance issues

### ISSUE THREAD

**Issue by dktapps** [pmmp/PocketMine-MP#456]
### Issue description
Many people will have noticed the crazy numbers on timings next to UseItemPacket and RemoveBlockPacket. This is due to synchronous on-the-fly block light updates when light-emitting blocks are placed or removed.

I added timings locally to monitor the extent of the time taken to execute Level->setBlock() and do lighting updates. An example timings report can be seen [here](https://timings.imgcl.co/?url=24240666). While these timings were being executed I placed and removed maybe half-a-dozen torches in a flat world.

Raw timings results on my machine showed that on average, placing a torch with no nearby light sources caused the server to spend ~90ms updating nearby block light, and ~50ms removing block light.

Based on other timings results I believe it may actually be significantly faster to fast-serialize up to 9 adjacent chunks and perform these operations in an AsyncTask. 

### Steps to reproduce the issue

1. place or remove any light-emitting block
2. see CPU spike on that tick

### OS and versions

* PocketMine-MP: https://github.com/pmmp/PocketMine-MP/pull/454 with local additions to add timings for setBlock and lighting updates
* PHP: 7.0.16
* Server OS: w10
* Game version: not relevant

**Comment by madecode15** [comment]
This may be related, but on my build server CPU starts to get leaked the more my builders build with just 1-5 players. The load will increase from 2% to 30% and not go down even when all the builders leave. I'll try to get a timings report of it though it seems somewhat related to this. It happens gradually, meaning the load increases slowly and usually by the time the server has been on for an hour. It only happens if blocks are being placed whiten the servers session.

**Comment by dktapps** [comment]
@madecode15 that's unlikely to be related to this issue, this issue outlines the reason for temporary lag spikes when building. A consistent CPU leak is something else. If you can get timings of it, that would be great.

**Comment by dktapps** [comment]
While working on liquids recently (in #1753) I observed that water and lava flow setting blocks and directly triggering on-the-fly lighting updates has a huge impact on the performance. Since these lighting updates are often overwriting the light updates of previous light updates executed on the fly on the same tick, this is a huge waste of performance.

This would be better achieved by aggregating positions needing light updates and then execute a light update chunk by chunk with several light sources set.

**Comment by dktapps** [comment]
Using a batched on-tick approach would also expose the possibility to perform asynchronous runtime lighting updates on a chunk.
