### ISSUE TITLE
Call to a member function addEntityMovement() on null

### ISSUE THREAD

**Issue by JackNoordhuis** [pmmp/PocketMine-MP#457]
### Issue description
I just updated my server to start using PMMP and within minutes of disabling the movement checks this crash occurred, now the server won't run for more than 10 minutes without crashing.

### Steps to reproduce the issue
1. Disable the movement checks (pocketmine.yml player.allow-movement-cheats)
2. Let a few players join your server
3. Wait for it to crash ;D

### OS and versions
* PocketMine-MP version: 1.6.2dev #0 [Protocol 102; API 3.0.0-ALPHA4]
* Git commit: 96801be3d3ea8876c503f8cacbad3ff15b284e68
* PHP Version: 7.0.3
* Zend version: 3.0.0
* OS : Linux, linux

### Crashdump, backtrace or other files
* https://gist.github.com/JackNoordhuis/fe75b6f008531c785642bffc7dd9666b

**Comment by dktapps** [comment]
Is this crash reproducible without plugins?

**Comment by JackNoordhuis** [comment]
@dktapps Not sure. I've since figured out that a related error can be reproduced through a plugin though: `24.03 18:30:40 [Server] Server thread/CRITICAL Could not execute task duels\duel\DuelCountdown: Call to a member function getSafeSpawn() on null`

**Comment by dktapps** [comment]
```
        "Components": {
            "name": "Components",
            "version": "0.1.0_ALPHA",
            "authors": [
                "Jack Noordhuis"
            ],
            "api": [
                "3.0.0-ALPHA4",
                "3.0.0-ALPHA5",
                "3.0.0-ALPHA6",
                "3.0.0-ALPHA7",
                "3.0.0-ALPHA8",
                "3.0.0-ALPHA9",
                "3.0.0-ALPHA10",
                "3.0.0-ALPHA11",
                "3.0.0-ALPHA12"
            ],
            "enabled": true,
            "depends": [],
            "softDepends": [],
            "main": "\\core\\Main",
            "load": "STARTUP",
            "website": null
        },
        "Duels": {
            "name": "Duels",
            "version": "0.0.9_ALPHA",
            "authors": [
                "Jack Noordhuis"
            ],
            "api": [
                "3.0.0-ALPHA4",
                "3.0.0-ALPHA5",
                "3.0.0-ALPHA6",
                "3.0.0-ALPHA7",
                "3.0.0-ALPHA8",
                "3.0.0-ALPHA9",
                "3.0.0-ALPHA10",
                "3.0.0-ALPHA11",
                "3.0.0-ALPHA12"
            ],
            "enabled": true,
            "depends": [],
            "softDepends": [],
            "main": "duels\\Main",
            "load": "POSTWORLD",
            "website": null
        }
```
:facepalm:

**Comment by JackNoordhuis** [comment]
Shhh, I'm too lazy to bump the API on every plugin every time the source does it ;p

**Comment by madecode15** [comment]
@JackNoordhuis -.- The API version exists for a reason. What is the point of it if you just add all the versions? It is to protect your server if breaking API changes are made. You completely defeated the purpose of it.

**Comment by dktapps** [comment]
I'm giving consideration to removing the capability to specify multiple API versions.

> because realistically speaking it doesn't do anything on stable API anyway, because minor versions are supposed to retain backwards compatibility anyway.
> And for major API bumps and betas it just provides a dangerous way to sit on both sides of the fence

but of course, many people won't like that and will turn to spoons instead.

**Comment by JackNoordhuis** [comment]
@madecode15 You really think I'd update the software on production servers without testing to make sure everything works first 🤦‍♂️ 

@dktapps People who know what they're doing shouldn't have to worry about bumping an API version in a file that practically never gets touched.

**Comment by dktapps** [comment]
yeah, and that's exactly my point... 99% of people _don't_ know what they are doing. They just are too lazy to open a text editor and edit one damn number. It's ridiculous.

**Comment by jasonwynn10** [comment]
That got off-topic quickly...

**Comment by dktapps** [comment]
I either need reproducing code or a way to reproduce this without plugins, since I have never encountered this issue.

I can theorize why this could be happening - I'd hazard a guess at some issue with PlayerQuitEvent and/or leaked Player objects. 

If you're holding strong refs to players - well, for a start I _definitely_ don't advise that, as you'll leak a significant amount of memory when said players quit - but regardless, make sure you check `player->closed === false` before doing anything with referenced players.

**Comment by ExaSonit** [comment]
I had the same problem yesterday, it was enough to re-download the "Player" file to resolve.

**Comment by dktapps** [comment]
Any update on this?

**Comment by Muqsit** [comment]
@dktapps I occasionally get `addParticle() on null` (Arrow.php, line 59) error on the console when players fire arrows.
Relatable.

**Comment by ExaSonit** [comment]
Halso

**Comment by dktapps** [comment]
@Muqsit #443

**Comment by JackNoordhuis** [comment]
@dktapps Pretty sure it was a memory leak caused by a plugin. I've since fixed the cause and forgotten about this issue :P
