### ISSUE TITLE
Torches cannot be placed on top of some blocks

### ISSUE THREAD

**Issue by dktapps** [pmmp/PocketMine-MP#458]
### Issue description
Torches cannot be placed on any transparent block other than fences or cobblestone walls.
http://minecraft.gamepedia.com/Torch#Placement

### Steps to reproduce the issue

1. place glass block
2. place a torch on top of it

### OS and versions

* PocketMine-MP: #454
* PHP: 7.0.16
* Server OS: w10
* Game version: Win10

**Comment by flaxues** [comment]
Beds also can't be placed on slabs

**Comment by thebigsmileXD** [comment]
Effects:

- [ ] Flowers
- [ ] Mushrooms
- [ ] Torches
- [ ] Redstone-Torches
- [ ] Signs
- [ ] Pressure plates
- [ ] Flower Pots

**Comment by jasonwynn10** [comment]
I don't think beds can be placed on beds in vanilla anyway @Matthww

**Comment by dktapps** [comment]
Relates to #4856, fixed by #4886
