### ISSUE TITLE
Crash Bug

### ISSUE THREAD

**Issue by jibixyt** [pmmp/PocketMine-MP#4582]
### Steps to reproduce the issue
1. Open your creative inventory
2. Click on search
3. Scroll down under the Potions

**Comment by dktapps** [comment]
⚠️ This issue ticket doesn't have all the required information ⚠️ 
To make it as quick and easy as possible for maintainers to fix your problem, an issue template is provided which lists certain required information. This includes (but is not limited to):

- PocketMine-MP version (use the `version` command)
- PHP version
- Minecraft version and/or edition
- List of all plugins used (use the `plugins` command)

Without this information, your problem cannot begin to be investigated, so the issue will be closed. You may amend this one, or create a new one, providing all the required information using one of the provided [issue templates](https://github.com/pmmp/PocketMine-MP/issues/new/choose).

Help us to help you by providing the information we ask for.
