### ISSUE TITLE
[Bug-PM4] add player effect visble

### ISSUE THREAD

**Issue by FlxiBoy1313** [pmmp/PocketMine-MP#4584]
### Issue description

- If I add an effect to a player that he does not see the effects either.
- I have turned off visble, but the player gets it anyway.

### Steps to reproduce the issue
1. Take a plugin, or the command / effect
2. Enter an effect and go as far as visible

### OS and versions

* PocketMine-MP: 4.0.0-BETA12
* PHP: 8.0.12
* Using JIT: no
* Server OS: win
* Game version: Win11

### Plugins
Multiworld, FormAPI, BuilderTools, DevTools, 2x my plugins

- If you remove all plugins, does the issue still occur?
   Yes

### Crashdump, backtrace or other files
- No crahses

### Pictures
![image](https://user-images.githubusercontent.com/65186341/142672121-a3a7f785-3e94-41e1-b53f-67cd256d2199.png)
If I bet true back there, it won't work either.

**Comment by dktapps** [comment]
I'm not sure what you're expecting here. The effect icon will still show regardless. `visible` merely controls whether the particles are shown or not.

**Comment by FlxiBoy1313** [comment]
Yes, that's right, sorry, I meant the particles
