### ISSUE TITLE
Player->kick() and /kick do not show kick reason.

### ISSUE THREAD

**Issue by Cosmic5173** [pmmp/PocketMine-MP#4588]
### Issue description

- Expected result: When a player is kicked via /kick or ``Player->kick()`` the reason specified should show on the disconnect screen.
- Actual result: Only the message ``Disconnected from Server`` appears.

### Steps to reproduce the issue
/kick <reason>
Player->kick(<reason>)

```php
class Main extends PluginBase {

    protected function onEnable(): void {
        $this->getServer()->getPluginManager()->registerEvents(new class() implements Listener {
            public function onJoin(PlayerJoinEvent $event): void {
                $event->getPlayer()->kick("This is a test kick, can you see me?");
            }
        }, $this);
    }
}
```

### OS and versions

* PocketMine-MP: 4.0.0-BETA12
* PHP: 8.0.12
* Using JIT: no
* Server OS: Linux
* Game version: Win10

### Plugins

- If you remove all plugins, does the issue still occur? Yes

**Comment by dktapps** [comment]
This has already been fixed in latest master.
