### ISSUE TITLE
No animation when hitting the air

### ISSUE THREAD

**Issue by GanniDEV** [pmmp/PocketMine-MP#4598]
### Issue description

- Expected result: Animation of the hit when hitting the air
- Actual result: No animation is performed

### Steps to reproduce the issue
1. Hit air

### OS and versions

* PocketMine-MP: 4.0.0-BETA13+dev
* PHP: 8.0.12
* Using JIT: no
* Server OS: Linux
* Game version: Win10

### Plugins
n/a

- If you remove all plugins, does the issue still occur? yes
- If the issue is **not** reproducible without plugins:
  - Have you asked for help on our forums before creating an issue? yes
  - Can you provide sample, *minimal* reproducing code for the issue? no

**Comment by dktapps** [comment]
This is expected. No action is bound to left-clicking, so there's nothing for the server to react to short of the client's own animation packets. We don't handle those because it allows abuse. This is a sacrifice that I'm willing to make.

**Comment by GanniDEV** [comment]
which has just been created, I didn't add any plugin on it, if it comes from me then I don't understand, but I would like to know if it comes from pm4 or not (I tested on 2 different vps)

**Comment by GanniDEV** [comment]
Just hit a player
