### ISSUE TITLE
Cooldown on hit

### ISSUE THREAD

**Issue by GanniDEV** [pmmp/PocketMine-MP#4599]
### Issue description

When I hit a player, there is a very very minimal cooldown, but it is quite disturbing, it feels like the knockback is not fluid. It's very disturbing for the fights, it's a bug that I don't have on pm3 (0 plugins on server)

### Steps to reproduce the issue
1. 

### OS and versions

* PocketMine-MP: 4.0.0-BETA13+dev
* PHP: 8.0.12
* Using JIT: No
* Server OS: Linux
* Game version: Win10

### Plugins

- If you remove all plugins, does the issue still occur? No
- If the issue is **not** reproducible without plugins:
  - Have you asked for help on our forums before creating an issue? Yes

**Comment by dktapps** [comment]
I can't do anything without reproducing information.

**Comment by GanniDEV** [comment]
Just hit a player, which has just been created the server, I didn't add any plugin on it, if it comes from me then I don't understand, but I would like to know if it comes from pm4 or not (I tested on 2 different vps)

**Comment by dktapps** [comment]
I can't reproduce this (knockback is equally bad on PM3 and PM4 both for me and others I just tested with on test.pmmp.io).

Test it for yourself if you want: `test.pmmp.io:19132` (PM4) and `test.pmmp.io:19133` (PM3).

If you can reproduce it on those servers, please send videos to demonstrate what the difference is.
