### ISSUE TITLE
Touch a block in end world, this break lots of block like brush

### ISSUE THREAD

**Issue by SPMP2** [pmmp/PocketMine-MP#4608]
### Issue description

- Expected result: What were you expecting to happen?
- Actual result: What actually happened?

### Steps to reproduce the issue
1. Touch block on end...
2. ...

### OS and versions

* PocketMine-MP:
* PHP:
* Using JIT: yes/no (delete as appropriate) 
* Server OS:
* Game version: Android/iOS/Win10/Xbox/PS4/Switch (delete as appropriate)

### Plugins

- If you remove all plugins, does the issue still occur?
- If the issue is **not** reproducible without plugins:
  - Have you asked for help on our forums before creating an issue?
  - Can you provide sample, *minimal* reproducing code for the issue? If so, paste it in the bottom section

**Comment by dktapps** [comment]
⚠️ This issue ticket doesn't have all the required information ⚠️ 
To make it as quick and easy as possible for maintainers to fix your problem, an issue template is provided which lists certain required information. This includes (but is not limited to):

- PocketMine-MP version (use the `version` command)
- PHP version
- Minecraft version and/or edition
- List of all plugins used (use the `plugins` command)

Without this information, your problem cannot begin to be investigated, so the issue will be closed. You may amend this one, or create a new one, providing all the required information using one of the provided [issue templates](https://github.com/pmmp/PocketMine-MP/issues/new/choose).

Help us to help you by providing the information we ask for.

**Comment by SPMP2** [comment]
Are you disabled man? No need to give you anithing !!! Ok to make you happy. 
API 3.26.1 
PLUGINS: 1 : MULTIWORLD 
TO REPRODUCE THIS BUG GO ON NETHER / END AND TOUCH A BLOCK , BLOCKS ARE REMOVED (5 BLOCK REMOVED)  (LIKE A BRUSH OF BLOCKSNIPER)

**Comment by xRedemption** [comment]
1. dimensions isn't supported by pocketmine
2. it happens on other dimensions when you click a block it just removes it client side

**Comment by SPMP2** [comment]
Any solution?
