### ISSUE TITLE
Bug Report

### ISSUE THREAD

**Issue by CarpeSurGitHub** [pmmp/PocketMine-MP#4612]
### Issue description

You can place redstone dust on a redstone dust like if it was an carpet. 
You take fall damage at 2 blocks but it's 3 in the game.

### OS and versions
* PocketMine-MP: 4.0.0
* PHP: 8
* Using JIT: yes/no (delete as appropriate) 
* Server OS:
* Game version: Win10

### Plugins
no plugins

**Comment by dktapps** [comment]
Don't report two bugs in one issue.
