### ISSUE TITLE
Consider using PoweredByRedstoneTrait for all solid/opaque.

### ISSUE THREAD

**Issue by NTT1906** [pmmp/PocketMine-MP#4615]
## Description
So in **Minecraft (Bedrock)**, all the opaque blocks aka solid blocks (not including transparent blocks) can be powered but in the current pmmp, they don't like that, I wonder if everyone is waiting to design the complete set of traits?

## Justification
Well, this could be made without modifying the server software but native features are better in general and I don't want to add it to every in-game solids block. If there is any way around it, please let me know. Thank you!

**Comment by NTT1906** [comment]
also, the blocks that are being powered are called soft power to split it from normal power.

**Comment by dktapps** [comment]
opaque != solid, there's a reason it was renamed.

PoweredByRedstoneTrait is solely intended to fill in blockstate properties for blocks that have such flags. Using it for opaque blocks would not be appropriate since those are weakly powered.

**Comment by NTT1906** [comment]
> opaque != solid, there's a reason it was renamed.
> 
> PoweredByRedstoneTrait is solely intended to fill in blockstate properties for blocks that have such flags. Using it for opaque blocks would not be appropriate since those are weakly powered.
> weakly powered.
soft powered?

**Comment by NTT1906** [comment]
okay, so i should check all the side of that block and cause redstone update?
