### ISSUE TITLE
Method 'init' not found in \pocketmine\inventory\CreativeInventory

### ISSUE THREAD

**Issue by GrosserZak** [pmmp/PocketMine-MP#4616]
### Issue description

The method CreativeInventory::init() has not been added in the release but the changelog says the opposite

  - `Item::initCreativeItems()` -> `CreativeInventory::init()`

**Comment by AkmalFairuz** [comment]
Method init is implemented

**Comment by dktapps** [comment]
The equivalent would be `CreativeInventory::reset()`, but note that the behaviour is not quite the same - it doesn't actually reinitialize until you next call `CreativeInventory::getInstance()`.
