### ISSUE TITLE
Vanilla commands are case-sensitive

### ISSUE THREAD

**Issue by TheDiamondYT1** [pmmp/PocketMine-MP#462]
### Issue description
Vanilla commands arent automatically converted to lowercase. For example /Op *wont* work but /op *will*.

### Steps to reproduce the issue
1. Download latest build
2. Execute any command but with a capital (e.g. /vErsion)

### OS and versions

* PocketMine-MP: https://github.com/pmmp/PocketMine-MP/commit/5926bab32389bde976a3d2c151777c2e90f3c4a0

### Possible fix
In tne command executing code in the player class, check if the command is an instance of VanillaCommand and use `strtolower` . (By checking if its an instance of VanillaCommand we make all vanilla  commands lowercase, but not plugin commands)

**Comment by dktapps** [comment]
This is not a bug, as commands are case-sensitive across the board. 

However I do note that registering a core command with a mixed- or uppercase name will not be correctly executed when used in that case.

**Comment by TheDiamondYT1** [comment]
Oh yeah, even on vanilla. This just seemed like a bug to me.
