### ISSUE TITLE
TNT Works Incorrectly.

### ISSUE THREAD

**Issue by NFGamerMC** [pmmp/PocketMine-MP#463]
### Issue description

Today I was removing parts of my server with TNT and when I blew up something in the sky it would drop the exploded blocks in the ground while when you are in a local world it just removes the blocks as they were exploded,

### Actual result: What actually happened?
 I was expecting it to remove the blocks and not just make them fall onto the ground as items.

### Steps to reproduce the issue

1. Make a tower in the sky
2. Blow it up and see blocks falling

### OS and versions

* PocketMine-MP: PocketMine-MP_1.6.2dev-24_34f833fa_API-3.0.0-ALPHA4
* PHP: 7.0.0
* Server OS: Ubnutu 16
* Game version: PE (delete as appropriate)

### Crashdump, backtrace or other files

* irrelevant

### Demo
* https://ibb.co/gojNGF

**Comment by dktapps** [comment]
This behaviour is intended, it behaves as it does in Pocket Edition survival, and as it does in PC. The only time TNT _doesn't_ produce drops, is in PE, when the world gamemode is set to creative. Since PocketMine doesn't have per-world gamemodes, this issue is invalid.

**Comment by Sandertv** [comment]
One thing to note though, is as far as I know, item entities don't bundle together. It may appear as if TNT drops blocks differently in PocketMine than in Vanilla PE, because in Vanilla PE the item entities bundle together.
