### ISSUE TITLE
Water Spreading

### ISSUE THREAD

**Issue by wrathxz** [pmmp/PocketMine-MP#4635]
### Issue description

In Vanilla Bedrock, water spreads all four ways when placed from a bucket. 
However, when you place it on Pocketmine, it only spreads 2/3 ways.

### Steps to reproduce the issue
1. I kept replacing water buckets in creative and survival.
2. Attempted various regions, and locations. Would not fall a forth way. 

### OS and versions
* PocketMine-MP: 4.0.2

**Comment by dktapps** [comment]
Actually it depends on the terrain.
