### ISSUE TITLE
Broken translation argument order

### ISSUE THREAD

**Issue by Unickorn** [pmmp/PocketMine-MP#4639]
### Issue description

The translation arguments for the game mode message seem to be broken.
I didn't have time or the will to look through files and/or submit a PR, so just dropping this in the issues.

- Expected result: Set TheDiablo660's game mode to Creative Mode
- Actual result: Set Creative Mode's game mode to TheDiablo660

### OS and versions

* PocketMine-MP: 4.0.1 (git hash: 036b90d2472ab317305d3724f69dc498d424e07c)
* PHP: 8.0.13
* Using JIT: no
* Server OS: linux

**Comment by dktapps** [comment]
I don't understand how this has happened again ...

Is this just in-game or on the console too?
