### ISSUE TITLE
Random->nextSignedFloat() returns a positive value from 0.0 - 2.0

### ISSUE THREAD

**Issue by CortexPE** [pmmp/PocketMine-MP#4646]
### Issue description

- Expected result: `Random->nextSignedFloat()` Returns a float between -1.0 and 1.0 (inclusive)
- Actual result: Unless subtracted `-1` after the function call, the range is actually 0.0 - 2.0

### OS and versions
* PocketMine-MP: 3.0.0+ and 4.0.0+, (possibly earlier versions after 32-Bit PM)
* PHP: 8.0.12
* Using JIT: no
* Server OS: Windows

### Plugins
A plugin or a world generator is needed to invoke the function, the following snippet may be used to produce a similar output below:
```php
$rnd = new Random(time());
for ($i = 0; $i < 10; $i++){
	var_dump($rnd->nextSignedFloat());
}
```

### Crashdump, backtrace or other files
```
float(0.29852969632415555)
float(0.43232020290210854)
float(1.309339682249976)
float(0.4176374564029451)
float(0.011033924767297658)
float(1.4331631215443663)
float(1.2559785234071215)
float(0.9514171718393533)
float(1.4906703999688244)
float(0.8924013901932172)

```

**Comment by dktapps** [comment]
⚠️ This issue ticket doesn't have all the required information ⚠️ 
To make it as quick and easy as possible for maintainers to fix your problem, an issue template is provided which lists certain required information. This includes (but is not limited to):

- PocketMine-MP version (use the `version` command)
- PHP version
- Minecraft version and/or edition
- List of all plugins used (use the `plugins` command)

Without this information, your problem cannot begin to be investigated, so the issue will be closed. You may amend this one, or create a new one, providing all the required information using one of the provided [issue templates](https://github.com/pmmp/PocketMine-MP/issues/new/choose).

Help us to help you by providing the information we ask for.

**Comment by CortexPE** [comment]
Issue description updated

**Comment by dktapps** [comment]
This is caused by #4645
