### ISSUE TITLE
Something strange with animations.

### ISSUE THREAD

**Issue by hausemaster3734** [pmmp/PocketMine-MP#4650]
### Issue description

- Expected result: Attacks should be shown all, like attacks in the air and a blow to the player. Also with sounds.
- Actual result: The server translates only attack animation and only when attack cooldown is ended, but not the rest, such as a blow to the air, the same with the sounds, they as if they were confused.

### Steps to reproduce the issue
1. Start the battle with another person on the server. Tell the opponent to record the process. Record too.
2. View two video, everything will be visible.

### OS and versions

* PocketMine-MP: 4.0.2
* PHP: 8.0
* Using JIT: No
* Server OS: Linux Mint

### Plugins

- None

### Crashdump, backtrace or other files
- None

**Comment by dktapps** [comment]
I don't understand the problem.

**Comment by hausemaster3734** [comment]
> I don't understand the problem.

Oh, sorry for my bad english. I will send video.

**Comment by hausemaster3734** [comment]
https://youtu.be/0X946ci1Og8 - Attacker.
https://youtu.be/XpXJbtULEzA - Victim.
Sorry for a long expectation.

**Comment by dktapps** [comment]
The victim video has no sound at all.

**Comment by hausemaster3734** [comment]
> The victim video has no sound at all.

More importantly, the fact that I am very quickly attacked by a sacrifice, and I saw a victim from my eyes, which I hit one attack, and not a bunch of attacks.

**Comment by hausemaster3734** [comment]
> > The victim video has no sound at all.
> 
> More importantly, the fact that I am very quickly attacked by a sacrifice, and I saw a victim from my eyes, which I hit one attack, and not a bunch of attacks.

If you do not understand me, I'll close the issue.

**Comment by dktapps** [comment]
I can see a difference in the rate of attacks, but I can't verify what you're saying about sounds.

**Comment by hausemaster3734** [comment]
> I can see a difference in the rate of attacks, but I can't verify what you're saying about sounds.

Alas, I do not know how to record video on my phone with sounds. But they are very different from vanilla.

**Comment by JavierLeon9966** [comment]
> > I can see a difference in the rate of attacks, but I can't verify what you're saying about sounds.
> 
> Alas, I do not know how to record video on my phone with sounds. But they are very different from vanilla.

Then try recording with the other device

**Comment by hausemaster3734** [comment]
> > > I can see a difference in the rate of attacks, but I can't verify what you're saying about sounds.
> > 
> > 
> > Alas, I do not know how to record video on my phone with sounds. But they are very different from vanilla.
> 
> Then try recording with the other device

Sorry, but I can't. Already changed the name.
