### ISSUE TITLE
Loading YML Config file - No error when malformated

### ISSUE THREAD

**Issue by benda95280** [pmmp/PocketMine-MP#4654]
### Issue description

- Expected result:
When loading an YML file malformed, it should throw an error when loaded
- Actual result:
It's like it is empty

### Steps to reproduce the issue
Use config.yml as : 
```
---
apiKey:"TEST" 
...
```
Use following code to get data :
```
        $this->saveDefaultConfig();
        $config = $this->getConfig();
        var_dump($config->get("apiKey"));
```
It return "False", without any error thrown

### OS and versions

* PocketMine-MP: PocketMine-MP version 4.0.2
* PHP: 8.0.13
* Using JIT: yes
* Server OS: W10 21H2
* Game version: Android/iOS/Win10/Xbox/PS4/Switch (delete as appropriate)

### Plugins

- If you remove all plugins, does the issue still occur? Yes
- If the issue is **not** reproducible without plugins:
  - Have you asked for help on our forums before creating an issue?
  - Can you provide sample, *minimal* reproducing code for the issue? If so, paste it in the bottom section

### Crashdump, backtrace or other files

No error at all

**Comment by dktapps** [comment]
This has the same underlying cause as #4628
