### ISSUE TITLE
The block is not placed if you put it on an interactive block

### ISSUE THREAD

**Issue by Gaprix** [pmmp/PocketMine-MP#4659]
### Issue description
If you try to place a block on a block with which you can interact, then it will only be placed on the client side 

- Expected result: The block has been placed
- Actual result: The block is placed only on the client side and disappears after clicking on it

### Steps to reproduce the issue
1. Place the door
2. Take a block of stone in your hand
3. Hold down the shift key
4. Try putting a stone on the door
5. The block is placed only on the client side

### OS and versions

* PocketMine-MP: 4.1.0+dev (git hash: 089f22d9030654a439a736802b89afdfb18236a1)
* PHP: 8.0.12
* Server OS: Win
* Game version: Win10

### Plugins
none

### Crashdump, backtrace or other files
https://youtu.be/cT-sz-PcUJw

**Comment by dktapps** [comment]
Can you test this in 4.0?

**Comment by Gaprix** [comment]
The bug is missing on version 4.0.2

**Comment by dktapps** [comment]
This is most likely caused by this change: 292827a311a8792718b6405975518ef923a47475

**Comment by Gaprix** [comment]
It's true

**Comment by Gaprix** [comment]
I found another consequence: https://youtu.be/ZxUycx6MXIw

**Comment by dktapps** [comment]
I've no idea what causes that.

**Comment by ColinHDev** [comment]
> This is most likely caused by this change: [292827a](https://github.com/pmmp/PocketMine-MP/commit/292827a311a8792718b6405975518ef923a47475)

This is caused by sneaking not being registered by the server any longer.
Therefore `Player::isSneaking()` will return false and the block interaction will take place. https://github.com/pmmp/PocketMine-MP/blob/next-minor/src/world/World.php#L1809
