### ISSUE TITLE
Dead coral appears as Tube Coral in Creative Mode

### ISSUE THREAD

**Issue by PocketMiner92** [pmmp/PocketMine-MP#4663]
### Issue description

- Expected result: What were you expecting to happen?
- Actual result: What actually happened?

### Steps to reproduce the issue
1. Choose Gamemode 1
2. Coral Blue 6 Times in Creative Mode

### OS and versions

* PocketMine-MP: 4.0.3
* PHP: 8.0.13
* Using JIT: no (delete as appropriate) 
* Server OS: Linux
* Game version: Android (delete as appropriate)

### Plugins

- Multiworld
- MyPlot
- TheSpawn
- PurePerms
- PureChat

- If you remove all plugins, does the issue still occur? Yes
- If the issue is **not** reproducible without plugins:
  - Have you asked for help on our forums before creating an issue?
  - Can you provide sample, *minimal* reproducing code for the issue? If so, paste it in the bottom section

**Comment by PocketMiner92** [comment]
![Screenshot_2021-12-18-11-28-39-13_5c8300b655012b1930f2e0a7b81bf6a9.jpg](https://user-images.githubusercontent.com/96331694/146637998-fd41d260-fa1c-41e5-a0e0-9becf9967b24.jpg)

**Comment by dktapps** [comment]
The duplicated ones would be dead coral, but those aren't representable according to the 1.12 states table (which is what PM currently uses).

**Comment by PocketMiner92** [comment]
OK thank you very much.
Pocketmine 4 is great.
Thanks for youre hard Work.
Have a Nice Day.

**Comment by dktapps** [comment]
This was fixed in PM5, probably by f24f2d9ca9efec495a652bf8d440c06a465c93d2
