### ISSUE TITLE
Long NBT tag causes server to hang

### ISSUE THREAD

**Issue by Gaprix** [pmmp/PocketMine-MP#4664]
### Issue description
If a player picks up an item with a long NBT tag, the server will freeze for a few seconds

- Expected result: Server does not freeze 
- Actual result: Server freezes while picking up an item

### Steps to reproduce the issue
1. Enter creative mode 
2. Place the chest
3. Copy it by pressing the mouse wheel and the control button
4. Put the received item in the chest
5. Repeat steps several times 
6. Break the chest
7. Pick up an item

### OS and versions

* PocketMine-MP: 4.0.3 (git hash: 795ebd182461f96beeb47b067f7fe33e76bc9059)
* PHP: 8.0.12
* Using JIT: no
* Server OS: win

### Plugins
none

### Crashdump, backtrace or other files
![изображение](https://user-images.githubusercontent.com/45711510/146650959-20a444e5-f446-4e3d-9fcd-cdddd0fb1c3a.png)
https://youtu.be/TfQ1w5yU2I8

**Comment by dktapps** [comment]
Related feature issue: pmmp/BedrockProtocol#56

**Comment by dktapps** [comment]
Should be fixed as of pmmp/BedrockProtocol@51f539997cda4f788fba74f0a03fd92b9a78175d
