### ISSUE TITLE
setMaxValue() on null.

### ISSUE THREAD

**Issue by Muqsit** [pmmp/PocketMine-MP#467]
### Issue description

I was expecting the zombie's max health value to change.
The server gave me a critical error instead.

### Steps to reproduce the issue

1. Spawn a zombie/living non-player
2. Log your console.

### OS and versions

* PocketMine-MP: 7a36d80
* PHP: 7.0.17
* Server OS: Ubuntu 14.04
* Game version: Win10

### Crashdump, backtrace or other files

* http://pastebin.com/MXW326u1
* http://pastebin.com/3VBwXZzh
* [A dump of zombie's $attributeMap](http://pastebin.com/Eec0GhHw)

**Comment by dktapps** [comment]
If I understood correctly, you simply spawned a zombie and this issue occurred? If so, I'm afraid I can't reproduce this.

**Comment by dktapps** [comment]
ah, I think I see your issue. You're using a custom Zombie class by my eyes. When your initEntity() is called, have you called `parent::initEntity()` before attempting to do this? If you haven't, the attribute map will not yet be initialized.

**Comment by Muqsit** [comment]
**My bad.**
That solves it up. I was trying to move my projects over from G-fork to here. All the mob classes had this:
```
    public function initEntity(){
        $this->setMaxHealth(20);
        parent::initEntity();
    }
```
Thanks <3
