### ISSUE TITLE
Throwing ender pearl while sleeping causes the client stopping interacting

### ISSUE THREAD

**Issue by matcracker** [pmmp/PocketMine-MP#4672]
### Issue description

- Expected result: the player continues to sleep without changing its position and it is able to interact, place or break blocks.
- Actual result: the player stops sleeping without changing its position but it is not able to interact, place or break blocks.

### Follow up
Requires some testing with teleport function while sleeping, I don't know what's happen.

### Steps to reproduce the issue
1. Place a bed and set night
2. Throw an ender pearl
3. Before the ender pear hits the ground, try to sleep
4. Enjoy!

### OS and versions

* PocketMine-MP: 4.0.3
* PHP: 8.0.13
* Using JIT: no
* Server OS: Linux
* Game version: Win10 (not tested in other platforms)

### Plugins

- If you remove all plugins, does the issue still occur?
- If the issue is **not** reproducible without plugins:
  - Have you asked for help on our forums before creating an issue?
  - Can you provide sample, *minimal* reproducing code for the issue? If so, paste it in the bottom section
 
Tried on PMMP Test Server

**Comment by hausemaster3734** [comment]
Vanilla:

https://user-images.githubusercontent.com/60012371/147383276-cc5b006b-39e8-4f6a-b75c-84e3a8f25af7.mp4

PMMP:

https://user-images.githubusercontent.com/60012371/147383281-5c5d39db-b75d-4b2a-9b24-6835b1d5e016.mp4
