### ISSUE TITLE
Teleporting during sleeping on bed causes player won't be able to receive an updated chunk

### ISSUE THREAD

**Issue by alvin0319** [pmmp/PocketMine-MP#4679]
### Issue description

- Expected result: What were you expecting to happen? Player will receive an updated chunk after teleporting to another world during sleeping on the bed.
- Actual result: What actually happened? Player won't receive an updated chunk after teleporting to another world during sleeping on the bed.

### Steps to reproduce the issue
1. Set up a PM4 server, you may need any multiworld plugin to reproduce this.
2. Sleep on the bed, and open a chat and try to teleport to another world.
3. then you'll see the player doesn't receive an updated chunk.

### OS and versions

* PocketMine-MP: 795ebd182461f96beeb47b067f7fe33e76bc9059
* PHP: 8.0.13
* Using JIT: no
* Server OS: Ubuntu 18.04
* Game version: 1.18.2

### Plugins

```
[01:24:46.834] [Server thread/INFO]: Plugins (2): DevTools v1.15.0+dev, MultiWorld v1.0.0
```

- If you remove all plugins, does the issue still occur? Yes

### Crashdump, backtrace or other files

https://user-images.githubusercontent.com/32565818/147517741-a199c1fb-d8c2-4dc2-9ddc-2bfbe974744b.mp4

**Comment by matcracker** [comment]
Related to #4672

**Comment by jasonw4331** [comment]
Closing in favor of #4672
