### ISSUE TITLE
/kill command doesn’t kill the player directly 

### ISSUE THREAD

**Issue by JavierLeon9966** [pmmp/PocketMine-MP#4680]
### Issue description

- Expected result: The player should directly die.
- Actual result: The player takes 500 hearts of damage.

### Steps to reproduce the issue
1. Give yourself max level (255) health boost or absorption with /effect
2. Execute /kill
3. Notice that you only took damage

### OS and versions

* PocketMine-MP: 4.0.0 (git hash: 468faa464b2bc5c97f23fafbb71ea61035f6f218)
* PHP: 8.0.12
* Using JIT: no 
* Server OS: linux
* Game version: iOS

### Plugins
This issue can be reproduced without plugins.

### Crashdump, backtrace or other files

https://user-images.githubusercontent.com/58715544/147520799-5e7c24a9-c2f0-4337-88c3-31653abbd7ad.mp4

**Comment by NTT1906** [comment]
In Vanilla Bedrock, **/kill** don't kill/despawn anything directly, it just gives that entity a bunch of damage

at least, that was what I remembered...

**Comment by Xd-pro** [comment]
> In Vanilla Bedrock, **/kill** don't kill/despawn anything directly, it just gives that entity a bunch of damage
> 
> at least, that was what I remembered...

No, that's what Java Edition does and since PocketMine is designed around Java Edition's source this was implemented the same way.

**Comment by JavierLeon9966** [comment]
> > In Vanilla Bedrock, **/kill** don't kill/despawn anything directly, it just gives that entity a bunch of damage
> > at least, that was what I remembered...
> 
> No, that's what Java Edition does and since PocketMine is designed around Java Edition's source this was implemented the same way.

Java Edition made the /kill command directly kill entities since 1.8 (14w02c). You can check the /kill command history in the wiki:
https://minecraft.fandom.com/wiki/Commands/kill?so=search#History

**Comment by dktapps** [comment]
What vanilla does in any edition is irrelevant to the issue at hand.
