### ISSUE TITLE
Whitelist doesn't work

### ISSUE THREAD

**Issue by alvin0319** [pmmp/PocketMine-MP#4682]
### Issue description

- Expected result: What were you expecting to happen? when whitelist is turned on, the player who is not in the whitelist cannot join
- Actual result: What actually happened? The player who is not in the whitelist still can join

### Steps to reproduce the issue
1. make a fresh PM4 server
2. turn on whitelist, and join the server

### OS and versions

* PocketMine-MP: 795ebd182461f96beeb47b067f7fe33e76bc9059
* PHP: 8.0.13
* Using JIT: no
* Server OS: Ubuntu 18.04
* Game version: Android/iOS/Win10/Xbox/PS4/Switch (delete as appropriate)

### Plugins
```
[00:57:08.421] [Server thread/INFO]: Plugins (0):
```

- If you remove all plugins, does the issue still occur? Yes
- If the issue is **not** reproducible without plugins:
  - Have you asked for help on our forums before creating an issue?
  - Can you provide sample, *minimal* reproducing code for the issue? If so, paste it in the bottom section

### Crashdump, backtrace or other files
![image](https://user-images.githubusercontent.com/32565818/147713473-0cda7916-b96b-44da-a5ba-20641999bb87.png)

**Comment by dktapps** [comment]
Opped players can always join, regardless of whether they are whitelisted or not.

**Comment by ghost** [comment]
After restart whitelist stops working.

**Comment by ethaniccc** [comment]
> After restart whitelist stops working.

You should open a new issue for that with relevant information (the reported issue is different from the one you're reporting)
