### ISSUE TITLE
Cant Start Pocketmine

### ISSUE THREAD

**Issue by BintangPutra606** [pmmp/PocketMine-MP#469]
Im Using The Latest Unleashed "ALPHA4" Release Of Pocketmine And PHP 7.03 But When I Try To Start With 

> ./start.sh

It Says

> ./start.sh: line 54: /root/PocketMine-MP-1.6.2dev-3.0.0-ALPHA4/bin/php7/bin/php: No such file or directory

### OS and versions
* PocketMine-MP: PocketMine-MP 1.6.2dev "Unleashed" with API 3.0.0-ALPHA4
* PHP: 7.0.3
* Server OS: Ubuntu 16.04
* Game version: PE/Win10 (BOTH)

**Comment by dktapps** [comment]
Setup issue. This is not a support forum, read the README.
