### ISSUE TITLE
Creative Inventory causing Client Crash

### ISSUE THREAD

**Issue by kallyluv** [pmmp/PocketMine-MP#4698]
### Issue description

- Expected result: What were you expecting to happen?
- Actual result: What actually happened?

### Steps to reproduce the issue
1. Open Creative Inventory
2. Click on the bed icon or island icon OR scroll down a little over halfway in search tab

### OS and versions

* PocketMine-MP: 4.0.4
* PHP: 8
* Using JIT: No
* Server OS: Windows 10
* Game version: Windows 10

### Plugins

- If you remove all plugins, does the issue still occur?
Yes
- If the issue is **not** reproducible without plugins:
  - Have you asked for help on our forums before creating an issue?
\> No, this issue is clearly internal and has happened on every PocketMine-MP server I have run, even completely default ones.
  - Can you provide sample, *minimal* reproducing code for the issue? If so, paste it in the bottom section

**Comment by kallyluv** [comment]
### Further Information
This is reproducible on any device, no errors show in the console with or without debug logs showing. Not reproducible in vanilla worlds

**Comment by Giulizo** [comment]
Hi xJustJqy,

I would be happy to help you with your request.

If you are using a proxy, then as far as I know you have to activate "enable_edu_features" in the configuration file there.
Thus, the inventory should no longer crash.

I hope that I can help you with this.

Best regards
Giulizo

**Comment by dktapps** [comment]
I can't reproduce this, but this is a known issue caused by WDPE.

**Comment by kallyluv** [comment]
> Hi xJustJqy,
> 
> I would be happy to help you with your request.
> 
> If you are using a proxy, then as far as I know you have to activate "enable_edu_features" in the configuration file there. Thus, the inventory should no longer crash.
> 
> I hope that I can help you with this.
> 
> Best regards Giulizo

Thank you very much, I don't know why I never looked to my proxy for answers.
