### ISSUE TITLE
Fall damage when landing in 1 block deep water

### ISSUE THREAD

**Issue by dktapps** [pmmp/PocketMine-MP#470]
Will add the tl;dr later.

**Comment by Smarticles101** [comment]
This occurs with lava as well

**Comment by jasonwynn10** [comment]
I suppose that this is with all liquids then

**Comment by Smarticles101** [comment]
I don't think so @jasonwynn10 I just tested all the blocks that are meant to reset fall distance and all of them have the same effect.  The one thing I noticed that was different is that I still take damage when falling onto 2 blocks deep vines.  I think that could related to the fact that upon collision with a ladder, 
 `$entity->onGround = true;` is executed.
