### ISSUE TITLE
Allow entity registration via short function(fn)

### ISSUE THREAD

**Issue by xxAROX** [pmmp/PocketMine-MP#4703]
### Error
Declaration of callable `function ( pocketmine\world\World $world, pocketmine\nbt\tag\CompoundTag $nbt )` must be compatible with `function ( pocketmine\world\World $world, pocketmine\nbt\tag\CompoundTag $nbt ) : pocketmine\entity\Entity`

### My code
```php
EntityFactory::getInstance()->register(BlockEntity::class, fn (World $world, CompoundTag $nbt) => new BlockEntity(EntityDataHelper::parseLocation($nbt, $world), FallingBlock::parseBlockNBT(BlockFactory::getInstance(), $nbt)), ["xxarox:custom_falling_block"]);
```

**Comment by CortexPE** [comment]
it does work, you forgot to set a return type... use `fn(World $world, CompoundTag $nbt): BlockEntity =>`

**Comment by dktapps** [comment]
Arrow function shouldn't need a return type. It can be inferred from the return value.

**Comment by xxAROX** [comment]
ahh lol, thanks
