### ISSUE TITLE
$tile->setText(new signText()) has a problem

### ISSUE THREAD

**Issue by Shehab99** [pmmp/PocketMine-MP#4705]
### Issue description

- Expected result: What were you expecting to happen?
I used 
$tile = $this->getServer()->getWorldManager()->getDefaultWorld()->getTileAt($c->get("1= signx"), $c->get("1= signy"), $c->get("1= signz"));
                                    $tile->setText(new SignText(["1", "1", "house", "1"]));
And the sign's text did not change until i restart the server 

### Steps to reproduce the issue
1. ...
2. ...

### OS and versions

* PocketMine-MP:
* PHP:
* Using JIT: yes/no (delete as appropriate) 
* Server OS:
* Game version: Android/iOS/Win10/Xbox/PS4/Switch (delete as appropriate)

### Plugins

- If you remove all plugins, does the issue still occur?
- If the issue is **not** reproducible without plugins:
  - Have you asked for help on our forums before creating an issue?
  - Can you provide sample, *minimal* reproducing code for the issue? If so, paste it in the bottom section

**Comment by ipad54** [comment]
use this:

$world = $this->getServer()->getWorldManager()->getDefaultWorld();
$block = $world->getBlockAt($c->get("1= signx"), $c->get("1= signy"), $c->get("1= signz"));
if($block instanceof BaseSign) { 
$world->setBlock($block->getPosition(), $block->setText(new SignText(["1", "1", "house", "1"])));
}

**Comment by dktapps** [comment]
You're not supposed to use the tile. Use the block instead.
