### ISSUE TITLE
PlayerPreLoginEvent

### ISSUE THREAD

**Issue by ghost** [pmmp/PocketMine-MP#4709]
PlayerPreLoginEvent Line 48-53:

	public const KICK_REASON_PRIORITY = [
		self::KICK_REASON_PLUGIN, //Plugin reason should always take priority over anything else
		self::KICK_REASON_SERVER_FULL,
		self::KICK_REASON_SERVER_WHITELISTED,
		self::KICK_REASON_BANNED
	];
	
	But it is not possible to change the ban reason, i tried:
	
	public function onLogin(PlayerPreLoginEvent $event) {

        $bannedList = Server::getInstance()->getNameBans();
        $playerName = $event->getPlayerInfo()->getUsername();

        var_dump($playerName);
        var_dump($bannedList->isBanned($playerName));

        if ($bannedList->isBanned($playerName)) {
            $event->setKickReason(3, 'Test!'); //I also tried with Flag: 0
        }

    }

But i still recieve 'You are banned!' Reason...

**Comment by dktapps** [comment]
Stop hardcoding magic numbers ...

**Comment by dktapps** [comment]
This happens because you didn't use the `@handleCancelled` annotation on the event handler.

**Comment by ghost** [comment]
> This happens because you didn't use the `@handleCancelled` annotation on the event handler.

Okay, thank you!
