### ISSUE TITLE
Running in screen

### ISSUE THREAD

**Issue by Qhiliqq** [pmmp/PocketMine-MP#473]
### Issue description
If I run Pmine in a screen and stop the screen, Pmine is still online.

### Steps to reproduce the issue
Running the following command via screen:
./bin/php7/bin/php pocketmine.phar --memory-limit=1024M --disable-ansi --server-ip=xxx.xxx.xxx.xxx --server-port=19000

Kill the screen, and this is still online:
http://prntscr.com/ep5tre
The server is reachable at any time.

### OS and versions
* PocketMine-MP: PocketMine-MP_1.6dev-27_ef8227a0_API-2.0.0
* PHP: 7
* OS: Deb8

### Crashdump, backtrace or other files
none

**Comment by dktapps** [comment]
Ancient version. And you're killing the screen, _not_ the PocketMine process.
