### ISSUE TITLE
Effect problem

### ISSUE THREAD

**Issue by achedon12** [pmmp/PocketMine-MP#4730]
### Issue description

- Expected result: What were you expecting to happen?
Normally, there should be a gain in speed effect
- Actual result: What actually happened? It gives the effect for 1s instead of 20. 
It works for different effects but not for all, the duration makes the effect buggy (ex: speed, resistance)

### Steps to reproduce the issue
1. give a speed effect in new instance with a duration (it doesn't matter which one) and an amplification

### OS and versions

* PocketMine-MP:
* PHP:
* Using JIT: yes/no (delete as appropriate) 
* Server OS:
* Game version: Android/iOS/Win10/Xbox/PS4/Switch (delete as appropriate)

### Plugins

- If you remove all plugins, does the issue still occur?
Yes
- If the issue is **not** reproducible without plugins:
  - Have you asked for help on our forums before creating an issue?
  Yes
  - Can you provide sample, *minimal* reproducing code for the issue? If so, paste it in the bottom section
                 $player->getEffects()->add(new EffectInstance(VanillaEffects::SPEED(), 2147483647/2, 2, true));

**Comment by dktapps** [comment]
EffectInstance takes a duration argument in ticks.

**Comment by achedon12** [comment]
It still doesn't solve the problem. Try the code, and you'll see that it won't work

**Comment by dktapps** [comment]
I did try it. It works fine.
