### ISSUE TITLE
Can't sneak and walk beside chest

### ISSUE THREAD

**Issue by NguyenDuck** [pmmp/PocketMine-MP#4739]
### Issue description

- Expected result: Can move like Vanilla
- Actual result: Can't move

### Steps to reproduce the issue
1. Place a solid block
2. Place same bounding box of chest on solid block
3. Jump to beside the chest
4. Sneak and walk

### OS and versions
* PocketMine-MP: 4.0.6
* PHP: 8.0.13
* Using JIT: no
* Server OS: Linux
* Game version: 1.18.2
* Android
### Plugins
* No plugin installed

**Comment by dktapps** [comment]
I don't understand what you mean. Please provide videos comparing vanilla and PM for what you're talking about.

**Comment by NguyenDuck** [comment]
Vanilla
https://user-images.githubusercontent.com/83252725/150098421-6914934e-c736-4935-aaf2-357f00b58117.mp4

PMMP
https://user-images.githubusercontent.com/83252725/150098447-b7d2c17a-a08d-4eb9-974e-282d66a695d1.mp4

**Comment by dktapps** [comment]
I have no idea what would cause that. There shouldn't be any difference from vanilla.

**Comment by dktapps** [comment]
I'm able to reproduce this in vanilla too. I don't think the fault lies with PM.

You should consider reporting a bug on https://bugs.mojang.com instead.
