### ISSUE TITLE
Brewing stand has wrong collide box? Block has more type of boxes?

### ISSUE THREAD

**Issue by NTT1906** [pmmp/PocketMine-MP#4746]
### Issue description

- Expected result: Arrow/projectile got stuck at the select/pick-up boxes.
- Actual result: It goes through the select/pick-up boxes but stops at collision boxes.

In vanilla
![image](https://user-images.githubusercontent.com/54394881/150319840-15d508cc-a102-4e56-a209-e43707a73842.png) 

### Steps to reproduce the issue
1. Try throwing a trident or shooting an arrow, any projectile to brewing stand.
2. Try again in vanilla

### OS and versions
* PocketMine-MP: build from the current stable branch. After [BrewingStand: fixed collision box](https://github.com/pmmp/PocketMine-MP/commit/6679c53e56f4d23a96e41998d9e8dcacc1300cfa)
* PHP: 8.0
* Server OS: Window
* Game version: Win10 (1.18.2, 1.17.2 dev version, 1.16.30 dev version)

### Plugins
None
### Crashdump, backtrace, or other files
N/A
### Disparity between bedrock and PMMP:
In bedrock vanilla, there are multi-type of boxes included:
- Outline boxes: (Red /orange): unknown, maybe item collection? Both block, entity, and even player have these boxes. 
- Structure Bounding boxes (Green): mob spawning at a specific place
- Entity's bounding boxes (Blue): this is for contact with the block collision box, entity's hitbox?
- Block's collision boxes (Blue): this was made for dealing with contact collision, making block solid, entities cannot go through this.
- Select/pick-up boxes/ hitbox? (Black / Dark grey?): to interact with the block: destroy, get,...
- Second collision boxes (Yellow?):  this behaves in a strange way, it seems like this is for projectile collision... (Arrow got stuck when arrow both collide with this and pick-up boxes)
![image](https://user-images.githubusercontent.com/54394881/150320046-5096a67b-5aca-404d-be08-abdb104bdd1a.png)
![image](https://user-images.githubusercontent.com/54394881/150324745-34220fc6-f94e-4de8-aa89-016f1d62673d.png)
![image](https://user-images.githubusercontent.com/54394881/150324760-8e21c44e-e00d-4f3b-9cb3-52450c0d8f43.png)
![image](https://user-images.githubusercontent.com/54394881/150324808-1e306a18-f1d7-4d2b-81f6-12a94bcf83bf.png)
![image](https://user-images.githubusercontent.com/54394881/150324845-a2c0e6df-b264-4ae7-b0cd-07a2c7a1f974.png)
The arrow should fall down but it doesn't in vanilla
![image](https://user-images.githubusercontent.com/54394881/150324877-1919fca6-ed78-4bac-b014-4ef6bdacd561.png)
![image](https://user-images.githubusercontent.com/54394881/150324908-20f2b250-e6be-4b75-b046-c063f24d90ef.png)
![image](https://user-images.githubusercontent.com/54394881/150324936-0640f308-43c5-4345-9dca-cafd0160b954.png)
![image](https://user-images.githubusercontent.com/54394881/150324954-cb9bb3a7-b691-4b87-8cb0-5f0e05638916.png)
![image](https://user-images.githubusercontent.com/54394881/150324978-76c5a4e6-3da4-44c0-a553-4d9975f8551f.png)
Also, the overdraw line didn't render so those boxes showed up isn't really the real size of the box

In PMMP, there are only collisions boxes and bounding right ~~?

**Comment by NTT1906** [comment]
oh nvm, the issue was fixed but hopefully, you read the Disparity between bedrock and PMMP

**Comment by inxomnyaa** [comment]
https://github.com/pmmp/PocketMine-MP/commit/6679c53e56f4d23a96e41998d9e8dcacc1300cfa

**Comment by NTT1906** [comment]
> [6679c53](https://github.com/pmmp/PocketMine-MP/commit/6679c53e56f4d23a96e41998d9e8dcacc1300cfa)

this is about it :l

**Comment by dktapps** [comment]
Actually it's correct for Bedrock. Java is not a suitable test bed for these things.

**Comment by NTT1906** [comment]
> Actually it's correct for Bedrock. Java is not a suitable test bed for these things.

umm, you could try it in vanilla ^-^

**Comment by NTT1906** [comment]
![image](https://user-images.githubusercontent.com/54394881/150339625-550ec896-d79b-424b-baf4-6bb295dfb854.png)
in vanilla, arrow will collide like this.

**Comment by dktapps** [comment]
I did. That's not what I saw.

**Comment by NTT1906** [comment]
> I did. That's not what I saw.

wdym, i'm confused

**Comment by dktapps** [comment]
The current behaviour matches Java, which, IMO, makes a lot more sense and looks less stupid.

**Comment by NTT1906** [comment]
> The current behaviour matches Java, which, IMO, makes a lot more sense and looks less stupid.

this is true but what i'm about to say is Minecraft Bedrock has two type of collision boxes, one for normal entity included players and one for projectile. At least, it's a thing in bugrock :p

**Comment by dktapps** [comment]
That's a thing in JE too, so that arrows don't get stuck in the air above fences. That's not implemented yet.
