### ISSUE TITLE
After starting breaking the block and abruptly stop breaking, particles and sounds are alive

### ISSUE THREAD

**Issue by ghost** [pmmp/PocketMine-MP#4754]
### Steps to reproduce the issue
1. Start breaking the block and abruptly stop breaking it.
2. https://youtu.be/hTYkUpQiICY

### OS and versions

* PocketMine-MP: e7d17eb4d327f6573ae702273e3838305844d2d6
* PHP: 8.0
* Server OS: Arch Linux

### Crashdump, backtrace or other files
- None

**Comment by dktapps** [comment]
I can't reproduce this.

**Comment by ghost** [comment]
> I can't reproduce this.

Could this be a client?  Or is it only in the mobile version?
