### ISSUE TITLE
[Server thread/CRITICAL] Failed to load chunk don't know how to decode levelDB subchunk format version 9

### ISSUE THREAD

**Issue by adoboing** [pmmp/PocketMine-MP#4763]
### Basically, it doesn't load a void world I have properly, and gives this error message:
[Server thread/CRITICAL] Failed to load chunk don't know how to decode levelDB subchunk format version 9

- Expected result: for it to properly load the void world
- Actual result: turned the void into flatworld chunks

### Steps to reproduce the issue
1. Load this void world I'm going to provide
2. Join the server and watch it not work properly

### OS and versions

* PocketMine-MP: 4.0.7
* PHP: 8.0.13
* Using JIT: no
* Server OS: Windows 10 Pro
* Game version: Android and iOS

### Plugins
BuilderToold v1.3.1, KygekRanksUI v2.0.0, and MultiWorld v1.7.0-beta4

- If you remove all plugins, does the issue still occur? Yes

### Crashdump, backtrace or other files

no crashes, just this error
[void.zip](https://github.com/pmmp/PocketMine-MP/files/7921404/void.zip)

**Comment by dktapps** [comment]
This is expected. Worlds newer than 1.12 are not currently supported.
