### ISSUE TITLE
Add LiquidDisappearEvent

### ISSUE THREAD

**Issue by AkmalFairuz** [pmmp/PocketMine-MP#4770]
## Description
Add event when liquid block disappear. In my case it was useful for bedwars plugin to remove blocks placed in memory.
https://github.com/pmmp/PocketMine-MP/blob/32b07e094055c42859e6ac9d937b4b055063cf3a/src/block/Liquid.php#L301

## Alternative methods
Register blocks that extends to custom Liquid class.

**Comment by dktapps** [comment]
I don't see the use case. This happens because of a source block being deleted. I don't understand why you would want to prevent the flow from going away.

**Comment by dktapps** [comment]
This is a weird enough use case (which I don't see the point of) that I think it makes more sense if you stick to registering custom liquids.
