### ISSUE TITLE
Bug Tick Speed of Plantation

### ISSUE THREAD

**Issue by SenseiTarzan** [pmmp/PocketMine-MP#4772]
Here is a video that shows in evidence the problem on the speed of growth on pmmp4
https://www.youtube.com/watch?v=-yPR2GwVI8M 

pmmp3.0 server (which is not to our ):
20 tick time
poggit plugins it must have 20-30 

server pmmp4.0(which is our set here):
tps of 20-19 tick
plugin 13 poggit plugin and a big proprietary plugin that manages all the server system scoreboard, nametag, events, Chat,Group,Faction

PocketMine Version: 4.1.0 Beta 1
OS: Debian 10 
Processor: i9-10850K
RAM: 64 Go
Stockage: 1To MVME
we have a dedicated server and we use Proxmox to create Debian containers 

CPU usage 3.69% of 20 CPU(s)
 IO delay 0.18%
 Load average 1.10,1.10,1.07

Bin php Custom for add MongoDB
PHP Version: lasted
JIT: false

**Comment by dktapps** [comment]
Fixed by 6cbc14f2b23976dc1c3c07188648785a1f5470fb.
