### ISSUE TITLE
Dimension change cause very strange bugs

### ISSUE THREAD

**Issue by ipad54** [pmmp/PocketMine-MP#4778]
### Steps to reproduce the issue
Send ChangeDimensionPacket:

public function onJoin(\pocketmine\event\player\PlayerJoinEvent $e) {
$e->getPlayer()->getNetworkSession()->sendDataPacket(\pocketmine\network\mcpe\protocol\ChangeDimensionPacket::create(\pocketmine\network\mcpe\protocol\types\DimensionIds::NETHER, $this->getServer()->getWorldManager()->getDefaultWorld()->getSafeSpawn(), true));
$e->getPlayer()->teleport($this->getServer()->getWorldManager()->getDefaultWorld()->getSafeSpawn());
}

### OS and versions
* PocketMine-MP: 3.26.2, 4.1-BETA1
* PHP: 8.0
* Using JIT: no
* Server OS: Ubuntu 18.04
* Game version: Android/iOS/
* 
### Crashdump, backtrace or other files
https://youtu.be/0iRxBLGlW6A

**Comment by dktapps** [comment]
This is not supported behaviour.
