### ISSUE TITLE
Player will not disconnect

### ISSUE THREAD

**Issue by xxAROX** [pmmp/PocketMine-MP#4779]
### Issue description

- Expected result: Player should disconnect.
- Actual result: Player will disconnect on form close

### Steps to reproduce the issue
1. open a form and keep it open
2. stop the server

### OS and versions
* This server is running PocketMine-MP
* Server version: 4.0.6 (git hash: f7d25f251e431aace3ca835918b661583d32e6e7)
* Compatible Minecraft version: 1.18.0 (protocol version: 475)
* PHP version: 8.0.13
* PHP JIT: disabled
* Operating system: win

### Plugins
* DevTools v1.15.0
* Form-Test v1.0

**Comment by dktapps** [comment]
This is a client bug. As soon as you close the form, the client will realize it has disconnected.
You should report this on https://bugs.mojang.com.
