### ISSUE TITLE
Command Blocks

### ISSUE THREAD

**Issue by LagHD** [pmmp/PocketMine-MP#478]
Will Command Blocks Be Added to PMMP anytime Soon? MCPE 1.0.5 Officially got Released Yesterday!

**Comment by SOF3** [comment]
Depending on the definition of "Soon", yes and no. Hopefully better than @shoghicp's promise of "implementing mob AI soon".

**Comment by dktapps** [comment]
Read the issue template before submitting issues. And don't ask developers for ETAs.
