### ISSUE TITLE
Bamboo can be placed underwater

### ISSUE THREAD

**Issue by ipad54** [pmmp/PocketMine-MP#4783]
### Issue description

- Actual result: Bamboo can be placed underwater

### Steps to reproduce the issue
1.  If you quickly try to place bamboo under water - it is placed

### OS and versions
* PocketMine-MP: 4.0.1-BETA3+dev
* PHP: 8.0
* Using JIT: no
* Server OS: Ubuntu
* Game version: Android/iOS/Win10

### Crashdump, backtrace or other files
https://youtu.be/25XWTRDoUNg

**Comment by dktapps** [comment]
This video is too dark. I can't see anything.

**Comment by ipad54** [comment]
https://youtu.be/csEJRHyAB0I

**Comment by ghost** [comment]
> This video is too dark. I can't see anything.

The video is not dark.
