### ISSUE TITLE
[BUG]: Hitbox is smaller when a player is wearing an Elytra

### ISSUE THREAD

**Issue by supercrafter333** [pmmp/PocketMine-MP#4784]
### Issue description

- Expected result: Hitbox will be normal
- Actual result: Hitbox is smaller than the normal hitbox of a player (with default size)

### Steps to reproduce the issue
1. Wear a elytra
2. Hitbox will be smaller than normal and nametag will be set smaller to

### OS and versions

* PocketMine-MP: 4.1.0-BETA3+dev
* PHP: 8.0.15
* Using JIT: no
* Server OS: Linux Ubuntu 20.04
* Game version: Win10 and all other

### Plugins
--- with and without any plugins --

### Crashdump, backtrace or other files
--- nothing ---

**Comment by dktapps** [comment]
Elytra is not supported.

**Comment by supercrafter333** [comment]
Gliding was implemented. Elytras wasn't. Why?
This is a bug because it's after gliding.

**Comment by supercrafter333** [comment]
@dktapps This is a hitbox bug. It's been after swimming and gliding.

**Comment by dktapps** [comment]
This is fixed in 1.18.10.
