### ISSUE TITLE
Sleep should not be used on the main thread

### ISSUE THREAD

**Issue by madecode15** [pmmp/PocketMine-MP#479]
### Issue description
As a java developer, one of the most basic rules I went through in collage is not to use sleep on the main thread... it creates an unnecessary slow down of the entire project for no reason. For that same reason we don't use sleep to get the program to do 20 ticks a second, we use mircotime(true) and calculate the time difference.

https://github.com/pmmp/PocketMine-MP/blob/master/src/pocketmine/Server.php#L2129

This seems more like a hack anyways, 20 ticks should still be produced a second and there should be no need for sleep.

**Comment by dktapps** [comment]
Please re-read the code. That sleep makes the server wait the _remaining_ time until the next tick. For example if the end of the server tick is reached in 10ms, the server will then sleep for 40ms until the start of the next tick. This works exactly as intended.
