### ISSUE TITLE
Setting a chest in the position of a trapped chest

### ISSUE THREAD

**Issue by ElectroGamesDev** [pmmp/PocketMine-MP#4798]
### Issue description

- Expected result: The chest to replaced by a trapped chest
- Actual result: The chest did not get replaced so there are now a trapped chest and chest in the same position. The trap chest breaks if you punch the trap chest then the chest appears. (The trapped chest is under the chest). This also happens with setting a chest in a trapped chest position.

### Steps to reproduce the issue
1. Place a trapped chest in game
2. Set a chest to that position using setBlock()
3. You will see nothing has changed until you break the trapped chest and see the chest under it.

### OS and versions
* PocketMine-MP: 4.1.0-BETA1
* PHP: 8.0.13
* Server OS: Windows

### Plugins

BankUI v2.0.0, BetterFlight v1.0.0, BetterHomes v1.0.0, BetterWarps v1.0.0, BuilderTools v1.3.1, CustomItemLoader v2.3.1, DeathMoney v1.0.1, DevTools v1.15.0, DragonEscape v1.0.0, EconomyAPI v5.7.3-PM4, FakePlayer v0.0.1, FateDecider v1.0.0, ImageOnMap v1.0.0, InfiniteBuckets v2.0.0, MaintenanceMode v1.0.2, MultiWorld v1.7.0-beta2, NickMe v1.0.0, NoVoid v1.0.0, PlayerScale v1.0.0, RemoteConsole v2.0.0, Scripter v0.0.1, SimpleFeed v2.0.0, SimpleHeal v2.0.0, SimpleNPC v3.0.0-snapshot, SkyWars v1.0.0, Spleef v1.0.0, TellRaw v2.0.0, TheBlockingDead v1.0.0, TheBridge v1.0.0, TransferMe v2.0.0, Vouchers v1.0.0, WordScrambler v1.0.0

- If you remove all plugins, does the issue still occur? Yes

**Comment by dktapps** [comment]
Please provide sample code and an example of how this occurs (preferably video).

**Comment by ElectroGamesDev** [comment]
> Please provide sample code and an example of how this occurs (preferably video).

Sure, I will at a later time/date when I am able to.

**Comment by dktapps** [comment]
This is a client bug. You can reproduce it in vanilla by placing a trapped chest and then using `/setblock x y z chest`.

You should report this on https://bugs.mojang.com.
