### ISSUE TITLE
PHP Bin ?

### ISSUE THREAD

**Issue by MrReskill** [pmmp/PocketMine-MP#481]
Hello i have a bug with the software && binary (latest LINUX 64/86bits)
Error: ./start.sh: ligne 54: /home/gsp_920/g3.hmserv.eu-19139/bin/php7/bin/php: Aucun fichier ou dossier de ce type

I'm french !

**Comment by dktapps** [comment]
https://github.com/pmmp/PocketMine-MP#setup-help--support-faqs

**Comment by MrReskill** [comment]
Please ;(

**Comment by MrReskill** [comment]
@dktapps
