### ISSUE TITLE
CONNECTION IMPOSSIBLE 

### ISSUE THREAD

**Issue by xodamcm** [pmmp/PocketMine-MP#4817]
### Issue description

Loggin timeout
### Steps to reproduce the issue
1. Put pocketminr 3.28
2. Start your server
3. Try to connect

### OS and versions

* PocketMine-MP: 3.28
* PHP: 8
* Using JIT: yes/no (delete as appropriate) 
* Server OS:
* Game version: 1.18.10 on Android/iOS/Win10/Xbox/PS4/Switch (delete as appropriate)

### Plugins

0 plugins
- If you remove all plugins, does the issue still occur? Yes
- If the issue is **not** reproducible without plugins: issue without plugin and with plugins
  - Have you asked for help on our forums before creating an issue? I don’t know any forum 
  - Can you provide sample, *minimal* reproducing code for the issue? If so, paste it in the bottom section
  - 
![Uploading F144D1E3-633E-47E6-AB75-2F4B3B8D4968.png…]()

**Comment by pepepaco** [comment]
hello did you manage to solve the issue? i have the same problem.

Well I went directly to discord and found the solution
Just **switch to Classic Skin** your character before join the server.

**Comment by xodamcm** [comment]
Hello i have found it with AntiInternalKick plugin!
