### ISSUE TITLE
player food animation

### ISSUE THREAD

**Issue by Bubbelwubbel** [pmmp/PocketMine-MP#4822]
### Issue description

- That when eating, the food is carried to the mouth
- It stays down

### Steps to reproduce the issue
1. Take a meal from inventory
2. Eat this, the other players cannot see the full animation. (See image)

### OS and versions
* PocketMine-MP: 4.2.0 (git hash: 44818e6d1456dcf1f0fd3cd27da1dfecbe03c08b)
* PHP: 8.0.13
* Using JIT: not supported
* Server OS: linux
* Game version: Android/iOS/Win10/Xbox/PS4/Switch

### Plugins
BuilderTools v1.4.0-dev, MultiWorld v1.7.0-beta4

- If you remove all plugins, does the issue still occur? yes

### Crashdump, backtrace or other files
![image](https://user-images.githubusercontent.com/65186341/153713746-c12a530c-a862-43cc-af9d-9cf2f3964b68.png)

**Comment by dktapps** [comment]
I'm not able to reproduce this.

**Comment by Bubbelwubbel** [comment]
@dktapps hey sry, I tried it again and the animation is just not displayed in gamemode 1, why?

**Comment by dktapps** [comment]
Eating isn't supported in creative yet.
