### ISSUE TITLE
Fake-Enchantment after using a dropped shovel

### ISSUE THREAD

**Issue by supercrafter333** [pmmp/PocketMine-MP#4823]
### Issue description

- Expected result: Use a shovel with silk-touch and drop the shovel, after using the dropped shovel on a grass block, a grass block will drop.
- Actual result: Use a shovel with silk-touch and drop the shovel, after using the dropped shovel on a grass block, a **dirt** block will drop. But before the shovel was dropped a grass block will drop after breaking a grass-block.

### Steps to reproduce the issue
1. enchant a shovel with silk-touch
2. Use the shovel on a grass-block (a grass-block will drop)
3. Drop the shovel and break a grass-block again (a dirt-block will drop)

### OS and versions
* PocketMine-MP: 4.2.0
* PHP: 8.0.15
* Using JIT: no
* Server OS: Linux Ubuntu 20.04
* Game version: Win10

**Comment by dktapps** [comment]
⚠️ This issue ticket doesn't have all the required information ⚠️ 
To make it as quick and easy as possible for maintainers to fix your problem, an issue template is provided which lists certain required information. This includes (but is not limited to):

- PocketMine-MP version (use the `version` command)
- PHP version
- Minecraft version and/or edition
- List of all plugins used (use the `plugins` command)

Without this information, your problem cannot begin to be investigated, so the issue will be closed. You may amend this one, or create a new one, providing all the required information using one of the provided [issue templates](https://github.com/pmmp/PocketMine-MP/issues/new/choose).

Help us to help you by providing the information we ask for.

**Comment by xxFLORII** [comment]
https://www.youtube.com/watch?v=MpyCaLt1Rac @supercrafter333 you mean this bug, or?

**Comment by supercrafter333** [comment]
I'm Not using some Plugins. The're no crashdumps.

The shovel cannot ne moved in the inventory too.

(Please reopen)

**Comment by dktapps** [comment]
This bug report is way too confusing, I have no idea what you're trying to report.
