### ISSUE TITLE
[BUG]: A silk-touch enchanted shovel is very buggy after being dropped.

### ISSUE THREAD

**Issue by supercrafter333** [pmmp/PocketMine-MP#4824]
### Issue description

- Expected result: 
Attempting to mine a grass block with a shovel enchanted with soll touch after the shovel has dropped should drop a grass block.
- Actual result:
Attempting to mine a grass block with a silk touch enchanted shovel after it has dropped will drop a dirt block. 
### Steps to reproduce the issue
1. Enchant a shovel with silk touch
2. drop the shovel and pick it up again.
3. Try to mine a grass-block with the shovel (a dirt-block will drop) OR try to move the shovel in your inventory.

### OS and versions
* PocketMine-MP: 4.2.0
* PHP: 8.0.15
* Using JIT: no
* Server OS: Linux Ubuntu 20.04
* Game version: Win10

### Plugins
None

### Crashdump, backtrace or  files
No crashdump(s) or other files

**Comment by dktapps** [comment]
Closing in favour of #4825
