### ISSUE TITLE
Ghost item left in client side inventory when dropping tool while mining

### ISSUE THREAD

**Issue by xxFLORII** [pmmp/PocketMine-MP#4825]
### Issue description

- Expected result: Only one shovel should be dropped with the silk-touch enchantment
- Actual result: There are currently 2 shovels dropped. Once the real and once a "fake" shovel with alleged silk-touch enchantment, which despawns when dropping

### Steps to reproduce the issue
1. Give you a shovel (Diamond shovel)
2. Enchante this shovel with silk touch
3. Mine a grass block and drop this shovel meanwhile

### OS and versions
* PocketMine-MP: 4.2.0 (git hash: 44818e6d1456dcf1f0fd3cd27da1dfecbe03c08b)
* PHP: 8.0.15
* Using JIT: no
* Server OS: Debian 10

### Plugins
 Plugins (0):

### Videos
https://www.youtube.com/watch?v=SEpEoBiPXek

**Comment by supercrafter333** [comment]
Thank you
