### ISSUE TITLE
Collision of 2 events. Can you separate BlockBreakEvent and PlayerInteractEvent.

### ISSUE THREAD

**Issue by WillyDuGang** [pmmp/PocketMine-MP#4826]
### Issue description

Can you separate PlayerInteractEvent and BlockBreakEvent like on PM3. This is not easy to use when both events are called.

### Steps to reproduce the issue
When I start to break a block, PlayerInteractEvent is call first and BlockBreakEvent secondly.

### OS and versions
* PocketMine-MP: 4.x.x
* PHP: 8
* Using JIT: yes
* Server OS: Ubuntu 20
* Game version: Android/iOS/Win10/Xbox/PS4/Switch

### Plugins
Any

**Comment by dktapps** [comment]
It's always worked the same way, PM3 and PM4...
