### ISSUE TITLE
Items don't appear in the hotbar 

### ISSUE THREAD

**Issue by Misteboss** [pmmp/PocketMine-MP#483]
### Issue description
Very often, when i set an item in the hotbar it doesn't appear but he's on the inventory
Check the video below
-->

### Steps to reproduce the issue

1. ... Join the Server
2. ... setItem

### OS and versions
* PocketMine-MP:PocketMine-MP 1.6.2dev "Unleashed" with API 3.0.0-ALPHA5 / branch master with last commit
* PHP: 7.0.2
* Server OS: Debian
* Game version: PE/Win10 (delete as appropriate) PE 1.0.4

#

## Crashdump, backtrace or other files

* ... https://youtu.be/ubnT7yLxckw

**Comment by dktapps** [comment]
Also seen when using the /give command. I believe this is a client-sided issue, however it is a very common issue. Regardless, I'm hoping it will be resolved in 1.1.1.

**Comment by Misteboss** [comment]
@dktapps Nop it doesn't happen with Elywing (sorry for this fucking work but i need to mention it) ! You

**Comment by dktapps** [comment]
In which case it will have been resolved in the inventory upgrades I made to Genisys in August last year, before Elywing was spooned from it. PocketMine inventory rewrite is pending shoghicp's new transaction system, as I have stated elsewhere. We're expecting these updates to arrive in MCPE 1.1.1. Until then, I'm putting no significant effort into fixing this.

**Comment by Misteboss** [comment]
@dktapps Ok 😕 and is their a way to find a hack to fix it

**Comment by dktapps** [comment]
Inventory->sendContents() should resolve the issue, but that is a definite hack.

**Comment by Misteboss** [comment]
After the set the items i did $player->getInventory()->sendContent($player); but it doesn't did anything :c

**Comment by Misteboss** [comment]
I found an hack to fix it.

**Comment by Misteboss** [comment]
It's coming from pmmp

**Comment by dktapps** [comment]
I'm fully aware of that.

> In which case it will have been resolved in the inventory upgrades I made to Genisys in August last year, before Elywing was spooned from it.

**Comment by Misteboss** [comment]
I don't change anything i just use $player->getInventory()->resetHotbar after setItem/addItem and it works perfectly @dktapps

**Comment by dktapps** [comment]
Hmm... ok.

**Comment by Misteboss** [comment]
It's strange but it works, items aren't resetting same for HeldItemSlot

**Comment by Muqsit** [comment]
Looks like the inventory only updates if the player has viewed their inventory at least once.

**Comment by dktapps** [comment]
This issue will be fixed in the upcoming 1.2 release.

**Comment by dktapps** [comment]
Closing this since it's fixed in the 1.2 beta.
