### ISSUE TITLE
Position Problem

### ISSUE THREAD

**Issue by lenlenlL6** [pmmp/PocketMine-MP#4832]
Pocketmine 4.2.0 is having position problems. Like this image, standing above or below, the postion "y" stays the same. This problem is causing my plugins to get stuck. Please fix it.
![Screenshot_20220217-215251_Minecraft](https://user-images.githubusercontent.com/62021442/154508597-f4f02a88-1fec-4f6e-8738-3ea5f0198de0.jpg)
![Screenshot_20220217-215247_Minecraft](https://user-images.githubusercontent.com/62021442/154508618-d3e7377f-2f26-42a2-b9d4-82e68ef28ef7.jpg)

**Comment by dktapps** [comment]
Duplicate of #4815
