### ISSUE TITLE
Entity->setScale() doesn't set entity boundingbox..?

### ISSUE THREAD

**Issue by mal0ne-23** [pmmp/PocketMine-MP#484]
### Issue description

Players/entities with a smaller scale that walk under blocks that are smaller than their actual bounding box will take damage.

### Steps to reproduce the issue

1. Set a player's scale to 0.5
2. Walk in between a one block area

### OS and versions

* PocketMine-MP: 868602a559cf697f9318d9f266f4d9a74339fe9a
* PHP: 7.0. something idk irrelevent
* Server OS: Ubuntu
* Game version: doesnt matter

### Crashdump, backtrace or other files

* ...

**Comment by Sandertv** [comment]
Blame me, I haven't implemented that along with the functions. Not sure if I will, as dktapps is planning to rewrite it.

**Comment by mal0ne-23** [comment]
Ah.. Alright

**Comment by Tarik02** [comment]
As you can see [here](https://github.com/pmmp/PocketMine-MP/blob/master/src/pocketmine/entity/Entity.php#L406), it doesn't change AABB, only sets data property.

**Comment by mal0ne-23** [comment]
Thank you!
