### ISSUE TITLE
The player's hitbox broke down due to the innovation of swimming animation

### ISSUE THREAD

**Issue by LordBombardir** [pmmp/PocketMine-MP#4847]
### Issue description

- Expected result: The player's normal hitbox
- Actual result: The player's broken hitbox:
![Снимок экрана (2104)](https://user-images.githubusercontent.com/60620262/154685427-649e5975-d68c-4af9-88a2-7edb33218cb4.png)

### Steps to reproduce the issue
1. After the player got into the water and started swimming, his hitbox broke

### OS and versions

* PocketMine-MP: 4.2.0
* PHP: 8.0
* Using JIT: no
* Server OS: Linux
* Game version: Android/iOS/Win10

**Comment by ghost** [comment]
Duplicate of #4815.

**Comment by LordBombardir** [comment]
> Duplicate of #4815.

Oh, I didn't notice. I apologize
