### ISSUE TITLE
Coral don't die

### ISSUE THREAD

**Issue by ShockedPlot7560** [pmmp/PocketMine-MP#4849]
### Issue description

Currently coral blocks and coral fans die well if placed out of the water (instantly or after a few seconds depending on the type).
However, for the following types, they never die:
- ``tube_coral``
- ``brain_coral``
- ``bubble_coral``
- ``fire_coral``
- ``horn_coral``

### Steps to reproduce the issue
1. Get one of the coral problem.
2. Place them
3. Wait your life until they die (which will never happen)

### OS and versions

* PocketMine-MP: 4.3.0-dev (next-minor branch with last commit: 3ed336fa0e5247cf142b70c52fd460e8d3391ed3)
* PHP: 8.0.13
* Server OS: Windows

### Plugins

- If you remove all plugins, does the issue still occur? yes

### Crashdump, backtrace or other files
![image](https://user-images.githubusercontent.com/66992287/154820113-0761e3a2-888f-4c58-97e0-97c504b30c63.png)

**Comment by dktapps** [comment]
relates to #4663 

In 1.12 they didn't exist in the dead variants at all, so they couldn't die.

**Comment by dktapps** [comment]
This was fixed in PM5, probably by f24f2d9ca9efec495a652bf8d440c06a465c93d2
