### ISSUE TITLE
Client crashed when trying to changing player's gamemode while have an inventory opened in spectator gamemode

### ISSUE THREAD

**Issue by ItsZodiaX** [pmmp/PocketMine-MP#4853]
### Issue description

- Expected result: Gamemode changed without client crashing
- Actual result: Once code executed client crashed

### Steps to reproduce the issue
1. Set player's gamemode to "Spectator"
2. Open an inventory
3. Let scheduler task set player's gamemode to "Survival"

### OS and versions
* PocketMine-MP: 4.2.1
* PHP: 8.0.13
* Using JIT: no
* Server OS: Mac
* Game version: 1.18.12 Android/iOS/Win10

### Plugins
Plugins (2): DevTools v1.15.0+dev, Test v0.0.1

- If you remove all plugins, does the issue still occur? N/A
- If the issue is **not** reproducible without plugins: Yes
  - Have you asked for help on our forums before creating an issue? Yes
  - Can you provide sample, *minimal* reproducing code for the issue? If so, paste it in the bottom section
  ```php
	public function execute(CommandSender $sender, string $commandLabel, array $args) {
		if($sender instanceof Player){
			$sender->setGamemode(GameMode::SPECTATOR());
			Main::getInstance()->getScheduler()->scheduleDelayedTask(new ClosureTask(function () use ($sender) {
				//$sender->removeCurrentWindow();
				$sender->setGamemode(GameMode::SURVIVAL());
			}), 20 * 5);
		}
	}
  ```
I have tried "$sender->removeCurrentWindow()", Client still crashed.

### Crashdump, backtrace or other files
Video: https://cdn.discordapp.com/attachments/878545340058468412/944958420656734258/RPReplay_Final1645363387.mp4

**Comment by dktapps** [comment]
This is an old client bug, there's nothing I can do about it.
