### ISSUE TITLE
Server crashed

### ISSUE THREAD

**Issue by TaxosTV** [pmmp/PocketMine-MP#4855]
Link to crashdump: https://crash.pmmp.io/view/5993176

**Comment by dktapps** [comment]
This happens because a plugin kicked a player during EntityDamageEvent.

**Comment by TaxosTV** [comment]
Ok, but I don't have a plugin that would kick the player.

**Comment by TaxosTV** [comment]
I have checked all plugins, and there is no plugin that would kick a player with the EntityDamageEvent.

**Comment by dktapps** [comment]
Well that's the only way this issue would occur ...

**Comment by TaxosTV** [comment]
I checked everything several times, and I didn't find anything like that. I have another crash that appears very often, can you help with it? Link - https://github.com/pmmp/PocketMine-MP/issues/4857

**Comment by dktapps** [comment]
This isn't a support forum.

**Comment by TaxosTV** [comment]
Okay, what should I do then? There is no player kick in the plugin.

**Comment by jasonw4331** [comment]
reproduce it without a plugin on the server then 👍

**Comment by TaxosTV** [comment]
Good thanks
