### ISSUE TITLE
Server crashed PMMP4

### ISSUE THREAD

**Issue by TaxosTV** [pmmp/PocketMine-MP#4857]
Link to crashdump: https://crash.pmmp.io/view/6001358

**Comment by dktapps** [comment]
This is most likely caused by a player being kicked during PlayerChatEvent.

**Comment by TaxosTV** [comment]
No, the players communicate freely, and no error appears when sending a message to the chat.

**Comment by dktapps** [comment]
Well, you are the only one who's reported this, so it's far more likely a fault in one of your plugins than in PM.

**Comment by TaxosTV** [comment]
OK, how do I find out which plugin has the error?

**Comment by PocketMiner92** [comment]
Auth Plugin
