### ISSUE TITLE
Full Server Tick problem ?

### ISSUE THREAD

**Issue by Misteboss** [pmmp/PocketMine-MP#486]
### Issue description
Hello, i made some timings on my server when i was alone on and this is a result, i think there is a problem with Full Server Tick cause my server have 100 slots and i was alone on ^^.

### Steps to reproduce the issue

1. ... Join Server, Do /timings on then /timings paste few secs after
2. ... Check the timings file

### OS and versions

* PocketMine-MP: Last commit of api3/network branch
* PHP:7.0.2
* Server OS: Debian
* Game version: PE/Win10 1.0.5

* ... Timings link https://timings.pmmp.io/?url=24281531

**Comment by dktapps** [comment]
You can see at a glance that this is a plugin issue.

**Comment by Misteboss** [comment]
I don't understand, from what it's coming ? @dktapps

**Comment by dktapps** [comment]
It looks like you have a large number of tiles in wherever you've spawned.

**Comment by Misteboss** [comment]
Ok i am going to look at that thanks ;)

**Comment by Misteboss** [comment]
It's time to delete the message queue system

**Comment by Misteboss** [comment]
The duplication bug of message is fixed in 1.0.5 @dktapps

**Comment by dktapps** [comment]
Please check the commit history before commenting.

**Comment by Misteboss** [comment]
@dktapps Can you tell me from what is coming the FullTickTimer Timings ? (What file)

**Comment by madecode15** [comment]
@Misteboss Take a look into:

>     0.17%	   6.88%	  0.06 s	     3.44 ms	 0.0	       0.0k	    Task: glorious\StatsTask(interval 40)
  >     0.07%	   3.00%	  0.02 s	     1.50 ms	 0.0	       0.0k	    Task: glorious\NPC(interval 40)

**Comment by Misteboss** [comment]
Oh it´s coming from a task ? @madecode15

**Comment by Misteboss** [comment]
I tested without task and alone on the server on flat world and i always have this Full Server Tick problem... Can you tell from what is it coming @dktapps ?

**Comment by Misteboss** [comment]
Can you answer please.. I think this is an issue
