### ISSUE TITLE
Error Generation Block in 1.18.10 (pm4)

### ISSUE THREAD

**Issue by crischutu07** [pmmp/PocketMine-MP#4862]
### Issue description

- Expected result: if player in 1.18.2 is showing grass block as path block like this

![received_372413547583907](https://user-images.githubusercontent.com/81855366/155496419-ac21d7f1-a6b5-44d8-b626-95a266f164d4.jpeg)

Between my pov in 1.18.10

![received_343987597630082](https://user-images.githubusercontent.com/81855366/155496589-2ba71508-9373-43d2-bba9-fb91ad115375.jpeg)

- Actual result: My friends going to build with me, but actually they using 1.18.2 and get that error generation (maybe) if they you using 1.18.10 they will never get this error 

### Steps to reproduce the issue
1. Open Minecraft with 1.18.2
2. Press Play 
3. Press Server 
4. Join the server 
5. Get Generation Error

### OS and versions
* PocketMine-MP: 4.0.0 
* PHP: 8.0.12
* Using JIT: No
* Server OS: Linux 
* Game versions: 1.18.10

### Plugins
pl [09:35:07.892] [Server thread/INFO]: Plugins (30): AdvancedInstantRespawn v1.0.0, AntiInstaBreak v1.0.0, Better Ban v4.1.1, BetterWarps v1.0.0, Build er Tools v1.3.1, DevTools v1.15.0, Eco nomyAPI v5.7.3-PM4, FFA v1.0.0, FormA PI v2.1.0, HideCommands v2.0.1, ItemL ifeTime v0.0.1, KygekRulesUI v2.0.0, MultiProtocol v1, MultiWorld v1.7.0-b eta4, MyPlot v2.1.0, NBTEditor v1.0.0 Netherite v2.0, Oneblock v0.0.4, Pl ayerSelectors v2.0.0, PlotChat v3.0.0 Pockit v1.1.0, PureChat v2.0.0, Pur ePerms v1.4.5, Shield v1.5.0, SkyBloc kMenuUI v1.0.0, SkyBlocks PM v1.0.1, S lapper v2.0.1, Sudo v1.2, WordScrambler v1.0.0, World Protect v2.3.11
- If you remove all plugins, does the issue still occur?
 - no, if a player join with 1.18.2 they will can't join because Outdated Version
- If the issue is **not** reproducible without 
 -  no
- plugins:
 - Have you asked for help on our forums before creating an issue?
  - Yes they will thinking this a bug in PocketMine-MP generally 
 - Can you provide sample, *minimal* reproducing code for the issue? If so, paste it in the bottom section

### Crashdump, backtrace or other files

Video:
https://user-images.githubusercontent.com/81855366/155498953-ac225e7f-5305-4d56-bfac-86c0552af8a8.mp4

**Comment by crischutu07** [comment]
Maybe this is error about MutiProtocol Plugin

**Comment by crischutu07** [comment]
Also if I place A grass block is turn into path block

**Comment by ipad54** [comment]
This isn't PocketMine-MP bug. You should report this to MultiProtocol author, because clean PocketMine support only 1.18.10 version

**Comment by crischutu07** [comment]
> This isn't PocketMine-MP bug. You should report this to MultiProtocol author, because clean PocketMine support only 1.18.10 version

I checked plugin carefully there is no generation code is only the multi protocol

**Comment by crischutu07** [comment]
> This isn't PocketMine-MP bug. You should report this to MultiProtocol author, because clean PocketMine support only 1.18.10 version

Also 1.18.10 is same thing as 1.18.2

**Comment by ipad54** [comment]
I think the MultiProtocol plugin has a broken bedrock date. But you should close this issues and report this bug to the developer of MultiProtocol. Don't waste the time of the PocketMine-MP developers, this is not a PocketMine bug.
