### ISSUE TITLE
api3/network: Remove data saving from PlayerQuitEvent, add separate events for saving player data

### ISSUE THREAD

**Issue by dktapps** [pmmp/PocketMine-MP#487]
### Issue description
Lots of plugins like to do weird things during PlayerQuitEvent, such as unloading their level (#284).

Irrelevant of the crash noted in referenced issue, if said crash was fixed, unloading a player's level during PlayerQuitEvent will have some unintended side-effects due to the way player data saving is tied up with PlayerQuitEvent. These side-effects include the player's current level and spawn position not being saved due to the level being inaccessible.

### Proposed solution
Separate the two events - have a PlayerDataSaveEvent independent from PlayerQuitEvent. On quit, the player's data will then be saved _before_ the PlayerQuitEvent is called. PlayerDataSaveEvent can then be used anytime a player is saved. This will also allow weird stuff like #284 to be done without affecting saved data.

**Comment by legoboy0215** [comment]
I guess I just like to do weird stuff :P

**Comment by legoboy0215** [comment]
YEAH!
