### ISSUE TITLE
onEntityLand() is not called on some types of block

### ISSUE THREAD

**Issue by ipad54** [pmmp/PocketMine-MP#4875]
### Issue description

- Actual result: Now onEntityLand() is called only for those blocks that have a collision. Some blocks (such as sweet berry bush) do something when an entity falls on them, without having a collision. For example, in vanilla, the sweet berry bush absorbs fall damage

### Steps to reproduce the issue
1. Add an onEntityLand() method that will do something in a block that does not have a collision

### OS and versions
* PocketMine-MP: 4.2.1
* PHP: 8.0.13
* Using JIT: no
* Server OS: Win
* Game version: Android/iOS/Win10/Xbox/PS4/Switch

**Comment by dktapps** [comment]
onEntityInside should be used for this, similar to liquids.
