### ISSUE TITLE
Fire is invisible when lit on glass blocks

### ISSUE THREAD

**Issue by TobiasGrether** [pmmp/PocketMine-MP#4879]
### Issue description

- Expected result: What were you expecting to happen?
- Fire should be visible on glass blocks, although I am unsure whether it should be able to burn on glass anyways.
(Possibly related to #3719)
- Actual result: What actually happened?
Glass is lit on fire, but the fire is invisible to players.
### Steps to reproduce the issue
1. Place glass
2. Lit glass on fire using flint & steel

### OS and versions

* PocketMine-MP: 4.2.2+dev
* PHP: 8.0.16
* Using JIT: no
* Server OS: MacOS
* Game version: MacOS

### Plugins
---
- If you remove all plugins, does the issue still occur?
- Yes

**Comment by dktapps** [comment]
related to #4856

**Comment by dktapps** [comment]
correction: this has nothing to do with #4856 whatsoever; the problem remains that transparent non-flammable blocks shouldn't get fire placed on them. Mixing up `isSolid` and `!isTransparent` seems to be a common source of gameplay bugs.
