### ISSUE TITLE
New Player Functions ?

### ISSUE THREAD

**Issue by Misteboss** [pmmp/PocketMine-MP#488]
This isn't an issue but i don't know where i can contact you.
Can you add or can you give me the permission to add new Player functions to get the OS of the player,  the game edition and other new things discovered in the LoginPacket like $player->getDeviceOs() ?
Thanks.

**Comment by dktapps** [comment]
If you use the DataPacketReceiveEvent, you can access these fields in the clientData field, which is an associative array of json-decoded data from the packet.

**Comment by Misteboss** [comment]
Why you won't add them directly as functions ? It's the easiest way..

**Comment by Misteboss** [comment]
If you want i can do it (add them) @dktapps then you won't lost time

**Comment by dktapps** [comment]
I'm currently in the middle of networking rewrites on api3/network, and large amounts of Player.php are going to be stripped apart. I haven't decided how to handle authentication and client data yet, but these will be implemented in the future. Thank you for offering to help though.

**Comment by Misteboss** [comment]
No problem tell me if you need me to do it when it will be time to do it

**Comment by Misteboss** [comment]
Can you DM me on Twitter please ? I wanna talk to you about something ^^

**Comment by TheDiamondYT1** [comment]
Stop spamming this issue incase dylan locks it.

**Comment by ealgueiroqb9** [comment]
Hello, I just checked the content of the DataPacketReceiveEvent, but there is no field stating wether the client is Android or Windows10, for example, in clientData.
Are you sure that info is there?
thanks

**Comment by Sandertv** [comment]
That is because there is no difference between Android and Windows10. There is currently no possible way to find out if the user is using Android or Windows10.

**Comment by dktapps** [comment]
@ealgueiroqb9 There's no explicit "Android", "Windows10" if that's what you're expecting. You're looking for the DeviceOS field. Up to you to figure out the values, I don't know them.

**Comment by dktapps** [comment]
Sample code
```
		public function onPacketReceived(\pocketmine\event\server\DataPacketReceiveEvent $e){
			if($e->getPacket() instanceof \pocketmine\network\mcpe\protocol\LoginPacket){
				safe_var_dump($e->getPacket()->clientData);
			}
		}
```
Sample output
```
array(13) {
  ["ADRole"]=>
  int(2)
  ["ClientRandomId"]=>
  int(4340844811939028985)
  ["CurrentInputMode"]=>
  int(2)
  ["DefaultInputMode"]=>
  int(2)
  ["DeviceModel"]=>
  string(11) "LGE LG-H955"
  ["DeviceOS"]=>
  int(1)
  ["GameVersion"]=>
  string(7) "1.0.6.0"
  ["GuiScale"]=>
  int(-1)
  ["ServerAddress"]=>
  string(17) "192.168.0.4:19132"
  ["SkinData"]=>
  string(21848) base64 mess
  ["SkinId"]=>
  string(13) "Standard_Alex"
  ["TenantId"]=>
  string(0) ""
  ["UIProfile"]=>
  int(1)
}
```

**Comment by jasonwynn10** [comment]
I guess 1 is android then...

**Comment by ealgueiroqb9** [comment]
No, it's actually blank :/

**Comment by dktapps** [comment]
Then you're doing something wrong.

**Comment by IrishPacks** [comment]
1=> Android
2=> iOS
7=> Windows 10

**Comment by JackNoordhuis** [comment]
Android => 1
iOS => 2
OSX => 3
FireOS => 4
GearVR => 5
Hololens => 6
Win10 => 7
Win32 => 8
Dedicated => 9
A more complete list (as of 1.0.4) @IrishPacks

**Comment by IrishPacks** [comment]
Win32? How in the... I'm not going to question it.

**Comment by dktapps** [comment]
@IrishPacks my best guess is EDU edition is w32, since (I assume) it's not a Windows Store app.

**Comment by IrishPacks** [comment]
That'd make sense, same thing with OSX I assume.

**Comment by Misteboss** [comment]
How MaxOSX ?:0 @JackNoordhuis

**Comment by robske110** [comment]
And it's not really called OSX anymore #blameapple. But where did you get that list from anyway? Decompiling(well, if you can call it that) minecraft shouldn't give such descriptive names.

**Comment by HimbeersaftLP** [comment]
Wait, that really makes no sense, MCPE doesn't run on macOS/OSX whatever you want to call it, does it?!

**Comment by dktapps** [comment]
@HimbeersaftLP Edu edition does.

**Comment by HimbeersaftLP** [comment]
> @HimbeersaftLP Edu edition does.

Really?! Sorry didn't know that

**Comment by IISAAC300** [comment]
maybe it returns all devices type because it's running in a language of programming...

**Comment by NiclasOlofsson** [comment]
Thanks @JackNoordhuis

**Comment by IrishPacks** [comment]
> maybe it returns all devices type because it's running in a language of programming...

what are you trying to say, because to me it sounds like one of the most idiotic things someone has said regarding programming in a while.

**Comment by SOF3** [comment]
Why was this closed?

**Comment by sero583** [comment]
@JackNoordhuis are these values still the same? Btw ty

**Comment by Misteboss** [comment]
@sero583 Here is the update list of the os constant ```const OS_ANDROID = 1;
const OS_IOS = 2;
const OS_OSX = 3;
const OS_FIREOS = 4;
const OS_GEARVR = 5;
const OS_HOLOLENS = 6;
const OS_WIN10 = 7;
const OS_WIN32 = 8;
const OS_DEDICATED = 9;
const OS_ORBIS = 10;
const OS_NX = 11;```

**Comment by Joshiiiii** [comment]
Can anyone send an updated version of these constants? Or are they still the same?
