### ISSUE TITLE
Double login to the server from the same nickname

### ISSUE THREAD

**Issue by scarichen777** [pmmp/PocketMine-MP#4883]
### Issue description

- Expected result: won't let me into the server
- Actual result: entered the server actually from one nickname, but from two devices

### Steps to reproduce the issue
1. On the first device, you need to make a nickname: Steve
2. On the second device, change any letter to uppercase or lowercase: StevE
3. You need to join the server from two devices at the same time!
Thanks to this flaw, you can cause critical server errors, as well as dupe

### OS and versions
Version: 1.18.12 - Bedrock Edition
* PocketMine-MP 4.2.2:
* PHP 8.0:
* Using JIT: no
* Server OS: Debian-8-x86_64
* Game version: Android/iOS/Win10/Xbox/PS4/Switch (delete as appropriate)

### Plugins
Plugins (0)

- If you remove all plugins, does the issue still occur? - YES
- If the issue is **not** reproducible without plugins:
  - Have you asked for help on our forums before creating an issue? - no, only on discord
  - Can you provide sample, *minimal* reproducing code for the issue? If so, paste it in the bottom section - NO
### Crashdump, backtrace or other files
 NO
 NO

Please, please, please. Fix it
The plug-in did not work to fix it, and the option to enable Xbox sign-in verification is not suitable

**Comment by mopsikzlo** [comment]
всем привет, с вами антонскар

**Comment by MrBlasyMSK** [comment]
![image](https://user-images.githubusercontent.com/85447029/158641016-5759842b-413c-46dc-954a-85056d7a69b7.png)

Confirmed, but only on Android, I can't get it on Windows 10
The server does not register that it has been duplicated

```
[Server thread/INFO]: [NetworkSession: xx.xx.xxx.xxx xxxxx] Session opened
[Server thread/INFO]: [NetworkSession: xx.xx.xxx.xxx xxxxx] Player: MrBlasyMSK
[Server thread/INFO]: MrBlasyMSK[/xx.xx.xxx.xxx xxxxx] logged in with entity id 2 at (Lobby, 21.4893, 115, -4.4933)
[Server thread/INFO]: [+] MrBlasyMSK se ha conectado
```

**Comment by scarichen777** [comment]
@dktapps These cases are caused due to this bug with logging into the server with one nickname. Wait for a fix?
![Screenshot_2](https://user-images.githubusercontent.com/100973407/158832253-2d625079-64a0-4b9b-89ad-2444316fd588.png)

**Comment by dktapps** [comment]
> @dktapps These cases are caused due to this bug with logging into the server with one nickname. Wait for a fix? ![Screenshot_2](https://user-images.githubusercontent.com/100973407/158832253-2d625079-64a0-4b9b-89ad-2444316fd588.png)

This happens because you kicked the player during PlayerJoinEvent, which has nothing to do with this issue.

**Comment by scarichen777** [comment]
> > @dktapps These cases are caused due to this bug with logging into the server with one nickname. Wait for a fix? ![Screenshot_2](https://user-images.githubusercontent.com/100973407/158832253-2d625079-64a0-4b9b-89ad-2444316fd588.png)
> 
> This happens because you kicked the player during PlayerJoinEvent, which has nothing to do with this issue.

I was trying to fix a double entry bug. That's how it happened

**Comment by dktapps** [comment]
That's irrelevant to the point at hand. The fact that you created an attempted solution that made your particular problem worse is no one's fault but your own. Please stop filling the issue with irrelevant comments.
