### ISSUE TITLE
Can't open shulker chests underwater

### ISSUE THREAD

**Issue by NhanAZ** [pmmp/PocketMine-MP#4884]
# In vanilla:

https://user-images.githubusercontent.com/60387689/156894264-04f1196b-5331-4230-b3f2-55ffe4056ac0.mp4

# In PM4:

https://user-images.githubusercontent.com/60387689/156894283-93ac6097-d931-4869-b969-7b1f121dd82e.mp4

**Comment by NTT1906** [comment]
go sleeping, it's 1am

**Comment by NTT1906** [comment]
https://github.com/pmmp/PocketMine-MP/blob/5d970cf5bdfd1ce09dfa349e77fd225cbbebe069/src/block/ShulkerBox.php#L94
