### ISSUE TITLE
Damage from berries

### ISSUE THREAD

**Issue by NhanAZ** [pmmp/PocketMine-MP#4887]
Damage from the berry occurs even when the player is standing still inside it

In Vanilla:

https://user-images.githubusercontent.com/60387689/156904107-963d805c-c35c-4703-8a3b-e5272c036985.mp4

In PM4:

https://user-images.githubusercontent.com/60387689/156904112-7493c7d0-1c23-400e-ae84-7626943c8279.mp4

**Comment by NTT1906** [comment]
Dupe of #4704

**Comment by NhanAZ** [comment]
Dupe of https://github.com/pmmp/PocketMine-MP/issues/4704
