### ISSUE TITLE
The door can not be placed where the player is standing

### ISSUE THREAD

**Issue by Gaprix** [pmmp/PocketMine-MP#4888]
### Issue description

- Expected result: The door can be placed 
- Actual result: The door can not be placed 

### Steps to reproduce the issue
1. Stand on the part of the block where the door should be placed
2. Put the door under you 
3. The server did not set the door 

### OS and versions
* PocketMine-MP: 4.2.2
* PHP: 8.0.16
* PHP JIT: disabled

### Crashdump, backtrace or other files
![изображение](https://user-images.githubusercontent.com/45711510/156940516-5cda871b-1cee-4d60-968f-1bfd3be15b17.png)

Note: This bug does not recur on PM3

**Comment by dktapps** [comment]
Blocks aren't supposed to be placeable if their collision box would intersect with that of the player. Therefore this is expected behaviour.

**Comment by NTT1906** [comment]
> Blocks aren't supposed to be placeable if their collision box would intersect with that of the player. Therefore this is expected behaviour.

Am i having a fake memory or something but you can place door like that

**Comment by NTT1906** [comment]
https://user-images.githubusercontent.com/54394881/157629305-90514c22-0c63-4bc5-a824-e9550641d1d6.mp4

**Comment by Gaprix** [comment]
In a single player game, you can place a door on the part of the block on which you are standing. In this case, the block will be placed, and the player will be moved to the side

**Comment by dktapps** [comment]
Making it work that way in PM would entail extra work for a pointless special case. It's more likely that vanilla simply didn't account for the same cases that PM does.
