### ISSUE TITLE
Bounding box issues ?

### ISSUE THREAD

**Issue by Misteboss** [pmmp/PocketMine-MP#489]
### Issue description
When you sprint on a stair, there is a rollback and the console detect your movement as wrong : "Misteboss moved wrongly"

I will record that tomorrow and put the link in backtrace field

### Steps to reproduce the issue

1. ... Join your server
2. ... Sprint on a stair

### OS and versions
* PocketMine-MP: Last api3/network commit
* PHP: 7.0.2
* Server OS: Debian
* Game version: PE I didn't test on Win10 but i think there is the same issue

### Crashdump, backtrace or other files

* ...

**Comment by dktapps** [comment]
Please search the issue tracker before opening new issues. #169

**Comment by Misteboss** [comment]
Oh sorry i searched but i didn't find it ^^, btw i think it's very important to fix that issue cause it can make the difference for servers owner to choose between spoons and Pocketmine because it's very annoying

**Comment by dktapps** [comment]
As a temporary measure you can disable movement checks in pocketmine.yml (https://github.com/pmmp/PocketMine-MP/blob/master/src/pocketmine/resources/pocketmine.yml#L99-L106).

**Comment by Misteboss** [comment]
Thanks.
