### ISSUE TITLE
Server crashed

### ISSUE THREAD

**Issue by Reared** [pmmp/PocketMine-MP#4895]
When executing the case, the server issues Critical error, unexpected class, syntax error, what to do? At the expense of the code, everything is fine with it, there are no errors, I attach what I see in the console:![image](https://user-images.githubusercontent.com/81175026/158017816-8468717a-cf06-47b0-8bcc-1c13a4b7dfea.jpeg)

**Comment by dktapps** [comment]
⚠️ This issue ticket doesn't have all the required information ⚠️ 
To make it as quick and easy as possible for maintainers to fix your problem, an issue template is provided which lists certain required information. This includes (but is not limited to):

- PocketMine-MP version (use the `version` command)
- PHP version
- Minecraft version and/or edition
- List of all plugins used (use the `plugins` command)

Without this information, your problem cannot begin to be investigated, so the issue will be closed. You may amend this one, or create a new one, providing all the required information using one of the provided [issue templates](https://github.com/pmmp/PocketMine-MP/issues/new/choose).

Help us to help you by providing the information we ask for.
