### ISSUE TITLE
Flower in flower pot interacting issue.

### ISSUE THREAD

**Issue by TheDataLioness** [pmmp/PocketMine-MP#4896]
### Flower in flower pot issue

- Expected result: When interacting with flower pot flower should get out of the pot.
- Actual result: You interact with the flower pot and you get unlimited flowers (client side and just despawns when interacting with those items.)

### Steps to reproduce the issue
1. Place a flower pot
2. Place a flower inside of it.
3. Interact with an empty hand
4. You will receive more flowers.

### OS and versions

* PocketMine-MP: 4.2.2
* PHP: 8.0.16
* Using JIT: no
* Server OS: ubuntu-20.04-x86_64
* Game version: Win 10

### Plugins
Tested without plugins

### Example video

https://user-images.githubusercontent.com/34657342/158071215-8591b294-657b-46ec-a0e3-7a7ae1534b40.mp4

**Comment by dktapps** [comment]
The ghost item issue has been addressed by 90a8595a40f250b9274c9da32910975b53a0c9e4.
