### ISSUE TITLE
No block breaking/placing sound effects

### ISSUE THREAD

**Issue by rockmacaca** [pmmp/PocketMine-MP#49]
### Issue description

This is probably well-known, but might as well log it here. The sounds that play while breaking a block, when the block breaks, and when placing a block do not play.
### OS and versions

- PocketMine-MP: Any
- PHP: 7
- Server OS: Any (tested on Windows+Linux)
- Game version: PE/Win10

**Comment by SuperMaXAleX** [comment]
I succeed to add the sound when you are breaking a block and also added particles.
But for the sound when you are placing a block no longer working :/
Maybe it changed or I did something wrong.

**Comment by PrimusLV** [comment]
Perhaps client-side bug

**Comment by dktapps** [comment]
No, it's just not added. I added them to Genisys, but then 0.16 made a mess of everything so I haven't bothered doing so here yet.

**Comment by Rover656** [comment]
Any chance of fixing soon?

**Comment by SOF3** [comment]
Seems this issue is of very low priority. Who cares about the sound effects of block breaking after all?

**Comment by dktapps** [comment]
Merging into #158
