### ISSUE TITLE
Double login to the server from the same nickname (2)

### ISSUE THREAD

**Issue by MrBlasyMSK** [pmmp/PocketMine-MP#4906]
### Issue description

- Expected result: That the message "Player x has connected" will be displayed only 1 time
- Actual result: The message is displayed 2 times, although I have not been able to reproduce it on Windows10, only on Android.

### Steps to reproduce the issue
1. Log in to the server
2. If you are unlucky, the connected player's message will appear twice.

### OS and versions

* PocketMine-MP: 4.2.3 (git hash: 6c1c0c867e178f8da8b266e962ca13f4b4280ab4)
* PHP: 8.0.16
* Using JIT: no
* Server OS: linux
* Game version: Android11

### Plugins
Plugins (61): AdvanceDeaths v3.5, Alias v1.4.1, AntiCombatLog v1.0.0, BedrockEconomy v2.0.7, BetterBan v4.1.2, BetterMute v1.0.0, BlockLagFix v1.0.1, BuilderTools v1.4.0-dev, CapesLocker v1.2.0, ChatThin v1.3.0, CommandSpy v1.0.4, CropGrowth v2.0.1, Crossbow v2.0.0, CustomBow v0.0.1, CustomMessages v1.0.1, DeathPosition v1.2, DevTools v1.15.0, Disguise v1.0.0, FactionMaster v4.2.1, Football v2.0.0, FormAPI v2.1.0, ImageOnMap v1.0.2, InvSee v2.0.1, ItemFactory v1.0.2, ItemLifeTime v0.1.0, JailMate v1.1.7, KygekPingTPS v2.0.0, LiveXYZ v1.0.0, MOTDShuffle v1.3.0, MentionSound v0.1.0, Mobs v1.1.0, MultiWorld v1.7.0-beta4, MyPlot v2.1.0, Netherite v2.3, NoAdvertisings v0.0.6, NoVoid v1.0.0, PersonaAdapter v1.0.1, PiggyCustomEnchants v3.0.0, PlayerTags v2.0.0, PureChat v2.0.1, PurePerms v2.0.2, PurePermsScore v2.0.0, RedstoneCircuit v3.0.3, ReportSystem v2.1.0, SayWelcome v1.0.1, ScoreHud v7.0.0, Shield v1.5.0, SimpleLay v3.0.1, SimpleNPC v3.0.1, SkinThief v1.0.0, Spyglass v1.0.0, StaffChat v1.0-alpha, TellRaw v2.0.0, VanillaElytra v1.4.0, VanillaHopper v2.0.1, VanillaX v3.0.0, VanishV2 v3.1.0, Weather v1.0.4, Worlds v3.1.0, theSpawn v1.7.0, Voting38 v0.0.1

- If you remove all plugins, does the issue still occur? Yes
- If the issue is **not** reproducible without plugins:
  - Have you asked for help on our forums before creating an issue? X
  - Can you provide sample, *minimal* reproducing code for the issue? If so, paste it in the bottom section X

### Crashdump, backtrace or other files
![158641016-5759842b-413c-46dc-954a-85056d7a69b7](https://user-images.githubusercontent.com/85447029/158901553-dfadb921-cff9-4704-8d3b-1e920af7f761.png)
```
[Server thread/INFO]: [NetworkSession: xx.xx.xxx.xxx xxxxx] Session opened
[Server thread/INFO]: [NetworkSession: xx.xx.xxx.xxx xxxxx] Player: MrBlasyMSK
[Server thread/INFO]: MrBlasyMSK[/xx.xx.xxx.xxx xxxxx] logged in with entity id 2 at (Lobby, 21.4893, 115, -4.4933)
[Server thread/INFO]: [+] MrBlasyMSK se ha conectado
```

**Comment by dktapps** [comment]
Repeated messages like this are a client bug. It happens on Windows in certain conditions too. I don't know why.
