### ISSUE TITLE
Can't change skin

### ISSUE THREAD

**Issue by TheDataLioness** [pmmp/PocketMine-MP#4907]
### Can't change skin in the game

- Expected result: Your skin changes when changing your skin
- Actual result: You change your skin in the pause menu but that won't happen.

### Steps to reproduce the issue
1. Change your skin in the pause menu
2. Skin won't change in-game

### OS and versions

* PocketMine-MP: 4.3.0+dev (Also happens on 4.2.3)
* PHP: 8.0.16
* Using JIT: no
* Server OS: Linux
* Game version: Win 10

I tested this on test.pmmp.io:19132

**Comment by dktapps** [comment]
Does this happen with all skins or only specific ones?

**Comment by TheDataLioness** [comment]
Tested with different types of skins: Marketplace and Custom (Just a local picture file) doesn't work for both.

**Comment by TheDataLioness** [comment]
https://user-images.githubusercontent.com/34657342/159061858-a68b5d54-a6ba-47ce-bcf1-42b83b62d25e.mp4

**Comment by dktapps** [comment]
I don't know if the pause menu updating is expected or not. What matters is that the skin seen by other players (and yourself in 3rd person view) should match the one selected.

**Comment by TheDataLioness** [comment]
It should update in the pause menu.
But it doesn't update at all even outside of the pause menu.

**Comment by TheDataLioness** [comment]
https://user-images.githubusercontent.com/34657342/159062857-441f8e2f-8338-4cdc-bab6-616200d7eb5f.mp4

**Comment by dktapps** [comment]
Can you reproduce this on other servers (e.g. dragonfly, nukkit)?

**Comment by TheDataLioness** [comment]
Yeah let me try

**Comment by TheDataLioness** [comment]
Ah just tried on CubeCraft same issue, Mineville same issue looks like its a Minecraft bug.
Blame Minecraft.
I'm sorry for bothering you.

**Comment by IvanCraft623** [comment]
Is it reproducible in vanilla?

**Comment by dktapps** [comment]
You should test it in vanilla before arriving at that conclusion. It's possible there was some undocumented behaviour change.

**Comment by TheDataLioness** [comment]
Yes I just tested it in Vanilla.
Doesn't work either.

**Comment by IvanCraft623** [comment]
Works for me

**Comment by TheDataLioness** [comment]
Okay so I got it working again as well.
I cleared my whole dressing room.
And I got it to work again.
Which is really weird.
![image](https://user-images.githubusercontent.com/34657342/159067412-77642410-7b55-4270-b5d5-2c1f9b155992.png)

**Comment by TheDataLioness** [comment]
Definitely a bug on Minecraft's side.
Okay I'm sorry for bothering you guys in this issue.

**Comment by dktapps** [comment]
You should report this on https://bugs.mojang.com if it hasn't been already.

**Comment by dktapps** [comment]
FWIW, I wasn't able to reproduce this on 1.18.12.
