### ISSUE TITLE
Add capes to Pocketmine

### ISSUE THREAD

**Issue by MrBlasyMSK** [pmmp/PocketMine-MP#4909]
## Description
1. - Before closing an issue, check whether or not it works.
2. - This is not a Minecraft bug, it is a function that pocketmine has not added, here is a video entering a Nukkit server that if the capes work. https://streamable.com/9vasoq
3. - If you need to check it yourself, go to a default server (Mineplex for example) and you will see that the capes work

**Comment by dktapps** [comment]
This happens because the addition of a cape causes the skin to be converted to Persona format. At the present time I have no intention whatsoever of implementing support for Persona due to the laggy bloated pile of ... that it is.
