### ISSUE TITLE
Server crashed when joining

### ISSUE THREAD

**Issue by MatthieuLeboeuf** [pmmp/PocketMine-MP#4910]
### Issue description
Hello,
The pocketmine server runs under pterodactyl and the files are accessible via ZFS and without ZFS there is no problem.
There is disk space available as well as ram available.

Link to logs: (in server.log) https://haste.matthieul.dev/kaxmv (in console) https://haste.matthieul.dev/svfit

### Steps to reproduce the issue

1. A pocketmine server with the files accessible via ZFS
2. Connect to the server

### OS and versions

- PocketMine-MP: 4.2.3
- PHP: 8.0.15
- Using JIT: no
- Server OS: linux
- Game version: Win10

**Comment by dktapps** [comment]
This happens because your tmp filesystem is full. This has nothing to do with PM. You should contact your server hosting provider.

**Comment by MatthieuLeboeuf** [comment]
Yes but this problem has appeared since PocketMine 4 with PocketMine 3 there is no problem
I asked my host and the tmp is not full

**Comment by MatthieuLeboeuf** [comment]
This problem has appeared since PocketMine 4 with PocketMine 3 there is no problem
The tmp is not full

**Comment by dktapps** [comment]
This code hasn't changed ...

**Comment by MatthieuLeboeuf** [comment]
With PocketMine 3, it works, so it's good that something has been changed.

**Comment by dktapps** [comment]
It's more likely your hosting provider botched something during the update. Please go to our Discord server for further support.
