### ISSUE TITLE
Inaccurate documentation of `Inventory::contains`

### ISSUE THREAD

**Issue by SOF3** [pmmp/PocketMine-MP#4911]
`Inventory::contains` is documented as:

https://github.com/pmmp/PocketMine-MP/blob/fdd42fd15f7c558d5fd2b455c1d5eceab27aa0b9/src/inventory/Inventory.php#L88-L89

However, according to the BaseInventory implementation:

https://github.com/pmmp/PocketMine-MP/blob/fdd42fd15f7c558d5fd2b455c1d5eceab27aa0b9/src/inventory/BaseInventory.php#L104-L111

Apparently it's not checking if it contains any item with the same amount, but to check if there are *totally* so many items with *at least* that amount.

### OS and versions

* PocketMine-MP: fdd42fd15f7c558d5fd2b455c1d5eceab27aa0b9

**Comment by dktapps** [comment]
The documentation of most of those methods leaves a lot to be desired. See also #382

**Comment by dktapps** [comment]
Fixed by a66f966b0861ef6d56e25fd93412e0846b983c6a.
