### ISSUE TITLE
The damage to the stairs is uneven

### ISSUE THREAD

**Issue by MrBlasyMSK** [pmmp/PocketMine-MP#4919]
## Description
I would like to modify the height of the damage when falling on the stairs because the Pocketmine detects the 2nd step of the stairs as if it were a block below, which in minecraft does not happen.

[Video of Minecraft falling at the bottom of the 2nd staircase](https://streamable.com/nvbq62)

[Video of Pocketmine falling at the bottom of the 2nd staircase](https://streamable.com/nu13rr)

## Justification
It can annoy players jumping on the stairs of the mine to get down faster, or in their own homes if they have stairs and want to get down a little faster.

**Comment by dktapps** [comment]
This appears to be the same bug as reported in #4686
