### ISSUE TITLE
world teleport error

### ISSUE THREAD

**Issue by Bubbelwubbel** [pmmp/PocketMine-MP#4920]
### Issue description

- World Teleport goes
- it does not work

### Steps to reproduce the issue
1. idk

### OS and versions

* PocketMine-MP: 4.2.4 (git hash: 05a5e5eac126064583af2e892cb9b3cc0b0a88b6)
* PHP: 8.0.12
* Using JIT: no
* Server OS: Windows10
* Game version: Android/iOS/Win10/Xbox/PS4/Switch

### Plugins
BuildFFA v0.1-DEMO, BuilderTools v1.4.0-dev, CoinsSystem v1.0.0, DevTools v1.15.0+dev, FormAPI v1.0.0, LanguageSystem v1.0.0, MultiWorld v1.7.0-beta4, OnlineTime v1.0.0, PocketManager v1.0.0, RankSystem v1.0.0

### Crashdump, backtrace or other files
[Tue_Mar_22-11.54.29-GMT_2022.log](https://github.com/pmmp/PocketMine-MP/files/8323929/Tue_Mar_22-11.54.29-GMT_2022.log)

**Comment by dktapps** [comment]
⚠️ This issue ticket doesn't have all the required information ⚠️ 
To make it as quick and easy as possible for maintainers to fix your problem, an issue template is provided which lists certain required information. This includes (but is not limited to):

- PocketMine-MP version (use the `version` command)
- PHP version
- Minecraft version and/or edition
- List of all plugins used (use the `plugins` command)

Without this information, your problem cannot begin to be investigated, so the issue will be closed. You may amend this one, or create a new one, providing all the required information using one of the provided [issue templates](https://github.com/pmmp/PocketMine-MP/issues/new/choose).

Help us to help you by providing the information we ask for.
