### ISSUE TITLE
You can interact with Item Frames in Spectator Mode using 'Pick Block' button

### ISSUE THREAD

**Issue by SleepSpace9** [pmmp/PocketMine-MP#4923]
### Interacting with Item Frames in Spectator Mode using 'Pick Block' button

- Expected result: Nothing happens
- Actual result: When you use the 'Pick Block' button on an item frame that contains an item that is not in your inventory, that item will be cloned into your inventory slot 

### Steps to reproduce the issue
1. Change to Specator Mode.
2. Interact with an item frame containing an item that is not in your inventory.
3. You will receive a cloned item from the item frame.

### OS and versions

* PocketMine-MP: 4.2.4
* PHP: 8.0.16
* Using JIT: no
* Server OS: Debian 10 (x86_64)
* Game version: Win10

### Plugins
-none-

**Comment by dktapps** [comment]
Not sure I see why this is a problem.

**Comment by SleepSpace9** [comment]
I don't know if there is any rule about it, but my understanding of gamemode Spectator is that you can observe the world without interacting with it in any way. 

But you are right, on most servers only staff members have access to this gamemode and won't abuse this for item duplication. But if you're using item frames for a shop and players are set to spectator mode after death, they could do so. Same if you don't trust all of your staff. :hand_over_mouth:

Of course it's also easy to block this action using PlayerBlockPickEvent.

**Comment by dktapps** [comment]
I don't see how you can use this for item duplication. There's no way to use the items you acquire unless you change gamemode again.

**Comment by Xd-pro** [comment]
> I don't see how you can use this for item duplication. There's no way to use the items you acquire unless you change gamemode again.

A lot of the time, you do change gamemode again. For example, if a game has a respawn cooldown that uses spectator mode, you'd be able to middle click an item frame and keep the item when you respawn if inventories aren't cleared.

**Comment by dktapps** [comment]
One possible solution is to make `Player->hasFiniteResources()` return true in Spectator mode.

**Comment by SleepSpace9** [comment]
I think this can be closed as of https://github.com/pmmp/PocketMine-MP/pull/5111
