### ISSUE TITLE
The color of the sign becomes glowing

### ISSUE THREAD

**Issue by ShockedPlot7560** [pmmp/PocketMine-MP#4932]
### Issue description

When we color the sign with a dye directly interacting with it, it will transform the color into glowing.

- Expected result: https://youtu.be/fCZoOVeac4M
- Actual result: https://youtu.be/Ko9q0n8yInA

### Steps to reproduce the issue
1. Place and write something in the sign
2. Get a dye and click on the sign
3. The sign will become glowing with the color

### OS and versions

* PocketMine-MP:
* PHP:
* Using JIT: yes/no (delete as appropriate) 
* Server OS:
* Game version: Android/iOS/Win10/Xbox/PS4/Switch (delete as appropriate)

### Plugins

- PocketMine-MP: 4.3.0+dev
- PHP: 8.0.13
- Using JIT: no
- Server OS: windows
- Game version: Win10

**Comment by MrBlasyMSK** [comment]
In addiction, I don't know if it happens to you, when i restart the server, the letters return to their normal color

**Comment by ShockedPlot7560** [comment]
When we use a dye on a sign, yes
