### ISSUE TITLE
I cant play mcpe serveur 

### ISSUE THREAD

**Issue by BXSExample** [pmmp/PocketMine-MP#4934]
### Issue description

- Expected result: I Can play mcpe server but with my 4g
- Actual result: I want to play Minecraft using my connection
### Steps to reproduce the issue
1. ...
2. ...

### OS and versions

* PocketMine-MP:
* PHP:
* Using JIT: yes/no (delete as appropriate) 
* Server OS: Bedoland 
* Game version: Android and Win10

**Comment by MrBlasyMSK** [comment]
> ### Issue description
> * Expected result: I Can play mcpe server but with my 4g
> * Actual result: I want to play Minecraft using my connection
> 
> ### Steps to reproduce the issue
> 1. ...
> 2. ...
> 
> ### OS and versions
> * PocketMine-MP:
> * PHP:
> * Using JIT: yes/no (delete as appropriate)
> * Server OS: Bedoland
> * Game version: Android and Win10

![Screenshot_20220329_133834_com mojang minecraftpe](https://user-images.githubusercontent.com/85447029/160603162-2a3923d6-6cfd-48cd-85f3-b2ca1ab7abeb.jpg)
