### ISSUE TITLE
Current timings system is completely proprietary

### ISSUE THREAD

**Issue by Bqleine** [pmmp/PocketMine-MP#4938]
## Description
The current timings system (Aikar's timings) has multiple problems and should be changed for a more open format.

## Justification
Firstly, the timings format is not clearly documented and is absolutely proprietary, as stated in the project readme :
> The Timings v2 file format is not designed for public use. It is highly condensed and meant to be specially known how to parse it.
This makes it complicated for people to make their own impletations of both the timings server and client.

Secondly, server timings have to be uploaded to aikar's servers because of a lack of alternative implentations, this is an issue as aikar's servers use guessable numbers as identifiers and timings are therefore public and easily searchable with a script, revealing information server might want to keep private (mostly the plugin list).

## Solution
My ideal solution would be to have a newer, possibly better or similar file format that would be less of a mess and better documented.
If making a new timing viewer is a problem, I already have a small [working implentation](https://github.com/Bqleine/timings-viewer) of Aikar's timings that could easily be adapted for a new format.

**Comment by dktapps** [comment]
PM doesn't use the timings v2 system, for this exact reason. You should do some more research before writing an issue.

**Comment by Bqleine** [comment]
Thanks for reading my issue. I did use a quote from timings v2 (my bad) but the problem stays the same, the timings v1 fomat is undocumented and can be scraped when uploaded, which is almost obligatory due to the lack of alternate implementations (due to the lac of format documentation etc...).

The format should at least be documented even if it stays the same.

**Comment by dktapps** [comment]
The v1 format is trivial and can be analysed just by looking at it. I hardly think it's necessary.
