### ISSUE TITLE
Hitboxes problem

### ISSUE THREAD

**Issue by F4nX1ngCN** [pmmp/PocketMine-MP#4958]
Issue description

I’m a staff from a pvp server.I got hit by other players when I was swim in the water.And my hitbox become smaller,it allows me to through a hole of 1block height.

Steps to reproduce the issue
1. Swim in the water 
2. Get damages

OS and versions
* PocketMine-MP: 4.3.0+dev
* PHP: 8.0.13
* Server OS: Linux
* Game version: iOS

 Plugins

- If you remove all plugins, does the issue still occur?
- If the issue is **not** reproducible without plugins:
  - Have you asked for help on our forums before creating an issue?
  - Can you provide sample, *minimal* reproducing code for the issue? If so, paste it in the bottom section

In fact I don’t have the console so I can’t do that.I’m sorry.

 Crashdump, backtrace or other files

**Comment by dktapps** [comment]
Update your server. This was long since fixed.
