### ISSUE TITLE
Throwing splash potions while targeting a block leaves a ghost item

### ISSUE THREAD

**Issue by Xd-pro** [pmmp/PocketMine-MP#4961]
### Issue description
Throwing splash potions while targeting a block should remove the item from your inventory.
- Expected result: What were you expecting to happen?
The potion is thrown and the item disappears
- Actual result: What actually happened?
The potion is thrown, but a ghost item remains

### Steps to reproduce the issue
Throw a potion while targeting a block

### OS and versions
* PocketMine-MP: 4.2.6
* PHP: 8.0.15
* Using JIT: no 
* Server OS: linux
* Game version: Win10

### Plugins
None

- If you remove all plugins, does the issue still occur?
Yes

### Crashdump, backtrace or other files
Example video: https://streamable.com/h3h0ru

**Comment by dktapps** [comment]
You're sure this is on the latest version? A similar issue was fixed very recently.

**Comment by dktapps** [comment]
This is the same issue as #4894 and has already been resolved in the upcoming 4.2.7 release.
