### ISSUE TITLE
Server crashed

### ISSUE THREAD

**Issue by Joshiiiii** [pmmp/PocketMine-MP#4964]
**Issue description**
When having lots of plugins on my server, the server crashes when being started, and I need to force kill the process.
The issue doesn't happen every server start, just around every 3-4 starts.

**OS and versions**
- PocketMine-MP: 4.2.6
- PHP: 8.0.15
- Using JIT: no
- Server OS: Linux

**Plugins**
There are lots of plugins on the server. I tried several hours to specify it on one plugin, but it seems to be a general issue.

**If you remove all plugins, does the issue still occur?**
No, since this issue seems to be connected to the plugin loader. Without any plugin, it works fine.

**Crashdump, backtrace or other files**
Crashdump: https://pastebin.com/b9mHQUtt
![Screenshot of crash](https://user-images.githubusercontent.com/49375131/163565911-8200c5eb-927b-4a45-8612-0d6566fe7182.png)

**Comment by dktapps** [comment]
There's nothing I can do without specific information on what caused this.

**Comment by Joshiiiii** [comment]
What specific information can I provide to you? I don‘t think that the list of plugins plays any role in this issue since it sometimes works with the list of plugins and sometimes don‘t.

**Comment by dktapps** [comment]
I don't think the cars on the road have anything to do with road accidents, because sometimes road accidents don't happen ...

**Comment by Xd-pro** [comment]
Could you try to use empty plugins, to check if it's the loader's fault? You can generate blank plugins using devtools and the /genplugin command.

**Comment by SOF3** [comment]
Do you have some sort of auto updater for the server or otherwise processes that may be interfering with the PocketMine phar? What platform are you using to run the server? Is it containerized? Please provide more information on your environment.

**Comment by Joshiiiii** [comment]
Thanks for your help @Xd-pro and @SOF3! So I figured out that it has something to do with the libasynql Virion, which I used. Seems like there are different Plugins which use different versions of the virion.

Would be helpful to see that in the error message instead of an error from Pocketmine.

**Comment by Joshiiiii** [comment]
I fixed it by injecting the right virions directly into the phars(which is also strongly advised, ik)
