### ISSUE TITLE
TextPacket vulnerabilities

### ISSUE THREAD

**Issue by StefanFox-Dev** [pmmp/PocketMine-MP#4974]
### Issue description

- Actual result: crash

### Steps to reproduce the issue
1. Turn on the bot through a proxy 
2. We go to the server with a proxy 
3. We send the package "TextPacket" count message: 99999999999/second.
4. Ready! The server lay down for 30 minutes, nothing works, there is no crash and it will only save reboot VDS

### OS and versions
* PocketMine-MP: 0.0.1 - 4.2.9
* PHP: 7.0.1 - 8.0.17
* Using JIT: yes/no
* Server OS: Ubuntu 20.04
* Game version: Android/iOS/Win10/Xbox/PS4/Switch

### Plugins

Plugins null.

### Crashdump, backtrace or other files
No crash server.

### FIX PROBLEM:
`public function onCrashGuard(DataPacketReceiveEvent $ev){
		
if($ev->getPacket() instanceof TextPacket){
if(mb_strlen($ev->getPacket()->message) > 500){
 var_dump(mb_strlen($ev->getPacket()->message));
 $ev->getOrigin()->getPlayer()->kick('Off bot please!');
$ev->cancel();
              }
         }
    }`

### BOT:
![o0sqFLqevnexKfTqdyvLns309KSVPTdsqjRKZVEGKHy5m05YHldxZvCUxbhd0RPDCUgVRtMLzJzyomwWgxydpCpp](https://user-images.githubusercontent.com/59245729/164200154-bea9c243-3a75-49a6-b8b7-cae8c33f7f94.jpg)
![A_6JlISh_rMmgT6GjwI5UHEStOceVlhoKBA0yEtyEn6n4HeQOD24aUvLM-a1KNzy4060LBWw_bAQENd7qPf7L5s4](https://user-images.githubusercontent.com/59245729/164200159-287cb1be-c97d-42f4-a1fe-0abefbe544e9.jpg)

## PROBLEM:
Stupidly the server is frozen, it works everywhere, any server! Therefore, I leaked a fix to you :) 
![XZ5m_i5oOr3FC3x10KJSgEE6PgVfQHo6fgWzY72Ipi-uq9Usf9kARnAuk_KSebNPnras0jwFD7C-Ne7OMex33W8H](https://user-images.githubusercontent.com/59245729/164200602-d27ecc69-e347-4eda-ac0c-e78bb9bedfea.jpg)

**Comment by dktapps** [comment]
well done, you just advertised this "vulnerability" to 300 people ...

**Comment by StefanFox-Dev** [comment]
How else could it be written?

**Comment by Nerahikada** [comment]
See [SECURITY.md](https://github.com/pmmp/PocketMine-MP/blob/624a7dff16589734d017fd76f590da24796e88db/SECURITY.md)

**Comment by StefanFox-Dev** [comment]
It's clear

**Comment by Tara1237284** [comment]
Delete

**Comment by StefanFox-Dev** [comment]
> ### Issue description
> * Actual result: crash
> 
> ### Steps to reproduce the issue
> 1. Turn on the bot through a proxy
> 2. We go to the server with a proxy
> 3. We send the package "TextPacket" count message: 99999999999/second.
> 4. Ready! The server lay down for 30 minutes, nothing works, there is no crash and it will only save reboot VDS
> 
> ### OS and versions
> * PocketMine-MP: 0.0.1 - 4.2.9
> * PHP: 7.0.1 - 8.0.17
> * Using JIT: yes/no
> * Server OS: Ubuntu 20.04
> * Game version: Android/iOS/Win10/Xbox/PS4/Switch
> 
> ### Plugins
> Plugins null.
> 
> ### Crashdump, backtrace or other files
> No crash server.
> 
> ### FIX PROBLEM:
> `public function onCrashGuard(DataPacketReceiveEvent $ev){
> 
> if($ev->getPacket() instanceof TextPacket){ if(mb_strlen($ev->getPacket()->message) > 500){ var_dump(mb_strlen($ev->getPacket()->message)); $ev->getOrigin()->getPlayer()->kick('Off bot please!'); $ev->cancel(); } } }`
> 
> ### BOT:
> ![o0sqFLqevnexKfTqdyvLns309KSVPTdsqjRKZVEGKHy5m05YHldxZvCUxbhd0RPDCUgVRtMLzJzyomwWgxydpCpp](https://user-images.githubusercontent.com/59245729/164200154-bea9c243-3a75-49a6-b8b7-cae8c33f7f94.jpg) ![A_6JlISh_rMmgT6GjwI5UHEStOceVlhoKBA0yEtyEn6n4HeQOD24aUvLM-a1KNzy4060LBWw_bAQENd7qPf7L5s4](https://user-images.githubusercontent.com/59245729/164200159-287cb1be-c97d-42f4-a1fe-0abefbe544e9.jpg)
> 
> ## PROBLEM:
> Stupidly the server is frozen, it works everywhere, any server! Therefore, I leaked a fix to you :) ![XZ5m_i5oOr3FC3x10KJSgEE6PgVfQHo6fgWzY72Ipi-uq9Usf9kARnAuk_KSebNPnras0jwFD7C-Ne7OMex33W8H](https://user-images.githubusercontent.com/59245729/164200602-d27ecc69-e347-4eda-ac0c-e78bb9bedfea.jpg)

**Comment by dktapps** [comment]
It's too late for that. Anyone receiving email notifications now knows about this problem, as well as anyone paying attention to our Discord server.
