### ISSUE TITLE
Item drop pickup trigger.

### ISSUE THREAD

**Issue by Muqsit** [pmmp/PocketMine-MP#498]
### Issue description

Items dropped cannot be picked up by a player unless they are showing "movement" (yaw/pitch included).
If the player isn't moving, they can't pick up any item, whatever be the item's distance from the player.
I am assuming this has always been an issue as it exists in all pocketmine-based forks (hah, "forks").

### Steps to reproduce the issue

1. Look down.
2. Drop an item.
3. Do NOT move.
4. Wait for an eternity.

### OS and versions

* PocketMine-MP: cd47716
* PHP: 7.0.17
* Server OS: Ubuntu 14.04 64-bit
* Game version: Win10 (Irrelevant)

### Crashdump, backtrace or other files

-=-

**Comment by dktapps** [comment]
I expect this is because PocketMine isn't doing near-entity checks unless the player has moved on that tick.

**Comment by Muqsit** [comment]
Yeah, checkNearEntities() executed inside Player::processMovement(). That might be it.

**Comment by dktapps** [comment]
I've pushed the fix for this to the network branch since I don't have a 1.0.4 device to test this currently.

**Comment by TheDiamondYT1** [comment]
@dktapps Dont you have android?

**Comment by dktapps** [comment]
... and I'm not downgrading for the sake of testing a simple fix.

**Comment by TheDiamondYT1** [comment]
It only take like 2 minutes
