### ISSUE TITLE
Space on tchat (\n)

### ISSUE THREAD

**Issue by xodamcm** [pmmp/PocketMine-MP#4980]
With purechat plugin, with 4.3.0, not on other version, and this just happen woth purechat, when player send message on chat, they have this message and a empty message (\n)

- Expected result: What were you expecting to happen?
- Actual result: What actually happened?

### Steps to reproduce the issue
1. ...
2. ...

### OS and versions

* PocketMine-MP:
* PHP:
* Using JIT: yes/no (delete as appropriate) 
* Server OS:
* Game version: Android/iOS/Win10/Xbox/PS4/Switch (delete as appropriate)

### Plugins

- If you remove all plugins, does the issue still occur?
- If the issue is **not** reproducible without plugins:
  - Have you asked for help on our forums before creating an issue?
  - Can you provide sample, *minimal* reproducing code for the issue? If so, paste it in the bottom section

**Comment by StefanFox-Dev** [comment]
This was introduced in 4.2.10, it is necessary to fix a critical bug on the kernel side.
