### ISSUE TITLE
failed command args

### ISSUE THREAD

**Issue by Bubbelwubbel** [pmmp/PocketMine-MP#4982]
### Issue description

- That the args are not displayed, because it is not really necessary.
- Args are displayed although it is not necessary.

### Steps to reproduce the issue
1. Join the server
2. Open the chat
3. enter /ver or a command as desired
4. Example images at /ver, /ban and /mw (MultiWorld) (See below!!!!)

### OS and versions
* PocketMine-MP: 4.3.0 (git hash: e4ce467c0ba22e8e9f0300bd5d375a0728369813)
* PHP: 8.0.13
* Using JIT: no
* Server OS: linux
* Game version: Android/iOS/Win10/Xbox/PS4/Switch

### Plugins
DevTools v1.15.0, EasyEdit v2.1.0-dev, Fly v0.1, MultiWorld v1.7.0-beta4

- If you remove all plugins, does the issue still occur?
  Yes

### Crashdump, backtrace or other files
![image](https://user-images.githubusercontent.com/65186341/164555453-dafbef43-a7ff-4ead-ae47-2c5db285c4b6.png)
![image](https://user-images.githubusercontent.com/65186341/164555495-214847cf-150e-4c70-a68e-011415c2ec74.png)
![image](https://user-images.githubusercontent.com/65186341/164555528-0a38dd6c-8e6d-48e3-a16f-ba8c3a4ba209.png)

**Comment by jasonw4331** [comment]
Related to https://github.com/pmmp/BedrockProtocol/pull/60

**Comment by Bubbelwubbel** [comment]
Ah okay, thanks. I have not seen.
