### ISSUE TITLE
Player doesnt teleport clientside

### ISSUE THREAD

**Issue by LuciaDX** [pmmp/PocketMine-MP#4985]
Im teleporting player to respawn point when it receives fatal hit, but if i hit fast, player doesnt teleport on my screen only on server 
This wont happen if i hit it 1 time per 1-2 seconds

**Comment by dktapps** [comment]
⚠️ This issue ticket doesn't have all the required information ⚠️ 
To make it as quick and easy as possible for maintainers to fix your problem, an issue template is provided which lists certain required information. This includes (but is not limited to):

- PocketMine-MP version (use the `version` command)
- PHP version
- Minecraft version and/or edition
- List of all plugins used (use the `plugins` command)
- **Most importantly, clear steps to reproduce the problem.**

Without this information, your problem cannot begin to be investigated, so the issue will be closed. You may amend this one, or create a new one, providing all the required information using one of the provided [issue templates](https://github.com/pmmp/PocketMine-MP/issues/new/choose).

Help us to help you by providing the information we ask for.
