### ISSUE TITLE
Player doesnt teleport clientside

### ISSUE THREAD

**Issue by LuciaDX** [pmmp/PocketMine-MP#4986]
### Issue description

- Expected result: Player will teleport on my screen
- Actual result: Player stays where he died on my screen but not on server

### Steps to reproduce the issue
1. Create player damage listener
2. Teleport player when he receives fatal hit
3. Hit this player very fast

### OS and versions
* PocketMine-MP: 4.3.0
* PHP: 8.0.17
* Using JIT: no
* Server OS: Ubuntu 18.04
* Game version: Android/iOS/Win10/Xbox/PS4/Switch

### Plugins
 - 

- If you remove all plugins, does the issue still occur?
yes

### Crashdump, backtrace or  other files
![Screenshot_7](https://user-images.githubusercontent.com/82135652/164894214-f3975b2f-bc58-4442-bc7b-5b174d18882c.png)
![Screenshot_6](https://user-images.githubusercontent.com/82135652/164894203-5bc0c8ea-29e6-4aa9-ac75-ba4062880b9b.png)

**Comment by LuciaDX** [comment]
duplicate of #4394

**Comment by dktapps** [comment]
That issue is supposed to be fixed already ...

**Comment by LuciaDX** [comment]
> That issue is supposed to be fixed already ...

idk latest pocketmine ver and i still get this bug

**Comment by dktapps** [comment]
The other issue you referenced is closed as fixed. If you're having this problem on the latest version, it's not the same bug.

**Comment by dktapps** [comment]
This is likely related to the workaround for #4394.
