### ISSUE TITLE
Incomplete drop of leaves

### ISSUE THREAD

**Issue by ShockedPlot7560** [pmmp/PocketMine-MP#4988]
### Issue description

- Expected result: Leaves drop sticks
- Actual result: Leaves drop only saplings

### Steps to reproduce the issue
1. Place leaves
2. Wait and see

### OS and versions
* PocketMine-MP: 4.3.2
* PHP: 8.0.13
* Using JIT: no
* Server OS: windows
* Game version: Win10

### Plugins

- If you remove all plugins, does the issue still occur? yes

**Comment by IvanCraft623** [comment]
According to the wiki also Jungle Leaves have a chance of: 2.5% (1⁄40). Pocketmine applies a 5% (1⁄20) chance to all leaves.
https://minecraft.fandom.com/wiki/Leaves#Breaking

**Comment by dktapps** [comment]
Implemented by #5019. Other drop problems should be reported as separate issues.
