### ISSUE TITLE
Player drowns when sprint-swimming on the surface of water

### ISSUE THREAD

**Issue by HackMaster1910** [pmmp/PocketMine-MP#4989]
## Description

In minecraft if you swim with your head above water the drowning effect goes away. However in pocketmine you still drown even with your head above water. 

## Justification

It's useful for SMPs as if you were swimming with your head above water because you were chasing someone, everyone would drown (which isn't great.)

**Comment by HackMaster1910** [comment]
![image](https://user-images.githubusercontent.com/80475386/164967742-6015bd74-2db1-4ec2-8823-b03e3f9c1d2f.png)

**Comment by ghost** [comment]
I think this is up for discussion. Indeed, in Vanilla, the hit-box goes out from water a little so that there is something to breathe.  And then server have to do the calculation of this? Or does the server still do the calculations incorrectly?

**Comment by HackMaster1910** [comment]
I am really not sure. I will go through the API to see if I can find anything.

EDIT: I haven't found anything yet related to calculating the hitbox.

**Comment by ghost** [comment]
> I am really not sure. I will go through the API to see if I can find anything.
> 
> EDIT: I haven't found anything yet related to calculating the hitbox.

Actually, they are, look in airSupply.

**Comment by dktapps** [comment]
This is most likely the fault of `Entity->isUnderwater()`, which uses the eye height to determine whether the entity's head is underwater. Perhaps the eye height when swimming is incorrect.
