### ISSUE TITLE
Problem Human

### ISSUE THREAD

**Issue by StefanFox-Dev** [pmmp/PocketMine-MP#4991]
### Issue description

- Expected result: Join server
- Actual result: crash

### Steps to reproduce the issue
1. Join server
2. Crash...

### OS and versions
* PocketMine-MP: 4.3.1
* PHP: 8.0.16
* Using JIT: yes
* Server OS: Ubuntu 20.04
* Game version: Android/iOS/Win10/Xbox/PS4/Switch

### Plugins
I have plugins: 1, "Pets".

### Crashdump, backtrace or other files
![Screenshot_20220425-133749_Cx File Explorer](https://user-images.githubusercontent.com/59245729/165078525-a7273b4b-ba7c-470a-9d1c-2d0de80ebcd7.jpg)

**Comment by dktapps** [comment]
This is insufficient information to reproduce the problem.

**Comment by StefanFox-Dev** [comment]
![Screenshot_20220425-133205_JuiceSSH](https://user-images.githubusercontent.com/59245729/165079606-6e1d569a-0a42-475f-81b7-9715418b7d40.jpg)

**Comment by dktapps** [comment]
Until such a time as you can provide reliable reproducing steps for this issue, it's not going to be investigated since there's nothing I can meaningfully do about it.

**Comment by StefanFox-Dev** [comment]
Do I know where the error comes from?

**Comment by Tara1237284** [comment]
God knows.

**Comment by Tara1237284** [comment]
Therts knows where

**Comment by StefanFox-Dev** [comment]
I bought a pet and left the server, logged in - everything is fine, restarting the server - and then I can't log in, crash.
