### ISSUE TITLE
Problem from Brewing Stand

### ISSUE THREAD

**Issue by StefanFox-Dev** [pmmp/PocketMine-MP#4997]
### Issue description

- Expected result: Give it to the player in the store through ItemFactory, but received an unknown block. 
- Actual result: The block is strange, but you can put it.
- 
![20220426_132939](https://user-images.githubusercontent.com/59245729/165281240-f2fc7973-f920-4d97-a369-00591ec10af3.jpg)
![Screenshot_20220426-114112_Minecraft](https://user-images.githubusercontent.com/59245729/165281305-b3ee941c-3e0c-4ef6-818e-b63beaf69c23.jpg)

### Steps to reproduce the issue
1. $sender->getInventory()->addItem(ItemFactory::getInstance()->get(117, 0, 1));
2. We get a block without a texture, but it functions. 

### OS and versions
* PocketMine-MP: 4.3.1
* PHP: 8.0.16
* Using JIT: yes
* Server OS: Ubuntu 20.04
* Game version: Android/iOS/Win10/Xbox/PS4/Switch

### Plugins
- If you remove all plugins, does the issue still occur? — Yes.

### Crashdump, backtrace or other files
No crash.

**Comment by ArkaziaMC** [comment]
use VanillaItems and VanillaBlocks
