### ISSUE TITLE
Custom entity(Human)

### ISSUE THREAD

**Issue by Xiaoming0313883** [pmmp/PocketMine-MP#4999]
### Issue description

- Custom human entity have some problem when updated to latest version
- In previous version(4.0) it work well but since I updated to the latest version, this bug appear
- Entity blinking if teleport repeatly, it didn't happen in previous version
- In player list, it will appear that custom entity name also
- the resources pack of minecraft also broke when that bug appear

### Steps to reproduce the issue
1. Create a custom entity
2. On onupdate function, teleport repeatly

### OS and versions

* PocketMine-MP: 4.3.1
* PHP: 8
* Using JIT: no
* Server OS: Windows 10
* Game version: Win10

![image](https://user-images.githubusercontent.com/85933240/165515247-e3df43d3-1c93-4ddd-a5db-90bb52dd5755.png)

https://user-images.githubusercontent.com/85933240/165515435-ada4cc6e-0c75-4b61-9d1d-81cbadba49d4.mp4

plugin that I used to test:
[test.zip](https://github.com/pmmp/PocketMine-MP/files/8571838/test.zip)

This kind of thing didn't appear in previous version ( >4.0, <4.3.1 ), maybe is my fault? Tell me if is ;-;

**Comment by Xiaoming0313883** [comment]
The previous version that I use is 4.2.4, this bug appear after update to latest(4.3.1)

**Comment by dktapps** [comment]
This is caused by https://github.com/pmmp/PocketMine-MP/commit/d1dfbd95e2bc01e63d252fe077f2906ca6977005.

Since this problem is very minor compared to the annoying issues caused by the original problem, I don't plan on fixing this issue.
