### ISSUE TITLE
Falling Block instantly fall when a falling Block in a cobweb

### ISSUE THREAD

**Issue by crischutu07** [pmmp/PocketMine-MP#5000]
### Issue description

- Expected result: What were you expecting to happen? When place a cobweb below a air with a fallable block (ex: sand, anvil) in the head of cobweb, is will instantly fall 
- Actual result: When I setup my server done I try doing a bug like expected I said

### Steps to reproduce the issue
1. Setup Server
2. Open Minecraft 
3. Joining server
4. Doing a bug

### OS and versions

* PocketMine-MP: 4.3.1
* PHP: 8.0
* Using JIT: no (delete as appropriate) 
* Server OS: Linux (Ubuntu 20.04)
* Game version: 1.18.30 Android/iOS/Win10/Xbox/PS4/Switch (delete as appropriate)

### Plugins

- If you remove all plugins, does the issue still occur? Yes
- If the issue is **not** reproducible without plugins:
  - Have you asked for help on our forums before creating an issue? yes
  - Can you provide sample, *minimal* reproducing code for the issue? If so, paste it in the bottom section

**Comment by crischutu07** [comment]
My issues (if it's hard to understand)
[Here](https://youtu.be/S-fDofrRCu0)

**Comment by dktapps** [comment]
Duplicate of #4818
