### ISSUE TITLE
the hitbox doesn't get bigger when exiting the water.

### ISSUE THREAD

**Issue by Wayder228** [pmmp/PocketMine-MP#5002]
### Issue description

- Expected result: The player will exit swim mode and the hitbox will be normal.
- Actual result: The player entered the water and swam

### Steps to reproduce the issue
1. Fix it.
2. Or make the hitbox big when swimming as when walking, it will cause less problems.

### OS and versions

* PocketMine-MP: 4.2.0 
* PHP: 8.0
* Using JIT: yes/no (delete as appropriate) 
* Server OS: linux
* Game version: Android/iOS/Win10/Xbox/PS4/Switch (delete as appropriate)

### Plugins

- If you remove all plugins, does the issue still occur?
- If the issue is **not** reproducible without plugins:
  - Have you asked for help on our forums before creating an issue?
  - Can you provide sample, *minimal* reproducing code for the issue? If so, paste it in the bottom section

**Comment by dktapps** [comment]
4.2.0 is outdated. The issue was fixed in 4.2.1.
