### ISSUE TITLE
Items not stacking to appropriate max stack size in inventory transactions

### ISSUE THREAD

**Issue by NickteeChunky** [pmmp/PocketMine-MP#5010]
### Issue description

- Expected result: The override item (which I set its stack size to 1) to not stack up till its original stack size (64).
- Actual result: It stacked above 1.

### Steps to reproduce the issue
1. Register an override class for an existing item.
2. Adjust getMaxStackSize to return a number lower than of the existing item's (1 in this case).
3. Add two of the item to your inventory.
4. Drag and drop the items onto each other.

### OS and versions

* PocketMine-MP: 4.3.1
* PHP: 8.0.8
* Using JIT: no
* Server OS: Windows
* Game version: Windows
  - Other plugins not affecting results.
  - Can you provide sample, *minimal* reproducing code for the issue? If so, paste it in the bottom section

Main:
```PHP
ItemFactory::getInstance()->register(new TestFeather(new ItemIdentifier(ItemIds::FEATHER, 0), "Feather"), true);
```
TestFeather:
```PHP
<?php

declare(strict_types=1);

namespace NickteeChunky\items;

use pocketmine\item\Item;

class TestFeather extends Item {

    public function getMaxStackSize(): int
    {
        return 1; // default 64
    }
}
```

https://user-images.githubusercontent.com/31430653/166393539-50457fac-d1ce-4c3c-b093-6e4b1d4bb757.mp4

**Comment by SenseiTarzan** [comment]
It 's normal because is client to say yeah you can stacked this item. the serveur don't is responsable of to stack system  item.
Sorry if my english is bad

**Comment by dktapps** [comment]
This is expected behaviour. The server has no way to inform the client of the altered max stack size.

**Comment by IvanCraft623** [comment]
> This is expected behaviour. The server has no way to inform the client of the altered max stack size.

I think the server should reverse it.
