### ISSUE TITLE
Open chest and player inventory at the same time makes players can't open any inventory

### ISSUE THREAD

**Issue by AkmalFairuz** [pmmp/PocketMine-MP#5021]
### Issue description

- Expected result: Inventory open
- Actual result: Inventory won't open

### Steps to reproduce the issue
1. Place a chest
2. Open chest and open player inventory (Right click chest & press E) at the same time
3. Open player inventory or another inventory (chest)

### OS and versions
(Tested on test.pmmp.io:19132)
* PocketMine-MP: 37f0ccd
* PHP: 8.0.16
* Server OS: linux
* Game version: Windows

### Crashdump, backtrace or other files
https://cdn.discordapp.com/attachments/546255162222706696/972558300644278332/2022-05-08_00-54-11.mp4

**Comment by dktapps** [comment]
I'm not too sure how this should be handled. Opening and closing inventories in quick succession is quite flaky right now.

**Comment by AkmalFairuz** [comment]
I solved this problem by sending a ContainerClosePacket every ContainerOpenPacket sent (but this is not good solution, at least the player don't need to rejoin the server to fix the problem)
```php
if($packet->windowId !== 92) {
      $target->sendDataPacket(ContainerClosePacket::create(92, false)); // 92 = player inventory window id
}
```

This usually happens when player opening player and chest inventory during the player lag.
