### ISSUE TITLE
`SignUpdateEvent::getOldText()` will return a array with empty-strings

### ISSUE THREAD

**Issue by supercrafter333** [pmmp/PocketMine-MP#5035]
### Issue description

- Expected result: The "old-text" should be the text that the player had write on the sign.
- Actual result: The "new-text" is now the text that the player had write on the sign.

### Steps to reproduce the issue
1. Place a sign and write something on it
2. dump the old and the new text

### OS and versions

* PocketMine-MP: 4.3.2
* PHP: 8.0.17
* Using JIT: no
* Server OS: Linux Ubuntu 20.04
* Game version: Win10/Win11/Android

### Plugins
The bug still occour with and without plugins.

### Crashdump, backtrace or other files
nothing

**Comment by dktapps** [comment]
This is expected due to a change in client behaviour in 1.18.30.

**Comment by supercrafter333** [comment]
WHat should plugin-developers do now?

**Comment by dktapps** [comment]
If anything this change is good for plugin developers. I don't see any problem.

**Comment by supercrafter333** [comment]
What's about remove getOldText() and getNewText() and replace it with anything like `getText()`?

**Comment by dktapps** [comment]
That's an API break.

**Comment by supercrafter333** [comment]
PM5?

**Comment by dktapps** [comment]
The behaviour might still be changed again by Mojang. PM5 is a long time away. I won't make such hasty API decisions based on one version.

**Comment by supercrafter333** [comment]
Okay
