### ISSUE TITLE
Custom Crafting Recipes doesn't work

### ISSUE THREAD

**Issue by Crasher508** [pmmp/PocketMine-MP#5036]
### Issue description

- If I put a custom crafting recipe in the crafting table and execute the craftig with a click in the output slot, everythink works fine, if I click the item from output and want to put them in the player inventory they disappears
- https://youtu.be/tvOuT5Wfad0
- https://youtu.be/9sPoiguWI1Q

### Steps to reproduce the issue
1. create a custom shapedrecipe (like: https://pastebin.com/J4wpXTam)
2. put all items correct in the crafting table
3. start to craft
4. look in the videos, there you see everythink

### OS and versions

* PocketMine-MP: 4.3.3+dev
* PHP: 8.0.13
* Using JIT: no
* Server OS: linux/win
* Game version: Win10

### Plugins
- Custom recipe test
https://pastebin.com/J4wpXTam

**Comment by dktapps** [comment]
It won't work unless you do it before the player joins. You can't register recipes during gameplay.

Side note: You can get a block as an item by `VanillaBlocks::CHEST()->asItem()`; it's not necessary to use ItemFactory.

**Comment by Crasher508** [comment]
https://pastebin.com/xhH1HnMN will called in onEnable(), it works fine before a small time
