### ISSUE TITLE
Server crashed

### ISSUE THREAD

**Issue by LordBombardir** [pmmp/PocketMine-MP#5037]
Link crashdump: https://pastebin.com/DifF1uhm

In the getPlayer method, the Player object is obtained in the PlayerJoinEvent class.
When calling the following method, where this object is required, but the server receives an error that the player did not connect to the server. Why?

Note: this does not always happen, only in some cases.

**Comment by ipad54** [comment]
#4594

**Comment by LordBombardir** [comment]
> #4594

Я его не кикаю из игры.

**Comment by LordBombardir** [comment]
I can't even get a typical player name

**Comment by LordBombardir** [comment]
Logged in with Windows 10

> Link crashdump: https://pastebin.com/DifF1uhm
> 
> In the getPlayer method, the Player object is obtained in the PlayerJoinEvent class. When calling the following method, where this object is required, but the server receives an error that the player did not connect to the server. Why?
> 
> Note: this does not always happen, only in some cases.

**Comment by StefanFox-Dev** [comment]
Show the code

**Comment by LordBombardir** [comment]
> Show the code

public function PlayerJoinEvent(PlayerJoinEvent $event) : void
    {
        Server::getInstance()->getLogger()->notice('Testing: ' . $event->getPlayer()->getName());
    }

**Comment by SOF3** [comment]
Thanks, but this issue tracker is not intended for support requests. Please read the guidelines on [submitting an issue](https://github.com/pmmp/PocketMine-MP/blob/master/CONTRIBUTING.md#creating-an-issue).

[Docs](https://pmmp.rtfd.io) | [Discord](https://discord.gg/bmSAZBG) | [Forums](https://forums.pmmp.io)
