### ISSUE TITLE
What? Skins bug...

### ISSUE THREAD

**Issue by StefanFox-Dev** [pmmp/PocketMine-MP#5038]
### Issue description

- Expected result: There is nothing complicated, just go to the server. 
- Actual result: As a result, he was left without a skin.
- This problem exists for more than a year, and no one is going to fix it?
![Screenshot_20220515-170404_Minecraft](https://user-images.githubusercontent.com/59245729/168478305-a720ebf8-afaf-4372-8747-47ca03f67d86.jpg)

### Steps to reproduce the issue
1. Join server

### OS and versions

* PocketMine-MP: 3.15.0-4.3.2
* PHP: 7.0-8.0
* Using JIT: yes
* Server OS:
* Game version: Android/iOS/Win10/Xbox/PS4/Switch

### Plugins

No use plugins.

### Crashdump, backtrace or other files

No crash.
![Screenshot_20220515-170353_Minecraft](https://user-images.githubusercontent.com/59245729/168478262-0aaccf2c-c576-4103-90ab-e1ab78211872.jpg)

**Comment by jasonw4331** [comment]
Install a persona skins plugin

**Comment by StefanFox-Dev** [comment]
Why do I need steves if I want my own skin? There is no such bullshit in 1.14

**Comment by alvin0319** [comment]
https://github.com/pmmp/PocketMine-MP/blob/stable/changelogs/3.10.md#note-about-skins

**Comment by StefanFox-Dev** [comment]
Ohh
