### ISSUE TITLE
Furnace error and server crashing

### ISSUE THREAD

**Issue by kabluinc** [pmmp/PocketMine-MP#504]
### Issue description
Sorry for creating so many issues lately but since yesterday iv been getting some errors related to Furnaces and shorty later server is crashing.

### Steps to reproduce the issue
Keep server running normally.

### OS and versions

* PocketMine-MP: 1.6.2 dev b24d516
* PHP: 7.0.14
* Server OS: Windows 10
* Game version: PE 1.0.5

### Crashdump, backtrace or other files
This error spamming console:

`2017-04-01 [15:24:25] [Server thread/CRITICAL]: Could not tick level "Prison": Cannot use object of type stdClass as array
2017-04-01 [15:24:25] [Server thread/CRITICAL]: Error: "Cannot use object of type stdClass as array" (EXCEPTION) in "/src/pocketmine/tile/Furnace" at line 298`

`2017-04-01 [15:24:25] [Server thread/CRITICAL]: Could not tick level "world": Cannot use object of type stdClass as array
2017-04-01 [15:24:25] [Server thread/CRITICAL]: Error: "Cannot use object of type stdClass as array" (EXCEPTION) in "/src/pocketmine/tile/Furnace" at line 298`

Crashdump:

`
PocketMine-MP Crash Dump Sat Apr 1 11:29:37 BST 2017

Error: Call to a member function getItem() on null
File: /src/pocketmine/tile/Chest
Line: 78
Type: notice

Code:
[69] 
[70] parent::close();
[71] }
[72] }
[73] 
[74] public function saveNBT(){
[75] $this->namedtag->Items = new ListTag("Items", []);
[76] $this->namedtag->Items->setTagType(NBT::TAG_Compound);
[77] for($index = 0; $index < $this->getSize(); ++$index){
[78] $this->setItem($index, $this->inventory->getItem($index));
[79] }
[80] }
[81] 
[82] /**
[83] * @return int
[84] */
[85] public function getSize(){
[86] return 27;
[87] }
[88] 

Backtrace:
#0 /src/pocketmine/level/format/io/region/Anvil(85): pocketmine\tile\Chest->saveNBT(boolean)
#1 /src/pocketmine/level/format/io/region/RegionLoader(163): pocketmine\level\format\io\region\Anvil->nbtSerialize(pocketmine\level\format\Chunk object)
#2 /src/pocketmine/level/format/io/region/McRegion(316): pocketmine\level\format\io\region\RegionLoader->writeChunk(pocketmine\level\format\Chunk object)
#3 /src/pocketmine/level/Level(977): pocketmine\level\format\io\region\McRegion->saveChunk(integer -1, integer -9)
#4 /src/pocketmine/level/Level(965): pocketmine\level\Level->saveChunks(boolean)
#5 /src/pocketmine/Server(2265): pocketmine\level\Level->save(boolean )
#6 /src/pocketmine/Server(2405): pocketmine\Server->doAutoSave(boolean)
#7 /src/pocketmine/Server(2138): pocketmine\Server->tick(boolean)
#8 /src/pocketmine/Server(2021): pocketmine\Server->tickProcessor(boolean)
#9 /src/pocketmine/Server(1642): pocketmine\Server->start(boolean)
#10 /src/pocketmine/PocketMine(493): pocketmine\Server->__construct(BaseClassLoader object, pocketmine\utils\MainLogger object, string phar://E:\UserFiles\LIAMG\GameServers\TC03428615845884033855301\PocketMine-MP.phar/, string E:\UserFiles\LIAMG\GameServers\TC03428615845884033855301\, string E:\UserFiles\LIAMG\GameServers\TC03428615845884033855301\plugins\)
#11 (1): require_once(string phar://E:/UserFiles/LIAMG/GameServers/TC03428615845884033855301/PocketMine-MP.phar/src/pocketmine/PocketMine.php)

PocketMine-MP version: 1.6.2dev #0 [Protocol 105; API 3.0.0-ALPHA5]
Git commit: 0000000000000000000000000000000000000000
uname -a: Windows NT NS306121 6.1 build 7601 (Windows Server 2008 R2 Standard Edition Service Pack 1) i586
PHP Version: 7.0.10
Zend version: 3.0.0
OS : WINNT, win`

**Comment by dktapps** [comment]
Same issue as #490

**Comment by kabluinc** [comment]
k sorry didn't know.

**Comment by dktapps** [comment]
Don't be sorry, naturally you didn't know. I just happened to recognize it for what it was. :)

**Comment by kabluinc** [comment]
Your the best dev in the world :)
