### ISSUE TITLE
Feature Request: Official Pterodactyl Egg Json File

### ISSUE THREAD

**Issue by myxxmikeyxx** [pmmp/PocketMine-MP#5049]
## Description
I would love to see an official Pterodactyl Egg for Pterodactyl Panel.
Something Like PowerNukkit's implication would be fine, just two buttons on [the site](https://powernukkit.org/) that downloads a json file with the settings.
Then they have a second button so you can see the GitHub repo: [here](https://github.com/PowerNukkit/PowerNukkit-Pterodactyl-Egg) 

## Justification
This seems to be a popular option in the gaming community for spinning up many servers. Source Engine Servers like:
- Team Fortress 2
-  Insurgency
- Gary's Mod
- Counter-Strike: Global Offensive
- Ark: Survival Evolved
It also supports Rust Servers as well as Mumble / TeamSpeak 3

And of course Minecraft servers. Out of the box Pterodactyl already supports Minecraft java with multiple options such as:
- Bungeecord
- Forge Minecraft
- Paper (Like Spigot but a rewrite for better optimization)
- Sponge (Like Forge but also has some support for plugins on a forge modded server)
- Vanilla Minecraft

I would love to see a Minecraft Bedrock Option come prebuilt in that has:
- PocketMine-MP (PMMP)
- Nukkit (For older versions)
- NukkitX (The rewrite of Nukkit)
- PowerNukkit (NukkitX but with support for water logging and more "features" as well as more plugins than Nukkit & NukkitX)

## Alternative methods
Currently I have found these Eggs's (Pterodactyl calls Groups like Minecraft, Voice Servers, and Source Engine a nest and eggs are the servers that can be ran)
- [Link 1](https://gist.github.com/TwistedAsylumMC/59dcb8ad1578d835029329f965510db8)
- [Link 2](https://forums.pmmp.io/threads/pterodactyl-panel-support.6049/)

The problem is that the most recent one I can find is 2 years old. The links also appear to be broken.

PS: I would have marked this as a feature request is a tag for that existed.

**Comment by dktapps** [comment]
A very brief Google search leads me to this community egg, which is widely used by server hosts: https://github.com/parkervcp/eggs/blob/master/game_eggs/minecraft/bedrock/pocketmine_mp/egg-pocketmine-m-p.json

**Comment by myxxmikeyxx** [comment]
Thank you. It is still not an official version but I will gladly try it out.

**Comment by dktapps** [comment]
Since none of the PMMP development team uses Pterodactyl, you're better off sticking with an egg that's made by a community with some idea what it's doing.
