### ISSUE TITLE
[REQUEST] Add isArmor()

### ISSUE THREAD

**Issue by PMMPFTW** [pmmp/PocketMine-MP#506]
### Request

I request you to add an 'isArmor()' function. Hope you (yes, you) add it soon.
Thanks. And I appreciate all the work you have been doing to keep up the project. Glad someone took responsibility, or else I don't know what would've happen to the MCPE community altogether.

I apologize for not following the issue format as I don't think it's suitable for a request.

**Comment by Misteboss** [comment]
What is the objective of this function ? Cause i you wanna check if player have an armor some functions are already available 
https://github.com/pmmp/PocketMine-MP/blob/a8650a241cc1aaeb35877ae45b290fae97195754/src/pocketmine/inventory/PlayerInventory.php#L261

**Comment by Sandertv** [comment]
Can't you just check if an item is instanceof Armor?

**Comment by SOF3** [comment]
Having so many methods to check item type is a failure of the item API that may be subject to change in the future (or may not).

**Comment by SOF3** [comment]
Slightly irrelevant to this issue, instanceof check only works if item was created probably through Item::get(). We may want to enforce using the correct class if the item class exists, or check its correctness when it gets cloned or otherwise the instance gets into the API (e.g. inventory operations)

**Comment by dktapps** [comment]
@SOF3 due to the way items are going to be constructed in the future, the only legal way will be to use Item::get() anyway, so that isn't concern.

**Comment by Muqsit** [comment]
I believe he/she meant Item::isArmor(), in case someone didn't get it.
(Item::class instanceof Armor) does the same thing.
