### ISSUE TITLE
Upgrade the Config API (finally!)

### ISSUE THREAD

**Issue by Swift-Strider** [pmmp/PocketMine-MP#5062]
## Description
[`pocketmine\Utils\Config`](https://github.com/pmmp/PocketMine-MP/blob/stable/src/utils/Config.php) is a great way for new programmers to start writing plugins. Using [`$plugin->getConfig()`](https://github.com/pmmp/PocketMine-MP/blob/stable/src/plugin/PluginBase.php#L279) you don't even have to think about where you config file is! But it has a major drawback, a lack of type safety. Bad configs cause server instability as a TypeError can appear from falsely assuming the type of a config value.

### Solution
We introduce a `Parser` that keeps track of errors (missing properties, custom error checks)

### TL;DR / Code Examples
*from Plugin.php*
```php
/** @var \pocketmine\plugin\PluginBase $this */
$data = $this->getConfig()->getAll();
$parser = new Parser(
    data: $data,
    labelTemplate: '%error_count% error(s) in config.yml',
    subParserLabelTemplate: '%error_count% error(s) in %element_name%'
);

try {
    $config = MyConfig::parse($parser);
} catch (ParseStopException $e) {
    $message = $parser->generateErrorMessage();
    $this->getLogger()->critical("Failed to load config, details below...\n$message");
    throw $e; // Crash Server
}
```

*from MyConfig.php*
```php
final class MyConfig
{
    public function __construct(
        public string $message,
        public int $times
    ) {}

    public static function parse(Parser $parser): self
    {
        /** @var ParsedValue $message */
        $message = $parser->rString('message');
        // Require "times" element before potentially stopping error checks are performed
        $times = $parser->rInt('times');

        // Custom Error Check:
        // A caveat is that if "message" isn't defined on the config a ParseStopException
        // will be thrown here. I've moved this check to after all properties
        // have been required, so an error here will still be able to report on "times" property
        // if it happens to be missing.
        if (strlen($message->take()) > 5) {
            // This error is in a "suspended" state, and when $parser->check() is called
            // a ParseStopException will be thrown.
            $parser->error("Element \"message\" must not be over 5 characters long.");
        }

        $parser->check(); // If any properties are missing a ParseStopException is thrown.
        return new self(
            message: $message->take(), // If the config had no message this would throw an error, however this is guaranteed never to throw in this case because $parser->check() will see that this property is missing before we hit this line.
            times: $times->take()
        );
    }
}
```

*from Server Stdout when `$data=[]`*
```log
Failed to load config, details below...
2 error(s) in config.yml
  Element "message" is missing, it must be type `string`.
  Element "times" is missing, it must be type `integer`.
```

Some (working) implementations of [`Parser`](https://github.com/Swift-Strider/QuickFriends/blob/master/src/DiamondStrider1/QuickFriends/Config/Parser.php), [`ParsedValue`](https://github.com/Swift-Strider/QuickFriends/blob/master/src/DiamondStrider1/QuickFriends/Config/ParsedValue.php), and [`ParseStopException`](https://github.com/Swift-Strider/QuickFriends/blob/master/src/DiamondStrider1/QuickFriends/Config/ParsedValue.php)
An example of [`ConfigModule`](https://github.com/Swift-Strider/QuickFriends/blob/master/src/DiamondStrider1/QuickFriends/Config/ConfigModule.php) creating a [`MainConfig`](https://github.com/Swift-Strider/QuickFriends/blob/master/src/DiamondStrider1/QuickFriends/Config/MainConfig.php)

###  Explanation

`$parser->check()` and `$message->take()` are examples of potentially stopping operations, meaning they may throw an exception an stop any more config errors from being found. `$parser->rInt()` is an example of an error-suspending operation, meaning that if the function fails to find the property it won't immediatly throw an exception but instead log it in $parser's internal error tracker. `$parser->check()` is placed at the end to guarantee that there are no errors currently suspended. A surround try-catch detects the error and uses `$parser->generateErrorMessage()` to make an admin-friendly error message.

## Justification

* This increases server stability by verifying beforehand that configuration is correct.
* This is admin-friendly as it is able to report a tree of errors at once.

## Alternative methods

One would be manually checking for config errors. It is however tedious to do so and would take a sizeable chunk of time to be able to report multiple config errors without having a hard-to-read code base.

**Comment by dktapps** [comment]
Current intent is to remove Config entirely since it just gets in the way. You're better off using some unmarshalling library like many you can find on Packagist (or perhaps something like [ConfigStruct](https://github.com/Endermanbugzjfc/ConfigStruct)).

There's a long winded RFC about this here: #4113

**Comment by SOF3** [comment]
I don't think this necessarily needs to be part of the PocketMine API. Introducing more unnecessary API = more burden every major API change.
