### ISSUE TITLE
Server crashed

### ISSUE THREAD

**Issue by StefanFox-Dev** [pmmp/PocketMine-MP#5068]
Link to crashdump:  null

### Additional comments (optional)

PocketMine-MP version: 4.3.4 [Protocol 503]
Git commit: 0000000000000000000000000000000000000000
PHP version: 8.0.19
OS: Linux, linux
Error: pocketmine\network\mcpe\handler\InGamePacketHandler::__construct(): Argument #3 ($inventoryManager) must be of type pocketmine\network\mcpe\InventoryManager, null given, called in /root/srv1/src/network/mcpe/NetworkSession.php on line 767
File: pmsrc/src/network/mcpe/handler/InGamePacketHandler
Line: 155
Type: TypeError
Backtrace:
#0 pmsrc/src/network/mcpe/NetworkSession(767): pocketmine\network\mcpe\handler\InGamePacketHandler->__construct(object Player#572032, object pocketmine\network\mcpe\NetworkSession#577667, null)
#1 pmsrc/src/network/mcpe/NetworkSession(758): pocketmine\network\mcpe\NetworkSession->onClientSpawnResponse()
#2 pmsrc/src/network/mcpe/handler/SpawnResponsePacketHandler(47): pocketmine\network\mcpe\NetworkSession->pocketmine\network\mcpe\{closure}()
#3 pmsrc/vendor/nethergamesmc/bedrock-protocol/src/SetLocalPlayerAsInitializedPacket(42): pocketmine\network\mcpe\handler\SpawnResponsePacketHandler->handleSetLocalPlayerAsInitialized(object pocketmine\network\mcpe\protocol\SetLocalPlayerAsInitializedPacket#573306)
#4 pmsrc/src/network/mcpe/NetworkSession(444): pocketmine\network\mcpe\protocol\SetLocalPlayerAsInitializedPacket->handle(object pocketmine\network\mcpe\handler\SpawnResponsePacketHandler#548403)
#5 pmsrc/src/network/mcpe/NetworkSession(404): pocketmine\network\mcpe\NetworkSession->handleDataPacket(object pocketmine\network\mcpe\protocol\SetLocalPlayerAsInitializedPacket#573306, int 486, string[3] q..)
#6 pmsrc/src/network/mcpe/raklib/RakLibInterface(201): pocketmine\network\mcpe\NetworkSession->handleEncoded(string[51] c.<.h:........=r*...4k.?'.8h.......d...MX..D....Y..)
#7 pmsrc/vendor/pocketmine/raklib-ipc/src/RakLibToUserThreadMessageReceiver(42): pocketmine\network\mcpe\raklib\RakLibInterface->onPacketReceive(int 10, string[60] ..5$...8zUG..Y..@...y..M.b...j...Q..?..._..B2R.....O...:I.l#)
#8 pmsrc/src/network/mcpe/raklib/RakLibInterface(131): raklib\server\ipc\RakLibToUserThreadMessageReceiver->handle(object pocketmine\network\mcpe\raklib\RakLibInterface#34175)
#9 pmsrc/vendor/pocketmine/snooze/src/SleeperHandler(123): pocketmine\network\mcpe\raklib\RakLibInterface->pocketmine\network\mcpe\raklib\{closure}()
#10 pmsrc/vendor/pocketmine/snooze/src/SleeperHandler(82): pocketmine\snooze\SleeperHandler->processNotifications()
#11 pmsrc/src/Server(1669): pocketmine\snooze\SleeperHandler->sleepUntil(float 1653563377.4477)
#12 pmsrc/src/Server(1052): pocketmine\Server->tickProcessor()
#13 pmsrc/src/PocketMine(295): pocketmine\Server->__construct(object BaseClassLoader#3, object pocketmine\utils\MainLogger#2, string[11] /root/srv1/, string[19] /root/srv1/plugins/)
#14 pmsrc/src/PocketMine(318): pocketmine\server()

Code:
[146] 	protected $lastRightClickTime = 0.0;
[147] 	/** @var UseItemTransactionData|null */
[148] 	protected $lastRightClickData = null;
[149] 
[150] 	/** @var bool */
[151] 	public $forceMoveSync = false;
[152] 
[153] 	private InventoryManager $inventoryManager;
[154] 
[155] 	public function __construct(Player $player, NetworkSession $session, InventoryManager $inventoryManager){
[156] 		parent::__construct($session);
[157] 
[158] 		$this->player = $player;
[159] 		$this->inventoryManager = $inventoryManager;
[160] 	}
[161] 
[162] 	public function handleText(TextPacket $packet) : bool{
[163] 		if($packet->type === TextPacket::TYPE_CHAT){
[164] 			return $this->player->chat($packet->message);
[165] 		}

> Reason: I don’t know what the problem is, but it’s already with 4.3.2, there are more than 20 players on the server - crash.

**Comment by StefanFox-Dev** [comment]
* Information from the player, he wrote in the book

**Comment by IvanCraft623** [comment]
NetherGames fork detected

**Comment by IvanCraft623** [comment]
Is seems to be the same as #4594

**Comment by StefanFox-Dev** [comment]
Okay, thanks for the info.
