### ISSUE TITLE
NBT TAGS ISSUE

### ISSUE THREAD

**Issue by JunkDaCoder** [pmmp/PocketMine-MP#507]
Issue description

1.Items with this code drops out of ur inv and cant be picked back up without them being thrown out, unless u relog.
Steps to reproduce the issue
Heres code from @Muqsit that reproduces it$item = Item::get(Item::DIAMOND_SWORD, 0, 10);
$item->setCustomName(TextFormat::RESET.TextFormat::AQUA.'A Custom Named TNT');
$nbt = $item->getNamedTag();
$nbt->tag1 = new StringTag('tag1', 'A custom tag');
$nbt->tag2 = new StringTag('tag2', 'Another custom tag');
$item->setNamedTag($nbt);
//Player::getInventory()->addItem($item);
Then drop and pick it up
OS and versions
PHP: 7.0.14
Server OS: CentOS7
Game version: 1.0.5

**Comment by Muqsit** [comment]
Pmmp doesn't face the issue

**Comment by JunkDaCoder** [comment]
@Muqsit is it floating inventorys then? if so where are the transactions handled (the file)
