### ISSUE TITLE
Lanterns cannot be placed on walls and fences

### ISSUE THREAD

**Issue by MrBlasyMSK** [pmmp/PocketMine-MP#5070]
### Issue description

It simply does not leave colored lanterns on walls or fences.
- Expected result: ![image](https://user-images.githubusercontent.com/85447029/170800695-c41384b6-e47b-423a-ab3c-4042121684de.png)
- Actual result: ![image](https://user-images.githubusercontent.com/85447029/170800716-eea3297a-7237-4dc2-9a55-64bc82e9fbfd.png)

### Steps to reproduce the issue
1. Try placing a lantern under or on a fence or wall.
2. You will see how it disappears instantly

### OS and versions

* PocketMine-MP: 4.3.4
* PHP: 8.0.18
* Using JIT: no
* Server OS: linux
* Game version: Win10

### Plugins

- If you remove all plugins, does the issue still occur? yes
- If the issue is **not** reproducible without plugins:
  - Have you asked for help on our forums before creating an issue?
  - Can you provide sample, *minimal* reproducing code for the issue? If so, paste it in the bottom section

**Comment by Nerahikada** [comment]
This has already been fixed in [4.4.0-BETA1](https://github.com/pmmp/PocketMine-MP/releases/tag/4.4.0-BETA1).

**Comment by MrBlasyMSK** [comment]
Theoretically this will be corrected in the next version, I close issue
