### ISSUE TITLE
difficulty seems to be on peaceful regardless of change

### ISSUE THREAD

**Issue by metulburr** [pmmp/PocketMine-MP#5073]
When i play there are no NPC's at night. It is acting as if it is on peaceful. The difficulty setting was defaulted to 2. which i am assuming was normal as per minecraft settings usually are. 

Regardless of what i change the difficulty to it, there are no NPC's at all as if it is on peaceful all the time. 

Server running on Ubuntu 20.04.2
client is Android 11 on minecraft version 1.18.3~(cant read the last number)

**Comment by dktapps** [comment]
This is expected. PocketMine-MP is not a vanilla server and various vanilla features are not supported.
