### ISSUE TITLE
Non-burning furnaces glow in the dark

### ISSUE THREAD

**Issue by dktapps** [pmmp/PocketMine-MP#508]
### Issue description
Unlit furnaces emit block light. 🤦‍♂️

Expected result: What were you expecting to happen?
- Unlit furnaces I place to not glow in the dark

Actual result: What actually happened?
- furnace glows in the dark

### Steps to reproduce the issue

1. set world to night time
2. place an unlit furnace
3. quit + rejoin, notice the area around the furnace is illuminated

### OS and versions
* PocketMine-MP: 202bac28fc7f9332e5b02643d54d574a7fbe6732 with lots of local changes
* PHP: 7.0.17
* Server OS: w10
* Game version: PE

**Comment by dktapps** [comment]
test

**Comment by dktapps** [comment]
Fixed on api3/network, will be closed automatically when the branch is merged.

**Comment by TheDiamondYT1** [comment]
It would make more sense for BurningFurnace to extend Furnace, not the other way around.
