### ISSUE TITLE
No air hit animation & sound

### ISSUE THREAD

**Issue by Lunarelly** [pmmp/PocketMine-MP#5081]
### Hit animation doesnt appear for another players (sound too!)

- Expected result: Hit animation for another players (appears only for player who hits **client-side**)
- Actual result: No hit animation & sound

### Steps to reproduce the issue
1. Hit the air

### OS and versions
* PocketMine-MP: 4.3.4
* PHP: 8.0
* Using JIT: no
* Server OS: tried on Linux & WIndows
* Game version: tried Windows, Android (literally every version)

### Plugins
My practice core

- If you remove all plugins, does the issue still occur? Yes.

### Crashdump, backtrace or other files
No

### Other
This bug doesnt appear using PM3, only in PM4

https://user-images.githubusercontent.com/58974140/171295335-ca8bbeb8-c4d3-4141-9916-851bf2561dc7.mp4

**Comment by Blackjack200** [comment]
same as https://github.com/pmmp/PocketMine-MP/issues/4334

**Comment by ghost** [comment]
Dylan...
