### ISSUE TITLE
Scheduler Task Id and Remove Single Task By Task ID.

### ISSUE THREAD

**Issue by StarCodeSuperior** [pmmp/PocketMine-MP#5082]
I used to remove a scheduler task simple before pm4 like it was easy $this->getScheduler()->removeTask($this->getTaskId());

but now there is only cancelAllTasks();

why and how to remove a specified single task by task id and how to get task id now.

- Expected result: Cancel a Scheduler task with task id.
- Actual result: CancelAllTasks

### Steps to reproduce the issue
1.  Can You please say me how to get scheduler Task Id which is running and how to cancela single task by task id.
2. Or if that feature is removed please get it back.

### OS and versions

* PocketMine-MP: 4.3.0
* PHP: 8.0.18
* Using JIT:  no
* Server OS: win
* Game version: Android

**Comment by Nerahikada** [comment]
```php
$task = new SomethingTask();

$handler = $this->getScheduler()->scheduleTask($task);
$handler->cancel();

// or
$task->getHandler()->cancel();
```
