### ISSUE TITLE
There is no "creating-an-issue" in CONTRIBUTING.md

### ISSUE THREAD

**Issue by Nerahikada** [pmmp/PocketMine-MP#5083]
### Issue description
This section doesn't exist since a5b08fc8f26152b2f5031ec9ea983bafb658384b.
The reply to the support request needs to be re-written.
https://github.com/pmmp/PocketMine-MP/blob/681a9bb0e18612f5d166ddbe2bf57713e032ba81/.github/workflows/support.yml#L16

**Comment by dktapps** [comment]
Fixed by 8b86e43d51fa71322f5d84fbd7ff4506f9b76182.
