### ISSUE TITLE
The result of crafting a suspicious stew is replaced with an unknown block

### ISSUE THREAD

**Issue by Gaprix** [pmmp/PocketMine-MP#5093]
### Issue description
The result of crafting a suspicious stew is replaced with an unknown block.

- Expected result: On PM 4.4.1, crafting works and you get a suspicious stew
- Actual result: As a result of crafting, you get an unknown block

### Steps to reproduce the issue
1. test.pmmp.io:19132
2. Use the recipe for crafting a suspicious stew

### OS and versions

* PocketMine-MP: 5.0.0+dev (git hash: 01af70f671c6340e023b5cf80811cf948ddea750)
* PHP: 8.0.19
* Using JIT: no
* Server OS: linux
* Game version: Win10

### Plugins
test.pmmp.io:19132

### Crashdump, backtrace or other files
![image](https://user-images.githubusercontent.com/45711510/172024642-0412a6cb-e9d7-42cb-80a9-423f7fb60ae9.png)
![image](https://user-images.githubusercontent.com/45711510/172024761-d4f3eb4c-f952-46b2-9b11-28203ee06610.png)

**Comment by dktapps** [comment]
Suspicious stew isn't implemented yet. It shouldn't work on any version.

**Comment by Gaprix** [comment]
Crafting works successfully on PM4

**Comment by dktapps** [comment]
I'm aware. As I said, it's not supposed to work at all.

**Comment by Gaprix** [comment]
This causes a weird bug: https://youtu.be/RgKPEFSKAl8

**Comment by StefanFox-Dev** [comment]
And if you still use the core from NetherGamesMC, then when crafting it will generally crash)))

**Comment by dktapps** [comment]
This has been fixed on `modern-world-support` (which is the only place the update! block issue occurred) but recipes with unknown items should be filtered from all versions, so I'll leave this open for now.
