### ISSUE TITLE
5.0.0 target release date (Mar 2023), planned changes and more

### ISSUE THREAD

**Issue by dktapps** [pmmp/PocketMine-MP#5097]
Answering some (very) frequently asked questions about PM5 plans...

## What is PM5?
PM5 is the codename for the next major release of PocketMine-MP, v5.0.0.

## When is PM5 planned for release?
~~**December 2022**~~. This date is not finalized and may be delayed or moved forward depending on what happens.

**Update 11 Sep 2022: We are delaying this until March 2023 due to unforeseen circumstances. Please read comments below for more details.**

## Is it going to be as big as PM4?
No. PM4 spent over 3 years in development. PM5 will have spent only 1 year, i.e. less than 1/3rd of that time. This means that the overall amount of changes will be much smaller than PM4.

## What's going to change?
The change list is currently not finalized, but the following things are currently in active development:
- increased world height
- 3D biomes support
- new blocks and items from versions 1.13-1.19
- support for loading worlds created by Bedrock 1.13 and newer
- various API improvements, such as:
  - PHP 8.0 upgrades (typed properties, promoted properties)
  - removing legacy block and item IDs
  - revamping block and item internals handling
  - more dynamic and consistent block property APIs

There are various other things that are under discussion that might be implemented too. You can view things on the issue tracker such as:
- [5.0.0 milestone](https://github.com/pmmp/PocketMine-MP/milestone/5)
- [Change Proposals](https://github.com/pmmp/PocketMine-MP/issues?q=is%3Aopen+is%3Aissue+label%3A%22Type%3A+Change+Proposal%22)

There's still several months of development open. There will be a beta a couple of months before final release to preview changes.

## Can I contribute?
Yes, you can! You can contribute in the following ways:

- Write and submit change proposals
- Report bugs
- Take a shot at implementing existing proposals in a pull request (target `next-major` branch)
- Make constructive reviews of open PRs (e.g. suggest improvements or point out mistakes)
- Donate

## But I don't want to change all my plugins again!
Get used to it. Change is necessary for improvement, and sometimes that involves breaking plugins.
Also, as mentioned above, PM5 will be a much smaller update than PM4.

## Will people read this message and stop asking the same questions over and over?
I doubt it, but I suppose it can't hurt to try...

**Comment by PushkarOP** [comment]
Nice 👏

**Comment by piyushbest** [comment]
Waiting for this update 😀😄

**Comment by ghost** [comment]
Thank you Dylan for this incredible and massive work.

**Comment by Steellgold** [comment]
What is "3D biome support" ?

**Comment by ProtectorYT364** [comment]
That's close

**Comment by rac14** [comment]
Nice

**Comment by ipad54** [comment]
> What is "3D biome support" ?

3D biomes are a generation phenomena, where multiple biomes can essentially be generated on top of each other.

This has already been observed in Minecraft 1.18 largely in cave biomes, where underground biomes such as lush caves can generate immediately over dripstone caves, making a mash-up of biomes that are either thinly separated or not separated at all.

**Comment by ghost** [comment]
> > What is "3D biome support" ?
> 
> 3D biomes are a generation phenomena, where multiple biomes can essentially be generated on top of each other.
> 
> This has already been observed in Minecraft 1.18 largely in cave biomes, where underground biomes such as lush caves can generate immediately over dripstone caves, making a mash-up of biomes that are either thinly separated or not separated at all.

This thing is named column

**Comment by ReyyanGamer** [comment]
Coooooool

**Comment by AzaleeX** [comment]
Excellent dommage que cela sorte en décembre

**Comment by mmm545** [comment]
better lock this issue lol

**Comment by dadodasyra** [comment]
> removing legacy block and item IDs

what do you mean by this ? What is the good way to do it for example using customs IDs and for configs purposes ?

**Comment by dktapps** [comment]
## Delay of PocketMine-MP 5.0.0 stable release date
I'm sorry to announce that 5.0.0's stable release date is going to be pushed back from December 1st 2022 to **March 1st, 2023**.

This is due to concerns about changes made in PM5 which are not yet matured enough to be released as stable, and insufficient time to resolve those concerns before feature freeze and beta releases.
In addition, I (Dylan) am preparing to relocate, so my availability to commit and review code will be significantly reduced during September and October.

If you have any questions about this announcement, hop into the PocketMine-MP Community Discord and our community will be happy to help.

Thank you all for your understanding.
