### ISSUE TITLE
Add inventory to PlayerDropItemEvent

### ISSUE THREAD

**Issue by boi1216** [pmmp/PocketMine-MP#5115]
## Description
PlayerDropItemEvent should return whether the item was dropped from regular inventory or armor inventory

## Justification
As an example lets say we want to remove item from armor inventory instead of getting it dropped. With the current API we need to write a check to see if the armor piece is part of player inventory or armor inventory, but if there was something like getInventory(), we could simply get the armor inventory instance when item is dropped from armor inventory.

**Comment by dktapps** [comment]
You can use InventoryTransactionEvent for this. There's no guarantee that a dropped item in PlayerDropItemEvent has a source.
