### ISSUE TITLE
The server crashes depending on the path to the server folder

### ISSUE THREAD

**Issue by Gaprix** [pmmp/PocketMine-MP#5129]
### Issue description
If the PocketMine folder is located in the user's folder, a crash occurs. But if it is in the root of the C drive, then there is no error.

### Steps to reproduce the issue
1. Path to the PocketMine folder C:\Users\79154\modern-world
2. Start the server
3. A crash will occur during server startup

### OS and versions
* PocketMine-MP: 5.0.0+dev (9f0b32e748e4052a4f81d841817d15adca5a05bd-dirty)
* PHP: 8.0.19
* Server OS: Windows 10 (21H2), Russian localization

### Plugins
None

### Crashdump, backtrace or other files
I was unable to upload the crash dump to the archive
https://pastebin.com/qssVXGJ3

**Comment by dktapps** [comment]
I'm using Windows and I don't have any such issue ...

The crashdump upload is rejected because you modified the server source code. The line numbers in your crash don't match the actual code.
