### ISSUE TITLE
Cant Join

### ISSUE THREAD

**Issue by JunkDaCoder** [pmmp/PocketMine-MP#513]
### Issue description
I cant join from my windows 10, it keeps saying Raklib Blocked IP and then i get login timout
* PocketMine-MP: Current
* PHP: 7
* Server OS: Ubuntu
* Game version: PE/Win10 (delete as appropriate)

**Comment by JunkDaCoder** [comment]
Why was this closed

**Comment by dktapps** [comment]
> NOTE: LATEST is not a valid version.
s/LATEST/Current

> PocketMine version should include Jenkins build number and/or git commit hash.

**Comment by JunkDaCoder** [comment]
there

**Comment by dktapps** [comment]
Backtrace? Game version?

**Comment by TheDiamondYT1** [comment]
Update your server version, i had this problem before the latest commit

**Comment by dktapps** [comment]
This is a spoon issue. That constant has never existed in PocketMine-MP.

**Comment by JunkDaCoder** [comment]
yep i forgot i pasted over some stuff to the playerphp file, rip
