### ISSUE TITLE
Server crashed

### ISSUE THREAD

**Issue by StefanFox-Dev** [pmmp/PocketMine-MP#5134]
Link to crashdump:
Null

### Additional comments (optional)
19:16 DEBUG: [Player: Korotkiy10] Closing inventory pocketmine\block\inventory\BarrelInventory#1882581
19:16 ОШИБКА: LogicException: "Player is not connected" (EXCEPTION) in "pmsrc/src/player/Player" at line 559
--- Stack trace ---
  #0 pmsrc/src/network/mcpe/convert/RuntimeBlockMapping(141): pocketmine\player\Player->getNetworkSession()
  #1 pmsrc/src/world/World(932): pocketmine\network\mcpe\convert\RuntimeBlockMapping::sortByProtocol(array[40])
  #2 pmsrc/src/world/World(829): pocketmine\world\World->actuallyDoTick(int 1098184)
  #3 pmsrc/src/world/WorldManager(348): pocketmine\world\World->doTick(int 1098184)
  #4 pmsrc/src/Server(1824): pocketmine\world\WorldManager->tick(int 1098184)
  #5 pmsrc/src/Server(1706): pocketmine\Server->tick()
  #6 pmsrc/src/Server(1068): pocketmine\Server->tickProcessor()
  #7 pmsrc/src/PocketMine(281): pocketmine\Server->__construct(object BaseClassLoader#3, object pocketmine\utils\MainLogger#2, string[11] /root/srv1/, string[19] /root/srv1/plugins/)
  #8 pmsrc/src/PocketMine(302): pocketmine\server()
--- End of exception information ---

**Comment by JustStevee** [comment]
Dktapps: This kid again

**Comment by ghost** [comment]
> Dktapps: This kid again

ukraine fox dev: this dktapps again
