### ISSUE TITLE
There is no animation of arm swinging when interacting with some blocks on Windows 10

### ISSUE THREAD

**Issue by Gaprix** [pmmp/PocketMine-MP#5141]
### Issue description
When clicking with a hoe on grass and an axe on wood, there is no animation of swinging your hand.
This bug occurs on Windows 10 but does not occur on Android.

- Expected result: The arm swings
- Actual result: The arm doesn't swing

### Steps to reproduce the issue
1. Place a grass block
2. Click on it with a hoe

### OS and versions
* PocketMine-MP: 5.0.0+dev (git hash: 00db73a5b2e988001247c436491ef98297b2fdc6)
* PHP: 8.0.19
* Server OS: win
* Game version: Win10

### Plugins
None

**Comment by dktapps** [comment]
This is a client bug. From other players' perspective your arm will swing, since the swing animation is handled by the server.

**Comment by Gaprix** [comment]
I checked it on BDS and there is no bug there
