### ISSUE TITLE
Item id mapping on chunk sending is wrong since the 1.19.10 release of pmmp

### ISSUE THREAD

**Issue by SleepSpace9** [pmmp/PocketMine-MP#5154]
### Issue description

You can see this behaviour on item frames. Just place an item into it and rejoin the server.
- Expected result: you see the same item in the item frame
- Actual result: you see a different item in the item frame

EDIT: If you tap on the item frame block the item frame contents will be updated to the correct item.

### Steps to reproduce the issue
see issue description

### OS and versions

* PocketMine-MP: 4.6.0
* PHP: 8.0.13
* Using JIT: no
* Server OS: Windows 10
* Game version: Win10

### Plugins
-none-

### Crashdump, backtrace or other files
-none-

**Comment by dktapps** [comment]
Item frames are generally broken regardless of which version of PM you're using. This is some really hairy bug in the client.

**Comment by SleepSpace9** [comment]
It seems to me that now the legacy item id is used instead of the `runtime_id` in required_item_list.json to display the item. For example if I place a golden apple (item id 322), it will be displayed as a golden sword (runtime_id 322) on the next join.

**Comment by dktapps** [comment]
It's a bug. It's interpreted differently depending on context, and this isn't the only thing broken. Using the modern format (using string IDs) causes a bug where the item simply doesn't load unless using the SubChunkRequest system.

**Comment by dktapps** [comment]
Reported as https://bugs.mojang.com/browse/MCPE-159081
