### ISSUE TITLE
Session closed due to Packet processing error

### ISSUE THREAD

**Issue by FarizFx** [pmmp/PocketMine-MP#5159]
This message appears when I try to login to the server
[12:03:46.490] [Server thread/ERROR]: [NetworkSession: xx.xx.xx.xx 54990] Bad packet (error ID caaa323c1327): Error processing LoginPacket: JSON property "IsEditorMode" does not exist in object of type pocketmine\network\mcpe\protocol\types\login\ClientData

[13:43:58.828] [Server thread/INFO]: This server is running PocketMine-MP
[13:43:58.828] [Server thread/INFO]: Server version: 4.5.1 (git hash: d641812c52ef278e714e9d72c5277733b0b2fda9)
[13:43:58.829] [Server thread/INFO]: Compatible Minecraft version: 1.19.0 (protocol version: 527)
[13:43:58.829] [Server thread/INFO]: PHP version: 8.0.19
[13:43:58.829] [Server thread/INFO]: PHP JIT: enabled (CRTO: 1254)
[13:43:58.829] [Server thread/INFO]: Operating system: linux

Plugins (81): AcidIsland v0.0.2, AntiVoid v1.2.0, AnvilUI v1.0.0, AuctionHouse v2.0.1, BanItem-PM4 v2.3.4, BetterMobsOverworld v1.1.0, BetterRename v1.0.0, BetterWarps v1.0.0, BlazinFly v1.9.0, BlockPets v2.0.1, BlockSniper v4.0.0, BloodInMC v1.0.0, BuilderTools v1.3.1, BurgerSpawners v0.2.0, ChestShopXSOAP v6.6.6, Clothes v6.5, ContactUI v1, CustomWing v1.5, DevTools v1.15.0+dev, DeviceACM v1.0, DimensionPortals v0.1.2, EasyKits v2.0.0, EconomyAPI v5.7.3-PM4, EconomyCShop v1.0.0, EnchantShop v1.0.0, ExtendedBlocksConverter v1.0.0, FormAPI v1.4.0, GamemodeUI v1.1, HealAndFeed v2.1.0, Hub v1, ImageOnMap v1.0.2, InvCraft v0.2, InvSee v2.0.1, JobUI v2.3.7, JoinACM v1.0, KDR v1.0.0, KeepInventory v2.0.0, KeyShop v1, KygekRanksUI v2.0.0, KygekRulesUI v2.0.0, MOTDShuffle v1.3.0, MineReset v4.0.0, MultiWorld v1.7.0-beta4, NickUI v1, OnlineTime v1.0.0, Perks v3.0.2, PiggyCrates v3.0.1, PureChat v2.0.0, PurePerms v1.4.5, RedstoneCircuit v3.0.3, Repair v1.0.1, ReportSystem v2.1.0, Rewards v5.0, RulesUI v1, ScoreHud v5.2, ScoreboardAPI v1.0.2, SellAll v1.3.0-PM4, SellUI v2.0.0, ShopGUI v1.0.0, ShowPerms v2.0.0, SimpleBroadcast v6.0.0, SimpleLay v3.0.0, SimpleNPC v3.0.1, SizeUI v1.0, SkinThief v1.0.0, Slapper v2.0.8, SlapperParticle v1, SlapperRotationV2 v2.0.2, SlapperSound v0.0.1, SoulWell v1.2, Spyglass v1.0.1, Sudo v1.2.1, TGCapes v1.0.3, TopMoneyNPC v1, VanillaCoordinates v1.1.0, VanishV2 v3.0.2, Voting38 v0.0.2, WFT v1.3.3, WarpUI v0.0.1, WorldProtect v2.3.11, WorldTeleportUI v1.0.1

**Comment by UnknownOre** [comment]
are you logging in with a proxy?

**Comment by FarizFx** [comment]
> are you logging in with a proxy?

idk, I use wifi internet with default settings, I don't have any settings

**Comment by dktapps** [comment]
⚠️ This issue ticket doesn't have all the required information ⚠️ 
To make it as quick and easy as possible for maintainers to fix your problem, an issue template is provided which lists certain required information. This includes (but is not limited to):

- PocketMine-MP version (use the `version` command)
- PHP version
- Minecraft version and/or edition
- List of all plugins used (use the `plugins` command)
- **Most importantly, clear steps to reproduce the problem.**

Without this information, your problem cannot begin to be investigated, so the issue will be closed. You may amend this one, or create a new one, providing all the required information using one of the provided [issue templates](https://github.com/pmmp/PocketMine-MP/issues/new/choose).

Help us to help you by providing the information we ask for.

**Comment by ShockedPlot7560** [comment]
this happens when trying to connect to the server with an outdated client and the new 4.6

**Comment by dktapps** [comment]
I'm running it on the test servers and haven't seen any such errors...

**Comment by IvanCraft623** [comment]
> this happens when trying to connect to the server with an outdated client and the new 4.6

Vice versa, that happend when trying to connect to the server outdated (4.5) with the new 1.19.10

**Comment by dktapps** [comment]
I tested it on both versions and have no such issue. You guys must be using some plugin or external tool that's causing this.

You can see here that it checks the protocol version before attempting to validate the JWT: https://github.com/pmmp/PocketMine-MP/blob/38d6284671e8b657ba557e765a6c29b24a7705f5/src/network/mcpe/handler/LoginPacketHandler.php#L66

Therefore, under normal circumstances, what you're reporting cannot happen on standard PM.
