### ISSUE TITLE
Missing sounds when equipping or unequipping armour using right-click

### ISSUE THREAD

**Issue by dktapps** [pmmp/PocketMine-MP#5167]
### Issue description
As per title.

### Steps to reproduce the issue
1. Right-click to equip an armour piece
2. Notice the lack of sounds

### OS and versions

* PocketMine-MP: 4.6.0 / 5.0.0-ALPHA2

**Comment by ShockedPlot7560** [comment]
Fixes in https://github.com/pmmp/PocketMine-MP/commit/f799cfaba6318dcf90fce3956bb4843d12581df2
