### ISSUE TITLE
Add an API for resource management to the `Plugin` interface

### ISSUE THREAD

**Issue by ghost** [pmmp/PocketMine-MP#5176]
## Description
Add an API for resource management to the `Plugin` interface

## Justification
Now, the `Plugin` interface does not contain the API methods for managing plugin resources. Such as: `getResource()`, `saveResource()` and `getResources()`.

Given that a `ResourceProvider` must be provided in the constructor of this class, this looks odd.

**Comment by ghost** [comment]
The question of the need for this interface is also relevant.

**Comment by dktapps** [comment]
The need for these methods in such an interface is questionable...

The point of `Plugin` is to describe all the things that a plugin's main class must provide in order for the server to interact with it. The server never interacts with plugin resources, so this proposal doesn't make any sense.

**Comment by ghost** [comment]
but at the same time, the core gives me a ResourceProvider. oh yes

**Comment by dktapps** [comment]
It has to know whether your constructor accepts that because the constructor is called dynamically. It's up to you whether you use it or not.
