### ISSUE TITLE
CauldronTile does not update when switching to a different cauldron type

### ISSUE THREAD

**Issue by IvanCraft623** [pmmp/PocketMine-MP#5178]
### Issue description

- Expected result: What were you expecting to happen?
The Cauldron Tile is updated when changing the cauldron.
- Actual result: What actually happened?
Tile is not updated
### Steps to reproduce the issue
This is only reproducible with code:
1. Set a PotionCauldron
2. In the same position of the PotionCauldron set another type of cauldron. (Preferably WaterCauldron to make the problem more noticeable)
3. Tile data is not updated!

### OS and versions

* PocketMine-MP: 280788d67cc5f5250c479da4ef42c4cc6fa8d9ae
* PHP: 8.0.19
* Server OS: Win10

Example code with which it can be reproduced:
```php
<?php

declare(strict_types=1);

namespace IvanCraft623\TestPlugin;

use pocketmine\block\BlockTypeIds;
use pocketmine\block\VanillaBlocks;
use pocketmine\command\Command;
use pocketmine\command\CommandSender;
use pocketmine\item\PotionType;
use pocketmine\item\VanillaItems;
use pocketmine\math\VoxelRayTrace;
use pocketmine\player\Player;
use pocketmine\plugin\PluginBase;

final class TestPlugin extends PluginBase {

	protected function onEnable() : void {
	}

	public function onCommand(CommandSender $sender, Command $command, string $label, array $args) : bool {
		switch ($label) {
			case 'test':
				if ($sender instanceof Player && isset($args[0])) {
					$world = $sender->getWorld();
					$block = null;
					foreach (VoxelRayTrace::inDirection($sender->getEyePos(), $sender->getDirectionVector(), $sender->getViewDistance() * 16) as $pos) {
						$b = $world->getBlock($pos);
						if ($b->getTypeId() !== BlockTypeIds::AIR) {
							$block = $b;
							break;
						}
					}
					switch ($args[0]) {
						case 'block':
							$sender->sendMessage($block->__toString());
							break;

						case 'tile':
							var_dump($world->getTile($block->getPosition()));
							break;

						case '1':
							$world->setBlock($block->getPosition(), VanillaBlocks::WATER_CAULDRON()->setFillLevel(6));
							break;

						case '2':
							$potion = VanillaItems::POTION()->setType(PotionType::NIGHT_VISION());
							$world->setBlock($block->getPosition(), VanillaBlocks::POTION_CAULDRON()->setPotionItem($potion)->setFillLevel(6));
							break;
						
						default:
							$sender->sendMessage("Nope");
							break;
					}
				}
				break;
		}
		return false;
	}
}
```

### Crashdump, backtrace or other files

https://user-images.githubusercontent.com/57236932/179641340-5123f2c0-93e7-4600-a7ec-ba89ef290e9a.mp4

This must be solved before merging #5170

**Comment by dktapps** [comment]
This is a client bug, as I said previously, caused by the bug described in #5174.

**Comment by dktapps** [comment]
My bad, I misundestood the issue. (in my defence, the video does not make it clear what you're trying to demonstrate...)

**Comment by IvanCraft623** [comment]
Video explained:
- First I place a filled WaterCauldron (it is observed that there was no problem).
- I place a PotionCauldron with night vision potion (also no problem).
- I place a WaterCauldron in place of the PotionCauldron (it looks as if it is not updated).

What happens when I place the WaterCauldon is that `readStateFromWorld` is executed detecting the Tile with the PotionCauldron data (which should not happen), replacing it with PotionCauldron.
