### ISSUE TITLE
Smithing Mismatch transaction

### ISSUE THREAD

**Issue by crazyshadowpro** [pmmp/PocketMine-MP#5179]
### Issue description

- Expected result: Smithing to give netherite helmet
- Actual result: Gives "Mismatch transaction received"

### Steps to reproduce the issue
1. Get Diamond Helmet and 1 netherite ingot(issue seems to only happen with 1 ingot)
2. Go into survival mode
3. place a smithing table and try upgrading it

### OS and versions

* PocketMine-MP: 5.0.0-ALPHA2
* PHP: 8.0
* Server OS: Windows
* Game version: Win10

### Plugins
0 plugins

- If you remove all plugins, does the issue still occur?: Yes issue happens without plugins, i installed 0 plugins.

### Crashdump, backtrace or other files
Not a crash

**Comment by dktapps** [comment]
I bet this is one of those telltale signs that we need to abandon the old transaction system ...

It seems like the client itself has some kind of problem with this, since there's no error on the server side. I'm not really sure there's anything that can be done about it.

Relates to #3899.

**Comment by dktapps** [comment]
Closing this as WF since there's nothing that can be done about it from the server side, other than implementing #3899.
