### ISSUE TITLE
Add if whitelist is enabled in query

### ISSUE THREAD

**Issue by theohdg2** [pmmp/PocketMine-MP#5189]
when we make a query this one does not tell us whether or not the whitelist is activated which would however be very valuable for many servers using a proxy

**Comment by dktapps** [comment]
It's already in there. https://github.com/pmmp/PocketMine-MP/blob/38d6284671e8b657ba557e765a6c29b24a7705f5/src/network/query/QueryInfo.php#L214

**Comment by theohdg2** [comment]
https://api.mcsrvstat.us/2/goldrushmc.fun:19132
I also saw it in the code however if you look at the link it is not in it..

**Comment by dktapps** [comment]
That's because the API you're using isn't showing it. That's not a PM problem.

**Comment by theohdg2** [comment]
do you have an api that shows me if the whitelist is activated?
