### ISSUE TITLE
Players can sprint backwards

### ISSUE THREAD

**Issue by xxFLORII** [pmmp/PocketMine-MP#5195]
### Issue description

- Expected result: Players can only sprint forward
- Actual result: Players can sprint backwards

### Steps to reproduce the issue
1. Sprint forward
2. Run backwards while sprinting forward

### OS and versions
* PocketMine-MP: 5.0.0-ALPHA2 (git hash: 66f2116e57cfff32f3529d1df5c14efee8b93fb9)
* PHP: 8.0.15
* Using JIT: no
* Server OS: Debian 10
* Game version: Win10

### Plugins
 Plugins (0):

- If you remove all plugins, does the issue still occur?
- If the issue is **not** reproducible without plugins:
  - Have you asked for help on our forums before creating an issue?
  - Can you provide sample, *minimal* reproducing code for the issue? If so, paste it in the bottom section

### Crashdump, backtrace or other files
https://youtu.be/lm0pMxzwMK0?t=11

**Comment by JavierLeon9966** [comment]
This a vanilla bug, you should report it to Minecraft instead

**Comment by Gewinum** [comment]
> This a vanilla bug, you should report it to Minecraft instead

yeah, pmmp cant do anything with that

**Comment by ghost** [comment]
> yeah, pmmp cant do anything with that

no, pmmp can. just call `Player::setSprinting(false)` if `PlayerAuthInputPacket` has the `PlayerAuthInputFlags::DOWN` flag

**Comment by Endermanbugzjfc** [comment]
> > yeah, pmmp cant do anything with that
> 
> no, pmmp can. just call `Player::setSprinting(false)` if `PlayerAuthInputPacket` has the `PlayerAuthInputFlags::DOWN` flag

Consider doing this with a plugin. :heavy_check_mark:

**Comment by ghost** [comment]
> Consider doing this with a plugin. :heavy_check_mark: 

instead 3 lines of code in `InGamePacketHandler`?
