### ISSUE TITLE
Sub-MOTD (Lan-MOTD) Support

### ISSUE THREAD

**Issue by xRodzMC** [pmmp/PocketMine-MP#5204]
## Must be changed
- [x] Must added SubMotd support like [Nukkit](https://github.com/CloudburstMC/Nukkit)

## Screenshot
![](https://www.wikihow.com/images/thumb/7/75/Join-Servers-in-Minecraft-PE-Step-38.jpg/v4-460px-Join-Servers-in-Minecraft-PE-Step-38.jpg.webp)

## Why?
The "My World" will change as on `server.properties` provided sub-motd. We can say its useless but if we add this feature we can say people will not going to make their own pocketmine-mp for changing `VersionInfo.php` the name. So we can use function `NetworkSession->setNetwork("Server Name", "Server Sub-MOTD" = "PocketMine-MP Server");` if value is missing it will returning `PocketMine-MP` as default. People wont make their own useless Pocketmine-MP Forks to implement this feature.

**Comment by dktapps** [comment]
No one is going to fork the repo unless they really have absolutely nothing better to do, and think it's worth losing official support just to change some text that no one sees anyway. It doesn't show on the main server list. This means only people developing servers will see it, and those people should have more important things to think about than a random bit of text that no player will see.

**Comment by dktapps** [comment]
Besides, if someone really wants this bad enough to fork, they could easily submit a PR, which no one has done ...

**Comment by xRodzMC** [comment]
Implement this on https://github.com/pmmp/PocketMine-MP/pull/5237
