### ISSUE TITLE
Add BlockBreakEvent->getDropsCount()

### ISSUE THREAD

**Issue by MCPEAbdu77** [pmmp/PocketMine-MP#5207]
## Description
`$event->getDrops()->getDropsCount();` 
or maybe simply `$event->getDropsCount();`
This method counts the number of the drops a block drops during BlockBreakEvent, returns an integer.
Ex. 
Breaking coal ore sometimes drops more than 1 coal. 

## Justification
Knowing the count of drops will be very useful for plugin developers, ex. if each coal sells for a certain price, the dev can simply multiply the amount with the price.

## Alternative methods
still trying to find out how.

**Comment by IvanCraft623** [comment]
Just...
```php
$count = 0;
foreach ($event->getDrops() as $drop) {
	$count += $drop->getCount();
}
```
