### ISSUE TITLE
Server crashed

### ISSUE THREAD

**Issue by PmmpDevelop** [pmmp/PocketMine-MP#5215]
Sometimes when players exit, the server crashed
Api: 4.6.2
Php8

2022-08-09 [00:11:03.021] [Server thread/CRITICAL]: LogicException: "Player is not connected" (EXCEPTION) in "pmsrc/src/player/Player" at line 555
-— Stack trace —-
#0 pmsrc/src/player/Player(1963): pocketmine\player\Player->getNetworkSession()
#1 pmsrc/src/player/Player(1946): pocketmine\player\Player->sendTranslation(string[27] ..e%multiplayer.player.left, array[1])
#2 pmsrc/src/Server(1279): pocketmine\player\Player->sendMessage(object pocketmine\lang\Translatable#29398)
#3 pmsrc/src/player/Player(2102): pocketmine\Server->broadcastMessage(object pocketmine\lang\Translatable#29398)
#4 pmsrc/src/network/mcpe/NetworkSession(530): pocketmine\player\Player->onPostDisconnect(string[13] Server closed, object pocketmine\lang\Translatable#29398)
#5 pmsrc/src/network/mcpe/NetworkSession(509): pocketmine\network\mcpe\NetworkSession->pocketmine\network\mcpe\{closure}()
#6 pmsrc/src/network/mcpe/NetworkSession(533): pocketmine\network\mcpe\NetworkSession->tryDisconnect(object Closure#29389, string[13] Server closed)
#7 pmsrc/src/network/NetworkSessionManager(79): pocketmine\network\mcpe\NetworkSession->disconnect(string[13] Server closed)
#8 pmsrc/src/Server(1491): pocketmine\network\NetworkSessionManager->close(string[13] Server closed)
#9 pmsrc/src/Server(1672): pocketmine\Server->forceShutdown()
#10 pmsrc/src/Server(1571): pocketmine\Server->crashDump()
#11 pmsrc/src/Server(1066): pocketmine\Server->exceptionHandler(object LogicException#137375)
#12 pmsrc/src/PocketMine(304): pocketmine\Server->__construct(object BaseClassLoader#3, object pocketmine\utils\MainLogger#2, string[6] /home/, string[14] /home/plugins/)
#13 pmsrc/src/PocketMine(327): pocketmine\server()
#14 pmsrc(11): require(string[50] phar:///home/PocketMine-MP.phar/src/PocketMine.php)
-— End of exception information —-
2022-08-09 [00:11:03.021] [Server thread/EMERGENCY]: Crashed while crashing, killing process

**Comment by r3pt1s** [comment]
I would say that this error comes up through one of your plugins.

**Comment by ZippingBoat9588** [comment]
@PmmpDevelop so you use Pure perms/Chat?
