### ISSUE TITLE
Client Crash with Floating text particles

### ISSUE THREAD

**Issue by xLordShadow** [pmmp/PocketMine-MP#5216]
### Issue description

- Expected result: What were you expecting to happen?
You spawn the particle without a title and it works as it normally would.
- Actual result: What actually happened?
If no title is present, there is a client bug that causes the text to flicker due to there being an empty line in the text. The player eventually crashes. 

### Steps to reproduce the issue
1. Spawn a particle without a title set
2. Watch it flicker till you crash

### OS and versions

* PocketMine-MP: 4.7.0 (git hash: 0000000000000000000000000000000000000000)
* PHP: 8.0.13
* Using JIT: no
* Server OS: linux
* Game version: Win10

### Plugins

- If you remove all plugins, does the issue still occur?
Yes
- If the issue is **not** reproducible without plugins:
  - Have you asked for help on our forums before creating an issue?
  - Can you provide sample, *minimal* reproducing code for the issue? If so, paste it in the bottom section

### Crashdump, backtrace or other files
None

**Comment by dktapps** [comment]
Word is that Microsoft is working on a fix for this problem, so I'm going to close this. It doesn't really make sense to create a floating text without any text, anyway...

**Comment by xLordShadow** [comment]
> Word is that Microsoft is working on a fix for this problem, so I'm going to close this. It doesn't really make sense to create a floating text without any text, anyway...

Sorry, the ft was made with text, just without a title. ($particle->setTitle())
