### ISSUE TITLE
Internal ServerException {code :500 }

### ISSUE THREAD

**Issue by Apoorslime** [pmmp/PocketMine-MP#5217]
## Introduction to the problem
 tried to install Pocketmine-MP over and over again however it always shows me the same error **`Internal ServerException { code : 500 }`**.

## Possible cause
The error may occur due to memory, if you have no space on the device as a result it will show the error and will not load the server version list.

Many people have had this problem project, hope you can solve it

![Screenshot_2022-08-10-13-43-03-66_3686cb59f45a8f4a2b1e8d6e99664d6d](https://user-images.githubusercontent.com/82715467/183893999-36ae60fa-d613-4d4b-8fb1-37df0b8c4cec.jpg)

**Comment by dktapps** [comment]
This app has nothing to do with PMMP.

**Comment by harmas12** [comment]
how to fix this error if i have a large amount of memory
