### ISSUE TITLE
Server crashed

### ISSUE THREAD

**Issue by Likan-dep** [pmmp/PocketMine-MP#5219]
[Thu_Aug_11-12.07.28-CEST_2022.log](https://github.com/pmmp/PocketMine-MP/files/9307938/Thu_Aug_11-12.07.28-CEST_2022.log)

**Comment by Superomarking** [comment]
This has been fixed in [7e6bea5](https://github.com/NetherGamesMC/PocketMine-MP/commit/7e6bea5d0de7d99d9df57c4c6020f1a90066ba02), This isn't really a pmmp but NG's multiprotocol's issue, Don't state this here.
