### ISSUE TITLE
CreativeContentPacket encoding takes a long time

### ISSUE THREAD

**Issue by Nerahikada** [pmmp/PocketMine-MP#5229]
### Issue description
It takes a long time to change the game mode of a player.
The reason is that the creation of the CreativeContentPacket is taking a long time.
See this PR for details: #5118

**Comment by dktapps** [comment]
The timings reports I received from servers after 4.16 didn't really indicate any major issues with this. Most of the reports I saw put it in a 3-10 ms ballpark, which is not great, but also not that big of a problem, since it's a cold path.

**Comment by dktapps** [comment]
Related to #5703

**Comment by Nerahikada** [comment]
I no longer have the resources to reproduce this issue so I can't confirm it, but I'm closing it because #5703 has been implemented
