### ISSUE TITLE
New found action type?

### ISSUE THREAD

**Issue by jasonwynn10** [pmmp/PocketMine-MP#523]
### Issue description

Whilst playing on a server with some friends, I noticed the console fill up with a debug message.
### Steps to reproduce the issue

1. Have player on PC do things on the server

### OS and versions

* PocketMine-MP: 1c2895e
* PHP: 7.0.3
* Server OS: Win10
* Game version: Win10

### Crashdump, backtrace or other files

* `[15:14:03] [Server thread/DEBUG]: Unhandled/unknown player action type 17 from squidjgaming`

**Comment by jasonwynn10** [comment]
The server has no plugins or anything. I will keep testing to get a more specific cause.

**Comment by dktapps** [comment]
It's something to do with punching blocks in spectator mode last I checked. Not certain of that though.

**Comment by madecode15** [comment]
The thought of this going unnoticed if dktapps did not add the unhanded action message. Always thinking ahead.

**Comment by thebigsmileXD** [comment]
17 = break in A/SPC, 16 = place in A/SPC

**Comment by dktapps** [comment]
This appears to be the Build Denied action from Education Edition. MCPE does not send this action anymore, so I'm going to close this.
