### ISSUE TITLE
Using setItemInHand in PlayerItemHeldEvent sets the item in the previously held slot

### ISSUE THREAD

**Issue by Muqsit** [pmmp/PocketMine-MP#525]
### Issue description

Using \pocketmine\Player::getInventory()->setItemInHand(Item::class) sets the item in "highlited slot + 1" slot (so, if the player is on slot 4, it'll set the item on slot 5).

### Steps to reproduce the issue

Using this code:
```
public function onItemHold(PlayerItemHeldEvent $event){
    if($event->getItem()->getId() === Item::APPLE){
        $event->getPlayer()->getInventory()->setItemInHand(Item::get(Item::BONE));//sets item bone in slot: "getHeldItemSlot() + 1".
    }
}
```

### OS and versions

* PocketMine-MP: 1c2895e
* PHP: 7.0.17
* Server OS: Ubuntu 14.04 64-bit
* Game version: Win10

### Crashdump, backtrace or other files

-===-

**Comment by SOF3** [comment]
PlayerItemHeldEvent is fired before the hotbar slot changes. That's why setItemInHand does not change the item the user clicked.

**Comment by Muqsit** [comment]
@SOF3 so there's basically no way of changing the item that the player is holding other than using a task, is that what you are trying to say?

**Comment by SOF3** [comment]
You can do it through `$event->getPlayer()->getInventory()->setItem($event->getInventorySlot(), Item::get(Item::BONE));`.

This issue remains valid until there is proper documentation about that. (But probably many similar cases around the event API)

**Comment by Muqsit** [comment]
@SOF3 Thanks. Some background: I am shifting my plugins from a spoon to pmmp, and it looks like the spoon dktapps worked for, hadn't have this problem.

**Comment by dktapps** [comment]
I might mention that this method does not exist in BaseInventory... :p

**Comment by TheDiamondYT1** [comment]
@dktapps No, but it exists in [PlayerInventory](https://github.com/pmmp/PocketMine-MP/blob/master/src/pocketmine/inventory/PlayerInventory.php#L177#L179)

**Comment by dktapps** [comment]
@TheDiamondYT1 duh. I'm pointing out his title is incorrect.

**Comment by TheDiamondYT1** [comment]
@dktapps Ohhh

**Comment by dktapps** [comment]
nice, I also noticed that the inventory slot reported in the event is frequently the previously held inventory slot as opposed to the one they are trying to equip... gg me

**Comment by dktapps** [comment]
I'm going to close this in favour of #851 .
