### ISSUE TITLE
Client crashed by clicking on Decoration tab

### ISSUE THREAD

**Issue by JaapTijmes** [pmmp/PocketMine-MP#5250]
### Additional comments (optional)

- switch gamemode to creative
- open inventory
- click on decoration tab
- client crash

Server:
- no error
- PocketMine-MP version 4.7.3
- no plugin
- Vanilla installation

Ig there are some missing registerd items ore they are not matched

Thx

**Comment by dktapps** [comment]
I'm not able to reproduce this on 1.19.21.
