### ISSUE TITLE
(PM5) Bug in the animation of suspicious stew

### ISSUE THREAD

**Issue by MrGalletaYT** [pmmp/PocketMine-MP#5253]
### Issue description

- Expected result: What were you expecting to happen?
Eating animation is reproduced when consuming a suspicious stew in survival
- Actual result: What actually happened?
The animation does not it played

### Steps to reproduce the issue
1. Get a suspicious stew
2. Change your gamemode to survival
3. Consume the suspicious stew

### OS and versions

* PocketMine-MP: fedd5416636df18654d7883dc3cd8a72b3351538
* PHP: 8.0
* Using jit: no 
* Server OS: windows 10
* Game version: Android

### Plugins
No plugins

**Comment by IvanCraft623** [comment]
Reproduced

https://user-images.githubusercontent.com/57236932/186551435-9ac06e4d-fff7-43a2-8cb2-ce9303006dc7.mp4

**Comment by IvanCraft623** [comment]
This is a client bug: https://bugs.mojang.com/browse/MCPE-122491
