### ISSUE TITLE
Server Crash

### ISSUE THREAD

**Issue by BeeAZ-pm-pl** [pmmp/PocketMine-MP#5264]
### Issue description

- Actual result: The Server Is Running Normal For A Short Time When I Reconnect the VPS I See The Server Close And Show Below Line

### Steps to reproduce the issue
...

### OS and versions

* PocketMine-MP: 4.8.1
* PHP: 8.0.13
* Using JIT: no
* Server OS: Window Server 2016 Standard
* Game version:  1.19.21
* Android 

### Plugins
...

### Crashdump, backtrace or other files

https://pastebin.com/hBBzAsEw

**Comment by KanekiOnMC** [comment]
Hello, I think you have to try to reinstall the bin or Pocketmine

**Comment by KanekiOnMC** [comment]
And maybe check if you have installed Visual sstudioif you haven't , here is the doc here: 
[Installation doc - PMMP](https://doc.pmmp.io/en/rtfd/installation/installing-manually.html)
