### ISSUE TITLE
Server crashed with unsupported item in inventory in PM5

### ISSUE THREAD

**Issue by leolee3914** [pmmp/PocketMine-MP#5265]
Link to crashdump: https://crash.pmmp.io/view/7444891

### Additional comments (optional)
1. join a server which is using PM4
2. /give (your ID) crossbow
3. update the server to PM5 (git hash: d5762d3f4487772ffb6b7c77af4cd659585f6520)
4. join the server

**Comment by dktapps** [comment]
Duplicate of #5128
