### ISSUE TITLE
Use attributes instead of phpdoc to manipulate events and their handlers.

### ISSUE THREAD

**Issue by JuraSciix** [pmmp/PocketMine-MP#5280]
## Description
I suggest to abandon annotation via phpdoc and use PHP 8 attributes. In particular, I propose configuring and handling events through attributes, as shown in the repository below.

## Justification
Modern. Comfortable

## Alternative methods
I have already tried to partially implement this through a plugin: https://github.com/JuraSciix/AdvancedEvents

**Comment by ghost** [comment]
BC-break. Just add an annotation

**Comment by dktapps** [comment]
> Modern. Comfortable

This is not a good enough reason to make a BC break.

In addition, this has already been proposed here: #4865
