### ISSUE TITLE
Smithing does not work if upgradable item is enchanted

### ISSUE THREAD

**Issue by ipad54** [pmmp/PocketMine-MP#5282]
### Issue description

- Actual result: Smithing does not work if upgradable item is enchanted

### Steps to reproduce the issue
1. Enchant diamond tool/armor and try to upgrade it using smithing table

### OS and versions
* PocketMine-MP: 5.0.0 (https://github.com/pmmp/PocketMine-MP/commit/d5762d3f4487772ffb6b7c77af4cd659585f6520)
* PHP: 8.0.13
* Using JIT: no
* Server OS: Windows
* Game version: Android/iOS/Win10/Xbox/PS4/Switch

### Crashdump, backtrace or other files

https://www.youtube.com/watch?v=8BVlKOeE2vo

**Comment by dktapps** [comment]
This is most likely going to remain broken until we switch to the ItemStackRequest system.

**Comment by dktapps** [comment]
Related to #5179

**Comment by dktapps** [comment]
The underlying issue here is fixed by 8408da853424ae3d4edecfbe873eb8126a6fb95d; however, the implementation of smithing has been changed by Mojang, and the new method has not yet been implemented by PM.
