### ISSUE TITLE
Target directory path does not exist or is not a directory

### ISSUE THREAD

**Issue by KanekiOnMC** [pmmp/PocketMine-MP#5283]
Link to crashdump: https://crash.pmmp.io/view/7491854

**Comment by KanekiOnMC** [comment]
Hello, I tried to updrade Golden Armor's Protection and Durability and make the OveryTagsUI Listen the PlayerDeathEvent and register the killer and his number of kills on a YAML File

**Comment by KanekiOnMC** [comment]
But when I hit a player that equipped the Golden Armor says that he gets no Damage, and after some Combo with a Diamond Sword with Sharpness V Enchant, the server crashes and I see that the player is supposed to be dead on the Backtrace.

**Comment by KanekiOnMC** [comment]
Ummm... It's not a support request

**Comment by KanekiOnMC** [comment]
It's a problem with Pocketmine

**Comment by KanekiOnMC** [comment]
You can try it on a server, you will see

**Comment by alvin0319** [comment]
> It's a problem with Pocketmine

> Warning: the OveryTagsUI plugin was indirectly involved in this crash. This may be a false positive. Please contact the plugin author before opening a bug ticket.

Crashdump tells you that this crash was caused by the plugin, not PocketMine.

**Comment by KanekiOnMC** [comment]
> > It's a problem with Pocketmine
> 
> > Warning: the OveryTagsUI plugin was indirectly involved in this crash. This may be a false positive. Please contact the plugin author before opening a bug ticket.
> 
> Crashdump tells you that this crash was caused by the plugin, not PocketMine.

Check the Backtrace, it says that the player is supposed to be dead, and the Plugin is Listening to the PlayerDeathEvent

**Comment by Azvyl** [comment]
> Check the Backtrace, it says that the player is supposed to be dead, and the Plugin is Listening to the PlayerDeathEvent

no, it says that the directory path `/home/OveryNew/plugin_data/OveryTagsUI/other/killdata/data.yml` doesn't exist

**Comment by KanekiOnMC** [comment]
How is that possible
