### ISSUE TITLE
Incorrect default state of mushroom block when block-picked

### ISSUE THREAD

**Issue by dotV3** [pmmp/PocketMine-MP#5284]
### Issue description

- Expected result: When picking the block Red Mushroom Block (100:14) it should return the same block with the same meta (100:14)
- Actual result: The block was returned but a different meta (100:0)

### Steps to reproduce the issue
1. Use creative inventory or creative to get Red Mushroom Block (in creative it's 100:14 and 100:0 does not exist in the creative inventory)
2. Place it
3. Use pick block to get the placed block

### OS and versions
* PocketMine-MP: 4.8.0
* PHP: 8.0.19
* Using JIT: no
* Server OS: Linux
* Game version: Android/iOS/Win10/Xbox/PS4/Switch

### Plugins
- If you remove all plugins, does the issue still occur? Yes

**Comment by dktapps** [comment]
Mushroom blocks are a headache to implement, since they break a lot of the normal rules of item data retention.

In PM5 the behaviour is similarly bizarre, with the same blocks appearing twice.

**Comment by dotV3** [comment]
Good luck Dylan fr.
