### ISSUE TITLE
T_Variable

### ISSUE THREAD

**Issue by raycrawford** [pmmp/PocketMine-MP#529]
I am installing PMMP and getting the following error:

./start.sh  PHP Parse error:  syntax error, unexpected 'class' (T_CLASS), expecting identifier (T_STRING) or variable (T_VARIABLE) or '{' or '$' in /PocketMine-MP/src/pocketmine/PocketMine.php on line 121

Install is happening in a CentOS container from the cloned master as of today.

[root@fe49c938ed61 PocketMine-MP]# php -v
PHP 5.4.16 (cli) (built: Nov  6 2016 00:29:02) 
Copyright (c) 1997-2013 The PHP Group
Zend Engine v2.4.0, Copyright (c) 1998-2013 Zend Technologies
[root@fe49c938ed61 PocketMine-MP]#

**Comment by Muqsit** [comment]
PMMP runs on PHP 7
