### ISSUE TITLE
Sometimes when you join chunks aren't loading

### ISSUE THREAD

**Issue by Misteboss** [pmmp/PocketMine-MP#530]
### Issue description
Sometimes chunks aren't loading when you spawn and you are moving very fast and when i try to /kill me i don't receive the RespawnPacket and i need to restart my game

### Steps to reproduce the issue

1. ... Join the server 
2. ... See

### OS and versions

* PocketMine-MP: last api3\network commit
* PHP: 7.0.2
* Server OS: Debian
* Game version: PE/Win10 

### Crashdump, backtrace or other files

* ...

**Comment by dktapps** [comment]
Steps to reproduce:

- /tp ~10000 ~ ~10000
- Quit and rejoin
- /kill
- spaz

**Comment by Misteboss** [comment]
Yes sometimes when i spawn at the spawnpount i have the same issue

**Comment by dktapps** [comment]
Yeah, it's a common issue. I'm not 100% certain why it's happening.

**Comment by dktapps** [comment]
To clarify, the cause of the client-sided spaz is PocketMine teleporting the player into chunks which are not yet loaded. The missing chunks _always_ seem to be the square of ~9 chunks around the spawnpoint.

**Comment by Misteboss** [comment]
And if someone know a hack or a way to rensend chunks tell me pls (Waiting it to be fixed)

**Comment by dktapps** [comment]
Seems that delayed teleport and client-sided expecting respawn immediate teleportation don't play nice together. It appears that in some circumstances the client will ignore distant chunks after a Respawn is sent, unless they are actually teleported directly to that area as chunks are loaded. Very strange issue.

**Comment by Misteboss** [comment]
Ok thanks i will test it in few hours

**Comment by Misteboss** [comment]
Btw i don't know if this have a link with this issue but when i teleport or sendTitle(no link) onPlayerJoinEvent the player isn't teleported and sometimes didn't receive the title, and in debug mode it's written that they are sended too early, maybe the PlayerJoinEvent is called too early ?

**Comment by dktapps** [comment]
Make sure not to confuse PlayerJoinEvent with PlayerLoginEvent.

**Comment by Misteboss** [comment]
nop it's not the PreLoginEvent but the JoinEvent ^^

**Comment by Misteboss** [comment]
Uhmm sorry it was PreLoginEvent it's my fault ^^

**Comment by Misteboss** [comment]
I think I found on other issue, i need to did some test to verify ^^

**Comment by Misteboss** [comment]
Btw about you're chunk-patch, is it fixing the same problem who is happening onJoin ?

**Comment by Misteboss** [comment]
Should i had `$this->teleportImmediate($pos);` at https://github.com/pmmp/PocketMine-MP/blob/master/src/pocketmine/Player.php#L846

**Comment by dktapps** [comment]
No, it won't solve the join problem, only the death issue.

**Comment by dktapps** [comment]
Debugging with a coordinates resource pack I noticed some unusual peculiarities in the respawn behaviour. If I remember, I'll debug this tomorrow.

**Comment by optimusprime338** [comment]
@dktapps this seems to be happening again!
