### ISSUE TITLE
missing enchantment swift sneak

### ISSUE THREAD

**Issue by xerenahmed** [pmmp/PocketMine-MP#5301]
### Issue description

Needs implementation for [swift sneak enchantment](https://minecraft.fandom.com/wiki/Swift_Sneak) 

Summary:
Swift Sneak is a non-renewable [enchantment](https://minecraft.fandom.com/wiki/Enchantment) that can be applied to [leggings](https://minecraft.fandom.com/wiki/Leggings) and allows the player to walk more quickly while [sneaking](https://minecraft.fandom.com/wiki/Sneaking).

**Comment by dktapps** [comment]
This should be pretty trivial to implement. I don't think the server currently does anything for sneaking, other than just enabling and disabling the flag.
