### ISSUE TITLE
Kick reason not showed when kicking after LoginEvent

### ISSUE THREAD

**Issue by dadodasyra** [pmmp/PocketMine-MP#5321]
### Issue description

- Expected result: The client should show the reason of the kick whilst kicking between Login and Join events.
- Actual result: The client shows a generic kick message (Disconnected from the server)

### Steps to reproduce the issue
```php
class Main extends PluginBase {
    protected function onEnable(): void {
        $this->getServer()->getPluginManager()->registerEvents(new class() implements Listener {
            public function onLogin(PlayerLoginEvent $event): void {
              $event->setKickMessage("Hello world");
              $event->cancel();
            }
        }, $this);
    }
}
```

### OS and versions
* PocketMine-MP: 4.9.0
* PHP: 8.0.15
* Using JIT: no
* Server OS: Linux
* Game version: Tried on Windows, probably every platforms

### Plugins
- If you remove all plugins, does the issue still occur? Yes

### More infos
The problem is present in every kicking way while doing it between Login and Join event. Even while using `Player->kick()` on LoginEvent.
Maybe this is a client sided issue, maybe not. Maybe PMMP close the socket too early before the client gets the disconnect packet.
In my memories this bug wasn't existing in PM3. 
This could be related to #4588, #4592 #4594 
![image](https://user-images.githubusercontent.com/44753923/194047435-6ba63ca7-d3fe-4f18-b64d-21b004cc12ea.png)

**Comment by dktapps** [comment]
This issue has been around for years and I've tried many times to work around it. The most recent workaround in RakLib (allowing the client to end the session itself) should have taken care of this.

Closing as a client issue (WF).
