### ISSUE TITLE
put a special character freezes the cmd

### ISSUE THREAD

**Issue by crischutu07** [pmmp/PocketMine-MP#5329]
### Issue description

- Expected result: if I put the special, it must be alright
- Actual result: cmd freezes when do that

### Steps to reproduce the issue
1. run the server 
2. Put a special character 
3. Cmd freezes 
### OS and versions

* PocketMine-MP: 4.9.0
* PHP: 8.0.22
* Using JIT: yes
* Server OS: Windows Server 2016
* Game version: 1.19.30

### Plugins

- If you remove all plugins, does the issue still occur? Yes
- If the issue is **not** reproducible without plugins:
  - Have you asked for help on our forums before creating an issue? Yes
  - Can you provide sample, *minimal* reproducing code for the issue? If so, paste it in the bottom section

### Crashdump, backtrace or other files

https://user-images.githubusercontent.com/81855366/194704588-1b6e323a-7b18-4124-a450-a93888b6eed1.mp4

**Comment by Endermanbugzjfc** [comment]
Well, it was not actually frozen. It was just not responding to the command. The server is still running.

If your command has other non-special characters, the server should respond, but excluding them. Example: `àb` -> `b`.

**Comment by crischutu07** [comment]
> Well, it was not actually frozen. It was just not responding to the command. The server is still running.

Yep but, when do that I can't type anything
