### ISSUE TITLE
Health changes are not reflected properly on the client side

### ISSUE THREAD

**Issue by ch4rindo** [pmmp/PocketMine-MP#5356]
### Issue description

- Expected result: Set the player's health and maximum health to 20
- Actual result: The player's maximum health changes normally, but the health appears to remain unchanged (var_dump returns a float(20), but the client-side display is unchanged).

### Steps to reproduce the issue
1. Set the player's health and maximum health to 1 (Player->setHealth(1), Player->setMaxHealth(1))
2. Set the player's health and maximum health to 20 (Player->setHealth(20), Player->setMaxHealth(20))

### OS and versions

* PocketMine-MP: 4.9.2
* PHP: 8.1.9
* Using JIT: no
* Server OS: Win10
* Game version: Win10

### Plugins
DevTools v1.16.0, EvalBook v0.1.2, RedstoneCircuit v3.0.6

**Comment by DaisukeDaisuke** [comment]
Could you please provide a code, photo or video that reproduces this issue?
This issue is vague at this time and may not be reproducible.

**Comment by Nerahikada** [comment]
reproducible code:
```php
public function onInteract(PlayerInteractEvent $event) : void{
	$health = match($event->getAction()){
		PlayerInteractEvent::LEFT_CLICK_BLOCK => 1,
		PlayerInteractEvent::RIGHT_CLICK_BLOCK => 20,
	};
	$player = $event->getPlayer();
	$player->setMaxHealth($health);
	$player->setHealth($health);
}
```

**Comment by dktapps** [comment]
This looks like a client bug to me. If you take damage afterwards it shows correctly.
