### ISSUE TITLE
Server crash

### ISSUE THREAD

**Issue by Wengareki** [pmmp/PocketMine-MP#5370]
PocketMine-MP Crash Dump Fri Oct 28 17:08:12 UTC 2022

PocketMine-MP version: 4.10.0 [Protocol 557]
Git commit: 0d5287bf0bd7138113e1c154d3c3a3b83a407d82
PHP version: 8.0.24
OS: Linux, linux

Error: Typed property pocketmine\network\mcpe\protocol\SetActorDataPacket::$syncedProperties must not be accessed before initialization
File: pmsrc/vendor/pocketmine/bedrock-protocol/src/SetActorDataPacket
Line: 57
Type: Error
Backtrace:
#0 pmsrc/vendor/pocketmine/bedrock-protocol/src/DataPacket(84): pocketmine\network\mcpe\protocol\SetActorDataPacket->encodePayload(object pocketmine\network\mcpe\protocol\serializer\PacketSerializer#126796)
#1 pmsrc/vendor/pocketmine/bedrock-protocol/src/serializer/PacketBatch(54): pocketmine\network\mcpe\protocol\DataPacket->encode(object pocketmine\network\mcpe\protocol\serializer\PacketSerializer#126796)
#2 pmsrc/src/network/mcpe/NetworkSession(466): pocketmine\network\mcpe\protocol\serializer\PacketBatch::fromPackets(object pocketmine\network\mcpe\protocol\serializer\PacketSerializerContext#29490, object pocketmine\network\mcpe\protocol\StartGamePacket#115692, object pocketmine\network\mcpe\protocol\AvailableActorIdentifiersPacket#114936, object pocketmine\network\mcpe\protocol\BiomeDefinitionListPacket#114938, object pocketmine\network\mcpe\protocol\UpdateAttributesPacket#112451, object pocketmine\network\mcpe\protocol\AvailableCommandsPacket#111259, object pocketmine\network\mcpe\protocol\UpdateAbilitiesPacket#111376, object pocketmine\network\mcpe\protocol\UpdateAdventureSettingsPacket#111324, object pocketmine\network\mcpe\protocol\SetActorDataPacket#111278, object pocketmine\network\mcpe\protocol\InventoryContentPacket#111108, object pocketmine\network\mcpe\protocol\InventoryContentPacket#111115, object pocketmine\network\mcpe\protocol\InventoryContentPacket#111138, object pocketmine\network\mcpe\protocol\InventorySlotPacket#111193, object pocketmine\network\mcpe\protocol\MobEquipmentPacket#111100, object pocketmine\network\mcpe\protocol\CreativeContentPacket#111184, object pocketmine\network\mcpe\protocol\CraftingDataPacket#126763, object pocketmine\network\mcpe\protocol\PlayerListPacket#126762, object pocketmine\network\mcpe\protocol\SetActorDataPacket#115815, object pocketmine\network\mcpe\protocol\SetActorDataPacket#115827, object pocketmine\network\mcpe\protocol\SetActorDataPacket#114674, object pocketmine\network\mcpe\protocol\UpdateAttributesPacket#126771)
#3 pmsrc/src/network/mcpe/NetworkSession(1118): pocketmine\network\mcpe\NetworkSession->flushSendBuffer()
#4 pmsrc/src/network/NetworkSessionManager(67): pocketmine\network\mcpe\NetworkSession

**Comment by dktapps** [comment]
This is caused by a plugin.
