### ISSUE TITLE
Breaking a durable item with more than one count gives it infinite durability

### ISSUE THREAD

**Issue by JavierLeon9966** [pmmp/PocketMine-MP#5378]
### Issue description
Getting a durable item like a diamond sword with a count more than 1 in one slot and breaking gives it infinite durability instead of resetting the durability of the item with.

### Steps to reproduce the issue
1. Give yourself a durable item with more than one count in one slot
2. Break it
3.  You will notice the item will have used all its durability but can't be broken

### OS and versions

* PocketMine-MP: 4.10.0 (git hash: 0d5287bf0bd7138113e1c154d3c3a3b83a407d82)
* PHP: 8.0.24
* Using JIT: no 
* Server OS: win
* Game version: Win10

**Comment by dktapps** [comment]
I think the current implementation was supposed to mimic the vanilla behaviour at the time, but it's been done incorrectly. In any case, the vanilla implementation -- and that of PM -- are not really defined behaviour, since this should never occur without plugin intervention anyway.
