### ISSUE TITLE
Using a command alias with "$1" will fill the argument with an empty string

### ISSUE THREAD

**Issue by JavierLeon9966** [pmmp/PocketMine-MP#5379]
### Issue description
When adding a command alias to pocketmine.yml and you are using the argument "$1" (`say $1`)  will invoke the command with an empty string instead of not using the argument and fail if neccessary.

### Steps to reproduce the issue
1. Add a command alias: `test: say $1`
2. Execute `test` in console
3. The command output will be `[Server] `

### OS and versions

* PocketMine-MP: 4.10.0
* PHP: 8.0.24
* Using JIT: no 
* Server OS: win
* Game version: Win10

**Comment by dktapps** [comment]
Related to #5354

**Comment by dktapps** [comment]
This appears to be intended behaviour. `$1` is considered an optional parameter and will be filled with an empty string if not provided. I'm not really sure what else we could fill it with. Use `$$1` if you want to make the parameter mandatory.

It's possible we could just leave the `$args` offset missing, and then simply require that `$args` must be a linear array (no holes). This would avoid passing empty strings to commands.
