### ISSUE TITLE
Spawn point is setting in the void when using special seed

### ISSUE THREAD

**Issue by ipad54** [pmmp/PocketMine-MP#5390]
### Issue description
- Actual result:  Spawn point is setting in the void when using special seed, video: https://www.youtube.com/watch?v=UXnBnrVf6ks
 
### Steps to reproduce the issue
1. Delete your player data (to reset position)
2. Create a fresh world with seed 2040763946

### OS and versions
* PocketMine-MP: 5.0.0 (68e862b6fa26fec380ffc7ad6d9f9f2c4c7e561d)
* PHP: 8.0.24
* Using JIT: no
* Server OS: win
* Game version: Android/iOS/Win10/Xbox/PS4/Switch

### Plugins
This issue can be reproduced without plugins

**Comment by hausemaster3734** [comment]
Fix:
if($seed == 2040763946) {
$spawnPos = new Vector3(128, 63, 121);
}

**Comment by dktapps** [comment]
This occurs when the blocks at the default spawn (usually y=70) are solid. It's supposed to seek upwards to find an appropriate spawn when this happens, but due to a misplaced `break` it just keeps going down instead.
