### ISSUE TITLE
Incorrect damage calculation for non-arrow projectiles

### ISSUE THREAD

**Issue by IvanCraft623** [pmmp/PocketMine-MP#5393]
### Issue description
The damage caused by non-arrow projectiles is wrong, due to `Projectile` class has code that should be in the `Arrow` class:
<https://github.com/pmmp/PocketMine-MP/blob/stable/src/entity/projectile/Projectile.php#L131>, in vanilla this is applied exclusively for arrows. Currently this is not affecting anything within pocketmine, because there are no implemented projectiles other than arrows that actually do damage.

- Expected result: What were you expecting to happen?
Projectiles that deal damage such as tridents do correctly calculated damage.

- Actual result: What actually happened?
Non-arrow projectiles do incorrect damage.

### Steps to reproduce the issue
1. Implement a new damaging projectile
2. Release the projectile
3. Note that the arrow damage logic in applied to it.

### OS and versions
* PocketMine-MP: 4.10.0
* PHP: 8.0.1

**Comment by dktapps** [comment]
I don't really understand why this affects tridents. Don't tridents use the same logic as arrows? They share much of the same code in Bedrock.

**Comment by IvanCraft623** [comment]
> I don't really understand why this affects tridents. Don't tridents use the same logic as arrows? They share much of the same code in Bedrock.

`much of the same code !== all code`

https://minecraft.fandom.com/wiki/Trident#Damage:
`The damage remains the same regardless of the trident's speed.`
