### ISSUE TITLE
0.16.0 Windows 10 Crash on Join

### ISSUE THREAD

**Issue by RedstoneAlmeida** [pmmp/PocketMine-MP#54]
### Issue description

Write a short description about the issue
I'm join in Server, Crash my Client, is possible fix?

### Steps to reproduce the issue

1. ...
2. ...

### OS and versions

* PocketMine-MP: Last Version from 0.16
* PHP: 7
* Server OS: Windows 10
* Game version: Win10 0.16.0

### Crashdump, backtrace or other files

* ...

**Comment by dktapps** [comment]
Not supported.

**Comment by RedstoneAlmeida** [comment]
You persecute me? here in PocketMine there in Genisys, I just to ask, and you and mega ignorant.

**Comment by dktapps** [comment]
0.16 hasn't yet been merged, it is still in testing. Therefore, issues relating to 0.16 are invalid and will be closed.
