### ISSUE TITLE
Custom particle atlas is not applying.

### ISSUE THREAD

**Issue by ghost** [pmmp/PocketMine-MP#5417]
### Issue description

- Expected result: Particle style from /textures/particle/*.png should appear.
- Actual result: Server is showing default(vanilla) particles.

### Steps to reproduce the issue
Video: https://youtu.be/SwJHFiTelng

### OS and versions
* PocketMine-MP: 4.10.0
* PHP: 8.0

**Comment by ghost** [comment]
Caused by: https://github.com/pmmp/PocketMine-MP/blob/65623351203658c8ac2850ca7d259bfd50e7d416/src/network/mcpe/handler/ResourcePacksPacketHandler.php#L127

How to fix: Chemistry is loading with priority 1 (On top of all resource packs). need to make chemistry loading on last.

**Comment by ghost** [comment]
It turned out that this is on the client side. I see two solutions to this problem:
1. Use a custom resource pack with chemistry (edited).
2. Make it possible to turn off chemistry in pocketmine.yml

**Comment by dktapps** [comment]
Does this work correctly in vanilla when chemistry is enabled on a world?

**Comment by ghost** [comment]
> Does this work correctly in vanilla when chemistry is enabled on a world?

No

**Comment by dktapps** [comment]
Then this should be reported on https://bugs.mojang.com, since it's not a PocketMine-MP issue.
