### ISSUE TITLE
Add `onInteractEntity` in Item

### ISSUE THREAD

**Issue by iBryanidk** [pmmp/PocketMine-MP#5431]
## Description
It should be added to get player interaction with an entity (with the item in hand, like in Nukkit), the method could be called here: https://github.com/pmmp/PocketMine-MP/blob/stable/src/player/Player.php#L1807

IDK which could be better to call, `onClickEntity` or `onInteractEntity`, the goal is to add that method on `Item`

## Justification
This can be useful for NameTag where `right-click` is used to assign the name to the entity. It may have some other utility but that is separate.

I made an example to show what I mean: https://github.com/iBryanidk/PocketMine-MP/commit/de1a490fd3d3f5c7e6db635559bbee854dde66ab (I think the 'bool' return type is unnecessary, as well as in 'onDestroyBlock', since it won't be used)

## Alternative methods
n/a

**Comment by dktapps** [comment]
Yes, I do think this is necessary. In fact it's one of the main reasons I wasn't happy with #5209.

**Comment by iBryanidk** [comment]
> Yes, I do think this is necessary. In fact it's one of the main reasons I wasn't happy with #5209.

I can do a PR about this to see how it goes

**Comment by dktapps** [comment]
This should stay open until the change has been merged
