### ISSUE TITLE
Add `.self` and `.other` permissions for `/gamemode`

### ISSUE THREAD

**Issue by dktapps** [pmmp/PocketMine-MP#5468]
## Description
Currently it's not possible to allow a player to change their own gamemode without also allowing them to change anyone's gamemode. This turned out to be inconvenient for test.pmmp.io.

## Alternative methods
You can write your own /gamemode command in a plugin, but that kinda sucks...

**Comment by IvanCraft623** [comment]
Would it also make sense to implement it for `/teleport` and `/give` ?

**Comment by dktapps** [comment]
For `/teleport` yes. For `/give` it's probably pointless since you can just toss the items on the ground anyway.

**Comment by dktapps** [comment]
List of commands that could benefit from this:

- /gamemode
- /tp
- /give
- /enchant
- /effect
- /spawnpoint
- /title
- perhaps /kick ?

Some other commands already have permissions like this, such as /clear and /kill.

**Comment by dktapps** [comment]
Implemented by #5470.
