### ISSUE TITLE
Non-vanilla behavour of when projectile damage is cancelled

### ISSUE THREAD

**Issue by IvanCraft623** [pmmp/PocketMine-MP#5475]
### Issue description

- Expected result: What were you expecting to happen?
 Projectiles should follow their normal trajectory and not combusts entities if when hitting an entity the damage is cancelled.

- Actual result: What actually happened?
 Projectiles are despawned and combusts the entity when damage is canceled

### Steps to reproduce the issue
1. Throw any projectile at an entity
2. Cancels the damage event

### OS and versions
* PocketMine-MP: 4.12.2
* PHP: 8.0
* Server OS: Win10

### Plugins

- If you remove all plugins, does the issue still occur?
- If the issue is **not** reproducible without plugins:
  - Have you asked for help on our forums before creating an issue?
  - Can you provide sample, *minimal* reproducing code for the issue? If so, paste it in the bottom section

### Crashdump, backtrace or other files
[Vanilla behavour](https://cdn.discordapp.com/attachments/715214348338855987/1056799795798347836/Projectile_with_no_hurtable_entity_test.mp4)

**Comment by dktapps** [comment]
I don't think this "vanilla behaviour" is really relevant. PM has had this behaviour since long before vanilla ever had such a thing.
