### ISSUE TITLE
PM5: Glowing Item Frames use incorrect blockentity

### ISSUE THREAD

**Issue by supercrafter333** [pmmp/PocketMine-MP#5478]
### Issue description

- Expected result: After a restart the items in glowing itemframes will be visible
- Actual result: If you restart your PM5-server and look at you glowing itemframes they will be looking as "emtpy" itemframes but it't just the item that isn't visible. If you try to add a **new** item to the glowing itemframe, your **old** item will be visible again in  the itemframe. 

### Steps to reproduce the issue
1. Put a item in a glowing itemframe
2. restart your server
3. look at the glowing itemframe (it will be "empty")
4. try to add a new (and different) item (you'll see you old item again)

### OS and versions

* PocketMine-MP: 5.0.0-ALPHA6
* PHP: 8.1.13
* Server OS: Linux Ubuntu 22.04
* Game version: Win11, Android 10

**Comment by dktapps** [comment]
does this happen with normal item frames?

**Comment by supercrafter333** [comment]
No, only with glowing item frames.

**Comment by dktapps** [comment]
It turns out glow item frames have a separate tile, which I didn't expect. It's going to be a hassle to fix.

**Comment by dktapps** [comment]
Fixed by ca1f1bf09fb646088d47f5cd819f8095e9255d3e.
