### ISSUE TITLE
[Suggestion] Add a setting to plugin.yml to avoid creating a directory in the plugin_data

### ISSUE THREAD

**Issue by BrandPVP** [pmmp/PocketMine-MP#5479]
## Description
Add a new setting "no_data: true" to plugin.yml

Tell me if i should make a PR

```name: Economy
main: Server\MyPlugin\Loader
version: 1.0.0
api: 4.0.0
no_data: true
```

## Justification
There is a lot of plugins that don't use the data folder, so we can get rid of empty folders without configs/files

## Alternative methods
https://poggit.pmmp.io/p/DataCleaning/3.0.4

**Comment by dktapps** [comment]
The point is to ensure the folder always exists, and it has no meaningful negative effects. It's like the `/data/data` directory on Android. Every app has its own directory whether it wants one or not. This is a conscious design decision made to simplify plugins.
