### ISSUE TITLE
InventoryCloseEvent never called

### ISSUE THREAD

**Issue by MHIGists** [pmmp/PocketMine-MP#5500]
### Issue description

Wanted to use InventoryCloseEvent but it never gets called when closing Player's inventory

### Steps to reproduce the issue
public function onInventoryClose(InventoryCloseEvent $event){
        echo '==========================================================' . 
    }

### OS and versions

* PocketMine-MP: 4.12.4
* PHP: 8.1
* Using JIT: no  
* Server OS: Windows 11
* Game version: Win10

### Plugins

DevTools v1.16.0, FormAPI v2.1.0

**Comment by dktapps** [comment]
The player is always viewing its own inventory, so there's no event to be called.
