### ISSUE TITLE
Player network send

### ISSUE THREAD

**Issue by joinasau** [pmmp/PocketMine-MP#5504]
### Issue description

- Expected result: that players on my server can play.
- Actual result: an unbearable lag and a huge flood of packets

### Steps to reproduce the issue
1. just let 100 players join the server
2. 

### OS and versions

* PocketMine-MP: latest
* PHP: latest
* Using JIT: yes
* Server OS: Ubuntu 18.04
* Game version: Android/iOS/Win10/Xbox/PS4/Switch/Linux

### Plugins
Really?

- If you remove all plugins, does the issue still occur? Yes

Description:

https://timings.pmmp.io/?id=254113

**Comment by IvanCraft623** [comment]
PocketMine-MP is not designed to support such a large number of players, split your server into multiple instances.

**Comment by UnknownOre** [comment]
> PocketMine-MP is not designed to support such a large number of players, split your server into multiple instances.

The timings say there's about 10 players on

**Comment by IvanCraft623** [comment]
> The timings say there's about 10 players on

Uhh, I read this:

> 1. just let 100 players join the server

However, this is Support Request
