### ISSUE TITLE
Pls add the option to change the Gravity

### ISSUE THREAD

**Issue by DemonicDev** [pmmp/PocketMine-MP#5525]
## Description
I want an API function, so i can change the Gravity of a player... 

## Justification
so i can manage the fall speed of a player and the jump high,,, so i could code for my own, that the gravity is specific per world
so yeah you could make many things, when you could change also the gravity

**Comment by dktapps** [comment]
Implemented by 59a04c971fdd177e565fb2cb398626546a773e92.
