### ISSUE TITLE
Proxyable Event Listeners

### ISSUE THREAD

**Issue by xerenahmed** [pmmp/PocketMine-MP#5529]
## Description
Listener register method uses `ReflectionClass->getMethods`. However, if you want to `wrap` or `proxy` a `Listener` (with __call magic method), you can't. You have the inner `Listener` class but you don't have any methods or their doc comments. 

## Justification
I'm using AwaitGenerator and I saw I'm repeatedly using `AwaitGenerator::f2c` so I want to wrap it.

## Alternative methods
It might not be the best idea but before `getMethods()` it can look for `getInnerListener(): Listener` method. If there is, search for it.

**Comment by xerenahmed** [comment]
Customizable Listener-Registrar might be way better idea

**Comment by dktapps** [comment]
I don't really understand the use case, and this sounds hella complicated to implement. There's no way to know which events would be handled by a __call(), so it would have to receive all events at every priority. That would cause a performance impact.

**Comment by xerenahmed** [comment]
Perhaps I just need to use my own algorithm and call `registerEvent` for my purpose, rather than `registerEvents`
