### ISSUE TITLE
Incorrect Deepslate drops

### ISSUE THREAD

**Issue by Azvyl** [pmmp/PocketMine-MP#5531]
### Issue description

- Expected result: Deepslate should drops Cobbled Deepslate when broken in survival

https://user-images.githubusercontent.com/67502532/214653418-d8cb3969-55a8-4bcb-8bf3-b2fa04f4e06e.mp4

- Actual result: Deepslate dropping Deepslate like using a silk touch

https://user-images.githubusercontent.com/67502532/214654083-4328f25d-fab3-44c0-9266-67b06ccedacf.mp4

### Steps to reproduce the issue
1. Breaking a Deepslate block

### OS and versions
* PocketMine-MP: 5.0.0-ALPHA9+dev
* PHP: 8.2.1
* Using JIT: no
* Server OS: linux
* Game version: Android

**Comment by dktapps** [comment]
Thanks, I completely forgot to implement this.
