### ISSUE TITLE
With a large radius of chunks, the packet sending speed limit is triggered

### ISSUE THREAD

**Issue by Gaprix** [pmmp/PocketMine-MP#5532]
### Steps to reproduce the issue
1. Set the chunk radius to 95 (server.properties and client)
2. Fly high
3. Wait for world autosave
4. "Receiving packets too fast" exception

### OS and versions

Command output | This server is running PocketMine-MP
Command output | Server version: 5.0.0-ALPHA8 (git hash: 5aa8b953a817491ea04f33cb1bc1e17e94796acf)
Command output | Compatible Minecraft version: 1.19.50 (protocol version: 560)
Command output | PHP version: 8.2.1
Command output | PHP JIT: disabled
Command output | Operating system: linux

### Plugins
none

### Crashdump, backtrace or other files
![изображение](https://user-images.githubusercontent.com/45711510/214674426-b63d318c-105c-42af-b9e9-b21703a43f23.png)
https://pastebin.com/PNJ95yPN

**Comment by Gaprix** [comment]
I noticed that this happens right after saving the world

**Comment by dktapps** [comment]
How long did the world take to autosave?

**Comment by Gaprix** [comment]
As you can see in the log, saving takes  44.226s

**Comment by dktapps** [comment]
Wow, that's pretty bad. The packet limiter allows a backlog of 5 seconds before it kicks you off the server.
