### ISSUE TITLE
Skin changes to Steve-Skin after join PM 4.14.0 server

### ISSUE THREAD

**Issue by supercrafter333** [pmmp/PocketMine-MP#5565]
### Issue description

- Expected result: Players can use their own skin in-game and their own skin is correct.
- Actual result: After a player joins a pmmp 4.14.0 server the skin changes to a steve-skin. If you open your settings-menu you can see your real skin, but you have a steve-skin in-game .

### Steps to reproduce the issue
1. Use a custom skin and join a pmmp 4.14.0 server
2. Use 3rd person

### OS and versions

* PocketMine-MP: 4.14.0
* PHP: 8.1.13
* Using JIT: no
* Server OS: Linux Ubuntu 22.04
* Game version: Win11, Win10

**Comment by jasonw4331** [comment]
I suspect this is a byproduct of the hack used to prevent the feedback loop on skin changes

**Comment by supercrafter333** [comment]
Do you mean [these changes](https://github.com/pmmp/PocketMine-MP/commit/7bbc04e6deaf5dd31d2d3f4f17e18517f1fcc440#diff-29e90796c25d0ce7acf2176465f3f5e1e9e5f9781547994227c877f02ba80bc9R41-R47)?

**Comment by dktapps** [comment]
It has nothing to do with that. Skins are just broken in 1.19.60 because Mojang did some pointless changes.

**Comment by dktapps** [comment]
Technical analysis: The client reverts any skin update which has a different skin ID than the skin it's locally using.

Word I'm hearing is that this will be fixed in 1.19.61. I'm aware some people have worked around it, but I don't think it's worth adding a hack for a bug that will be shortly fixed.
