### ISSUE TITLE
bedrock which is destroyed with a tnt

### ISSUE THREAD

**Issue by TEZULS** [pmmp/PocketMine-MP#5582]
### Issue description

- Expected result: I thought the bedrock would be unstoppable at explosion 
- Actual result: the bedrock was destroyed with the tnt

### Steps to reproduce the issue
1. set a tnt to quote from the bedrock
2. lite the tnt
3. look the bedrock

### OS and versions
* PocketMine-MP:
* PHP: 8.0.25
* Server OS: linux

### Plugins
none.

**Comment by jasonw4331** [comment]
Cannot reproduce on API 4 and you've not supplied all the necessary information.
