### ISSUE TITLE
Cut Copper Stairs cannot be selected in inventory (PM 5.0.0)

### ISSUE THREAD

**Issue by GH-PM** [pmmp/PocketMine-MP#5619]
### Issue description

- Expected result: When selecting the stairs, you can drag them to the inventory and use them
- Actual result: Selecting them removes them from the mouse

### Steps to reproduce the issue
1. Grab the stairs
2. See how it disappears the second you grab them

https://user-images.githubusercontent.com/127597296/224480140-b3e75ca7-fe55-4a44-b1f3-32df00001a7c.mp4

### OS and versions

* PocketMine-MP: 5.0.0-BETA1
* PHP: 8.0.28
* Using JIT: not supported
* Server OS: linux
* Game version: Win10

### Plugins

No plugins

**Comment by dktapps** [comment]
Does this happen with any other blocks?

**Comment by GH-PM** [comment]
> Does this happen with any other blocks?

I have tried a few more and it seems that the only affected block is that one

**Comment by dktapps** [comment]
How bizarre. How about waxed cut copper stairs?

**Comment by GH-PM** [comment]
https://user-images.githubusercontent.com/127597296/224496242-284fb2fa-f56d-46dd-b405-c3c519f006da.mp4

Take a look

**Comment by dktapps** [comment]
This might be a client bug - it's sending a mismatch transaction when I try to take the item from the inventory.

**Comment by dktapps** [comment]
Fixed by 8408da853424ae3d4edecfbe873eb8126a6fb95d.
