### ISSUE TITLE
Shulkers incorrectly provide support for blocks such as candles

### ISSUE THREAD

**Issue by GH-PM** [pmmp/PocketMine-MP#5621]
### Issue description

- Expected result: What were you expecting to happen? 

https://user-images.githubusercontent.com/127597296/224494521-d824317e-28ec-4c57-92b5-4ad3b62abe4d.mp4

- Actual result: What actually happened?

https://user-images.githubusercontent.com/127597296/224494566-7ddb9028-95b2-4f34-baaa-29a13306cf15.mp4

### Steps to reproduce the issue
1. Place a Shulker
2. Place candles on top of the Shulker
3. Got it

### OS and versions

* PocketMine-MP: 5.0.0-BETA1
* PHP: 8.0.28
* Using JIT: not supported
* Server OS: linux
* Game version: Win10

### Plugins

No plugins
- If you remove all plugins, does the issue still occur?
- If the issue is **not** reproducible without plugins:
  - Have you asked for help on our forums before creating an issue?
  - Can you provide sample, *minimal* reproducing code for the issue? If so, paste it in the bottom section

**Comment by dktapps** [comment]
Shulker boxes probably support other blocks they aren't supposed to as well, such as torches.

**Comment by dktapps** [comment]
Fixed by 6ea7fd7d6b7cb8219f7ffb54d15c8ddf2632d6e0
