### ISSUE TITLE
Water protrudes from the slabs (PM 5.0.0)

### ISSUE THREAD

**Issue by GH-PM** [pmmp/PocketMine-MP#5626]
### Issue description

- Expected result: What were you expecting to happen? 

https://user-images.githubusercontent.com/127597296/224537736-f19eb138-e818-4f49-9945-33b8456c2ac0.mp4

- Actual result: What actually happened?

https://user-images.githubusercontent.com/127597296/224537779-66cee0a4-5037-42f3-8960-a5ef737d70b2.mp4

### Steps to reproduce the issue
1. Dig a 1x1 hole
2. Put a slab in the hole
3. Put water on the slab
4. See how it rises and protrudes from the hole

### OS and versions

* PocketMine-MP: 5.0.0-BETA1
* PHP: 8.0.28
* Using JIT: not supported
* Server OS: linux
* Game version: Win10

### Plugins

0 plugins
- If you remove all plugins, does the issue still occur?
- If the issue is **not** reproducible without plugins:
  - Have you asked for help on our forums before creating an issue?
  - Can you provide sample, *minimal* reproducing code for the issue? If so, paste it in the bottom section

**Comment by Azvyl** [comment]
pocketmine doesn't have a waterlogging system yet
#3722
