### ISSUE TITLE
Enderpearl teleport

### ISSUE THREAD

**Issue by roimee6** [pmmp/PocketMine-MP#5631]
### Issue description

- Expected result: The pearl should be cancelled because the world is not the same as the player

- Actual result: When you throw a pearl in a world that you change world you will be teleported to the position of the pearl in the other world

### Steps to reproduce the issue
Pmmp: https://www.youtube.com/watch?v=lD8g8D7WNYQ
Minecraft: https://youtu.be/Aa1YzW3nHto

### OS and versions

* PocketMine-MP: 4.16.0

### Plugins

- If you remove all plugins, does the issue still occur?  yes

**Comment by GH-PM** [comment]
Duplicated of #3397
