### ISSUE TITLE
Face on blockbreak

### ISSUE THREAD

**Issue by roimee6** [pmmp/PocketMine-MP#5657]
## Description

Add a getFace method to the BlockBreak event when a player breaks a block 

## Justification

It can be done for the BlockPlace but not for the BlockBreak

**Comment by dktapps** [comment]
As far as I recall, this information is not available in the protocol, so we have no idea which face was being attacked when the block was broken. It might be possible to make this work for some cases using the information given to attackBlock(), but it wouldn't work for instabreak blocks and creative.

**Comment by roimee6** [comment]
okok
