### ISSUE TITLE
Wool color isn't displayed in item frames

### ISSUE THREAD

**Issue by JavierLeon9966** [pmmp/PocketMine-MP#5660]
### Issue description
When placing wool of any color it will always display as white.
- Expected result: The wool should display its corresponding color
- Actual result: The wool always displays as white

### Steps to reproduce the issue
1. Place wool that isn't white in an item frame

### OS and versions

* PocketMine-MP: 4.18.1 (git hash: cd603e82663937fa6660c78842a657acfbcc4bab)
* PHP: 8.1.16
* Using JIT: no
* Server OS: win
* Game version: Android

### Crashdump, backtrace or other files

https://user-images.githubusercontent.com/58715544/228649474-6e33d9de-bae2-487f-8f1f-1db35315e74a.mp4

**Comment by dktapps** [comment]
I suspect this will also happen if you put a non-white wool in an item frame on a 1.12 world and load it on 1.19.70.

**Comment by dktapps** [comment]
Confirmed, this bug also occurs when loading an old world on 1.19.70.

Reported as https://bugs.mojang.com/browse/MCPE-169154.
