### ISSUE TITLE
Invalid JWT Header

### ISSUE THREAD

**Issue by SkulZOnTheYT** [pmmp/PocketMine-MP#5662]
### Issue description

- Expected result: What were you expecting to happen?
- Actual result: What actually happened?

### Steps to reproduce the issue
1. login in the server
2. can not login in the server

### OS and versions

* PocketMine-MP: 4.18.1
* PHP: 8.0.28
* Using JIT: no 
* Server OS: linux
* Game version: Win10 (delete as appropriate)

### Plugins

- If you remove all plugins, does the issue still occur? "I Haven't tried it yet"
- If the issue is **not** reproducible without plugins:
  - Have you asked for help on our forums before creating an issue? "no"
  - Can you provide sample, *minimal* reproducing code for the issue? If so, paste it in the bottom section

### Crashdump, backtrace or other files

![Minecraft 30_03_2023 05_23_50](https://user-images.githubusercontent.com/92020118/228684607-dec6495f-fde0-4be3-9c4e-88101c18b346.png)

**Comment by SkulZOnTheYT** [comment]
please handle this immediately @dktapps

**Comment by jasonw4331** [comment]
Fixed in [`455dbad`](https://github.com/pmmp/BedrockProtocol/commit/455dbad93d29b4489b60910a41e38b8007b26563)
