### ISSUE TITLE
Offhand inventory doesn't work

### ISSUE THREAD

**Issue by Aduqate** [pmmp/PocketMine-MP#5667]
### Issue description
Placing any item in the offhand slot will simply prevent it from being placed there.
- Expected result: The Item should be placed in the offhand slot
- Actual result: Item doesn't go in the offhand slot

### Steps to reproduce the issue
1. Place an item in the offhand slot

### OS and versions

* PocketMine-MP:  4.18.2
* PHP: 8.0.28
* Using JIT: no
* Server OS: linux
* Game version: Win10

### Plugins

- If you remove all plugins, does the issue still occur? Yes

**Comment by dktapps** [comment]
Can you try to reproduce this with `debug.level` set to `2` in `pocketmine.yml` and paste the output?

**Comment by dktapps** [comment]
> [22:59:32.269] [DEBUG] [NetworkSession: mctestDylan] ItemStackRequest #-3 failed: Error processing action 0 (PlaceStackRequestAction): No such inventory slot :PlayerOffHandInventory#26773, slot: 1
[22:59:32.269] [DEBUG] [NetworkSession: mctestDylan] pocketmine\network\mcpe\handler\ItemStackRequestProcessException: "Error processing action 0 (PlaceStackRequestAction): No such inventory slot :PlayerOffHandInventory#26773, slot: 1" (EXCEPTION) in "pmsrc/src/network/mcpe/handler/ItemStackRequestExecutor" at line 363

This looks like some kind of weird bug in the client.

**Comment by dktapps** [comment]
Dragonfly has worked around the issue here: https://github.com/df-mc/dragonfly/blame/365f21525f4598e139fb59811486e4ba6630453e/server/session/handler_item_stack_request.go#L408
