### ISSUE TITLE
Add an API for enabling emote muting in chat

### ISSUE THREAD

**Issue by BrandPVP** [pmmp/PocketMine-MP#5669]
## Description
PlayerEmoteEvent->setMuted(true)

**Comment by ColinHDev** [comment]
`PlayerEmoteEvent::cancel()` might be the method you are searching for.

**Comment by JavierLeon9966** [comment]
That will just cancel the emote, not mute it from chat.

**Comment by ColinHDev** [comment]
Didn't know they get announced in the chat, my bad.

**Comment by dktapps** [comment]
#5512 might be a better solution for this

**Comment by dktapps** [comment]
Fixed by 5e7f18cbcf2240c3dac6c6dccd91c9bbda5a380a
