### ISSUE TITLE
PM5: Add `WoodStripEvent`

### ISSUE THREAD

**Issue by supercrafter333** [pmmp/PocketMine-MP#5672]
## Description
An event that's called when a wood-block was stripped.

## Justification
If you currently try to cancel wood-stripping you have to use the PlayerInteractEvent. But if you cancel the InteractEvent player are also not able to break wood.
I think a event for wood-stripping would be good.

**Comment by supercrafter333** [comment]
Plugin-developers should be able to cancel the event.

**Comment by Azvyl** [comment]
I'm not sure Dylan will be happy with this,
canceling the PlayerInteractEvent with the right click action should not cancel the block to break

**Comment by dktapps** [comment]
> I'm not sure Dylan will be happy with this, canceling the PlayerInteractEvent with the right click action should not cancel the block to break

This is correct.
