### ISSUE TITLE
Join Error

### ISSUE THREAD

**Issue by HopeDoggo20** [pmmp/PocketMine-MP#5677]
- Actual result: I can't join my Server (Im using https://server.pro)

### Steps to reproduce the issue
1. I join
2. Error Come: 
3. [Server thread/INFO]: 
4. [NetworkSession: ThorMagHunde] Session closed due to Invalid session. Reason: Invalid JWT header: JSON property "x5t" does not exist in object of type pocketmine\network\mcpe\protocol\types\login\JwtHeader

* PocketMine-MP: 4.17.0
* PHP: 8.0.12
* Using JIT: no
* Server OS: LINUX
* Game version: v1.19.73 (Ps4)

Plugins no

**Comment by Laith98Dev** [comment]
This issue already fixed, just update to latest pocketmine version.
