### ISSUE TITLE
Cannot drop items from the creative contents menu

### ISSUE THREAD

**Issue by JavierLeon9966** [pmmp/PocketMine-MP#5679]
### Issue description
When selecting an item from the creative contents menu and dropping it it doesn't actually drop.
- Expected result: The item drops.
- Actual result: The item doesn't drop.

### Steps to reproduce the issue
1. Go to creative mode.
2. Drop any item from the creative contents menu.

### OS and versions

* PocketMine-MP: 4.18.2 (git hash: 17a1266056e3aeaaf5e28db100137f05545ca549)
* PHP: 8.1.16
* Using JIT: no 
* Server OS: win
* Game version: Android

### Crashdump, backtrace or other files

https://user-images.githubusercontent.com/58715544/229597768-7f1ae229-dd0f-4271-84c8-583bf394ceea.mp4

**Comment by dktapps** [comment]
This happens because the magic "created item output" slot is not handled for the drop item case.
