### ISSUE TITLE
sand not falling

### ISSUE THREAD

**Issue by YasinK2003** [pmmp/PocketMine-MP#5684]
### Issue description

- Expected result: What were you expecting to happen?
- Actual result: What actually happened?

### Steps to reproduce the issue
1. place sand
2. destroy block below sand

### OS and versions

* PocketMine-MP: 4.18.3
* PHP: 8.0.28
* Using JIT: yes/no (delete as appropriate) 
* Server OS: linux
* Game version: Android/iOS/Win10/Xbox/PS4/Switch (delete as appropriate) 

### Plugins

none

- If you remove all plugins, does the issue still occur?
- If the issue is **not** reproducible without plugins:
  - Have you asked for help on our forums before creating an issue?
  - Can you provide sample, *minimal* reproducing code for the issue? If so, paste it in the bottom section

**Comment by dktapps** [comment]
I'm not able to reproduce this. Please provide more detail.

**Comment by dktapps** [comment]
Closing this due to unable to reproduce and no further details provided.
