### ISSUE TITLE
LevelDB world format unsupported

### ISSUE THREAD

**Issue by Fourghkmc** [pmmp/PocketMine-MP#5717]
### Issue description

- Expected result: What were you expecting to happen?
- I was trying to move vanilla BE world to PNMP
- Actual result: What actually happened?
- [03:00:36.033] [Server thread/ERROR]: Could not load world "world1": Unsupported format: LevelDB world format version 10 is currently unsupported

### Steps to reproduce the issue
1. Move all files in ./worlds folder of original MCBE official server to ./world1 of PNMP
2. Start PNMP in Docker

### OS and versions

* PocketMine-MP: 4.19.3
* PHP: 8.0.28
* Using JIT: Disabled (delete as appropriate) 
* Server OS: Docker (Running in Ubuntu 22.04 LTS)
* Game version: Win10 (delete as appropriate)

### Plugins

- If you remove all plugins, does the issue still occur?
- No plugins are installed
### Crashdump, backtrace or other files
- https://crash.pmmp.io/view/8701594

**Comment by SenseiTarzan** [comment]
If you have downgraded your server from pm5 to pm5 then it's normal or if you downloaded a Map mcbe on your server it's normal because it only supports levelDB version 8 and below It's completely normal
