### ISSUE TITLE
Bug craft still occurs

### ISSUE THREAD

**Issue by Nat392** [pmmp/PocketMine-MP#5718]
### Issue description

The crash bug with shift + click doesn't seem to be solved, it does it to me in 4.19.3.

### OS and versions
- PMMP Version : 4.19.3
- PHP Version : 8.0.25
- OS : debian 10

https://user-images.githubusercontent.com/54687432/233942066-121be4e4-4e9d-4009-89c2-a081edcddb3b.mov

**Comment by Nat392** [comment]
https://user-images.githubusercontent.com/54687432/233946591-ba597292-1e51-43d9-86c4-29b35b5b6653.mp4


And you can't even put items in a chest with shift + click

**Comment by dktapps** [comment]
I'm not able to reproduce this. Please check that your server version is actually what you think it is.

**Comment by HBIDamian** [comment]
Just to make sure, can you fill in the rest of the bug report so we can reproduce it easier?

Copy this, and fill them all. Including the version (which you've done, but copy and paste from console too)

```markdown
### Version
<!--- use the `version` command and paste the console's output below -->


### Plugins
<!--- use the `plugins` command and paste the output below -->

- If you remove all plugins, does the issue still occur?
- If the issue is **not** reproducible without plugins:
  - Have you asked for help on our forums before creating an issue?
  - Can you provide sample, *minimal* reproducing code for the issue? If so, paste it in the bottom section

### Steps to reproduce the issue
1. ...
2. ...

```
