### ISSUE TITLE
Spectator mode weird behavior when going through blocks

### ISSUE THREAD

**Issue by NickteeChunky** [pmmp/PocketMine-MP#5722]
### Issue description

- Expected result: to be able to move through blocks in spectator mode
- Actual result: every time my head hits a block in spectator mode, my flight resets (sometimes) and it moves me downwards slightly. it's very cursed behavior so watch the video below

### Steps to reproduce the issue
1. execute /gamemode spectator
2. move through a block

### OS and versions

* PocketMine-MP: 4.20.0
* PHP: 8.0.13
* Using JIT: no
* Server OS: windows & linux
* Game version: Win10

holding jump is what causes it to keep repeating
https://streamable.com/gsrs4p

**Comment by dktapps** [comment]
Looks like the client-side "push out of blocks" physics is kicking in when it shouldn't. Not sure why it would be doing that though.

**Comment by dadodasyra** [comment]
It seems that the blockCollision ability still works though. Just someone told me you lose the flight state when going upward with it, don't know if it's related.

**Comment by dktapps** [comment]
Yeah, I haven't been able to figure out why it's behaving this way. If anyone finds a way to fix it, please let me know or send a PR.

**Comment by MINTEDCLICKS** [comment]
i am also suffering from this issue
