### ISSUE TITLE
Bad packet from 10.10.10.10 55933: Not enough bytes left in buffer: need 8, have 0

### ISSUE THREAD

**Issue by uwuv3** [pmmp/PocketMine-MP#5746]
![image](https://github.com/pmmp/PocketMine-MP/assets/100004271/43d8e38d-7fab-4f0a-a417-a55cc48e8b68)
I got this error and im unable connect the world

**Comment by gamegam** [comment]
/ban-ip 10.10.10.10 Hit it.
That way, the error message will not be printed.

**Comment by uwuv3** [comment]
> /ban-ip 10.10.10.10 Hit it. That way, the error message will not be printed.

I want allow
