### ISSUE TITLE
Remove or edit?

### ISSUE THREAD

**Issue by gamegam** [pmmp/PocketMine-MP#5763]
## Description
public function register(Block $block) : void{
		$typeId = $block->getTypeId();

		if(isset($this->typeIndex[$typeId])){
			throw new \InvalidArgumentException("Block ID $typeId is already used by another block");
		}

## Justification
if(isset($this->typeIndex[$typeId])){
			throw new \InvalidArgumentException("Block ID $typeId is already used by another block");
		}
Removal request.. Reason is: RuntimeBlockStateRegistry::getInstance()->register(new FarmLand(new BlockIdentifier(BlockTypeIds::FARMLAND), "Farmlands", new BlockTypeInfo(VanillaBlocks::FARMLAND()->getBreakInfo())), true); But I get this error 09:40:46.221] [Server thread/CRITICAL]: InvalidArgumentException: "Block ID 10265 is already used by another block" (EXCEPTION) in "pmsrc/src/block/RuntimeBlockStateRegistry" at line 93 .
So I want to use something like that for the user or me.
The source function is a function that keeps crops without water.

**Comment by dktapps** [comment]
You're not supposed to reuse type IDs.
