### ISSUE TITLE
Negative TypesIds

### ISSUE THREAD

**Issue by RemBog** [pmmp/PocketMine-MP#5769]
Please add negative ids to the TypeIds class. I'm having problems with the tripwire hook, for example. (To PM5)

**Comment by SenseiTarzan** [comment]
The typeId is an identifier on the pmmp side and not on the client side and for the itemBlock a Negative typeIds compared to the block

**Comment by SenseiTarzan** [comment]
I think you have not understood the principle of typeId

**Comment by dktapps** [comment]
Type IDs are only useful for comparing item/block types. There's no significance to the numeric values.
