### ISSUE TITLE
Change ROOT_USER to ROOT_EVERYONE

### ISSUE THREAD

**Issue by AzaleeX** [pmmp/PocketMine-MP#5771]
🚀 **Enhancing DefaultPermissions API for Improved Understanding**

The current API employs the `**DefaultPermissions::ROOT_USER**` constant to represent the default permissions of the root user. However, in a quest to enhance comprehension and logical consistency for new developers, I propose a modification by replacing this constant with `**DefaultPermissions::ROOT_EVERYONE**` instead of USER.

Here are the steps to make this change:

In the file containing the constant definitions (DefaultPermissions), locate the declaration of the ROOT_USER constant.

### 🕶 Before the change:

```php
public const ROOT_USER = Names::GROUP_USER;
```

_Change the value of the ROOT USER constant to use ROOT EVERYONE instead of USER._

### 👓 After the change:
```php
public const ROOT_EVERYONE = Names::GROUP_USER;
```

**🛑 Be sure to update all places where the DefaultPermissions::ROOT_USER constant is used in your code to now use DefaultPermissions::ROOT_EVERYONE.**

😃_New developers will be able to better understand the meaning of ROOT_EVERYONE and immediately grasp that it affects everyone. This change will make the code more logical and intuitive for those committing to the project._

**Comment by AzaleeX** [comment]
I just wanted to let you know that I have started working on modifying the mentioned file. I've already made some changes, but I don't think I'm done editing everything. I also take the time to carefully study existing code to make sure I'm making the right changes.

If anyone would like to contribute or help out, I would love to receive your support! You can check out my GitHub repository at: 

[Go to my pocketmine edit](https://github.com/Zaelee/PocketMine-MP/commit/c09947959461935bd80c1a7cd9d985813a34dfe3)

**Comment by jasonw4331** [comment]
"everyone" is more confusing because changes made to this permission group do not affect users of the operator group. It does not affect all players, it only affects non-operator players aka "users".

**Comment by dktapps** [comment]
> "everyone" is more confusing because changes made to this permission group do not affect users of the operator group. It does not affect all players, it only affects non-operator players aka "users".

that's not actually true, this permission is included in the operator group.

However, to paraphrase the discussion from Discord, this permission group might not be synonymous with "everyone" in the future, for example if we were to implement visitor mode like in vanilla.
