### ISSUE TITLE
Placing item in offhand drops it instead

### ISSUE THREAD

**Issue by diamond-gold** [pmmp/PocketMine-MP#5780]
### Issue description

- Expected result: Item stays in offhand
- Actual result: Item is dropped

### Steps to reproduce the issue
1. Join test.pmmp.io
2. Take any item and put in offhand

### OS and versions

* PocketMine-MP: 4.21.0
* PHP: 8.1
* Using JIT: no
* Server OS: Windows/Linux
* Game version: Win10

### Plugins

None

**Comment by dktapps** [comment]
This doesn't seem to be a PM bug. It only happens with items that are not normally supposed to go in the offhand (e.g. a sword). If you put arrows in there it works normally.

Since PM does not restrict the items that can be placed into the offhand, this isn't the fault of PM.
