### ISSUE TITLE
Limit block bug

### ISSUE THREAD

**Issue by AraaCuteUwU** [pmmp/PocketMine-MP#5781]
### Issue description
Players may not place blocks above a height of Y 95 and above

### OS and versions

* PocketMine-MP: 5.0.0-BETA5

* PHP: 8.1.19
* Server OS: Linux

### Plugins
- If you remove all plugins, does the issue still occur? Yes, it's still occur

https://github.com/pmmp/PocketMine-MP/assets/71029264/c11fea7f-9720-45e2-88e9-8fbd7afd4a1e

**Comment by dktapps** [comment]
This was caused by ffe3556be1c8c20218190da184510518694f3234 and fixed by 8744032ab6e19baf4e902e61b39fb7b2f8f73f44.
