### ISSUE TITLE
5.0.0 stable release announcement

### ISSUE THREAD

**Issue by dktapps** [pmmp/PocketMine-MP#5784]
# 5.0.0 stable release announcement

I'm happy to announce that 5.0.0 is on track for its target release date of **June 1st, 2023.** A draft changelog can be seen here: <https://gist.github.com/dktapps/8d21a965d642e9140c82ebc1dc3faab6>
Please let me know if you notice any errors or omissions.

## What happens to PM 4.x after 5.0 release?
4.x will enter feature freeze after June 1st, as the focus of improvement will be 5.x going forward.
However, 4.x will receive security updates, bug fixes and support for new Minecraft versions until at least **September 1st, 2023**, giving users a grace period of at least **3 months** to update.

The grace period may be extended if the protocol updates after the 3-month mark aren't too much of a hassle to support. (Fortunately, PM4 is a lot easier to maintain than PM3). However, you should **not** rely on this.

## What's next after 5.0?
- 5.1 will support Bedrock 1.20.0.
- 5.2 will focus on refinement and cleanup of 5.0.
- 6.0 is the next major version planned, currently targeting **June 1st, 2024** (subject to change).

## Previous announcements
You can also take a look at #5097 and #5571 if it interests you.

**Comment by DidntPot** [comment]
wowzers! another SHIT release.

**Comment by N0RTHSIDE** [comment]
wowzersssss

**Comment by DidntPot** [comment]
use [this](https://github.com/df-mc/dragonfly)!

**Comment by JustStevee** [comment]
> use [this](https://github.com/df-mc/dragonfly)!

Nope! Use BDS!

**Comment by dktapps** [comment]
> wowzers! another SHIT release.

I think you forgot to include "no life bottom-feeder" in your bio

**Comment by DidntPot** [comment]
> > wowzers! another SHIT release.
> 
> I think you forgot to include "no life bottom-feeder" in your bio

ratio
