### ISSUE TITLE
Cannot connect to server with Windows client

### ISSUE THREAD

**Issue by ritterbuf** [pmmp/PocketMine-MP#5788]
### Issue description
I am unable to connect to the server using the Windows Minecraft Bedrock Edition client.
I don't see any messages in the server console indicating that a connection attempt is being made.

- Expected result: I am able to connect
- Actual result: Connection fails

### Steps to reproduce the issue
1. Attempt to connect with the Windows client

### OS and versions

* PocketMine-MP: 5.0.0
* PHP: 8.1
* Using JIT: no
* Server OS: Windows 10
* Game version: Win10

### Plugins
None

### Crashdump, backtrace or other files
None

**Comment by alvin0319** [comment]
If you are trying to connect to the server in the same host, follow [this instruction](https://doc.pmmp.io/en/rtfd/faq/connecting/win10localhostcantconnect.html).

**Comment by ritterbuf** [comment]
Thank you. I had to run that PowerShell command. I wasn't using `localhost` but even the normal IP address wasn't working (not using the loopback).
