### ISSUE TITLE
Blocks: Chest ID in VanillaBlocks is different

### ISSUE THREAD

**Issue by hvlxh** [pmmp/PocketMine-MP#5797]
```php
parent::__construct(new ItemIdentifier(VanillaBlocks::CHEST()->getTypeId(), 0), "§r§6Cosmetics §r§7(Right Click)");
```
![image](https://github.com/pmmp/PocketMine-MP/assets/91016099/725c4cf0-5782-45df-857f-151cd57fb862)

**Comment by SenseiTarzan** [comment]
Use the asItem method it will give you a class ItemBlock in relation to the block
