### ISSUE TITLE
RCON have no server response

### ISSUE THREAD

**Issue by Lunarelly** [pmmp/PocketMine-MP#5801]
# RCON is not working properly

First command after restart is just fine, but second and so on are not getting any response from server (but they are still being executed)

Its not a RCON plugin fault, cause literally nothing changed in it. (One guy told me that it was working fine until ALPHA-9)

PocketMine 5.0.1, PHP 8.1

**Comment by dktapps** [comment]
I'm not able to reproduce this using 2.0.1 and PM 5.0.1.

> One guy told me that it was working fine until ALPHA-9

RconServer never even supported ALPHA9.
