### ISSUE TITLE
Teleport making entities invisible

### ISSUE THREAD

**Issue by MateusBlackyOFC** [pmmp/PocketMine-MP#5815]
The entities become invisible if I TP to where they are and kill them with a hit kill.
This is a big problem that is already affecting me and other people who have servers.

Watch this video for a better view of what happened: https://youtu.be/SRQUi3jlKx8

 ```
   protected function endDeathAnimation(): void
    {
        if (!$this->settings->canRespawn()) {
            parent::endDeathAnimation();
            return;
        }

		$this->actionHandler->setTarget(null);

        $this->ticksLived = 0;

        $this->deadTicks = 0;

        $this->setPosition($this->getSpawnPosition());
        $this->setMotion(Vector3::zero());

        $this->spawnToAll();

        $this->updateSettings();

		// stupid hack to spawn boss with custom skin again
		$this->wasRespawned = false;
    }
```

This server is running PocketMine-MP
Server version: 4.22.1
Compatible Minecraft version: 1.20.0 (protocol version: 589)
PHP version: 8.1.19
PHP JIT: not supported
Operating system: linux

**Comment by MateusBlackyOFC** [comment]
EndDeathAnimation was my solution to the error proposed in #5810

**Comment by dktapps** [comment]
Since this issue involves incomplete plugin code, I can't help you, and this issue is invalid.

The dying entity is not being teleported, so this is unrelated to the previous report.

I'm afraid you're going to have to debug this one yourself.
