### ISSUE TITLE
Cherry Door not register to Item

### ISSUE THREAD

**Issue by TrueToneTeam** [pmmp/PocketMine-MP#5817]
### Issue description

- Expected result: Unable to acquire cherry door
- Actual result: Cherry door items are not properly added and cannot be acquired

### Steps to reproduce the issue
1. Creative Inventory Open
2. Search Cherry Trees Door

### OS and versions

* PocketMine-MP: 5.2.0
* PHP: 8.1
* Using JIT: no
* Server OS: Windows
* Game version: 1.20.0

**Comment by TrueToneTeam** [comment]
![Uploading IMG_2167.png…]()

**Comment by TrueToneTeam** [comment]
![IMG_2167](https://github.com/pmmp/PocketMine-MP/assets/44334220/2697e030-0d15-44a4-a52e-514aae926e2d)

**Comment by dktapps** [comment]
Related to #5818 and https://github.com/pmmp/BedrockData/commit/fb89ccdc039252462d8d068a769635e24151b7e2
