### ISSUE TITLE
BlockBreakEvent position problem

### ISSUE THREAD

**Issue by psevdonimux** [pmmp/PocketMine-MP#5828]
## Description
how do I get the coordinates of a broken block if the getBlock() method in BlockBreakEvent is removed and not done through getItem()?

## Justification
inability to get the coordinates of a broken block

## Alternative methods
return the getBlock() method or add the getPosition() method to ItemBlock.php

**Comment by IvanCraft623** [comment]
Because when placing a block in special cases 2 or more are actually placed (eg: doors), a BlockTransaction system is now used, which can contain more than one block at a time, so you will have to obtain the position of the blocks as follows.

```php
    public function onPlace(BlockPlaceEvent $event): void {
        $blocks = $event->getTransaction()->getBlocks();
        foreach ($blocks as [$x, $y, $z, $block]) {
            //your code...
        }
    }
  
   ```
