### ISSUE TITLE
retrieve the interaction of an item on an actionable block

### ISSUE THREAD

**Issue by royaljacques** [pmmp/PocketMine-MP#5842]
When I was searching and asking on the pocketmine discord server, I was told that it was impossible to know when a player was interacting with a chest or a door. However, this would be very useful. 
For example, if a developer wants to create a sellStick, he has to go through the InteractEvent. It would be nice to be able to get this directly via the item's class so that all his code isn't lost amongst useless files. 

Proposed additions : 

adds the onInteractActionnable() function to the item class

**Comment by dktapps** [comment]
`PlayerInteractEvent` is the canonical solution for this. I don't see why another solution is needed.

`onInteractBlock()` isn't fired in your case because the block's action takes precedence over that of the item, which is by design. This ensures that, for example, you don't accidentally spawn a mob when clicking on a chest using a spawn egg.

**Comment by royaljacques** [comment]
Is it possible to implement it?

**Comment by dktapps** [comment]
I don't know what you mean. As I said, the current behaviour is intended.

**Comment by royaljacques** [comment]
Wouldn't it be possible to add the **onInteractActionnable()** function so that you can interact directly in the item?

**Comment by dktapps** [comment]
As I said, you can do this with PlayerInteractEvent already, and I don't see the need for an extra API. You can also use PlayerInteractEvent to call any method of your choice on an item, so you can actually implement this yourself in a plugin.

**Comment by royaljacques** [comment]
use playerInteractEvent in 1 plugin why not . but in a core it's just impossible . if I have to make several items and I put them all in the event I don't think it optimises the core correctly . and quite simply it doesn't look good.
