### ISSUE TITLE
Errors in moving items in inventory

### ISSUE THREAD

**Issue by VennDev** [pmmp/PocketMine-MP#5843]
### Issue description
- Errors in moving items in inventory

### Steps to reproduce the issue
- Link video: https://youtu.be/wsdt-OPgju4

### OS and versions
* PocketMine-MP: 5.1.2 (git hash: 7cd317bf398a017f7c690a475c5a67650c610323)
* PHP: 8.2.6
* Using JIT: no
* Server OS: Windows 10
* Game version: Win10

**Comment by dktapps** [comment]
There isn't sufficient information to begin investigating this. I need reproducing steps and/or information of what leads to this problem. (and no, "it happens randomly" is not helpful)

You also haven't listed your plugins, which could easily be responsible for this.
