### ISSUE TITLE
LevelDB world protocol version 2147483647 is currently unsupported

### ISSUE THREAD

**Issue by acronixs** [pmmp/PocketMine-MP#5844]
I transfer the vanilla world from 1.20 to pm4 1.20 and this error pops up how to fix it?

error: LevelDB world protocol version 2147483647 is currently unsupported

**Comment by IvanCraft623** [comment]
This actually looks like a bug from a converter like chunker.

**Comment by acronixs** [comment]
> This actually looks like a bug from a converter like chunker.

And then what kind of converter to convert from java to poketmine?

**Comment by Matze997** [comment]
https://github.com/Amulet-Team/Amulet-Map-Editor

**Comment by dktapps** [comment]
While this does look like it's caused by a converter missing the `NetworkVersion` tag, this error message could definitely be less confusing...
