### ISSUE TITLE
Add the multi direction for blocks

### ISSUE THREAD

**Issue by roimee6** [pmmp/PocketMine-MP#5857]
## Description
Add system to add multi-direction for blocks (describer)

You can search here "multi_face_direction_bits": https://minecraft.fandom.com/wiki/Block_states

I noticed that this had already been added by a modified pocktetmine: https://github.com/DavyCraft648/PM-NG/blob/stable/src/data/bedrock/block/convert/BlockStateReader.php#L142

## Justification
Add the blocks like sculk vein, glow lichen..

**Comment by JavierLeon9966** [comment]
Already implemented in `minor-next`: https://github.com/pmmp/PocketMine-MP/blob/36f52f1ade4d36b959c746665bb2443158ccafdb/src/data/bedrock/block/convert/BlockStateReader.php#L142 and https://github.com/pmmp/PocketMine-MP/blob/36f52f1ade4d36b959c746665bb2443158ccafdb/src/data/bedrock/block/convert/BlockStateWriter.php#L98

**Comment by roimee6** [comment]
Ty, i didn't see
