### ISSUE TITLE
The growth phase error of melon and pumpkin stems

### ISSUE THREAD

**Issue by TrueToneTeam** [pmmp/PocketMine-MP#5858]
### Issue description

- If you place melon and pumpkin seeds in Farmland, they’re not fully grown, but they look like they’re fully grown.

![IMG_2257](https://github.com/pmmp/PocketMine-MP/assets/44334220/6893d693-a814-4058-afd2-f6df6e010be0)

### Steps to reproduce the issue
1. Plant melon seeds or pumpkin seeds in Farmland

### OS and versions

* PocketMine-MP: 5.2.0
* PHP: 8.1
* Using JIT: no
* Server OS: windows
* Game version: 1.20.1

**Comment by dktapps** [comment]
The facing property for this hasn't yet been implemented, which means that the default I used to fill in the blanks is likely incorrect.

**Comment by VladimirLogunov** [comment]
Хм

**Comment by dktapps** [comment]
This has been fixed for the upcoming 5.4.0 release.
