### ISSUE TITLE
Server crashed Player is not connected

### ISSUE THREAD

**Issue by gggggGGGGSQ** [pmmp/PocketMine-MP#5860]
Link to crashdump: 

### Additional comments (optional)

PocketMine-MP version: 4.22.1 [Protocol 589]
Git commit: ee903cad1fe2db43ed0e5fffa9d582ac47766d03
PHP version: 8.1.19
OS: Linux, linux

Error: Player is not connected
File: pmsrc/src/player/Player
Line: 599
Type: LogicException
Backtrace:
#0 pmsrc/src/player/Player(2054): pocketmine\player\Player->getNetworkSession()
#1 pmsrc/src/Server(1296): pocketmine\player\Player->sendMessage(string[25] ..a..l[-] ..ePulupulu8470)
#2 pmsrc/src/player/Player(2205): pocketmine\Server->broadcastMessage(string[25] ..a..l[-] ..ePulupulu8470)
#3 pmsrc/src/network/mcpe/NetworkSession(660): pocketmine\player\Player->onPostDisconnect(string[17] client disconnect, string[25] ..a..l[-] ..ePulupulu8470)
#4 pmsrc/src/network/mcpe/NetworkSession(596): pocketmine\network\mcpe\NetworkSession->pocketmine\network\mcpe\{closure}()
#5 pmsrc/src/network/mcpe/NetworkSession(662): pocketmine\network\mcpe\NetworkSession->tryDisconnect(object Closure#383412, string[17] client disconnect)
#6 pmsrc/src/network/mcpe/raklib/RakLibInterface(154): pocketmine\network\mcpe\NetworkSession->onClientDisconnect(string[17] client disconnect)
#7 pmsrc/vendor/pocketmine/raklib-ipc/src/RakLibToUserThreadMessageReceiver(75): pocketmine\network\mcpe\raklib\RakLibInterface->onClientDisconnect(int 10, string[17] client disconnect)
#8 pmsrc/src/network/mcpe/raklib/RakLibInterface(122): raklib\server\ipc\RakLibToUserThreadMessageReceiver->handle(object pocketmine\network\mcpe\raklib\RakLibInterface#365429)
#9 pmsrc/vendor/pocketmine/snooze/src/SleeperHandler(123): pocketmine\network\mcpe\raklib\RakLibInterface->pocketmine\network\mcpe\raklib\{closure}()
#10 pmsrc/src/TimeTrackingSleeperHandler(58): pocketmine\snooze\SleeperHandler->processNotifications()
#11 pmsrc/vendor/pocketmine/snooze/src/SleeperHandler(82): pocketmine\TimeTrackingSleeperHandler->processNotifications()
#12 pmsrc/src/Server(1688): pocketmine\snooze\SleeperHandler->sleepUntil(float 1687758268.1687)
#13 pmsrc/src/Server(1068): pocketmine\Server->tickProcessor()
#14 pmsrc/src/PocketMine(336): pocketmine\Server->__construct(object BaseClassLoader#5, object pocketmine\utils\MainLogger#2, string[16] /home/container/, string[24] /home/container/plugins/)
#15 pmsrc/src/PocketMine(359): pocketmine\server()
#16 pmsrc(11): require(string[60] phar:///home/container/PocketMine-MP.phar/src/PocketMine.php)

Code:
[590] 		return $this->isConnected();
[591] 	}
[592] 
[593] 	public function isConnected() : bool{
[594] 		return $this->networkSession !== null && $this->networkSession->isConnected();
[595] 	}
[596] 
[597] 	public function getNetworkSession() : NetworkSession{
[598] 		if($this->networkSession === null){
[599] 			throw new \LogicException("Player is not connected");
[600] 		}
[601] 		return $this->networkSession;
[602] 	}
[603] 
[604] 	/**
[605] 	 * Gets the username
[606] 	 */
[607] 	public function getName() : string{
[608] 		return $this->username;
[609] 	}

**Comment by scamaccas** [comment]
Plugin issue
