### ISSUE TITLE
Server crashed while loging in. "No deserializer found for ID minecraft:crimson_button"

### ISSUE THREAD

**Issue by JBakers** [pmmp/PocketMine-MP#5868]
Link to crashdump:  https://crash.pmmp.io/view/8811670

### Additional comments (optional)

I have 2 players logging in simultaneously for a long time.
After updating the server one of the two cant log in anymore or the server will crash.

I removed all plugins just to be sure.
But it still crashes.

**Comment by dktapps** [comment]
This is because of plugins you used in PM4 to add extra blocks. Those items associated with those blocks have not been correctly upgraded to PM5.

**Comment by JBakers** [comment]
Any suggestion how i can fix that?

**Comment by fx-k** [comment]
> Any suggestion how i can fix that?

same here, any solution please?
