### ISSUE TITLE
Unable to describe new enums using RuntimeDataDescriber

### ISSUE THREAD

**Issue by diamond-gold** [pmmp/PocketMine-MP#5877]
## Description
Please add a way to accept string/enum block states in RuntimeDataDescriber, or add all known states to RuntimeDataDescriber

## Justification
String block states could not be loaded or saved
Possibly auto generate block state enums & RuntimeDataDescriber methods from BedrockData?

Affected blocks: 
- Big dripleaf
- Pointed dripstone
- Seagrass
- Structure block
- Structure void
- Sniffer egg
- Turtle egg

Blocks states:
- BlockStateStringValues::BIG_DRIPLEAF_TILT_*
- BlockStateStringValues::CRACKED_STATE_*
- BlockStateStringValues::DRIPSTONE_THICKNESS_*
- BlockStateStringValues::SEA_GRASS_TYPE_*
- BlockStateStringValues::STRUCTURE_BLOCK_TYPE_*
- BlockStateStringValues::STRUCTURE_VOID_TYPE_*
- BlockStateStringValues::TURTLE_EGG_COUNT_*

As of 1.20.10, PM 5.3
The observer block is also affected
Block states: BlockStateStringValues::MC_FACING_DIRECTION_*

## Alternative methods
Hack!

https://github.com/diamond-gold/DummyItemsBlocks/blob/main/src/diamondgold/DummyItemsBlocks/block/hack/HackStringProperty.php

https://github.com/diamond-gold/DummyItemsBlocks/blob/main/src/diamondgold/DummyItemsBlocks/block/PointedDripstone.php

**Comment by dktapps** [comment]
> Possibly auto generate block state enums & RuntimeDataDescriber methods from BedrockData?

No, we specifically avoid doing this because we don't want to be bound by the Bedrock internals, which are a disastrously inconsistent mess.
There is no such thing as a "string" state in PM internals. They exist at the NBT layer to represent enums.

Not being able to represent new enums is indeed a design limitation of current RuntimeDataDescriber design, which has also caused issues in other areas. I haven't had time to explore how to solve this problem yet.

**Comment by dktapps** [comment]
You might also consider properly implementing these blocks in a PR, instead of making a plugin to add dummy blocks.

**Comment by diamond-gold** [comment]
The plugin's main aim is to solve the problem of blocks becoming update blocks and items disappearing. At the same time, allow building with these blocks.
The functionality can come later, it is a lot more work to properly implement these blocks, plus with the current backlog of PRs, it will take a while for them to make it into release.

**Comment by markeev** [comment]
Pm - PocketMine-MP 5.2.0 - https://github.com/pmmp/PocketMine-MP/releases/tag/5.2.0#:~:text=Releases-,5.2.0,-PocketMine%2DMP%205.2.0
Php - https://github.com/pmmp/PHP-Binaries/releases/tag/php-8.1-latest

**Comment by dktapps** [comment]
Fixed by 7dcd2592d4dd5d59dbd38069b859f57a14fcd895.
