### ISSUE TITLE
Server crashed pm4

### ISSUE THREAD

**Issue by GabBiswajit** [pmmp/PocketMine-MP#5881]
Error: Player is not connected
File: pmsrc/src/player/Player
Line: 599
Type: LogicException
Backtrace:
#0 pmsrc/src/player/Player(2054): pocketmine\player\Player->getNetworkSession()
#1 pmsrc/src/Server(1301): pocketmine\player\Player->sendMessage(string[19] ... WEN BISWAJIT346)
#2 pmsrc/src/player/Player(885): pocketmine\Server->broadcastMessage(string[19] ... WEN BISWAJIT346)
#3 pmsrc/src/network/mcpe/NetworkSession(792): pocketmine\player\Player->doFirstSpawn()
#4 pmsrc/src/network/mcpe/NetworkSession(785): pocketmine\network\mcpe\NetworkSession->onClientSpawnResponse()
#5 pmsrc/src/network/mcpe/handler/SpawnResponsePacketHandler(37): pocketmine\network\mcpe\NetworkSession->pocketmine\network\mcpe\{closure}()
#6 pmsrc/vendor/pocketmine/bedrock-protocol/src/SetLocalPlayerAsInitializedPacket(42): pocketmine\network\mcpe\handler\SpawnResponsePacketHandler->handleSetLocalPlayerAsInitialized(object pocketmine\network\mcpe\protocol\SetLocalPlayerAsInitializedPacket#88093)
#7 pmsrc/src/network/mcpe/NetworkSession(433): pocketmine\network\mcpe\protocol\SetLocalPlayerAsInitializedPacket->handle(object pocketmine\network\mcpe\handler\SpawnResponsePacketHandler#88817)
#8 pmsrc/src/network/mcpe/NetworkSession(377): pocketmine\network\mcpe\NetworkSession->handleDataPacket(object pocketmine\network\mcpe\protocol\SetLocalPlayerAsInitializedPacket#88093, string[2] q.)
#9 pmsrc/src/network/mcpe/raklib/RakLibInterface(198): pocketmine\network\mcpe\NetworkSession->handleEncoded(string[47] c*d.........*j...l[......`.(.......d...MX......)
#10 pmsrc/vendor/pocketmine/raklib-ipc/src/RakLibToUserThreadMessageReceiver(42): pocketmine\network\mcpe\raklib\RakLibInterface->onPacketReceive(int 0, string[56] .._...%....5.l.. ...V...G,~.P(...;..!+pH.+.F...Y.. /e...)
#11 pmsrc/src/network/mcpe/raklib/RakLibInterface(122): raklib\server\ipc\RakLibToUserThreadMessageReceiver->handle(object pocketmine\network\mcpe\raklib\RakLibInterface#38816)
#12 pmsrc/vendor/pocketmine/snooze/src/SleeperHandler(123): pocketmine\network\mcpe\raklib\RakLibInterface->pocketmine\network\mcpe\raklib\{closure}()
#13 pmsrc/src/TimeTrackingSleeperHandler(58): pocketmine\snooze\SleeperHandler->processNotifications()
#14 pmsrc/vendor/pocketmine/snooze/src/SleeperHandler(82): pocketmine\TimeTrackingSleeperHandler->processNotifications()
#15 pmsrc/src/Server(1693): pocketmine\snooze\SleeperHandler->sleepUntil(float 1688660434.7387)
#16 pmsrc/src/Server(1073): pocketmine\Server->tickProcessor()
#17 pmsrc/src/PocketMine(336): pocketmine\Server->__construct(object BaseClassLoader#5, object pocketmine\utils\MainLogger#2, string[16] /home/container/, string[24] /home/container/plugins/)
#18 pmsrc/src/PocketMine(359): pocketmine\server()
#19 pmsrc(11): require(string[60] phar:///home/container/PocketMine-MP.phar/src/PocketMine.php)

**Comment by xRedemption** [comment]
You are sending a message to an offline player
