### ISSUE TITLE
The player's hitbox does not decrease when you press the shift

### ISSUE THREAD

**Issue by Gaprix** [pmmp/PocketMine-MP#5891]
### Issue description

- Expected result: The player can go under the slab
- Actual result: The player can't go under the slab

### Steps to reproduce the issue
1. Place a slab
2. Try to go under it with the shift pressed

### OS and versions
Этот сервер использует PocketMine-MP
Версия сервера: 5.3.0 (git hash: d630b3af7bbdd5754dedd1ca4dd6e486fd3012ef)
Совместимая версия Minecraft: 1.20.10 (версия протокола: 594)
Версия PHP: 8.1.20
PHP JIT: не поддерживается
Операционная система: linux

### Crashdump, backtrace or other files
https://youtu.be/MC0vuqcdU4M

**Comment by jasonw4331** [comment]
There is a plugin which implements the requested change [here](https://github.com/DavyCraft648/ShortSneak)

**Comment by jasonw4331** [comment]
This is listed within Minecraft's experiments as short_sneaking. I don't think this feature should be enabled in the core by default.

**Comment by Gaprix** [comment]
Starting from version 1.20.10, you do not need to enable the experiment for this feature to work

**Comment by jasonw4331** [comment]
Should this change only effect Human entities or all Living entities?

**Comment by dktapps** [comment]
I don't think it matters. So far as I know, non-human entities can't normally sneak anyway, so the behaviour is undefined.

**Comment by dktapps** [comment]
Implemented by #5892.
