### ISSUE TITLE
Server crashed

### ISSUE THREAD

**Issue by MateusBlackyOFC** [pmmp/PocketMine-MP#5896]
Link to crashdump: https://crash.pmmp.io/view/8957687

**Comment by dktapps** [comment]
How did you come across this crash?

**Comment by MateusBlackyOFC** [comment]
Simply doing nothing.

**Comment by dktapps** [comment]
Without reproducing steps there's nothing I can do.

If it happens a lot, try removing some of your plugins and see if you can find which one is causing the problem.

**Comment by dktapps** [comment]
Closing due to lack of useful information.
