### ISSUE TITLE
[0.16 branch] $flags Variable in FloatingTextParticle not defined

### ISSUE THREAD

**Issue by SleepSpace9** [pmmp/PocketMine-MP#59]
### Issue description
I created some floating texts and got spammed by the following message:
```Notice: Undefined variable: flags in phar:///usr/games/pocketmine-test/PocketMine-MP.phar/src/pocketmine/level/particle/FloatingTextParticle.php on line 92```

I think it's missing...
```php
$flags = Array();
```
before...
https://github.com/pmmp/PocketMine-MP/blob/0.16/src/pocketmine/level/particle/FloatingTextParticle.php#L92

### Steps to reproduce the issue
Create a floating text and wait for the AddEntityPacket at join. At console you will see the notice.

### OS and versions
* PocketMine-MP: branch **0.16** Commit 46af92f
* PHP: 7.0.9
* Server OS: Ubuntu 14.04
* Game version: PE + Win10

**Comment by SOF3** [comment]
$flags should be initialized with 0, not empty array.

**Comment by dktapps** [comment]
It's preferable if you could comment on the pull request with this kind of issue and keep the issue tracker for master only.
