### ISSUE TITLE
Short sneaking does not work if the connection is lost

### ISSUE THREAD

**Issue by Gaprix** [pmmp/PocketMine-MP#5902]
### Issue description
On Bedrock Dedicated Server, if the player loses the connection, he will still be able to sneak and go into a 1.5 block high area.
On PMMP, if the connection is lost, the player loses the ability to become 1.5 blocks tall.

### Steps to reproduce the issue
1. Terminate the server process in such a way that the player remains in the world
2. Try to go into a 1.5 block high area

### OS and versions
* PocketMine-MP: 5.3.1
* Game version: Win10 (Not tested on others)

### Plugins
test.pmmp.io server's plugins

**Comment by jasonw4331** [comment]
It can't be a server problem if the server isn't involved anymore by definition

**Comment by Gaprix** [comment]
This is a server problem, since this problem does not exist on Bedrock Dedicated Server.

Moreover, this problem can occur if the player has a bad Internet connection (mobile network) and he temporarily lost connection to the network.

**Comment by dktapps** [comment]
I don't think this is worth investigating even if it does differ. Everything breaks in a timeout anyway.

**Comment by Gaprix** [comment]
If the player has lost the network for a short time, then he will not disconnect from the server

**Comment by Gaprix** [comment]
I found out that this also causes a weird bug in which the player "shakes" if he did not hold down the shift key, but just pressed it 1 time
https://youtu.be/ZWLqlYl7I-Y

**Comment by dktapps** [comment]
You're welcome to debug this if it makes you happy, but I have no intent of investigating this.
