### ISSUE TITLE
Being in the 1.5 block space is interpreted as pressing the shift key

### ISSUE THREAD

**Issue by Gaprix** [pmmp/PocketMine-MP#5903]
### Issue description

- Expected result: The player interacts with the block
- Actual result: The player places a block

### Steps to reproduce the issue
1. Go into a 1.5 block high area
2. Don't press shift key
3. Hold a block in your hand
4. Try to click on a block that you can interact with

### OS and versions
* PocketMine-MP: 5.3.1
* Game version: Win10 (Not tested on others)

### Plugins
test.pmmp.io server's plugins

### Crashdump, backtrace or other files
https://youtu.be/cbSFCt28Phg

**Comment by dktapps** [comment]
I'm not really sure what to do about this. This means that the client never sent the STOP_SNEAKING flag, which means that they are still sneaking ...

**Comment by dktapps** [comment]
Possibly related to #5792
