### ISSUE TITLE
Bug Elytras

### ISSUE THREAD

**Issue by BlueKill456** [pmmp/PocketMine-MP#5905]
### Issue description

- Expected result: What were you expecting to happen?
- Actual result: What actually happened?

### Steps to reproduce the issue
1. This doesn't happen without plugins, it seems that the basic functionalities of pm 5 and pm 4 were affected in 1.20.10
2. Use Elytras, fly and spam the jump button, then you will fly above the ground

### OS and versions

* PocketMine-MP: 4.23.1 and 5.3.1
* PHP: 8.1
* Using JIT: yes/no (delete as appropriate) 
* Server OS:
* Game version: Android/iOS/Win10/Xbox/PS4/Switch (delete as appropriate)

### Plugins

- If you remove all plugins, does the issue still occur? No, this happens when the Elytras plugin
- If the issue is **not** reproducible without plugins:
  - Have you asked for help on our forums before creating an issue?
  - Can you provide sample, *minimal* reproducing code for the issue? If so, paste it in the bottom section

### Crashdump, backtrace or other files

Vid: https://youtu.be/mZ3TyIJqAB8

**Comment by dktapps** [comment]
Please check whether this also happens in singleplayer

**Comment by BlueKill456** [comment]
I already checked and this definitely doesn't happen in singleplayer.

**Comment by dktapps** [comment]
Since this feature is not yet supported by PM anyway, I have no way to debug this, so unfortunately you're on your own.

**Comment by BlueKill456** [comment]
maybe this is helpful to implement and fix it?
https://github.com/DavyCraft648/VanillaElytra-1/commit/b8490ac94e05e6c515f38b763114af88bedd868c
