### ISSUE TITLE
Unable to load the world correctly

### ISSUE THREAD

**Issue by Atara6431** [pmmp/PocketMine-MP#5911]
many of my worlds become like this after updating PM5
![image](https://github.com/pmmp/PocketMine-MP/assets/48610466/d8f0493c-8f78-4475-9a24-70d61e876b5b)
![_1608643464__9a05a767cabe4c1b9edafc07e06f7693_-1424699146_Screenshot_20230717_224429_0_wifi_0](https://github.com/pmmp/PocketMine-MP/assets/48610466/d79a4759-fdb3-496f-846f-e5ffdba6aee9)
[Server thread/CRITICAL]: [World: feixu] Failed to load chunk x=-68 z=26: Invalid blockstate NBT at offset 0 in paletted storage: Root is not a TAG_Compound
all of the worlds can be used normally in Pm4 without any problems...
Do you see those neat big pits on the map? all of which are blocks that haven't been loaded yet,and this is the end after updating PM5. After working hard to update the plugin, I found that many worlds cannot even load normally like before! 
I try to use "chunk"/amulet to convert the world, but it not work.
This is one of my world.
[feixu.zip](https://github.com/pmmp/PocketMine-MP/files/12081657/feixu.zip)

**Comment by Atara6431** [comment]
seems many users have this problem

**Comment by dktapps** [comment]
> Invalid blockstate NBT at offset 0 in paletted storage: Root is not a TAG_Compound

This error usually appears due to an incorrect structure of some chunk data. Where did this world come from?

**Comment by Atara6431** [comment]
I always use Java edition 1.12 to build things first and put it into sever, Because the old pm only supported up to 1.12. and when the world is converted by pm, it cannot be read by any world converter, so now I don't have any way to solve it.

**Comment by dktapps** [comment]
What version of PM did you first use the world in?

**Comment by Atara6431** [comment]
one of the PM4 version, can't remember it,and some of it start at PM3.

**Comment by dktapps** [comment]
Did you use any other software, such as a fork of PM, Nukkit, etc?

**Comment by Atara6431** [comment]
I haven't used it before

**Comment by dktapps** [comment]
What about world converters or external editing tools?

**Comment by Atara6431** [comment]
I try to use "chunk"/amulet, but these tools even can't read the world.
![image](https://github.com/pmmp/PocketMine-MP/assets/48610466/86b80dc7-57cf-455b-b5fb-be4496b56202)

**Comment by dktapps** [comment]
I meant in the past, did you use any tools such as MCEdit or similar to modify the world?

**Comment by Atara6431** [comment]
yes,It can be read normally before using PM, but my world has been built for a long time in PM and cannot use the previous version  o(╥﹏╥)o

**Comment by dktapps** [comment]
Did you ever use this plugin? https://github.com/Refaltor77/CustomItemAPI

**Comment by Atara6431** [comment]
yes I have load it but  I haven't really used it before.

**Comment by dktapps** [comment]
Alright, good to know. It appears that the plugin has corrupted your world due to an incorrect re-implementation of the LevelDB world format.

**Comment by Atara6431** [comment]
oh no.So is there a solution? These worlds can load normally in PM4 without any problems.

**Comment by dktapps** [comment]
It works in PM4 because PM4's code lacks some invalid data checks. It was never supposed to save this type of data to begin with.

PM5 expanded the range of stuff supported in the world format, which resulted in this error being detected, since this type has to be handled slightly differently.

I'm working on a workaround to fix the problem, but you should be very wary of custom plugins like that which override parts of PM's internal system, as it's a recipe for disaster.

**Comment by Atara6431** [comment]
Thank you very much. I will pay attention.(≧∇≦)ﾉ

**Comment by Atara6431** [comment]
Did the new version 5.3.2 fixed this problem?

**Comment by dktapps** [comment]
A new release will be created soon ™️

**Comment by Atara6431** [comment]
ok, I will still wait there.o(╥﹏╥)o

**Comment by Atara6431** [comment]
Haven't pm fixed it yet?I haven closed the server in a month.(꒦_꒦)

**Comment by Atara6431** [comment]
soon

**Comment by Atara6431** [comment]
soon....
