### ISSUE TITLE
JSON property "sandboxId" does not exist

### ISSUE THREAD

**Issue by StefanFox-Dev** [pmmp/PocketMine-MP#5914]
### Issue description

- Expected result: What were you expecting to happen?
- Actual result: What actually happened?
` Bad packet: Error processing LoginPacket: JSON property "sandboxId" does not exist in object of type pocketmine\network\mcpe\protocol\types\login\AuthenticationData`

### Steps to reproduce the issue
1. join player server
2. error

### OS and versions

* PocketMine-MP: 5.3.1
* PHP: 8.2
* Using JIT: no
* Server OS: Ubuntu
* Game version: Android/iOS/Win10/Xbox/PS4/Switch

### Plugins

- If you remove all plugins, does the issue still occur?
- If the issue is **not** reproducible without plugins:
  - Have you asked for help on our forums before creating an issue?
  - Can you provide sample, *minimal* reproducing code for the issue? If so, paste it in the bottom section

**Comment by dktapps** [comment]
Fixed by https://github.com/pmmp/BedrockProtocol/commit/db48400736799cc3833a2644a02e308992a98fa8
