### ISSUE TITLE
Abandoned Connection issue

### ISSUE THREAD

**Issue by GabBiswajit** [pmmp/PocketMine-MP#5920]
Some Time Player try To Join Server And The Server Was Say **Abandoned Connection issue**
And Host Ram Was Increase.
![Uploading Screenshot_20230718_083611_com.mojang.minecraftpe.jpg…]()

**Comment by alvin0319** [comment]
It is fixed in [1.20.12](https://feedback.minecraft.net/hc/en-us/articles/17690571678605)
> Fixed connection stability related to "Abandoned connection closed" errors
