### ISSUE TITLE
Campfire doesn't go out

### ISSUE THREAD

**Issue by ghost** [pmmp/PocketMine-MP#5925]
### Whatever I try, a campfire won't go out. I've tried water and a shovel, nothing works.

- Expected result: I want the campfire to go out with water or a shovel.
- Actual result: When I used a shovel, it didn't go out. When I submerged it in water, it didn't go out

### Steps to reproduce the issue
1. Get a campfire
2. Get a shovel/water
3. Try to put it out with those materials

### OS and versions
* PocketMine-MP: 5.3.2
* PHP: 8.1.20
* Using JIT: "not supported"
* Server OS: Linux
* Game version: iPadOS

**Comment by dktapps** [comment]
Campfire is not implemented.
