### ISSUE TITLE
Suddenly an additional slab block appears when placing slab on slab

### ISSUE THREAD

**Issue by AraaCuteUwU** [pmmp/PocketMine-MP#5945]
### Issue description

- Expected result: What were you expecting to happen?
- Actual result: What actually happened?

### OS and versions

* PocketMine-MP: 5.3.3
* PHP: 8.1.21
* Using JIT: yes/no (delete as appropriate) 
* Server OS: linux
* Game version: Android/iOS/Win10/Xbox/PS4/Switch (delete as appropriate)

### Plugins

Command output | Plugins (3): DevTools v1.17.0+dev, FormAPI v1.4.0, MultiWorld v1.8.0-ALPHA1

- If you remove all plugins, does the issue still occur? Yes

https://github.com/pmmp/PocketMine-MP/assets/71029264/3b5f26ee-2dca-4609-ae5c-766ce73a3f1c

**Comment by dktapps** [comment]
It appears there is some cursed behaviour / bug in vanilla where this is concerned.

When placing the third slab in vanilla, for some reason it places a slab in the middle slot, rather than on top. The slab is actually a single stone slab on the server side.

**Comment by AraaCuteUwU** [comment]
>

https://github.com/pmmp/PocketMine-MP/assets/71029264/da85bed3-505b-4f93-b338-5dd8cc08e1f2

Yes, I have tried it in vanilla world and it is different from pocketmine

**Comment by dktapps** [comment]
https://bugs.mojang.com/browse/MCPE-168979

**Comment by dktapps** [comment]
Closing this as it's a client bug.
