### ISSUE TITLE
ArmorInventory transactions with fast proxy transfers

### ISSUE THREAD

**Issue by dadodasyra** [pmmp/PocketMine-MP#5987]
### Issue description

- Expected result: Armor should be possible to remove
- Actual result: The transaction is dismissed and a debug error is thrown

### Steps to reproduce the issue
1. Use a fast proxy transfer such as Waterdog
2. Do some transfers (or not ?)
3. Seems to randomly happens but when your stuck in the bug even after reconnection it still occurs
You can stop this happening by removing the armor content with a plugin with a command such as /removearmor

### OS and versions

* PocketMine-MP: 5.4.2 (works too on my PM4 servers)
* PHP: 8.3
* Using JIT: no (delete as appropriate) 
* Server OS: Debian 11
* Game version: Win10 (should also works with other ones)

### Crashdump, backtrace or other files

Could be related to #5727.
First I though the issue was only on my side so I wasn't saying anything but some other servers has the same issues with proxies so I guess it should at least has an issue to it. I'm open to answer any question about the issue.
The bug exists since at least april.
<details><summary>Debug details</summary>

<div class="notranslate position-relative overflow-auto"><pre class="notranslate"><code class="notranslate">[22:33:27.168] [Server thread/DEBUG]: [NetworkSession: dadodasyra] ItemStackRequest #-483 failed: Error processing action 0 (PlaceStackRequestAction): ArmorInventory#80351, slot: 0: Mismatched expected itemstack, client expected: 14, server actual: 31, last modified by request: none
[22:33:27.168] [Server thread/DEBUG]: [NetworkSession: dadodasyra] pocketmine\network\mcpe\handler\ItemStackRequestProcessException: "Error processing action 0 (PlaceStackRequestAction): ArmorInventory#80351, slot: 0: Mismatched expected itemstack, client expected: 14, server actual: 31, last modified by request: none" (EXCEPTION) in "pmsrc/src/network/mcpe/handler/ItemStackRequestExecutor" at line 366
--- Stack trace ---
  #0 pmsrc/src/network/mcpe/handler/InGamePacketHandler(592): pocketmine\network\mcpe\handler\ItemStackRequestExecutor->generateInventoryTransaction()
  #1 pmsrc/src/network/mcpe/handler/InGamePacketHandler(614): pocketmine\network\mcpe\handler\InGamePacketHandler->handleSingleItemStackRequest(object pocketmine\network\mcpe\protocol\types\inventory\stackrequest\ItemStackRequest#79836)
  #2 pmsrc/vendor/pocketmine/bedrock-protocol/src/ItemStackRequestPacket(55): pocketmine\network\mcpe\handler\InGamePacketHandler->handleItemStackRequest(object pocketmine\network\mcpe\protocol\ItemStackRequestPacket#80133)
  #3 pmsrc/src/network/mcpe/NetworkSession(438): pocketmine\network\mcpe\protocol\ItemStackRequestPacket->handle(object pocketmine\network\mcpe\handler\InGamePacketHandler#80659)
  #4 pmsrc/src/network/mcpe/NetworkSession(382): pocketmine\network\mcpe\NetworkSession->handleDataPacket(object pocketmine\network\mcpe\protocol\ItemStackRequestPacket#80133, string[19] ...................)
  #5 pmsrc/src/network/mcpe/raklib/RakLibInterface(218): pocketmine\network\mcpe\NetworkSession->handleEncoded(string[64] ....x......A.....?.XO`d..w_...N...].l...N2te...8.#.....7a.^.....)
  #6 pmsrc/vendor/pocketmine/raklib-ipc/src/RakLibToUserThreadMessageReceiver(40): pocketmine\network\mcpe\raklib\RakLibInterface->onPacketReceive(int 2, string[65] .....x......A.....?.XO`d..w_...N...].l...N2te...8.#.....7a.^.....)
  #7 pmsrc/src/network/mcpe/raklib/RakLibInterface(110): raklib\server\ipc\RakLibToUserThreadMessageReceiver->handle(object pocketmine\network\mcpe\raklib\RakLibInterface#109842)
  #8 pmsrc/vendor/pocketmine/snooze/src/SleeperHandler(120): pocketmine\network\mcpe\raklib\RakLibInterface->pocketmine\network\mcpe\raklib\{closure}()
  #9 pmsrc/src/TimeTrackingSleeperHandler(58): pocketmine\snooze\SleeperHandler->processNotifications()
  #10 pmsrc/vendor/pocketmine/snooze/src/SleeperHandler(79): pocketmine\TimeTrackingSleeperHandler->processNotifications()
  #11 pmsrc/src/Server(1690): pocketmine\snooze\SleeperHandler->sleepUntil(float 1691706807.2008)
  #12 pmsrc/src/Server(1064): pocketmine\Server->tickProcessor()
  #13 pmsrc/src/PocketMine(334): pocketmine\Server->__construct(object pocketmine\thread\ThreadSafeClassLoader#3, object pocketmine\utils\MainLogger#6, string[29] /root/servers/miscs/betatest/, string[37] /root/servers/miscs/betatest/plugins/)
  #14 pmsrc/src/PocketMine(357): pocketmine\server()
  #15 pmsrc(11): require(string[73] phar:///root/servers/miscs/betatest/PocketMine-MP.phar/src/PocketMine.php)
--- Previous ---
pocketmine\network\mcpe\handler\ItemStackRequestProcessException: "ArmorInventory#80351, slot: 0: Mismatched expected itemstack, client expected: 14, server actual: 31, last modified by request: none" (EXCEPTION) in "pmsrc/src/network/mcpe/handler/ItemStackRequestExecutor" at line 99
  #0 pmsrc/src/network/mcpe/handler/ItemStackRequestExecutor(124): pocketmine\network\mcpe\handler\ItemStackRequestExecutor->matchItemStack(object pocketmine\inventory\ArmorInventory#80351, int 0, int 14)
  #1 pmsrc/src/network/mcpe/handler/ItemStackRequestExecutor(149): pocketmine\network\mcpe\handler\ItemStackRequestExecutor->getBuilderInventoryAndSlot(object pocketmine\network\mcpe\protocol\types\inventory\stackrequest\ItemStackRequestSlotInfo#81076)
  #2 pmsrc/src/network/mcpe/handler/ItemStackRequestExecutor(134): pocketmine\network\mcpe\handler\ItemStackRequestExecutor->removeItemFromSlot(object pocketmine\network\mcpe\protocol\types\inventory\stackrequest\ItemStackRequestSlotInfo#81076, int 1)
  #3 pmsrc/src/network/mcpe/handler/ItemStackRequestExecutor(307): pocketmine\network\mcpe\handler\ItemStackRequestExecutor->transferItems(object pocketmine\network\mcpe\protocol\types\inventory\stackrequest\ItemStackRequestSlotInfo#81076, object pocketmine\network\mcpe\protocol\types\inventory\stackrequest\ItemStackRequestSlotInfo#80221, int 1)
  #4 pmsrc/src/network/mcpe/handler/ItemStackRequestExecutor(364): pocketmine\network\mcpe\handler\ItemStackRequestExecutor->processItemStackRequestAction(object pocketmine\network\mcpe\protocol\types\inventory\stackrequest\PlaceStackRequestAction#80154)
  #5 pmsrc/src/network/mcpe/handler/InGamePacketHandler(592): pocketmine\network\mcpe\handler\ItemStackRequestExecutor->generateInventoryTransaction()
  #6 pmsrc/src/network/mcpe/handler/InGamePacketHandler(614): pocketmine\network\mcpe\handler\InGamePacketHandler->handleSingleItemStackRequest(object pocketmine\network\mcpe\protocol\types\inventory\stackrequest\ItemStackRequest#79836)
  #7 pmsrc/vendor/pocketmine/bedrock-protocol/src/ItemStackRequestPacket(55): pocketmine\network\mcpe\handler\InGamePacketHandler->handleItemStackRequest(object pocketmine\network\mcpe\protocol\ItemStackRequestPacket#80133)
  #8 pmsrc/src/network/mcpe/NetworkSession(438): pocketmine\network\mcpe\protocol\ItemStackRequestPacket->handle(object pocketmine\network\mcpe\handler\InGamePacketHandler#80659)
  #9 pmsrc/src/network/mcpe/NetworkSession(382): pocketmine\network\mcpe\NetworkSession->handleDataPacket(object pocketmine\network\mcpe\protocol\ItemStackRequestPacket#80133, string[19] ...................)
  #10 pmsrc/src/network/mcpe/raklib/RakLibInterface(218): pocketmine\network\mcpe\NetworkSession->handleEncoded(string[64] ....x......A.....?.XO`d..w_...N...].l...N2te...8.#.....7a.^.....)
  #11 pmsrc/vendor/pocketmine/raklib-ipc/src/RakLibToUserThreadMessageReceiver(40): pocketmine\network\mcpe\raklib\RakLibInterface->onPacketReceive(int 2, string[65] .....x......A.....?.XO`d..w_...N...].l...N2te...8.#.....7a.^.....)
  #12 pmsrc/src/network/mcpe/raklib/RakLibInterface(110): raklib\server\ipc\RakLibToUserThreadMessageReceiver->handle(object pocketmine\network\mcpe\raklib\RakLibInterface#109842)
  #13 pmsrc/vendor/pocketmine/snooze/src/SleeperHandler(120): pocketmine\network\mcpe\raklib\RakLibInterface->pocketmine\network\mcpe\raklib\{closure}()
  #14 pmsrc/src/TimeTrackingSleeperHandler(58): pocketmine\snooze\SleeperHandler->processNotifications()
  #15 pmsrc/vendor/pocketmine/snooze/src/SleeperHandler(79): pocketmine\TimeTrackingSleeperHandler->processNotifications()
  #16 pmsrc/src/Server(1690): pocketmine\snooze\SleeperHandler->sleepUntil(float 1691706807.2008)
  #17 pmsrc/src/Server(1064): pocketmine\Server->tickProcessor()
  #18 pmsrc/src/PocketMine(334): pocketmine\Server->__construct(object pocketmine\thread\ThreadSafeClassLoader#3, object pocketmine\utils\MainLogger#6, string[29] /root/servers/miscs/betatest/, string[37] /root/servers/miscs/betatest/plugins/)
  #19 pmsrc/src/PocketMine(357): pocketmine\server()
  #20 pmsrc(11): require(string[73] phar:///root/servers/miscs/betatest/PocketMine-MP.phar/src/PocketMine.php)
--- End of exception information ---
[22:33:27.201] [Server thread/DEBUG]: [NetworkSession: dadodasyra] Full inventory sync requested, sending contents of 5 inventories
</code></pre>
  </div></div>
</details>

**Comment by JavierLeon9966** [comment]
This is the proxy's fault by not translating the transaction IDs from other servers and the client. For now just disable fast transfer on them so the client transaction ID gets reset correctly.

**Comment by dadodasyra** [comment]
> This is the proxy's fault by not translating the transaction IDs from other servers and the client. For now just disable fast transfer on them so the client transaction ID gets reset correctly.

Can you give me more details ? I have my own proxy so I need to correctly understand why the issue happens, and how can I fix it. It wasn't happening in 2022

**Comment by dktapps** [comment]
It wasn't happening in 2022 because inventories were still using the legacy transaction system. The new system has new requirements. You need to sync the contents of all inventories from the destination server to ensure that itemstackIDs are correct.

**Comment by dktapps** [comment]
It appears a client bug is involved here - whenever the server sends slots to the client, the client won't update its ID if the new item is the same as the one it already knows about. This is an irritating bug, but can be worked around.

The initial occurrence of the bug is because of a transaction validation failure (as-yet unknown), but the subsequent failed transactions continue to happen due to this bug.

**Comment by dktapps** [comment]
More findings on this: For some reason this bug only occurs with armor, offhand and temporary inventories such as the enchanting table menu. Other inventories, such as the player's main inventory, chests, etc. are not affected.
