### ISSUE TITLE
Server crashed while loading resource packs

### ISSUE THREAD

**Issue by creeperplayer20** [pmmp/PocketMine-MP#5990]
Link to crashdump: 

### Additional comments (optional)

Hello, I am trying to create a clean server with the latest version of PocketMine-MP (5.4.2). After completing the set-up wizard, the server tries to start but cannot progress beyond the ‘Loading resource packs’ check, eventually crashing the Server did not show any errors or produce an error file. I don’t use any resource packs; This is a clean installation. I have attached a video to investigate.

https://github.com/pmmp/PocketMine-MP/assets/42560781/fa9d62f1-11a2-4fbe-b9a6-37686ec92a46

**Comment by JaxkDev** [comment]
Issue will be closed as invalid but, that looks like the PHP8.3 issue use 8.2/8.1 if you are using 8.3

**Comment by creeperplayer20** [comment]
> Issue will be closed as invalid but, that looks like the PHP8.3 issue use 8.2/8.1 if you are using 8.3

Solved my problem, thank you. 😊
