### ISSUE TITLE
Crashdump generation failed on fatal error

### ISSUE THREAD

**Issue by ShockedPlot7560** [pmmp/PocketMine-MP#6007]
### Issue description

- Expected result: Crashdump is correctly written in folder.
- Actual result: `[22:17:32.696] [Server thread/CRITICAL]: Unable to create crash file: Cannot assign null to property pocketmine\crash\CrashDumpData::$thread of type string`

### Steps to reproduce the issue
1. Have `Fatal error: Cannot declare class xxx, because the name is already in use in xxx.php on line xx` during plugin onEnable

### OS and versions

* PocketMine-MP: 5.4.2
* PHP: 8.2.8
* Using JIT: no
* Server OS: Ubuntu 22.04

### Plugins

- If you remove all plugins, does the issue still occur? `no`, logic
- If the issue is **not** reproducible without plugins:
  - Have you asked for help on our forums before creating an issue?
  - Can you provide sample, *minimal* reproducing code for the issue? If so, paste it in the bottom section

I can't get any reproducible code, however it's playing with the autoloader, probably even any fatal error causes this

### Crashdump, backtrace or other files

N/A

**Comment by dktapps** [comment]
https://github.com/pmmp/PocketMine-MP/blob/stable/src/crash/CrashDump.php#L202

`$error["thread"]` isn't populated here
