### ISSUE TITLE
Unable to load 1.12+ ItemBlocks obtained in PM4

### ISSUE THREAD

**Issue by diamond-gold** [pmmp/PocketMine-MP#6008]
Link to crashdump: https://crash.pmmp.io/view/9112014

### Steps to reproduce
1. Use PM 4.23.5 and https://github.com/ipad54/INether
2. Give yourself `warped_nylium` or any of the blocks added by the plugin
3. Stop server and copy player.dat to PM 5.4.2 server
4. Use a plugin that registers the block `warped_nylium` such as https://github.com/diamond-gold/DummyItemsBlocks
5. Start and join PM5 server

**Comment by justin-eckenweber** [comment]
Can confirm, also happens to me. Would be great if it either would be replaced with an update block or if it would accept the deserializer from the plugin.

**Comment by Azvyl** [comment]
from what i see it's because pm 4 doesn't save block tag on items so pm creates `1.12.0_item_id_to_block_id_map.json` file to read pm4 block items. The file is used in [R12ItemIdToBlockIdMap](https://github.com/pmmp/PocketMine-MP/blob/stable/src/data/bedrock/item/upgrade/R12ItemIdToBlockIdMap.php)

You can use reflection to add your item -> block map for >1.12 blocks

**Comment by dktapps** [comment]
This is the fault of the plugin for using IDs and meta in PM4 that weren't supported by vanilla. You need a plugin that registers the proper upgrade mappings in BlockIdMetaUpgrader in PM5.

**Comment by dktapps** [comment]
The server crashing issue is a duplicate of #5128

**Comment by diamond-gold** [comment]
This issue seems to be fixed by registering the itemblocks as items, so there really is something wrong in the way PM4 saves the itemblocks
For blocks that are implemented by PM like shroomlight, it won't get fixed by this workaround in the plugin
```php
    /**
     * https://github.com/diamond-gold/DummyItemsBlocks/issues/5
     * Doesn't work for blocks already taken over by pmmp since they can't exist in config
     * @param string[] $blocks
     * @param string[] $items
     * @return void
     */
    private function workaroundIssue5(array $blocks, array $items): void
    {
        foreach (array_diff($blocks, $items) as $block) {
            //$this->getLogger()->debug("Block $block registering workaround...");
            try {
                self::registerSimpleItem($block, StringToItemParser::getInstance()->parse($block), [], false);
            } catch (Throwable $e) {
                //$this->getLogger()->debug("Failed to register block $block as item: " . $e->getMessage());
            }
        }
    }
```

**Comment by dktapps** [comment]
This is not the fault of PM. There is a very good reason none of the >1.12 blocks were implemented in PM4. I warned people this would happen...

**Comment by justin-eckenweber** [comment]
> This is not the fault of PM. There is a very good reason none of the >1.12 blocks were implemented in PM4. I warned people this would happen...

Can’t you just replace these blocks with update blocks or just don’t load them (air)? Otherwise servers with this blocks are bricked for ever. I think this will help to at least not lose everything from PM4… who cares about these nether items blocks if you can keep the rest.

**Comment by justin-eckenweber** [comment]
> > This is not the fault of PM. There is a very good reason none of the >1.12 blocks were implemented in PM4. I warned people this would happen...
> 
> Can’t you just replace these blocks with update blocks or just don’t load them (air)? Otherwise servers with this blocks are bricked for ever. I think this will help to at least not lose everything from PM4… who cares about these nether items blocks if you can keep the rest.

Or just with the base block if it exists? There has to be a solution otherwise I won’t be able to use my servers anymore.
