### ISSUE TITLE
Cake isn't always eatable in creative

### ISSUE THREAD

**Issue by mtugb** [pmmp/PocketMine-MP#6056]
### Issue description

In mojang's default minecraft, we can eat cake anytime in creative, but in pmmp we not.

### Steps to reproduce the issue
1. Eat cake in creative when you are full.

### OS and versions

* PocketMine-MP: 5.5.0
* PHP: 8.2.10 (cli) (built: Sep  4 2023 17:37:11) (ZTS Visual C++ 2019 x64)
* Using JIT: probably no
* Server OS:win10
* Game version: Win10

### Plugins
DevTools v1.17.1, EasyEdit v3.0.1, TGCapes v2.1.1, server v0.0.1

- If you remove all plugins, does the issue still occur? probably yes

### Crashdump, backtrace or other files
This problem doesn't occur any crash.

**Comment by dktapps** [comment]
Related to #5923
