### ISSUE TITLE
Add Behavior Pack Support

### ISSUE THREAD

**Issue by MrRagtime** [pmmp/PocketMine-MP#6065]
#### New issue since #2765 is closed and was 4 years go.
there are more behavior packs then plugins for [Poggit](https://poggit.pmmp.io/)
like backpack, a wither storm like pack, player graves, expansive biomes, etc.

## Here is a list of them
https://mcpedl.com/category/addons/

**Comment by dktapps** [comment]
We decided long ago not to bother with this due to the large amount of work required to support them. If you want something like that, write a plugin.
