### ISSUE TITLE
chest custom screen problem

### ISSUE THREAD

**Issue by cherrychip8293** [pmmp/PocketMine-MP#6067]
### Issue description

- Expected result: What were you expecting to happen?
- Actual result: What actually happened?

### Steps to reproduce the issue
Create a custom screen, put it on the server, and call that custom screen.

### OS and versions

* PocketMine-MP:  5.6.0
* PHP: 8.2
* Using JIT: yes/no (delete as appropriate) 
* Server OS: Linux
* Game version: Android/iOS/Win10/Xbox/PS4/Switch (delete as appropriate) Win10

### Plugins

- If you remove all plugins, does the issue still occur?
CustomItemLoader v3.3.1, DEVirion v1.3.0, DevTools v1.17.0, IslandPlugin v1.1.3, JobLoader v0.0.1, MarketPlugin v1.1.0, Menu v1.0.0, MoneyCore v1.0.5, MultiWorld v2.1.1, Popularity v1.0.0, RconServer v2.0.1+dev, Reservation v1.0.0, Size v1.0.0, WarnLoader v0.0.1, libItemRegistrar v1.0.0

### Crashdump, backtrace or other files

![image](https://github.com/pmmp/PocketMine-MP/assets/82744478/b1e5a752-9b1c-4178-8ac4-7bfe7c8c070e)
The photo was taken in the version currently experiencing loading issues.

![image](https://github.com/pmmp/PocketMine-MP/assets/82744478/efaca1bc-4f41-42a3-991c-360b8fbc095e)
This GUI window was tested on the older version, version 1.20.10.
It outputs normally in that version.

**Comment by xSuperr** [comment]
There was a change that affects resource packs adding custom menus in 1.20.30, this is a pack problem not a pocketmine problem.

**Comment by inotflying** [comment]
[MCPE-175115](https://bugs.mojang.com/browse/MCPE-175115)
