### ISSUE TITLE
Implement crop growth speed modifiers

### ISSUE THREAD

**Issue by dktapps** [pmmp/PocketMine-MP#6070]
## Description
Things that should influence crop growth:
- Adjacent farmland accelerates (especially if hydrated)
- Adjacent crops of the same type decelerates

## Justification
This has been a lacking feature for many years. It's probably not that difficult to implement, and is needed for vanilla farming mechanics to work as expected.

**Comment by dktapps** [comment]
Additionally, crops normally don't grow unless the combined light level (accounting for time of day) is at least 9.

**Comment by gamegam** [comment]
> Additionally, crops normally don't grow unless the combined light level (accounting for time of day) is at least 9.
Please answer 2 posts below

**Comment by xSuperr** [comment]
A better description of these mechanics are as follows:

The growth probability is 1 / (floor(25/points) + 1), where as in PM it is just 33%


- A light level of 9 or higher in the block ABOVE the crop
- 2 points are given if the crops farmland is dry, or 4 if fertilized
- For 8 blocks around the crop (Arranged in a 3x3 with the crop being the center), if its dry farmland it gives 0.25 points, or 0.75 if fertilized 
- If any crops of the same type are growing in those blocks, the point value is divided in half, UNLESS the crops are arranged in rows. This means the row can go north-south OR east-west. Not both (Like a plus pattern). This chance is only halved once if these conditions are met.

SOURCE: https://minecraft.fandom.com/el/wiki/Tutorials/Crop_farming#Growth_rate

**Comment by dktapps** [comment]
> For 8 blocks around the crop (Arranged in a 3x3 with the crop being the center), if its dry farmland it gives 0.25 points, or 0.75 if fertilized

It's different for the corners vs the directly adjacent blocks. Directly adjacent farmland counts for 1 point, and the corners count for 0.25. Any value is multiplied by 3 if hydrated.

**Comment by xSuperr** [comment]
> > For 8 blocks around the crop (Arranged in a 3x3 with the crop being the center), if its dry farmland it gives 0.25 points, or 0.75 if fertilized
> 
> It's different for the corners vs the directly adjacent blocks. Directly adjacent farmland counts for 1 point, and the corners count for 0.25. Any value is multiplied by 3 if hydrated.

So 1/3 for adjacent and 0.25/0.75 for corners, and does the multiplier affect the block the crop is on, or is it just 2/4?

**Comment by dktapps** [comment]
I forget the exact behaviour for the crop's own block, but there is an effect, yes.

**Comment by xSuperr** [comment]
From my testing with the above values, a crop sitting by itself or in a row would have a 50% chance to grow, and a crop in the middle of a 3x3 of crops would have a 33% chance, which seems about right. However my implementation of it is very poorly written so perhaps someone else could PR it.

**Comment by dktapps** [comment]
Implemented by 109673382d213222fcf18b0d08ae18b73a3e1e51.
