### ISSUE TITLE
[Server thread/ERROR]: [NetworkSession: plug Plugins] Bad packet: Too many packets in batch

### ISSUE THREAD

**Issue by gamegam** [pmmp/PocketMine-MP#6088]
### Issue description

- Expected result: What were you expecting to happen?
- Actual result: What actually happened?

### Steps to reproduce the issue
: [NetworkSession: plug Plugins] Session closed: A packet processing error occurred (Error ID: 39a5-8266-1ffd)
If you turn on Nuker while testing cheating detection (anti-cheat), you will get that bug.

### OS and versions

* PocketMine-MP: 5.6.1
* PHP: 8.1
* Using JIT: yes/no (delete as appropriate) 
* Server OS win:
* Game version: Android/iOS/Win10/Xbox/PS4/Switch (delete as appropriate)

### Plugins

- If you remove all plugins, does the issue still occur?
- If the issue is **not** reproducible without plugins:
  - Have you asked for help on our forums before creating an issue?
  - Can you provide sample, *minimal* reproducing code for the issue? If so, paste it in the bottom section

**Comment by dktapps** [comment]
It's not a bug. Nuker spams packets which trips the server's rate limits. It's doing exactly what it's designed to do.
