### ISSUE TITLE
PlayerHandUseEvent

### ISSUE THREAD

**Issue by gamegam** [pmmp/PocketMine-MP#6091]
## Description
PlayerHandUseEvent By adding , it is detected when the player hits the air or left-clicks. However, it is only detected when the player right-clicks with PlayerInteractEvent.
On the contrary, the event detected when you hit the air or left-click (PlayerItemUseEvent) can only be used while holding the item.
PlayerHandUseEvent is detected whenever you left-click without holding an item or anything.

## Justification
This is useful when creating a CPS plugin or anti-cheat.
There is a cheat in Anti-Cheat that teleports when touched.
If you right-click, it is detected, but if you left-click and run TouchTP, it is not detected.

**Comment by dktapps** [comment]
PlayerMissSwingEvent is what you're looking for
