### ISSUE TITLE
Resolve promise with null result in promise rejection

### ISSUE THREAD

**Issue by ShockedPlot7560** [pmmp/PocketMine-MP#6110]
### Issue description

If we resolve a promise with null before we have register completion handlers, when we will add new completion handlers, it will result in rejection and not resolved.

This happens because when registering completion handlers, if the resolution value is null, it is considered rejected.

### Steps to reproduce the issue
1. Create a PromiseResolver, resolve it with null `$resolver->resolve(null);`
2. Register new completion handlers with `$promise->onCompletion(...);`
3. Note that the reject handler is called instead of the resolution handler.

### OS and versions

* PocketMine-MP: 5.6.1
* PHP: 8.1
* Using JIT: no
* Server OS: Windows/Linux

**Comment by dktapps** [comment]
I thought I added a `resolved` property for this exact reason ...

**Comment by dktapps** [comment]
Never mind, I see the problem: https://github.com/pmmp/PocketMine-MP/blob/38d6284671e8b657ba557e765a6c29b24a7705f5/src/promise/Promise.php#L45

Perhaps `bool|null` or an enum would be more appropriate.
