### ISSUE TITLE
Related to blocks

### ISSUE THREAD

**Issue by gamegam** [pmmp/PocketMine-MP#6113]
![화면 캡처 2023-10-23 175939](https://github.com/pmmp/PocketMine-MP/assets/48847058/7b34b02d-4069-42ff-b8e4-df0c8d08afc9)

## Description
Let's assume that it's soul sand.
This is a recently patched vanilla feature.
Same as the picture.

It's common knowledge that walking the soul block slows down. Walking outward won't slow you down.
(Other blocks are the same)

**Comment by Bqleine** [comment]
Related minecraft bug report : https://bugs.mojang.com/browse/MC-1133

**Comment by dktapps** [comment]
> Related minecraft bug report : https://bugs.mojang.com/browse/MC-1133

Thanks for this @Bqleine. From the issue alone I had no idea what the problem was. The linked Minecraft issue makes it clear.

**Comment by dktapps** [comment]
I don't think this actually has anything to do with PM at all. Soul sand is a block like any other to PM.
