### ISSUE TITLE
Server crashed with unset permission

### ISSUE THREAD

**Issue by dadodasyra** [pmmp/PocketMine-MP#6119]
Link to crashdump: https://pastebin.com/YQ71BBSq

### Additional comments (optional)
We already talked about it on Discord, this may (dylan seems confident about it) be related to automatic garbage collector.
This crash is recurring on my server and happening randomly with any permission.

**Comment by dadodasyra** [comment]
I dont know why it seems that I'm the only one really affected by this. I have like 10 crashs/day with this.

**Comment by dktapps** [comment]
It could be a bunch of different things, but essentially it comes down to something removing permission subscriptions in a __destruct(), perhaps indirectly. The function isn't reentrant safe.

**Comment by MateusBlackyOFC** [comment]
> Não sei por que parece que sou o único realmente afetado por isso. Tenho cerca de 10 falhas/dia com isso.

This has also happened to me with several failures in a single day!
