### ISSUE TITLE
Melon and Pumpkin cannot grow

### ISSUE THREAD

**Issue by Azvyl** [pmmp/PocketMine-MP#6131]
### Issue description
Related changes: 390cc30

- Expected result:
  This is what happened in PM 5.7.1

  https://github.com/pmmp/PocketMine-MP/assets/67502532/b4ae48af-e283-4c35-963c-3ee47b3ff6b7

- Actual result:

  https://github.com/pmmp/PocketMine-MP/assets/67502532/819f8e9e-b7fd-4585-ab1f-8a09703c5038

### Steps to reproduce the issue
1. Setup a PocketMine 5.7.1 server
2. Set `chunk-ticking.blocks-per-subchunk-per-tick` in pocketmine.yml to a higher value (240 is used in the video), then start the server
3. Place Melon seeds and Pumpkin seed
4. Update to PM 5.8.1 and try to place Melon Seeds and Pumpkin Seeds again

### OS and versions
* PocketMine-MP: 5.8.1
* PHP: 8.2.10
* Using JIT: not supported
* Server OS: win
* Game version: Android

**Comment by dktapps** [comment]
This is most likely an unintended side effect of 390cc3060a9183ceac9cea07a3c7801c8b9d68eb
