### ISSUE TITLE
Impossible to give this item pitcher_plant

### ISSUE THREAD

**Issue by Nat392** [pmmp/PocketMine-MP#6133]
Hello, in your latest update (5.8.1), you've implemented some items like pitcher plant but we can't get to them or see them in the creative menu.

**Comment by dktapps** [comment]
Yeah, `pitcher_pod` is also missing.

**Comment by dktapps** [comment]
Fixed by c44758f36cad5ce33d6bbbcea6e43d97aeff6371.
