### ISSUE TITLE
AddPlayerPacket

### ISSUE THREAD

**Issue by gamegam** [pmmp/PocketMine-MP#6159]
## Description
$pk->actorRuntimeId = int;

Please let me use strings instead of numbers
That way, we can create more

I use that for Tag plugin. Even if I use mt_rand, it seems like something will become unstable.

**Comment by SenseiTarzan** [comment]
This is not possible because Minecraft works like this and pmmp must follow the packets that Minecraft expects

**Comment by SenseiTarzan** [comment]
This is not possible because Minecraft works like this and pmmp must follow the packets that Minecraft expects

**Comment by dktapps** [comment]
You shouldn't be using that packet directly anyway ...
