### ISSUE TITLE
Unusable inventory

### ISSUE THREAD

**Issue by roimee6** [pmmp/PocketMine-MP#6185]
### Issue description

- Expected result: Just nothing
- Actual result: The inventory become bug

### Steps to reproduce the issue
1. /give player air

### OS and versions

* PocketMine-MP: 5.8.2 
* PHP: PHP 8.1 - Latest (Build 325) [Latest]
* Server OS: Debian

### Plugins

- If you remove all plugins, does the issue still occur?

YES

### Crashdump, backtrace or other files

https://youtu.be/3iSKDnihLcM

**Comment by TheNewHEROBRINEX** [comment]
Probably caused by #6016
