### ISSUE TITLE
When a player crashes against a wall

### ISSUE THREAD

**Issue by gamegam** [pmmp/PocketMine-MP#6196]
## Description
PlayerCollisionEvent

Each time you collide with a wall, this meshed is output.

It should be output based on the block below.
Example: Y: Suppose there are blocks in 4 and 5.
Then, it recognizes it as 4 blocks and outputs it.

## Justification
If you add this, you will not be able to create content.

## Alternative methods
$player->isCollision()

**Comment by Matze997** [comment]
It´s sounds like a lot of spam

Something OnPlayerCollisionEvent would make more sense to avoid spamming like in [PressurePlateUpdateEvent](https://github.com/pmmp/PocketMine-MP/blob/stable/src/event/block/PressurePlateUpdateEvent.php)

**Comment by jasonw4331** [comment]
Use `PlayerMoveEvent` coupled with `Entity->isCollided`, `Entity->isCollidedHorizontally`, or `Entity->isCollidedVertically` to indicate collision state. You can then get the blocks surrounding the player yourself.

**Comment by jasonw4331** [comment]
Related to #5799
