### ISSUE TITLE
Inventory Syncing Bug

### ISSUE THREAD

**Issue by odavidu** [pmmp/PocketMine-MP#6206]
### Issue description

- Expected result: **A player's inventory slots would be updated.**
- Actual result: **It does get updated... just about 60 times a second.**

### Steps to reproduce the issue
1. Have at least one item in your invewntory
2. Manually call `Player->getNetworkSession()->getInvManager()->requestSyncAll()` when a player joins
3. See your item flicker in your inventory

### OS and versions

* PocketMine-MP: **5.10.0**
* PHP: **8.1.24**
* Using JIT: **no**
* Server OS: **Linux**
* Game version: **Win10**

### Plugins

![image](https://github.com/pmmp/PocketMine-MP/assets/142190596/5e059387-d6ad-4195-9915-8e9382390813)

- If you remove all plugins, does the issue still occur?: **No**
- If the issue is **not** reproducible without plugins: **Yes**
  - Have you asked for help on our forums before creating an issue?: **No**
  ****- Can you provide sample, *minimal* reproducing code for the issue? If so, paste it in the bottom section

### Crashdump, backtrace or other files

```php
<?php
declare(strict_types=1);

namespace issue;

use pocketmine\event\Listener;
use pocketmine\event\player\PlayerJoinEvent;
use pocketmine\plugin\PluginBase;

class Issue extends PluginBase implements Listener {

    protected function onEnable(): void {
        $this->getServer()->getPluginManager()->registerEvents($this, $this);
    }

    public function onPlayerJoin(PlayerJoinEvent $event) {
        $player = $event->getPlayer();
        $player->getNetworkSession()->getInvManager()->requestSyncAll();
    }
}
```
![image](https://github.com/pmmp/PocketMine-MP/assets/142190596/a3cba692-7ebb-4a8d-8f8a-50c9deb896ec)

**Comment by dktapps** [comment]
That function isn't supposed to be used by plugins anyway...
