### ISSUE TITLE
Parts of plants don't grow.

### ISSUE THREAD

**Issue by AzOxStOz** [pmmp/PocketMine-MP#6207]
### Issue description

- Expected result: When planting sugar cane, oak tree plant they should grow automatically.
- Actual result: The function onRandomTick do not execute so they don't grow, but when it's wheat, potato (Crops) they grow and the methode is executed. If you bone meal the don't grow plants it grows.

### Steps to reproduce the issue
1. Put a sugar cane next to water. Make sure to delete all your plugins and server configuration so server is brand new.
2. Put a wheat next to the sugar cane for comparaison.
3. Wait and see that the weath can grow 8 times but sugar cane no

### OS and versions

* PocketMine-MP: 5.9.0 (git hash: 46307973e33e569e3730117a6a0a976c11438fe5)
* PHP: 8.3.0
* Using JIT: no
* Server OS: Windows 10 and Linux too
* Game version: don't matter 

### Plugins
0

- If you remove all plugins, does the issue still occur? YES
- If the issue is **not** reproducible without plugins: NO
  - Have you asked for help on our forums before creating an issue? YES BUT GOT A MUTE
  - Can you provide sample, *minimal* reproducing code for the issue? If so, paste it in the bottom section NO CRASH

**Comment by dktapps** [comment]
The growth rate for sugarcane is much slower than wheat. In ideal conditions wheat grows approximately once every 3.5 minutes. Sugarcane grows once every 18 minutes.
