### ISSUE TITLE
Magma block onEntityInside does not work

### ISSUE THREAD

**Issue by Squashhh** [pmmp/PocketMine-MP#6209]
Hello,
I tried to walk on a magma block, but it was coded to set me on fire, so it didn't work! Here's a video attached!
Thanks

https://github.com/pmmp/PocketMine-MP/blob/7a55a6e6b6c10f5033491603443c16f434d0deed/src/block/Magma.php#L41C18-L41C32

https://github.com/pmmp/PocketMine-MP/assets/83670807/d2043087-288f-4045-85b9-d314d3039add

**Comment by IvanCraft623** [comment]
Duplicate of #2041
