### ISSUE TITLE
World::setTime() sometimes not updating block lights

### ISSUE THREAD

**Issue by minijaham** [pmmp/PocketMine-MP#6212]
### Issue description
- Expected result: World::setTime() should change the block's lights as well, depending on the time set in the param.
- Actual result: Every time, the sky changes properly. However, the world's blocks' lights do not update.

### Steps to reproduce the issue
1. Use /time set day
2. Use /time set night
3. Repeat 1 and 2.

### OS and versions
* PocketMine-MP: 5.10.0
* PHP: 8.2 (Build 331)
* Using JIT: No
* Server OS: Windows 10
* Game version: Win10 (Only tested on Win10)

### Plugins
- Happens without plugins as well.

### Crashdump, backtrace or other files
Demonstration:
https://youtu.be/oYXx_XICwtQ

**Comment by dktapps** [comment]
This looks like a client side issue
