### ISSUE TITLE
Custom `phar://` stream wrapper to prevent `/tmp` wastage

### ISSUE THREAD

**Issue by dktapps** [pmmp/PocketMine-MP#6214]
## Description
`ext-phar` decompresses compressed phar contents into temporary files in `/tmp`. This is problematic because the cached temporary file is not shared between different threads, leading to several MB of wasted `/tmp` footprint per thread started.

While this is not a unique problem to PM, it should be possible to work around this with a custom stream wrapper that either doesn't cache the files at all (the cache is only really useful when including the same file multiple times without opcache, or when loading a data file directly), or that caches them in a more thread-friendly manner.

## Justification
Recently users of Pterodactyl hosts have experienced issues with tmp space being filled due to this issue.

**Comment by dktapps** [comment]
Apparently reading the file via manually opening the `Phar` causes the same problem as using `phar://`. There doesn't appear to be any way to read phar contents without dumping useless crap into `/tmp`.

**Comment by dktapps** [comment]
Related to php/php-src#13055

**Comment by dadodasyra** [comment]
If I can add maybe something to this, I had issue in the past with some crash loops where the /tmp folder began to grow and grow. Normally the "anti crash loop system" of pocketmine is enough but if it crashs before pmmp correctly starts (for example a plugin with the wrong api version) it will create a lot of temp files, until saturation of the storage.

**Comment by dktapps** [comment]
Yeah, the tmp spam on crash is a pretty big issue, and not easy to solve.

The main issue is that we have no way to identify which tmpfiles belong to the server after it restarts, so we don't know which ones are in use and which ones can be deleted. A few possible solutions to this:

- Change tmpdir to `/tmp/pocketmine/<pid>` and then nuke the directory on the next startup based on the contents of `server.lock`
- Put tmpfiles in the server's data directory - unpleasant solution, sucks for backup purposes
- Stop compressing the phar entirely - not great, phar size jumps to 15 MB :(

**Comment by dktapps** [comment]
Fixed by #6217.
