### ISSUE TITLE
Scaling a projectile does not actually scale its hitbox

### ISSUE THREAD

**Issue by IvanCraft623** [pmmp/PocketMine-MP#6231]
### Issue description
As title, making a projectile larger does not increase the area in which it hits entities/blocks.

### Steps to reproduce the issue
1. Throw a prjectile (Be sure to aim right next to the target.)
2. Scale it wahterver you want (more than 4 times makes evident)
3. Observes that the projectile does not collide

### OS and versions

* PocketMine-MP: 5.10.1
* PHP:  8.2.13

### Crashdump, backtrace or other files

https://github.com/pmmp/PocketMine-MP/assets/57236932/bda93ab2-a51d-4a68-a340-038ce81d04ea

**Comment by dktapps** [comment]
This is expected due to the way projectile movement works (using ray trace). It's not practical to change this, as the current method is required to make normal projectiles work correctly.
