### ISSUE TITLE
Fatal Error Server crashed

### ISSUE THREAD

**Issue by DragonfireHD98** [pmmp/PocketMine-MP#6232]
<Fatal error: Uncaught ErrorException: include(): Write of 2764 bytes failed with errno=28 No space left on device in phar:///home/container/PocketMine-MP.phar/vendor/composer/ClassLoader.php:576
Stack trace:
#0 phar:///home/container/PocketMine-MP.phar/vendor/composer/ClassLoader.php(576): pocketmine\errorhandler\ErrorToExceptionHandler::handle(8, 'include(): Writ...', 'phar:///home/co...', 576)
#1 phar:///home/container/PocketMine-MP.phar/vendor/composer/ClassLoader.php(576): include()
#2 phar:///home/container/PocketMine-MP.phar/vendor/composer/ClassLoader.php(427): Composer\Autoload\{closure}('phar:///home/co...')
#3 phar:///home/container/PocketMine-MP.phar/src/thread/CommonThreadPartsTrait.php(133): Composer\Autoload\ClassLoader->loadClass('pocketmine\\thre...')
#4 [internal function]: pocketmine\thread\Worker->pocketmine\thread\{closure}()
#5 phar:///home/container/PocketMine-MP.phar/src/thread/CommonThreadPartsTrait.php(128): pmmp\thread\ThreadSafe->synchronized(Object(Closure))
#6 [internal function]: pocketmine\thread\Worker->onShutdown()
#7 {main}
  thrown in phar:///home/container/PocketMine-MP.phar/vendor/composer/ClassLoader.php on line 576

**Comment by DragonfireHD98** [comment]
crashdump dosent exists

**Comment by ShockedPlot7560** [comment]
The crash is clear
