### ISSUE TITLE
Old Version

### ISSUE THREAD

**Issue by MrShrekThird** [pmmp/PocketMine-MP#6245]
PMMP needs to update to Minecraft version 1.20.60

**Comment by ShockedPlot7560** [comment]
Its already supported

**Comment by MrShrekThird** [comment]
No its notSent from my iPhoneOn 6 Feb 2024, at 5:04 pm, ShockedPlot7560 ***@***.***> wrote:﻿
Its already supported

**Comment by ShockedPlot7560** [comment]
I had read 1.20.50, my bad

**Comment by MrShrekThird** [comment]
👍Sent from my iPhoneOn 6 Feb 2024, at 5:06 pm, ShockedPlot7560 ***@***.***> wrote:﻿
I had read 1.20.50, my bad

**Comment by MrShrekThird** [comment]
When do you think this will be patched

**Comment by MrShrekThird** [comment]
Do you know?

**Comment by Newcoolboys** [comment]
Being annoying for a update isn't going to make it come out any faster, the version just came out, expect PM to be updated in a couple of days
