### ISSUE TITLE
Fixed variables in e.g. VanillaBlocks.php

### ISSUE THREAD

**Issue by pandaaaBE** [pmmp/PocketMine-MP#6263]
Would be cool if you had fixed variables in e.g. VanillaBlock.php for new Info(BreakInfo::instant) etc.

**Comment by dktapps** [comment]
I have no idea what this is supposed to mean

**Comment by pandaaaBE** [comment]
e.g. in my PR I use new Info(BreakInfo::instant) but for this I had to create a $var although the same breakinfo is used over 30x in the code

**Comment by dktapps** [comment]
I don't think the code would be any clearer if the registrations were referencing a random variable 200 lines away.
