### ISSUE TITLE
Version 

### ISSUE THREAD

**Issue by GabBiswajit** [pmmp/PocketMine-MP#6283]
Add new 1.20.70 version and don't remove 1.20.60 version ☠️ can it possible pocketmine support multiple versions?

**Comment by AnyBananaGAME** [comment]
You could make a plugin that adds support for multi versions. No need for it to be in the software itself. Not everyone wants that and may cause issues for them

**Comment by GabBiswajit** [comment]
Ok but when 1.20.70 version support add ?

**Comment by AnyBananaGAME** [comment]
Soon
