### ISSUE TITLE
Changer RakLib write in full php to extension zend with Raknet official

### ISSUE THREAD

**Issue by SenseiTarzan** [pmmp/PocketMine-MP#6302]
I wonder if this could help to have better output than if it were done in php?

**Comment by dktapps** [comment]
No. It's premature optimisation. As I've said elsewhere, we have no idea of the performance characteristics of RakLib.

**Comment by dktapps** [comment]
Official RakNet is also abandonware, riddled with bugs, and vastly more complicated than RakLib. The only thing we'd really achieve would be massively increasing the server's attack surface.

**Comment by SenseiTarzan** [comment]
> Official RakNet is also abandonware, riddled with bugs, and vastly more complicated than RakLib. The only thing we'd really achieve would be massively increasing the server's attack surface.

And would it be interesting for you to do it again in C++ with php-cpp?

**Comment by dktapps** [comment]
no

**Comment by SenseiTarzan** [comment]
> no

Explain to me why?
