### ISSUE TITLE
Entities are not loaded from disk

### ISSUE THREAD

**Issue by alvin0319** [pmmp/PocketMine-MP#6316]
### Issue description

- Expected result: What were you expecting to happen? Entities should be loaded from disk which was imported from vanilla world
- Actual result: What actually happened? Entities are not loaded from disk

### Steps to reproduce the issue
1. Get some vanilla world
2. Try loading it on PM

### OS and versions

* PocketMine-MP: 5.13.0
* PHP: 8.3
* Using JIT: no
* Server OS: Windows
* Game version: Windows 10

### Plugins
N/A

- If you remove all plugins, does the issue still occur? Yes
- If the issue is **not** reproducible without plugins:
  - Have you asked for help on our forums before creating an issue?
  - Can you provide sample, *minimal* reproducing code for the issue? If so, paste it in the bottom section

### Crashdump, backtrace or other files

Expected (From vanilla)
![Minecraft 2024-04-01 오후 7_08_31](https://github.com/pmmp/PocketMine-MP/assets/32565818/b781867b-1073-4d3f-9e68-9d1575846699)

Actual (From PM)
![Minecraft 2024-04-01 오후 7_09_30](https://github.com/pmmp/PocketMine-MP/assets/32565818/34f16af0-5a36-4067-b6bb-b08fee8465ab)

World used by this test: [4S0KZg8gAgA=.zip](https://github.com/pmmp/PocketMine-MP/files/14822380/4S0KZg8gAgA.zip)

**Comment by diamond-gold** [comment]
#5855

**Comment by dktapps** [comment]
Duplicate of #5855
