### ISSUE TITLE
Stuck at downloading resource pack

### ISSUE THREAD

**Issue by UnknownOre** [pmmp/PocketMine-MP#6338]
### Issue description

- Expected result: players downloading resource pack in loading screen
- Actual result: players getting stuck at download resource pack

### Steps to reproduce the issue
1. Connect to a servers that's using PM 5.14.0 and above (not on local host)
2. Sometimes you get stuck at downloading resource pack

### OS and versions

* PocketMine-MP: 5.4.2
* PHP: 8.3
* Using JIT: yes/no (delete as appropriate) 
* Server OS: Ubuntu 22.04
* Game version: Android/iOS/Win10/Xbox/PS4/Switch (delete as appropriate) 1.20.70

### Crashdump, backtrace or other files

This started happening after this commit  https://github.com/pmmp/PocketMine-MP/commit/b9a1ef1357e6b784f5f2de15e5a0b7bc31e296a5

**Comment by dktapps** [comment]
I can't do anything without more specific reproducing information. "It happens randomly" type issues are impossible to debug. The referenced commit fixed many issues with resource packs so I won't be rolling it back.

**Comment by UnknownOre** [comment]
Well, it happens 1/3 times so the chances of it happening on a remote server is pretty high, I heard a lot of servers complaining about the issue, but no one bothered to create an issue though.

**Comment by dktapps** [comment]
Any specific servers?

**Comment by dktapps** [comment]
This will be closed as Won't Fix if no more information is provided

**Comment by UnknownOre** [comment]
You can close it for now, I will debug it and post reproducing steps
