### ISSUE TITLE
Unexpected Freezes

### ISSUE THREAD

**Issue by 6kek6** [pmmp/PocketMine-MP#6361]
### Issue description
 https://github.com/pmmp/PocketMine-MP/issues/2618 
 Same problems again.

### OS and versions
* PocketMine-MP: 5.16.1
* PHP: 8.2.17
* Using JIT: no
* Server OS: Ubuntu 20.04
* Game version: all

### Plugins
 Without plugins

### Crashdump, backtrace or other files
 Similarly #2618

**Comment by dries-c** [comment]
Would it be possible to send us timings of this happening?

**Comment by IvanCraft623** [comment]
To provide timings you need to follow these steps:
1. Run `/timings on` command
2. Try to replicate the freeze or wait for it to happen, the report should be at least 25 minutes with players on the server.
3. Run `/timings paste` command
4. Send us the generated URL

**Comment by 6kek6** [comment]
The timing is completely random. It could happen in an hour, it could happen in a few days.

Regarding timings, do you generally understand the essence of the problem? The server completely freezes at a random moment and NOTHING CAN BE RECEIVED (Only if you take some data directly from PHP).

This is such an interesting problem, very...

**Comment by Gewinum** [comment]
@6kek6 have you ever had any beef with players

**Comment by Gewinum** [comment]
@IvanCraft623 i might know reasons of freeze, can you please contact me? can't talk about this in public. my dc @gewinum

**Comment by 6kek6** [comment]
Currently trying to get more logs and information.

**Comment by Gewinum** [comment]
> Currently trying to get more logs and information.

please contact me in discord @gewinum

**Comment by s1111111111c** [comment]
Garbage Collection

**Comment by IvanCraft623** [comment]
Closing due to lack of basic reproduction steps
