### ISSUE TITLE
getFlag

### ISSUE THREAD

**Issue by gamegam** [pmmp/PocketMine-MP#6362]
## Description
Could you please add functionality within PMMP so that if $player->getNetworkProperties()->getGenericFlag(EntityMetadataFlags::RIDING); does not have the EntityMetadataFlags::RIDING flag for the player or entity in question, it will be treated as null and If present, it is displayed as true.

## Justification
If you add this, your creativity will be better.

1. I'll give you that flag
Check whether it is granted or not.

2. It is also useful for making anti-cheats.
Reason: Add a vaxter or flag and give the rider to that player and it will also be detected by the speed nucleus.
This allows you to deport only abnormal players without being banished to the server or banished to the server by determining that you are on a rider if you are not null.

## Alternative methods
None

**Comment by dries-c** [comment]
It's a very specific request and could be integrated into a plugin directly by reversing the FLAGS & FLAGS2 bit responsible for it.
