### ISSUE TITLE
My friend's can't enter in my server

### ISSUE THREAD

**Issue by MarwanEA** [pmmp/PocketMine-MP#64]
Hi ,
I have a server PocketMine in my **tablet**,with os Android 4.2.2 and version minecraft **0.15.10**, in my tablet i can enter in my server, but my friend's not ,because my ip and port are false ,if i add them in another phone of using **the same wifi,** i saw the server in broadcaster lan and it is fixed, but in another wifi not. 
My ip : 192.168.1.27
Port: 19312 or 25565
 please help me or contact me in gmail : Marwanelaoumrani@gmail.com 👍

**Comment by 99leonchang** [comment]
This is an issue with portforwarding, not with PocketMine.

**Comment by daniktheboss** [comment]
Port forward your ip. Go to Google my ip and then ur router setting and port it to port 19132

**Comment by dktapps** [comment]
This is not a support forum, please stop treating it as one.
