### ISSUE TITLE
Effects particles are not visible

### ISSUE THREAD

**Issue by IWareQ** [pmmp/PocketMine-MP#6402]
### Issue description

- Expected result: particles are visible
- Actual result: particles are not visible

### Steps to reproduce the issue
1. /effect [player] speed

Instead of `speed`, there can be any effect that gives particles

### OS and versions

* PocketMine-MP: 5.17.0 (git hash: 37bf4bc0b0c095758c8ee09e5681a369396da7ce)
* PHP: 8.2.17
* Using JIT: no
* Server OS: win
* Game version: Win10

### Crashdump, backtrace or other files
![image](https://github.com/user-attachments/assets/ea117e28-471d-4995-85e1-c3bc8d4df429)

**Comment by nicholass003** [comment]
is it only for certain effects or for all effects?

**Comment by IWareQ** [comment]
> is it only for certain effects or for all effects?

Instead of `speed`, there can be any effect that gives particles

**Comment by Lioncat6** [comment]
This could be caused by mojang updating the formatting of a data packet or something similar, but I'm not entirely sure..,

![image](https://github.com/user-attachments/assets/a9c9529d-a6cd-4887-a886-92834267ac47)

**Comment by ipad54** [comment]
This is caused because Bedrock no longer uses `POTION_COLOR` metadata property for displaying effects. It now uses a separated property that writes effect ids instead of colours.

**Comment by IWareQ** [comment]
> This is caused because Bedrock no longer uses `POTION_COLOR` metadata property for displaying effects. It now uses a separated property that writes effect ids instead of colours.

Thank! This work for me:
![image](https://github.com/user-attachments/assets/93cb605d-c46e-441e-9526-6518cb07e0d7)
