### ISSUE TITLE
Lots of items named ENCHANTED_BOOK in Creative Inventory

### ISSUE THREAD

**Issue by b1zeyofficial** [pmmp/PocketMine-MP#6411]
### Issue description

- Expected result: What were you expecting to happen?
- Actual result: What actually happened?

### Steps to reproduce the issue
1. Launched the latest version of PocketMine
2. Logged into the server, opened Creative Inventory

### OS and versions
* PocketMine-MP:
* PHP: 8.2.17
* Using JIT: no
* Server OS: Win
* Game version: Android/iOS/Win10/Xbox/PS4/Switch

### Plugins

- If you remove all plugins, does the issue still occur? YES.
- If the issue is **not** reproducible without plugins:
  - Have you asked for help on our forums before creating an issue? NO.
![Screenshot 2024-08-04 105543](https://github.com/user-attachments/assets/b642cebd-f9e6-422a-8fce-3945c811e1c6)

**Comment by dktapps** [comment]
These are most likely the ones whose enchantments aren't implemented yet

**Comment by ShockedPlot7560** [comment]
> These are most likely the ones whose enchantments aren't implemented yet

No book has enchantments

**Comment by ShockedPlot7560** [comment]
The enchantments are stored in the json and are correctly injected into the creativeInventory. The problem is that the client does not have any enchantments and when a book is retrieved, no enchantments are present.

**Comment by dktapps** [comment]
Yeah, because this discards unknown enchantments: https://github.com/pmmp/PocketMine-MP/blob/5a926a79cb97f284c64c754d3f60fba8348435b8/src/item/Item.php#L316

**Comment by ShockedPlot7560** [comment]
Some items have enchantments that are already known, but none in the creative inventory has an enchantment.

**Comment by b1zeyofficial** [comment]
By the way, this bug only happens in the items tab

**Comment by dktapps** [comment]
> Some items have enchantments that are already known, but none in the creative inventory has an enchantment.

The ones that appear in this mess are indeed the ones that have un-implemented enchantments, but if you look near Book & Quill in the Items tab, you'll notice this:

![image](https://github.com/user-attachments/assets/2d568295-6e68-4c0a-8592-f28f9a55b024)
![image](https://github.com/user-attachments/assets/19e0655e-b068-4aa5-bab3-5fc87fdcb768)

Basically, the ones that do have enchantments are grouped together under one icon, but the ones that don't are dumped at the end of the list by the client. Makes it hard to spot what's going on.

The only thing PM could really do about this would be to omit the books which have no enchantments on them, but it's just a cosmetic issue.

**Comment by b1zeyofficial** [comment]
removing unenchanted books will make the players inventory tidier and more logical, but it does not in itself fix any major bug or add new features
