### ISSUE TITLE
bug block slap 

### ISSUE THREAD

**Issue by Didin109** [pmmp/PocketMine-MP#6431]
PocketMine-MP Crash Dump Sat Aug 17 16:39:27 WIB 2024

PocketMine-MP version: 5.18.0 [Protocol 712]
Git commit: 9176b2494a4a84729f9cc4dd1f75dd3ec2c8618d
PHP version: 8.2.17
OS: Linux, linux

A PLUGIN WAS INVOLVED IN THIS CRASH

Thread: AsyncWorker#1
Error: pocketmine\data\bedrock\block\convert\BlockObjectToStateSerializer::pocketmine\data\bedrock\block\convert\{closure}(): Argument #1 ($block) must be of type pocketmine\block\Slab, pocketmine\block\UnknownBlock given, called in phar:///tmp/PocketMine-MP-phar-cache.0/PMMPRZxfC7.tar/src/data/bedrock/block/convert/BlockObjectToStateSerializer.php on line 271
File: pmsrc/src/data/bedrock/block/convert/BlockObjectToStateSerializer
Line: 235
Type: TypeError
Backtrace:
#0 pmsrc/src/data/bedrock/block/convert/BlockObjectToStateSerializer(271): pocketmine\data\bedrock\block\convert\BlockObjectToStateSerializer->pocketmine\data\bedrock\block\convert\{closure}(object pocketmine\block\UnknownBlock#183741)
#1 pmsrc/src/data/bedrock/block/convert/BlockObjectToStateSerializer(215): pocketmine\data\bedrock\block\convert\BlockObjectToStateSerializer->serializeBlock(object pocketmine\block\UnknownBlock#183741)
#2 pmsrc/src/network/mcpe/convert/BlockTranslator(61): pocketmine\data\bedrock\block\convert\BlockObjectToStateSerializer->serialize(int 22003275)
#3 pmsrc/src/network/mcpe/serializer/ChunkSerializer(148): pocketmine\network\mcpe\convert\BlockTranslator->internalIdToNetworkId(int 22003275)
#4 pmsrc/src/network/mcpe/serializer/ChunkSerializer(94): pocketmine\network\mcpe\serializer\ChunkSerializer::serializeSubChunk(object pocketmine\world\format\SubChunk#183662, object pocketmine\network\mcpe\convert\BlockTranslator#49725, object pocketmine\network\mcpe\protocol\serializer\PacketSerializer#164746, false)
#5 pmsrc/src/network/mcpe/ChunkRequestTask(74): pocketmine\network\mcpe\serializer\ChunkSerializer::serializeFullChunk(object pocketmine\world\format\Chunk#164737, int 0, object pocketmine\network\mcpe\convert\BlockTranslator#49725, string[94] ....id.Bed..x.v..yz..z.0..color......id.Bed..x.v..yz..z.0..color......id.Hopper.)
#6 pmsrc/src/scheduler/AsyncTask(81): pocketmine\network\mcpe\ChunkRequestTask->onRun()
#7 (): pocketmine\scheduler\AsyncTask->run()

Code:
[226] 		}
[227] 		$this->serializers[$block->getTypeId()] = $serializer;
[228] 	}
[229] 
[230] 	public function mapSimple(Block $block, string $id) : void{
[231] 		$this->map($block, fn() => Writer::create($id));
[232] 	}
[233] 
[234] 	public function mapSlab(Slab $block, string $singleId, string $doubleId) : void{
[235] 		$this->map($block, fn(Slab $block) => Helper::encodeSlab($block, $singleId, $doubleId));
[236] 	}
[237] 
[238] 	public function mapStairs(Stair $block, string $id) : void{
[239] 		$this->map($block, fn(Stair $block) => Helper::encodeStairs($block, Writer::create($id)));
[240] 	}
[241] 
[242] 	public function mapLog(Wood $block, string $unstrippedId, string $strippedId) : void{
[243] 		$this->map($block, fn(Wood $block) => Helper::encodeLog($block, $unstrippedId, $strippedId));
[244] 	}
[245]

**Comment by IvanCraft623** [comment]
> A PLUGIN WAS INVOLVED IN THIS CRASH
