### ISSUE TITLE
Blue Ice Block should be affected by Silk Touch Enchantment (Similar to Ice & Packed Ice)

### ISSUE THREAD

**Issue by HydroGames-dev** [pmmp/PocketMine-MP#6437]
### Issue description

Issue referenced by: https://discord.com/channels/373199722573201408/480650036972224513/1278090556584628336

- Expected result: Blue Ice Dropping when mined with a tool with silk touch enchantment.
- Actual result: Blue Ice does not drop when mined with a silk touch enchanted tool.

Source: https://minecraft.wiki/w/Blue_Ice
`Blue ice can be obtained using any tool enchanted with Silk Touch, although a pickaxe is the fastest. Breaking the block without Silk Touch drops nothing.`

[Blue Ice](https://github.com/pmmp/PocketMine-MP/blob/stable/src/block/BlueIce.php) Missing `isAffectedBySilkTouch` the property

### Steps to reproduce the issue
1. Place a Blue Ice.
2. Mine the block with an tool enchanted with silk touch.

### OS and versions
* PocketMine-MP: 5.18.0 (git hash: 9176b2494a4a84729f9cc4dd1f75dd3ec2c8618d)
* PHP: 8.2
* Server OS: Windows
* Game version: Win10

Expected Result:
https://cdn.discordapp.com/attachments/480650036972224513/1278090556156809277/RPReplay_Final1724782701.mov?ex=66cf8a16&is=66ce3896&hm=7890f0a19c765c052c77676dfb6494cda5e5316ea63b9faa3133cfbb670a6fd5&

Actual result:

https://github.com/user-attachments/assets/46fbb675-de26-4910-86f2-8d811a06d9a2

**Comment by nicholass003** [comment]
also BlueIce didnt emit lights since v1.17.10 update
https://minecraft.wiki/w/Bedrock_Edition_1.17.10
