### ISSUE TITLE
canPlaceOn, canDestroy have no effect on clients

### ISSUE THREAD

**Issue by Nerahikada** [pmmp/PocketMine-MP#6460]
### Issue description

- Expected result: Using `Item::setCanPlaceOn()`, `Item::setCanDestroy()` should be able to change the item's behavior
- Actual result: These changes are not reflected on the client and nothing happens

This issue is caused by this code:
https://github.com/pmmp/PocketMine-MP/blob/0a7cbdd56df893c1778b72ca0bd452555ccf7c4d/src/network/mcpe/convert/TypeConverter.php#L226

### Steps to reproduce the issue
1. Create an item and give it to the player
```php
$item = VanillaItems::IRON_HOE();
$item->setCanDestroy(["minecraft:grass_block"]);
$player->getInventory()->addItem($item);
```

### OS and versions
* PocketMine-MP: 5.19.0

**Comment by dktapps** [comment]
See https://github.com/pmmp/PocketMine-MP/pull/6461#issuecomment-2495983517
