### ISSUE TITLE
Garbage Collection Cycle Count Increases on Player Disconnect

### ISSUE THREAD

**Issue by kostamax27** [pmmp/PocketMine-MP#6484]
### Issue description

- Expected result: Running `/gc` in the console should show `Cycles: 0` after a player disconnects.
- Actual result: Running `/gc` shows `Cycles: 38` after a player disconnects.

This issue is caused by this code:
https://github.com/pmmp/PocketMine-MP/blob/b3b8aaddffe3b3a1eee8dcc62dd08fcd10581916/src/inventory/ArmorInventory.php#L45

### Steps to reproduce the issue
1. Join the game.
2. Quit the game.
3. Use `/gc` in the console to check the garbage collection cycle count.

### OS and versions

* PocketMine-MP: [5.21.0](https://github.com/pmmp/PocketMine-MP/releases/tag/5.21.0)

### Plugins
Plugins (0):

- If you remove all plugins, does the issue still occur? **Yes**

**Comment by dktapps** [comment]
Yeah, we had problems like this before with DelegateInventory. It needs to use a weakref to reference $this.

**Comment by ShockedPlot7560** [comment]
Right, the slot validator is a new feature, thanks !
