### ISSUE TITLE
Underwater TNT texture does not match

### ISSUE THREAD

**Issue by nicholass003** [pmmp/PocketMine-MP#6494]
### Issue description

Underwater TNT textures are incompatible since v1.21.40
As of 1.21.30 they are working fine

- Expected result: Underwater TNT must use its own texture
- Actual result: Underwater TNT uses the normal TNT texture

### Steps to reproduce the issue
1. Join server with PM version 5.20.0 - latest (which supports v1.21.40)
2. Give or search Underwater TNT in inventory

### OS and versions

* PocketMine-MP: 5.20.0 - 5.21.0
* PHP: 8.2.17
* Using JIT: no 
* Server OS: win
* Game version: Win10

### Plugins

- If you remove all plugins, does the issue still occur? : Yes
- If the issue is **not** reproducible without plugins:
  - Have you asked for help on our forums before creating an issue? : Yes
  - Can you provide sample, *minimal* reproducing code for the issue? If so, paste it in the bottom section

### Crashdump, backtrace or other files

![Screenshot 2024-11-11 085826](https://github.com/user-attachments/assets/5df001bc-ef52-4e94-befb-74bc07fd2ee1)
![Screenshot 2024-11-11 090330](https://github.com/user-attachments/assets/90807f2c-e717-432b-b731-346d47eca88e)

**Comment by dktapps** [comment]
Please check this in vanilla

**Comment by nicholass003** [comment]
> Please check this in vanilla

Alrighht it's vanilla issue (tested on BDS v1.21.44.01)
![Screenshot 2024-11-12 214858](https://github.com/user-attachments/assets/f1b61039-9aff-4d7b-90e2-cf4202ec1272)

**Comment by dktapps** [comment]
Please report it on bugs.mojang.com

**Comment by dktapps** [comment]
Fixed by d11cf1e59209e30c54c47a9863f8c09e40256be4
