### ISSUE TITLE
lcg_value() is deprecated in PHP 8.4

### ISSUE THREAD

**Issue by AkmalFairuz** [pmmp/PocketMine-MP#6521]
## Description
lcg_value() is deprecated in PHP 8.4. I wanted to make a PR about this, but I see that the replacement is (new Randomizer())->getFloat(...), so maybe we need another replacement (maybe create a `Utils::getRandomFloat()`?).

`Deprecated: Function lcg_value() is deprecated since 8.4, use \Random\Randomizer::getFloat() instead in phar:///tmp/PocketMine-MP-phar-cache.0/PMMPiq4ekripkj4b26HJHGV.tar/src/world/World.php on line 2004`

**Comment by dktapps** [comment]
`mt_rand() / mt_getrandmax()` should be fine
