### ISSUE TITLE
"Locating Server" infinite screen 

### ISSUE THREAD

**Issue by reizonmods** [pmmp/PocketMine-MP#6535]
It gets stuck on the 'Locating Server' screen for over 30 minutes without loading. I call it 'infinite loading' since it never progresses. Interestingly, some friends can play without issues, while I and three others experience this bug. Note that I'm using the original Minecraft from Google Play Store. Thinking it might be the issue, I tried the pirated version, but it didn't resolve the problem. I've reverted to the original, and the error persists.
![Screenshot_20241125_112634_Minecraft](https://github.com/user-attachments/assets/2557aeae-80c0-485f-810c-6ae93adae422)

**Comment by dadodasyra** [comment]
You shall use issue templates and for good reason, you're throwing you're issue without any of both soft and hardware informations.
no console, just nothing

**Comment by dktapps** [comment]
⚠️ This issue ticket doesn't have all the required information ⚠️ 
To make it as quick and easy as possible for maintainers to fix your problem, an issue template is provided which lists certain required information. This includes (but is not limited to):

- PocketMine-MP version (use the `version` command)
- PHP version
- Minecraft version and/or edition
- List of all plugins used (use the `plugins` command)
- **Most importantly, clear steps to reproduce the problem.**

Without this information, your problem cannot begin to be investigated, so the issue will be closed. You may amend this one, or create a new one, providing all the required information using one of the provided [issue templates](https://github.com/pmmp/PocketMine-MP/issues/new/choose).

Help us to help you by providing the information we ask for.
