### ISSUE TITLE
Campfire sound glitch

### ISSUE THREAD

**Issue by portfolec** [pmmp/PocketMine-MP#6566]
### Issue Description

The campfire block is generating an excessive number of overlapping sounds recursively. This overwhelms the audio system, making it impossible to hear surrounding sounds, which are quickly drowned out or silenced.

### Steps to Reproduce

1. Place one or more campfire blocks in the world.  
2. Wait for the campfire sounds to play.  
3. Attempt to play or listen to any other sounds in the environment.  

### Observed Behavior

- A large number of campfire sounds are played simultaneously, creating a "glitchy" audio experience.  
- Surrounding sounds become inaudible due to the overwhelming volume and number of campfire sounds.  

### Expected Behavior

- The campfire should play its ambient sound at a reasonable and consistent level without recursively increasing.  
- Surrounding sounds should remain audible and unaffected by the campfire sound effect.

**Comment by dktapps** [comment]
⚠️ This issue ticket doesn't have all the required information ⚠️ 
To make it as quick and easy as possible for maintainers to fix your problem, an issue template is provided which lists certain required information. This includes (but is not limited to):

- PocketMine-MP version (use the `version` command)
- PHP version
- Minecraft version and/or edition
- List of all plugins used (use the `plugins` command)
- **Most importantly, clear steps to reproduce the problem.**

Without this information, your problem cannot begin to be investigated, so the issue will be closed. You may amend this one, or create a new one, providing all the required information using one of the provided [issue templates](https://github.com/pmmp/PocketMine-MP/issues/new/choose).

Help us to help you by providing the information we ask for.
