### ISSUE TITLE
Start.sh doesn't work when php is installed via homebrew 

### ISSUE THREAD

**Issue by edalzell** [pmmp/PocketMine-MP#66]
### Issue description
If you have php7 installed via homebrew, start.sh cannot find it automatically and returns "no php found"

### Steps to reproduce the issue

1. Install php7 via homebrew
2. Run start.sh

### OS and versions

* PocketMine-MP: 1.6dev
* PHP: 7.0.11
* Server OS: macOS 10.12.1
* Game version: PE

**Comment by robske110** [comment]
start.sh is not designed to use system php

**Comment by pillose** [comment]
copy php7 binary on "./bin/php7/bin"

**Comment by pillose** [comment]
copy php7 binary on "./bin/php7/bin"

**Comment by Intyre** [comment]
PHP7 from homebrew doesn't have the needed modules.
```
[PHP Modules]
bcmath
calendar
Core
ctype
curl
date
filter
ftp
gd
gmp
hash
json
mbstring
mcrypt
mysqli
mysqlnd
pcntl
pcre
Phar
posix
pthreads
Reflection
shmop
sockets
SPL
sqlite3
standard
tokenizer
Weakref
yaml
Zend OPcache
zip
zlib

[Zend Modules]
Zend OPcache
```

**Comment by edalzell** [comment]
Works fine for me actually. Just had to add pthreads and all is good. But, the start.sh won't pick up, had to send it in via `-p`

**Comment by edalzell** [comment]
[This PR](https://github.com/pmmp/PocketMine-MP/pull/67/commits/daed82612ca524d9df40de9eb8780d43fa5668b8) fixes my problem.

Sweet.
