### ISSUE TITLE
16.0 not working 

### ISSUE THREAD

**Issue by MCITGAMER11** [pmmp/PocketMine-MP#68]
Hi!
I tried the 16.0 phar and the servee was working.In MCPE, it was shown 16.0 in the server info but when i tapped it , it was saying Outdated Server.
How can it be outdated?
I have 16.0 And the server also has 16.0.
I dont have the beta of 16.0.
I have the real 16.0 Version of MCPE.
Please fix this and reply that how should I solve this problem.

**Comment by dktapps** [comment]
THIS IS NOT A SUPPORT FORUM. Please stop treating it as one.
