### ISSUE TITLE
Tests failing as of 0.16 PR #42 (dc07fc4)

### ISSUE THREAD

**Issue by jhead** [pmmp/PocketMine-MP#69]
After merging #42 (dc07fc4), Jenkins builds are failing during `PocketMine-MP Test`. Because of this, no 0.16-compatible builds are available yet.

I figured an issue to track the status of this block would be helpful. If not, feel free to close.

**Comment by dktapps** [comment]
Thanks for the report, but we're already aware of the problem. It's an issue with the preprocessor since some method signatures were changed in this update. Working on a fix currently.

**Comment by xDidntPot** [comment]
69th issue! Nice!
