### ISSUE TITLE
Not an issue: How to automate updates to a repo server

### ISSUE THREAD

**Issue by rivermigue** [pmmp/PocketMine-MP#71]
Hello,

So, I have this script which was properly working with another build of Pocketmine, however this time I'm not sure how to get it to work in order to download the latest successful build from the jenkins server since the file that is being downloaded has a different series of combinations between letters and numbers.

Here is the script:

```
#!/bin/bash
function jsonValue() {
  KEY=$1
  num=$2
  awk -F"[,:}]" '{for(i=1;i<=NF;i++){if($i~/'$KEY'\042/){print $(i+1)}}}' | tr -d '"' | sed -n ${num}p
}
RLS=`curl -sX GET https://jenkins.pmmp.gq/job/PocketMine-MP/api/json | jsonValue number 1`
cd /var/www/html/jar
wget https://jenkins.pmmp.gq/job/PocketMine-MP/lastSuccessfulBuild/artifact/PocketMine-MP_1.6.1dev-$RLS_f50c63a0_API-2.1.0..phar -O pocketmine.phar
chown -R nobody:nobody pocketmine.phar
```

So, after the build number on the file's name, on each new build there are extra letters/numbers that are not included in the json file, how can I tweak this in order to automate my repo server to dowload each successful build and rename it to just pocketmine.phar so that I can download it on my other nodes whenever someone deploys a new instance of pocketmine?

This script will only grab the build number.

**Comment by dktapps** [comment]
This is not a support forum. Please use the [forums](forums.pocketmine.net) for questions.

**Comment by dktapps** [comment]
I'd recommend downloading an artifacts zip and unpack it to retrieve a phar instead, less messing about that way.
