### ISSUE TITLE
Can i convert world from minecraft PE to pocketMine?

### ISSUE THREAD

**Issue by LestaD** [pmmp/PocketMine-MP#74]
I have good world on my minecraft, now i want to run it under pocketmine

**Comment by dktapps** [comment]
This is not a support forum, if you continue to treat it as one you will be banned.

**Comment by LestaD** [comment]
@dktapps Seriously? Good support! *sarcasm*

**Comment by dktapps** [comment]
https://forums.pocketmine.net
