### ISSUE TITLE
Src

### ISSUE THREAD

**Issue by DarkEtch** [pmmp/PocketMine-MP#76]
![screenshot_2016-11-04-05-00-55](https://cloud.githubusercontent.com/assets/23136453/19994171/b743f052-a24b-11e6-8308-4668d4e174c2.png)

**Comment by KnownUnown** [comment]
This isn't an issue with PMMP. Please use a prebuilt version.

**Comment by DarkEtch** [comment]
Were is the prebuilt version

**Comment by KnownUnown** [comment]
This isn't a support forum, tell the developer of the app to use the packaged version of PocketMine-MP found on Jenkins.

**Comment by DarkEtch** [comment]
Were is it then

**Comment by Leo3418** [comment]
There is no any prebuilt version yet. The issue tracker is not a proper place for Q&As. Also, please do not report issues unrelated to vanilla PocketMine-MP.

**Comment by DarkEtch** [comment]
Okayyy its understood

**Comment by Muqsit** [comment]
Close it. It is NOT an issue. You are basically just downloading the .zip file and using it. Check the the src of this project. It has linked 'raklib' and 'spl' directories. These don't get downloaded or compressed in the .zip file. Better git.

**Comment by dktapps** [comment]
https://jenkins.pmmp.gq
