### ISSUE TITLE
New Items/Blocks

### ISSUE THREAD

**Issue by Misteboss** [pmmp/PocketMine-MP#810]
When new blocks or items will be added, cause some like potions need to be added cause it's very useful for servers for PvP

**Comment by jasonwynn10** [comment]
Never ask for ETAs we can't give info on anything. add them yourself if you want them sooner and make a PR. It might not be recommended right now thought due to a massive rewrite currently in progress

**Comment by Misteboss** [comment]
OK thanks.

**Comment by SuperMaXAleX** [comment]
@Misteboss ferme l'issue
