### ISSUE TITLE
setScale() nametag height issue.

### ISSUE THREAD

**Issue by Muqsit** [pmmp/PocketMine-MP#819]
### Issue description

Using setScale() set's the entity's nametag very high.
![sx](https://cloud.githubusercontent.com/assets/15074389/24953042/8a94581c-1f82-11e7-9dc8-bf6f1acb56bf.JPG)

### Steps to reproduce the issue

Code executed:
```
//class extending Creature
protected function initEntity(){
    parent::initEntity();
    $this->setNameTagVisible(true);
    $this->setNameTagAlwaysVisible(true);
    $this->setMaxHealth(400);
    $this->setHealth(400);
    $this->setNameTag(TextFormat::BOLD.TextFormat::YELLOW.'Cute Slime');
    $this->setScale(6.5);
}
```

### OS and versions

* PocketMine-MP: 172d733
* PHP: 7.0.17
* Server OS: Ubuntu 14.04 64-bit
* Game version: Win10

### Crashdump, backtrace or other files

-=-

**Comment by jasonwynn10** [comment]
That would be due to the bounding box changes

**Comment by dktapps** [comment]
hmm, I also noticed that players' POV doesn't change when setting scale... not sure why, probably related.

**Comment by Muqsit** [comment]
Yeah; but for the most part, the function works fine.
There are two ways to deal with entity scaling.
**1.** $this->setDataProperty(self::DATA_SCALE, self::DATA_TYPE_FLOAT, _float_);
**2.** $this->setScale(_float_);

Both the functions do the same thing except the second function calls the first function and also updates the bounding boxes of the entity. It could be a bounding box issue, or not. It did exist well before the bounding box issue.

1st function: The height of the nametag would be 2 - 3 blocks above the entity.
2nd function: The height of the nametag would be well over 40 blocks above the entity.

**Comment by jasonwynn10** [comment]
The nametag didn't move positions when setting the scale as a property. The perspective of it's location only changed because the player looks smaller. The second function, however, i believe to be because of the bounding box change.

**Comment by dktapps** [comment]
OH SHIT

**Comment by dktapps** [comment]
@jasonwynn10 yes, since the default isn't stored.

Setting entity scale to 0.5 when it was previously 2.0 will result in all lengths being multiplied by 0.25, which is correct.

**Comment by IrishPacks** [comment]
As far as I'm aware, add-ons that change player scale don't modify the player's POV.

**Comment by jasonwynn10** [comment]
Is there even a way to change where the player's POV is looking from? as in, can the view be moved to the feet of the player? If so, that same method may be able to be used in scaling

**Comment by IrishPacks** [comment]
You'd think the developer's wouldn't hardcode the POV, but alas it seems as if they did.

**Comment by AppleDevelops** [comment]
I noticed that it doesn't modify the items that the player holds, I have no idea if this affects vanilla too.

**Comment by jasonwynn10** [comment]
Yea, the player's held item is always at the same location no matter what scale it's set to

**Comment by thebigsmileXD** [comment]
The item and nametag issue both happen on pe too for me.
