### ISSUE TITLE
Setting player's pitch not working

### ISSUE THREAD

**Issue by mad-hon** [pmmp/PocketMine-MP#821]
### Issue description
Setting player's position ignores whatever is supplied as pitch and resets player's pitch to 0.

### Steps to reproduce the issue
$player->teleport(new Vector3($x, $y, $z), 0, 45);

This should set player's pitch to look 45 degrees down but it does not.

Via some trial and error I discovered that adding the pitch float value once more into the move player packet makes this work:

```
	public function encode(){
		$this->reset();
		$this->putEntityRuntimeId($this->eid);
		$this->putVector3f($this->x, $this->y, $this->z);
		$this->putLFloat($this->pitch);
		$this->putLFloat($this->yaw);
		$this->putLFloat($this->bodyYaw); //TODO
		$this->putLFloat($this->pitch); // <---- Added to make PMMP able to set player's pitch
		$this->putByte($this->mode);
		$this->putBool($this->onGround);
	}

```

Not sure though that this is 100% correct.
I suggest you verify what exactly has changed in the protocol, and then update the MovePlayerPosition class accordingly.

**Comment by SuperMaXAleX** [comment]
I can confirm. I have the same problem when I'm doing this.

**Comment by dktapps** [comment]
That encoding is incorrect. I'm sorry, but we don't do guesswork. I can say for 100% certain that there is no extra float in MovePlayerPacket. It's more likely that you accidentally hit the MODE_ROTATION movement type. The current encoding is correct.

**Comment by dktapps** [comment]
iTXTech/Genisys#1997

**Comment by Driesboy** [comment]
can not be found

**Comment by mad-hon** [comment]
Well, but when I tried to use the current encoding, I was not able to change the player's pitch, whatever mode I passed in. I mentioned that I am not sure my fix is correct, but it was the only way I actually made it work.

**Comment by mad-hon** [comment]
BTW, don't forget that when you only reverse-engineer communication between Minecraft PE client and server, you don't actually get a functional packet where server would be setting the player's pitch, so how can you be sure there's no extra float expected in such case?

**Comment by dktapps** [comment]
> It's more likely that you accidentally hit the MODE_ROTATION movement type. The current encoding is correct.

We know far more about MCPE internals than you give us credit for.

**Comment by mad-hon** [comment]
Well, that's good then! I was actually hoping that you do have access to more info.
But how do you explain that setting mode to rotation does not work and adding that extra float actually does work? That for me at least proves that the current encoding is still missing something.

**Comment by dktapps** [comment]
Once again:

> I can say for 100% certain that there is no extra float in MovePlayerPacket.

The encoding is definitely not _missing_ anything. As I said, you've guessed and hit something that works by accident.

**Comment by mad-hon** [comment]
I confirm I guessed and made something work by accident. I have never said otherwise.
The primary reason I was trying that is that something is not right. At least the $player->teleport does not work properly because it ignores the pitch even though it accepts it as parameter.
If the packet encoding is right then the bug is somewhere between the Player::teleport method and the MovePlayerPacket::encode method.
Sorry for guessing wrong where the bug is. Will keep searching...

**Comment by dktapps** [comment]
Not necessarily. The referenced issue in Genisys above also described this same issue. The general consensus was that it is a client-sided bug, however I never got around to putting the effort into finding out why the issue was occurring.

**Comment by mad-hon** [comment]
The fact that I succeeded making the player's pitch change is an indication that it can be solved from within PMMP, regardless of whether it would be a bug fix or workaround.

**Comment by mad-hon** [comment]
Slight progress - it seems the MODE_ROTATION does indeed work, but it is not used anyware.

**Comment by mad-hon** [comment]
OK, I have a workaround that works, but you tell me what's cleaner - sending an extra packet like I do, or just modifying the mode from MODE_NORMAL to MODE_ROTATION ?

`	public function sendPosition(Vector3 $pos, $yaw = null, $pitch = null, $mode = MovePlayerPacket::MODE_NORMAL, array $targets = null){
		$yaw = $yaw === null ? $this->yaw : $yaw;
		$pitch = $pitch === null ? $this->pitch : $pitch;

		$pk = new MovePlayerPacket();
		$pk->eid = $this->getId();
		$pk->x = $pos->x;
		$pk->y = $pos->y + $this->getEyeHeight();
		$pk->z = $pos->z;
		$pk->bodyYaw = $yaw;
		$pk->pitch = $pitch;
		$pk->yaw = $yaw;
		$pk->mode = $mode;

		if($targets !== null){
			$this->server->broadcastPacket($targets, $pk);
		}else{
			$this->dataPacket($pk);
		}
		
		// Workaround for MCPE ignoring pitch in MODE_NORMAL and MODE_RESET modes
		if($pitch){
		  $pk->mode = MovePlayerPacket::MODE_ROTATION;
      if($targets !== null){
        $this->server->broadcastPacket($targets, $pk);
      }else{
        $this->dataPacket($pk);
      }
		}

		$this->newPosition = null;
	}
`

**Comment by mad-hon** [comment]
Hmm, seems like overriding the mode in Player::sendPosition helps to achieve what I need although the behavior indicates it's still not a clear solution...

$pk->mode = ($pitch and ($mode == MovePlayerPacket::MODE_RESET)) ? MovePlayerPacket::MODE_ROTATION : $mode;

**Comment by madecode15** [comment]
@mad-hon You did not succeed. Go decompile MCPE yourself instead of guessing as dktapps said. Also, altering packets like that will cause unexpected client bugs. MiNet's encoding of the packet is virtually the same of how PocketMine does it.

**Comment by Chris-Prime** [comment]
@madecode15 He never said that encoding was incorrect! What's your point of this comment (same goes to my self) ? You're total ignorant and apparently trying to get @dktapps respect by defending his opinion and words. You've hit the ceilings of stupidity! :man_facepalming: 

Don't ban me :laughing:

**Comment by madecode15** [comment]
@Chris-Prime 

I never said the encoding was incorrect. I said altering packets has unintended side effects weather good or bad; for example some time ago not using Mode_Reset during teleports caused weird client side glitches. I could care less about anyone's opinions, although most notably I do admire @PEMapModder contributions to PocketMine.

**Comment by Chris-Prime** [comment]
I should have read what you wrote more carefully. Excuse me, let me delete my post right after you read this.

**Comment by mad-hon** [comment]
Well, I don't have time to decompile and examine MCPE. I thought I was helping as I assumed the main reason @dktapps did not fix this yet was low priority of this issue. Apparently my assumptions were wrong, didn't want to waste anyone's time.
Anyway, it's still helpful to know that server can affect player's pitch, even though there's no guarantee it can be done without breaking something else...

**Comment by TheDiamondYT1** [comment]
Related to https://github.com/pmmp/PocketMine-MP/commit/716efe25492a19e6ba7bd93b3943378fb1532c24?

**Comment by dktapps** [comment]
@TheDiamondYT1 no.

This is indeed a client-sided bug. They actually hacked around this by adding a separate MovePlayerPacket mode, purely for setting the player's pitch. I'm just... wtf.
