### ISSUE TITLE
addTitle() buggy (and solution).

### ISSUE THREAD

**Issue by Muqsit** [pmmp/PocketMine-MP#823]
### Issue description

When sending title to player after you've already sent them a title some time ago, the title glitches.
The following could be the result:
* The subtitle, if set, would still not be shown.
* The player would receive a previously sent subtitle/title.

### Steps to reproduce the issue

1. Send the player a title with a subtitle using Player::addTitle("", "").
2. Wait a few seconds.
3. Send the player another title with a subtitle (make the text different from the first one to spot differences).
4. Watch how they glitch.

### OS and versions

* PocketMine-MP: 7c66af5
* PHP: 7.0.17
* Server OS: Ubuntu 14.04 64-bit
* Game version: Win10

### Crashdump, backtrace or other files

-=-

**Comment by SuperMaXAleX** [comment]
Thanks Max x)

**Comment by dktapps** [comment]
Please create a pull request if you know how to fix the issue.

**Comment by Muqsit** [comment]
This has been fixed in api3/network. Closing..

**Comment by dktapps** [comment]
I meant to squash-merge that PR, but my browser was acting up. There are two commits on the branch head, yours (319763dd935e8c1dd8da5848cfb6b0c504d45601) and the merge commit (40775f5d).
