### ISSUE TITLE
Unable to fire bows while/just after sprinting

### ISSUE THREAD

**Issue by Muqsit** [pmmp/PocketMine-MP#827]
### Issue description

While you are sprinting or have just stopped sprinting, and shoot a bow, the animation does happen but the arrow isn't fired. It's as if the EntityShootBowEvent had been cancelled.

### Steps to reproduce the issue

1. Give yourself bow and arrow(s).
2. Fire the bow while sprinting (yes, firing it will slow you down. Just ignore it slowing you down and fire it).

### OS and versions

* PocketMine-MP: 40775f5
* PHP: 7.0.17
* Server OS: Ubuntu 14.04 64-bit
* Game version: PE and Win10 (tested on both)

### Crashdump, backtrace or other files

-=-

**Comment by AppleDevelops** [comment]
Reproduced

**Comment by dktapps** [comment]
This will be closed automatically when api3/network is merged to master. Leaving this open in case anyone tries to report this as an issue on master.

**Comment by AppleDevelops** [comment]
Also noticed, arrows don't deal knockback.
