### ISSUE TITLE
api3/network sendContents() on null error

### ISSUE THREAD

**Issue by Muqsit** [pmmp/PocketMine-MP#828]
### Issue description

The server triggers an error and crashes when the `chunk-sending.spawn-radius` in `pocketmine.yml` is set to `0`. (See crashdump)
### Steps to reproduce the issue

1. Set `chunk-sending.spawn-radius` in `pocketmine.yml` to `0`.
2. Join the server.

### OS and versions

* PocketMine-MP: f2159c5
* PHP: 7.0.17
* Server OS: Ubuntu 14.04 64-bit
* Game version: Win10 (irrelevant)

### Crashdump, backtrace or other files

* https://pastebin.com/8vqFPJNG
* https://pastebin.com/yyWzjn09

**Comment by dktapps** [comment]
oh geez... the changes on api3/network-mcpe-1.1 are really needed :o

**Comment by dktapps** [comment]
Brief explanation: Player is tangled up with network and the server is attempting to spawn the player before they have completed the login sequence.

**Comment by dktapps** [comment]
Fixed in 080b35bf538b5af7e8c4095a762034bd52156967

**Comment by dktapps** [comment]
Reopened this because the commit fixing the issue had to be reverted.

**Comment by Muqsit** [comment]
@dktapps any reason behind the revert?

**Comment by dktapps** [comment]
@Muqsit the commit fixed this bug, but caused others.
