### ISSUE TITLE
Gamemode text output issue on client

### ISSUE THREAD

**Issue by L3ice** [pmmp/PocketMine-MP#83]
### Issue description

When you change the gamemode of a player via command, it does not show to which gamemode it was changed.

### Steps to reproduce the issue

1. Change gamemode from the server or the client
2. Look at the output on the client

### OS and versions

* PocketMine-MP: https://github.com/pmmp/PocketMine-MP/commit/557257baed69b8d77e8188ca133f611c8453ab60
* PHP: 7
* Server OS: Windows 10
* Game version: Win 10 & PE

### Crashdump, backtrace or other files

*![upload](https://cloud.githubusercontent.com/assets/5413827/20038271/bcca0944-a430-11e6-9a24-7a99ac54bb05.png)

**Comment by Sandertv** [comment]
I can confirm this.

**Comment by iPocket** [comment]
"Non-Image content-type returned"
Reupload?

**Comment by Awzaw** [comment]
this can be fixed by setting force-language to true in pocketmine.yml

**Comment by L3ice** [comment]
But using the language files from pocketmine is not a good solution if u have clients with different languages
