### ISSUE TITLE
Spam

### ISSUE THREAD

**Issue by HackzModZ** [pmmp/PocketMine-MP#833]
### Steps to reproduce the issue

1. ...
2. ...

### OS and versions

* PocketMine-MP:
* PHP:
* Server OS:
* Game version: PE/Win10 (delete as appropriate)

### Crashdump, backtrace or other files

* ...

**Comment by SOF3** [comment]
User @HackzModZ has been blocked due to spamming 3 issues in a minute as detected by SOFe's issue watcher

**Comment by dktapps** [comment]
s/The truth/Opinionated spam
