### ISSUE TITLE
Spawning a Human entity with an invalid skin causes the server to always crash when joining the world

### ISSUE THREAD

**Issue by ImKyd** [pmmp/PocketMine-MP#835]
I created nbt and forgotten to setSkin 
and now server crashing with error
[17:32:51] [Server thread/CRITICAL]: InvalidStateException: "Human must have a valid skin set" (EXCEPTION) in "/src/pocketmine/entity/Human" at line 474
[17:32:51] [Server thread/EMERGENCY]: An unrecoverable error has occurred and the server has crashed. Creating a crash dump
[17:32:51] [Server thread/EMERGENCY]: Please upload the "C:\Users\me\Desktop\TestServer\crashdumps/Sun_Apr_16

**Comment by dktapps** [comment]
This is a plugin issue. If you create a non-player human entity without a skin, this exception will be raised.

**Comment by ImKyd** [comment]
Is possible to fix it without deleting world?

**Comment by dktapps** [comment]
You should be able to use an NBT editor to remove the invalid entity.

**Comment by ImKyd** [comment]
Ok, I have tried NBT Editors,but I have here only this
![image](https://cloud.githubusercontent.com/assets/26284839/25066320/e7fd2860-2222-11e7-8941-dd63d0624f91.png)
What I must edit? I think there is not something with amount of entities etc

**Comment by jasonwynn10** [comment]
Shouldn't the core prevent the entity from being saved in the first place?

**Comment by dktapps** [comment]
This exception should be thrown when actually _constructing_ the entity, not when trying to spawn it. Currently the entity is perfectly "valid" and will be loaded and saved despite the fact it has no skin. The crash will be triggered when the server attempts to spawn the bad entity _to_ a player.

**Comment by Smarticles101** [comment]
I'm working on a solution for this following what @dktapps said

**Comment by dktapps** [comment]
The referenced pull request resolves this issue, the issue will be closed automatically when changes are merged to master. Leaving this open in case anyone encounters the same issue with other branches.
