### ISSUE TITLE
Not support Pocketmine Linux php files simplexml_load_file()

### ISSUE THREAD

**Issue by andris155** [pmmp/PocketMine-MP#837]
### Issue description

Not support Pocketmine Linux php files simplexml_load_file()

### Steps to reproduce the issue

1. Install PocketMine php files
2. Install MineMarketPE plugin
3. Plugin write errors. :(

### OS and versions

* PocketMine-MP: https://github.com/pmmp/PocketMine-MP/commits/master
* PHP: 7.0.18
* Server OS: ubuntu 16.04 64 bit
* Game version: PE/Win10 (delete as appropriate)

### Crashdump, backtrace or other files

`29.05 00:00:12 [Server] Server thread/CRITICAL Could not execute task MineMarket\ScheduleTask: Call to undefined function MineMarket\simplexml_load_file()`

**Comment by dktapps** [comment]
Your PHP binary is missing the SimpleXML extension required for this function.

**Comment by SOF3** [comment]
Actually a plugin issue.
