### ISSUE TITLE
Outdated Server

### ISSUE THREAD

**Issue by benstr** [pmmp/PocketMine-MP#841]
### Issue description
Unable to join the server. 
```
Could not connect: Outdated server!
```

### OS and versions
Tried a fresh install:
```
This server is running PocketMine-MP 1.6.2dev-43 「Unleashed」 implementing API version 3.0.0-ALPHA4 for Minecraft: PE v1.0.4.11 (protocol version 102)
```

Also tried the latest Jenkins build:
```
This server is running PocketMine-MP 1.6.2dev 「Unleashed」 implementing API version 3.0.0-ALPHA3 for Minecraft: PE v1.0.4.0 beta (protocol version 101)
```

**Comment by AppleDevelops** [comment]
Spam

**Comment by KnownUnown** [comment]
Assuming you're using Minecraft: PE 1.0.6, the changes required for that version aren't yet on the master branch. If you want to try stuff out, you can use the `api3/network` branch. Jenkins doesn't build phars from that branch, so you can grab one [here](https://poggit.pmmp.io/r/3874/PocketMine-MP.phar).

**Comment by benstr** [comment]
Spam?! haha I don't get how my issue is spam. I'm trying to setup a home server for my kids.

The clients are on Minecraft PE v1.0.4. The server is a Mac Mini running OSX server. I follow the documentation and get to the point where clients cannot connect to the Sever.

**Comment by iPocket** [comment]
If you need help, please go to the main forums linked on the README.

**Comment by HimbeersaftLP** [comment]
Uhmmm, it is indeed spam, see the reason below:

>Spam?! haha I don't get how my issue is spam. I'm trying to setup a home server for my kids.
>
>The clients are on Minecraft PE v1.0.4. The server is a Mac Mini running OSX server. I follow the >documentation and get to the point where clients cannot connect to the Sever.

⬇️⬇️⬇️

>Assuming you're using Minecraft: PE 1.0.6, the changes required for that version aren't yet on the master branch. If you want to try stuff out, you can use the api3/network branch. Jenkins doesn't build phars from that branch, so you can grab one here.
