### ISSUE TITLE
api3/network-mcpe-1.1 errors with texture shadings

### ISSUE THREAD

**Issue by wsngamerz** [pmmp/PocketMine-MP#843]
### Issue description
As you can see from the image below, i have gotton alot of texture issues with a fresh install of pmmp. Just wanted to let you guys know.
![screenshot_20170417-143228](https://cloud.githubusercontent.com/assets/15077095/25090469/421fae7c-237b-11e7-94d5-7a867891b3ce.png)

**Comment by Sandertv** [comment]
PocketMine isn't to blame for texture issues. Blame Mojang I'd say.

**Comment by dktapps** [comment]
This is a client-sided issue with chunk replacement. It has been reported to Mojang.

**Comment by wsngamerz** [comment]
but this issue only occurs on the pmmp server

**Comment by dktapps** [comment]
MiNET also has these issues with rendering.

As for the black grass, that is due to a very basic sky light implementation. Previously to 1.1 sky light was not rendered like this by the game. I'm already aware of this problem and am working on a fix.

**Comment by wsngamerz** [comment]
Ah okay, thanks

**Comment by dktapps** [comment]
Previously-generated terrain will still be affected by the lighting problems, but as of commit dab73d8 the lighting problems should be resolved. The rendering glitches however will not.
