### ISSUE TITLE
Entity eye height offset causing entity movement bugs

### ISSUE THREAD

**Issue by dktapps** [pmmp/PocketMine-MP#848]
### Issue description
https://forums.pmmp.io/members/sandertv.16/#profile-post-2213

I've been meaning to fix this for about 8 months now...

Simply removing the eye height fixes such bugs, but also causes TNT to behave very strangely. As I recall, this is something to do with the fact TNT coordinates are taken from the centre, not from the base.

**Comment by dktapps** [comment]
Removed this eye-height offset on mcpe-1.1 branch, but the aforementioned issue with TNT is still present for reasons I do not understand.

**Comment by thebigsmileXD** [comment]
https://github.com/pmmp/PocketMine-MP/blob/mcpe-1.1/src/pocketmine/entity/PrimedTNT.php#L111

This looks promising for tnt. Removing this line makes it corrct client side, but wrong on the server side

**Comment by Muqsit** [comment]
Yeah, not just the TNT coordinates, but also the falling sand. If you were to spawn falling sand, half of it would be submerged into the floor.

**Comment by dktapps** [comment]
The centre-coordinates issue also seems to target items, I think this causes the bug described in #271

**Comment by dktapps** [comment]
This has been fixed for the 1.1 update and will be closed when the changes are merged to master.
