### ISSUE TITLE
Item duplication in creative mode

### ISSUE THREAD

**Issue by L3ice** [pmmp/PocketMine-MP#85]
### Issue description

You can duplicate a stack of item if you move it around in the inventory.
Only happens in creative mode.

### Steps to reproduce the issue

1. Get yourself a type of item in creative mode
2. Open the inventory
3. Move it to the second slot in the inventory
4. Move it back to the first slot
5. Close inventory
6. Disconnect from the server
7. Connect again
8. Look at your inventory

### OS and versions

* PocketMine-MP: https://github.com/pmmp/PocketMine-MP/commit/1ac74fe5bc0bc9e5d8add5f00e8d197f701a0528
* PHP: 7
* Server OS: Windows 10
* Game version: PE

### Crashdump, backtrace or other files

* ![Image of MCPE](https://lh3.googleusercontent.com/cFE7clonNtOfjiagpfwEN-aE-xvsB4X2RdVjRDR6qF4ctS2c8D2levJRzxBYl0Y4djl3eCuSh1OTAOlOiFcN-iDnT8IgKBKZcV5nVVVvGn7pdOs6rf2A2cmMrok35ETszxgy-uiibhvoHeHtmWGklJo3EKhJZ-9zslrlXhHdpm8sAnoAaSwbbzbQXmGBgBKnRd534IfR61g9dd4p8gUF_fEu54tADr4A2MkqlAz6_X2p19d4PbVulEJYxTsJzZr0pJL4ZZp1CSQ0z5NqLqvW15E_GH2UNpp3CEpvdh-b2Z2A4xyeTaOdb2TRg55s9I9cO2HeBmK_dEXMj1AtasBHeC6wuaQKIEubA670WPKVsTku3WAqk7i8B463vl_HTu8kKnjEcY-_hf4TfLEQRTXflu-YIDXxJ1VyhVfrr2eXG2SUC6JjK_TkKzVVKosr4AnvSJOncbMwAjWBVZHswHs3GDt61S4pH4P2LOTcJXyssJch3W-az0Z-At4Pv2qP3yGfQ_IaqavcMoyaU9Z1rPoroWgE-j0mR1s-LECHO5-3fDuctn7yZvERcD7bHG3O0AQG_vts0cCydgzP5mi8YWw-CRoZg-Gl9Sti6nwcuFxzvTrjK8-2=w1684-h948-no)

**Comment by dktapps** [comment]
In creative mode, this isn't an issue since you have infinite items anyway, merely a cosmetic problem. This will therefore be closed, however rest assured that this bug and others related to inventory will be fixed in an upcoming inventory rewrite.

**Comment by L3ice** [comment]
No problem, as long if you start with the inventory rewrite soon :)

**Comment by dktapps** [comment]
Soon™
