### ISSUE TITLE
Players in spectator mode can shoot bows

### ISSUE THREAD

**Issue by dktapps** [pmmp/PocketMine-MP#852]
### Issue description
^^^

### Steps to reproduce the issue

1. get bow and arrows
2. switch to spectator mode
3. shoot somebody

### OS and versions

* PocketMine-MP: 957a8db
* PHP: 7.0.18
* Server OS: w10
* Game version: not relevant, core issue

**Comment by ralphblogz** [comment]
Hehehe, no one can find the one who's shooting. LoL

**Comment by dktapps** [comment]
Fixed in MCPE 1.2 inventory changes.
