### ISSUE TITLE
Not able to sprint in Creative when hungry

### ISSUE THREAD

**Issue by HimbeersaftLP** [pmmp/PocketMine-MP#860]
### Issue description

When you are too hungry to sprint (in survival mode) and switch to creative, you still can't sprint (player stops sprinting a few ticks after starting to sprint).

Expected: I'm able to sprint like in Vanilla
Actual result: I'm not able to sprint

### Steps to reproduce the issue

1. Get hungry in survival
2. Switch to creative mode
3. Try to sprint

### OS and versions

* PocketMine-MP: Branch: api3/network; Git commit: 6ece57e23e7af7680e0bf201dad4ff91101bfff3
* PHP: 7.0.3
* Server OS: Debian Jessie
* Game version: PE

### Crashdump, backtrace or other files

* Demonstration video: https://youtu.be/ttOY1QQ2Fqg

**Comment by dktapps** [comment]
Yeah, I noticed this bug yesterday, forgot to fix it though.

**Comment by dktapps** [comment]
This is a pain in the butt to fix cleanly due to the Player/Human mess. Humans don't have a gamemode, but the food ticking is done there. If only Player wasn't such a mess of networking stuff that split wouldn't be necessary. >_<

**Comment by dktapps** [comment]
You actually don't even need to be in survival, just sprint-fly some distance in creative >_<
