### ISSUE TITLE
Hunger can not be cancelled in entityregainhealth event

### ISSUE THREAD

**Issue by ImKyd** [pmmp/PocketMine-MP#862]
Hunger can not be cancelled using EntityRegainHealthEvent when you cancell it unsetting hunger

**Comment by dktapps** [comment]
Without knowing your PocketMine-MP version, OS, PHP, Client version, or plugins and how the issue occurred, the issue cannot begin to be solved.
A pre-formatted template is provided that shows the required information to begin to find, test and solve an issue.
Until the adequate template and information is provided, the issue will be closed; it may be reopened if you update the ticket with the correct template and required information.

[Contribution guidelines](https://github.com/pmmp/PocketMine-MP/blob/master/CONTRIBUTING.md)

**Comment by ImKyd** [comment]
Now is it correct?

**Comment by dktapps** [comment]
You need to use PlayerExhaustEvent for controlling food point loss, EntityRegainHealthEvent is an unrelated event.
