### ISSUE TITLE
PHP 7 does not load libraries

### ISSUE THREAD

**Issue by Rickytornadus** [pmmp/PocketMine-MP#867]
Good morning.
I'm installing Pocketmine-Mp for the first time on a Windows Server 2016 64x.
After downloading the PHAR file from the Jenkins portal and the PHP 7 binaries for Windows from your Binatry page, I started the Start.cmd file
However, instead of appearing on the initial configuration screen, I found the error in the image.
Can you solve this problem?
If you need more information about the error you can also contact me.

Image of the error:
![errore php](https://cloud.githubusercontent.com/assets/18429412/25360844/38cbd7e4-294b-11e7-946c-99e0d94196f4.jpg)

**Comment by TheDiamondYT1** [comment]
Not a PocketMine issue.

**Comment by Intyre** [comment]
https://support.microsoft.com/en-us/search?query=api-ms-win-crt-runtime-l1-1-0.dll
