### ISSUE TITLE
Fast Hunger (Sprint)

### ISSUE THREAD

**Issue by kaitododoyt** [pmmp/PocketMine-MP#868]
### Issue description
Creative Hunger is fixed, but when a player sprint, the hunger bar is reduced faster

### Steps to reproduce the issue
Run in Survival

### OS and versions
* PocketMine-MP: 1.6.2dev #0 [Protocol 107; API 3.0.0-ALPHA5]
* PHP: 7.0.3
* Server OS: WINNT, win
* Game version: PE/Win10

### Crashdump, backtrace or other files

**Comment by TheDiamondYT1** [comment]
Its supposed to.

**Comment by kaitododoyt** [comment]
Yes, but is very fast in contrast with vanilla

**Comment by dktapps** [comment]
Incorrect. If you compare to vanilla MCPE in the same difficulty you'll observe that they are actually roughly the same.
