### ISSUE TITLE
What is PMMP's Email?

### ISSUE THREAD

**Issue by infinity-pe** [pmmp/PocketMine-MP#869]
I don't know where to ask this, I cannot find a email-address for PMMP.
What is PMMP's Email? I want to ask why I got banned on the PMMP Forum, I cannot even read the reason!

Sorry if this really doesn't fit here, but I don't know any other place where to ask this.

**Comment by TheDiamondYT1** [comment]
Here is the email for @dktapps

https://github.com/pmmp/PocketMine-MP/commit/716efe25492a19e6ba7bd93b3943378fb1532c24.patch

**Comment by SOF3** [comment]
Please do not use the issue tracker for anything not related to the project.
Nor should such issues be responded to, otherwise it's a form of encouragement for such questions.
Users who abuse the issue tracker may be blocked from the organization.
