### ISSUE TITLE
I can't start up the server/program.

### ISSUE THREAD

**Issue by ActivistLime02** [pmmp/PocketMine-MP#870]
### Issue description 
(first time using github so sorry if i fill in things wrong) If i open it it will close it self. Maybe this video will help https://youtu.be/z-0NgBQ2Tw4

### Steps to reproduce the issue

1. Open file
2. Click start

### OS and versions

* PocketMine-MP: Can't open it
* PHP: Sorry don't know
* Server OS: My PC is windows 10 (dutch)
* Game version: On my ipad is MCPE 1.0.7 If thats what you mean

### Crashdump, backtrace or other files

* Will this help? [PocketMine-MP.zip](https://github.com/pmmp/PocketMine-MP/files/966007/PocketMine-MP.zip)

**Comment by SOF3** [comment]
Please use [forums](https://forums.pmmp.io) for support.
