### ISSUE TITLE
Call to null->getAttribute()

### ISSUE THREAD

**Issue by Misteboss** [pmmp/PocketMine-MP#871]
### Issue description

1. ... Run your server
2. ... I don't know why but my server crash

### OS and versions

* PocketMine-MP: Last of master branch
* PHP: 7.0.2
* Server OS: Debian
* Game version: PE/Win10 1.0.7

### Crashdump, backtrace or other files

* ... 
![capture d ecran 2017-04-29 a 22 03 54](https://cloud.githubusercontent.com/assets/17687222/25558481/de693072-2d27-11e7-852e-2067e85e5c2d.png)

**Comment by dktapps** [comment]
Do you have any crashdump?

**Comment by vzlomka76** [comment]
Do you have any plugins?

**Comment by Misteboss** [comment]
wait i am going to make him crashing again

**Comment by Misteboss** [comment]
![capture d ecran 2017-04-29 a 22 00 11](https://cloud.githubusercontent.com/assets/17687222/25558446/3e0ffb9c-2d27-11e7-80c4-d941081eeb6a.png)

**Comment by dktapps** [comment]
@Misteboss If you can reproduce this issue, please enable debug output and paste a stack trace.

**Comment by Misteboss** [comment]
This is the first error (second post) then, when i reboot the second error happens it's the first screen

**Comment by Misteboss** [comment]
got it !
![capture d ecran 2017-04-29 a 22 03 54](https://cloud.githubusercontent.com/assets/17687222/25558471/c68d8d36-2d27-11e7-8a46-48bcc2d10936.png)

**Comment by dktapps** [comment]
There is no call like that on l92. https://github.com/pmmp/PocketMine-MP/blob/master/src/pocketmine/entity/Human.php#L92

**Comment by Misteboss** [comment]
Fail xd cause for me it's `public function getFood() : float{
		return $this->attributeMap->getAttribute(Attribute::HUNGER)->getValue();
	}`

**Comment by dktapps** [comment]
This stack trace does not match up to current master code. Please update and try to reproduce this on latest master source.

**Comment by Misteboss** [comment]
Ooohhh.. Sorry i am using the api3\network branch

**Comment by Misteboss** [comment]
This is why but it's an issue

**Comment by dktapps** [comment]
The stack trace also doesn't match api3/network.

**Comment by Misteboss** [comment]
Maybe cause my IDE reformat it

**Comment by dktapps** [comment]
> Please update and try to reproduce this on latest master source.

**Comment by Misteboss** [comment]
hmm ok

**Comment by Misteboss** [comment]
but this an issue x)

**Comment by SuperMaXAleX** [comment]
Mais t'es stupide ou quoi ? Il y a une MAJ en rapport avec ça, je crois que tu vas te faire taper

**Comment by thebigsmileXD** [comment]
I want to add: applying effects to non-living classes will keep spamming could not tick level. Effects should be calculated for Living entities anyways.

For this crash: @Misteboss > wait i am going to make him crashing again

Could you tell us how you crash it exactly?

**Comment by ImagicalGamer** [comment]
Adding effects to players that haven't spawned in yet can also throw this error.

**Comment by dktapps** [comment]
Yea, ref #828 similar issue. Need to split Player entity and networking. Working on that on nuclear-mess but it's a long way from done yet. Network stuff is taking a back seat at the moment so I can catch up on some gameplay stuff.
