### ISSUE TITLE
Language keys that match mcpe language keys display incorrectly

### ISSUE THREAD

**Issue by TheDiamondYT1** [pmmp/PocketMine-MP#872]
### Issue Description
Language strings thar match the same key as in mcpe display incorrectly to the client.

### Reproduce
Ive realised that language keys in the pocketmine language file that match the same keys as the mcpe language files display incorrectly in chat, but correctly in console.
https://github.com/pmmp/PocketMine-Language/blob/master/eng.ini#L146

*Try running '/op' and the error message will be incorrect*

However if the language key DOESNT match mcpe then it displays correctly.
https://github.com/pmmp/PocketMine-Language/blob/master/eng.ini#L286

*Try running '/transferserver' and the message will be correct.*

**Comment by dktapps** [comment]
#236

**Comment by TheDiamondYT1** [comment]
@dktapps I didnt see that because i just searched the issues for "language".
