### ISSUE TITLE
Why everytime the console throw: Player x moved wrongly!

### ISSUE THREAD

**Issue by SoyPro** [pmmp/PocketMine-MP#873]
### Issue description

 The console everytime throw Player x moved wrongly!, i desactivated the allow-flight check in server.properties, but still happen, my server is host on a pc(windows 10 64 bits).what i have to do, edit the player.php?, sorry for my bad english, im spanish.

### Steps to reproduce the issue

1. ... Everytime the console throw player x moved wrongly, i have been found solutions, but i dont know how to do it
2. ...

### OS and versions

* PocketMine-MP: PocketMine-MP 1.6.2 dev-63, api 3.0.0-ALPHA5 for minecraft pe v1.0.7.0
* PHP: 7.0.3
* Server OS: Windows 10
* Game version: Mcpe v1.0.7.0- (android for play)

### Crashdump, backtrace or other files

* ...

**Comment by AppleDevelops** [comment]
The repo isn't for support, ask for support on forums.pmmp.io, this will be considered spam.

**Comment by SOF3** [comment]
#119

**Comment by corytortoise** [comment]
It might not seem like it, but this issue is probably because of #169. The server thinks players aren't colliding with blocks correctly because of faulty bounding boxes.

**Comment by xinghao2003** [comment]
In pocketmine.yml set allow-movement to true

**Comment by SoyPro** [comment]
i saw pocketmine.yml, but i dont found allow-movement.

**Comment by Driesboy** [comment]
remove your pocketmine.yml 
restart your server
stop your server
open the pocketmine.yml
go to anticheat and allow-movementcheats to false

**Comment by xinghao2003** [comment]
original is false , just set it true, because it say do you allow the movement cheat, if true means allow, server will not check player movement, the message will also wont appear in the console
