### ISSUE TITLE
So there is an ingame issue with the inventory where when you take something and place it in one of the inventory slots (not the hot bar) and then try put it somewhere else it will duplicate and after a short time (30sec-2min) it will go back same with when your trying to craft something or smelt something it all duplicated and glitches back into the spot it was originally in the inventory (I am on MCPE iOS version MCPE 1.0.7 and iPhone ) Pleease fix this

### ISSUE THREAD

**Issue by Yologamer1084** [pmmp/PocketMine-MP#875]
### Steps to reproduce the issue

1. ...
2. ...

### OS and versions

* PocketMine-MP:
* PHP:
* Server OS:
* Game version: PE/Win10 (delete as appropriate)

### Crashdump, backtrace or other files

* ...

**Comment by Yologamer1084** [comment]
To reproduce this take a block and place it in your inventory slots anywhere and then move it it will duplicate and then glitch back (same with furnace and crafting table)

**Comment by Yologamer1084** [comment]
I'm also new so I didn't fully understand how to file an issue next issue is being properly done

**Comment by TheDiamondYT1** [comment]
Please, use a short but descriptive title and don't make multiple issues for the same thing
