### ISSUE TITLE
Server inventory issues / lag / code gitch 

### ISSUE THREAD

**Issue by Yologamer1084** [pmmp/PocketMine-MP#877]
### Issue description

 The blocks in the inventory glitch and teleport around the place and then you cannot use your inventory or the crafting table or furnace or chest.

### Steps to reproduce the issue

1. Place a block type in your inventory.
2. Then move it around and you will see that they will duplicate and glitch around.
3. Try craft something or smelt something and things will also likely duplicate & then glitch around.

### OS and versions

* PocketMine-MP: ?
* PHP: ?
* Server OS: ?
* Game version: MCPE 1.0.2-1.0.7

### Crashdump, backtrace or other files

* ...

**Comment by Yologamer1084** [comment]
What are all the things that have a '?'beside them , what do they mean and how do you find them out?

**Comment by dktapps** [comment]
Without knowing your PocketMine-MP version, OS, PHP, Client version, or plugins and how the issue occurred, the issue cannot begin to be solved.
A pre-formatted template is provided that shows the required information to begin to find, test and solve an issue.
Until the adequate template and information is provided, the issue will be closed; it may be reopened if you update the ticket with the correct template and required information.

[Contribution guidelines](https://github.com/pmmp/PocketMine-MP/blob/master/CONTRIBUTING.md)
