### ISSUE TITLE
freeze on command

### ISSUE THREAD

**Issue by TDMidkwhatisxd** [pmmp/PocketMine-MP#88]
Its not only /register, and i wanna ask if PmmP fixed it!
If u do show more on timings u can see other commands lag too a little!
If u spam commands it freeze!
I wanted to ask if PmmP have this problem , thats all ! Please look more before closing and issue!

Idc if i ever get banned! Is just another project "© by Dktapps" , so all are bound to get banned sooner or later!

**Comment by SOF3** [comment]
You were using Elywing.

> I wanted to ask if PmmP have this problem ,

Thank you for your benevolence so concerned about a software you aren't using, but no thanks. If you don't even know if an issue is happening, you shouldn't even report it ~~(and continue using your stable no-bugs Elywing)~~.

Action shall be taken the next time a similar issue is opened.

**Comment by SOF3** [comment]
Moreover, from your timings report, all commands that pmmp provides (/tell, /say, /status) take less than 3 ms to execute. Only commands from your plugins take a long time to execute. Therefore this is a plugin issue.

![image](https://cloud.githubusercontent.com/assets/19623715/20035386/46c86afa-a41d-11e6-9467-7b082ab12ff0.png)
