### ISSUE TITLE
setBlock does not create/remove tiles

### ISSUE THREAD

**Issue by thebigsmileXD** [pmmp/PocketMine-MP#880]
### Issue description

For several reasons i've experienced plugin using setBlock, but forgetting to create/remove a tile for e.g. chests.
So, there are invisible tile blocks after a rejoin, which can be quite annoying

The other scenario: A plugin uses setblock, but doesn't remove the tile. when another tile is placed at the same position, it contains the same data as the old one.
For example you can setBlock a monsterspawner where a chest was, and then you hav a chest displayed inside a monster spawner.

Giving the server the option to remove this would also reduce some load (ticked tiles) and memory on levels, and Level::getTiles() would no longer return invalid tiles.

When setting a TileBlock, a tile could be created using the default compound (previousely getSpawnCompound)

### Steps to reproduce the issue

1. setblock a chest
2. ur setblock air where a chest was

### OS and versions

* PocketMine-MP: https://jenkins.pmmp.io/view/All/job/PocketMine-MP/lastSuccessfulBuild/artifact/PocketMine-MP_1.6.2dev-65_6d90f91b_API-3.0.0-ALPHA5.phar
* PHP: 7.0.1
* Server OS: Windows Server 2012

**Comment by robske110** [comment]
btw you can't link a static artifact name on lastSuccessfulBuild @thebigsmileXD

**Comment by thebigsmileXD** [comment]
Why not, the vrsion is fully stated behind it.

**Comment by thebigsmileXD** [comment]
Bump: Is this actually a TODO, or should users better create tiles themself via the new, easier tile function?

**Comment by dktapps** [comment]
ideally plugin developers shouldn't need to know that "tiles" or "block entities" are even a thing - they should just be blocks with special behaviour. So yes, this is a TODO.
