### ISSUE TITLE
Placing flowers or tall grass causes them to appear like half blocks

### ISSUE THREAD

**Issue by madecode15** [pmmp/PocketMine-MP#882]
### Issue description
When you place tall flowers or tall grass they will appear as a half block on the bottom and invisible on the top (put your finger on it and you can see the white outline)

Expected result: What were you expecting to happen? Tall grass & flowers to be placed like vanilla.
Actual result: What actually happened? They get placed as half blocks.

### Steps to reproduce the issue
1. Place tall grass or any tall flower.
2. Watch it appear as a halfblock.

### OS and versions
* PocketMine-MP: https://github.com/pmmp/PocketMine-MP/commit/f889bf9cf56ea8284fefa55c3011fc4b66591ef6 (This bug has effected PocketMine since 0.10.5)
* PHP: 7.0.3
* Server OS: Linux
* Game version: PE/Win10 (irrelevant)

**Comment by dktapps** [comment]
Double plants aren't implemented yet.

**Comment by jasonwynn10** [comment]
https://github.com/PocketMine/PocketMine-MP/pull/3565

**Comment by dktapps** [comment]
@jasonwynn10 that's pretty much useless, it only adds growth for bonemeal. That doesn't solve this issue.

**Comment by jasonwynn10** [comment]
Do you mean terrain generation?

**Comment by dktapps** [comment]
???

> Placing flowers or tall grass causes them to appear like half blocks

what does generation have to do with it?

**Comment by PMMPFTW** [comment]
Someone did create a pull request for this on the main repo.
https://github.com/PocketMine/PocketMine-MP/pull/3953

**Comment by TheDiamondYT1** [comment]
@dktapps Does `Status: Pending` mean the fix is waiting to be merged to master?
