### ISSUE TITLE
RakLib blocks Player

### ISSUE THREAD

**Issue by McpeBooster** [pmmp/PocketMine-MP#884]
Whenever I try to join my Pocketmine server, a message that the server blocked me comes and the server kicks me ... as you can see in the photo. Previously, everything worked ... also other pmmp server running over my VServer I and other players can not enter anymore ... 
I have no plugins on the server.

* PocketMine-MP:
* PHP:
* Debian 8 minimal:
* Game version: PE/Win10

![unbenannt](https://cloud.githubusercontent.com/assets/22411285/25638094/86eeaea0-2f87-11e7-8f76-db0ebab0d212.PNG)

**Comment by dktapps** [comment]
Without knowing your PocketMine-MP version, OS, PHP, Client version, or plugins and how the issue occurred, the issue cannot begin to be solved.
A pre-formatted template is provided that shows the required information to begin to find, test and solve an issue.
Until the adequate template and information is provided, the issue will be closed; it may be reopened if you update the ticket with the correct template and required information.

[Contribution guidelines](https://github.com/pmmp/PocketMine-MP/blob/master/CONTRIBUTING.md)

**Comment by ZizzyZizzy** [comment]
I've seen that error before. It was caused by an outdated RakLib. Use the one here in this repo:
https://github.com/pmmp/RakLib

Also, why are you on such an antiquated version of PHP? Update to PHP 7 for best performance.

**Comment by McpeBooster** [comment]
@ZizzyZizzy can you tell me how exactly I update the RakLib

**Comment by TheDiamondYT1** [comment]
@McpeBooster PocketMine shouldnt even work with PHP 5, check PocketMine.php. its not possible.

**Comment by ZizzyZizzy** [comment]
@McpeBooster 
The person with the automated build script where you source your .phar needs to ensure they are grabbing the correct PMMP source .zip file and RakLib .zip from the pmmp repo. They should know what to do with it after that. 

Hint: it goes into the source tree:
`rsync -ax RakLib-master/ PocketMine-MP-master/src/raklib/`
