### ISSUE TITLE
Effects can be given to non-Living classes

### ISSUE THREAD

**Issue by thebigsmileXD** [pmmp/PocketMine-MP#886]
### Issue description

Effects can be given to non-Living.php classes like: Items, Arrows, FallingSand and cause the Level to freeze
Only Living classes are actually _tickable_ by effects in vanilla (Mobs + Human)

### Steps to reproduce the issue

1. Apply an effect to a mentioned type above
2. Could not tick level, getAmplifier/Effect/id on null (varies)

### OS and versions

* PocketMine-MP: https://jenkins.pmmp.io/view/All/job/PocketMine-MP/69/artifact/PocketMine-MP_1.6.2dev-69_966e4bf8_API-3.0.0-ALPHA5.phar
* PHP: 7.0.1

### Crashdump, backtrace or other files

* Later, really busy at work right now

**Comment by dktapps** [comment]
tl;dr: entities are a confusing inconsistent mess. Same thing applies with attributes.

**Comment by thebigsmileXD** [comment]
https://giphy.com/gifs/perfect-read-didnt-gGh4I6osbjyRa

**Comment by jasonwynn10** [comment]
Shouldn't arrows be able to have effects? or is it just the particles that follow them?

**Comment by dktapps** [comment]
@jasonwynn10 no, tipped arrows have metadata for potion particles.

**Comment by mal0ne-23** [comment]
doesnt pocketmine ignore spammed packets of the player moving or something like that? Maybe the server doesnt see that the player has physcially moved yet due to that and ignores the teleport, am i making sense?

**Comment by Muqsit** [comment]
I don't know if this would be a valid fix but eh..
```php
class Projectile extends Entity {
    public function addEffect(Effect $effect){
        throw new \Error("really...");
    }
}
```

**Comment by thebigsmileXD** [comment]
its not just projectiles, tnt etc too. the addeffect in entity class just needs a instance of living check.

**Comment by mal0ne-23** [comment]
> Or maybe just move the function from Entity to Living and everything will be alright.

I think this is a valid fix, why check if the entity is living, just put it in the Living class and no extra checks need to be done.

**Comment by thebigsmileXD** [comment]
True and good idea.
