### ISSUE TITLE
"Unable to connect to server"

### ISSUE THREAD

**Issue by NickTehUnicorn** [pmmp/PocketMine-MP#888]
### PocketMine is running, I'm getting the unable to connect to server error.

So I'm new to running a server and as a beginner, I'm having problems.
Basically I run PocketMine on my win10 PC, the console thingie looks great and I've set everything up. When I go to **Minecraft: Windows 10 Edition** (from the same device) and press my server that pops up on LAN Games, it gives me an "**Unable to connect to server**" error. I have tried almost every single phar I've heard but right now I have **Tessaract 1.2.1**. There's no crashdump file.

Can someone help?

---
### OS and versions
* PocketMine-MP: 1.6.2 dev
* PHP: 7
* Server OS: Windows 10
* Game version: Win10

**Comment by dktapps** [comment]
If I had a good enough facepalm gif I would totally post it right now.

From the README.md in the root of the repository:
> [Setup, help & support, FAQs](https://github.com/pmmp/PocketMine-MP#setup-help--support-faqs)
**Please do not use our issue tracker for support requests.**

From the issue template:
> NO support whatsoever will be provided for forks or spoons of PocketMine. Issues relating to non-official distributions will be closed as spam. Please send such issues to whoever is responsible for the fork or spoon you are using.

**Comment by HimbeersaftLP** [comment]
@dktapps Here we go:
![](http://www.gifbin.com/bin/062010/1275389857_naked-gun-facepalm.gif)

**Comment by TheDiamondYT1** [comment]
@dktapps Also note he said he is currently using Tesseract

**Comment by dktapps** [comment]
why can't I react to posts with facepalm emojis... 🤦‍♂️

**Comment by thebigsmileXD** [comment]
Seeing 2 Boxes?

**Comment by NFGamerMC** [comment]
Not very bright, if you are using Tesseract you shouldn't be here.

**Comment by dktapps** [comment]
@NFGamerMC Speaking of "not bright"... stop spamming me with spoon organisation invitations.
