### ISSUE TITLE
enchanted bow with infinity does not function as expected.

### ISSUE THREAD

**Issue by dsclassen** [pmmp/PocketMine-MP#889]
### Issue description

I gave an enchanted bow to a player with the following command:
`give user bow 1 {display:{Name:"§r§6§lEPIC BOW"},durability:1,ench:[{id:19s,lvl:5s},{id:22s,lvl:1s},{id:20s,lvl:2s},{id:21s,lvl:1s}]}`

### If you are reporting a regression or unexpected behaviour, please include the below information:
Expected result: enchanted bow would be able to shoot an infinite number of arrows
Actual result: After shooting the single arrow in the players inventory they were not able to shoot aother arrow.

### Steps to reproduce the issue

1. give user an enchanted bow `give user bow 1 {display:{Name:"§r§6§lEPIC BOW"},durability:1,ench:[{id:22s,lvl:1s}]}`
2. give user an arrow `give user arrow 1`
3. have user shoot arrow
4. now the user can't shoot anymore arrows.

### OS and versions

* PocketMine-MP: This server is running PocketMine-MP 1.6.2dev ãUnleashedã implementing API version 3.0.0-ALPHA5 for Minecraft: PE v1.0.7.0 (protocol version 107)
* PHP: PHP 7.0.6 (cli) (built: May 19 2016 22:56:30) ( ZTS DEBUG )
Copyright (c) 1997-2016 The PHP Group
Zend Engine v3.0.0, Copyright (c) 1998-2016 Zend Technologies
    with Zend OPcache v7.0.6-dev, Copyright (c) 1999-2016, by Zend Technologies
* Server OS: CentOS Linux release 7.3.1611 (Core) 
* Game version: iOS v1.0.7

**Comment by MCPEPIG** [comment]
Enchants aren't yet implemented.

**Comment by thebigsmileXD** [comment]
@MCPEPIG well.. Protection is /lol

**Comment by dktapps** [comment]
@thebigsmileXD no, it is registered, but not implemented. Closing in favour of #414
