### ISSUE TITLE
i think PmmP devs should read this!

### ISSUE THREAD

**Issue by TDMidkwhatisxd** [pmmp/PocketMine-MP#89]
-Delleted issue about ServerAuth-
And whats more , spamming it in chat , cause console errors, showing u timings in process , was crazy!
(I told some players, if they can to spam with �)
-PmmP devs read from this point
Last issue affect all forks and even PmmP, spamming with that unknown symbol cause console gliches!

Tested on linux!

**Comment by archie426** [comment]
Isn't this a plugin?

**Comment by TDMidkwhatisxd** [comment]
Ya, read last issue, is not by plugin!

**Comment by archie426** [comment]
@TDMidkwhatisxd So you are spamming the repo?

**Comment by TDMidkwhatisxd** [comment]
No? Please read all what i write, ok i will edit the issue!

**Comment by TDMidkwhatisxd** [comment]
Ok i edited, now read!

**Comment by TDMidkwhatisxd** [comment]
Oh ha sorry, was becouse of command tracker, but it increase loads anyway, that unknown symbol!
Sorry again!

**Comment by SOF3** [comment]
Such issues are anti-hacks issues, and should be fixed with plugins, not the server software.

**Comment by TDMidkwhatisxd** [comment]
This is why i closed, sorry!

But @SOF3 , @dktapps  , a server software should have the basic anti-hack ! If not is just a resource for "spoons"!

**Comment by SOF3** [comment]
A server should only provide what it takes to be a server. Others are extensions and should be done through plugins. not everyone wants antihacks.
