### ISSUE TITLE
Players can fall up to 5 blocks without taking any damage

### ISSUE THREAD

**Issue by dktapps** [pmmp/PocketMine-MP#891]
In vanilla, you take 1/2 heart of damage for every block fallen above 3 blocks. In PocketMine-MP, this appears to be 5. I don't understand why this is a problem, since the logic for fall damage appears correct, but it appears that the fall calculation is always less than the actual distance by 2 blocks.

### Steps to reproduce the issue

- build a stack of something 4-5 blocks tall and jump off the top
- /tp ~ ~5 ~ in survival

### OS and versions

* PocketMine-MP: c4f461f65d71efc0b5e0ca00c49e3c4b97c57757
* PHP: 7.0.18
* Server OS: w10
* Game version: PE/Win10

**Comment by dktapps** [comment]
This is partly due to a hacky `checkGroundState()` override for Players which checks a whole block beneath the player to see if they are on the ground.

**Comment by jasonwynn10** [comment]
possibe cause? https://github.com/pmmp/PocketMine-MP/blob/adbb53929e8b01e4f0c63afde392a54a5bc8b70a/src/pocketmine/entity/Entity.php#L1168

**Comment by diamond-gold** [comment]
Maybe use PlayerFallPacket?

**Comment by dktapps** [comment]
Using PlayerFallPacket would allow hacked clients to cheat their way out of taking fall damage. I don't know why Mojang added it, but it's not a sensible solution. This is a core bug which hasn't yet been isolated.
