### ISSUE TITLE
Blocks/Items 'multiply' when putting into chests

### ISSUE THREAD

**Issue by winterbuild7074** [pmmp/PocketMine-MP#892]
### Issue description

I have the same problem as this: https://github.com/PocketMine/PocketMine-MP/issues/2541
I have 5 Iron Ingots, for example. Now I open a chest put some of the Iron Ingots inside – and take them out again. Now I do this again and again: put some iron in the chest, and out again. Now the glitch is, that suddenly the blocks/items multiply – I take items/blocks out of my inventory; the items I took out are now inside the chest; in my inventory, the items I took out, come back again (example: I took out 10 irons of my inventory and they now appear inside the chest. I look back at my inventory, and those 10 irons didn't disappear at all, they are still inside my inventory. Now I can get out those 10 irons inside the chest, and I got 20 irons now). It sounds very glitchy and soon after a few minutes I got 3 stacks of Iron Ingots.
Please fix this, it's really a bad glitch and people can easily multiply their things on my server.

If you are reporting a regression or unexpected behaviour, please include the below information:
Expected result: That it won't multiply
Actual result: The items multiplied extremely.

### Steps to reproduce the issue

I can't really say when it happens. But suddenly the items get more and more until I reach 3 stacks.
1. I open a chest (or anything else that is "openable")
2. I put some of the items inside that chest
3. I take them out again
4. Do step 2 and 3 a few times
5. Items should multiply and get more and more

### OS and versions

* PocketMine-MP: 1.6.2dev Unleashed
* PHP: 7.0.3 (I guess)
* Server OS: VPS Control, Debian 8.0 + MCPE Server
* Game version: PE v1.0.7.0

### Crashdump, backtrace or other files

No errors or crashdumps or console messages.

**Comment by thebigsmileXD** [comment]
Confirming, tried to state that out before.

**Comment by dktapps** [comment]
This will be resolved in 1.1.1 when the new transaction system is implemented into MCPE (inventory in PocketMine-MP will be rewritten).

**Comment by Muqsit** [comment]
was about to say that^
3m late.

**Comment by infinity-pe** [comment]
But I need to fix this soon! Or players can easily multiply their things and that's "cheating" on my game.
Plus, sometimes a chest never gets empty.

**Comment by dktapps** [comment]
Should you shut up and stop complaining and acting as if we owe you something? Yes you certainly should.

I don't care what issues this causes on your server. You don't contribute anything to PocketMine-MP or its developers, therefore you are not priority.

Once again, PocketMine-MP is free software, and its developers work for free. Nobody is going to prioritize your issue just because you're self-centred.

**Comment by jasonwynn10** [comment]
@infinity-pe are you sure that the items are not just a visual glitch? can the be crafted with or thrown?

**Comment by infinity-pe** [comment]
But is there nothing I can do? If yes, what next? I shall accept and be happy that players cheated a lot? And wait until 1.1.1? OK, great, I'll be extremely happy about this...

**Comment by dktapps** [comment]
You can shut up and stop whining because we don't work for you. Nobody cares if you're happy with it or not. Newsflash: the world does not revolve around you.

**Comment by infinity-pe** [comment]
I'm not whining or anything like that. I'm only asking if there's a anything I can do.

**Comment by TheDiamondYT1** [comment]
@infinity-pe You don't need to be rude. As Dylan said above, *PocketMine-MP is free software*. Nobody gets paid (except for the occasional donation so unless you're willing to donate a lot of money then your issue won't be prioritized. 

Even if you did donate money, nobody can promise the bug will be fixed anytime soon. We all have lives. And they shouldn't stop because of you.

**Comment by infinity-pe** [comment]
I'm only asking if there's a way for me to fix this MYSELF.

**Comment by TheDiamondYT1** [comment]
@infinity-pe And that's fine. But you didn't need to include the rest of the issue.

> I shall accept and be happy that players cheated a lot? And wait until 1.1.1? OK, great, I'll be extremely happy about this...

**Comment by dktapps** [comment]
This has been fixed in the inventory changes for MCPE 1.2.
