### ISSUE TITLE
Can not connect to MCPE Server.

### ISSUE THREAD

**Issue by cpdyj** [pmmp/PocketMine-MP#894]
### Issue description
The Server is started but I connect to the port 19132. The connect be refused. Thank you.

### Steps to reproduce the issue

1. adduser mcb
2. use wget to download…
3.run start.sh and setup by the guide.
4.Server is run but I cannot connect

### OS and versions

* PocketMine-MP:1.6.2dev-76 「 Unleashed」  implementing API version 3.0.0-ALPHA5 for Minecraft: PE v1.0.7.0 (protocol version 07)

* PHP:PHP7(I guess)
* Server OS: Ubuntu 17.04(The vultr VPS)
* Game version:

**Comment by KnownUnown** [comment]
Please specify the version of MCPE you're using.

**Comment by cpdyj** [comment]
PocketMine-MP:1.6.2dev-76 「 Unleashed」 implementing API version 3.0.0-ALPHA5 for Minecraft: PE v1.0.7.0 (protocol version 07)

**Comment by cpdyj** [comment]
I use version command in mcpe server.

**Comment by KnownUnown** [comment]
We need the version of the MCPE _client_.
This can be found in the bottom left corner of the game when you first open the app.

**Comment by cpdyj** [comment]
Thank you... It's v 1.0.7 
And I try to connect by telnet but the connect be refused...

**Comment by corytortoise** [comment]
Android, iOS, or Win10?

**Comment by cpdyj** [comment]
The client is runs on Android and the server is runs on Ubuntu

**Comment by KnownUnown** [comment]
Does the server log indicate that the client is connecting at all? Do you get a timeout message in the console?

**Comment by cpdyj** [comment]
Nothing. The log is nothing about that.

**Comment by jasonwynn10** [comment]
Possible failure to portforward. Make a post on the forums at forums.pmmp.io

**Comment by dktapps** [comment]
How many damned times... Please actually READ the README before posting an issue.
