### ISSUE TITLE
Falling blocks get destroyed on grass

### ISSUE THREAD

**Issue by TheDiamondYT1** [pmmp/PocketMine-MP#897]
### Issue description

Falling sand and gravel gets destroyed if it lands on grass. Expected behaviour is the grass gets destroyed.
### Steps to reproduce the issue

1. ... Place some grass
2. ... Place some sand 3 blocks above the grass so it falls

### OS and versions

* PocketMine-MP: https://github.com/pmmp/PocketMine-MP/commit/4bc9e1000b35f76885d1c035cd1de613e68ecad4
* Server OS: Windows
* Game version: PE

**Expected behaviour**
- Mushroom - Destroy sand  
- Sapling - Destroy sand  
- Flower pot - Destroy sand
- Lily pad - Destory sand
- Cactus - Destroy sand
- Torch - Destroy sand
- Tall grass - Destroy sand
- Brewing stand - Destroy sand
- Sign - Destroy sand
- Cake - Destroy sand
- Enchantment table - Destroy sand
- Dragon head - Destroy sand
- Carpet - Destroy sand
- Stairs - Destroy sand

---
  
- Slime block - Nothing happens (i expected it to bounce lol)

---
  
- Cobweb - Sand sinks through it slowly
- Grass - Destoy grass without dropping grass item

##### Tested on MCPE 1.1.0.9

**Comment by dktapps** [comment]
The logic of the falling-block code is poor, this doesn't surprise me in the slightest.

**Comment by dktapps** [comment]
That check probably ought to be for blocks that can be replaced as opposed to whether it's solid or not.

**Comment by thebigsmileXD** [comment]
https://github.com/pmmp/PocketMine-MP/blob/master/src/pocketmine/entity/FallingSand.php#L124
I confirm isSolid is the fault, though tallgrass is not solid. On that line isSolid should be canbeReplaced/canBePlacedInto

**Comment by thebigsmileXD** [comment]
t
