### ISSUE TITLE
Plain world?

### ISSUE THREAD

**Issue by arfianadam** [pmmp/PocketMine-MP#900]
### Issue description
The generated world is too plain. I didn't find any mines or caves. The grass is also scarce. No mobs/entities either. Is it indeed the way it is for now? I played in realms and the generated world is beautiful and so "complex" (caves, mines, mountains, hills, etc).

### Steps to reproduce the issue
1. Install from fresh
2. Start the server
3. Join the server
4. Fly around the chunks

### OS and versions
* PocketMine-MP: 1.6.2dev-76
* PHP: 7.0.3
* Server OS: Ubuntu 16.04.2
* Game version: PE

### Crashdump, backtrace or other files
Nothing

**Comment by dktapps** [comment]
> Not implemented or known issues:
> Please do not report lacking features to the bug tracker, only report bugs on implemented features.
>
> - Entities / Entity AI
> - No conversion for old levels (will be added later)
> - No Minecarts
> - Not all items are implemented
> - Generated worlds use a basic generator

Also:
> pmmp/PocketMine are not affiliated with Mojang. PocketMine-MP is not a Mojang-approved software, nor is it associated with Mojang.

**Comment by arfianadam** [comment]
@dktapps ah, my bad! thank you for the notice. you guys are doing great job!

**Comment by jasonwynn10** [comment]
@arfianadam I would recommend BetterGen by @ad5001 for better world Generation if that's what you're looking for
