### ISSUE TITLE
Cancelling interactevent when tapping doors opens them client side

### ISSUE THREAD

**Issue by thebigsmileXD** [pmmp/PocketMine-MP#906]
### Issue description

I am cancelling the PlayerInteractEvent in all worlds. Doors still open on the clients side, but only for the player who opens it.

### Steps to reproduce the issue

1. Place door
2. Use a plugin that cancels all Interacts
3. Open a door

### OS and versions

* PocketMine-MP: Build 74
* PHP: 7.0.1
* Server OS: Windows
* Game version: PE/Win10 (delete as appropriate)
both
### Crashdump, backtrace or other files

* ...

**Comment by dktapps** [comment]
PocketMine isn't smart enough to resend block updates for both halves of the door.
