### ISSUE TITLE
Raklib out of memory

### ISSUE THREAD

**Issue by thebigsmileXD** [pmmp/PocketMine-MP#907]
### Issue description

-
Might be related to #885 

### Steps to reproduce the issue

1. Running the server

### OS and versions

* PocketMine-MP: Build 76
* PHP: 7.0.1
* Server OS: Windows Server 2012

### Crashdump, backtrace or other files

* https://gist.github.com/thebigsmileXD/a9b0b8db1a8d2b97fcf84f87eacd8b63
![image](https://cloud.githubusercontent.com/assets/8733998/25934998/281482ce-3621-11e7-9feb-7b8c63cbcefe.png)

**Comment by dktapps** [comment]
That's not RakLib out of memory, you can see that from the partial namespace. This isn't so much related to #885 as it is a perfect duplicate it.
