### ISSUE TITLE
PMMP On Multicraft?

### ISSUE THREAD

**Issue by EtchReborn** [pmmp/PocketMine-MP#909]
Well i used the latest PMMP Build and renamed it to Custom-phar.phar to enable other kind of softwares and now it says "get a php from installation website" But how do i get the php and put it into the ftp on multicraft???

**Comment by dktapps** [comment]
Does anyone read the README anymore? This is not a support forum. We are not associated with Multicraft, we do not endorse it and we do not provide support for it. This is not a support forum, but an issue tracker.

**Comment by EtchReborn** [comment]
Thats a issue You need to support Multicraft Or This Software will not be used

**Comment by dktapps** [comment]
**This is not a support forum**. I invite you to read the [README.md](https://github.com/pmmp/PocketMine-MP#setup-help--support-faqs).
