### ISSUE TITLE
Water flow wraps around to the top of the world when falling into the void

### ISSUE THREAD

**Issue by XDqrkneZ** [pmmp/PocketMine-MP#914]
### Issue description

 Hey guys! I just found some crazy bug that needs to be fixed.. so if water fall to void it will spawn back to sky.. i got some photos if you do not understand what i mean..

### Steps to reproduce the issue

1. ... 
2. ...

### OS and versions

* PocketMine-MP: PocketMine-MP 1.6.2dev-76
* PHP: 3.0.0
* Server OS: Minecraft: PE v1.0.7.0 (protocol version 107)
* Game version: PE/Win10 (delete as appropriate)

### Crashdump, backtrace or other files

http://imgur.com/a/jEpyE
http://imgur.com/a/0u4eC
* ...

**Comment by dktapps** [comment]
This is an issue with the Y_MASK bitmask being applied to block hashes for the cache when using Level->getBlock(). Quite a pain in the ass to be truthful.

**Comment by dktapps** [comment]
This is a very widespread problem actually, this is just one amusing bug that results from this problem. Other issues like this include:

- Breaking a block at y=0 triggers block updates at y=255
- Falling out of the world tries to check blocks at the top of the world to see if you're colliding with them

**Comment by XDqrkneZ** [comment]
so its fixed? ...sorry i did not understand any of your comments :(

**Comment by xinghao2003** [comment]
@XDqrkneZ 😂 But i understand 😂

**Comment by XDqrkneZ** [comment]
@xinghao2003 ok does https://github.com/pmmp/PocketMine-MP/issues/915

**Comment by XDqrkneZ** [comment]
@xinghao2003 is it fixed?

**Comment by dktapps** [comment]
@XDqrkneZ as you can see there's a PR referenced with a fix, but there is an issue with the preprocessor which must be resolved before it can be merged.
