### ISSUE TITLE
BlockBreakEvent doesn't works properly 

### ISSUE THREAD

**Issue by FaigerSYS** [pmmp/PocketMine-MP#917]
### Issue description

BlockBreakEvent ingnore isCancelled() in some situations

### Steps to reproduce the issue

1. Cancell PlayerInteractEvent before player breaks block
2. Catch BlockBreakEvent and see that it's not cancelled
3. ...
4. Block not destroyed!

### OS and versions

* PocketMine-MP: dbb8e8a
* PHP: 7.0.16
* Server OS: Ubuntu 14.04 x64
* Game version: 1.0.8 (PE)

**Comment by FaigerSYS** [comment]
This breaking plugin API, because it's expected that the block will be destroyed

**Comment by dktapps** [comment]
If you cancel the interaction event when a player starts breaking a block (left-click), their break timer will not be started, which results in the BlockBreakEvent being set to cancelled before it is called due to the time taken to break the block not being enough. You should not assume that an event is not cancelled simply because your plugin's handler has been called.

**Comment by FaigerSYS** [comment]
@dktapps , maybe you don't understand. Block must be breaked because event not cancelled. This breaks logic of the plugin, because it's expected that block is broken, but it's not. 

> You should not assume that an event is not cancelled simply because your plugin's handler has been called.
What you talking about? You can simply check this using isCancelled() (and MONITOR priority if you want), and it will return false. Break timer must be checked before calling the event, not after that

**Comment by dktapps** [comment]
You didn't read what I said.
> If you cancel the interaction event when a player starts breaking a block (left-click), their break timer will not be started

This causes the block break to be automatically aborted. If you want to change that, you must use `$ev->setInstaBreak()` or find an alternative solution which does not involve cancelling the left-click interaction.

**Comment by SOF3** [comment]
Could you clarify what exactly you mean:

1. Do you explicitly cancel the PlayerInteractEvent? Or you just checked, and is it cancelled or not?
2. Do you explicitly cancel the BlockBreakEvent? Or you just checked, and is it cancelled or not?
3. Is the block finally broken?

**Comment by FaigerSYS** [comment]
1. There I cancelling event
2. There I checking, is event cancelled or not (return fasle, that means that block will be destroyed)
3. No (unexpected result)
