### ISSUE TITLE
Server crashing whenever a player connects.

### ISSUE THREAD

**Issue by ZaneWalter** [pmmp/PocketMine-MP#918]
### Issue description

Server will crash whenever a player tries to connect with the error AddEntityPacket not found.

### Steps to reproduce the issue

Simply try to connect to the server with a  PC generated world. Moments later the server crashes.

### OS and versions

* PocketMine-MP:  1.6.2dev [Protocol 107; API 3.0.0-ALPHA] commit: 576702f
* PHP: 7.0.9
* Server OS: Linux, linux
* Game version: PE 1.0.7 

### Crashdump, backtrace or other files

* https://gist.github.com/ZaneWalter/1f7d78c228b435f8f952c465709804e6

**Comment by dktapps** [comment]
> THIS CRASH WAS CAUSED BY A PLUGIN

**Comment by ZaneWalter** [comment]
Sorry. My bad. I completely didn't saw that.
