### ISSUE TITLE
@SOF3

### ISSUE THREAD

**Issue by thebigsmileXD** [pmmp/PocketMine-MP#92]
### Issue description

SOF3
- locks issues
- ignores help
- acts like a retarded

### Steps to reproduce the issue

1. Write something
2. SOF3 Blocks and acts ignoring

### OS and versions

* PocketMine-MP: *
* PHP: *
* Server OS: *
* Game version: PE/Win10 (delete as appropriate) *

### Crashdump, backtrace or other files

* ...

**Comment by dktapps** [comment]
Is there any need?

**Comment by thebigsmileXD** [comment]
There is, because the way he handles Genisys and PMMP is inaceptable and makes me not use pmmp

**Comment by thebigsmileXD** [comment]
//undo

**Comment by archie426** [comment]
If you have a problem with a brilliant developer, you can leave. Now. (Please excuse me if I haven't interpreted this well)
