### ISSUE TITLE
Player Lagging, And Moved Wrongly When Stepping Into Slabs

### ISSUE THREAD

**Issue by ChaostixZix** [pmmp/PocketMine-MP#923]
Hi.

I Used Ubuntu 16.04 And PocketMine-MP 1.6.2dev Unleashed And I Have 2 Gigs Of Ram On My Vps.

When Player Joined The Server, The TPS Goes Down Into 8TPS And When No One Is On My Server, The Tps Goes Up again To 20TPS

And Whenever The Player Step Into Slab, It Says Player Moved Wrongly, Then It Says Can't Keep Up, Is The Server Overloaded?

When I Use Cmd /status , Total Of The Memory Is Only 100MB, I Tried To Allocate More Memory On Pocketmine.yml But It Doesn't Work

**Comment by Sandertv** [comment]
You could remove movement checking in the pocketmine.yml. The issue of the slab and stair 'player moved wrongly' is caused by wrong bounding (or was it collision?) boxes as far as I'm aware of.

**Comment by dktapps** [comment]
#169
