### ISSUE TITLE
How to build php7 for iOS?

### ISSUE THREAD

**Issue by zxl777** [pmmp/PocketMine-MP#925]
I have a iOS app can run multiplayer for MCPE.  
I want to run the pmmp on my app. So at first there are need php7 bin for iOS. 

I can not found any script to build php7 for iOS. 

Did you know any information about this question?

**Comment by dktapps** [comment]
https://github.com/pmmp/PocketMine-MP#setup-help--support-faqs

> Please do not use our issue tracker for support requests.
