### ISSUE TITLE
Method getHighestBlockAt(x, z) always returns the generator block

### ISSUE THREAD

**Issue by matcracker** [pmmp/PocketMine-MP#927]
### Issue description
Using the `getHighestBlockAt(x, z)` always return the heighest block of level generator.
### Steps to reproduce the issue

1. Generate a level (Default or Flat).
2. Fly over some generated blocks (such as trees or caves)
3. Place a block and fly or jump over.
4. Height will result constant in base of chunk generator

### OS and versions

* PocketMine-MP: [0f174f7
](https://github.com/pmmp/PocketMine-MP/commit/0f174f76050f81909f725aff46a4210d378d0307)
* PHP: 7.0.16
* Server OS: Windows 10
* Game version: PE/Win10 1.0.9/1.0.8

If could be helpful, use this code:
```
public function onPlayerMove(PlayerMoveEvent $event)
{
    $p = $event->getPlayer();
    $to = $event->getTo();
        
    $ground = $p->getLevel()->getHighestBlockAt($to->x, $to->z);
    $p->sendMessage("Ground = " . $ground);
}
```

**Comment by Sandertv** [comment]
I can confirm getHighestBlockAt often does not return what you expect it to return...

**Comment by dktapps** [comment]
This is because the heightmap is never updated. This issue is fixed on the mcpe-1.1 branch.

**Comment by matcracker** [comment]
:+1:

**Comment by SOF3** [comment]
@matcracker Extracted from CONTRIBUTING.md:

![image](https://cloud.githubusercontent.com/assets/19623715/26274762/f79a6e0a-3d83-11e7-8ee7-4115a6f3cfcf.png)

**Comment by gizanopatrica** [comment]
@dktapps In which commit on the mcpe-1.1 branch was this issue fixed?

**Comment by dktapps** [comment]
https://github.com/pmmp/PocketMine-MP/commit/dab73d895099e4c1c7d632711e204971cbbb0590
