### ISSUE TITLE
Create Docker container for easier distribution

### ISSUE THREAD

**Issue by crscheid** [pmmp/PocketMine-MP#928]
### Issue description
PMMP Team: I've created a docker image for PMMP that may be useful to include in the broader distribution. If you think its worth to have as part of the main distribution I can fork and submit a PR.

https://github.com/crscheid/pocketmine-mp

### Steps to reproduce the issue
None

### OS and versions
N/A

### Crashdump, backtrace or other files
N/A

**Comment by crscheid** [comment]
Quick update on this. I published a Docker container which references the prior repository. It is located at: https://hub.docker.com/r/cscheide/pocketmine-mp

**Comment by Roemer** [comment]
Any plans to have an official docker image?

**Comment by dktapps** [comment]
yes, we've been looking at using Docker for linux distributions, because distributing prebuilt PHP for linux is an enormous pain in the ass. I'd forgotten this issue was here.

**Comment by crscheid** [comment]
More than happy to assist if helpful. Mine is not perfect and could probably use some revisions that tie a little better to the release conventions of PMMP. But more than happy to contribute.

**Comment by crscheid** [comment]
Updated my repository to track all versions. Trying to track your releases as quickly as possible: https://github.com/crscheid/pocketmine-mp

Reading up on how best to distribute multi-version Docker images. I've decided to revert to a build script instead and track Dockerfiles by version. Seems like there might be a better approach if integrated with your build process at some point. Food for thought.

**Comment by michaelfavia** [comment]
Using this for a family server. Just wanted to say thank you @crscheid. Makes it much easier for people to install and use.

**Comment by crscheid** [comment]
@michaelfavia Thanks! And thanks a lot for the pull request earlier. Hopefully we can convince the pmmp folks to build it into their formal release here at some point. Until then, I'll keep updating it as best as I can.

**Comment by samysousa** [comment]
This is one of the best docker installs out there for Pocketmine.
The only thing that would make it better in my opinion is to expose some of the missing configuration folders as persistent.

**plugin_data** : Not exposed and so to for configure plugins you need to "shell" into the container when running on a headless environment.

**sever.log** : Not redirected so can't debug properly in headless

As for the rest it`s a question of documentation on configuring different plugins but that is really unrelated to this project.

**Comment by Roemer** [comment]
Just as a side note: There is an official (very good working) alpha of the official server with all features like in the realms available: https://minecraft.net/en-us/download/server/bedrock/
and also docker containers with it (like mine here: https://hub.docker.com/r/roemer/bedrock-server).

**Comment by crscheid** [comment]
Awesome, thanks! I will be tearing down my build then and using this moving forward.

**Comment by SOF3** [comment]
It's not entirely stable yet. Right now it is built on docker hub builder, which suffers from all sorts of concurrency issues. I am going to move the build process back to our Jenkins server soon.

**Comment by crscheid** [comment]
Ok cool, will keep mine in place for the time being then and track the progress. Either way, its a great development that will help keep the builds in sync for Docker users.
