### ISSUE TITLE
Minecraft 0.16.1

### ISSUE THREAD

**Issue by MarwanEA** [pmmp/PocketMine-MP#93]
Hi,
I have server pocketmine of version minecraft 0.15.10 and now i update my version minecraft ,please I want pocketmine-mp for version minecraft 0.16 or up
### OS and versions

* Server OS: android 4.2.2
* Game version: 0.16

**Comment by dktapps** [comment]
https://jenkins.pmmp.gq

https://pmmp.rtfd.io

**Comment by archie426** [comment]
THIS IS NOT A SUPPORT FORUM.

**Comment by dktapps** [comment]
@archie426 Enough.
