### ISSUE TITLE
Cancelling interactevent when tapping craft tables opens craft them client side

### ISSUE THREAD

**Issue by Andrew1481432** [pmmp/PocketMine-MP#934]
### Issue description
I am cancelling the PlayerInteractEvent in all worlds. craft table still open on the clients side, but only for the player who opens it.

### Steps to reproduce the issue
1. Place craft table
2. Use a plugin that cancels all Interacts
3. Open a craft

* PocketMine-MP: api3/network
* PHP: 7.0.18
* Server OS: Debian 8
* Game version: PE/Win10

**Comment by dktapps** [comment]
Crafting GUI is handled client-side, there is nothing the server can do about this.
