### ISSUE TITLE
When anvil falls,it removes stairs

### ISSUE THREAD

**Issue by poustmal** [pmmp/PocketMine-MP#935]
### Steps to reproduce the issue
1.Place an anvil 2-3 blocks high and watch it destroying the stair
2. .Do the same on mcpe vanilla,there is a difference

### OS and versions
-->
* PocketMine-MP:commit 674394c4
* PHP:7.0.3
* Server OS:Android
* Game version: 1.0.8 pe

### Crashdump, backtrace or other files

* ...

**Comment by poustmal** [comment]
Pmmp
![screenshot_2017-05-23-17-43-57](https://cloud.githubusercontent.com/assets/22281205/26369644/f33b8c32-3ffd-11e7-9353-9bccee62e468.png)

**Comment by poustmal** [comment]
Mcpe vanilla
![screenshot_2017-05-23-17-53-41](https://cloud.githubusercontent.com/assets/22281205/26369664/03151010-3ffe-11e7-9a44-51674efbface.png)

**Comment by dktapps** [comment]
related to #897

**Comment by TheDiamondYT1** [comment]
Reproduced.

**Comment by dktapps** [comment]
Nice, they destroy slabs too :O

**Comment by TheDiamondYT1** [comment]
@dktapps Watch out for the killer anvils! They're taking over!!! :O
