### ISSUE TITLE
Arrow rotates in the wrong direction as it reaches a wall

### ISSUE THREAD

**Issue by Hugheth** [pmmp/PocketMine-MP#936]
### Issue description

When you fire an arrow it rotates as it comes close to a wall it rotates to hit the wall at the wrong angle.

http://imgur.com/JZNC5H3

Expected result: The arrow hits the wall at the same angle it is fired at.
Actual result: The arrow rotates at the last minute to align at the wrong orientation, typically the same compass direction whatever direction the wall is facing.

### Steps to reproduce the issue
1. Fire an arrow at a wall with a bow, or use Entity::createEntity to create an arrow
2. The arrow rotates at the last minute to face (typically) the wrong direction as it hits the wall

### OS and versions
* PocketMine-MP: 1.6.2dev "Unleashed" (API 3.0.0-ALPHA5)
* PHP: 7.0.18
* Server OS: MacOS Sierra 10.12.5
* Game version: PE

**Comment by dktapps** [comment]
This issue has already been fixed on a development branch.

**Comment by Hugheth** [comment]
Thanks a lot, which development branch is it on?

**Comment by dktapps** [comment]
`mcpe-1.1`, but as the name suggests, it's for the 1.1 update, not the current 1.0 release builds.
