### ISSUE TITLE
Levers and buttons rotate to odd angles when placed

### ISSUE THREAD

**Issue by Hugheth** [pmmp/PocketMine-MP#937]
### Issue description

Expected result: when you place a lever or button on a wall, it should remain fixed to the wall
Actual result: after a tick or so, the button or level changes orientation, often to the same compass direction.

https://imgur.com/CmNhjkV

### Steps to reproduce the issue
1. Place a lever or button in creative, or open a map from the Java version of Minecraft with buttons/levers on walls
2. The lever or button quickly rotates to an odd orientation

### OS and versions
* PocketMine-MP: 1.6.2dev "Unleashed" (API 3.0.0-ALPHA5)
* PHP: 7.0.18
* Server OS: MacOS Sierra 10.12.5
* Game version: PE

**Comment by dktapps** [comment]
Yes, these (and various other blocks) aren't yet implemented and don't function correctly. Usual policy is to simply leave them out until we're prepared to implement them, but a maintainer broke this rule last year and auto-generated a bunch of classes without adding actual functionality, so a large number of blocks are present that don't work correctly.

Closing this in favour of #336 .

**Comment by smakosav** [comment]
Is it really difficult to solve this problem? (I hope you have already made an idea of how you should do it) :)
