### ISSUE TITLE
Cannot press lever

### ISSUE THREAD

**Issue by Hugheth** [pmmp/PocketMine-MP#938]
### Issue description

Expected result: When you click on a lever (in any game mode?) in pocket edition it should flip
Actual result: it does not

### Steps to reproduce the issue
1. Place a lever in creative
2. On single player, tapping the lever will flip it. When using Pocket Mine it does not

### OS and versions
* PocketMine-MP: 1.6.2dev "Unleashed" (API 3.0.0-ALPHA5)
* PHP: 7.0.18
* Server OS: MacOS Sierra 10.12.5
* Game version: PE

**Comment by dktapps** [comment]
See my comment on #937
