### ISSUE TITLE
0.16 version minecraft

### ISSUE THREAD

**Issue by MarwanEA** [pmmp/PocketMine-MP#94]
Hi again,
Men I don't know how I can download pocketmine.phar and genisys.yml
Please give me direct link

**Comment by archie426** [comment]
You don't need genisys.yml. Can't you do the rest yourself?

**Comment by MarwanEA** [comment]
OK but I can't download pocket mine.phar

**Comment by dsclassen** [comment]
Check the project out from github. It's not rocket science.

**Comment by MarwanEA** [comment]
Oh please help me
Firstly I can't download pocket mine.phat
Secondly my friend can't play with me in my server
.....

**Comment by dktapps** [comment]
This is not a support forum. 

https://forums.pocketmine.net
https://pmmp.rtfd.io
