### ISSUE TITLE
Shrunk players get kicked for flying when moving

### ISSUE THREAD

**Issue by DaPigGuy** [pmmp/PocketMine-MP#943]
### Issue description

Players get kicked for flying when they move if their scale is set lower than 1 (in this case 0.25). They should move around normally.

### Steps to reproduce the issue

1.Set a player's scale below 1
2. Move around

### OS and versions

* PocketMine-MP: Build #748 on Poggit
* PHP: 7.0.3
* Server OS: Windows 10
* Game version: PE

### Crashdump, backtrace or other files

* None

**Comment by dktapps** [comment]
Same root cause as #944
