### ISSUE TITLE
Set Spawn function doesn't change compass orientation

### ISSUE THREAD

**Issue by MCPEPIG** [pmmp/PocketMine-MP#944]
### Issue description

 When you set a player's spawn or send a SetSpawnPositionPacket to a player, the compass orientation doesn't change like it should. 

### Steps to reproduce the issue

1. Get a compass.
2. Use the setSpawn() function.

### OS and versions

* PocketMine-MP: Build #748 on Poggit
* PHP: 7.0.3
* Server OS: Windows 10
* Game version: PE

### Crashdump, backtrace or other files

* None

**Comment by alex2534alex** [comment]
Everything like it should be. Compass​ showing world spawn direction, not player's

**Comment by Muqsit** [comment]
@alex2534alex Nope, look at this.
https://github.com/pmmp/PocketMine-MP/blob/master/src/pocketmine/Player.php#L1180-#L1185

**Comment by alex2534alex** [comment]
Totally forgot about this. Sorry :P

**Comment by thebigsmileXD** [comment]
Could it be that this is a client bug?

**Comment by dktapps** [comment]
it also doesn't update when you sleep in a bed... I think this is indeed a client-sided issue.

**Comment by AppleDevelops** [comment]
Can confirm, it is a client side bug.

**Comment by AppleDevelops** [comment]
I'm quoting the response I got from an MCPE Mod:

> This is* working as intended*. Compasses are supposed to point to the world's spawn point, not and an individual player's spawn point. This makes it so that all players compasses point to the same location.

**Comment by dktapps** [comment]
what?

**Comment by AppleDevelops** [comment]
Here's the link
https://bugs.mojang.com/browse/MCPE-22102

**Comment by dktapps** [comment]
I guess this is "Works as Intended" too then. The wiki does also say this, but it seems counterintuitive...

**Comment by AppleDevelops** [comment]
#BlameShoghi

**Comment by dktapps** [comment]
If that's the case you should in theory be able to spoof it using [this](https://github.com/pmmp/PocketMine-MP/commit/954271b90f07e59be467046bcafa3d826cd2acc7#diff-2d6fda59fbf79fa08f568f8f0a52bdbcR33) if you want to change the compass needle direction for a specific player. It's the first field in the packet. This theory is however untested.

**Comment by MCPEPIG** [comment]
I've tested and it works. I set type as world spawn and set force to true.
