### ISSUE TITLE
Shrunk players can go under 1 block holes but suffocate

### ISSUE THREAD

**Issue by DaPigGuy** [pmmp/PocketMine-MP#945]
### Issue description

If a player is small enough to go through 1 block holes, they suffocate while doing that. What should happen is they will just go through the hole.

### Steps to reproduce the issue

1. Shrink a player to 0.50 or below.
2. Walk through a one block hole.

### OS and versions

* PocketMine-MP: Build #748 on Poggit
* PHP: 7.0.3
* Server OS: Windows 10
* Game version: PE

### Crashdump, backtrace or other files

* None

**Comment by thebigsmileXD** [comment]
did you use setScale? it recalculates bounding box too, which is the main cause for such issues

**Comment by dktapps** [comment]
If using the API, this issue does not occur. I remember fixing a similar issue recently. #484

**Comment by MCPEPIG** [comment]
I'm using setScale(). They can go through the holes but they suffocate from it.

**Comment by dktapps** [comment]
This issue seems to be because PocketMine is recalculating the eye-height to match the scale, but the positions sent by the client are always offset by a fixed 1.62 blocks. >_<

**Comment by Qimie** [comment]
Camt we make the player box thingy be configureable through plugin instead of plugin force the server to do so?
