### ISSUE TITLE
[RakLibServer thread/NOTICE]: Blocked * for 5 seconds

### ISSUE THREAD

**Issue by yerktoyn** [pmmp/PocketMine-MP#953]
### Issue description

This is not a new problem, I have already faced it for a long time. That's why I had to use forks for a while.

### Steps to reproduce the issue
1. Craft something

### OS and versions
* PocketMine-MP: PocketMine-MP 1.6.2dev 「Unleashed」 implementing API version 3.0.0-ALPHA5 for Minecraft: PE v1.0.7.0 (protocol version 107)
* PHP: Latest from bintray
* Server OS: Ubuntu 16.04 (64)

### Crashdump, backtrace or other files

Notice: Undefined offset: 0 in phar:///root/server/PocketMine-MP/PocketMine-MP.phar/src/pocketmine/Player.php on line 2986
[17:07:15] [RakLibServer thread/NOTICE]: Blocked * for 5 seconds

I was trying to put the last RakLib from the repository.

Clean installation of PocketMine using the script pmmp.io

**Comment by yerktoyn** [comment]
I rented the server on Server.pro, they have the same problem with the PocketMine-MP

**Comment by dktapps** [comment]
#45

**Comment by ByxNilsGFX** [comment]
hey i have a problem my server blocked ips for 5 seconds how can i fix this?
