### ISSUE TITLE
Changes to BlockEntityDataPacket behaviour for Signs in v1.1.0.9 beta

### ISSUE THREAD

**Issue by Awzaw** [pmmp/PocketMine-MP#956]
### Description
MCPE 1.1 beta7 sends a BlockEntityDataPacket for every keypress during sign creation, firing multiple **SignChangeEvent**s.  Previously this was only the case when the sign was finalised - now there is no such indication that the user has finished typing, which breaks plugins that require user-generated signs.

### Steps to Reproduce
Install a plugin to listen for **SignChangeEvent**s. Create and place a sign, observe output: SignChangeEvent is fired on each keypress (except 'new line'), but no event is fired when the user closes the window to finalise the sign.

### OS and Versions
* PocketMine-MP: 1.6.2dev "Unleashed" for v1.1.0.9 beta (api/blocks or mcpe-1.1 branches)
* PHP: 7.0.3
* OS: OSX 10.11.6

**Comment by dktapps** [comment]
This behaviour is, I believe, intended. However the lack of ability to tell when the sign text is finalised is considered a bug by Mojang and has been reported as https://bugs.mojang.com/browse/MCPE-22124.

**Comment by Muqsit** [comment]
Mojang back at it again!

**Comment by bettylovedertderrdy** [comment]
genisyspro better !

**Comment by dktapps** [comment]
I'd prefer this remained open, this might be a client issue but it is also an API problem.

**Comment by dktapps** [comment]
I'm going to close this since it is not fixable by a server (this is a client sided issue). I was going to try and do a hack for this based on the ABORT_BREAK action, but it seems the client doesn't send this action when closing the sign UI anymore, so there is pretty much no way this can be solved short of guessing what is happening.
