### ISSUE TITLE
Not running on Raspberry pi 3

### ISSUE THREAD

**Issue by VengeanceVenger** [pmmp/PocketMine-MP#960]
### Issue description

When running `./start.sh` on my Raspberry pi 3 (after using `wget -q -O - https://get.pmmp.io | bash -s` to install. I get this error.

`pi@Pi:~/Server/PMMP $ ./start.sh `
`./start.sh: line 28: type: php: not found`
`Couldn't find a working PHP 7 binary, please use the installer.`
`pi@Pi:~/Server/PMMP $ `

### Steps to reproduce the issue

1. use `wget -q -O - https://get.pmmp.io | bash -s` to install into a directory.
2. start using `./start.sh`
*Note: This must be run on a raspberry pi 3 with latest versions installed.

### OS and versions

* PocketMine-MP: Unknown (probably most current as of Wednesday. 5/31/2017)
* PHP: (Unknown: This is what causes the problems) probably PHP 7 
* Server OS: Latest
* Game version: PE

### Crashdump, backtrace or other files

* None (wont even run)

**Comment by TheDiamondYT1** [comment]
I invite you to read the [README.md](README.md).

> Please do not use our issue tracker for support requests.

If you want help with something, go ask in [the forums](https://forums.pmmp.io).

**Comment by VengeanceVenger** [comment]
I did but it had nothing to help me
I thought that someone might have advice

**Comment by dktapps** [comment]
This is not a support forum.

**Comment by VengeanceVenger** [comment]
thanks anyway

**Comment by jrodr10** [comment]
@VengeanceVenger try apt-get install php7.0 first then run wget -q -O - https://get.pmmp.io | bash -s

**Comment by TheDiamondYT1** [comment]
@jrodr10 

Quote @dktapps
> This is not a support forum.

If he wants help he can easily sign up to the forums. People will use the issue tracker to ask questions if you provide the answer. Therefore, dont provide an answer.
