### ISSUE TITLE
Installing error

### ISSUE THREAD

**Issue by XDqrkneZ** [pmmp/PocketMine-MP#961]
### Steps to reproduce the issue

1. ...
2. ...

### OS and versions

* PocketMine-MP: N/A, I wasn't able to /ver because of the error
* PHP:
* Server OS:
* Game version: PE/Win10 (delete as appropriate)

### Crashdump, backtrace or other files

I am using the stable build on jenkins

root@vps129702:~/test# ./start.sh
./start.sh: line 52: ./bin/php7/bin/php: No such file or directory
To escape the loop, press CTRL+C now. Otherwise, wait 5 seconds for the server to restart.

./start.sh: line 52: ./bin/php7/bin/php: No such file or directory
Restarted 1 times
To escape the loop, press CTRL+C now. Otherwise, wait 5 seconds for the server to restart.

./start.sh: line 52: ./bin/php7/bin/php: No such file or directory
Restarted 2 times
To escape the loop, press CTRL+C now. Otherwise, wait 5 seconds for the server to restart.

* ...

**Comment by dktapps** [comment]
does anyone read the README anymore
