### ISSUE TITLE
Cannot Craft Stone Pickaxe

### ISSUE THREAD

**Issue by markkrueg** [pmmp/PocketMine-MP#963]
### Issue description
It is not possible to craft a stone pickaxe.

Expected result: Proper amount of cobble and sticks are in inventory; stone pickaxe can be tapped to craft it.
Actual result: Stone pickaxe is not highlighted as a crafting item in crafting screen.
-->

### Steps to reproduce the issue
1. Make crafting table
2. Gather 3 cobblestone
3. Gather wood
4. Craft 2 sticks
5. Enter crafting interface by tapping crafting table
6. Stone Pickaxes is grayed out

### OS and versions
* PocketMine-MP: Master branch as of commit 31e2c1d
* PHP: 7.0.16
* Server OS: Ubuntu Server 16.04.2 LTS
* Game version: iOS 1.1.0, Win10 1.1.0

**Comment by dktapps** [comment]
This is a client-sided issue. They screwed up the meta values in the crafting data so I haven't updated the recipes yet.

**Comment by markkrueg** [comment]
Ugh...Mojang :-(  Thanks for the info. If I need an interim workaround; would you mind pointing me in the general direction of the file I need to edit? Are crafting recipes for the pickaxe stored in the json these days or php?

**Comment by dktapps** [comment]
`recipes.json`, edit everything that takes cobblestone in the input to damage value 15 instead of 0

**Comment by dktapps** [comment]
actually probably better make that -1 instead of 15 or the core code will get confused

**Comment by markkrueg** [comment]
Unfortunately I am still unable to craft anything with stone as a component even with source as of e4e4ef5. This includes your two commits related to this.

Are you able to craft stone tools, furnace, etc. using current master branch? I will test the api3/blocks branch shortly since I will be testing that for farming issues anyway.

I had briefly tried to fix this myself yesterday using value 15 and then -1, but neither seemed to fix the problem. Sorry for not updating you on this yesterday.

**Comment by dktapps** [comment]
I tested this earlier with various stone tools and it worked fine for me. If you're using git to update, make sure you reset or stash your directory before pull or your local installation will not update.

**Comment by markkrueg** [comment]
Hmm...interesting. No luck here with master. My process:

```
sudo rm -r pocketmine-mp.git
git clone --recursive https://github.com/pmmp/pocketmine-mp.git pocketmine-mp.git
```

I did just pull the api3/blocks branch, and was then able to craft stone items:

`git clone --recursive --branch api3/blocks https://github.com/pmmp/pocketmine-mp.git pocketmine-mp-blocks.git`

**Comment by dktapps** [comment]
Yes, I just observed the same issue on master, works fine on api3/blocks. Not 100% sure why, will investigate.

**Comment by dktapps** [comment]
Gahhh... this isn't going to be straightforward to fix. Please use api3/blocks for the time being... fixing this on master will require lots of hacks that just aren't worth the trouble it will cause.

**Comment by jasonwynn10** [comment]
#BlameShoghi

**Comment by thebigsmileXD** [comment]
@jasonwynn10 do not blame when you don't know whats the actual reason. Blame complex code.

**Comment by dktapps** [comment]
No... do blame shoghi. I know exactly what causes this issue... problem is that it's replicated throughout the code and fixing it will require lots of replacement of duplicated code which I instead prefer to remove.

**Comment by dktapps** [comment]
The code is not to blame... the author of the code is. Only a bad workman blames his tools, or his work. Regardless, it doesn't matter who is to blame, only that the issue is resolved.
