### ISSUE TITLE
Pumpkin seeds cannot be planted, also some existing pumpkin plants turn to seeds.

### ISSUE THREAD

**Issue by markkrueg** [pmmp/PocketMine-MP#965]
### Issue description
Pumpkin/melon plants cannot be planted.

Expected result: Plant pumpkin seed and you should see green young pumpkin plant.
Actual result: Seeds immediately appear when you attempt to plant pumpkin. 

### Steps to reproduce the issue
1. Use a hoe to hoe land.
2. Attempt to plant pumpkin seed.
3. See that pumpkin seeds were not planted and are instead floating in front of you.

### OS and versions
* PocketMine-MP: Master branch as of commit 31e2c1d
* PHP: 7.0.16
* Server OS: Ubuntu Server 16.04.2 LTS
* Game version: Android 1.1.0, iOS 1.1.0, Win10 1.1.0

### Crashdump, backtrace or other files
Update: Melon seeds have the same issue.

**Comment by thebigsmileXD** [comment]
I'll look into that

**Comment by dktapps** [comment]
Could you try `api3/blocks`? I might have fixed this on there, I don't recall.

**Comment by dktapps** [comment]
and this once again reminded me why I am rewriting the blocks mess... duplicated code everywhere. >_<

To clarify, this is a bug that recently affected regular crops because I changed farmland to be transparent as per MCPE to fix lighting issues. I'll add a quick fix for the issue, but note to self: _need to get this rewrite finished_.

**Comment by markkrueg** [comment]
I just tested with a current pull from api3/blocks. The results for pumpkins/melons were the same as when using current master. 

Also note that this effects melons as well.

**Comment by thebigsmileXD** [comment]
>  recently affected regular crops

@markkrueg melon stems and pumpkin stems are crop classes

**Comment by markkrueg** [comment]
6686bd4 fix confirmed working. Thank you very much!!!
