### ISSUE TITLE
PlayerInventory bug

### ISSUE THREAD

**Issue by AydarTop** [pmmp/PocketMine-MP#966]
### Issue description
Player's can't join

### Steps to reproduce the issue
2017-06-02 [13:23:32] [Server thread/CRITICAL]: InvalidArgumentException: "Inventory slot index "255" is out of range" (EXCEPTION) in "/src/pocketmine/inventory/PlayerInventory" at line 117

### OS and versions
* PocketMine-MP: PocketMine-MP 1.6.2dev-112 Unleashed
* PHP: 7.0.1
* Server OS: Linux
* Game version: PE

**Comment by dktapps** [comment]
This was already fixed in the master head commit. Try build 113.

**Comment by kumaya1109** [comment]
i had same problem 

[Server thread/CRITICAL]: InvalidArgumentException: "Inventory slot index "255" is out of range" (EXCEPTION) in "/src/pocketmine/inventory/PlayerInventory" at line 117
