### ISSUE TITLE
Bed's color bug

### ISSUE THREAD

**Issue by AydarTop** [pmmp/PocketMine-MP#968]
### Issue description
Only white bed's on creative inventory

### OS and versions
PocketMine-MP version: 1.6.2dev #11#114 [Protocol 113; API 3.0.0-ALPHA5]
Git commit: 0000000000000000000000000000000000000000
uname -a: Linux s2.24serv.pro 4.1.37 #2 SMP Mon Jan 9 09:59:03 MSK 2017 x86_64
PHP Version: 7.0.18
Zend version: 3.0.0
OS : Linux, linux

### Crashdump, backtrace or other files
![minecraft - pocket edition_2017-06-02-14-01-42](https://cloud.githubusercontent.com/assets/24245658/26723283/74960aaa-479c-11e7-82c1-c9efdf815e27.png)

**Comment by dktapps** [comment]
I already noted this in the commit message of https://github.com/pmmp/PocketMine-MP/commit/2db6ea6b18e7625e0d5cd922e18b680a2f2472bf. This issue is fixed on the api3/blocks branch.

**Comment by AydarTop** [comment]
@dktapps Also you will add blocks from 1.0 and 1.1 versions? I mean purpur blocks, end stone bricks, glazed terracotta block and other.

**Comment by Sandertv** [comment]
@AydarTop everything at its time. Dktapps has already added glazed terracotta on the api3/blocks branch.

**Comment by AydarTop** [comment]
@Sandertv Cool

**Comment by AydarTop** [comment]
@dktapps @Sandertv  We're forgot concrete and concrete powder.

**Comment by dktapps** [comment]
Fixed in https://github.com/pmmp/PocketMine-MP/commit/8a3b31077ef2ea651cde6534291d21344fde0050
