### ISSUE TITLE
Tip are broke 

### ISSUE THREAD

**Issue by Kebad45** [pmmp/PocketMine-MP#97]
### Issue description

Write a short description about the issue
When you use sendTip in a task it doesn't work and cause lags, when you sens a tip manually it doesn't work too:|
### Steps to reproduce the issue

1. ...
2. ...

### OS and versions

* PocketMine-MP: bd5bbbe 
* PHP: 7.0.2
* Server OS: Linux
* Game version: PE 0.16

### Crashdump, backtrace or other files

* ...

**Comment by dktapps** [comment]
Good job reading that "LATEST is not a valid version". This will be closed until/unless you provide adequate information.

**Comment by Kebad45** [comment]
Done @dktapps

**Comment by MichaelM04** [comment]
I can confirm this happens, I was doing a teleportation part in a plugin, using sendTip() for the message after teleport, I simply thought it was a tremendous amount of lag from teleporting, later to find out after switching to sendMessage() there was no lag at all, not sure what's causing this, but its there.

**Comment by Tarik02** [comment]
This just a client issue.

**Comment by SOF3** [comment]
> it doesn't work and cause lags

This is very vague. What doesn't work? What exactly happened, and how exactly is it different from expectation? And causes what lag? Where is the lag? Client or server?

> a tremendous amount of lag

Server-side lag or client-side lag?

**Comment by Tarik02** [comment]
@SOF3, fps is lower, when i show tip, so client issue.

**Comment by dktapps** [comment]
This is a client bug, not fixable by us.
