### ISSUE TITLE
Join issue

### ISSUE THREAD

**Issue by Driesboy** [pmmp/PocketMine-MP#971]
### Issue description

the first join the game will crash the 2x join it works

### Steps to reproduce the issue

1. Join and look
2. 

### OS and versions

* PocketMine-MP: https://github.com/pmmp/PocketMine-MP/commit/e4e4ef5f2a5b50ad9dc546b08a1f812da43ca0ef
* PHP: 7.0.19
* Server OS: Windows Vista
* Game version: PE

### Crashdump, backtrace or other files

* ...

**Comment by dktapps** [comment]
Do not assume that just because you have an issue that others automatically do so too and are able to reproduce it.

If you have PurePerms on your server, remove it.

**Comment by Driesboy** [comment]
alternative plugin for PurePerms?

**Comment by dktapps** [comment]
I don't know, but PurePerms causes issues with clients crashing due to it doing permission recalculation during PlayerLoginEvent.

**Comment by Driesboy** [comment]
https://github.com/poggit-orphanage/PurePerms

**Comment by Driesboy** [comment]
fixed thx

**Comment by HimbeersaftLP** [comment]
I don't want to go Off-Topic, but seriously, Windows Vista?!

**Comment by Driesboy** [comment]
yep its a new pc i need to install linux on it

Op 2-jun.-2017 22:13 schreef "HimbeersaftLP" <notifications@github.com>:

**Comment by thebigsmileXD** [comment]
@HimbeersaftLP you are going heavily offtoppic, go to the forums to talk about those things.

**Comment by HimbeersaftLP** [comment]
@thebigsmileXD So I should post a thread on forum that says "omg, that guy in the issue said he is using Windows Vista" or what? You just went more offtopic and just went even more offtopic by posting more comments...
