### ISSUE TITLE
PocketMine really slow since MCPE 1.1

### ISSUE THREAD

**Issue by Matthww** [pmmp/PocketMine-MP#975]
### Issue description

Since the merge of the 1.1 branch PMMP has become really laggy (Low TPS). I have removed all my plugins. And it's still lagging

### Steps to reproduce the issue

1. Server with a decent amount of players

### OS and versions

* PocketMine-MP: 087a994
* PHP: 7.0.12
* Server OS: Debian Jessie

### Crashdump, backtrace or other files

* Timings: https://timings.pmmp.io/?url=24751404

**Comment by dktapps** [comment]
Blame Mojang. Everything is zlib-compressed since 1.1. Nothing we can do about this.

**Comment by dktapps** [comment]
Reducing compression level in pocketmine.yml may help lighten the workload.

**Comment by Matthww** [comment]
It's already on 1

**Comment by ImagicalGamer** [comment]
Matthew u stoopid? 1 isn't the smallest number, use 0.00000000000000001

**Comment by thebigsmileXD** [comment]
@ImagicalGamer u spammy?
