### ISSUE TITLE
Extreme FPS drop and weird chiseled stone brick texture

### ISSUE THREAD

**Issue by Sandertv** [pmmp/PocketMine-MP#976]
### Issue description

When using the latest version of the api3/blocks branch, something extremely strange happened, which keeps occuring over and over again. So it may sound really weird, but here it goes. Sometimes, when walking around or joining the game, the client seems to be stuck in a chiseled stone brick block. Huge amounts of block sounds can be heard when this happens. Over the coming 5-10 seconds the client completely freezes because of the FPS lag. Teleporting does not seem to work. Kicking the player through console is the only way that seems to work.

Now too badly I do not know how to reproduce this issue. It happens not very occasionally, and seem to occur most when teleporting and with walking on slabs and stairs. The chiseled stone bricks block always show up, even though there were absolutely none nearby.

### Steps to reproduce the issue

1. Possible reproduction methods mentioned above.

### OS and versions

* PocketMine-MP: api3/blocks: 7a3ee42bfa719ae5642e89672a0ab88112587890
* PHP: 7.0
* Server OS: Ubuntu
* Game version: PE (possibly win10)

### Crashdump, backtrace or other files

I also noticed the issue below. I do not know whether this has to do with it or not.
```
[Server thread/CRITICAL]: TypeError: "Argument 1 passed to pocketmine\Player::sendPosition() must be an instance of pocketmine\math\Vector3, null given, called in phar:///
home/blabla/PocketMine-MP.phar/src/pocketmine/Player.php on line 2189" (EXCEPTION) in "/src/pocketmine/Player" at line 3838
```

**Comment by dktapps** [comment]
Do you have a full backtrace for this?

**Comment by Sandertv** [comment]
Okay I can confirm this issue is NOT from that error. I'm actually suspecting a plugin, because I keep 'teleporting' to the same spot. I'll try and get a backtrace of that issue once I get it again and report back.

**Comment by dktapps** [comment]
![screenshot_2017-06-02-22-06-45](https://cloud.githubusercontent.com/assets/14214667/26744876/d6fe8fee-47df-11e7-9e59-dfdeea28bd27.png)
@Sandertv does this look familiar? ^

**Comment by Sandertv** [comment]
That is EXACTLY my issue @dktapps.

**Comment by dktapps** [comment]
Yeah, it's a tricky one to reproduce... seems to happen when the client tries to move and the server reverts it... not 100% sure why. I've seen the coordinates randomly become NaN for reasons I don't understand too. Will investigate further.

**Comment by Muqsit** [comment]
HELLO, this was our conversation dktapps!

**Comment by Sandertv** [comment]
@Muqsit do you know by any chance if there's a creature/monster at that spot where you get stuck in the stone? In my case it brings me to the same spot under one of my 'boss creatures' every single time, and this issue doesn't occur if I remove the plugin. Likely something to do with entities.

**Comment by Muqsit** [comment]
This can be noticed easily when you teleport the player to another world. Some more things (mojang issues) that happen during this event are:
* You can see an emerald (not right above your head, maybe right above your head + X:2,Y:0,Z:2). You'll need to go in F3 mode to notice this.
* If you see right beneath your feet, you'll notice a TON of stone bricks, not the block, but some sort of an entity. There are just so many of those stone bricks looking entity (I think it's falling sand with a changed data flag) that it completes a full circle as it is spawned in the same direction with different yaws.

**Comment by Muqsit** [comment]
@Sandertv I do see a spider on top of my head, but I can be mistaken as I haven't tried this in full vanilla (as in no plugins). Not sure if that's a mojang bug but I'll try.

**Comment by Muqsit** [comment]
I tried getting a screenshot:
![screenshot_20170603-042437](https://cloud.githubusercontent.com/assets/15074389/26749002/b6e4e7f0-4814-11e7-8aad-71900a3c41be.png)
The world name is "lobby1" in this case
/status:
![20170603_042714](https://cloud.githubusercontent.com/assets/15074389/26749027/f82fcafe-4814-11e7-90c8-79c08757becb.png)

**Comment by jojoe77777** [comment]
Update your plugins to use `entityRuntimeId` instead of `eid` for AddPlayerPackets and AddEntityPackets.

**Comment by Sandertv** [comment]
You're right @jojoe77777!
The issue of the stone entities is still very weird though. I can confirm that this bug has been in the came at least since 1.0. When creating an entity riding plugin there, bumping into a wall would cause the exact same insane FPS lag until eventually the player would freeze. Perhaps this IS an MCPE issue.

**Comment by thebigsmileXD** [comment]
> , bumping into a wall would cause the exact same insane FPS lag

Reproduced this with in-core riding.
This is an issue that pmmp constantly teleports the client back because the SetEntityMotionPacket not being decoded and applied to the entities. Adding a proper encoding for the class and some plugin that handles the packet values + applies them to the movement values fixes the packet spam and stops that lag.

**Comment by dktapps** [comment]
No. This is an issue with client/server movement reversion. The client will still attempt to send movements even when the server has reverted it. A crossover with those sometimes causes this issue. It has nothing to do with motion.

**Comment by SuperMaXAleX** [comment]
*why mojang out a buggy mcpe, whyyy*

**Comment by dktapps** [comment]
No, this isn't a client-sided issue. It's been around for a while. PocketMine has many problems related to teleportation.

**Comment by thebigsmileXD** [comment]
> This is an issue with client/server movement reversion

thats exactly what i wanted to say, thanks for clarifying.

**Comment by Qimie** [comment]
How to reproduce:~

~  Join CosmicPE.
~  Walk Like 5-8 Blocks.
~ Wait A Few Sec.
~ FPS Drop To 0.
~ Then Your MCPE Starts To Crashing.
![screenshot_2017-06-03-21-24-12](https://cloud.githubusercontent.com/assets/18200541/26757170/9f513436-48e6-11e7-89ae-6eec27bdc038.png)
![screenshot_2017-06-03-21-24-05](https://cloud.githubusercontent.com/assets/18200541/26757171/a22fd946-48e6-11e7-85ec-eb5757d42917.png)

**Comment by thebigsmileXD** [comment]
I'd say, related to the setmotion? @dktapps

**Comment by dktapps** [comment]
> **It has nothing to do with motion.**

**Comment by Akuroma** [comment]
I also had this problem.  I removed all of my entity based plugins, like Pets or Slapper etc.. Now it works.

**Comment by Sandertv** [comment]
I can confirm eid -> entityRuntimeId fixes definitely help to cover up the issue, but I can't assume that's the actual core of the issue. Why would the player randomly teleport under one of the entities? That doesn't make sense. Also, I got reports of players still getting this issue even with the fix, so I don't think it always applies.

**Comment by dktapps** [comment]
I managed to reproduce this once without any plugins. If there was a field type issue I'd expect IDEs to highlight it, and I haven't seen anything. I don't believe this issue has anything to do with the eid 0 issue.

**Comment by dktapps** [comment]
Anyone who can reliably reproduce this, would you mind applying the Coordinates Unlocker resource pack and tell what coordinates it thinks you're at when the bug occurs?

**Comment by jarne** [comment]
With commit b01ad01effbf1de36db5a1124bcbe899b0a4cc29, I can't reproduce because the server crashes:

```
[16:44:49] [Server thread/INFO]: thejjtesting[/10.0.0.13:57935] logged in with entity id 1 at (world, 10.7892, 16, -9.4084)
[16:44:51] [Server thread/CRITICAL]: Could not pass event 'pocketmine\event\player\PlayerJoinEvent' to 'FloatingText v1.0.0': strlen() expects parameter 1 to be string, null given on surva\floatingtext\EventListener
[16:44:51] [Server thread/CRITICAL]: TypeError: "strlen() expects parameter 1 to be string, null given" (EXCEPTION) in "/src/pocketmine/utils/BinaryStream" at line 268
[16:44:51] [Server thread/INFO]: thejjtesting joined the game
[16:44:51] [Server thread/CRITICAL]: TypeError: "strlen() expects parameter 1 to be string, null given" (EXCEPTION) in "/src/pocketmine/utils/BinaryStream" at line 268
[16:44:51] [Server thread/EMERGENCY]: An unrecoverable error has occurred and the server has crashed. Creating a crash dump
[16:44:51] [Server thread/EMERGENCY]: Please upload the "/Users/jarne/Downloads/PocketMine-MP/crashdumps/Sun_Jun_4-16.44.51-CEST_2017.log" file to the Crash Archive and submit the link to the Bug Reporting page. Give as much info as you can.
```

It looks like this before the connection quits:

![img_3894](https://cloud.githubusercontent.com/assets/15860314/26762592/3ba19a16-4945-11e7-82c0-01ed78f394c5.PNG)

With commit 8bb0e8d3985e6f067816fe5b41b8a2cfe2ffac90, it looks like this:

![img_3892](https://cloud.githubusercontent.com/assets/15860314/26762576/f8c362ec-4944-11e7-8cbe-0647e8e212c8.PNG)

And should be like this:

![img_3893](https://cloud.githubusercontent.com/assets/15860314/26762578/fc274af2-4944-11e7-8f02-1bc630ab62a2.PNG)

**Comment by dktapps** [comment]
maybe a varint encoding issue... hmm.

**Comment by Akuroma** [comment]
I'm not sure if this would help, but I just downloaded the newest version of Slapper from Poggit. And in this version, this bug is contained. The older version of Slapper, which I'm using currently, is alright and this bug doesn't appear.

**Comment by jarne** [comment]
It works because he fixed it like described in one of his previous post, but @dktapps is still searching the reason for it

**Comment by xxFlare** [comment]
Reproduced. This happened on a teleport for me.. and there was no wool around. I did not get any sounds, just out of control movement jittering.
![screenshot_2017-06-04_11 48 59](https://cloud.githubusercontent.com/assets/10011687/26764551/dc1594fc-4936-11e7-9245-7b64d557628e.png)

**Comment by Qimie** [comment]
Guys. It just tp you inside a block ur standing on. I tried on CosmicPE.

**Comment by Akuroma** [comment]
I just relized that this happens also with pets. One player of us just spawned a rabbit, using our pets plugin. When I joined the server, I was bugging inside of this pet and the block under it.

**Comment by Sandertv** [comment]
@Akuroma that is because the plugin still uses $pk->eid when spawning the entity, instead of $pk->entityRuntimeId. If there are no entities that use this wrong property, you only happen to be teleported inside the block you're standing on. If there IS an entity with this wrong property stuff, you get teleported inside the block below the entity, no matter how far away you are from it.

**Comment by dktapps** [comment]
If anything is using an incorrect packet field as of the latest commits, it should trigger a crash...

**Comment by SuperMaXAleX** [comment]
I had this issue. As @Sandertv & @jojoe77777 said, you need to replace $pk->eid by $pk->entityRuntimeId. This issue will be fixed!

**Comment by dktapps** [comment]
I've seen this happen during multiworld teleports using ManyWorlds. Not certain if it's a plugin bug or core.

**Comment by mal0ne-23** [comment]
http://imgur.com/3Rqnex5

Happened when I opened this chest on CosmicPE i think? I heard a bunch of sounds like I was walking on blocks and being pushed back? Might be a different issue

**Comment by Qimie** [comment]
Thats the problem I'm having too.

**Comment by dktapps** [comment]
Can anybody reproduce this with #1153 ?

**Comment by Sandertv** [comment]
Since that commit this does no longer occur for me. Time to close. Thanks @dktapps.
