### ISSUE TITLE
In third person you can hit people through walls

### ISSUE THREAD

**Issue by Megalunchbox** [pmmp/PocketMine-MP#978]
### Issue description

usually in third person you should not be allowed to hit people through walls but you can.

### Steps to reproduce the issue

1. go in third person

2. hit someone who is behind a wall

### OS and versions

* PocketMine-MP: All recent versions
* PHP:
* Server OS:  all
* Game version: PE/Win10

**Comment by SOF3** [comment]
Such antihacks should be implemented in plugins.

**Comment by thebigsmileXD** [comment]
@SOF3 it actually has nothing to do with antihacks/cheats. Mojang is to blame, players that use the PE gui can tap out of their straight view line, which allows them to interact where the cursor actually not is.
