### ISSUE TITLE
Server crashing.

### ISSUE THREAD

**Issue by brianzp** [pmmp/PocketMine-MP#981]
### Issue description

The server crashes as soon as a player connects to the server.

### Steps to reproduce the issue

1. Join the server.
2. The server crashes instantly

### OS and versions

* PocketMine-MP: b83082f
* PHP: 7.0.9.
* Server OS: Linux, linux
* Game version: PE

### Crashdump, backtrace or other files

https://gist.github.com/brianzp/f4e3965663dffe4fa5c1089b236dc4dc

**Comment by dktapps** [comment]
This is a Slapper issue. Please update to the latest version.
