### ISSUE TITLE
Issue with my plugin by using PocketMine

### ISSUE THREAD

**Issue by Akuroma** [pmmp/PocketMine-MP#982]
### Issue description
Hey. I want that players spawn in my Lobby, everytime they join onto the server. My code which you can see below, worked perfectly with Tesseract. Since I use PocketMine-MP, it doesn't work anymore. No error outputs, no crashdumps, it just won't work.

If you are reporting a regression or unexpected behaviour, please include the below information:
Expected result: Players should spawn at the servers spawn point on join.
Actual result: Nothing happens. Players spawn on there last point, before quit.
-->

### OS and versions

* PocketMine-MP: PocketMine-MP 1.6.2dev 「Unleashed」
* PHP: 7.0
* Server OS: Linux (Ubuntu 14.04)
* Game version: PE/Win10

### Crashdump, backtrace or other files

* ...
![code](https://cloud.githubusercontent.com/assets/19476909/26753910/e7db3344-4870-11e7-8443-bb62b3c6888a.PNG)

**Comment by jasonwynn10** [comment]
Invalid Issue.
1. This issue tracker isn't for plugins.
2. WE DON'T SUPPORT TESSERACT

**Comment by dktapps** [comment]
This is not a support forum, and we do not provide support for spoons. I invite you to read the [README.md](https://github.com/pmmp/PocketMine-MP#setup-help--support-faqs), particularly the part that says `Please do not use our issue tracker for support requests.`

**Comment by Akuroma** [comment]
@jasonwynn10 Calm down. I never asked for support, which belongs to Tesseract. I only said that this piece of code, worked in Tesseract in PocketMine it didn't work.
Bye.

**Comment by thebigsmileXD** [comment]
I can confirm the bug though, i'd retitle the issue to: immediate teleport on login doesn't work.
@Akuroma you could set the spawn position on prejoin instead, falls du weißt was ich meine
