### ISSUE TITLE
Cant Place Blocks on my Back

### ISSUE THREAD

**Issue by arsenicblast** [pmmp/PocketMine-MP#983]
### Issue description

 You cant place blocks on your back.Need this to be fix because I have Skyblock 
![image](https://cloud.githubusercontent.com/assets/28137526/26754116/e72a2f8c-48a6-11e7-947d-b0886c8a0aa3.png)

### Steps to reproduce the issue

1. Go to your mcpe and sneak
2. Look at the ground
3. Now place block on your back or on the block you are standing (break the next block to where you are standing)
4. The block will disappear

### OS and versions

* PocketMine-MP:
* PHP: 7.0.3
* Server OS: Windows 8
* Game version: PE

### Crashdump, backtrace or other files

* ...

**Comment by dktapps** [comment]
I'm afraid I don't understand the issue. What exactly are you trying to do?

**Comment by AppleDevelops** [comment]
I'm pretty sure he means that sometimes you can't place a block below you or when you do, it sometimes disappears.

**Comment by HimbeersaftLP** [comment]
A video showing exactly what you mean would be helpful

**Comment by SuperMaXAleX** [comment]
You can't place/break blocks or attack somebody at where I'm pointing : [click meh plz](https://image.noelshack.com/fichiers/2017/22/1496505062-img-2878.png)

**Comment by dktapps** [comment]
ah, that explains why I couldn't reproduce it... I use crosshair controls, and with crosshair it's impossible to reach behind you like that.

**Comment by SuperMaXAleX** [comment]
Just edited

**Comment by AppleDevelops** [comment]
Some of it is client side, like if you were to break a block in front of you sometimes in breaks the block below you in cmode, but I've reproduced it in single player.

**Comment by SuperMaXAleX** [comment]
On servers, I'm not sure it's a ""bug"" but the security who is blocking us

**Comment by dktapps** [comment]
It's because of the interaction checks in the anti-cheat. It's ported from PC, and in PC you can't do things like this, so it doesn't cater for the possibility.

**Comment by SuperMaXAleX** [comment]
It will change a little my gameplay if this interaction checks is removed !

**Comment by arsenicblast** [comment]
So how am I supposed to get rid of it ?

**Comment by Pugzy** [comment]
This seems familiar to the one I am experiencing so I'll leave this here and create a new issue if required (determined not to be the same cause).

I'm unable to place blocks (similar to OP) when shifting at certain Y levels. This is on the latest versions using W10 Edition. Y levels 7, 8, 31 and 32 whilst shifting.

Video: https://youtu.be/OAvz9_7qH7E

**Comment by bettylovedertderrdy** [comment]
genisyspro better !

**Comment by dktapps** [comment]
If anyone would like to test the referenced PR (#1842) please do, and apologies for the long wait in this getting fixed.
