### ISSUE TITLE
AddTitle Dont Work

### ISSUE THREAD

**Issue by ChaostixZix** [pmmp/PocketMine-MP#985]
* PocketMine-MP: 1.6.2Dev Unleashed For 1.1
* PHP: 7.0.3
* Server OS: Mac Os X
* Game version: PE

Im Using $player->addTItle("Test", "Test", -1, -1, -1);

But then i got this 

> [18:23:17] [Server thread/CRITICAL]: Unhandled exception executing command 'par claim 1' in par: Argument 1 passed to pocketmine\utils\Binary::writeVarInt() must be of the type integer, null given, called in /Users/chaostix/Desktop/PocketMine-MP/src/pocketmine/utils/BinaryStream.php on line 301
[18:23:17] [Server thread/CRITICAL]: TypeError: "Argument 1 passed to pocketmine\utils\Binary::writeVarInt() must be of the type integer, null given, called in /Users/chaostix/Desktop/PocketMine-MP/src/pocketmine/utils/BinaryStream.php on line 301" (EXCEPTION) in "/src/pocketmine/utils/Binary" at line 496

**Comment by TheDiamondYT1** [comment]
Try the latest master build

**Comment by ChaostixZix** [comment]
@TheDiamondYT1  Im Using The Latest Master Build :D

**Comment by dktapps** [comment]
Don't you just love it when undefined behaviour causes a crash instead of unexpected behaviour

**Comment by thebigsmileXD** [comment]
Yes

**Comment by ChaostixZix** [comment]
@dktapps So, It will be fixed? :D

**Comment by dktapps** [comment]
On a semi-related note, there appears to be a client-sided issue on some Pocket Edition clients causing titles not to work. This also happens in vanilla, so please do not report that as an issue.
