### ISSUE TITLE
Is bug

### ISSUE THREAD

**Issue by RateekMCPE** [pmmp/PocketMine-MP#986]
The water is lag 
![sans te22222222itre](https://cloud.githubusercontent.com/assets/21282002/26755679/d0aebc96-4892-11e7-8b74-64e46fb6a0be.png)

**Comment by dktapps** [comment]
Without knowing your PocketMine-MP version, OS, PHP, Client version, or plugins and how the issue occurred, the issue cannot begin to be solved.
A pre-formatted template is provided that shows the required information to begin to find, test and solve an issue.
Until the adequate template and information is provided, the issue will be closed; it may be reopened if you update the ticket with the correct template and required information.

[Contribution guidelines](https://github.com/pmmp/PocketMine-MP/blob/master/CONTRIBUTING.md)
