### ISSUE TITLE
Bugs !

### ISSUE THREAD

**Issue by RateekMCPE** [pmmp/PocketMine-MP#988]
### Bugs :
* The water is lag (screen)
* Sorry im french x)
![sans te22222222itre](https://cloud.githubusercontent.com/assets/21282002/26755679/d0aebc96-4892-11e7-8b74-64e46fb6a0be.png)

### OS and versions
* PocketMine-MP: last commit
* PHP: 7.1
* Server OS: VPS Ubuntu
* Game version: PE/Win10

**Comment by dktapps** [comment]
LAST is not a valid version.

**Comment by TheDiamondYT1** [comment]
@dktapps You realise he'll just create more issues, right?

We can assume he means the latest commit on master and although she shouldnt have to assume, we can.
