### ISSUE TITLE
Bugs inventory bar mc:pe 1.1

### ISSUE THREAD

**Issue by RateekMCPE** [pmmp/PocketMine-MP#989]
### Bugs :
* The water is lag (screen)
* Sorry im french x)

![sans te22222222itre](https://cloud.githubusercontent.com/assets/21282002/26755679/d0aebc96-4892-11e7-8b74-64e46fb6a0be.png)

### OS and versions
* PocketMine-MP: 1.6.2dev "Unleashed" (API 3.0.0-ALPHA5)
* PHP: 7.1
* Server OS: VPS Ubuntu 
* Game version: PE/Win10

**Comment by dktapps** [comment]
Are you using a 32-bit system?

**Comment by RateekMCPE** [comment]
@dktapps Yeah.

**Comment by RateekMCPE** [comment]
@dktapps 'Running PocketMine-MP with 32-bit systems/PHP is deprecated. Support for 32-bit may be dropped in the future.'

**Comment by dktapps** [comment]
Then this is a known issue and will not be fixed. PocketMine-MP support for 32-bit systems is deprecated and may be removed. See #984 .

**Comment by TheDiamondYT1** [comment]
@RateekMCPE Upgrade to a 64-bit OS, or 64-bit PHP build. #984
