### ISSUE TITLE
Head/body do not rotates

### ISSUE THREAD

**Issue by udwarf** [pmmp/PocketMine-MP#991]
When one player is moving or rotating head - other player see him staring always in the same direction.
Was checked on the latest master without plugins.
Clients was win10 1.1.0 and android 1.1.0.55

**Comment by dktapps** [comment]
Without knowing your PocketMine-MP version, OS, PHP, Client version, or plugins and how the issue occurred, the issue cannot begin to be solved.
A pre-formatted template is provided that shows the required information to begin to find, test and solve an issue.
Until the adequate template and information is provided, the issue will be closed; it may be reopened if you update the ticket with the correct template and required information.

[Contribution guidelines](https://github.com/pmmp/PocketMine-MP/blob/master/CONTRIBUTING.md)
