### ISSUE TITLE
AddTitle() Subtitle Too Big

### ISSUE THREAD

**Issue by ChaostixZix** [pmmp/PocketMine-MP#995]
* PocketMine-MP: Latest Master Branch
* PHP:7.0.3
* Server OS:Mac Os X
* Game version: Win10

I Used AddTitle API. But when i use it, the subtitle not added on the new line
![screenshot at jun 04 01-38-03](https://cloud.githubusercontent.com/assets/19998246/26760246/420bf018-48c8-11e7-8563-3287b656f2c6.png)
But Then I Use \n, I Got This
![screenshot at jun 04 01-42-23](https://cloud.githubusercontent.com/assets/19998246/26760252/4fddb370-48c8-11e7-9ca1-20225d45f9b5.png)

**Comment by dktapps** [comment]
Mojang oversight. Nothing we can do about this, we don't know client screen size.

**Comment by ChaostixZix** [comment]
@dktapps It Happens When I Updated My Pocketmine, Not The MCPE

**Comment by ChaostixZix** [comment]
@dktapps Survival Player Got Water Bar, And Started To Die
