### ISSUE TITLE
Beds act like slime blocks!

### ISSUE THREAD

**Issue by Lazerplayz** [pmmp/PocketMine-MP#996]
### Issue description

 Beds act liek slime blocks!

### Steps to reproduce the issue

1. Place a bed
2. Jump onto the "white bed" 

### OS and versions

* PocketMine-MP:
* PHP:
* Server OS:
* Game version: PE/Win10 (delete as appropriate)

### Crashdump, backtrace or other files

* ...

**Comment by thebigsmileXD** [comment]
What he means, the client starts to bounce and the bad anticheat in pmmp will either drag you down, causing an infinite bouncing loop, or kick for flying. Happens to slime blocks and beds

**Comment by jasonwynn10** [comment]
I thought bouncing on beds was a feature...
