### ISSUE TITLE
Beds (without tiles) don't appear

### ISSUE THREAD

**Issue by moskadev** [pmmp/PocketMine-MP#997]
### Issue description
Not sure if this is an issue but anyway, I will see.
I'm trying to update my server to PMMP 1.1.

When I was testing my game and others things on my server, I saw all beds invisible. (These beds where placed on MC:PE 1.0 - when there weren't beds' tiles.

I cancelled BlockBreakEvent and tried to break these beds to see what happens - Beds reappeared but have random color.

To fix that, I tried to do this code : 
```
$pointA = new Vector3(x, y, z);
$pointB = new Vector3(x, y, z);
$color = mt_rand(0, 15);

for($z = $pointA->z; $z <= $pointB->z; ++$z){
    for($y = $pointA->y; $y <= $pointB->y; ++$y){
        for($x = $pointA->x; $x <= $pointB->x; ++$x){
            $block = $levelArena->getBlock(new Vector3($x, $y, $z));
            if($block->getId() == Block::BED_BLOCK){
                echo "Placed bed" . PHP_EOL; //echo are sent 2 times, so bed's blocks are there
                $levelArena->setBlock(new Vector3($x, $y, $z), Block::get(Block::BED_BLOCK, $block->getDamage())); //Tried without setBlock() too
                $nbt = new CompoundTag("", [
                    new StringTag("id", Tile::BED),
                    new ByteTag("color", $color & 0x0f), //Tried without "& 0x0f" too
                    new IntTag("x", $block->x),
                    new IntTag("y", $block->y),
                    new IntTag("z", $block->z),
                ]);

                Tile::createTile(Tile::BED, $levelArena, $nbt);
            }
        }
    }
}
```
I have done exactly the same steps I mentioned above.
Beds still invisible but tiles & blocks are there now, and we need again to break it to see the bed again. The colors are no longer random and and are correctly set.

[[So, this code doesn't fix the problem but just the color.]]
EDIT : This code fixes beds but I need to unload & load chunk of where is the bed.

Thanks for reading, and sorry for my bad english.

### Steps to reproduce the issue
1. Use a old world who wasn't generated or used on MC:PE 1.1.
2. Place some bed blocks.
3. Try this world on MC:PE 1.1.
4. Beds are invisible.

### OS and versions
I'm actually using the api3/blocks branch, not the master. (I'll post more informations (Jenkins, etc..) there when I'll come back to my home.)

* PocketMine-MP: PocketMine-MP 1.6.2dev 「Unleashed」 implementing API version 3.0.0-ALPHA5 for Minecraft: PE v1.1.0.55 (protocol version 113)
* PHP: 7.0.3
* Server OS: OS X El Capitan
* Game version: PE/W10

### Crashdump, backtrace or other files
* None

**Comment by dktapps** [comment]
Newly placed beds on api3/blocks will not have an issue, but PocketMine doesn't scan for existing old beds without tiles due to performance considerations and no suitable method currently in place to do this.

**Comment by SuperMaXAleX** [comment]
That's really perturbing. :/

**Comment by thebigsmileXD** [comment]
Create a plugin cycling through all blocks when a chunk is loaded as example, then place a red tile at all beds. I think i'll create a plugin for that soon, fixing all tiles that are missing. https://github.com/thebigsmileXD/TileFixer will be the future repo.

**Comment by ImagicalGamer** [comment]
Why do we call them "tiles"? They are block entities.

**Comment by Sandertv** [comment]
Because blame shoghi. Changing that would break a huge amount of plugins. Perhaps it would be a good idea though as it's still 3.0.0-ALPHA... It would require lots of changes in PMMP too.

**Comment by dktapps** [comment]
"Block entity" is also somewhat misleading... they aren't entities at all, merely blocks with some extra data/behaviour. For backwards-compatibility's sake, we stick with the old Tile name (they used to be called tiles in vanilla PC a few years ago).

**Comment by xxFlare** [comment]
@Sandertv Not shoghicp's fault, when he re-wrote PocketMine they were called tiles.

**Comment by SOF3** [comment]
We already have three distinct nouns "Block", "Entity" and "Tile" referring to entirely different things. Why try to increase the confusion?

**Comment by thebigsmileXD** [comment]
Added a chunk fixing command to tilefixer, fixing the tiles in the current chunk. This should help you for now.

**Comment by SuperMaXAleX** [comment]
^^^^ EDIT ^^^^
The code on the description of this issue is working, but to see the bed, you need to unload & load the chunk.

**Comment by jojoe77777** [comment]
@SuperMaXAleX forgot to spawnToAll()? ;)

**Comment by SuperMaXAleX** [comment]
@jojoe77777 eh ? The player ?

**Comment by JackNoordhuis** [comment]
@SuperMaXAleX He means changing `Tile::createTile(Tile::BED, $levelArena, $nbt);` to
```
$tile = Tile::createTile(Tile::BED, $levelArena, $nbt);
$tile->spawnToAll();
```

**Comment by thebigsmileXD** [comment]
@jojoe77777 He did indeed.

**Comment by SuperMaXAleX** [comment]
@JackNoordhuis Just tried this code but nothing changes

**Comment by bettylovedertderrdy** [comment]
genisyspro better !

**Comment by thebigsmileXD** [comment]
Note: Extends #880

**Comment by dktapps** [comment]
The general issue of missing and invalid tiles for blocks is planned for resolution in 4.0.

**Comment by thebigsmileXD** [comment]
Right now beds without or with invalid tiles crash the client when clicked

**Comment by dktapps** [comment]
This should be cheap to fix with paletted chunks. (Previously the obstacle to implementing this has been performance, but with palettes it's very cheap to check if a chunk needs to be scanned for tile fixing.)

**Comment by dktapps** [comment]
Since some version in the past (I'm not sure exactly when) the client now renders beds without tiles as a default red bed (instead of being invisible), so no further action is needed on this.

**Comment by thebigsmileXD** [comment]
> 
> 
> The general issue of missing and invalid tiles for blocks is planned for resolution in 4.0.

This still persists, should it be moved into a new issue? Plugins might expect a tile when clicking a bed - or similar, causing unexpected crashes.

**Comment by dktapps** [comment]
In PM4 it's not expected that plugins will directly interact with tiles anyway. Most APIs are provided directly by the Block now, so I don't consider that an issue.

The general issue of missing tiles has been removed frlm PM4 milestone due to low priority and high time cost.
